### ISSUE TITLE
add streamInto on Cursor and ResultQuery

### ISSUE THREAD

**Issue by arnaudroger** [jOOQ/jOOQ#5795] opened 2017-01-18 10:49 UTC
the equivalent of fetchInto that return a Stream of mapped object.

Any thought about also implementing a StackWalker like Function<Stream<T>, R> callback 
to avoid stream leak?

**Comment by lukaseder** [comment] 2017-01-18 16:16
Thank you very much for your suggestion

> the equivalent of fetchInto that return a Stream of mapped object.

Yes, we already have that on our list for 3.10 (hopefully): https://github.com/jOOQ/jOOQ/issues/5361. It's not a high priority, but it would certainly make sense to add it, eventually.

> Any thought about also implementing a StackWalker like Function<Stream, R> callback
to avoid stream leak?

There was https://github.com/jOOQ/jOOQ/issues/4932, which we rejected. Does that cover your idea? If not, would you mind describing it a bit more?

**Comment by lukaseder** [comment] 2017-01-18 16:16
Closing this as a duplicate of #5361

**Closed by lukaseder** 2017-01-18 16:16 UTC
Labels: C: Functionality, P: Medium, T: Enhancement

**Comment by arnaudroger** [comment] 2017-01-18 16:22
missed that ticket, I need to review my issue research skills :)

was thinking of http://download.java.net/java/jdk9/docs/api/java/lang/StackWalker.html#walk-java.util.function.Function-

<T> T stream(Function<? super Stream<R>,? extends T> function)

That would also address Stream that are instantiated but dont have a terminate operation.

it's less convinient though...

**Comment by lukaseder** [comment] 2017-01-18 16:27
There are too many issues to search... Almost 6000! (looking forward to be able to say "over 9000").

Oh, I see. So yes, that's the same as #4932, then. I must say, I'm not too much of a fan of that StackWalker API. It's just the JDK developers admitting that they too wish Java 8 introduced auto-closing streams. I had rather re-visit #4932 and spend more time thinking about wrapping the JDK streams to add this guarantee.

Let's do that (and let's continue discussing on #4932)
