### ISSUE TITLE
DAO.insert() does not populate ID in Kotlin POJO with isKotlinNotNullPojoAttributes = true

### ISSUE THREAD

**Issue by sgrimm** [jOOQ/jOOQ#15655] opened 2023-09-28 17:33 UTC
### Expected behavior

If a table has an autogenerated primary key column and some `NOT NULL` columns without defaults, calling a DAO `insert()` method should populate the POJO's primary key field.

### Actual behavior

If `isKotlinNotNullPojoAttributes` is false, the DAO `insert()` method modifies the POJO to set the generated primary key as expected.

If `isKotlinNotNullPojoAttributes` is true, the POJO is not modified (primary key field remains null).

### Steps to reproduce the problem

Given a table like
```sql
CREATE TABLE demo (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);
```
with `isKotlinNotNullPojoAttributes` enabled, jOOQ generates a mutable data class with the expected nullability:
```kotlin
data class Demo(
    var id: Long? = null,
    var name: String
)
```
I then try to insert a row into the table using a DAO class:
```kotlin
val demoRow = Demo(name = "Testing")
demoDao.insert(demoRow)
println(demoRow.id)
```
and get `null`. If I disable `isKotlinNotNullPojoAttributes`, I get the ID.

I dug into this a little bit and I believe it's because `DefaultRecordMapper` is combining "the POJO is mutable" with, "the POJO class has a no-args constructor." In this case, the POJO is in fact mutable, but there isn't a no-args constructor because the non-nullable fields don't have default values.

### jOOQ Version

3.18.6

### Database product and version

PostgreSQL 14.9 (Homebrew) on aarch64-apple-darwin22.4.0, compiled by Apple clang version 14.0.3 (clang-1403.0.22.14.1), 64-bit

### Java Version

openjdk 20.0.2 2023-07-18

### OS Version

macOS Ventura 13.5.2

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment] 2023-09-29 13:05
Thanks for your report. This looks like a duplicate of https://github.com/jOOQ/jOOQ/issues/15559

**Comment by lukaseder** [comment] 2023-09-29 13:28
Indeed, there's no default constructor available, so jOOQ tries to apply the immutable constructor logic. This works, internally, but now the internal data class instance must be mapped back to your user instance, which doesn't work because of this:

- https://github.com/jOOQ/jOOQ/issues/15564

**Comment by lukaseder** [comment] 2023-09-29 13:29
I'm closing your issue as a duplicate of #15559 an #15564. Will have another attempt at fixing #15564

**Closed by lukaseder** 2023-09-29 13:29 UTC
Labels: T: Defect, P: Medium, C: Integration: Kotlin, E: All Editions
