### ISSUE TITLE
Kotlin DSL module

### ISSUE THREAD

**Issue by raderio** [jOOQ/jOOQ#8499] opened 2019-04-09 14:05 UTC
Will be great to have Kotllin DSL support as a separate module.

So, all information needed for `TableImpl` and `Record` will be possible to have by implementing a base class `TableDefinition`.
And example will be
```
object Cities : TableDefinition() {
    val id = integer("id").autoIncrement().primaryKey()
    val name = varchar("name", 50)
}
```
So, `TableDefinition` will have information needed for `TableImpl` and `Record` by analyzing class properties.

**Comment by lukaseder** [comment] 2019-04-09 14:16
Thank you very much for your suggestion.

I don't think we need a Kotlin specific API here, this will be generally useful, and I think it will already be covered by #7444.

So, I'm closing this as a duplicate of #7444

**Closed as completed by lukaseder** 2019-04-09 14:16 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, R: Duplicate, E: All Editions

**Comment by raderio** [comment] 2019-04-16 14:50
```
object AccountsTable : TableImpl<Record>("accounts") {

    val id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "")
    val type = createField("type", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "")
}
```
```
    val result = DSL.using(connection)
            .select(AccountsTable.id, AccountsTable.type)
            .from(AccountsTable)
            .orderBy(AccountsTable.id)
            .fetch()

    println(result)
```
this generate result as
```
+----+----------+
|  id| type      |
+----+----------+
```
How to have a result as
```
+----+----------+
|  accounts.id| accounts.type      |
+----+----------+
```
as if I use 
```
val result = DSL.using(connection)
            .select(field("accounts.id", Long::class.java), field("accounts.type"))
            .from(table("accounts"))
            .orderBy(field("accounts.id"))
            .fetch()
```

**Comment by lukaseder** [comment] 2019-04-16 15:08
when you write `field("accounts.id")`, what you're really doing is you're using a "plain SQL template":
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating

You could pass any SQL fragment there, including something like `field("(select 1+2 from dual) as id")`. jOOQ wouldn't know or care. The `Field.getName()` produced by this is the entire expression, unless you call `Field.as()` on it and alias the field explicitly. The `Field.getName()` is what you can see in that printed result set.

With `TableImpl.createField()`, there's no point in producing such a qualified expression, because the field name is well defined. It is `id`. If you still want the entire expression in the field's name, you could alias it explicitly. But why would you want that?

**Comment by raderio** [comment] 2019-04-16 20:07
> But why would you want that?
```
object IndividualsTable : TableImpl<Record>("individuals") {

    val id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "")
    val firstName = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "")
}
```
```
val result = DSL.using(connection)
            .select(AccountsTable.id, AccountsTable.type, IndividualsTable.id, IndividualsTable.firstName)
            .from(AccountsTable)
            .leftJoin(IndividualsTable).on(IndividualsTable.id.eq(AccountsTable.id))
            .orderBy(AccountsTable.id)
            .fetch()

    println(result)
```
How to extract `accounts.id` and `individuals.id` from `result` ?

**Comment by lukaseder** [comment] 2019-04-17 15:23
You can extract the individual columns by using:

```java
val accountsTableId = record[AccountsTable.id]
val individualsTableId = record[IndividualsTable.id]
```

In other words, call [`Record.get(Field)`](https://www.jooq.org/javadoc/latest/org/jooq/Record.html#get-org.jooq.Field-)

**Comment by raderio** [comment] 2019-04-17 20:42
```
record[IndividualsTable.id]
```
throws an exception
```
Exception in thread "main" java.lang.IllegalStateException: result.get(0).get(IndividualsTable.id) must not be null
```
As I understand 
```
select(AccountsTable.id, AccountsTable.type, IndividualsTable.id, IndividualsTable.firstName)
```
returns a non-nullable type for `IndividualsTable.id`, but in this case it can have `null` because it is `left join` 

So, is there a way to indicate that `IndividualsTable.id` can be nullable in same cases, and in others not, for exmple if we only select from `individuals` table?

**Comment by lukaseder** [comment] 2019-04-18 07:58
> returns a non-nullable type for IndividualsTable.id, but in this case it can have null because it is left join

In SQL, all types are nullable, always. There are "not null constraints" on some physical columns, but as soon as you apply SQL queries to those columns, they may become nullable again. See:
https://blog.jooq.org/2017/07/25/5-things-you-may-not-have-known-about-jooq/#thing1

If you had used the code generator, this would have been reflected by the fact that also in Java, all types are nullable, and the Kotlin / Java interoperability would have kicked in. I'm assuming that because you used Kotlin to define your tables, and you assumed that your `id` column was not nullable, you ran into this problem. If you do define all your jOOQ tables with Kotlin, you must ensure manually that all possibly nullable column references are indeed nullable in the Kotlin language as well.

My Kotlin-fu is not very good, but maybe something like this could work?

```kotlin
object Cities : TableDefinition() {
    val id: Field<Integer?> = integer("id").autoIncrement().primaryKey()
    val name: Field<String?> = varchar("name", 50)
}
```

Of course, once more, I must ensure that it is understood that the best way to use jOOQ is not to bypass using the code generator, which already solved many problems like this particular one for you. You're going to keep running into all the problems that code generation already solved years ago... :)

**Comment by raderio** [comment] 2019-04-18 11:02
I have defined tables in Java
```
public class AccountsTable extends TableImpl<Record> {

    public TableField<Record, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");
    public TableField<Record, String> type = createField("type", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    public AccountsTable(String name) {
        super(name);
    }

    public AccountsTable() {
        super("accounts");
    }
}

public class IndividualsTable extends TableImpl<Record> {

    public TableField<Record, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");
    public TableField<Record, String> firstName = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    public IndividualsTable(String name) {
        super(name);
    }

    public IndividualsTable() {
        super("individuals");
    }
}
```
```
val result = DSL.using(connection)
            .select(acc.id, acc.type, indv.id, indv.firstName)
            .from(acc)
            .leftJoin(indv).on(indv.id.eq(acc.id))
            .orderBy(acc.id)
            .fetch()

    println(result)
    println(result.get(0).get(indv.id))
```
Also throws same exception "java.lang.IllegalStateException: result.get(0).get(indv.id) must not be null"

So the issue is not that I defined tables in Kotlin.

**Comment by raderio** [comment] 2019-04-18 12:17
Nevermind. It is something strange with `println` method
```
println(result.get(0).get(indv.id) == null)
```
works

**Comment by lukaseder** [comment] 2019-04-18 13:18
> Nevermind. It is something strange with println method

Interesting, thanks for the update
