### ISSUE TITLE
JOOQ meta-model for UDT types doesn't reference schema

### ISSUE THREAD

**Issue by stellingsimon** [jOOQ/jOOQ#7685] opened 2018-07-24 09:35 UTC
### Expected behavior and actual behavior:

The JOOQ model for UDT types does not reference the DB schema they originate from, which leads to errors upon inserting records with such a UDT type under two conditions:

 * the connection used to insert does not have the respective schema on its `search_path`.
 * a converter for the UDT-typed column is registered in the JOOQ generator configuration

### Steps to reproduce the problem (include example code if possible):

We have a complex user-defined type in our Postgres schema:

```
CREATE TYPE myschema.my_type (
    a text,
    b text
);
```

```
CREATE TABLE myschema.my_table (
   id UUID PRIMARY KEY,
   my_type_field MY_TYPE
);
```

and register a custom `Converter` to be used in the JOOQ metamodel:

```
<forcedType>
    <userType>com.my.custom.classes.MyType</userType>
    <converter>com.my.model.MyType.JOOQMyTypeConverter</converter>
    <expression>.*\.MY_TYPE_FIELD</expression>
</forcedType>
```

Then, we insert into `my_table` using JOOQ **on a connection that doesn't have `myschema` on its `search_path`**:

```
MyTableRecord record = new MyTableRecord(UUID.randomUUID(), new MyType("a", "b"));
record.attach(dsl.configuration());
record.insert();
```
which generates the following SQL statement:
```
insert into "myschema"."my_table" ("id", "my_type_field") 
values (cast(? as uuid), ?::"my_type") 
returning "myschema"."my_table"."id"

-- ERROR: type "my_type" does not exist
```
The UDT type is defined in the schema `myschema`, but this information is lost when rendering the `INSERT` statement.

The problem is **reproducible only** if a converter is used. This is because some inlining transformation is applied if no converter is present, such that the rendered statement no longer refers to `my_type`:

```
insert into "myschema"."my_table" values (cast(? as uuid), row(?, ?));
```

The cause of this issue seems to be that the schema value `null` passed into `UDTImpl::new` is being used instead of the value returned by `MyType::getSchema`. I verified this experimentally by changing the super-constructor call in `MyType::new` as follows:

The problem can be remedied by manually adjusting the private constructor of JOOQ's `MyType`:
```
    private MyType() {
        super("my_type",
        SomeOtherSchema.SOME_OTHER_SCHEMA, // was 'null'
        null,
        false);
```

which lead to the following error:

```
-- ERROR: type "some_other_schema.my_type" does not exist
```

### Versions:

- jOOQ: 3.11.2
- Java: `javac 1.8.0_181`
- Database (include vendor): PostgreSQL
- OS: Linux
- JDBC Driver (include name if inofficial driver): 42.2.1

**Comment by lukaseder** [comment] 2018-07-26 07:52
Thank you very much for your report. That's curious - we do have integration tests that cover qualified UDT types both in Oracle and PostgreSQL. The qualification doesn't happen over the constructor, but over the `getSchema()` getter, which is overridden. It might well be that there's an edge case where the qualification doesn't work. Will investigate this ASAP

**Comment by stellingsimon** [comment] 2018-07-26 08:34
@lukaseder Not realizing that you have answered already, I changed the original description...

Anyhow, I can verify experimentally that the value passed to the constructor is being used instead of the one returned by `getSchema`.

**Comment by stellingsimon** [comment] 2018-07-26 08:49
@lukaseder I think the problem is that `UDTImpl` doesn't override `getQualifiedName`. The field `AbstractNamed::name` contains the schema passed to `UDTImpl::new` instead of `MyType::getSchema`...

**Comment by lukaseder** [comment] 2018-08-21 15:38
I can reproduce this issue and can confirm that the problem is with `getQualifiedName()` not returning the correct value. I don't think the method should be overridden. Rather the `name` attribute should be fully qualified, which means this is essentially a code generator problem.

Will do further investigations tomorrow.

**Comment by stellingsimon** [comment] 2018-08-21 16:36
Thanks Lukas. 

From what I've gathered, there seems to be a big caveat with the workaround I initially proposed (referencing the schema object in the UDT constructor): after deploying it, we had flaky builds, observing still a `null` schema being passed to the `UDTImpl` constructor **sometimes, but not always**. I suspected a cycle in the static initialization graph, and we're now using `new SchemaImpl("myschema")` as the argument to `UDTImpl`'s constructor -- this solved the flaky builds.

**Comment by lukaseder** [comment] 2018-08-22 07:48
Yes indeed, that static initialisation cycle is the reason why `UDTImpl.getSchema()` is overloaded, because that getter call does not happen during the initialisation. Your right, passing a `new SchemaImpl()` is probably the way to go here, as a quick fix, before the initialisation itself is fixed.

**Comment by lukaseder** [comment] 2018-11-22 13:45
The main problem appears only when there are more than 1 user defined types per schema, see #7496 for a discussion. When I tried to reproduce this particular issue, it has not occurred to me to try that. With a single type in `myschema`, there is no problem. The first type that is initialised always work. The other ones don't.

I will close this issue as a duplicate of #7496, as the other issue is more specific.

**Closed by lukaseder** 2018-11-22 13:45 UTC
Labels: C: Code Generation, C: DB: PostgreSQL, E: All Editions, P: High, T: Defect
