### ISSUE TITLE
Provide option to suppress warnings about functions without named parameters

### ISSUE THREAD

**Issue by tomdcc** [jOOQ/jOOQ#4765] opened 2015-12-01 06:24 UTC
Hi

We are generating code against a Postgres database that has the widely used `pgcrypto` extension installed. `pgcrypto` has many functions that have parameters that are not named. This results in many warnings each time we generate code, which spams our output and makes it difficult to see any warnings that we actually care about.

For the time being, I've explicitly excluded all of the pgcrypto function names from generation, but this isn't a great solution: not only is that list of function names fragile, but if we ever want to call any directly from our app (currently we just call one from a postgres function of our own) we'll be back in the same boat.

It would be nice to have a generator option to suppress this warning.

**Comment by lukaseder** [comment] 2015-12-01 09:58
Thank you for your suggestion. The discussion is similar to that of #4764. There's certainly room for improvement, but we need to find the most far-sighted solution to fine-tuning logging. Let's further discuss in the other issue.

**Comment by lukaseder** [comment] 2015-12-01 09:59
Closing this as a duplicate of the renamed issue #4764

**Closed by lukaseder** 2015-12-01 09:59 UTC
Labels: C: Code Generation, P: Medium, R: Duplicate, T: Enhancement
