### ISSUE TITLE
LocalDate conversion discrepancy before and after June 15, 1916, in Europe/Paris timezone

### ISSUE THREAD

**Issue by lefebvrecharlie** [jOOQ/jOOQ#16449] opened 2024-03-14 10:42 UTC
### Steps to reproduce the problem

I've identified a date conversion inconsistency with jOOQ version 3.19.5, specifically when handling dates around the introduction of daylight saving time in France. The issue arises when converting timestamps from the database into LocalDate in the Europe/Paris timezone.

When retrieving a timestamp recorded as "1916-06-14 00:00:00.000" from the database and converting it to LocalDate using record.get(xxxx.xxxx, LocalDate.class), the resulting date is incorrectly "1916-06-13". However, using record.get(xxxx.xxxx) and then converting it to LocalDate with .toLocalDate() yields the correct date of "1916-06-14". Interestingly, this issue does not occur for dates starting from "1916-06-15" onwards, which aligns with the historical introduction of daylight saving time in France on June 14, 1916.

This suggests that there might be a specific issue with how timezone conversion is managed for dates immediately before the implementation of daylight saving time.

Steps to Reproduce:

1. Set the system to the Europe/Paris timezone.
2. Retrieve a timestamp from the database for "1916-06-14 00:00:00.000".
3. Convert this timestamp to LocalDate using record.get(xxxx.xxxx, LocalDate.class) and note the incorrect date of "1916-06-13".
4. Convert the same timestamp to LocalDate using record.get(xxxx.xxxx).toLocalDate() and observe the correct date of "1916-06-14".
5. Repeat steps 2-4 for a date of "1916-06-15" or later and observe no discrepancy in the conversion.

Expected Behavior:
Both methods of conversion should result in the correct date, regardless of the timestamp being before or after the introduction of daylight saving time in France.

Actual Behavior:
A discrepancy is observed in the conversion of dates immediately before the introduction of daylight saving time, with direct LocalDate conversion resulting in an incorrect date.

<img width="557" alt="Capture d’écran 2024-03-14 à 11 24 33" src="https://github.com/jOOQ/jOOQ/assets/35916470/b6448ee8-13d5-4f9f-b923-76778ca0f95e">
<img width="550" alt="Capture d’écran 2024-03-14 à 11 24 44" src="https://github.com/jOOQ/jOOQ/assets/35916470/a8f2c387-7651-44c2-afa3-ad80e1fa03f2">
<img width="512" alt="Capture d’écran 2024-03-14 à 11 25 01" src="https://github.com/jOOQ/jOOQ/assets/35916470/6350742a-d998-4eaf-adde-b0171122a21a">
<img width="504" alt="Capture d’écran 2024-03-14 à 11 36 20" src="https://github.com/jOOQ/jOOQ/assets/35916470/58f11f2b-7a17-413f-aad3-30bf4d323699">
<img width="615" alt="Capture d’écran 2024-03-14 à 11 36 34" src="https://github.com/jOOQ/jOOQ/assets/35916470/83940d94-66cc-47f8-9abe-ccb415e9d9d8">
<img width="522" alt="Capture d’écran 2024-03-14 à 11 36 44" src="https://github.com/jOOQ/jOOQ/assets/35916470/015e8306-04ea-4761-ae69-8a8b1f924f27">

### jOOQ Version

jOOQ Pro 3.19.5

### Database product and version

Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

### Java Version

21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

Oracle JDBC 19.3.0.0

**Comment by lukaseder** [comment] 2024-04-24 10:29
(https://github.com/jOOQ/jOOQ/issues/14866 was included in 3.19.7)

**Comment by lukaseder** [comment] 2024-05-13 10:07
I'm closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/14866.

Let me know if there's still another related issue that I may have overlooked.

**Closed by lukaseder** 2024-05-13 10:07 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Duplicate, E: All Editions
