### ISSUE TITLE
Returning jOOQ Record from Spring Boot @RestController doesn't work as expected

### ISSUE THREAD

**Issue by AnghelLeonard** [jOOQ/jOOQ#11203] opened 2021-01-08 12:22 UTC
### Expected behavior
Consider a query returning a `Record` (e.g., `CustomerRecord`) and the following Spring Boot REST `Controller`:

```Java
@GetMapping("/customer")
public CustomerRecord findAnyCustomer() {

    return {some_CustomerRecord};
}
```

Expecting that the default Spring Boot (Jackson based) serializer will output a JSON containing the `CustomerRecord` data. 

### Actual behavior
Initially, it throws an exception: 
*com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.jooq.TableOptions and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: jooq.generated.tables.records.CustomerRecord["table"]->jooq.generated.tables.Customer["options"])*

After setting `FAIL_ON_EMPTY_BEANS` in `application.properties` I got a relatively big JSON that looks like this fragment:
*{"table":{"name":"customer","comment":"","options":{},"identity":{"table":{"name":"customer","comment":"","options":{},"identity":{"table":{"name":"customer","comment":" ...*

### Versions

- jOOQ: 3.14.4
- Java: 14 (Spring Boot 2.3.6)
- Database (include vendor): MySQL (but, I don't think it matters)
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): latest MySQL driver (`<artifactId>mysql-connector-java</artifactId>`)

**Comment by lukaseder** [comment] 2021-01-12 13:52
Thanks a lot for your report.

While we currently do not have any dependencies on Jackson, etc. to help serialise records, it might still make sense to do so since Jackson is a very popular library for this purpose. We're already using Jackson, if discovered from the classpath, using reflection, to map from SQL/JSON results to POJOs.

I'll look into this some time soon.

**Comment by AnghelLeonard** [comment] 2021-05-14 06:22
I've created here: 
[https://github.com/spring-projects/spring-boot/issues/26457](https://github.com/spring-projects/spring-boot/issues/26457)

**Comment by lukaseder** [comment] 2021-05-14 09:41
Thanks a lot for creating that Spring Boot issue. So, in summary, this can be resolved in 2 ways:

- Using Spring (Boot) configuration as suggested in that issue spring-projects/spring-boot#26457
- By letting `Record <: Map<String, Object>` as suggested here: https://github.com/jOOQ/jOOQ/issues/11889

I think from the jOOQ perspective, this doesn't have anything to do with `@RestController`. I wouldn't want to implement anything specific to that particular kind of jOOQ usage. But letting `Record` subtype `Map` (just like `Result<R> <: List<R>`) is *very* promising, and also has a lot of other uses.

So, I'm closing this as a duplicate of the above two

**Closed by lukaseder** 2021-05-14 09:41 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Enhancement
