### ISSUE TITLE
SQL Script Codegen failed due to unsupported IF NOT EXISTS

### ISSUE THREAD

**Issue by jesset-twosigma** [jOOQ/jOOQ#7664] opened 2018-07-10 21:08 UTC
### Expected behavior and actual behavior:
Expected:
Parse SQL scripts and generate code.

Actual:
```
ERROR DDLDatabase - An exception occurred while parsing script source : ./sql/upgrades/fobo_trade/1.1.sql. Please report this error to https://github.com/jOOQ/jOOQ/issues/new
org.jooq.impl.ParserException: Unsupported query type: [1:1] [*]IF NOT EXISTS (SELECT * FROM sysobjects AS so WHERE so.name = 'foo_list')
BEGIN...
        at org.jooq.impl.ParserContext.exception(ParserImpl.java:8469)
        at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:778)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:444)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:431)
        at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:199)
        at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:178)
        at org.jooq.meta.extensions.ddl.DDLDatabase.create0(DDLDatabase.java:138)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:231)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:220)
        at org.jooq.meta.AbstractDatabase.getDialect(AbstractDatabase.java:202)
        at org.jooq.codegen.AbstractGenerator.logDatabaseParameters(AbstractGenerator.java:155)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:297)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:750)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:220)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:192)
```
### Steps to reproduce the problem (include example code if possible):
Create an SQL file that uses IF NOT EXISTS to protect against re-running:
```
IF NOT EXISTS (SELECT * FROM sysobjects AS so WHERE so.name = 'foo_list')
BEGIN
    CREATE TABLE [dbo].[foo_list] (
        [foo] [int] NOT NULL,
    ) ON [PRIMARY]
END
```
Create a XML file that uses the org.jooq.meta.extensions.ddl.DDLDatabase database:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd">
  <logging>TRACE</logging>

  <generator>
    <database>
      <name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
      <properties>
        <property>
          <key>scripts</key>
          <value>sql/1.1.sql</value>
        </property>
        <property>
          <key>sort</key>
          <value>semantic</value>
        </property>
      </properties>
    </database>
  </generator>

  <target>
    <packageName>com.foo.data</packageName>
    <directory>java/src</directory>
  </target>
</configuration>
```

Run the code generator as normal.

### Versions:
- jOOQ: 3.11.2
- Java: 1.8.0_172
- OS: Linux
- JDBC Driver (include name if inofficial driver): org.jooq.meta.extensions.ddl.DDLDatabase

**Comment by lukaseder** [comment] 2018-07-12 07:52
Thank you very much for your suggestion. This is definitely a T-SQL language feature to keep in mind when we'll be adding support for procedural language features through #6475

**Comment by lukaseder** [comment] 2019-02-06 11:02
#6475 implements support for procedural logic, but we need more than that to be able to use it in `DDLDatabase`. As it stands now, DDLDatabase emulates SQL scripts by translating them to the H2 dialect, then running them in memory on an H2 database prior to reverse engineering the schema. If we continue to do this, we'll need to:

- Emulate procedural logic in H2 using generated Java code. Currently, H2 doesn't support anonymous blocks, only procedures. I've requested support for anonymous blocks here: https://github.com/h2database/h2database/issues/1723.
- In the absence of anonymous blocks in H2, there are 2 ways they could be emulated:
  - By creating a stored procedure for them, in some temporary schema: #8195
  - By interpreting them in the client: #8193
- In any case, we also need to emulate dictionary views by translating them to the target database: #8301

As all the missing features from this issue are addressed in other features, I will close this one here as a duplicate of the other ones.

**Closed by lukaseder** 2019-02-06 11:02 UTC
Labels: C: Functionality, E: Enterprise Edition, E: Professional Edition, P: Medium, T: Enhancement
