### ISSUE TITLE
Serializing to String ignores registered ConverterProvider

### ISSUE THREAD

**Issue by blurb-jared-martin** [jOOQ/jOOQ#17631] opened 2024-11-19 00:18 UTC
### Expected behavior

After registering a `ConverterProvider`, I expect that serialization would check to see if the type matches one registered in the `ConverterProvider` and it does not.

### Actual behavior

jOOQ creates a hardcoded instance of `ConvertAll` which doesn't seem to check if the `configuration` has a `ConverterProvider` registered.

### Steps to reproduce the problem

1. Make the `ConverterProvider`

I'm doing this with io.vavr.control.Option, but anything would work:

```
import io.vavr.control.Option;
import org.jooq.Converter;
import org.jooq.ConverterProvider;
import org.jooq.impl.DefaultConverterProvider;

public class VavrOptionConverterProvider implements ConverterProvider {
    final ConverterProvider delegate = new DefaultConverterProvider();

    @Override
    public <T, U> Converter<T, U> provide(Class<T> tType, Class<U> uType) {
        // I assumed this would be the serialization bit
        if (Option.class.isAssignableFrom(tType)) {
            return Converter.ofNullable(tType, uType,
                                        t -> ((Option<U>) t).getOrNull(),
                                        u -> (T) Option.of(u));
        }
        // This is obviously the deserialization bit
        if (Option.class.isAssignableFrom(uType)) {
            return Converter.ofNullable(tType, uType,
                                        t -> (U) Option.of(t),
                                        u -> ((Option<T>) u).getOrNull());
        }
        return delegate.provide(tType, uType);
    }
}
```

2. Make the DSLContext:

```
    @Bean
    @Lazy
    public DSLContext dslContext(DataSource dataSource) {
        DSLContext context = DSL.using(dataSource, <whatever>);
        context.configuration()
               .set(new VavrOptionConverterProvider());
        return context;
    }
```

3. Serialize the POJO to a column that has type `varchar` or `string` or whatever SQL

```
class MyPojo {
     Option<String> myOpt;
}

public store(MyPojo p) {
    var newRecord = context.newRecord(MY_POJOS, p);
    newRecord.store();
}
```

The value that is stored is `Some("theString")` not simply `"theString"`.

Note that I am aware that there is a workaround with implementing a `RecordUnmapperProvider` - which is in the Javadoc, but not in the main body of documentation, but it seems weird to implement both a `ConverterProvider` and then only implement a `RecordUnmapperProvider` - and if I'm going to go with the `RecordUnmapperProvider` I'm a lot safer to use `RecordMapperProvider` instead of `ConverterProvider`? 

### jOOQ Version

jOOQ Open Source Edition 3.19.10

### Database product and version

postgres:15.5 in TestContainer

### Java Version

Amazon Corretto 21.0.4

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.2

**Comment by lukaseder** [comment] 2024-11-22 08:10
Thanks for your report.

This seems to be a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/14980

**Closed by lukaseder** 2024-11-22 08:10 UTC
Labels: T: Defect
