### ISSUE TITLE
Bad extra derived table generated when INSERT .. SELECT references target table from correlated subquery in MariaDB, MySQL

### ISSUE THREAD

**Issue by TheDIM47** [jOOQ/jOOQ#11486] opened 2021-02-20 17:18 UTC
### Expected behavior
`Exists` expressions should not generate extra SQL

### Actual behavior
`.andNotExists(DSL.selectZero().from(RR).where(RR.ID.eq(TT.ID)))`
generates:
`AND NOT (EXISTS (SELECT * FROM (SELECT 0 AS ZERO FROM ... AS RR WHERE (RR.CHID = TT.ID)) AS T))`
may be simplified to:
`AND NOT EXISTS (SELECT 0 FROM ... AS rr WHERE (rr.id = tt.id))`

Looks like applies to all xxxExists() functions.

### Steps to reproduce the problem

Original query:
```sql
ctx.insertInto(b)
.columns(x,y,z)
.select(
  ctx.select(x, y, z)
    .from(a)
    .where(...)
    .andNotExists(DSL.selectZero().from(b).where(b.id.eq(a.id)))
)
.onDuplicateKeyIgnore()
.execute();
```
Minimal example:
```sql
create table tmp(id int, name varchar(10));
create table tmp2(id int, name varchar(10));

insert into tmp(id, name)
select id, name
from tmp2 as v
where 0=1 and not exists(select * from (select 0 from tmp2 as u where u.name=v.name) as t);
```
Error: Unknown column 'v.name' in 'where clause'
1 statement failed.

```sql
insert into tmp(id, name)
select id, name
from tmp2 as v
where 0=1 and not exists(select 0 from tmp2 as u where u.name=v.name);
```
INSERT INTO tmp successful
0 rows affected

### Versions

- jOOQ: 3.14.7
- Java: 8, 11
- Database (include vendor): MariaDB 10.3.16-MariaDB
- OS: Linux
- JDBC Driver (include name if inofficial driver): com.mysql.jdbc.Driver, 5.1.49

**Comment by lukaseder** [comment] 2021-02-22 08:36
Thanks a lot for your report. The reason for this additional derived table is #6583, a limitation of some MySQL and MariaDB versions, regarding the possibility of selecting from a table that is being written to.

I can reproduce both the syntax error you ran into, as well as the fact that the query works correctly on MySQL 8.0.22 and MariaDB 10.5.8.

To be investigated if:

- The two RDBMS have fixed this somehow in the recent past (I doubt it)
- The workaround in #6583 is being applied too aggressively and some cases of self references are possible already, e.g. when used from an `EXISTS` subquery

**Comment by lukaseder** [comment] 2021-02-22 08:49
It appears that the rules implemented in #6583 do not apply to `INSERT .. SELECT`. Only to e.g. `INSERT .. VALUES ((SELECT ..))` and other DML statements operating on correlated subqueries.

**Comment by lukaseder** [comment] 2021-02-22 08:55
The simplest possible fix would be to treat the `SELECT` in `INSERT .. SELECT` as a subquery, internally. But that could have other side effects with logic that depends on the subquery level, including e.g. the "top level CTE" transformations.

**Comment by lukaseder** [comment] 2021-02-22 09:14
Better not tamper with the subquery level for this. We can simply exclude the #6583 workaround for the `INSERT .. SELECT` statement.

**Comment by TheDIM47** [comment] 2021-02-22 09:19
Thanks a lot for clarification! IMHO: Disable aggressive optimizations and allow users rewrite query parts manually, based on their DBMS type or context, will be simple. i.e. I can fix in my code:
```sql
subQuery = ctx.select().from()...
if (<I need wrapper>) subQuery = ctx.select(subQuery).as("t")
...
and later:
.not(exists(subQuery))...
```
Otherwise:
1. Enable/Disable this feature based on DBMS type/version
2. Enable/Disable based on context
looks overcomplicated.

**Comment by lukaseder** [comment] 2021-02-22 09:21
Fixed in jOOQ 3.15.0 and 3.14.8 (#11489)

**Comment by lukaseder** [comment] 2021-02-22 09:24
> Disable aggressive optimizations and allow users rewrite query parts manually, based on their DBMS type or context, will be simple. i.e. I can fix in my code

This isn't an "optimisation". This is a workaround for a syntax that is not supported at all. The assumption here was that using correlated subqueries in DML referencing the target table is not possible *at all* in MariaDB/MySQL, e.g. try this:

```sql
insert into tmp (id) values ((select coalesce(max(id)) + 1 from tmp))
```

It produces:

> SQL Error [1093] [HY000]: (conn=4) Table 'tmp' is specified twice, both as a target for 'INSERT' and as a separate source for data

So, this is just a bug, not a feature.

> 1. Enable/Disable this feature based on DBMS type/version

We could, and we sometimes offer such flags. But here, given that a certain totally valid SQL syntax doesn't work *at all* in these dialects, it seems unnecessary to offer a feature toggle. The fact that it was applied for `INSERT .. SELECT` where it's not needed is simply a bug.

Having hundreds of these feature toggles also overcomplicates jOOQ's internals. We'd have to:

1. Document these flags
2. Maintain these flags (backwards compatibly)

**Closed by lukaseder** 2021-02-22 09:24 UTC
Labels: C: DB: MariaDB, C: DB: MySQL, C: Functionality, E: All Editions, P: Medium, T: Defect

**Comment by TheDIM47** [comment] 2021-02-22 09:26
Great! Thanks!
