### ISSUE TITLE
NullPointerException when using plain SQL identity and additional column in INSERT .. RETURNING

### ISSUE THREAD

**Issue by GavinRay97** [jOOQ/jOOQ#14771] opened 2023-03-09 16:22 UTC
### Expected behavior

I am experimenting with supplying my own identity keys for `returning` because I would know what they are
Running into an NPE doing this though, with the below code:

I saw this answer on SO, which I tried to mimic:
- https://stackoverflow.com/questions/60778582/how-do-i-use-jooq-insert-returning-in-mysql-without-code-generation

```kt
    val jdbcUrl = "jdbc:mysql://localhost:3306/Chinook?allowMultiQueries=true&user=root&password=Password123%23"
    val conn = DriverManager.getConnection(jdbcUrl)

    val ctx = DSL.using(
        conn,
        SQLDialect.MYSQL_8_0_20,
        Settings()
            .withRenderFormatted(true)
            .withStatementType(StatementType.STATIC_STATEMENT)
    )

    val columns = listOf(
        DSL.field("Name")
    )

    val rows = listOf(
        DSL.row(
            listOf(
                DSL.inline("foobar") // Name
            )
        )
    )

    val results = ctx.insertInto(DSL.table("Artist"))
        .columns(columns)
        .valuesOfRows(rows)
        .returning(
            DSL.field("ArtistId", SQLDataType.INTEGER.identity(true)),
            DSL.field("Name")
        )
        .fetch()

    println(results)
    println("Result size: ${results.size}")
```

I get the following error:
```java
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.jooq.Field.in(Object[])" because the return value of "org.jooq.Table.field(org.jooq.Field)" is null
	at org.jooq_3.18.0-SNAPSHOT.MYSQL_8_0_20.debug(Unknown Source)
	at org.jooq.impl.AbstractDMLQuery.selectReturning(AbstractDMLQuery.java:1324)
	at org.jooq.impl.AbstractDMLQuery.executeReturningGeneratedKeysFetchAdditionalRows(AbstractDMLQuery.java:1257)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1060)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:341)
	at org.jooq.impl.DMLQueryAsResultQuery.fetch(DMLQueryAsResultQuery.java:144)
```

### Steps to reproduce the problem

Attempt to provide a manual identity field for an auto-inc table in a query with `returning` as above

### jOOQ Version

jOOQ Enterprise 3.18-SNAPSHOT

### Database product and version

MySQL 8

**Comment by GavinRay97** [comment] 2023-03-09 16:34
FWIW, I also tried with columns of `(ArtistId, Name)` and rows of `(DSL.DefaultValue(), foobar)` thinking that might have been the issue, but no dice there

**Comment by GavinRay97** [comment] 2023-03-09 16:49
Okay so it does work if you request just the identity column in the returning:

```kt
.returning(
    DSL.field("ArtistId", SQLDataType.INTEGER.identity(true)),
)
```

It looks like there's an if/else in the logic that decides whether to issue a second query based on whether you only select identity columns and if you only select identity columns then it doesn't.

**Comment by lukaseder** [comment] 2023-03-10 14:47
Thanks a lot for your report. The `NullPointerExceptoin` should certainly be fixed. Let me try to reproduce this soon.

**Comment by josephglanville** [comment] 2023-09-09 02:29
I am also running into this, I have created a minimal reproduction: https://github.com/josephglanville/mysql-returning-repro/blob/master/src/test/kotlin/Test.kt#L83-L88

**Comment by GavinRay97** [comment] 2023-09-09 12:59
Heya @josephglanville 

I forgot to post a public resolution to this for future-searchers.

What you have to do, when the schema is not pre-generated by jOOQ and you're using dynamic queries, is use `.returning()` with column definitions manually marked as `SQLDataType.INTEGER.identity(true)`:

```kt
val insertQuery = DSL.insertInto(DSL.table(DSL.name(table.name)))
        .columns(columns)
        .valuesOfRows(rows)
        .returning(primaryKeyColumnNames.map { DSL.field(it.value, SQLDataType.INTEGER.identity(true)) })
```

Hope this helps 👍

**Comment by josephglanville** [comment] 2023-09-12 09:21
@GavinRay97 yup I found the same workaround, see my repo above.

The problem is that it's documented to do a follow up query to get the non-generated fields in `returning`/`returningResult` and it doesn't do that.

So I have done my own emulation for now that will do said follow up query in the same transaction and that seems to work.

**Comment by lukaseder** [comment] 2023-11-29 16:07
Thanks for your comments, folks, and sorry for the delay. It seems that it would be sufficient to just avoid looking up the identity column from the `INSERT` target table if it isn't available.

The reason why this was being done is aliasing:

- #5050
- #9946

Prior to #9946, your code would have worked, so, a regression introduced in 3.14, if you will.

**Comment by lukaseder** [comment] 2023-11-29 16:10
Fixed in versions:

- 3.19.0
- 3.18.8 (https://github.com/jOOQ/jOOQ/issues/15894)
- 3.17.17 (https://github.com/jOOQ/jOOQ/issues/15896)
- 3.16.23 (https://github.com/jOOQ/jOOQ/issues/15895)

**Closed by lukaseder** 2023-11-29 16:10 UTC
Labels: T: Defect, C: Functionality, C: DB: MySQL, P: Medium, E: All Editions
