### ISSUE TITLE
Creation of tables from generated schema is incomaptible across dialects

### ISSUE THREAD

**Issue by ndawg** [jOOQ/jOOQ#7847] opened 2018-09-07 18:51 UTC
### Expected behavior and actual behavior:

When generating code from a database (in this instance, a Postgres db), the code that is generated has some hard-coded properties, for example, casts:
```java
public final TableField<DiscordConfigRecord, String> CONFIG = createField("config", org.jooq.impl.SQLDataType.CLOB.defaultValue(org.jooq.impl.DSL.field("'{}'::text", org.jooq.impl.SQLDataType.CLOB)), this, "");
```

If the dialect is switched to SQLite, the following statement will fail due to the above field:
```java
db.createTable(DISCORD_CONFIG).execute()
```
The resulting error is, predictably:
```
org.jooq.exception.DataAccessException: SQL [create table if not exists "public"."discord_config"("guild" bigint not null, "config" text null default '{}'::text)]; [SQLITE_ERROR] SQL error or missing database (unrecognized token: ":")
```
Ideally, jOOQ would be able to handle the creation of these databases, even across dialects. I'm unsure if this is within the scope of what jOOQ aims to support. If it isn't, I would love to be made aware of alternative options. 

### Steps to reproduce the problem (include example code if possible):

1. Generate code from a PSQL database
2. Switch to an empty SQLite database and attempt to create tables from the schema

### Versions:

- jOOQ: 3.9.2
- Java: 1.8
- Database (include vendor): psql 9.2 and sqlite3

**Comment by lukaseder** [comment] 2018-09-10 09:57
Thank you very much for your report. This is a very interesting case, where the generated jOOQ code currently isn't sophisticated enough for what you're trying to do. I currently see these possible workarounds:

- Rewrite default expressions in a more standard way, e.g. use a `CAST()` expression rather than `::`, and use `varchar` rather than `text`
- Override the jOOQ-meta classes to prevent default values from being generated on your columns
- Post process the generated code and remove the `defaultValue()` statements from it

I'm aware that none of these are very compelling...

The problem could be fixed on the jOOQ side in 2 ways:

- Use the parser on `DEFAULT` expressions and build a jOOQ expression tree for the expression, rather than a plain SQL field. This means we need to be able to generate jOOQ code using a `SQLDialect.JOOQ`: #6277. Of course, if the expression cannot be parsed, we'll revert to the plain SQL field. I've created a new issue for this: #7849
- Generate a parse call rather than a plain SQL call in the meta model itself. I've created a new issue for this: #7850

The latter approach is definitely doable for jOOQ 3.12. The former is more complex as the `SQLDialect.JOOQ` dialect will not be trivial to implement.

I'm closing this issue as a duplicate of the above two. Thanks again for reporting this!

**Closed by lukaseder** 2018-09-10 09:57 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect
