### ISSUE TITLE
3.12.0 regression with subselects

### ISSUE THREAD

**Issue by tbroyer** [jOOQ/jOOQ#9105] opened 2019-08-29 16:17 UTC
### Expected behavior and actual behavior:

I'm trying to upgrade to jOOQ 3.12.0 from 3.11.12, and codegen fails with the following error:

<details>
  <summary>codegen error</summary>
  <pre>

août 29, 2019 5:25:01 PM org.jooq.tools.JooqLogger warn
AVERTISSEMENT: SQL exception            : Exception while executing meta query: ERROR: syntax error at or near "select"
  Position : 1122

If you think this is a bug in jOOQ, please report it here: https://github.com/jOOQ/jOOQ/issues/new

```sql
select 
  "tables"."table_schema", 
  "tables"."table_name", 
  "tables"."specific_name", 
  "tables"."table_valued_function", 
  "tables"."materialized_view", 
  "tables"."description"
from (
  (
    select 
      "information_schema"."tables"."table_schema", 
      "information_schema"."tables"."table_name", 
      "information_schema"."tables"."table_name" as "specific_name", 
      false as "table_valued_function", 
      false as "materialized_view", 
      "pg_catalog"."pg_description"."description"
    from "information_schema"."tables"
      join "pg_catalog"."pg_namespace"
        on "information_schema"."tables"."table_schema" = "pg_catalog"."pg_namespace"."nspname"
      join "pg_catalog"."pg_class"
        on (
          "pg_catalog"."pg_class"."relname" = "information_schema"."tables"."table_name"
          and "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid
        )
      left outer join "pg_catalog"."pg_description"
        on (
          "pg_catalog"."pg_description"."objoid" = "pg_catalog"."pg_class".oid
          and "pg_catalog"."pg_description"."objsubid" = 0
        )
    where (
      "information_schema"."tables"."table_schema" in ('siar')
      and ("information_schema"."tables"."table_schema", "information_schema"."tables"."table_name") not in 
        select 
          "pg_catalog"."pg_namespace"."nspname", 
          "pg_catalog"."pg_class"."relname"
        from "pg_catalog"."pg_class"
          join "pg_catalog"."pg_namespace"
            on "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid
        where "pg_catalog"."pg_class"."relkind" = 'm'
      
    )
  )
  union all (
    select 
      "pg_catalog"."pg_namespace"."nspname"::varchar, 
      "pg_catalog"."pg_class"."relname"::varchar, 
      "pg_catalog"."pg_class"."relname"::varchar, 
      false as "table_valued_function", 
      true as "materialized_view", 
      "pg_catalog"."pg_description"."description"
    from "pg_catalog"."pg_class"
      join "pg_catalog"."pg_namespace"
        on "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid
      left outer join "pg_catalog"."pg_description"
        on (
          "pg_catalog"."pg_description"."objoid" = "pg_catalog"."pg_class".oid
          and "pg_catalog"."pg_description"."objsubid" = 0
        )
    where (
      "pg_catalog"."pg_namespace"."nspname" in ('siar')
      and "pg_catalog"."pg_class"."relkind" = 'm'
    )
  )
  union all (
    select 
      "information_schema"."routines"."routine_schema", 
      "information_schema"."routines"."routine_name", 
      "information_schema"."routines"."specific_name", 
      true as "table_valued_function", 
      false as "materialized_view", 
      ''
    from "information_schema"."routines"
      join "pg_catalog"."pg_namespace"
        on "information_schema"."routines"."specific_schema" = "pg_catalog"."pg_namespace"."nspname"
      join "pg_catalog"."pg_proc"
        on (
          "pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid
          and (("pg_catalog"."pg_proc"."proname" || '_') || cast("pg_catalog"."pg_proc".oid as varchar)) = "information_schema"."routines"."specific_name"
        )
    where (
      "information_schema"."routines"."routine_schema" in ('siar')
      and "pg_catalog"."pg_proc"."proretset"
    )
  )
) as "tables"
order by 
  1, 
  2
```

août 29, 2019 5:25:01 PM org.jooq.tools.JooqLogger error
GRAVE: Error while fetching tables
org.jooq.exception.DataAccessException: SQL [select "tables"."table_schema", "tables"."table_name", "tables"."specific_name", "tables"."table_valued_function", "tables"."materialized_view", "tables"."description" from ((select "information_schema"."tables"."table_schema", "information_schema"."tables"."table_name", "information_schema"."tables"."table_name" as "specific_name", false as "table_valued_function", false as "materialized_view", "pg_catalog"."pg_description"."description" from "information_schema"."tables" join "pg_catalog"."pg_namespace" on "information_schema"."tables"."table_schema" = "pg_catalog"."pg_namespace"."nspname" join "pg_catalog"."pg_class" on ("pg_catalog"."pg_class"."relname" = "information_schema"."tables"."table_name" and "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid) left outer join "pg_catalog"."pg_description" on ("pg_catalog"."pg_description"."objoid" = "pg_catalog"."pg_class".oid and "pg_catalog"."pg_description"."objsubid" = ?) where ("information_schema"."tables"."table_schema" in (?) and ("information_schema"."tables"."table_schema", "information_schema"."tables"."table_name") not in select "pg_catalog"."pg_namespace"."nspname", "pg_catalog"."pg_class"."relname" from "pg_catalog"."pg_class" join "pg_catalog"."pg_namespace" on "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid where "pg_catalog"."pg_class"."relkind" = 'm')) union all (select "pg_catalog"."pg_namespace"."nspname"::varchar, "pg_catalog"."pg_class"."relname"::varchar, "pg_catalog"."pg_class"."relname"::varchar, false as "table_valued_function", true as "materialized_view", "pg_catalog"."pg_description"."description" from "pg_catalog"."pg_class" join "pg_catalog"."pg_namespace" on "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid left outer join "pg_catalog"."pg_description" on ("pg_catalog"."pg_description"."objoid" = "pg_catalog"."pg_class".oid and "pg_catalog"."pg_description"."objsubid" = ?) where ("pg_catalog"."pg_namespace"."nspname" in (?) and "pg_catalog"."pg_class"."relkind" = 'm')) union all (select "information_schema"."routines"."routine_schema", "information_schema"."routines"."routine_name", "information_schema"."routines"."specific_name", true as "table_valued_function", false as "materialized_view", '' from "information_schema"."routines" join "pg_catalog"."pg_namespace" on "information_schema"."routines"."specific_schema" = "pg_catalog"."pg_namespace"."nspname" join "pg_catalog"."pg_proc" on ("pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid and (("pg_catalog"."pg_proc"."proname" || ?) || cast("pg_catalog"."pg_proc".oid as varchar)) = "information_schema"."routines"."specific_name") where ("information_schema"."routines"."routine_schema" in (?) and "pg_catalog"."pg_proc"."proretset"))) as "tables" order by 1, 2]; ERROR: syntax error at or near "select"
  Position : 1122
	at org.jooq_3.12.0.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2717)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:383)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:353)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2693)
	at org.jooq.meta.postgres.PostgresDatabase.getTables0(PostgresDatabase.java:445)
	at org.jooq.meta.AbstractDatabase.getTables(AbstractDatabase.java:1507)
	at org.jooq.meta.SchemaDefinition.getTables(SchemaDefinition.java:71)
	at org.jooq.codegen.JavaGenerator.generateSchema(JavaGenerator.java:4751)
	at org.jooq.codegen.JavaGenerator.generateSchema(JavaGenerator.java:4717)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:507)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:468)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:389)
	at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:800)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:221)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:216)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:188)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "select"
  Position : 1122
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:138)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3928)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:294)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:369)
	... 14 more

</pre>
</details>

More precisely, it points at the `select` in the `not in` on line 33 of the SQL query (I copy/pasted the query to a `psql` prompt), which should be enclosed in parentheses. This looks like a regression in

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

I'm calling jooq-codegen from Gradle with a `JavaExec` task (no specific plugin), which generates a command similar (I edited the file paths system property values) to:
```
/usr/lib/jvm/java-11-openjdk/bin/java -Ddb.password=xxx -Ddb.schema=xxx -Ddb.url=jdbc:postgresql:xxx -Ddb.user=xxx -Doutputdir=…/db/src/main/jooq -Dfile.encoding=UTF-8 -Duser.country=FR -Duser.language=fr -Duser.variant -cp …/jooq-codegen-3.12.0.jar:…/postgresql-42.2.6.jar:…/jooq-meta-3.12.0.jar:…/jooq-3.12.0.jar:…/jaxb-api-2.3.0.jar:…/reactive-streams-1.0.2.jar org.jooq.codegen.GenerationTool …/db/src/jooq-codegen.xml
```

For comparison, using 3.11.12, the command was:
```
/usr/lib/jvm/java-11-openjdk/bin/java -Ddb.password=xxx -Ddb.schema=xxx -Ddb.url=jdbc:postgresql:xxx -Ddb.user=xxx -Doutputdir=…/db/src/main/jooq -Dfile.encoding=UTF-8 -Duser.country=FR -Duser.language=fr -Duser.variant -cp …/jooq-codegen-3.11.12.jar:…/postgresql-42.2.6.jar:…/jaxb-runtime-2.3.2.jar:…/jooq-meta-3.11.12.jar:…/jooq-3.11.12.jar:…/jaxb-api-2.2.12.jar:…/stax-ex-1.8.1.jar:…/jakarta.xml.bind-api-2.3.2.jar:…/FastInfoset-1.2.16.jar:…/istack-commons-runtime-3.0.8.jar:…/jakarta.activation-api-1.2.1.jar:…/txw2-2.3.2.jar org.jooq.codegen.GenerationTool …/db/src/jooq-codegen.xml
```
I was including `org.glassfish.jaxb:jaxb-runtime:2.3.2` as an additional dependency, which explains the difference, but I also tried with only changing my jOOQ dependencies from 3.11.12 to 3.12.0 (and keeping JAXB in the classpath) and it didn't change the outcome.

My jooq-codegen.xml contains the following (I also have `<strategy>` and `<forcedTypes>`, but I believe they're only used after the failing query, so omitting them here), and I didn't change it between 3.11.12 and 3.12.0:
```xml
<configuration>
  <jdbc>
    <driver>org.postgresql.Driver</driver>
    <url>${db.url}</url>
    <user>${db.user}</user>
    <password>${db.password}</password>
  </jdbc>
  <generator>
    <database>
      <name>org.jooq.meta.postgres.PostgresDatabase</name>
      <inputSchema>${db.schema}</inputSchema>
      <excludes>flyway_schema_history|flyway_data_history|pgp_armor_headers</excludes>
      <includeRoutines>false</includeRoutines>
    </database>
    <generate>
      <records>false</records>
      <pojos>true</pojos>
      <javaTimeTypes>true</javaTimeTypes>
    </generate>
    <target>
      <packageName>fr.ird.siar.db.jooq</packageName>
      <directory>${outputdir}</directory>
      <encoding>UTF-8</encoding>
    </target>
  </generator>
</configuration>
```

### Versions:

- jOOQ: 3.12.0
- Java: openjdk 11.0.4+11
- Database (include vendor): postgresql 11, from the `postgres:11` "official" Docker image, specifically image ID `c3fe76fef0a611a53dfc8d3ca21fa51bf8ba03cf84c593e50dfe6cc830c69de6`
- OS: Arch Linux
- JDBC Driver (include name if inofficial driver): `org.postgresql.Driver` from `org.postgresql:postgresql:42.2.6`, from the Central Repository.

**Comment by lukaseder** [comment] 2019-08-29 16:29
Thank you very much for your report. This looks like a duplicate of #9104, which we're investigating ASAP. We'll release a patch soon.

**Closed by lukaseder** 2019-08-29 16:29 UTC
Labels: C: Code Generation, C: DB: PostgreSQL, E: All Editions, P: Urgent, T: Defect
