### ISSUE TITLE
ORA-00904: invalid identifier when trying to insert into tables with lower case identifier in Oracle

### ISSUE THREAD

**Issue by RenBrand** [jOOQ/jOOQ#17506] opened 2024-10-28 16:07 UTC
### Expected behavior

Inserting a new record with TableRecordImpl#insert() shouldn't fail with an `'ORA-00904: "ID": invalid identifier' - DataAccessException` if the "autogenerated" primary key column is named "id" in lower case.

### Actual behavior

Inserting the record fails with the following weird error-message because the column wasn't inserted at all.

```
org.jooq.exception.DataAccessException: SQL [insert into "BOX"."a_simple_table" ("col1", "col2") values (?, ?)]; ORA-00904: "ID": invalid identifier
```

Even the log output with inlined-parameter doesn't mention the column:

```SQL
insert into "BOX"."a_simple_table" ("col1", "col2") values ('a simple', 'test record')
```

The debugging of the underlying `oracle.jdbc.driver.T4CPreparedStatement` showed the following:

```SQL
insert into "BOX"."a_simple_table" ("col1", "col2") values (?, ?) RETURNING id INTO ?
```

Here everything is quoted except the returning column `id` which is appended by `org.jooq.impl.AbstractDMLQuery.prepare0(ExecuteContext)`  during the `default`-branch of the switch. Appending the column is totally fine because the record should be populated with the generated ID after the insert but the name should be quoted. (I've also tried the with the setting `withRenderQuotedNames( RenderQuotedNames.ALWAYS )` which also doesn't fix the problem)

### Steps to reproduce the problem

* create the following table on an oracle DB
  ```SQL
  CREATE TABLE "BOX"."a_simple_table" (
	"id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY(START with 1 INCREMENT by 1),
	"col1" VARCHAR2(128) NOT NULL,
	"col2" VARCHAR2(128) NOT NULL,
	
	CONSTRAINT "a_simple_table_pkey" PRIMARY KEY ("id")
  );
  ```
* generate the Jooq-TableRecords for the table
* insert a new record with
  ```JAVA
    ASimpleTableRecord rec = ctx.newRecord( A_SIMPLE_TABLE );
    rec.setCol1( "a simple" );
    rec.setCol2( "test record" );
    rec.insert();
  ```

### jOOQ Version

jOOQ Professional Edition 3.19.14

### Database product and version

Oracle Database 23ai Free Release 23.0.0.0.0 - Develop, Learn, and Run for Free

### Java Version

openjdk version "21" 2023-09-19

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.oracle.database.jdbc:ojdbc11:23.5.0.24.07

**Comment by lukaseder** [comment] 2024-10-28 16:49
Thanks for your report.

This seems to be another bug in ojdbc in this area. They had a few bugs with their generated `RETURNING` clause in the past. jOOQ doesn't generate this clause the way you're observing. If jOOQ generates a `RETURNING` clause, then it's inside of a PL/SQL block and everything is quoted correctly. This happens:

- When there are multiple rows inserted (e.g. `INSERT .. SELECT`)
- When the `ROWID` is returned
- When expressions are returned (including also virtual client side computed columns: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-computed/ - you could try this as a workaround)
- When UDTs are returned

(Most of the above trigger other ojdbc bugs / limitations). 

But in this case, we're calling JDBC's `Connection.prepareStatement(String, int)` with `Statement.RETURN_GENERATED_KEYS`. There's currently no way to override jOOQ's decision in `AbstractDMLQuery::emulateOracleReturning` - I suspect we should offer a `Settings` here, or similar.

**Comment by lukaseder** [comment] 2024-10-29 07:27
The issue can be reproduced with JDBC alone:

```sql
```

And then:

```java
try (PreparedStatement s = connection.prepareStatement(
    """
    insert into "t_17506" ("val") values (?)
    """,
    new String[] { "id" }
)) {
    s.setInt(1, 1);
    s.executeUpdate();

    try (ResultSet rs = s.getGeneratedKeys()) {
        System.out.println(rs.getMetaData().getColumnCount());

        while (rs.next()) {
            for (int i = 0; i < rs.getMetaData().getColumnCount(); i++)
                System.out.println(rs.getMetaData().getColumnName(i + 1) + rs.getString(i + 1));
        }
    }
}
```

Producing:

```
https://docs.oracle.com/error-help/db/ora-00904/
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:709)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:609)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1347)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1100)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:408)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:499)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:274)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1484)
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:2008)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1621)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3955)
	at oracle.jdbc.driver.OraclePreparedStatement.doExecuteLargeUpdate(OraclePreparedStatement.java:4314)
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:4291)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:4273)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:997)
	at org.jooq.testscripts.JDBC.main(JDBC.java:42)
Caused by: Error : 904, Position : 54, SQL = insert into "t_17506" ("val") values (:1 )
 RETURNING id INTO :2  [SQL INCLUDES EXPRESSIONS ADDED BY THE ORACLE JDBC DRIVER], Original SQL = insert into "t_17506" ("val") values (?)
 RETURNING id INTO ?, Error Message = ORA-00904: "ID": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:717)
	... 15 more
```

I've reported this bug here:
https://forums.oracle.com/ords/apexds/post/ora-00904-invalid-identifier-when-trying-to-insert-into-a-t-4909

So, the solution is really twofold:

- Add a heuristic to check whether any returned columns need quoting, in case of which we don't delegate to JDBC but emulate Oracle `RETURNING`
- Add a settings to override the default behaviour: https://github.com/jOOQ/jOOQ/issues/17508

**Comment by lukaseder** [comment] 2024-10-29 08:06
Fixed in versions:

- 3.20.0
- 3.19.15 (https://github.com/jOOQ/jOOQ/issues/17509)
- 3.18.22 (https://github.com/jOOQ/jOOQ/issues/17510)
- 3.17.31 (https://github.com/jOOQ/jOOQ/issues/17511)

**Closed by lukaseder** 2024-10-29 08:06 UTC
Labels: T: Defect, C: Functionality, C: DB: Oracle, P: Medium, E: Professional Edition, E: Enterprise Edition

**Comment by lukaseder** [comment] 2024-10-29 08:08
In the JDBC example, a workaround would be to just quote the identifier when calling JDBC:

```java
try (PreparedStatement s = connection.prepareStatement(
   """
   insert into "t_17506" ("val") values (?)
   """,
   new String[] { "\"id\"" }
)) { ... }
```

**Comment by RenBrand** [comment] 2024-10-29 09:25
> In the JDBC example, a workaround would be to just quote the identifier when calling JDBC:
> 
> ```java
> try (PreparedStatement s = connection.prepareStatement(
>    """
>    insert into "t_17506" ("val") values (?)
>    """,
>    new String[] { "\"id\"" }
> )) { ... }
> ```

That's what I've seen during my debug-sessions where I just changed the plain `id` with a quoted `"id"`. Thanks again for the fast response, the ORACLE forum entry and the intermediate fix on your side.
