### ISSUE TITLE
DAOs / fetchInto POJOs makes pojo with duplicate IDs

### ISSUE THREAD

**Issue by jordanamr** [jOOQ/jOOQ#12999] opened 2022-02-05 18:17 UTC
### Expected behavior

Using DAOs function findAll should return POJOs with unique IDs

### Actual behavior

Using DAOs function findAll returns a list of POJOs with their propers field... except for the primary key "id" which shows a lot of duplicate when it's impossible and not the case in my database

### Steps to reproduce the problem

I am creating my DAO this way : 
```java
MariaDbPoolDataSource pool = new MariaDbPoolDataSource(url);
DSLContext dsl = DSL.using(pool, SQLDialect.MARIADB);
CoachCardsDao dao = new CoachCardsDao(dsl.configuration());
```

And querying it like this:
```java
dao.findAll().forEach(pojo -> {
    log.info("{} : {}", pojo.getId(), pojo.getName());
});
```
Returns a lot of IDs that are duplicate... but other fields of the POJOs are not, and there is NO duplicate IDs in my table. this is very weird.
It also happens when using directly the DSL and using the fetchInto() function with the POJO class.

However, if I only use the DSL like this it works perfectly fine (no duplicate) : 
```java
dsl.select().from(COACH_CARDS).forEach(record -> {
    log.info("{} : {}", record.get(COACH_CARDS.ID), record.get(COACH_CARDS.NAME);
});
```

I am linking my table .sql file to this issue.
[coach_cards.zip](https://github.com/jOOQ/jOOQ/files/8008579/coach_cards.zip)
Thanks in advance.

(I also tried downgrading jOOQ to 3.15 and using the MySQL Connector/J but without any luck.)

### Versions

- jOOQ: 3.16.3
- Java: OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
- Database (include vendor): MariaBD 10.6.5
- OS: Windows 11 21H2 (22000.434)
- JDBC Driver (include name if inofficial driver): org.mariadb.jdbc:mariadb-java-client 3.0.3

**Comment by lukaseder** [comment] 2022-02-07 08:13
Thanks for your report. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/10696

**Closed by lukaseder** 2022-02-07 08:13 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Duplicate, E: All Editions
