### ISSUE TITLE
Deadlock on lazy initialisation of Tables in Scala

### ISSUE THREAD

**Issue by joroKr21** [jOOQ/jOOQ#10849] opened 2020-11-03 15:56 UTC
### Expected behavior
No deadlock.

### Actual behavior
Sometimes (but not every time) there is a deadlock when accessing a table for the first time.

### Steps to reproduce the problem
Unfortunately I don't have a standalone reproduction but I do have a thread dump: [threaddump.txt](https://github.com/jOOQ/jOOQ/files/5481850/threaddump.txt)
See thread `psp-gateway-contexts.database-1463` and thread `psp-gateway-contexts.database-400`
Some background on `lazy val` and deadlocks: https://blog.codecentric.de/en/2016/02/lazy-vals-scala-look-hood/

I believe the issue was introduced with commit dc47fdd342b4109131ad722e43bb115c9d47e4c8
We observed the problem after updating jOOQ 3.14.0 and reverting to 3.13.5 made it go away.
We haven't tried 3.13.6 but I assume it would have the same problem because of the backport. 

Looking at the generated code:
```scala
  /** The table <code>public.housekeeping</code>. */
  lazy val HOUSEKEEPING = Housekeeping.HOUSEKEEPING
```

I think we can just replace `lazy val` with `def` and rely on the lazy initialisation of objects (i.e. `Housekeeping`) instead.
There is no need for double laziness and it will also be more performant (no locking and memory barriers).
I'm not sure about the other uses of `lazy val` in dc47fdd342b4109131ad722e43bb115c9d47e4c8

### Versions

- jOOQ: 3.14.0
- Java: Amazon Coretto 8
- Database (include vendor): RDS Aurora 9.6
- OS: Linux
- JDBC Driver (include name if inofficial driver): postgresql

**Comment by lukaseder** [comment] 2020-11-03 16:07
Thanks a lot for your report and for your suggestions. 

> I think we can just replace `lazy val` with `def` and rely on the lazy initialisation of objects (i.e. `Housekeeping`) instead.

Have you tried patching the `JavaGenerator` and work with `def` instead of `lazy val`? I.e. can you confirm this won't produce the deadlock? I'll try this change on my side tomorrow.

**Comment by joroKr21** [comment] 2020-11-03 16:15
> Have you tried patching the JavaGenerator and work with def instead of lazy val? I.e. can you confirm this won't produce the deadlock? I'll try this change on my side tomorrow.

Nope, but I can try 👍

**Comment by lukaseder** [comment] 2020-11-10 14:49
So, I can confirm that `def` instead of `lazy val` works on our side (in the integration tests). However, there might be other subtle regressions because what used to be a property is now a method. There are a few edge cases where the empty parentheses are required to disambiguate things.

I guess we have a tradeoff here:

- Use `val` and live with the ugly but from what I can tell cosmetic `UninitializedFieldError`
- Use `lazy val` and live with the risk of deadlock (I don't think that's an option)
- Use `def` and live with the risk of having to add `()` in some cases, which I can't see right now

Let's try `def`

**Comment by lukaseder** [comment] 2020-11-10 14:51
I should have obviously mentioned this earlier. There's a workaround to prevent the deadlock. You can turn off generating these "global object references", see:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-globals/

**Comment by lukaseder** [comment] 2020-11-10 15:07
Fixed in jOOQ 3.15.0 and 3.14.4 (#10903). Any pre-3.14.4 release feedback would still be highly appreciated, regarding:

- Whether `def` doesn't introduce new regressions in existing code bases
- Whether this actually fixes the deadlock
- A reproducer would still be useful to help prevent regressions in the future

**Closed by lukaseder** 2020-11-10 15:07 UTC
Labels: C: Code Generation, C: Integration: Scala, E: All Editions, P: Urgent, T: Defect

**Comment by joroKr21** [comment] 2020-11-10 15:39
Thanks, I didn't have time to try in our project yet. A bit swamped ATM 😅 

> Use val and live with the ugly but from what I can tell cosmetic `UninitializedFieldError`

I haven't investigated the original issue (#8139) but it could be that the changes to the constructor in dc47fdd342b4109131ad722e43bb115c9d47e4c8 (i.e. adding the `null` parameter) were already enough to break the initialization cycle. It's hard for me to tell though because I have no mental model of how the code generator works.

> Use def and live with the risk of having to add () in some cases, which I can't see right now

I'm not sure I understand this, if there is a name clash it wouldn't work with `val` either.
And we can have `def foo = bar` without `()`.

Thanks for the workaround too 👍

**Comment by lukaseder** [comment] 2020-11-10 15:46
> > Use def and live with the risk of having to add () in some cases, which I can't see right now
> 
> I'm not sure I understand this, if there is a name clash it wouldn't work with `val` either.
> And we can have `def foo = bar` without `()`.

Here's an example of what I mean: https://github.com/jOOQ/jOOQ/issues/10877. I didn't investigate this problem, but the `()` cannot always be avoided, neither at the declaration site (see #10877) nor at the call site. I don't have a ready example for a call site usage where `()` are mandatory (e.g. `TABLE_NAME().COLUMN_NAME`)

**Comment by lukaseder** [comment] 2021-01-19 16:16
This fix has been released a while ago in jOOQ 3.14.4. I haven't heard anything, so I take this is now fixed?

**Comment by joroKr21** [comment] 2021-02-18 18:46
Yes, sorry for the long wait, I found some time to update to 3.14 and it's fixed 🎉

**Comment by lukaseder** [comment] 2021-02-18 18:48
Perfect, that's great to hear!
