### ISSUE TITLE
Error when generating code from a MariaDB database containing packages

### ISSUE THREAD

**Issue by ZlobniyVinya** [jOOQ/jOOQ#15319] opened 2023-06-30 14:23 UTC
### Expected behavior

No errors while fetching routines

### Actual behavior

i have an error

```
[ERROR] Error while fetching routines
java.lang.NullPointerException: Cannot invoke "org.jooq.meta.mysql.mysql.enums.ProcType.name()" because "type" is null
    at org.jooq.meta.mysql.MySQLDatabase.lambda$getRoutines0$6 (MySQLDatabase.java:620)
    at java.lang.Iterable.forEach (Iterable.java:75)
    at org.jooq.meta.mysql.MySQLDatabase.lambda$getRoutines0$7 (MySQLDatabase.java:611)
    at java.util.LinkedHashMap.forEach (LinkedHashMap.java:721)
    at org.jooq.meta.mysql.MySQLDatabase.getRoutines0 (MySQLDatabase.java:610)
    at org.jooq.meta.AbstractDatabase.lambda$getRoutines$23 (AbstractDatabase.java:2873)
    at org.jooq.meta.AbstractDatabase.onError (AbstractDatabase.java:3795)
    at org.jooq.meta.AbstractDatabase.getRoutines (AbstractDatabase.java:2872)
    at org.jooq.codegen.JavaGenerator.generateSchemaIfEmpty (JavaGenerator.java:581)
    at java.util.stream.MatchOps$1MatchSink.accept (MatchOps.java:90)
    at java.util.ArrayList$ArrayListSpliterator.tryAdvance (ArrayList.java:1602)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:129)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:527)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:513)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:499)
    at java.util.stream.MatchOps$MatchOp.evaluateSequential (MatchOps.java:230)
    at java.util.stream.MatchOps$MatchOp.evaluateSequential (MatchOps.java:196)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.anyMatch (ReferencePipeline.java:632)
    at org.jooq.codegen.JavaGenerator.generateCatalogIfEmpty (JavaGenerator.java:571)
    at org.jooq.codegen.JavaGenerator.generate0 (JavaGenerator.java:533)
    at org.jooq.codegen.AbstractGenerator.generate (AbstractGenerator.java:191)
    at org.jooq.codegen.JavaGenerator.generate (JavaGenerator.java:222)
    at org.jooq.codegen.GenerationTool.run0 (GenerationTool.java:944)
    at org.jooq.codegen.GenerationTool.run (GenerationTool.java:244)
    at org.jooq.codegen.GenerationTool.generate (GenerationTool.java:239)
    at org.jooq.codegen.maven.Plugin.execute (Plugin.java:216)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
```

### Steps to reproduce the problem

I have a MariaDB
root pass and user
DB runinng in sql_mode=ORACLE
in application properties file
spring.jooq.sql-dialect=mariadb

```xml
<configuration>
	<!-- JDBC connection parameters -->
	<jdbc>
		<driver>${spring.datasource.driver-class-name}</driver>
		<url>${spring.datasource.url}</url>
		<user>${spring.datasource.username}</user>
		<password>${spring.datasource.password}</password>
	</jdbc>
	<!-- Generator parameters -->
	<generator>
		<database>
			<name>
				org.jooq.meta.mariadb.MariaDBDatabase
			</name>
			<includes>.*</includes>
			<excludes/>
			<inputSchema>public</inputSchema>
		</database>
		<generate>
			<pojos>true</pojos>
			<pojosEqualsAndHashCode>true</pojosEqualsAndHashCode>
			<javaTimeTypes>true</javaTimeTypes>
			<fluentSetters>true</fluentSetters>
			<!-- Generate the DAO classes -->
			<daos>false</daos>
			<!-- Annotate DAOs (and other types) with spring annotations, such as @Repository and @Autowired
for auto-wiring the Configuration instance, e.g. from Spring Boot's jOOQ starter -->
			<springAnnotations>true</springAnnotations>
			<!-- Generate Spring-specific DAOs containing @Transactional annotations -->
			<springDao>false</springDao>
			<!-- Generate the Routines class and a class for each individual routine -->
			<routines>true</routines>
			<deprecated>false</deprecated>
		</generate>
		<target>
			<packageName>jooq.dbmodel</packageName>
			<directory>src/main/java</directory>
		</target>
	</generator>
	<onError>LOG</onError>
	<onUnused>LOG</onUnused>
</configuration>
```

### jOOQ Version

3.18.5

### Database product and version

11.0.2-MariaDB-1:11.0.2+maria~ubu2204

### Java Version

open jdk 17

### OS Version

windows 11

### JDBC driver name and version (include name if unofficial driver)

org.mariadb.jdbc:mariadb-java-client:3.0.10

**Comment by lukaseder** [comment] 2023-06-30 17:26
Thanks for your report. What are you getting for these queries on your database instance?

```sql
select distinct type from mysql.proc;
select * from mysql.proc where coalesce(type, '') not in ('PROCEDURE', 'FUNCTION');
```

**Comment by ZlobniyVinya** [comment] 2023-06-30 17:37
> Thanks for your report. What are you getting for these queries on your database instance?
> 
> ```sql
> select distinct type from mysql.proc;
> select * from mysql.proc where coalesce(type, '') not in ('PROCEDURE', 'FUNCTION');
> ```
select distinct type from mysql.proc;
type
PACKAGE
PACKAGE BODY
PROCEDURE
FUNCTION

select * from mysql.proc where coalesce(type, '') not in ('PROCEDURE', 'FUNCTION');
db	name	type	specific_name	language	sql_data_access	is_deterministic	security_type	param_list	returns	body	definer	created	modified	sql_mode	comment	character_set_client	collation_connection	db_collation	body_utf8	aggregate
masdb	pg_domain	PACKAGE BODY	pg_domain	SQL	CONTAINS_SQL	NO	DEFINER	[BLOB]	[BLOB]	[BLOB]	mas@%	2023-06-30 14:15:15.000	2023-06-30 14:15:15.000	PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ORACLE,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_FIELD_OPTIONS,NO_AUTO_CREATE_USER,SIMULTANEOUS_ASSIGNMENT		utf8mb4	utf8mb4_general_ci	utf8mb4_bin	[BLOB]	NONE
masdb	pg_ml_string	PACKAGE BODY	pg_ml_string	SQL	CONTAINS_SQL	NO	DEFINER	[BLOB]	[BLOB]	[BLOB]	mas@%	2023-06-30 14:10:55.000	2023-06-30 14:10:55.000	PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ORACLE,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_FIELD_OPTIONS,NO_AUTO_CREATE_USER,SIMULTANEOUS_ASSIGNMENT		utf8mb4	utf8mb4_general_ci	utf8mb4_bin	[BLOB]	NONE

i copied one row, but we have a many stored procedures in packages

**Comment by lukaseder** [comment] 2023-06-30 18:07
Thanks for the feedback. Hmm, I see, the problem is packages, which we don't support yet in MariaDB:

- https://github.com/jOOQ/jOOQ/issues/9309

We're currently only expecting the `pg_proc.type` values that MySQL used to declare. I'll look into fixing this early next week. Even without package support, code generation obviously shouldn't fail.

**Comment by lukaseder** [comment] 2023-07-03 09:09
Fixed in versions

- 3.19.0
- 3.18.6 (https://github.com/jOOQ/jOOQ/issues/15328)
- 3.17.15 (https://github.com/jOOQ/jOOQ/issues/15329)
- 3.16.21 (https://github.com/jOOQ/jOOQ/issues/15330)

**Closed** 2023-07-03 09:09 UTC
Labels: T: Defect, C: Code Generation, P: High, R: Fixed, C: DB: MariaDB, E: All Editions

**Comment by lukaseder** [comment] 2023-07-03 09:13
It's really curious how this issue hasn't popped up yet in so many years. Probably, almost no one uses packages in MariaDB? What are you using them for? Would you like to see support for them (#9309)?

**Comment by ZlobniyVinya** [comment] 2023-07-03 13:14
> 

we have a lot of experience with oracle and when using maria db we are more accustomed to working with packages
