### ISSUE TITLE
Update statement with SQLSERVER

### ISSUE THREAD

**Issue by BaYaaN** [jOOQ/jOOQ#6479] opened 2017-08-01 13:19 UTC
Hi I receive strange error on professional trial version (3.9.5) with SQLSERVER. I would like to invoke update statement and I received erro like this:

> "error": "Internal Server Error",
    "exception": "org.springframework.jdbc.BadSqlGrammarException",
    "message": "jOOQ; bad SQL grammar [update FlightEngine.dbo.corporate_codes set (?) = (?) where id = ?]; nested exception is java.sql.SQLException: Incorrect syntax near '('.",

Generate by JOOQ sql query is invalid:

> update FlightEngine.dbo.corporate_codes set (?) = (?) where id = ?

Why UpdateSetFirstStep does not support SQLSERVER ?!

**Comment by lukaseder** [comment] 2017-08-03 08:37
Thank you very much for your report. From the generated SQL statement that you've seen in the logs, I suspect you've put a bind variable as the `UpdateSetFirstStep.set()` method's first argument, e.g. like so:

```java
DSL.using(configuration)
   .update(TABLE)
   .set(val(1), val(2))
   .where(TABLE.ID.eq(3))
   .execute();
```

Of course, this is just a guess on my side. Your statement may look differently. In order to best help you, would you mind posting the jOOQ code that you've written to get to this statement?

**Comment by lukaseder** [comment] 2017-08-23 11:15
I take that the problem was really caused by the API misuse that I've documented in my previous comment, so I'm closing this issue.

Feel free to reopen it if you think there are any further problems in jOOQ.

**Closed by lukaseder** 2017-08-23 11:15 UTC
Labels: C: Functionality, P: Medium, T: Support request
