### ISSUE TITLE
Wrong SQL generation for PostgreSQL function calls having arguments with custom data types.

### ISSUE THREAD

**Issue by vagelis-savvas** [jOOQ/jOOQ#9343] opened 2019-10-09 09:39 UTC
### Expected behavior and actual behavior:
jOOQ doesn't produce valid SQL when calling a PostgreSQL function which has an IN argument of a user-defined data type, for example when calling the f_test_func that accepts a text[], a my_type[] and a my_type we get this:

  `org.jooq.exception.DataAccessException: SQL [select "f_test_func" from "f_test_func"("words" := ?::varchar[], "my_types" := ?::.my_type[], "my_data" := row(?, ?))]; ERROR: syntax error at or near "."`

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
You can find an MCVE at https://github.com/vagelis-savvas/jOOQ-mcve
Compared to the default MCVE this one uses PostgreSQL and a modified pom.xml where a PG Docker container is used to create a schema (with Flyway) and then jOOQ Maven plugin is invoked to generate code against this schema. The integration test is then run against the running PG container. The container exposes PG over port 44444 which can be changed in pom.xml

### Versions:

- jOOQ: 3.12.1
- Java: 8 or 11
- Database (include vendor): PostgreSQL 11.5
- OS: Linux (Debian)
- JDBC Driver (include name if inofficial driver): PostgreSQL JDBC Driver 42.2.6

**Comment by knutwannheden** [comment] 2019-10-09 13:18
Thank you for your report.

The problem occurs when a user defined type is defined in the default schema (i.e. "public") or when the jOOQ code generator was set up to map the owning schema to the default schema. As a workaround you should thus be able to disable the mapping to the default schema.

The bug will be fixed in 3.13 and also backported to 3.12 for the next patch release.

**Closed** 2019-10-09 13:43 UTC
Labels: C: DB: PostgreSQL, C: Functionality, E: All Editions, P: Medium, R: Fixed, T: Defect

**Comment by vagelis-savvas** [comment] 2019-10-09 14:05
Thanx for your response.
Following your suggestion I removed the (build time) mapping to the default schema and attempted a run-time mapping. Then the custom type name is prefixed with the input schema name instead of with the output one:
`SQL [select "f_test_func" from "evcm"."f_test_func"("words" := ?::varchar[], "my_types" :=?::mcve.my_type[], "my_data" := row(?, ?))]; ERROR: function evcm.f_test_func(words => character varying[], my_types => mcve.my_type[], my_data => record) does not exist`

(where input schema is mcve and output evcm)

Maybe you have another idea for a workaround? Thank you.

**Comment by knutwannheden** [comment] 2019-10-09 14:23
No, I am afraid that this will currently not work correctly in the presence of runtime schema mappings.

In the scope of this issue we will only fix the code generation time schema mapping to the default schema. Supporting runtime schema mappings in this context is however another issue, which we will look into as part of #9347.

To me it seems like you in your case should be able to map the `mcve` schema to `evcm` in the jOOQ code generation configuration, in which case I expect the SQL to be rendered as expected:

```xml
<schema>
    <inputSchema>mcve</inputSchema>
    <outputSchema>evcm</outputSchema>
</schema>
```

**Comment by vagelis-savvas** [comment] 2019-10-10 08:41
Hello and thank you for the follow up. Unfortunately I can't hard-code the mapping because the target schema is only known at run-time (multi-tenant app). In any case I will wait for the actual patch release. May I ask if there is an ETA on the patch release? Cheers

**Comment by lukaseder** [comment] 2019-10-14 10:08
> May I ask if there is an ETA on the patch release?

I'm hoping to release 3.12.2 this week.

**Comment by vagelis-savvas** [comment] 2019-10-14 16:35
Thank you for the update, that sounds great, cheers!

**Comment by lukaseder** [comment] 2019-10-29 13:45
This fix has introduced a regression:
https://github.com/jOOQ/jOOQ/issues/7496#issuecomment-546048221

In fact, the regression is caused by another issue, which should be fixed in this case:
https://github.com/jOOQ/jOOQ/issues/7172

I won't reopen this issue here, but fix https://github.com/jOOQ/jOOQ/issues/7172 instead.

Thanks again for your report, and for maintaining your useful MCVE!
