### ISSUE TITLE
should NO table qualify if NO table alias

### ISSUE THREAD

**Issue by trydofor** [jOOQ/jOOQ#9055] opened 2019-08-17 02:09 UTC
if there is not table alias, (1) is better than (2).
```
-- (1) 
SELECT * FROM TABLE WHERE ID=?
DELETE FROM `TST_DEMO` WHERE `ID` = ?
-- (2) 
SELECT TABLE.* FROM TABLE WHERE TABLE.ID=?
DELETE FROM `TST_DEMO` WHERE `TST_DEMO`.`ID` = ?
```

AND  bad syntax if alias to Insert and Delete
### Expected behavior and actual behavior:
```kotlin
val t = TstDemoTable.TST_DEMO.`as`("t")
//val t = TstDemoTable.TST_DEMO
dsl.insertInto(t)
        .columns(t.ID,t.CREATE_DT,t.COMMIT_ID)
        .values(1L, LocalDateTime.now(),1L)
        .execute()
dsl.delete(t)
      .where(t.ID.eq(id))
      .execute()
```
**Expected** without  alias (or withou `tablename.` qulify as plain sql)
```mysql
insert into `TST_DEMO` (`ID`, `CREATE_DT`, `COMMIT_ID`) values (?, ?, ?)
delete from `TST_DEMO`  where `ID` = ?
```
**actual**
```
2019-08-17 09:59:57.930 DEBUG 12416 --- [           main] org.jooq.tools.LoggerListener            : Executing query          : 
insert into `TST_DEMO` as `t` (`ID`, `CREATE_DT`, `COMMIT_ID`) values (?, ?, ?)
delete `t` from `TST_DEMO` as `t` where `t`.`ID` = ?

....
.... without alias
....
delete from `TST_DEMO` where `TST_DEMO`.`ID` <= ?
select `TST_DEMO`.`ID` from `TST_DEMO` where `TST_DEMO`.`ID` <= ? limit ?
```
### Versions:

- jOOQ: 3.11.11
- Java: 8
- Database (include vendor): mysql 5.7
- OS:ubuntu 18.04
- JDBC Driver (include name if inofficial driver):

**Comment by trydofor** [comment] 2019-08-17 12:29
``` java
// TableFieldImpl
    @Override
    public final void accept(Context<?> ctx) {
        ctx.data(DATA_OMIT_CLAUSE_EVENT_EMISSION, true);

        if (ctx.qualify()) {
            // [#9055] should NO table qualify if NO table alias
            boolean qualify = true;
            if (table instanceof TableImpl) {
                qualify = ((TableImpl) table).alias != null;
            }
            if (qualify) {
                ctx.visit(table);
                ctx.sql('.');
            }
        }

        ctx.visit(getUnqualifiedName());
        ctx.data(DATA_OMIT_CLAUSE_EVENT_EMISSION, null);
    }
```

**Comment by lukaseder** [comment] 2019-08-19 08:01
Thank you very much for your request

> if there is not table alias, (1) is better than (2).

There are a number of reasons why this isn't true. The simplest of all would be the presence of a `JOIN` in the table expression, where an ambiguity between identical column names in joined tables would arise. There are many more.

The SQL generated by jOOQ is a bit more verbose than what would be hand written SQL. This includes, for example, the presence of table qualifications in all column references, as well as the quoting of all identifiers by default.

It is usually possible to turn these things off, but the default is to turn them on.

> Expected without alias (or withou tablename. qulify as plain sql)

It may be that the generated SQL is incorrect in some cases, e.g. when aliasing tables in DDL statements, which is not supported in all dialects. In the case of the `INSERT` statement, we already have an issue to emulate support for aliased tables: https://github.com/jOOQ/jOOQ/issues/8384

However, this limitation of an edge case does not warrant a generic fix for all queries, including `SELECT`, which would break a lot of other SQL statements that rely on the columns being fully qualified.

Given that we're going to address the current limitations of aliasing in a future release, I will close this as a duplicate of #8384 and other issues.

The workaround is to currently not alias any tables in DDL statements, if jOOQ or the underlying dialect does not support this.

**Closed by lukaseder** 2019-08-19 08:01 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect

**Comment by trydofor** [comment] 2019-08-27 09:55
Thank you for such a detailed answer.
I suggest to provide an option like `withRenderTable(false)` to toggle the default action.
for my case, the only way is make my patched jar to private maven repository.

**Comment by lukaseder** [comment] 2019-08-27 11:16
Thank you very much for your suggestion. We will consider it.

**Comment by lukaseder** [comment] 2019-10-21 08:28
Notice, we have moved the essence of the `Settings.renderTable` feature to https://github.com/jOOQ/jOOQ/issues/8893
