### ISSUE TITLE
KotlinGenerator. Variable disambiguation.

### ISSUE THREAD

**Issue by pauliusrum** [jOOQ/jOOQ#10810] opened 2020-10-28 21:19 UTC
### Expected behavior

The generator should add `this` to allow the compiler to disambiguate variable references.

### Actual behavior

The generator does not add `this` and compiler throw an error: Val cannot be reassigned.

### Steps to reproduce the problem

We have table:
```sql
CREATE TABLE `Translation` (
    `id` BINARY(16) NOT NULL,
    `translationKey` VARCHAR(255) NOT NULL,
    `language` VARCHAR(2) NULL,
    `value` text NOT NULL,
    PRIMARY KEY (`id`)
);
```

I'm using KotlinGenerator with default naming strategy.
The generator generates the following:
```kotlin
/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
class TranslationRecord() : UpdatableRecordImpl<TranslationRecord>(Translation.TRANSLATION), Record4<UUID?, String?, String?, String?> {

    // other code that is irrelevant for the problem

    override fun value4(value: String?): TranslationRecord {
        value = value // <------------ here we get an error: Val cannot be reassigned
        return this
    }
}
```

### Versions

- jOOQ: 3.14.0
- Java: 8
- Kotlin: 1.4.10
- Database (include vendor): MySQL 8

**Comment by lukaseder** [comment] 2020-10-28 21:39
Thanks for your report. Please upgrade to version 3.14.1.

Closing as duplicate of https://github.com/jOOQ/jOOQ/issues/10767

**Closed by lukaseder** 2020-10-28 21:39 UTC
Labels: C: Code Generation, C: Integration: Kotlin, E: All Editions, P: Medium, R: Duplicate, T: Defect
