### ISSUE TITLE
Using EnumConverter with jOOQ

### ISSUE THREAD

**Issue by pvorb** [jOOQ/jOOQ#11909] opened 2021-05-21 10:48 UTC
### Your question:

I'm using jOOQ's codegen Maven plugin to generate my classes for a DB schema in PostgreSQL. I also have a custom enum type in my schema, so I have a `forcedType` declaration that maps this enum to an enum class I have defined in source code.
Additionally, I have configured `<outputSchemaToDefault>true</outputSchemaToDefault>`, since there are multiple schemas with the same set of tables, types, etc. and their names are not known when running the code generation.

~~~ xml
<forcedType>
	<userType>custom.pkg.AssetStatus</userType>
	<binding>custom.pkg.AssetStatusBinding</binding>
	<includeTypes>asset_status</includeTypes>
</forcedType>
~~~

Now, if I want to use that enum in queries with jOOQ, I need to cast them explicitly, e.g.:

~~~ java
return dsl.insertInto(ASSET)
	.set(ASSET.NAME, name)
	.set(ASSET.STATUS, cast(status, ASSET.STATUS))
	.set(ASSET.FIRST_ONLINE_AT, Instant.now())
	.returning()
	.fetchOne();
~~~

Why do I need to cast the enum at all? Shouldn't this be done by the `EnumConverter`?

The generated column definition in my table looks like this:

~~~ java
public final TableField<AssetRecord, AssetStatus> STATUS = createField(DSL.name("status"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"asset_status\"").nullable(false), this, "", new EnumConverter<Object, AssetStatus>(Object.class, AssetStatus.class));
~~~

Additionally, the above statement still doesn't work because the `"public".` qualifier is still present in the cast expression, which leads to the following exception:

~~~
org.jooq.exception.DataAccessException: SQL [insert into "asset" ("name", "status", "first_online_at") values (?, cast(? as "public"."asset_status"), cast(? as timestamp(3) with time zone)) returning "asset"."id", "asset"."name", "asset"."status", "asset"."first_online_at"]; ERROR: column "status" is of type asset_status but expression is of type public.asset_status
  Hint: You will need to rewrite or cast the expression.
~~~

I configured jOOQ to not render the schema or catalog (`renderSchema=false, renderCatalog=false`).

Is there a bug somewhere in jOOQ or did I do something wrong? Any help would be appreciated.

I can work around this by implementing my own `Binding`, but still I'm wondering if this is how it should work.

### Versions:

- jOOQ: 3.14.8
- Java: AdoptOpenJDK 11.0.7.10
- Database (include vendor): PostgreSQL 12 (in the form of the TimescaleDB Docker Image `timescale/timescaledb:1.7.4-pg12`)
- OS: Ubuntu 20.04 LTS 64-bit
- JDBC Driver (include name if inofficial driver): [postgresql:42.2.19](https://search.maven.org/artifact/org.postgresql/postgresql/42.2.19/jar)

**Comment by lukaseder** [comment] 2022-03-10 10:08
I'm closing this as I can't reproduce it, currently. Sorry again for the delay. I'll be happy to look into the issue again, if I can reproduce it. Possibly, it has been resolved by some other bug fix, already.

**Closed by lukaseder** 2022-03-10 10:08 UTC
Labels: C: Functionality, C: DB: PostgreSQL, P: Medium, R: Worksforme, T: Support request, E: All Editions
