### ISSUE TITLE
Implement updated_at update column on every modification

### ISSUE THREAD

**Issue by raderio** [jOOQ/jOOQ#7746] opened 2018-08-10 09:23 UTC
Please add functionality to implement update_at at code side not database.
When a table has column `updated_at` currently we have a trigger to update this column.
Will be great if joo can detect if such column exists and add `new Date()` as value for this column on every update.

**Comment by lukaseder** [comment] 2018-08-10 10:10
Thank you very much for the suggestion. This is a duplicate of #1592

**Closed by lukaseder** 2018-08-10 10:10 UTC
Labels: C: Functionality, P: Medium, R: Duplicate, T: Enhancement
