### ISSUE TITLE
Illegal code generated for Postgres routine when in parameter name appears in result set

### ISSUE THREAD

**Issue by joewildish** [jOOQ/jOOQ#5716] opened 2016-12-20 16:42 UTC
Given a postgres function like so:

```sql
create or replace function companies
(
  company_name text default null
)
returns table
(
  company_name    text,
  incorporated_on date
)
as $$
  select company_name,
         incorporated_on
  from   company
  where  ($1 is null or company_name = $1)
  order  by company_name;
$$ language sql
;
```

The generated Java code for accessing this routine is illegal as `company_name` denotes both an in parameter and the name of a field in the result set.

A workaround is to use the Oracle-style `p_` prefix for the in parameter, and have a custom name generator strategy to produce nicely-named Java members.

**Comment by lukaseder** [comment] 2016-12-20 19:15
Thanks for your report. Hmm, this seems to be working for me (upcoming version 3.9.0-SNAPSHOT). What version are you using? Also, did you turn on/off `<tableValuedFunctions/>` in your code generator configuration?

**Comment by joewildish** [comment] 2016-12-21 08:34
Hi Lukas. Just did a quick test. Used this exact function:

```sql
create or replace function companies2
(
  company_name text default null
)
returns table
(
  company_name    text
)
as $$
  select company_name
  from   data.company
  where  ($1 is null or company_name = $1)
  order  by company_name;
$$ language sql
;
```

Get this error on a `mvn compile`:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project database-api: Compilation failure: Compilation failure:
[ERROR] /Users/joe/Development/<redacted>/Backend/database-api/target/generated-sources/jooq/<redacted>/database/administrator/routines/Companies2.java:[43,43] variable COMPANY_NAME is already defined in class <redacted>.database.administrator.routines.Companies2
[ERROR] /Users/joe/Development/<redacted>/Backend/database-api/target/generated-sources/jooq/<redacted>/database/administrator/routines/Companies2.java:[73,19] method getCompanyName() is already defined in class <redacted>.database.administrator.routines.Companies2
```

Version of jOOQ I'm using is 3.8.6. Haven't touched the `<tableValuedFunctions/>` setting (it seems to be generating code for mine without me having to explicitly say I wanted them?)

Happy to provide actual files (POMs, schemas, etc) if you're unable to replicate but would need to do so privately.

**Comment by lukaseder** [comment] 2016-12-21 08:39
OK, thanks for the feedback, @joewildish. I'll try again shortly using your exact function and 3.8.6

> (it seems to be generating code for mine without me having to explicitly say I wanted them?)

The default value for PostgreSQL is `true`. Setting this to true will treat table valued functions like tables, instead of like routines

**Comment by lukaseder** [comment] 2016-12-22 10:19
Hmm, still no avail. But I have another idea. Your function is called `companies2`. Is there also a `companies` function, and is it overloaded? Or is `companies2` overloaded? Because there *is* an issue with overloaded table-valued functions in the jOOQ code generator:
https://github.com/jOOQ/jOOQ/issues/4055

**Comment by joewildish** [comment] 2016-12-23 11:20
I used the name `companies2` as it is unique within my database, to eliminate such things as overloading confusion (obviously `companies2` is a cut-down version of a real function called `companies`). 

The only other thing that I can think of is that it resides in a schema called `admin` (as opposed to `public`, which might be where many others would create their objects). In fact I have several schemas that contain API functions (mimicking an Oracle package). There is also a `data` schema containing tables, and one or two other schemas that contain internal-only functions. I can't see how this setup would cause problems with the code generator though.

If I have time later today I will attempt to re-create the issue in a completely clean database.

**Comment by lukaseder** [comment] 2020-07-17 13:19
I haven't been able to reproduce this issue, closing as "worksforme".

Will be happy to review again should it re-appear.

**Closed by lukaseder** 2020-07-17 13:19 UTC
Labels: C: Code Generation, C: DB: PostgreSQL, P: Medium, R: Worksforme, T: Defect
