### ISSUE TITLE
Cannot insert inlined UUID value when using Policies in PostgreSQL

### ISSUE THREAD

**Issue by diastremskii** [jOOQ/jOOQ#16334] opened 2024-02-23 16:34 UTC
### Expected behavior

The query contains the correct type information and executes successfully

### Actual behavior

Query loses the types and PG fails to derive it, so the query fails to execute

### Steps to reproduce the problem

Create a test table, something like this:
```
create table sales
(
    id        int primary key not null,
    name      text not null,
    price     int  not null,
    tenant_id uuid NOT NULL
);
```

Define a tenant:
```kotlin
val tenantA = UUID.fromString("55be0301-83f5-45e6-8e1d-e902fe99dc43")
```

Add jOOQ policies on the table:

```kotlin
DefaultPolicyProvider().append(SALES, SALES.TENANT_ID.eq(tenantA))
```

Run the query that uses `.batch`, like:
```kotlin
context.batch(
            context
                .insertInto(Sales.SALES)
                .set(SalesRecord()
                    .also {
                        it.id = 100
                        it.name = "test"
                        it.price = 1
                        it.tenantId = tenantA
                    })
        ).execute()
```
it would generate and run the following query:
```sql
INSERT INTO
    "public"."sales" ("id", "name", "price", "tenant_id")
SELECT
    "t"."id",
    "t"."name",
    "t"."price",
    "t"."tenant_id"
FROM
    (
        SELECT
            100,
            'test',
            1,
            '55be0301-83f5-45e6-8e1d-e902fe99dc43'
    ) AS "t" ("id", "name", "price", "tenant_id")
WHERE
    "t"."tenant_id" = '55be0301-83f5-45e6-8e1d-e902fe99dc43';
```
that fails with the following error:
```
Caused by: org.postgresql.util.PSQLException: ERROR: column "tenant_id" is of type uuid but expression is of type text
  Hint: You will need to rewrite or cast the expression.
```

### jOOQ Version

3.19.4

### Database product and version

PostgreSQL 15.2

### Java Version

Amazon Corretto 17

### OS Version

MacOS 14.2.1

**Comment by lukaseder** [comment] 2024-02-26 15:13
Thanks a lot for your report and detailed reproduction instructions. I'll try to reproduce this, soon

**Comment by lukaseder** [comment] 2024-02-28 08:18
Are you using `preferQueryMode=simple` as well here, as with https://github.com/jOOQ/jOOQ/issues/16360 ?

**Comment by diastremskii** [comment] 2024-02-28 08:34
> Are you using preferQueryMode=simple as well here, as with https://github.com/jOOQ/jOOQ/issues/16360 ?

Nope, this one reproduces without `preferQueryMode=simple`

**Comment by lukaseder** [comment] 2024-02-28 10:29
I can reproduce the problem. Looking into it now.

**Comment by lukaseder** [comment] 2024-02-28 10:37
Interestingly, we're not casting UUID types with `SQLDialect.POSTGRES`. We probably got away with it so far because:

- When using bind values, we pass the `java.util.UUID` type to pgjdbc, which seems to know what to do with it
- When using inline values, our existing integration tests so far didn't run into such edge cases where subqueries project the type and thus lose context for automatic conversions (e.g. `INSERT INTO t (uu) VALUE ('...')` works)

Luckily, adding the cast is an easy fix as we already auto-cast quite a few other data types.

**Comment by lukaseder** [comment] 2024-02-28 10:39
This might not be strictly related to batching. The main thing that happens with batching using the batch multiple statements API is that we inline bind values. So, you could run into the same problem when using `StatementType.STATIC_STATEMENT`, or just simply an explicit inline value using `DSL.inline()`.

**Comment by lukaseder** [comment] 2024-02-28 10:40
In fact, this would also happen if you wrote the `INSERT .. SELECT` statement yourself, without an explicit cast

**Comment by lukaseder** [comment] 2024-02-28 10:41
Fixed in versions:

- 3.20.0
- 3.19.6 (https://github.com/jOOQ/jOOQ/issues/16364)
- 3.18.13 (https://github.com/jOOQ/jOOQ/issues/16365)
- 3.17.22 (https://github.com/jOOQ/jOOQ/issues/16366)

Thanks again for your report!

**Closed by lukaseder** 2024-02-28 10:41 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: Professional Edition, E: Enterprise Edition

**Comment by lukaseder** [comment] 2024-02-28 10:52
I'll add a few more integration tests for such data types in more generic usages, e.g. as in the previous issue:

```sql
select cast(value as type) -- Explicit cast here
union all
select (select value)      -- Test if auto-cast is required
```

**Comment by diastremskii** [comment] 2024-02-28 10:53
Thanks a lot for a quick resolution! 🙏

**Comment by lukaseder** [comment] 2024-02-28 11:08
As a heads-up, if you're always inlining data, you might run into this problem as well if you're inlining `NULL` literals:

- https://github.com/jOOQ/jOOQ/issues/14199

I'll increase the priority of that issue.

**Comment by lukaseder** [comment] 2024-02-29 12:01
This also affects HSQLDB:

```
org.jooq.exception.DataAccessException: SQL [select cast('f8a90c12-1542-4742-aa8f-846f59e3a226' as uuid) from (values(1)) as dual(dual) union all select (select 'f8a90c12-1542-4742-aa8f-846f59e3a226' from (values(1)) as dual(dual)) from (values(1)) as dual(dual)]; incompatible data types in combination
	at org.jooq_3.17.22-SNAPSHOT.HSQLDB.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3364)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:735)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:344)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2837)
	at org.jooq.impl.Tools.attach(Tools.java:1554)
	at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:4629)
	at org.jooq.impl.DefaultDSLContext.fetchValues(DefaultDSLContext.java:4716)
	at org.jooq.test.all.testcases.DataTypeTests.lambda$testDataType0$4(DataTypeTests.java:1741)
	at org.jooq.test.jOOQAbstractTest.withDSLContext(jOOQAbstractTest.java:2140)
	at org.jooq.test.jOOQAbstractTest.bindAndInline(jOOQAbstractTest.java:2128)
	at org.jooq.test.BaseTest.bindAndInline(BaseTest.java:1825)
	at org.jooq.test.all.testcases.DataTypeTests.testDataType0(DataTypeTests.java:1732)
	at org.jooq.test.all.testcases.DataTypeTests.testDataType_UUID(DataTypeTests.java:1728)
	at org.jooq.test.jOOQAbstractTest.testDataType_UUID(jOOQAbstractTest.java:4425)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.sql.SQLSyntaxErrorException: incompatible data types in combination
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.execute(Unknown Source)
	at org.jooq.tools.jdbc.DefaultStatement.execute(DefaultStatement.java:102)
	at org.jooq.impl.SettingsEnabledPreparedStatement.execute(SettingsEnabledPreparedStatement.java:227)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4654)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:330)
	... 46 more
Caused by: org.hsqldb.HsqlException: incompatible data types in combination
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.types.CharacterType.getAggregateType(Unknown Source)
	at org.hsqldb.types.Type.getAggregateType(Unknown Source)
	at org.hsqldb.QuerySpecification.resolveTypesPartOne(Unknown Source)
	at org.hsqldb.QueryExpression.resolveTypesPartOne(Unknown Source)
	at org.hsqldb.QueryExpression.resolve(Unknown Source)
	at org.hsqldb.ParserDQL.compileCursorSpecification(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatements(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 54 more
```

**Comment by lukaseder** [comment] 2024-02-29 12:33
And SQL Server:

```
SQL [select cast(null as uniqueidentifier) union all select (select null)]; Operand type clash: uniqueidentifier is incompatible with int
```
