### ISSUE TITLE
Sybase ASE to MySQL not working

### ISSUE THREAD

**Issue by UCFKnights83** [jOOQ/jOOQ#10604] opened 2020-09-08 15:37 UTC
I get unsupported query type when trying to convert the following query

```sql
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED    

SELECT
	al.dateadded AS 'Date Added',
	al.company_id AS 'Company ID',
	c.companyname AS 'Company Name',
	u.firstname + ' ' + u.lastname as 'User Name',
	mfd.description AS 'Search/Report Description',
	al.fname AS 'First Name',
	al.mname AS 'Middle Name',
	al.lname AS 'Last Name',
	al.dob AS 'DOB',
	al.address AS 'Address',
	al.city AS 'City',
	al.state AS 'State',
	al.zip AS 'Zip Code',
	al.zip4 AS '+4 Zip Code',
	al.phone AS 'Phone Number',
	al.business_name AS 'Business Name',
	al.reference_code AS 'Reference Code',
	al.record_count AS 'Num of Records'
FROM
	accurint_al..accounting_log_last al INNER JOIN accurint..moxie_function_desc mfd ON mfd.transaction_type = al.transaction_type
            AND mfd.function_name = al.function_name
		INNER JOIN accurint..company c ON c.companyid = al.company_id
		left outer join accurint..users u on u.loginid = al.billing_code and u.companyid = al.company_id
WHERE
	al.company_id IN (1234567)
ORDER BY
	al.dateadded
```

**Comment by lukaseder** [comment] 2020-09-09 10:14
Thank you very much for your report. We currently don't support the `database..table` identifier style that omits the default schema yet (it's in our list of known issues for the parser: https://github.com/jOOQ/jOOQ/issues/10572). The workaround for now is to manually patch these identifiers and write e.g. `accurint_al.dbo.accounting_log_last` instead of `accurint_al..accounting_log_last`.

I'm closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/10572

**Closed by lukaseder** 2020-09-09 10:14 UTC
Labels: C: Functionality, C: Parser, E: All Editions, P: Medium, T: Defect
