### ISSUE TITLE
DataTypeException: Cannot convert from false in Jooq v.3.8.2

### ISSUE THREAD

**Issue by sytolk** [jOOQ/jOOQ#5357] opened 2016-06-23 10:11 UTC
I have MySQL with maven plugin generated pojos and DAOs. With the jooq v.3.7.3 I dont have this Exceptions:
```
Caused by: org.jooq.exception.MappingException: An error ocurred when mapping record to class com.stil.generated.mysql.tables.pojos.SystemProperties
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:658)
...
Caused by:  org.jooq.exception.DataTypeException: Cannot convert from false (class java.lang.Boolean) to class com.stil.generated.mysql.tables.pojos.SystemPropertiesHistory
	at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:1113)
```

full stack trace http://pastebin.com/cditt1t8

I have use generated Dao function fetchOneByUniqueKey()
this is my tables structure
```sql
CREATE TABLE `system_properties` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sys_key` varchar(32) NOT NULL,
  `sys_value` varchar(256) DEFAULT NULL,
  `description` varchar(255) NOT NULL,
  `order_column` int(11) DEFAULT NULL,
  `history` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `key` (`sys_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `system_properties_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `users_id` int(11) DEFAULT NULL,
  `properties_id` int(11) NOT NULL,
  `datecreated` date NOT NULL,
  `new_value` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `properties_id_2` (`properties_id`,`datecreated`),
  KEY `users_id` (`users_id`),
  KEY `properties_id` (`properties_id`),
  CONSTRAINT `system_properties_history_ibfk_1` FOREIGN KEY (`properties_id`) REFERENCES `system_properties` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `system_properties_history_ibfk_2` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

maybe this is problem in jooq-codegen-maven plugin
with v.3.8.2 I have generated pojo:
```java
public class SystemProperties implements Serializable {

    private static final long serialVersionUID = -442588835;

    private Integer                 id;
    private String                  sysKey;
    private String                  sysValue;
    private String                  description;
    private Integer                 orderColumn;
    private SystemPropertiesHistory history; //this is object instead of Boolean in MySQL table structure (there is not FK) and with jooq-codegen-maven v.3.7.3 its Boolean.
}

public class SystemPropertiesHistory implements Serializable {

    private static final long serialVersionUID = -1868690069;

    private Integer   id;
    private Integer   usersId;
    private Integer   propertiesId;
    private Timestamp datecreated;
    private String    newValue;
}
```
jooq-codegen-maven config:
```xml
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>${jooq.version}</version>

                <executions>
                    <execution>
                        <id>generate-mysql</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>

                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>5.1.31</version>
                    </dependency>
                </dependencies>

                <configuration>
                    <jdbc>
                        <driver>com.mysql.jdbc.Driver</driver>
                        <url>${DB_URL}</url>
                        <user>${DB_USER}</user>
                        <password>${DB_PASS}</password>
                    </jdbc>

                    <generator>
                        <database>
                            <name>${jooq.generator.db.dialect}</name>
                            <includes>.*</includes>
                            <excludes></excludes>
                            <dateAsTimestamp>true</dateAsTimestamp>
                            <inputSchema>${DB_SCHEMA}</inputSchema>
                        </database>
                        <generate>
                            <deprecated>false</deprecated>
                            <instanceFields>true</instanceFields>
                            <records>true</records>
                            <relations>true</relations>
                            <pojos>true</pojos>
                            <daos>true</daos>
                        </generate>
                        <target>
                            <packageName>com.stil.generated.mysql</packageName>
                            <directory>target/generated-sources/jooq-mysql</directory>
                        </target>
                    </generator>
                </configuration>
            </plugin>
```

**Comment by lukaseder** [comment] 2016-06-28 07:18
Thanks a lot for your detailed report. This is a duplicate of #5334, I think. jOOQ 3.8.3 will be released this week with a fix for this regression. Sorry for the inconvenience this is causing.

**Closed by lukaseder** 2016-06-28 07:18 UTC
Labels: C: DB: MariaDB, C: DB: MySQL, C: Functionality, P: Urgent, T: Defect

**Comment by sytolk** [comment] 2016-06-28 07:53
Ok thanks I will check with Jooq v 3.8.3
