### ISSUE TITLE
ParseExceptions are being thrown when exporting DDL of a view that includes an "interval" clause

### ISSUE THREAD

**Issue by mgramin** [jOOQ/jOOQ#15236] opened 2023-06-16 09:08 UTC
### Expected behavior

I expect DDL of view:
```sql
create or replace view test_table_view as
select id, order_date + interval id day
from test_table_for_view;
```

### Actual behavior

jOOQ throws exception when try to export DDL of the view:
```java
Exception in thread "main" org.jooq.impl.ParserException: Token ')' expected: [1:141] ...la`.`test_table_for_view`.`order_date` + interval [*]`sakila`.`test_table_for_view`.`id` day) AS `order_date + interval id day` from ...
	at org.jooq.impl.DefaultParseContext.expected(ParserImpl.java:14686)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:13925)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:13920)
```

### Steps to reproduce the problem

Create a table:
```sql
create table `test_table_for_view` (
  `id` int(11) not null,
  `order_date` datetime not null,
  primary key (`id`)
);
```

Create a view:
```sql
create or replace view test_table_view as
select id, order_date + interval id day
from test_table_for_view;
```

Run this code:
```java
        Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:6000/sakila", "root", "admin");
        Configuration configuration = new DefaultConfiguration().set(conn).set(SQLDialect.MYSQL);
        Meta meta = using(configuration).meta();
        Arrays.stream(meta.filterSchemas(v -> v.getName().equalsIgnoreCase("sakila")).ddl().queries()).forEach(System.out::println);
```

### jOOQ Version

jOOQ Professional Edition 3.18.4

### Database product and version

MySQL 5.7.42

### Java Version

openjdk 17.0.2 2022-01-18

### OS Version

Microsoft Windows [Version 10.0.19044.2846]

### JDBC driver name and version (include name if unofficial driver)

mysql-connector-java:8.0.33

**Comment by lukaseder** [comment] 2023-06-16 09:14
Thanks for your report. We don't support dynamic interval expressions like this, yet

**Comment by lukaseder** [comment] 2023-06-16 09:14
Duplicate of https://github.com/jOOQ/jOOQ/issues/8792

**Closed by lukaseder** 2023-06-16 09:14 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Duplicate, E: All Editions, C: Parser

**Comment by mgramin** [comment] 2023-06-16 10:31
Thank you for your prompt response. Is there a way to export the DDL of views without parsing on the jOOQ side, if we only need the DDL script?

**Comment by lukaseder** [comment] 2023-06-16 10:54
That probably makes sense. We already have `Settings.parseMetaDefaultExpression`, which allows for opting out of parsing `DEFAULT` expressions in `CREATE TABLE`, so we could attempt this as well. It's not always obvious, because:

- Some RDBMS provide the complete source (`CREATE VIEW .. AS SELECT`) and others only the body (`SELECT`)
- If the complete source is provided, then there may be vendor specific keywords, prefixes, etc.

So, we'd have to make a heuristic and assume that the first occurrence of `AS` will be sufficient to distinguish the command from the body.

**Comment by lukaseder** [comment] 2023-06-16 10:56
I'll implement this in 2 steps:

1. A bug fix that reverts to plain SQL views in case of a parser error (backported to 3.18, 3.17, 3.16)
2. The `Settings.parseMetaViewSource` flag (only in 3.19)
