### ISSUE TITLE
Wrong precision generated for SQL Server SMALLDATETIME data type

### ISSUE THREAD

**Issue by jesset-twosigma** [jOOQ/jOOQ#11522] opened 2021-02-24 22:57 UTC
I am trying to upgrade my company from 3.13.1 to 3.14.7. We have a common pattern of taking our jooq generated code, creating an H2 database (using context.ddl(..)), and writing unit tests.

For a smalldatetime column, the jooq generated code has:
` public final TableField<MyTableRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(16).nullable(false), this, "");`

When I set my dialect to H2 and use context.ddl, the generated CREATE TABLE has:
`create table .... ( "update_time" timestamp(16) not null ) ...`

H2 fails claiming the timestamp is overly precise:
`java.sql.SQLSyntaxErrorException: precision or scale out of range in statement`
 
It appears in 3.13.1, the precision was left off. It seems there might be a difference in the precision between MSSQL (16 bytes?) and H2 (0-9 sub-second precision?)

Is this a regression? Is there a workaround? I found several related looking issues, so you may already be aware.

### Versions

- jOOQ: 3.14.7
- Java: openjdk 11.0.9.1 2020-11-04
- Database (include vendor): H2 1.4.199
- OS: Linux

**Comment by lukaseder** [comment] 2021-02-25 18:25
Thank you very much for your report. That looks like a regression indeed. A 3.14.8 release is under way, I'll delay it and try to fix this tomorrow.

**Comment by lukaseder** [comment] 2021-02-26 08:24
Looking into this now. It seems like we're poorly supporting the `smalldatetime` data type, not having covered it in integration tests yet. The type seems to be a deprecation candidate (though not yet deprecated), given the note in the documentation:
https://docs.microsoft.com/en-us/sql/t-sql/data-types/smalldatetime-transact-sql?view=sql-server-ver15

What's the reason you're using this type?

In any case, we obviously mustn't produce the wrong precision for this type.

**Comment by lukaseder** [comment] 2021-02-26 08:36
The problem is we're reading the `sys.all_columns.precision` instead of `sys.all_columns.scale` for `smalldatetime` types (unlike for the other temporal types `time`, `date`, `datetime2`, `datetimeoffset`). This should be an easy fix.

**Comment by lukaseder** [comment] 2021-02-26 08:46
Fixed in jOOQ 3.15.0 and 3.14.8 (#11534). Thanks again for your report!

**Closed by lukaseder** 2021-02-26 08:46 UTC
Labels: C: Code Generation, C: DB: SQL Server, E: Enterprise Edition, E: Professional Edition, P: High, T: Defect

**Comment by lukaseder** [comment] 2021-02-26 16:47
3.14.8 has been released with this fix included.
