### ISSUE TITLE
"Nullable" Kotlin generator is incorrect for columns with default values

### ISSUE THREAD

**Issue by atollk** [jOOQ/jOOQ#14787] opened 2023-03-14 08:45 UTC
### Expected behavior

By adding the newly introduced (https://github.com/jOOQ/jOOQ/issues/10212) kotlinNotNullRecordAttributes configuration property, I expect generated properties to have the null-correct types. 

For example, this column `username character varying(255) NOT NULL` will generate this property in the records:

```kotlin
    open var username: String
        set(value): Unit = set(8, value)
    @Nonnull
        get(): String = get(8) as String
```

or this property in the POJOs:

```kotlin
    val username: String
```

### Actual behavior

"NOT NULL" seems to be ignored if the column has a "DEFAULT" assigned to it. For example, this column `username2 character varying(255) NOT NULL DEFAULT ''` will generate this property in the records:

```kotlin
    open var username2: String?
        set(value): Unit = set(9, value)
    @Nullable
        get(): String? = get(9) as String?
```

And this property in the POJOs:

```kotlin
    val username2: String? = null
```

### Steps to reproduce the problem

Define any column with both "NOT NULL" and "DEFAULT".

[jooq_test.zip](https://github.com/jOOQ/jOOQ/files/10966293/jooq_test.zip)

### jOOQ Version

Community 3.18.0

### Database product and version

Postgres 15

### Java Version

18.0.2 (Amazon.com Inc. 18.0.2+9-FR)

### OS Version

macOS Ventura Version 13.2.1 (22D68)

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.3.3

**Comment by lukaseder** [comment] 2023-03-14 09:27
Duplicate of https://github.com/jOOQ/jOOQ/issues/14786

**Closed by lukaseder** 2023-03-14 09:27 UTC
Labels: T: Defect, C: Code Generation, P: Medium, E: All Editions

**Comment by atollk** [comment] 2023-03-14 09:50
@lukaseder So, this behavior is intended? May I ask what the thought behind this design is? It seems odd to me that a column should not be annotated as "NotNull" anymore just because it is described with further information.

**Comment by lukaseder** [comment] 2023-03-14 09:51
See https://github.com/jOOQ/jOOQ/issues/14786#issuecomment-1466469520

**Comment by lukaseder** [comment] 2023-03-14 10:04
I'll elaborate again.

The null bikeshed is as old as jOOQ itself. Everyone has opinions. No one will ever be truly happy. jOOQ has a ton of historic compromises already, one of these compromises is that when loading a POJO into a `Record`, the POJO may contain valid `NULL` values, e.g. for `ID` or defaulted columns, because well, especially the `ID` value can't be known prior to insertion if it's a surrogate key. So, the POJO contains `NULL`, and that `NULL` is going to be set explicitly on the `Record` (people don't want to expose jOOQ `Record` types outside of data access logic, even if it would resolve their problems, but the architecture wouldn't be "clean" anymore).

So, what to do with such a `NULL`? Despite the clear design of a `Record` (explicit setting the value = including it in the DML operation), we have to ignore these `NULL` values, even if set explicitly. So, we must allow users to be able to set the value of an otherwise non-`NULL` column to `NULL`.

There are other valid reasons for this, too.

**Comment by atollk** [comment] 2023-03-14 10:08
Thanks for the explanation!
