### ISSUE TITLE
Unable to fetch metadata when using a c3p0 pooled datasource

### ISSUE THREAD

**Issue by benjamin84** [jOOQ/jOOQ#6458] opened 2017-07-26 10:25 UTC
When invoking DSLContext.meta().getTables() I get an exception, when the DSLContext is constructed with a pooled datasource (in this case: c3p0).

```
Caused by: org.jooq.exception.DataAccessException: Error while accessing DatabaseMetaData
	at org.jooq.impl.MetaImpl$MetaCatalog.getSchemas(MetaImpl.java:253)
	at org.jooq.impl.MetaImpl.getSchemas(MetaImpl.java:163)
	at org.jooq.impl.MetaImpl.getTables(MetaImpl.java:173)
	at ...
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: You can't operate on a closed DatabaseMetaData!!!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getCatalogs(NewProxyDatabaseMetaData.java:3024)
	at org.jooq.impl.MetaImpl$MetaCatalog.getSchemas(MetaImpl.java:235)
	... 11 more
Caused by: java.lang.NullPointerException
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.attach(NewProxyResultSet.java:5015)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.<init>(NewProxyResultSet.java:5027)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.<init>(NewProxyResultSet.java:5039)
	at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getCatalogs(NewProxyDatabaseMetaData.java:3018)
	... 12 more
```
The problem might be, that `MetaImpl` uses the `DatabaseMetaData` Object after closing/releasing the connection:

```
    private final DatabaseMetaData meta() {
        if (meta == null) {
            ConnectionProvider provider = configuration.connectionProvider();
            Connection connection = null;

            try {
                connection = provider.acquire();
                meta = connection.getMetaData();
            }
            catch (SQLException e) {
                throw new DataAccessException("Error while accessing DatabaseMetaData", e);
            }
            finally {
                if (connection != null) {
                    provider.release(connection);
// !!!              ^ connection is closed before meta-Object is returned

                }
            }
        }

        return meta;
    }
```

I am using c3p0 0.9.5.2

**Comment by lukaseder** [comment] 2017-07-26 10:38
Thanks for reporting. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/4762, which was fixed in jOOQ 3.8 and 3.7.2 so far.

**Closed by lukaseder** 2017-07-26 10:38 UTC
Labels: C: Functionality, P: Medium, T: Defect
