### ISSUE TITLE
Error when generating code for DuckDB user defined types from non-main schema

### ISSUE THREAD

**Issue by shoffmeister** [jOOQ/jOOQ#17251] opened 2024-09-16 15:26 UTC
### Expected behavior

No code generation warning emitted by jooq when a schema-bound `TYPE` is used in DuckDB 1.1.0

### Actual behavior

Code generation warning:
```
[WARNING] SQL exception            : Exception while executing meta query: java.sql.SQLException: Catalog Error: Type with name mytype does not exist!
Did you mean "myschema.mytype"?

If you think this is a bug in jOOQ, please report it here: https://jooq.org/bug

Note you can mute some exceptions using the configuration/onError flag

---sql
create table dummy_1816872077 (
  dummy mytype
)---

[ERROR] Error while initialising type
org.jooq.exception.DataAccessException: SQL [create table dummy_1816872077 (dummy mytype)]; java.sql.SQLException: Catalog Error: Type with name mytype does not exist!
Did you mean "myschema.mytype"?
```

### Steps to reproduce the problem

```bash
rm gummiente.db
./duckdb gummiente.db 'create schema myschema; create type myschema.mytype as struct(v int); create table myschema.mytable(mt myschema.mytype);
```
then use `mvn clean compile` on
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://maven.apache.org/POM/4.0.0"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.3</version>
        <relativePath />
    </parent>

    <groupId>com.example</groupId>
    <artifactId>sample</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <jooq.codegen.duckdb.url>jdbc:duckdb:./gummiente.db</jooq.codegen.duckdb.url>
        <jooq.version>3.19.11</jooq.version>
        <duckdb.version>1.1.0</duckdb.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>${jooq.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>org.duckdb</groupId>
                        <artifactId>duckdb_jdbc</artifactId>
                        <version>${duckdb.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jdbc>
                        <driver>org.duckdb.DuckDBDriver</driver>
                        <url>${jooq.codegen.duckdb.url}</url>
                    </jdbc>
                    <generator>
                        <database>
                            <includes>.*</includes>
                            <inputSchema>myschema</inputSchema>
                            <includeExcludeColumns>true</includeExcludeColumns>
                        </database>
                    </generator>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.duckdb</groupId>
            <artifactId>duckdb_jdbc</artifactId>
            <version>${duckdb.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jooq</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>${jooq.version}</version>
        </dependency>
    </dependencies>
</project>
```

### jOOQ Version

3.19.11 OSS

### Database product and version

DuckDB 1.1.0

### Java Version

openjdk version "17.0.6" 2023-01-17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.duckdb:duckdb_jdbc:1.1.0

**Comment by shoffmeister** [comment] 2024-09-16 15:30
Something has changed on DuckDB 1.1.0 for types on schemas.

I found actually found a regression on DuckDB 1.1.0 where it will find the type even when referenced _without_ a schema (i.e. a missing error). DuckDB will find the type _with_ the schema, too, so that at least is fine. I had a cursory look at the metadata in DuckDB: it would seem as if `mytype` is always correctly scoped to `myschema` there.

I don't have a good means to work with earlier versions of DuckDB.

**Comment by lukaseder** [comment] 2024-09-17 07:18
Thanks for your report. I'll try to reproduce this.

The reason why we're doing what we're doing is because DuckDB doesn't have any good metadata on user defined types. There's `duckdb_types`, but that just returns the type name without exposing its structure.

I've already suggested improving this here:

- https://github.com/duckdb/duckdb/discussions/8832

But it's not getting any traction. Perhaps you can chime in on that discussion? Anyway, I'll look into working around this problem for 1.1.0

**Comment by lukaseder** [comment] 2024-09-17 07:26
This problem already exists with DuckDB 1.0.0

**Comment by lukaseder** [comment] 2024-09-17 07:37
I keep running into this segfault here, which prevents further investigation of UDT problems:

- https://github.com/jOOQ/jOOQ/issues/17235#issuecomment-2344029991

Will look at that, first.

**Comment by lukaseder** [comment] 2024-09-17 09:03
I can reproduce the problem and it seems the workaround would be to create the dummy table in the same schema as the type, see:

- https://github.com/duckdb/duckdb/issues/13981

**Comment by lukaseder** [comment] 2024-09-17 09:13
In 1.0.0, both cross schema and same schema references didn't work. In 1.1.0, only cross schema references don't work.

**Comment by shoffmeister** [comment] 2024-09-17 10:26
Created https://github.com/duckdb/duckdb/issues/13985 for the DuckDB cross schema defect.

**Comment by lukaseder** [comment] 2024-09-17 10:33
I've already reported this here #13981

**Comment by lukaseder** [comment] 2024-09-17 10:46
In order to support also versions prior to DuckDB 1.1.0, instead of fully qualifying the user defined type, we'll execute a `USE schema` command and avoid UDT qualification.

**Comment by lukaseder** [comment] 2024-09-17 10:52
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17253)

**Closed by lukaseder** 2024-09-17 10:52 UTC
Labels: T: Defect, C: Code Generation, P: Medium, E: All Editions, C: DB: DuckDB
