### ISSUE TITLE
DEFAULT clause in ALTER ... MODIFY statement causes error on DDLDatabase parsing

### ISSUE THREAD

**Issue by Parannarae** [jOOQ/jOOQ#11589] opened 2021-03-09 09:13 UTC
### Expected behavior
When a migration sql file contains DEFAULT clause in ALTER... MODIFY statement, it should be processed without an error.

### Actual behavior
Code generation has failed with following error:
```
ERROR org.jooq.meta.extensions.ddl.DDLDatabase - DDLDatabase Error        : Your SQL string could not be parsed or interpreted. This may have a variety of reasons, including:
- The jOOQ parser doesn't understand your SQL
- The jOOQ DDL simulation logic (translating to H2) cannot simulate your SQL

...

org.jooq.impl.ParserException: Unexpected token or missing query delimiter: [7:72] ...messages` MODIFY `mdf_dt` timestamp(6) NOT NULL [*]DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
```

### Steps to reproduce the problem
I uses `DDLDatabase` for the code generation to get the schema from sql files. Since I use flyway as an migration tool, sql files are structured as conventional `Vxxxx__some_name.sql` format.

The column that I run ALTER statement looks as follows:
```
CREATE TABLE `messages` (
   ...  
  `mdf_dt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   ...
);
```
Then when I add the following script:
```
ALTER TABLE `messages` MODIFY `mdf_dt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
```
code generation failed.

I found out that removing `DEFAULT` clause does not make any error, and I can somewhat achieve what I wanted using two different statements:
```
ALTER TABLE `messages` MODIFY `mdf_dt` timestamp(6) NOT NULL;
ALTER TABLE `messages` ALTER `mdf_dt` SET DEFAULT CURRENT_TIMESTAMP(6);
```

But as you can see, this method does not allow to add `ON UPDATE` constraint.

Just to let you know, `ALTER ... ADD` statement has no problem on adding `DEFAULT` clause:
```
ALTER TABLE `messages` ADD `some_dt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
```

### Versions

- jOOQ: 3.14.4
- Java: 11
- Database (include vendor): MySQL
- OS: MacOS
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2021-03-12 15:17
Thanks a lot for your report. Yes, we should support that, but we don't yet, see: https://github.com/jOOQ/jOOQ/issues/9247

For the time being, if our parser cannot handle some syntax, but it isn't important for the code generation, you can work around the problem by commenting out the relevant DDL section with a comment syntax that is readable by jOOQ only

```
ALTER TABLE `messages` 
  MODIFY `mdf_dt` timestamp(6) NOT NULL 
  /* [jooq ignore start] */
  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
  /* [jooq ignore stop] */
;
```

This way, when running this DDL on MySQL, it will execute as expected, but jOOQ's code generation is not aware of it. Of course, this means the generated code won't know about the `DEFAULT` expression either.

See also:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-parser/

Closing this as a duplicate of #9247

**Comment by lukaseder** [comment] 2021-03-12 15:18
Also related: https://github.com/jOOQ/jOOQ/issues/11332

**Closed by lukaseder** 2021-03-12 15:17 UTC
Labels: T: Defect
