### ISSUE TITLE
SQL Translation Error (H2, possibly Oracle)

### ISSUE THREAD

**Issue by GavinRay97** [jOOQ/jOOQ#13133] opened 2022-02-23 19:06 UTC
### SQL translator incorrectly translates this query:

```sql
select
    "h"."id",
    "h"."address",
    json_arrayagg(json_object(
        key 'users' value
            select json_arrayagg(json_object(
                key 'id' value "u"."id",
                key 'todos' value
                    select json_arrayagg(json_object(
                        key 'id' value "t"."id",
                        key 'description' value "t"."description"
                    ))
                    from "todos" as "t"
                    where "t"."user_id" = "u"."id"
            ))
            from "users" as "u"
            where "u"."house_id" = "h"."id"
    )) as "names"
from "houses" as "h"
group by "h"."id", "h"."address"
order by "h"."id"
```

### Parser output:

```sql
Token ')' expected: [6:20] ...t(
        key 'users' value
            select [*]json_arrayagg(json_object(
                key 'id' value "u"."id",
          ...
```

The query seems to work when run manually:
![image](https://user-images.githubusercontent.com/26604994/155389118-62f7ddc9-6ea3-4b5e-8131-9f7c6226bd28.png)

![image](https://user-images.githubusercontent.com/26604994/155389163-270799c6-ee23-42e2-a45d-f90ce9b4c4da.png)

**Comment by lukaseder** [comment] 2022-02-23 20:01
Thanks for your feedback. I'm not sure if that is intended to work in H2 in the first place. It doesn't seem standards compliant. This would be correct:

```sql
select json_object(
  key 'a' value (select 1), 
  key 'b' value (select 2)
)
```

As always, scalar subqueries need to be wrapped in parentheses. Without the parentheses, there are just too many ambiguities. E.g. this works:

```sql
select json_object(
  key 'a' value (select 1), 
  key 'b' value select 2
)
```

But this doesn't:

```sql
select json_object(
  key 'a' value select 1, 
  key 'b' value select 2
)
```

Let's see what H2 thinks about it: https://github.com/h2database/h2database/issues/3449. I'm reluctant to reproduce this weird parser behaviour in the jOOQ parser. It doesn't seem sound

**Comment by GavinRay97** [comment] 2022-02-23 20:06
Ahh fair enough, I thought it was a bit weird (it turns out it doesn't run on Oracle, the proper Oracle query is below)
Seems like a H2-specific quirk probably not worth working on

```sql
SELECT
    "houses"."id" AS "id",
    "houses"."address" AS "address",
    (
        SELECT
            JSON_ARRAYAGG(JSON_OBJECT(
                KEY 'id' VALUE "users"."id",
                KEY 'name' VALUE "users"."name",
                KEY 'todos' VALUE (
                    SELECT
                        JSON_ARRAYAGG(JSON_OBJECT(
                            KEY 'id' VALUE "todos"."id",
                            KEY 'description' VALUE "todos"."description"
                        ))
                    FROM
                        "todos"
                    WHERE
                        "todos"."user_id" = "users"."id"
                )
            ))
        FROM
            "users"
        WHERE
            "users"."house_id" = "houses"."id"
    ) "users"
FROM
    "houses"
GROUP BY
    "houses"."id",
    "houses"."address"
```

**Comment by lukaseder** [comment] 2022-02-24 13:04
Given the feedback on https://github.com/h2database/h2database/issues/3449, I'll close this issue here as "won't fix". I don't think it's reasonable to replicate all the edge cases this parser lenience causes, as I don't think they're predictable.

**Closed by lukaseder** 2022-02-24 13:04 UTC
Labels: T: Defect, P: Medium, R: Feedback Pending, E: All Editions, C: Parser
