### ISSUE TITLE
Wrong SQL generated when nesting predicates on subqueries projecting embeddables within MULTISET

### ISSUE THREAD

**Issue by NorbertKawinski** [jOOQ/jOOQ#16310] opened 2024-02-19 22:45 UTC
MCVE: https://github.com/NorbertKawinski/jOOQ-mcve/tree/mcve-for-issue-16310

### Expected behavior

Query runs the same way it does without using embeddables:
```
select row ("mcve"."author"."id", "mcve"."author"."name", "mcve"."author"."born") as "author", (select coalesce(jsonb_agg(jsonb_build_array("v0", "v1", "v2")), jsonb_build_array()) from (select "mcve"."book"."id" as "v0", "mcve"."book"."title" as "v1", "mcve"."book"."author_id" as "v2" from "mcve"."book" where "mcve"."book"."author_id" = (select "mcve"."author"."id" from "mcve"."author" fetch next ? rows only)) as t) from "mcve"."author"
```

### Actual behavior

org.jooq.exception.DataAccessException: 
SQL [
```
select row (row ("mcve"."author"."id"), "mcve"."author"."name", "mcve"."author"."born") as "author", (select coalesce(jsonb_agg(jsonb_build_array("v0", "v1", "v2")), jsonb_build_array()) from (select "mcve"."book"."id" as "v0", "mcve"."book"."title" as "v1", jsonb_build_array("mcve"."book"."author_id") as "v2" from "mcve"."book" where ("mcve"."book"."author_id") = (select jsonb_build_array("mcve"."author"."id") from "mcve"."author" fetch next ? rows only)) as t) from "mcve"."author"
```
]; ERROR: operator does not exist: mcve.author_id = jsonb
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.

### Steps to reproduce the problem

Enable embeddables generation:
```
<embeddableDomains>.*</embeddableDomains>
```

Create following schema:
```
CREATE DOMAIN mcve.author_id AS uuid;

CREATE TABLE mcve.author
(
--     id uuid PRIMARY KEY,
    id mcve.author_id PRIMARY KEY,
    name varchar(255) NOT NULL,
    born date
);
INSERT INTO mcve.author (id, name, born)
VALUES ('00000000-0000-0000-0000-000000000001', 'AuthorNameHere', '1234-12-24');

CREATE TABLE mcve.book
(
    id uuid PRIMARY KEY,
    title varchar(255) NOT NULL,
--     author_id uuid NOT NULL,
    author_id mcve.author_id NOT NULL,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES mcve.author (id)
);
INSERT INTO mcve.book (id, title, author_id)
VALUES ('00000000-0000-0000-0000-000000000002', 'Book1NameHere', '00000000-0000-0000-0000-000000000001');
INSERT INTO mcve.book (id, title, author_id)
VALUES ('00000000-0000-0000-0000-000000000003', 'Book2NameHere', '00000000-0000-0000-0000-000000000001');
```

Run following code:
```
    @Test
    public void mcveTest() {
        var authorIdQuery = ctx.select(AUTHOR.ID).from(AUTHOR).limit(1);

        var booksMultiset = multiset(
                selectFrom(BOOK).where(BOOK.AUTHOR_ID.eq(authorIdQuery))
        );

        var resultRecord = ctx
                .select(AUTHOR, booksMultiset)
                .from(AUTHOR)
                .fetchOne();

        var resultBooks = resultRecord.component2();
        assertEquals(2, resultBooks.size());
    }
```

### jOOQ Version

org.jooq.trial:jooq:3.19.4

### Database product and version

postgres:16.1-alpine Docker image

### Java Version

Openjdk 21.0.1

### OS Version

Microsoft Windows 11 Pro [10.0.22621 Build 22621]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by NorbertKawinski** [comment] 2024-02-19 22:47
You can find MCVE here: https://github.com/NorbertKawinski/jOOQ-mcve/tree/mcve-for-issue-16310

Note: The branch is "mcve-for-issue-16310"

**Comment by lukaseder** [comment] 2024-02-20 07:48
Thanks for your report. I will look into this soon.

**Comment by lukaseder** [comment] 2024-02-21 11:02
I can reproduce the problem with your MCVE

**Comment by lukaseder** [comment] 2024-02-21 11:25
The reason for this behaviour is that our  internal `BooleanDataKey.DATA_MULTISET_CONTENT` flag is never reset to `false` once we enter `MULTISET` content, even if it should remain true only for (nested) projection usage.

In your case, the problem arises from a `field.eq(select)` condition within a `MULTISET`. The fact that you're using embeddables is one case where a problem might appear, but there can be others, mainly whenever a `select` is used somewhere, which creates a nested projection case. But those projections are no longer related to the `MULTISET`.

While this patch here would fix your specific issue:

```patch
diff --git a/jOOQ/src/main/java/org/jooq/impl/Eq.java b/jOOQ/src/main/java/org/jooq/impl/Eq.java
index f819977..ad4c56d 100644
--- a/jOOQ/src/main/java/org/jooq/impl/Eq.java
+++ b/jOOQ/src/main/java/org/jooq/impl/Eq.java
@@ -37,6 +37,7 @@
  */
 package org.jooq.impl;
 
+import static org.jooq.impl.AbstractRowAsField.forceMultisetContent;
 import static org.jooq.impl.DSL.*;
 import static org.jooq.impl.Internal.*;
 import static org.jooq.impl.Keywords.*;
@@ -127,7 +128,7 @@
         SelectQueryImpl<?> s;
 
         if (field1Embeddable && arg2 instanceof ScalarSubquery)
-            ctx.visit(compareRowSubquery.apply(row(embeddedFields(arg1)), ((ScalarSubquery<?>) arg2).query));
+            ctx.data(DATA_MULTISET_CONTENT, false, c -> c.visit(compareRowSubquery.apply(row(embeddedFields(arg1)), ((ScalarSubquery<?>) arg2).query)));
         else if (field1Embeddable && arg2.getDataType().isEmbeddable())
             ctx.visit(compareRowRow.apply(row(embeddedFields(arg1)), row(embeddedFields(arg2))));
         else if ((op == org.jooq.Comparator.IN || op == org.jooq.Comparator.NOT_IN)
```

I'll think a bit more about other, related problems caused by the underlying issue of never resetting `DATA_MULTISET_CONTENT`. For example, it might be safe to reset it in at least *all* condition contents.

**Comment by lukaseder** [comment] 2024-02-21 12:05
For example, `NULL` predicates are also incorrect, currently:

```java
select(t.EMBEDDABLE_2).isNotNull()
```

Something like this might be generated:

```sql
where (
  select jsonb_build_array(public.t_embeddable_replacement.B, public.t_embeddable_replacement.C)
) is not null
```

This doesn't create a syntax error, but is simply never `FALSE`, even if the embeddable should be `NULL`

**Comment by lukaseder** [comment] 2024-02-21 12:24
Hmm, there's a different, related problem outside of `MULTISET` usage, which I'll fix as well:

- https://github.com/jOOQ/jOOQ/issues/16319

**Comment by lukaseder** [comment] 2024-02-21 13:04
Fixed in versions:

- 3.20.0
- 3.19.5 (https://github.com/jOOQ/jOOQ/issues/16320)
- 3.18.12 (https://github.com/jOOQ/jOOQ/issues/16321)
- 3.17.21 (https://github.com/jOOQ/jOOQ/issues/16322)

Thanks again for your report and for your excellent minimal reproducer for such a specific edge case!

**Closed by lukaseder** 2024-02-21 13:04 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: Professional Edition, E: Enterprise Edition

**Comment by NorbertKawinski** [comment] 2024-02-21 19:42
Thank you very much! ❤️
