### ISSUE TITLE
DateAdd support QUARTER and WEEK

### ISSUE THREAD

**Issue by fangniude** [jOOQ/jOOQ#12535] opened 2021-10-18 10:01 UTC
### Use case:
In PostgreSQL, add date by quarter or week 
``` sql
select
  birth_date,
  (birth_date + 1 * interval '3 month')::date add_quarter,
  (birth_date + 1 * interval '1 week')::date add_week
from
  student
```

### Possible solution you'd like to see:
``` java
DSL.dateAdd(field, DatePart.QUARTER) 
DSL.dateAdd(field, DatePart.WEEK)
```

**Comment by lukaseder** [comment] 2021-10-19 08:42
Thank you very much for your suggestion.

This is a duplicate of https://github.com/jOOQ/jOOQ/issues/8823

**Closed by lukaseder** 2021-10-19 08:42 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, R: Duplicate, E: All Editions
