### ISSUE TITLE
PARSER ERROR select case when comparing dates

### ISSUE THREAD

**Issue by fredpolicarpo** [jOOQ/jOOQ#7257] opened 2018-03-07 12:17 UTC
```java
context.parser().parseQuery("select (CASE WHEN (now() < now()) THEN 1 ELSE 0 END) as bar from foo")
```

**C42000_NO_SUBCLASS: [1:23] select (CASE WHEN (now[*]() < now()) THEN 1 ELSE 0 END) as bar from foo**

**Comment by lukaseder** [comment] 2018-03-07 12:33
Thank you very much for your report. This is a duplicate of #7237. We'll backport the fix to jOOQ 3.10.6, soon: #7239

**Closed by lukaseder** 2018-03-07 12:33 UTC
Labels: C: Functionality, P: Medium, T: Defect
