### ISSUE TITLE
I use your program and I get Indexes from Data table by  But get some fields Index I have null

### ISSUE THREAD

**Issue by ogneyar79** [jOOQ/jOOQ#14585] opened 2023-02-08 06:48 UTC
### Expected behavior

![getIndexes](https://user-images.githubusercontent.com/26259839/217451607-1c1efe4c-85be-45e6-991f-3ec9cfa0da87.png)

Actual I have Sorted Field and field there Null Ordering    equal null

![debug](https://user-images.githubusercontent.com/26259839/217453736-4cda6ce5-5bfd-4141-8462-e2181a939e02.png)

![goodresult](https://user-images.githubusercontent.com/26259839/217454927-ff130b4e-bac5-4c20-9e34-37932188b937.png)

### Actual behavior

But if I use another way to get indexes from data base, use data base language I get true and false with field Null Ordering at
Sorted Fields

![debug2](https://user-images.githubusercontent.com/26259839/217454824-be1d342e-06be-4bbf-9fa0-43444bfb52eb.png)

### Steps to reproduce the problem

![goodresult](https://user-images.githubusercontent.com/26259839/217454737-20987bfd-949e-4f11-9f74-32e3cdadde49.png)

### jOOQ Version

JOOQ 3.16.5 by gradle 

### Database product and version

image: postgres:14.1

### Java Version

openjdk version "11.0.2" 2019-01-15 and java -17

### OS Version

Linux Meant

### JDBC driver name and version (include name if unofficial driver)

'org.springframework.boot:spring-boot-starter-jooq:3.0.1' with default

**Comment by lukaseder** [comment] 2023-02-08 13:10
Thank you for your report. Can you please show the exact DDL for your table (`CREATE TABLE` with all the constraints and indexes)

**Comment by ogneyar79** [comment] 2023-02-08 13:30
![first screen](https://user-images.githubusercontent.com/26259839/217543670-16be7a7e-f946-4198-b0dc-4e115b4242b8.png)
![9s](https://user-images.githubusercontent.com/26259839/217543793-7155047a-0ac5-47d7-92b4-1c2f069452f9.png)
![8ss](https://user-images.githubusercontent.com/26259839/217543799-7939aac7-ef37-4a10-b5db-cec36a48ba00.png)
![7s](https://user-images.githubusercontent.com/26259839/217543806-092911c9-bde3-4118-8eda-02c5db9b49c8.png)
![6s](https://user-images.githubusercontent.com/26259839/217543812-55e318f0-098c-4386-80b0-90e839bfcda0.png)
![5s](https://user-images.githubusercontent.com/26259839/217543814-7c9c7323-633e-47a2-b7a0-4161cf80a0d7.png)
![4s](https://user-images.githubusercontent.com/26259839/217543820-d560d11b-7d9d-483f-86d8-46471fada8da.png)
![3s](https://user-images.githubusercontent.com/26259839/217543823-f783ba34-e834-440f-a7c9-38ae5778dc59.png)
![2s](https://user-images.githubusercontent.com/26259839/217543825-b3b7ef45-576c-48b9-9a8f-06ae72bfb008.png)

**Comment by lukaseder** [comment] 2023-02-23 09:41
Thanks for your patience.

If I understand your report correctly, you did something like:

```sql
create table x (c int);
create index i on x (c asc nulls last);
```

And since this information is reproducible with:

```sql
select 
  p.name,
  pg_index_column_has_property('public.i'::regclass, 1, p.name)
from unnest(array['nulls_first', 'nulls_last']) p(name)
```

You expect it to reproduce also with:

```java
ctx.meta().getIndexes();
```

However, that `Meta` instance is currently backed by JDBC's `DatabaseMetaData`, which does not expose this information. A quick run of:

```java
println(ctx.fetch(connection.getMetaData().getIndexInfo(null, "public", "x", false, false)));
```

Yields:

```
+---------+-----------+----------+----------+---------------+----------+----+----------------+-----------+-----------+-----------+-----+----------------+
|TABLE_CAT|TABLE_SCHEM|TABLE_NAME|NON_UNIQUE|INDEX_QUALIFIER|INDEX_NAME|TYPE|ORDINAL_POSITION|COLUMN_NAME|ASC_OR_DESC|CARDINALITY|PAGES|FILTER_CONDITION|
+---------+-----------+----------+----------+---------------+----------+----+----------------+-----------+-----------+-----------+-----+----------------+
|{null}   |public     |x         |true      |{null}         |i         |   3|               1|c          |A          |        0.0|    1|{null}          |
+---------+-----------+----------+----------+---------------+----------+----+----------------+-----------+-----------+-----------+-----+----------------+
```

So we cannot detect whether it has a `NULLS FIRST` or `NULLS LAST` flag, or uses the default. I've created a feature request for this: https://github.com/jOOQ/jOOQ/issues/14681

I'm closing this issue in favour of the other, as it will be more immediately clear what is requested there.

Thanks again

**Closed by lukaseder** 2023-02-23 09:41 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Feedback Pending, E: All Editions

**Comment by ogneyar79** [comment] 2023-02-23 15:50
Thanks a lot.
