### ISSUE TITLE
DSL.md5() documentation should mention PostgreSQL support

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#10126] opened 2020-04-27 04:34 UTC
### Expected behavior and actual behavior:
The documentation for DSL.md5() is confusing for two reasons.

1. It talks about implementing mysql-specific behavior but the implementation is not mysql-specific.
2. It does not mention PSQL support even though it does support it.

### Versions:

jOOQ: 3.13.1

**Comment by lukaseder** [comment] 2020-04-27 07:15
Thanks a lot for your report. There are a few of these Javadoc which are out of date. The mechanism is always the same:

- We implement a feature for dialects A, B, and possibly document it in Javadoc for A, B
- We then add implementations for C, D, E, overlooking Javadoc and/or manual

This has been bothering me as well, in the past, but I don't want to fix individual problems anymore. Better find a more thorough solution. I.e.

- Document each function in the manual with some details about usage: https://github.com/jOOQ/jOOQ/issues/10078
- Link to manual functions from the Javadoc
- Automate the generation of examples per dialect in a standard format for all of these functions, in both Javadoc and manual: https://github.com/jOOQ/jOOQ/issues/10127

Both of the above issues will have high prio for the next release, with possible backports to 3.13 and 3.12. With the above fixed, the `MD5()` specific problems will be addressed implicitly.

Thanks again for your report!

**Comment by lukaseder** [comment] 2020-04-27 07:15
Closing this as a duplicate of a more thorough approach: #10127

**Closed by lukaseder** 2020-04-27 07:15 UTC
Labels: T: Defect
