### ISSUE TITLE
UPDATE .. RETURNING doesn't work correctly on Derby

### ISSUE THREAD

**Issue by guss77** [jOOQ/jOOQ#6378] opened 2017-07-04 13:49 UTC
Jooq update crashes with:

```
org.jooq.exception.NoDataFoundException: Exactly one row expected for refresh. Record does not exist in database.
        at org.jooq.impl.UpdatableRecordImpl.refresh(UpdatableRecordImpl.java:345)
        at org.jooq.impl.TableRecordImpl.getReturningIfNeeded(TableRecordImpl.java:232)
        at org.jooq.impl.UpdatableRecordImpl.storeUpdate0(UpdatableRecordImpl.java:262)
        at org.jooq.impl.UpdatableRecordImpl.access$100(UpdatableRecordImpl.java:86)
        at org.jooq.impl.UpdatableRecordImpl$2.operate(UpdatableRecordImpl.java:210)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
        at org.jooq.impl.UpdatableRecordImpl.storeUpdate(UpdatableRecordImpl.java:206)
        at org.jooq.impl.UpdatableRecordImpl.update(UpdatableRecordImpl.java:156)
        at org.jooq.impl.UpdatableRecordImpl.update(UpdatableRecordImpl.java:151)
        at org.jooq.impl.DAOImpl.update(DAOImpl.java:191)
        at org.jooq.impl.DAOImpl.update(DAOImpl.java:172)
        at tech.greenfield.tests.derby.JooqTest.run(JooqTest.java:38)
        at tech.greenfield.tests.derby.JooqTest.main(JooqTest.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
```

when trying to update a record in a Derby database with an identify field (primary AI key).

See minimal test case here: https://github.com/guss77/jooq-update-crash , runs that demonstrate the error can be seen here: https://circleci.com/gh/guss77/jooq-update-crash (starting with build 3).

The problem seems to be in [`UpdatableRecordImpl::storeUpdate0`](https://github.com/jOOQ/jOOQ/blob/33d29e07e2ecea49af2d46e19531c4f96b2815f9/jOOQ/src/main/java/org/jooq/impl/UpdatableRecordImpl.java#L247) that calls `setReturningIf()` causing jOOQ to try to fetch a generated identity, though none is generated. After the update, `storeUpdate0` will try to refresh the record with the "generated ID" , but as it wasn't generated (it reads as null, then converts to an integer as 0) the fetch fails and we get an exception.

I found no workaround for this, though the same code doesn't trigger the behavior on MySQL, so I assume all this behavior is triggered only on Derby.

**Comment by lukaseder** [comment] 2017-07-04 15:55
Thanks for your report. We'll look into this shortly.

**Comment by lukaseder** [comment] 2017-07-05 09:04
Indeed, I can reproduce this with jOOQ 3.9.3, but not with 3.10-SNAPSHOT. Will look into what fixed this, and then we'll consider a patch for 3.9.4

**Comment by lukaseder** [comment] 2017-07-05 09:12
I see, this is a bit more specific than #5940, which seems to have fixed this as well. Will keep this as a separate issue to #5940, which is more of a performance problem, not a correctness one.

**Comment by lukaseder** [comment] 2017-07-05 10:23
There is also: #6222, which strikes here

**Comment by guss77** [comment] 2017-07-11 14:02
Hey, any plans to release 3.9.4 with a fix for this issue?

**Comment by lukaseder** [comment] 2017-07-12 09:05
3.9.4 will be released next week, I cannot promise the inclusion of this fix, though. You could try 3.10-SNAPSHOT (built from GitHub) to see if #5940 fixes the issue for you and then perhaps apply a patch to 3.9.x.

**Comment by Diego1977** [comment] 2017-07-18 16:47
We are experiencing same issue with MySQL -even after upgrading to JOOQ 3.9.4-; we are using HikariCP for connection pooling, and set it's configuration to AutoCommit=false because we manage Transactions with AOP interceptors (with Guice). Interceptors are working OK, transaction nesting in them is working OK, but when we insert a row in a table with Autoincremental PK we get the same exception:
```
org.jooq.exception.NoDataFoundException: Exactly one row expected for refresh. Record does not exist in database.
        at org.jooq.impl.UpdatableRecordImpl.refresh(UpdatableRecordImpl.java:345)
        at org.jooq.impl.TableRecordImpl.getReturningIfNeeded(TableRecordImpl.java:232)
        at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:208)
        at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:169)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
        at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:165)
        at org.jooq.impl.UpdatableRecordImpl.store0(UpdatableRecordImpl.java:196)
        at org.jooq.impl.UpdatableRecordImpl.access$000(UpdatableRecordImpl.java:86)
        at org.jooq.impl.UpdatableRecordImpl$1.operate(UpdatableRecordImpl.java:136)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
        at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:132)
        at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:124)
```

Our code calls store this way:
```
//RECORD is a Generic type
RECORD record = create.get().newRecord(table);
record.store();
```

**Comment by lukaseder** [comment] 2017-07-18 19:05
Yes indeed, no fix has been included in 3.9.4 yet.

**Comment by lukaseder** [comment] 2017-07-20 12:30
@Diego1977: Would you mind creating a new issue for this? I doubt it's the exact same problem. Can you please include the DDL of the table you used for this, as well as your code generation configuration?

**Comment by lukaseder** [comment] 2017-07-20 13:32
For the record, I'm still trying to reproduce this in our integration tests. I can reproduce the problem with your simple test case, but not with our test setup.

The underlying issue is that `Statement.getGeneratedKeys()` doesn't return any values in your test case, but it works correctly in our integration test suite...

**Comment by lukaseder** [comment] 2017-07-20 13:47
I see. I can reproduce it with Derby version 10.13.1.1. Our integration tests still ran with 10.12.1.1. Looks like a regression on the Derby side. Will investigate.

**Comment by lukaseder** [comment] 2017-07-20 13:57
I've created this issue here: https://issues.apache.org/jira/browse/DERBY-6952.

However, I'm not convinced that `Statement.getGeneratedKeys()` is really working well in Derby. We'll fix this through #5940

**Comment by lukaseder** [comment] 2017-07-20 14:19
I have merged #5940 on the 3.9 branch for 3.9.5 (#6437). You can build 3.9.5 already from GitHub.

I'll rename this issue to the more fundamental problem of `UPDATE .. RETURNING` not working correctly for Derby.

**Comment by guss77** [comment] 2017-07-20 15:13
Regarding the Derby issue - I would have been surprised that `getGeneratedKeys()` returned a key for an update statement - seeing as no keys are generated for an update statement.

After more research, I can see that some JDBC implementations use this JDBC API to return a list of row IDs for updated rows, instead of or in addition to supporting the SQL `RETURNING` clause. According to JDBC 4.1 section 13.16, while this is not strictly forbidden, the behavior of this is undefined and as we've learned - subject to change without notice, so I suggest not relying on UPDATE statements supporting `getGeneratedKeys()` at all, not even in driver specific implementations, unless there's absolutely no other way to support the required functionality.

**Comment by lukaseder** [comment] 2017-07-20 15:23
> Regarding the Derby issue - I would have been surprised that getGeneratedKeys() returned a key for an update statement - seeing as no keys are generated for an update statement.

That `getGeneratedKeys()` method is rather unfortunate. The JDBC API isn't clear about what should be done, and every driver implements it a bit differently. HSQLDB and Oracle, for instance, are capable of returning any generated values (not just keys) from the database - very useful for trigger-generated stuff, or other `DEFAULT` columns. DB2, Firebird, and PostgreSQL (and Oracle PL/SQL) have native `RETURNING` support, so we can bypass this `getGeneratedKeys()` method.

> as we've learned - subject to change without notice

Well, I'd definitely consider this a bug in Derby, not a change.

> unless there's absolutely no other way to support the required functionality.

That is the case much more often than you might think, I'm afraid.

But yes. The fix in #5940 will avoid the call if it isn't really needed, which of course it isn't in this case.

**Comment by lukaseder** [comment] 2021-11-10 09:50
Still no luck in Derby 10.15: https://db.apache.org/derby/docs/10.15/ref/rrefsqlj26498.html, nor is the standard SQL data change delta table supported: https://issues.apache.org/jira/browse/DERBY-6953

I'll be notified once that feature request is implemented. In the meantime, this here isn't a bug in jOOQ, so I'll close it to stop tracking it.

**Closed by lukaseder** 2021-11-10 09:50 UTC
Labels: T: Defect, C: Functionality, C: DB: Derby, P: Medium

**Comment by bourbonblue** [comment] 2025-02-04 09:05
I clarified the response



https://stackdev.space/questions/clear-all-entries-from-a-table-in-javas-derby-database
