### ISSUE TITLE
DSL.using(...).meta( ).getTables( name(tablename)) returns no result while one is expected

### ISSUE THREAD

**Issue by NLSurfMan** [jOOQ/jOOQ#15173] opened 2023-06-05 09:23 UTC
### Expected behavior

I am trying to get a Table from a connection that the user provides, based on the name. I use the meta information for that. So my first attempt was to use :
```
//connection is a plain javax.sql.Connection object, dialect is an org.joog.SQLDialect object
//tableName is a String
List<Table<?>> tables = DSL.using(connection, dialect)
   .meta()
   .getTables(name(tableName))
```
However, on MySQL this always returns zero tables, even though I know the table exists. (I haven't tried any other databases yet)

When I use the following code, the table shows up in the list:
```
List<Table<?>> tables = DSL.using(connection, dialect)
   .meta()
   .getTables()
   .stream()
   .filter(table->table.getName().equalsIgnoreCase(tableName))
   .collect(Collectors.toList());
```

The same name is used in the select-call, where it works as expected.
```
Select<Record> jooq = dslContext.select(columnFields)
   .from(table(name(tablename)))
   .where(filterConditions)
```

### Actual behavior

Jooq returns zero tables from the meta().getTables(name(tablename)) even though there should be at least one result. The same construction for the select() method works as expected. (See code example)

### Steps to reproduce the problem

1) Setup a MySQL database with one table called Blah
2) Create a column id and add a row or two
3) Run the following code:

```java
import org.jooq.SQLDialect;
import org.jooq.impl.DSL;

import java.sql.Connection;
import java.sql.DriverManager;

import static org.jooq.impl.DSL.name;

class Scratch {
    public static void main(String[] args) throws Exception {
        try (Connection connection = DriverManager.getConnection("jdbc:mariadb://127.0.0.1:3306/testdb", "root", "********")) {
            String tableName = "Blah";

            System.out.println("Finding metadata for table " + tableName);
            System.out.println(DSL.using(connection, SQLDialect.MYSQL)
                                       .meta()
                                       .getTables(name(tableName))
            );

            System.out.println("Running select * on table " + tableName);
            System.out.println(DSL.using(connection, SQLDialect.MYSQL)
                                       .selectFrom(name(tableName))
                                       .fetch()
            );
        };
    }
}
```

### jOOQ Version

jooq professional 3.17.3

### Database product and version

MySQL Server 8.0.32

### Java Version

11.0.12 (OpenJDK)

### OS Version

MS Windows 11 Professional

### JDBC driver name and version (include name if unofficial driver)

mariadb-java-client-3.1.4

**Comment by NLSurfMan** [comment] 2023-06-05 09:34
This is the output from the example code below:
```text
Finding metadata for table Blah
[]
Running select * on table Blah
+----+
|  id|
+----+
|   1|
|   2|
+----+
```

**Comment by lukaseder** [comment] 2023-06-05 09:53
Thanks a lot for your report. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/7146, and related issues.

While I can see the benefits of supporting case insensitive lookups in jOOQ's API, this isn't a simple change. Case sensitivity is highly vendor specific (and depending on the vendor, even object type specific and OS specific), so I can't promise any prioritisation of https://github.com/jOOQ/jOOQ/issues/7146

**Closed by lukaseder** 2023-06-05 09:53 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, E: All Editions

**Comment by NLSurfMan** [comment] 2023-06-05 09:59
Thanks for looking at this. 

What confuses me though, is that it works with `select()`, and not with `meta().getTables(...)`.

I've now created a helper method that does this, but it feels 'hackish': 
```java
    private Table<?> findTableByName(Connection connection, SQLDialect dialect, String tableName) {
        return getDsl(connection, dialect)
                .meta()
                .getTables()
                .stream()
                .filter(table->table.getName().equalsIgnoreCase(tableName))
                .findFirst()
                .orElse(null);
    }
```
Would you approve of this as an alternative, or is there a jOOQ setting I could use? (Keeping in mind that I am not in control of the dialect and the column name)

**Comment by lukaseder** [comment] 2023-06-05 10:04
For the record, you'll have to use the exact casing that you're getting from e.g. `information_schema.tables` or when you query the JDBC `DatabaseMetaData` directly. 

> Would you approve of this as an alternative

Sure, if you don't know the exact case of your table, then you have to use such a workaround.

> or is there a jOOQ setting I could use? (Keeping in mind that I am not in control of the dialect and the column name)

The setting you're looking for is the one from #7146, which hasn't been implemented yet.
