### ISSUE TITLE
jOOQ generates wrong refer name to enum class when using a custom GeneratorStrategy

### ISSUE THREAD

**Issue by alex-lx** [jOOQ/jOOQ#9350] opened 2019-10-10 01:51 UTC
### Expected behavior and actual behavior:
Expected: We defined a custom strategy to add a `Table` suffix for generated table class.
Actual: The generated table class name is as expected with a `Table` suffix, while the reference to enum in the table class is added a `Table` suffix, too.
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

Define a custom GeneratorStrategy for adding a `Table` suffixes for generated table class.
```java
    @Override
    public String getJavaClassName(Definition definition, Mode mode) {
        String defaultName = super.getJavaClassName(definition, mode);
        if (mode == Mode.DEFAULT) {
            return defaultName + "Table";
        }
        return defaultName;
    }
```
And we expect just the Table classes' name to be changed. However, something is wrong when dealing enum class.

enum class declare without `Table` suffix
```java
public enum TblProxyInfoType implements EnumType {
```
and its reference in pojo class has a `Table` suffix
```java
public class TblProxyInfo implements Serializable {

    private static final long serialVersionUID = 757765549;

    private String                id;
    private String                host;
    private Integer               port;
    private TblProxyInfoTypeTable type; // **note the `Table` suffix
```
and its reference in table class has a `Table` suffix
```java
    public final TableField<Record, TblProxyInfoTypeTable> TYPE = createField(DSL.name("type"), org.jooq.impl.SQLDataType.VARCHAR(6).asEnumDataType(some.package.TblProxyInfoTypeTable.class), this, "‘DIRECT’, ‘’, ‘’");

```

### Versions:

- jOOQ: 3.12.0 and 3.11.11
- Java: 1.8
- Database (include vendor): TiDB(mysql compatible)
- OS: mac os 10.14
- JDBC Driver (include name if inofficial driver): com.mysql.jdbc.Driver

**Comment by lukaseder** [comment] 2019-10-10 20:28
Thanks a lot for your report. We'll look into this shortly

**Comment by lukaseder** [comment] 2023-10-04 09:43
This might be a duplicate of https://github.com/jOOQ/jOOQ/issues/9903.

I can no longer reproduce this compilation error.

**Closed by lukaseder** 2023-10-04 09:43 UTC
Labels: T: Defect, C: Code Generation, P: Medium, E: All Editions
