### ISSUE TITLE
Trouble updating a Timestamp with jOOQ 3.11.0

### ISSUE THREAD

**Issue by WebsByTodd** [jOOQ/jOOQ#7561] opened 2018-06-09 18:46 UTC
### Expected behavior and actual behavior:
For a simple table like the following:
```
CREATE TABLE user
(
  id bigint NOT NULL,
  last_seen_at timestamp
);
```
Since updating to 3.11.0 I am having trouble updating timestamp fields using the `org.jooq.impl.UpdatableRecordImpl.update()` method
```
// update the record's lastSeen
UserRecord user = create.selectFrom(USER)
  .limit(1)
  .fetchOne();

if (user != null) {
  user.setLastSeenAt(new Timestamp(System.currentTimeMillis())); // throws an exception
  user.update();
}
```
This worked fine for me on Jooq 3.10.2

```
org.jooq.exception.DataAccessException: SQL [update "public"."user" set "last_seen_at" = cast(? as timestamp) where "public"."user"."id" = ?]; Connection is closed
	at org.jooq_3.11.0.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2380)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:737)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:364)
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate0(UpdatableRecordImpl.java:253)
	at org.jooq.impl.UpdatableRecordImpl.access$100(UpdatableRecordImpl.java:84)
	at org.jooq.impl.UpdatableRecordImpl$2.operate(UpdatableRecordImpl.java:209)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:125)
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate(UpdatableRecordImpl.java:205)
	at org.jooq.impl.UpdatableRecordImpl.update(UpdatableRecordImpl.java:155)
	at org.jooq.impl.UpdatableRecordImpl.update(UpdatableRecordImpl.java:150)
	at common.JooqTest.updateRecordTest(JooqTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:490)
	at com.sun.proxy.$Proxy23.prepareStatement(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:318)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:73)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:73)
	at org.jooq.impl.AbstractQuery.prepare(AbstractQuery.java:416)
	at org.jooq.impl.AbstractDMLQuery.prepare(AbstractDMLQuery.java:511)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322)
	... 33 more

```
### Versions:

- jOOQ: 3.11.0
- Java: 1.8.0_162
- Database (include vendor): PostGres 10.3
- OS: Mac 10.11.6 (El Capitan)
- JDBC Driver (include name if unofficial driver): org.postgresql:postgresql:42.2.2

**Comment by lukaseder** [comment] 2018-06-11 08:48
Thanks a lot for reporting this. There had been some changes to jOOQ's internals with respect to how connections are acquired and released from the `ConnectionProvider`. There should not be any regression in this area as the `ConnectionProvider` specification has not been changed.

How can this be reproduced? In particular, it will be useful to know how you're setting up your `Configuration` (including `Settings`, `ConnectionProvider`, `DataSource`, etc.)

**Comment by WebsByTodd** [comment] 2018-06-11 21:33
We're using [jooby](https://jooby.org/doc/) which sets up the configuration as follows:

https://github.com/jooby-project/jooby/blob/v1.4.0/modules/jooby-jooq/src/main/java/org/jooby/jooq/jOOQ.java#L356-L377

If that's not enough information I can try to reproduce the issue in an open source project and point you to it there.

**Comment by ciaccia** [comment] 2018-06-12 14:52
Hi all, I have just added a comment with a standalone test case to the issue #7569. It looks like this issue is not related to Timestamps at all, rather to the way connections are acquired/released from the connection pool. One of the two issues should be probably marked as duplicate.

**Comment by lukaseder** [comment] 2018-06-26 12:06
This does look indeed like #7569. I will comment there and close this as a duplicate.

**Closed by lukaseder** 2018-06-26 12:06 UTC
Labels: C: Functionality, P: High, R: Feedback Pending, T: Defect

**Comment by lukaseder** [comment] 2018-06-27 12:29
jOOQ 3.11.2 was released yesterday. Would be great if you folks could provide feedback to see if this is indeed a duplicate

**Comment by lukaseder** [comment] 2018-06-28 07:15
Cool, thanks a lot for the feedback!
