### ISSUE TITLE
Record.into(Table) uses incorrect columns when the column names are the same as a joined table

### ISSUE THREAD

**Issue by wrporter** [jOOQ/jOOQ#5512] opened 2016-08-24 22:51 UTC
Say I have an email system with 3 separate MySQL tables: `emails`, `contacts`, and `messages` where `contacts` and `messages` both share a common column name `email_id`.

Then with the following code:

``` java
Record record = create().select()
    .from(EMAILS)
    .join(CONTACTS).on(CONTACTS.EMAIL_ID.eq(EMAILS.ID))
    .fetch();

EmailsRecord email = record.into(EMAILS);
ContactsRecord contact = record.into(CONTACTS);
MessagesRecord message = record.into(MESSAGES); // should have null values
```

I would expect `EmailsRecord` and `ContactsRecord` to be populated with the values that come from the query, but `MessagesRecord` should have all `null` values. However, the actual result is that `MessagesRecord` will have `email_id` set with the value that comes from the `contacts` table.

**Comment by lukaseder** [comment] 2016-08-25 09:41
Thank you very much for reporting. Indeed, this is a known issue and it is frequently being discussed as users have found this behaviour confusing. The reason for this behaviour is that when you call `record.get(MESSAGES.SOME_COLUMN)`, you will get back the value of the "best" `SOME_COLUMN` match in the `record`. For instance, when you rename `MESSAGES` to `MESSAGES.as("m")`, you still want to be able to fetch  `SOME_COLUMN` from it. When you nest your `MESSAGES` table in a deep tree of derived tables, but still select `SOME_COLUMNS` throughout your SQL statement, you still want `MESSAGES.SOME_COLUMN` to be a valid reference for that `SOME_COLUMN` column.

The unfortunate side effect of this feature is that sometimes, you may see "accidental", unexpected matches. In other words, once you have a `Result` or a `Record`, jOOQ has no knowledge of the original query that produced this result, and it's impossible to know for jOOQ what you really meant when you look for columns from the `MESSAGES` table in your `Record`...

I hope this helps.

**Comment by lukaseder** [comment] 2016-08-25 09:42
Thank you very much for reporting. Indeed, this is a known issue and it is frequently being discussed as users have found this behaviour confusing. The reason for this behaviour is that when you call `record.get(MESSAGES.SOME_COLUMN)`, you will get back the value of the "best" `SOME_COLUMN` match in the `record`. For instance, when you rename `MESSAGES` to `MESSAGES.as("m")`, you still want to be able to fetch  `SOME_COLUMN` from it. When you nest your `MESSAGES` table in a deep tree of derived tables, but still select `SOME_COLUMNS` throughout your SQL statement, you still want `MESSAGES.SOME_COLUMN` to be a valid reference for that `SOME_COLUMN` column.

The unfortunate side effect of this feature is that sometimes, you may see "accidental", unexpected matches. In other words, once you have a `Result` or a `Record`, jOOQ has no knowledge of the original query that produced this result, and it's impossible to know for jOOQ what you really meant when you look for columns from the `MESSAGES` table in your `Record`...

I hope this helps.

**Comment by mniederkofler** [comment] 2017-06-12 09:41
Hi Lukas,
ran into a similar issue with the following query.

```
DSL.using(ds, SQLDialect.ORACLE11G)
                     select().from(MDC_OPERATION)
				.innerJoin(MDC_ORDER).onKey()
				.innerJoin(MST_ITEMS).onKey()
				.innerJoin(MST_MACHINE).onKey()
                                ...
```

When trying to fetch a record for a table which is not part of the select (for dynamic mapping reasons), I would have expected the .into function to return null.

```
MstWorkcentersRecord entity = record.into(MST_WORKCENTERS);
if (entity != null)
```

Instead it tries to construct the values from the other tables which is at least unexpected. 
Tried it with:
```
.into(MstWorkcenters.MST_WORKCENTERS)
.into(MstWorkcentersRecord.class)
.into(MstWorkcenters.MST_WORKCENTERS).into(MstWorkcentersRecord.class)
```

Could we modify the behaviour to at least return null when the fetched class is not part of the select?

**Comment by lukaseder** [comment] 2017-06-15 12:50
> When trying to fetch a record for a table which is not part of the select (for dynamic mapping reasons), I would have expected the .into function to return null.

That would be a different issue than this one here. In any case, your expectations wouldn't work out because the use-case behind this `into()` method is transforming a record selected from a table `A` into a record type of a table (or view!) `B`, which is "similar" to `A`, meaning that it has at least partially the same column names. Imagine `A` being the "original" table and `B` being the backup table of `A`

Unless you have a `TableRecord`, you should not assume that a `Record` has anything to do with a particular table. That's not how SQL works. SQL uses projections (`SELECT` clause) which allows you to project arbitrary expressions, such as `FIRST_NAME || LAST_NAME`, and rename those expressions to arbitrary column names.

> Instead it tries to construct the values from the other tables which is at least unexpected.

I certainly understand the surprise here, but the behaviour is consistent with the entire jOOQ API. That being:

- Your source record has a set of fields (possibly ambiguous)
- Your target record type has a set of fields (regardless if you define that type with individual fields or with a table)
- Now, the only reasonable mapping between source and target is the mapping that considers matching field names.

> Could we modify the behaviour to at least return null when the fetched class is not part of the select?

No, `into()` will never return null. While you find the existing behaviour unexpected (understandably after your joins), the change would be even more unexpected to many.

Perhaps there's a hidden use-case I'm missing and perhaps there's a new feature that we could add, but right now, I don't have the full picture of what you're really trying to achieve. Would you mind creating a new issue, or better, discuss this on the [user group](https://groups.google.com/forum/#!forum/jooq-user)?

**Comment by lukaseder** [comment] 2017-07-24 13:04
Closing this issue as the API works as designed.

**Closed by lukaseder** 2017-07-24 13:04 UTC
Labels: C: Functionality, P: Medium, R: Worksforme, T: Defect
