### ISSUE TITLE
`DSL.row` in H2 renames fields

### ISSUE THREAD

**Issue by atollk** [jOOQ/jOOQ#13849] opened 2022-08-12 09:51 UTC
The `DSL.row` function when used with an H2 database causes fields to change their name. That means e.g. you can't use `Table.fieldsRow()` in combination with `Record.into` because none of the fields will be found.

### Expected behavior
`dsl.select(CHATS.fieldsRow()).from(CHATS).fetch().first().value1()["ID"]`
->
`4960c447-2e70-4c43-a921-671e03e6ebb3`

### Actual behavior
`dsl.select(CHATS.fieldsRow()).from(CHATS).fetch().first().value1()["ID"]`
->
`Field (ID) is not contained in Row (  "row.ID",  "row.CHAT_DELETED",  "row.CREATED_AT",  "row.UPDATED_AT")`

`dsl.select(CHATS.fieldsRow()).from(CHATS).fetch().first().value1()["row.ID"]`
->
`4960c447-2e70-4c43-a921-671e03e6ebb3`

### Steps to reproduce the problem
Create any table with at least one column and one row in an H2 database (in the example above, table `chats` with column `chats.id`) and run the above query.

### Versions

- jOOQ: 3.16.5
- Kotlin: 1.6.20
- Database (include vendor): H2 2.1.214
- OS: Linux 5.18.16-arch1-1

**Comment by lukaseder** [comment] 2022-08-15 08:33
Thanks a lot for your report.

When you create a `ROW` of those fields, then you're effectively nesting the fields into a nested data structure. The synthetic name arises from the fact that a field within that row is no longer a top level field. The exact name is not really specified, and currently used for internals only (like all the names of expressions).

Did you perhaps intend to just use `CHATS.fields()`? What's the use-case of using this access pattern?

**Comment by atollk** [comment] 2022-08-16 10:06
Hi, thanks for the response.
I realize that keeping the field names is not guaranteed by specification but it's the natural expectation in my opinion. I also found that for some database implementations, Postgres for example, it works like I expected. I guess you could argue then that it's more of a feature request rather than a bug report.

The use case is (in my case) to select from two tables at once, like so:
```kotlin
DSL
    .select(CHATS.fieldsRow(), CHATMEMBERS.fieldsRow())
    /* from, join, ... */
    .fetch()
    .map { record ->
        val chatsRecord = record.value1().into(CHATS)
        val chatmembersRecord = record.value2().into(CHATMEMBERS)
    }
```

Using `Table.fields()` or `Table.asterisk()` gives you a generic `Record` object rather than the specific and type-safe `Record2` you get from my example.

**Comment by lukaseder** [comment] 2022-08-31 07:52
> The use case is (in my case) to select from two tables at once, like so:

Starting from jOOQ 3.17, why not just write:

```java
DSL
    .select(CHATS, CHATMEMBERS)
    /* from, join, ... */
    .fetch()
    .map { record ->
        val chatsRecord = record.value1() // .into(CHATS)
        val chatmembersRecord = record.value2() // .into(CHATMEMBERS)
    }
```

The `.into(Table)` calls are no longer required. See: https://www.jooq.org/doc/latest/manual/sql-building/table-expressions/tables-as-selectfield/

**Comment by lukaseder** [comment] 2022-08-31 08:03
I've just noticed that this API usage depends on this flag being set: `<recordsImplementingRecordN>true</recordsImplementingRecordN>`

Without it, the `fieldsRow()` method returns `Row`, rather than `RowN`, and as such, doesn't profit from the row being projectable. I think that's a limitation worth fixing: https://github.com/jOOQ/jOOQ/issues/13938

I'll look into your original request shortly.

**Comment by lukaseder** [comment] 2022-08-31 08:16
Never mind https://github.com/jOOQ/jOOQ/issues/13938, it's not possible to implement, see https://github.com/jOOQ/jOOQ/issues/13938#issuecomment-1232613517

**Comment by lukaseder** [comment] 2022-08-31 08:33
I'm curious about this take here:

> Postgres for example, it works like I expected.

That's not how I understand it. If you write:

```sql
select (r).* 
from (
  select row(id, title)
  from t_book
) t (r);
```

Then the output looks something like this:

```
|f1 |f2          |
|---|------------|
|1  |1984        |
|2  |Animal Farm |
|3  |O Alquimista|
|4  |Brida       |
```

The nested record's column names aren't maintained this way. You maybe had this in mind, where you nest the record using PostgreSQL's table notation syntax:

```sql
select (r).* 
from (
  select t_book
  from t_book
) t (r);
```

And now, you're getting the original column names. In any case, I don't think the renaming is the issue here, per se. The issue you're requesting is to allow for accessing nested column aliases (of nested records or not) via partial path expressions.

For example, there's a historic feature where you could name your columns like this:

```java
List<P> result =
ctx.select(BOOK.ID.as("x.y.id"))
   .from(BOOK)
   .fetchInto(P.class);
```

And define:

```java
record Y (int id) {}
record X (Y y) {}
record P (X x) {}
```

Now by convention, the mapping as implemented by `DefaultRecordMapper` would work as expected. Your expectation here is to be able to refer to the column in the record by `"x.y.id"`, `"y.id"`, or `"id"`, as if the column had a qualified name.

Indeed, all of this is more of a feature request than a bug. I've created a new issue describing the feature request a bit more in detail, without the distraction of the nested name being generated incidentally by `fieldsRow()`, which should be irrelevant to your actual feature: https://github.com/jOOQ/jOOQ/issues/13939

Thanks again for bringing this up. Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/13939

**Closed by lukaseder** 2022-08-31 08:33 UTC
Labels: T: Defect, C: Functionality, C: DB: PostgreSQL, P: Medium, E: All Editions
