### ISSUE TITLE
Select from  DSLContext#innerJoin() produces incorrect results when no match

### ISSUE THREAD

**Issue by rtomsick** [jOOQ/jOOQ#5352] opened 2016-06-18 20:36 UTC
# Description

When obtaining the results from a `DSLContext#leftJoin()`, the `Record#get()` appears to produce incorrect data in cases where the right table contains no matching values.
# Steps to reproduce

My query code looks like this:

```
this.ctx().selectFrom(DSL.table("data").as("d")
                         .leftJoin(EXTENDED_DATA_TABLE.as("e"))
                         .on(DSL.field(DSL.name("d", "id"))
                                     .eq(DSL.field(DSL.name("e", "id")))))
          .where(DSL.field(DSL.name("d", "id"), UUID.class).in(ids))
          .fetch( <fn goes here> )
```

This generates the following query:

```
select *
from data as "d"
  left outer join extended_data as "e"
  on "d"."id" = "e"."id"
where (
  "d"."id" in (
    <omitted>
  )
))
```

The mapping function in question contains this line:

`final UUID edID = r.get(DSL.name("e", "id"), UUID.class);`

Now the problem is that even when the resulting Record contains a null value for the `id` column of `extended_data` (i.e. no match), the above code produces a value, specifically the `id` column of `data`.  This makes it impossible to determine if there was a match by checking for `null` values of `e.id` (although in this particular case, other columns can be used.

A glance at the console reveals a warning about an ambiguous column name when doing `final UUID id = r.get(DSL.name("d", "id"), UUID.class)`.  This makes me question whether DSL#name() is working as described.  However, since the `DSL.table(..).as("foo")` pattern doesn't appear to work with `r.get(DSL.field("foo.id"))` in this case, I'm sort of at a loss.

This seems to me to be a bug, or at the very least a severe mismatch between the documentation and what actually happens.  Either that, or I'm reading the docs wrong.  (Hey, it happens. ;) )

Please let me know if you need additional information to reproduce.

**Comment by lukaseder** [comment] 2016-06-28 13:13
Thank you very much for your detailed report. This is a bit unfortunate indeed. There are a couple of effects that play into this situation: You're not telling jOOQ what columns will be returned and jOOQ cannot figure out the columns because they're not available from your table objects (as you're using `DSL.table(Name)`). This means that jOOQ will generate an asterisk and will have to deal with whatever information is delivered by the JDBC driver's `ResultSetMetaData`. It may be that your database doesn't deliver the table name, or it delivers the table name and the schema name. In both cases, jOOQ cannot resolve the "exact" match on your call to `r.get(Name)` and will return any `id` field's value.

**Comment by lukaseder** [comment] 2016-06-28 13:14
What database are you using?

**Comment by rtomsick** [comment] 2016-06-28 16:18
Database is Postgres 9.5, but IIRC it's the same for at least >= 9.2.  (I haven't tried others outside that range.)

In light of the above I'd suggest that (ideally):

1) The documentation be updated to explain this behavior and the requirements for it to work as expected (since it is somewhat unintuitive why this happens, although logical once you think about it.)

2) jOOQ fail with some form of exception when the above code is executed.  The rational here is that the user intent is clear (retrieve the "id" column of the table "d"), but the behavior is subtly incorrect (really *any* "id" column is returned).  The current behavior is logical if no table prefix is provided, however given the use of `DSL.name("d", "id")` it could be reasonably expected that any value returned matches "d.id", and not "*.id".  I'd argue that the latter behavior is never correct and should be treated as an outright bug.

It should be possible to detect when insufficient information is available and throw an exception, and IMHO a hard failure is better than a wrong but perhaps plausible-looking result.

Thanks!
-R

**Comment by lukaseder** [comment] 2022-09-16 13:37
Stumbled upon this issue again. There are several parts:

- Improving the documentation. I agree, this should be done, and will be done via: https://github.com/jOOQ/jOOQ/issues/13995
- Changing behaviour: This is impossible in a backwards compatible way, and I reckon things will simply be different, not better (they may be better for you, but worse for others, who appreciate the current behaviour)

I've explained the current behaviour a few times (and will again, in the Javadoc added via #13995). There are pros to the current behaviour as much as there are pros to failing fast.

Since there is nothing "incorrect" being produced here, I'm closing this as won't fix and duplicate of https://github.com/jOOQ/jOOQ/issues/13995

**Closed by lukaseder** 2022-09-16 13:37 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
