### ISSUE TITLE
Forced type config need to be added for postgres citext

### ISSUE THREAD

**Issue by sourav-jha** [jOOQ/jOOQ#12660] opened 2021-11-25 09:00 UTC
### Expected behavior
Without adding forced type, citext field is getting converted to object type instead of string.
### Actual behavior
citext field should be string.
### Steps to reproduce the problem
* Add extension citext.
* Create a table with one of the column of type citext.
* maven plugin conf: 
` <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>3.14.1</version>
                
                 <executions>
                   <execution>
                     <goals>
                       <goal>generate</goal>
                     </goals>
                   </execution>
                 </executions>
                <configuration>
                    
                    <jdbc>
                        <driver>org.postgresql.Driver</driver>
                        <url>jdbc:postgresql://localhost:5432/sampl</url>
                        <user>postgres</user>
                        <password>postgres</password>
                    </jdbc>
                    
                    <generator>
                        <database>
                            <name>org.jooq.meta.postgres.PostgresDatabase</name>
                            <includes>.*</includes>
                            <inputSchema>public</inputSchema>
                            <forcedTypes>
                            <forcedType>
                                <name>CLOB</name>
                                <includeExpression>.*\.column1</includeExpression>
                            </forcedType>

                         
                        </database>
                        <target>
                            <packageName>com.sample.datastore.jooq.codegen</packageName>
                            <directory>src/main/java</directory>
                        </target>
                        <generate>
                            <pojos>true</pojos>
                        </generate>
                    </generator>
                </configuration>
            </plugin>`

### Versions

- jOOQ: 3.14.1
- Java: Java 11
- Database (include vendor): Postgres
- OS: mac OS 11.2.3
- JDBC Driver (include name if inofficial driver): Postgres

**Comment by lukaseder** [comment] 2021-11-25 09:04
Duplicate of https://github.com/jOOQ/jOOQ/issues/5934

**Closed by lukaseder** 2021-11-25 09:04 UTC
Labels: T: Defect, C: Code Generation, P: Medium, R: Duplicate, E: All Editions
