### ISSUE TITLE
 jOOQ's code generator generate uncompilable classes on 3.9.0

### ISSUE THREAD

**Issue by kirys** [jOOQ/jOOQ#5912] opened 2017-02-25 08:36 UTC
Since 3.9.0 the code generation create not compilable classes.

this is caused because some elements have a _ suffix when declared while don't have it when accessed.

this doesn't happen with 3.8.6

e.g.:
```
/*
 * This file is generated by jOOQ.
*/
package com.gasce.dbmodel.accounts;


import com.gasce.dbmodel.accounts.tables.Accounts;
import com.gasce.dbmodel.accounts.tables.AuditTrail;
import com.gasce.dbmodel.accounts.tables.records.AccountsRecord;
import com.gasce.dbmodel.accounts.tables.records.AuditTrailRecord;
import com.gasce.dbmodel.registry.tables.records.ServersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>accounts</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AccountsRecord, Long> IDENTITY_ACCOUNTS_ = Identities0.IDENTITY_ACCOUNTS_;
    public static final Identity<AuditTrailRecord, Long> IDENTITY_AUDIT_TRAIL = Identities0.IDENTITY_AUDIT_TRAIL;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountsRecord> PKACCOUNTS = UniqueKeys0.PKACCOUNTS;
    public static final UniqueKey<AuditTrailRecord> PKAUDIT_TRAIL = UniqueKeys0.PKAUDIT_TRAIL;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AuditTrailRecord, AccountsRecord> AUDIT_TRAIL__FK_AUDIT_TRAIL_ACCOUNTS = ForeignKeys0.AUDIT_TRAIL__FK_AUDIT_TRAIL_ACCOUNTS;
    public static final ForeignKey<AuditTrailRecord, ServersRecord> AUDIT_TRAIL__FK_AUDIT_TRAIL_SERVERS = ForeignKeys0.AUDIT_TRAIL__FK_AUDIT_TRAIL_SERVERS;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AccountsRecord, Long> IDENTITY_ACCOUNTS = createIdentity(Accounts.ACCOUNTS_, Accounts.ACCOUNTS_.ACCOUNT_ID);
        public static Identity<AuditTrailRecord, Long> IDENTITY_AUDIT_TRAIL = createIdentity(AuditTrail.AUDIT_TRAIL, AuditTrail.AUDIT_TRAIL.ATID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AccountsRecord> PKACCOUNTS = createUniqueKey(Accounts.ACCOUNTS_, "pkaccounts", Accounts.ACCOUNTS_.ACCOUNT_ID);
        public static final UniqueKey<AuditTrailRecord> PKAUDIT_TRAIL = createUniqueKey(AuditTrail.AUDIT_TRAIL, "pkaudit_trail", AuditTrail.AUDIT_TRAIL.ATID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<AuditTrailRecord, AccountsRecord> AUDIT_TRAIL__FK_AUDIT_TRAIL_ACCOUNTS = createForeignKey(com.gasce.dbmodel.accounts.Keys.PKACCOUNTS, AuditTrail.AUDIT_TRAIL, "audit_trail__fk_audit_trail_accounts", AuditTrail.AUDIT_TRAIL.EXECUTOR_ACCOUNT);
        public static final ForeignKey<AuditTrailRecord, ServersRecord> AUDIT_TRAIL__FK_AUDIT_TRAIL_SERVERS = createForeignKey(com.gasce.dbmodel.registry.Keys.PKSERVERS, AuditTrail.AUDIT_TRAIL, "audit_trail__fk_audit_trail_servers", AuditTrail.AUDIT_TRAIL.SERVER);
    }
}

```
in  Identities0 the var is declared a IDENTITY_ACCOUNTS
and then is accesed this way:
    public static final Identity<AccountsRecord, Long> IDENTITY_ACCOUNTS_ = Identities0.IDENTITY_ACCOUNTS_;

Bye
K.

**Comment by lukaseder** [comment] 2017-02-25 21:47
Thank you very much for reporting.

Just to be sure this isn't perhaps a duplicate of https://github.com/jOOQ/jOOQ/issues/5786. Have you tried jOOQ 3.9.1 as well?

If that doesn't help, could you perhaps provide the DDL of your tables to help reproduce the issue, along with your code generator configuration and what database you're using.

**Comment by lukaseder** [comment] 2017-04-26 15:22
Thus far, I couldn't reproduce this issue. Feel free to reopen if you have further instructions for reproduction.

**Closed by lukaseder** 2017-04-26 15:22 UTC
Labels: C: Code Generation, P: Medium, T: Defect
