### ISSUE TITLE
java.lang.ClassCastException with org.postgresql:r2dbc-postgresql:1.0.0.RELEASE

### ISSUE THREAD

**Issue by newzubakhin** [jOOQ/jOOQ#14261] opened 2022-11-19 12:04 UTC
### Actual behavior

Trying to execute update/insert queries with the latest r2dbc-postgresql produces java.lang.ClassCastException.

Most probably it's because [this PR](https://github.com/pgjdbc/r2dbc-postgresql/issues/484)  was included to the last r2dbc pg driver release. 

### Steps to reproduce the problem

Use 1.0.0.RELEASE of org.postgresql:r2dbc-postgresql and try to execute update/insert query

```kotlin
    val dsl = DSL.using(connectionFactiory)
    val result = Mono.from(dsl
        .update(NOTIFICATION)
        .set(NOTIFICATION.ID, UUID.randomUUID())
        .where(DSL.falseCondition())
    ).awaitSingle()
```

### jOOQ Version

3.17.5

### Database product and version

Postgres 12

### Java Version

17

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:r2dbc-postgresql:1.0.0.RELEASE

**Comment by lukaseder** [comment] 2022-11-21 07:33
Thanks for your report. We do not yet support R2DBC 1.0, see https://github.com/jOOQ/jOOQ/issues/13565. The main reason is that not all drivers have implemented the 1.0 version of the SPI yet, and as you've noticed, there might be incompatibilities.

We'll very likely support 1.0 starting from jOOQ 3.18

**Comment by lukaseder** [comment] 2022-11-21 07:34
Duplicate of https://github.com/jOOQ/jOOQ/issues/13565

**Closed by lukaseder** 2022-11-21 07:33 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by lukaseder** [comment] 2023-01-12 07:54
Just to confirm jOOQ 3.18 now supports R2DBC 1.0: https://github.com/jOOQ/jOOQ/issues/13565
