### ISSUE TITLE
Postgres GENERATED AS IDENTITY support

### ISSUE THREAD

**Issue by viartemev** [jOOQ/jOOQ#8990] opened 2019-07-26 15:00 UTC
### Use case:
PostgreSQL version 10 introduced a new feature called `GENERATED AS IDENTITY` constraint that allows you to automatically assign a unique value to a column. The GENERATED AS IDENTITY constraint is the SQL standard-conforming variant of the PostgreSQL’s SERIAL column. [Link](https://www.postgresql.org/docs/10/sql-createtable.html)
Currently, all records with this feature don't extend from org.jooq.UpdatableRecord.

### Possible solution you'd like to see:
GENERATED AS IDENTITY is used as a primary key, accordingly, all records with this field should be implementations of org.jooq.UpdatableRecord.

### Versions:

- jOOQ: 3.11.11
- Java: 12
- Database (include vendor): Postgres
- OS: MacOS
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.1.4

**Comment by lukaseder** [comment] 2019-07-26 15:13
Thanks a lot for your request. We'll support this feature in the near future: #6659

Closing this as a duplicate of #6659

**Comment by viartemev** [comment] 2019-07-26 15:13
Thanks! Sorry, I didn't find the original issue :(

**Closed by lukaseder** 2019-07-26 15:13 UTC
Labels: C: DB: PostgreSQL, C: Functionality, E: All Editions, P: Medium, T: Enhancement

**Comment by lukaseder** [comment] 2019-07-26 15:16
> Thanks! Sorry, I didn't find the original issue :(

No problem at all :) Issues having duplicates is a good sign for an issue getting more popular.

> GENERATED AS IDENTITY is used as a primary key, accordingly, all records with this field should be implementations of org.jooq.UpdatableRecord.

Do note that even with #6659 implemented, this is not sufficient: An identity and a primary key are two distinct things. Technically, there is no requirement for an identity to be unique, even if that is a weird thing to allow. But I have seen weird things :)

In order to profit from `UpdatableRecord`, I recommend you *still* add primary keys to your identity columns.

Or, you could configure synthetic primary keys:
https://www.jooq.org/doc/3.11/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-synthetic-primary-keys/

Using programmatic code generator configuration (or in 3.12 using SQL to generate the regular expression), you could collect all identity columns explicitly and produce a regular expression to match them all in this synthetic primary key configuration.

I hope this helps

**Comment by lukaseder** [comment] 2019-07-26 15:17
... there's also a synthetic identity configuration: https://www.jooq.org/doc/3.11/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-synthetic-identities/
