### ISSUE TITLE
onConflict with returning

### ISSUE THREAD

**Issue by kbalyasnikov** [jOOQ/jOOQ#5897] opened 2017-02-21 10:42 UTC
Didn't find a way to build a query with `on conflict` followed by `returning`:

`on conflict(shop_id, lower(external_id)) do nothing RETURNING id`

This is a part of valid Postgres query.

**Comment by lukaseder** [comment] 2017-02-22 10:02
Thanks for reporting. This is a well-known limitation that already pre-existed in the MySQL syntax `ON DUPLICATE KEY UPDATE`, which currently doesn't support the `RETURNING` clause.

We should definitely support this. Closing this issue as a duplicate of : https://github.com/jOOQ/jOOQ/issues/2123

**Closed by lukaseder** 2017-02-22 10:02 UTC
