### ISSUE TITLE
JOOQ Parsing Fails for BITWISE And for postgres

### ISSUE THREAD

**Issue by moovon** [jOOQ/jOOQ#14813] opened 2023-03-20 05:27 UTC
### Expected behavior

While parsing a SQL

with a select statement like this in Aurora Postgres

`case when (column1 & 64) <> 0 then 1 else 0 end`

Error 
```
`Caused by: org.jooq. imply.ParserException: Token ')' 
    case when (column1 [*]& 64) <> 0 then 1 else 0 end 
```

### Actual behavior

Parsing should be success

### Steps to reproduce the problem

write a SQL with bitwise AND..

and parse the SQL with 

```
parser().parseSelect(customSQL)
```

### jOOQ Version

3.17.5

### Database product and version

PostGres

### Java Version

jdk 11

### OS Version

MAC

**Comment by lukaseder** [comment] 2023-03-20 07:21
Thanks for your report. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/14683.

The problem at this point is ot find a way to correctly handle the disagreement about operator precedence among all the SQL dialects and encode that in a more powerful version of the parser. See:

- https://github.com/jOOQ/jOOQ/issues/12339
- https://github.com/jOOQ/jOOQ/issues/14683

**Closed by lukaseder** 2023-03-20 07:21 UTC
Labels: T: Defect, P: Medium, R: Duplicate, E: All Editions, C: Parser

**Comment by lukaseder** [comment] 2023-03-20 07:23
Note, I don't think there's a good workaround short of patching the parser right now. While `ParseListener` can be used to extend the parser to parse additional `Field` expressions:
https://www.jooq.org/doc/latest/manual/sql-building/sql-parser/sql-parser-listener/

... it cannot be reasonably used for operators, without compromising on operator precedence.

**Comment by lukaseder** [comment] 2023-03-20 07:51
See also: https://stackoverflow.com/q/75784518/521799
