### ISSUE TITLE
Check @Support annotation on WithStep#mergeInto() methods

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9180] opened 2019-09-06 12:43 UTC
Currently the `WithStep#mergeInto()` methods, corresponding to a `WITH ... MERGE INTO` CTE, only declare support for SQL Server. At least also H2 appears to support this syntax: http://www.h2database.com/html/commands.html#with.

Alternatively these methods should possibly also be `@Pro` annotated.

Please also note that in the OSS edition these methods are annotated as `@Supported({})`, which is wrong, as it means *all* dialects support this syntax.

**Comment by katzyn** [comment] 2019-09-07 03:58
Please note that current BNF grammar on website is incomplete, actually both [non-standard](https://h2database.com/html/commands.html#merge) and [standard](https://h2database.com/html/commands.html#merge_using) `MERGE` statement are supported.

CTEs are still experimental in H2, however, and they have some known issues.

**Comment by lukaseder** [comment] 2021-11-09 13:53
Duplicate of https://github.com/jOOQ/jOOQ/issues/9318

**Closed by lukaseder** 2021-11-09 13:53 UTC
Labels: T: Enhancement, C: Functionality, C: DB: H2, P: Medium, E: All Editions
