### ISSUE TITLE
Exception in MetaImpl when encountering string literal default expressions in MariaDB 10.1

### ISSUE THREAD

**Issue by cstamas** [jOOQ/jOOQ#15762] opened 2023-10-26 10:41 UTC
### Your question

We upgraded MariaDB JDBC driver from 2.7.9 to 3.2.0 (along with jOOQ update from 3.18.6 to 3.18.7) while remote DB is ancient MariaDB 10.1 w/ DDL deployed, and started seeing these "harmless" exceptions logged by jOOQ:

```
2023-10-25 17:08:57,014+0000 INFO [jetty-main-1] *SYSTEM org.jooq.impl.MetaImpl - Cannot parse default expression: 0000-00-00 00:00:00
org.jooq.impl.ParserException: Unexpected content after end of field input: [1:12] 0000-00-00 [*]00:00:00
	at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:14720)
	at org.jooq.impl.DefaultParseContext.done(ParserImpl.java:14906)
	at org.jooq.impl.DefaultParseContext.lambda$parseField0$7(ParserImpl.java:1001)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:14913)
	at org.jooq.impl.DefaultParseContext.parseField0(ParserImpl.java:1001)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:844)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:839)
	at org.jooq.impl.MetaImpl$MetaTable.initColumns(MetaImpl.java:1210)
	at org.jooq.impl.MetaImpl$MetaTable.<init>(MetaImpl.java:799)
	at org.jooq.impl.MetaImpl$MetaSchema.lambda$getTables$2(MetaImpl.java:487)
	at org.jooq.impl.Tools.map(Tools.java:2451)
	at org.jooq.impl.MetaImpl$MetaSchema.getTables(MetaImpl.java:458)
	at org.jooq.impl.MetaImpl.lambda$getTables0$2(MetaImpl.java:294)
	at org.jooq.impl.Tools.flatMap(Tools.java:2466)
	at org.jooq.impl.MetaImpl.getTables0(MetaImpl.java:294)
	at org.jooq.impl.AbstractMeta.lambda$initTables$4(AbstractMeta.java:181)
	at org.jooq.impl.AbstractMeta.get(AbstractMeta.java:371)
	at org.jooq.impl.AbstractMeta.initTables(AbstractMeta.java:181)
	at org.jooq.impl.AbstractMeta.getTables(AbstractMeta.java:167)
	at org.jooq.impl.AbstractMeta.getTables(AbstractMeta.java:162)
...
```

This happens at marked line in code:

```
    private void mayExecuteDDL(final Configuration configuration) {
        DSLContext context = DSL.using(configuration);
  >>>  if (context.meta().getTables(Tables.STORAGE_ITEM_V3.getName()).isEmpty()) {
            checkArgument(configuration.dialect() == SQLDialect.H2, "Auto DDL allowed only on embedded H2!");
            context.ddl(Public.PUBLIC, new DDLExportConfiguration().createSchemaIfNotExists(true))
                    .executeBatch();
            log.debug("DDL executed");
        }
    }
```

(we "auto-create" tables only when running in "embedded H2" mode, in prod MariaDB DDL/tables are deployed).

This is the DDL of `STORAGE_ITEM_V3` table:
```
DROP TABLE IF EXISTS `storage_item_v3`;

CREATE TABLE `storage_item_v3` (
  `itemKey` varchar(40) NOT NULL,
  `parentKey` varchar(40) NOT NULL,
  `providerKey` varchar(40) NOT NULL,
  `version` varchar(40) NOT NULL, 
  `container` varchar(255) NOT NULL,
  `path` varchar(4096) NOT NULL,
  `contentSize` bigint,
  `contentId` varchar(5000),
  `itemType` varchar(40) NOT NULL,
  `metadata` text NOT NULL,
  PRIMARY KEY (`itemKey`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE INDEX `storage_item_v3_parentKey` on `storage_item_v3`(`parentKey`);
```

So, what does `Unexpected content after end of field input: [1:12] 0000-00-00 [*]00:00:00` actually mean here?

### jOOQ Version

3.18.7

### Database product and version

MariaDB 10.1

### Java Version

21.0.1-zulu

### OS Version

Linux

### JDBC driver name and version (include name if unofficial driver)

org.mariadb.jdbc.Driver 3.2.0 + HikariCP 5.1.0

**Comment by lukaseder** [comment] 2023-10-26 12:27
I'm afraid I cannot reproduce this with your instructions. We have a template to create fully self contained reproducers here, if this helps: https://github.com/jOOQ/jOOQ-mcve.

Note, you can turn off this parsing with `Settings.parseMetaDefaultExpressions`, in case of which the default expression is just retrieved as a plain SQL template.

**Comment by cstamas** [comment] 2023-10-26 13:05
Here it is https://github.com/jOOQ/jOOQ-mcve/pull/36

Console is full of:
```
15:03:03,659  INFO [org.jooq.impl.MetaImpl                            ] - Cannot parse default expression: 0000-00-00 00:00:00
org.jooq.impl.ParserException: Unexpected content after end of field input: [1:12] 0000-00-00 [*]00:00:00
	at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:14720) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.DefaultParseContext.done(ParserImpl.java:14906) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.DefaultParseContext.lambda$parseField0$7(ParserImpl.java:1001) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:14913) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.DefaultParseContext.parseField0(ParserImpl.java:1001) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:844) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:839) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.MetaImpl$MetaTable.initColumns(MetaImpl.java:1210) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.MetaImpl$MetaTable.<init>(MetaImpl.java:799) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.MetaImpl$MetaSchema.lambda$getTables$2(MetaImpl.java:487) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.Tools.map(Tools.java:2451) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.MetaImpl$MetaSchema.getTables(MetaImpl.java:458) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.MetaImpl.lambda$getTables0$2(MetaImpl.java:294) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.Tools.flatMap(Tools.java:2466) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.MetaImpl.getTables0(MetaImpl.java:294) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.AbstractMeta.lambda$initTables$4(AbstractMeta.java:181) ~[jooq-3.18.7.jar:?]
	at org.jooq.impl.AbstractMeta.get(AbstractMeta.java:371) [jooq-3.18.7.jar:?]
	at org.jooq.impl.AbstractMeta.initTables(AbstractMeta.java:181) [jooq-3.18.7.jar:?]
	at org.jooq.impl.AbstractMeta.getTables(AbstractMeta.java:167) [jooq-3.18.7.jar:?]
	at org.jooq.impl.AbstractMeta.getTables(AbstractMeta.java:162) [jooq-3.18.7.jar:?]
	at org.jooq.mcve.test.java.mysql.JavaTest.mcveTest(JavaTest.java:79) [test-classes/:?]

```

**Comment by lukaseder** [comment] 2023-10-26 13:21
Thanks a lot. I'll look into it right away.

**Comment by lukaseder** [comment] 2023-10-26 13:38
Note, you can also filter tables like this, to omit the system tables in your query, which will also be faster:

```java
context.meta()
       .filterSchemas(...)
       .filterTables(...)
       .getTables(Tables.STORAGE_ITEM_V3.getName())
```

**Comment by cstamas** [comment] 2023-10-26 14:20
Agreed, MariaDB 10.1 is really ancient (and EOL 3+ years), no need to act on this. We will try to push for DB upgrade.

**Comment by lukaseder** [comment] 2024-12-20 14:10
So, this issue already disappears on MariaDB 10.2! I'll fix it for 10.1 because it's an easy fix, but I suspect you've already upgraded your RDBMS instance.

**Comment by lukaseder** [comment] 2024-12-20 14:11
Fixed in versions:

- 3.20.0
- 3.19.17 (https://github.com/jOOQ/jOOQ/issues/17795)
- 3.18.24 (https://github.com/jOOQ/jOOQ/issues/17796)
- 3.17.33 (https://github.com/jOOQ/jOOQ/issues/17797)

**Comment by cstamas** [comment] 2024-12-20 14:11
Yup yup, many thanks!

**Closed by lukaseder** 2024-12-20 14:11 UTC
Labels: T: Defect, C: Functionality, P: Medium, C: DB: MariaDB, E: Professional Edition, E: Enterprise Edition
