### ISSUE TITLE
[Multiset + MySQL] No Converter found for types org.jooq.Converters$UnknownType and java.util.Set

### ISSUE THREAD

**Issue by JayAhn2** [jOOQ/jOOQ#12389] opened 2021-09-03 03:56 UTC
### Expected behavior
I got the below error when I try to map multiset result to DTO. As I assume, it is related to wrapping `priceHistories`'s child with `[]` instead of `{}`.

```
No Converter found for types org.jooq.Converters$UnknownType and java.util.Set
```

### Actual behavior
generated SQL
```sql
SET @t = @@group_concat_max_len;
SET @@group_concat_max_len = 4294967295;
SELECT `ecommerce`.`product`.`id`,
       `ecommerce`.`product`.`active`,
       `ecommerce`.`product`.`name`,
       `ecommerce`.`product`.`description`,
       `ecommerce`.`product`.`sku`,
       `ecommerce`.`product`.`vendor_id`,
       `ecommerce`.`product`.`category_id`,
       `ecommerce`.`product`.`price`,
       (SELECT COALESCE(JSON_MERGE_PRESERVE('[]',
                                            CONCAT('[', GROUP_CONCAT(JSON_ARRAY(`v0`, `v1`, `v2`, `v3`) SEPARATOR ','),
                                                   ']')), JSON_ARRAY())
        FROM (SELECT DISTINCT `ecommerce`.`product_price_history`.`id`         AS `v0`,
                              `ecommerce`.`product_price_history`.`price`      AS `v1`,
                              `ecommerce`.`product_price_history`.`started_at` AS `v2`,
                              `ecommerce`.`product_price_history`.`ended_at`   AS `v3`
              FROM `ecommerce`.`product_price_history`
              WHERE `ecommerce`.`product_price_history`.`product_id` =
                    `ecommerce`.`product`.`id`) AS `t`)                                              AS `priceHistories`,
       (SELECT COALESCE(JSON_MERGE_PRESERVE('[]',
                                            CONCAT('[', GROUP_CONCAT(JSON_ARRAY(`v0`, `v1`, `v2`) SEPARATOR ','), ']')),
                        JSON_ARRAY())
        FROM (SELECT DISTINCT `ecommerce`.`related_product`.`id`                 AS `v0`,
                              `ecommerce`.`related_product`.`related_product_id` AS `v1`,
                              `ecommerce`.`related_product`.`relevance_score`    AS `v2`
              FROM `ecommerce`.`related_product`
              WHERE `ecommerce`.`related_product`.`product_id` =
                    `ecommerce`.`product`.`id`) AS `t`)                                              AS `relatedProducts`
FROM `ecommerce`.`product`
WHERE `ecommerce`.`product`.`id` = 181948386763603968;
SET @@group_concat_max_len = @t;;
```
ResultSet Log
```
|-------------------|-------|-------------|----------------------|-----------------|----------|------------|-------|------------------------------------------------------------------|----------------|
|id                 |active |name         |description           |sku              |vendor_id |category_id |price  |pricehistories                                                    |relatedproducts |
|-------------------|-------|-------------|----------------------|-----------------|----------|------------|-------|------------------------------------------------------------------|----------------|
|181948386763603968 |1      |Nike Force 1 |It is really good one |SKU-20304-234123 |124251234 |1231412     |120.90 |[[181948386763603969, 120.9, "2021-09-03 03:46:20.000000", null]] |[]              |
|-------------------|-------|-------------|----------------------|-----------------|----------|------------|-------|------------------------------------------------------------------|----------------|
```
Error log
```
org.jooq.exception.DataTypeException: No Converter found for types org.jooq.Converters$UnknownType and java.util.Set
	at org.jooq.impl.Tools.converterOrFail(Tools.java:1217) ~[jooq-3.15.2.jar:na]
	at org.jooq.impl.Tools.converterOrFail(Tools.java:1226) ~[jooq-3.15.2.jar:na]
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:351) ~[jooq-3.15.2.jar:na]
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.set(DefaultRecordMapper.java:1146) ~[jooq-3.15.2.jar:na]
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.mapNonnested(DefaultRecordMapper.java:1137) ~[jooq-3.15.2.jar:na]
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:1124) ~[jooq-3.15.2.jar:na]
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:610) ~[jooq-3.15.2.jar:na]
	at org.jooq.impl.AbstractRecord.into(AbstractRecord.java:804) ~[jooq-3.15.2.jar:na]
	at org.jooq.impl.ResultQueryTrait.fetchOneInto(ResultQueryTrait.java:530) ~[jooq-3.15.2.jar:na]
```
Query
```kotlin
    override fun fetchById(id: Long): ProductDto {
        return ctx.select(
            product.ID,
            product.ACTIVE,
            product.NAME,
            product.DESCRIPTION,
            product.SKU,
            product.VENDOR_ID,
            product.CATEGORY_ID,
            product.PRICE,
            multiset(
                selectDistinct(
                    priceHistory.ID,
                    priceHistory.PRICE,
                    priceHistory.STARTED_AT,
                    priceHistory.ENDED_AT
                ).from(priceHistory)
                    .where(priceHistory.PRODUCT_ID.eq(product.ID))
            ).`as`("priceHistories")
                .convertFrom { it.into(ProductPriceHistoryDto::class.java) },
            multiset(
                selectDistinct(
                    relatedProduct.ID,
                    relatedProduct.RELATED_PRODUCT_ID,
                    relatedProduct.RELEVANCE_SCORE,
                ).from(relatedProduct)
                    .where(relatedProduct.PRODUCT_ID.eq(product.ID))
            ).`as`("relatedProducts")
                .convertFrom { it.into(RelatedProductDto::class.java) },
        )
            .from(product)
            .where(product.ID.eq(id))
            .fetchOneInto(ProductDto::class.java)
            ?: throw RecordNotFoundException("Product is not found by id: $id")
    }
```

DTO
```kotlin
data class ProductDto(
    val id: Long,
    val active: Boolean,
    val name: String,
    val description: String?,
    val sku: String,
    val vendorId: Long,
    val categoryId: Long,
    val price: BigDecimal,
    @JsonSetter(nulls = Nulls.AS_EMPTY)
    val priceHistories: Set<ProductPriceHistoryDto>,
    @JsonSetter(nulls = Nulls.AS_EMPTY)
    val relatedProducts: Set<RelatedProductDto>

)

data class ProductPriceHistoryDto(
    val id: Long,
    val price: BigDecimal,
    val startedAt: String,
    val endedAt: String?
) {
}

data class RelatedProductDto(
    val id: Long,
    val relatedProductId: Long,
    val relevanceScore: BigDecimal
)

```
### Versions

- jOOQ: 3.15.2
- Java: Open JDK 1
- Database (include vendor): MySQL
- OS: Mac
- JDBC Driver (include name if inofficial driver): 8.0.26

**Comment by lukaseder** [comment] 2021-09-03 08:14
Thanks for report. The problem seems to be related to your usage of the classic reflective record mapping. A key advantage of the multiset approach is to be able to use reflection free, functional mapping, which should work out of the box, e.g. if you replace your lambdas by these:

```kotlin
// ...
{ it.intoSet(Records.mapping(::ProductPriceHistoryDto)) }
// ...
{ it.intoSet(Records.mapping(::RelatedProductDto)) }
// ...
.fetchOne(Records.mapping(::ProductDto))
```

Have you tried this? Meanwhile, I'll investigate the reflection mapping issue. The `List` to `Set` conversion should not cause any trouble.

**Comment by lukaseder** [comment] 2021-09-03 08:23
Yeah, it's the same issue as this one: https://github.com/jOOQ/jOOQ/issues/12208. The reflective mappings don't work well yet, when deeply nesting multisets.

But again, using reflection here is risky (it already was, before). Thanks to the new `MULTISET` and `MULTISET_AGG` operators, you can now bring type safety to your entire tree mapping logic, so better use it.

**Comment by lukaseder** [comment] 2021-09-03 08:23
Duplicate of https://github.com/jOOQ/jOOQ/issues/12208

**Comment by lukaseder** [comment] 2021-09-03 09:00
Looking at this more closely, the problems are related, but not strictly the same thing. It would have been the same thing if you had written:

```kotlin
{ it.intoSet { it.into(ProductPriceHistoryDto::class.java) } }
```

This also doesn't work yet (and will be fixed with #12208), but you didn't write that. i.e. you didn't convert the nested `Result<?>` into a set explicitly, but you tried to rely on the implicit conversion of `Result` to `Set`. That would require a new feature: https://github.com/jOOQ/jOOQ/issues/12390

That new feature risks breaking existing reflection code in subtle ways, so I won't backport it. The fix for #12208 will be backported to 3.15.3.

Thanks again.

**Closed by lukaseder** 2021-09-03 09:00 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by JayAhn2** [comment] 2021-09-03 09:37
@lukaseder So the below would work in the fix?
 ```kotlin
    override fun fetchById(id: Long): ProductDto {
        return ctx.select(
            product.ID,
            product.ACTIVE,
            product.NAME,
            product.DESCRIPTION,
            product.SKU,
            product.VENDOR_ID,
            product.CATEGORY_ID,
            product.PRICE,
            multiset(
                selectDistinct(
                    priceHistory.ID,
                    priceHistory.PRICE,
                    priceHistory.STARTED_AT,
                    priceHistory.ENDED_AT
                ).from(priceHistory)
                    .where(priceHistory.PRODUCT_ID.eq(product.ID))
            ).`as`("priceHistories")
                .convertFrom { it.intoSet(it.into(ProductPriceHistoryDto::class.java)) },
            multiset(
                selectDistinct(
                    relatedProduct.ID,
                    relatedProduct.RELATED_PRODUCT_ID,
                    relatedProduct.RELEVANCE_SCORE,
                ).from(relatedProduct)
                    .where(relatedProduct.PRODUCT_ID.eq(product.ID))
            ).`as`("relatedProducts")
                .convertFrom { it.intoSet(it.into(RelatedProductDto::class.java)) },
        )
            .from(product)
            .where(product.ID.eq(id))
            .fetchOneInto(ProductDto::class.java)
            ?: throw RecordNotFoundException("Product is not found by id: $id")
    }
```
currenctly I'm getting this syntax error. 
![image](https://user-images.githubusercontent.com/25868002/131984541-4e08e9c2-9f21-44ab-82c9-2ec23efc3601.png)

The below doesn't work as well with this error.
```kotlin
    override fun fetchById(id: Long): ProductDto {
        return ctx.select(
            product.ID,
            product.ACTIVE,
            product.NAME,
            product.DESCRIPTION,
            product.SKU,
            product.VENDOR_ID,
            product.CATEGORY_ID,
            product.PRICE,
            multiset(
                selectDistinct(
                    priceHistory.ID,
                    priceHistory.PRICE,
                    priceHistory.STARTED_AT,
                    priceHistory.ENDED_AT
                ).from(priceHistory)
                    .where(priceHistory.PRODUCT_ID.eq(product.ID))
            ).`as`("priceHistories")
                .convertFrom { it.intoSet(Records.mapping(::ProductPriceHistoryDto)) },
            multiset(
                selectDistinct(
                    relatedProduct.ID,
                    relatedProduct.RELATED_PRODUCT_ID,
                    relatedProduct.RELEVANCE_SCORE,
                ).from(relatedProduct)
                    .where(relatedProduct.PRODUCT_ID.eq(product.ID))
            ).`as`("relatedProducts")
                .convertFrom { it.intoSet(Records.mapping(::RelatedProductDto)) },
        )
            .from(product)
            .where(product.ID.eq(id))
            .fetchOne(Records.mapping(::ProductDto))
            ?: throw RecordNotFoundException("Product is not found by id: $id")
    }
```
![image](https://user-images.githubusercontent.com/25868002/131984697-21c8cc68-eb00-4eef-bbe4-5eb7afae3c77.png)
![image](https://user-images.githubusercontent.com/25868002/131984729-64094ea6-cd76-44a1-9745-f074c6ea7c02.png)

**Comment by lukaseder** [comment] 2021-09-03 09:49
Look closely.

```kotlin
// Correct
{ it.intoSet { it.into(ProductPriceHistoryDto::class.java) } }

// Wrong
{ it.intoSet(it.into(ProductPriceHistoryDto::class.java)) }
```

If you're using the `KotlinGenerator`, then the second error is because you have to make all of your DTO attributes nullable, see discussion here: https://github.com/jOOQ/jOOQ/issues/12347

If not (given you have those `T!` types in the error), perhaps there's a type inference error because kotlin can't infer the correct return type for `fetchOne` in your `?:` expression?
