### ISSUE TITLE
JPADatabase should throw Hibernate's exceptions when there is anything going wrong with the SchemaExport

### ISSUE THREAD

**Issue by javiercj93** [jOOQ/jOOQ#17274] opened 2024-09-19 06:06 UTC
### Your question

I've tried to follow the documentation [here](https://www.jooq.org/doc/latest/manual/code-generation/codegen-jpa/), however, I was unable to make it work and I could not find any working example.
What I am trying to achieve is simple, I want to generate jooq code based on jpa entities. 

In a multimodule project I've created an entitties module which contains a single entity:
```
@Entity
@Table(name = "entity_a")
public class EntityA {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "name")
    private String name;

    @Column(name = "description")
    private String description;

    @Column(name = "value")
    private Integer value;
}
```

Then in my application module, I've added the following plugin configuration:
```
<plugin>
      <groupId>org.jooq</groupId>
      <artifactId>jooq-codegen-maven</artifactId>
      <version>3.19.11</version>
      <dependencies>
        <dependency>
          <groupId>com.javier</groupId>
          <artifactId>entities</artifactId>
          <version>${project.version}</version>
        </dependency>
      </dependencies>
      <executions>
        <execution>
          <goals>
            <goal>generate</goal>
          </goals>
          <configuration>

            <!-- Generator configuration -->
            <generator>
              <!-- Database schema -->
              <database>
                <name>org.jooq.meta.extensions.jpa.JPADatabase</name>
                <includes>.*</includes>
                <properties>
                  <!-- Set packages to scan for JPA entities -->
                  <property>
                    <key>packages</key>
                    <value>com.javier.entities</value>
                  </property>

                  <!-- Explicitly set Hibernate dialect -->
                  <property>
                    <key>hibernate.dialect</key>
                    <value>org.hibernate.dialect.PostgreSQLDialect</value>
                  </property>

                  <!-- Use attribute converters if necessary -->
                  <property>
                    <key>useAttributeConverters</key>
                    <value>true</value>
                  </property>

                  <!-- Unqualified schema handling -->
                  <property>
                    <key>unqualifiedSchema</key>
                    <value>none</value>
                  </property>
                </properties>
              </database>

              <!-- Target package and directory -->
              <target>
                <packageName>com.javier.application.generated</packageName> <!-- Set your desired package name -->
                <directory>src/main/java</directory>
              </target>
              <generate>
                <pojos>true</pojos>
                <daos>true</daos>
              </generate>

              <!-- Define the strategy for generating DTOs and DAOs -->
              <strategy>
                <name>org.jooq.codegen.DefaultGeneratorStrategy</name>
              </strategy>
            </generator>
          </configuration>
        </execution>
      </executions>
    </plugin>
```

When I run it, I can see the following:
```
[INFO] Entities added           : Number of entities added: 1
```

But then nothing is generated, could I get a link to an example or something I could use as a reference? The following examples in a similar issue does not seem available anymore:
```
https://github.com/etiennestuder/gradle-jooq-plugin/issues/194#issuecomment-959044176
```

### jOOQ Version

3.19.11

### Database product and version

mysql8

### Java Version

openjdk v17

**Comment by lukaseder** [comment] 2024-09-19 08:50
Thanks for your message. Could you please provide the complete `INFO` log output

**Comment by javiercj93** [comment] 2024-09-19 17:43
It did not work either without
```
<property>
  <key>hibernate.dialect</key>
  <value>org.hibernate.dialect.PostgreSQLDialect</value>
</property>
```

**Comment by lukaseder** [comment] 2024-09-20 07:27
I'm afraid I don't see what could be the problem. I cannot reproduce any such issue with our integration tests. Can you provide a more complete reproducer, e.g. based on our template here? https://github.com/jOOQ/jOOQ-mcve

If that's too much effort, some other troubleshooting ideas:

- Turn on debug logging on both jOOQ and Hibernate
- Turn on SQL logging in Hibernate to check if it actually exports anything at all
- Use `mvnDebug` to step into the `JPADatabase` and check if the in-memory H2 database is really populated correctly

**Comment by javiercj93** [comment] 2024-09-20 08:45
Thanks for the support @lukaseder, really appreciate it.

I have recreated an example based on the provided templates (I've removed all the other modules and left just an entity module + the "generator" module.

```
[INFO] Entities added           : Number of entities added: 2
Sep 20, 2024 10:37:46 AM org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
Sep 20, 2024 10:37:46 AM org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
Sep 20, 2024 10:37:47 AM org.hibernate.tool.hbm2ddl.SchemaExport execute
INFO: HHH000227: Running hbm2ddl schema export
Sep 20, 2024 10:37:47 AM org.hibernate.jpa.internal.util.LogHelper logPersistenceUnitInformation
INFO: HHH000204: Processing PersistenceUnitInfo [name: AttributeConverterExtractor]
Sep 20, 2024 10:37:47 AM org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
Sep 20, 2024 10:37:47 AM org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator initiateService
INFO: HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
[INFO] License parameters       

```


This time I added a second entity (EntityB)

Please let me know if you are able to replicate on your side and apologies because it is probably some misconfiguration on my side.

Link to example -> https://github.com/javiercj93/jOOQ-mcve

**Comment by lukaseder** [comment] 2024-09-20 09:40
Thanks for the reproducer. I can see how nothing is generated, will investigate.

**Comment by lukaseder** [comment] 2024-09-20 09:44
Using a debugger, right after the Hibernate export command, I can see that no tables have been added to the in-memory H2 database. Only the `INFORMATION_SCHEMA` is present:

![image](https://github.com/user-attachments/assets/ba131647-ac85-4663-9198-803056e8de7a)

**Comment by lukaseder** [comment] 2024-09-20 09:59
OK, I see. There are some exceptions being swallowed by the schema export:

```
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table entity_a (id bigint generated by default as identity, description varchar(255), name varchar(255), [*]value integer, primary key (id))"; expected "identifier"; SQL statement:
create table entity_a (id bigint generated by default as identity, description varchar(255), name varchar(255), value integer, primary key (id)) [42001-224]
```

Very unfortunate... You ran into this issue:

- https://stackoverflow.com/q/70767876/521799

A workaround is to quote your identifier: `@Column(name = "`value`")`

There are two bugs in jOOQ here:

1. We should throw any exceptions caught by hibernate. There's probably an SPI to extract them from the `SchemaExport`
2. We should be able to handle those keywords, which H2 doesn't support as identifiers anymore (it used to, in the past)

**Comment by lukaseder** [comment] 2024-09-20 10:05
The H2 keyword specific bug will be this one:

- https://github.com/jOOQ/jOOQ/issues/17311

I'll fix this issue here right away, re-throwing Hibernate's errors when exporting the schema

**Comment by lukaseder** [comment] 2024-09-20 10:10
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17312)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17313)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17314)

Thanks again for your report and your patience, providing the MCVE. I should have tried your actual entity from the issue description when reproducing the problem. I used my own entity and focused only on what could have gone wrong with the configuration...

**Closed by lukaseder** 2024-09-20 10:10 UTC
Labels: T: Defect, C: Code Generation, P: Medium, C: Integration: Jakarta EE, E: All Editions

**Comment by lukaseder** [comment] 2024-09-20 12:13
The current fix may lead to this regression:

> 13:54:34,923 [ERROR] Failed to execute goal org.jooq.trial:jooq-codegen-maven:3.20.0-SNAPSHOT:generate (generate-jpadatabase) on project jooq-test-codegen-java: Error running jOOQ code generation tool: Error while exporting schema: Halting on error : Error executing DDL "drop table if exists master_data.language CASCADE " via JDBC Statement: Schema "MASTER_DATA" not found; SQL statement:

Since we're working on an in-memory database, might as well omit the dropping of the schema

**Comment by javiercj93** [comment] 2024-09-20 12:58
Appreciate your help! Thanks for the explanation and workaround!
