### ISSUE TITLE
java 9 split packages

### ISSUE THREAD

**Issue by hbrackmann** [jOOQ/jOOQ#7510] opened 2018-05-25 10:36 UTC
jooq contains split packages therefore can't be used as module.

"Split packages: Every module in Java 9 must contain unique packages. Many JARs in legacy and current code bases probably have split packages — the same package appears in one or more JAR. This probably includes open source and commercial third-party libraries. Your main work is then to refactor and re-architect the modules that you own. The third-party vendors and library team are responsible for their software and will handle their work."

**Comment by lukaseder** [comment] 2018-05-25 11:58
Thanks for reporting. We're aware :) And this will be fixed in jOOQ 3.11: #7419.

Duplicate of #7419

**Closed by lukaseder** 2018-05-25 11:58 UTC
Labels: C: Functionality, P: Medium, R: Duplicate, T: Defect
