### ISSUE TITLE
Support quoting built-in function calls

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8813] opened 2019-06-18 13:36 UTC
Most (if not all) databases have a set of built-in functions. Whether the name of a built-in function in an SQL query should be regarded as a keyword or identifier could potentially depend on the SQL dialect. But for dialects where these are identifiers, it would make sense if they would get quoted if `RenderQuotedNames#ALWAYS` is specified in the `Settings`.

**Comment by lukaseder** [comment] 2020-08-10 11:55
This change is included in #9931, when (if) we introduce a new concept of a "system name", i.e. a special kind of name for a built-in function.

I think that quoting these is almost never a good idea, even in dialects that have an actual function in the catalog backing the built-in function. There are always exceptions, and special functions that are not part of the catalog after all, but are translated by the parser to some other internal function syntax.

Closing this as a duplicate of #9931

**Closed by lukaseder** 2020-08-10 11:55 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Enhancement
