### ISSUE TITLE
Add code generation support for PostgreSQL types referencing domains

### ISSUE THREAD

**Issue by stangls** [jOOQ/jOOQ#7070] opened 2018-01-16 12:08 UTC
### Expected behavior and actual behavior:

expected: the codegen should use the correct domain
actual: the codegen uses `Object` and creates a depreceted method (because it assumes we need a binding)

### Steps to reproduce the problem:
1. create small database like this:
```
create domain biggerint AS NUMERIC(512, 0);

create table works (
  id biggerint PRIMARY KEY
);

create type id_tuple AS (
  id1 biggerint,
  id2 INT
)
```
2. run codegenerator with DAOs & POJOs enabled.
3. look at correctly generated pojo class `Works` which has `private BigInteger id;`
and compare to incorrectly generated pojo class `IdTuple` which has `private Object  id1;` and deprecated `getId1()` method.

### Versions:

- jOOQ: 3.10.3
- Java: 1.8.0_151
- Database (include vendor): PostgreSQL 9.6
- JDBC Driver (include name if inofficial driver): official postgresql driver 9.4.1212.jre7

**Comment by lukaseder** [comment] 2018-01-16 12:13
Thanks for your report. Adding support for type domains is on our roadmap: #681. I wonder if this issue here turns out to be a duplicate of #681 once the latter is implemented...

**Comment by stangls** [comment] 2018-01-16 12:53
oh okay. I assumed domains are already supported because they work .. well in some simple cases apparently :)

**Comment by lukaseder** [comment] 2020-06-09 14:28
#681 is now implemented. Looking into this soon

**Comment by lukaseder** [comment] 2020-08-07 13:06
I can confirm this now works with #681, starting from jOOQ 3.14

**Closed by lukaseder** 2020-08-07 13:06 UTC
Labels: C: Code Generation, C: DB: PostgreSQL, E: All Editions, P: Medium, T: Defect
