### ISSUE TITLE
Cannot call PG function having enum array parameter with null

### ISSUE THREAD

**Issue by ciaccia** [jOOQ/jOOQ#6824] opened 2017-11-20 14:51 UTC
Consider the following Postgres SQL:

```sql
CREATE TYPE jooq_type AS ENUM ('feature', 'bug');

CREATE OR REPLACE FUNCTION enum_array_fn(p_enums sre.jooq_type[])
RETURNS SETOF text AS $$
   SELECT UNNEST(ARRAY['bar','foo']);
$$ LANGUAGE SQL;
```

When I call the function using the code below, everything works correctly:

```java
Result<EnumArrayFnRecord> result = Routines.enumArrayFn(dslCtx.configuration(), new JooqType[0]);
```

If the function parameter is null, an exception is thrown:

```java
Result<EnumArrayFnRecord> a = Routines.enumArrayFn(dslCtx.configuration(), null);
```

> org.jooq.exception.DataAccessException: SQL [select "enum_array_fn"."enum_array_fn" from "sre"."enum_array_fn"(cast(? as varchar))]; ERROR: function sre.enum_array_fn(character varying) does not exist
>   Hint: No function matches the given name and argument types. You might need to add explicit type casts.
>   Position: 45
> 	at org.jooq_3.9.4.POSTGRES.debug(Unknown Source)
> 	at org.jooq.impl.Tools.translate(Tools.java:1994)
> 	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:676)
> 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:363)
> 	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:315)
> 	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2708)
> 	at org.jooq.Routines.enumArrayFn(Routines.java:32)
> 	at org.jooq.JooqBug.main(JooqBug.java:27)
>

**Comment by lukaseder** [comment] 2017-11-22 14:04
Thanks for your report. I will look into this shortly.

**Comment by lukaseder** [comment] 2017-11-22 14:35
Hmm, I cannot reproduce this with 3.11-SNAPSHOT, in case of which the following query is generated:

```sql
select "f_enum_table_6824"."f_enum_table_6824" from "public"."f_enum_table_6824"(?::"public"."u_country"[])
```

Have you tried other versions?

**Comment by lukaseder** [comment] 2017-11-22 14:52
Also works on 3.10. I wonder what fixed it, I cannot seem to see anything relevant in the release notes... Let's try 3.9 as well...

**Comment by ciaccia** [comment] 2017-11-22 15:31
Hallo Lukas, when compiling the stubs with jOOQ 3.9.4 and running the code with jOOQ 3.10.1 the problem is still reproducible. If I compile the stubs with jOOQ 3.10.1, the problem disappears.

**Comment by lukaseder** [comment] 2017-11-22 15:40
Oh interesting. By "compiling the stubs" do you mean running the code generator? Because there was a fix in the code generator related to enums: #6367. It was fixed only in 3.10, given the complexity of the fix...

**Comment by ciaccia** [comment] 2017-11-22 15:44
By "compiling" I meant generating, sorry for the confusion. We will upgrade to jOOQ 3.10 asap to have the problem fixed.

**Comment by lukaseder** [comment] 2017-11-22 15:50
OK, perfect, thank you very much. Closing this as a potential duplicate of #6367

**Closed by lukaseder** 2017-11-22 15:50 UTC
Labels: C: DB: PostgreSQL, C: Functionality, P: Medium, T: Defect
