### ISSUE TITLE
jOOQ-gradle-plugin multi execution configuration shouldn't require an explicit default configuration

### ISSUE THREAD

**Issue by hantsy** [jOOQ/jOOQ#16083] opened 2024-01-16 05:48 UTC
When upgrading to the latest 3.19.2, Gradle build failed.

```bash 
Cannot query the value of task ':jooqCodegen' property 'outputDirectory' 
because it has no value available
```

The related jooq config in Gradle build script, the `jooq` config is same as https://stackoverflow.com/questions/77676948/failed-when-upgrading-to-use-jooq-gradle-plugin-to-generate-codes

```kotlin 
jooq{
  ...
                    target {
                        packageName = "com.example.jooq"
                        directory = "${projectDir}/build/generated/jooq/main" 
                    }
}
```

**Comment by lukaseder** [comment] 2024-01-16 07:43
Hmm, I don't understand why the `outputDirectory` is required to have a value. I marked it as `@Optional`...

**Comment by hantsy** [comment] 2024-01-16 07:51
When add an empty `configuration{}` block to `jooq {}` like this.

```kotlin
jooq {
  configuration {} // add this 
  executions {}
}
```

I got build error:

```bash 
Execution failed for task ':jooqCodegen'.
> No JDBC URL configured.
```

**Comment by hantsy** [comment] 2024-01-16 07:54
When using `configuration {}` in the `jooq{}` directly.

```kotlin 
jooq {
   configuration{} // no executions
}
```
I got the build error like this:

```bash 
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':kaptGenerateStubsKotlin'.
> Task with path 'jooqCodegenMain' not found in root project 'myproject'
```

**Comment by lukaseder** [comment] 2024-01-16 07:56
> When add an empty `configuration{}` block to `jooq {}` like this.
> 
> ```kotlin
> jooq {
>   configuration {} // add this 
>   executions {}
> }
> ```
> 
> I got build error:
> 
> ```shell
> Execution failed for task ':jooqCodegen'.
> > No JDBC URL configured.
> ```

Did you just leave both things empty? What is your expectation of doing that? You didn't configure any jOOQ code generation at all, then...

> When using `configuration {}` in the `jooq{}` directly.
> 
> ```kotlin
> jooq {
>    configuration{} // no executions
> }
> ```
> 
> I got the build error like this:
> 
> ```shell
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':kaptGenerateStubsKotlin'.
> > Task with path 'jooqCodegenMain' not found in root project 'myproject'
> ```

Yes, because there's no `jooqCodegenMain` task. Check `gradle tasks` to see what tasks there are. See also: https://www.jooq.org/doc/latest/manual/code-generation/codegen-gradle/

**Comment by hantsy** [comment] 2024-01-16 08:04
OK, I think the second solution works for me now.

```kotlin 
jooq {
  configuration{...}
}
```

There is a task set dependency on `jooqCodegenMain`, I change it to `jooqCodegen`, it seems the build is ok.

**Comment by hantsy** [comment] 2024-01-16 08:12
>Did you just leave both things empty? What is your expectation of doing that? You didn't configure any jOOQ code generation at all, then...

No, I means adding an empty `configuration{}` before existing `executions{}` block.

**Comment by lukaseder** [comment] 2024-01-16 08:13
> > Did you just leave both things empty? What is your expectation of doing that? You didn't configure any jOOQ code generation at all, then...
> 
> No, I means adding an empty `configuration{}` before existing `executions{}` block.

I'm happy to look at complete examples. Otherwise, I'll just be chasing assumptions.

**Comment by hantsy** [comment] 2024-01-16 08:28
> I'm happy to look at complete examples. Otherwise, I'll just be chasing assumptions.
It seems works in my personal example, https://github.com/hantsy/spring-r2dbc-sample/pull/338/files.

**Comment by lukaseder** [comment] 2024-01-16 08:29
> It seems works in my personal example, https://github.com/hantsy/spring-r2dbc-sample/pull/338/files.

OK. Let me know if you find another example where it doesn't work. There are surely more bugs hidden in this early implementation.

**Comment by lukaseder** [comment] 2024-01-16 09:46
Fixed in versions:

- 3.20.0
- 3.19.3 (https://github.com/jOOQ/jOOQ/issues/16086)

Thanks again for your report and for your help in reproducing this. I've also fixed a vaguely related issue:

- https://github.com/jOOQ/jOOQ/issues/16084

3.19.3 should be released this week, given how annoying such pitfalls can be for new users of the plugin.

**Closed by lukaseder** 2024-01-16 09:46 UTC
Labels: T: Defect, C: Code Generation, P: High, R: Fixed, E: All Editions
