### ISSUE TITLE
Provide DSL.extract function for intervals and JSR-310 fields

### ISSUE THREAD

**Issue by lightoze** [jOOQ/jOOQ#5206] opened 2016-04-15 11:17 UTC
Currently DSL.extract function is quite limited. It would be very beneficial to support Interval and JSR-310 typed fields. Also please consider adding more DatePart options, such as EPOCH.

http://www.postgresql.org/docs/9.4/static/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT

**Comment by lukaseder** [comment] 2016-04-15 11:35
Indeed, thank you very much for your suggestion.

The "EPOCH" and other non-standard datepart extraction is already on the roadmap: https://github.com/jOOQ/jOOQ/issues/2132

The java.time discussion is scattered across a variety of issues. E.g. https://github.com/jOOQ/jOOQ/issues/4429. The problem here lies with the fact that there is currently no way in Java to properly overload API that accepts "classic" `java.sql` temporal types with API that accepts "new" `java.time` temporal types. This is due to the lack of union types and/or reified generics. I have currently no solution for this problem, short of perhaps, not overloading methods, but introducing new names.

Closing this issue as a duplicate of existing issues.

**Closed by lukaseder** 2016-04-15 11:35 UTC
Labels: C: Functionality, P: Medium, T: Enhancement
