### ISSUE TITLE
SelectQuery.setForUpdate and similar methods do not clear flag when value is false

### ISSUE THREAD

**Issue by hwestphal** [jOOQ/jOOQ#11244] opened 2021-01-17 15:35 UTC
When calling `SelectQuery.setForUpdate` with parameter `false` the `FOR UPDATE` flag is added the query.

The expected behavior (as suggested in the API documentation) is that for ` SelectQuery.setForUpdate(true)` the flag is added to the query, and for `SelectQuery.setForUpdate(false)` the flag is not added to the query.

The same applies to `setForNoKeyUpdate`, `setForKeyShare`, `setForShare` accordingly.

jOOQ version: 3.14.4

**Comment by lukaseder** [comment] 2021-01-18 07:59
Thanks a lot for your report. That seems to be a regression introduced in jOOQ 3.12 with https://github.com/jOOQ/jOOQ/issues/7705. Prior to jOOQ 3.12, setting the flag to `false` had the desired effect.

**Comment by lukaseder** [comment] 2021-01-18 08:11
Fixed in jOOQ 3.15.0 and 3.14.5 (#11245). Thanks again for your report

**Closed by lukaseder** 2021-01-18 08:11 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect
