### ISSUE TITLE
INSERT .. RETURNING with aliased target table generates wrong SQL in Oracle

### ISSUE THREAD

**Issue by mnisius** [jOOQ/jOOQ#9922] opened 2020-03-06 11:19 UTC
### Expected behavior and actual behavior:
Hi, 
if we use the returning() Method after declaring an insert the generated sql statment ist wrong. 

### Steps to reproduce the problem 
This is our code:

```java
    IncentiveGutscheincodes igc = new IncentiveGutscheincodes().as("igc");

    final InsertSetMoreStep<IncentiveGutscheincodesRecord> insert =
      create.insertInto(igc)
        .set(igc.INGC_ID, Sequences.SEQ_INGC.nextval().coerce(Long.class))
        .set(igc.INGC_ERSTELLT_VON, DSL.currentUser())
        .set(igc.INGC_ERSTELLUNGSZEITPUNKT, LocalDateTime.now());

    LOG.info("correct insert statement: {} ", insert.getSQL(ParamType.INLINED));

    final InsertResultStep<IncentiveGutscheincodesRecord> insertWithReturn = insert.returning();
    LOG.info("broken insertWithReturn statement: {} ", insertWithReturn.getSQL(ParamType.INLINED));

    //-> java.sql.SQLSyntaxErrorException: ORA-04043: Objekt TEST."IGC" ist nicht vorhanden
    final IncentiveGutscheincodesRecord incentiveGutscheincodesRecord = insertWithReturn.fetchOne();
```
These are the generated statments 

correct insert statement: 

```sql
insert into "TEST"."INCENTIVE_GUTSCHEINCODES" "igc" ("INGC_ID", "INGC_ERSTELLT_VON", "INGC_ERSTELLUNGSZEITPUNKT") 
values ("TEST"."SEQ_INGC".nextval, user, cast(timestamp '2020-03-06 12:17:15.1303232' as date))
```

broken insertWithReturn statement: 

```sql
insert into TEST."igc" ("INGC_ID", "INGC_ERSTELLT_VON", "INGC_ERSTELLUNGSZEITPUNKT") 
values ("TEST"."SEQ_INGC".nextval, user, cast(timestamp '2020-03-06 12:17:15.1303232' as date))
```

As you can see the table name is replaced with only the alias so the statment fails.. 

### Versions:

- jOOQ: 3.12.x & 3.13.x
- Java: 8 & 11
- Database (include vendor): Oracle 18
- OS : Windows / Linux
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2020-03-06 11:27
Thanks, that makes sense. We'll look into it.

In the meantime, there's `returningResult()` (rationale here: #7475) which you could use to return `igc.fields()` instead.

**Comment by maximumstock** [comment] 2020-03-10 15:49
Hello,

I have a similar problem and tried your proposed solution with `returningResult(alias.fields())` which results in the same problem as using `returning()`. Namely the full table name being omitted, as described in the original issue above.

My setup:

- jOOQ: 3.13.1
- Java: 11
- Database (include vendor): Oracle 18
- OS : Windows

**Comment by lukaseder** [comment] 2020-03-11 14:40
Thanks for the confirmation, @maximumstock

**Comment by lukaseder** [comment] 2020-03-11 14:47
Related issue: #8384

**Comment by lukaseder** [comment] 2020-03-11 16:39
The suggested syntax also doesn't work, depending on the JDBC driver:

```sql
insert into "TEST"."INCENTIVE_GUTSCHEINCODES" "igc"
```

See #7962, which introduced this regression. If you're not affected by #7962, you can work around the issue by setting the `Settings.setApplyWorkaroundFor7962(false)`

**Comment by lukaseder** [comment] 2020-03-11 17:06
Fixed in jOOQ 3.14.0. Backport scheduled for 3.13.2 (#9943)

**Comment by lukaseder** [comment] 2020-03-12 10:07
Other dialects may also be unable to correctly handle `INSERT .. RETURNING` because `getIdentity()` produces the unaliased, fully qualified column reference in a follow-up `SELECT` query: https://github.com/jOOQ/jOOQ/issues/5050

**Comment by lukaseder** [comment] 2020-03-12 10:20
Relevant issue for other dialects: https://github.com/jOOQ/jOOQ/issues/9946

**Closed** 2020-03-16 15:44 UTC
Labels: C: DB: Oracle, C: Functionality, E: Enterprise Edition, E: Professional Edition, P: Medium, R: Fixed, T: Defect
