### ISSUE TITLE
Add support for SQL Server 2017 STRING_AGG

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6976] opened 2018-01-02 16:17 UTC
See:
https://docs.microsoft.com/de-ch/sql/t-sql/functions/string-agg-transact-sql

At least PostgreSQL and CockroachDB also support this function.

**Comment by knutwannheden** [comment] 2020-02-24 13:58
Closing as duplicate of #9868.

**Closed by knutwannheden** 2020-02-24 13:58 UTC
Labels: C: DB: CockroachDB, C: DB: PostgreSQL, C: DB: SQL Server, E: All Editions, P: Medium, R: Duplicate, T: Enhancement
