### ISSUE TITLE
Postgres 9.5 INSERT INTO ... ON CONFLICT ... DO UPDATE SET ... RETURNING syntax

### ISSUE THREAD

**Issue by ayedo** [jOOQ/jOOQ#6284] opened 2017-05-26 12:16 UTC
jOOQ 3.9 added support for the "ON CONFLICT ... DO UPDATE SET ... " syntax, which is great!

If we look at the [full insert syntax](https://www.postgresql.org/docs/9.5/static/sql-insert.html), it allows for the "RETURNING" keyword after "DO UPDATE SET".

In jOOQ this does not seem to work.

**Comment by lukaseder** [comment] 2017-05-26 12:28
Yes, stay tuned :)
Duplicate of https://github.com/jOOQ/jOOQ/issues/2123

**Closed by lukaseder** 2017-05-26 12:28 UTC
