### ISSUE TITLE
java.lang.StackOverflowError at org.jooq.impl.Expression.acceptAssociative

### ISSUE THREAD

**Issue by SindhuSGit** [jOOQ/jOOQ#14356] opened 2022-12-02 17:46 UTC
### Your question

The following query when ran with large number of records fails with StackOverFlowError but works fine with a smaller chunk.

```java
    
    private fun query(guestIdAddressTypeMap: Map<String, List<String>>): Map<String?, Result<GuestCurrentAddressRecord>> {
        var guestCurrentAddressRecordMap: Map<String?, Result<GuestCurrentAddressRecord>> = emptyMap()
        if (guestIdAddressTypeMap.isNotEmpty()) {
            val currentAddressQuery = context.selectQuery(GUEST_CURRENT_ADDRESS)
            var condition = noCondition()
            guestIdAddressTypeMap.forEach {
                condition = condition.or(GUEST_CURRENT_ADDRESS.REDCARD_GUEST_ID.eq(it.key).and(GUEST_CURRENT_ADDRESS.ADDRESS_TYPE.`in`(it.value)))
            }
            currentAddressQuery.addConditions(condition)
            guestCurrentAddressRecordMap = currentAddressQuery.fetchGroups(GUEST_CURRENT_ADDRESS.REDCARD_GUEST_ID)
        }
        return guestCurrentAddressRecordMap
    }
```
    
   We cannot figure out what produces the infinite loop, and are unable to debug the issue

{"timeMillis":1670234292612,"thread":"pool-2-thread-1","level":"ERROR","loggerName":"io.micronaut.configuration.kafka.exceptions.KafkaListenerExceptionHandler","message":"Kafka consumer [redcard.core.consumer.kafka.EventListener@3d84ae5] produced error: null","timeMillis":1670234292613,"thrown":{"commonElementCount":0,"name":"java.lang.StackOverflowError","extendedStackTrace":"java.lang.StackOverflowError: null\n\tat org.jooq.impl.ScopeStack.listOrNull(ScopeStack.java:225) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.ScopeStack.get(ScopeStack.java:190) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.DefaultRenderContext.scopeMapping(DefaultRenderContext.java:204) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.AbstractContext.visit(AbstractContext.java:237) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.TableFieldImpl.lambda$accept$0(TableFieldImpl.java:127) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.AbstractContext.toggle(AbstractContext.java:338) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.AbstractContext.data(AbstractContext.java:349) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.TableFieldImpl.accept(TableFieldImpl.java:125) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.AbstractContext.visit(AbstractContext.java:295) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.Eq.lambda$accept$0(Eq.java:104) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.Eq.acceptCompareCondition(Eq.java:145) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.Eq.accept(Eq.java:104) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.AbstractContext.visit(AbstractContext.java:295) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.Expression.acceptAssociative(Expression.java:906) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.Expression.acceptAssociative(Expression.java:880) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.And.accept(And.java:113) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:720) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.AbstractContext.visit(AbstractContext.java:295) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.Expression.acceptAssociative(Expression.java:906) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.Expression.acceptAssociative(Expression.java:880) ~[jooq-3.16.4.jar:?]\n\tat org.jooq.impl.Expression.acceptAssociative(Expression.java:901) ~[jooq-3.16.4.jar:?]\n\tat 

This repeats again

### jOOQ Version

3.16.4

### Database product and version

PostgreSQL

**Comment by lukaseder** [comment] 2022-12-05 10:20
Thank you for your report. Can you please post the complete exception stack trace? Also, a "minimal, complete, verifiable example" would be helpful. Your jOOQ API usage doesn't seem extraordinary, and indeed, I can't reproduce such a significant error with a simple example as yours:

```kotlin
val q = dsl.selectQuery(table("x"))
var condition = noCondition()
val map: Map<String, List<String>> = mapOf("a" to listOf("b", "c"), "d" to listOf("e", "f"))
map.forEach {
    condition = condition.or(field("x").eq(it.key).and(field("y", String::class.java).`in`(it.value)))
}
q.addConditions(condition)
println(q)
```

This just produces:

```sql
select *
from x
where (
  (
    x = 'a'
    and y in (
      'b', 'c'
    )
  )
  or (
    x = 'd'
    and y in (
      'e', 'f'
    )
  )
)
```

Which is expected.

We have a template to create MCVEs here: https://github.com/jOOQ/jOOQ-mcve. Upgrading first might help, too. jOOQ keeps fixing issues, and maybe, the underlying problem has gone already.

**Comment by mheider** [comment] 2022-12-12 15:42
I ran into a similar error:

```
java.lang.StackOverflowError: null
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:873) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:905) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:884) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:905) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:884) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:905) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:884) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:905) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:884) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:905) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:884) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:905) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:884) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:905) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:884) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:905) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:884) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:905) ~[jooq-3.17.5.jar:na]
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:884) ~[jooq-3.17.5.jar:na]
```

The function that produced the error was the following:

```kt
    fun startsWith(codes: Set<String>?) = if (codes == null) {
        DSL.trueCondition()
    } else {
        codes.map { TABLE_NAME.FIELD_NAME.startsWith(it.name) }
            .fold(DSL.falseCondition(), Condition::or)
    }
```

Still maybe it was a misusage on my side. The `codes` set could get pretty large.
I just thought maybe it helps in debugging the issue.

**Comment by lukaseder** [comment] 2022-12-12 16:02
How big are those collections?

**Comment by lukaseder** [comment] 2022-12-12 19:07
Yeah, that's it. I can reproduce the problem like this:

```java
System.out.println(
IntStream.range(0, 10000)
    .mapToObj(i -> val(i).eq(i))
    .reduce(Condition::or)
    .toString());
```

I suspect the algorithm can be changed to prefer iteration over recursion for these associative traversals...

**Comment by lukaseder** [comment] 2022-12-12 19:13
This risk of producing `StackOverflowError` has probably been introduced with https://github.com/jOOQ/jOOQ/issues/10710 in jOOQ 3.16. As a part of the new `QOM` API, the previous implementation that used `List<Condition>` for `AND` or `OR` predicates, we now support binary operators only to make the `QOM` API simpler and more straightforward. This deepens the expression tree.

But again, we can probably flatten its traversal for associative operations by using iteration rather than recursion.

**Comment by mheider** [comment] 2022-12-12 21:34
Thanks for the fast reply :)

I built a workaround with the following query:

```kt
    fun startsWith(codes: Set<String>?) = if (codes == null) {
        DSL.trueCondition()
    } else {

        val anyArrayField = DSL.field("ANY(ARRAY[${codes.joinToString(", ") { "'${it}%'" }}])", String::class.java)

        DSL.exists(
            DSL.selectOne()
                .from(TABLE_NAME)
                .where(TABLE_NAME.FIELD_NAME.likeIgnoreCase(anyArrayField))
        )
    }
```

It ain't a beauty, but it works. 💪

**Comment by lukaseder** [comment] 2022-12-12 22:18
That looks SQLi prone. Better use an array bind variable

```kotlin
field("ANY(?)", String::class.java, arrayOf<String>(...))
```

**Comment by lukaseder** [comment] 2022-12-13 11:56
The alternative algorithm for `org.jooq.impl.Expression::acceptAssociative` trades stack depth for heap allocations. In a quick benchmark, I couldn't see any significant difference for ordinary expression tree sizes, but it might be something to keep an eye out for.

**Comment by lukaseder** [comment] 2022-12-16 13:21
The fix is incorrect. Depending on the tree structure of associative expressions, we're now commuting arguments, which isn't always correct, depending on the operator. It's also weird from a user perspective even if the operator *is* commutative. The tests so far only tested for these two types of trees:

```
((((a op b) op c) op d) op e
a op (b op (c op (d op e))))
```

But of course, there are many more possible associations

I've added these tests:

```java
        assertFormattingEqualsAll(
            "(1 + 2 + 3 + 4)",
            c1.plus(c2).plus(c3).plus(c4),
            c1.plus(c2.plus(c3)).plus(c4),
            c1.plus(c2).plus(c3.plus(c4)),
            c1.plus(c2.plus(c3).plus(c4)),
            c1.plus(c2.plus(c3.plus(c4)))
        );

        assertFormattingEqualsAll(
            "(1 + 2 + 3 + 4 + 5)",
            c1.plus(c2).plus(c3).plus(c4).plus(c5),
            c1.plus(c2).plus(c3).plus(c4.plus(c5)),
            c1.plus(c2.plus(c3)).plus(c4).plus(c5),
            c1.plus(c2.plus(c3)).plus(c4.plus(c5)),
            c1.plus(c2).plus(c3.plus(c4)).plus(c5),
            c1.plus(c2).plus(c3.plus(c4).plus(c5)),
            c1.plus(c2).plus(c3.plus(c4.plus(c5))),
            c1.plus(c2.plus(c3).plus(c4)).plus(c5),
            c1.plus(c2.plus(c3).plus(c4).plus(c5)),
            c1.plus(c2.plus(c3).plus(c4.plus(c5))),
            c1.plus(c2.plus(c3.plus(c4))).plus(c5),
            c1.plus(c2.plus(c3.plus(c4)).plus(c5)),
            c1.plus(c2.plus(c3.plus(c4).plus(c5))),
            c1.plus(c2.plus(c3.plus(c4.plus(c5))))
        );
```

The first one fails with:

```
org.junit.ComparisonFailure: Unformatted comparison expected:<([1 + 2 + 3] + 4)> but was:<([3 + 1 + 2] + 4)>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.jooq.test.AbstractTest.assertEquals(AbstractTest.java:202)
	at org.jooq.test.formatting.AbstractFormattingTest.assertFormattingEquals0(AbstractFormattingTest.java:186)
	at org.jooq.test.formatting.AbstractFormattingTest.assertFormattingEquals(AbstractFormattingTest.java:174)
	at org.jooq.test.formatting.AbstractFormattingTest.assertFormattingEqualsAll(AbstractFormattingTest.java:179)
	at org.jooq.test.formatting.FormattingExpressionTest.testArithmeticExpressions(FormattingExpressionTest.java:154)
```

**Comment by lukaseder** [comment] 2022-12-16 13:24
The failing expression is `c1.plus(c2).plus(c3.plus(c4))`, or `(1 + 2) + (3 + 4)`. The other ones with 4 operands are all still correct

**Closed** 2022-12-16 13:57 UTC
Labels: T: Defect, C: Functionality, P: High, E: All Editions

**Comment by lukaseder** [comment] 2022-12-16 16:44
Another fun challenge, though a bit less likely, perhaps, `StackOverflowError` when nesting subqueries 1024 times: https://github.com/jOOQ/jOOQ/issues/14418
