### ISSUE TITLE
PostgreSQL12, Generated Columns are ReadOnly

### ISSUE THREAD

**Issue by eiswind** [jOOQ/jOOQ#9592] opened 2019-11-25 13:38 UTC
### Use case:

I created a table like:

```
create table ${db.schema}.book_product(
                id uuid not null ,
                version int4 default 0 not null ,
                product jsonb not null ,
                last_modified timestamp not null ,
                title_text varchar(511) generated always as ( trim('&quot;' FROM jsonb_path_query_first(product, '$.descriptiveDetail.titleDetails[0].titleElements[0].titleText')::text) ) stored
            )
```
if i run 
```
val bp = BookProduct()
        bp.id = UUID.randomUUID()
        bp.lastModified = LocalDateTime.now()
        bp.product = p

        bookProductDao.insert(bp) 
```
it fails with
```
35025 [ERROR] testInsert  Time elapsed: 0.185 s  <<< ERROR!
org.springframework.jdbc.BadSqlGrammarException: 
jOOQ; bad SQL grammar [insert into "jooq"."book_product" ("id", "product", "last_modified", "title_text", "version") values (cast(? as uuid), ?::jsonb, cast(? as timestamp), ?, ?) returning "jooq"."book_product"."id"]; nested exception is org.postgresql.util.PSQLException: ERROR: cannot insert into column "title_text"
  Detail: Column "title_text" is a generated column.
	at de.eiswind.onixbuddy.backend.repositories.BookProductRepositoryTest.testInsert(BookProductRepositoryTest.kt:40)
Caused by: org.postgresql.util.PSQLException: 
ERROR: cannot insert into column "title_text"
  Detail: Column "title_text" is a generated column.
```

### Possible solution you'd like to see:

Is there a way to make jooq be aware that this is a read-only column?

- jOOQ: 3.12.3
- Java: 11
- Database (include vendor): Postgres12
- OS:Linux
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2019-11-25 18:21
That's a very interesting thought, thanks very much for your feature request.

There are mainly two popular concepts in a variety of RDBMS that should lead to columns not being included in a variety of operations that touch the "entire record":

- Read only columns
- Defaulted columns (sometimes, inclusion is desired, sometimes it is not)
- Invisible columns

We'll think about this, and probably implement a few new features based on this idea in separate issues.

**Comment by lukaseder** [comment] 2019-11-25 18:22
Note, we already have such logic when a `NOT NULL` column is defaulted, in case of which we assume that `NULL` is not a desireable value to load into this record when storing it from a POJO.

**Comment by ieugen** [comment] 2020-03-12 09:48
I've encountered this need also. Having support for read-only columns can make the implementation of some solutions quite easy and straight forward.

One use case that comes to mind is this: created and updated time on column kept via db triggers. I would like for those columns to be read only from the Java application.

Also in some cases, an application could be built so that it can only read some tables but not change it because they are changed by another application. This is useful in some "micro-service" scenarios that integrate at the db level. (notice the quotes)

I've seen this feature is marked for enterprise only though :( .

**Comment by lukaseder** [comment] 2020-03-12 11:17
Thanks for your comment, @ieugen 

> One use case that comes to mind is this: created and updated time on column kept via db triggers. I would like for those columns to be read only from the Java application.

See also my own comment: https://github.com/jOOQ/jOOQ/issues/9592#issuecomment-558278633

> Also in some cases, an application could be built so that it can only read some tables but not change it because they are changed by another application.

I think that approach is best solved with privileges (`GRANT SELECT` only). To my surprise (being an Oracle guy, where the default privileges are nothing, and DBAs will frown upon every single `GRANT` request), so many systems work with a single database user, when a lot of SQL dialects offer a variety of security features that solve precisely these problems.

**Comment by lukaseder** [comment] 2020-12-02 12:40
See also: https://github.com/jOOQ/jOOQ/issues/11073

**Comment by lukaseder** [comment] 2021-11-02 13:45
I'm currently adding support for readonly columns in jOOQ 3.16 (https://github.com/jOOQ/jOOQ/issues/9864), and there will be support for computed columns as well (https://github.com/jOOQ/jOOQ/issues/6492).

Closing this as a duplicate of the other two.

**Closed by lukaseder** 2021-11-02 13:45 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, E: All Editions
