### ISSUE TITLE
Wrong statement generated for MySQL when leading unqualified asterisk is used with plain SQL template table

### ISSUE THREAD

**Issue by loicmathieu** [jOOQ/jOOQ#15975] opened 2023-12-20 14:48 UTC
### Expected behavior

Statements generated on MySQL with jOOQ 3.18 should works.

### Actual behavior

We have a query statement with an asterisk and a rownumber in the same select clause.
It works fine in jOOQ 3.17 but didn't work anymore on jOOQ 3.18.
We support multiple databases and only MySQL is affected (H2 and PostgreSQL works fine).

### Steps to reproduce the problem

See the following reproducer, it contains a test that works in 3.17, when changing the version in the pom.xml to 3.18 it didn't work anymore.
The README contains information on how to create the table on MySQL.

[jooq-issue.zip](https://github.com/jOOQ/jOOQ/files/13728652/jooq-issue.zip)

### jOOQ Version

3.18

### Database product and version

MySQL 8.2

### Java Version

openjdk version "17.0.8.1" 2023-08-24

### OS Version

Linux *** 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### JDBC driver name and version (include name if unofficial driver)

mysql:mysql-connector-java:8.0.33

**Comment by lukaseder** [comment] 2023-12-20 14:56
Thanks for your message. We don't maintain those old versions anymore, but from your ZIP file contents, you probably mean jOOQ 3.17 and 3.18 instead?

**Comment by loicmathieu** [comment] 2023-12-20 14:57
@lukaseder yes, sorry, it was from 3.17 to 3.18, I updated the issue

**Comment by lukaseder** [comment] 2023-12-20 15:22
I can reproduce this. It seems the asterisk in the inner most derived table gets removed. Related, known issues include:

- https://github.com/jOOQ/jOOQ/issues/7841
- https://github.com/jOOQ/jOOQ/issues/14299

A workaround in your case is this:

```java
fields.add(DSL.table("flows").asterisk());
```

**Comment by lukaseder** [comment] 2023-12-20 15:30
This is a regression due to 

- https://github.com/jOOQ/jOOQ/issues/14300

A workaround for a "missing feature" (i.e. bug) in MySQL's parser:

- https://bugs.mysql.com/bug.php?id=109206

This workaround should not be applied for plain SQL tables, of course, since we can't expand the asterisk in those cases. As stated in #14300, that MySQL limitation only affects unqualified asterisks (since it seems to be a parser bug, not a functional one), so this is why the qualified asterisk works as a workaround.

**Comment by lukaseder** [comment] 2023-12-20 16:00
Fixed in versions:

- 3.20.0
- 3.19.2 (https://github.com/jOOQ/jOOQ/issues/15976)
- 3.18.9 (https://github.com/jOOQ/jOOQ/issues/15977)

Thanks again for your report!

**Comment by loicmathieu** [comment] 2023-12-20 16:01
Thanks, I confirm the workaround fixes our issue with MySQL without causing issues with H2 or PostgreSQL.

**Closed by lukaseder** 2023-12-20 16:00 UTC
Labels: T: Defect, C: Functionality, C: DB: MySQL, P: Medium, C: DB: MariaDB, E: All Editions

**Comment by loicmathieu** [comment] 2023-12-20 16:03
And thanks for the quick fix!
