### ISSUE TITLE
DayToSecond normalization can misrepresent time ranges if PSQL server's local timezone observes DST

### ISSUE THREAD

**Issue by ruke47** [jOOQ/jOOQ#13126] opened 2022-02-23 00:52 UTC
### Expected behavior

If I construct DayToSecond with `DayToSecond(0, 25, 0)`, I expect it to store `0 days, 25 hours, 0 minutes, 0 seconds, 0 nano, negative = false`.

### Actual behavior
If I construct DayToSecond with `DayToSecond(0, 25, 0)`, it actually stores `1 days, 1 hours, 0 minutes, 0 seconds, 0 nano, negative = false`.

### Steps to reproduce the problem

- Have a Postgresql server where the timezone is configured to a Daylight Savings Time-observing timezone, like `America/Los_Angeles`. Note that the bug appears based off of the _server's_ timezone, not the timezone of the SQL values.
- Compare the difference between adding `24 hours` and `1 day` while crossing a DST boundary. (Adding `1 day` keeps the hour value equal, but with the new offset. This is equivalent to adding `23 hours` in the spring, or adding `25 hours` in the fall.)

```
test_db=# select '2022-03-12 12:00:00 America/Los_Angeles'::timestamptz + interval '24 hours';
        ?column?        
------------------------
 2022-03-13 13:00:00-07
(1 row)

test_db=# select '2022-03-12 12:00:00 America/Los_Angeles'::timestamptz + interval '1 day';
        ?column?        
------------------------
 2022-03-13 12:00:00-07
(1 row)
```

### Versions

- jOOQ: All
- Java: n/a
- Database (include vendor): Postgresql
- OS: n/a
- JDBC Driver (include name if inofficial driver): n/a

**Comment by lukaseder** [comment] 2022-02-23 13:56
Thanks a lot for your report. That seems to be the same issue as https://github.com/jOOQ/jOOQ/issues/13027 ?

Closing this a sa duplicate of https://github.com/jOOQ/jOOQ/issues/13027. Please let me know if I'm overlooking a detail making this a different issue.

**Closed by lukaseder** 2022-02-23 13:56 UTC
Labels: T: Defect, C: Functionality, C: DB: PostgreSQL, P: Medium, E: All Editions

**Comment by ruke47** [comment] 2022-02-23 18:37
Ah, yes, this appears to be a duplicate. Thanks!
