### ISSUE TITLE
Introspect database schema and check indexes when searching

### ISSUE THREAD

**Issue by raderio** [jOOQ/jOOQ#9056] opened 2019-08-17 15:21 UTC
Will be great if based on information about the database indexes, jOOQ will emit a warning in case there are some methods that do not use indexes for searching.

**Comment by lukaseder** [comment] 2019-08-19 07:48
Thank you very much for your suggestion. In version 3.11, we've introduced the new `DiagnosticsListener` SPI (https://github.com/jOOQ/jOOQ/issues/5960), which we will eventually extend to a full blown, independent product. Some ideas are already gathered in issue https://github.com/jOOQ/jOOQ/issues/7527.

This new product will include gathering metrics like the one you suggested, as it will be relatively simple to make some basic indexing suggestions based on statistics gathered on months' worth of logged jOOQ queries.

However, we're not there yet. We are planning on creating a number of new products in the near future, and we still need to prioritise them appropriately.

I'm closing this as a duplicate of #7527

**Closed by lukaseder** 2019-08-19 07:48 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Enhancement
