### ISSUE TITLE
Regression: UpdateQuery.execute() with RETURNING clause returns 1 even when no records were updated

### ISSUE THREAD

**Issue by krzysztof-osiecki** [jOOQ/jOOQ#14571] opened 2023-02-02 14:46 UTC
### Expected behavior

Returning 0 from UpdateQuery when no records are updated.

### Actual behavior

Returning 1 from UpdateQuery when no records are updated.

### Steps to reproduce the problem

This is a follow up to offtopic message in https://github.com/jOOQ/jOOQ/issues/13574

We build UpdateQuery like so:
```
		//tableInfo being our descriptor of some tables that we know how to convert into Table object
                Table<Record> table = getTable(tableInfo);
		UpdateQuery<Record> updateQuery = dsl.updateQuery(table);
                //... multiple addValue statements
                //conditions determining if update made
                updateQuery.addConditions(jooqTable.ID.eq(record.getId()));
		updateQuery.addConditions(jooqTable.VER.eq(version));
                //setting columns modified by triggers to be returned
		updateQuery.setReturning(getReturningFields(tableInfo));
		int updatedCount = updateQuery.execute();
                 if (updatedCount <= 0) {
			throw IllegalUpdateException("No records were updated, we throw exception and handle it somewhere else.")
		}
                Record triggeredValues = updateQuery.getReturnedRecord();
                //proceed to do important things with triggeredValues like
                triggeredValues.getValue("someColumn")
```
This was our approach in jooq 3.16.1 with java11 and postgresql jdbc driver 42.4.2. We upgraded java to 17 and with it jooq to 3.17.7 and postgres driver 42.5.1. 
After this upgrade we got NPE from triggeredValues.getValue("someColumn"). So we considered that this is either because of jooq or postgresql upgrade as java was not a big suspect.
Even though no record was updated the return value was 1 instead of 0. After debuging we found that the 1 comes from AbstractDMLQuery#execute where final result is set to `result = Math.max(result, returnedResult.size());` where `result` is initalized with 1, so method returns 1 despite returnedResult.size() being 0.
This Math.max call is preceeded by a comment stating:
```
                // [#13574] The DML statement itself may have produced a rowcount
                //          but the returned results might be empty, so keep the
                //          higher value of the two
```
Which is the reason for me to raise the question in the previously mentioned issue.

We changed our code to:
```
		//tableInfo being our descriptor of some tables that we know how to convert into Table object
                Table<Record> table = getTable(tableInfo);
		UpdateQuery<Record> updateQuery = dsl.updateQuery(table);
                //... multiple addValue statements
                //conditions determining if update was made
                updateQuery.addConditions(jooqTable.ID.eq(record.getId()));
		updateQuery.addConditions(jooqTable.VER.eq(version));
                //setting columns modified by triggers to be returned
		updateQuery.setReturning(getReturningFields(tableInfo));
		updateQuery.execute();
                Record triggeredValues = updateQuery.getReturnedRecord();
                 if (triggeredValues  == null) {
			throw IllegalUpdateException("No records were updated, we throw exception and handle it somewhere else.")
		}
                //proceed to do important things with triggeredValues like
                triggeredValues.getValue("someColumn")
```

and it works fine for our case. However the documentation of Query#execute states that for Update implementation the result should be number of updated records so it seems like a bug.

### jOOQ Version

3.17.7

### Database product and version

PostgreSQL 11.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

### Java Version

openjdk-17.0.2

### OS Version

Windows 10 Enterprise 19043.2006

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.1

**Comment by lukaseder** [comment] 2023-02-03 09:12
Thanks a lot for your report. I'll look into this soon.

**Comment by lukaseder** [comment] 2023-02-08 15:58
Thanks again for your report and for your detailed analysis. Indeed, this is all because `result` is initialised to `1`. This must be very historic, when we only supported single-row `INSERT .. RETURNING`, in case of which the value `1` might make sense in some test cases.

These APIs (`UpdateQuery`) are quite old, and haven't seen too many direct integration tests anymore. From the DSL API, there's no way to access the `UpdateQuery`, and we'll soon do a few changes in this area:

- https://github.com/jOOQ/jOOQ/issues/11241

While `UpdateQuery` et al. won't be removed or even deprecated in the near future, their usage will be discouraged. There's usually no reason to prefer those APIs over the DSL API, even for dynamic SQL.

In any case, checking if the returned record is `null` is certainly a good workaround.

**Comment by lukaseder** [comment] 2023-02-08 16:06
Fixed in jOOQ 3.18.0 and 3.17.8 (https://github.com/jOOQ/jOOQ/issues/14596)

**Closed by lukaseder** 2023-02-08 16:06 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by lukaseder** [comment] 2023-02-08 16:12
Though, the fix does produce a regression on https://github.com/jOOQ/jOOQ/issues/13574. Perhaps https://github.com/jOOQ/jOOQ/issues/13574 was simply fixed the wrong way. I'll investigate this further, tomorrow

**Comment by lukaseder** [comment] 2023-02-09 10:16
It's not strictly a regression of #13574. Initialising the `result = 1` has always been wrong, but that wrongness was clouded by the fact that in most cases, the value `1` coincided with the actual row count, e.g. when calling `UpdatableRecord::merge`.

A better fix is to initialise the `result = 0`, and then:

```java
result = Math.max(Math.max(result, ctx.rows()), returnedResult.size());
```

Knowing that either:

- `result` was set to some other value in some dialect
- `ctx.rows()` was set by some utility
- `returnedResult` is available

Where `max` is just returning any non-zero value.
