### ISSUE TITLE
Converted Datatype's don't appear to convert when called with getValue()

### ISSUE THREAD

**Issue by talios** [jOOQ/jOOQ#10853] opened 2020-11-04 08:27 UTC
In my code I have the following declared:

```
public static final DataType<Instant> InstantType = SQLDataType.OFFSETDATETIME.asConvertedDataType(new InstantConverter());
```

which is used in a `DSL.field()` declaration.

### Expected behavior

When accessed from a record with `Instant i = record.getValue(CREATED_DATE)` - I expect to get an `Instant` instance returned.

### Actual behavior

I get a `ClassCastException` in my application code as the call returns an instance of `OffsetDateTime`.

Has anything changed in the recent 3.14 release? Possibly something related to #10694 ?

### Versions

- jOOQ: 3.14.1
- Java: Java 8
- Database (include vendor): PostgresSQL ( 13 ) 
- OS: OSX
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.18

**Comment by lukaseder** [comment] 2020-11-04 08:49
Thank you very much for your report. Can you show a full example that helps reproduce the problem? E.g. what is `CREATED_DATE` and what's the stack trace of the exception?

By the way, we have an `SQLDataType.INSTANT`...

**Comment by lukaseder** [comment] 2020-11-04 08:50
(This might be a duplicate of https://github.com/jOOQ/jOOQ/issues/5846, but I'm not sure yet, from the description)

**Comment by talios** [comment] 2020-11-04 10:20
```
  // old convenience method of ours to force using a name()
  public static <T> Field<T> tableField(Table<Record> t, DataType<T> type, String field) {
    return DSL.field(name(t.getName(), field), type);
  }
  public static final Field<Instant> CREATED_DATE = tableField(TENANCY, InstantType, "created_date");
```

Stack trace is:

```
2020-11-04 07:51:06,813 [AbstractProblemHandler.java:182:ERROR] WARNING: 500 GET against /api/vendor/1004/tenancies: java.time.OffsetDa
teTime cannot be cast to java.time.Instant
java.lang.ClassCastException: java.time.OffsetDateTime cannot be cast to java.time.Instant
        at smx3.tenancy.jooq.Tenancies.lambda$static$0(Tenancies.java:83)
        at org.jooq.impl.ResultImpl.map(ResultImpl.java:1318)
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:1560)
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:3951)
        at smx3.tenancy.jooq.Tenancies.findTenanciesByCustomerReference(Tenancies.java:65)
```

Sorry - I should have included that to begin with. I'm working on a standalone example - altho it seems that seems to work as expected.

Interestingly - sometime ago we hit an issue with `timestamp with time zone` fields and the postgresql driver returning `Timestamp` or `OffsetDateTime` on different versions/installs.

We added our `InstantType` before jooq had one built in - that might be the better course of action for our code - but I'll continue to try get this example to break :)

**Comment by lukaseder** [comment] 2020-11-04 10:59
This reproduces it:

```java
public class JDBC {
    public static void main(String[] args) throws Exception {
        SQLDialect dialect = SQLDialect.POSTGRES;

        DatabaseSetup dbSetup = new DatabaseSetup(new Config(dialect, "", false));
        try (Connection c = dbSetup.getConnection()) {
            DSLContext ctx = DSL.using(c, dialect);

            try {
                ctx.execute("create table t (ts timestamptz)");
                ctx.execute("insert into t(ts) values (now())");

                // These work:
                Instant i1 = ctx.select(TS_TZ).from("t").fetchOne().getValue(TS_TZ);
                System.out.println(i1);
                Instant i2 = ctx.resultQuery("select * from t").coerce(TS_TZ).fetchOne().getValue(TS_TZ);
                System.out.println(i2);

                // This fails
                Instant i3 = ctx.fetchOne("select * from t").getValue(TS_TZ);
                System.out.println(i3);
            }
            finally {
                ctx.execute("drop table t");
            }
        }
    }

    public static DataType<Instant> InstantType = SQLDataType.OFFSETDATETIME
        .asConvertedDataType(new InstantConverter());

    public static <T> Field<T> tableField(Table<Record> t, DataType<T> type, String field) {
        return field(name(t.getName(), field), type);
    }

    public static final Field<Instant> TS_TZ = tableField(table(name("t")), InstantType, "ts");
}
```

Producing:

```
2020-11-04T10:58:38.244917Z
2020-11-04T10:58:38.244917Z
Exception in thread "main" java.lang.ClassCastException: class java.time.OffsetDateTime cannot be cast to class java.time.Instant (java.time.OffsetDateTime and java.time.Instant are in module java.base of loader 'bootstrap')
	at org.jooq.testscripts.JDBC.main(JDBC.java:43)
```

That's the same issue as https://github.com/jOOQ/jOOQ/issues/5846. I'm assuming this is what you're doing? The example shows how the exception can be avoided by specifying the field in the `select()` clause or by calling `coerce()` on a plain SQL `ResultQuery`.

If you're doing something different, please let me know and I'll reopening this, otherwise, this is a duplicate of #5846

**Closed by lukaseder** 2020-11-04 10:59 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Feedback Pending, T: Defect

**Comment by talios** [comment] 2020-11-05 00:09
I managed to reproduce the issue locally:

```
/// usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS org.jooq:jooq:3.14.1 org.postgresql:postgresql:42.2.18

import static org.jooq.impl.DSL.field;
import static org.jooq.impl.DSL.name;

import java.sql.*;
import java.time.*;

import org.jooq.*;
import org.jooq.impl.*;

class jooq_instant {
  public static final DataType<Instant> InstantType = SQLDataType.OFFSETDATETIME.asConvertedDataType(new InstantConverter());

  private static class InstantConverter implements Converter<OffsetDateTime, Instant> {
    @Override
    public Instant from(OffsetDateTime databaseObject) {
      return databaseObject == null ? null : databaseObject.toInstant();
    }

    @Override
    public OffsetDateTime to(Instant userObject) {
      return userObject == null ? null : OffsetDateTime.from(userObject);
    }

    @Override
    public Class<OffsetDateTime> fromType() {
      return OffsetDateTime.class;
    }

    @Override
    public Class<Instant> toType() {
      return Instant.class;
    }
  }

  public static <T> Field<T> tableField(Table<Record> t, DataType<T> type, String field) {
    return field(name(t.getName(), field), type);
  }

  public static <T> Field<T> tableField(Table<Record> t, Class<T> type, String field) {
    return field(name(t.getName(), field), type);
  }

  static Table TABLE = DSL.table("pg_stat_activity");
  static Field<Instant> FIELD = tableField(TABLE, InstantType, "backend_start");
  static RecordMapper<Record, Instant> MAPPER = record -> record.getValue(FIELD);

  public static void main(String... args) throws ClassNotFoundException, SQLException {
    Class.forName("org.postgresql.Driver");
    String url = "jdbc:postgresql:template1";
    Connection conn = DriverManager.getConnection(url);
    DSLContext dslContext = DSL.using(conn, SQLDialect.POSTGRES);

    Object instant = dslContext.selectFrom(TABLE).fetch(MAPPER);

    System.exit(0);
  }
}
```

One difference from what I was doing last night in my test is using a record mapper. Running this with `jbang jooq_instant.java` I get:

```
~ took 2s ❯ jbang jooq_instant.java | pbcopy
Nov 05, 2020 1:08:25 PM org.jooq.tools.JooqLogger info
Thank you for using jOOQ 3.14.1

Exception in thread "main" java.lang.ClassCastException: java.time.OffsetDateTime cannot be cast to java.time.Instant
        at jooq_instant.lambda$static$0(jooq_instant.java:48)
        at org.jooq.impl.ResultImpl.map(ResultImpl.java:1318)
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:1560)
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:3951)
        at jooq_instant.main(jooq_instant.java:56)
```

**Comment by talios** [comment] 2020-11-05 00:11
Using the provided `SQLDataType.INSTANT` also yields the same issue with this test.

**Comment by lukaseder** [comment] 2020-11-05 11:01
Yes, that's the same example as mine, where I do this:

```java
Instant i3 = ctx.fetchOne("select * from t").getValue(TS_TZ);
```

You're using plain SQL, which means jOOQ will derive data types from JDBC `ResultSetMetaData`. You'll then run into https://github.com/jOOQ/jOOQ/issues/5846.

**Comment by lukaseder** [comment] 2020-11-05 11:02
For the time being, please use the workaround using `ResultQuery.coerce()` shown here: https://github.com/jOOQ/jOOQ/issues/10853#issuecomment-721663921

**Comment by talios** [comment] 2020-11-05 20:01
> You're using plain SQL

For clarification - given there's no plain SQL in the actual example, it's because I"m using `selectFrom()` here which generates a `select * from` - with no `Field<T>` specifiers - but if I were to use `select(TABLE, FIELD...)` when JOOQ runs the query, because it knows theres a converted field in use it handles the casting/conversion correctly?

That makes sense, I might just make a lint ruling saying "NO" to `selectFrom` in favour of something like:

```
Field<?>[] ALL_FIELDS = {FIELD};
dslContext.select(ALL_FIELDS).from(TABLE).fetch(record -> record.getValue(FIELD));
```

Which looks to work a treat, and generates much nicer SQl.

**Comment by lukaseder** [comment] 2020-11-05 20:49
You're using `DSL.table(String)`. [From the Javadoc](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/impl/DSL.html#table(java.lang.String)):

> A plain SQL table is a table that [...]

Whenever jOOQ doesn't *know* your data types, it has to read them from the JDBC `ResultSetMetaData`. Also, whenever jOOQ doesn't *know* what to project, it will project `*`.

> but if I were to use `select(TABLE, FIELD...)` when JOOQ runs the query, because it knows theres a converted field in use it handles the casting/conversion correctly?

Yes, see again the examples here: https://github.com/jOOQ/jOOQ/issues/10853#issuecomment-721663921

> That makes sense, I might just make a lint ruling saying "NO" to `selectFrom` in favour of something like:

This isn't about `selectFrom`. This is about not providing any way to derive a projection from your code. E.g. you can safely use `selectFrom` with tables from the code generator. Or, if you used the internal (undocumented) APIs to create your own `TableImpl` instances. Or, again, if you explicitly project the columns. Or, if you call `ResultQuery.coerce()`.

But this is simply a bug (in your case): #5846. It should still be possible to delay the conversion until you fetch the value from the record using the type information you're providing.

Anyway. It's always a good idea to project things explicitly. You'll get less data transfer, less I/O in the database, more chances of join elimination, etc.

**Comment by talios** [comment] 2020-11-06 02:23
> You're using DSL.table(String). 

Ahh! Now I get you. I had assumed (quite wrongly) assumed the types on the `Field<T>` instances influenced that. All good.

Cheers.
