### ISSUE TITLE
Add support for date_trunc(DatePart.QUARTER) in SQLDialect.POSTGRES

### ISSUE THREAD

**Issue by nielsmeijer** [jOOQ/jOOQ#16053] opened 2024-01-10 11:45 UTC
### Use case

When executing a `date_trunc` function with a `DatePart.QUARTER` on `SQLDialect.POSTGRES`, a `java.lang.UnsupportedOperationException: Unknown date part : QUARTER` is raised. 

Example code:

```java
context.select(trunc(TABLE.DATE, DatePart.QUARTER))
.from(TABLE)
.fetch()
```

While the following database query works on postgresql:

```sql
select date_trunc('quarter', date)
from table
```

### Possible solution

Add `DatePart.QUARTER` to `org.jooq.impl.TruncDate`. 

```java
  case POSTGRES: {
                switch (part) {
                    case YEAR:   keyword = "year";   break;
                    case QUARTER:  keyword = "quarter";  break;
                    case MONTH:  keyword = "month";  break;
                    case DAY:    keyword = "day";    break;
                    case HOUR:   keyword = "hour";   break;
                    case MINUTE: keyword = "minute"; break;
                    case SECOND: keyword = "second"; break;
                    default: throwUnsupported();
                }
```

### Possible workarounds

Rendering the inline function with DSL.function is of course possible. 

```java
context
.select(function("date_trunc", LocalDate.class, inline(DatePart.QUARTER.toName()), TABLE.DATE))
.from(TABLE)
.fetch();
```

### jOOQ Version

3.19.1

### Database product and version

PostgreSQL 16.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2), 64-bit

### Java Version

17

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.1

**Comment by lukaseder** [comment] 2024-01-17 14:43
Thanks for your suggestion. Duplicate of:

- https://github.com/jOOQ/jOOQ/issues/8418

**Closed by lukaseder** 2024-01-17 14:43 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, R: Duplicate, E: All Editions
