### ISSUE TITLE
PostgresConnectionClosedException when using batch request

### ISSUE THREAD

**Issue by davinkevin** [jOOQ/jOOQ#12774] opened 2021-12-30 18:52 UTC
### Expected behavior

No error during jooq calls, even if the result is ok.

### Actual behavior

Some `org.jooq.exception.DataAccessException: SQL [org.jooq.impl.BatchMultiple@267aa523]; Connection closed` appears

### Steps to reproduce the problem

You can find a complete configured project to reproduce this case [here](https://gitlab.com/davinkevin.fr/issues/jooq/r2dbc-pg-error-with-block).

The problem is very similar to what we saw in #12108, but still present in JOOQ 3.15.5.

If I write this:

```kotlin
@JooqR2DBCTest
@Import(ExampleRepository::class)
internal class ExampleRepositoryTest(
    @Autowired val query: DSLContext,
    @Autowired val repository: ExampleRepository
) {

    @BeforeEach
    fun createTable() {
        Hooks.onOperatorDebug()
        query
            .createTableIfNotExists(EXAMPLE)
            .column(ID)
            .column(DESC)
            .primaryKey(ID)
            .toMono()
            .block()
    }

    @Nested
    @DisplayName("should find by id")
    inner class ShouldFindById {

        @BeforeEach
        fun beforeEach() {
            query.batch(
                truncate(EXAMPLE).cascade(),
                insertInto(EXAMPLE)
                    .set(ID, UUID.fromString("34c5aada-6e9e-4fe2-96aa-421c8a8715ec"))
                    .set(DESC, "FOO"),
                insertInto(EXAMPLE)
                    .set(ID, UUID.fromString("b2861264-1968-410b-96ca-eac3a6292d29"))
                    .set(DESC, "BAR")
            )
                .toMono()
                .block()
        }

        @Test
        fun `with success`() {
            /* Given */
            /* When */
            StepVerifier.create(repository.findOne(UUID.fromString("b2861264-1968-410b-96ca-eac3a6292d29")))
            /* Then */
                .expectSubscription()
                .expectNext(Example(
                    id = UUID.fromString("b2861264-1968-410b-96ca-eac3a6292d29"),
                    desc = "BAR"
                ))
                .verifyComplete()
        }

    }

    companion object {
        @JvmStatic
        private  val pgContainer = PostgreSQLContainer(DockerImageName.parse("postgres:12.3-alpine"))
            .withUsername("username")
            .withPassword("password")
            .withDatabaseName("db")
            .waitingFor(HostPortWaitStrategy())

        @BeforeAll
        @JvmStatic
        fun beforeAll() {
            pgContainer.start()
        }

        @JvmStatic
        @DynamicPropertySource
        fun registerDynamicProperties(registry: DynamicPropertyRegistry) {
            registry.add("spring.r2dbc.url") { pgContainer.jdbcUrl.replace("jdbc", "r2dbc").also { println("the url is $it") } }
            registry.add("spring.r2dbc.username", pgContainer::getUsername)
            registry.add("spring.r2dbc.password", pgContainer::getPassword)
        }
    }
}
```

The execution produces the following result:

```log
2021-12-30 19:42:24.392  INFO   --- [actor-tcp-nio-1] org.jooq.Constants                       : 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.15.5
                                      
2021-12-30 19:42:24.394  INFO   --- [actor-tcp-nio-1] org.jooq.Constants                       : 

jOOQ tip of the day: Want to learn more about SQL? Check out our many blog posts: https://blog.jooq.org/sql

2021-12-30 19:42:24.532 ERROR   --- [actor-tcp-nio-2] reactor.core.publisher.Operators         : Operator called default onErrorDropped

org.jooq.exception.DataAccessException: SQL [org.jooq.impl.BatchMultiple@267aa523]; Connection closed
	at org.jooq.impl.Tools.translate(Tools.java:2978)
	at org.jooq.impl.Tools.translate(Tools.java:2962)
	at org.jooq.impl.R2DBC$AbstractResultSubscriber.onError(R2DBC.java:263)
	at reactor.core.publisher.StrictSubscriber.onError(StrictSubscriber.java:106)
	at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onError(FluxDiscardOnCancel.java:92)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.signalAsyncError(FluxWindowPredicate.java:352)
	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.checkTerminated(FluxWindowPredicate.java:534)
	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.drainLoop(FluxWindowPredicate.java:486)
	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.drain(FluxWindowPredicate.java:430)
	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onError(FluxWindowPredicate.java:289)
	at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onError(FluxDiscardOnCancel.java:92)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at reactor.core.publisher.FluxCreate$BaseSink.error(FluxCreate.java:453)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:781)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.error(FluxCreate.java:726)
	at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:230)
	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:169)
	at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:735)
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:986)
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:860)
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:767)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:503)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:295)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:279)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:388)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:404)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.r2dbc.postgresql.client.ReactorNettyClient$PostgresConnectionClosedException: Connection closed
	at io.r2dbc.postgresql.client.ReactorNettyClient.lambda$static$1(ReactorNettyClient.java:102)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.FluxCreate] :
	reactor.core.publisher.Flux.create(Flux.java:643)
	io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.addConversation(ReactorNettyClient.java:786)
Error has been observed at the following site(s):
	*_______Flux.create ⇢ at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.addConversation(ReactorNettyClient.java:786)
	|_ Flux.doOnDiscard ⇢ at io.r2dbc.postgresql.client.SimpleQueryMessageFlow.exchange(SimpleQueryMessageFlow.java:49)
	|_ Flux.windowUntil ⇢ at io.r2dbc.postgresql.SimpleQueryPostgresqlStatement.execute(SimpleQueryPostgresqlStatement.java:152)
	|_         Flux.map ⇢ at io.r2dbc.postgresql.SimpleQueryPostgresqlStatement.execute(SimpleQueryPostgresqlStatement.java:152)
Original Stack Trace:
		at io.r2dbc.postgresql.client.ReactorNettyClient.lambda$static$1(ReactorNettyClient.java:102)
		at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.close(ReactorNettyClient.java:1018)
		at io.r2dbc.postgresql.client.ReactorNettyClient.drainError(ReactorNettyClient.java:518)
		at io.r2dbc.postgresql.client.ReactorNettyClient.lambda$close$8(ReactorNettyClient.java:191)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
		at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.lambda$cancel0$5(R2DBC.java:583)
		at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:209)
		at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.cancel0(R2DBC.java:578)
		at org.jooq.impl.R2DBC$AbstractSubscription.complete(R2DBC.java:197)
		at org.jooq.impl.R2DBC$AbstractSubscription.cancel(R2DBC.java:183)
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:81)
		at org.jooq.impl.Internal$1.onNext(Internal.java:433)
		at org.jooq.impl.R2DBC$Forwarding.onNext(R2DBC.java:229)
		at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
		at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
		at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
		at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:229)
		at reactor.core.publisher.FluxWindowPredicate$WindowFlux.checkTerminated(FluxWindowPredicate.java:766)
		at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:660)
		at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:746)
		at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onComplete(FluxWindowPredicate.java:812)
		at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:241)
		at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onNext(FluxDiscardOnCancel.java:86)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
		at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154)
		at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:735)
		at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:986)
		at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:860)
		at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:767)
		at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:503)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:295)
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
		at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:279)
		at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:388)
		at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:404)
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:834)

BUILD SUCCESSFUL in 7s
```

### Versions

- jOOQ: 3.15.5
- Java: 17
- Database (include vendor): PostgreSQL
- OS: MacOS
- JDBC Driver (include name if inofficial driver): R2DBC 0.8.10

**Comment by lukaseder** [comment] 2022-01-03 15:09
Thanks a lot for your report. I'll look into this soon

**Comment by lukaseder** [comment] 2023-01-17 13:24
I've fixed a few related issues just recently. Definitely worth upgrading to 3.17.7. My gut feeling says that this issue here isn't fixed yet, given this particular implementation doesn't pass the TCK yet, though: https://github.com/jOOQ/jOOQ/issues/14495

**Comment by lukaseder** [comment] 2024-09-23 15:16
Looking into this again. Another user has made a suggestion on how to fix this:

- https://github.com/jOOQ/jOOQ/issues/17094

The suggested fix would remove the exception from the logs in your reproducer.

**Comment by lukaseder** [comment] 2024-09-23 15:42
I'm aware that it's been some time since your report, thank you for your patience. If you're still using jOOQ with R2DBC and are still running into this problem, I would appreciate your feedback on any of the upcoming versions 3.20.0, 3.19.13, 3.18.20, 3.17.29 to see if they fix the problem for you, outside of the reproducer.

**Comment by davinkevin** [comment] 2024-09-23 16:01
No, I switched back to `jdbc` 😇. And I don't know if it will be simple for me to test it on top of a previous version 🤔 

Feel free to close in that case.

**Comment by lukaseder** [comment] 2024-09-24 07:12
Thanks for the feedback, @davinkevin. Switching back to JDBC seems to be the pragmatic choice, quite often :) No worries, it does look like your issue is the same as #17094, so I'm closing this as a duplicate.

**Closed by lukaseder** 2024-09-24 07:12 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Feedback Pending, E: All Editions
