### ISSUE TITLE
Can't insert OffsetDateTime in PostgreSQL with ParamCastMode.NEVER

### ISSUE THREAD

**Issue by cmerkel-eitco** [jOOQ/jOOQ#9174] opened 2019-09-05 13:27 UTC
### Description:
When ParamCastMode is set to NEVER it is not possible to insert a value of type OffsetDateTime in a column of type timestamptz in a PostgreSQL database. JOOQ still converts the value to a string expression like "timestamp with time zone '2019-09-05 15:02:14.5015411+02:00'" instead of just passing it to the JDBC driver. The documentation for the JDBC driver states that the driver is able to handle values of that type: 
https://jdbc.postgresql.org/documentation/head/8-date-time.html

Log with ParamCastMode.DEFAULT:

```
org.jooq.tools.LoggerListener            : Executing query          : insert into "datetimetest" ("int", "datetime") values (?, cast(? as timestamp with time zone))
org.jooq.tools.LoggerListener            : -> with bind values      : insert into "datetimetest" ("int", "datetime") values (1, timestamp with time zone '2019-09-05 15:02:14.5015411+02:00')
```

Log with ParamCastMode.NEVER:

```
org.jooq.tools.LoggerListener            : Executing query          : insert into "datetimetest" ("int", "datetime") values (?, ?)
org.jooq.tools.LoggerListener            : -> with bind values      : insert into "datetimetest" ("int", "datetime") values (1, timestamp with time zone '2019-09-05 15:10:29.3311661+02:00')
...
org.postgresql.util.PSQLException: ERROR: column "datetime" is of type timestamp with time zone but expression is of type character varying
```

### Steps to reproduce:
I used a simple Spring Boot app from spring Initializr with spring-boot-starter-jooq and one bean to test:

```java
@Component
public class TestBean implements InitializingBean {

    private static final Logger LOGGER = LoggerFactory.getLogger(TestBean.class);

    private final DataSource dataSource;
    private final DSLContext context;

    @Autowired
    public TestBean(DataSource dataSource, DSLContext context) {
        this.dataSource = dataSource;
        this.context = context;
        context.settings().setParamCastMode(ParamCastMode.NEVER);
    }

    @Override
    public void afterPropertiesSet() throws Exception {

        try {
            Table<Record> table = DSL.table(DSL.name("datetimetest"));
            Field<Object> field1 = DSL.field(DSL.name("datetimetest", "int"));
            Field<Object> field2 = DSL.field(DSL.name("datetimetest", "datetime"));

            OffsetDateTime datetime = OffsetDateTime.now();

            context.insertInto(table, field1, field2).values(1, datetime).execute();
        } catch (Exception e) {
            LOGGER.error(e.getMessage());
        }

        // this works:
        NamedParameterJdbcTemplate template = new NamedParameterJdbcTemplate(dataSource);
        String sql = "insert into \"datetimetest\" (\"int\",\"datetime\") values (:p1, :p2)";
        Map<String, Object> parameters = Map.of("p1", 2, "p2", OffsetDateTime.now());

        template.execute(sql, parameters, PreparedStatement::execute);
    }
}
```

Database table:

```sql
create table datetimetest
(
    datetime timestamp with time zone,
    int      integer
);
```
### Versions:

- spring-boot-starter-jooq: 2.1.7.RELEASE
- jOOQ: 3.11.11
- Java: OpenJdk 11.0.1+13
- Database (include vendor): PostgreSQL 10.5-1
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): postgresql-42.2.6

**Comment by lukaseder** [comment] 2020-07-09 13:36
Looking into this now. This isn't strictly related to the `ParamCastMode.NEVER` setting, which just removes the cast, but doesn't influence how the bind variable is passed to the JDBC driver.

For backwards compatibility reasons, we're still binding JSR 310 types as strings in most dialects, as JDBC drivers haven't adopted them immediately. There's a pending feature request to pass the JSR 310 type instead of the string: https://github.com/jOOQ/jOOQ/issues/9902

Once that is implemented, this issue will go away.

I'm closing this as a duplicate of #9902 (and will look into increasing #9902's priority)

Thanks again for your report.

**Closed by lukaseder** 2020-07-09 13:36 UTC
Labels: C: DB: PostgreSQL, C: Functionality, E: All Editions, P: Medium, T: Defect
