### ISSUE TITLE
Feedback about manual section "jooq-in-7-steps-step3"

### ISSUE THREAD

**Issue by jonathanl-telenav** [jOOQ/jOOQ#13981] opened 2022-09-12 20:59 UTC
### The documentation URL

https://www.jooq.org/doc/3.17/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step3/

### Feedback

It's kinda sad that you can't just run jooq without aggregating the jars and putting them on the class path and so on. Would be nice to just run jooq.sh or something.

**Comment by lukaseder** [comment] 2022-09-13 06:04
Thanks a lot for your feedback.

Indeed, that tutorial is quite dated. Our plan is to replace it with a demo based on github. All the manual code examples will then be downloadable and executable from github.

Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/13617

**Closed by lukaseder** 2022-09-13 06:04 UTC
Labels: T: Enhancement, C: Documentation, P: Medium, E: All Editions
