### ISSUE TITLE
[Postgres] ArrayIndexOutOfBoundsException when generating class for index with INCLUDE-columns

### ISSUE THREAD

**Issue by jaromor** [jOOQ/jOOQ#10727] opened 2020-10-09 09:26 UTC
Specify an index with INCLUDE column(s):
`CREATE UNIQUE INDEX users_external_id ON web.users (external_id) INCLUDE (id);`

...jOOQ then treats all columns included in the index as if they were supposed to have ORDER specified (which for INCLUDE-columns isn't the case):

PostgresDatabase.java:
![image](https://user-images.githubusercontent.com/40000923/95566516-f1b06580-0a21-11eb-82e0-f2adb9df93a3.png)

**Comment by jaromor** [comment] 2020-10-09 09:36
Also it seems it is not possible to exclude indexes from generating...?

**Comment by lukaseder** [comment] 2020-10-09 10:08
Duplicate of #10726

**Closed by lukaseder** 2020-10-09 10:08 UTC
Labels: C: Code Generation, E: All Editions, P: Medium, R: Duplicate, T: Defect
