### ISSUE TITLE
MySQL CTE INSERT SELECT generates SQL in incorrect order

### ISSUE THREAD

**Issue by krnhotwings** [jOOQ/jOOQ#11365] opened 2021-02-03 16:49 UTC
### Expected behavior

MySQL 8.0 expects `INSERT SELECT` statements that include CTEs to be in the order: `INSERT ... WITH ... SELECT`

Example:
```sql
insert into `my_table` (
  `col1`
)
with `bogus_cte`(`bogus_col1`) as (
  select 'bogus value'
  from dual
)
select
  'doesn''t matter'
from dual
```

### Actual behavior

jooq generates SQL in the order: `WITH ... INSERT ... SELECT`

```sql
with `bogus_cte`(`bogus_col1`) as (
  select 'bogus value'
  from dual
)
insert into `my_table` (
  `col1`
)
select
  'doesn''t matter'
from dual
```

### Steps to reproduce the problem

```sql
CREATE TABLE my_table (
  col1 VARCHAR(100)
);
```

```scala
val bogusCte = DSL.name("bogus_cte").fields("bogus_col1").as(create.select(DSL.value("bogus value")))

create.`with`(bogusCte)
  .insertInto(MY_TABLE, MY_TABLE.COL1)
  .select(create.select(DSL.value("doesn't matter")))
```

### Versions

- jOOQ: 3.13.2, 3.14.7
- Java: OpenJDK 11.0.9.1
- Database (include vendor): MySQL 8.0.23
- OS: Ubuntu 20.04.2
- JDBC Driver (include name if inofficial driver): 8.0.16

**Comment by lukaseder** [comment] 2021-02-03 17:02
Thanks a lot for your report.

You're right, we could emulate this PostgreSQL / SQL Server syntax on other dialects as well. For the time being, just use the MySQL native syntax in jOOQ directly, instead of the PG / SQL Server one:

```kotlin
create
  .insertInto(MY_TABLE, MY_TABLE.COL1)
  .select(create.`with`(bogusCte).select(DSL.value("doesn't matter")))
```

**Comment by lukaseder** [comment] 2021-02-03 17:06
This is a duplicate of https://github.com/jOOQ/jOOQ/issues/8437

**Comment by lukaseder** [comment] 2021-02-03 17:07
The emulation is not as simple as it may look at first. Here's a more tricky case:

```sql
with x (i) as (select 1)
insert into t
values ((select i from x)), ((select i from x));
```

Emulation:

```sql
insert into t
values ((
  with x (i) as (select 1)
  select i from x
)), ((
  with x (i) as (select 1)
  select i from x
));
```

**Closed by lukaseder** 2021-02-03 17:06 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect

**Comment by lukaseder** [comment] 2021-02-03 17:07
For the record, please observe the `@Support` annotation on all of jOOQ's API to assess whether your dialect supports a given method. `WithStep.insertInto()` is annotated as:

```java
@Support({ AURORA_POSTGRES, COCKROACHDB, POSTGRES, SQLDATAWAREHOUSE, SQLITE, SQLSERVER })
```
