### ISSUE TITLE
Feedback about manual section "settings-listener-invocation-order"

### ISSUE THREAD

**Issue by savoury-square** [jOOQ/jOOQ#13452] opened 2022-04-14 03:54 UTC
>  jOOQ offers a variety of SPIs in the [Configuration](https://www.jooq.org/doc/3.16/manual/sql-building/dsl-context/) object.

I'm not sure that `SPI` has been introduced at this point in the documentation so it may be helpful to include the meaning of that acronym here. 
Thanks for all the great work!

----
See: https://www.jooq.org/doc/3.16/manual/sql-building/dsl-context/custom-settings/settings-listener-invocation-order/

**Comment by lukaseder** [comment] 2022-04-14 10:27
Thanks for your message. It's a very common term in programming: https://en.wikipedia.org/wiki/Service_provider_interface

There are ~28 references to SPI in the manual. Rather than fixing these individually, maybe we need a glossary whose terms will be automatically linked to wikipedia from wherever in the manual?

I'd like to find a cost/benefit effective solution here...

**Comment by lukaseder** [comment] 2022-04-14 10:40
Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/2194 (glossary)

**Closed by lukaseder** 2022-04-14 10:40 UTC
Labels: T: Enhancement, C: Documentation, P: Medium, E: All Editions
