### ISSUE TITLE
Code generator: Postgres 14: Exception while executing meta query: ERROR: column c.consrc does not exist

### ISSUE THREAD

**Issue by jonathancast** [jOOQ/jOOQ#14419] opened 2022-12-16 20:17 UTC
[WARNING] SQL exception            : Exception while executing meta query: ERROR: column c.consrc does not exist
  Hint: Perhaps you meant to reference the column "c.conkey" or the column "c.conbin".
  Position: 127

Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new

```sql
with recursive "domains"("domain_id", "base_id", "typbasetype", "src") as (
  (
    select 
      "d".oid, 
      "d".oid, 
      "d"."typbasetype", 
      array["c"."consrc"]
    from "pg_catalog"."pg_type" as "d"
      join "pg_catalog"."pg_namespace" as "n"
      on "n".oid = "d"."typnamespace"
      left outer join "pg_catalog"."pg_constraint" as "c"
      on "d".oid = "c"."contypid"
    where (
      "d"."typtype" = 'd'
      and "n"."nspname" in ('public')
    )
  )
  union all (
    select 
      "domains"."domain_id", 
      "d".oid, 
      "d"."typbasetype", 
      case
        when "c"."consrc" is null then "domains"."src"
        else array_append("domains"."src", "c"."consrc")
      end
    from "domains"
      join "pg_catalog"."pg_type" as "d"
      on "domains"."typbasetype" = "d".oid
      left outer join "pg_catalog"."pg_constraint" as "c"
      on "d".oid = "c"."contypid"
  )
)
select 
  "n"."nspname", 
  "d"."typname", 
  "d"."typnotnull", 
  "d"."typdefault", 
  "b"."typname", 
  "b"."typlen", 
  "domains"."src"
from "pg_catalog"."pg_type" as "d"
  join "domains"
  on (
    "domains"."typbasetype" = 0
    and "domains"."domain_id" = "d".oid
  )
  join "pg_catalog"."pg_type" as "b"
  on "domains"."base_id" = "b".oid
  join "pg_catalog"."pg_namespace" as "n"
  on "n".oid = "d"."typnamespace"
where (
  "d"."typtype" = 'd'
  and "n"."nspname" in ('public')
)
order by 
  "n"."nspname", 
  "d"."typname"
```

Configuration is

        <configuration>
          <skip>${database.skip}</skip>

          
          <jdbc>
            <driver>org.postgresql.Driver</driver>
            <url>jdbc:postgresql://${database.hostname}/</url>
            <user>${database.username}</user>
            <password>${database.password}</password>
          </jdbc>

          <generator>
            <database>
              <name>org.jooq.util.postgres.PostgresDatabase</name>
              <includes>.*</includes>
              <excludes>
                audit_.*
              </excludes>
              <inputSchema>public</inputSchema>
            </database>
            <generate/>

            <target>
              
              <packageName>arbitifer.datasource.database</packageName>

              
              <directory>src/main/java</directory>
            </target>
          </generator>
        </configuration>

The error does not seem to prevent the code from being generated as desired.

I'm running Postgres 14.5 from the distribution repos on Ubuntu 22.04 LTS.

**Comment by lukaseder** [comment] 2022-12-19 09:21
Thanks for your report. You haven't mentioned the jOOQ version you're using. This looks like a duplicate of https://github.com/jOOQ/jOOQ/issues/9331, can you confirm?

**Comment by lukaseder** [comment] 2023-01-01 13:50
As far as I can tell, this is a duplicate of #9331. If you have additional findings, just let me know and I can have another look.

**Closed by lukaseder** 2023-01-01 13:50 UTC
Labels: T: Defect, C: Code Generation, C: DB: PostgreSQL, P: Medium, R: Duplicate, E: All Editions
