### ISSUE TITLE
Password for MS Access MDB file Inquiry

### ISSUE THREAD

**Issue by shivchadha** [jOOQ/jOOQ#6960] opened 2017-12-28 22:57 UTC
I tried to use the "access-sakila.mdb" file in MS Access, but was prompted to enter a password. I entered my MS Access/365 password, to no avail.

From my understanding, these file types can be encrypted/given passwords? Has anyone else experienced this and found a work-around?

**Comment by lukaseder** [comment] 2017-12-29 08:28
Duplicate of https://github.com/jOOQ/jOOQ/issues/6959

**Closed by lukaseder** 2017-12-29 08:28 UTC
Labels: C: DB: Access, P: Low, R: Duplicate, T: Support request

**Comment by fortunewalla** [comment] 2024-10-18 10:51
https://github.com/ivanceras/sakila/issues/4#issuecomment-2422184496
