### ISSUE TITLE
LiquibaseDatabase should support using an external database connection

### ISSUE THREAD

**Issue by Quicksteve** [jOOQ/jOOQ#11067] opened 2020-12-01 19:46 UTC
### Use case:

It would be great if the Liquibase files could be applied to a external database (Postgres in this case), as otherwise using custom SQL or other DB-specific features is not possible.

### Possible solution you'd like to see:

Maybe `AbstractInterpretingDatabase` could be changed to delegate to a Database implementation instead of inheriting from `H2Database`?

### Possible workarounds:

It can be worked around by applying the Liquibase scripts manually on the external DB, then running jOOQ on the external DB directly.

### Versions:

- jOOQ: 3.12.3
- Java: AdoptOpenJDK 11.0.9
- Database (include vendor): Postgres 12
- OS: Windows 10/Ubuntu 18.04
- JDBC Driver (include name if inofficial driver): `org.postgresql.Driver`

**Comment by lukaseder** [comment] 2020-12-02 11:29
Thanks for your suggestion. If you don't want to manage this external database, then this will already be covered in https://github.com/jOOQ/jOOQ/issues/6551 (using testcontainers) or https://github.com/jOOQ/jOOQ/issues/7034 (interpret the SQL rather than execute it).

If you want to manage this external database, then the suggested approach is not to use the `LiquibaseDatabase` migration simulation, but run the actual thing via Liquibase itself. This isn't a workaround. If you have access to an actual database, that will always be the better approach. The simulation will always be limited.

Closing as duplicate of other issues.

**Closed by lukaseder** 2020-12-02 11:29 UTC
Labels: T: Enhancement
