### ISSUE TITLE
AbstractField#like(String) pattern is passed to custom converter as-is

### ISSUE THREAD

**Issue by AlexMisha** [jOOQ/jOOQ#12687] opened 2021-12-01 16:49 UTC
Hi!

I'm trying to migrate jooq version of my project from 3.12 to 3.15.
After fixing some migration issues I've found one of my tests is broken.

Those test runs a query like this:
`select * from table where field like 'pattern%';`
and asserts result is empty.

Field is declared as varchar and mapped to some custom java class via `Converter<String, CustomType>` implementation which additionally verifies field values which satisfy some rules.

jooq 3.12 doesn't invoke converter for building such queries at all and everything is ok.
But jooq 3.15 uses converter for some reasons and passes pattern as-is which breaks verification.

I suppose jooq would later use "stored" value in CustomType for building a query via `Converter#to`, so such "storing" may lead to pattern corruption according to specific `Converter` implementations.

### Expected behavior

Custom converter should not be invoked during building of queries which use fields of custom types conforms to string-like types.

### Actual behavior

Converter#from(U) is invoked with pattern as-is (e.g. 'pattern%').

### Steps to reproduce the problem

MCVE - https://github.com/AlexMisha/jOOQ-mcve

- Declare varchar field in table, CustomType, CustomTypeConverter and mapping in forcedTypes
- CustomTypeConverter throws exception if '%' character is present in value for demonstration purposes
- Write a query with LIKE predicate using CustomType field
- Building a query fails with exception thrown by CustomTypeConverter

Reproducible in main branch.

### Versions

- jOOQ: 3.15.4, main branch
- Java: 11

Seems like regression of `DSL/Tools#nullSafe`.
3.12.4 `DSL`
```
    protected static <T> Field<T> nullSafe(Field<T> field, DataType<?> type) {
        return field == null ? (Field<T>) val((T) null, type) : field;
    }
```

vs 3.15.4 `Tools`
```
    static final <T> Field<T> nullSafe(Field<T> field, DataType<?> type) {
        return field == null
             ? (Field<T>) DSL.val((T) null, type)
             : convertVal(field, type);
    }

    @SuppressWarnings("unchecked")
    static final <T> Field<T> convertVal(Field<T> field, DataType<?> type) {
        return isVal(field)
             ? (Field<T>) extractVal(field).convertTo(type)
             : field;
    }
```

Anyway it seems like I have no possibility to determine in which context my converter invoked is to avoid some corrupting modifications of pattern.

Best regards.

**Comment by lukaseder** [comment] 2022-03-08 16:30
Thanks a lot for your report and your patience. I'm afraid, the notification email must have slipped by.

This looks like a duplicate of https://github.com/jOOQ/jOOQ/issues/12472, which also documents workarounds.

**Comment by lukaseder** [comment] 2024-11-06 12:26
Related issue: 

- https://github.com/jOOQ/jOOQ/issues/17561

**Comment by lukaseder** [comment] 2024-11-08 08:38
This is indeed a duplicate of https://github.com/jOOQ/jOOQ/issues/12472

**Closed by lukaseder** 2024-11-08 08:38 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by lukaseder** [comment] 2024-11-08 08:44
> Seems like regression of `DSL/Tools#nullSafe`.

Likely interoduced with this change in jOOQ 3.14:

- https://github.com/jOOQ/jOOQ/issues/10438
