### ISSUE TITLE
KotlinGenerator - isKotlinNotNullPojoAttributes setting prevents generated DAO to set serial ID to pojo

### ISSUE THREAD

**Issue by VitaPlsek** [jOOQ/jOOQ#15559] opened 2023-09-08 11:18 UTC
### Expected behavior

Generated DAO method insert update id of Pojo, when it is generated using KotlinGenerator and isKotlinNotNullPojoAttributes attribut set to true

### Actual behavior

Id of pojo is not updated

### Steps to reproduce the problem

DDL
```
CREATE TABLE client
(
    id     BIGSERIAL PRIMARY KEY,
    name   VARCHAR(64) NOT NULL,
    active BOOLEAN     NOT NULL,
    age    INTEGER
);
```

When I try to insert POJO, using generated dao, its id of serial column is null 

```
val client = Client(name = "test", active = true)
clientDao.insert(client)

client.id shouldNotBe null
```            

It looks the problem isin KotlinGenerator's `isKotlinNotNullPojoAttributes` setting. When this setting is not set to false, it works

```
jooq {
    version.set("3.18.6")

    configurations {
        create("main") {
            jooqConfiguration.apply {
                jdbc.apply {
                    url = postgresContainer?.jdbcUrl
                    user = postgresContainer?.username
                    password = postgresContainer?.username
                }

                logging = org.jooq.meta.jaxb.Logging.WARN
                generator.apply {
                    name = "org.jooq.codegen.KotlinGenerator"
                    database.apply {
                        name = "org.jooq.meta.postgres.PostgresDatabase"

                        inputSchema = "public"
                        isOutputSchemaToDefault = true
                        excludes = "databasechangelog|databasechangeloglock"
                    }
                    generate.apply {
                        isDaos = true
                        isPojos = true
                        isRecords = true
                        isSpringAnnotations = true

                        isKotlinNotNullPojoAttributes = true // <------------- when set to false, it works
                    }
                    target.apply {
                        packageName = "cz.benefitplus.portals.assistant.jooq"
                    }
                    strategy.name = "org.jooq.codegen.DefaultGeneratorStrategy"
                }
            }
        }
    }
}
````

### jOOQ Version

3.18.6

### Database product and version

POSTGRESQL 14.8

### Java Version

17

**Comment by lukaseder** [comment] 2023-09-08 14:40
Thanks a lot for your report. Will look into this soon.

**Comment by lukaseder** [comment] 2023-09-08 16:01
It seems that this issue fixes it:

- https://github.com/jOOQ/jOOQ/issues/15563

This is the change (https://github.com/jOOQ/jOOQ/commit/312901e7b4ad280e34dc2384d04fbfaf846a6262.patch):

```patch
From 312901e7b4ad280e34dc2384d04fbfaf846a6262 Mon Sep 17 00:00:00 2001
From: Lukas Eder <lukas.eder@datageekery.com>
Date: Fri, 8 Sep 2023 17:17:00 +0200
Subject: [PATCH] [jOOQ/jOOQ#15563] DefaultRecordMapper should skip most
 mappers when an instance is provided

---
 .../org/jooq/impl/DefaultRecordMapper.java    | 22 ++++++++++---------
 1 file changed, 12 insertions(+), 10 deletions(-)

diff --git a/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java b/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java
index 875932cfa4..f49261efcb 100644
--- a/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java
+++ b/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java
@@ -382,16 +382,18 @@ private final void init(E instance) {
             return;
         }
 
-        if (Stream.class.isAssignableFrom(type)) {
-            delegate = r -> (E) Stream.of(((FieldsImpl<R>) rowType).mapper(configuration, Object[].class).map(r));
-            return;
-        }
+        if (instance == null) {
+            if (Stream.class.isAssignableFrom(type)) {
+                delegate = r -> (E) Stream.of(((FieldsImpl<R>) rowType).mapper(configuration, Object[].class).map(r));
+                return;
+            }
 
-        // [#1470] Return a proxy if the supplied type is an interface
-        // [#10071] [#11148] Primitive types are abstract! They're mapped by a ConverterProvider only later
-        if (Modifier.isAbstract(type.getModifiers()) && !type.isPrimitive()) {
-            delegate = new ProxyMapper();
-            return;
+            // [#1470] Return a proxy if the supplied type is an interface
+            // [#10071] [#11148] Primitive types are abstract! They're mapped by a ConverterProvider only later
+            if (Modifier.isAbstract(type.getModifiers()) && !type.isPrimitive()) {
+                delegate = new ProxyMapper();
+                return;
+            }
         }
 
         // [#2989] [#2836] Records are mapped
@@ -401,7 +403,7 @@ private final void init(E instance) {
         }
 
         // [#10071] Single-field Record1 types can be mapped if there is a ConverterProvider allowing for this mapping
-        if ((debugVTFL = fields.length == 1) && (debugVTCP = Tools.converter(configuration, instance, (Class) fields[0].getType(), type) != null)) {
+        if ((debugVTFL = fields.length == 1) && instance == null && (debugVTCP = Tools.converter(configuration, instance, (Class) fields[0].getType(), type) != null)) {
             delegate = new ValueTypeMapper();
             return;
         }
```

It's weird to me, because it doesn't seem strictly related, but with this fix, I can no longer reproduce the issue you've described (even for multiple columns). Can you confirm this on your end?

**Comment by VitaPlsek** [comment] 2023-09-12 14:17
I have tried to build and test it with 3.18-7-SNAPSHOT and it behaves the same, still does not set the ID

**Comment by lukaseder** [comment] 2023-09-29 13:32
https://github.com/jOOQ/jOOQ/issues/15564 would probably fix the issue

**Comment by lukaseder** [comment] 2023-09-29 14:51
So, this should indeed be fixed now with https://github.com/jOOQ/jOOQ/issues/15564

Fixed in versions:

- 3.19.0
- 3.18.7 (https://github.com/jOOQ/jOOQ/issues/15659)
- 3.17.16 (https://github.com/jOOQ/jOOQ/issues/15660)
- 3.16.22 (https://github.com/jOOQ/jOOQ/issues/15661)

**Closed by lukaseder** 2023-09-29 14:51 UTC
Labels: T: Defect, C: Functionality, P: Medium, C: Integration: Kotlin, E: All Editions

**Comment by VitaPlsek** [comment] 2023-10-12 12:31
I can confirm that it works in 3.18.7. Thank you :)

**Comment by lukaseder** [comment] 2023-10-12 12:36
Thanks for the feedback, @VitaPlsek
