### ISSUE TITLE
meta().getTables() fails for H2 2.0.202

### ISSUE THREAD

**Issue by lalithsuresh** [jOOQ/jOOQ#12685] opened 2021-11-30 20:59 UTC
### Expected behavior

We have code that uses information from `meta()` to tell the type of tables and fields, that fails with the newest release of H2.

Here's a test that reproduces the problem.

```java
    @Test
    public void testJooqH2() {
        final DSLContext conn = DSL.using("jdbc:h2:mem:");
        conn.execute("create table t1(c1 integer)");
        System.out.println(conn.meta().getTables());
    }
```

### Actual behavior

`getTables()` throws this exception:

```

org.jooq.exception.DataAccessException: SQL [select INFORMATION_SCHEMA.CONSTRAINTS.TABLE_CATALOG, INFORMATION_SCHEMA.CONSTRAINTS.TABLE_SCHEMA, INFORMATION_SCHEMA.CONSTRAINTS.TABLE_NAME, INFORMATION_SCHEMA.CONSTRAINTS.CONSTRAINT_NAME, INFORMATION_SCHEMA.INDEXES.COLUMN_NAME, INFORMATION_SCHEMA.INDEXES.ORDINAL_POSITION from INFORMATION_SCHEMA.CONSTRAINTS join INFORMATION_SCHEMA.INDEXES on (INFORMATION_SCHEMA.CONSTRAINTS.TABLE_SCHEMA = INFORMATION_SCHEMA.INDEXES.TABLE_SCHEMA and INFORMATION_SCHEMA.CONSTRAINTS.TABLE_NAME = INFORMATION_SCHEMA.INDEXES.TABLE_NAME and INFORMATION_SCHEMA.CONSTRAINTS.UNIQUE_INDEX_NAME = INFORMATION_SCHEMA.INDEXES.INDEX_NAME) where (INFORMATION_SCHEMA.CONSTRAINTS.TABLE_SCHEMA in (cast(? as varchar(2147483647))) and INFORMATION_SCHEMA.CONSTRAINTS.CONSTRAINT_TYPE in ('UNIQUE')) order by INFORMATION_SCHEMA.CONSTRAINTS.TABLE_SCHEMA, INFORMATION_SCHEMA.CONSTRAINTS.CONSTRAINT_NAME, INFORMATION_SCHEMA.INDEXES.ORDINAL_POSITION]; Table "CONSTRAINTS" not found; SQL statement:
select INFORMATION_SCHEMA.CONSTRAINTS.TABLE_CATALOG, INFORMATION_SCHEMA.CONSTRAINTS.TABLE_SCHEMA, INFORMATION_SCHEMA.CONSTRAINTS.TABLE_NAME, INFORMATION_SCHEMA.CONSTRAINTS.CONSTRAINT_NAME, INFORMATION_SCHEMA.INDEXES.COLUMN_NAME, INFORMATION_SCHEMA.INDEXES.ORDINAL_POSITION from INFORMATION_SCHEMA.CONSTRAINTS join INFORMATION_SCHEMA.INDEXES on (INFORMATION_SCHEMA.CONSTRAINTS.TABLE_SCHEMA = INFORMATION_SCHEMA.INDEXES.TABLE_SCHEMA and INFORMATION_SCHEMA.CONSTRAINTS.TABLE_NAME = INFORMATION_SCHEMA.INDEXES.TABLE_NAME and INFORMATION_SCHEMA.CONSTRAINTS.UNIQUE_INDEX_NAME = INFORMATION_SCHEMA.INDEXES.INDEX_NAME) where (INFORMATION_SCHEMA.CONSTRAINTS.TABLE_SCHEMA in (cast(? as varchar(2147483647))) and INFORMATION_SCHEMA.CONSTRAINTS.CONSTRAINT_TYPE in ('UNIQUE')) order by INFORMATION_SCHEMA.CONSTRAINTS.TABLE_SCHEMA, INFORMATION_SCHEMA.CONSTRAINTS.CONSTRAINT_NAME, INFORMATION_SCHEMA.INDEXES.ORDINAL_POSITION [42102-202]

	at org.jooq_3.15.4.H2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2988)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:639)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
	at org.jooq.impl.MetaImpl$MetaSchema.lambda$initUks$3(MetaImpl.java:462)
	at org.jooq.impl.MetaImpl.lambda$meta$0(MetaImpl.java:187)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:656)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:187)
	at org.jooq.impl.MetaImpl$MetaSchema.initUks(MetaImpl.java:455)
	at org.jooq.impl.MetaImpl$MetaSchema.getUks(MetaImpl.java:443)
	at org.jooq.impl.MetaImpl$MetaSchema.lambda$getTables$2(MetaImpl.java:425)
	at org.jooq.impl.Tools.map(Tools.java:2033)
	at org.jooq.impl.MetaImpl$MetaSchema.getTables(MetaImpl.java:397)
	at org.jooq.impl.MetaImpl.lambda$getTables0$2(MetaImpl.java:247)
	at org.jooq.impl.Tools.flatMap(Tools.java:2048)
	at org.jooq.impl.MetaImpl.getTables0(MetaImpl.java:247)
	at org.jooq.impl.AbstractMeta.lambda$initTables$4(AbstractMeta.java:181)
	at org.jooq.impl.AbstractMeta.get(AbstractMeta.java:371)
	at org.jooq.impl.AbstractMeta.initTables(AbstractMeta.java:181)
	at org.jooq.impl.AbstractMeta.getTables(AbstractMeta.java:173)

Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CONSTRAINTS" not found; SQL statement:
select INFORMATION_SCHEMA.CONSTRAINTS.TABLE_CATALOG, INFORMATION_SCHEMA.CONSTRAINTS.TABLE_SCHEMA, INFORMATION_SCHEMA.CONSTRAINTS.TABLE_NAME, INFORMATION_SCHEMA.CONSTRAINTS.CONSTRAINT_NAME, INFORMATION_SCHEMA.INDEXES.COLUMN_NAME, INFORMATION_SCHEMA.INDEXES.ORDINAL_POSITION from INFORMATION_SCHEMA.CONSTRAINTS join INFORMATION_SCHEMA.INDEXES on (INFORMATION_SCHEMA.CONSTRAINTS.TABLE_SCHEMA = INFORMATION_SCHEMA.INDEXES.TABLE_SCHEMA and INFORMATION_SCHEMA.CONSTRAINTS.TABLE_NAME = INFORMATION_SCHEMA.INDEXES.TABLE_NAME and INFORMATION_SCHEMA.CONSTRAINTS.UNIQUE_INDEX_NAME = INFORMATION_SCHEMA.INDEXES.INDEX_NAME) where (INFORMATION_SCHEMA.CONSTRAINTS.TABLE_SCHEMA in (cast(? as varchar(2147483647))) and INFORMATION_SCHEMA.CONSTRAINTS.CONSTRAINT_TYPE in ('UNIQUE')) order by INFORMATION_SCHEMA.CONSTRAINTS.TABLE_SCHEMA, INFORMATION_SCHEMA.CONSTRAINTS.CONSTRAINT_NAME, INFORMATION_SCHEMA.INDEXES.ORDINAL_POSITION [42102-202]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:9452)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:9433)
	at org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:9417)
	at org.h2.command.Parser.readTableOrView(Parser.java:9412)
	at org.h2.command.Parser.readTableFilter(Parser.java:2202)
	at org.h2.command.Parser.parseSelectFromPart(Parser.java:3102)
	at org.h2.command.Parser.parseSelect(Parser.java:3220)
	at org.h2.command.Parser.parseQuerySub(Parser.java:3092)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:2930)
	at org.h2.command.Parser.parseQuery(Parser.java:2900)
	at org.h2.command.Parser.parsePrepared(Parser.java:1101)
	at org.h2.command.Parser.parse(Parser.java:1068)
	at org.h2.command.Parser.parse(Parser.java:1037)
	at org.h2.command.Parser.prepareCommand(Parser.java:965)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:614)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:552)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1111)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:283)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:82)
	at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:210)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:302)

```

### Steps to reproduce the problem

See test above

### Versions

- jOOQ: 3.15.4
- Java: openjdk version "16" 2021-03-16
- Database (include vendor): H2 2.0.202
- OS: Mac OSX
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2021-12-01 08:44
Thanks for your report. H2 2.0.202 has introduced quite a few backwards incompatible changes, including changes to the `INFORMATION_SCHEMA`. I'm currently owrking on supporting this new H2 version in jOOQ 3.16, maintaining support for the older versions in the commercial jOOQ distributions.

The relevant issue for this task is this: https://github.com/jOOQ/jOOQ/issues/9609

**Comment by lukaseder** [comment] 2021-12-01 08:44
Duplicate of https://github.com/jOOQ/jOOQ/issues/9609

**Closed by lukaseder** 2021-12-01 08:44 UTC
Labels: T: Defect, C: Functionality, C: DB: H2, P: Medium, E: All Editions
