### ISSUE TITLE
Compilation error in Oracle generated code for package type in PL/SQL RECORD constructor

### ISSUE THREAD

**Issue by mdaepp** [jOOQ/jOOQ#15097] opened 2023-05-22 19:11 UTC
### Expected behavior

Generated code compiles. There should be a corresponding copy constructor in TMoneyAmountTabRecord.

### Actual behavior

Compilation error:

```
[ERROR] /C:/git/db-model-sakila/target/generated-sources/org/jooq/sakila/packages/customers/udt/records/TNetWorthRecRecord.java:[107,62] constructor TMoneyAmountTabRecord in class org.jooq.sakila.packages.customers.udt.records.TMoneyAmountTabRecord cannot be applied to given types;
  required: no arguments
  found:    java.util.List<org.jooq.sakila.packages.customers.udt.records.TMoneyAmountRecRecord>
  reason: actual and formal argument lists differ in length
```

There is no copy constructor in TMoneyAmountTabRecord.

[TMoneyAmountTabRecord.java.txt](https://github.com/jOOQ/jOOQ/files/11536045/TMoneyAmountTabRecord.java.txt)
[TNetWorthRecRecord.java.txt](https://github.com/jOOQ/jOOQ/files/11536047/TNetWorthRecRecord.java.txt)

This problem might be related to #15096.

### Steps to reproduce the problem

1. Use https://github.com/jOOQ/sakila/tree/main/oracle-sakila-db as a base.
2. Modify oracle-sakila-schema-pl-sql.sql as follows:

```sql
CREATE PACKAGE customers AS
  TYPE person IS RECORD (
    first_name VARCHAR2(50),
    last_name VARCHAR2(50)
  );
  TYPE t_money_amount_rec IS RECORD (
    amount   NUMBER(18, 3),
    currency VARCHAR2(3 CHAR)
  );
  TYPE t_money_amount_tab IS TABLE OF t_money_amount_rec INDEX BY BINARY_INTEGER;
  TYPE t_net_worth_rec IS RECORD (
    net_worth t_money_amount_tab
  );
  FUNCTION get_customer(p_customer_id NUMBER) RETURN person;
END customers;
/
```

3. Generate code.

Config:

```xml
<generate>
  <pojos>true</pojos>
  <validationAnnotations>true</validationAnnotations>
</generate>
```

### jOOQ Version

jOOQ 3.18.4 trial edition

### Database product and version

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

### Java Version

openjdk 17.0.7 2023-04-18

### OS Version

Microsoft Windows [Version 10.0.19045.2965]

### JDBC driver name and version (include name if unofficial driver)

oracle.jdbc.OracleDriver 19.3.0.0.0

**Comment by lukaseder** [comment] 2023-05-24 08:26
I can reproduce this. It doesn't look like the same issue as https://github.com/jOOQ/jOOQ/issues/15096, superficially. Will look into a fix right away.

**Comment by lukaseder** [comment] 2023-05-24 08:33
I've created a feature request to add the copy constructor in the future: https://github.com/jOOQ/jOOQ/issues/15107

**Comment by lukaseder** [comment] 2023-05-24 08:58
The problem is more profound. The POJO `TNetWorthRec` has a property `netWorth` of type `List<TMoneyAmountRec>`, when in fact, it should be a `Map<Integer, TMoneyAmountRec>`. It seems we simply don't support POJOs for associative arrays yet.

I suspect this has gone unnoticed so far, because customers probably don't really use the feature combination: Associative records and POJOs, and our integration tests also don't cover this.

To get rid of the compilation error:

- You can turn off `<pojos/>` for your code generation runs that generate PL/SQL packages.
- We'll generate an exception thrown at the point where the compilation error occurs, currently.

A more thorough fix will address the above issue of referencing the associative array as a `Map<K, V>` rather than a `List<V>`:

- https://github.com/jOOQ/jOOQ/issues/15108

**Comment by lukaseder** [comment] 2023-05-24 09:32
Fixed in jOOQ 3.19.0, 3.18.5 (https://github.com/jOOQ/jOOQ/issues/15109), and 3.17.14 (https://github.com/jOOQ/jOOQ/issues/15110).

A backport to 3.16.20 is too risky as there had been quite a few changes to the logic behind associative array generation in 3.17.

Thanks again for your report!

**Closed by lukaseder** 2023-05-24 09:32 UTC
Labels: T: Defect, C: DB: Oracle, C: Code Generation, P: Medium, E: Professional Edition, E: Enterprise Edition

**Comment by lukaseder** [comment] 2023-05-25 06:36
> However, POJO's would be a lot easier to work with

I'm curious about this requirement, especially in the case of using stored procedures. You would always have to map between the record and POJO world, manually. Doesn't that strike you as cumbersome?

I mean, POJOs were introduced for queries, mostly, where automatic mapping with the `DefaultRecordMapper` is available, but this has never been implemented for stored procedures.

> since they do not have a bunch of fieldN, componentN and valueN methods.

Thoes particular methods can be turned off using `<recordsImplementingRecordN/>`

**Comment by mdaepp** [comment] 2023-05-26 07:29
Thanks for the hint regarding the `<recordsImplementingRecordN/>` flag. That renders my argument about the ease of use invalid, at least as far as further processing of the data is concerned.

However, I am not planning to use POJO's in conjunction with stored procedures.

I am looking into ways to migrate a PL/SQL application to Java. One part of said application basically aggregates data from various sources (i.e. data stored in other schemas) into records which are then used for further processing. One approach would be to generate jOOQ code from the other schemas, replicate the queries from the current application using jOOQ and fetch the data into the generated POJO's (from the schema containing the current application). Ultimately, only these POJO's would "survive" from the current application. That could save a lot of effort (with regard to creating the POJO's) and exisiting queries (that are already optimized) could be "reused". There might be cases that require further optimization (e.g. when the number of DB roundtrips becomes an issue), but the approach outlined above seems promising to me as a general concept.

**Comment by lukaseder** [comment] 2024-05-08 10:06
Similar issue:

- https://github.com/jOOQ/jOOQ/issues/16661
