### ISSUE TITLE
Exceptoin when accessing MetaImpl::ddl with a user that lacks privileges to access certain databasese in SQL Server

### ISSUE THREAD

**Issue by vitaly-ivanov** [jOOQ/jOOQ#17255] opened 2024-09-17 12:29 UTC
### Expected behavior

DB metadata only for available databases is calculated

### Actual behavior

Error occurred:
```
org.jooq.exception.DataAccessException: Error while running ConnectionCallable
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:663)
	at org.jooq.impl.MetaImpl.meta(MetaImpl.java:211)
	at org.jooq.impl.MetaImpl$MetaCatalog.getSchemas(MetaImpl.java:350)
	at org.jooq.impl.MetaImpl.lambda$getSchemas0$2(MetaImpl.java:308)
	at org.jooq.impl.Tools.flatMap(Tools.java:2619)
	at org.jooq.impl.MetaImpl.getSchemas0(MetaImpl.java:308)
	at org.jooq.impl.AbstractMeta.lambda$initSchemas$1(AbstractMeta.java:157)
	at org.jooq.impl.AbstractMeta.get(AbstractMeta.java:409)
	at org.jooq.impl.AbstractMeta.initSchemas(AbstractMeta.java:157)
	at org.jooq.impl.AbstractMeta.getSchemas(AbstractMeta.java:149)
	at org.jooq.impl.MetaImpl$MetaTable.getReferences(MetaImpl.java:1186)
	at org.jooq.impl.MetaImpl$MetaTable.removeSystemIndexes(MetaImpl.java:1048)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$getIndexes$2(MetaImpl.java:987)
	at org.jooq.impl.Tools.ignoreNPE(Tools.java:7714)
	at org.jooq.impl.MetaImpl$MetaTable.getIndexes(MetaImpl.java:985)
	at org.jooq.impl.FilteredMeta$FilteredTable.getIndexes(FilteredMeta.java:466)
	at org.jooq.impl.DDL.createIndex(DDL.java:316)
	at org.jooq.impl.DDL.queries(DDL.java:559)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:635)
...
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The server principal "input_user2" is not able to access the database "one" under the current security context.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:261)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1752)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:686)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:605)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7748)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4410)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:293)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:263)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQueryInternal(SQLServerPreparedStatement.java:535)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getSchemasInternal(SQLServerDatabaseMetaData.java:1511)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getSchemas(SQLServerDatabaseMetaData.java:1521)
	at com.zaxxer.hikari.pool.ProxyDatabaseMetaData.getSchemas(ProxyDatabaseMetaData.java:257)
	at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getSchemas(HikariProxyDatabaseMetaData.java)
	at org.jooq.impl.MetaImpl$MetaCatalog.lambda$getSchemas$0(MetaImpl.java:356)
	at org.jooq.impl.MetaImpl.lambda$meta$0(MetaImpl.java:211)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:657)
	... 60 more

```

Note: If the following flags are disabled: DDLFlag.FOREIGN_KEY, DDLFlag.INDEX, DDLFlag.UNIQUE, DDLFlag.PRIMARY_KEY, the error will disappear:

### Steps to reproduce the problem

Create two databases: `my` and `other`.

Create a user that does not have access to other databases:
```sql
-- Create User
CREATE LOGIN my_user WITH PASSWORD = 'P@assword123';
CREATE USER my_user FOR LOGIN my_user;

-- Grant Access to my Database
USE input;
CREATE USER my_user FOR LOGIN my_user;
ALTER ROLE db_datareader ADD MEMBER my_user;
ALTER ROLE db_datawriter ADD MEMBER my_user;

-- Deny Access to other Database
USE output;
CREATE USER my_user FOR LOGIN my_user;
DENY SELECT, INSERT, UPDATE, DELETE ON DATABASE::other TO my_user;
```

Configure login for the `my_user` and perform metadata calculation:
```kotlin
 val ddlExportConfiguration = DDLExportConfiguration()
    .flags(EnumSet.allOf(DDLFlag::class.java))
 
 dslContext.meta()
    .ddl(ddlExportConfiguration)
    .queries()
```

### jOOQ Version

jOOQ Professional  3.19.11

### Database product and version

SQL Server docker image mcr.microsoft.com/mssql/server:2017-latest

### Java Version

openjdk 17.0.2

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.microsoft.sqlserver:mssql-jdbc:11.2.3.jre17

**Comment by lukaseder** [comment] 2024-09-17 13:45
Thanks for your message.

I'm not sure if this is a defect, though I'll look into whether we can work around this if there's a reasonable way to discover privileges without implementing all of this:

- https://github.com/jOOQ/jOOQ/issues/12672

The user `my_user` has access to see the catalog `other` via JDBC's `DatabaseMetaData.getCatalogs()` and then can't access its contents via `DatabaseMetaData.getSchemas()`. I'm not sure if jOOQ should handle this situation (unless of course we implement #12672).

If you know about your privileges, you can avoid querying catalogs using `Meta.filterCatalogs()`

**Comment by vitaly-ivanov** [comment] 2024-09-17 13:55
Sorry for the misleading reproducer, the error still occurs when filtering by catalog:
```kotlin
 dslContext.meta()
    .filterCatalogs { it.name == "my" }
    .ddl(ddlExportConfiguration)
    .queries()
```

**Comment by lukaseder** [comment] 2024-09-18 08:42
I can reproduce the case where `filterCatalogs()` is not applied correctly:

- https://github.com/jOOQ/jOOQ/issues/17259

That's definitely a bug independent of privileges of the user querying the database, which can probably be fixed easily.

I'll revert to this issue afterwards.

**Comment by lukaseder** [comment] 2024-09-18 08:54
Can you share the stacktrace that you saw, when you called `filterCatalogs()`? Just to be sure there isn't yet another issue that appears only with your database setup, not with our integration test database...

**Comment by lukaseder** [comment] 2024-09-18 09:11
It looks like the entirety of `FilteredMeta` needs to be reviewed as it doesn't push down filtering into all of the `Meta` methods, so the filter is always applied too late.

**Comment by vitaly-ivanov** [comment] 2024-09-18 12:10
> Can you share the stacktrace that you saw, when you called `filterCatalogs()`? Just to be sure there isn't yet another issue that appears only with your database setup, not with our integration test database...

As far as I can see, there is no exception on the `filterCatalogs()` call.

I did some more tests and there are some interesting results:
The meta successully exported after the third attempt:
```kotlin
val ddlExportConfiguration = DDLExportConfiguration()
  .flags(EnumSet.allOf(DDLFlag::class.java))
val meta = dslContext.meta()
  .filterCatalogs { it.name == "my" }

meta
  .ddl(ddlExportConfiguration)
  .queries()
    
kotlin.runCatching {
   meta
       .ddl(ddlExportConfiguration)
       .queries()
}.onFailure {
     it.printStackTrace()
}
// Result - Exception from the issue description

kotlin.runCatching {
   meta
       .ddl(ddlExportConfiguration)
       .queries()
}.onFailure {
     it.printStackTrace()
}
// Result - Exception two


meta
   .ddl(ddlExportConfiguration)
   .queries()
// Result - success
```

The second exception:
```
java.lang.NullPointerException: Cannot invoke "org.jooq.Schema.getTable(String)" because "schema" is null
	at org.jooq.impl.MetaImpl.lookupTable(MetaImpl.java:302)
	at org.jooq.impl.MetaImpl$MetaTable.lambda$getReferences$9(MetaImpl.java:1203)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.jooq.impl.MetaImpl$MetaTable.getReferences(MetaImpl.java:1190)
	at org.jooq.impl.FilteredMeta$FilteredTable.getReferences(FilteredMeta.java:517)
	at org.jooq.impl.DDL.foreignKeys(DDL.java:462)
	at org.jooq.impl.DDL.queries(DDL.java:584)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:635)
```

**Comment by vitaly-ivanov** [comment] 2024-09-18 12:23
OK, let me know if the reproducer is needed in a separate repo for further investigation. 

I also updated the stacktrace in the description, it was cut off at first.

**Comment by lukaseder** [comment] 2024-09-18 12:39
So, the filtering issue that I've observed has been fixed:

- https://github.com/jOOQ/jOOQ/issues/17259

I'll have a look at your NPE:

- https://github.com/jOOQ/jOOQ/issues/17263

It's certainly related, possibly fixed by #17259. I cannot reproduce it yet, but I can see how it could happen. Perhaps I'll find a simpler reproducer that isn't dependent on SQL Server and privileges.

**Comment by lukaseder** [comment] 2024-09-18 13:39
Or even better, we just catch the exception and check for error code `916` to avoid running another SQL query

**Comment by lukaseder** [comment] 2024-09-18 13:44
Related: (where we intercept error code `40515` for similar reasons)

- #12291

**Comment by lukaseder** [comment] 2024-09-18 14:02
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17267)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17268)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17269)

**Closed by lukaseder** 2024-09-18 14:02 UTC
Labels: T: Defect, C: Functionality, C: DB: SQL Server, P: Medium, E: Professional Edition, E: Enterprise Edition

**Comment by lukaseder** [comment] 2024-09-19 10:50
A related issue (though not in SQL Server):

- https://github.com/jOOQ/jOOQ/issues/17288

**Comment by vitaly-ivanov** [comment] 2024-09-19 11:43
@lukaseder, thanks for the quick fix. I have checked 3.19.12-SNAPSHOT, the bug is no longer reproducible.

**Comment by lukaseder** [comment] 2024-09-19 11:45
Great news, thanks for the feedback!
