### ISSUE TITLE
Potential improvement to the `Loader` when using foreign keys?

### ISSUE THREAD

**Issue by fge** [jOOQ/jOOQ#5121] opened 2016-02-29 07:04 UTC
Here are the two tables:

```
rochedb=> \d metrics
                Table "public.metrics"
        Column         |       Type       | Modifiers
-----------------------+------------------+-----------
 uuid                  | uuid             | not null
 class_name            | text             | not null
 method_name           | text             | not null
 halstead_volume       | double precision | not null
 code_lines            | integer          | not null
 cyclomatic_complexity | integer          | not null
Indexes:
    "metrics_index" UNIQUE, btree (uuid, class_name, method_name)
Foreign-key constraints:
    "metrics_uuid_fkey" FOREIGN KEY (uuid) REFERENCES analyses(uuid)

rochedb=> \d analyses
                Table "public.analyses"
    Column    |            Type             | Modifiers
--------------+-----------------------------+-----------
 uuid         | uuid                        | not null
 project_name | text                        | not null
 parse_date   | timestamp without time zone | not null
Indexes:
    "analyses_index" UNIQUE, btree (uuid, project_name, parse_date)
    "analyses_uuid" UNIQUE, btree (uuid)
Referenced by:
    TABLE "metrics" CONSTRAINT "metrics_uuid_fkey" FOREIGN KEY (uuid) REFERENCES analyses(uuid)
```

Now, my problem is as follows: I insert data into the `metrics` table using a CSV. But currently I have to store the UUID in the CSV so that I can use a `Loader`... And that's not really optimal.

What I'd really like to do is be able to use a `Loader` with a way to generate my records from the data in the CSV with a foreign key (the UUID in my case) which I submit.

The reason I would like that is while I can do it by hand, the loader code is written to use JDBC batches etc and I would like to avoid replicating all of this by hand...

Is it possible?

**Comment by lukaseder** [comment] 2016-02-29 10:26
Thanks for your suggestion. Nice use-case. I'll mark this as a duplicate of #4941, which is a bit more of a general requirement than this one.

Currently, you would have to either:

- Preprocess the CSV string, e.g. using regular expressions, or a CSV library
- Use the loader API with `Object[]` data sources, rather than CSV, which would make pre-processing easier

**Closed by lukaseder** 2016-02-29 10:26 UTC
Labels: C: Functionality, P: Medium, T: Enhancement

**Comment by fge** [comment] 2016-02-29 10:59
Hmmm, I didn't know .loadArrays(). I'm certainly going to use that.

The doc is a little unclear, though...

I take it that the expected `Object[]` arrays contain the values for the specified fields, right? With the correct types and all? Also, it doesn't have to be in memory, I wager, I can just using an `Iterator` I obtain from a `Stream`, right? :p

**Comment by fge** [comment] 2016-02-29 12:20
OK, done. Indeed, an iterator from a `Stream` works :)

Here's the code I use now; which is _much_ better than loading line by line, and all of this in a `TransactionalRunnable` to boot :p

```java
        try (
            final DSLContext context = DSL.using(configuration);
            final Stream<Object[]> stream = Files.lines(path)
                .map(this::createRecord);
        ) {
            context.insertInto(Tables.ANALYSES)
                .columns(Tables.ANALYSES.fields())
                .values(uuid, projectName, timestamp)
                .execute();

            final Loader<MetricsRecord> loader = context
                .loadInto(Tables.METRICS)
                .loadArrays(stream.iterator())
                .fields(Tables.METRICS.fields())
                .execute();
            LOGGER.info("{} lines stored in database", loader.stored());
        } catch (IOException e) {
            throw new RuntimeException("Cannot open CSV for reading", e);
        }
    }

    private Object[] createRecord(final String line)
    {
        final String[] data = COMMA.split(line);

        return new Object[] {
            uuid,
            data[0],
            data[1],
            Double.parseDouble(data[2]),
            Integer.parseInt(data[3]),
            Integer.parseInt(data[4])
        };
    }
```

**Comment by lukaseder** [comment] 2016-02-29 12:26
Nice. Looks like a verbose Unix pipe! :)

**Comment by fge** [comment] 2016-02-29 12:28
Might I suggest that the documentation of .loadArrays() be updated though? It was not quite clear from the documentation what the Object[] arrays had to contain. Plus, IIRC, the doc on the main site doesn't mention that possibility, does it?

**Comment by lukaseder** [comment] 2016-02-29 12:44
I just recently added this: http://www.jooq.org/doc/latest/manual/sql-execution/importing. Sure, there's always room for improvement. What's missing for you, better Javadoc?

**Comment by fge** [comment] 2016-02-29 13:00
Yes. The javadoc only says that this method "loads data from memory". Proposal:

```
Loads object arrays from an Iterator

Each array provided by this iterator is an array with the number of elements, and matching types, of the injected {@link xxx#fields(...) fields} you are loading.
```

Or something like that. I deduced that this was how it worked, but a first read didn't really tell me that ;)
