### ISSUE TITLE
Create temporary table on mysql

### ISSUE THREAD

**Issue by nandsourav** [jOOQ/jOOQ#5503] opened 2016-08-19 13:53 UTC
Trying to create a jooq statement for temporary table creation for mysql with jooq version 3.6.4. But the problem is that statement generated starting as "create global temporary table", and mysql doesn't like the syntax. After drilling down the code, I can see the implementation of CreateTableImpl.class where the "global temporary" keyword gets appended for all family() except  POSTGRES [Line number 247 in same class].
Do we already have a fix/workaround for this problem?

**Comment by lukaseder** [comment] 2016-08-21 14:33
Thank you very much for your feedback. Indeed, version 3.6.4 does not yet support temporary table creation on MySQL. We considered merging the feature to version 3.6.5, which has not been released yet: https://github.com/jOOQ/jOOQ/issues/5049. The first minor release to support the syntax for MySQL is 3.8.0: https://github.com/jOOQ/jOOQ/issues/4375.

I'm closing this as a duplicate of #4375 / #5049

**Closed by lukaseder** 2016-08-21 14:33 UTC
Labels: C: DB: MySQL, C: Functionality, P: Medium, R: Duplicate, T: Enhancement

**Comment by Azuaron** [comment] 2016-08-22 14:00
Is there a schedule for when 3.6.5 is expected to be released?

**Comment by lukaseder** [comment] 2016-08-22 14:42
Thanks for your question, @Azuaron.

We currently don't have any plans to ship patches for old releases (older than the latest minor release 3.8), unless a paying customer is requesting it. If you're a paying customer of the jOOQ Professional or Enterprise Edition and would like to request such a patch release, we're very happy to discuss this through our commercial support channels.
