### ISSUE TITLE
Generate DAO.fetchOneByXYZ for unique columns missing with SQLite

### ISSUE THREAD

**Issue by vptp** [jOOQ/jOOQ#16667] opened 2024-05-09 09:14 UTC
### Expected behavior

Generated TestDao class should also have a method:
`fun fetchOneByCd(value: Int): org.jooq.mcve.kotlin.sqlite.tables.pojos.Test?`
Since the column is declared unique: `cd INTEGER NOT NULL UNIQUE`

### Actual behavior

Generated TestDao is missing method: `fetchOneByCd` in jOOQ versions ≥ 3.15
jOOQ versions 3.11 to 3.14 correctly include the `fetchOneByCd` for SQLite

### Steps to reproduce the problem

MCVE: https://github.com/vptp/jOOQ-mcve Test case is in `jOOQ-mcve-kotlin-sqlite`
Both the Kotlin and Java generators omit the `fetchOneByCd` method from `TestDao` with jOOQ ≥ 3.15
Swap jOOQ versions to 3.14.16 to see the `fetchOneByCd` methods generated as expected.

Related to: https://github.com/jOOQ/jOOQ/issues/6632

### jOOQ Version

jOOQ 3.15.12

### Database product and version

SQLite 3.36.0.3

### Java Version

openjdk version "1.8.0_402"

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.xerial:sqlite-jdbc:3.36.0.3

**Comment by lukaseder** [comment] 2024-05-13 08:20
Thanks for your report. I can reproduce the problem.

It works with jOOQ 3.19.8

**Comment by lukaseder** [comment] 2024-05-13 08:26
There has been some work in the past to get this to work for SQLite, in the context of these issues:

- https://github.com/jOOQ/jOOQ/issues/10823
- https://github.com/jOOQ/jOOQ/issues/11286

I'm not sure why there's still a problem in version 3.15.14, but apparently, the problem has been fixed in the meantime.

**Closed by lukaseder** 2024-05-13 08:26 UTC
Labels: T: Defect, C: Code Generation, P: Medium, E: All Editions

**Comment by lukaseder** [comment] 2024-05-14 06:20
> For our project we were trying to avoid updating JVM so were trying to avoid the jump to jOOQ 3.17. Thanks for the help though. We might just have to update Java.

The jOOQ Express Edition still supports Java 8 until jOOQ 3.18:
https://www.jooq.org/download/versions

**Comment by lukaseder** [comment] 2024-05-14 06:21
> I can open a separate issue if that would be better

Yes, please open a new issue. Thanks already for the updated MCVE!

**Comment by lukaseder** [comment] 2024-06-25 07:14
@vptp Sorry for the delay. Without a separate issue, comments on closed issues are hard to track. In the meantime, someone has reported another, similar issue here, with a similar reproducer:

- https://github.com/jOOQ/jOOQ/issues/16854

I'll check if this is the same problem as yours.

**Comment by lukaseder** [comment] 2024-06-25 07:37
It probably is the same issue indeed, because the foreign key name is derived from the unique key name, and if the unique key is unnamed, we have the problem described in #16854

**Comment by lukaseder** [comment] 2024-06-25 07:56
Ah, never mind. You did open a new issue, which was fixed in 3.19.9:

- https://github.com/jOOQ/jOOQ/issues/16675

I was mislead by the comment in your MCVE where you added another UNIQUE constraint to expose a related problem, which has now also been fixed via #16854. #16675 only fixed the problem related to the FK constraint.
