### ISSUE TITLE
'fetchStream' does not return connection to pool when 'findAny/findFirst' is used on the stream

### ISSUE THREAD

**Issue by dimi-nk** [jOOQ/jOOQ#12760] opened 2021-12-20 22:37 UTC
### Expected behavior

The lazy cursor respects the stream behaviour.

### Actual behavior

Connection leaks, i.e. connection not returned to the connection pool (tested with HikariCP).

### Steps to reproduce the problem

Please see the minimal reproduced example: [jooq-bug-report-12760-stream-with-optional](https://github.com/dimi-nk/jooq-bug-report-12760-stream-with-optional)

I did a jOOQ version bisect and located the issue at version `3.14.10`. I could possibly be https://github.com/jOOQ/jOOQ/commit/d680ae72c713091b0b9e15849d4894d8842d232e.

### Versions

- jOOQ: 3.15.5
- Java: Amazon corretto 11
- Database (include vendor): PostgresQL 11 (tested against 11, 11-alpine, and 13-alpine using testcontainers)
- OS: macOS 12.0.1 (21A559)
See repo for detailed versions used - used latest version in all dependencies.

**Comment by lukaseder** [comment] 2021-12-21 07:55
Thanks for your report. Can you show your own code please that helps reproducing this? Are you closing the stream?

**Comment by lukaseder** [comment] 2021-12-21 07:58
My bad, I didn't see the repo link. You're not closing the stream as required by [`fetchStream()`](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/ResultQuery.html#fetchStream()). There is no other way to guarantee auto closing a stream

**Comment by lukaseder** [comment] 2021-12-21 08:00
See also:
- https://github.com/jOOQ/jOOQ/issues/4932
- http://stackoverflow.com/q/34753078/521799

Closing as duplicate of #4932

**Closed by lukaseder** 2021-12-21 08:00 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Feedback Pending, E: All Editions

**Comment by dimi-nk** [comment] 2021-12-21 13:50
I missed that part of the docs! Thanks for the quick reply and the links 🙏🏼
