### ISSUE TITLE
PostgreSQL on conflict with table columns

### ISSUE THREAD

**Issue by jottyfan** [jOOQ/jOOQ#5684] opened 2016-11-23 14:40 UTC
Having read much about the not yet ready solution for the onConflict support, I think it should be summarized clearly here how I (as a user of jooq) would like to have that feature included. Just assume this as a change request for postgreSQL specific extensions; it could really be helpful to have this feature soon available.

Now for the details:
````sql
create table MY_TABLE(pk serial, 
                      my_name text, 
                      my_mail text,
                      my_date timestamp,
                      my_comment text,
                      unique(my_name, my_mail));
````

As you can see, MY_TABLE contains a primary key PK and a unique constraint combining MY_NAME and MY_MAIL. This is a usual combination from real life, no academic construct.

Assume to have the requirement to "put" a person to that table; if the person still exists, just update the timestamp field MY_DATE and the comment MY_COMMENT. This could be done in that way:
````sql
insert into MY_TABLE(my_name, my_mail, my_date, my_comment) 
  values (?, ?, ?, ?)
  on conflict(my_name, my_mail) 
  do update set 
    my_date = excluded.my_date,
    my_comment = excluded.my_comment;
````

Doing so in jooq would be nice, I assume it that way:
````java
DSL.insertInto(MY_TABLE, MY_TABLE.MY_NAME, MY_TABLE.MY_MAIL, MY_TABLE.MY_DATE, MY_TABLE.COMMENT)
   .values(bean.getName(), bean.getMail(), bean.getDate(), bean.getComment())
   .onConflict(MY_TABLE.MY_NAME, MY_TABLE.MY_MAIL)
   .doUpdateExcluded(MY_TABLE.MY_DATE, MY_TABLE.MY_COMMENT)
   .execute();
````

The two commands "onConflict" and "doUpdateExcluded" do not exist in current's jooq release. "onConflict" may be part of jooq 3.9 due to Issue #5297, but what about the "doUpdateExcluded" part that allows me not to have to add the bean values again?

Would be great to have this two methods (even if named otherwise) in jooq 3.9.

**Comment by lukaseder** [comment] 2016-11-29 14:24
Thank you very much for your suggestions.

Indeed, the `ON CONFLICT` clause will be supported in 3.9 with #5297. The `EXCLUDED` pseudo table is also on the roadmap, but won't make it in 3.9: https://github.com/jOOQ/jOOQ/issues/5214

You can easily emulate it by using plain SQL, though:

```java
DSL.field("excluded.{0}", MY_TABLE.MY_DATE)
```

Closing this as a duplicate of #5297 and #5214

**Closed by lukaseder** 2016-11-29 14:24 UTC
Labels: C: DB: PostgreSQL, C: Functionality, P: Medium, T: Enhancement
