### ISSUE TITLE
Forcetype a date time / timestamp field to Instant then has no way to use `DSL.current*()` functions

### ISSUE THREAD

**Issue by apatrida** [jOOQ/jOOQ#14517] opened 2023-01-18 19:09 UTC
### Expected behavior

If I have a type that I convert to java `Instant` using forced types and code generation, my table changes the type from say `Timestamp` or `INT` (Unix Time) to `Instant` in the generated code.  Great! 

But now I can't use a default function like `DSL.current*()` functions to set it.

* `currentTimestamp()` is wrong type `Timestamp`
* `currentOffsetDateTime()` is wrong type `OffsetDateTime`
* `currentLocalDateTime()` is wrong type `LocalDateTime`
* and then, the one you would expect to work, `currentInstant()` generates invalid code (at least for MySQL, generates `CURRENT_TIMESTAMP cast as Instant` (paraphrased) which then fails the SQL.  

I think the solution for this is `coerce()` the value to the type of the actual underlaying field on the setter side?

```
update(MY_TABLE).set(MY_FIELD.coerce(Timestamp.class), DSL.currentTimestamp())
```

so that it binds it as the value of what was mapped previously from `TimeStamp` to `Instant` by some converter, but matches what the database expects in the end.  Therefore, people working against the generated code have to also know the underlaying type of the database to get this right, and won't find mentions of this in the converter documentation.

A field does have its SqlType buried in it.  For example:

```
public final TableField<UsersRecord, Instant> UPDATED_2FA_AT = createField(DSL.name("updated_2fa_at"), SQLDataType.INTEGER, this, "", new UnixTimeAsInstantConverter());
```

I think in this case JOOQ should use instead `ConvertedTableField<UsersRecord, Instant, Integer>` (made up new subclass of `TableField`) so that the original type is moved up a notch, and other functions can be present that work on these field types to align with that SQL type.

The `ConvertedTableField` could have a `coerceToSqlType()` so that you don't have to know what it is but can do it.  Which makes my workaround above now:

```
update(MY_TABLE).set(MY_FIELD.coerceToSqlType(), DSL.currentTimestamp())
```

Here we have both a marker that this is converted, what the type it is converted from, and a way to coerce it back at will.

### Actual behavior

general pain and suffering

### Steps to reproduce the problem

All in the above description.

### jOOQ Version

3.17.x

### Database product and version

All

### Java Version

All

### OS Version

All

### JDBC driver name and version (include name if unofficial driver)

All

**Comment by lukaseder** [comment] 2023-01-19 12:45
Thanks for your report.

This isn't specific to the date time function you mentioned, it is relevant for *all* built-in functions. For example, if a `Field<String>` expression is mapped to your user type `Field<U>`, then `DSL.upper(Field<String>)` won't work with it. Likewise, in your case, you can't just use the `dateAdd()`, `timestampDiff()` and other functions with your `Field`

To some extent, this makes sense, because once you start adding domain semantics to raw data types, they're no longer that "raw". On the other hand, I obviously understand the use-case.

We can't fix this in isolation for individual functions. The only "real" fix for this kind of problem is to add another type to *all* `Field<T>` expressions, making them effectively `Field<T, U>`, where the `T` type would never be changed, only the `U` type would. By default, your field would be a `Field<Timestamp, Timestamp>`, but you can change it to `Field<Timestamp, UserType>`. The relevant feature request is: https://github.com/jOOQ/jOOQ/issues/11088

Needless to say that this would be a *very* backwards incompatible change, so at this point, I'm uncertain if jOOQ will ever implement it.

> I think in this case JOOQ should use instead `ConvertedTableField<UsersRecord, Instant, Integer>` (made up new subclass of `TableField`)

This suggestion is too shortsighted. It might (or might not) work for generated code, depending on usage. For example, the `Table::fields` method wouldn't return the new type, so the added methods won't be available.

Besides, anyone who doesn't work with generated code won't profit from this solution, so this isn't generic enough, compared to #11088, which solves the problem thoroughly for all expressions.

Additionally, I don't think your solution even works for your own case. You expect the `set()` method (and tons of others) to be overloaded, such that the generic type variables can be captured. But which one should be captured? `T` or `U`? Because when you pass a bind value, then you want the `U` types to match, not the `T` types. Note that #11088 will have the same problem, so in addition to adding more type variables to the ecosystem, we'll also need to ensure that any `Field<T, T>` expression can be conveniently coerced into a `Field<T, U>` expression. Another sign that this may be a problem not necessarily worth solving.

I think the usual workaround for this case are sufficient:

- Either unsafe cast/convert/coerce expressions
- Or convert them using your `Converter` instance

Closing this as duplicate of #11088

**Closed by lukaseder** 2023-01-19 12:45 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, E: All Editions

**Comment by apatrida** [comment] 2023-01-20 14:12
@lukaseder There is the issue that `currentInstant()` generates a cast to a datatype that does not exist in MySQL

```cast(current_timestamp() as instant)```

Even if coerced, even if mapped/converted.  So there is no `currentTimestamp`. / `currentLocalDateTime()` / `currentOffsetDateTime()` version for `Instant` that works at all.  Even coerced.

```
DSL.currentInstant().coerce(Timestamp::class.java)
```

still generates:

```cast(current_timestamp() as instant)```

**Comment by lukaseder** [comment] 2023-01-20 14:59
Thanks for your comments, @apatrida. The `@Support` annotations on those methods are probably misleading.

What would these things map to on MySQL, given there is no `TIMESTAMP WITH TIME ZONE` data type? In particular from a forward compatibility perspective, in case MySQL ever implements https://bugs.mysql.com/bug.php?id=95054

**Comment by fredgalvao** [comment] 2024-07-20 20:25
@lukaseder Given that MySQL `TIMESTAMP` is _supposed to be an instant-like data type_, I'm curious about why JOOQ has decided not to support `Instant` as a mapping to it. I'm aware of how _non-standard_ MySQL is on this area (see [this](https://stackoverflow.com/questions/65757500/how-to-use-sql-timestamp-with-java-instant-in-jooq/65757893#65757893)), but I don't see how that would prevent these two data types from being mappable.
Especially given discussions like https://github.com/jOOQ/jOOQ/issues/9665 and [a few others](https://github.com/jOOQ/jOOQ/issues?q=instant+mysql) mentioning `Instant` and `MySQL` together (many code snippets with custom converters/bindings).

I came to this topic/question/issue from realizing that `javaTimeTypes = true` makes MySQL `TIMESTAMP` (an instant-like value) be mapped to `LocalDateTime` (not an instant-like value), which implies implicit time zone conversions happening behind the curtains, and I worry that query code around such mappings is not intuitive to maintain, so I'm sincerely curious about the knowledge JOOQ has about this topic.

**Comment by lukaseder** [comment] 2024-07-31 08:36
@fredgalvao JDBC doesn't specify `Instant`, only `OffsetDateTime`, see table B-4 in https://download.oracle.com/otn-pub/jcp/jdbc-4_3-mrel3-eval-spec/jdbc4.3-fr-spec.pdf, this is why `INSTANT` is never the default for the `TIMESTAMP WITH TIME ZONE` style data types, even if it seems more suitable in some dialects, including also PostgreSQL. In the case of MySQL, it seems that `OffsetDateTime` would be the best pick, given that the session / system time zones are relevant when retrieving the `TIMESTAMP` value.

jOOQ is > 15 years old, dating older than Java 8 and JSR-310. At the time, JDBC only offered `java.sql.Time`, `java.sql.Date`, and `java.sql.Timestamp`. There was no out of the box support for time zone independent values. I'm very reluctant to change behaviour incompatibly, breaking every existing system out there. Though, you can try your luck and create a feature request to incompatibly change the `MySQLDataType.TIMESTAMP` binding to bind to `OffsetDateType` instead of `java.sql.Timestamp`. That way, we can at least collect community interest in the topic.

Knowing the defaults and the history, it does seem simple enough to configure the code generator to something more suitable to your system for the time being.
