### ISSUE TITLE
Cannot read field "bindValues" because "this.rendered" is null on JOOQ query

### ISSUE THREAD

**Issue by dragonmushu** [jOOQ/jOOQ#14947] opened 2023-04-17 22:01 UTC
### Actual behavior

Exception stack trace:

> java.lang.NullPointerException: Cannot read field "bindValues" because "this.rendered" is null 	at org.jooq_3.13.4.POSTGRES.debug(Unknown Source) 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:366) 	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:502) 	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:471) 	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:485) 	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:654) 	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2884) 	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:4246) 	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:4284)

Noticed this exception intermittently for a query we run on our postgres database:

> query = dsl.select(count())
>         .from("information_schema.role_table_grants")
>         .where(field("grantee").eq(userName))
>         .and(field("table_name").eq("test"))
>         .and(field("privilege_type").in("INSERT", "UPDATE"));
>
> dsl.fetchValue(query);

Debug log sql statement with bind value:

> with bind values      : select count(*) from information_schema.role_table_grants where (grantee = 'test1' and table_name = 'test' and privilege_type in ('INSERT', 'UPDATE'))

The exception surfaces intermittently for the query.

### Steps to reproduce the problem

> query = dsl.select(count())
>         .from("information_schema.role_table_grants")
>         .where(field("grantee").eq(userName))
>         .and(field("table_name").eq("test"))
>         .and(field("privilege_type").in("INSERT", "UPDATE"));
>
> dsl.fetchValue(query);

### jOOQ Version

3.13.4

### Database product and version

PostgreSQL 12.11

### Java Version

jdk 17

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.4.3

**Comment by lukaseder** [comment] 2023-04-18 09:05
Thanks for your report. Even in this rather old jOOQ version that you're currently using, I don't really see a reasonable call flow that would lead to the  `rendered` attribute to be `null` at the location of your stack trace:
https://github.com/jOOQ/jOOQ/blob/version-3.13.4/jOOQ/src/main/java/org/jooq/impl/AbstractQuery.java#L366

The only reason I can see is some exotic concurrency or serialization problem. Can you provide a fully self contained reproducer to help reproduce the problem you're seeing? We have a template here that could help you create such a reproducer:
https://github.com/jOOQ/jOOQ-mcve

**Comment by lukaseder** [comment] 2023-05-15 14:05
Closing this for now, since I cannot reproduce it. If you have any additional info that helps with reproduction, just let me know and we'll reopen.

**Closed by lukaseder** 2023-05-15 14:05 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Worksforme, E: All Editions
