### ISSUE TITLE
jOOQ returning() SQL generated for MSSQL can cause truncation?

### ISSUE THREAD

**Issue by tomdarshan** [jOOQ/jOOQ#13901] opened 2022-08-22 10:29 UTC
### Your question:

Background: I have a table with binary content in my MS SQL Database. Let' call the table 'document' and this column `content` in our example.

When my program executes an update statement with `returning()` on this table, the SQL generated by jOOQ will 
look something like this 

```
declare @result table ([content] binary);

update [content] set XXX
output [inserted].[content] into @result
merge into @result [r] using ((select * from [document])) 
on [r].[id] = [s].[id] when matched then update set [r].[content] = [s].[content];

select [r].[id], [r].[content] from @result [r];
```

The issue I'm seeing is that the column `content` in my table is defined as `varbinary(max)`. The temporary result table however uses just `binary`. As a consequence I get a truncation error when my program executes the SQL.

From my searches through github I couldn't find an issue related to this. Is there a workaround that isn't straight up using plain SQL? The resulting SQL in the real case I'm having is a lot longer and I would like to avoid this if possible.

### Versions:

- jOOQ:  jOOQ professional 3.14.15
- Java: 8
- Database (include vendor): Microsoft SQL Server 2017 (RTM-CU12) (KB4464082) - 14.0.3045.24 (X64)
- OS: Windows 11
- JDBC Driver (include name if unofficial driver): com.microsoft.sqlserver:mssql-jdbc

**Comment by lukaseder** [comment] 2022-08-23 08:07
Thanks a lot for your report. That might be a bug, though I can't reproduce it on my end. Can you post the exact DDL of your table here? Does the code generator produce `BINARY` or `VARBINARY` for that particular column? If it produces `BINARY`, can you post your code generator configuration?

**Comment by lukaseder** [comment] 2022-08-23 14:32
Related issue that would help work around the problem: https://github.com/jOOQ/jOOQ/issues/13912. I.e. we're generating all of this logic irrespective of whether there are any triggers, because we currently don't *know* if there are triggers. If jOOQ knew about triggers, then we could avoid the logic in case it's not necessary, and just run this, instead:

```sql
update [content] set XXX
output [inserted].[content]
```

**Comment by tomdarshan** [comment] 2022-08-23 15:09
First of all, thank you for your help and the tip regarding the workaround.

I checked the generated code (we are generating against postgres) and interestingly enough the field is being generated as a `SqlDataType.BLOB`.

We generate via gradle and have the following settings:
Generator:
```
name = "org.jooq.codegen.DefaultGenerator"
strategy.name = "org.jooq.codegen.DefaultGeneratorStrategy"
```
Database:
```
name = "org.jooq.meta.postgres.PostgresDatabase"
```
Generate:
```
isGlobalCatalogReferences = false
isGlobalObjectReferences = false
isRecords = true
```

As for the table DDL, I've extracted the following from Postgres (and removed anything distracting):

```
CREATE TABLE example.table (
    id uuid NOT NULL,
    content bytea
);
```

**Comment by lukaseder** [comment] 2022-08-23 15:25
> I checked the generated code (we are generating against postgres) and interestingly enough the field is being generated as a `SqlDataType.BLOB`.

I see, so that's probably a bug in jOOQ then. We should generate `VARBINARY(MAX)` for `BLOB`, not just `BINARY`.

You could maybe rewrite the data type to `VARBINARY` in the code generator as another workaround?
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-rewrite/

**Comment by lukaseder** [comment] 2022-08-25 09:46
I cannot reproduce this with jOOQ 3.17, where the following query is being generated for a test case:

```sql
declare @result table (
  [id] int,
  [val_default] varbinary(max), -- Column declared as VARBINARY in generated code
  [val_blob] varbinary(max)     -- Column declared as CLOB in generated code
);
insert into [test].[dbo].[t_identity_pk_binary] ([val_default], [val_blob])
output inserted.[id], inserted.[val_default], inserted.[val_blob]
into @result
values (
  null, 
  null
);
merge into @result [r]
using (
  select
    [test].[dbo].[t_identity_pk_binary].[id],
    [test].[dbo].[t_identity_pk_binary].[val_default] [alias_47760031],
    [test].[dbo].[t_identity_pk_binary].[val_blob] [alias_129165383]
  from [test].[dbo].[t_identity_pk_binary]
) [s]
on [r].[id] = [s].[id]
when matched then update set
  [val_default] = [s].[alias_47760031],
  [val_blob] = [s].[alias_129165383];
select [id], [val_default], [val_blob]
from @result [r];
```

The following code also works fine in 3.17:

```java
System.out.println(DSL.using(SQLDialect.SQLSERVER).render(cast(null, SQLDataType.BLOB)));
```

Producing:

```sql
cast(? as varbinary(max))
```

But indeed, in 3.15 and 3.16, it produces:

```sql
cast(? as binary)
```

**Comment by lukaseder** [comment] 2022-08-25 09:46
I see, this is a duplicate of https://github.com/jOOQ/jOOQ/issues/13202, which wasn't backported to earlier versions than 3.17.0, because of the subtle change of behaviour it may cause for users who have come to rely on the previous behaviour.

**Closed by lukaseder** 2022-08-25 09:46 UTC
Labels: T: Defect, C: Functionality, C: DB: SQL Server, P: High, E: Professional Edition, E: Enterprise Edition

**Comment by lukaseder** [comment] 2022-08-25 09:48
If you can't upgrade to 3.17.x yet, a workaround could be to implement an `ExecuteListener` that replaces the following `"] \\bbinary\\b" by `"] varbinary(max)"` in all jOOQ generated SQL?
