### ISSUE TITLE
Default constructor in kotlin and custom conversion column

### ISSUE THREAD

**Issue by stosik** [jOOQ/jOOQ#14492] opened 2023-01-12 23:12 UTC
### Your question

Having defined:

```
@JvmInline
value class AccountId(val value: UUID)
```

along with a custom converter for such value class:

```
internal class AccountIdConverter : Converter<ByteArray, AccountId> {

    override fun from(databaseObject: ByteArray): AccountId = AccountId(databaseObject.toUUID())

    override fun to(userObject: AccountId): ByteArray = userObject.value.toByteArray()

    override fun fromType(): Class<ByteArray> = ByteArray::class.java

    override fun toType(): Class<AccountId> = AccountId::class.java
}
```

and finally registering such converter in `gradle.kts`:
```
...
forcedTypes = listOf(
  ForcedType()
     .withUserType("com.example.AccountId")
     .withObjectType(COLUMN)
     .withIncludeExpression("account.id")
     .withConverter("com.example.AccountIdConverter")
```

Generated code for this specific column looks like follows:
```
/**
  * The column <code>account.id</code>.
 */
public final TableField<AccountRecord, AccountId> ID = createField(DSL.name("id"), SQLDataType.BINARY(16).nullable(false), this, "", new AccountIdConverter());
```

But when I try initialize AccountRecord:
`private fun Account.toRecord() = AccountRecord(id)`

where `id` is of type `AccountId` I end up with an error on runtime:

```
void database.schema.tables.records.AccountRecord.<init>(com.example.AccountId, kotlin.jvm.internal.DefaultConstructorMarker)'
java.lang.NoSuchMethodError: 'void database.schema.tables.records.AccountRecord.<init>(com.example.AccountId, kotlin.jvm.internal.DefaultConstructorMarker)'
	at com.example.JooqAccountRepository.toRecord(JooqAccountRepository.kt:59)
```

That's what the auto-generated constructor looks like for AccountRecord:
```
/**
  * Create a detached, initialized AccountRecord
*/
public AccountRecord(AccountId id) {
    super(Account.ACCOUNT);

    setId(id);
}
```

Is there something I am missing? If there is anything I can provide more I would be more than happy to help.

### jOOQ Version

3.17.5

### Database product and version

MYSQL 8.0

### Java Version

openjdk 17.0.4 2022-07-19 LTS

### JDBC driver name and version (include name if unofficial driver)

com.mysql:mysql-connector-j:8.0.31

**Comment by lukaseder** [comment] 2023-01-13 12:22
Related, a bug that has been fixed in 3.17.6 to support kotlin value classes: https://github.com/jOOQ/jOOQ/issues/14283

Not sure if this fixes your issue. If not, I can have a look, but currently, you've provided a few snippets only. I'm not sure if I can get the complete picture here. Can you try making an MCVE from this template? https://github.com/jOOQ/jOOQ-mcve It has a kotlin template as well...

I'm particularly unclear where you define `private fun Account.toRecord() = AccountRecord(id)`, and why an error in your own utility `JooqAccountRepository` is supposed to be jOOQ related?

**Comment by stosik** [comment] 2023-01-13 16:28
Here is the MCVE although it does not yield the exception I am facing in my other repository https://github.com/stosik/jOOQ-mcve. Will look into the differences as it's quite unclear to me why it works in MCVE perfectly fine but in my other project it is not. Although I run mysql and here just left h2 for time being/

**Comment by lukaseder** [comment] 2023-02-23 09:46
Thanks for your MCVE and for your patience. I'll try to reproduce this soon. Other related issues:

- https://github.com/jOOQ/jOOQ/issues/14533
- https://github.com/jOOQ/jOOQ/issues/14608

**Comment by lukaseder** [comment] 2023-10-04 13:15
I've had a look at this now, but I can't reproduce any problem with the MCVE you've provided, either. Will close this for now as "worksforme". There are the previously related issues regarding inline value classes, which are still open. If you can reproduce the issue again, just let me know.

**Closed by lukaseder** 2023-10-04 13:15 UTC
Labels: C: Functionality, P: Medium, T: Support request, R: Feedback Pending, E: All Editions
