### ISSUE TITLE
Adding support for ADD COLUMN IF NOT EXISTS

### ISSUE THREAD

**Issue by twasyl** [jOOQ/jOOQ#5683] opened 2016-11-23 09:56 UTC
Hello,

In the H2 dialect, it is possible to create table columns if they not exist using the query `ALTER TABLE name ADD COLUMN IF NOT EXISTS col_name ...`.

Currently, jOOQ doesn't allow to create a column if it doesn't exist. An API like `DSL.alterTable(...).addColumnIfNotExists(...)`would be very useful, especially when performing table migrations.

Cheers

**Comment by lukaseder** [comment] 2016-11-23 22:21
Thank you very much for your suggestion. You're absolutely right, this will be a very useful addition. I've already thought about this in the past. Unfortunately, it won't make it in jOOQ 3.9 anymore, but it's definitely on the roadmap: https://github.com/jOOQ/jOOQ/issues/5314

**Comment by lukaseder** [comment] 2016-11-23 22:21
Closed as duplicate of https://github.com/jOOQ/jOOQ/issues/5314

**Closed by lukaseder** 2016-11-23 22:21 UTC
