### ISSUE TITLE
Compiled types and runtime types do not match for MULTISET nested in ROW nested in MULTISET

### ISSUE THREAD

**Issue by jippeholwerda** [jOOQ/jOOQ#14554] opened 2023-01-26 11:09 UTC
### Expected behavior

Given the following (simplified) jOOQ query: 

```kotlin
    private fun DSLContext.hhrProjection() = this.select(
        DSL.multiset(
            this.select(
                HHR_ATTRIBUUT_WAARDE.ID.convertFrom { AttribuutId(it!!) },
                DSL.row(
                    HHR_ATTRIBUUT_WAARDE.hhrHhiAttribuutDefinitie.ID.convertFrom { AttribuutDefinitieId(it!!) },
                    HHR_ATTRIBUUT_WAARDE.hhrHhiAttribuutDefinitie.NAAM.convertFrom { it!! },
                    DSL.multiset(
                        this.select(
                            HHR_HHI_ATTRIBUUT_LIJST_WAARDE.LIJST_WAARDE.convertFrom { it!! },
                            HHR_HHI_ATTRIBUUT_LIJST_WAARDE.LIJST_KEY.convertFrom { it!! },
                            HHR_HHI_ATTRIBUUT_LIJST_WAARDE.TOELICHTING
                        )
                            .from(HHR_HHI_ATTRIBUUT_LIJST_WAARDE)
                            .where(HHR_HHI_ATTRIBUUT_LIJST_WAARDE.HHI_ATTRIBUUT_DEFINITIE_ID.eq(HHR_ATTRIBUUT_WAARDE.hhrHhiAttribuutDefinitie.ID))
                            .orderBy(HHR_HHI_ATTRIBUUT_LIJST_WAARDE.VOLGORDE)
                    ).convertFrom { r -> r.map(mapping(::AttribuutLijstWaarde)) },
                ).mapping(::AttribuutDefinitie),
                HHR_ATTRIBUUT_WAARDE.WAARDE,
            ).from(HHR_ATTRIBUUT_WAARDE)
                .join(HHR_HHI_TYPE_ATTRIBUUT_LIJST).on(
                    HHR_ATTRIBUUT_WAARDE.HHI_ATTRIBUUT_DEFINITIE_ID.eq(HHR_HHI_TYPE_ATTRIBUUT_LIJST.HHI_ATTRIBUUT_DEFINITIE_ID)
                        .and(HHR_HHI_TYPE_ATTRIBUUT_LIJST.HHI_TYPE_ID.eq(HHR_HANDHAVINGSREGISTRATIE.hhrHhiType.ID))
                )
                .where(HHR_ATTRIBUUT_WAARDE.HHR_ID.eq(HHR_HANDHAVINGSREGISTRATIE.ID))
                .orderBy(HHR_HHI_TYPE_ATTRIBUUT_LIJST.VOLGORDE)
        ).convertFrom { r -> r.map(mapping(::Attribuut)) },
    ).from(HHR_HANDHAVINGSREGISTRATIE)
    .fetch(mapping(::Hhr))
```

I would expect the function to return a list of type `Hhr`. The `Hhr` contains a list of `Attribuut` which has an `AttribuutDefinitie` containing a list of `AttribuutLijstWaarde`. The compiler agrees with me.

### Actual behavior

However, runtime the following type is returned:

![Screenshot from 2023-01-26 12-00-50](https://user-images.githubusercontent.com/117410/214821106-8cf4a84b-afe2-4a3b-ba4c-d673de1f1d89.png)

Where instead of a `List<AttribuutLijstWaarde>` it actually is an `ArrayList<String>`.

### Steps to reproduce the problem

If the above is unclear I can invest some time to setup an MCVE.

### jOOQ Version

jOOQ Open Source 3.17.7

### Database product and version

PostgreSQL 14.6 (Ubuntu 14.6-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit

**Comment by jippeholwerda** [comment] 2023-01-26 11:26
The workaround I've come up with is:

```kotlin
DSL.row(
    HHR_ATTRIBUUT_WAARDE.hhrHhiAttribuutDefinitie.ID.convertFrom { AttribuutDefinitieId(it!!) },
    HHR_ATTRIBUUT_WAARDE.hhrHhiAttribuutDefinitie.NAAM.convertFrom { it!! },
    HHR_ATTRIBUUT_WAARDE.hhrHhiAttribuutDefinitie.INTERNE_NAAM.convertFrom { it!! },
    HHR_ATTRIBUUT_WAARDE.hhrHhiAttribuutDefinitie.VALUE_TYPE.convertFrom { AttribuutType.valueOf(it!!.literal) },
    HHR_ATTRIBUUT_WAARDE.hhrHhiAttribuutDefinitie.VERPLICHT.convertFrom { it!! },
    HHR_ATTRIBUUT_WAARDE.hhrHhiAttribuutDefinitie.TOELICHTING,
    DSL.multiset(
        this.select(
            HHR_HHI_ATTRIBUUT_LIJST_WAARDE.LIJST_WAARDE.convertFrom { it!! },
            HHR_HHI_ATTRIBUUT_LIJST_WAARDE.LIJST_KEY.convertFrom { it!! },
            HHR_HHI_ATTRIBUUT_LIJST_WAARDE.TOELICHTING
        )
            .from(HHR_HHI_ATTRIBUUT_LIJST_WAARDE)
            .where(HHR_HHI_ATTRIBUUT_LIJST_WAARDE.HHI_ATTRIBUUT_DEFINITIE_ID.eq(HHR_ATTRIBUUT_WAARDE.hhrHhiAttribuutDefinitie.ID))
            .orderBy(HHR_HHI_ATTRIBUUT_LIJST_WAARDE.VOLGORDE)
    ).convertFrom { r -> r.map { listOf(it.value1(), it.value2(), it.value3()) } },
).mapping { id, naam, interneNaam, valueType, verplicht, toelichting, lijstWaardes ->
    AttribuutDefinitie(
        id,
        naam,
        interneNaam,
        valueType,
        verplicht,
        toelichting,
        lijstWaardes.map { AttribuutLijstWaarde(it[0].toString(), it[1].toString(), it[2]?.toString()) }
    )
},
```

The `convertFrom { r -> r.map { listOf(it.value1(), it.value2(), it.value3()) } }` function seems not te be called. However, now the compiled type matches the runtime type so that I can manually construct the correct objects.

**Comment by lukaseder** [comment] 2023-01-26 11:29
Thanks for your report. While the non-MCVE reduction of the example to something more minimal was a bit confusing (e.g. your screenshot lists attributes which your query doesn't project), I think I can try to take it from here to make my own reproduction attempts.

It seems to be a combination of nesting `MULTISET` -> `ROW` -> `MULTISET` along with the ad hoc converters.

**Comment by strindberg** [comment] 2023-01-28 06:31
We see the same problem. I was preparing a MCVE when I noticed this report which seems to be exactly what we see. The following (simplified) example gives us runtime types which don't match the compile time types, and it does indeed seem that it's the multiset -> row -> multiset combination that is causing the problem:

```kotlin
        jooq.select(
            CONSENT_CASE_FORM.ID,
            multiset(
                select(
                    row(
                        CONSENT_CASE_ENQUIRY.ID,
                        multiset(
                            select(CONSENT_CASE_ENQUIRY_OUTCOME.ID)
                                .from(CONSENT_CASE_ENQUIRY_OUTCOME)
                                .where(CONSENT_CASE_ENQUIRY_OUTCOME.CONSENT_CASE_ENQUIRY_ID.eq(CONSENT_CASE_ENQUIRY.ID))
                        ).mapping(::ConsentCaseEnquiryOutcome)
                    ).mapping(::ConsentCaseEnquiry)
                ).from(CONSENT_CASE_ENQUIRY)
                    .where(CONSENT_CASE_ENQUIRY.CONSENT_CASE_ID.eq(id))
            ).mapping { it },
        ).from(CONSENT_CASE_FORM)
            .where(CONSENT_CASE_FORM.ID.eq(id))
            .fetchOne(mapping(::ConsentCaseForm))
```

In this particular case, the `row(...)`serves no purpose, but when we refactor this into reusable components, we need the row "containers" as return values from our methods.

**Comment by lukaseder** [comment] 2023-03-03 13:09
@strindberg, @jippeholwerda https://github.com/jOOQ/jOOQ/issues/14657 has been fixed in 3.18.0, 3.17.9, and 3.16.15. That issue looks very similar to yours:

- Nesting of `MULTISET` / `ROW` / `MULTISET` / `ROW`
- Application of ad-hoc conversion
- Resulting in missing mappings

So, it might be a duplicate. Can any of you verify if the latest snapshots fix the issue for you? You can either build the snapshots from github if you're using the jOOQ Open Source Edition, or access them from here after tonight, if you're licensed: https://www.jooq.org/download/versions

**Comment by strindberg** [comment] 2023-03-04 05:28
I can confirm that with the latest 3.17.9-SNAPSHOT this problem has been fixed in all places where we experienced it, so from my point of my this issue has been fixed. Thank you!

**Comment by lukaseder** [comment] 2023-03-06 12:51
Thanks a lot for the feedback, @strindberg, I really appreciate it.

So, I'm closing this as a duplicate. In case there's a subtly different issue persisting, we can still reopen.

**Comment by lukaseder** [comment] 2023-03-06 12:52
Duplicate of https://github.com/jOOQ/jOOQ/issues/14657

**Comment by lukaseder** [comment] 2023-03-06 12:52
I'll release the fix soon, probably later this week.

**Closed by lukaseder** 2023-03-06 12:51 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Feedback Pending, E: All Editions
