### ISSUE TITLE
Regression Liquibase: Error while exporting schema: The file was not found

### ISSUE THREAD

**Issue by gpor0** [jOOQ/jOOQ#13021] opened 2022-02-08 13:13 UTC
### Expected behavior

Jooq generator should read the changelog file as it reads in 3.15.5.

### Actual behavior

When upgraded to 3.16.3 mvn package returns

```
Error running jOOQ code generation tool: Error while exporting schema: The file src/test/resources/database.xml was not found in....
...Specifying files by absolute path was removed in Liquibase 4.0. Please use a relative path or add '/' to the classpath parameter.
```

### Steps to reproduce the problem
having jooq.xml configuration:
```xml
<database>
	<name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
	<properties>
		<property>
			<key>scripts</key>
			<value>src/test/resources/database.xml</value>
		</property>
		<property>
			<key>includeLiquibaseTables</key>
			<value>false</value>
		</property>
	</properties>
</database>
``` 

Please consider upgrading Liquibase dependency to latest in 3.17.0 .

### Versions

- jOOQ: 3.16.3
- Java: 11
- Database (include vendor): Liquibase H2
- OS: OSX

**Comment by lukaseder** [comment] 2022-02-08 14:32
Thanks for your report. We should probably document classpath usage. Have you tried using `<value>/database.xml</value>`?

We'll probably upgrade the dependency, yes, but I don't think it would change anything? What exactly are you asking here? To revert to the old behaviour? But we can't do anything liquibase cannot do, either...

**Comment by gpor0** [comment] 2022-02-08 20:14
I see that it is actually a Liquibase problem due to the upgrade from 3.x to 4.x. I will investigate this further and open ticket with them if needed. Thank you.

**Comment by gpor0** [comment] 2022-02-08 20:45
As I can see Liquibase changed their path configuration as a result it is required to configure root paths. From Jooq side I can see that ClassLoaderResourceAccessors are added where configuration with `<value>/database.xml</value>` works as you mentioned but only if i have database.xml file in `src/main/resources`. It does not work anymore for running tests where the file is in `src/test/resources`. 

Would it be possible to configure path trough another parameter beside `scripts` to configure the Liquibase classpath? Currently source shows 'fsra = new FileSystemResourceAccessor();' which does not bring any rootpaths...

**Comment by lukaseder** [comment] 2022-02-09 15:34
Might be a duplicate of https://github.com/jOOQ/jOOQ/issues/12872

> It does not work anymore for running tests where the file is in `src/test/resources`.

What would be the rationale of putting that file in the `src/test/resources` dir? Is it a copy of the actual file, which is located elsewhere?

> Would it be possible to configure path using another parameter beside `scripts` to configure the Liquibase classpath? Currently source shows 'fsra = new FileSystemResourceAccessor();' which does not bring any rootpaths...

I'm sorry, I'm not sure what you mean by that.

**Comment by gpor0** [comment] 2022-02-09 15:48
It is in test resources because the project needs it for running unit tests therefore I don't want this file to be packaged with release. In my case H2 and Liquibase is being used with Jooq setup database for each test. As you can see in [code](https://github.com/gpor0/jOOreo/blob/1ba844f1e91bd03b77004d6dde76515db580a9eb/src/test/java/com/github/gpor0/jooreo/test/support/JooreoTest.java#L48) for test initialization works (since I can pass custom resource accessor as parameter). But from [Jooq generator config](https://github.com/gpor0/jOOreo/blob/1ba844f1e91bd03b77004d6dde76515db580a9eb/src/test/resources/jooq.xml#L8) I don't have this option.  BR Gregor.

**Comment by lukaseder** [comment] 2022-02-09 16:19
Probably another limitation from the fix in jOOQ 3.14: https://github.com/jOOQ/jOOQ/issues/9866

**Comment by lukaseder** [comment] 2022-02-09 16:25
This really looks like a duplicate of https://github.com/jOOQ/jOOQ/issues/12872. The solution will be to offer an explicit configuration for the `rootPath`, defaulting to `.` (whatever that is in the user's context)

**Comment by gpor0** [comment] 2022-02-09 16:25
Yes. But thanks for related issue, I will try to do a workaround using maven variable as suggested but as you already mentioned in #9866 this should not be the proper solution. I believe this is more a problem of Liquibase for having so complex configuration it is hard to port to other tools like Jooq.

**Closed by lukaseder** 2022-02-09 16:25 UTC
Labels: T: Defect, C: Code Generation, P: Medium, R: Duplicate, C: Integration: Liquibase, E: All Editions

**Comment by gpor0** [comment] 2022-02-09 16:50
Yes. If I generate sources in `generate-test-sources` build fails since imports in test code `src/main/java` does not find the generated packages. This 3.16 upgrade is a nightmare not mentioning Jakarta and Geometry 😩.

**Comment by lukaseder** [comment] 2022-02-09 17:03
> This 3.16 upgrade is a nightmare not mentioning Jakarta and Geometry 😩 but I will leave those thoughts on stackoverflow.

Yes, please, do provide feedback! Greatly appreciated
