### ISSUE TITLE
Chaining ad-hoc converters in a multiset using JSON emulation results in ClassCastException

### ISSUE THREAD

**Issue by matt-snider** [jOOQ/jOOQ#14773] opened 2023-03-09 19:38 UTC
### Expected behavior

It should be possible to chain ad-hoc converters inside a multiset query when using JSON emulation.

This looks to be related to #14657 

e.g.

```java
var result = db.select(
    multiset(
        select(
            row(
                val("Hello").convertFrom(String::length).convertFrom(x -> x + 100),
                val("World")
            ).mapping(Tuple2::new)
        ).from(dual())
    ).convertFrom(r -> r.map(Record1::component1))
).from(dual())
.fetchOne(Record1::component1);

log.debug("The result: {}", result);
```

### Actual behavior

An exception is thrown.

```
Caused by: java.sql.SQLException: Error while reading field: multiset(
  select row (
    'Hello',
    'World'
  )
  from (
    select 'X' "DUMMY"
  ) "DUAL"
), at JDBC index: 1
        at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1591)
        at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1517)
        at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1432)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1389)
        ... 25 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
        at org.jooq.impl.JSONReader.read(JSONReader.java:125)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultisetJSON(DefaultBinding.java:4243)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.lambda$readMultiset$1(DefaultBinding.java:4204)
        at org.jooq.impl.Tools.apply(Tools.java:2195)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:4202)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:4174)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:4167)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:4145)
        at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1071)
        at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1581)
        ... 29 common frames omitted
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
        at org.jooq.Converter$1.from(Converter.java:179)
        at org.jooq.Converters.from(Converters.java:202)
        at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:312)
        at org.jooq.impl.Tools.setValue(Tools.java:3558)
        at org.jooq.impl.DefaultRecordUnmapper$IterableUnmapper.unmap(DefaultRecordUnmapper.java:170)
        at org.jooq.impl.DefaultRecordUnmapper.unmap(DefaultRecordUnmapper.java:106)
        at org.jooq.impl.AbstractRecord.from0(AbstractRecord.java:917)
        at org.jooq.impl.AbstractRecord.from(AbstractRecord.java:965)
        at org.jooq.impl.JSONReader.lambda$patchRecord$2(JSONReader.java:300)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
        at org.jooq.impl.JSONReader.patchRecord(JSONReader.java:299)
        at org.jooq.impl.JSONReader.read(JSONReader.java:213)
        at org.jooq.impl.JSONReader.read(JSONReader.java:122)
        ... 38 common frames omitted
```

### Steps to reproduce the problem

Run the above query.

Note also the following:

- I am using `val(...).convertFrom(...).convertFrom(...)` to emulate the real world issue since this seems to be a more minimal reproduction. The actual issue I'm having is a `forcedType` on an `tinyint` column that converts it to an enum, which I am then selecting and using `convertFrom()` on. It seemed to me that the first `convertFrom()` call would be equivalent or similar to the `forcedType` and seems to result in the same exception
- I tried with just `val("Hello").convertFrom(String::length)` and it worked fine
- I tried without a multiset and the same `val()` with two  `convertFrom()` calls and it worked fine

### jOOQ Version

3.18.0 (also tested and issue is present with 3.17.8 and 3.17.9)

### Database product and version

MySQL 8.0.28 (I'm aware I need to upgrade to >= 8.0.31, but it doesn't seem to be the issue here)

### Java Version

openjdk version "19.0.1" 2022-10-18

### JDBC driver name and version (include name if unofficial driver)

mysql:mysql-connector-java:8.0.31

**Comment by matt-snider** [comment] 2023-03-09 19:42
I just tested this in 3.17.8 to see if it was present before #14657 and it does appear to be the case. So I guess it was not a regression introduced as a result of that change.

**Comment by lukaseder** [comment] 2023-03-10 15:47
> I just tested this in 3.17.8 to see if it was present before #14657 and it does appear to be the case. So I guess it was not a regression introduced as a result of that change.

Thanks for the confirmation, @matt-snider. I'll have a closer look early next week.

**Comment by lukaseder** [comment] 2023-03-14 14:30
As a side note, I've noticed you're using `.from(dual())`, though that shouldn't really be needed?

**Comment by matt-snider** [comment] 2023-03-14 14:59
Ah right, probably not. I've never run a query in JOOQ without a table so I thought it was needed but didn't try without

**Comment by lukaseder** [comment] 2023-03-14 15:09
I see now, the problem is indeed related to the chaining. Which means, the workaround is to simply avoid it and chain the functions outside of jOOQ.

**Comment by lukaseder** [comment] 2023-03-14 15:28
The problem is that the value is converted twice:

1. By the nested converter (turning `"Hello"` into `5`)
2. By the chained converter (trying to turn `"Hello"` into `5` into `100 + 5`)

In that way, it is similar to these, where we also experienced "double passes" of conversions, for different reasons:

- #12155
- #12413

Those were fixed in `ConvertedDataType::convert`. There's probably a more systematic error hidden here somewhere.

**Comment by matt-snider** [comment] 2023-03-14 16:01
@lukaseder Thank you for your investigation! 

Yeah I agree, the workaround is easy. I started doing that when I opened the ticket and it seems to work well so far. It mostly just means using `row(...).mapping(MyModel::of)` instead of  `row(...).mapping(MyModel::new)` and similar when the types of the model fields don't match up with the types of the DB columns

**Comment by lukaseder** [comment] 2024-12-10 15:45
This issue no longer reproduces. Probably a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/16013

**Closed by lukaseder** 2024-12-10 15:45 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
