### ISSUE TITLE
MYSQL Date_Add and Date_Sub throws Parser Error, when using another column

### ISSUE THREAD

**Issue by ghoshrahul** [jOOQ/jOOQ#12034] opened 2021-06-22 04:39 UTC
### Expected behavior
On executing the SQL query, it should correctly add the interval specified in the query

### Actual behavior
It is throwing a parser exception

### Steps to reproduce the problem

```java
String sqlQuery = "select date(`users`.`created`) as `Created`, `users`.`frequency` as `Frequency`, ifnull(date_add(`users`.`created`, interval -((`users`.`frequency` - 2E0)) day), '0000-00-00 00:00:00') as `Date Add` from `users` as `users`";
ResultQuery jooqQuery = DSL.using(dslContext.configuration()).parser().parseResultQuery(sqlQuery);
// SQL generated -> select date(`users`.`created`) as `Created`, `users`.`frequency` as `Frequency`, ifnull(date_add(`users`.`created`, interval -((`users`.`frequency` - 2E0)) day), '0000-00-00 00:00:00') as `Date Add` from `users` as `users`
```

Irrespective of the meta table, it is throwing a parser exception. 

Here `frequency` column is an integer. I have given the example of date_sub, but the same can be reproduced for the date_add.
Another point to note is that the **sqlQuery** is generated by JOOQ itself.

**Result**:

```
Token ')' expected: [1:222] ...ncy`, ifnull(date_add(`users`.`created`, interval [*]-((`users`.`frequency` - 2E0)) day), '0000-00-00 00:00:00') as `Date Add` from `...
	at org.jooq.impl.DefaultParseContext.expected(ParserImpl.java:13372)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:12668)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:12663)
	at org.jooq.impl.DefaultParseContext.parseFieldDateAddIf(ParserImpl.java:9237)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:7303)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:7043)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:7020)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:6997)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:6943)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:6928)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:6869)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:6859)
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:5796)
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:5698)
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:5688)
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:5679)
	at org.jooq.impl.DefaultParseContext.parseField(ParserImpl.java:6770)
	at org.jooq.impl.DefaultParseContext.parseField(ParserImpl.java:6702)
	at org.jooq.impl.DefaultParseContext.parseFieldIfnullIf(ParserImpl.java:10102)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:7420)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:7043)
	at org.jooq.impl.DefaultParseContext.parseExp(ParserImpl.java:7020)
	at org.jooq.impl.DefaultParseContext.parseFactor(ParserImpl.java:6997)
	at org.jooq.impl.DefaultParseContext.parseSum(ParserImpl.java:6943)
	at org.jooq.impl.DefaultParseContext.parseNumericOp(ParserImpl.java:6928)
	at org.jooq.impl.DefaultParseContext.parseCollated(ParserImpl.java:6869)
	at org.jooq.impl.DefaultParseContext.parseConcat(ParserImpl.java:6859)
	at org.jooq.impl.DefaultParseContext.parsePredicate(ParserImpl.java:5796)
	at org.jooq.impl.DefaultParseContext.parseNot(ParserImpl.java:5698)
	at org.jooq.impl.DefaultParseContext.parseAnd(ParserImpl.java:5688)
	at org.jooq.impl.DefaultParseContext.parseOr(ParserImpl.java:5679)
	at org.jooq.impl.DefaultParseContext.parseFieldOrRow(ParserImpl.java:6763)
	at org.jooq.impl.DefaultParseContext.parseFieldOrRow(ParserImpl.java:6710)
	at org.jooq.impl.DefaultParseContext.parseSelectField(ParserImpl.java:6706)
	at org.jooq.impl.DefaultParseContext.parseSelectList(ParserImpl.java:6651)
	at org.jooq.impl.DefaultParseContext.parseQueryPrimary(ParserImpl.java:1294)
	at org.jooq.impl.DefaultParseContext.parseQueryTerm(ParserImpl.java:1198)
	at org.jooq.impl.DefaultParseContext.parseQueryExpressionBody(ParserImpl.java:1164)
	at org.jooq.impl.DefaultParseContext.parseSelect(ParserImpl.java:940)
	at org.jooq.impl.DefaultParseContext.parseSelect(ParserImpl.java:935)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:781)
	at org.jooq.impl.DefaultParseContext.parseResultQuery0(ParserImpl.java:564)
	at org.jooq.impl.ParserImpl.parseResultQuery(ParserImpl.java:411)
	at org.jooq.impl.ParserImpl.parseResultQuery(ParserImpl.java:406)
```
### Versions

- jOOQ: 3.15.0-SNAPSHOT
- Java: 11
- Database (include vendor):  MYSQL 5.7
- OS: Ubuntu 18.04
- JDBC Driver: com.mysql.jdbc.Driver

**Comment by lukaseder** [comment] 2021-08-16 13:49
There's a missing feature in jOOQ that allows for parsing and expressing dynamic interval expressions: https://github.com/jOOQ/jOOQ/issues/8792

This is quite a vast feature that touches on a lot of different functionality (not just `DATE_ADD`).

I'm closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/8792

**Closed by lukaseder** 2021-08-16 13:49 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
