### ISSUE TITLE
Support H2's TOP <n> [ PERCENT ] [ WITH TIES ] clause

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9179] opened 2019-09-06 12:39 UTC
H2 also supports SQL Server's `TOP <n> [ PERCENT ] [ WITH TIES ]` clause: http://www.h2database.com/html/commands.html#select

While other uses of the `PERCENT` clause are already covered by #8415, this one is not yet supported for H2.

**Comment by lukaseder** [comment] 2019-09-06 12:49
While SQL Server was probably the first dialect to support these features, the standard (and Oracle, H2) use the `FETCH NEXT n [ PERCENT ] ROWS { ONLY | WITH TIES } syntax.

I think we should generate that for H2, which supports both standard and T-SQL syntaxes.

**Comment by knutwannheden** [comment] 2019-09-06 12:54
Makes sense. What I forgot to mention is that the parser currently complains when trying to parse a `SELECT TOP` query. While H2 does support this, it could of course still be argued that this should remain a commercial feature.

**Comment by lukaseder** [comment] 2019-09-06 13:00
Yes, it should remain commercial only IMO.

**Comment by katzyn** [comment] 2019-09-06 13:01
You really should generate only standard `OFFSET` / `FETCH` clauses for H2.

H2 supports `LIMIT` / `OFFSET` and `TOP` only for compatibility with other databases and with very old versions of itself.

**Comment by lukaseder** [comment] 2019-09-16 09:59
`FETCH FIRST n ROWS WITH TIES` was supported for H2 in jOOQ 3.12 with #8415. As can be confirmed on https://www.jooq.org/translate

![image](https://user-images.githubusercontent.com/734593/64949380-5332ee80-d879-11e9-8c9a-27c0c74a7a81.png)

Closing this as a duplicate of #8415

**Closed by lukaseder** 2019-09-16 09:59 UTC
Labels: C: DB: H2, C: Functionality, E: All Editions, P: Medium, T: Enhancement
