### ISSUE TITLE
NullPointerException when misconfiguring code generator, lacking a <database/>

### ISSUE THREAD

**Issue by paulschmitz82** [jOOQ/jOOQ#10587] opened 2020-09-03 13:09 UTC
I'm trying to excecute an jooq codegen and get this error : 

```
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.13.4:generate (default-cli) on project shop-backend: Error running jOOQ code generation tool: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

i really dont know why this nullpointerexception is getting caused, and i'm having some trouble implementing jooq at generel ( i'm new to database integration)

**Comment by lukaseder** [comment] 2020-09-03 14:09
Thanks for your report. Can you run your code generation again, using the `-e` switch?

**Comment by lukaseder** [comment] 2020-09-03 14:45
Thanks for your help. This is the line:

https://github.com/jOOQ/jOOQ/blob/version-3.13.4/jOOQ-codegen/src/main/java/org/jooq/codegen/GenerationTool.java#L555

I can see how this happens, i.e. when no `<database/>` is configured in the jOOQ configuration. There shouldn't be a `NullPointerException`, but you probably also have a problem (a typo?) in your configuration. Can you post your code generation configuration here?

**Comment by lukaseder** [comment] 2020-09-03 14:50
I can reproduce the NPE when I leave out the optional `<database/>` element in a configuration. It should be optional, alas, it's not.

**Comment by lukaseder** [comment] 2020-09-03 14:52
This is a regression of #3669

**Comment by lukaseder** [comment] 2020-09-03 14:57
The NPE is fixed in jOOQ 3.14.0. Backport scheduled for 3.13.5 (#10589).

I'll be happy to review your configuration, if needed.

**Closed by lukaseder** 2020-09-03 14:57 UTC
Labels: C: Code Generation, E: All Editions, P: Medium, R: Feedback Pending, T: Defect

**Comment by paulschmitz82** [comment] 2020-09-04 09:49
Here code generation configuration, i thought i did that right, but is there a problem with the database integration?
![grafik](https://user-images.githubusercontent.com/32984714/92226139-8dd7d180-eea4-11ea-8c93-843719275b3d.png)

**Comment by lukaseder** [comment] 2020-09-04 10:14
Yes, unfortunately, due to this bug, you need a `<database/>` element in `<configuration/>`

**Comment by paulschmitz82** [comment] 2020-09-04 10:21
I can't use the database element tag :/
![image](https://user-images.githubusercontent.com/32984714/92229026-1fe1d900-eea9-11ea-862e-2c5367563409.png)

**Comment by lukaseder** [comment] 2020-09-04 10:25
I'm sorry, I meant in `<generator/>`

**Comment by paulschmitz82** [comment] 2020-09-04 17:21
Ok it's working, thanks a lot
