### ISSUE TITLE
ClassCastException: class [Lorg.jooq.JSON; cannot be cast to class org.jooq.JSON

### ISSUE THREAD

**Issue by dwitry** [jOOQ/jOOQ#11463] opened 2021-02-18 10:08 UTC
### Expected behavior

Deserialize JSON record from database or allow to use custom converter.

### Actual behavior

[ClassCastException](https://github.com/dwitry/jooq-cce/blob/master/docs/cce.log) before custom converters are executed:

```
java.lang.ClassCastException: class [Lorg.jooq.JSON; cannot be cast to class org.jooq.JSON ([Lorg.jooq.JSON; and org.jooq.JSON are in unnamed module of loader 'app')
	at org.jooq_3.14.4.DEFAULT.debug(Unknown Source) ~[na:na]
	at org.jooq.impl.DefaultBinding$DefaultJSONBinding.sqlBind0(DefaultBinding.java:4450) ~[jooq-3.14.4.jar:na]
	at org.jooq.impl.DefaultBinding$AbstractBinding.sql(DefaultBinding.java:810) ~[jooq-3.14.4.jar:na]
	at org.jooq.impl.DefaultBinding$AbstractBinding.sql(DefaultBinding.java:786) ~[jooq-3.14.4.jar:na]
...
```

### Steps to reproduce the problem

* Example at <https://github.com/dwitry/jooq-cce>:
  - Start with [default Kotlin Spring Boot](https://start.spring.io/#!type=gradle-project&language=kotlin&platformVersion=2.4.2.RELEASE&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo) project using Spring Initializr
  - Add [SQLite and jOOQ](https://github.com/dwitry/jooq-cce/commit/3d6cb5863628840628f0986b9844418d8608c5c6)
  - Use [schema](https://github.com/dwitry/jooq-cce/blob/master/docs/schema.sql) with `JSON` or `JSONB` type
* Execute `./gradlew :bootRun`
* Application fails in runtime on [context.newRecord](https://github.com/dwitry/jooq-cce/blob/master/src/main/kotlin/com/example/demo/DataBaseTest.kt#L27)

### Versions

- jOOQ: 3.14.4
- Java: openjdk 11.0.6 (Kotlin 1.4.21)
- Database (include vendor): SQLite 3.34.0
- OS: Ubuntu 20.04.2 LTS
- JDBC Driver (include name if inofficial driver): org.xerial:sqlite-jdbc:3.34.0

**Comment by lukaseder** [comment] 2021-02-18 13:10
Thanks a lot for your detailed report.

We're currently not integration testing any SQLite JSON integration, as SQLite doesn't have such a data type out of the box. Are you using this extension, perhaps? https://www.sqlite.org/json1.html If not, why did you declare your column as `JSON`?

In any case, a `ClassCastException` shouldn't happen, of course.

**Comment by dwitry** [comment] 2021-02-18 13:14
Hello @lukaseder,

Thank you for your prompt reply!

Yes it fact I'm using JSON extension as it now comes enabled by default in `org.xerial:sqlite-jdbc` driver.

Will be happy to provide any additional information/testing if needed.

**Comment by dwitry** [comment] 2021-02-18 13:55
Additional detail: it looks like when calling `newRecord` field value with list type `"ADMIN", "USER"` will be transformed to array `JSON[]` instead of `JSON`. This seems to be cause of `ClassCastException`

**Comment by lukaseder** [comment] 2021-02-18 14:05
> Yes it fact I'm using JSON extension as it now comes enabled by default in `org.xerial:sqlite-jdbc` driver.

Oh interesting, I hadn't noticed that. We'll support this extension fully, then: https://github.com/jOOQ/jOOQ/issues/11465

**Comment by dwitry** [comment] 2021-02-18 14:13
Good, @lukaseder thank you very much for managing this. Looking forward for this. Any advice what I should research for workaround until support is implemented?

**Comment by lukaseder** [comment] 2021-02-18 14:17
Yes, you can implement a custom data type binding, and attach that to your JSON columns: https://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings/

**Comment by lukaseder** [comment] 2022-03-07 13:01
I'm looking into this now. The reproducer required quite some attention to remove all sorts of side-effects that weren't relevant to this issue (JDK incompatibilities, outdated spring boot, incorrectly configured data source for spring boot, etc.)

The `ClassCastException` isn't reproducible with jOOQ 3.16.4, though it was using the dependency versions you were using in the reproducer.

In any case there seems to be an expectation of `List<?>` types being automatically serialised to `JSON` documents. This is not the case, currently. It might be done in the future. If you're interested in such functionality, I recommend creating a feature request that clearly indicates your expectations towards such a feature.

I'm closing this as "worksforme", because the `ClassCastException` no longer reproduces.

**Closed by lukaseder** 2022-03-07 13:01 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
