### ISSUE TITLE
Missing cast on enum generated with DDLDatabase when inserting in PostgreSQL

### ISSUE THREAD

**Issue by padeledicq** [jOOQ/jOOQ#14389] opened 2022-12-09 11:50 UTC
First, I am still learning, but thank you for this awesome library.

### Expected behavior

Insert queries should correctly cast enum values when inserting in a PostgreSQL database

### Actual behavior

Here is my problem.
When trying to insert enum values in database, it returns the following error:

> insert into "demo"."employee" ("ref", "firstname", "lastname", "company_id", "gender") values (?, ?, ?, ?, ?)]; ERROR: column "gender" is of type gender but expression is of type character varying

After digging a bit, I realized the generated enum did not return the correct schema
```java
public enum Gender implements EnumType {
...
@Override
    public Schema getSchema() {
        return null;
    }
``` 

I set the correct schema in the generated enum class (here I used a specific schema but the result is the same with 'public' schema and returning DefaultSchema)
```java
@Override
    public Schema getSchema() {
        return Demo.DEMO;
    }
```

then it worked as expected:
```sql
insert into "demo"."employee" ("company_id", "firstname", "lastname", "ref", "gender")
values (1, 'First Name', 'Last Name', 'ref', cast('F' as "demo"."gender"))
returning "demo"."employee"."id"
```

Edit: I tried to generate from the database, the schema is correctly returned and the 'cast' is correclty added.

The thing is I would rather avoid modifying generated class, since I try to generate classes at build time.

Thank you in advance.

### Steps to reproduce the problem

Configure generator with:

```xml
<name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
<inputSchema>DEMO</inputSchema>
<outputSchema>DEMO</outputSchema>
``` 

Define and use an enum in PostgreSQL:

```sql
SET search_path TO demo,pg_catalog;
CREATE TYPE gender AS ENUM ('M', 'F');
CREATE TABLE IF NOT EXISTS employee (
  id SERIAL PRIMARY KEY,
  company_id INT NOT NULL,
  firstName TEXT NOT NULL,
  lastName TEXT NOT NULL,
  ref VARCHAR(45) NULL,
  gender gender NOT NULL,
  create_date_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now());
```

Insert a record with:

```java
dsl.newRecord(EMPLOYEE)
                   .setRef("ref")
                   .setFirstname("First Name")
                   .setLastname("Last Name")
                   .setCompanyId(Integer.valueOf(1))
                   .setGender(Gender.F)
                   .store();
```

### jOOQ Version

3.17.6

### Database product and version

PostgreSQL 15.1 (docker image)

### Java Version

openjdk version 19

### OS Version

Windows 10 Entreprise (10.0.19041.2251)

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.1

**Comment by lukaseder** [comment] 2022-12-12 10:11
Thank you very much for your report. I'm trying to reproduce this without success. With the information you've provided, I can see the generated schema reference in the code generation output. There's probably a piece of code generation configuration, or dependency information missing?

If you have some additional time, would it be possible to make an MCVE (template here: https://github.com/jOOQ/jOOQ-mcve)?

**Comment by lukaseder** [comment] 2022-12-12 10:15
Did you perhaps downgrade `jooq-meta-extension`'s H2 dependency? H2 used to not store enum types in the proper schema, but that's not longer the case, I think?

**Comment by lukaseder** [comment] 2022-12-12 10:52
This is a duplicate of https://github.com/jOOQ/jOOQ/issues/13936. The issue wasn't backported, because it depended on some new 3.18 specific changes. I prefer to keep it this way. 3.18 will be published early 2023, so the fix is on the way.

**Closed by lukaseder** 2022-12-12 10:52 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by padeledicq** [comment] 2022-12-12 12:46
Then I will patiently wait for 3.18. 

I didn't see your last comments, I was busy creating the MVCE ([https://github.com/padeledicq/jOOQ-mcve](https://github.com/padeledicq/jOOQ-mcve)) :).

I don't know if it's related, but I got a different error when prefixing the type with the schema instead of using search_path; the type prefix was missing from the H2 create statement of the table using it (see [https://github.com/padeledicq/jOOQ-mcve/blob/main/jOOQ-mcve-java/src/main/resources/db/test/V1__initialise_database_with_schema_prefix.sql](https://github.com/padeledicq/jOOQ-mcve/blob/main/jOOQ-mcve-java/src/main/resources/db/test/V1__initialise_database_with_schema_prefix.sql)).

Thank you for your time.

**Comment by lukaseder** [comment] 2022-12-12 14:23
> I didn't see your last comments, I was busy creating the MVCE (https://github.com/padeledicq/jOOQ-mcve) :).

Yikes, sorry. I should have researched it more before posting... Thanks for the extra effort!

> I don't know if it's related, but I got a different error when prefixing the type with the schema instead of using search_path; the type prefix was missing from the H2 create statement of the table using it (see https://github.com/padeledicq/jOOQ-mcve/blob/main/jOOQ-mcve-java/src/main/resources/db/test/V1__initialise_database_with_schema_prefix.sql).

It does look related. It works in jOOQ 3.18.0-SNAPSHOT. I'll have another look at backporting #13936 later this week. Perhaps the risk isn't that big.

**Comment by lukaseder** [comment] 2022-12-13 12:42
OK, I'm going to backport https://github.com/jOOQ/jOOQ/issues/13936 to 3.17.7, given that the H2 dependency had already been 2.1.214. A backport to 3.16.13 still looks too risky.

**Comment by padeledicq** [comment] 2022-12-13 13:55
Great! Thank you again.
