### ISSUE TITLE
SQL Error during code generation with jooq 3.10.0

### ISSUE THREAD

**Issue by DiabolusExMachina** [jOOQ/jOOQ#6648] opened 2017-10-09 08:22 UTC
### Expected behavior and actual behavior:
Expected: code generation runs without SQL Error.  %ROWTYPE Records are generated. 
Actual:  

> [ERROR] Error while fetching udts
> org.jooq.exception.DataAccessException: SQL [with "args_with_siblings" as (select "a"."OWNER", "a"."OBJECT_NAME", "a"."PACKAGE_NAME", "a"."OBJECT_ID", "a"."OVERLOAD", "a"."SUBPROGRAM_ID", "a"."ARGUMENT_NAME", "a"."POSITION", "a"."SEQUENCE", "a"."DATA_LEVEL", "a"."DATA_TYPE", "a"."DEFAULTED", "a"."DEFAULT_VALUE", "a"."DEFAULT_LENGTH", "a"."IN_OUT", "a"."DATA_LENGTH", "a"."DATA_PRECISION", "a"."DATA_SCALE", "a"."RADIX", "a"."CHARACTER_SET_NAME", "a"."TYPE_OWNER", "a"."TYPE_NAME", "a"."TYPE_SUBNAME", "a"."TYPE_LINK", "a"."PLS_TYPE", "a"."CHAR_LENGTH", "a"."CHAR_USED", "a"."ORIGIN_CON_ID", lead("a"."SEQUENCE", 1, 99999999) over (partition by "a"."OWNER", "a"."PACKAGE_NAME", "a"."SUBPROGRAM_ID", "a"."DATA_LEVEL" order by "a"."SEQUENCE") "next_sibling" from "SYS"."ALL_ARGUMENTS" "a" where ("a"."OWNER" in (?, ?, ?) and "a"."PACKAGE_NAME" is not null)) (select "SYS"."ALL_TYPES"."OWNER", '' "pkg", "SYS"."ALL_TYPES"."TYPE_NAME", 0 "synthetic" from "SYS"."ALL_TYPES" where ("SYS"."ALL_TYPES"."OWNER" in (?, ?, ?) and "SYS"."ALL_TYPES"."TYPECODE" in ('OBJECT', 'XMLTYPE'))) union (select "a"."TYPE_OWNER" "OWNER", "a"."TYPE_NAME" "pkg", "a"."TYPE_SUBNAME" "TYPE_NAME", 0 "synthetic" from "SYS"."ALL_ARGUMENTS" "a" where ("a"."TYPE_OWNER" in (?, ?, ?) and "a"."DATA_TYPE" = 'PL/SQL RECORD')) union (select distinct "a"."OWNER" "OWNER", "a"."PACKAGE_NAME" "pkg", (case when "a"."DATA_LEVEL" = 0 then "a"."OBJECT_NAME" else (select "q"."TYPE_SUBNAME" from "args_with_siblings" "q" where ("a"."DATA_LEVEL" = ("q"."DATA_LEVEL" + 1) and "a"."OWNER" = "q"."OWNER" and "a"."PACKAGE_NAME" = "q"."PACKAGE_NAME" and "a"."SUBPROGRAM_ID" = "q"."SUBPROGRAM_ID" and "a"."SEQUENCE" between "q"."SEQUENCE" and "q"."next_sibling")) end || nvl2("a"."ARGUMENT_NAME", ('_' || "a"."ARGUMENT_NAME"), '')) "TYPE_NAME", 1 "synthetic" from "SYS"."ALL_ARGUMENTS" "a" where ("a"."OWNER" in (?, ?, ?) and "a"."TYPE_OWNER" is null and "a"."TYPE_NAME" is null and "a"."TYPE_SUBNAME" is null and "a"."DATA_TYPE" = 'PL/SQL RECORD')) order by 1, 2, 3]; ORA-00904: "a"."ORIGIN_CON_ID": ungültiger Bezeichner

### Steps to reproduce the problem:
Start codegeneration on Oracle 11g

### Versions:

- jOOQ 3.10.0:
- Java 1.8
- Database (include vendor): Oracle 11g
- JDBC Driver (include name if inofficial driver): ojdbc7

### Question
Is this behavior normal on Oracle 11g and %ROWTYPE Records generation is only supported on Oracle 12g?  If so this should be noticed somewhere in the documentation.

**Comment by DiabolusExMachina** [comment] 2017-10-09 08:28
Btw the query runs fine if I remove the a.ORIGIN_CON_ID column from the query

**Comment by lukaseder** [comment] 2017-10-09 08:42
Thank you very much for your report. This seems to be a duplicate of : #6643. We'll look into fixing this immediately. There's a patch release 3.10.1 scheduled early this week.

There should not be any exception or error on 11g. This should work on 11g - I will investigate why this wasn't reported by our integration tests. Further discussion on #6643.

**Closed by lukaseder** 2017-10-09 08:42 UTC
Labels: C: Code Generation, C: DB: Oracle, P: Urgent, T: Defect

**Comment by lukaseder** [comment] 2017-10-11 15:12
The fix for this issue has now been released in 3.10.1
