### ISSUE TITLE
arrayAgg() does not apply custom converters on enum fields

### ISSUE THREAD

**Issue by stravag** [jOOQ/jOOQ#11839] opened 2021-05-05 07:02 UTC
Similarly to https://github.com/jOOQ/jOOQ/issues/7471 there is an issue with enums and custom converters in combination with `arrayAgg`

```
public final TableField<SomeRecord, MyType> MY_FIELD = createField(DSL.name("my_field"), SQLDataType.UUID, this, "", new MyConverter());

DSL.arrayAgg(MY_FIELD) // works fine with (3.14.9)

public final TableField<SomeRecord, MyEnumType> MY_ENUM = createField(DSL.name("my_enum"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(.....DbEnumType.class), this, "", new EnumConverter());

DSL.arrayAgg(MY_ENUM) // crashes with (3.14.9)

Caused by: org.jooq.exception.DataTypeException: Cannot convert from MY_ENUM_VALUE (class org.postgresql.util.PGobject) to class ....MyEnumType
	at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:1290)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:1189)
	at org.jooq.tools.Convert.convert0(Convert.java:383)
	at org.jooq.tools.Convert.convert(Convert.java:456)
	at org.jooq.tools.Convert.convertArray(Convert.java:345)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:596)
	at org.jooq.tools.Convert.convert0(Convert.java:383)
	at org.jooq.tools.Convert.convert(Convert.java:456)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.convertArray(DefaultBinding.java:1259)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.pgGetArray(DefaultBinding.java:1248)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1165)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1019)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:871)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1725)
	... 105 more

```

My current workaround is

```
val arrayField = arrayAgg(MY_ENUM).coerce(Array<String>::class.java)
val myEnums: List<MyEnumType> = record[arrayField].map { MyEnumType.valueOf(it) } 
```

### Versions

- jOOQ: 3.14.9
- Java: 11 (Kotlin 1.4)
- Database (include vendor): Postgres 13.2
- OS: MacOS

**Comment by lukaseder** [comment] 2022-02-25 20:04
This has been fixed in jOOQ 3.17.0 and backported to 3.16.5 and 3.15.9. Closing this as a duplicate of #13073 and #13097

**Closed by lukaseder** 2022-02-25 20:04 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
