### ISSUE TITLE
Data conversion error converting "ENUM to JSON" in H2

### ISSUE THREAD

**Issue by SebastianS90** [jOOQ/jOOQ#13139] opened 2022-02-24 10:44 UTC
Similar to #12141 and #10769

### Expected behavior

When using `DSL.multisetAgg`, the conversion from SQL ENUM to JSON and back to the Java ENUM should work fine.

### Actual behavior

```
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "ENUM to JSON"
```

### Steps to reproduce the problem

See MCVE: https://github.com/SebastianS90/jOOQ-mcve/tree/enum-conversion/jOOQ-mcve-java

Most relevant part:
```java
ctx.select(
            AUTHOR.ID,
            AUTHOR.NAME,
            DSL.multisetAgg(
                    BOOK.ID,
                    BOOK.AUTHOR_ID,
                    BOOK.TITLE,
                    BOOK.AVAILABLE_AS // <-- ENUM('PRINT_ONLY', 'ONLINE_ONLY', 'BOTH')
            )
    )
    .from(AUTHOR)
    .innerJoin(BOOK).onKey(Keys.FK_BOOK_AUTHOR)
    .groupBy(AUTHOR.ID, AUTHOR.NAME)
    .fetch();
```

The [`mcveTest2` method](https://github.com/SebastianS90/jOOQ-mcve/blob/enum-conversion/jOOQ-mcve-java/src/test/java/org/jooq/mcve/test/java/JavaTest.java#L79) is a workaround (manually casting to VARCHAR and converting the Java String to the Java Enum).

### Versions

- jOOQ: 3.16.3
- Java: 11
- Database (include vendor): H2 2.1.210
- OS: Arch Linux

**Comment by lukaseder** [comment] 2022-02-24 11:31
Thanks for your report. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/13081. See also: https://github.com/h2database/h2database/issues/3439

**Closed by lukaseder** 2022-02-24 11:31 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Duplicate, E: All Editions
