### ISSUE TITLE
Asterisk is not expanded in returning DML statement

### ISSUE THREAD

**Issue by dvoloshyn** [jOOQ/jOOQ#12653] opened 2021-11-23 18:06 UTC
### Expected behavior
.asterisk().except() should expand asterisk for postgresql for returning DML statements the same way as it does for SELECT statements

### Actual behavior
.asterisk().except() is not expanded and added as is resulting in syntax error

### Steps to reproduce the problem

The next code:
'''
private static final QualifiedAsterisk ALL_EXCEPT_BINARIES = REQUESTS.asterisk().except(REQUESTS.DOC_BYTES, REQUESTS.SIGN_BYTES);
Mono.from(context.insertInto(REQUESTS).set(record).returning(ALL_EXCEPT_BINARIES))
'''

Generates SQL:
```
insert into "requests" (...) values (...) returning "requests".* except ("requests"."doc_bytes", "requests"."sign_bytes")
```

Which results in error:
```
io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42601] syntax error at or near "except"
```

### Versions

- jOOQ: 3.15.4
- Java: 17
- Database (include vendor): Postgresql 14
- OS: Windows 10 x64
- JDBC Driver (include name if inofficial driver): r2dbc-postgresql 0.9.0.M2

**Comment by lukaseder** [comment] 2021-11-25 10:36
Thanks a lot for your report. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/8690

**Closed by lukaseder** 2021-11-25 10:36 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
