### ISSUE TITLE
Values of sum function are sometimes multiplied by 10

### ISSUE THREAD

**Issue by enwired** [jOOQ/jOOQ#5474] opened 2016-07-29 21:47 UTC
I'm doing a fairly complicated query in a postgres database.  The final part of the query involves summing values from some column.  The sum is often computed correctly, but is often, apparently at random, multiplied by 10.  It seems that the problem is in some way related to converting postgres bigint to Java BigDecimal.

This is the simplest code I can come up with that reproduces the problem.  It does not require any database tables:
```java

  private final void getFoo() {
    DSLContext context = createDSLContext(); // should be a postgres context

    Field<Integer> X = DSL.field("x", Integer.class);
    Field<Integer> Y = DSL.field("y", Integer.class);

    String values = " (VALUES (444, 3), (444, 5)) as user_input (\"x\", \"y\") ";

    CommonTableExpression<Record2<Integer, Integer>> cte = DSL.name("cte")
        .as(DSL.select(X, Y).from(values));


    Table<Record2<Integer, Integer>> asTable = cte.asTable("tempTable", "a", "b");
    Field<Integer> A = asTable.field(0, Integer.class);
    Field<Integer> B = asTable.field(1, Integer.class);

    SelectHavingStep<Record2<Integer, BigDecimal>> query = context
        .with(cte)
        .select(A, DSL.sum(B))
        .from(asTable)
        .groupBy(A);

    System.out.println("query = \n\n" + query + "\n");

    Record2<Integer, BigDecimal> record = query.fetchOne();
    System.out.println("result: \n" + record);
  }
```

This is basically intended to sum the values "3" and "5" in the two rows.  The value "444" is arbitrary.  I realize this is a strange query that could be simplified.  My real query is quite different and involves joining tables.

Running this code produces this SQL:
```SQL
with "cte" as (
  select  x, y  from  (VALUES (444, 3), (444, 5)) as user_input ("x", "y") 
)
select "tempTable"."a",  sum("tempTable"."b")
from "cte" as "tempTable"("a", "b")
group by "tempTable"."a"
```

When running it, the first few times the result will usually be correct 3+5 = 8:
```
result: 
+----+----+
|   a| sum|
+----+----+
| 444|   8|
+----+----+
```

But running it several more times, the result will usually eventually switch to an incorrect value 10 times higher 3+5=8E+1:
```
result: 
+----+----+
|   a| sum|
+----+----+
| 444|8E+1|
+----+----+
```

I have reproduced this error in JOOQ 3.7.1 and 3.8.4.
Running the same query directly in postgres via pgadmin always gives the correct answer.

**Comment by enwired** [comment] 2016-08-01 19:32
I have found that I can avoid this issue in my code by using a cast:
```select(A, DSL.sum(B).cast(SQLDataType.BIGINT))```  instead of ```select(A, DSL.sum(B))```

This avoids the creation of a BigDecimal object and thus avoids triggering the bug.

One of my co-workers found that the bug could also be avoided by using a different name for the CTE each time: "tempTable1", "tempTable2", etc.

Because the bug never seems to happen the first time the query is run, but only after the query has run at least 2 or 3 times, there is a possibility that the bug actually is in the Java HotSpot optimizer rather than in JOOQ.

**Comment by lukaseder** [comment] 2016-08-02 11:15
Thank you very much for reporting. Very interesting, scary observation. I cannot reproduce this with Java 1.8.0_92. When looping 100 times over your code, I keep getting the correct value 8 in the result.

The cast workaround is certainly the easiest way, as it avoids the `BigDecimal` data type.

**Comment by lukaseder** [comment] 2016-08-02 11:16
I'm closing this as "worksforme". Feel free to reopen if you think that this is really related to jOOQ (and not, e.g. the JDBC driver version)

**Closed by lukaseder** 2016-08-02 11:15 UTC
Labels: C: DB: PostgreSQL, C: Functionality, P: Medium, T: Defect

**Comment by enwired** [comment] 2016-08-02 20:11
Thanks @lukaseder for investigating!

I should not have jumped to the assumption that it was JOOQ.  It could have been Hikari DataSource or the Java HotSpot compiler, or several other things.

It turns out that it was a bug in the postgresql JDBC driver, and nothing related to JOOQ at all.

https://github.com/pgjdbc/pgjdbc/issues/424

**Comment by lukaseder** [comment] 2016-08-02 20:37
No worries. It's good to have this documented here, in case someone else stumbles upon it!
