### ISSUE TITLE
SET constants cause jOOQ parser to fail

### ISSUE THREAD

**Issue by rsmckinney** [jOOQ/jOOQ#9160] opened 2019-09-04 23:16 UTC
The problem deals with jOOQ dynamically generating a Java enum class to correspond with a Sql SET.  It appears the generated enum constants do not take into account syntax differences between Sql SET constants and Java enum constants e.g., SET constants can have spaces, dashes, and other chars not legal for enum constants.

More generally I'm surprised jOOQ is creating an enum class like this.  I would think a more abstract form of type information would be sufficient at this stage in the parser.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

- Download and extract the standard [sakila-schema](https://downloads.mysql.com/docs/sakila-db.zip) from MySql.
- Parse the `sakila-schema.sql` file:
```java
...
DSLContext ctx = DSL.using(SQLDialect.MYSQL);
Meta meta = ctx.meta(Source.of(sakila));
```
- Results in exception due to non-indentifier chars in SET constant names:
```
Error:java: org.jooq.tools.reflect.ReflectException: Compilation error: /org/jooq/impl/GeneratedEnum12521848.java:3: error: ',', '}', or ';' expected
Error:java: /org/jooq/impl/GeneratedEnum12521848.java:3: error: '}' expected
Error:java: /org/jooq/impl/GeneratedEnum12521848.java:5: error: class, interface, or enum expected
Error:java: /org/jooq/impl/GeneratedEnum12521848.java:7: error: class, interface, or enum expected
Error:java: /org/jooq/impl/GeneratedEnum12521848.java:9: error: class, interface, or enum expected
Error:java: /org/jooq/impl/GeneratedEnum12521848.java:10: error: class, interface, or enum expected
Error:java: 6 errors
```

### Versions:

- jOOQ: 3.12.0
- Java: 8
- JDBC Driver (include name if inofficial driver): H2

**Comment by lukaseder** [comment] 2019-09-05 12:58
Thanks a lot for your detailed bug report. This looks like a duplicate of #8721.

The reason jOOQ generates actual `enum` classes behind the scenes is historic. In the jOOQ type system, we expect enums to be generated enum classes (generated by the code generator), which extend `java.lang.Enum`, and which can be reflected upon via `Class.getEnumConstants()`, etc.

These assumptions also cause issues when working with other languages than Java, e.g. when using Scala. See #7025.

I believe that this particular issue will be addressed sufficiently by the other two issues, mainly by #7025, which is why I'm closing this one here as a duplicate.

**Closed by lukaseder** 2019-09-05 12:58 UTC
Labels: C: Parser, E: All Editions, P: Medium, T: Defect

**Comment by lukaseder** [comment] 2019-09-05 13:00
I've just noticed that in both issue cases, I've already been talking about this with you :-)
