### ISSUE TITLE
Add support to load, create and drop UDTs

### ISSUE THREAD

**Issue by rbuehlma** [jOOQ/jOOQ#8403] opened 2019-03-11 14:08 UTC
### Use case:

We are working on a migration tool which is able to do automated DDL migration to a predefined schema. To support multiple databases, we rely on jOOQ to generate the actual statements. jOOQ directly connects to the DB and is not used to generate any classes.

### Possible solution you'd like to see:

Add support to load (using meta() without creating the jOOQ classes), create and drop UDTs.

**Comment by lukaseder** [comment] 2019-03-12 16:49
Thank you very much for your request. To be sure I properly understand it, I'm assuming you mean:

> Add support to load (using meta() without creating the jOOQ classes)

`org.jooq.Meta` should provide a way to access `org.jooq.UDT` instances, either directly (new method) or indirectly (through the relevant `org.jooq.Schema` instance)?

> create and drop UDTs.

This part is asking for the relevant `CREATE TYPE` and `DROP TYPE` statements?

- `CREATE TYPE .. AS ENUM` is going to be supported in jOOQ 3.12: #7570
- `DROP TYPE` is going to be supported in jOOQ 3.12: #7774
- `ALTER TYPE` is on the roadmap: #7775
- Additional `CREATE TYPE` statements would need to be supported separately.

I'm assuming you're mostly interested in creating composite types / row types / object types right now? Or also Oracle table types, or others?

**Comment by rbuehlma** [comment] 2019-03-13 08:58
> org.jooq.Meta should provide a way to access org.jooq.UDT instances, either directly (new method) or indirectly (through the relevant org.jooq.Schema instance)?

Yes, that was the indention.

Currently, only ENUMs are planned to be implemented. Therefore, I guess this issue will be resolved for us with  jOOQ 3.12. In the future, we might also consider additional UDTs

**Comment by lukaseder** [comment] 2019-04-01 09:44
Created a additional feature requests

- to support composite type creation through DDL statements: #8474.
- to fetch UDTs (composite types only, currently) through `org.jooq.Meta`: #8475
- to unify UDT API, currently for composite types, array types, enums: #8476

Supporting more DDL is not too difficult, but the general improvement of the UDT API to enable more and better meta inspection is a non-trivial API design task. If we want to do this right, this will need a lot more research into what various RDBMS are currently offering. I cannot make any promises here. In terms of introspection, if you're currently limited to PostgreSQL, it might be easier to write the glue code querying the `pg_catalog` tables directly yourself in order to reconstruct types from existing schemas.

I'm closing this issue as a duplicate of all the other ones, as I think that each individual idea is now covered in a separate issue.

**Closed by lukaseder** 2019-04-01 09:44 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Feedback Pending, T: Enhancement

**Comment by rbuehlma** [comment] 2019-04-01 10:43
> In terms of introspection, if you're currently limited to PostgreSQL, it might be easier to write the glue code querying the pg_catalog tables directly yourself in order to reconstruct types from existing schemas.

This is exactly what we currently do until it is supported by Jooq.
