### ISSUE TITLE
Version 3.11 generate invalid create table with MariaDB recursive CTE

### ISSUE THREAD

**Issue by DocLM** [jOOQ/jOOQ#7916] opened 2018-10-07 12:30 UTC
### Expected behavior and actual behavior:
From jOOQ 3.11 the following snippets of code generate an invalid create table sql code, in jOOQ 3.10 it works.

```
Exception: `Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(select distinct `example`.`items`.`id` as `id` from `subtree` join `example`.`l' at line 1
Query is: create temporary table `example`.`cache` as with recursive `subtree` as ((select `example`.`tree`.`id`, `example`.`tree`.`parent_id` from `example`.`tree` where `example`.`tree`.`id` in (1)) union all (select `example`.`tree`.`id`, `example`.`tree`.`parent_id` from `example`.`tree` join `subtree` on `example`.`tree`.`parent_id` = `subtree`.`id`)) (select distinct `example`.`items`.`id` as `id` from `subtree` join `example`.`leaves` on `subtree`.`id` = `example`.`leaves`.`node` join `example`.`items` on `example`.`items`.`leaf` = `example`.`leaves`.`id` where `example`.`items`.`id` not in (select `example`.`items`.`id` from `example`.`items` where `example`.`items`.`id` in (1))) union all (select `example`.`items`.`id` as `id` from `example`.`items` where `example`.`items`.`id` in (1))
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:255)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)
	... 5 more`
```

### Steps to reproduce the problem (include example code if possible):

Example database schema
```SQL
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE /*!32312 IF NOT EXISTS*/ `example` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;
USE `example`;

DROP TABLE IF EXISTS `tree`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `tree` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` INT(10) UNSIGNED DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,

  PRIMARY KEY (`id`),
  KEY `tree_parent` (`parent_id`),

  CONSTRAINT `tree_parent_node`
  FOREIGN KEY (`parent_id`)
  REFERENCES `tree` (`id`)
  ON UPDATE CASCADE
  ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `leaves`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `leaves` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `node` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),

  CONSTRAINT `tree_node`
  FOREIGN KEY (`node`)
  REFERENCES `tree` (`id`)
  ON UPDATE CASCADE
  ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `items`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `items` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `leaf` INT(10) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),

  CONSTRAINT `leaf_node`
  FOREIGN KEY (`leaf`)
  REFERENCES `leaves` (`id`)
  ON UPDATE CASCADE
  ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
```

Main.java
```JAVA
package doclm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Collection;
import org.jooq.CreateTableOnCommitStep;
import org.jooq.DSLContext;
import org.jooq.SQLDialect;
import org.jooq.impl.DSL;
import org.jooq.types.UInteger;


public class Main
{
  public static void main(String[] args) throws SQLException
  {
    Connection connection = DriverManager.getConnection("jdbc:mariadb://localhost:3306/example", "root", "mariadb");

    DSLContext create = DSL.using(connection, SQLDialect.MARIADB);
    Collection<UInteger> filter = Arrays.asList(UInteger.valueOf(1));
    Query query = new Query(create);
    CreateTableOnCommitStep command = query.createTempTable(filter, filter, filter);

    System.out.println(command);
    command.execute();
  }
}
```

Query.java
```JAVA
package doclm;

import static doclm.jooq.example.Example.EXAMPLE;

import java.util.Collection;
import org.jooq.Condition;
import org.jooq.CreateTableOnCommitStep;
import org.jooq.DSLContext;
import org.jooq.Field;
import org.jooq.Record;
import org.jooq.SelectField;
import org.jooq.SelectOnConditionStep;
import org.jooq.SelectOrderByStep;
import org.jooq.Table;
import org.jooq.WithStep;
import org.jooq.impl.DSL;
import org.jooq.types.UInteger;

public class Query {

  private DSLContext create;

  public static final Table<Record> SUBTREE = DSL.table(DSL.name("subtree"));

  public static final Field<UInteger> ID = DSL
      .field(DSL.name(SUBTREE.getName(), EXAMPLE.TREE.ID.getName()), EXAMPLE.TREE.ID.getType());

  public Query(DSLContext create)
  {
    this.create = create;
  }

  public WithStep treeChildren(Condition parentCondition) {
    return create.withRecursive(SUBTREE.getName())
        .as(
            create.select(EXAMPLE.TREE.ID, EXAMPLE.TREE.PARENT_ID)
                .from(EXAMPLE.TREE)
                .where(parentCondition)

                .unionAll(
                    create.select(EXAMPLE.TREE.ID, EXAMPLE.TREE.PARENT_ID)
                        .from(EXAMPLE.TREE)
                        .join(SUBTREE)
                        .on(EXAMPLE.TREE.PARENT_ID.eq(ID))
                )
        );
  }

  public SelectOnConditionStep<Record> treeLeaves(Condition parentCondition,
      SelectField<?>[] fields) {
    return this.treeChildren(parentCondition)
        .selectDistinct(fields)
        .from(SUBTREE)
        .join(EXAMPLE.LEAVES)
        .on(ID.eq(EXAMPLE.LEAVES.NODE));
  }

  public SelectOrderByStep<Record> treeCache(Collection<UInteger> parents, Collection<UInteger> exclude, Collection<UInteger> include) {
    SelectField<?>[] fields = {
        EXAMPLE.ITEMS.ID.as(DSL.name(EXAMPLE.getQualifiedName(), DSL.name("cache"), DSL.name("id")))
    };

    return this.treeLeaves(
        EXAMPLE.TREE.ID.in(parents),
        fields
    )
        .innerJoin(EXAMPLE.ITEMS)
        .on(EXAMPLE.ITEMS.LEAF.eq(EXAMPLE.LEAVES.ID))
        .where(EXAMPLE.ITEMS.ID.notIn(
            this.create
                .select(
                    EXAMPLE.ITEMS.ID
                )
                .from(EXAMPLE.ITEMS)
                .where(
                    EXAMPLE.ITEMS.ID.in(exclude)
                )
            )
        )
        .unionAll(
            create.select(fields)
                .from(EXAMPLE.ITEMS)
                .where(
                    EXAMPLE.ITEMS.ID.in(include)
                )
        );
  }

  public CreateTableOnCommitStep createTempTable(Collection<UInteger> parents, Collection<UInteger> exclude, Collection<UInteger> include) {
    return this.create
        .createTemporaryTable(DSL.table(DSL.name(EXAMPLE.getQualifiedName(), DSL.name("cache"))))
        .as(this.treeCache(parents, exclude, include));
  }
}

```

#### Generated SQL Code:
jOOQ 3.10
```SQL
create temporary table `example`.`cache`
as
with recursive `subtree` as (
  
  select *
  from (
    select 
      `example`.`tree`.`id`, 
      `example`.`tree`.`parent_id`
    from `example`.`tree`
    where `example`.`tree`.`id` in (1)
  ) x
  union all 
  select *
  from (
    select 
      `example`.`tree`.`id`, 
      `example`.`tree`.`parent_id`
    from `example`.`tree`
      join `subtree`
      on `example`.`tree`.`parent_id` = `subtree`.`id`
  ) x
)

select *
from (
  select distinct `example`.`items`.`id` as `id`
  from `subtree`
    join `example`.`leaves`
    on `subtree`.`id` = `example`.`leaves`.`node`
    join `example`.`items`
    on `example`.`items`.`leaf` = `example`.`leaves`.`id`
  where `example`.`items`.`id` not in (
    select `example`.`items`.`id`
    from `example`.`items`
    where `example`.`items`.`id` in (1)
  )
) x
union all 
select *
from (
  select `example`.`items`.`id` as `id`
  from `example`.`items`
  where `example`.`items`.`id` in (1)
) x
```

jOOQ 3.11
```SQL
create temporary table `example`.`cache`
as
with recursive `subtree` as (
  (
    select 
      `example`.`tree`.`id`, 
      `example`.`tree`.`parent_id`
    from `example`.`tree`
    where `example`.`tree`.`id` in (1)
  )
  union all (
    select 
      `example`.`tree`.`id`, 
      `example`.`tree`.`parent_id`
    from `example`.`tree`
      join `subtree`
      on `example`.`tree`.`parent_id` = `subtree`.`id`
  )
)
(
  select distinct `example`.`items`.`id` as `id`
  from `subtree`
    join `example`.`leaves`
    on `subtree`.`id` = `example`.`leaves`.`node`
    join `example`.`items`
    on `example`.`items`.`leaf` = `example`.`leaves`.`id`
  where `example`.`items`.`id` not in (
    select `example`.`items`.`id`
    from `example`.`items`
    where `example`.`items`.`id` in (1)
  )
)
union all (
  select `example`.`items`.`id` as `id`
  from `example`.`items`
  where `example`.`items`.`id` in (1)
)
```
### Versions:
- jOOQ: 3.11
- Java: Java 8
- Database: MariaDB >= 10.2 with recursive CTE
- OS: Linux
- JDBC Driver: group: 'org.mariadb.jdbc', name: 'mariadb-java-client', version: '2.2.+'

**Comment by lukaseder** [comment] 2018-10-08 08:57
Thanks for your report. This isn't really related with the `CREATE [ TEMPORARY ] TABLE` prefix to the CTE, but the CTE itself. I'll close this as a duplicate of #5808

**Closed by lukaseder** 2018-10-08 08:57 UTC
Labels: C: DB: MariaDB, C: Functionality, E: All Editions, P: Medium, T: Defect
