### ISSUE TITLE
Constructors with default arguments generated by KotlinGenerator for Record

### ISSUE THREAD

**Issue by k163377** [jOOQ/jOOQ#13821] opened 2022-07-23 09:34 UTC
### Use case:
The use of default arguments (no arguments specified) when calling the constructor of the generated `Record` class appears to be using the table defaults.
On the other hand, the actual behavior is not so; it is treated the same as explicitly setting `null`.

This can trigger bugs in the following use cases
- The generated `Record` class is used to insert.
- There are some columns, such as `created_at`, for which must use the table default.

### Possible solution you'd like to see:
1. Add option to `KotlinGenerator` not to generate constructor with default arguments
2. Do not set `changed` flag for default arguments

The concept of 1 is simple and therefore omitted from the explanation.

#### About 2:
2 is how to use instance match comparisons to generate code that does not call `set` when default arguments are used.
For example, the following code is assumed to be generated

```kotlin
object AbsentValues {
  val INT: Int? = Integer.valueOf(Int.MIN_VALUE)
  // ...
}

open class FooRecord() : UpdatableRecordImpl<FooRecord>(/*...*/) {
  /*...*/
  constructor(serialId: Int? = AbsentValues.INT, /*...*/) {
    if (serialId !== AbsentValues.INT) this.serialId = serialId
  }
}
```

There are some major problems with this approach, but implementation using the generated code would be convenient and simple.

### Possible workarounds:
This problem can be avoided by using `JavaGenerator` at a minimum.
Even if `KotlinGenerator` is used, it can be avoided in operation by limiting the use of constructors with no arguments.

### Versions:
- jOOQ: 3.16.6

**Comment by lukaseder** [comment] 2022-08-15 12:16
Thanks a lot for your report. There was a tradeoff here in favour of making use of default parameters, not in favour of keeping the behaviour exposed by the `JavaGenerator`. That tradeoff may have been a mistake, but it cannot be fixed anymore, now (except with yet another code generation flag, which I'd like to avoid)

All ideas won't work:

- Using magic values won't do the trick, because we can't assume users will never use those values themselves.
- Identity comparisons also won't work, because in kotlin, `Int` values are values without identity, and they will be as well in Java, "soon."
- There's also no way to distinguish between default parameter values having been passed explicitly by the user or implicitly, because as far as I can tell, default parameter value assignments are syntax sugar which is inlined to the call site, so both syntaxes are effectively identical in generated byte code:
https://stackoverflow.com/q/61761668/521799
- Not setting the `changed` flag on those values doesn't work, because sometimes, users *want* `NULL` to be that value that is inserted explicitly

This leaves us with the code generation flag to turn off the feature. I'd like to collect more user feedback first, before going forward with this.

**Comment by k163377** [comment] 2022-08-15 15:15
@lukaseder 
Thanks for the reply.

I have created a simple test to confirm.
This test succeeds with Java 11, 17, and 18.

```kotlin
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

class DefaultTest {
    object AbsentValues {
        val INT: Int? = Integer.valueOf(Int.MIN_VALUE)
        // ...
    }

    class Result(i: Int? = AbsentValues.INT) {
        var isDefault: Boolean? = null

        init { isDefault = AbsentValues.INT === i }
    }

    @BeforeEach
    fun beforeEach() {
        println(System.getProperty("java.version"))
    }

    @Test
    fun default() {
        assertTrue(Result().isDefault!!)
        assertTrue(Result(AbsentValues.INT).isDefault!!)
    }

    @Test
    fun differentValue() {
        assertFalse(Result(Int.MAX_VALUE).isDefault!!)
        assertFalse(Result(null).isDefault!!)
    }

    @Test
    fun sameValue() {
        assertFalse(Result(Int.MIN_VALUE).isDefault!!)
    }
}
```

As shown in the above test, instance comparisons will fail for the same value if the value is outside the cache range of the wrapper type.
In other words, unless you refer to the value set in `AbsentValues`, I think you can determine that the externally given value is always the default value.

This method is not valid when the arguments of functions generated by `jOOQ` contain primitive types, but at least now all the arguments are `nullable`.
It is also not impossible to circumvent this condition by having functions that do not use primitive types be generated separately as factory functions.

In addition, the `changed` flag would be properly set if the field is initialized via a `setter` (the first code I presented was written with this in mind).

As stated above, I believe this method will work as long as there are no destructive changes to the specification regarding instance comparisons between wrapper types.
Is there anything that I am missing?

**Comment by lukaseder** [comment] 2022-08-15 16:57
Please see: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/doc-files/ValueBased.html

> When two instances of a value-based class are equal (according to `equals`), a program should not attempt to distinguish between their identities, whether directly via reference equality or indirectly via an appeal to synchronization, identity hashing, serialization, or any other identity-sensitive mechanism.

**Comment by k163377** [comment] 2022-08-15 17:23
Thank you, I understand what you are saying.

**Comment by lukaseder** [comment] 2023-03-21 08:40
Looking into this issue again. I think the discussion here got distracted by the idea of setting the `DEFAULT` to some specific value, which is hard to get right.

But if the column is both:

- `NOT NULL`
- `DEFAULT`-ed

*And*, if the user doesn't have any good way of triggering the `DEFAULT` (because of the way the code is generated), then we must ignore the explicit `NULL` value (from the constructor default). We're already doing this elsewhere, e.g.:

- https://github.com/jOOQ/jOOQ/issues/14727

I'm fixing this for jOOQ 3.19.0 and 3.18.1 via https://github.com/jOOQ/jOOQ/issues/14817.

**Comment by lukaseder** [comment] 2023-03-21 08:40
Duplicate of https://github.com/jOOQ/jOOQ/issues/14817

**Closed by lukaseder** 2023-03-21 08:40 UTC
Labels: T: Enhancement, C: Code Generation, P: Medium, C: Integration: Kotlin, E: All Editions
