### ISSUE TITLE
Static type registry deprecation warning shouldn't appear when using the INSERT valuesOfRows() clause with converted data types

### ISSUE THREAD

**Issue by strindberg** [jOOQ/jOOQ#16425] opened 2024-03-09 06:02 UTC
### Actual behavior

After upgrading to jOOQ 3.19, we are starting to see warnings with stack traces in our logs. I can see no way of getting rid of these warnings and no way to fix the problem they are warning about.

### Steps to reproduce the problem

We have the following SQL:
```sql
CREATE TYPE signing_task_status AS ENUM ('CREATED', 'COMPLETED', 'REJECTED', 'EXPIRED', 'DELETED');

create table draft_signee
(
    draft_id    bigint    not null,
    person_id   text     not null,
    sign_status signing_task_status not null,
);
```

We instruct the code generation to map the signing_task_status type to a Kotlin model enum:
```kotlin
ForcedType().withEnumConverter(true)
  .withIncludeTypes("SIGNING_TASK_STATUS").withUserType("model.SigningTaskStatus")
```

We use this Kotlin code to save an object to the database:
```kotlin
import model.SigningTaskStatus
import model.Signee

fun save(signees: List<Signee>) {
  jooq.insertInto(DRAFT_SIGNEE)
    .columns(DRAFT_SIGNEE.DRAFT_ID, DRAFT_SIGNEE.PERSON_ID, DRAFT_SIGNEE.SIGN_STATUS)
    .valuesOfRows(signees.map { signee -> row(id, signee.personId, SigningTaskStatus.CREATED) })
    .execute()
  }
```

Running this code gives us the following warning and stack trace:
```
WARN  o.j.impl.DefaultDataType.getDataType - Static type registry     : The deprecated static type registry was being accessed for a non-built-in data type: signing_task_status /* model.SigningTaskStatus */. It is strongly recommended not looking up DataType<T> references from Class<T> references by relying on the internal static type registry. See https://github.com/jOOQ/jOOQ/issues/15286 for details.
org.jooq.impl.DefaultDataType$DiscouragedStaticTypeRegistryUsage: null
	at org.jooq.impl.DefaultDataType.check(DefaultDataType.java:842)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:835)
	at org.jooq.impl.DSL.getDataType0(DSL.java:35584)
	at org.jooq.impl.DSL.val0(DSL.java:33244)
	at org.jooq.impl.Tools.lambda$field$50(Tools.java:2122)
	at org.jooq.impl.Tools.field(Tools.java:2117)
	at org.jooq.impl.Tools.field(Tools.java:2122)
	at org.jooq.impl.DSL.row(DSL.java:34022)
	at repo.DraftRepository.saveDraft(DraftRepository.kt:63)
	at repo.DraftRepository$saveDraft$1.invokeSuspend(DraftRepository.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

I think I understand what the warning is about, but I can see no way in the above code to make a change and make the warning disappear. It seems to me that the warning might trigger too aggressively, or that more documentation on how to fix the actual problem is required.

### jOOQ Version

3.19.6

### Database product and version

Postgres 15

**Comment by lukaseder** [comment] 2024-03-11 07:41
Thank you very much for your report. I believe that in your particular case, the warning shouldn't appear, so this is a bug. The idea of the warning is to log:

- If you don't supply an explicit data type (e.g. by using `DSL.val(value, dataType)`
- If jOOQ can't infer the data type (e.g. when doing things like `COL.eq(value)`. In your case, it should be possible as well)

As a workaround until this is fixed, you should be able to mute the logger `org.jooq.impl.DefaultDataType.getDataType` by setting the logging threshold to `ERROR`.

Alternatively, you can wrap all values in `DSL.val(value, dataType)` explicitly, in your `DSL.row()` call.

**Comment by lukaseder** [comment] 2024-03-11 07:47
> It seems to me that the warning might trigger too aggressively, 

I'm assuming that by "aggressively," you mean the stack trace. The idea of logging a stack trace is to be able to track down the exact call site that produced the warning. It would be difficult to track down otherwise. The logger is configured to log only 5 times per JVM instance (or rather, per class loader instance, which is usually the same).

> or that more documentation on how to fix the actual problem is required.

I agree that this would be helpful in the log message. I've created another issue for this:

- https://github.com/jOOQ/jOOQ/issues/16427

**Comment by strindberg** [comment] 2024-03-11 08:00
> > It seems to me that the warning might trigger too aggressively,
> 
> I'm assuming that by "aggressively," you mean the stack trace. The idea of logging a stack trace is to be able to track down the exact call site that produced the warning. It would be difficult to track down otherwise. The logger is configured to log only 5 times per JVM instance (or rather, per class loader instance, which is usually the same).

I was more focused on the fact that it seemed to create warnings in code that was out of our (immediate) control, which you  have confirmed. I understand the need for the stack trace. Thanks for the quick reply and the suggested workaround.

**Comment by lukaseder** [comment] 2024-03-11 08:17
This is probably a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/16090

**Comment by lukaseder** [comment] 2024-03-11 09:25
Related issue that has been fixed recently:

- https://github.com/jOOQ/jOOQ/issues/14694

We have a means to delay the application of a specific type to a bind value. Perhaps, this warning should be logged only when the SQL query is rendered, and the user `DataType` hasn't been refined yet, not when the `DSL.row()` (or `DSL.inline()` value in the case of #16090) is constructed.

That would then produce a slightly different stack trace, i.e. that of the query execution, not of the construction of the `DSL.row()` value, making tracking down a bit harder.

**Comment by lukaseder** [comment] 2024-03-11 09:57
Also related:

- https://github.com/jOOQ/jOOQ/issues/8517

**Comment by lukaseder** [comment] 2024-03-11 10:34
Fixed in versions:

- 3.20.0
- 3.19.7 (https://github.com/jOOQ/jOOQ/issues/16430)

**Closed by lukaseder** 2024-03-11 10:34 UTC
Labels: T: Defect, C: Functionality, P: High, R: Fixed, E: All Editions

**Comment by lukaseder** [comment] 2024-03-11 10:37
The fix included a new internal undocumented flag which we'll turn on in integration tests going forward, effectively throwing the logged exception to catch more of these warnings when they shouldn't appear in cases where types can be inferred.
