### ISSUE TITLE
Nullable Binary Field with nullableAnnotation creates invalid Java for Record

### ISSUE THREAD

**Issue by diamondq** [jOOQ/jOOQ#12581] opened 2021-11-01 03:48 UTC
### Expected behavior

Defining a column with a nullable="true" constraint and a blob data type (H2), and having the codegen define a nullable annotation, such as 
```xml
<nullableAnnotation>true</nullableAnnotation>
<nullableAnnotationType>org.checkerframework.checker.nullness.qual.Nullable</nullableAnnotationType>
```
should generate a valid getter and setter method in the generated Record.

### Actual behavior

Instead, the `@Nullable` annotation is attached to the byte, not the byte[], which is illegal (primitive's can't be null). If the column is called valuebinary:
```java
    public @Nullable byte[] getValueBinary() {
        return (byte[]) get(4);
    }
```
should be 
```java
    public  byte @Nullable [] getValueBinary() {
        return (byte[]) get(4);
    }
```

### Steps to reproduce the problem

The code is generated via Maven:
```xml
<generator>
	<database>
		<name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
		<properties>
			<property>
				<key>scripts</key>
				<value>${project.basedir}/src/main/resources/hubdb/liquibase-changelog.xml</value>
			</property>
			<property>
				<key>includeLiquibaseTables</key>
				<value>false</value>
			</property>
			<property>
				<key>changeLogParameters.contexts</key>
				<value>!test</value>
			</property>
		</properties>
	</database>
	<generate>
		<nullableAnnotation>true</nullableAnnotation>
		<nullableAnnotationType>org.checkerframework.checker.nullness.qual.Nullable</nullableAnnotationType>
	</generate>
	<target>
		<packageName>ca.bc.rdffg.hub.db.generated</packageName>
	</target>
</generator>
```

The liquibase definition is
```xml
<column name="value_binary" type="blob">
	<constraints nullable="false"/>
</column>
```
### Versions

- jOOQ: 3.15.3
- Java: 16
- Database (include vendor): H2
- OS: Windows 10

**Comment by lukaseder** [comment] 2021-11-01 13:51
Thanks for your report. There's a historic assumption behind the current implementation, which assumes that these annotations are method annotations, not type annotations. In the former case, the semantics is currently correct, in the latter, it obviously isn't.

Since jOOQ doesn't know what annotation type you're using, jOOQ can't make the right decision (though some heuristics based on the type package could be made). An improvement is on the way: https://github.com/jOOQ/jOOQ/issues/10759

I'll check if this can be done sooner rather than later. Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/10759

**Closed by lukaseder** 2021-11-01 13:51 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
