### ISSUE TITLE
JSONReader cannot handle MySQL opaque values

### ISSUE THREAD

**Issue by dillon-giacoppo** [jOOQ/jOOQ#12254] opened 2021-07-25 13:28 UTC
I have tried to convert some existing code to [multiset operator](https://blog.jooq.org/2021/07/06/jooq-3-15s-new-multiset-operator-will-change-how-you-think-about-sql/).

Specifically, I have code that looks roughly like this:

The `FLAG` record has this schema:

```sql
CREATE TABLE flag (
  _id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  bool_value BIT(1) NULL,
...
```

```java
var flags =
  multiset(
    select()
      .from(FLAG)
      .where(FLAG.VARIANT_ID.eq(VARIANT._ID)))
      .convertFrom(
        results ->
          results.map(
            record -> FlagMapper.convert(record.into(FLAG))));  // record.into(Flag).getBoolValue() is always null
```

When decoding this record, the `bool_value` field will always be null and never true/false.

I have narrowed this down to the fact that the multiset queries go via JSON and MySQL is returning `"base64:type16:AQ==",` for `BIT(1)` values when casting `BIT => JSON`. 

It seems this is poorly documented behaviour in MySQL https://github.com/mysql/mysql-server/blob/beb865a960b9a8a16cf999c323e46c5b0c67f21f/sql/json_dom.h#L1000-L1008. I couldn't find any documentation for this "opaque" type.

It seems this is not reproducible when using `BOOL` (`TINYINT(1)`) with a `forcedType` conversion.

Whilst this seems like poor behaviour from MySQL, it doesn't look like an upstream bug in MySQL server since there is no API or documentation suggesting that `BIT(1) == BOOL`. It seems like this convention has caught on in downstream consumers: [JDBC driver](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-type-conversions.html) and jOOQ [handling the conversion](https://github.com/jOOQ/jOOQ/commit/77a3943a65b9fdb207f3935f2b8d676347d45f59) implicitly.

It may be worthwhile for the jOOQ JSONReader to handle this `base64:typeXX` structure to avoid unexpected NPE.

### Versions

- jOOQ: `org.jooq:jooq:3.15.1`
- Java: 16
- Database (include vendor):  8.0.22 MySQL Community Server - GPL (docker)
- OS: MacOS
- JDBC Driver (include name if inofficial driver): `mysql:mysql-connector-java:8.0.24`

**Comment by lukaseder** [comment] 2021-07-26 09:58
Thanks a lot for your report. Lack of support for `BINARY` types in `MULTISET` is a known issue: https://github.com/jOOQ/jOOQ/issues/12134, which will be addressed very soon. It requires a bit of research, and possibly additional infrastructure, to make sure base64 encoding works properly when embedded in XML or JSON.

> It seems this is not reproducible when using `BOOL` (`TINYINT(1)`) with a `forcedType` conversion.

That helps because you profit from https://github.com/jOOQ/jOOQ/issues/11025, a workaround for the lack of actual `BOOLEAN` type support in MySQL.

> Whilst this seems like poor behaviour from MySQL

I don't think it is. `BIT` is really a binary type in MySQL, and as such, the encoding makes perfect sense. The fact that `BIT(1)` can be used as a `BOOLEAN` encoding is just convention, and a misunderstanding on jOOQ's side, which defaults to this encoding, see also https://github.com/jOOQ/jOOQ/issues/10323

The workaround if you can't use actual `BOOLEAN` types would be to use a `CAST` expression, I suspect?

**Comment by lukaseder** [comment] 2022-02-25 19:39
This issue was re-discovered elsewhere and fixed in the meantime in jOOQ 3.17.0 (https://github.com/jOOQ/jOOQ/issues/13089), 3.16.5 (https://github.com/jOOQ/jOOQ/issues/13090), and 3.15.9 (https://github.com/jOOQ/jOOQ/issues/13091). The latter two should be released soon.

Closing this as duplicate of #13089

**Closed by lukaseder** 2022-02-25 19:39 UTC
Labels: T: Defect, C: Functionality, P: High, E: All Editions

**Comment by matt-snider** [comment] 2022-07-07 09:42
@lukaseder I'm seeing the same issue in a multiset selecting a `tinyint unsigned` (`UByte`) field. It's configured with a forced type converting it to an enum (`MyEnum::fromUByte`, `MyEnum::uByteValue`).

```
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: class org.example.MyEnum cannot be cast to class org.jooq.types.UByte (org.example.MyEnum and org.jooq.types.UByte are in unnamed module of loader 'app')
	at org.jooq.impl.JSONReader.read(JSONReader.java:125)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultisetJSON(DefaultBinding.java:4111)
        ...
```

As a workaround, I was able to cast it to another type (Integer) and then convert explicitly with a new method which duplicates the logic of `fromUByte()`:

```java
// MY_TABLE.MY_FIELD already has type MyEnum but we need to convert explicitly
// to avoid ClassCastException
MY_TABLE.MY_FIELD.cast(Integer.class).convertFrom(MyEnum::fromInt)
```

**Comment by lukaseder** [comment] 2022-07-07 09:55
Thanks, @matt-snider. This issue here was closed as a duplicate of #13089, which has been fixed. So, quite likely, you're running into an unrelated/loosely related issue, which is best tracked as a new issue, with all the necessary information for reproduction. Please, can you create a new issue? https://github.com/jOOQ/jOOQ/issues/new/choose

(Closed issues are no longer being tracked in any overview / reports, so appart from the single notification email that this triggered, your comment is off any radar now)

**Comment by matt-snider** [comment] 2022-07-07 10:07
@lukaseder Thanks for the quick response! Understood. I will open up a new issue later this week once I've had to time to create a minimal reproduction

**Comment by matt-snider** [comment] 2022-07-09 10:00
Just an update - I spent some time trying to create a minimal reproduction and creating a simple `tinyint unsigned` table, the enum & conversion, and the multiset select.

I was not able to reproduce the issue there. I will have to look into it more

**Comment by matt-snider** [comment] 2023-02-19 12:45
I ran into this again recently so I finally opened that issue

**Comment by lukaseder** [comment] 2023-02-20 09:22
Thanks, @matt-snider
