### ISSUE TITLE
jOOQ fails with java.lang.NullPointerException: Cannot invoke "org.jooq.Table.getUnqualifiedName()" because the return value of "org.jooq.impl.Tools.getMappedTable(org.jooq.Scope, org.jooq.Table)" is null 

### ISSUE THREAD

**Issue by mcspaskiy** [jOOQ/jOOQ#17805] opened 2024-12-26 13:43 UTC
### Expected behavior

It is expected that in multithreaded mode, the SchemaMapping#map method should not return null.

### Actual behavior

The error is a NullPointerException because a null value is being returned from SchemaMapping#map

**Supposed reason**: using synchronization for writes without synchronizing reads when working with HashMap can lead to undefined behavior.

### Steps to reproduce the problem

Call the SchemaMapping#map method from multiple concurrent threads. jooq-3.18.7

### jOOQ Version

jOOQ 3.18.7 Professional Edition

### Database product and version

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

**Comment by lukaseder** [comment] 2024-12-26 17:12
This looks like a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/11519

**Comment by lukaseder** [comment] 2024-12-26 17:13
It appears that the snapshot builds currently aren't working. I'll let you know once they are so you can try to see if the latest snapshots will fix the issue for you.

**Comment by lukaseder** [comment] 2024-12-27 09:01
Snapshot builds are up to date. Could you check with 3.18.24-SNAPSHOT

**Comment by mcspaskiy** [comment] 2024-12-28 12:20
Thank you for your response and attention. Yes, it seems that these changes resolve the issue. I cannot reproduce the bug.

**Comment by lukaseder** [comment] 2024-12-31 10:17
Thanks for the feedback. Closing as duplicate of https://github.com/jOOQ/jOOQ/issues/11519

**Closed by lukaseder** 2024-12-31 10:17 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Duplicate, E: All Editions
