### ISSUE TITLE
Aloow use of xml config file with maven plugin

### ISSUE THREAD

**Issue by ypconstante** [jOOQ/jOOQ#6770] opened 2017-10-31 16:24 UTC
Currently jOOQ requires the code generation config to be inside of the pom.xml file when using the jooq-codegen-maven plugin. I think it would be interesting if the maven plugin could be configured to use a xml file to do the config, like when using the GenerationTool [[https://www.jooq.org/doc/3.10/manual/code-generation/codegen-configuration/](https://www.jooq.org/doc/3.10/manual/code-generation/codegen-configuration/)].
This would be helpful for situations when the config is too long or complex, or when it is necessary to use multiple databases in one project (AFAIK it's not possible to do this with the plugin).

**Comment by lukaseder** [comment] 2017-10-31 18:16
Indeed, you can use the `<configurationFile/>` element directly in the plugin `<configuration>`. This is documented here:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-maven/

Closing this as a duplicate of #5477

**Closed by lukaseder** 2017-10-31 18:16 UTC
Labels: C: Code Generation, P: Medium, R: Duplicate, T: Enhancement

**Comment by ypconstante** [comment] 2017-10-31 18:38
Hadn't seen that config yet! To generate the code from multiple databases the only option is to uso JVM args or the plugin has some option to use multiples files?

**Comment by lukaseder** [comment] 2017-11-01 09:42
You need multiple Maven executions in order to generate code from multiple databases. I've provided an example here: https://stackoverflow.com/a/26105204/521799
