### ISSUE TITLE
JooqCodeGen occurred `ParserException` in pg_dump on postgresql 17.2

### ISSUE THREAD

**Issue by ccmjga** [jOOQ/jOOQ#17804] opened 2024-12-25 04:48 UTC
### Expected behavior

The code is created properly according to the ddl.

### sql 1
```sql
--
-- Name: oidc_id_seq; Type: SEQUENCE OWNED BY; Schema: mjga; Owner: -
--

ALTER SEQUENCE mjga.oidc_id_seq OWNED BY mjga.oidc.id;

```

### sql 2
```sql
ALTER TABLE mjga.permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mjga.permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

```

### sql 3

```sql
ALTER TABLE ONLY mjga.oidc ALTER COLUMN id SET DEFAULT nextval('mjga.oidc_id_seq'::regclass);
```

### sql 1

```java
*Caused by: org.jooq.impl.ParserException: CACHE, CYCLE, INCREMENT BY, MAXVALUE, MINVALUE, NO CACHE, NO CYCLE, NO MAXVALUE, NO MINVALUE, OWNER TO, RENAME TO, RESTART, or START WITH expected: [69:33] ...; Owner: -
--

ALTER SEQUENCE mjga.oidc_id_seq [*]OWNED BY mjga.oidc.id;

--
-- Name: permission; Type: TABLE; Schema: mjga; ...
	at org.jooq.impl.DefaultParseContext.expected(ParserImpl.java:15195)
	at org.jooq.impl.DefaultParseContext.parseAlterSequence(ParserImpl.java:4458)
	at org.jooq.impl.DefaultParseContext.parseAlter(ParserImpl.java:3072)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1122)
	at org.jooq.impl.DefaultParseContext.lambda$parse$0(ParserImpl.java:910)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:15405)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:898)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:776)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:771)
	at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:179)
	at org.jooq.meta.extensions.ddl.DDLDatabase.lambda$export$0(DDLDatabase.java:166)
	at org.jooq.FilePattern.load0(FilePattern.java:310)
	at org.jooq.FilePattern.load(FilePattern.java:290)
	at org.jooq.FilePattern.load(FilePattern.java:303)
	at org.jooq.FilePattern.load(FilePattern.java:259)
	at org.jooq.meta.extensions.ddl.DDLDatabase.export(DDLDatabase.java:166)
	at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:100)
	... 127 more

```

### sql 2
```java
Caused by: org.jooq.impl.ParserException: Unsupported query type: [83:49] ...
ALTER TABLE mjga.permission ALTER COLUMN id ADD [*]GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mjga.permission_id_seq
  ...
	at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:15212)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1291)
	at org.jooq.impl.DefaultParseContext.lambda$parse$0(ParserImpl.java:910)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:15405)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:898)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:776)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:771)
	at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:179)
	at org.jooq.meta.extensions.ddl.DDLDatabase.lambda$export$0(DDLDatabase.java:166)
	at org.jooq.FilePattern.load0(FilePattern.java:310)
	at org.jooq.FilePattern.load(FilePattern.java:290)
	at org.jooq.FilePattern.load(FilePattern.java:303)
	at org.jooq.FilePattern.load(FilePattern.java:259)
	at org.jooq.meta.extensions.ddl.DDLDatabase.export(DDLDatabase.java:166)
	at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpretingDatabase.java:100)
	... 127 more

```

### sql 3
```java
Caused by: org.jooq.impl.ParserException: Token ')' expected: [199:82] ...R COLUMN id SET DEFAULT nextval('mjga.oidc_id_seq'[*]::regclass);


--
-- Name: purchase oder_no_uniq; Type: CONSTRAINT; Schema: ...
	at org.jooq.impl.DefaultParseContext.expected(ParserImpl.java:15178)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:14339)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:14334)
	at org.jooq.impl.DefaultParseContext.parseNextvalCurrvalIf(ParserImpl.java:9883)
	at org.jooq.impl.DefaultParseContext.parseTerm(ParserImpl.java:9082)
	at org.jooq.impl.DefaultParseContext.parseUnaryOps(ParserImpl.java:8376)
```

### Steps to reproduce the problem

PostgreSQL=17.2
Jooq =3.19.16
1. Run pg_dump `sudo docker exec -it database pg_dump -U username -O -s -x database > backup.sql` or `sudo docker exec -it database pg_dump -U username -s database > backup.sql`
2. Run `jooqCodeGen` with `backup.sql`
3. An error has occurred.

### jOOQ Version

JOOQ 3.19.16 community edition

### Database product and version

PostgreSQL 17.2

### Java Version

openjdk version 21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.4

**Comment by ccmjga** [comment] 2024-12-25 04:57
And the following was not created by `pg_dump`, but it did throw a ParserException
```sql
DROP TYPE IF EXISTS "mjga"."oidc_platfrom";
CREATE TYPE "mjga"."oidc_platfrom" AS ENUM ('oidc_name');
```
```java
Caused by: org.jooq.impl.ParserException: Unsupported query type: [15:27] ...ISTS mjga.oidc_id_seq;
DROP TYPE IF EXISTS "mjga"[*]."oidc_platfrom";
CREATE TYPE "mjga"."oidc_platfrom" AS ENUM ('oidc_name');

-...
	at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:15212)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1291)
	at org.jooq.impl.DefaultParseContext.lambda$parse$0(ParserImpl.java:910)
```

**Comment by lukaseder** [comment] 2024-12-27 09:39
Thanks for your report.

Note that a workaround for most of these is to use the jOOQ parser ignore syntax:

- https://blog.jooq.org/the-jooq-parser-ignore-comment-syntax/

I've created separate issues for the things that can be fixed easily. Separate issues are much more easily trackable than summary issues like this one:

- https://github.com/jOOQ/jOOQ/issues/17806 (sql 1)
- https://github.com/jOOQ/jOOQ/issues/17807 (sql 3)
- https://github.com/jOOQ/jOOQ/issues/17808 (comment)

There's already a feature request for:

- https://github.com/jOOQ/jOOQ/issues/8936 (sql 2)

Closing this as a duplicate of the above.

**Closed by lukaseder** 2024-12-27 09:39 UTC
Labels: T: Defect, P: Medium, E: All Editions, C: Parser
