### ISSUE TITLE
Automatic JPA Entity mapping without @Column

### ISSUE THREAD

**Issue by cdalexndr** [jOOQ/jOOQ#8940] opened 2019-07-14 16:45 UTC
When mapping query results to a JPA Entity using method `Record.into(Class type)`, currently I need to map every column with a `@Column(name=...)` annotation.

I suggest an automatic mapping using hibernate's [NamingStrategy](https://docs.jboss.org/hibernate/orm/5.1/javadocs/org/hibernate/cfg/NamingStrategy.html) to resolve entity members to column names, when `@Column(name=...) `is missing, and not `@Transient`.

This proposition is for Hibernate impl of JPA.

**Comment by lukaseder** [comment] 2019-07-15 07:29
Thank you very much for your suggestion. Indeed, we could enhance our support for this JPA annotation, and possibly for others. There is already a feature request for this on the roadmap: #4586

Currently, I'm unsure whether we should invest more into supporting JPA annotations, or do something much more explicit / FP friendly in the future. Supporting JPA annotations is quite some investment, and not 100% aligned with jOOQ's API philosophy.

I'm closing this as a duplicate of #4586

**Closed by lukaseder** 2019-07-15 07:29 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Enhancement
