### ISSUE TITLE
Introduce jOOQ setting to hide fetched results in LoggerListener

### ISSUE THREAD

**Issue by marceloverdijk** [jOOQ/jOOQ#8312] opened 2019-02-10 12:22 UTC
### Use case:

Hide fetched results when enabling logging

### Possible solution you'd like to see:

Introduce a setting like `renderFetchedResults` to enable/disable logging the fetched results in https://github.com/jOOQ/jOOQ/blob/master/jOOQ/src/main/java/org/jooq/tools/LoggerListener.java#L144-L154

Please describe a possible solution you'd like to see in jOOQ, ideally with example code.

### Possible workarounds:

Override LoggerListener.

### Versions:

- jOOQ:
- Java: 3.11
- Database (include vendor): N/A
- OS: N/A
- JDBC Driver (include name if inofficial driver): N/A

**Comment by lukaseder** [comment] 2019-02-11 08:26
Thank you very much for your suggestion. This idea has been discussed a few times both on the mailing list and on github. The last time was here: #7301

I have rejected #7301 based on the following grounds:

1) The logger listener is incredibly simple and can be written by users in any way they want very easily
2) Just adding a flag for the results won't do it. We'll need to add a flag for every little thing the logger listener currently does, as people have had very different ideas of what they want logged and what not. Not only what is logged, but also on what log level and in what order. Perhaps even add an expression language, such that certain logs can be turned on and off dynamically? At which point we should quickly review the complexity (or lack thereof) of the implementation of the default logger listener to see that any such request will just lead to overengineering the default logger listener.

I will close this as a duplicate of #7301

**Closed by lukaseder** 2019-02-11 08:26 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Enhancement

**Comment by marceloverdijk** [comment] 2019-02-17 09:51
OK thx for feedback.
