### ISSUE TITLE
NullPointerException in GenerationUtil with Postgres CITEXT extension applied

### ISSUE THREAD

**Issue by ayedo** [jOOQ/jOOQ#6078] opened 2017-04-14 08:42 UTC
Environment: jooq-codegen:3.9.1, Postgres:9.6, JDBC: postgresql:42.0.0, Java:1.8.0_05 

Enabling the [CITEXT extension ](https://www.postgresql.org/docs/current/static/citext.html) with

`CREATE EXTENSION citext`

crashes the generator with [this output](https://gist.github.com/ayedo/69e3aca0644ec0d8a98c857f75faecf3).

Excluding the following two functions removes the issue:

`
<excludes>
      public.regexp_matches |
      public.regexp_split_to_table
</excludes>
`

**Comment by lukaseder** [comment] 2017-04-25 09:18
Thanks for reporting. I can reproduce this issue. The relevant query producing this result is in `PostgresTableValuedFunction`:

```sql
(
  select 
    "information_schema"."parameters"."parameter_name", 
    row_number() over (partition by "information_schema"."parameters"."specific_name" order by "information_schema"."parameters"."ordinal_position" asc) as "ordinal_position", 
    "information_schema"."parameters"."data_type", 
    "information_schema"."parameters"."character_maximum_length", 
    "information_schema"."parameters"."numeric_precision", 
    "information_schema"."parameters"."numeric_scale", 
    'true' as "is_nullable", 
    "information_schema"."parameters"."parameter_default" as "column_default", 
    "information_schema"."parameters"."udt_schema", 
    "information_schema"."parameters"."udt_name"
  from "information_schema"."routines"
    join "information_schema"."parameters"
    on ("information_schema"."routines"."specific_catalog", "information_schema"."routines"."specific_schema", "information_schema"."routines"."specific_name") = ("information_schema"."parameters"."specific_catalog", "information_schema"."parameters"."specific_schema", "information_schema"."parameters"."specific_name")
    join "pg_catalog"."pg_namespace"
    on "information_schema"."routines"."specific_schema" = "pg_catalog"."pg_namespace"."nspname"
    join "pg_catalog"."pg_proc"
    on (
      "pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid
      and "pg_catalog"."pg_proc"."proname" = "information_schema"."routines"."routine_name"
    )
  where (
    "information_schema"."routines"."specific_name" = 'regexp_matches_414762'
    and "information_schema"."parameters"."parameter_mode" <> 'IN'
    and "pg_catalog"."pg_proc"."proretset"
  )
)
union all (
  select 
    coalesce("information_schema"."columns"."column_name", 'regexp_matches') as "column_name", 
    coalesce("information_schema"."columns"."ordinal_position", 1) as "ordinal_position", 
    coalesce("information_schema"."columns"."data_type", "information_schema"."routines"."data_type") as "data_type", 
    coalesce("information_schema"."columns"."character_maximum_length", "information_schema"."routines"."character_maximum_length") as "character_maximum_length", 
    coalesce("information_schema"."columns"."numeric_precision", "information_schema"."routines"."numeric_precision") as "numeric_precision", 
    coalesce("information_schema"."columns"."numeric_scale", "information_schema"."routines"."numeric_scale") as "numeric_scale", 
    coalesce("information_schema"."columns"."is_nullable", 'true') as "is_nullable", 
    coalesce("information_schema"."columns"."column_default", null) as "column_default", 
    coalesce("information_schema"."columns"."udt_schema", null) as "udt_schema", 
    coalesce("information_schema"."columns"."udt_name", "information_schema"."routines"."udt_name") as "udt_name"
  from "information_schema"."routines"
    left outer join "information_schema"."columns"
    on ("information_schema"."routines"."type_udt_catalog", "information_schema"."routines"."type_udt_schema", "information_schema"."routines"."type_udt_name") = ("information_schema"."columns"."table_catalog", "information_schema"."columns"."table_schema", "information_schema"."columns"."table_name")
    join "pg_catalog"."pg_namespace"
    on "information_schema"."routines"."specific_schema" = "pg_catalog"."pg_namespace"."nspname"
    join "pg_catalog"."pg_proc"
    on (
      "pg_catalog"."pg_proc"."pronamespace" = "pg_catalog"."pg_namespace".oid
      and (("pg_catalog"."pg_proc"."proname" || '_') || cast("pg_catalog"."pg_proc".oid as varchar)) = "information_schema"."routines"."specific_name"
    )
  where (
    "information_schema"."routines"."specific_name" = 'regexp_matches_414762'
    and ("information_schema"."routines"."specific_catalog", "information_schema"."routines"."specific_schema", "information_schema"."routines"."specific_name") not in (
      select 
        "information_schema"."parameters"."specific_catalog", 
        "information_schema"."parameters"."specific_schema", 
        "information_schema"."parameters"."specific_name"
      from "information_schema"."parameters"
      where "information_schema"."parameters"."parameter_mode" = 'OUT'
    )
    and "pg_catalog"."pg_proc"."proretset"
  )
)
order by 2 asc
```

which doesn't return the correct data type information for the return type of this function:

![image](https://cloud.githubusercontent.com/assets/734593/25377805/d4961880-29a8-11e7-9223-f14fff3e944f.png)

Will investigate

**Comment by lukaseder** [comment] 2017-04-25 09:43
This seems to be an issue in the PostgreSQL `information_schema` dictionary views (not the first), where the unreliable `udt_name` column doesn't contain the correct information.

I guess we'll have to resort to coalescing one more value into the second `union all` subquery:

```sql
    coalesce(
      "information_schema"."columns"."udt_name", 
      "information_schema"."routines"."udt_name", 
      (
        select "pg_catalog"."pg_type"."typname"
        from "pg_catalog"."pg_type"
        where "pg_catalog"."pg_type".oid = "pg_catalog"."pg_proc"."prorettype"
      )
    ) as "udt_name"
```

This way, the NPE can be fixed on my machine, and the correct type information is included. Note, there's no need to install `citext`. The same issue can be observed with "ordinary text" function equivalents in the `pg_catalog`

Thanks again for reporting!

**Closed by lukaseder** 2017-04-25 09:43 UTC
Labels: C: Code Generation, C: DB: PostgreSQL, P: Medium, T: Defect
