### ISSUE TITLE
JOOQ, Don't get enum from DB Postgresql

### ISSUE THREAD

**Issue by PetiaLeshiy** [jOOQ/jOOQ#10455] opened 2020-07-29 06:52 UTC
- jOOQ: 3.13.2
- Java: 11
- Database (include vendor): postgresql
- OS: MAc
- JDBC Driver (include name if inofficial driver): postgresql 42.2.11

Hello!
I have a problem) I hope, you can help me.

I have two identical Schema in Postgresql DB - for example "public" and "pavlik". In this schema i have table with enum type column, and type:

```sql
test1=# create type testType as ENUM ('TEST');
CREATE TYPE
test1=# create type test.testType as ENUM ('TEST');
CREATE TYPE
test1=# create table testTable (id integer, name varchar(50), type testType); 
CREATE TABLE
test1=# create table test.testTable (id integer, name varchar(50), type test.testType); 
CREATE TABLE
test1=# insert into test.testTable (id, name, type) values (1, 'pavlik', 'TEST');
INSERT 0 1
test1=# insert into testTable (id, name, type) values (1, 'pavlik', 'TEST');
INSERT 0 1
```

And i have model and Enum in java.

When i generate java files with jooq - no problem in both case files generated, type field = my java Enum.
But when i try to take data from db:

```
case1 (schema = public) - TestTableModel{id=1, name='pavlik', type=TEST}
case2 (schema = test) - TestTableModel{id=1, name='pavlik', type=**null**}
```

I have tried for case two used enum implement EnumType with override field - vainly.

example git project for you:

https://github.com/PetiaLeshiy/testJooq/tree/develop

**Comment by lukaseder** [comment] 2020-07-29 14:21
Thanks a lot for your report. I will look into this soon. This one seems related: https://github.com/jOOQ/jOOQ/issues/10277

**Comment by lukaseder** [comment] 2022-03-29 07:18
Thanks a lot for your patience. Finally looking into this. Can reproduce it with jOOQ 3.13.2 and also with jOOQ 3.16.5.

The problem seems to be related to the missing generated enum type, i.e. when you use `<includes>.*</includes>`, the problem goes away.

From the example itself, it's unclear though why the enum converter wouldn't work for schemas other than `public`. Will investigate that.

**Comment by lukaseder** [comment] 2022-03-29 07:22
The problem is that the `EnumConverter` looks up the database object as is, when in fact, without any explicit data type associated with it (e.g. the generated enum), the supplied database object is of type `PGobject`, the JDBC driver wrapper type:

![image](https://user-images.githubusercontent.com/734593/160555954-1c88c735-a03a-4be7-b71c-020667d7d660.png)

Seemingly, because the JDBC driver feels the need for documenting the qualified type name. This isn't the case when the schema is `public`, which is why things work there:

![image](https://user-images.githubusercontent.com/734593/160556202-115729b4-f12d-476a-9868-ccc39df1831d.png)

I'll have to investigate this a bit further. Seems to be inconsistent behaviour by the JDBC driver...

**Comment by lukaseder** [comment] 2022-03-29 07:55
Neither with a table involved:

```java
try (Statement s = connection.createStatement()) {
    try {
        s.execute("create type e as enum ('a', 'b')");
        s.execute("create table t (e e)");
        s.execute("insert into t values ('a'::e)");
        s.execute("create schema s");
        s.execute("create type s.e as enum ('a', 'b')");
        s.execute("create table s.t (e s.e)");
        s.execute("insert into s.t values ('a'::s.e)");

        try (ResultSet rs = s.executeQuery("select public.t.e, s.t.e from public.t, s.t")) {
            while (rs.next()) {
                Object o1 = rs.getObject(1);
                Object o2 = rs.getObject(2);

                System.out.println(o1 + ":" + o1.getClass());
                System.out.println(o2 + ":" + o2.getClass());
            }
        }
    }
    finally {
        s.execute("drop table t");
        s.execute("drop type e");
        s.execute("drop schema s cascade");
    }
}
```

This still produces:

```
a:class java.lang.String
a:class java.lang.String
```

**Comment by lukaseder** [comment] 2022-03-29 08:02
I see. My JDBC tests were done with `org.postgresql:postgresql:42.3.3`. Your dependency in your test project was `org.postgresql:42.2.11`. Upgrading the JDBC driver fixes the problem also in your reproducer.

**Comment by lukaseder** [comment] 2022-03-29 08:03
Closing this as "worksforme" as the bug was in the JDBC driver.

**Closed by lukaseder** 2022-03-29 08:03 UTC
Labels: T: Defect, C: Code Generation, C: DB: PostgreSQL, P: Medium, R: Worksforme, E: All Editions
