### ISSUE TITLE
Error when converting String valued but Object typed column to Enum type

### ISSUE THREAD

**Issue by bligny** [jOOQ/jOOQ#17536] opened 2024-11-05 08:48 UTC
### Expected behavior

As far as I know, String to/from Java enum conversions are built-in/automatic !?

### Actual behavior

Caused by: org.jooq.exception.DataTypeException: Cannot cast from class java.lang.Object (instance type: class java.lang.String to class java.lang.Object
	at org.jooq.impl.DefaultConverterProvider.lambda$provide$3(DefaultConverterProvider.java:137)
	at org.jooq.Converters.lambda$nullable$0(Converters.java:261)
	at org.jooq.Converter$1.from(Converter.java:248)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:358)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.set(DefaultRecordMapper.java:1163)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.mapNonnested(DefaultRecordMapper.java:1154)
	at org.jooq.impl.DefaultRecordMapper$ImmutablePOJOMapper.map(DefaultRecordMapper.java:1141)

### Steps to reproduce the problem

Here is my (pretty stupid) POJO class:

```java
@Value // Lombok
public class CrunchedMovement {
    ...
    private AccountingJournalType journalType;
    .... 
}

public enum AccountingJournalType {
    BUY, SELL, FIN, OD, OTHER, REOPEN
}
```

and the query that gives an error:

```java
...
return dslContext.select(FIELDS) // all fields (including the 'journalType' column)
                .from(CRUNCHED_MOVEMENT)
                .where(condition)
                .fetchSize(FETCH_SIZE)
                .fetchInto(CrunchedMovement.class)              
                .stream();
```

When debugging, I see that JOOQ is unable to map the (string) "FIN" value:

![IntelliJ IDEA 2024-11-05 09 12 51](https://github.com/user-attachments/assets/906553c3-6762-4bf7-81f8-97020e9b9885)

I do not understand what's wrong with my code ?
Should I customise the default (SpringBoot starter) config in order to support enums, eg:

```java:
    @Bean
    public DefaultConfigurationCustomizer configurationCustomizer() {
        return (config ->
                config.settings()
                        .withRenderNameCase(RenderNameCase.LOWER)
        );
    }
```

### jOOQ Version

3.19.14 (OpenSource)

### Database product and version

H2

### Java Version

java-21.0.4-amzn

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.h2database:h2:2.2.224

**Comment by bligny** [comment] 2024-11-05 09:36
Forgot to add that the db type of the journal type is not a db enum but a mere string:

`journal_type varchar(255)`

**Comment by lukaseder** [comment] 2024-11-05 11:33
Thanks for your report. I cannot reproduce such a problem with a minimal reproducer:

```java
class A {
    final String x;
    final E y;

    A(String x, E y) {
        this.x = x;
        this.y = y;
    }

    @Override
    public String toString() {
        return "A [x=" + x + ", y=" + y + "]";
    }
}

enum E { A, B }
```

And then:

```java
System.out.println(
    ctx.select(val("A").as("x"), val("B").as("y"))
        .fetchOneInto(A.class)
);
```

Produces:

```
12:30:57,655 DEBUG [LoggerListener                ] - Fetched result           : +----+----+
12:30:57,655 DEBUG [LoggerListener                ] -                          : |x   |y   |
12:30:57,655 DEBUG [LoggerListener                ] -                          : +----+----+
12:30:57,655 DEBUG [LoggerListener                ] -                          : |A   |B   |
12:30:57,655 DEBUG [LoggerListener                ] -                          : +----+----+
12:30:57,655 DEBUG [LoggerListener                ] - Fetched row(s)           : 1
A [x=A, y=B]
```

Even adding the `@ConstructorProperties` annotation (which I assume is generated by Lombok's `@Value`?) doesn't change things

Please provide a complete reproducer, ideally without using Lombok. We have a template that makes creating minimal reproducers really simple:
https://github.com/jOOQ/jOOQ-mcve

**Comment by lukaseder** [comment] 2024-11-05 11:38
There's a bug in the error message itself:

> Cannot cast from class java.lang.Object (instance type: class java.lang.String to class java.lang.Object

The second type (*"to class"*) shouldn't be the same as the first one (*"from class"*). I've created a separate issue for this:

- https://github.com/jOOQ/jOOQ/issues/17537

**Comment by lukaseder** [comment] 2024-11-05 13:29
It's probably this change:

- https://github.com/jOOQ/jOOQ/issues/10071

Did you upgrade from before 3.14?

**Comment by lukaseder** [comment] 2024-11-05 14:49
Another workaround is to copy `DefaultRecordMapper` and set it on your configuration with an additional check `tWrapper == Object.class` to delegate to the internal `Convert` utility.

**Comment by lukaseder** [comment] 2024-11-05 14:58
I mean, like this:

```patch
diff --git a/jOOQ/src/main/java/org/jooq/impl/DefaultConverterProvider.java b/jOOQ/src/main/java/org/jooq/impl/DefaultConverterProvider.java
index a6301d9..e1794ee 100644
--- a/jOOQ/src/main/java/org/jooq/impl/DefaultConverterProvider.java
+++ b/jOOQ/src/main/java/org/jooq/impl/DefaultConverterProvider.java
@@ -85,6 +85,7 @@
         if (tWrapper == uWrapper
             || uWrapper.isAssignableFrom(tWrapper)
             || isCollection(tWrapper) && isCollection(uWrapper)
+            || tWrapper == Object.class
             || tWrapper == Optional.class
             || uWrapper == Optional.class
             || uWrapper == String.class
```

**Comment by lukaseder** [comment] 2024-11-05 15:45
Fixed in versions:

- 3.20.0
- 3.19.16 (https://github.com/jOOQ/jOOQ/issues/17541)
- 3.18.23 (https://github.com/jOOQ/jOOQ/issues/17542)
- 3.17.32 (https://github.com/jOOQ/jOOQ/issues/17543)

**Closed by lukaseder** 2024-11-05 15:45 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by bligny** [comment] 2024-11-06 08:10
> Did you upgrade from before 3.14?

Yes, from 3.13.6

**Comment by lukaseder** [comment] 2024-11-06 08:39
> > Did you upgrade from before 3.14?
> 
> Yes, from 3.13.6

Thanks for confirming
