### ISSUE TITLE
Unable to run codegen when user does not have access to `mysql.proc` table

### ISSUE THREAD

**Issue by royaldark** [jOOQ/jOOQ#10333] opened 2020-06-30 18:05 UTC
### Expected behavior and actual behavior:

Expected: Jooq code generation succeeds, even if the MySQL user does not have access to the `mysql` schema
Actual: In Jooq 3.13.x, code generation fails when the user does not have access to the `mysql` schema

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

1. Create a non-root MySQL user. This user will by default have access to `information_schema`, but not `mysql`.
2. Create a table and include it in code generation.
2. Attempt to run codegen, and it fails due to insufficient permissions.

Example error:

```
Exception while executing meta query: SELECT command denied to user 'myuser'@'myip' for table 'proc'

  If you think this is a bug in jOOQ, please report it here: https://github.com/jOOQ/jOOQ/issues/new

  Note you can mute some exceptions using the configuration/onError flag

  select
    mysql.proc.db as ROUTINE_SCHEMA,
    mysql.proc.name as ROUTINE_NAME,
    mysql.proc.comment as ROUTINE_COMMENT,
    mysql.proc.param_list,
    mysql.proc.returns,
    mysql.proc.type as ROUTINE_TYPE
  from mysql.proc
  where mysql.proc.db in (<database names...>)
  order by
    1,
    2,
    6
```

### Versions:

- jOOQ: 3.13.2 (affects all 3.13.x, does NOT appear to affect 3.12.x)
- Java: 1.8.0_191-b12
- Database (include vendor): MySQL 5.x
- OS: OSX
- JDBC Driver (include name if inofficial driver):

This appears to be a regression, identical to the original issue, https://github.com/jOOQ/jOOQ/issues/2958.

Original issue discussion: https://groups.google.com/forum/#!topic/jooq-user/WpUnYQSDIlY

I strongly suspect this to be the offending change: https://github.com/jOOQ/jOOQ/commit/4e9a29dbd65db2a7844831d9d2902ee834d81314#diff-fe2a65bf991b1deea30109e1bba052b5

**Comment by lukaseder** [comment] 2020-07-01 08:43
Thanks a lot for your report.

> I strongly suspect this to be the offending change: [4e9a29d#diff-fe2a65bf991b1deea30109e1bba052b5](https://github.com/jOOQ/jOOQ/commit/4e9a29dbd65db2a7844831d9d2902ee834d81314#diff-fe2a65bf991b1deea30109e1bba052b5)

This just reorganised code around checking if some table exists. I don't think it's really related to any regression. 

In jOOQ 3.12, we already checked the `mysql.proc` table to find routines in MySQL 5.x:
https://github.com/jOOQ/jOOQ/blob/version-3.12.4/jOOQ-meta/src/main/java/org/jooq/meta/mysql/MySQLDatabase.java#L465

But yes, the logging strategy changed with 3.13, via #9807, which corresponds to the `configuration/onError` flag mentioned in the log message. I agree that there should be an additional check to see if the `PROC` table can be accessed. We only check if it exists right now.

**Comment by lukaseder** [comment] 2020-07-01 08:49
What grants do you have for your user?

```sql
show grants for myuser
```

**Comment by lukaseder** [comment] 2020-07-01 08:58
This grant is required to even see the `mysql` database tables in `information_schema.tables`:

```sql
grant show view on `mysql`.* TO 'myuser'@'%'
```

I'm curious, what's the use case of granting users to show views in that schema, but not to query them?

**Comment by royaldark** [comment] 2020-07-01 19:51
The user has the following grants:

```
GRANT USAGE ON *.*
GRANT ALL PRIVILEGES ON `chatdb`.* 
```


> But yes, the logging strategy changed with 3.13, via #9807, which corresponds to the configuration/onError flag mentioned in the log message.

Does that mean setting `onError = 'LOG'` in the Gradle configuration is the recommended way to handle errors like this from now on?

**Comment by lukaseder** [comment] 2020-07-02 10:15
> Does that mean setting `onError = 'LOG'` in the Gradle configuration is the recommended way to handle errors like this from now on?

I recommend more fine grained grants, or a different database user for code generation only

**Comment by lukaseder** [comment] 2020-07-02 10:25
While this is indeed a regression on a previous issue, there are workarounds, such as logging or more suitable grants. If there is no grant to read the `mysql.proc` table, then stored procedures cannot be generated in MySQL 5.7. Ignoring this error is an option (as in #2958), but

1. It is debatable as well, because if someone *wants* stored procedure support on MySQL 5.7, and doesn't get them, then trouble shooting the grants might be difficult if they don't see an obvious exception
2. This should really be solved with grants
3. Starting from MySQL 8, the `mysql.proc` table has been removed, and we're not using it anymore, so this problem is MySQL 5.x specific
4. Another workaround is to just turn off `<includeRoutines/>`, to prevent the query entirely
5. While this is a problem about default grants in MySQL (e.g. curiously, the `information_schema` is selectable but not the `mysql` schema with your grants), technically, it could happen with all the individual tables as well. E.g. someone could have a grant to read `information_schema.tables`, but not `information_schema.columns`. Maybe, there's room for a solution where we check for both the existence, and the sufficiency of grants of each table that `jOOQ-meta` is querying, but not in a MySQL specific way: https://github.com/jOOQ/jOOQ/issues/10344

I'm closing this as a duplicate of #10344, where we'll implement a more thorough solution than one that just works for the MySQL 5.x `mysql.proc` table.

**Closed by lukaseder** 2020-07-02 10:25 UTC
Labels: C: Code Generation, C: DB: MySQL, E: All Editions, P: Medium, T: Defect
