### ISSUE TITLE
Optimistic lock is ignored on onDuplicateKeyUpdate

### ISSUE THREAD

**Issue by pavan2017** [jOOQ/jOOQ#10253] opened 2020-06-08 13:35 UTC
I am using jOOQ  version 3.13.1. Opmistic lock is ignored when updating record with onDuplicateKeyUpdate.
It would be nice to have optimistic lock working with onDuplicateKeyUpdate so that we dont miss mergeInto feature

**Comment by lukaseder** [comment] 2020-06-08 13:40
Thank you very much for your report. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/10050, which will ship with jOOQ 3.14.

**Closed by lukaseder** 2020-06-08 13:40 UTC
Labels: T: Defect
