### ISSUE TITLE
H2 generated key processing failure

### ISSUE THREAD

**Issue by oflege** [jOOQ/jOOQ#8062] opened 2018-11-26 10:22 UTC
### Expected behavior and actual behavior:
For this table
```
CREATE TABLE mcve.test
(
  uid  UUID    NOT NULL DEFAULT RANDOM_UUID(),
  name VARCHAR NOT NULL,
  num  INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT pk_test PRIMARY KEY (uid)
);
```
this code
```
      TestRecord t = ctx.newRecord(TEST);
        t.setUid(UUID.randomUUID()); // fails if this line is included, succeeds if not ?!
        t.setName("test");
        t.insert();
```
fails with "Cannot convert from 0 (class java.lang.Integer) to class java.util.UUID". Apparently, the generated key value 0 belongs to the 'num' column but is processed as if it were belonging to 'uid'.

It only fails for the latest h2 Version 1.4.197 and only if the table has a non-key column with a default value and the actual key value is set explicitly.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

https://github.com/oflege/jOOQ-mcve

### Versions:

- jOOQ: 3.11.7
- Java: 1.8
- Database (include vendor): h2 1.4.197
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2018-11-26 10:40
Thanks a lot for your report and thanks also for using our new MCVE template - I could reproduce this right away. Will investigate now

**Comment by katzyn** [comment] 2018-11-26 10:45
For information: there was a minor issue in 1.4.197 with default columns.
https://github.com/h2database/h2database/issues/994

If columns with generated keys are not specified, this version returns not only real generated columns, but also a columns with constant default expressions. However, all returned columns have their names in `ResultSetMetaData`, so it's easy to choose the proper one.

**Comment by lukaseder** [comment] 2018-11-26 10:52
Thanks a lot for your quick feedback, @katzyn. I can confirm this issue does not occur with 1.4.196 or 1.4.198-SNAPSHOT, so it seems to be fixed.

jOOQ is accessing those returned columns by index, not by name. In this case, it seems that there is only 1 column and its value is zero. `rs.getMetaData().getColumnLabel(1)` returns `NUM` as mentioned by @oflege, so I guess jOOQ cannot really do much here...

**Comment by lukaseder** [comment] 2018-11-26 10:53
I'm closing this as the fix seems to be very local to only one version of H2, and the problem has already been fixed in H2

**Closed by lukaseder** 2018-11-26 10:53 UTC
Labels: C: DB: H2, C: Functionality, E: All Editions, P: High, R: Wontfix, T: Defect

**Comment by katzyn** [comment] 2018-11-26 10:58
H2 does not return values that weren't actually generated. `uid` column will be returned if and only if its value weren't set explicitly.
```
t.setUid(UUID.randomUUID());
```
If this value is passed to an `INSERT` statement, it will not be returned. That's why there is no `uid` column in generated keys.

**Comment by lukaseder** [comment] 2018-11-26 11:00
Thanks for the additional info. jOOQ can handle that, in fact.
