### ISSUE TITLE
An API incompatibility was encountered while executing org.jooq:jooq-codegen-maven:3.19.16:generate

### ISSUE THREAD

**Issue by markwimpory** [jOOQ/jOOQ#17781] opened 2024-12-16 13:31 UTC
### Expected behavior

I was expecting to get a JOOQ code gen of my JPA entity classes.  Using latest Hibernate and latest JOOQ

### Actual behavior

[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.19.16:generate (default-cli) on project csor-death-crindex: Execution default-cli of goal org.jooq:jooq-codegen-maven:3.19.16:generate failed: An API incompatibility was encountered while executing org.jooq:jooq-codegen-maven:3.19.16:generate: java.lang.NoSuchMethodError: 'void org.hibernate.tool.schema.spi.SchemaCreator.doCreation(org.hibernate.boot.Metadata, org.hibernate.tool.schema.spi.ExecutionOptions, org.hibernate.tool.schema.spi.SourceDescriptor, org.hibernate.tool.schema.spi.TargetDescriptor)'
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.jooq:jooq-codegen-maven:3.19.16

Looking at the hibernate code this method call is missing the parameter  ContributableMatcher

### Steps to reproduce the problem

            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>3.19.16</version>

                <executions>
                    <execution>
                        <id>jooq-codegen</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>

                <configuration>
                    <generator>
                        <database>
                            <name>org.jooq.meta.extensions.jpa.JPADatabase</name>
                            <properties>

                                <property>
                                    <key>packages</key>
                                    <value>uk.gov.hmpo.crpf.csor.deathcrindex.jpa;</value>
                                </property>

                                <property>
                                    <key>useAttributeConverters</key>
                                    <value>true</value>
                                </property>

                                <property>
                                    <key>unqualifiedSchema</key>
                                    <value>none</value>
                                </property>

                            </properties>
                        </database>
                    </generator>
                </configuration>
            </plugin>

### jOOQ Version

jOOQ Open 3.19.16

### Database product and version

N/A but target is postgres

### Java Version

openjdk 17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

N/A but target is postgres

**Comment by lukaseder** [comment] 2024-12-16 17:11
Duplicate of: https://github.com/jOOQ/jOOQ/discussions/17780

**Closed by lukaseder** 2024-12-16 17:11 UTC
Labels: P: Medium, T: Support request, C: Integration: Jakarta EE, E: All Editions
