### ISSUE TITLE
Order of calling DataType.asConvertedDataType(Converter) and DataType.getArrayDataType() should not matter

### ISSUE THREAD

**Issue by juriad** [jOOQ/jOOQ#13073] opened 2022-02-15 08:32 UTC
This issue is similar to https://github.com/jOOQ/jOOQ/issues/13029 and https://github.com/jOOQ/jOOQ/issues/10664 (where I tried to report my use-case.

### Expected behavior

The following two types should be equivalent in all situations:

```
Converter<UUID, Id> converter = Converter.ofNullable(UUID.class, Id.class, Id::new, Id::getUuid);

    DataType<Id[]> IDS = SQLDataType.UUID
            .asConvertedDataType(converter)
            .getArrayDataType();

    DataType<Id[]> IDS2 = SQLDataType.UUID
            .getArrayDataType()
            .asConvertedDataType(converter.forArrays());
```

### Actual behavior

The first one generates incorrect insert values (possibly casts). The second generates incorrect column type during create table.

### Steps to reproduce the problem

Create a table using type IDS2, the column will not be an array.
Insert an array using IDS, the value will not be `UUID.toString()` but `Id.toString()`

```
        ctx.createTable("a").column("b", IDS).execute(); // IDS2 create table with wrong column type (UUID instead of UUID[])
        ctx.insertInto(DSL.table("a"))
//                .values((Object) new Id[] {Id.rnd()}) // wrong serialization as expected - jOOQ does not know the type Id
//                .values(DSL.val(new Id[]{Id.rnd()}, IDS)) // wrong serialization
                .values(DSL.val(new Id[]{Id.rnd()}, IDS2)) // works
                .execute();

        ctx
//                .select(DSL.field("b")) // fetches as UUID[] which is expected - jOOQ does not know the type Id
                .select(DSL.field("b", IDS)) // works
                .select(DSL.field("b", IDS2)) // works
                .from("a")
                .fetch();
```

In the previous code `Id` is simply:
```
class Id {
        private final UUID uuid;

        public Id(UUID uuid) {
            this.uuid = uuid;
        }

        public static Id rnd() {
            return new Id(UUID.randomUUID());
        }

        public UUID getUuid() {
            return uuid;
        }

        // toString (if defined) must not return `uuid.toString()`
    }
```
---

In case of IDS2 for create table, I tracked the issue down to:
```
AbstractDataType:306:
    public String getTypeName(Configuration configuration) {
        return this.getDataType(configuration).getTypeName();
    }
```
where this is the `ConvertedDataType` and the `this.getDataType(configuration)` is the `ArrayDataType`. Then asking for `getTypeName()` must return wrong value (assigned in constructor of `ArrayDataType` as best effort approach I suspect) because the configuration and dialect are not known to the `ArrayDataType`.

The second case of IDS used for insert is caused by `ArrayDataType` not overriding `getBinding()` (nor passing it to `super` in the constructor like `DomainDataType` does it). It fails in `org.jooq.impl.DefaultBinding.AbstractBinding#sql(org.jooq.BindingSQLContext<U>)` where the converter (obtained from `ArrayDataType`) is `IdentityConverter`.

---
<jOOQ-feedback>

We use converted data types a lot. Sometimes jOOQ is hiding bugs for us; consider this piece of code (not related to arrays this time):
```
        ctx.createTableIfNotExists("a").column("b", ID).execute();
        ctx.insertInto(DSL.table("a")).values(UUID.randomUUID()).execute();
```
Clearly, we provided the wrong value - the type is UUID instead of Id, and it magically worked. This also "works":
```
ctx.insertInto(DSL.table("a")).values(DSL.inline("56dd38a1-811d-4827-b2f1-61236910f968")).execute();
```

~What is worse, when we try to convert to the same data type (which we don't do in our codebase), the conversion is ignored. This inserts a random UUID which is not correct.~
Edit: this actually works as expected; the insert does not mention the datatype of the column anywhere. When the datatype is explicitly added (as `.columns(DSL.field("b", CONVERTED_UUID))` or in values `DSLval(UUID.randomUUID(), CONVERTED_UUID)`) it inserts `00000000-0000-0001-0000-000000000001`.
```
        ctx.createTableIfNotExists("b").column("b", SQLDataType.UUID
                .asConvertedDataType(Converter.ofNullable(UUID.class, UUID.class,
                        u -> new UUID(0, 0), u -> new UUID(1, 1)))).execute();
        ctx.insertInto(DSL.table("b")).values(UUID.randomUUID()).execute();
        System.out.println(ctx.select().from(DSL.table("b")).fetch());
```

We sometimes wish for jOOQ to be more strict.

</jOOQ-feedback>

### Versions

- jOOQ: 3.16.4 professional (but our project actually uses 3.15 and cannot be yet upgraded to 3.16 due to https://blog.jooq.org/jooq-3-16-and-java-ee-vs-jakarta-ee/, so the fix should also target 3.15)
- Java: 11
- Database (include vendor): Postgres 11+
- OS: Linux
- JDBC Driver (include name if inofficial driver):

**Comment by juriad** [comment] 2022-02-16 09:10
Fetching does not work either when using `IDS` because the converter is actually not called. jOOQ just decides to convert `UUID` to `Id` by invoking the constructor of `Id` instead of using the converter of the DataType. That works in the previous demonstration but not in our actual codebase where `Id` does not have a single argument constructor. What is worse, calling the constructor may be the wrong thing to do.

Replace the definition of `Id` with this one:
```
    static class Id {
        private final UUID uuid;

        public Id(UUID uuid, boolean flag) {
            this.uuid = uuid;
        }

        static Id rnd() {
            return new Id(UUID.randomUUID(), true);
        }

        static Id fromUUID(UUID uuid) {
            return new Id(uuid, false);
        }

        public UUID getUuid() {
            return uuid;
        }
    }
```

This will cause:
```
rg.jooq.exception.DataAccessException: SQL [select b from a]; Error while reading field: b, at JDBC index: 1

	at org.jooq_3.16.4.POSTGRES.debug(Unknown Source)
	at org.jooq_3.16.4.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3089)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1462)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1423)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:236)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:259)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2843)
	at org.jooq.mcve.test.java.JavaTest.test(JavaTest.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.sql.SQLException: Error while reading field: b, at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1584)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1523)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1482)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1447)
	... 38 more
Caused by: org.jooq.exception.DataTypeException: Cannot convert from 2392c438-3f09-493c-a2e2-0afcaff647e6 (class java.util.UUID) to class org.jooq.mcve.test.java.JavaTest$Id
	at org.jooq.impl.Convert$ConvertAll.fail(Convert.java:1484)
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:1317)
	at org.jooq.impl.Convert.convert0(Convert.java:432)
	at org.jooq.impl.Convert.convert(Convert.java:507)
	at org.jooq.impl.Convert.convertArray(Convert.java:394)
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:646)
	at org.jooq.impl.Convert.convert0(Convert.java:432)
	at org.jooq.impl.Convert.convert(Convert.java:507)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.convertArray(DefaultBinding.java:1377)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.pgGetArray(DefaultBinding.java:1366)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1289)
	at org.jooq.impl.DefaultBinding$DefaultArrayBinding.get0(DefaultBinding.java:1143)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:997)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1574)
	... 42 more
```

Can we disable this jOOQ (in)convenience of implicit conversion? We want to always be explicit about types. Any mismatch *must* cause an exception (or not compile if possible). jOOQ *must not* try to convert types just because there exists a single-parameter constructor. It also *must not* call `toString()` on values that it does not have converter/binding for. This just goes against the fast-fail principle and makes jOOQ much less reliable.

We spent a full day trying to find out what was happening. In the end, the same workaround as for inserting values (using `IDS2` instead of `IDS`) also helps here.

**Comment by lukaseder** [comment] 2022-02-17 10:52
Thanks again for your detailed report. I can reproduce the issues. The behaviour is different on jOOQ 3.17, 3.16, and 3.15, partially because https://github.com/jOOQ/jOOQ/issues/13029 already works around one problem when creating the DDL, though it doesn't fix the problem correctly. One `DataType` expression correctly produces `uuid[]` in DDL (the vendor specific type declaration), the other one produces `uuid array` (the standard type declaration, which happens to work as well in PostgreSQL). So, somewhere, the `SQLDialect` information is lost, or not used.

Before I further investigate, here a few answers to some points you made:

> Sometimes jOOQ is hiding bugs for us; consider this piece of code (not related to arrays this time):

I appreciate that there have been some frustrations in the discovery of this problem, but in order to best help you, and actually fix things, it's always best to keep separate concerns separate.

I will address tangential topics here in this comment, but this issue will be about the array type conversion problems.

Regarding that specific example:

```java
ctx.createTableIfNotExists("a").column("b", ID).execute();
ctx.insertInto(DSL.table("a")).values(UUID.randomUUID()).execute();
```

I'm not sure what else you were expecting? The `INSERT` statement is operating without any type information, and `UUID` is a type jOOQ supports natively (`SQLDataType.UUID`). Just like when you write this:

```java
ctx.createTableIfNotExists("a").column("b", INTEGER).execute();
ctx.insertInto(DSL.table("a")).values(1).execute();
```

What possible failures would you expect here? The `INSERT INTO t VALUES (?)` statement is treacherous. People should usually provide explicit column lists instead. But it's valid SQL in many dialects, so we support it as well.

> Clearly, we provided the wrong value - the type is UUID instead of Id, and it magically worked.

It didn't "magically" work, although I can see why you were surprised. But again, your `Converter<T, U>` binds `T = UUID` and `U = Id`, and `UUID` happens to be supported by jOOQ.

> This also "works":
> 
> ```java
> ctx.insertInto(DSL.table("a")).values(DSL.inline("56dd38a1-811d-4827-b2f1-61236910f968")).execute();
> ```

Of course it does! Because this works in native PostgreSQL:

```sql
create table t (u uuid);
insert into t values ('56dd38a1-811d-4827-b2f1-61236910f968');
```

We could argue the benefits and drawbacks of implicit type conversions in SQL itself. I've been bitten a few times by Oracle's auto-conversion between `VARCHAR2` and `NUMBER` in the past. We could argue SQLite's "type affinity", which essentially means there are no types.

But you seem to be attributing these caveats to jOOQ? You didn't tell jOOQ anything about the data types involved, so what else could jOOQ be doing in your case? It just binds a string, and that happens to work in PostgreSQL.

> Can we disable this jOOQ (in)convenience of implicit conversion? We want to always be explicit about types. Any mismatch _must_ cause an exception (or not compile if possible). jOOQ _must not_ try to convert types just because there exists a single-parameter constructor. It also _must not_ call `toString()` on values that it does not have converter/binding for. This just goes against the fast-fail principle and makes jOOQ much less reliable.
> 
> We spent a full day trying to find out what was happening. In the end, the same workaround as for inserting values (using `IDS2` instead of `IDS`) also helps here.

I will investigate what is actually happening and why. Again, I can very much relate to the frustration of spending so much time with tricky bugs. But in order to do the right thing *now*, it's important to first sort out:

- What's a bug (which can be addressed relatively easily)
- What's a design flaw (which may not be addressed as easily, because we value backwards compatibility and don't want to break someone else's code)
- What's just a misunderstanding

I'll update this issue with additional findings, soon.

**Comment by lukaseder** [comment] 2022-02-17 11:26
So, a first problem is related to https://github.com/jOOQ/jOOQ/issues/13029 and I've described it further in https://github.com/jOOQ/jOOQ/issues/13029#issuecomment-1042842836.

This test still fails:

```java
Configuration h2 = using(H2).configuration();
Configuration pg = using(POSTGRES).configuration();

Converter<Integer, String> is = Converter.ofNullable(Integer.class, String.class, Object::toString, Integer::valueOf);
Converter<String, Integer> si = is.inverse();

Converter<Integer[], String[]> isa = is.forArrays();
Converter<String[], Integer[]> sia = si.forArrays();

assertEquals("integer array", INTEGER.getArrayDataType().asConvertedDataType(isa).getTypeName());
assertEquals("integer array", INTEGER.asConvertedDataType(is).getArrayDataType().getTypeName());
assertEquals("int array", INTEGER.getArrayDataType().asConvertedDataType(isa).getTypeName(h2));
assertEquals("int array", INTEGER.asConvertedDataType(is).getArrayDataType().getTypeName(h2));
assertEquals("int[]", INTEGER.getArrayDataType().asConvertedDataType(isa).getTypeName(pg));
assertEquals("int[]", INTEGER.asConvertedDataType(is).getArrayDataType().getTypeName(pg));

assertEquals("integer array", INTEGER.getArrayDataType().asConvertedDataType(isa).getCastTypeName());
assertEquals("integer array", INTEGER.asConvertedDataType(is).getArrayDataType().getCastTypeName());
assertEquals("int array", INTEGER.getArrayDataType().asConvertedDataType(isa).getCastTypeName(h2));
assertEquals("int array", INTEGER.asConvertedDataType(is).getArrayDataType().getCastTypeName(h2));
assertEquals("int[]", INTEGER.getArrayDataType().asConvertedDataType(isa).getCastTypeName(pg));
assertEquals("int[]", INTEGER.asConvertedDataType(is).getArrayDataType().getCastTypeName(pg));
```

It is an extension of #13029, as the original #13029 only tested array data types, not converted array data types. That part will be fixed and backported as of #13029, and it should fix the `CREATE TABLE` problem illustrated by this issue here.

**Comment by lukaseder** [comment] 2022-02-17 11:42
With that fix in place:

```java
// This still doesn't work:
DataType<UUIDWrapper[]> t1 = SQLDataType.UUID.asConvertedDataType(converter).getArrayDataType();

// This now works:
DataType<UUIDWrapper[]> t2 = SQLDataType.UUID.getArrayDataType().asConvertedDataType(converter.forArrays());
```

As a workaround, that could be good enough, in case the second problem exposed here proves more tricky to solve, though it shouldn't be. I'll investigate that later, today.

**Comment by lukaseder** [comment] 2022-02-17 13:47
So, it looks as though the `converter` somehow gets lost in the first case. Will check if that's a regression on https://github.com/jOOQ/jOOQ/issues/10664, or something unrelated.

In any case, while I agree that both should work the same way (see also https://github.com/jOOQ/jOOQ/issues/10664), they're not equivalent. Specifically in the case of working with custom `Binding`, there's no way jOOQ can make the first version work, where the custom data type `Binding` has been implemented for `U` values, but not for `U[]` values.

We should possibly throw an exception in those cases: https://github.com/jOOQ/jOOQ/issues/13094.

While this is definitely confusing, I think it makes sense in hindsight? An explicit `Converter` (or `Binding`) for arrays should always be preferred:

```java
SQLDataType.UUID.getArrayDataType().asConvertedDataType(converter.forArrays())
```

**Comment by lukaseder** [comment] 2022-02-17 15:03
This override in `ConvertedDataType` seems to be sufficient:

```java
    @Override
    public final DataType<U[]> getArrayDataType() {
        return delegate.getArrayDataType().asConvertedDataType(binding.converter().forArrays());
    }
```

It makes sure the two expressions are equivalent by turning the first one into the second one.

**Comment by lukaseder** [comment] 2022-02-17 16:26
Narrator: It wasn't sufficient.

The change exposed another bug / edge case when using nested ad-hoc converters along with arrays, e.g. this:

```java
    static record Book(int id, String title) {}
    static record BooksWithAuthor(String firstName, String lastName, Book[] books, List<Book> bookList) {}
    static record BooksWithAuthorAndId(int id, BooksWithAuthor author) {}

    public void testFetchIntoRecordMapperBasedOnFunctionsWithAdHocConverterAndNestedRowsAndArrays() throws Exception {
        List<BooksWithAuthorAndId> result =
        create().select(
                    TAuthor_ID(),
                    row(
                        TAuthor_FIRST_NAME(),
                        TAuthor_LAST_NAME(),

                        // [#11823] Can't omit the Class<U> literal here when wrapping a ROW(...)[]
                        array(select(row(TBook_ID(), TBook_TITLE()).mapping(Book.class, Book::new))
                            .from(TBook())
                            .where(TBook_AUTHOR_ID().eq(TAuthor_ID()))
                            .orderBy(TBook_ID())
                        ),
                        array(select(row(TBook_ID(), TBook_TITLE()).mapping(Book.class, Book::new))
                            .from(TBook())
                            .where(TBook_AUTHOR_ID().eq(TAuthor_ID()))
                            .orderBy(TBook_ID())
                        ).convertFrom(Arrays::asList)
                    ).mapping(BooksWithAuthor::new)
                )
                .from(TAuthor())
                .orderBy(TAuthor_ID())
                .fetch(mapping(BooksWithAuthorAndId::new));

        assertEquals(AUTHOR_IDS, seq(result).map(r -> r.id).toList());
        assertEquals(AUTHOR_FIRST_NAMES, seq(result).map(r -> r.author.firstName).toList());
        assertEquals(AUTHOR_LAST_NAMES, seq(result).map(r -> r.author.lastName).toList());
        assertEquals(asList(BOOK_IDS.subList(0, 2), BOOK_IDS.subList(2, 4)), seq(result).map(a -> Seq.seq(a.author.bookList).map(b -> b.id).toList()).toList());
        assertEquals(asList(BOOK_TITLES.subList(0, 2), BOOK_TITLES.subList(2, 4)), seq(result).map(a -> Seq.of(a.author.books).map(b -> b.title).toList()).toList());
        assertEquals(asList(BOOK_TITLES.subList(0, 2), BOOK_TITLES.subList(2, 4)), seq(result).map(a -> Seq.seq(a.author.bookList).map(b -> b.title).toList()).toList());
    }
```

I guess that other bug was cancelled out by this bug here somehow.

**Comment by lukaseder** [comment] 2022-02-18 08:29
Spinning off parts of the fix as a new feature: https://github.com/jOOQ/jOOQ/issues/13097

**Comment by lukaseder** [comment] 2022-02-18 09:14
Fixed in jOOQ 3.17.0, 3.16.5 (https://github.com/jOOQ/jOOQ/issues/13102), and 3.15.9 (https://github.com/jOOQ/jOOQ/issues/13101). The fix should be available from the next nightly builds from here: https://www.jooq.org/download/versions

Would love to hear if 3.15.9-SNAPSHOT fixes the issue for you.

Regarding the various criticism expressed here:

> Can we disable this jOOQ (in)convenience of implicit conversion? We want to always be explicit about types. Any mismatch _must_ cause an exception (or not compile if possible). jOOQ _must not_ try to convert types just because there exists a single-parameter constructor. It also _must not_ call `toString()` on values that it does not have converter/binding for. This just goes against the fast-fail principle and makes jOOQ much less reliable.

I think that most of this was just a side-effect of the two bugs discussed in this issue here. The various reflection based mappings are very useful for a lot of users, so I think we can disclaim any "must not" recommendations at this point - we certainly don't want to break anyone else's code.

Obviously, in your case there must not be any unexpected behaviour, but that was just produced by the bugs, not by some design error. If you still think that there are implicit conversion problems after this fix has been applied, I'll be very happy to discuss them in separate issues.

**Closed by lukaseder** 2022-02-18 09:14 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by juriad** [comment] 2022-02-18 10:55
I tested it with `jOOQ-3.17.0-SNAPSHOT-20220218010018.zip` and confirm that all scenarios work as expected. Thanks for the quick fix! 

We actually use CustomTables like this. The table has parametrized data types coming through the constructor. Fixing this issue allows us to simply derive an array data type whenever needed.

```
    // we don't ever need to use the TableRecord because we always hand-pick which columns we want to select
    class TR extends CustomRecord<TR> {
        protected TR(Table<TR> table) {
            super(table);
        }
    }

    class T extends CustomTable<TR> {
        public final TableField<TR, Id> id;
        public final TableField<TR, Id[]> ancestors;

        protected T(String name, DataType<Id> idType) {
            super(DSL.name(name));
            id = createField("id", idType.nullable(false));
            ancestors = createField("ancestors", idType.getArrayDataType().nullable(false));
            // some other fields
        }

        @Override
        public Class<? extends TR> getRecordType() {
            return TR.class;
        }
    }
```

Yeah, half of the frustration comes from the bug and the other half from unreasonable expectations like:
```
ctx.createTableIfNotExists("a").column("b", ID).execute();
ctx.insertInto(DSL.table("a")).values(UUID.randomUUID()).execute();
```
I am so used to working with tables defined like above, that I forget that in this case, I am not providing enough information. It is funny how hard it is to simplify my use-case to a small demonstration of a bug while not making bugs myself.

---

Maybe this could be considered a feature request:
```        
ctx.insertInto(t)
//                .columns(t.id, t.ancestors)
                .values(UUID.randomUUID().toString(), new UUID[] {UUID.randomUUID()})
                .execute();
 ```
When the columns line is uncommented, it does not compile - as expected. When commented, it "magically" works even though the types do not match (String vs Id and UUID[] vs Id[]). This time, jOOQ knows the types and uses them for conversion (if Id is given in .values), but does not require them to match.
If this is not intended, I can create an issue for it.

**Comment by lukaseder** [comment] 2022-02-18 12:06
> It is funny how hard it is to simplify my use-case to a small demonstration of a bug while not making bugs myself.

Well, I can definitely relate. Once a wrong analysis path has been chosen, it's hard to retract. Especially the second issue was not trivial at all as this regression has shown: https://github.com/jOOQ/jOOQ/issues/13073#issuecomment-1043151675

> If this is not intended, I can create an issue for it.

You could certainly make the argument, yes, so while for plain SQL templates (e.g. `t = table("t")`), nothing can be done, we could do something about `t instanceof TableImpl` or `t instanceof CustomTable`, or in short, if `t.fields()` is defined.

I'm not yet sure whether we should, but sure, why not create a feature request for this.
