### ISSUE TITLE
PostgreSQL Translation Error

### ISSUE THREAD

**Issue by arvindnitharwal** [jOOQ/jOOQ#12478] opened 2021-10-02 07:47 UTC
### translator not able to translates this query:

```sql
SELECT * FROM public.notifications where reference_object ->> 'questionId' ='0e75ce19-d124-4d86-84e8-10362c38c972'


```error
Identifier expected: [1:60] ...FROM public.notifications where reference_object -[*]>> 'questionId' ='0e75ce19-d124-4d86-84e8-10362c38c972';

**Comment by lukaseder** [comment] 2021-10-05 14:20
Thanks a lot for your report. This has been a frequent feature request, see also: https://github.com/jOOQ/jOOQ/issues/10018. We'll add support for this syntax, soon.

Closing as duplicate of https://github.com/jOOQ/jOOQ/issues/10018

**Closed by lukaseder** 2021-10-05 14:20 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, E: All Editions
