### ISSUE TITLE
Stored procedure name overloading does not work on postgres

### ISSUE THREAD

**Issue by dmiorandi** [jOOQ/jOOQ#5542] opened 2016-09-16 10:15 UTC
I'm using pg 9.2 with latest jdbc drivers. When generating jooq classes from db I run into an issue.
There are some stored procedure with name overloading. Jooq generate a record class with duplicated
fields and doesn't compile btw.
I pretty sure that this is due sp overloading. Probably jooq write more times in same class when generating (3.7.4, 3.8.4 same behavior)

I'm not sure if it's related to #4034  too.
Here there are an example (3 storead with overloading and relative generated jooq record)

[Jooq_overloading_issue.zip](https://github.com/jOOQ/jOOQ/files/476592/Jooq_overloading_issue.zip)

**Comment by lukaseder** [comment] 2016-09-16 18:02
Thank you very much for reporting. Indeed, this is an annoying, known issue: https://github.com/jOOQ/jOOQ/issues/4055

Possible workaround: Avoid overloading...

I'm closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/4055

**Closed by lukaseder** 2016-09-16 18:02 UTC
Labels: C: Code Generation, C: DB: PostgreSQL, P: Medium, R: Duplicate, T: Defect
