### ISSUE TITLE
Converter or Binding is not applied to standalone bind values that are passed to functions like DECODE(), COALESCE(), NVL(), etc.

### ISSUE THREAD

**Issue by Nthalk** [jOOQ/jOOQ#4556] opened 2015-09-15 17:08 UTC
When using a boolean converter for a `char(1): 'Y'/'N'`, using decode transforms `true` to 1 and `false` to 0. I was expecting that it would use my `StringBooleanConverter` that is bound on this field and have the `true` convert to `Y` just like the `insert`/`update`/`condition` semantics.

**Comment by lukaseder** [comment] 2015-09-16 12:11
Thank you very much for your report.

Could you maybe provide some information that will help reproduce this case? E.g.

- What do you mean by "using decode"?
- Could you perhaps show the code of your `StringBooleanConverter`
- Could you show an example that uses (should use) your converter when running a query that fails for you?

**Comment by Nthalk** [comment] 2015-09-17 19:01
Here is the code for a failing test, and configuration:

https://gist.github.com/Nthalk/5942545778811b44b380

Note that the issue is that the decode is requiring it's forced type, and than not converting the supplied argument.

**Comment by lukaseder** [comment] 2015-09-19 16:05
Thanks for the update. I see, this is indeed wrong. I suspect, though, that a variety of other use-cases behave equally wrongly. For instance the `CASE` expression itself:

```java
choose(new TestTable().FIELD1).when(true, "SO TRUE").when(false, "SO FALSE")
-- yields case "testTable"."field1" when true then 'SO TRUE' when false then 'SO FALSE' end
```

Or simpler, `COALESCE`:

```java
new TestTable().FIELD1.coalesce(true)`
-- yields coalesce("testTable"."field1", true)
```

This is a rather substantial bug. The workaround in your case would be to use explicit data types with all your bind variables:

```java
new TestTable().FIELD1.decode(
    val(true, new TestTable().FIELD1), 
    val("SO TRUE"), 
    val(false, new TestTable().FIELD1), 
    val("SO FALSE")
)
```

**Comment by lukaseder** [comment] 2015-10-06 08:34
This would be a substantial change. I'm postponing this fix for a later minor release than 3.7, as we're about to release that version

**Comment by lukaseder** [comment] 2015-12-16 10:59
Another incidence of the same issue:
https://groups.google.com/d/msg/jooq-user/XiN3OZDg0qc/-Pq96AfrAwAJ

**Comment by lukaseder** [comment] 2016-03-15 14:44
In essence, the meaning of this fix is that the `Field.getDataType()` of a "master expression" must be coerced onto any "derived expression". Coercion must be able to handle any type of `Field`, including correlated subqueries, such as:

```java
TABLE.YN.in(select(inline(value)));
```

Assuming that `YN` binds a `boolean` Java type to a `VARCHAR(1)` database type, the bind variable `value` will need to be converted to a `Y` / `N` string literal also in the subselect.

On the other hand

```java
TABLE.YN.eq(field(TABLE.A.eq(TABLE.B)));
```

This would compile, as `YN` is `Field<Boolean>` and it can be compared with a predicate as shown above. The predicate, however, doesn't encode `Y` / `N`. It is either a native boolean type, or encoded as `1` / `0`.

**Comment by erlendk** [comment] 2016-04-14 10:40
I stumbled upon this issue again today.

`BOOL_FIELD.equal(false)` does not produce the same result as `BOOL_FIELD.isFalse()`, which fails with an error for me because of the missing conversion.

Are there any good reasons for inlining the boolean value in AbstractField.isFalse, like this?:

```
else if (Boolean.class.isAssignableFrom(type)) {
    return ((Field<Boolean>) this).equal(inline(false));
}
```

Without the call to `inline` I think things would have worked in this case...

**Comment by lukaseder** [comment] 2016-04-25 16:17
Thanks for the hint about `isFalse()`. The reason for inlining is to help the optimiser make a better choice depending on index histograms. Given that there are only two possible values, inlining seemed appropriate here. This predicate was implemented long before converters and bindings, though.

Obviously, it prevents your use-case, which raises new questions - not specific to `isFalse()` but specific to converters / bindings used along with `inline()`. There are a lot of internal usage of `inline()`

**Comment by lukaseder** [comment] 2016-04-25 16:18
I'm postponing this fix for another release. Sorry for the inconvenience. There seems too big of a flaw hiding behind this to be fixed quickly. jOOQ 3.8 is due for this week...

**Comment by msiler** [comment] 2016-05-05 18:42
It seems like this issue is already being well-handled, but I'll one other case:
`q.where(booleanColumn)` does not apply the converter but `q.where(booleanColumn.eq(true))` does.

**Comment by lukaseder** [comment] 2016-05-06 11:13
@msiler: Hmm interesting. What is that `booleanColumn`? Is it really a bind variable? Because converters / bindings only apply to bind variables, not to ordinary column expressions...

**Comment by msiler** [comment] 2016-05-10 14:20
Ah, maybe this is something different then. I'll should elaborate. In my case, `booleanColumn` is a `TableField<MyTable, Boolean>` variable. I have a query similar to
```
create.select()
    .from(MyTable)
    .where(MyTable.booleanColumn)
```
If I'm using a converter to convert a Y/N char(1) column to a boolean, then the above expression doesn't work (in SQL Server, it generates `...where [dbo].[MyTable].[booleanColumn] = 1`). Instead I have to explicitly use `.where(MyTable.booleanColumn.eq(true))`. If this isn't the same phenomenon, I can open a separate issue.

**Comment by lukaseder** [comment] 2016-05-12 10:49
Oh, I see, thanks for clarifying @msiler. This makes sense of course. It is indeed the same issue as reported in a previous comment (due to usage of `DSL.inline()`):
https://github.com/jOOQ/jOOQ/issues/4556#issuecomment-209873861

Thanks for reporting!

**Comment by lukaseder** [comment] 2018-02-22 12:35
Fixed this for:

- [x] `Field.decode()` (only for search, not for result)
- [x] `DSL.choose(value).when(...)` (only for search, not for result)
- [x] `Field.coalesce()`, `Field.nvl()`, `Field.nullif()`
- Others will be fixed and listed here

**Closed** 2018-02-22 13:32 UTC
Labels: C: Functionality, P: High, T: Defect
