### ISSUE TITLE
Batch fail running queries on LocalDateTime columns

### ISSUE THREAD

**Issue by dmiorandi** [jOOQ/jOOQ#7843] opened 2018-09-03 11:59 UTC
### Expected behavior and actual behavior:
When executing a query inside jooq batch, datetime parameters are not converted in right way resulting
in a wrong query syntax (probably sql server only?).
Executed query have all datetime parameters without T character between date and time. This is the wrong query
```sql
insert into [BANBARCOD] (
  [bdd_barcode], 
  [bdd_codsoc], 
  [bdd_codart], 
  [bdd_dtvalidita]
)
values (
  '3284790032343', 
  '25', 
  'ABEB2096932', 
  cast('2018-08-31 11:27:24.703' as datetime)
)
```
and SQLServer doesn't accept that expression without T. Please note that datetime string expression are exactly serialization of Timestamp type.

Executing same query directly in single mode (q2.execute() not using batch) it works. I'm quite sure it works cause parameters is not passed as string but as datetime in jdbc. Could be a missing converter issue in batch?

### Steps to reproduce the problem (include example code if possible):
just execute a code like this
```
List<Query> queries=new ArrayList<>();
//cycle here to produce n queries.....
                    BanbarcodRecord banbarcodeRecord=BANBARCOD.newRecord()
                        .setBddCodsoc(calcCodSoc())
                        .setBddCodart(product.getCode())
                        .setBddBarcode(product.getEan())
                        .setBddDtvalidita(LocalDateTime.now());
                    InsertSetMoreStep<BanbarcodRecord> query2=createHpSs
                        .insertInto(BANBARCOD)
                        .set(banbarcodeRecord);
                   queries.add(query2);
//when cycle completed run batch......
                  createHpSs.batch(queries).execute();
```
record column is defined as 
```
    /**
     * The column <code>Stocksystem.dbo.BANBARCOD.bdd_dtvalidita</code>.
     */
    public final TableField<BanbarcodRecord, LocalDateTime> BDD_DTVALIDITA = createField("bdd_dtvalidita", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");
```

### Versions:

- jOOQ: 3.11.4
- Java: 1.8.0_171
- Database (include vendor): MS SQLSERVER 2008 ITALIAN
- OS: Windows Server 2008R2  ITALIAN (DB) And windows 10 (code)
- JDBC Driver (include name if inofficial driver): mssql 4.2 by Microsoft

**Comment by lukaseder** [comment] 2020-07-07 11:38
Finally looking into this. I cannot reproduce it with jOOQ 3.14. Trying to reproduce with older jOOQ versions now

**Comment by lukaseder** [comment] 2020-07-07 13:03
Cannot reproduce this with jOOQ 3.13 or 3.12 either. I wonder if this is SQL Server 2008 specific, as I've been trying things with more recent versions.

Can you still reproduce this, @dmiorandi ?

**Comment by dmiorandi** [comment] 2020-07-07 18:59
Hi @lukaseder I've no access to code in this moment. In any case what do you reproduced?
Does your code run sql query as 
2018-08-31 11:27:24.703     or
2018-08-31T11:27:24.703
It's not clear to me that part. What is sure is that my sql server instance accept just second format and give error on first.
This is why I opened this issue.

**Comment by lukaseder** [comment] 2020-07-08 10:23
Thanks for the feedback. It generates `2018-03-31 11:27:24.703`. I'm not aware of SQL Server requiring the ISO 8601 `T` character. Rather, it works with the standard SQL (optional ISO 8601) ` ` whitespace character. According to the documentation:
https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver15

Both should work, which can be verified here:
https://dbfiddle.uk/?rdbms=sqlserver_2019&fiddle=1a87bdcbcf9c3eeb4634b4c6d93407c9

When installing SQL Server with the default settings, I think the SQL format has always been accepted. I'm not sure about the ISO 8601 format. We could, of course, add some configuration in jOOQ regarding how date time literals should be generated, but I think that this will be very rarely useful, especially since it seems that newer versions of SQL Server accept both out of the box...

**Comment by lukaseder** [comment] 2020-07-08 10:24
Of course, the workaround would be to create a custom data type binding and attach that to all the `DATETIME` and `DATETIME2` data types. That way, you can control how the literal is being generated:
https://www.jooq.org/doc/3.13/manual/code-generation/custom-data-type-bindings/

**Comment by dmiorandi** [comment] 2020-07-09 11:57
Ok tks. Probably T is is due to italian db setup. I dont know. In any case
iso9660 use T.



Il Mer 8 Lug 2020, 12:24 Lukas Eder <notifications@github.com> ha scritto:

**Comment by lukaseder** [comment] 2020-07-09 12:28
Thanks for the feedback.

I'm closing this for now as I cannot reproduce it (in setups I've tried, SQL Server accepts both syntaxes, according to the documentation), and there is a workaround with the custom data type binding that overrides this.

**Closed by lukaseder** 2020-07-09 12:28 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Feedback Pending, T: Defect
