### ISSUE TITLE
Add support for altering multiple columns in one statement

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7898] opened 2018-09-26 09:06 UTC
Some databases, like Oracle, support altering multiple column definitions in a single statement:

```sql
ALTER TABLE t MODIFY (col1 type1, col2 type2);
```

jOOQ should support this as well

**Comment by knutwannheden** [comment] 2019-09-20 09:17
Closing this as a duplicate of #8834 and #8846.

**Closed by knutwannheden** 2019-09-20 09:17 UTC
Labels: C: Functionality, C: Parser, E: All Editions, P: Medium, R: Duplicate, T: Enhancement
