### ISSUE TITLE
MULTISET with MariaDB 10.6 - errors with unknown column in where clause

### ISSUE THREAD

**Issue by ascertrobw** [jOOQ/jOOQ#12414] opened 2021-09-08 17:42 UTC
Wondering if there's an issue with MariaDB supporting the awesome new MULTISET features (or whether I'm just missing something obvious).

My Java code looks like this (simplified to remove additional multiset operations):

        Result res = tlsCreate.get().select(
                        MSG_TEMPLATE.MT_ID,
                        MSG_TEMPLATE.NAME,
                        MSG_TEMPLATE.REC_VERSION,
                        multiset(
                          select(
                            COLECTION.COL_ID,
                            COLECTION.SUBPATH, 
                            COLECTION.NAME, 
                            COLECTION.SCOPE, 
                            COLECTION.REC_VERSION) 
                          .from(COLECTION)
                          .where(COLECTION.COL_ID.eq(MSG_TEMPLATE.ROOT_COL_ID))
                        )
                     )
                     .from(MSG_TEMPLATE)
                     .orderBy(MSG_TEMPLATE.MT_ID)
                     .fetch();

Which produces the following exception:

org.jooq.exception.DataAccessException: SQL [set @t = @@group_concat_max_len; set @@group_concat_max_len = 4294967295; select `MSG_TEMPLATE`.`MT_ID`, `MSG_TEMPLATE`.`NAME`, `MSG_TEMPLATE`.`REC_VERSION`, (select coalesce(json_merge_preserve('[]', concat('[', group_concat(json_array(`v0`, `v1`, `v2`, `v3`, `v4`) separator ','), ']')), json_array()) from (select distinct `COLECTION`.`COL_ID` as `v0`, `COLECTION`.`SUBPATH` as `v1`, `COLECTION`.`NAME` as `v2`, `COLECTION`.`SCOPE` as `v3`, `COLECTION`.`REC_VERSION` as `v4` from `COLECTION` where `COLECTION`.`COL_ID` = `MSG_TEMPLATE`.`ROOT_COL_ID`) as `t`) from `MSG_TEMPLATE`  order by `MSG_TEMPLATE`.`MT_ID`; set @@group_concat_max_len = @t;]; (conn=82) Unknown column 'MSG_TEMPLATE.ROOT_COL_ID' in 'where clause'

If I strip the generated query out of the error message:

```
select MSG_TEMPLATE.MT_ID, MSG_TEMPLATE.NAME, MSG_TEMPLATE.REC_VERSION, 
	(select coalesce(json_merge_preserve('[]', concat('[', group_concat(json_array(v0, v1, v2, v3, v4) separator ','), ']')), json_array()) 
		from (select COLECTION.COL_ID as v0, COLECTION.SUBPATH as v1, COLECTION.NAME as v2, COLECTION.SCOPE as v3, COLECTION.REC_VERSION as v4 
			from COLECTION where COLECTION.COL_ID = MSG_TEMPLATE.ROOT_COL_ID) as t)
from MSG_TEMPLATE order by MSG_TEMPLATE.MT_ID
```
and then try a manual query into our DB I get a consistent error - which makes me think Maria may not like the generated query.

Although it's an old thread, I wonder if it was related to this - https://stackoverflow.com/questions/50142330/sql-generated-by-jooq-for-nested-select-doesnt-work-in-mysql-mariadb. Since the where clause is nested down in a subquery.

### Versions

- jOOQ: 3.15.2
- Java: 14
- Database (include vendor): MariaDB 10.6
- OS: Windows 10

**Comment by lukaseder** [comment] 2021-09-09 07:08
Thanks for your report. This is https://github.com/jOOQ/jOOQ/issues/12045. In your particular case, you can work around the problem by using `MULTISET_AGG` instead of `MULTISET`:

```sql
Result<?> res = tlsCreate.get().select(
				MSG_TEMPLATE.MT_ID,
				MSG_TEMPLATE.NAME,
				MSG_TEMPLATE.REC_VERSION,
				multisetAgg(
					COLECTION.COL_ID,
					COLECTION.SUBPATH, 
					COLECTION.NAME, 
					COLECTION.SCOPE, 
					COLECTION.REC_VERSION) 
			 )
			 .from(MSG_TEMPLATE)
			 .join(COLECTION)
				  .on(COLECTION.COL_ID.eq(MSG_TEMPLATE.ROOT_COL_ID))
			 .groupBy(
				MSG_TEMPLATE.MT_ID,
				MSG_TEMPLATE.NAME,
				MSG_TEMPLATE.REC_VERSION)
			 .orderBy(MSG_TEMPLATE.MT_ID)
			 .fetch();
```

It's not as powerful, of course, and you'll have to handle `NULL` values in case you prefer left join semantics. It would work with MySQL 8

**Comment by lukaseder** [comment] 2021-09-09 07:08
Duplicate of https://github.com/jOOQ/jOOQ/issues/12045

**Closed by lukaseder** 2021-09-09 07:08 UTC
Labels: T: Defect

**Comment by lukaseder** [comment] 2021-09-09 07:10
You can upvote this issue, of course: https://jira.mariadb.org/browse/MDEV-19078, and perhaps even leave a comment making a case in favour of supporting this particular jOOQ feature (which works on MySQL 8)

**Comment by ascertrobw** [comment] 2021-09-09 07:52
Cheers - I thought I had tried multisetAgg, but I guess in all the various forms I tried I must have got some part wrong!
