### ISSUE TITLE
Add transaction support for Reactive API

### ISSUE THREAD

**Issue by segocago** [jOOQ/jOOQ#12842] opened 2022-01-12 11:29 UTC
### Use case:

Transaction is an essential feature for software development. Jooq does have transactional support for non reactive api but it does not seem to have the same support for reactive api. I saw @lukaseder 's comment about reactive api not having transaction support yet in the blog [post](https://blog.jooq.org/reactive-sql-with-jooq-3-15-and-r2dbc/) where reactive support is announced. I've checked the recent release notes to see if it was added in the recent versions but could not find it there either. 

### Possible solution you'd like to see:

Adding transaction support to reactive api.

### Possible workarounds:

I can't see any workarounds for this except not using reactive api since transaction support is a must have for our services.

### Versions:

- jOOQ: 3.15.4 - open source
- Java: 17
- Database (include vendor): PostgreSQL 11.11
- OS:
- JDBC Driver (include name if inofficial driver): r2dbc

**Comment by lukaseder** [comment] 2022-01-12 12:11
Thanks for your report. Just like with JDBC, offering an R2DBC backed transaction API is mere convenience and not strictly necessary as you can fall back to:

- R2DBC's native transaction API
- Relying on Spring to manage transactions for you

We'll offer this API eventually, but that's already tracked here: https://github.com/jOOQ/jOOQ/issues/11717

Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/11717

**Closed by lukaseder** 2022-01-12 12:11 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, R: Duplicate, E: All Editions

**Comment by segocago** [comment] 2022-01-12 12:21
Thanks for your quick reply Lukas. I did not see [#11717](https://github.com/jOOQ/jOOQ/issues/11717) while searching for transaction among issues. We are using micronaut instead of Spring but it also seems to have a transactional support. Guess we need to use it until the support is added.

**Comment by lukaseder** [comment] 2022-01-12 12:58
That seems to work just like Spring's transaction management:
https://micronaut-projects.github.io/micronaut-r2dbc/1.0.x/guide/#transactionManagement

Why would you prefer jOOQ's? Whatever jOOQ is going to offer will be much more low level than the aspect oriented approach by these frameworks.

**Comment by segocago** [comment] 2022-01-12 13:18
I did not think we could use micronaut transaction management with Jooq, i was thinking it was for the Micronaut Data ORM. An AoP solution would be nice, need to check the documents to make it work with Jooq.

**Comment by lukaseder** [comment] 2022-01-12 13:29
I haven't tried it myself, but I'd say the point of frameworks like Spring/Spring Boot/Micronaut is precisely to implement this kind of glue code and provide the necessary objects via dependency injection. I'd naively assume that if you run `@Transactional` code, and inject a jOOQ `DSLContext` anywhere, then it would be pre-configured. If not, that's worth a feature request, but you can still inject the R2DBC `ConnectionFactory` (https://micronaut-projects.github.io/micronaut-r2dbc/1.0.x/guide/#clients) and wrap that in a jOOQ `DSLContext` with a 1-liner: `DSL.using(connectionFactory)`
