### ISSUE TITLE
SQL Translation Error: MySQL session variables in SQL statements

### ISSUE THREAD

**Issue by CloudDevOpsEngineer** [jOOQ/jOOQ#10657] opened 2020-09-21 01:03 UTC
### SQL translator incorrectly translates this query:

```sql
Select * 
from (
SELECT `COUNT`,((`COUNT`*SUM(Duration))/3600) AS total
FROM (
    SELECT
        COUNT(*) AS `Count`,
        UNIX_TIMESTAMP(Times2.Time) - UNIX_TIMESTAMP(Times1.Time) AS Duration
    FROM (
        SELECT @rownum1 := @rownum1   1 AS rownum, `Time`
        FROM (
            SELECT DISTINCT(lineItem_UsageStartDate) AS `Time` FROM data.book1
            UNION
            SELECT DISTINCT(lineItem_UsageEndDate) AS `Time` FROM data.book1
        ) AS AllTimes, (SELECT @rownum1 := 0) AS Rownum
        ORDER BY `Time` DESC
    ) As Times1
    JOIN (
        SELECT @rownum2 := @rownum2   1 AS rownum, `Time`
        FROM (
            SELECT DISTINCT(lineItem_UsageStartDate) AS `Time` FROM data.book1
            UNION
            SELECT DISTINCT(lineItem_UsageEndDate) AS `Time` FROM data.book1
        ) AS AllTimes, (SELECT @rownum2 := 0) AS Rownum
        ORDER BY `Time` DESC
    ) As Times2
    ON Times1.rownum = Times2.rownum   1
    JOIN data.book1 ON Times1.Time >= data.book1.lineItem_UsageStartDate AND Times2.Time <= data.book1.lineItem_UsageEndDate
    GROUP BY Times1.rownum
) Totals
GROUP BY `Count`
) AS workaround
where COUNT > 1
```

### Parser output:

```sql
Token ')' expected: [9:25] ...e) AS Duration
    FROM (
        SELECT @rownum1 [*]:= @rownum1   1 AS rownum, `Time`
        FROM (
            SELECT DISTINCT(lin...
```

**Comment by lukaseder** [comment] 2020-09-21 07:05
Thanks a lot for your report.

Supporting the syntax in our parser and in the jOOQ API is on the roadmap: https://github.com/jOOQ/jOOQ/issues/2558.

However, translating it seems quite difficult, and I'm not even sure if it can be done correctly. SQL is a 4GL. It normally doesn't matter in which order statements are executed. These session variables from within SQL statements, however, make a lot of assumptions about this order. In your example, it can be reasonably expected that the cross joined `@rownum := 0` expression will somehow be executed first, and the increments in the projection `@rownum1 := @rownum1 + 1` later. But in more complex statements, where `@rownum` might also appear in the `WHERE` clause, one can quickly see how edge cases make transformations of this expression hard.

I tend to suggest a manual rewrite to using MySQL 8 window functions (`ROW_NUMBER() OVER ...`).

Closing this as a duplicate of #2558

**Closed by lukaseder** 2020-09-21 07:05 UTC
Labels: C: Parser, C: Translator, E: All Editions, P: Medium, T: Enhancement
