### ISSUE TITLE
feat(comment): be able to add comment on query for analysis and observability

### ISSUE THREAD

**Issue by davinkevin** [jOOQ/jOOQ#11335] opened 2021-01-29 09:58 UTC
### Use case:

Following the ability to trace and analysis request cost and impact, a new "system" is available through a [library](https://github.com/google/sqlcommenter) and a managed service on Google Cloud Service for [CloudSQL](https://cloud.google.com/blog/products/databases/get-ahead-of-database-performance-issues-with-cloud-sql-insights?utm_source=twitter&utm_medium=unpaidsoc&utm_campaign=FY21-Q1-GC-Blog&utm_content=-&utm_term=-). 

As a developer, I would like to be able to add this kind of comment on my SQL request, through the JOOQ API. 

Link to https://github.com/google/sqlcommenter/issues/40

### Possible solution you'd like to see:

```kotlin
query
                .select(ITEM.ID, ITEM.TITLE, ITEM.URL,
                        ITEM.PUB_DATE, ITEM.DOWNLOAD_DATE, ITEM.CREATION_DATE,
                        ITEM.DESCRIPTION, ITEM.MIME_TYPE, ITEM.LENGTH, ITEM.FILE_NAME, ITEM.STATUS,

                        PODCAST.ID, PODCAST.TITLE, PODCAST.URL,
                        COVER.ID, COVER.URL, COVER.WIDTH, COVER.HEIGHT
                )
                .from(
                        ITEM.innerJoin(PODCAST).on(ITEM.PODCAST_ID.eq(PODCAST.ID))
                                .innerJoin(COVER).on(ITEM.COVER_ID.eq(COVER.ID))
                )
                .where(ITEM.ID.eq(id))
                .comment("controller='index',db_driver='django.db.backends.postgresql',
framework='foo/bar',route='/api/v1/items%24',
traceparent='00-5bd66ef5095369c7b0d1f8f4bd33716a-c532cb4098ac3dd2-01',
tracestate='congo%3Dt61rcWkgMzE%2Crojo%3D00f067aa0ba902b7'")
```

### Possible workarounds:

I think, some workarounds are possible trough `ExecutionListener`, but not really sure if this is the right / best solution. 

### Versions:

- jOOQ: 3.14+
- Java: 11+
- Database (include vendor): PostgreSQL at first in my case
- OS: Linux
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2021-01-29 10:31
Thanks for your suggestion. I'm closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/2541, which is more far reaching than just appending a comment somewhere, because the logical extension to this is:

- Being able to append arbitrary SQL fragments
- Doing this anywhere in the query, not just at the end

You can already use the `hint()` method to append arbitrary comments, or plain SQL templating. E.g. replace your `where()` clause with:

```java
.where("{0} /* controller='index',db_driver='django.db.backends.postgresql' */", ITEM.ID.eq(id))
```

Or use an `ExecuteListener`, which I think is the best approach to this type of tagging of queries, which then applies to an entire set of queries automatically, and won't be forgotten on a per-query basis. Perhaps, if your driver supports it (Oracle doesn, not sure about PostgreSQL), you could even use JDBC's `Connection::setClientInfo`, which has also been designed for exactly this tagging purpose.

**Closed by lukaseder** 2021-01-29 10:31 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Duplicate, T: Enhancement

**Comment by davinkevin** [comment] 2021-01-29 16:01
Thanks for the quick response. 

I will dig on a solution based on the `ExecuteListener`. 

BTW, I didn't know we can use this kind of syntax with the `where`. But there is no equivalent if we are doing for example `orderBy`. But, like you've said, `ExecuteListener` is a better way to access sql request globally. 👍

**Comment by lukaseder** [comment] 2021-01-29 16:12
> But there is no equivalent if we are doing for example `orderBy`.

Of course there is. You can use plain SQL templates anywhere in jOOQ! E.g. `orderBy(field("{0} /* hackety-hack */", WHATEVER.COLUMN))`

Here's how it works:

- https://www.jooq.org/doc/latest/manual/sql-building/plain-sql/
- https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

**Comment by davinkevin** [comment] 2021-01-29 16:38
The JOOQ API is so huge, I always miss some parts !

Thanks for the tips 😉.

**Comment by juriad** [comment] 2021-01-29 18:40
I was just about to create an issue about the same thing. In my case I would like to prepend a comment to a query so that it is visible in `pg_stat_activity`. I don't want to add anything in the middle, I don't want to add a clause, just a comment at the beginning.

**Comment by juriad** [comment] 2021-01-29 18:44
Maybe https://github.com/jOOQ/jOOQ/issues/11265 could be used to achieve this?

**Comment by lukaseder** [comment] 2021-01-29 19:26
> @davinkevin The JOOQ API is so huge, I always miss some parts !

It happened to me, before 😁

> @juriad I was just about to create an issue about the same thing. In my case I would like to prepend a comment to a query so that it is visible in `pg_stat_activity`. I don't want to add anything in the middle, I don't want to add a clause, just a comment at the beginning.

Use an `ExecuteListener`, or wrap your query in a plain SQL template again. Though, the `ExecuteListener` feels cleaner

> Maybe #11265 could be used to achieve this?

The purpose of that is for random internal `QueryPart` implementations to be able to "emit" a signal to the renderer to generate some additional SQL. There are other, similar mechanisms to "emit" top-level CTEs. I wouldn't want to expose this as public API to users, when there's a clean, well defined SPI called `ExecuteListener` that does exactly this.

**Comment by lukaseder** [comment] 2021-01-29 19:30
I mean, it's as simple as this:

```java
ctx.configuration().derive(myListener).dsl().select(...).from(...);
```

You can hide this behind some utility API, as well, similar to that which you're using already to produce your local `DSLContext` instances. Or you use your favourite DI framework to inject two distinctly configured `DSLContext `instances.

It's really the cleanest approach to this.

**Comment by lukaseder** [comment] 2021-08-30 12:45
Here are a few recent improvements from jOOQ 3.15:

- #11530 `Configuration.deriveAppending()` makes *adding* `ExecuteListener` instances (instead of replacing them) much easier
- #11520 `ExecuteListener.onRenderEnd()` makes *creating* `ExecuteListener` instances much easier.

So, the original feature request, which was:

```java
ctx.select(...)
   .from(...)
   .comment("controller='index',[...]")
   .fetch();
```

Can now be achieved as:

```java
ctx.configuration()
   .deriveAppending(onRenderEnd(e -> e.sql(e.sql() + "/* controller='index',[...] */")))
   .dsl()
   .select(...)
   .from(...)
   .fetch();
```
