### ISSUE TITLE
Oracle RETURNING emulation doesn't use configured ConverterProvider from an AutoConverter

### ISSUE THREAD

**Issue by RenBrand** [jOOQ/jOOQ#17512] opened 2024-10-29 12:53 UTC
### Expected behavior

The `returning()`-statement of a Field which uses the `AutoConverter` (accessing a configured `ConverterProvider`) should use the ConverterContext from the given configuration.

### Actual behavior

The expected behavior happens on non-Oracle-DBs, but if an Oracle-DB with `emulateOracleReturning()` is used the wrong `ConverterContext` (the one from `org.jooq.impl.Internal.CONVERTER_SCOPE`) will be used. This causes an

```
java.lang.NullPointerException: Cannot invoke "org.jooq.Converter.fromType()" because "converter" is null
	at org.jooq_3.19.14.ORACLE23C.debug(Unknown Source)
	at org.jooq.ContextConverter.scoped(ContextConverter.java:134)
	at org.jooq.impl.AutoConverter.from(AutoConverter.java:59)
	at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:314)
	at org.jooq.impl.AbstractDataType.convert(AbstractDataType.java:767)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1239)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348)
	at org.jooq.impl.AbstractDMLQueryAsResultQuery.fetch(AbstractDMLQueryAsResultQuery.java:140)
	at org.jooq.impl.ResultQueryTrait.fetchLazy(ResultQueryTrait.java:281)
	at org.jooq.impl.ResultQueryTrait.fetchLazyNonAutoClosing(ResultQueryTrait.java:290)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:437)
	at apackage.AServiceImpl.delete(AnObject.java:177)
        ....
```

The Problem seems to be located in the ORACLE-Case of `org.jooq.impl.AbstractDMLQuery.execute(ExecuteContext, ExecuteListener)` which uses `org.jooq.DataType.convert(Object)` - Method on line 1239. This method access the `org.jooq.impl.Internal.CONVERTER_SCOPE` instead of using a ConverterContext form the current configuration which has configured a non-DefaultConfiguration.

### Steps to reproduce the problem

* create the following table
   ```SQL
   CREATE TABLE T1(
       "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY(START with 1 INCREMENT by 1),
       "JSON" VARCHAR2(4000)
    );

   INSERT INTO T1 ("JSON") VALUES ( '{"value": "test"}' );
   ```
* add a "forced type" to the configuration of the MetaData-Generator
   ```XML
  <forcedTypes>
    <forcedType>
      <userType>apackage.AnObject</userType>
      <autoConverter>false</autoConverter>
      <!-- the exact table column -->
      <includeExpression>T1\.JSON</includeExpression>
    </forcedType>
  </forcedTypes>
   ```
* Define the Java-Object
   ```
   package apackage;

   public static record AnObject( String value ) {}
   ```
* Use a `ConverterProvider` in your configuration which is able to convert a JSON-String to an Object
  ```JAVA
  ...
  dslContext.configuration().set( new org.jooq.ConverterProvider() {
      private static final JsonMapper JSON_MAPPER = JsonObjectMapperFactory.createJsonObjectMapper();

      @SuppressWarnings( { "unchecked", "rawtypes", "serial" } )
      public <T, U> Converter<T, U> provide( Class<T> tType, Class<U> uType ) {
        if( tType.equals( String.class ) && uType.equals( AnObject.class ) ) {
          return new org.jooq.impl.AbstractConverter( tType, uType ) {

            @Override
            public Object from( Object databaseObject ) {
              if( databaseObject == null ) return null;
              try {
                return JSON_MAPPER.readValue( databaseObject.toString(), uType );
              } catch( IOException e ) {
                throw new UncheckedIOException( e );
              }
            }

            @Override
            public Object to( Object userObject ) {
              if( userObject == null ) return null;
              try {
                return JSON_MAPPER.writeValueAsString( userObject );
              } catch( IOException e ) {
                throw new UncheckedIOException( e );
              }
            }

          };
        }

        return null;
      }
    } );
  ```
* use the following delete query to retrieve the delete value (for later use)
  ```JAVA
  AnObject deletedEntry = ctx.deleteFrom( T1 )
                                .where( T1.ID.eq( 1 ) )
                                .returning( T1.JSON )
                                .fetchOne( T1.JSON );
  ```

### jOOQ Version

jOOQ Professional Edition 3.19.14

### Database product and version

Oracle Database 23ai Free Release 23.0.0.0.0 - Develop, Learn, and Run for Free

### Java Version

openjdk version "21" 2023-09-19

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.oracle.database.jdbc:ojdbc11:23.5.0.24.07

**Comment by lukaseder** [comment] 2024-10-31 10:11
Thanks for your report. I tried your code against our MCVE template (https://github.com/jOOQ/jOOQ-mcve):

```patch
diff --git a/jOOQ-mcve-java-oracle/pom.xml b/jOOQ-mcve-java-oracle/pom.xml
index ecde922..7585162 100644
--- a/jOOQ-mcve-java-oracle/pom.xml
+++ b/jOOQ-mcve-java-oracle/pom.xml
@@ -30,6 +30,17 @@

     <dependencies>

+        <dependency>
+            <groupId>com.fasterxml.jackson.core</groupId>
+            <artifactId>jackson-core</artifactId>
+            <version>2.17.1</version>
+        </dependency>
+        <dependency>
+            <groupId>com.fasterxml.jackson.core</groupId>
+            <artifactId>jackson-databind</artifactId>
+            <version>2.17.1</version>
+        </dependency>
+
         <!-- TODO: Add your JDBC driver dependency here -->
         <dependency>
             <groupId>com.oracle.database.jdbc</groupId>
@@ -218,6 +229,14 @@
                                             <inputSchema>MCVE</inputSchema>
                                         </schema>
                                     </schemata>
+                                    <forcedTypes>
+                                        <forcedType>
+                                            <userType>apackage.AnObject</userType>
+                                            <autoConverter>false</autoConverter>
+                                            <!-- the exact table column -->
+                                            <includeExpression>T1\.JSON</includeExpression>
+                                        </forcedType>
+                                    </forcedTypes>
                                 </database>
                                 <generate>
                                     <generatedAnnotation>false</generatedAnnotation>
diff --git a/jOOQ-mcve-java-oracle/src/main/java/apackage/AnObject.java b/jOOQ-mcve-java-oracle/src/main/java/apackage/AnObject.java
index 2256ccf..24a7afc 100644
--- a/jOOQ-mcve-java-oracle/src/main/java/apackage/AnObject.java
+++ b/jOOQ-mcve-java-oracle/src/main/java/apackage/AnObject.java
@@ -1,4 +1,3 @@
 package apackage;

-public record AnObject() {
-}
+public record AnObject( String value ) {}
\ No newline at end of file
diff --git a/jOOQ-mcve-java-oracle/src/main/java/org/jooq/mcve/java/oracle/Mcve.java b/jOOQ-mcve-java-oracle/src/main/java/org/jooq/mcve/java/oracle/Mcve.java
index c3554df..0ff8a53 100644
--- a/jOOQ-mcve-java-oracle/src/main/java/org/jooq/mcve/java/oracle/Mcve.java
+++ b/jOOQ-mcve-java-oracle/src/main/java/org/jooq/mcve/java/oracle/Mcve.java
@@ -10,6 +10,7 @@ import java.util.List;
 import org.jooq.Catalog;
 import org.jooq.Table;
 import org.jooq.impl.SchemaImpl;
+import org.jooq.mcve.java.oracle.tables.T1;
 import org.jooq.mcve.java.oracle.tables.Test;


@@ -26,6 +27,11 @@ public class Mcve extends SchemaImpl {
      */
     public static final Mcve MCVE = new Mcve();

+    /**
+     * The table <code>MCVE.T1</code>.
+     */
+    public final T1 T1 = org.jooq.mcve.java.oracle.tables.T1.T1;
+
     /**
      * The table <code>MCVE.TEST</code>.
      */
@@ -47,6 +53,7 @@ public class Mcve extends SchemaImpl {
     @Override
     public final List<Table<?>> getTables() {
         return Arrays.asList(
+            T1.T1,
             Test.TEST
         );
     }
diff --git a/jOOQ-mcve-java-oracle/src/main/java/org/jooq/mcve/java/oracle/Tables.java b/jOOQ-mcve-java-oracle/src/main/java/org/jooq/mcve/java/oracle/Tables.java
index 567ea2e..aee6b84 100644
--- a/jOOQ-mcve-java-oracle/src/main/java/org/jooq/mcve/java/oracle/Tables.java
+++ b/jOOQ-mcve-java-oracle/src/main/java/org/jooq/mcve/java/oracle/Tables.java
@@ -4,6 +4,7 @@
 package org.jooq.mcve.java.oracle;


+import org.jooq.mcve.java.oracle.tables.T1;
 import org.jooq.mcve.java.oracle.tables.Test;


@@ -13,6 +14,11 @@ import org.jooq.mcve.java.oracle.tables.Test;
 @SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
 public class Tables {

+    /**
+     * The table <code>MCVE.T1</code>.
+     */
+    public static final T1 T1 = org.jooq.mcve.java.oracle.tables.T1.T1;
+
     /**
      * The table <code>MCVE.TEST</code>.
      */
diff --git a/jOOQ-mcve-java-oracle/src/main/resources/db/migration/init.sql b/jOOQ-mcve-java-oracle/src/main/resources/db/migration/init.sql
index 1dcc4f2..b158eae 100644
--- a/jOOQ-mcve-java-oracle/src/main/resources/db/migration/init.sql
+++ b/jOOQ-mcve-java-oracle/src/main/resources/db/migration/init.sql
@@ -3,4 +3,12 @@ CREATE TABLE mcve.test (
   cd NUMBER(7),

   CONSTRAINT pk_test PRIMARY KEY (id)
-);
\ No newline at end of file
+);
+
+
+CREATE TABLE T1(
+   "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY(START with 1 INCREMENT by 1),
+   "JSON" VARCHAR2(4000)
+);
+
+INSERT INTO T1 ("JSON") VALUES ( '{"value": "test"}' );
\ No newline at end of file
diff --git a/jOOQ-mcve-java-oracle/src/test/java/org/jooq/mcve/test/java/oracle/JavaTest.java b/jOOQ-mcve-java-oracle/src/test/java/org/jooq/mcve/test/java/oracle/JavaTest.java
index 98d3992..8a721df 100644
--- a/jOOQ-mcve-java-oracle/src/test/java/org/jooq/mcve/test/java/oracle/JavaTest.java
+++ b/jOOQ-mcve-java-oracle/src/test/java/org/jooq/mcve/test/java/oracle/JavaTest.java
@@ -1,8 +1,12 @@
 package org.jooq.mcve.test.java.oracle;

+import apackage.AnObject;
+import com.fasterxml.jackson.databind.json.JsonMapper;
+import org.jooq.Converter;
 import org.jooq.DSLContext;
 import org.jooq.SQLDialect;
 import org.jooq.impl.DSL;
+import org.jooq.mcve.java.oracle.Tables;
 import org.jooq.mcve.java.oracle.tables.records.TestRecord;
 import org.jooq.tools.JooqLogger;
 import org.junit.*;
@@ -13,12 +17,16 @@ import org.testcontainers.containers.wait.strategy.WaitAllStrategy;
 import org.testcontainers.utility.DockerImageName;
 import org.testcontainers.utility.ResourceReaper;

+import java.io.IOException;
+import java.io.UncheckedIOException;
+import java.math.BigDecimal;
 import java.sql.Connection;
 import java.sql.DriverManager;
 import java.sql.SQLException;
 import java.sql.Statement;
 import java.time.Duration;

+import static org.jooq.mcve.java.oracle.Tables.T1;
 import static org.jooq.mcve.java.oracle.Tables.TEST;
 import static org.junit.Assert.assertEquals;
 import static org.junit.Assert.assertNotNull;
@@ -95,14 +103,46 @@ public class JavaTest {

     @Test
     public void mcveTest() {
-        assertEquals(1,
-            ctx.insertInto(TEST)
-               .columns(TEST.CD)
-               .values(42)
-               .execute()
-        );
+        ctx.configuration().set( new org.jooq.ConverterProvider() {
+            private static final JsonMapper JSON_MAPPER = new JsonMapper();
+
+            @SuppressWarnings( { "unchecked", "rawtypes", "serial" } )
+            public <T, U> Converter<T, U> provide(Class<T> tType, Class<U> uType ) {
+                if( tType.equals( String.class ) && uType.equals( AnObject.class ) ) {
+                    return new org.jooq.impl.AbstractConverter( tType, uType ) {
+
+                        @Override
+                        public Object from( Object databaseObject ) {
+                            if( databaseObject == null ) return null;
+                            try {
+                                return JSON_MAPPER.readValue( databaseObject.toString(), uType );
+                            } catch( IOException e ) {
+                                throw new UncheckedIOException( e );
+                            }
+                        }
+
+                        @Override
+                        public Object to( Object userObject ) {
+                            if( userObject == null ) return null;
+                            try {
+                                return JSON_MAPPER.writeValueAsString( userObject );
+                            } catch( IOException e ) {
+                                throw new UncheckedIOException( e );
+                            }
+                        }
+
+                    };
+                }
+
+                return null;
+            }
+        } );
+
+        AnObject deletedEntry = ctx.deleteFrom(T1 )
+                .where( T1.ID.eq( BigDecimal.ONE ) )
+                .returning( T1.JSON )
+                .fetchOne( T1.JSON );

-        TestRecord record = ctx.fetchOne(TEST, TEST.CD.eq(42));
-        assertNotNull(record.getId());
+        System.out.println(deletedEntry);
     }
 }
```

I couldn't reproduce any problems, the test ran just fine:

```
11:06:51,339 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : declare o0 DBMS_SQL.VARCHAR2_TABLE; c0 sys_refcursor; begin delete from "MCVE"."T1" where "MCVE"."T1"."ID" = ? returning "MCVE"."T1"."JSON" bulk collect into o0; ? := sql%rowcount; open c0 for select * from table(o0); ? := c0; end;
11:06:51,340 DEBUG [org.jooq.tools.LoggerListener                     ] - -> with bind values      : declare o0 DBMS_SQL.VARCHAR2_TABLE; c0 sys_refcursor; begin delete from "MCVE"."T1" where "MCVE"."T1"."ID" = 1 returning "MCVE"."T1"."JSON" bulk collect into o0; ? := sql%rowcount; open c0 for select * from table(o0); ? := c0; end;
11:06:51,452 DEBUG [org.jooq.tools.LoggerListener                     ] - Affected row(s)          : 1
11:06:51,469 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched result           : +-----------------+
11:06:51,470 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |COLUMN_VALUE     |
11:06:51,470 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +-----------------+
11:06:51,470 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |{"value": "test"}|
11:06:51,470 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +-----------------+
11:06:51,470 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched row(s)           : 1
AnObject[value={"value": "test"}]
```

Can you please provide the missing bits in the above reproducer?

**Comment by lukaseder** [comment] 2024-10-31 10:14
I can see what the bug is, it's strictly related to `AutoConverter`, just trying to implement a regression test to make sure we'll fix this correctly for your case.

the workaround is to either:

- Not use `AutoConverter` but implement an explicit converter instead
- Delegate to `DefaultConverterProvider::provide` result instead of returning `null` in your `ConverterProvider`

**Comment by lukaseder** [comment] 2024-10-31 10:22
I guess this reproduces it more simply:

```java
record R(String value) {}

ctx.configuration().set(new ConverterProvider() {
    @Override
    public <T, U> Converter<T, U> provide(Class<T> tType, Class<U> uType) {
        return null;
    }
});

System.out.println(
ctx.select(val("a").coerce(VARCHAR.asConvertedDataType(new AutoConverter<String, R>(String.class, R.class))))
    .fetchOne()
    .value1()
);
```

I'm getting:

```
java.sql.SQLException: Error while reading field: 'a', at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1572)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1503)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1379)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1355)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:164)
	at org.jooq.impl.Tools.fetchOne(Tools.java:2945)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
	at org.jooq.testscripts.JDBC.main(JDBC.java:53)
Caused by: java.lang.NullPointerException: Cannot invoke "org.jooq.Converter.fromType()" because "converter" is null
	at org.jooq.ContextConverter.scoped(ContextConverter.java:134)
	at org.jooq.impl.AutoConverter.from(AutoConverter.java:59)
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1240)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1562)
	... 9 more
```

**Comment by lukaseder** [comment] 2024-10-31 10:37
> given that I couldn't reproduce the issue with your instructions

The most likely explanation is that you omitted a detail, such as another converted type that is not the `AnObject` type

**Comment by RenBrand** [comment] 2024-10-31 13:18
I will try to adapt the project to meet the error I'm talking about. Sorry for the inconvenience.

**Comment by RenBrand** [comment] 2024-10-31 13:32
@lukaseder I've modified your MCVE template in the way it fails as I mentioned it (https://github.com/RenBrand/jOOQ-mcve/tree/jOOQ-Issue-17512).

The only real difference form your test is the `AnObject` has now an additional parameter and hence jOOQ's default convert via a constructor can't be called.

```JAVA
package apackage;

public record AnObject( String value, int counter ) {}
```

and the Test-data in the `/jooq-mcve-java-oracle/src/main/resources/db/migration/init.sql` has been modified with:

```SQL
INSERT INTO T1 ("JSON") VALUES ( '{"value": "test", "counter": 42 }' );
```

**Comment by lukaseder** [comment] 2024-10-31 13:55
OK, I see now, thanks for the updated MCVE. The bug that I had fixed is still a bug, but a different (related) one. I've created a separate issue for this:

- https://github.com/jOOQ/jOOQ/issues/17525

Will look into your Oracle specific bug now. The problem is that with these `DataType.convert()` calls, the `ConverterContext` isn't passed to the `ContextConverter`. There's a generic issue for this problem:

- https://github.com/jOOQ/jOOQ/issues/16814

Will look into this particular issue right away.

**Comment by lukaseder** [comment] 2024-11-01 14:27
It appears that this particular bit of record fetching logic (Oracle style `RETURNING` implementation) uses ordinary public API to create records, rather than our internal APIs that are used to abstract over record lifecycle events, including `RecordListener` callbacks. That means that `RecordListener` also isn't invoked on the resulting records.

The fix will address both problems.

**Comment by lukaseder** [comment] 2024-11-01 14:43
After the fix, the output in your MCVE will be:

```
15:40:50,041 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : declare o0 DBMS_SQL.CLOB_TABLE; c0 sys_refcursor; begin delete from "MCVE"."T1" where "MCVE"."T1"."ID" = ? returning "MCVE"."T1"."JSON" bulk collect into o0; ? := sql%rowcount; open c0 for select * from table(o0); ? := c0; end;
15:40:50,042 DEBUG [org.jooq.tools.LoggerListener                     ] - -> with bind values      : declare o0 DBMS_SQL.CLOB_TABLE; c0 sys_refcursor; begin delete from "MCVE"."T1" where "MCVE"."T1"."ID" = 1 returning "MCVE"."T1"."JSON" bulk collect into o0; ? := sql%rowcount; open c0 for select * from table(o0); ? := c0; end;
15:40:50,430 DEBUG [org.jooq.tools.LoggerListener                     ] - Affected row(s)          : 1
15:40:50,486 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched result           : +---------------------------------+
15:40:50,486 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |COLUMN_VALUE                     |
15:40:50,486 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +---------------------------------+
15:40:50,486 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |{"value": "test", "counter": 42 }|
15:40:50,487 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +---------------------------------+
15:40:50,487 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched row(s)           : 1
AnObject[value=test, counter=42]
```

The fix relies on the presence of `ConverterContext` from jOOQ 3.18:

- https://github.com/jOOQ/jOOQ/issues/13961

... so it cannot be backported to earlier versions of jOOQ.

A lot of issues from this list still exist, so I will address them next week:

- https://github.com/jOOQ/jOOQ/issues/16814

**Comment by lukaseder** [comment] 2024-11-01 14:52
Fixed in versions:

- 3.20.0
- 3.19.15 (https://github.com/jOOQ/jOOQ/issues/17526)
- 3.18.22 (https://github.com/jOOQ/jOOQ/issues/17527)

**Closed by lukaseder** 2024-11-01 14:52 UTC
Labels: T: Defect, C: Functionality, C: DB: Oracle, P: Medium, R: Fixed, E: Professional Edition, E: Enterprise Edition
