### ISSUE TITLE
Allow access to the ConverterProvider for forcedType converters

### ISSUE THREAD

**Issue by chrisrhut** [jOOQ/jOOQ#13801] opened 2022-07-10 06:49 UTC
### Use case:

We use Jooq with Spring Boot and have a fairly intricately-configured Jackson `ObjectMapper` in our application, which we set up using the [Spring Boot ObjectMapper config options](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.spring-mvc.customize-jackson-objectmapper).

Our Spring Jooq configuration sets up a `ConverterProvider` using the SPI and, since that's done from a `@Configuration` class, we are able to inject and re-use our fully-configured Spring `ObjectMapper`.

However, the `forcedTypes` that are defined at code generation time are only able to instantiate `Converter` instances that are defined/instantiated outside of the realm of our application start-up, meaning that our custom JSONB Jackson serialization is unable to leverage the shared `ObjectMapper` instance.

Right now we have a workaround where our `Converter` uses a `static` ObjectMapper that we simply try to ensure gets initialized using Spring application lifecycle events. This works but feels fragile and hacky. I wondered if there's a way to pull the `ConverterProvider` out of the `Configuration` at conversion time instead.

### Possible solution you'd like to see:

At a very high level, I think a `Configuration` just needs to be made available in the forced type's defined `Converter` - then I believe it could delegate to `configuration.converterProvider.provide(tType, uType).convert()`. I would imagine that changing the required method signatures to pass in a configuration is a non-starter.

I noticed the `Attachable` interface provides a `configuration` and I wondered if it might work to call `attach()` on the _converter_ itself. Something along these lines:

```kt
class ProvidedConverter<T, U>(tType: Class<T>, uType: Class<U>) : AbstractConverter<T, U>(), Attachable {
  private var cfg: org.jooq.Configuration? = null

  override fun attach(configuration: org.jooq.Configuration) { cfg = configuration }
  override fun detach() { cfg = null }
  override fun configuration(): org.jooq.Configuration? = cfg

  override fun from(databaseObject: T?): U? {
    if (databaseObject == null) return null
    val config = cfg ?: throw IllegalStateException("attach() wasn't called")
    return config
      .converterProvider()
      .provide(fromType(), toType())
      .convert(fromType(), toType())
  }

  // to() omitted
}
```

Of course I'm not sure how feasible it is to invoke `attach()` everywhere needed upstream from the conversions, or whether there are other ramifications to stashing a `configuration` reference like this.

### Possible workarounds:

Our `Converter` classes reference a static `ObjectMapper` which we just make sure is initialized from the Spring-configured Jackson mapper, thanks to lifecycle events. As mentioned above, this is a bit of a hack and it'd be nice to be able to avoid it.

### Versions:

- jOOQ: 3.16.6
- Java: 17
- Database (include vendor): Postgres

**Comment by chrisrhut** [comment] 2022-07-10 18:28
Update: I came up with a different workaround to set my `configuration.converterProvider()` in a `ThreadLocal` via an `ExecuteListener`.

It still feels a _little bit_ jury-rigged but feels like a more solid solution. I'd still love to hear your input on other potential approaches in case I'm still missing something. Thanks again! 🙏

**Comment by lukaseder** [comment] 2022-07-13 19:39
Thanks for your feature request. This idea has come up a few times, and every time, it's been because of an `ObjectMapper` instance.

Personally, I don't think the static approach is hacky. `static` variables are legitimate singletons in my opinion. The fact that an `ObjectMapper` needs to participate in some elaborate application initialisation lifecycle is just a popular idiom (maybe even cargo cult), not a necessary thing. Behind the scenes, DI frameworks like Spring just hide the `static` variable from you, but they're not really doing anything else.

Also, the `ThreadLocal` approach is viable in these cases (unless you go async/reactive). I would have suggested it too if you hadn't already.

In any case, here are 2 thoughts:

- Unlike `Converter` methods, `Binding` methods can access the `Configuration`, so maybe this is an option for you? (They have their own limitations, and are more complex to implement)
- I can see a `Converter` subtype that offers an alternative API where `Configuration` objects (or rather, some other `org.jooq.Scope` object) are passed along with the `T`/`Class<T>` or `U`/`Class<U>` types. I'll think about this some time in the near future.

**Comment by chrisrhut** [comment] 2022-07-14 03:07
Thank you for your reply and validation of our approaches so far! I'll take a look into the `Binding` approach, though as you pointed out that comes with an added complexity cost and we seem to have one or two perfectly-adequate solutions at this point. 🙏

**Comment by lukaseder** [comment] 2022-07-14 16:34
> I'll take a look into the `Binding` approach, though as you pointed out that comes with an added complexity cost and we seem to have one or two perfectly-adequate solutions at this point. 🙏

Just to be sure, one of the limitations I meant is that it can't be used reasonably with `MULTISET` and `ROW` emulations, whereas `Converter` are fine.

**Comment by basanthjenuhb** [comment] 2022-08-30 08:03
@lukaseder 
Could you please provide some pointers on how this could be implemented
I can take a stab at it.

**Comment by lukaseder** [comment] 2022-08-30 08:06
The `ThreadLocal` based workarounds should do the trick for now?

In general, I'd rather not spend time explaining internals and engaging in a review process when changes are as complex as this one. Please see our contribution guidelines for details on this stance: https://github.com/jOOQ/jOOQ/blob/main/CONTRIBUTING.md

**Comment by lukaseder** [comment] 2022-09-06 07:01
I'm working on this now for jOOQ 3.18. I'll implement the work in a new, separate issue: https://github.com/jOOQ/jOOQ/issues/13961

The point of the separate issue is to document the new SPI and API, and avoid getting side-tracked with implementation specific details, e.g. of `forcedType` or of Jackson.

Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/13961

**Closed by lukaseder** 2022-09-06 07:01 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, T: Incompatible change, E: All Editions

**Comment by lukaseder** [comment] 2022-09-27 15:17
This great improvement here (implemented via https://github.com/jOOQ/jOOQ/issues/13961) has enabled `AutoConverter`, a converter that can automatically convert between `T <-> U` based on the `ConverterProvider` SPI! https://github.com/jOOQ/jOOQ/issues/13791

**Comment by chrisrhut** [comment] 2022-09-27 16:13
Thanks! Look forward to giving this a try 🙏

**Comment by lukaseder** [comment] 2022-09-27 20:48
Yeah, I just realised, you don't even need to implement your particular `Converter`, because it does exactly what `AutoConverter` does.
