### ISSUE TITLE
Getting org.jooq.impl.ParserException while getting tables/meta

### ISSUE THREAD

**Issue by cstamas** [jOOQ/jOOQ#13007] opened 2022-02-07 14:59 UTC
### Expected behavior

Code is using `context.meta().getTables(Tables.OWN_TABLE.getName())` to check presence of a table. Table is present, so I'd expect a non empty list.

### Actual behavior

jOOQ logs ParserException:
```
jvm 1    | 2022-02-07 14:26:09,272+0000 INFO  [jetty-main-1] *SYSTEM org.jooq.impl.MetaImpl - Cannot parse default expression: 0000-00-00 00:00:00
jvm 1    | org.jooq.impl.ParserException: Unexpected content after end of field input: [1:12] 0000-00-00 [*]00:00:00
jvm 1    |      at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:13549)
jvm 1    |      at org.jooq.impl.DefaultParseContext.done(ParserImpl.java:13709)
jvm 1    |      at org.jooq.impl.DefaultParseContext.parseField0(ParserImpl.java:562)
jvm 1    |      at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:427)
jvm 1    |      at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:422)
jvm 1    |      at org.jooq.impl.MetaImpl$MetaTable.initColumns(MetaImpl.java:1084)
jvm 1    |      at org.jooq.impl.MetaImpl$MetaTable.<init>(MetaImpl.java:679)
jvm 1    |      at org.jooq.impl.MetaImpl$MetaSchema.lambda$getTables$2(MetaImpl.java:425)
jvm 1    |      at org.jooq.impl.Tools.map(Tools.java:2042)
jvm 1    |      at org.jooq.impl.MetaImpl$MetaSchema.getTables(MetaImpl.java:397)
jvm 1    |      at org.jooq.impl.MetaImpl.lambda$getTables0$2(MetaImpl.java:247)
jvm 1    |      at org.jooq.impl.Tools.flatMap(Tools.java:2057)
jvm 1    |      at org.jooq.impl.MetaImpl.getTables0(MetaImpl.java:247)
jvm 1    |      at org.jooq.impl.AbstractMeta.lambda$initTables$4(AbstractMeta.java:181)
jvm 1    |      at org.jooq.impl.AbstractMeta.get(AbstractMeta.java:371)
jvm 1    |      at org.jooq.impl.AbstractMeta.initTables(AbstractMeta.java:181)
jvm 1    |      at org.jooq.impl.AbstractMeta.getTables(AbstractMeta.java:167)
jvm 1    |      at org.jooq.impl.AbstractMeta.getTables(AbstractMeta.java:162)
... own code from here (line above)
```

### Steps to reproduce the problem

I believe this has to do with MariaDB Connector/J 2.7.5 vs 3.0.3 change.

### Versions

- jOOQ: 3.15.7
- Java: 11.0.11
- Database (include vendor): MariaDB 10.1
- OS: Linux
- JDBC Driver (include name if inofficial driver): MariaDB JDBC 3.0.3 https://mariadb.com/kb/en/mariadb-connector-j-303-release-notes/  (this is my suspect, we upgraded from 2.7.5 to 3.0.3)

**Comment by cstamas** [comment] 2022-02-07 15:16
Confirmed, by downgrading MariaDB JDBC from 3.0.3 back to 2.7.5 these jOOQ logs are gone.

**Comment by lukaseder** [comment] 2022-02-08 12:01
Thanks for your report. Can you please provide the `CREATE TABLE` statement of your `OWN_TABLE` table to help reproduce this?

**Comment by cstamas** [comment] 2022-02-08 13:09
Table is not much, and I do not use any "date type" field either:
```
CREATE TABLE `my_table` (
  `itemKey` varchar(40) NOT NULL,
  `parentKey` varchar(40) NOT NULL,
  `providerKey` varchar(40) NOT NULL,
  `contentSize` bigint,
  `itemType` varchar(40) NOT NULL,
  `metadata` text NOT NULL,
  PRIMARY KEY (`itemKey`),
  INDEX `my_table_parentKey` (`parentKey`)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin';
```

**Comment by lukaseder** [comment] 2022-02-08 14:38
That table definition doesn't have any defaults, nor any temporal data types.

Can you place a breakpoint somewhere in the stack you've shown to help track down the actual table causing this problem? It seems unrelated to `OWN_TABLE`...

**Comment by lukaseder** [comment] 2022-02-08 14:40
I'll try to reproduce it by upgrading the driver to version 3.0.3 and running our integration tests... Perhaps it reproduces trivially.

**Comment by lukaseder** [comment] 2022-02-08 14:58
Yeah, that's my thought. Most integration tests fail with:

```
java.lang.ArrayIndexOutOfBoundsException: Index 379 out of bounds for length 280
	at org.jooq_3.17.0-SNAPSHOT.MARIADB.debug(Unknown Source)
	at org.mariadb.jdbc.client.impl.StandardReadableByteBuf.readByte(StandardReadableByteBuf.java:119)
	at org.mariadb.jdbc.message.server.ColumnDefinitionPacket.<init>(ColumnDefinitionPacket.java:74)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:198)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:807)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:746)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:665)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:608)
	at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:93)
	at org.mariadb.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:256)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4341)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:230)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:316)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2844)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506)
	at org.jooq.test.all.testcases.AggregateWindowFunctionTests.testAggregateFunctions_CORR(AggregateWindowFunctionTests.java:570)
	at org.jooq.test.jOOQAbstractTest.testAggregateFunctions_CORR(jOOQAbstractTest.java:6982)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

I guess you shouldn't use that version.

I'm closing this for now, seems to be a `mariadb-java-client` problem.

**Closed by lukaseder** 2022-02-08 14:58 UTC
Labels: T: Defect, C: Functionality, P: Medium, C: DB: MariaDB, R: Feedback Pending, E: All Editions

**Comment by cstamas** [comment] 2022-02-08 15:00
Strange, that one looks like https://jira.mariadb.org/browse/CONJ-901 that should be fixed in 3.0,3

**Comment by lukaseder** [comment] 2022-02-08 15:20
If they regress on their wire protocol interpretation, then they can regress numerous times...

**Comment by lukaseder** [comment] 2022-02-08 15:23
.. I mean, to me, this looks like they have a few off-by-1 errors in their binary protocol decoder, which might even explain the default that is being delivered to jOOQ?
