### ISSUE TITLE
Data type rewrites to BOOLEAN don't work in Oracle JSON_OBJECT

### ISSUE THREAD

**Issue by torstenwerner** [jOOQ/jOOQ#13690] opened 2022-06-19 08:32 UTC
The following table definition:

    create table TEST
    (
        BOOLEANCOLUMN NUMBER(1)
    );
    insert into TEST VALUES (1);
    commit;

I am using forced types with the generator:

    forcedTypes {
        // force the database type NUMBER(1) to be the java type Boolean
        forcedType {
            name = 'BOOLEAN'
            includeTypes = 'NUMBER\\(1\\)'
        }
    }

The java code is

    context.select(jsonObject(TEST.fields()))
            .from(TEST)
            .fetch();

I am getting the following error message with jooq pro 3.16.5 and oracle 19c (schema removed):

    SQL [select json_object(key ? value "..."."TEST"."BOOLEANCOLUMN" format json) from "..."."TEST"]; ORA-00932: inconsistent datatypes: expected CHAR got NUMBER
    org.jooq.exception.DataAccessException: SQL [select json_object(key ? value "..."."TEST"."BOOLEANCOLUMN" format json) from "..."."TEST"]; ORA-00932: inconsistent datatypes: expected CHAR got NUMBER
        at org.jooq_3.16.5.ORACLE18C.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:3102)

I've found a workaround using key().value(when().otherwise()) but it would be nice if it could work out of the box.

It works without the forcedTypes configuration but I am losing the nice java typing.

**Comment by lukaseder** [comment] 2022-06-21 11:12
Thanks a lot for your report. Will look into this soon.

**Comment by lukaseder** [comment] 2022-07-08 08:54
Thanks again for your report. I'm looking into this now. I can reproduce the problem, and I agree this should work out of the box.

> It works without the forcedTypes configuration but I am losing the nice java typing.

Without forced types, you'll get `1` and `0` values in the JSON, not `true` and `false`, though?

**Comment by lukaseder** [comment] 2022-07-08 09:40
So, this issue raises a few interesting questions about the concept of a `<forcedType>`, and its various features. Mainly:

- Data type rewrites
- Converters
- Bindings

### Data type rewrites

A data type rewrite tells the code generator to completely rewrite the type and forget about the actual type. The runtime will not remember that your column was a `NUMBER(1)`, and it can't act accordingly. It will assume the type was declared as `BOOLEAN` in the database, and because Oracle doesn't actually have such a type, will emulate it, the assumption being that once Oracle supports `BOOLEAN` types, you'll change your schema to use that instead. Until then, you should get `{"v":true}` and the likes.

*IF* an RDBMS supports the `BOOLEAN` type, and you're using this type rewrite there (e.g. in H2), then jOOQ will still assume the type was declared `BOOLEAN`, but since there's no `BOOLEAN` emulation on H2, you'll get `{"v":1}`, instead, because jOOQ thinks it's a `BOOLEAN`, but then it's not. And it can't read the boolean value anymore, because the RDBMS already embeds the value in a JSON document.

So, data type rewrites work a bit differently depending on whether the used dialect supports `BOOLEAN` types or not.

### Converter

A `Converter<T, U>` is applied on the result set *after* fetching `T` from the JDBC result set. If you were using a `Converter<Byte, Boolean>` here, then jOOQ wouldn't know how to turn your `{"v":1}` into a `{"v":true}` on the server side, because the value has already been embedded into JSON by Oracle, whereas `Converter` logic is applied in the client *after* fetching the data.

A `Converter` still works with `MULTISET`, despite the value being `1` in the JSON, because JSON is only used as a means of transporting data, not as a target document structure. So, converters can still be applied after reading data from a JSON-emulated `MULTISET`

### Binding

A `Binding<T, U>` is applied on the result set *while* fetching `T` or `U` directly from the JDBC result set. It is completely opaque to jOOQ's internals, hence it doesn't work for either JSON documents, nor `MULTISET`

### Future work

There's an idea of being able to influence the serialisation to / deserialisation from SQL/JSON and SQL/XML: https://github.com/jOOQ/jOOQ/issues/5673. For example, certain columns may need custom serialisation expressions (server side and/or client side) in order to embed them in a JSON document. The above distinctions show that this may indeed be needed to work around limitations encountered here.

### Back to your issue

In any case, again, the data type rewriting feature is the correct feature to apply here to get the behaviour you want. We already generate a similar `CASE` expression to the one you've used as a workaround for SQLite (see https://github.com/jOOQ/jOOQ/issues/13220). We can reuse that logic also in Oracle.

**Comment by torstenwerner** [comment] 2022-07-08 10:28
Thank you for the (verbose) update!

**Comment by lukaseder** [comment] 2022-07-08 11:48
Well, I'll have to look this up a few times myself, probably, in the future, so better be thorough... :)

Fixed in jOOQ 3.18.0, 3.17.3 (https://github.com/jOOQ/jOOQ/issues/13792), 3.16.9 (https://github.com/jOOQ/jOOQ/issues/new), and 3.15.13 (https://github.com/jOOQ/jOOQ/issues/13793).

Thanks again for your report!

**Closed by lukaseder** 2022-07-08 11:48 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: Professional Edition, E: Enterprise Edition

**Comment by lukaseder** [comment] 2024-08-22 09:57
Related issue in MySQL: 

- https://github.com/jOOQ/jOOQ/issues/17124
