### ISSUE TITLE
VALUES(RowN... rows) doesn't appear to respect custom bindings

### ISSUE THREAD

**Issue by ruke47** [jOOQ/jOOQ#5165] opened 2016-03-25 00:24 UTC
I've got a custom binding for `<Timestamp, Instant>`. I'm writing code that's basically:

``` Java
List<Instant> startTimes = getStartTimes();
Field<Instant> rangeBegin = field("range_begin", Instant.class);
Field<Instant> rangeEnd = field("range_end", Instant.class);

Row2<Instant, Instant>[] validRanges = startTimes.stream()
    .map(time -> row(time, time.plusSeconds(300)))
    .toArray(Row2[]::new);

create.select(MY_TABLE.EVENT_TIME)
      .distinctOn(MY_TABLE.EVENT_TIME)
      .from(values(validRanges).as("val_table", rangeBegin.getName(), rangeEnd.getName()))
      .innerJoin(MY_TABLE).on(MY_TABLE.EVENT_TIME.between(rangeBegin, rangeEnd))
      .orderBy(MY_TABLE.EVENT_TIME)
      .fetch();
```

This causes an error: `ERROR: operator does not exist: timestamp with time zone >= text`. However, if I change the Stream mapping function to be:

``` Java
.map(time -> row(time.atOffset(ZoneOffset.UTC),
                 time.plusSeconds(300).atOffset(ZoneOffset.UTC))
```

It works as expected. I know that my custom binding is functional - I use it all over my codebase. The only explanation that I can think of is that values isn't taking advantage of it.

**Comment by lukaseder** [comment] 2016-03-30 12:20
Thank you very much for reporting. This might be a duplicate of #4556, and #5148. However, in your case, I'm not sure where you'd expect that custom binding to apply, it is not explicitly passed along with any bind value.

I'll investigate...

**Comment by ruke47** [comment] 2016-03-30 18:01
Thank you for the response! Yes, I am using PostgreSQL (9.4.5, if it makes a difference).

I had also tried things like `row(val(time, rangeBegin), ...)` or `row(val(time, Instant.class), ...)`, but these produced identical results. 

If there is a way to pass along a binding to a ROW or VALUE that I'm simply missing, I'd be interested in hearing that, as well.

**Comment by lukaseder** [comment] 2016-03-31 13:25
Oh, I think I know what's happening now. You somehow profited from an internal static data type registry that registered your converter/binding for the `Instant` type. This "hidden feature" will eventually be removed. It is better to be explicit about data type bindings and data types. For instance, your  `rangeBegin` field should be declared as follows:

```java
// You can declare this globally:
DataType<Instant> instantType = SQLDataType.TIMESTAMP.asConvertedDataType(instantBinding);

// And then use it as such: 
Field<Instant> rangeBegin = field("range_begin", instantType);
```

Now, this binding will be applied to most situations automatically, when you use bind variables, e.g. 

```java
rangeBegin.eq(someInstant)
```

But due to bug #4556 / #5148, this won't work for `row()`, so you'll have to pass the data type explicitly again:

```java
row(val(time, rangeBegin), ...)
row(val(time, instantType), ...)
```

Does this help?

**Comment by ruke47** [comment] 2016-04-01 20:28
Yes, thank you very much!

**Comment by lukaseder** [comment] 2017-07-24 11:39
Closing this as worksforme. The error was arising due to API misuse (which may have been hidden by some internals in other cases)

**Closed by lukaseder** 2017-07-24 11:39 UTC
Labels: C: Functionality, P: Medium, R: Worksforme, T: Defect
