### ISSUE TITLE
Pimp *ReturningStep with option fetch in Scala extensions

### ISSUE THREAD

**Issue by coudy** [jOOQ/jOOQ#6016] opened 2017-03-25 01:45 UTC
`SELECT`s have methods like `fetchOneOption` and `fetchAnyOption`. However, these aren't available for `INSERT`s, `UPDATE`s and `DELETE`s with a `RETURNING` clause.

**Comment by lukaseder** [comment] 2017-03-25 18:57
Thank you very much for your suggestion.

Indeed, the currently available `fetch` convenience methods on the `*ResultStep` are very limited. However, instead of copying all these methods over from `ResultQuery` to the `*ResultStep` types, we had rather let `*ResultStep` *extend* `ResultQuery`, which would open up the possibility of many other conveniences, soon.

Given this context, I'll close this issue here as a duplicate of: https://github.com/jOOQ/jOOQ/issues/3185, as this issue would also automatically add those option fetches in Scala extensions. Feel free to comment or reopen if you think I've missed something else.

**Closed by lukaseder** 2017-03-25 18:57 UTC
Labels: C: Functionality, P: Medium, T: Enhancement
