### ISSUE TITLE
Wrong SQL generated with POSTGRES Dialect (queries seems to be flattened/bracketing is not followed correctly)

### ISSUE THREAD

**Issue by Priyank971** [jOOQ/jOOQ#14908] opened 2023-04-05 07:00 UTC
### Expected behavior

```java
private String getSqlForDialect(SQLDialect dialect) {
var dslContext = DSL.using(
      dialect,
      new Settings().withRenderFormatted(true).withStatementType(StatementType.STATIC_STATEMENT));
    var p1  = dslContext.select().from("A");
    var p2  = dslContext.select().from("A").union(dslContext.select().from("B"));

    var p3  = dslContext.select().from("A").union(dslContext.select().from("B").intersect(dslContext.select().from("C").union(dslContext.select().from("D").union(dslContext.select().from("E")))));
    return p1.union(p2).union(p3).getSQL();
}
```

We were expecting jooq to follow below bracketing for Postgres when we generated the query like above :

expected : `A ^ (A U B) ^ (A U (B^(C U D U E)))`

### Actual behavior

jooq is flattening the query in case of postgres dialect i.e. not following the bracketing

actual behaviour : `A ^ (A U B) ^ (A U B^C U D U E)`

### Steps to reproduce the problem

You will see the below query generated as i asserted but this is not expected.
Please let us know how can we fix or is it already fixed since i cannot find any issue regarding this

```java
private String getSqlForDialect(SQLDialect dialect) {
    var dslContext = DSL.using(
      dialect,
      new Settings().withRenderFormatted(true).withStatementType(StatementType.STATIC_STATEMENT));
    var p1  = dslContext.select().from("A");
    var p2  = dslContext.select().from("A").union(dslContext.select().from("B"));

    var p3  = dslContext.select().from("A").union(dslContext.select().from("B").intersect(dslContext.select().from("C").union(dslContext.select().from("D").union(dslContext.select().from("E")))));
    // A ^ (A U B) ^ (A U (B^(C U D U E)))
    return p1.union(p2).union(p3).getSQL();
  }

  @Test
  void testQueryGeneratedWithPostgres() {
    var postgres = getSqlForDialect(SQLDialect.POSTGRES);

    assertThat(postgres).isEqualToIgnoringWhitespace("(\n" +
      "  select *\n" +
      "  from A\n" +
      ")\n" +
      "union (\n" +
      "  select *\n" +
      "  from A\n" +
      "  union\n" +
      "  select *\n" +
      "  from B\n" +
      ")\n" +
      "union (\n" +
      "  select *\n" +
      "  from A\n" +
      "  union\n" +
      "  select *\n" +
      "  from B\n" +
      "  intersect\n" +
      "  select *\n" +
      "  from C\n" +
      "  union\n" +
      "  select *\n" +
      "  from D\n" +
      "  union\n" +
      "  select *\n" +
      "  from E\n" +
      ")");
  }
```

### jOOQ Version

3.15.0

### Database product and version

postgres:10.8

**Comment by lukaseder** [comment] 2023-04-05 08:32
Thanks a lot for your report. This still reproduces with jOOQ 3.19. Will look into it right away.

**Comment by lukaseder** [comment] 2023-04-05 08:53
As a workaround, you can set `Settings.renderParenthesisAroundSetOperationQueries` to true, see:

- https://github.com/jOOQ/jOOQ/issues/3676
- https://github.com/jOOQ/jOOQ/issues/9751

**Comment by Priyank971** [comment] 2023-04-05 09:40
Thanks for the quick response and for the workaround meanwhile.

Functionally the query now seems fine with the above flag being set to true as below , But can we also remove some unnecessary brackets in the below query with some flag?
(
  select *
  from A
)
union (
  (
    select *
    from A
  )
  union (
    select *
    from B
  )
)
union (
  (
    select *
    from A
  )
  union (
    (
      select *
      from B
    )
    intersect (
      (
        select *
        from C
      )
      union (
        select *
        from D
      )
      union (
        select *
        from E
      )
    )
  )
)

**Comment by lukaseder** [comment] 2023-04-05 09:43
The point of the flag is to *never* remove unnecessary brackets, e.g. in case this logic has bugs. The reason why the logic is so complex is because some dialects (e.g. older versions of MySQL / MariaDB) had tons of problems parsing parens in set operations.

**Comment by lukaseder** [comment] 2023-04-05 09:44
Fixed in jOOQ 3.19.0, 3.18.3 (https://github.com/jOOQ/jOOQ/issues/14909), 3.17.12 (https://github.com/jOOQ/jOOQ/issues/14910), and 3.16.18 (https://github.com/jOOQ/jOOQ/issues/14911)

**Closed by lukaseder** 2023-04-05 09:44 UTC
Labels: T: Defect, C: Functionality, P: High, E: All Editions

**Comment by Priyank971** [comment] 2023-04-05 09:53
Thanks. Just one more question : 
This flag 'renderParenthesisAroundSetOperationQueries' being true should not cause regression in our already generated queries for SPARK dialect right?
If not , then i ll make this flag as true in our Settings object for both the dialects.
I ll also try by bumping the jooq versions you mentioned that are compatible with our application.

**Comment by lukaseder** [comment] 2023-04-05 09:55
We don't support any "Spark" dialect, so I can't answer this question.

**Comment by Priyank971** [comment] 2023-04-05 09:56
My bad , Sorry i meant MYSQL

**Comment by lukaseder** [comment] 2023-04-05 10:01
That would depend on the MySQL version. Only recent versions of MySQL supported parsing all sorts of parentheses in set operations, see details here:

- https://github.com/jOOQ/jOOQ/issues/14301
- https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-31.html

**Comment by lukaseder** [comment] 2023-04-05 10:01
Anyway. You did report this for PostgreSQL, though? So, what are you really using?

**Comment by Priyank971** [comment] 2023-04-05 10:05
We use two different compute engines and different dialect for both of them:
1. Trino : For this the dialect is POSTGRES
2. Spark : For this the dialect is MYSQL

**Comment by lukaseder** [comment] 2023-04-05 11:30
Ah, I see. Well, the good news is that jOOQ 3.19 will support Trino! https://github.com/jOOQ/jOOQ/issues/11485
