### ISSUE TITLE
Slow query when generating 

### ISSUE THREAD

**Issue by lastcmaster** [jOOQ/jOOQ#5935] opened 2017-03-02 11:52 UTC
When generating jOOQ code from a database, got waring and request to report.

[blareportgen.log.txt](https://github.com/jOOQ/jOOQ/files/813652/blareportgen.log.txt)

**Comment by lukaseder** [comment] 2017-03-02 12:02
Thank you very much for reporting. Interesting, that looks just like this query here: https://github.com/jOOQ/jOOQ/issues/5836

I remember, you used to work on Oracle 10g, have you upgraded to 12c recently?

**Comment by lukaseder** [comment] 2017-03-12 19:59
I'm closing this as a duplicate of #5836.

**Closed by lukaseder** 2017-03-12 19:59 UTC
Labels: C: Code Generation, C: DB: Oracle, P: Medium, T: Defect
