### ISSUE TITLE
Update multiple connected tables in single query

### ISSUE THREAD

**Issue by AKuzmanoski** [jOOQ/jOOQ#6975] opened 2018-01-02 15:12 UTC
### Expected behavior and actual behavior:
This issue is either question or feature request.

I would like to update or insert a large amount of data in one call. This is supported and easy to implement when we want to update only one table by using a batch insert.

The problem is that I have to update several tables which are connected:
Tables (A, B, C, D)
B -> A
B -> C
C -> D

Something that works in PostgreSQL is the WITH clause for upserts:
```
WITH ("Upsert D") AS (
    insert into D on conflict ... do update ... returning *
), AS (
    insert into C 
    select id from D ... on conflict ... do update ... returning *
),
...
```
If this feature is supported in any newer version I apologize for this issue. Otherwise, an alternative solution which will solve my problem is welcome :D

NOTE: Tables are connected by sequence generated ids (managed by the database)

### Steps to reproduce the problem:
Try to create single insert/update query which operates on multiple connected tables

### Versions:

- jOOQ: 3.9.1
- Java: 1.8.0_151
- Database (include vendor): PostgeSQL
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:9.4.1212

**Comment by lukaseder** [comment] 2018-01-02 15:19
Thanks for your report. This seems to be a duplicate of #4474 (and a few other similar requests).

The workaround is to write a stored procedure and call that, or to resort to using plain SQL.

**Closed by lukaseder** 2018-01-02 15:19 UTC
Labels: C: DB: PostgreSQL, C: Functionality, P: Medium, T: Enhancement
