### ISSUE TITLE
Using row with limit on dialect Oracle 18C produces wrong SQL

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#13095] opened 2022-02-17 21:47 UTC
### Expected behavior

Running the following query:

```
        var x = create.select(
                        row(val(1)),
                        row(
                                val(1).cast(String.class)
                        )
                )
                .limit(pageSize + 1)
                .fetch();
```
Produces:

```
select "v0" row, "v1" row from (select "x"."v0", "x"."v1", rownum "rn" from (select 1 "v0.1", cast(1 as varchar2(4000)) "v1.cast" from DUAL) "x" where rownum <= (0 + 101)) where "rn" > 0
```

Which is not valid and thus Oracle throws:

```
Caused by: Error : 923, Position : 12, Sql = select "v0" row, "v1" row from (select "x"."v0", "x"."v1", rownum "rn" from (select :1  "v0.1", cast(:2  as varchar2(4000)) "v1.cast" from DUAL) "x" where rownum <= (0 + :3 )) where "rn" > 0, OriginalSql = select "v0" row, "v1" row from (select "x"."v0", "x"."v1", rownum "rn" from (select ? "v0.1", cast(? as varchar2(4000)) "v1.cast" from DUAL) "x" where rownum <= (0 + ?)) where "rn" > 0, Error Msg = ORA-00923: FROM keyword not found where expected
```

If we remove the limit clause everything works as expected. I can fill in more details if needed, but I find this very easy to reproduce, so hopefully this is good enough.

**Comment by lukaseder** [comment] 2022-02-18 07:56
Thanks a lot for your report. I think this is just another manifestation of an existing bug, which I'm working on for a near-future set of releases: https://github.com/jOOQ/jOOQ/issues/12930.

It is triggered in your particular case because of a lack of column aliases, in case of which we revert the `LIMIT` implementation to the Oracle 11g one, where `FETCH FIRST` was not yet supported. We do that because of a bug in Oracle, see: https://github.com/jOOQ/jOOQ/issues/5451

As a workaround, on Oracle 18c, you can just provide aliases to your `row()` expressions, so this should work:

```java
var x = ctx.select(
    row(val(1)).as("a"),
    row(
            val(1).cast(String.class)
    ).as("b")
)
.limit(1)
.fetch();
```

**Comment by lukaseder** [comment] 2022-02-18 08:08
It wasn't fixed for 18c, only for 21c in jOOQ 3.15: https://github.com/jOOQ/jOOQ/issues/7721. Older 18c releases (e.g. 18.1) still had the problem.

**Comment by lukaseder** [comment] 2022-02-18 08:21
I'm not too keen to fix #13096. Changing the behaviour would break things for people on older 18c releases, whereas a feature toggle seems excessive.

Better fix the nested row problem itself, which causes issues elsewhere as well.

**Comment by alf** [comment] 2022-02-18 08:21
Thank you for the work around, that's great. :+1:

**Comment by lukaseder** [comment] 2022-05-16 09:18
Duplicate of https://github.com/jOOQ/jOOQ/issues/13560

**Closed by lukaseder** 2022-05-16 09:18 UTC
Labels: T: Defect, C: Functionality, C: DB: Oracle, P: Medium, R: Duplicate, E: Professional Edition, E: Enterprise Edition
