### ISSUE TITLE
Generate behavior changes from 3.13.3 to 3.14.2

### ISSUE THREAD

**Issue by hemju** [jOOQ/jOOQ#10907] opened 2020-11-10 19:12 UTC
### Expected behavior

Records should be generated extending `UpdatableRecordImpl`. (they are generated like this in 3.13.3)

### Actual behavior

Records only extend `TableRecordImpl`, although a Primary key is in the table and the config hasn't changed.

### Versions

- jOOQ: 3.14.2
- Java: openjdk 13.0.2 2020-01-14
- Database (include vendor): PostgreSQL 12
- OS: MacOS
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.14

**Comment by lukaseder** [comment] 2020-11-10 19:13
Thanks for your report. Please upgrade again :)

Duplicate of https://github.com/jOOQ/jOOQ/issues/10902

**Closed by lukaseder** 2020-11-10 19:13 UTC
Labels: T: Defect
