### ISSUE TITLE
Cannot parse two "alter column"s within one "alter table" 

### ISSUE THREAD

**Issue by sp00m** [jOOQ/jOOQ#16996] opened 2024-07-31 08:23 UTC
### Expected behavior

I'm using PostgreSQL with Flyway, and one of my scripts has:

```sql
alter table "user"
    alter column "private_uuid" set not null,
    alter column "public_uuid" set not null;
```

I'm giving a try to `org.jooq.meta.extensions.ddl.DDLDatabase` to leverage your codegen tooling and I'm expecting it to be able to parse and load such a script.

### Actual behavior

It fails with the following stacktrace:

```text
org.jooq.impl.ParserException: Unsupported query type: ...user"
    alter column "private_uuid" set not null[*],
    alter column "public_uuid" set not null;
    ...
    at org.jooq.impl.DefaultParseContext.exception (ParserImpl.java:15161)
    at org.jooq.impl.DefaultParseContext.parseQuery (ParserImpl.java:1291)
    at org.jooq.impl.DefaultParseContext.lambda$parse$0 (ParserImpl.java:910)
    at org.jooq.impl.DefaultParseContext.wrap (ParserImpl.java:15354)
    at org.jooq.impl.DefaultParseContext.parse (ParserImpl.java:898)
    at org.jooq.impl.ParserImpl.parse (ParserImpl.java:776)
    at org.jooq.impl.ParserImpl.parse (ParserImpl.java:771)
    at org.jooq.meta.extensions.ddl.DDLDatabase.load (DDLDatabase.java:179)
```

Oddly enough, it passes if each `alter column` statement is within its own `alter table`:

```sql
alter table "user"
    alter column "private_uuid" set not null;
alter table "user"
    alter column "public_uuid" set not null;
```

### Steps to reproduce the problem

Codegen Maven plugin config:

```xml
<plugin>
    <groupId>org.jooq</groupId>
    <artifactId>jooq-codegen-maven</artifactId>
    <version>3.19.10</version>
    <dependencies>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-meta-extensions</artifactId>
            <version>3.19.10</version>
        </dependency>
    </dependencies>
    <executions>
        <execution>
            <id>jooq-codegen</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <generator>
            <database>
                <name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
                <properties>
                    <property>
                        <key>scripts</key>
                        <value>src/main/resources/db/migration/*.sql</value>
                    </property>
                    <property>
                        <key>sort</key>
                        <value>flyway</value>
                    </property>
                    <property>
                        <key>unqualifiedSchema</key>
                        <value>none</value>
                    </property>
                    <property>
                        <key>defaultNameCase</key>
                        <value>lower</value>
                    </property>
                </properties>
            </database>
        </generator>
    </configuration>
</plugin>
```

### jOOQ Version

3.19.10

### Database product and version

DDLDatabase loading PostgreSQL scripts

### Java Version

Corretto 21

**Comment by lukaseder** [comment] 2024-07-31 09:09
Thanks for your report. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/8834

**Closed by lukaseder** 2024-07-31 09:09 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, R: Duplicate, E: All Editions, C: Parser
