### ISSUE TITLE
Generating source from multiple files does not work

### ISSUE THREAD

**Issue by vojtapol** [jOOQ/jOOQ#7891] opened 2018-09-24 13:14 UTC
Relates to #6261

jOOQ does not see my SQL scripts when generating code using the DDLDatabase and ant-style path matching. If I set the value to `src/main/resources/db/migration/V1__initial_schema.sql` it correctly generates the tables but when I set it to `src/main/resources/db/migration/*.sql` nothing happens. The log does not print the SQL at all during build.

Dependencies:
```xml
<dependency>
  <groupId>org.jooq</groupId>
  <artifactId>jooq</artifactId>
  <version>3.11.4</version>
</dependency>
<dependency>
    <groupId>org.jooq</groupId>
    <artifactId>jooq-meta-extensions</artifactId>
    <version>3.11.4</version>
</dependency>
```

Plugin configuration:
```xml
<configuration>
    <generator>
        <database>
            <name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
            <properties>
                <property>
                    <key>scripts</key>
                    <value>src/main/resources/db/migration/V1__initial_schema.sql</value>  <!--WORKS-->
                    <!--<value>src/main/resources/db/migration/*.sql</value>-->  <!-- DOES NOT WORK-->
                </property>
            </properties>
        </database>
        <target>
            <packageName>com.example.generated.jooq</packageName>
            <directory>${project.build.directory}/generated-sources/jooq</directory>
        </target>
    </generator>
</configuration>
```

`V1__initial_schema.sql`:
```SQL
CREATE TABLE test (
  id CHAR(36) primary key,
  name VARCHAR(200)
);
```

I would expect it to load the files one by one in alphabetical order.

**Comment by lukaseder** [comment] 2018-09-25 14:42
Probably a duplicate of https://github.com/jOOQ/jOOQ/issues/7767, integrated in 3.11.5: https://github.com/jOOQ/jOOQ/issues/7768. Can you please try upgrading?

**Closed by lukaseder** 2018-09-25 14:42 UTC
