### ISSUE TITLE
jOOQ fails when generating class describing an index with INCLUDE

### ISSUE THREAD

**Issue by jaromor** [jOOQ/jOOQ#10726] opened 2020-10-09 09:25 UTC
Specify an index with INCLUDE column(s):
`CREATE UNIQUE INDEX users_external_id ON web.users (external_id) INCLUDE (id);`

...jOOQ then treats all columns included in the index as if they were supposed to have ORDER specified (which for INCLUDE-columns isn't the case):

PostgresDatabase.java:
![image](https://user-images.githubusercontent.com/40000923/95566516-f1b06580-0a21-11eb-82e0-f2adb9df93a3.png)

**Comment by lukaseder** [comment] 2020-10-09 10:04
Thanks a lot for your report. I'll look into it right away. Related issue: https://github.com/jOOQ/jOOQ/issues/10466

**Comment by lukaseder** [comment] 2020-10-09 10:09
This seems to be a duplicate of https://github.com/jOOQ/jOOQ/issues/10466. What jOOQ version were you using?

**Comment by jaromor** [comment] 2020-10-09 10:33
damn, 3.13.4 of course, my apology :)

**Comment by jaromor** [comment] 2020-10-09 10:34
also i am sorry about the double post, i got 404 from GitHub the first time

**Comment by lukaseder** [comment] 2020-10-09 12:05
No worries, thanks for the feedback!

**Closed by lukaseder** 2020-10-09 12:05 UTC
Labels: C: Code Generation, E: All Editions, P: High, R: Feedback Pending, T: Defect
