### ISSUE TITLE
Meta.ddl() can disrupt the correct sequence of database objects when exporting DDL with reserved names

### ISSUE THREAD

**Issue by mgramin** [jOOQ/jOOQ#15520] opened 2023-08-29 20:57 UTC
### Expected behavior

I expected that DDL from jOOQ `ddl()` method:
```sql
create table `sakila`.`test_table` (
  `id` varchar(100) not null
)

create view `sakila`.`all`(`id`)
as
select `t`.`id` as `id`
from `sakila`.`test_table` as `t`
```

In other words, first we create a table and then we create a related view.

### Actual behavior

But I received the DDL with broken sequence of objects:
```sql
create view `sakila`.`all`(`id`)
as
select `t`.`id` as `id`
from `sakila`.`test_table` as `t`

create table `sakila`.`test_table` (
  `id` varchar(100) not null
)
```

### Steps to reproduce the problem

1. Create a simple table and a view, but use one of the reserved words (from this list) as the view name:
```sql
create table test_table (
  id varchar(100) not null
);

create view `all` as select * from test_table t;
```

2. Run this Java code to generate DDL for objects:
```java
        Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:6000/sakila", "root", "admin");
        Configuration configuration = new DefaultConfiguration().set(conn).set(SQLDialect.MYSQL);
        Meta meta = using(configuration).meta();

        Arrays.stream(
                meta.filterSchemas(v -> v.getName().equalsIgnoreCase("sakila"))
                        .ddl()
                        .queries())
                .forEach(System.out::println);
```

3. As a result, we will obtain the DDL with a sequence of broken database objects:
```sql
create view `sakila`.`all`(`id`)
as
select `t`.`id` as `id`
from `sakila`.`test_table` as `t`

create table `sakila`.`test_table` (
  `id` varchar(100) not null
)
```

4. If we try to execute the generated SQL script, we will get an error because we are attempting to create a view before creating a related table:
```
SQL ERROR: Table 'sakila.test_table' doesn't exist [state: 42S02, code: 1146]
org.jooq.exception.DataAccessException: SQL [create view `sakila`.`all`(`id`)
as
select `t`.`id` as `id`
from `sakila`.`test_table` as `t`]; Table 'sakila.test_table' doesn't exist
```

PS

If we create a view with an ordinary name (without reserved words), jOOQ will export objects in the correct order.

### jOOQ Version

jOOQ Professional Edition 3.18.6

### Database product and version

MySQL 8.0.30

### Java Version

openjdk 17.0.2 2022-01-18

### OS Version

Microsoft Windows [Version 10.0.19044.2846]

### JDBC driver name and version (include name if unofficial driver)

mysql-connector-java:8.0.33

**Comment by lukaseder** [comment] 2023-08-30 09:01
Thanks for your report. This is a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/15326
- https://github.com/jOOQ/jOOQ/issues/15327

You can work around some issues by specifying `DDLFlag`, i.e. to export tables only first, then views only later. But the order within views will still not be maintained correctly, if you have a view hierarchy.

**Closed by lukaseder** 2023-08-30 09:01 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by mgramin** [comment] 2023-08-30 11:11
Thank you, @lukaseder, for your comprehensive and helpful response, which was also delivered with your usual lightning speed.

**Comment by lukaseder** [comment] 2023-09-01 16:09
You're welcome, @mgramin. Good news on https://github.com/jOOQ/jOOQ/issues/15327, btw. I've started work where we'll parse the view contents to extract dependency information based on `select.$traverse(Traversers.findingAll(p -> p instanceof Table))`. You could do that as well on your end, as a workaround, and sort the list accordingly.

#15327 will also include an SPI to override jOOQ's parser output, in case it fails.
