### ISSUE TITLE
"InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default"

### ISSUE THREAD

**Issue by JayAhn2** [jOOQ/jOOQ#12388] opened 2021-09-02 14:39 UTC
### Expected behavior
Parse LocalDateTime(when it comes to json result) to DTO without InvalidDefinitionException. I'm not sure it is a specific issue of jOOQ, or Spring Boot / Jackson issue.

### Actual behavior
When I executed the query which the result contains localDateTime(startedAt": "2021-09-02 16:25:44.000000"), it returns the below error. Based on the error message, I added `JacksonConfiguration`, but it doesn't help.

`Error`
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
 at [Source: (String)"{"id": 181535752075608064, "sku": "SKU-20304-234123", "name": "product", "price": 120.90, "active": 1, "vendorId": 124251234, "categoryId": 1231412, "description": "It is really good one", "priceHistories": [{"id": 181535752075608065, "price": 120.9, "endedAt": null, "startedAt": "2021-09-02 16:25:44.000000"}], "relatedProducts": null}"; line: 1, column: 282] (through reference chain: io.jahn.ecommerce.modules.products.product.infrastructure.query.dtos.ProductDto["priceHistories"]->java.util.HashSet[0]->io.jahn.ecommerce.modules.products.product.infrastructure.query.dtos.ProductPriceHistoryDto["startedAt"])

``` kotlin
@Configuration
class JacksonConfiguration {
    @Bean
    fun objectMapper(): ObjectMapper =
        ObjectMapper()
            .registerModule(JavaTimeModule())
            .registerModule(ParameterNamesModule())
            .registerModule(Jdk8Module())
            .registerModule(KotlinModule())
}
``` 

`DTO`
```kotlin
data class ProductDto(
    val id: Long,
    val active: Boolean,
    val name: String,
    val description: String?,
    val sku: String,
    val vendorId: Long,
    val categoryId: Long,
    val price: BigDecimal,
    @JsonSetter(nulls = Nulls.AS_EMPTY)
    val priceHistories: Set<ProductPriceHistoryDto>,
    @JsonSetter(nulls = Nulls.AS_EMPTY)
    val relatedProducts: Set<RelatedProductDto>
)

data class ProductPriceHistoryDto(
    val id: Long,
    val price: BigDecimal,
    val startedAt: LocalDateTime,
    val endedAt: LocalDateTime
) {
}

data class RelatedProductDto(
    val id: Long,
    val relatedProductId: Long,
    val relevanceScore: BigDecimal
)
```
`repository`
```kotlin
@Repository
class ProductJooqRepository(private val ctx: DSLContext) : ProductQueryRepository {
    private val product: Product = Product.PRODUCT
    private val priceHistory: ProductPriceHistory = ProductPriceHistory.PRODUCT_PRICE_HISTORY
    private val relatedProduct: RelatedProduct = RelatedProduct.RELATED_PRODUCT

    private val selectProduct =
        jsonObject(
            key("id").value(product.ID),
            key("active").value(product.ACTIVE),
            key("name").value(product.name),
            key("description").value(product.DESCRIPTION),
            key("sku").value(product.SKU),
            key("vendorId").value(product.VENDOR_ID),
            key("categoryId").value(product.CATEGORY_ID),
            key("price").value(product.PRICE),
            key("priceHistories").value(
                field(
                    select(
                        jsonArrayAgg(
                            jsonObject(
                                key("id").value(priceHistory.ID),
                                key("price").value(priceHistory.PRICE),
                                key("startedAt").value(localDateTime(priceHistory.STARTED_AT)),
                                key("endedAt").value(localDateTime(priceHistory.ENDED_AT))
                            )
                        )
                    )
                        .from(priceHistory)
                        .where(priceHistory.PRODUCT_ID.eq(product.ID))
                )
            ),
            key("relatedProducts").value(
                field(
                    select(
                        jsonArrayAgg(
                            jsonObject(
                                key("id").value(relatedProduct.ID),
                                key("relatedProductId").value(relatedProduct.RELATED_PRODUCT_ID),
                                key("relevanceScore").value(relatedProduct.RELEVANCE_SCORE)
                            )
                        )
                    )
                        .from(relatedProduct)
                        .where(relatedProduct.PRODUCT_ID.eq(product.ID))
                )
            )
        )

    override fun fetchById(id: Long): ProductDto {
        return ctx.select(selectProduct)
            .from(product)
            .where(product.ID.eq(id))
            .fetchOneInto(ProductDto::class.java)
            ?: throw RecordNotFoundException("Product is not found by id: $id")
    }
}
```
`codegen`
```kotlin
jooq {
    version.set(jooqVersion) // "3.15.2"
    edition.set(JooqEdition.OSS)

    configurations {
        create("main") {
            jooqConfiguration.apply {
                logging = org.jooq.meta.jaxb.Logging.WARN
                jdbc.apply {
                    driver = "com.mysql.cj.jdbc.Driver"
                    url = "jdbc:mysql://localhost:3307/ecommerce"
                    user = "root"
                    password = "root"
                }
                generator.apply {
                    name = "org.jooq.codegen.DefaultGenerator"
                    database.apply {
                        name = "org.jooq.meta.mysql.MySQLDatabase"
                        inputSchema = "ecommerce"
                        forcedTypes.addAll(
                            arrayOf(
                                ForcedType()
                                    .withName("varchar")
                                    .withIncludeExpression(".*")
                                    .withIncludeTypes("JSONB?"),
                                ForcedType()
                                    .withName("varchar")
                                    .withIncludeExpression(".*")
                                    .withIncludeTypes("INET")
                            ).toList()
                        )
                    }
                    generate.apply {
                        isDeprecated = false
                        isRecords = false
                        isImmutablePojos = false
                        isFluentSetters = false
                    }
                    target.apply {
                        packageName = "io.jahn.ecommerce"
                        directory = "build/generated/jooq"
                    }
                    strategy.name = "org.jooq.codegen.DefaultGeneratorStrategy"
                }
            }
        }
    }
}

tasks.named<JooqGenerate>("generateJooq") {
    dependsOn("flywayMigrate")
    inputs.files(fileTree("src/main/resources/db/migration"))
        .withPropertyName("migration")
        .withPathSensitivity(RELATIVE)

    allInputsDeclared.set(true)
    outputs.cacheIf { true }
}
```
`SQL DDL`
```sql
CREATE TABLE product
(
    id               BIGINT(20)     NOT NULL PRIMARY KEY,
    created_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_at TIMESTAMP      NULL,
    active           TINYINT(1)     NOT NULL DEFAULT 1,
    name             VARCHAR(100)   NOT NULL,
    description      VARCHAR(3000)  NULL,
    sku              VARCHAR(100)   NOT NULL,
    vendor_id        BIGINT(20)     NOT NULL,
    category_id      BIGINT(20)     NOT NULL,
    price            DECIMAL(13, 2) NOT NULL
);

CREATE TABLE product_price_history
(
    id               BIGINT(20)     NOT NULL PRIMARY KEY,
    created_at       TIMESTAMP      NOT NULL,
    last_modified_at TIMESTAMP      NULL,
    product_id       BIGINT(20)     NOT NULL,
    price            DECIMAL(13, 2) NOT NULL,
    started_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at         TIMESTAMP      NULL,
    CONSTRAINT product_price_history__product_id__fk FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE related_product
(
    id                 BIGINT(20)    NOT NULL PRIMARY KEY,
    created_at         TIMESTAMP     NOT NULL,
    last_modified_at   TIMESTAMP     NULL,
    product_id         BIGINT(20)    NOT NULL,
    related_product_id BIGINT(20)    NOT NULL,
    relevance_score    DECIMAL(5, 5) NOT NULL,
    CONSTRAINT related_product__product_id__fk FOREIGN KEY (product_id) REFERENCES product (id)
);
```
### Steps to reproduce the problem
You can find the above codes.

### Versions

- jOOQ: 3.15.2 with id("nu.studer.jooq") version "6.0.1"
- Java: OpenJDK 11
- Database (include vendor): MySQL (version: 5.7)
- OS: Mac
- JDBC Driver (include name if inofficial driver): mysql:mysql-connector-java:8.0.25

**Comment by JayAhn2** [comment] 2021-09-03 01:08
Seems it is an issue related to `JSON_OBJECT` of mysql. As it returns with `.SSSSSS`

```
"startedAt": "2021-09-02 16:25:44.000000"
```

I'm not sure how I can make this timestamp mapped to Date by jooq.

Ref: https://stackoverflow.com/questions/55165454/mysql-json-object-datetime-format

**Comment by lukaseder** [comment] 2021-09-03 10:46
Thanks for your report. jOOQ doesn't look at any of your Spring configured Jackson configurations, but creates a `new ObjectMapper` under the hood. It is thus limited by what this `ObjectMapper` can do out of the box. Granted, for such obvious cases, we should have an out-of-the-box solution.

The workaround is to provide a customer `ConverterProvider`, which should be relatively simple: https://www.jooq.org/doc/latest/manual/sql-execution/fetching/converter-provider/

**Comment by lukaseder** [comment] 2021-09-03 11:28
OK, so there are two things we should fix here. 

1) The more pressing one is supporting the JSR 310 types via Jackson *at all*. It seems Jackson 2.12 still has Java 7 as baseline (the pom.xml claims 8, but the `.class` file is 7 compatible). A related discussion is here: https://github.com/FasterXML/jackson-databind/issues/2683

We could again try to discover if a Jackson module is available from the classpath, similar to the kotlin module: https://github.com/jOOQ/jOOQ/issues/11165

But at some point, we'll become some automatic module discovery platform like OSGi or Spring Boot, and that should be avoided, especially since everything is being done via reflection, which is bothering folks using jOOQ with AOP (e.g. https://github.com/quarkiverse/quarkus-jooq). So, perhaps, instead of solving this particular issue, we should rather start retiring the static implementation we've added in jOOQ 3.14 (see https://github.com/jOOQ/jOOQ/issues/10072, https://github.com/jOOQ/jOOQ/issues/11898) and make sure users can inject their `ObjectMapper` to jOOQ more easily.

2) Some database dialects produce ISO 8601 timestamps *with* a `T` when timestamps are embedded in XML/JSON (e.g. PostgreSQL). Others don't do that, because the `T` less timestamp used to be valid according to ISO 8601 and is certainly valid in SQL. Regrettably, the `java.time` API is not lenient here, and rejects a timestamp with a `T`. I'll think about this. Probably, we should make sure our generated XML/JSON always contain ISO 8601 timestamps irrespective of what the SQL dialect thinks of this.

**Comment by lukaseder** [comment] 2021-09-03 11:30
Notice that Jackson seems to be able to parse timestamps with `T` and bind them to the `java.sql` types! Gson can't do either.

**Comment by JayAhn2** [comment] 2021-09-03 19:32
@lukaseder Thanks for your swift feedback :) 

I tried to implement a workaround through `ConverterProvider` you shared as below, but it is failed. Sorry for my short understanding of jOOQ... 

As far as I understand, I need to register the converter to the codegen as `forcedType`, but I'm not sure the below configuration is workable or not. 

Could you guide me what's wrong with this setting?

`JSONConverter`

`codegen`
```
jooq {
    version.set(jooqVersion)
    edition.set(JooqEdition.OSS)

    configurations {
        create("main") {
            jooqConfiguration.apply {
                logging = org.jooq.meta.jaxb.Logging.WARN
                jdbc.apply {
                    driver = "com.mysql.cj.jdbc.Driver"
                    url =
                        "jdbc:mysql://localhost:3307/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=UTC&useTimezone=true"
                    user = "root"
                    password = "root"
                }
                generator.apply {
                    name = "org.jooq.codegen.DefaultGenerator"
                    database.apply {
                        name = "org.jooq.meta.mysql.MySQLDatabase"
                        inputSchema = "ecommerce"
                        forcedTypes.addAll(
                            arrayOf(
                                ForcedType()
                                    .withUserType("java.time.LocalDateTime")
                                    .withConverter("io.jahn.ecommerce.config.jooq.JSONConverterProvider")
                                    .withIncludeExpression(".*")
                                    .withIncludeTypes("DATE(\\(.*\\))?")
                                ,
                                ForcedType()
                                    .withName("varchar")
                                    .withIncludeExpression(".*")
                                    .withIncludeTypes("JSONB?"),
                                ForcedType()
                                    .withName("varchar")
                                    .withIncludeExpression(".*")
                                    .withIncludeTypes("INET")
                            ).toList()
                        )
                    }
                    generate.apply {
                        isJavaTimeTypes = false
                        isDeprecated = false
                        isRecords = false
                        isImmutablePojos = false
                        isFluentSetters = false
                    }
                    target.apply {
                        packageName = "io.jahn.ecommerce"
                        directory = "build/generated/jooq"
                    }
                    strategy.name = "org.jooq.codegen.DefaultGeneratorStrategy"
                }
            }
        }
    }
}

tasks.named<JooqGenerate>("generateJooq") {
    dependsOn("flywayMigrate")
    inputs.files(fileTree("src/main/resources/db/migration"))
        .withPropertyName("migration")
        .withPathSensitivity(RELATIVE)

    allInputsDeclared.set(true)
    outputs.cacheIf { true }
}
```
`JSONConverterProvider`
```
class JSONConverterProvider : ConverterProvider {
    private val delegate: ConverterProvider = DefaultConverterProvider()
    private val mapper = ObjectMapper()
        .registerModule(JavaTimeModule())
        .registerModule(ParameterNamesModule())
        .registerModule(Jdk8Module())
        .registerModule(KotlinModule())

    override fun <T, U> provide(
        tType: Class<T>,
        uType: Class<U>
    ): Converter<T, U>? {
        // Our specialised implementation can convert from JSON (optionally, add JSONB, too)
        return if (tType == JSON::class) {
            Converter.ofNullable<T, U>(tType, uType,
                Function<T, U> ofNullable@{ t: T ->
                    try {
                        return@ofNullable mapper.readValue((t as JSON).data(), uType)
                    } catch (e: Exception) {
                        throw DataTypeException("JSON mapping error", e)
                    }
                },
                Function<U, T> ofNullable@{ u: U ->
                    try {
                        return@ofNullable JSON.valueOf(mapper.writeValueAsString(u)) as T
                    } catch (e: Exception) {
                        throw DataTypeException("JSON mapping error", e)
                    }
                }
            )
        } else delegate.provide(tType, uType)
    }
}
```

**Comment by lukaseder** [comment] 2021-09-06 11:59
Have you debug-stepped through your converter provider? I would imagine this test might fail:

```kotlin
tType == JSON::class
```

You should write this, instead:

```kotlin
tType == JSON::class.java
```

**Comment by JayAhn2** [comment] 2021-09-27 02:05
> Have you debug-stepped through your converter provider? I would imagine this test might fail:
> 
> ```kotlin
> tType == JSON::class
> ```
> 
> You should write this, instead:
> 
> ```kotlin
> tType == JSON::class.java
> ```

Sorry for late reply. 
This would bring type error.

![image](https://user-images.githubusercontent.com/25868002/134835133-11adbd58-764e-49e8-924c-df4a6cedb6bc.png)

**Comment by lukaseder** [comment] 2021-09-27 06:44
Well, yes. You need to apply some unsafe casts. `JSON` and `T` aren't the same types. Remove the `<T, U>` type witnesses (or whatever kotlin calls them) and unsafe-cast your resulting converter back to `Converter<T, U>` before returning it.

**Comment by JayAhn2** [comment] 2021-11-30 02:20
Hi! @lukaseder 

I managed to make the JSONConverterProvider works, but here is another issue with generated code.

`JSONConverterProvider`
```kotlin
class JSONConverterProvider : ConverterProvider {
    private val delegate: ConverterProvider = DefaultConverterProvider()
    private val mapper = ObjectMapper()
        .registerModule(JavaTimeModule())
        .registerModule(ParameterNamesModule())
        .registerModule(Jdk8Module())
        .registerModule(KotlinModule())

    override fun <T, U> provide(
        tType: Class<T>,
        uType: Class<U>,
    ): Converter<T, U>? {

        // Our specialised implementation can convert from JSON (optionally, add JSONB, too)
        return if (tType == JSON::class.java) {
            Converter.ofNullable(tType as Class<T>, uType,
                Function<T, U> { t: T ->
                    try {
                        return@Function mapper.readValue((t as JSON).data(), uType)
                    } catch (e: Exception) {
                        throw DataTypeException("JSON mapping error", e)
                    }
                },
                Function<U, T> { u: U ->
                    try {
                        return@Function JSON.valueOf(mapper.writeValueAsString(u)) as T
                    } catch (e: Exception) {
                        throw DataTypeException("JSON mapping error", e)
                    }
                }
            )
        } else delegate.provide(tType, uType)
    }
}
```

`codegen config`
```kotlin
jooq {
    version.set(jooqVersion)
    edition.set(JooqEdition.OSS)

    configurations {
        create("main") {
            jooqConfiguration.apply {
                logging = org.jooq.meta.jaxb.Logging.WARN
                jdbc.apply {
                    driver = "com.mysql.cj.jdbc.Driver"
                    url =
                        "jdbc:mysql://localhost:3307/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=UTC&useTimezone=true"
                    user = "root"
                    password = "root"
                }
                generator.apply {
                    name = "org.jooq.codegen.DefaultGenerator"
                    database.apply {
                        name = "org.jooq.meta.mysql.MySQLDatabase"
                        inputSchema = "ecommerce"
                        forcedTypes.addAll(
                            arrayOf(
                                ForcedType() // this part!!
                                    .withUserType("java.time.LocalDateTime")
                                    .withConverter("io.jahn.ecommerce.config.jooq.JSONConverterProvider")
                                    .withIncludeExpression(".*")
                                    .withIncludeTypes("DATE(\\(.*\\))?")
                                ,
                                ForcedType()
                                    .withName("varchar")
                                    .withIncludeExpression(".*")
                                    .withIncludeTypes("JSONB?"),
                                ForcedType()
                                    .withName("varchar")
                                    .withIncludeExpression(".*")
                                    .withIncludeTypes("INET")
                            ).toList()
                        )
                    }
                    generate.apply {
                        isJavaTimeTypes = false
                        isDeprecated = false
                        isRecords = false
                        isImmutablePojos = false
                        isFluentSetters = false
                    }
                    target.apply {
                        packageName = "io.jahn.ecommerce"
                        directory = "build/generated/jooq"
                    }
                    strategy.name = "org.jooq.codegen.DefaultGeneratorStrategy"
                }
            }
        }
    }
}

tasks.named<JooqGenerate>("generateJooq") {
    dependsOn("flywayMigrate")
    inputs.files(fileTree("src/main/resources/db/migration"))
        .withPropertyName("migration")
        .withPathSensitivity(RELATIVE)

    allInputsDeclared.set(true)
    outputs.cacheIf { true }
}
```

```java
    public final TableField<Record, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP(6)", SQLDataType.LOCALDATETIME)), this, "", new JSONConverterProvider()); // Seems createField expects Converter instead of ConverterProvider
```

Cannot resolve method 'createField(org.jooq.@org.jetbrains.annotations.NotNull Name, org.jooq.@org.jetbrains.annotations.NotNull DataType<java.time.LocalDateTime>, com.example.ecommerce.tables.JFood, java.lang.String, com.example.ecommerce.common.jooq.JSONConverterProvider)'

**Comment by ruiyang** [comment] 2021-12-03 01:12
Hi,
wonder if any plan for this issue in JOOQ

**Comment by lukaseder** [comment] 2021-12-08 10:48
Thanks for your patience folks. I don't really understand the problem here. What's your question? I mean:

>     public final TableField<Record, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP(6)", SQLDataType.LOCALDATETIME)), this, "", new JSONConverterProvider()); // Seems createField expects Converter instead of ConverterProvider

Yes indeed, you have to pass a `Converter`, not a `ConverterProvider`. But why did you configure jOOQ's code generator to use a `ConverterProvider`, then? You seem to already know the answer? Pass a `Converter` instead...

`ConverterProvider` is an SPI that you register with `Configuration.set(ConverterProvider)`. It has nothing to do with code generation, but is used as a default converter provider utility to help jOOQ understand how to convert between types in the absence of registered converters.

I'm closing this issue as I think it was just a support incident, and all questions are answered. Please open a new issue if you have any further questions about jOOQ usage.

**Comment by lukaseder** [comment] 2021-12-08 10:49
Note, for priority communication, we offer commercial support with all our commercial price plans by email, not on github.

**Closed by lukaseder** 2021-12-08 10:48 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by INeedMySpace** [comment] 2022-08-31 23:35
Hello there, it seems that this defect is still present and JOOQ ignores Spring ObjectMapper bean configuration.
Met this while using fetchInto() class with field which has jsonb column representation in Postgres db.
Added "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.3" and ObjectMapper or Jackson2ObjectMapperBuilder bean configuration but without success.

**Comment by lukaseder** [comment] 2022-09-01 06:44
Thanks for your message, @INeedMySpace. Can you please create a new issue and supply all the necessary information to reproduce your problem?
