### ISSUE TITLE
Allow easy filtering of unwanted fields

### ISSUE THREAD

**Issue by Diagoras** [jOOQ/jOOQ#8223] opened 2019-01-15 19:52 UTC
jOOQ allows you to select a subset of fields from a table really easily. However, filtering one or more specific fields is a little more awkward:

```java
create.select(MY_TABLE.fieldStream().filter(field -> !field.equals(MY_TABLE.UNWANTED_FIELD)).toArray())
```

An easy way to exclude the fields you don't want would be great. For example, something like:

```java
create.select(MY_TABLE.fieldsExcept(MY_TABLE.UNWANTED_FIELD))
```
As well as a varargs version, etc.

Thanks for the awesome library, and let me know if you need any more detail.

### Versions:

- jOOQ: 3.11.9
- Java: 1.8
- Database (include vendor): Postgres 9.3
- OS: MacOS
- JDBC Driver (include name if inofficial driver): 42.2.2

**Comment by lukaseder** [comment] 2019-01-15 20:04
Thanks a lot for the suggestion. In fact, H2 and Google BigQuery support the `* EXCEPT (column list)` syntax for both qualified and unqualified asterisks. This is definitely something I can see a future jOOQ having.

I'm closing this as a duplicate of #7921

**Closed by lukaseder** 2019-01-15 20:04 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Enhancement

**Comment by Diagoras** [comment] 2019-01-15 20:55
Ah, I didn't spot that one! Thanks Lukas, and sorry about the duplicate issue.

**Comment by lukaseder** [comment] 2019-01-16 20:41
No worries at all :) A duplicate issue is a stronger upvote, giving more weight to the original issue...
