### ISSUE TITLE
Translator should not fail with "Unknown function"

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9119] opened 2019-08-31 07:52 UTC
For the jOOQ Translate service I think it would make more sense to not fail with "Unknown function" errors. A warning somewhere would be nice, alternatively maybe a checkbox.

**Comment by lukaseder** [comment] 2019-09-03 10:25
Eventually we want to do that, indeed. But currently, we profit from the fact that "unknown functions" error out, so we can find them in the logs.

I agree though, we could offer the flag in the UI to users, defaulting to the current behaviour.

**Comment by knutwannheden** [comment] 2019-09-03 10:29
As with most these flags, we should offer FAIL, LOG_ERROR, LOG_WARN, LOG_INFO, and IGNORE strategies (can we have a single enum fir this?). And for the website we could simply do the logging, no?

**Comment by lukaseder** [comment] 2019-09-03 11:05
> can we have a single enum fir this?

We probably could

> And for the website we could simply do the logging, no?

You mean, parse the thing twice? Once for logging and once for the user output? But if a user uploads a huge query, expects it to be translated correctly from DB2 to Oracle, and in the middle of it, we simply ignored an "unknown function", that's not too nice either...

**Comment by knutwannheden** [comment] 2019-09-03 11:11
> You mean, parse the thing twice? Once for logging and once for the user output? But if a user uploads a huge query, expects it to be translated correctly from DB2 to Oracle, and in the middle of it, we simply ignored an "unknown function", that's not too nice either...

No, I was thinking we would parse using `LOG_WARN`, which should "translate" any unknown function calls like `FOO(42)` into the corresponding function call syntax of the target dialect (I suppose this will always be `FOO(42)`).

The user would then no longer get any warning or error displayed (unless we implement something specifically for the Translator), but the error would still get logged into the Translator's log.

**Comment by lukaseder** [comment] 2019-09-03 12:12
Yes, that's how I understood you, and my point was that this is useful for user defined functions, but not for built-in functions that we currently do not recognise, in case of which an error would be more useful for the user.

**Comment by knutwannheden** [comment] 2019-09-03 12:25
So we would first need to know all built-in functions for all dialects?

Also note that for dialects like Oracle, which allow overloading, we might have user-defined functions with the same name (but different signatures) as built-in functions.

**Comment by lukaseder** [comment] 2019-09-03 13:03
> So we would first need to know all built-in functions for all dialects?

Why "all"? I mean, clearly, our parser is not good enough yet to trust its judgement entirely. So, having users see errors is useful, right now. Allowing users to opt out of such errors could be useful too, I don't disagree with adding such buttons. But I disagree (with jOOQ 3.12) that we should stop displaying errors because of "unknown functions" entirely. We're not there yet.

> Also note that for dialects like Oracle, which allow overloading, we might have user-defined functions with the same name (but different signatures) as built-in functions.

Yes, I'm aware of that. As soon as we query the catalog for user defined functions, we'll have to start thinking of name resolution mechanisms of all the dialects, and adapt according to the parse dialect.

**Comment by lukaseder** [comment] 2020-10-16 15:47
Without re-iterating the discussion here, we've now changed the translator's setting to `Settings.parseUnknownFunctions = ParseUnknownFunctions.IGNORE`. Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/10680

**Closed by lukaseder** 2020-10-16 15:47 UTC
Labels: C: Translator, E: All Editions, P: Medium, T: Enhancement
