### ISSUE TITLE
SQL Translation Error

### ISSUE THREAD

**Issue by minleejae** [jOOQ/jOOQ#17158] opened 2024-09-02 04:37 UTC
### SQL translator incorrectly translates this query:

```sql
-- mysql -> postgresql
ALTER TABLE orders MODIFY fee_amount int(11) DEFAULT NULL
```

<img width="1651" alt="image" src="https://github.com/user-attachments/assets/c6fa6fc8-2efa-4adc-b2c1-2a2a46b27f35">

**Comment by lukaseder** [comment] 2024-09-02 05:50
Thanks for your report. Duplicate of:

- https://github.com/jOOQ/jOOQ/issues/9247

**Closed by lukaseder** 2024-09-02 05:50 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Duplicate, E: All Editions
