### ISSUE TITLE
ExecuteListener#end() not last lifecycle event when using DSLContext#fetchOne()

### ISSUE THREAD

**Issue by epkugelmass** [jOOQ/jOOQ#8544] opened 2019-04-18 00:03 UTC
### Expected behavior and actual behavior:

Expected 

Though it's not iron-clad explicit in the `ExecuteListener` javadoc, I would expect the `end` method to be the last method called in a given execution. Says the javadoc: `Called at the end of the execution lifecycle.`

Actual

When performing lazy fetches, the `end` method can be called before `resultEnd` and `fetchEnd`. `end` is called at https://github.com/jOOQ/jOOQ/blob/version-3.11.8/jOOQ/src/main/java/org/jooq/impl/Tools.java#L2436 and only then is `resultEnd` called at https://github.com/jOOQ/jOOQ/blob/version-3.11.8/jOOQ/src/main/java/org/jooq/impl/CursorImpl.java#L413

This seems to be related to the fixes for #1868 and #2373.
If this is in fact not a bug, I'd like to suggest that the guarantees (if any) around ExecuteListener invocation be clarified in the javadoc.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

Use `fetchOne` or any convenience method that calls `fetchLazy` under the hood.

### Versions:

- jOOQ: 3.11.8
- Java: 11.0.2
- Database (include vendor): MySQL 5.6
- OS: Mac 10.14.4
- JDBC Driver (include name if inofficial driver): MySQL Connector 5.1.39

**Comment by lukaseder** [comment] 2019-07-02 11:52
Related issue: #8877

**Comment by lukaseder** [comment] 2019-07-02 12:04
This issue is caused by logic related to #1868, #2373, #2385, where `Cursor.close()` is called eagerly as soon as we don't find any records in a JDBC `ResultSet` anymore.

**Comment by lukaseder** [comment] 2019-07-02 13:53
The big question (which we won't resolve immediately), is whether auto-closing cursors are really a good idea. This will be addressed when we tackle #8884 eventually.

Wherever we use cursors internally, without disclosing them to users, this problem can be solved easily by not using auto-closing cursors. We are already closing the cursors explicitly after using them, so we can better guarantee the lifecycle events ordering.

**Comment by lukaseder** [comment] 2019-07-02 13:54
This is a fix in a rather delicate area. I prefer not backporting it to 3.11.x to prevent possible regressions. Fixed for 3.12.0 only.

**Closed by lukaseder** 2019-07-02 13:54 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect

**Comment by lukaseder** [comment] 2019-07-11 16:36
Related: #8938
