### ISSUE TITLE
UPSERT bug w/ Postgres

### ISSUE THREAD

**Issue by rtomsick** [jOOQ/jOOQ#5166] opened 2016-03-25 18:07 UTC
# Description

Attempts to use Postgres UPSERT functionality via InsertOnDuplicateStep#onDuplicateKeyUpdate() fail by producing invalid SQL.  I believe this to be due to a bug (or at least an unsafe default behavior) in jOOQ.
# Steps to reproduce
1. Create a query similar to [1].  This is done with DSL.table() and DSL.field() calls in my case, as code generation is not used.
2. Attempt to execute the query (in my case in a batch via DSLContext#batch(Query) or similar.)
3. (Optionally) inspect the generated SQL.
# Expected outcome

Query executes successfully.  Generated SQL contains upsert clause similar to "on conflict (id)".
# Actual outcome

Query fails.  Generated SQL contains "on conflict ([unknown primary key])
# Discussion

This appears to be due to the following block in o.j.impl.InsertQueryImpl: 

``` java
                    if (table.getPrimaryKey() == null) {
                        ctx.sql("[unknown primary key]");
                    }
                    else {
                        boolean qualify = ctx.qualify();
                        ctx.qualify(false)
                           .visit(new Fields<Record>(table.getPrimaryKey().getFields()))
                           .qualify(qualify);
                    }
```

While debugging, it appears that since the Table on which the query is executed was obtained via DSL#table(String), jOOQ is unable to identify the primary key. This would not be a problem, however there appears to be no way to specify a primary key for the table nor does there appear to be a way to specify the columns/constraints to be used in the "ON CONFLICT" clause.

Given that the behavior results in loss of functionality, yet was reached using nothing other than what I believe to be supported, documented methods in a manner encouraged by the documentation, I believe this to be a bug.

Please let me know if you need additional information or if you'd like me to try something else.

Thanks for building jOOQ!

---

[1] 

``` java
this.ctx().insertInto(this.table())
    .set(DSL.field("id"), f.id())
    .set(DSL.field("last_modified"), Timestamp.from(Instant.now()))
    .onDuplicateKeyUpdate()
    .set(DSL.field("last_modified"), Timestamp.from(Instant.now())))
```

**Comment by lukaseder** [comment] 2016-03-30 12:10
Thank you very much for reporting this. There are indeed a couple of features that are not supported in jOOQ when using plain SQL, as constraint / identity information is not available on these tables.

In this particular case, ideally, a fix would add support for the PostgreSQL syntax, natively, allowing a user to specify the conflict constraint columns. You can already do this by using H2's syntax, which is emulated for PostgreSQL:

```java
ctx.mergeInto(table, field("id"), field("last_modified"))
   .key(field("id"))
   .values(f.id(), Timestamp.from(Instant.now()))
   .execute();
```

**Comment by lukaseder** [comment] 2016-03-30 12:13
Hmm, just realised that this is not yet implemented (`KEY` clause emulation for PostgreSQL)

**Comment by lightoze** [comment] 2016-04-01 21:10
In PostgreSQL it is a bit more complicated than just specifying key columns. You in fact specify a unique index signature. In my particular case I found it impossible to create `ON CONFLICT (col) WHERE active DO UPDATE SET ...` expression using jOOQ. Emulated `mergeInto` does not help here.

I would really appreciate if you have some workaround until this is properly implemented.

**Comment by lukaseder** [comment] 2016-04-03 14:00
The simplest workaround is `DSL.execute("INSERT INTO {0} ON CONFLICT ..", TABLE)`.

**Comment by lightoze** [comment] 2016-04-03 14:31
OK, thanks.

**Comment by dmitrygusev** [comment] 2017-03-30 14:11
Is there any plans/updates on this issue?
Anything we can do to see this fixed in one of the future releases?

**Comment by lukaseder** [comment] 2017-04-03 13:10
@dmitrygusev: jOOQ now supports `ON CONFLICT` for PostgreSQL natively since jOOQ 3.9. Does that solve the issue for you?

When PostgreSQL and MySQL should be supported in a single application, and plain SQL is used, in case of which jOOQ doesn't have the required primary key information, I don't have any answer yet.

**Comment by lightoze** [comment] 2018-03-17 12:03
For `ON CONFLICT` specifying constraint by name is not supported. When constraint is partial unique index this makes it impossible to use it with jOOQ.

**Comment by lukaseder** [comment] 2018-03-19 10:49
@lightoze : Can you please create a new issue with more details? I don't think this issue here is really related.

**Comment by lightoze** [comment] 2018-03-20 13:14
Right, those separate issues already exist as #6736 and #6906

**Comment by lukaseder** [comment] 2018-04-23 07:59
`ON CONFLICT .. ON CONSTRAINT` is now supported in jOOQ 3.11: #6906.

I'll close this as a duplicate of #6906

**Closed by lukaseder** 2018-04-23 07:59 UTC
Labels: C: DB: PostgreSQL, C: Functionality, P: Medium, T: Defect
