### ISSUE TITLE
Compilation error in KotlinGenerator generated code when @set:JvmName is applied to overriding property

### ISSUE THREAD

**Issue by NikolayMetchev** [jOOQ/jOOQ#12440] opened 2021-09-16 17:30 UTC
### Expected behavior
Code that can compile

### Actual behavior
Generates the following code which is invalid kotlin. The annotation cannot be applied there.
```
    @set:JvmName("setIsAuthorized")
    override var isAuthorized: Boolean?
        set(value): Unit = set(0, value)
        get(): Boolean? = get(0) as Boolean?
```
### Steps to reproduce the problem
The attached build file should reproduce the issue

[build.gradle.kts.zip](https://github.com/jOOQ/jOOQ/files/7179845/build.gradle.kts.zip)

### Versions

- jOOQ: 3.15.2
- Java: 11
- Database (include vendor): Postgres
- OS: MacOS Big Sur
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2021-09-17 07:35
Thanks, I can reproduce the compilation error, but why is it wrong in the first place? What would be the correct way to specify the setter here?

**Comment by lukaseder** [comment] 2021-09-17 07:40
A bit of research leads here:

- https://stackoverflow.com/a/59716818/521799
- https://youtrack.jetbrains.com/issue/KT-31420

It seems that this workaround does the trick:

```kotlin
    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsAuthorized")
    override var isAuthorized: Boolean?
        set(value): Unit = set(0, value)
        get(): Boolean? = get(0) as Boolean?
```

That's really ugly, and if we add it, we'll have to maintain this for a while even after KT-31420 is fixed. If you know a better solution, I'm all ears.

**Comment by NikolayMetchev** [comment] 2021-09-17 07:46
Is the renaming required? Why not keep the Kotlin names?

**Comment by lukaseder** [comment] 2021-09-17 07:50
See https://github.com/jOOQ/jOOQ/issues/11912

**Comment by NikolayMetchev** [comment] 2021-09-17 07:57
I see, well it seems the annotation is only needed if there is a clash. I suppose you could garble the name instead of using the annotation, only if there is a clash. Using backticks you could use a character in the clashing method that ensures it won't clash with anything else. A space maybe?

**Comment by lukaseder** [comment] 2021-09-17 08:02
> I suppose you could garble the name instead of using the annotation, only if there is a clash.

See: https://github.com/jOOQ/jOOQ/issues/11912#issuecomment-858601659

> Using backticks you could use a character in the clashing method that ensures it won't clash with anything else. A space maybe?

That doesn't sound like a good idea. How would that space work with e.g. the `DefaultRecordMapper`?

**Comment by lukaseder** [comment] 2021-09-17 08:03
Fixed in jOOQ 3.16.0, 3.15.3 (https://github.com/jOOQ/jOOQ/issues/12444), and 3.14.15 (https://github.com/jOOQ/jOOQ/issues/12445)

**Comment by NikolayMetchev** [comment] 2021-09-17 08:15
Thank you for the quick fix!

**Closed** 2021-09-17 08:16 UTC
Labels: T: Defect, C: Code Generation, P: Medium, R: Fixed, C: Integration: Kotlin, E: All Editions

**Comment by sgrimm** [comment] 2024-05-22 16:24
It seems like Kotlin 2.0.0 doesn't support the annotations that were added to fix this issue, so by default the Kotlin generator's Record classes produce warnings when compiled with 2.0.0.

For a pure Kotlin project, or one where you don't care whether the setter method names follow Java naming conventions, the workaround is to set `kotlinSetterJvmNameAnnotationsOnIsPrefix` to false in the [jOOQ generator settings](https://www.jooq.org/doc/latest/manual/code-generation/kotlingenerator/).

Noting the workaround here since this GitHub issue was the first one that came up when I did a Google search on the warning.

**Comment by lukaseder** [comment] 2024-05-23 06:35
Thanks, @sgrimm. I've created a new issue:

- https://github.com/jOOQ/jOOQ/issues/16690

> Noting the workaround here since this GitHub issue was the first one that came up when I did a Google search on the warning.

It's not really related, and the issue is already closed, so it's usually best to just open a new issue that can be tracked, labelled, and have milestones assigned. Comments are "ephemeral"

**Comment by lukaseder** [comment] 2024-05-23 07:28
To illustrate:I cannot reproduce the problem you seem to be having based on our existing integration tests. I found another one that I've fixed now, but it's unrelated to yours:

- https://github.com/jOOQ/jOOQ/issues/16691

So, can you please create a new issue with a reproducer?
