### ISSUE TITLE
CSVFormat: Customize array delimiter

### ISSUE THREAD

**Issue by hwellmann** [jOOQ/jOOQ#13871] opened 2022-08-16 14:05 UTC
### Use case:

I would like to import a CSV file generated with `formatCSV()` into a PostgreSQL database.

My table contains an array column `character varying[]`.

PostgreSQL expects array values to be formatted as `{"foo", "bar"}`. jOOQ exports them as `["foo", "bar"]`
### Possible solution you'd like to see:

Extend `CSVFormat` so that array delimiters (and likewise, separators) can be configured.
### Possible workarounds:

I had to work with a native `Connection` and use `CopyManager.copyOut()` from the `org.postgresql` JDBC driver.

### Versions:

- jOOQ: 3.17.1
- Java: 17
- Database (include vendor): PostgreSQL 14.5
- OS: MacOS 12.4
- JDBC Driver (include name if unofficial driver): org.postgresql 42.4.1

**Comment by lukaseder** [comment] 2022-08-16 14:35
Thanks for your feature request. There are probably numerous things that might need to be addressed (backwards incompatibly) to get this to work, including arrays, UDTs, and other data types.

**Comment by lukaseder** [comment] 2022-08-17 06:55
Related: https://github.com/jOOQ/jOOQ/issues/13872

**Comment by lukaseder** [comment] 2022-08-17 07:10
Also related: https://github.com/jOOQ/jOOQ/issues/13873. The question of how to export arrays should probably be addressed uniformly for all export formats, including:

- CSV
- JSON
- XML
- Text

In your particular case, I'm not convinced it's that easy. Your request isn't just about arrays. It's about being able to maintain the PostgreSQL object notation for arbitrary data types. And that has nothing to do with CSV either.

E.g. in a CSV context, we'd have to maintain quoting, which might conflict with the PG object notation, there are a lot of edge cases. I think you're better off doing this manually for now.

A thorough solution can be implemented once https://github.com/jOOQ/jOOQ/issues/5673 is available. In many cases, users will want to have control over how the CSV/JSON/XML/text exports format different data types. With an SPI to override the default formatting on a per `Field<T>` or per `DataType<T>` basis, you would then be able to easily produce the desired format.

I'm closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/5673

**Closed by lukaseder** 2022-08-17 07:10 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, T: Incompatible change, E: All Editions
