### ISSUE TITLE
Avoid the use of wildcard imports in documentation

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#13637] opened 2022-06-05 02:07 UTC
This is more of a general comment as an end-user: when reading the JOOQ documentation sometimes it's not clear where a certain class came from. One is tempted to click on the "show imports" button but then all we get is (for example):

```
import static com.example.generated.Tables.*;
import org.jooq.*;
import org.jooq.impl.*;
```

which does not help the reader's comprehension. I humbly suggest avoiding the use of wildcard imports in the documentation. This will help users figure out where each class or static import is coming from.

**Comment by lukaseder** [comment] 2022-06-05 07:50
This would be desirable, no doubt.

The current examples auto-generate the import statements based on heuristics based on the content of the example code. E.g. whenever there is something like `VARCHAR`, static import `org.jooq.impl.SQLDataType.*`. This heuristic could be overengineered endlessly, but that would just be busywork and sometimes it would still be wrong. So, a pragmatic choice was made, better than no imports.

The only real solution to this will be to create an example project (probably based on the new demo: https://github.com/jOOQ/demo, https://github.com/jOOQ/jOOQ/issues/13617), where fully self contained examples are implemented for Java/Kotlin/Scala. Benefits:

- Users can download the demo and run the examples on their machines, as well as tweak them
- Integration testing will guarantee the examples are always correct
- Minor benefits like non-wildcard imports will be possible

I don't think I'd like to address this import problem without addressing the much more useful improvement above, thoroughly.

**Comment by lukaseder** [comment] 2022-06-05 07:50
Closing as duplicate of https://github.com/jOOQ/jOOQ/issues/13617

**Closed by lukaseder** 2022-06-05 07:50 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, E: All Editions
