### ISSUE TITLE
JavaGenerator is failing on Postgres 11+ indexes using `INCLUDE` keyword

### ISSUE THREAD

**Issue by dmitrygusev** [jOOQ/jOOQ#11451] opened 2021-02-16 19:29 UTC
### Expected behavior
We use jOOQ JavaGenerator as Gradle plugin and code generation for indexes is ON by default.
We are not using the generated code, but it was not causing any issues until we added first index that uses `INCLUDE`  keyword [1].
Code generation failed with exception, while it shouldn't.
Disabling code generation for indexes fixed it for us:

```groovy
generator() {
 database() {
    //  jOOQ is failing on partial indexes with `INCLUDE`
    name('org.jooq.meta.postgres.PostgresDatabase')
    includeIndexes(false)
```

### Actual behavior

https://github.com/jOOQ/jOOQ/blob/version-3.13.2/jOOQ-meta/src/main/java/org/jooq/meta/postgres/PostgresDatabase.java#L234

```java
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
        at org.jooq.meta.postgres.PostgresDatabase$1.<init>(PostgresDatabase.java:234)
        at org.jooq.meta.postgres.PostgresDatabase.getIndexes0(PostgresDatabase.java:225)
        at org.jooq.meta.AbstractDatabase$14.run(AbstractDatabase.java:2037)
        at org.jooq.meta.AbstractDatabase.onError(AbstractDatabase.java:2547)
```

### Steps to reproduce the problem

Create an using `INCLUDE` keyword, e.g.:

```sql
create index index1 on table1 (a) include (b);
```

### Versions

- jOOQ: 3.13.2+ (maybe earlier versions too)
- Java: 11
- Database (include vendor): PostgreSQL 11+ (tested on 11.10)
- OS: MacOS
- JDBC Driver (include name if inofficial driver): postgresql-42.2.14.jar

[1] https://www.postgresql.org/docs/11/sql-createindex.html

**Comment by lukaseder** [comment] 2021-02-17 07:55
Duplicate of https://github.com/jOOQ/jOOQ/issues/10726, https://github.com/jOOQ/jOOQ/issues/10466. Fixed in 3.14.0 and 3.13.5 (#10470). Please upgrade.

**Closed by lukaseder** 2021-02-17 07:55 UTC
Labels: C: Code Generation, E: All Editions, P: Medium, T: Defect
