### ISSUE TITLE
Fetching enums with group by returns null

### ISSUE THREAD

**Issue by SebastianS90** [jOOQ/jOOQ#12464] opened 2021-09-23 07:01 UTC
### Expected behavior

Fetching enums in a statement using `group by` works.

### Actual behavior

Enum values are `null` when `group by` is used.

### Steps to reproduce the problem

https://github.com/SebastianS90/jOOQ-mcve-enum-group-by/tree/master/jOOQ-mcve-java

Note that `mcveTest1` works fine, but `mcveTest2` and `mcveTest3` are failing. The logger shows that jOOQ indeed fetches null values:
```
Executing query          : select "MCVE"."AUTHOR"."ID", "MCVE"."AUTHOR"."GENDER" from "MCVE"."AUTHOR"
Fetched result           : +----+------+
                         : |  ID|GENDER|
                         : +----+------+
                         : |   1|FEMALE|
                         : |   2|MALE  |
                         : +----+------+
Fetched row(s)           : 2

Executing query          : select "MCVE"."AUTHOR"."ID", "MCVE"."AUTHOR"."GENDER", count("MCVE"."BOOK"."ID") from "MCVE"."AUTHOR" left outer join "MCVE"."BOOK" on "MCVE"."BOOK"."AUTHOR_ID" = "MCVE"."AUTHOR"."ID" group by "MCVE"."AUTHOR"."ID"
Fetched result           : +----+------+-----+
                         : |  ID|GENDER|count|
                         : +----+------+-----+
                         : |   1|{null}|    2|
                         : |   2|{null}|    1|
                         : +----+------+-----+
Fetched row(s)           : 2

Executing query          : select "MCVE"."AUTHOR"."ID", "MCVE"."AUTHOR"."GENDER" from "MCVE"."AUTHOR" group by "MCVE"."AUTHOR"."ID"
Fetched result           : +----+------+
                         : |  ID|GENDER|
                         : +----+------+
                         : |   1|{null}|
                         : |   2|{null}|
                         : +----+------+
```

### Versions

- jOOQ: 3.15.3
- Java: 11
- Database (include vendor): H2 1.4.200
- OS: Linux

**Comment by lukaseder** [comment] 2021-09-23 07:17
Thanks for the report and MCVE. I can reproduce this. Will look into this right away

**Comment by lukaseder** [comment] 2021-09-23 07:20
It doesn't happen if you `.groupBy(AUTHOR.ID, AUTHOR.GENDER)`. Omitting those extra `GROUP BY` columns depends on the availability of a standard SQL `GROUP BY` feature that isn't implemented in all RDBMS, the fact that if you're grouping by a unique constraint, all functionally dependent columns can be projected as well. I wasn't aware the H2 supports this. It works when the query is run in DBeaver.

Will check what makes it fail in jOOQ.

**Comment by lukaseder** [comment] 2021-09-23 07:23
Seems to be H2. It produces the value `"1"`, not the enum literal when calling `ResultSet.getString()`. I'll create a JDBC based MCVE and report to H2 directly.

Please use the workaround I've mentioned above.

**Comment by lukaseder** [comment] 2021-09-23 08:09
I mean, you can try this in your `mcveTest3()`:

```java
try (PreparedStatement ps = connection.prepareStatement("select MCVE.AUTHOR.ID, MCVE.AUTHOR.GENDER from MCVE.AUTHOR group by MCVE.AUTHOR.ID")) {
    try (ResultSet rs = ps.executeQuery()) {
        while (rs.next()) {
            System.out.println(rs.getInt(1));
            System.out.println(rs.getString(2));
        }
    }
}
```

It produces:

```
1
1
2
0
```

I couldn't yet reduce the example to using JDBC only (without Maven, Flyway, etc.)

**Comment by lukaseder** [comment] 2021-09-23 08:14
I'm afraid, I can't seem to further reduce this to use only H2, no other tooling. But something is wrong when flyway sets up this database. The bug is in H2, I can connect to the `jdbc:h2:~/jooq-mcve-java` database with DBeaver and produce the same result as in the test:

![image](https://user-images.githubusercontent.com/734593/134474498-41c1e840-556d-4da9-8855-0b625494c0ad.png)

![image](https://user-images.githubusercontent.com/734593/134474536-ac87f031-5e55-4ac7-94d9-dd5e430418ac.png)

I'm closing this as not a jOOQ bug. Feel free to use this information here to report a bug to H2: https://github.com/h2database/h2database/issues/new

**Closed by lukaseder** 2021-09-23 08:14 UTC
Labels: T: Defect, C: Functionality, C: DB: H2, P: Medium, E: All Editions

**Comment by SebastianS90** [comment] 2021-09-23 10:08
Thanks for the update and your help. I'll just use `groupBy(AUTHOR.fields())` such that I can select all author columns. :+1:
