### ISSUE TITLE
Column alias loses `as` when round tripped through `parseQuery(…).getSQL()`

### ISSUE THREAD

**Issue by rkennedy-mode** [jOOQ/jOOQ#9769] opened 2020-01-28 20:20 UTC
### Expected behavior and actual behavior:

Expected: parsing a query using `Parser.parseQuery(String)` followed by rendering that same query using `Query.getSQL()` should preserve any `as` statements used for column aliases.

Actual: the `as` gets dropped while the remainder of the query is left intact.

### Steps to reproduce the problem:

```java
final Parser parser = DSL.using(SQLDialect.DEFAULT).parser();

final String originalQuery = "select foo as bar from baz";
final String substitutedQuery = parser.parseQuery(originalQuery).getSQL();

System.out.println("originalQuery    = " + originalQuery);
System.out.println("substitutedQuery = " + substitutedQuery);
```

Running the code above generates the following output:

```
originalQuery    = select foo as bar from baz
substitutedQuery = select foo bar from baz
```

### Versions:

- jOOQ: 3.12.2
- Java: 1.8.0 202
- Database (include vendor): none
- OS: macOS, Linux
- JDBC Driver (include name if inofficial driver): none

**Comment by rkennedy-mode** [comment] 2020-01-28 20:59
This also occurs even if you're not parsing the SQL but are generating it using `DSL`:

```java
final DSLContext context = DSL.using(SQLDialect.DEFAULT);
final String generatedSql = context.select(field(name("foo")).as(name("bar")))
            .from("baz")
            .getSQL();
System.out.println("generatedSql = " + generatedSql);
```

That produces:

```
generatedSql = select "foo" "bar" from baz
```

**Comment by lukaseder** [comment] 2020-01-29 11:01
Thank you very much for your report.

Historically, jOOQ is an internal DSL which generates appropriate SQL that is guaranteed to run on any given target dialect. There are ways to influence the exact SQL string, but only to some extent. For example, we might introduce a setting that allows for adding optional `AS` keywords to table and column aliases, where supported: https://github.com/jOOQ/jOOQ/issues/9502

With the parser, the use-cases may have shifted a bit, where users expect input SQL to be maintained where it does not strictly *have to* be adapted. In your case, we'd have to maintain on a per-alias basis whether the keyword `AS` is desireable or not. That's certainly doable, but not necessarily worth the effort. A similar case are optional `INNER` and `OUTER` keywords with joins, which can be influenced on a global basis with `Settings.renderOptionalInnerKeyword` and `Settings.renderOptionalOuterKeyword`, but also not on a per-usage basis.

Notice that it is not possible through the jOOQ API to omit the `AS` keyword, as it is through the parser.

In order to better understand your use-case and prioritise this feature request, I'd like to learn why you'd like for jOOQ to render this keyword. Could you share some more thoughts about your motivation?

**Comment by lukaseder** [comment] 2020-01-29 15:22
For the record, I've implemented https://github.com/jOOQ/jOOQ/issues/9502, which allows for globally configuring the generation of these keywords, if the underlying dialect supports them.

**Comment by rkennedy-mode** [comment] 2020-01-29 15:51
> In order to better understand your use-case and prioritise this feature request, I'd like to learn why you'd like for jOOQ to render this keyword. Could you share some more thoughts about your motivation?

It's a bit of an off-label use case where we're just using jOOQ's SQL parsing and generating features. We have a database we're using with a bug in how it applies parameters in parameterized queries. We're waiting for the vendor to fix the problem, but in the meantime are trying to implement parameter substitution in-application as a workaround. We then re-render the substituted SQL and push that down to the database. This particular database doesn't allow column aliases without `AS`, so the generated queries are failing during parsing in the database. We're executing the generated SQL ourselves (instead of letting jOOQ do it for us) as we've opted not to use this database's supplied JDBC driver. Here's the substitution function we're testing at the moment:

```java
import org.jooq.*;
import org.jooq.conf.ParamType;
import org.jooq.conf.ParseUnknownFunctions;
import org.jooq.conf.Settings;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultConfiguration;

public class SqlSubstitutions {
    public static String substitute(String query, Object... positionalParameters) {
        final Settings settings = new Settings()
                .withParseDialect(SQLDialect.DEFAULT)
                .withParseUnknownFunctions(ParseUnknownFunctions.IGNORE);

        final DefaultConfiguration configuration = new DefaultConfiguration();
        configuration.setSettings(settings);

        final DSLContext context = DSL.using(configuration);
        final Parser parser = context.parser();
        final Query substitutedQuery = parser.parseQuery(query, positionalParameters);
        return substitutedQuery.getSQL(ParamType.INLINED);
    }
}
```

We previously tried Calcite to do the same thing. We ran into some other issues there relating to the parser being a bit too strict with the `TRUNCATE` function to handle this database's dialect (it also has a function named `TRUNCATE` but it takes different parameters).

**Comment by lukaseder** [comment] 2020-01-29 16:00
Very interesting, thanks for sharing!

We definitely want to embrace such use cases in the future, but for arbitrary SQL dialects (what vendor is this, by the way?), this won't work well because both on the parser side as well as on the generation side, we need to know the dialect as we're always transforming things we already know (e.g. your `TRUNCATE` example). Once we do support the dialect, we'll have our entire feature set covered by integration tests. From then on, we can support also vendor specific features and syntaxes easily. I think that's a limitation Calcite is not aiming to address...

The `AS` keyword is an edge case that we can handle easily. The fix from #9502 should do the trick for you. You could build jOOQ from github and work with it right away.

I'd love to hear more about any limitations you may encounter. There's definitely room for improvement in these areas, given the limitations above.

**Comment by rkennedy-mode** [comment] 2020-01-29 16:22
> what vendor is this, by the way?

This is [VoltDB](https://www.voltdb.com/).

> I think that's a limitation Calcite is not aiming to address

Yeah, Calcite wants Calcite SQL to be sent in, which it will then convert to whatever dialect is needed for downstream queries. It's not meant to be a general purpose SQL parser, so this use case was just as off-label for them. With that said, I did find their visitor pattern pleasant for manipulating the queries. jOOQ's visitor bits felt more difficult to work with.

> I'd love to hear more about any limitations you may encounter.

One weird one we discovered late yesterday during our double dispatch experiment (we sent two queries: one with parameters substituted in-application and one with VoltDB performing the parameter substitution) is that jOOQ is silently rewriting `QUARTER` parameters passed to `EXTRACT` to `MONTH`. So if we send  in the query:

```sql
SELECT
EXTRACT(QUARTER FROM T3196834458925793283.A2) AS A00000457,
SUM(T3196834458925793283.A0) AS A00000474
FROM T3196834458925793283
GROUP BY EXTRACT(QUARTER FROM T3196834458925793283.A2)
ORDER BY EXTRACT(QUARTER FROM T3196834458925793283.A2) ASC
```

We get back:

```sql
select 
((extract(month from T3196834458925793283.A2) + 2) / 3) A00000457, 
sum(T3196834458925793283.A0) A00000474 
from T3196834458925793283 
group by ((extract(month from T3196834458925793283.A2) + 2) / 3) 
order by ((extract(month from T3196834458925793283.A2) + 2) / 3) asc
```

I've been meaning to separately file this one in the issues. I just haven't gotten there yet.

**Comment by lukaseder** [comment] 2020-01-29 16:32
> This is [VoltDB](https://www.voltdb.com/).

We're hoping to support that in the future: https://github.com/jOOQ/jOOQ/issues/1430. I cannot make any promises yet

> With that said, I did find their visitor pattern pleasant for manipulating the queries. jOOQ's visitor bits felt more difficult to work with.

Indeed, the design of our internal expression tree model makes it difficult to transform using a generic visitor pattern. One big goal of jOOQ 3.14 will be a new query object model, which is public and aims at SQL transformation use cases, which mainly benefit folks that use the parser.

> jOOQ is silently rewriting `QUARTER` parameters passed to `EXTRACT` to `MONTH`

That would depend on the target dialect. Most dialects don't support `QUARTER` as an extract date part (nor does the SQL standard), so we're producing an emulation that should work everywhere. But it will always depend on the output dialect. There isn't a "right" way to generate SQL by default.

**Comment by lukaseder** [comment] 2020-03-06 10:30
So, https://github.com/jOOQ/jOOQ/issues/9502 has shipped (global configuration of these `AS` keywords). I currently don't see the value of maintaining per-expression `AS`-y-ness in the query object model, unless we would really want to delve into the SQL formatting "business", where maintaining *exact* syntax is essential.

I'm closing this as a duplicate of #9502

**Closed by lukaseder** 2020-03-06 10:30 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Feedback Pending, T: Enhancement
