### ISSUE TITLE
Delete in kotlin coroutine reactive transaction fails silently

### ISSUE THREAD

**Issue by wfhartford** [jOOQ/jOOQ#13825] opened 2022-07-27 03:34 UTC
Deletes issued within a reactive transaction, using the Kotlin extension `DSLContext.transactionCoroutine` fail silently; no exception is thrown, the expected record count is returned, but records are not deleted. It's entirely possible that I'm doing something wrong, but I can't find it. The repository at https://github.com/wfhartford/jooq-already-resumed is a simple reproduction, and explains more in the README.

### Expected behavior
A delete issued in a reactive transaction from Kotlin should delete matching records

### Actual behavior
The delete appears to succeed, returning the expected number of records, but subsequent operations show that the records were not deleted. The reactor package logs many errors and warnings.

### Steps to reproduce the problem
I was unaware of the jOOQ MCVE project, so do not have a reproduction sample in that form, but there is a self-contained reproduction project at https://github.com/wfhartford/jooq-already-resumed. If a reproduction based on the MCVE project would be more helpful, I'd be happy to create that as well.

### Versions

- jOOQ: 3.17.2
- Java: openjdk version "17.0.3" 2022-04-19
- Database (include vendor): postgresql 14.2
- OS: Linux Pop!_OS 22.04 LTS
- JDBC Driver (include name if unofficial driver): org.postgresql:r2dbc-postgresql:0.9.1.RELEASE
- Kotlin: 1.6.20
- Kotlin Coroutines: 1.6.2

**Comment by wfhartford** [comment] 2022-07-27 16:32
I've verified that I still experience this issue with the latest versions of Kotlin (1.7.10) and coroutines (1.6.4).

**Comment by lukaseder** [comment] 2022-07-28 08:00
Thanks a lot for the report. I will look into this, soon

**Comment by juggernaut0** [comment] 2022-08-06 18:10
Likely duplicate of https://github.com/jOOQ/jOOQ/issues/13802

**Comment by lukaseder** [comment] 2023-01-17 08:44
The problem still reproduces on 3.18.0-SNAPSHOT and 3.17.7-SNAPSHOT, so this doesn't look as a duplicate.

**Comment by lukaseder** [comment] 2023-01-17 09:21
I made a mistake while changing version numbers, not updating IntelliJ's caches. On the commandline `gradlew run` works on 3.18.0-SNAPSHOT, but does not yet work on 3.17.7-SNAPSHOT

**Comment by lukaseder** [comment] 2023-01-17 09:26
Seems like I hadn't pushed the backport of #13802 to 3.17.7. After actually backporting things, the issue has now gone also in 3.17.7. So, this is indeed a duplicate of #13802

**Closed by lukaseder** 2023-01-17 09:26 UTC
Labels: T: Defect, C: Functionality, P: High, E: All Editions
