### ISSUE TITLE
Passing an empty array or collection to returningResult() does not match the behaviour of returning()

### ISSUE THREAD

**Issue by AnghelLeonard** [jOOQ/jOOQ#11437] opened 2021-02-13 16:28 UTC
### Expected behavior
The  `returningResult()` and `returning()` methods to return the same result.

### Actual behavior
The `returningResult()` method returns an empty result (wrong result).
The `returning()` method returns the expected result.

### Steps to reproduce the problem

I tried this query:

**RETURN THE TWO ROWS AS EXPECTED**
```Java
var inserted = ctx.insertInto(PRODUCTLINE, 
      PRODUCTLINE.PRODUCT_LINE, PRODUCTLINE.TEXT_DESCRIPTION, PRODUCTLINE.CODE)
  .values("Master Vans", "This new line of master vans ...", 11983423L)
  .values("Cool Cars", "This new line of cool cars ...", 11193384L)
  .returning()
  .fetch();
```
**RETURN AN EMPTY RESULT**
```Java
var inserted = ctx.insertInto(PRODUCTLINE, 
      PRODUCTLINE.PRODUCT_LINE, PRODUCTLINE.TEXT_DESCRIPTION, PRODUCTLINE.CODE)
  .values("Master Vans", "This new line of master vans ...", 11983423L)
  .values("Cool Cars", "This new line of cool cars ...", 11193384L)
  .returningResult()
  .fetch();
```
### Versions

- jOOQ: 3.14.7
- Java:14
- Database (include vendor): MySQL, SQL Server, PostgreSQL, Oracle
- OS:Windows 10
- JDBC Driver (include name if inofficial driver): -

**Comment by lukaseder** [comment] 2021-02-15 12:14
Thanks a lot for your report. Indeed, to be consistent with the various `select()` overloads, omitting an explicit field list always means to project the resolved `*` (asterisk) if we have table / column information available, or the `*` itself.

**Comment by lukaseder** [comment] 2021-02-15 13:05
Fixing this will be an incompatible change. Users who used the method as a way to indicate the absence of a `RETURNING` clause will get a regression if we fix this. This is especially true for users of `InsertQuery.setReturning(Collections.emptyList())`.

I still think we should fix this, because there's a `setReturning()` overload (no parameters), which looks like `setReturning(new SelectFieldOrAsterisk[0])`, but it behaves quite differently.

**Comment by lukaseder** [comment] 2021-03-30 09:15
I will be fixing this in jOOQ 3.15 via https://github.com/jOOQ/jOOQ/issues/5070. Starting from 3.15, `returningResult()` will be deprecated, and `returning()` will behave "as expected":

- `returning()` will return `R` types
- `returning(some columns)` will return `Record[N]` types

This matches the behaviour of `select()` and is what everyone expects.

**Comment by lukaseder** [comment] 2021-04-08 09:17
Having had a look at #5070, there are just way too many potential regressions caused by such a significant backwards incompatible change of API *and* behaviour. The API change would be OK-ish, but the behavioural change is really bad.

This issue here doesn't really depend on fixing #5070.

**Comment by lukaseder** [comment] 2021-04-08 09:23
The fix will also fix passing explicit empty arrays or collections to the various methods, which should have the same effect as calling `setReturningResult()`

**Comment by lukaseder** [comment] 2021-04-08 09:27
Fixed in jOOQ 3.15.0 and 3.14.9 (#11765). Thanks again for your report!

**Closed by lukaseder** 2021-04-08 09:27 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect, T: Incompatible change

**Comment by GeorgiPetkov** [comment] 2021-06-18 11:11
@lukaseder 

> Fixing this will be an incompatible change. Users who used the method as a way to indicate the absence of a `RETURNING` clause will get a regression if we fix this. This is especially true for users of `InsertQuery.setReturning(Collections.emptyList())`.
> 
> I still think we should fix this, because there's a `setReturning()` overload (no parameters), which looks like `setReturning(new SelectFieldOrAsterisk[0])`, but it behaves quite differently.

I totally agree with you about both the incompatibility and that it would be confusing if it's not fixed.
However, it's not only incompatible for users of 

> `InsertQuery.setReturning(Collections.emptyList())`

, but it also eliminates the only way to 

> indicate the absence of a `RETURNING`

for them.

This is currently used by a very useful addition to JOOQ for reactive users right here - https://github.com/gofabian/spring-boot-data-r2dbc-jooq/blob/master/src/main/java/gofabian/r2dbc/jooq/ReactiveQueryExecutor.java#L140

Obviously, I can set the `returning` field back to its initial value through reflection, but I would expect to have a separate method for that (to avoid just dropping the functionality). What do you think? I could write a separate issue for that if we're on the same page.

**Comment by lukaseder** [comment] 2021-06-18 11:21
> I could write a separate issue for that if we're on the same page.

Yes, please. Ideally with examples and version numbers before/after, because I'm not quite sure what is working / no longer working, or the other way round from your description.

**Comment by GeorgiPetkov** [comment] 2021-06-18 12:07
@lukaseder Here's the new issue - https://github.com/jOOQ/jOOQ/issues/12027.
