### ISSUE TITLE
DefaultBinding#pgNewArray does not handle arrays of records

### ISSUE THREAD

**Issue by BrentDouglas** [jOOQ/jOOQ#5333] opened 2016-06-06 11:04 UTC
jOOQ 3.7.2 professional
PG 9.4.5

Assuming we have a schema in PG like this:

``` sql
create type foo as (
  id int,
  name text,
  otherThing text
);

create type bar as (
  id int,
  foos foo[]
);
```

Selecting some data as a `bar` might result in a record looking like:
`(1,"{""(2,\\""First\\"",)"",""(3,\\""Second\\"",\\""This one is set\\"")""}")`

The column `foos` will not be mapped correctly by `DefaultBinding` as the parse logic does not consider 
embedded records and tokenises the array values using `,` which will split the first record after `2` (in the above example).

A workaround (and probably more robust general solution) is to call `row_to_json` and the unmap it afterwards but it would be nice to avoid the encoding overhead.

**Comment by lukaseder** [comment] 2016-06-07 05:53
Thank you very much for reporting this.

May I know how exactly you fetch the `bar` type? Is it from a table or a stored procedure? I.e. what's the jOOQ API usage you're running?

**Comment by BrentDouglas** [comment] 2016-06-07 07:44
Sorry, I should have included this in the original report. The sql I have looks roughly like this (using the type defs above):

```sql
create table t_foo (
  id serial primary key,
  name text not null,
  other text
);
create table t_bar (
  id serial primary key,
  foo_ids int[]
);

create or replace view v_bar as
  select
      b.id,
      row(
          b.id,
          coalesce(f.data, '{}')
      )::bar as data
  from t_bar b
  left join lateral (
      select
          array_agg(
              row(
                  f.id,
                  f.name,
                  f.other
              )::foo
          )::foo[] as data
      from t_foo f
      where f.id = any(b.foo_ids)
  ) f on true;
```

And the jOOQ code is:
```java
    public List<BarRecord> findBars() {
        return db.select(V_BAR.DATA)
                .from(T_BAR)
                .leftJoin(V_BAR)
                .on(V_BAR.ID.eq(T_BAR.ID))
                .fetchInto(BarRecord.class);
    }
```

In the above code `BarRecord` is a Pojo generated by the code-gen plugin.

I created a POC here (https://github.com/BrentDouglas/jooq-5333)

**Comment by lukaseder** [comment] 2016-06-07 16:21
Oh, very interesting query! Thanks a lot for the details. I will look into this soon

**Comment by BrentDouglas** [comment] 2016-06-07 19:59
I also noticed what looks like a bug in the Pojo generation code. If you look in the same example repo at the generated code for `Bar`, the field `foos` is an array of `FooRecord` while I would have expected it to be an array of `Foo` Pojos. The (paraphrased) generated class is below:

```java
package jooq5333.udt.pojos;

import java.io.Serializable;
import jooq5333.udt.records.FooRecord;

public class Bar implements Serializable {

	private Integer     id;
	private FooRecord[] foos;
        //...
}
```

I'm not sure if this a reasonable assumption to make or not.

**Comment by lukaseder** [comment] 2016-11-01 16:20
Also a duplicate of #5613 (see comment https://github.com/jOOQ/jOOQ/pull/5586#issuecomment-257611850 in #5586)

**Closed by lukaseder** 2016-11-01 16:20 UTC
Labels: C: DB: PostgreSQL, C: Functionality, P: Medium, T: Defect
