### ISSUE TITLE
SQL Translation Error from BigQuery to Snowflake

### ISSUE THREAD

**Issue by apptio-speravali** [jOOQ/jOOQ#13672] opened 2022-06-15 01:37 UTC
### SQL translator incorrectly translates this query: from BigQuery to Snowflake

```sql
CREATE OR REPLACE TABLE `proj.db1.saiperson1` AS
    ( SELECT name, AR.id AS colid, ASSIGNMENT_RATIO, (AR.id* ASSIGNMENT_RATIO) as colmetric1, (AR.id * ASSIGNMENT_RATIO) as col4evento FROM
      (SELECT id, 1/TEMP_TOTAL.TOTAL AS ASSIGNMENT_RATIO FROM `proj.db1.saiperson22`,
        (SELECT COUNT(DISTINCT(id)) AS TOTAL FROM `proj.db1.saiperson22`) AS TEMP_TOTAL
          GROUP BY id, TOTAL) AS AR CROSS JOIN `proj.db1.saiperson22` );

**Comment by lukaseder** [comment] 2022-06-15 06:59
Thanks for your report. We don't support parsing or representing the `CREATE OR REPLACE` statement yet, see https://github.com/jOOQ/jOOQ/issues/11453.

You can just remove the `OR REPLACE` subclause and it should work.

**Comment by lukaseder** [comment] 2022-06-15 06:59
Duplicate of https://github.com/jOOQ/jOOQ/issues/11453

**Closed by lukaseder** 2022-06-15 06:59 UTC
Labels: T: Enhancement, C: Functionality, P: High, R: Duplicate, E: All Editions
