### ISSUE TITLE
scala.UninitializedFieldError in runtime using generated data objects

### ISSUE THREAD

**Issue by astrofed** [jOOQ/jOOQ#8139] opened 2018-12-21 10:02 UTC
### Steps to reproduce the problem:
Using org.jooq.codegen.ScalaGenerator there are generated objects and classes for database objects (schema, catalogs, tables, records, etc). Then instantiating these objects in runtime the next error is excepted:

Caused by: scala.UninitializedFieldError: Uninitialized field: .../db/generated/Public.scala: 28

### Investigation results
It's caused by the fact that class Table has an argument in constructor Schema that's called from object Public (val PUBLIC = new Public), but constructor of Public contains reference on Catalog which called from object DefaultCatalog, but during initialization of DefaultCatalog in the body of this class there should be initialized val PUBLIC = com.opso.db.generated.Public.PUBLIC. As we can see there is a cross-reference and initialization loop. 

Looks like it's better to use **lazy val** instead **val** in scala case.

### Versions:
- jOOQ : 3.11.7
- Scala: 2.12.8
- Database (include vendor): PostgreSQL 11
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver (42.2.5)

**Comment by astrofed** [comment] 2018-12-21 10:04
Looks like https://github.com/jOOQ/jOOQ/issues/5489 has the same root

**Comment by lukaseder** [comment] 2018-12-21 10:40
Thanks for your report. Our integration tests work smoothly with Scala 2.12.8, but perhaps there's an edge case that cannot be reproduced so easily? Would it be possible to provide an MCVE (template here: https://github.com/jOOQ/jOOQ-mcve) that helps reproduce the issue?

**Comment by lukaseder** [comment] 2020-06-09 13:26
Unfortunately, we couldn't reproduce this issue in our integration tests so far. jOOQ 3.14 will have quite a few changes / improvements that were made to the `ScalaGenerator` in the context of the implementation of the new `KotlinGenerator`: https://github.com/jOOQ/jOOQ/issues/6248

It includes reordering of constructor declarations. Perhaps, this issue will resolve itself?

I'm closing this as "works for me". Will be happy to re-iterate a discussion with some more information on how to reproduce this.

**Comment by costa100** [comment] 2020-10-02 05:01
I have the exact same issue reported by the OP. I am using jooq 3.13.4. He described the accurately the issue. My database has exactly one table in the public schema and I generated the code using this config file:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.7.0.xsd">
  <jdbc>
    <driver>org.postgresql.Driver</driver>
    <url>jdbc:postgresql://localhost:5432/postgres</url>
    <user>postgres</user>
    <password>****</password>
  </jdbc>
  <generator>
    <name>org.jooq.codegen.ScalaGenerator</name>
    <database>
      <name>org.jooq.meta.postgres.PostgresDatabase</name>
      <inputSchema>public</inputSchema>
      <includes>.*</includes>
      <!--<excludes></excludes>-->
    </database>
    <target>
      <packageName></packageName>
      <directory>target/scala-2.13/src_managed/main</directory>
    </target>
  </generator>
</configuration>

```

**Comment by lukaseder** [comment] 2020-10-02 09:39
Thanks for the additional info, @costa100. I'll have another look

> I am so surprised nobody else complained about this since December 2018.

So far, our integration tests don't fail with this problem, so it does not seem to appear all the time. Anyway, I'll try to reproduce it again!

**Comment by lukaseder** [comment] 2020-10-02 12:07
Alrighty, this Maven plugin configuration is required to throw the exception:

```xml
<plugin>
    <groupId>net.alchim31.maven</groupId>
    <artifactId>scala-maven-plugin</artifactId>
    <executions>
        <execution>
            <goals>
                <goal>compile</goal>
                <goal>testCompile</goal>
            </goals>
        </execution>
    </executions>

    <configuration>
        <args>-Xcheckinit</args>
    </configuration>
</plugin>
```

**Comment by lukaseder** [comment] 2020-10-02 12:15
It was reported earlier already: https://github.com/jOOQ/jOOQ/issues/5489

**Comment by lukaseder** [comment] 2020-10-02 12:29
Fixed in jOOQ 3.14.0. Backport scheduled for 3.13.6 (#10708).

The workaround for the time being is to turn off the `-Xcheckinit` flag. The problematic, uninitialised generated objects do not seem to cause any issues per se, so the error seems to be cosmetic (for now).

**Closed by lukaseder** 2020-10-02 12:29 UTC
Labels: C: Code Generation, C: Integration: Scala, E: All Editions, P: Medium, T: Defect

**Comment by costa100** [comment] 2020-10-02 16:01
Thanks for the fast response! I wanted to say that I didn't explicitly set -Xcheckinit. I use Scala 2.13.2 and these were the scalacOptions in the sbt file:

```
scalacOptions ++= Seq(
  "-deprecation",
  "-encoding", "UTF-8",
  "-language:higherKinds",
  "-language:postfixOps",
  "-feature",
  "-Xfatal-warnings",
  "-Ymacro-annotations"
)
```

**Comment by lukaseder** [comment] 2020-10-02 17:48
Well, the scaladoc of [`scala.UninitializedFieldError`](https://www.scala-lang.org/api/current/scala/UninitializedFieldError.html) says that it is activated via `-Xcheckinit`:

> This class implements errors which are thrown whenever a field is used before it has been initialized. Such runtime checks are not emitted by default. They can be enabled by the -Xcheckinit compiler option.

Perhaps the `-Xfatal-warnings` flag also has this effect? I don't think `-Xcheckinit` is active by default, because it wasn't active in our integration tests, before I could reproduce it.

**Comment by joroKr21** [comment] 2020-11-02 09:38
Beware - using `lazy val` can cause a deadlock!

**Comment by lukaseder** [comment] 2020-11-02 09:46
@joroKr21 Well, does it?

**Comment by joroKr21** [comment] 2020-11-02 09:50
Yes, we observed a deadlock with 3.14.0 but I have no reproducer.
I do have a thread dump. I will open another issue soon.

**Comment by lukaseder** [comment] 2020-11-02 09:55
Oh no - thanks a lot for the report. We'll look into it ASAP

**Comment by joroKr21** [comment] 2020-11-03 15:57
#10849

**Comment by lukaseder** [comment] 2020-11-10 14:52
So, as discussed in https://github.com/jOOQ/jOOQ/issues/10849, we'll attempt generating `def` for these global object references, rather than `val` (which causes this error) or `lazy val` (which causes deadlocks)

**Comment by lukaseder** [comment] 2020-11-10 14:52
For anyone running into these cases, there's a workaround to prevent the deadlock. You can turn off generating these "global object references", see:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-globals/
