### ISSUE TITLE
withRenderSchema(false) does render schema in order by clause

### ISSUE THREAD

**Issue by simasch** [jOOQ/jOOQ#9296] opened 2019-09-27 13:05 UTC
### Expected behavior and actual behavior:

withRenderSchema(false) should disable adding the schema in the SQL statements but if there is an order by clause it does not:

select "KAMPAGNE"."KAMPAGNE" from "KAMPAGNE" where "KAMPAGNE"."KAMPAGNE" = 120 order by "TOSCA"."KAMPAGNE"."BEZ" fetch next 100 rows only

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

Generate the metadata classes with ojdbc8 against a Oracle 12.2.0.1.0 DB.
It seems that the generator is the problem not the runtime!
In runtime I can use the ojdbc8 driver if I generated with ojdbc7

### Versions:

- jOOQ: 3.12.1
- Java: AdoptOpenJDK 12.0.1.12
- Database (include vendor): Oracle 12.2.0.1.0
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): ojdbc8 12.2.0.1.0

**Comment by lukaseder** [comment] 2019-09-27 13:37
Thanks a lot for your report. I'll try to reproduce this.

For the record, this is following up on a discussion on https://stackoverflow.com/q/58099523/521799

**Comment by lukaseder** [comment] 2019-09-27 13:51
There is a known issue related to using `field(Name)`: https://github.com/jOOQ/jOOQ/issues/8991

But you're probably not using that, right? I cannot reproduce this issue with generated code. How can I reproduce it? Could you please post your entire jOOQ code that produces this query?

**Comment by simasch** [comment] 2019-09-27 14:05
You are right! I found the error.

I create a name with a schema

Name column = name(qualifiers);
Field<Object> field = field(column);

So it's not a bug! I'm sorry.

**Comment by lukaseder** [comment] 2019-09-27 14:24
Well, it is a bug: #8991. The schema mapping feature should also apply to qualified `Name` instances. But since this is what you're doing here, you can work around it by simply removing the schema qualifier as well in this case.

I'm closing this as a duplicate of #8991, which I've fixed in the meantime. The fix will ship with 3.12.2

**Closed by lukaseder** 2019-09-27 14:24 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect
