### ISSUE TITLE
SQL Translation Error : COPY

### ISSUE THREAD

**Issue by raphaelauv** [jOOQ/jOOQ#13842] opened 2022-08-09 08:46 UTC
### SQL translator incorrectly translates this query:

```sql
COPY myTable FROM 'value.txt' (DELIMITER('|'))
```

give 

```
Unexpected content after end of field input: [1:6] COPY [*]myTable FROM 'value.txt' (DELIMITER('|'));
```

**Comment by lukaseder** [comment] 2022-08-09 09:56
Thanks for your message. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/2747

However, it's unlikely that the COPY command can be translated to other dialects

**Closed by lukaseder** 2022-08-09 09:56 UTC
