### ISSUE TITLE
Wrong field indexes in code generated in record getters and setters for non-replacing embeddables when database reports non-consecutive column ordinals

### ISSUE THREAD

**Issue by Rattenkrieg** [jOOQ/jOOQ#17434] opened 2024-10-14 19:33 UTC
### Expected behavior

I have an embeddable composite field consisting of two columns.
I write a migration removing first column and adding another one.
I get ArrayIndexOutOfBoundsException when I try to set this field in the record

MCVE: https://github.com/Rattenkrieg/jOOQ-mcve/pull/2/files

### Actual behavior

```
ArrayIndexOutOfBounds Index 3 out of bounds for length 3
```

### Steps to reproduce the problem

```java
CompositeKeyExampleRecord record = new CompositeKeyExampleRecord();
record.setCompositeId(new CompositeKeyExampleIdRecord(2, 3));
```

```sql

CREATE TABLE mcve.composite_key_example (
  entity_1_id INT NOT NULL,
  entity_2_id INT NOT NULL,
  some_payload TEXT NOT NULL
);

ALTER TABLE mcve.composite_key_example ADD PRIMARY KEY (entity_1_id, entity_2_id);

ALTER TABLE mcve.composite_key_example DROP COLUMN entity_1_id;

ALTER TABLE mcve.composite_key_example ADD COLUMN entity_3_id INT NOT NULL;

```

```xml
<generator>
    <database>
        <includes>.*</includes>
        <schemata>

            <!-- PostgreSQL is lower case by default -->
            <schema>
                <inputSchema>mcve</inputSchema>
            </schema>
        </schemata>

        <embeddables>
        <embeddable>
            <catalog/>
            <schema>mvce</schema>
            <name>composite_key_example_id</name>
            <referencingName>composite_id</referencingName>
            <tables>composite_key_example</tables>
            <fields>
                <field><expression>entity_2_id</expression></field>
                <field><expression>entity_3_id</expression></field>
            </fields>
        </embeddable>
        </embeddables>
    </database>
    <generate>
        <generatedAnnotation>false</generatedAnnotation>
    </generate>
    <target>
        <packageName>org.jooq.mcve.java.postgres</packageName>
        <directory>src/main/java</directory>
    </target>
</generator>
```

### jOOQ Version

Open source edition 3.19.13

### Database product and version

postgres:latest

### Java Version

openjdk 21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.2

**Comment by lukaseder** [comment] 2024-10-15 09:11
Thanks a lot for your detailed report. I can reproduce the issue with your MCVE. The workaround is to avoid the generated setter, which seems to be generated incorrectly. This works:

```java
record.set(COMPOSITE_KEY_EXAMPLE.COMPOSITE_ID, new CompositeKeyExampleIdRecord(2, 3));
```

Related issue:

- https://github.com/jOOQ/jOOQ/issues/17435

I wonder if it's worth fixing the generated setters (and getters) at all, or if we should simply implement #17435.

**Comment by lukaseder** [comment] 2024-10-15 09:15
Again, this seems to be related strictly to non-replacing embeddables. The replacing embeddables don't run into this problem, as their generated getters and setters aren't "special."

**Comment by lukaseder** [comment] 2024-10-16 11:48
Looking into this now. The more thorough fix where the code generator logic is changed completely (https://github.com/jOOQ/jOOQ/issues/17435) is likely too risky for this specific problem alone, so I'll just address the off-by-1 error in generated code, first and backport that.

**Comment by lukaseder** [comment] 2024-10-16 12:02
Very interesting. Your DDL produces ordinal positions like this:

```sql
select column_name, ordinal_position
from information_schema.columns
where table_schema = 'mcve'
order by ordinal_position;
```

Result:

```
|column_name |ordinal_position|
|------------|----------------|
|entity_2_id |2               |
|some_payload|3               |
|entity_3_id |4               |
```

The reason can be seen in the underlying `pg_attribute` table:

```sql
select attname, attnum
from pg_attribute a
join pg_class c on a.attrelid = c.oid
where c.relname = 'composite_key_example'
and attnum > 0
order by attnum
```

Resulting in:

```
|attname                     |attnum|
|----------------------------|------|
|........pg.dropped.1........|1     |
|entity_2_id                 |2     |
|some_payload                |3     |
|entity_3_id                 |4     |
```

We can obviously handle this in jOOQ because PostgreSQL allows this, though it does seem to hint at a weird implementation detail of PostgreSQL leaking into the dictionary. I wonder what the story here is.

**Comment by lukaseder** [comment] 2024-10-16 12:14
Yeah, that's it. When generating ordinal positions for columns, we do our own counting in the code generator. But when referencing columns by position for embeddables, we're using the actual information supplied by the database (that's the only place where we use this information directly).

**Comment by lukaseder** [comment] 2024-10-16 12:39
Fixed in versions:

- 3.20.0
- 3.19.14 (https://github.com/jOOQ/jOOQ/issues/17445)
- 3.18.21 (https://github.com/jOOQ/jOOQ/issues/17446)
- 3.17.30 (https://github.com/jOOQ/jOOQ/issues/17447)

**Closed by lukaseder** 2024-10-16 12:39 UTC
Labels: T: Defect, C: Code Generation, P: Medium, E: All Editions

**Comment by lukaseder** [comment] 2024-10-17 08:25
The fact that PostgreSQL reports non-consecutive `ordinal_position` in `information_schema.columns` is probably a bug in PostgreSQL, as the SQL standard mandates consecutiveness. I've reported this to PostgreSQL:

- https://www.postgresql.org/message-id/18660-9ea9b58cce21a8bb%40postgresql.org

Thanks again for your help in discovering this, and for your simple and detailed reproducer.
