### ISSUE TITLE
NullPointerException when mapping NULL nested ROW from scalar subquery

### ISSUE THREAD

**Issue by strindberg** [jOOQ/jOOQ#12929] opened 2022-01-24 11:11 UTC
MCVE is published here: https://github.com/strindberg/jOOQ-mcve/tree/jooq_issue_12929

Database tables:

```sql
CREATE TABLE event
(
    id      bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    message text   NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE reply
(
    id       bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_id bigint NOT NULL,
    message  text   NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (event_id) REFERENCES event (id),
    UNIQUE (event_id)
);
```

Kotlin model:

```kotlin
data class Event(
    val id: Long? = null,
    val message: String,
    val reply: Reply? = null,
)

data class Reply(
    val eventId: Long,
    val message: String,
)
```

Kotlin code to retrieve `Events`:
  ```kotlin
dsl.select(
    ID,
    MESSAGE,
    field(
        select(row(REPLY.EVENT_ID, REPLY.MESSAGE).mapping(nullOnAllNull(::toReply)))
            .from(REPLY)
            .where(REPLY.EVENT_ID.eq(EVENT.ID))
    )
).from(EVENT).where(EVENT.ID.eq(eventId)).fetchOne(mapping(::toEvent))
```

If an `Event` has no matching `Reply` (which is OK according to the model), this code results in a `NullPointerException`within jOOQ. It seems as though the mapping to a `Reply` is attempted even though the nested row returned from the database query is null:

```
Caused by: java.sql.SQLException: Error while reading field: (
  select row ("public"."reply"."event_id", "public"."reply"."message")
  from "public"."reply"
  where "public"."reply"."event_id" = "public"."event"."id"
), at JDBC index: 3
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1584)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1523)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1482)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1447)
	... 41 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.jooq.Record2.value1()" because "r" is null
	at org.jooq.Records.lambda$mapping$12(Records.java:603)
	at org.jooq.RecordMapper.apply(RecordMapper.java:80)
	at org.jooq.RecordMapper.apply(RecordMapper.java:65)
	at org.jooq.Converter$1.from(Converter.java:178)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:997)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1574)
	... 45 more
```

### Versions

- jOOQ: 3.16.2
- Kotlin: 1.5.31
- Database (include vendor): PostreSQL 13.5

**Comment by lukaseder** [comment] 2022-01-24 12:20
Thanks for your report. I can reproduce this. Will look into this right away.

**Comment by lukaseder** [comment] 2022-01-24 12:20
Related: https://github.com/jOOQ/jOOQ/issues/12930

**Comment by lukaseder** [comment] 2022-01-24 12:34
I see, the error results from an assumption made by the `RecordMapper`:

```java
/**
 * Map a record into a POJO.
 *
 * @param record The record to be mapped. This is never null.
 * @return The mapped value, which may be <code>null</code> in some
 *         implementations.
 */
@Nullable
E map(R record);
```

The Javadoc establishes that `R` is never `null`, which was a reasonable assumption in pre jOOQ 3.15 days, when records were mostly used as elements in `Result<R>`, where they are indeed never `null`. But in the case of nested records, they can obviously be `NULL` as your example has demonstrated.

I'll have to investigate whether the `RecordMapper` assumption is wrong (`ROW (NULL, NULL)`, or whether the `Records::mapping` implementation is flawed. Given that `ROW (NULL, NULL)` isn't the exact same thing as `NULL` in SQL, I tend to think that `RecordMapper` is wrong. Fun example:

```sql
select 
  row (null, null) is distinct from null,
  row (null, null) is null
;
```

Result:

```
|?column?|?column?|
|--------|--------|
|true    |true    |
```

**Comment by lukaseder** [comment] 2022-01-24 14:05
There's a precedent for leaving the `RecordMapper` contract intact in various implementations

**`ResultQuery.fetchOne(RecordMapper)`**:

```java
@Override
default <E> E fetchOne(RecordMapper<? super R, E> mapper) {
    R record = fetchOne();
    return record == null ? null : mapper.map(record);
}
```

**`ResultQuery.fetchAny(RecordMapper)`**:

```java
@Override
default <E> E fetchAny(RecordMapper<? super R, E> mapper) {
    R record = fetchAny();
    return record == null ? null : mapper.map(record);
}
```

**`Cursor.fetchNext(RecordMapper)`**:

```java
@Override
public final <E> E fetchNext(RecordMapper<? super R, E> mapper) {
    R record = fetchNext();
    return record == null ? null : mapper.map(record);
}
```

Those are actually quite similar to a subquery producing a `NULL` record (i.e. the subquery not producing any records). They're for top level queries that might produce no record at all, in case we don't call the `RecordMapper` but maintain that a `null` input record produces a `null` output mapped value, which is allowed by the `RecordMapper` Javadoc.

So, rather than passing N `null` values to `nullOnAllNull`, we'll just skip mapping entirely, which has the same effect as what you intended with your code.

I'll add a remark to the individual Javadocs of those `nullOnAllNull` methods as well as on the `RecordMapper::map` method.

**Comment by lukaseder** [comment] 2022-01-24 14:19
Oh, the root cause is tricky!

`Row[N].mapping(Function[N])` does not have to adhere to the `RecordMapper` contract. Historically, it inherits the behaviour of `DataType::asConvertedDataType`, which delegates to `Converter::of`, not `Converter::ofNullable`.

`RecordMapper<R, E> <: Function<R, E>`, which is why a `RecordMapper` can be passed to the `Row[N]::mapping` method. So, the problem is in `Row[N]::mapping`, which wraps the argument `Function[N]` type in a `RecordMapper` compatible with the `Row[N]` type without taking into account null safety.

**Comment by lukaseder** [comment] 2022-01-24 15:20
Fixed in jOOQ 3.17.0, 3.16.3 (https://github.com/jOOQ/jOOQ/issues/12932), and 3.15.7 (https://github.com/jOOQ/jOOQ/issues/12933)

**Closed by lukaseder** 2022-01-24 15:20 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Fixed, E: All Editions

**Comment by lukaseder** [comment] 2022-01-24 15:21
Thanks again for your report. Will release these patch releases soon (today or tomorrow). The workaround in the meantime is to use a left join instead of a scalar subquery.

**Comment by strindberg** [comment] 2022-01-24 15:34
That's fantastic. Thanks for all your great work.
