### ISSUE TITLE
Regression when generating DDL from certain generated views

### ISSUE THREAD

**Issue by marceloverdijk** [jOOQ/jOOQ#17320] opened 2024-09-21 11:42 UTC
### Expected behavior

Correctly generate SQL for create views.

### Actual behavior

Generates an unexpected/additional 'create view' part in the statement.

### Steps to reproduce the problem

I'm currently doing:

```
    private fun writeCreateViews(ctx: DSLContext, out: PrintWriter) {
        ctx.settings().isRenderFormatted = true
        views.forEach { view ->
            ctx.ddl(view).queries().forEach { query ->
                val stmt = query.sql
                out.println("$stmt;")
                out.println("")
            }
        }
    }
```

to generate views.

Until 3.19.10 this works, e.g.:

```
SQL:
CREATE VIEW driver_of_the_day_result(
  race_id,
  position_display_order,
  position_number,
  position_text,
  driver_number,
  driver_id,
  constructor_id,
  engine_manufacturer_id,
  tyre_manufacturer_id,
  percentage
)
AS
SELECT
  race_data.race_id,
  race_data.position_display_order,
  race_data.position_number,
  race_data.position_text,
  race_data.driver_number,
  race_data.driver_id,
  race_data.constructor_id,
  race_data.engine_manufacturer_id,
  race_data.tyre_manufacturer_id,
  race_data.driver_of_the_day_percentage AS percentage
FROM race_data
WHERE race_data.type = 'DRIVER_OF_THE_DAY_RESULT'
```

but from 3.19.11 this generated wrong SQL:

```
SQL:
CREATE VIEW driver_of_the_day_result(
  race_id,
  position_display_order,
  position_number,
  position_text,
  driver_number,
  driver_id,
  constructor_id,
  engine_manufacturer_id,
  tyre_manufacturer_id,
  percentage
)
AS
    create view "driver_of_the_day_result" as SELECT
    "race_data"."race_id",
    "race_data"."position_display_order",
    "race_data"."position_number",
    "race_data"."position_text",
    "race_data"."driver_number",
    "race_data"."driver_id",
    "race_data"."constructor_id",
    "race_data"."engine_manufacturer_id",
    "race_data"."tyre_manufacturer_id",
    "race_data"."driver_of_the_day_percentage" AS "percentage"
FROM "PUBLIC"."race_data"
WHERE "race_data"."type" = 'DRIVER_OF_THE_DAY_RESULT'
```

It has a unexpected `create view "driver_of_the_day_result" as` before the `SELECT` statement.

### jOOQ Version

3.19.11

### Database product and version

Any

### Java Version

JDK 17`

**Comment by lukaseder** [comment] 2024-09-24 07:55
Thanks for your report. Can you please provide a more complete reproducer? E.g. what is `views`?

**Comment by marceloverdijk** [comment] 2024-09-24 09:03
More info here: https://github.com/f1db/f1db/blob/main/buildSrc/src/main/kotlin/com/f1db/plugin/writer/sql/SqlWriter.kt#L203-L212

On that project (`./gradlew clean dist assemble`), when updating to jOOQ 3.19.11 the generated SQL is invalid.
IF you prefer a minimal reproducer let me know, then I will create one later.

**Comment by lukaseder** [comment] 2024-09-24 09:41
OK, I won't try to figure out your build ;) Can you post an example generated view here so I can see what's going on?

**Comment by marceloverdijk** [comment] 2024-09-24 09:45
I understand ;-) I will post it later.

**Comment by lukaseder** [comment] 2024-09-24 11:29
I gave it a shot nonetheless. I didn't have to run the complete build to see what's being generated. Perhaps, this is the problem:

```java
    private DriverOfTheDayResult(Name alias, Table<DriverOfTheDayResultRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
            create view "driver_of_the_day_result" as SELECT
            "race_data"."race_id",
            "race_data"."position_display_order",
            "race_data"."position_number",
            "race_data"."position_text",
            "race_data"."driver_number",
            "race_data"."driver_id",
            "race_data"."constructor_id",
            "race_data"."engine_manufacturer_id",
            "race_data"."tyre_manufacturer_id",
            "race_data"."driver_of_the_day_percentage" AS "percentage"
        FROM "PUBLIC"."race_data"
        WHERE "race_data"."type" = 'DRIVER_OF_THE_DAY_RESULT'
        """), where);
    }
```

There's leading whitespace in the text block. And due to the implementation from #15238, we're not trimming the contents of the view source to assess whether there's a `create view` prefix (in case we cannot parse it):

- https://github.com/jOOQ/jOOQ/blob/7d2432dd2d010bc74e78908b94eb3d79d8755ddb/jOOQ/src/main/java/org/jooq/impl/DDL.java#L253

I suspect you should have seen an INFO log entry somewhere in your log output of the form:

```
Cannot parse view source (to skip parsing, use Settings.parseMetaViewSources): ...
```

I'll try to create a minimal reproducer from these assumptions

**Comment by lukaseder** [comment] 2024-09-24 11:54
> I suspect you should have seen an INFO log entry somewhere in your log output of the form:

No, that can't be the reason, otherwise the parsing would already fail in the `DDLDatabase`...

**Comment by lukaseder** [comment] 2024-09-24 12:05
OK, I can reproduce it simply with a test case like this:

```sql
CREATE VIEW v (a) AS SELECT 'a\b\c';
CREATE VIEW w (a1, a2) 
  AS 
    SELECT 
      a a1
    , a a2
    FROM v
    WHERE a != 'a';
```

When generating the DDL for `W`, then this exception is in the logs:

```
14:03:19,675  INFO [DDL                           ] - Cannot parse view source (to skip parsing, use Settings.parseMetaViewSources):     create view "W" as SELECT
    "A" AS "A1",
    "A" AS "A2"
FROM "PUBLIC"."V"
WHERE "A" <> 'a'

org.jooq.impl.ParserException: Unsupported query type: [5:7] ... AS "A1",
    "A" AS "A2"
FROM "PUBLIC"."V"
WHERE [*]"A" <> 'a'

	at org.jooq.impl.DefaultParseContext.exception(ParserImpl.java:15898) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1321) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.lambda$2(ParserImpl.java:940) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:16091) ~[classes/:?]
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:928) ~[classes/:?]
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:806) ~[classes/:?]
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:801) ~[classes/:?]
	at org.jooq.impl.DDL.applyAs(DDL.java:228) [classes/:?]
	at org.jooq.impl.DDL.createTableOrView(DDL.java:160) [classes/:?]
	at org.jooq.impl.DDL.queries(DDL.java:561) [classes/:?]
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:693) [classes/:?]
	at org.jooq.impl.DefaultDSLContext.ddl(DefaultDSLContext.java:4476) [classes/:?]
	at org.jooq.impl.DefaultDSLContext.ddl(DefaultDSLContext.java:4466) [classes/:?]
	at org.jooq.impl.DefaultDSLContext.ddl(DefaultDSLContext.java:4451) [classes/:?]
	at org.jooq.codegen.test.textblocks.TextblocksTest.testMeta(TextblocksTest.java:85) [test-classes/:?]
```

Will look into this right away, seems like an important regression caused by https://github.com/jOOQ/jOOQ/issues/16979

**Comment by lukaseder** [comment] 2024-09-24 12:33
Fixed in versions:

- 3.20.0
- 3.19.13 (https://github.com/jOOQ/jOOQ/issues/17356)
- 3.18.20 (https://github.com/jOOQ/jOOQ/issues/17357)
- 3.17.29 (https://github.com/jOOQ/jOOQ/issues/17358)

Thanks again for your report! I'll release this fix soon, later this week.

**Closed by lukaseder** 2024-09-24 12:33 UTC
Labels: T: Defect, C: Functionality, P: Urgent, E: All Editions

**Comment by marceloverdijk** [comment] 2024-09-24 12:54
Thx a log for the quick investigation and fix!
