### ISSUE TITLE
MariaDB: Update T as alias where t.id=<id> and not exists (select * from T where T.id=alias.id and <other conditions...> no longer works

### ISSUE THREAD

**Issue by jjqq2013** [jOOQ/jOOQ#14743] opened 2023-03-02 11:39 UTC
### Expected behavior

```
Update T as alias where t.id=<id> and not exists 
(select * from T where T.id=alias.id and <other conditions...>)
```
should be able to execute.

### Actual behavior

Error: column `id` does not exist.

### Steps to reproduce the problem

In Mariadb 10.3 (Mysql 5.7 equivilent)
```
    Test dlk = Test.as("dlk");
    return 1 == writeDslContext.transactionResult(configuration ->
        DSL.using(configuration).update(dlk)
            .set(dlk.IS_OWNER, true)
            .set(dlk.HEARTBEAT_AT, DSL.currentTimestamp(DSL.val(6)))
            .where(dlk.ID.eq(lockId))
            .and(DSL.notExists(
                DSL.select(val(1)).from(Test)
                    .where(Test.NAME.eq(dlk.NAME))
                    .and(Test.CREATED_AT.lessThan(dlk.CREATED_AT)
                        .or(Test.IS_OWNER.eq(true)))
            ))
            .execute());
```
acts different in different JOOQ version.

### In JOOQ 3.11.2, it produces following SQL 
```
update `test` as `dlk`
set `dlk`.`is_owner` = true, 
    `dlk`.`heartbeat_at` = current_timestamp(6)
where (
  `dlk`.`id` = 2720
  and not exists (
      select 1
      from `test`
      where (
        `test`.`name` = `dlk`.`name`
        and (
          `test`.`created_at` < `dlk`.`created_at`
          or `test`.`is_owner` = true
        )
      )
  )
)
```
It works.

#### In JOOQ 3.12.4, it produces following SQL
```
update `test` as `dlk`
set `dlk`.`is_owner` = true, 
    `dlk`.`heartbeat_at` = current_timestamp(6)
where (
  `dlk`.`id` = 2720
  and not exists (
  select * from (
      select 1
      from `test`
      where (
        `test`.`name` = `dlk`.`name`
        and (
          `test`.`created_at` < `dlk`.`created_at`
          or `test`.`is_owner` = true
        )
      )
  )
  ) as t
)
```

It actually added following wrapper to the subquery:
```
select * from
```

This is caused by the change in https://github.com/jOOQ/jOOQ/blob/8039850d7ca55946ca681405708b578749c70d55/jOOQ/src/main/java/org/jooq/impl/SelectQueryImpl.java#L1431-L1431

It is not difficult to find some workarounds, such as use inner join in the subquery.
```
                DSL.select(val(1)).from(Test)
                    .join(dlk) // to fix JOOQ bug, join myself. This dlk is unrelated with the update one.
                    .on(Test.NAME.eq(dlk.NAME))
                    .and(Test.REGION_CODE.eq(dlk.REGION_CODE))
                    .and(Test.DC_CODE.eq(dlk.DC_CODE))
                    .and(Test.CREATED_AT.lessThan(dlk.CREATED_AT)
                        .or(Test.IS_OWNER.eq(true)))
                    .where(dlk.ID.eq(lockId))
```
 
but it would be more convenient if we can improve the above change which is for another purpose.

Sorry I could not find the original PR of above change.

Anyway, to fix the issue of this ticket, actually it becomes how to improve the original PR, makes it works for all cases including the one I encountered in this ticket, especially not adding the extra `select * from`.

The improvement may be difficult, I am not sure if it is possible theoretically, it is not that obvious. I need check the original PR and related issue very carefully.
If theoretically there is no perfect solution, then I might give up.

### jOOQ Version

3.12.4

### Database product and version

Mariadb 10.3.8

### Java Version

17

### OS Version

Ubuntu Bionic

### JDBC driver name and version (include name if unofficial driver)

org.mariadb.jdbc:mariadb-java-client:3.0.8

**Comment by jjqq2013** [comment] 2023-03-02 11:41
Related issues
- https://github.com/jOOQ/jOOQ/issues/6583
- https://github.com/jOOQ/jOOQ/issues/14742

will add more if found.

**Comment by jjqq2013** [comment] 2023-03-02 11:43
The original PR seems be https://github.com/jOOQ/jOOQ/commit/14a73800ebd93bf3f0527c5977f7c87f79d76ead#r102735137

**Comment by jjqq2013** [comment] 2023-03-02 12:09
So the original PR was fighting with a MySQL optimizer issue. 

Then I turned to think why 
```
DELETE FROM story_category WHERE category_id NOT IN (
--          ^^^^^^^^^^^^^^ deleting from this table...

SELECT DISTINCT category.id FROM category 
       INNER JOIN story_category ON category_id=category.id);
--                ^^^^^^^^^^^^^^ ... prevents using the same table in predicates
``` 
does not work while my test sql works?
```
update `test` as `dlk`
set `dlk`.`is_owner` = true, 
    `dlk`.`heartbeat_at` = current_timestamp(6)
where (
  `dlk`.`id` = 2720
  and not exists (
      select 1
      from `test`
      where (
        `test`.`name` = `dlk`.`name`
        and (
          `test`.`created_at` < `dlk`.`created_at`
          or `test`.`is_owner` = true
        )
      )
  )
)
```

It seems that in my test sql , the MySQL optimizer knows that the following referenced columns can be estimated quickly
- `dlk`.`name`
- `dlk`.`created_at`
because the record can be located by the id = 2720.

Maybe `can or can not be estimated` is the whether nor nor MySQL reject execution.

**Comment by jjqq2013** [comment] 2023-03-02 12:14
Unfortunately, my guess is false. I dropped the condition `dlk.id = <constant>`, it still works
```
update `test` as `dlk`
set `dlk`.`is_owner` = true, 
    `dlk`.`heartbeat_at` = current_timestamp(6)
where (
  not exists (
      select 1
      from `test`
      where (
        `test`.`name` = `dlk`.`name`
        and (
          `test`.`created_at` < `dlk`.`created_at`
          or `test`.`is_owner` = true
        )
      )
  )
)
```

**Comment by jjqq2013** [comment] 2023-03-02 12:38
I have simplified the sql to 
```
update test as dlk set dlk.name = 'xxx'
where not exists (select * from test where test.name = dlk.name)
```
it still works.

Even 
```
update test as dlk set dlk.name = (select '1' from test where test.name > 'x' limit 1)
```
works.

```
update test as dlk set dlk.id = (select 1 from test where test.id=dlk.id limit 1)
```
also works.


What I missed? 

I re-checked the https://dev.mysql.com/doc/refman/5.7/en/subquery-restrictions.html
> UPDATE t ... WHERE col = (SELECT ... FROM t ...);

then tried
```
update test set id = (select 1 from test limit 1)
```
it still works!  

So I suspect that in MariaDB (at least 10.3), there is no such limitation. 

@lukaseder  if this is true, then we might just remove the MariaDB from the 
```
private static final Set<SQLDialect> REQUIRES_DERIVED_TABLE_DML      = SQLDialect.supportedUntil(MARIADB, MYSQL);
```

**Comment by jjqq2013** [comment] 2023-03-02 12:50
Really, the latest Mariadb also have no problem.

here is the evidence. You can change the mariadb:latest to other version such as mariadb:10.3.8

```
$ docker run -it -e MYSQL_ALLOW_EMPTY_PASSWORD=1 mariadb:latest
....
2023-03-02 12:45:58 0 [Note] Starting MariaDB 10.11.2-MariaDB-1:10.11.2+maria~ubu2204 source revision cafba8761af55ae16cc69c9b53a341340a845b36 as process 1
```

```
$_ docker ps |grep mariadb
f60f27323f31 ...

$__ docker exec -it f60f27323f31 bash
root@f60f27323f31:/# mysql
...
MariaDB [(none)]> create database db;
Query OK, 1 row affected (0.000 sec)
MariaDB [(none)]> ^DBye
root@f60f27323f31:/# mysql db
...
MariaDB [db]> create table test as select 1 as id, 'name' as name from dual;
Query OK, 1 row affected (0.008 sec)
Records: 1  Duplicates: 0  Warnings: 0

MariaDB [db]> desc test;
+-------+------------+------+-----+---------+-------+
| Field | Type       | Null | Key | Default | Extra |
+-------+------------+------+-----+---------+-------+
| id    | int(1)     | NO   |     | NULL    |       |
| name  | varchar(4) | NO   |     | NULL    |       |
+-------+------------+------+-----+---------+-------+
2 rows in set (0.001 sec)

MariaDB [db]> update test set id = (select 1 from test limit 1);
Query OK, 0 rows affected (0.001 sec)
Rows matched: 1  Changed: 0  Warnings: 0
```

**Comment by jjqq2013** [comment] 2023-03-02 12:54
And I have confirmed that in MySQL 5.7, the issue do exist:

Just change the `mariadb:latest` to `mysql:5.7` in above command.

```
mysql> create table test as select 1 as id, 'name' as name from dual;
Query OK, 1 row affected (0.01 sec)
Records: 1  Duplicates: 0  Warnings: 0

mysql> update test set id = (select 1 from test limit 1);
ERROR 1093 (HY000): You can't specify target table 'test' for update in FROM clause
```

**Comment by jjqq2013** [comment] 2023-03-02 12:59
There is no any document in Mariadb mentioned this limitation. So we can safely remove Mariadb from the work around list.

**Comment by lukaseder** [comment] 2023-03-02 13:07
> There is no any document in Mariadb mentioned this limitation. So we can safely remove Mariadb from the work around list.

I already have: https://github.com/jOOQ/jOOQ/issues/14742

Before I read all of the rest of your report, is this issue here about MariaDB or MySQL? I understand that you have documented individual steps of discovery. What's the takeaway from all of this?

**Comment by lukaseder** [comment] 2023-03-02 13:19
Ah, you've said it in the issue description:

> Mariadb 10.3.8

So, this is just a duplicate of #14742

**Comment by jjqq2013** [comment] 2023-03-02 14:04
@lukaseder  
> Before I read all of the rest of your report, is this issue here about MariaDB or MySQL?

It is about MariaDB, I just wrongly thought it should be same as MySQL.

> I already have: https://github.com/jOOQ/jOOQ/issues/14742
Strangely, I could not see the PR or the diff, where can I find it?

>What's the takeaway from all of this?
MariaDB does not have [the restriction of MySQL](https://dev.mysql.com/doc/refman/5.7/en/subquery-restrictions.html)   at all, I have confirmed in Mariadb 10.3.8 and latest one. 
```
MariaDB [db]> update test set id = (select 1 from test limit 1);
Query OK, 0 rows affected (0.001 sec)
Rows matched: 1  Changed: 0  Warnings: 0
```
So we can be confident to remove MariaDB from the workaround target list of the original PR.

**Comment by jjqq2013** [comment] 2023-03-02 14:26
@lukaseder  Are you sure you have done same modification as I did in https://github.com/jOOQ/jOOQ/pull/14744/files, I can not find the PR or diff in https://github.com/jOOQ/jOOQ/issues/14742.

**Comment by lukaseder** [comment] 2023-03-02 14:53
https://github.com/jOOQ/jOOQ/commit/9fb447315f5f01fe2672d8a023d652aab31ab0d0

**Comment by lukaseder** [comment] 2023-03-02 14:54
> So we can be confident to remove MariaDB from the workaround target list of the original PR.

Thanks for the clarification

**Comment by lukaseder** [comment] 2023-03-03 10:22
The change was premature. While some queries seem to work in MariaDB, which don't in MySQL, the change now produced a few integration test regressions. I'll investigate before releasing these patch versions.

**Closed** 2023-03-03 10:21 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Duplicate, E: All Editions

**Comment by lukaseder** [comment] 2023-03-03 11:44
See further comments here:

- https://github.com/jOOQ/jOOQ/issues/14742#issuecomment-1453310851

In particular, I suspect we'll still have to work around this particular MariaDB bug in order not to generate regressions for other jOOQ users:

- https://jira.mariadb.org/browse/MDEV-17954
