### ISSUE TITLE
codegen-liquibase : scripts relative to classpath

### ISSUE THREAD

**Issue by lolo101** [jOOQ/jOOQ#12298] opened 2021-08-12 13:46 UTC
Hi !

I have an issue with jOOQ code generation from liquibase scripts and I cannot figure a way out, and I failed to find help on the web.

I configured Maven plugin as such : 
```
	<plugin>
		<groupId>org.jooq</groupId>
		<artifactId>jooq-codegen-maven</artifactId>
		<dependencies>
			...
		</dependencies>
		<executions>
			<execution>
				<goals>
					<goal>generate</goal>
				</goals>
			</execution>
		</executions>
		<configuration>
			<generator>
				<database>
					<name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
					<properties>
						<property>
							<key>scripts</key>
							<value>src/main/resources/db/changelog/db.changelog-master.yaml</value>
						</property>
					</properties>
				</database>
			</generator>
		</configuration>
	</plugin>
```
And my `db.changelog-master.yaml` includes other scripts relative to the classpath : 
```
databaseChangeLog:
  - include:
      file: classpath:db/changelog/001.db-init.yaml
  - include:
      file: classpath:...
```
However the plugin cannot use the project output classpath (or I dont know how to).
And I cannot build the project without executing the jOOQ code generation because it relies on generated classes.

I find myself locked.

Can you help me about this issue ?

**Comment by lolo101** [comment] 2021-08-12 14:11
Actually the only way I found to workaround my issue is by specifying included scripts relative to changelog file : 
```
databaseChangeLog:
  - include:
      file: 001.db-init.yaml
      relativeToChangelogFile: true
  - include:
      file: 002...
      relativeToChangelogFile: true
```
But I dont find this solution very satisfying. What do you think ?

**Comment by lukaseder** [comment] 2021-08-13 07:12
Thanks a lot for your report.

We could probably tamper with the class loader to make sure Liquibase knows of Maven's classpath. This is always a bit hairy with Maven. There's a project classpath and a plugin classpath, and they share somethings, but not all (e.g. transitive dependencies of optional dependencies might not be available).

One possible way to solve this might be to put the required resources on your plugin classpath by specifying them as plugin dependencies. Have you tried that?

If that doesn't work, I'm happy to look into this in detail, if you could reduce your example to an MCVE? We have a template here: https://github.com/jOOQ/jOOQ-mcve

**Comment by lukaseder** [comment] 2021-08-13 07:20
Note, when all else fails, of course, you don't *have to* use the `LiquibaseDatabase`. Another option is to spin up a docker instance (e.g. using testcontainers), and run a complete migration in there prior to generating code the old fashioned way.

There's an example here: https://github.com/jOOQ/jOOQ/tree/main/jOOQ-examples/jOOQ-testcontainers-example

**Comment by lolo101** [comment] 2021-08-13 12:18
Hi @lukaseder and thanks for your quick answer.

Yes I thought about providing the liquibase changelog files to the plugin classpath but I couldn't figure out how to. And I confess I didn't want to spend much time investigating on that option that I felt, as you said, hairy.

I first used `PostgresDatabase` but faced two issues : 
- I had to replicate DB connection parameters in POM and in application configuration
- I could not deliver DB update with liquibase and code that relies on the update at the same time because the DB gets updated when the application starts, and in order to start the application, it needs to be built (obviously) but the DB needs to be up to date to generate the relevant source files to build the application...

`LiquibaseDatabase` effectively solved those two issues.

The docker option sounds a bit overkill for the project I'm working on but I'll take a look.

I'll try to set up an MCVE, many thanks for providing the template 😃

**Comment by lukaseder** [comment] 2022-01-13 12:32
Thanks for your comment, @pgokul. This issue here is about liquibase scripts referencing *other* liquibase scripts using classpath references. Yours seems to be different?

Can you please report a new issue with details to reproduce the problem? An MCVE would be greatly appreciated! https://github.com/jOOQ/jOOQ-mcve

**Comment by pgokul** [comment] 2022-01-14 15:05
Hi @lukaseder   thanks for clarifying. Filed #12872 for the issue I am facing with jooq 3.16.0

**Comment by lukaseder** [comment] 2022-01-14 15:37
Thanks a lot for the issue and MCVE. I'll check it out early next week

**Comment by lukaseder** [comment] 2023-05-12 14:53
I'm closing this issue as "worksforme" as related issues have been addressed by now:

- https://github.com/jOOQ/jOOQ/issues/12872
- https://github.com/jOOQ/jOOQ/issues/13031

I'm not entirely sure if this is the same issue as the above ones. If it isn't, please let me know.

**Closed by lukaseder** 2023-05-12 14:53 UTC
Labels: T: Defect, C: Code Generation, P: Medium, R: Worksforme, C: Integration: Liquibase, E: All Editions

**Comment by lolo101** [comment] 2023-05-14 22:54
Hi !

Unfortunately, I'm not working anymore on projects including jOOQ.
However, I promote switching from JPA to jOOQ for projects with high enough business complexity so I hope to use this wonderful library someday soon. I'll reopen this issue if need be.

Thank you ;)
