### ISSUE TITLE
Reactive transaction hangs when exception thrown in lambda constructing reactive flow

### ISSUE THREAD

**Issue by PiotrDuz** [jOOQ/jOOQ#15702] opened 2023-10-11 12:25 UTC
### Expected behavior

transactionPublisher method accepts lambda. If an exception is thrown inside this lambda, it should catch it and wrap into Publisher, to be consumed later.

### Actual behavior

When exception is thrown, it blocks transactionPublisher from completing.
If excepton is contained inside reactive flow, transactionPublisher finishes properly tho.

### Steps to reproduce the problem

Here is a reproduction: 
https://github.com/PiotrDuz/jooq-transaction-r2dbc-bug

Please run tests.
The one with @Timeout annotation shows the issue. 

There are 2 tests throwing errors. The difference is that one wraps error into reactive flow, and the other throws it outside of reactive flow, stopping transactionPublisher's lambda to return properly.

### jOOQ Version

3.18.6

### Database product and version

PostgreSQL 14

### Java Version

OpenJDK 17

### OS Version

Linux Ubuntu 22.10

### JDBC driver name and version (include name if unofficial driver)

I have used r2dbc driver, postgre 1.0.2.RELEASE

**Comment by lukaseder** [comment] 2023-10-12 12:30
Thanks for your report. I can confirm this with the following simpler test:

```java
Flux<Integer> flux =
Flux.from(ctx.transactionPublisher(c -> {
    throw new X();
}));
```

Our existing tests cover cases where we do something with the `Configuration` first, before there's an exception. This case seems to be special because the exception is the first thing that happens, so I'm guessing that something hasn't been initialised yet, or there's a race condition.

**Comment by lukaseder** [comment] 2023-10-12 12:48
Yeah, that's it. The problem here is that the initialisation of the `transactionPublisher` throws an exception, rather than the execution of the nested stream, so this is likely due to a bug in user code, not e.g. a constraint violation or any other "expected" exception in ordinary control flow.

Obviously, this should lead to jOOQ's transactional code hanging.

**Comment by PiotrDuz** [comment] 2023-10-12 12:51
Hey,
Thanks for having a look at this.
I might have misunderstood you but do you mean that  this is an expected outcome?

**Comment by lukaseder** [comment] 2023-10-12 12:53
No, what I meant is that it is very unlikely for an exception to be thrown at that point in the construction of a stream, which is why this hasn't been reported yet. E.g. `Mono.just(<throw an exception>)` isn't ordinary code - I guess you might have run into this due to a `NullPointerException`, or something similar?

Anyway, again, the fact that jOOQ hangs after this certainly is a bug, which I'm fixing right now.

**Comment by lukaseder** [comment] 2023-10-12 12:57
Fixed in versions:

- 3.19.0
- 3.18.8 (https://github.com/jOOQ/jOOQ/issues/15704)
- 3.17.17 (https://github.com/jOOQ/jOOQ/issues/15705)
- 3.16.23 (https://github.com/jOOQ/jOOQ/issues/15706)

**Closed by lukaseder** 2023-10-12 12:57 UTC
Labels: T: Defect, C: Functionality, P: High, E: All Editions

**Comment by PiotrDuz** [comment] 2023-10-12 13:06
Ah yes, exactly it is how we have experienced this problem. 
We've had some validation rules that have thrown an error on stream construction, so the exception was not wrapped into reactive container and bubbled from this lambda. 
Anyway, many thanks for your quick action.
Reactor and its types are adding another layer of complexity :/

**Comment by lukaseder** [comment] 2023-10-12 13:18
> Reactor and its types are adding another layer of complexity :/

I know. I generally recommend omitting it entirely, if possible. JDK 21/22 and Loom will (hopefully) help get rid of this fad very soon.
