### ISSUE TITLE
Generating Code with `org.jooq.codegen.GenerationTool`  and PostgreSQL 12 fails

### ISSUE THREAD

**Issue by fjf2002** [jOOQ/jOOQ#9686] opened 2019-12-18 16:45 UTC
### Expected behavior and actual behavior:
Generating Code with `org.jooq.codegen.GenerationTool`  and PostgreSQL 12 fails; it works with PostgreSQL 11,
cf. https://www.postgresql.org/docs/11/catalog-pg-constraint.html versus https://www.postgresql.org/docs/12/catalog-pg-constraint.html .

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
org.jooq.codegen.GenerationTool.generate

### Versions:
- jOOQ: 3.12.3
- Java: 1.8
- Database (include vendor): PostgreSQL 12.1
- OS: Ubuntu 19.10
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.9

### STDOUT:
SQL exception            : Exception while executing meta query: ERROR: column c.consrc does not exist
  Hinweis: Perhaps you meant to reference the column "c.conkey" or the column "c.conbin".
  Position: 127

Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new

```sql
with recursive "domains"("domain_id", "base_id", "typbasetype", "src") as (
  (
    select 
      "d".oid, 
      "d".oid, 
      "d"."typbasetype", 
      array["c"."consrc"]
    from "pg_catalog"."pg_type" as "d"
      join "pg_catalog"."pg_namespace" as "n"
      on "n".oid = "d"."typnamespace"
      left outer join "pg_catalog"."pg_constraint" as "c"
      on "d".oid = "c"."contypid"
    where (
      "d"."typtype" = 'd'
      and "n"."nspname" in ('public')
    )
  )
  union all (
    select 
      "domains"."domain_id", 
      "d".oid, 
      "d"."typbasetype", 
      case
        when "c"."consrc" is null then "domains"."src"
        else array_append("domains"."src", "c"."consrc")
      end
    from "domains"
      join "pg_catalog"."pg_type" as "d"
      on "domains"."typbasetype" = "d".oid
      left outer join "pg_catalog"."pg_constraint" as "c"
      on "d".oid = "c"."contypid"
  )
)
select 
  "n"."nspname", 
  "d"."typname", 
  "d"."typnotnull", 
  "d"."typdefault", 
  "b"."typname", 
  "b"."typlen", 
  "domains"."src"
from "pg_catalog"."pg_type" as "d"
  join "domains"
  on (
    "domains"."typbasetype" = 0
    and "domains"."domain_id" = "d".oid
  )
  join "pg_catalog"."pg_type" as "b"
  on "domains"."base_id" = "b".oid
  join "pg_catalog"."pg_namespace" as "n"
  on "n".oid = "d"."typnamespace"
where (
  "d"."typtype" = 'd'
  and "n"."nspname" in ('public')
)
order by 
  "n"."nspname", 
  "d"."typname"
```

**Comment by lukaseder** [comment] 2019-12-19 10:26
Thank you very much for your report. This seems like a duplicate of #9331, which we've backported to 3.12.2 (#9334).

Can you please confirm you're really using jOOQ 3.12.3 in your code generator, and not perhaps an older version that has been pulled in because of some transitive dependency? This could typically happen when using Spring Boot or a third party Gradle plugin to generate jOOQ code.

**Comment by lukaseder** [comment] 2020-01-30 13:44
In my opinion, this is a duplicate and should be fixed already. Please let me know if you think that's wrong and we can reopen this.

**Closed by lukaseder** 2020-01-30 13:44 UTC
Labels: C: Code Generation, E: All Editions, P: Medium, R: Duplicate, T: Defect
