### ISSUE TITLE
SQL Translation Error

### ISSUE THREAD

**Issue by seocliffdev** [jOOQ/jOOQ#8549] opened 2019-04-18 08:53 UTC
### SQL translator incorrectly translates this query:

```sql
USE [maju_man]
GO
/***** Object:  StoredProcedure [dbo].[sp_UserLogin]    Script Date: 04/09/2019 22:30:42 *****/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[sp_UserLogin]
@Email varchar(50),
@Password varchar(50),
@Token varchar(50)
as

update Users set token=@token where Email= @Email and PWD=@Password
select * from Users where Email= @Email and PWD=@Password
```

### Parser output:

```sql
DOMAIN, INDEX, SCHEMA, SEQUENCE, SESSION, TABLE, or VIEW expected: [8:7] ...NSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER [*]Procedure [dbo].[sp_UserLogin]
@Email varchar(50),
@Password varchar(50),
@Token...
```

**Comment by lukaseder** [comment] 2019-04-18 09:29
Thank you very much for your report. jOOQ, and by consequence, the translator currently do not fully support procedural languages, and DDL operations based on manipulating stored procedures and functions. We have a pending feature request for this: https://github.com/jOOQ/jOOQ/issues/8526

I'm closing this issue as a duplicate of #8526

**Closed by lukaseder** 2019-04-18 09:29 UTC
Labels: C: Functionality, E: Enterprise Edition, E: Professional Edition, P: Medium, T: Defect
