### ISSUE TITLE
Add support for the PostgreSQL timestamp value [+-]INFINITY

### ISSUE THREAD

**Issue by ciaccia** [jOOQ/jOOQ#7126] opened 2018-01-30 16:31 UTC
Starting with jOOQ 3.10, "timestamp with time zone" columns are mapped to `java.time.OffsetDateTime` instead of previous `java.sql.Timestamp`.

This new model is not able to handle values such as `'-infinity'::timestamptz` properly 
([documentation here](https://www.postgresql.org/docs/10/static/datatype-datetime.html#DATATYPE-DATETIME-SPECIAL-TABLE)).

Before the change, jOOQ internally called `java.sql.ResultSet#getTimestamp(int)` which knows how to handle special values such as +-infinity.

Now jOOQ gets the String version of the timestamp from the result set (using `java.sql.ResultSet#getString(int)` and passes the string value to `org.jooq.impl.DefaultBinding#offsetDateTime(String)`. Eventually an exception is throw complaining about `-infinity` not having the valid format.

Unfortunately I cannot fix this behavior using &lt;forcedTypes&gt; since jOOQ binding in this scenario is not passing Postgres' native type, rather `OffsetDateTime`. Ideally in this case the binding should receive a "native" type instead of a constructed one.

**Comment by lukaseder** [comment] 2018-01-30 16:39
Interesting, thanks for pointing this out.

> Unfortunately I cannot fix this behavior using <forcedTypes> since jOOQ binding in this scenario is not passing Postgres' native type

I think you're confusing the terms "converter" and "binding", here. You should be able to implement your own data type binding to work around the problem:
https://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings

Let me know if this helps

**Comment by ciaccia** [comment] 2018-01-31 10:00
Hi Lukas,
Please excuse me for the confusion. You are right, with a custom binder it is possible to avoid the problem. I got confused since the signature for the custom binder must be something like

    public class PGTimestampBinder implements org.jooq.Binding<OffsetDateTime, OffsetDateTime> {

which did not make any sense to me (why U and T in the template must be the same?). Nevertheless, with a custom binder on all timestamp column it is working fine. In the jOOQ configuration file I added it for all column with the timestamp with time zone type:

    <forcedTypes>
      <forcedType>
        <userType>java.time.OffsetDateTime</userType>
        <binding>com.example.PGTimestampBinder</binding>
        <expression>.*</expression>
        <types>.*timestamptz.*</types>
      </forcedType>
    </forcedTypes>

I don't know it it makes sense to you, but my fix is as following (which could be added to `DefaultBinding#offsetDateTime`:

    if ("epoch".equals(string)) {
        return OffsetDateTime.of(1970, 1, 1, 0, 0, 0, 0, ZoneOffset.UTC);
    } else if ("infinity".equals(string)) {
        return OffsetDateTime.ofInstant(new Date(DATE_POSITIVE_INFINITY).toInstant(), ZoneId.systemDefault());
    } else if ("-infinity".equals(string)) {
        return OffsetDateTime.ofInstant(new Date(DATE_NEGATIVE_INFINITY).toInstant(), ZoneId.systemDefault());
    } else if ("now".equals(string)) {
        return OffsetDateTime.now();
    } else if ("today".equals(string)) {
        return OffsetDateTime.ofInstant(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant(), ZoneId.systemDefault());
    } else if ("tomorrow".equals(string)) {
        return OffsetDateTime.ofInstant(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).plus(1, ChronoUnit.DAYS).toInstant(), ZoneId.systemDefault());
    } else if ("yesterday".equals(string)) {
        return OffsetDateTime.ofInstant(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).minus(1, ChronoUnit.DAYS).toInstant(), ZoneId.systemDefault());
    } else if ("allballs".equals(string)) {
        // This only for time, not for date/timestamp
        return OffsetDateTime.of(0, 0, 0, 0, 0, 0, 0, ZoneOffset.UTC);
    } else {
        return OffsetDateTime.parse(preparse(string, true));
    }


The two constants `DATE_POSITIVE_INFINITY` and `DATE_NEGATIVE_INFINITY` are copied from  [Posgres JDBC driver](https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/PGStatement.java)

**Comment by lukaseder** [comment] 2018-02-02 13:41
> which did not make any sense to me (why U and T in the template must be the same?)

Well, jOOQ's type (the T type) is `OffsetDateTime`. Your type (the U type) is also `OffsetDateTime`, even if you interpret it differently. So, `T` and `U` are the same type.

> I don't know it it makes sense to you, but my fix is as following (which could be added to DefaultBinding#offsetDateTime

That certainly does make sense. Are you interested in providing a contribution?

**Comment by ciaccia** [comment] 2018-02-07 14:17
Hi Lukas,
feel free to merge it in your DefaultBinding or wherever you think it makes more sense. Do you need a CLA to be signed for this?

**Comment by lukaseder** [comment] 2018-02-09 16:04
@ciaccia, yes, please. A signature on the transfer of rights agreement is required to allow us to dual license your contribution. The agreement is linked from the contribution guidelines: https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md

**Comment by lukaseder** [comment] 2018-03-09 15:31
I've added some comments directly on the PR : https://github.com/jOOQ/jOOQ/pull/7251. I'm sorry I hadn't noticed the flaws earlier. Do you have any idea on how to fix these things?

**Comment by rtomsick** [comment] 2018-03-31 01:44
Even if this is fixed for codegen users, this is a *serious* regression for one of the codebases that I maintain.  It uses the DSL API directly (no codegen), and relies on `field(name("foo"), Instant.class)` all over the place.  The change in the default behavior is a bad, bad break and pretty much means that we're stuck on 3.9.x.

Is there any workaround to this?  Anything we can configure?

**Comment by lukaseder** [comment] 2018-04-03 09:07
Thanks for joining, @rtomsick. Would you mind shedding some light on how this breaks your code? I'm not aware of `field(Name, Instant.class)` having worked in the past, not it being supported. Perhaps it's better you report a new issue with more details (see some guidelines here: https://stackoverflow.com/help/mcve) to be sure we're not missing anything.

**Comment by rtomsick** [comment] 2018-04-03 14:30
My mistake, I actually meant `field(name("foo"), Timestamp.class)` 

Still, it remains an issue for me...

**Comment by lukaseder** [comment] 2018-04-03 14:37
Thanks for clarifying. Does rewriting the `TIMESTAMP WITH TIME ZONE` types to `TIMESTAMP` work for you? Coincidentally, there has been a very similar discussion on the user group during the last few days:
https://groups.google.com/forum/#!topic/jooq-user/PmUYk7rtVa8

**Comment by lukaseder** [comment] 2018-04-03 14:38
Egh, didn't mean to close

**Comment by rtomsick** [comment] 2018-04-03 14:45
I haven't tried that, but I can.

I didn't realize that the previous behavior was [potentially] silently wrong.  If that's the case, then it might be better to bite the bullet and rewrite the field accesses to use `OffsetDateTime`.

**Comment by lukaseder** [comment] 2018-04-03 14:57
> I didn't realize that the previous behavior was [potentially] silently wrong

Yes. Very unfortunately, that was the case. It would have been better to fail fast and not pretend to support the `TIMESTAMP WITH TIME ZONE` data type in the past - it just happened to work well enough in simple setups (server and client in the same time zone).

**Comment by rtomsick** [comment] 2018-04-03 14:58
I'll take broken over silently wrong any day.  That makes it a bug on my end, not yours.  I'll rework the calling code.

**Comment by lukaseder** [comment] 2018-04-04 06:43
For the record, I have created https://github.com/jOOQ/jOOQ/issues/7378 to improve the behaviour of `<javaTimeTypes/>` to be more backwards compatible for people upgrading to jOOQ 3.9+. Will look into mechanisms to warn people of potential silent errors in case `java.sql.Timestamp` is used for a `TIMESTAMP WITH TIME ZONE` database type.

**Comment by lukaseder** [comment] 2018-11-09 10:39
I have given this some more thought and done some research. While it is definitely possible to write a custom binding in a way for PostgreSQL infinity values to be encoded as any kind of value in Java, including `OffsetDateTime.MIN` and `OffsetDateTime.MAX`, I'm not convinced yet that jOOQ should be opinionated here. Any encoding may be as good as any other encoding, e.g. I've seen applications encode `infinity` as `9999-12-31` and `-infinity` as `0000-00-00` (if that is possible in any given database).

Since the PostgreSQL JDBC driver supports infinities, these should be used: see
https://stackoverflow.com/a/51111336/521799

I'm closing this issue for now. If it gets more traction, I'll be happy to reopen and reconsider my decision.

**Closed by lukaseder** 2018-11-09 10:39 UTC
Labels: C: DB: PostgreSQL, C: Functionality, E: All Editions, P: Medium, T: Enhancement

**Comment by lukaseder** [comment] 2018-11-09 10:56
Hmm, in fact, this specific PostgreSQL JDBC driver "infinity" value works only when setting the value as a bind variable, not when inlining the value. That's what should be fixed here

**Comment by lukaseder** [comment] 2018-11-09 15:42
Work in progress committed. Still doesn't work correctly for `LocalDateTime` and `LocalDate`

**Comment by katzyn** [comment] 2018-11-10 05:03
@lukaseder
There are two incorrect assumptions in that JShell code.

The first one is about calendar systems. Old datetime data types in Java, including `java.sql.*` data types use traditional mixed Julian / Gregorian calendar system when last Julian date `1582-10-04` was followed by first Gregorian date `1582-10-15`. This transition is actually configurable in these data types using `java.util.Calendar` and JDBC has methods with additional `Calendar` parameter. They can be used to specify custom calendar system, but only some drivers support it properly. JSR-310 data types such as `LocalDate`, `LocalDateTime` and some others deal with proleptic Gregorian calendar system instead unconditionally. It actually means that there is no 1:1 mapping for dates before `1582-10-15`, proleptic Gregorian does not have some leap years that mixed calendar has, but proleptic Gregorian has dates between `1582-10-04` and `1582-10-15`, there is no gap. (BTW, PostgreSQL uses proleptic Gregorian too, but its JDBC driver uses tricky code to convert old dates for mixed calendar.)

The second one is about dealing with calendar eras in old data types in Java. `java.util.Date`, `java.sql.Date`, and `java.sql.Timestamp` can store BC dates internally, but their `toString()` methods historically can work only with AD era. Their `parse(String)` methods also were deprecated. `GregorianCalendar` or `DateFormat` implementations should be used instead. Some databases also cannot work with BC era.

`new Timestamp(-100_000_000_000_000L)` belongs to BC era, so you should not use implicit `toString()` here too, it simply can't format such timestamp correctly.

Unfortunately, many conversion methods between old and new JSR-310 data types also do not support BC era. Because all dates with the same calendar system (`1582-10-15` and following) belong to AD era this issue is not very significant, there is no exact mapping for older dates anyway and results will be weird and unexpected in any case.

`toInstant()` / `from(Instant)` methods, however, are fine because they simply work with `1970-01-01 00:00:00Z` offsets, used calendar system does not matter here.

**Comment by lukaseder** [comment] 2018-11-12 09:38
Thanks for the clarifications, @katzyn. You may have read 1-2 assumptions in that screenshot, which weren't there. The `toString()` calls were incidental. What was surprising (to me) is that the `Timestamp.toLocalDateTime()` would "lose information" by behaving just like `toString()`. Of course, knowing about the limitations of the Java libraries is helpful, nonetheless.

**Comment by katzyn** [comment] 2018-11-12 10:15
Not only the BC era, but also all dates before 1582-10-15 need special care, because different classes and methods return different results:

### 1500-02-29
1500 was a leap year actually and `java.util` / `java.sql` know it.
```Java
Timestamp ts = new Timestamp(
    new GregorianCalendar(1500, GregorianCalendar.FEBRUARY, 29, 0, 0, 0)
        .getTimeInMillis());
System.out.println(ts);
System.out.println(ts.toLocalDateTime());
```
But not in JSR-310:
```
1500-02-29 00:00:00.0
java.time.DateTimeException: Invalid date 'February 29' as '1500' is not a leap year
```
### 1500-02-28
```Java
TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
Timestamp ts = new Timestamp(
    new GregorianCalendar(1500, GregorianCalendar.FEBRUARY, 28, 0, 0, 0)
        .getTimeInMillis());
System.out.println(ts);
System.out.println(ts.toLocalDateTime());
System.out.println(ts.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime());
```
```Java
1500-02-28 00:00:00.0 // Julian
1500-02-28T00:00      // Julian? Not actually, LocalDateTime uses proleptic Gregorian
1500-03-09T00:00      // The same date in Gregorian
```

In some countries the actual Julian/Gregorian cutover should be different.

Different databases work with such old dates in different way, their calendar systems are also different. The only one good thing here is that such old dates are rarely used.

**Comment by knutwannheden** [comment] 2019-11-27 10:02
@lukaseder Is there anything left to be done here? I.e. should we reopen or add the corresponding issue resolution label?

**Comment by lukaseder** [comment] 2019-11-27 11:51
From what I recall, it was resolved. Perhaps with bugs in edge cases as documented in the comments.
