### ISSUE TITLE
Audit timestamps are ignored

### ISSUE THREAD

**Issue by cmrgKoradir** [jOOQ/jOOQ#14707] opened 2023-02-24 17:53 UTC
### Expected behavior

We've got audit columns defined on most of our tables, tracking who and when created or modified an entity
(where creation also counts as modification).

Because our database has no concept of a "logged-in user", we provide the necessary information via our own `IdentityProvider` (which behind the scenes has access to the Spring security context) to a  custom subclass of the `DefaultAuditProvider`.

We only need to overwrite the user, we rely on the default timestamp implementation from the `DefaultAuditProvider` to fill in the timestamp columns.

Expectation was that all these columns would be updated behind the scene.

### Actual behavior

JOOQ correctly updates the `auditInsertUser` and `auditUpdateUser` columns, but ignores our `auditInsertTimestamp` and `auditUpdateTimestamp` columns.

Quick debugging shows that even when we override the `DefaultAuditProvider::provideTimestamp` function, it is never actually invoked - unlike our `provideUser` function, which  works as intended.

### Steps to reproduce the problem

sql columns defined on the tables:
```sql
created           TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
created_by_id     INTEGER                  DEFAULT 1,
modified_by_id    INTEGER                  DEFAULT 1,
last_modification TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,,
```
(where the `~_by_id ` columns have a foreign key constraint each on a `person` table)

gradle.properties
```
fw_springBoot=2.7.8
fw_kotlin=1.6.21
plugin_jooq=8.1
lib_jooqPro=3.17.6
lib_postgresDriver=42.5.0
```

build.gradle (`:db-model`, only contains code-gen)
```groovy
import nu.studer.gradle.jooq.JooqEdition

buildscript {
    configurations['classpath'].resolutionStrategy.eachDependency {
        if (requested.group == 'org.jooq') {
            useVersion "$lib_jooqPro"
        }
    }
}

plugins {
    id("nu.studer.jooq") version "${plugin_jooq}"
}

dependencies {
    api("org.jooq.pro:jooq:$lib_jooqPro")

    implementation(project(":db-migration"))    //only contains our flyway migrations
    implementation("org.jooq.pro:jooq-codegen:$lib_jooqPro")
    implementation("org.jooq.pro:jooq-meta:$lib_jooqPro")

    jooqGenerator("org.postgresql:postgresql:$lib_postgresDriver")
    runtimeOnly("org.postgresql:postgresql:$lib_postgresDriver")

    modules {
        module("org.jooq:jooq") {
            replacedBy("org.jooq.pro:jooq", "nu.studer.jooq bugfix #183") // https://github.com/etiennestuder/gradle-jooq-plugin/issues/183
        }
    }
}

jooq {
    version = "$lib_jooqPro"
    edition = JooqEdition.PRO

    configurations {
        myapp {
            generateSchemaSourceOnCompilation = false

            generationTool {
                logging = org.jooq.meta.jaxb.Logging.WARN
                jdbc {
                    driver = "org.postgresql.Driver"
                    url = "jdbc:postgresql://localhost:5432/my-postgres-db"
                    user = ...
                    password = ...
                }
                generator {
                    name = "org.jooq.codegen.DefaultGenerator"
                    database {
                        name = "org.jooq.meta.postgres.PostgresDatabase"
                        inputSchema = "public"
                        includes = '.*'
                        excludes = '''
                              AUDIT_LOG
                            | FLYWAY.*
                        '''
                        forcedTypes {
                            forcedType {
                                name = "varchar"
                                includeExpression = ".*"
                                includeTypes = "JSONB?"
                            }
                            forcedType {
                                name = "varchar"
                                includeExpression = ".*"
                                includeTypes = "INET"
                            }
                            forcedType {
                                name = "INSTANT"
                                includeTypes = '''
                                      TIMESTAMPTZ
                                    | TIMESTAMP
                                '''
                            }
                            forcedType {
                                auditInsertTimestamp = true
                                name = "timestamptz"
                                includeExpression = "created"
                            }
                            forcedType {
                                auditInsertUser = true
                                name = "int"
                                includeExpression = "created_by_id"
                            }
                            forcedType {
                                auditInsertTimestamp = true
                                auditUpdateTimestamp = true
                                name = "timestamptz"
                                includeExpression = "last_modification"
                            }
                            forcedType {
                                auditInsertUser = true
                                auditUpdateUser = true
                                name = "int"
                                includeExpression = "modified_by_id"
                            }
                        }
                    }
                    generate {
                        pojos = false
                        daos = false
                        records = true
                        deprecated = false
                    }
                    target {
                        packageName = "my.app.db.model"
                        directory = "src/main/java"
                    }
                    strategy {
                        name = null
                        matchers {
                            tables {
                                table {
                                    tableClass {
                                        transform = 'PASCAL'
                                        expression = '$0_TABLE'
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```
worth noting that we exclude jOOQ as a dependency from the spring-boot starter:
build.gradle (`:db-repository`, only module that has access to jOOQ)
```groovy
import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    id 'io.spring.dependency-management'
}

dependencyManagement {
    imports {
        mavenBom SpringBootPlugin.BOM_COORDINATES
        mavenBom "org.jetbrains.kotlin:kotlin-bom:${fw_kotlin}"
    }
}

dependencies {
    implementation(project(":db-model"))   // the generated jOOQ files
    implementation("org.springframework.boot:spring-boot-starter-jooq") {
        exclude group: "org.jooq" //s.t. we get the transitive commercial jooq dependency from :db-model instead of the open-source version the starter normally pulls
    }
}
```

Custom jOOQ Config:
```kotlin
import com.google.common.annotations.VisibleForTesting
import my.app.foo.IdentityProvider
import org.jooq.AuditProvider
import org.jooq.Field
import org.jooq.GeneratorContext
import org.jooq.impl.DSL
import org.jooq.impl.DefaultAuditProvider
import org.jooq.impl.DefaultConfiguration
import org.springframework.boot.autoconfigure.jooq.DefaultConfigurationCustomizer
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration

const val UNKNOWN_PERSON_ID = 1

@Configuration
class JooqConfig(
    private val identityProvider: IdentityProvider,
) {
    @Bean
    fun configurationCustomizer() = DefaultConfigurationCustomizer { c: DefaultConfiguration ->
        c.setAuditProvider(auditProvider())
    }

    @Bean
    fun auditProvider(): AuditProvider = PrincipalAwareAuditProvider(identityProvider)

    @VisibleForTesting
    internal class PrincipalAwareAuditProvider(private val identityProvider: IdentityProvider) : DefaultAuditProvider() {
        private val auditorId: Int get() = identityProvider.currentUser?.id ?: UNKNOWN_PERSON_ID
        override fun <T : Any?> provideUser(ctx: GeneratorContext<*, *, T>): Field<T>? {
            return ctx.field()?.let { field ->
                when (val fieldType = field.dataType.type) {
                    Int::class.javaObjectType -> DSL.`val`(auditorId) as Field<T>
                    else -> throw IllegalStateException("expected INT-type db field but got ${field.name} $fieldType")
                }
            }
        }
    }
}
```

### jOOQ Version

Pro 3.17.6

### Database product and version

PostgreSQL 13.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit

### Java Version

openjdk 17

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.0

**Comment by lukaseder** [comment] 2023-02-28 18:58
Thanks a lot for your detailed report. I will look into this soon.

**Comment by lukaseder** [comment] 2023-03-07 07:48
Looking into this now. Could there be the problem that the audit timestamp `forcedType` is simply ignored because another `forcedType` matches first?

```
                            forcedType {
                                name = "INSTANT"
                                includeTypes = '''
                                      TIMESTAMPTZ
                                    | TIMESTAMP
                                '''
                            }
                            forcedType {
                                auditInsertTimestamp = true
                                name = "timestamptz"
                                includeExpression = "created"
                            }
```

Not sure if this is the exact configuration or a simplified one, given the upper case `TIMESTAMPTZ` type reference, which might not match anything in PostgreSQL.

The code generator doesn't merge forcedType configurations. It just applies the first one that matches per column, and ignores the rest, per column.

You can check this in various ways:

- Unused forced type configurations should produce a warning in code generation output
- If the forced type with audit timestamp is applied correctly, you should see an `AuditGenerator` on the generated column

In case that's not it, I might need a bit more information on how to reproduce this issue:

- Can you confirm the code is generated correctly?
- How do you run the failing `INSERT` / `UPDATE` statements, including relevant `Settings` / `Configuration`?

I know it might look like a bit of extra effort, but with the MCVE template, it's often much easier to create an exact reproducer that takes into account all the relevant details for reproduction of a bug: https://github.com/jOOQ/jOOQ-mcve. If it's not easy to reproduce with the template, that's fine, too, we'll figure it out.

**Comment by cmrgKoradir** [comment] 2023-03-08 22:01
> Not sure if this is the exact configuration

Yes, it is.

> the upper case TIMESTAMPTZ type reference, which might not match anything in PostgreSQL

No, no, it matches, because without it, we get `java.time.LocalDateTime` in our records instead of the `java.time.Instant` that we want.

> The code generator doesn't merge forcedType configurations. It just applies the first one that matches per column, and ignores the rest, per column.

Hm ... I think you're onto something ...

If I switch the forced types s.t. the audit columns are before the general timestamps, i.e.

```groovy
forcedTypes {
    forcedType {
        auditInsertTimestamp = true
        name = "timestamptz"
        includeExpression = "created"
    }
    forcedType {
        auditInsertTimestamp = true
        auditUpdateTimestamp = true
        name = "timestamptz"
        includeExpression = "last_modification"
    }
    forcedType {
        name = "INSTANT"
        includeTypes = '''
              TIMESTAMPTZ
            | TIMESTAMP
        '''
    }
    forcedType {
        auditInsertUser = true
        name = "int"
        includeExpression = "created_by_id"
    }
    forcedType {
        auditInsertUser = true
        auditUpdateUser = true
        name = "int"
        includeExpression = "modified_by_id"
    }
}
```

then all the timestamps on our records are being replaced, e.g.

```java
-    public final TableField<VersionRecord, Instant> LAST_MODIFICATION = createField(DSL.name("last_modification"), SQLDataType.INSTANT.nullable(false).defaultValue(DSL.field("now()", SQLDataType.INSTANT)), this, "");
+    public final TableField<VersionRecord, OffsetDateTime> LAST_MODIFICATION = createField(DSL.name("last_modification"), SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false).stored().defaultValue(DSL.field("now()", SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new org.jooq.impl.AuditGenerator<>(org.jooq.AuditType.TIMESTAMP, org.jooq.GeneratorStatementType.INSERT, org.jooq.GeneratorStatementType.UPDATE));
```

And I'm strongly expecting that this `new org.jooq.impl.AuditGenerator<>(org.jooq.AuditType.TIMESTAMP, org.jooq.GeneratorStatementType.INSERT, org.jooq.GeneratorStatementType.UPDATE)` is what we want to be there...

I do notice we lost the conversion of `OffsetDateTime` to `Instant`, so I suppose what we really want is

```groovy
forcedTypes {
    forcedType {
        auditInsertTimestamp = true
        name = "INSTANT"
        includeTypes = '''
              TIMESTAMPTZ
            | TIMESTAMP
        '''
        includeExpression = "created"
    }
    forcedType {
        auditInsertTimestamp = true
        auditUpdateTimestamp = true
        name = "INSTANT"
        includeTypes = '''
              TIMESTAMPTZ
            | TIMESTAMP
        '''
        includeExpression = "last_modification"
    }
    forcedType {
        name = "INSTANT"
        includeTypes = '''
              TIMESTAMPTZ
            | TIMESTAMP
        '''
    }
    forcedType {
        auditInsertUser = true
        name = "int"
        includeExpression = "created_by_id"
    }
    forcedType {
        auditInsertUser = true
        auditUpdateUser = true
        name = "int"
        includeExpression = "modified_by_id"
    }
}
```

which gives us

```java
public final TableField<VersionRecord, Instant> LAST_MODIFICATION = createField(DSL.name("last_modification"), SQLDataType.INSTANT.stored().defaultValue(DSL.field("now()", SQLDataType.INSTANT)), this, "", new org.jooq.impl.AuditGenerator<>(org.jooq.AuditType.TIMESTAMP, org.jooq.GeneratorStatementType.INSERT, org.jooq.GeneratorStatementType.UPDATE));
```

And that seems to finally do the trick. Thanks a lot. :upside_down_face: 

... aaaaand it refuses to work in some of our integration tests. :joy: 

Will have a look at why exactly later. It feels like it should be a user issue, rather than a jOOQ issue, but I'll keep you posted.

**Comment by cmrgKoradir** [comment] 2023-03-09 10:09
Turns out postgres uses the same `current_timestamp` throughout a transaction.

In the actual application, creation and modification are two transactions, so two different timestamps.

In our tests, we only have one transaction, so the modification timestamp does not differ from the creation timestamp.

We now test it like 

```kotlin
softly {
    assertThat(auditInfoAfterModification.createdBy).isEqualTo(creator)
    assertThat(auditInfoAfterModification.lastModifiedBy).isEqualTo(modifier)
    assertThat(auditInfoAfterModification.createdAt).isEqualTo(timeOfCreation)
    // postgres 'current_timestamp' does not change within the same transaction (cf. "Special values" on https://www.postgresql.org/docs/current/datatype-datetime.html )
    assertThat(updateQuery).contains("\"last_modification\" = cast(current_timestamp as timestamp with time zone)")
}
```

and that passes, even if it is a bit ugly.

Please let us know, if you know a nicer way of testing this. :sweat_smile:

**Comment by lukaseder** [comment] 2023-03-09 10:28
I'm glad to hear that you've been able to sort out the code generation issue. Unless I'm overlooking something, I can close this issue?

Can your test emulate the actual behaviour with 2 transactions? It's probably a better test that way. Other transaction specific things mmight play a role as well, if you're putting everything into a single transaction.

Other than that, there's always `statement_timestamp()`, see https://www.postgresql.org/docs/current/functions-datetime.html

**Closed by lukaseder** 2023-03-09 10:28 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Feedback Pending, E: Professional Edition, E: Enterprise Edition

**Comment by cmrgKoradir** [comment] 2023-03-09 10:43
Thank you, I'll have a look at those.

Yes, I think we can close this.

I do have a different question concerning the audit columns, but I'll open a new thread for that. :upside_down_face:
