### ISSUE TITLE
Feature request: returning typed Record after join without custom RecordMapper

### ISSUE THREAD

**Issue by ciaccia** [jOOQ/jOOQ#7003] opened 2018-01-05 13:14 UTC
Hi Lukas,
This is not a bug rather a feature request.

There are some situations where we must join two tables to get the desired result (i.e. SQL `exists` is not enough) but we are interested in the data coming from the first table only.  When a join is involved, jOOQ currently returns generic `Record` losing the typed record unless a RecordMapper is provided.

For example consider the following (postgres) schema:

```SQL
DROP TABLE IF EXISTS person_group;
DROP TABLE IF EXISTS person;

create table person
(
    id bigserial NOT NULL PRIMARY KEY,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL,
    UNIQUE (email)
);

create table person_group
(
    person_id bigint NOT NULL REFERENCES person(id),
    pos int NOT NULL,
    group_name text,
    UNIQUE (pos, group_name)
);

insert into person(id, first_name, last_name, email)
values (NEXTVAL('person_id_seq'), 'John', 'Doe', 'john.doe@example.com'),
    (NEXTVAL('person_id_seq'), 'Maria', 'Bernasconi', 'maria.bernasconi@example.com'),
    (NEXTVAL('person_id_seq'), 'Philipp', 'Muster', 'philipp.muster@example.com');

insert into person_group(person_id, pos, group_name)
VALUES ((select id from person where email = 'john.doe@example.com'), 0, 'a'),
    ((select id from person where email = 'maria.bernasconi@example.com'), 1, 'a'),
    ((select id from person where email = 'philipp.muster@example.com'), 2, 'a'),
    ((select id from person where email = 'john.doe@example.com'), 2, 'b'),
    ((select id from person where email = 'maria.bernasconi@example.com'), 1, 'b'),
    ((select id from person where email = 'philipp.muster@example.com'), 0, 'b');
```

Here we have a table containing people and a second table containing information about groups (à la MTM). With the following query it is possible to obtain all the people belonging to group "b" in an ordered way:

```SQL
select p.*
from person p
join person_group g on p.id = g.person_id
where g.group_name = 'b'
order by g.pos asc;
```

Note: to my knowledge it is not possible to rewrite the above query without the join, because of the `order by`.

In order to express the following query in jOOQ, we must write something like:
```java
List<PersonRecord> people = dslCtx.select()
    .from(PERSON)
    .join(PERSON_GROUP).on(PERSON.ID.eq(PERSON_GROUP.PERSON_ID))
    .where(PERSON_GROUP.GROUP_NAME.eq("b"))
    .orderBy(PERSON_GROUP.POS.asc())
    .fetch(r -> new PersonRecord(r.get(PERSON.ID), r.get(PERSON.FIRST_NAME), r.get(PERSON.LAST_NAME), r.get(PERSON.EMAIL)));
```

I believe the `RecordMapper<? super Record, PersonRecord>` passed in the `fetch` method is not nice and error prone, and it should be avoided whenever possible. Ideally either the first `select` or the last `fetch` should accept a `Table<R>` and return something like `List<R>`.

I don't know if this is feasible and/or if the generator must be changed to support this, but this feature would make this use case lots nicer. 😀

**Comment by lukaseder** [comment] 2018-01-05 13:25
This is a duplicate of #6541

Note, you can replace your explicit mapping by this:

```java
    .fetchInto(PERSON);
```

**Closed by lukaseder** 2018-01-05 13:25 UTC
Labels: C: Functionality, P: Medium, T: Enhancement
