### ISSUE TITLE
AlterSequenceStep#restart() should consider Sequence#getStartWith()

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9466] opened 2019-10-30 10:31 UTC
The `ALTER SEQUENCE ... RESTART` clause (see `AlterSequenceStep#restart()`) is currently being emulated for some commercial editions, by translating it to a `ALTER SEQUENCE ... RESTART WITH 1`. This is however not correct if the sequence was created with a `START WITH` clause with a value different from `1`.

**Comment by lukaseder** [comment] 2019-10-30 10:42
Duplicate of https://github.com/jOOQ/jOOQ/issues/9438

**Closed by lukaseder** 2019-10-30 10:42 UTC
Labels: C: DB: Hana, C: DB: Informix, C: DB: Vertica, C: Functionality, E: Enterprise Edition, E: Professional Edition, P: Medium, T: Enhancement
