### ISSUE TITLE
Unable to bind postgres hstore data type

### ISSUE THREAD

**Issue by mjburghoffer** [jOOQ/jOOQ#5363] opened 2016-06-28 19:29 UTC
When you query `information_schema.columns` for the `data_type` of a given column, postgres returns `USER-DEFINED` rather than something useful like `hstore`.  There is another column, `udt_name`, which returns the very-useful `hstore` string we are looking for.  Perhaps the introspection query can query that column in addition to `data_type`?

**Comment by lukaseder** [comment] 2016-06-29 12:34
Thank you very much for your questions. I'm sorry, I'm not sure if this is just a question about how jOOQ-meta does things, or if you're reporting an issue. Is there an actual problem?

**Comment by mjburghoffer** [comment] 2016-06-29 21:32
Reporting an issue.  There is no way to define a custom type binding based off the reported data type - need to bind the type based on the column + table name instead, which is a little inconvenient.

**Comment by lukaseder** [comment] 2016-07-01 12:40
Aha, I see, thanks for clarifying. Yes, indeed, there are a couple of inconveniences in that area. Will look into what's possible for PostgreSQL...

**Comment by lukaseder** [comment] 2017-05-22 16:02
Duplicate of https://github.com/jOOQ/jOOQ/issues/5872

**Closed by lukaseder** 2017-05-22 16:02 UTC
Labels: C: Code Generation, C: DB: PostgreSQL, P: Medium, T: Defect
