### ISSUE TITLE
MULTISET nested projection's ContextConverters don't receive correct ConverterContext

### ISSUE THREAD

**Issue by eralmansouri** [jOOQ/jOOQ#16655] opened 2024-05-07 01:24 UTC
### Expected behavior

I'm using JOOQ with Spring Boot and I initialize the Configuration with some data. eg:
```java
@Bean
DefaultConfigurationCustomizer jooqConfigCustomize() {
    return configuration -> {
        configuration.data("KEY_FOR_DATA", new ExampleDecryptor(key));
    };
}
```

I would expect this configuration data to be present in all areas that I try to read from config at any stage of a select query.

### Actual behavior

I have a ContextConverter that uses that data by reading it from ctx.configuration() as [described here](https://www.jooq.org/doc/latest/manual/sql-execution/fetching/context-converter/).

```java
@Slf4j
public class ExampleDecryptor<J, U> extends AbstractContextConverter<J, U> {
    public static final String CONTEXT_KEY = "KEY_FOR_DATA";

    private Object readFromCtx(ConverterContext ctx) {
        return ctx.configuration().data(CONTEXT_KEY);
    }

    // ... other code
}
```

The issue is, if I use a multiset query, the sub-select statement uses DSL.select() once more with the default configuration and I lose access to that data during conversion, preventing my access to that data. **Even more, because it reverts back to default configuration, I am struggling to even override the providers**.

### Steps to reproduce the problem

As an example, let's say I have this query. 
```
dsl.select(USER, USER.profile().PICTURE, USER.profile().JOB_RESUME,
      dsl.select(JOB_APPLICATION)
          .from(JOB_APPLICATION)
          .where(USER.ID.eq(JOB_APPLICATION.APPLICANT_ID))
          .asMultiset()
          .convertFrom(r -> r.map(mapping(JobApplicationImpl::new)))
  )
  .from(USER)
  .where(USER.ID.eq(userId))
```

The converter example above will have the data it needs from configuration() while converting the user fields or picture but will fail during conversion of job application fields due to reverting to Jooq's default configuration.

### jOOQ Version

3.19.8

### Database product and version

PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

### Java Version

21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.1

**Comment by lukaseder** [comment] 2024-05-07 06:22
Thank you very much for your report. I'll look into this soon.

**Comment by lukaseder** [comment] 2024-06-10 10:46
Looking into this now. As I suspected in https://github.com/jOOQ/jOOQ/pull/16660#issuecomment-2098786217, this does not have anything to do with a transient `QueryPart` that is being used for rendering the SQL having the correct `Configuration` attached to it or not (this may be relevant when bind values are present, which they aren't in your case, but even then, the suggested solution would unlikely be the right fix, we're using unattached `Select` objects all over the code base).

Instead, a test like this, which reproduces the problem (I think? Because you didn't provide a complete reproducer, so it might be a different problem):

```java
    public void testMultisetProjectionContextConverter() throws Exception {
        testMultisetEmulations(ctx -> {
            ctx.configuration().data("x", "y");

            class CC extends AbstractContextConverter<Integer, String> {

                public CC() {
                    super(Integer.class, String.class);
                }

                @Override
                public String from(Integer t, ConverterContext c) {

                    return t == null ? (String) c.configuration().data("x") : t.toString();
                }

                @Override
                public Integer to(String u, ConverterContext c) {
                    return u == null || u.equals(c.configuration().data("x")) ? null : Ints.tryParse(u);
                }
            }

            DataType<String> t = INTEGER.asConvertedDataType(new CC());
            Select<Record3<String, String, String>> s = select(val(null, t), val("y", t), val("1", t));

            testMultisetProjectionContextConverter0(ctx.fetch(s));
            testMultisetProjectionContextConverter0(ctx.fetchValue(multiset(s)));
        });
    }
```

It shows that this particular call here doesn't have any `Context` information available, and thus no `Configuration.data()` content, when reading data from a `ResultSet`:

```
java.lang.Throwable
	at org.jooq.test.all.testcases.MultisetTests$1CC.from(MultisetTests.java:956)
	at org.jooq.test.all.testcases.MultisetTests$1CC.from(MultisetTests.java:1)
	at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:319)
	at org.jooq.impl.Tools.setValue(Tools.java:3736)
	at org.jooq.impl.DefaultRecordUnmapper$IterableUnmapper.unmap(DefaultRecordUnmapper.java:175)
	at org.jooq.impl.DefaultRecordUnmapper.unmap(DefaultRecordUnmapper.java:111)
	at org.jooq.impl.AbstractRecord.from0(AbstractRecord.java:787)
	at org.jooq.impl.AbstractRecord.from(AbstractRecord.java:835)
	at org.jooq.impl.JSONReader.lambda$1(JSONReader.java:222)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.JSONReader.read(JSONReader.java:221)
	at org.jooq.impl.JSONReader.read(JSONReader.java:123)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultisetJSON(DefaultBinding.java:4468)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.lambda$2(DefaultBinding.java:4435)
	at org.jooq.impl.Tools.apply(Tools.java:2332)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:4433)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:4396)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:4389)
	at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1143)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1562)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1503)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1379)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1355)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:164)
	at org.jooq.impl.Tools.fetchOne(Tools.java:2906)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
	at org.jooq.impl.Tools.attach(Tools.java:1677)
	at org.jooq.impl.DefaultDSLContext.fetchOne(DefaultDSLContext.java:5019)
	at org.jooq.impl.DefaultDSLContext.lambda$61(DefaultDSLContext.java:5039)
	at org.jooq.impl.Tools.attach(Tools.java:1677)
	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:5039)
	at org.jooq.impl.DefaultDSLContext.fetchValue(DefaultDSLContext.java:5058)
	at org.jooq.test.all.testcases.MultisetTests.lambda$98(MultisetTests.java:970)
	at org.jooq.test.util.BaseTest.qomAssertions(BaseTest.java:780)
	at org.jooq.test.all.testcases.MultisetTests.lambda$97(MultisetTests.java:945)
	at org.jooq.test.all.testcases.MultisetTests.lambda$545(MultisetTests.java:3647)
	at org.jooq.test.all.testcases.MultisetTests.lambda$548(MultisetTests.java:3666)
	at org.jooq.test.all.testcases.MultisetTests.testRecordLevelListenerResults(MultisetTests.java:3702)
	at org.jooq.test.all.testcases.MultisetTests.testRecordLevelListenerResults(MultisetTests.java:3688)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetEmulations(MultisetTests.java:3666)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetEmulations(MultisetTests.java:3647)
	at org.jooq.test.all.testcases.MultisetTests.testMultisetProjectionContextConverter(MultisetTests.java:943)
	at org.jooq.test.jOOQAbstractTest.testMultisetProjectionContextConverter(jOOQAbstractTest.java:6322)
```

The problematic line is here:

```
	at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:319)
```

The line being:

```java
        // [#3200] Try to convert arbitrary objects to T
        else
            return ((ContextConverter<T, U>) getConverter()).from(delegate.convert(object), converterContext());
```

`Internal.converterContext()` doesn't reference your `Configuration`.

I'll check to see how this could be solved. I simple (but temporary) fix could be to use a `ThreadLocal` to store the `ConverterContext` for all of the deserialisation.

Or, we avoid calling `DataType.convert()` at:

```
	at org.jooq.impl.Tools.setValue(Tools.java:3736)
```

**Comment by lukaseder** [comment] 2024-06-10 10:49
We can't use the `Record.configuration()`, because there's a (slight) risk of `Settings.attachRecords == false`

**Comment by lukaseder** [comment] 2024-06-10 10:54
Yeah, I don't think the `ThreadLocal` approach will be the right solution here, as it just provides a hack to work around a bad status quo. The *real* problem is the `DataType.convert()` method, which has been obsolete for a long time and should be deprecated:

- https://github.com/jOOQ/jOOQ/issues/16810

Plus, our internals should avoid calling the method.

**Comment by lukaseder** [comment] 2024-06-10 11:37
Fixed in versions:

- 3.20.0
- 3.19.10 (https://github.com/jOOQ/jOOQ/issues/16811)
- 3.18.17 (https://github.com/jOOQ/jOOQ/issues/16812)
- 3.17.26 (https://github.com/jOOQ/jOOQ/issues/16813)

@eralmansouri, since there wasn't a reproducer in your issue description, I'm not 100% certain that I've fixed *your* issue. I did fix what I believe to be your issue. Do you have time to confirm the fix against a snapshot build on your end?

If you're licensed, you can download snapshot builds from here: https://www.jooq.org/download/versions

If not, then you could build a snapshot build from github.

**Closed by lukaseder** 2024-06-10 11:37 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by eralmansouri** [comment] 2024-08-05 19:31
Sorry for the super late reply here but yes the same code is working on 3.19.10 with no issue. 

Thank you!
