### ISSUE TITLE
Using id with returningResult and fetchOne results in exception

### ISSUE THREAD

**Issue by piotrponikowski** [jOOQ/jOOQ#8039] opened 2018-11-12 13:25 UTC
### Expected behavior and actual behavior:

I am using insert with returningResult option and returning single column as a result.
When executing fetchOne, ClassCastException is thrown: "java.lang.ClassCastException: my.package.TmUserRecord cannot be cast to org.jooq.Record1". Class TmUserRecord inherits from Record5.

When I change fetchOne to fetch, then Record1 is correctly returned without any exceptions.

Additionals notes: when I return column other than id, then there is also no issues (Record1 returned instead Record5). It looks like this can be reproduced only when using id in returningResult + fetchOne.

I expected that Record1 is returned instead Record5 when only one column is used in returningResult.

### Steps to reproduce the problem (include example code if possible):

```
//this works
Result<Record1<Integer>> result1 = dsl.insertInto(TM_USER)
	.columns(TM_USER.FIRST_NAME, TM_USER.LAST_NAME, TM_USER.LOGIN, TM_USER.PASSWORD)
	.values("Name", "Surname", "login", "password")
	.returningResult(TM_USER.ID)
	.fetch();

//this one throws java.lang.ClassCastException: my.package.TmUserRecord cannot be cast to org.jooq.Record1
//my.package.TmUserRecord inherits from org.jooq.Record5
//code compiles without any issues
Record1<Integer> result2 = dsl.insertInto(TM_USER)
	.columns(TM_USER.FIRST_NAME, TM_USER.LAST_NAME, TM_USER.LOGIN, TM_USER.PASSWORD)
	.values("Name", "Surname", "login", "password")
	.returningResult(TM_USER.ID)
	.fetchOne();
```

### Versions:

- jOOQ: 3.11.6
- Java: 1.8
- Database (include vendor): MySql 5.7.18
- OS: Windows
- JDBC Driver: mysql-connector-java onnector-java 8.0.13

**Comment by lukaseder** [comment] 2020-01-15 15:47
Closing this, as I could not reproduce this issue when it was reported.

Feel free to reopen if the issue persists.

**Closed by lukaseder** 2020-01-15 15:47 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Worksforme, T: Defect
