### ISSUE TITLE
ClassCastException during invocation of double-wrapped ConvertedDataType

### ISSUE THREAD

**Issue by Spikhalskiy** [jOOQ/jOOQ#16013] opened 2024-01-05 14:48 UTC
### Expected behavior

If the creation of "double-wrapped" converters is not supported, an exception with a clear reason should be thrown during the creation time.

### Actual behavior

With the following definition

```
class GeometryCoordinateConverter : Converter<Geometry, Coordinate>

    val COORDINATE_GEOMETRY: DataType<Coordinate> = SQLDataType.GEOMETRY.asConvertedDataType(GeometryCoordinateConverter())
    val GEOMETRY_COORDINATE: DataType<Geometry> = COORDINATE_GEOMETRY.asConvertedDataType(GeometryCoordinateConverter().inverse())
```

Invocation `GEOMETRY_COORDINATE.convert(coordinate)` causes 

```
java.lang.ClassCastException: class Coordinate cannot be cast to class org.jooq.Geometry (Coordinate and org.jooq.Geometry are in unnamed module of loader 'app')
	at GeometryCoordinateConverter.from(GeometryCoordinateConverter.kt:19)
	at org.jooq.ContextConverter$1.from(ContextConverter.java:131)
	at org.jooq.Converters.from(Converters.java:202)
	at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:312)
```

### jOOQ Version

3.19.1

### Database product and version

PostgreSQL 15

**Comment by lukaseder** [comment] 2024-01-05 14:52
Thanks for your report. I don't see anything wrong with that usage, so it's just a bug, not a wrong exception.

Can you please show the complete stack trace, and some example code to reproduce it?

**Comment by Spikhalskiy** [comment] 2024-01-05 14:53
I would appreciate advice on how to create a GEOMETRY_COORDINATE binding correctly. 

Context:

The following code in our project: `DSL.stContains(regionPolygon.cast(Geometry::class.java), DSL.coerce(coordinate, Geometry::class.java))`
started to log

```
Static type registry     : The deprecated static type registry was being accessed for a non-built-in data type: geometry /* Coordinate */. It is strongly recommended not looking up DataType<T> references from Class<T> references by relying on the internal static type registry. See https://github.com/jOOQ/jOOQ/issues/15286 for details.
org.jooq.impl.DefaultDataType$DiscouragedStaticTypeRegistryUsage: null
	at org.jooq.impl.DefaultDataType.check(DefaultDataType.java:842)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:835)
	at org.jooq.impl.DSL.getDataType0(DSL.java:35535)
	at org.jooq.impl.DSL.val0(DSL.java:33195)
	at org.jooq.impl.Tools.lambda$field$51(Tools.java:2097)
	at org.jooq.impl.Tools.field(Tools.java:2092)
	at org.jooq.impl.Tools.field(Tools.java:2097)
	at org.jooq.impl.DSL.coerce(DSL.java:17177)
```

and I'm trying to migrate it to something like

```
DSL.stContains(
            regionPolygon.cast(Geometry::class.java),
            JooqTypes.GEOMETRY_COORDINATE.convert(coordinate),
        )
```

but having a hard time creating the right binding.

**Comment by lukaseder** [comment] 2024-01-05 15:03
I'll be happy to help but I need the complete context. I don't know what you're trying to do here. What's `regionTableField`, for example? Can you provide the DDL, any relevant code generation configuration, the complete `GeometryCoordinateConverter` class, etc.

Also, you didn't state if this is using the jOOQ Open Source Edition (without support for these types) or a commercial edition.

**Comment by Spikhalskiy** [comment] 2024-01-05 15:15
> Also, you didn't state if this is using the jOOQ Open Source Edition (without support for these types) or a commercial edition.

We use commercial edition and the code above (before my attempted migration) actually works in production.

> Can you provide the DDL, any relevant code generation configuration, the complete GeometryCoordinateConverter class, etc.

Sorry, I'm not comfortable sharing all of this from the closed-source project and I don't see how a converter implementation is relevant here for example. The exception doesn't come from the converter, but from jOOQ invoking the converter when configured this specific way. This converter is working as expected in production and converts Coordinate <-> Geometry.
You can find more context in this question I asked earlier where you helped me to implement the original version of the code: https://github.com/jOOQ/jOOQ/issues/15454#issuecomment-1671082940

> `regionTableField`

```
    /**
     * The column <code>cookin.availability_regions.region</code>.
     */
    val REGION: TableField<RegionsRecord, Polygon?> = createField(DSL.name("region"), SQLDataType.GEOMETRY.nullable(false), this, "", GeometryPolygonConverter())
```

**Comment by lukaseder** [comment] 2024-01-05 15:26
Thanks, for the additional information. I'll try reproducing this from the various bits and will get back if I can't.

**Comment by lukaseder** [comment] 2024-01-05 15:38
So, this appears to be a minimal reproducer (in Java):

```java
class Coordinate {}

Converter<Geometry, Coordinate> c = Converter.ofNullable(Geometry.class, Coordinate.class, x -> null, x -> null);
DataType<Coordinate> COORDINATE_GEOMETRY = SQLDataType.GEOMETRY.asConvertedDataType(c);
DataType<Geometry> GEOMETRY_COORDINATE = COORDINATE_GEOMETRY.asConvertedDataType(c.inverse());

System.out.println(DSL.stContains(
    DSL.field("test", SQLDataType.GEOMETRY).cast(Geometry.class),
    GEOMETRY_COORDINATE.convert(new Coordinate())
));
```

Producing:

```
Exception in thread "main" java.lang.ClassCastException: class org.jooq.testscripts.JDBC$1Coordinate cannot be cast to class org.jooq.Geometry (org.jooq.testscripts.JDBC$1Coordinate and org.jooq.Geometry are in unnamed module of loader 'app')
	at org.jooq.Converters.lambda$3(Converters.java:237)
	at org.jooq.Converter$1.from(Converter.java:181)
	at org.jooq.Converters.from(Converters.java:202)
	at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:312)
	at org.jooq.testscripts.JDBC.main(JDBC.java:45)
```

Can you confirm this corresponds to what you're doing?

For the record:

> Sorry, I'm not comfortable sharing all of this as-is from the closed-source project.

I just asked because there were missing bits in your report. I don't necessarily need *actual* code, I just need a minimal reproducer. Sometimes, with missing bits, I can go off chasing wrong assumptions (on my end) for hours...

**Comment by Spikhalskiy** [comment] 2024-01-05 15:42
> I just asked because there were missing bits in your report. I don't necessarily need actual code, I just need a minimal reproducer. Sometimes, with missing bits, I can go off chasing wrong assumptions (on my end) for hours...

I totally understand that you don't need our source code and just want to get a full picture to don't waste time on failing reproduction. I do my best to give all the important bits.

> Can you confirm this corresponds to what you're doing?

Your reproduction is quite accurate and close to what we are doing in the important parts, yes!

**Comment by Spikhalskiy** [comment] 2024-01-05 15:46
I'm looking at the structure of the datatype the code above produces and I'm not sure it's what I want to achieve.

![Screenshot 2024-01-05 at 10 35 42 AM](https://github.com/jOOQ/jOOQ/assets/532108/03ef54e7-55b3-4505-a4a4-8043cb4845f0)

So it actually creates a chained binding. When what I want to get is a simple one-step binding from Coordinate to Geometry. That's why I question if I use the right tool to create the desired result.

**Comment by lukaseder** [comment] 2024-01-05 15:46
Regarding:

> Context:
> 
> The following code in our project: `DSL.stContains(regionTableField.cast(Geometry::class.java), DSL.coerce(coordinate, Geometry::class.java))` began logging

The exception there indicates that a code path was chosen that relies on the very historic internal static type registry, which will, at some point in the far away future, be removed.

This is due to this usage of yours:

```kotlin
DSL.coerce(coordinate, Geometry.class)
```

Think about it this way, what should jOOQ do with this information? It can see a bind value of an unknown type `Coordinate`, which you expect jOOQ to automatically bind according to a previously class loaded converter for that type. But what if:

- The converter hasn't been loaded yet, for whatever race condition reason?
- There are multiple converters for the type, e.g. one for `Geometry`, one for `String`, etc.?

The `DSL.coerce()` method is static, and as such, has no way of accessing any jOOQ `Configuration` with its SPIs, and any possible way to configure such thing, so historically, there was simply one `Converter` that registered itself automatically, statically, and it won by accident.

Maybe, for a case like yours, this doesn't appear so risky, but what about cases where users register various `String -> String` converters (e.g. password hashing functions, etc.). How to pick the right one statically?

So, this exception tries to hint at API being used in the wrong way. The correct way would be:

```kotlin
DSL.val(coordinate, COORDINATE_GEOMETRY)
```

No need for coercion.

**Comment by lukaseder** [comment] 2024-01-05 15:46
> > Can you confirm this corresponds to what you're doing?
> 
> Your reproduction is quite accurate and close to what we are doing in the important parts, yes!

Thanks, I'll investigate this soon.

**Comment by lukaseder** [comment] 2024-01-05 15:54
> That's why I question if I use the right tool to create the desired result.

The problem stems from the fact that our DSL APIs only accept built-in data types, not user defined types for built-in functions. There's a discussion here about a potential (incompatible) fix for this, where we can pass around both `T` (built-in type) and `U` (user type) types throughout the API:

- https://github.com/jOOQ/jOOQ/issues/11088

Until that's happening, my intuition is for you to use `DSL.val(coordinate, COORDINATE_GEOMETRY).coerce(SQLDataType.GEOMETRY)`, or just unsafe cast in Kotlin, from `Field<Coordinate>` to `Field<Geometry>`.

I'll give you a more definitive answer next week, when I investigate the bug, when I can create better reproducers.

**Comment by Spikhalskiy** [comment] 2024-01-05 15:59
> Until that's happening, my intuition is for you to use DSL.val(coordinate, COORDINATE_GEOMETRY).coerce(SQLDataType.GEOMETRY)

This does work, thank you!

**Comment by lukaseder** [comment] 2024-10-16 08:21
This issue popped up again. Here's a workaround, where the second conversion happens on a nested record, rather than on the scalar value directly:

- https://github.com/jOOQ/jOOQ/issues/17428#issuecomment-2416066857

**Comment by lukaseder** [comment] 2024-10-16 09:56
Fixed in versions:

- 3.20.0
- 3.19.14 (https://github.com/jOOQ/jOOQ/issues/17442)
- 3.18.21 (https://github.com/jOOQ/jOOQ/issues/17443)
- 3.17.30 (https://github.com/jOOQ/jOOQ/issues/17444)

**Closed by lukaseder** 2024-10-16 09:56 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
