### ISSUE TITLE
Code generation fails to parse H2 GEOMETRY type if constraints are specified

### ISSUE THREAD

**Issue by taven** [jOOQ/jOOQ#10177] opened 2020-05-07 13:34 UTC
H2 has the GEOMETRY data type which has an optional constraint on the type of geometry to store.
The code generation can successfully parse this data type if no constraints are specified. If a constraint is specified e.g GEOMETRY(POINT) then parsing fails with the exception:

> org.jooq.impl.ParserException: Token ')' expected: [20:65] ... GEOMETRY[*](POINT)
> at org.jooq.impl.ParserContext.expected(ParserImpl.java:11088)
> at org.jooq.impl.ParserImpl.parse(ParserImpl.java:10530)
> at org.jooq.impl.ParserImpl.parse(ParserImpl.java:10525)
> at org.jooq.impl.ParserImpl.parseCreateTable(ParserImpl.java:3361)

Found using jooq-3.13.2

**Comment by katzyn** [comment] 2020-05-07 15:45
H2 uses definition mostly compatible with PostGIS.

**Comment by lukaseder** [comment] 2020-05-07 15:52
Thanks a lot for your report.

We currently do not support the various vendor's GIS extensions: #982. We definitely want to support them in the future, but this is a bigger project than merely supporting them in the parser.

I'm closing this as a duplicate of #982

**Closed by lukaseder** 2020-05-07 15:52 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Duplicate, T: Enhancement
