### ISSUE TITLE
Add support for MySQL COMMENT syntax in DDLDatabase's CREATE TABLE statements

### ISSUE THREAD

**Issue by tarunjainsagar** [jOOQ/jOOQ#12779] opened 2022-01-03 10:28 UTC
### Issue:
I wish to generate comments for table and columns during code generation for java.
Currently, the generated comments are empty.
Please share one example for each:

1. Generate Comments for Table
2. Generate Comments for Column

### Expected behavior for table
```
private Zones(Name alias, Table<ZonesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Zones Table"), TableOptions.table());
    }

```
### Actual behavior for table
```
private Zones(Name alias, Table<ZonesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

```

### Expected behavior for column
```
public final TableField<ZonesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "DIMENSION");
```

### Actual behavior for column
```
public final TableField<ZonesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");
```

### Steps to reproduce the problem

1. Setup configuration as shown below.
2. Add DDL command with separate comments for table and column.
3. Compile code.
4. Check generated POJOs, comments are empty

### Configuration
```
<plugin>
                <groupId>org.jooq.pro-java-11</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>3.15.5</version>
                <executions>
                    <execution>
                        <id>generate-model</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <generator>
                                <database>
                                    <name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
                                    <properties>
                                        <property>
                                            <key>scripts</key>
                                            <value>src/main/resources/db/domain/*.sql</value>
                                        </property>
                                    </properties>
                                </database>
                                <target>
                                    <packageName>com.bizom.jooq</packageName>
                                    <directory>${project.build.directory}/generated-sources</directory>
                                </target>
                            </generator>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

### DDL Statement

```sql
CREATE TABLE `zones` (
  `id` int(11) NOT NULL COMMENT 'DIMENSION'
) COMMENT 'Zones Table' ;
```

### Related Feature Ticket
Generate comments also on POJOs - https://github.com/jOOQ/jOOQ/issues/6456

### Versions

- jOOQ: **3.15.5 (pro - edition)**
- Java: 11
- Database (include vendor): mysql 5.7
- OS: ubuntu 20.04
- JDBC Driver (include name if inofficial driver): com.mysql.cj.jdbc.Driver

**Comment by lukaseder** [comment] 2022-01-03 15:00
Thanks a lot for your report.

The `DDLDatabase` currently translates all incoming SQL to H2 and runs that against an in-memory H2 database. We currently don't emulate the MySQL `CREATE TABLE .. COMMENT` syntax in other dialects.

There are numerous open issues that will improve this situation, including:

- Stop translating to H2 and start interpreting the DDL ourselves
- Better manage compound statement emulations

While this issue is a duplicate of a few other issues, I'll keep it open as a reminder to check this works eventually.

**Comment by tarunjainsagar** [comment] 2022-01-04 07:31
Thanks for the response.

Can you suggest the alternatives to achieve the same ?
We need this on urgent basis.

jOOQ Version: **3.15.5 (pro - edition)**

**Comment by lukaseder** [comment] 2022-01-04 07:54
The `DDLDatabase` is always just an approximation of the actual dialect. It will always have such edge case limitations. Why not try working with an actual `MySQLDatabase` instead? You can even spin up one just for code generation purposes using testcontainers: https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

**Comment by tarunjainsagar** [comment] 2022-01-04 08:04
Can you please share the exact configuration for using actual `MySQLDatabase` ?

**Comment by lukaseder** [comment] 2022-01-04 08:09
> Can you please share the exact configuration for using actual `MySQLDatabase` ?

What exactly are you looking for? A quick fix? This isn't a quick fix suggestion, I'm suggesting that instead of using the `DDLDatabase` (which parses your SQL, translates it to H2, runs it on H2, and reverse engineers the resulting H2 schema), you use the `MySQLDatabase` instead (which connects to an actual MySQL database, and reverse engineers that).

It's just an ordinary code generation configuration, as documented throughout the manual, e.g.:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-configuration/

**Comment by katzyn** [comment] 2022-01-05 14:48
H2 also supports this syntax for comments:
https://h2database.com/html/grammar.html#column_definition

**Comment by lukaseder** [comment] 2022-01-05 15:07
In any case, the jOOQ API currently can't represent the DDL `COMMENT` clause, we're just parsing and discarding it for now.

**Comment by katzyn** [comment] 2022-01-05 15:19
Table comments can be specified with undocumented and therefore unsupported `COMMENT IS …` clause after name of the table in its definition, or with separate documented `COMMENT ON TABLE …` command:
https://h2database.com/html/commands.html#comment_on
Maybe this clause should become documented and supported. But in many cases vendor-specific clauses and commands have significant design flaws.

**Comment by lukaseder** [comment] 2022-01-05 15:29
> or with separate documented `COMMENT ON TABLE …` command:

Sure, and we support that. But jOOQ currently doesn't handle compound DDL statements too well (create the table *and then* append a column)

**Comment by lukaseder** [comment] 2022-02-02 09:44
Another workaround could be to use the synthetic comments feature of the code generator to translate SQL comments to generated comments: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-comments/

**Comment by lukaseder** [comment] 2022-02-07 09:58
The implementation will share code with a new API that is documented here: https://github.com/jOOQ/jOOQ/issues/13000. `Query.decompose()` will allow for decomposing arbitrary compound DDL statements into their individual parts. The feature set is part of a bigger task: https://github.com/jOOQ/jOOQ/issues/9645

**Comment by lukaseder** [comment] 2022-02-07 10:01
Alternatively, I could increase the priority of https://github.com/jOOQ/jOOQ/issues/7034, which removes H2 from the equation. We can already interpret the `COMMENT` syntax ourselves, so if we hadn't translated everything to H2 for DDL simulation, then this would not be an issue. Might perhaps be a better approach to solving this.

**Comment by lukaseder** [comment] 2022-02-07 10:09
Both options #7034 and #13000 are viable, but #13000 is much easier to implement, whereas #7034 risks introducing a variety of regressions as our own interpreter might work subtly different from the current to-H2-translation mechanism, so users simply wanting support for the MySQL `COMMENT` syntax are better off with the #13000 approach.

**Comment by lukaseder** [comment] 2022-02-07 10:48
We need to implement the `QOM.CreateTable` and `QOM.AlterTable` query object model API first: https://github.com/jOOQ/jOOQ/issues/12772

**Comment by lukaseder** [comment] 2022-02-07 20:12
I've pushed a first implementation draft that supports interpreting the `COMMENT` syntaxes in `CREATE TABLE`. More preliminary work is needed in #12772 to support this also for `ALTER TABLE`. With the implementation via #13000, this is currently available to commercial jOOQ editions only. Once #7034 is implemented, it will be available to the jOOQ Open Source Edition as well.

**Comment by lukaseder** [comment] 2022-06-02 12:05
I'm postponing the `ALTER TABLE` implementation. I think that `COMMENT` support in `CREATE TABLE` is already quite useful.

**Closed by lukaseder** 2022-06-02 12:05 UTC
Labels: T: Enhancement, C: Code Generation, P: Medium, E: Professional Edition, E: Enterprise Edition
