### ISSUE TITLE
Update jooq-meta-extensions-hibernate to work with Hibernate6

### ISSUE THREAD

**Issue by kennymacleod** [jOOQ/jOOQ#16809] opened 2024-06-10 08:22 UTC
### Use case

The `JpaDatabase` codegen tool does not work with Hibernate 6, due to API changes between 5.6 and 6, some of which seem rather non-ovious.

### jOOQ Version

3.19 OS

### Database product and version

n/a

**Comment by lukaseder** [comment] 2024-06-10 08:38
Duplicate of https://github.com/jOOQ/jOOQ/issues/13721

**Closed by lukaseder** 2024-06-10 08:38 UTC
Labels: T: Enhancement, C: Code Generation, P: Medium, R: Duplicate, E: All Editions
