### ISSUE TITLE
Change PostgreSQL implementation of Field.sortAsc() to use ARRAY_POSITION() instead

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#13160] opened 2022-02-27 16:15 UTC
### Use case:

Ability to order by specific values. For example, I want to look up rows with ID 5,100, 3, 500, 200 and return them in that specific order.

### Possible solution you'd like to see:

Use Postgresql array_position() as discussed at https://stackoverflow.com/a/53453248/14731

### Possible workarounds:

Sort results in application code instead of in database.

### Versions:

- jOOQ: 3.16.4
- Java: 17
- Database (include vendor): Postgresql 14
- OS: Microsoft Windows [Version 10.0.19044.1566]
- JDBC Driver (include name if inofficial driver): PostgreSQL JDBC Driver 42.3.3

**Comment by cowwoc** [comment] 2022-02-27 17:37
Related issue: https://github.com/jOOQ/jOOQ/issues/5799

**Comment by cowwoc** [comment] 2022-02-27 18:01
I found another workaround, though I don't know the implications (performance or otherwise) of this approach versus `unnest()` and `array_position()`: https://stackoverflow.com/a/66560169/14731

**Comment by cowwoc** [comment] 2022-02-28 05:21
For what it's worth, in my case it was substantially faster to sort rows in the application than ask the database to do it. Retrieving and ordering 208k rows used to take a whopping 45 seconds. Moving ordering from the DB to the application reduced the time to 2.5 seconds. That's still longer than I'd like, but it's a huge step in the right direction.

**Comment by lukaseder** [comment] 2022-02-28 10:07
Thanks for your messages. I've changed the title of this issue to what I think you'd like to see here? There are multiple takes here to consider:

- We already have a `Field.sortAsc()` and related functionality that does the trick. I don't think a new API needs to be added, so this issue should be about improving the existing API and the SQL generated by it.
- There are obviously always means to improve existing generated SQL. Generated SQL being ugly isn't a good argument in favour or against some expression (you argue network I/O of transmitting generated SQL, others may argue readability), but performance surely is, though I'd like to see reproducible benchmarks to back claims. Some benchmarking techniques are shown here: https://www.jooq.org/benchmark. I believe to remember having seen some PostgreSQL committers on twitter confirming that the `DISTINCT` predicate doesn't behave like other operators in the parser, and as such might evade some index related ordering optimisations, so chances are, there are indeed better options
- Even if there's room for improvement here, there's always the option of bypassing out-of-the-box API via custom written dynamic SQL, and given that `ARRAY_POSITION()` isn't supported (yet), you can add support for it using plain SQL templating: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

**Comment by lukaseder** [comment] 2022-02-28 10:08
I forgot:

- Can you please show some examples of using `ARRAY_POSITION()`

**Comment by lukaseder** [comment] 2022-02-28 13:21
Here's a simple benchmark:

```sql
CREATE TABLE t (c integer);
INSERT INTO t SELECT * FROM generate_series(1, 100000) ORDER BY random();

DO $$
DECLARE
  v_ts TIMESTAMP;
  v_repeat CONSTANT INT := 25;
  rec RECORD;
BEGIN

  -- Repeat the whole benchmark several times to avoid warmup penalty
  FOR r IN 1..5 LOOP
    v_ts := clock_timestamp();

    FOR i IN 1..v_repeat LOOP
      FOR rec IN (
        SELECT *
        FROM t
        ORDER BY CASE 
          WHEN c IS NOT DISTINCT FROM 3 THEN 1
          WHEN c IS NOT DISTINCT FROM 10 THEN 2
          WHEN c IS NOT DISTINCT FROM 5 THEN 3
        END
      ) LOOP
        NULL;
      END LOOP;
    END LOOP;

    RAISE INFO 'Run %, Statement 1: %', r, (clock_timestamp() - v_ts);
    v_ts := clock_timestamp();

    FOR i IN 1..v_repeat LOOP
      FOR rec IN (
        SELECT *
        FROM t
        ORDER BY array_position(array[3, 10, 5], c)
      ) LOOP
        NULL;
      END LOOP;
    END LOOP;

    RAISE INFO 'Run %, Statement 2: %', r, (clock_timestamp() - v_ts);
    RAISE INFO '';
  END LOOP;
END$$;
```

The result doesn't confirm your hypothesis yet:

```
Run 1, Statement 1: 00:00:02.060765
Run 1, Statement 2: 00:00:01.65671

Run 2, Statement 1: 00:00:01.639422
Run 2, Statement 2: 00:00:01.92419

Run 3, Statement 1: 00:00:01.734562
Run 3, Statement 2: 00:00:01.639159

Run 4, Statement 1: 00:00:01.65366
Run 4, Statement 2: 00:00:01.788534

Run 5, Statement 1: 00:00:01.643491
Run 5, Statement 2: 00:00:01.797622
```

Even when I add an index:

```sql
CREATE INDEX i ON t (c);
```

The result is this:

```
Run 1, Statement 1: 00:00:01.758848
Run 1, Statement 2: 00:00:02.056828

Run 2, Statement 1: 00:00:01.713303
Run 2, Statement 2: 00:00:01.699209

Run 3, Statement 1: 00:00:01.575544
Run 3, Statement 2: 00:00:01.759337

Run 4, Statement 1: 00:00:01.797081
Run 4, Statement 2: 00:00:01.694133

Run 5, Statement 1: 00:00:01.583285
Run 5, Statement 2: 00:00:01.77107
```

So, I don't think it's reasonable to rush taking any action?

**Comment by cowwoc** [comment] 2022-02-28 17:58
@lukaseder I like the idea of keeping the existing API and improving the implementation under the hood.

With respect to performance, what I found interesting is that when the number of cases/indices was large (208k rows in my case) the performance difference between sorting in the DB vs application were huge. ~40 seconds when sorting in the DB versus 50ms when sorting in Java.

You are more knowledgeable with SQL than I am so I'm sure you'll find a way to close this gap, but I strongly suggest you benchmark using a large number of rows (e.g. 208k as I did). You'll only encounter a meaningful overhead if test against a large number of rows.

**Comment by lukaseder** [comment] 2022-02-28 18:29
I understand that 40 seconds is terrible for query execution. There's something really bad going on. But the important thing here (and always with SQL performance) is to not jump to conclusions but do a root cause analysis instead. I have shown with a simple benchmark that the difference can't be as "obvious" as you seemed to have suggested. You can try to reproduce the issue. I've repeated it with 1M rows getting these times (though on a different, faster computer now):

```
Run 1, Statement 1: 00:00:10.124976
Run 1, Statement 2: 00:00:10.712181

Run 2, Statement 1: 00:00:09.784853
Run 2, Statement 2: 00:00:10.682163

Run 3, Statement 1: 00:00:09.641516
Run 3, Statement 2: 00:00:10.556442

Run 4, Statement 1: 00:00:09.619456
Run 4, Statement 2: 00:00:10.533981

Run 5, Statement 1: 00:00:09.618228
Run 5, Statement 2: 00:00:10.58082
```

Still no difference. In fact, there's even a slight bias towards the `ARRAY_POSITION` being slower *in this particular case*, suggesting that your approach is worse than the existing one. But again, let's not jump to conclusions.

Maybe, you can tweak the benchmark in a way to show what the problem is in a reproducible way?

**Comment by lukaseder** [comment] 2022-02-28 18:34
Anyway. If you do experience a big improvement *in your case* with `ARRAY_POSITION`, then just use that instead:

```java
DSL.field("array_position({0}, {1})", SQLDataType.INTEGER, DSL.array(values), TABLE.COLUMN);
```

**Comment by cowwoc** [comment] 2022-02-28 18:37
@lukaseder Sorry if I wasn't clearer on this point earlier... I initially thought that `ARRAY_POSITION` would perform better than `ORDER BY CASE` but (to your point) I was wrong.

I am now saying that seeing as sorting in the database is so much slower than application-side sorting, it stands to reason that there must be a better way to do this. There should be some implementation that would achieve performance similar to that of application-side sorting.

**Comment by lukaseder** [comment] 2022-02-28 18:40
I see, thanks for clarifying. Well, you can always call `Result.sortAsc()` and pass a `Comparator`...? But if the database sucks at sorting things (and there can be many reasons) then jOOQ can't really help you much, or what did you have in mind, specifically?

**Comment by cowwoc** [comment] 2022-02-28 18:48
@lukaseder As you know, there are a million and one ways to solve a problem in SQL. I was wondering if you were familiar with a different way to solve this problem that might have better performance.

If `ORDER BY CASE`, `UNNEST` and `ARRAY_POSITION` are the only way and they all suck then I will happily do all sorting in the application. I just wanted to make sure I didn't miss any low-hanging fruit.

**Comment by lukaseder** [comment] 2022-02-28 18:55
> I was wondering if you were familiar with a different way to solve this problem that might have better performance.

Well, I'd have to see the specific query, table definitions, indexes, execution plans, etc. etc. It's a time consuming task, perhaps even related to a bug or flaw in PG. I wonder if it's worth investigating, especially since you've already found a better solution. I used to do this kind of consultancy in the past, but I hardly ever do it these days, as the focus has shifted towards maintaining jOOQ (which is mostly not about SQL performance, regrettably, the topic is very interesting). But I could recommend some consultancy agencies?

If I knew a very obvious better way than the status quo, then I'd have implemented it already. The speedup you experienced (45s down to 2.5s) is compelling. But I couldn't reproduce it yet, and don't see any reason other than an edge case or bug that makes the `CASE` statement that much slower than the `ARRAY_POSITION` function... `CASE` is O(N) at worst (with N = number of cases), but might have some optimisations. `ARRAY_POSITION` is pretty certainly O(N). At the same time, sorting is O(N log N) (with N = number of rows), unless you can extract the data from a pre-sorted index, so it's always a relatively heavy operation, especially if it triggers I/O.

**Comment by lukaseder** [comment] 2022-02-28 18:56
So, if you agree, I'm closing this issue as I can't see an obvious improvement in the suggested change (other than the subjective syntactic improvement, but there's always a regression risk, see e.g. https://github.com/jOOQ/jOOQ/issues/13085, so I'd rather not)

**Closed by lukaseder** 2022-02-28 18:56 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, R: Worksforme, E: All Editions

**Comment by cowwoc** [comment] 2022-02-28 18:58
Agreed. Thank you.
