### ISSUE TITLE
"Duplicate column name" in VALUES for MySQL

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8608] opened 2019-05-08 08:57 UTC
When translating a jOOQ statement like (taken from `org.jooq.test.MySQLTest.testMySQLYearType()` which currently fails):

```java
        create().insertInto(T_DATES,
                    T_DATES.ID,
                    T_DATES.Y2,
                    T_DATES.Y4)
                .values(1, d1, d1)
                .values(2, d2, d2)
                .execute();
```
the SQL that is generated looks like this:

```sql
insert into `test`.`t_dates` (
  `id`, 
  `y2`, 
  `y4`
)
select 
  `t`.`v0`, 
  `t`.`v1`, 
  `t`.`v2`
from (
  
  select *
  from (
    select 
      null as `v0`, 
      null as `v1`, 
      null as `v2`
    from dual
    where 1 = 0
  ) x
  union all 
  select *
  from (
    
    select *
    from (
      select 
        1, 
        {d '2012-01-01'}, 
        {d '2012-01-01'}
      from dual
    ) x
    union all 
    select *
    from (
      select 
        2, 
        {d '1999-01-01'}, 
        {d '1999-01-01'}
      from dual
    ) x
  ) x
) as `t`
```
This doesn't work however, since the columns in the innermost SELECTs (corresponding to the VALUES clause) don't have any explicit names and identical values. MySQL reports a "Duplicate column name" error (see also #4856).

Similarly the following query also doesn't work in MySQL:

```sql
    select *
    from (
      select 
        1, 
        {d '2012-01-01'}, 
        {d '2012-01-01'}
      from dual
    ) x
```
While the latter may be more difficult to fix, it seems like it should be possible to fix the problem in the context of the INSERT ... VALUES statement.

**Comment by lukaseder** [comment] 2019-05-08 09:07
Huh, yes. That SQL generation definitely does too much. The subquery containing `where 1 = 0` is generated because of a derived column list, which should not be needed here. See also #6206

**Comment by knutwannheden** [comment] 2019-05-14 15:14
This limitation is also present in MemSQL and causes some integration tests to fail.

**Comment by lukaseder** [comment] 2020-04-01 13:13
The test still fails, but not for the reasons mentioned here. It fails because of #9738.

I'm closing this as I cannot reproduce it right now.

**Closed by lukaseder** 2020-04-01 13:13 UTC
Labels: C: DB: MemSQL, C: DB: MySQL, E: All Editions, P: Medium, T: Defect
