### ISSUE TITLE
TableRecord null value has its changed flag reset despite a Converter encoding the null value as a non-null value

### ISSUE THREAD

**Issue by bekoeppel** [jOOQ/jOOQ#17224] opened 2024-09-10 09:43 UTC
### Expected behavior

I have this database table
```sql
CREATE TABLE mcve.test (
  id INT NOT NULL AUTO_INCREMENT,
  cd INT,
  data varchar(255) not null,
  
  CONSTRAINT pk_test PRIMARY KEY (id) 
);
```

Note that the `data` column is `not null` but has no default.

For the `data` column, I want to store Java `null` as `"nil"` in the database. So I have a custom type and converter:
```java
public class CustomType {
    private String value;
    public CustomType(String value) {
        this.value = value;
    }
    ...
}
```

```java
public class CustomConverter implements Converter<String, CustomType> {

    @Override
    public CustomType from(String databaseObject) {
        if (databaseObject == null) {
            return null;
        } else if (databaseObject.equals("nil")) {
            return null;
        } else {
            return new CustomType(databaseObject);
        }
    }

    @Override
    public String to(CustomType userObject) {
        if (userObject == null || userObject.getValue() == null) {
            return "nil";
        } else {
            return userObject.getValue();
        }
    }

    @Override
    public Class<String> fromType() {
        return String.class;
    }

    @Override
    public Class<CustomType> toType() {
        return CustomType.class;
    }
}
```

and configure it in the config:
```xml
<generator>
    <database>
        ...
        <forcedTypes>
            <forcedType>
                <userType>custom.CustomType</userType>
                <converter>custom.CustomConverter</converter>
                <expression>data</expression>
            </forcedType>
        </forcedTypes>
        ...
```

and create two `TestRecord`s:
```java
TestRecord newRecord1 = new TestRecord(1, 42, null);
TestRecord newRecord2 = new TestRecord(2, 999, new CustomType("foo"))
```

When I insert them into the database, I expect the `CustomConverter` to be applied, thus storing the `newRecord1` with `data = "nil"` in the database. jOOQ up to (including) version 3.18.0 behaved as expected.

### Actual behavior

Starting with jOOQ 3.18.1, the `CustomConverter` is not applied anymore, and instead I get the following exception:
```
[ERROR] Errors:
[ERROR]   JavaTest.mcveTest:46 » IntegrityConstraintViolation SQL [select "ID" from final table (insert into "MCVE"."TEST" ("ID", "CD") values (?, ?)) "TEST"]; NULL not allowed for column "DATA"; SQL statement:
select "ID" from final table (insert into "MCVE"."TEST" ("ID", "CD") values (?, ?)) "TEST" [23502-224]
```

### Steps to reproduce the problem

See https://github.com/bekoeppel/jOOQ-mcve/tree/mcve-17224 (commit: https://github.com/bekoeppel/jOOQ-mcve/commit/4c2ac4319a9f6a5ec6cabcaf8e0bdf9982a35c39)

### jOOQ Version

starting 3.18.1, but also happens on 3.19.11

### Database product and version

H2 (but also happens on MySQL/MariaDB)

### Java Version

openjdk version "21.0.4" 2024-07-16 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

jdbc:h2

**Comment by bekoeppel** [comment] 2024-09-18 13:46
For now I'm using a custom `JavaGenerator`:

```
import org.jooq.codegen.JavaGenerator;
import org.jooq.codegen.JavaWriter;
import org.jooq.impl.IdentityConverter;
import org.jooq.meta.TableDefinition;

public class CustomJooqJavaGenerator extends JavaGenerator {

    @Override
    protected void generateRecordClassFooter(TableDefinition table, JavaWriter out) {
        out.ref(IdentityConverter.class);
        out.javadoc("Reset unchanged fields, but only if they don't have a custom converter");
        out.println("""
            @Override
            protected void resetChangedOnNotNull() {
                int size = this.size();
                for (int i = 0; i < size; i++) {
                    if (this.get(i) == null) {
                        if (!this.field(i).getDataType().nullable()) {
                            if (this.field(i).getConverter() instanceof IdentityConverter<?>) {
                                this.changed(i, false);
                            }
                        }
                    }
                }
            }""");
    }
}

**Comment by lukaseder** [comment] 2024-09-18 14:16
Thanks for your patience and for documenting your workaround. I can reproduce the issue with your MCVE. Your workaround hints at the problem having been introduced by:

- https://github.com/jOOQ/jOOQ/issues/14817

**Comment by lukaseder** [comment] 2024-09-18 14:23
The actual error has been around longer. That change just made it more visible as the wrong method `Tools.resetChangedOnNotNull` is now called in generated record constructors. The logic itself has been around since jOOQ 3.4:

- https://github.com/jOOQ/jOOQ/issues/2700

At the time, it was applied only to DAOs.

**Comment by lukaseder** [comment] 2024-09-18 14:39
The method in question could be updated to something like this:

```java
    @SuppressWarnings({ "unchecked", "rawtypes" })
    static final void resetTouchedOnNotNull(Record record) {
        int size = record.size();

        for (int i = 0; i < size; i++) {
            Field field = record.field(i);

            if (field.getConverter().to(record.get(i)) == null)
                if (!field.getDataType().nullable())
                    record.touched(i, false);
        }
    }
```

There's still a chance of this not behaving as it should, when users use a `Binding` and implement their `null` encoding in the binding logic instead of the `Converter`. I suspect we can fix this another day. Your case is far more likely.

I'll review this idea with some more tests.

**Comment by lukaseder** [comment] 2024-09-18 15:05
Caveat, not all converters implement their `to()` method (they're allowed to throw an exception). This could happen if a column is readonly or computed.

**Comment by lukaseder** [comment] 2024-09-18 15:31
I guess we'll have to offer 2 new marker interfaces to clearly declare readonly and write only `Converter` implementations, to play safe:

- https://github.com/jOOQ/jOOQ/issues/17272

**Comment by bekoeppel** [comment] 2024-09-18 19:35
Thank you for your investigation and help on this. We're OK using the workaround until 3.20 comes out, so it's no big deal if you prefer to not backport to 3.19 and 3.18. Do you have a rough date when 3.20 will be released?

**Comment by lukaseder** [comment] 2024-09-19 07:55
Thanks for the feedback. I've given this a bit more thought. The backport risk is very small, despite this SPI being very popular. See rationale here:
https://github.com/jOOQ/jOOQ/issues/17272#issuecomment-2360201108

I can't make promises about 3.20. 3.19 and 3.18 will ship soon.

**Comment by lukaseder** [comment] 2024-09-19 08:32
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17277)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17278)

**Closed by lukaseder** 2024-09-19 08:32 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by bekoeppel** [comment] 2024-09-19 10:03
Awesome, thank you so much! :tada:
