### ISSUE TITLE
NullPointerException in SchemaMapping due to race condition in SchemaMapping cache

### ISSUE THREAD

**Issue by suket123** [jOOQ/jOOQ#11519] opened 2021-02-24 16:19 UTC
I noticed the following stack trace on jooq version: 3.12.3. ( Upgraded our jooq to version 3.14.6 and still encountered the same error )
I randomly get this error and its not reproducible. I'm quite confused why this happens.

Stack trace from jooq version (3.12.3)
```
java.lang.NullPointerException
	at org.jooq_3.12.1.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.TableImpl.accept0(TableImpl.java:252)
	at org.jooq.impl.TableImpl.accept(TableImpl.java:234)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.Alias.toSQLWrapped(Alias.java:289)
	at org.jooq.impl.Alias.accept(Alias.java:223)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.TableAlias.accept(TableAlias.java:149)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.JoinTable.toSQLTable(JoinTable.java:327)
	at org.jooq.impl.JoinTable.accept(JoinTable.java:223)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.QueryPartList.accept(QueryPartList.java:121)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:1343)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:1115)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:903)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:703)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:510)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.AbstractDelegatingQuery.accept(AbstractDelegatingQuery.java:88)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:443)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.CommonTableExpressionImpl.accept(CommonTableExpressionImpl.java:104)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.QueryPartList.accept(QueryPartList.java:121)
	at org.jooq.impl.CommonTableExpressionList.accept(CommonTableExpressionList.java:64)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.WithImpl.accept(WithImpl.java:223)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:548)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:510)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.AbstractDelegatingQuery.accept(AbstractDelegatingQuery.java:88)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:443)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.CommonTableExpressionImpl.accept(CommonTableExpressionImpl.java:104)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.QueryPartList.accept(QueryPartList.java:121)
	at org.jooq.impl.CommonTableExpressionList.accept(CommonTableExpressionList.java:64)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.WithImpl.accept(WithImpl.java:223)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:548)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:510)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:583)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:457)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:218)
	at org.jooq.impl.AbstractQuery.getSQL0(AbstractQuery.java:521)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:324)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:353)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2693)
	at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:4090)
```

**Comment by lukaseder** [comment] 2021-02-24 17:12
Thanks for your report. I'll try to think about what could produce it. Can you post the 3.14.7 stack trace as well?

**Comment by lukaseder** [comment] 2021-02-25 10:49
Irrespective of the 3.14.7 stack trace, the version 3.12.1 `TableImpl.java:252` points here:
https://github.com/jOOQ/jOOQ/blob/version-3.12.1/jOOQ/src/main/java/org/jooq/impl/TableImpl.java#L252

```java
ctx.visit(Tools.getMappedTable(ctx.configuration(), this).getUnqualifiedName());
```

There might be a race condition when accessing the table mapping cache? We could improve our implementation in 3.15.0: https://github.com/jOOQ/jOOQ/issues/11524. As we have stopped supporting Java 6 and 7, we can improve the implementation's thread safety by using `ConcurrentHashMap::computeIfAbsent`

You can try to validate this by trying to eager initialise your schema mapping when you start your application. Let me know if you need any help with that.

**Comment by suket123** [comment] 2021-02-25 14:51
Thank-you for looking into this. Can you please point out how I can eager initialize my schema mapping?

**Comment by lukaseder** [comment] 2021-02-25 14:55
I'm assuming you use generated code? In that case, take your catalog, iterate over all the schemas, and over all the tables, and run this on each one:

```java
for (Schema schema : catalog)
  for (Table<?> table : schema)
    configuration.dsl().render(table);
```

To be sure, you can verify that this calls the logic in `SchemaMapping.map(Table)`.

**Comment by lukaseder** [comment] 2021-02-25 14:55
To make sure this is run early on, just put this code in some class initialiser of some class that you're loading early in your application:

```java
static {
  // Above code
}
```

**Comment by lukaseder** [comment] 2021-05-13 13:31
Improvements are on the way with #11524 (no promises when they arrive). Until then, unfortunately, I can't reproduce this issue, so I'm closing it as "worksforme"

**Comment by lukaseder** [comment] 2024-12-19 10:45
Having another look at this issue. With this loop, I can occasionally reproduce the problem:

```java
for (int r = 0; r < 100; r++) {
    ExecutorService s = Executors.newFixedThreadPool(13);
    DSLContext ctx2 = configuration.derive().dsl();
    RenderMapping m = new RenderMapping();
    final int MAX = 31;
    MappedSchema schema = new MappedSchema()
        .withInput("S")
        .withOutput("S");
    m.getSchemata().add(schema);

    for (int i = 0; i < MAX; i++) {
        schema.getTables().add(new MappedTable()
            .withInput("T" + i)
            .withOutput("T")
        );
    }

    ctx2.settings().withRenderMapping(m);
    Map<String, String> sql = new ConcurrentHashMap<>();
    AtomicInteger count = new AtomicInteger();
    for (int i = 0; i < 100000; i++) {
        s.execute(() -> {
            count.incrementAndGet();
            sql.put(ctx2.render(select().from(
                table(name("S", "T" + (int) (Math.random() * MAX))),
                table(name("S", "T" + (int) (Math.random() * MAX))),
                table(name("S", "T" + (int) (Math.random() * MAX)))
            )), "1");
        });
    }
    s.awaitTermination(5, TimeUnit.SECONDS);
    s.shutdown();

    System.out.println(count.get());
    System.out.println(sql.size());
    System.out.println(sql);
}
```

It prints, for example:

```
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
Exception in thread "pool-38-thread-11" java.lang.NullPointerException: Cannot invoke "org.jooq.Table.getUnqualifiedName()" because the return value of "org.jooq.impl.Tools.getMappedTable(org.jooq.Scope, org.jooq.Table)" is null
	at org.jooq.impl.TableImpl.accept0(TableImpl.java:487)
	at org.jooq.impl.TableImpl.accept(TableImpl.java:466)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:728)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:363)
	at org.jooq.impl.QueryPartCollectionView.acceptElement(QueryPartCollectionView.java:270)
	at org.jooq.impl.TableList.lambda$1(TableList.java:87)
	at org.jooq.impl.Tools.visitAutoAliased(Tools.java:3020)
	at org.jooq.impl.TableList.acceptElement(TableList.java:87)
	at org.jooq.impl.TableList.acceptElement(TableList.java:1)
	at org.jooq.impl.QueryPartCollectionView.accept(QueryPartCollectionView.java:240)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:728)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:363)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:2638)
	at org.jooq.impl.SelectQueryImpl.lambda$48(SelectQueryImpl.java:2148)
	at org.jooq.impl.AbstractContext.data(AbstractContext.java:420)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:2148)
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:2043)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:1631)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:728)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:363)
	at org.jooq.impl.AbstractDelegatingQuery.accept(AbstractDelegatingQuery.java:90)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:728)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:363)
	at org.jooq.impl.DefaultDSLContext.render(DefaultDSLContext.java:734)
	at org.jooq.testscripts.JDBC.lambda$0(JDBC.java:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
100000
1
{select * from "S"."T", "S"."T", "S"."T"=1}
```

This doesn't reproduce the problem reliably, but at least we can heuristically assume that if we run this for hours without any exceptions, then it's likely fixed. Reliable reproduction would be better, of course, as that would simplify a unit test. At least, if this test runs for 10s - 20s in *every* build, then we can keep an eye out for flaky tests, which would show that any fix isn't good enough yet.

**Comment by lukaseder** [comment] 2024-12-19 12:23
OK, this test is more reliable:

```java
    @Test
    public void testSchemaMappingConcurrency() throws Exception {
        for (int r = 0; r < 20; r++) {
            ExecutorService s = Executors.newFixedThreadPool(13);
            DSLContext ctx = DSL.using(SQLDialect.H2);
            RenderMapping m = new RenderMapping();
            int numTables = 31;
            int numExecutions = 100000;
            MappedSchema schema = new MappedSchema()
                .withInput("S")
                .withOutput("S");
            m.getSchemata().add(schema);

            for (int i = 0; i < numTables; i++) {
                schema.getTables().add(new MappedTable()
                    .withInput("T" + i)
                    .withOutput("T")
                );
            }

            ctx.settings().withRenderMapping(m);

            AtomicReference<Exception> exception = new AtomicReference<>();
            AtomicInteger executions = new AtomicInteger();
            for (int i = 0; i < numExecutions; i++) {
                int i0 = i;

                s.execute(() -> {
                    try {
                        Integer[] n = { i0, (i0 + 1) % numExecutions, (i0 + 2) % numExecutions };
                        shuffle(asList(n));

                        ctx.render(select().from(
                            table(name("S", "T" + n[0])),
                            table(name("S", "T" + n[1])),
                            table(name("S", "T" + n[2]))
                        ));
                    }
                    catch (Exception e) {
                        exception.set(e);
                    }

                    executions.incrementAndGet();
                });
            }

            for (int i = 0; i < numExecutions / 10 && executions.get() < numExecutions; i++)
                s.awaitTermination(10, TimeUnit.MILLISECONDS);
            s.shutdown();

            if (exception.get() != null)
                throw exception.get();
        }
    }
```

The key point here is that it makes it very likely for two concurrent renderings to have table mappings of the kind `FROM T1, T2, T3` and `FROM T3, T2, T1`, i.e. the same mapped tables in different order. When the renderings do this concurrently, the probability of one thread being interrupted while mapping a table that the other thread will map as well, then we run into this problem.

The problem appears only when mapping the tables for the first time, afterwards, they will be cached, which is why the test keeps creating new `Configuration` instances, in order to have empty caches time and again.

**Comment by ukarlsson** [comment] 2024-12-19 12:28
Many thanks for looking into this.

The test is consistent with our use case since we create a new configuration object with specific mappings on each request.

We also render explicitly directly after creating the mappings, but it does not seem to help

```
    catalogs.forEach { catalog -> catalog.schemas.forEach { schema -> schema.tables.forEach { context.render(it) } } }
```

**Comment by lukaseder** [comment] 2024-12-19 13:04
Fixed in versions:

- 3.20.0
- 3.19.17 (https://github.com/jOOQ/jOOQ/issues/17788)
- 3.18.24 (https://github.com/jOOQ/jOOQ/issues/17789)
- 3.17.33 (https://github.com/jOOQ/jOOQ/issues/17790)

**Closed by lukaseder** 2024-12-19 13:04 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by ukarlsson** [comment] 2024-12-19 13:09
> But then, how does the concurrency problem appear? Are your requests not thread-bound? I.e. do they run logic on multiple threads?

Each requests spawn many concurrent database queries, in particular with GraphQL that generates a lot of queries concurrently using the newly created configuration.

**Comment by lukaseder** [comment] 2024-12-19 14:00
Here's the 3.19 patch:

- https://github.com/jOOQ/jOOQ/commit/e63555e273790e189b850fa84936b9bba4ed839c.patch

Would be very useful to have your early feedback about whether this fixes the issue for you, @ukarlsson

**Comment by ukarlsson** [comment] 2024-12-19 15:10
Thanks, I have tested this and it seems to work better, I did not get any NPEs

**Comment by ukarlsson** [comment] 2025-01-07 10:52
Is it possible to get a release with this fixed? Many thanks
