### ISSUE TITLE
Code generation fails with H2 2.1.210 when using MySQL execution mode

### ISSUE THREAD

**Issue by cstamas** [jOOQ/jOOQ#13240] opened 2022-03-08 11:14 UTC
### Expected behavior
To have codegen succeed.

Codegen works as expected with H2 1.4.200 but only by upping H2 2.1.210 it fails. The failure is not our SQL, but the one executed by plugin.

### Actual behavior

Error output is:
```
[INFO] ----------------------------------------------------------
[INFO] Generating catalogs      : Total: 1
[INFO] ARRAYs fetched           : 0 (0 included, 0 excluded)
[INFO] Domains fetched          : 0 (0 included, 0 excluded)
[INFO] Tables fetched           : 6 (6 included, 0 excluded)
[INFO] Embeddables fetched      : 0 (0 included, 0 excluded)
[WARNING] SQL exception            : Exception while executing meta query: Schema "information_schema" not found; SQL statement:
select c.TABLE_SCHEMA , c.TABLE_NAME , c.COLUMN_NAME , array_agg(ev.value_name order by ev.VALUE_ORDINAL)
from INFORMATION_SCHEMA.ENUM_VALUES ev
join information_schema.columns c
on ev.OBJECT_SCHEMA = c.TABLE_SCHEMA
and ev.OBJECT_NAME = c.TABLE_NAME
and ev.ENUM_IDENTIFIER = c.DTD_IDENTIFIER
where ev.OBJECT_TYPE = 'TABLE'
and c.DOMAIN_NAME IS NULL
group by c.TABLE_SCHEMA , c.TABLE_NAME , c.COLUMN_NAME
order by 1, 2, 3
 [90079-210]
```
The SQL plugin execute is:

```sql
select c.TABLE_SCHEMA , c.TABLE_NAME , c.COLUMN_NAME , array_agg(ev.value_name order by ev.VALUE_ORDINAL)
from INFORMATION_SCHEMA.ENUM_VALUES ev
join information_schema.columns c
on ev.OBJECT_SCHEMA = c.TABLE_SCHEMA
and ev.OBJECT_NAME = c.TABLE_NAME
and ev.ENUM_IDENTIFIER = c.DTD_IDENTIFIER
where ev.OBJECT_TYPE = 'TABLE'
and c.DOMAIN_NAME IS NULL
group by c.TABLE_SCHEMA , c.TABLE_NAME , c.COLUMN_NAME
order by 1, 2, 3
```
Notice H2 error `Schema "information_schema" not found` (uses lowercase information_schema), and query really mixes the two.

It fails on this query:
https://github.com/jOOQ/jOOQ/blob/version-3.16.4/jOOQ-meta/src/main/java/org/jooq/meta/h2/H2Database.java#L828

### Steps to reproduce the problem

In POM we use `sql-maven-plugin` to execute DDL and then invoking `jooq-codegen-maven` to generate sources:

```xml
      <properties>
        <db.schema>PUBLIC</db.schema>
        <db.driver>org.h2.Driver</db.driver>
        <db.url>jdbc:h2:${basedir}/target/jooq-codegen;MODE=MySQL;DATABASE_TO_UPPER=false</db.url>
        <db.username>sa</db.username>
        <db.password/>
      </properties>


      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>sql-maven-plugin</artifactId>
        <version>1.5</version>
        <configuration>
          <driver>${db.driver}</driver>
          <url>${db.url}</url>
          <username>${db.username}</username>
          <password>${db.password}</password>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${h2.version}</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>execute-ddl</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <srcFiles>
                <scrFile>src/main/resources/ddl-jooq.sql</scrFile>
              </srcFiles>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.jooq</groupId>
        <artifactId>jooq-codegen-maven</artifactId>
        <dependencies>
          <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${h2.version}</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>jooq-codegen</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <jdbc>
                <url>${db.url}</url>
                <user>${db.username}</user>
                <password>${db.password}</password>
              </jdbc>
              <generator>
                <database>
                  <!--includes>.*</includes-->
                  <inputSchema>${db.schema}</inputSchema>
                </database>
                <target>
                  <packageName>com.company.project.jooq.codegen</packageName>
                  <directory>target/generated-sources/jooq</directory>
                </target>
              </generator>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

### Versions

- jOOQ: 3.16.4
- Java: Java11 Temurin
- Database (include vendor): H2 versions 1.4.200 and 2.1.210
- OS: Linux
- JDBC Driver (include name if inofficial driver): H2

**Comment by lukaseder** [comment] 2022-03-08 11:25
Thanks for your detailed report.

I can fix this, but I'd say this is mostly a cosmetic fix. There's no reason why this query should fail under normal circumstances on H2. The reason is most likely, because you're using this set of connection flags for some reason: `;MODE=MySQL;DATABASE_TO_UPPER=false`.

While the fix can be implemented, there won't be an integration test guaranteeing no such regressions appear in the future. H2's execution modes won't be supported by jOOQ.

**Comment by lukaseder** [comment] 2022-03-08 11:29
Fixed in jOOQ 3.17.0 and 3.16.5 (https://github.com/jOOQ/jOOQ/issues/13241)

**Closed by lukaseder** 2022-03-08 11:29 UTC
Labels: T: Defect, C: Code Generation, C: DB: H2, P: Low, E: All Editions

**Comment by cstamas** [comment] 2022-03-08 11:53
Confirmed, H2 2.1.210 and jOOQ 3.16.4 works just fine  when flag `DATABASE_TO_UPPER=false` removed. To be frank, unsure why this flag was present in the first place...

**Comment by lukaseder** [comment] 2022-03-08 12:41
Well, I'm guessing you're using H2 to speed up code generation, rather than using MySQL directly (akin to the [`DDLDatabase`](https://www.jooq.org/doc/latest/manual/code-generation/codegen-ddl/), which currently does the same thing). And H2 upper cases all unquoted identifiers, which affects code generation output.
