### ISSUE TITLE
TruncDate support QUARTER and WEEK 

### ISSUE THREAD

**Issue by fangniude** [jOOQ/jOOQ#12534] opened 2021-10-18 09:44 UTC
### Use case:

In PostgreSQL, group by date_trunc field 
``` sql
select date_trunc('year', birth_date) y, date_trunc('quarter', birth_date) q
from student
group by y, q
```

### Possible solution you'd like to see:
``` java
DSL.trunc(field, DatePart.QUARTER) 
DSL.trunc(field, DatePart.WEEK)
```

**Comment by lukaseder** [comment] 2021-10-19 08:41
Thank you very much for your suggestion.

This is a duplicate of https://github.com/jOOQ/jOOQ/issues/8418

**Closed as completed by lukaseder** 2021-10-19 08:41 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, R: Duplicate, E: All Editions
