### ISSUE TITLE
Regression in mocking capabilities due to `getDataType().getTypeName()` behavior for array fields

### ISSUE THREAD

**Issue by lalithsuresh** [jOOQ/jOOQ#12975] opened 2022-01-31 19:13 UTC
### Expected behavior

We've been using the mocking capabilities of JOOQ to support an in-memory, embedded, relational backend to a JOOQ-based frontend.

We've been previously manipulating and querying array types via this system and things worked fine.

### Actual behavior

After upgrading JOOQ to match the recent H2 releases, we found we are no longer able to query fields of array types (tested so far with integer types).

The root cause seems to be here, deep within the `MockingResultSetMetaData` class.

```
    public String getColumnTypeName(int column) throws SQLException {
        this.rs.checkNotClosed();
        return this.rs.result.field(column - 1).getDataType().getTypeName();
    }
```

Event though `this.rs.result.field` has Java type `Integer[]` (and the result has an array of integers in it), `getDataType().getTypeName()` returns `integer`, which in turns causes a `ClassCastException` as JOOQ tries to cast an `Integer[]` to `Integer`:

```java
org.jooq.exception.DataAccessException: SQL [select * from check_array_type]; Error while reading field: "PUBLIC"."CHECK_ARRAY_TYPE"."AGG", at JDBC index: 2

	at org.jooq_3.16.2.DEFAULT.debug(Unknown Source)
	at org.jooq_3.16.2.DEFAULT.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3089)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1462)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1423)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:236)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:259)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:335)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
	at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:847)
	at ddlog.JooqProviderTestBase.testArrayAggTypes(JooqProviderTestBase.java:572)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.sql.SQLException: Error while reading field: "PUBLIC"."CHECK_ARRAY_TYPE"."AGG", at JDBC index: 2
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1584)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1523)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1482)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1447)
	... 37 more
Caused by: java.lang.ClassCastException: class [Ljava.lang.Integer; cannot be cast to class java.lang.Integer ([Ljava.lang.Integer; and java.lang.Integer are in module java.base of loader 'bootstrap')
	at org.jooq.tools.jdbc.MockResultSet.getInt(MockResultSet.java:531)
	at org.jooq.tools.jdbc.DefaultResultSet.getInt(DefaultResultSet.java:144)
	at org.jooq.impl.CursorImpl$CursorResultSet.getInt(CursorImpl.java:615)
	at org.jooq.impl.DefaultBinding$DefaultIntegerBinding.get0(DefaultBinding.java:2810)
	at org.jooq.impl.DefaultBinding$DefaultIntegerBinding.get0(DefaultBinding.java:2777)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:997)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1574)
	... 41 more
```

### Steps to reproduce the problem

The code here shows the problem with and without using the mocks. Note that the `fetch()` passes in the first test (even though the type info is wrong). In the second test that uses the mocks, the `fetch()` itself fails and throws the exception (same stack trace as what we see in the larger system).

```java

    @Test
    public void testJooqArrayFieldTypeName() {
        final DSLContext conn = using("jdbc:h2:mem:");
        conn.execute("create table t1(c1 integer array)");
        conn.execute("insert into t1 values (ARRAY[100])");
        assertNotEquals(conn.fetch("select * from t1").get(0).field(0).getDataType().getTypeName(), "integer");
    }

    @Test
    public void testJooqArrayFieldTypeNameMock() {
        final DataProvider provider = new DataProvider();
        final MockConnection connection = new MockConnection(provider);
        final DSLContext conn = using(connection);
        conn.fetch("select * from t1");
    }

    private static class DataProvider implements MockDataProvider {
        private final DSLContext conn = using("jdbc:h2:mem:");
        private final Field<Integer[]> arrayCol = DSL.field("arraycol", Integer[].class);

        @Override
        public MockResult[] execute(MockExecuteContext mockExecuteContext) throws SQLException {
            final Result<Record1<Integer[]>> result = conn.newResult(arrayCol);
            final Record1<Integer[]> resultRecord = conn.newRecord(arrayCol);
            resultRecord.setValue(arrayCol, new Integer[]{151, 81});
            result.add(resultRecord);
            final MockResult[] ret = new MockResult[1];
            ret[0] = new MockResult(1, result);
            return ret;
        }
    }
```

### Versions

- jOOQ: 3.16.2
- Java: 11
- Database (include vendor): H2 2.1.210
- OS: Mac OSX
- JDBC Driver (include name if inofficial driver):

**Comment by lalithsuresh** [comment] 2022-02-08 19:51
@lukaseder apologies for poking. This issue is blocking us from upgrading H2 to deal with the recent flurry of CVEs. Any workarounds you could suggest?

**Comment by lukaseder** [comment] 2022-02-09 08:15
Thanks for the ping, @lalithsuresh. I was planning on looking into this later, this week. H2 changed their array implementation completely, from being only type-less `Object[]` to typed `T[]` support.

I really wish the CVE fixes had been backported to 1.4, though. There had been quite a few "regressions" caused by incompatible changes in 2.0, which are now more urgent than they would otherwise be, if there hadn't been those critical CVEs...

What are you using H2 for? Perhaps you could contribute patches to H2 1.4, for the CVEs?

**Comment by lukaseder** [comment] 2022-02-09 12:47
Looking into this now. I've extracted a new issue https://github.com/jOOQ/jOOQ/issues/13029 for the behaviour observed in this test here:

```java
    @Test
    public void testJooqArrayFieldTypeName() {
        final DSLContext conn = using("jdbc:h2:mem:");
        conn.execute("create table t1(c1 integer array)");
        conn.execute("insert into t1 values (ARRAY[100])");
        assertNotEquals(conn.fetch("select * from t1").get(0).field(0).getDataType().getTypeName(), "integer");
    }
```

That's not really a regression, it never really worked. The `DataType.getTypeName()` produced the array base type for an array type. In the old H2 1.4 database, this used to be the `ARRAY` type, which isn't really a formal array type. So, H2 fixed this by implementing the same behaviour as HSQLDB, which is specified by the SQL standard. This now exposed bug https://github.com/jOOQ/jOOQ/issues/13029.

A workaround for that bug is to pass the configuration to `getTypeName(configuration)`, to get a hold of an H2 specific data type, in this case `int array`, which is the correct type and already works in jOOQ 3.16.4.

Given that #13029 might break existing assumptions by users, I've flagged it as an incompatible change and won't backport it.

I'll look at the second test in a bit.

**Comment by lukaseder** [comment] 2022-02-09 13:09
The second test passes once #13029 is fixed. Hmm, I can see how this is a problem, as you can't really influence the logic that is used to decide what data type is returned, so jOOQ's internals produce this `ClassCastException`. I suspect, I'll backport #13029 nonetheless, to 3.16.5

**Comment by lukaseder** [comment] 2022-02-09 13:10
Closing this issue here as a duplicate of https://github.com/jOOQ/jOOQ/issues/13029, which is the real underlying issue.

**Closed by lukaseder** 2022-02-09 13:10 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
