### ISSUE TITLE
Error translate query sql server to informix query

### ISSUE THREAD

**Issue by thiago899** [jOOQ/jOOQ#8134] opened 2018-12-18 14:20 UTC
What is missing to translate to the informix query?

```sql
DECLARE @STARTDATE datetime
DECLARE @ENDDATE datetime
DECLARE @STARTHOUR INT
DECLARE @ENDHOUR INT
DECLARE @CSQS VARCHAR(50)

SET @STARTDATE = '{startDate}'
SET @ENDDATE = '{endDate}'
SET @STARTHOUR = '{startHour}'
SET @ENDHOUR = '{endHour}'
SET @CSQS = '{csqs}'


IF OBJECT_ID('tempdb.dbo.#HH', 'U') IS NOT NULL BEGIN DROP TABLE #HH END
IF OBJECT_ID('tempdb.dbo.#loggedin', 'U') IS NOT NULL BEGIN DROP TABLE #loggedin END
IF OBJECT_ID('tempdb.dbo.#agents', 'U') IS NOT NULL BEGIN DROP TABLE #agents END
IF OBJECT_ID('tempdb.dbo.#queue', 'U') IS NOT NULL BEGIN DROP TABLE #queue END
IF OBJECT_ID('tempdb.dbo.#queueAgent', 'U') IS NOT NULL BEGIN DROP TABLE #queueAgent END
IF OBJECT_ID('tempdb.dbo.#hoursummary', 'U') IS NOT NULL BEGIN DROP TABLE #hoursummary END
IF OBJECT_ID('tempdb.dbo.#hoursummaryAgent', 'U') IS NOT NULL BEGIN DROP TABLE #hoursummaryAgent END
IF OBJECT_ID('tempdb.dbo.#hourdata', 'U') IS NOT NULL BEGIN DROP TABLE #hourdata END
IF OBJECT_ID('tempdb.dbo.#hourdataAgent', 'U') IS NOT NULL BEGIN DROP TABLE #hourdataAgent END

select n into #HH from (SELECT n = ROW_NUMBER() OVER (ORDER BY [object_id]) - 1 
		FROM sys.all_objects) nums where n <= 23

select
	#HH.n as "Hour",
	sum(CASE when datepart(HH, asd.eventdatetime) between #HH.n and #HH.n+1 then 1 else 0 end) LoggedIn,
	sum(CASE when (datepart(HH, asd.eventdatetime) between #HH.n and #HH.n+1 and asd.eventtype between 5 and 6) then 1 else 0 end) Working
into #loggedin
from 
	"resource" r
	join agentstatedetail asd on r.resourceid = asd.agentid and asd.eventtype <> 7
	join #HH on #HH.n = datepart(HH,asd.eventdatetime)
where
	convert(date,asd.eventdatetime,105) between @STARTDATE and @ENDDATE
	and #HH.n between @STARTHOUR and @ENDHOUR
group by 
	#HH.n
order by 1, 2


select
	#HH.n as "Hour",
	sum(case when cqd.queuetime > 20 then 1 else 0 end) as Gt20Queue,
	max(cqd.queueorder) as MaxQueueSize,
	max(cqd.queuetime) as MaxQueueTime,
	sum(case when cqd.disposition = 1 then 1 else 0 end) as TotalAbandoned,
	sum(case when ccd.contactdisposition = 2 then 1 else 0 end) as TotalHandled
into #queue
from
	"contactservicequeue" csq
	join contactqueuedetail cqd on csq.contactservicequeueid = cqd.targetid and cqd.targettype = 0
	join contactcalldetail ccd on cqd.sessionid = ccd.sessionid
	join #HH on #HH.n = datepart(HH,ccd.startdatetime)
where
	convert(date,ccd.startdatetime,105) between @STARTDATE and @ENDDATE
	and #HH.n between @STARTHOUR and @ENDHOUR
	and (','+ @CSQS+',') LIKE '%,' + CAST(csq.contactservicequeueid as VARCHAR) + ',%'
group by
	#HH.n
order by 1,2

select
	#HH.n as "Hour",
	avg(acd.talktime + acd.worktime) as AvgDuration,
	stdevp(acd.talktime + acd.worktime) as stdDev,
	min(acd.talktime + acd.worktime) as MinDuration,
	max(acd.talktime + acd.worktime) as MaxDuration
into #hoursummary
from
	contactqueuedetail cqd
	join agentconnectiondetail acd on cqd.sessionid = acd.sessionid
	join #HH on #HH.n = datepart(HH,acd.startdatetime)
where
	convert(date,acd.startdatetime,105) between @STARTDATE and @ENDDATE
	and #HH.n between @STARTHOUR and @ENDHOUR
	and (','+ @CSQS+',') LIKE '%,' + CAST(cqd.targetid as VARCHAR) + ',%' and cqd.targettype = 0
group by
	#HH.n
order by 1,2

select
	#HH.n as "Hour",
	hs.AvgDuration,
	hs.stdDev,
	hs.MaxDuration,
	hs.MinDuration,
	sum(case when (acd.talktime + acd.worktime) >= hs.AvgDuration then 1 else 0 end) as GtAverage,
	sum(case when (acd.talktime + acd.worktime) < hs.AvgDuration then 1 else 0 end) as LtAverage
into #hourdata
from
	contactqueuedetail cqd
	join agentconnectiondetail acd on cqd.sessionid = acd.sessionid and cqd.disposition = 2
	join #HH on #HH.n = datepart(HH,acd.startdatetime)
	join #hoursummary hs on #HH.n = hs."Hour"
where
	convert(date,acd.startdatetime,105) between @STARTDATE and @ENDDATE
	and #HH.n between @STARTHOUR and @ENDHOUR
	and (','+ @CSQS+',') LIKE '%,' + CAST(cqd.targetid as VARCHAR) + ',%' and cqd.targettype = 0
group by
	#HH.n,
	hs.AvgDuration,
	hs.stdDev,
	hs.MaxDuration,
	hs.MinDuration	
order by 1,2


-- Query Part Agents

select
	#HH.n as "Hour",
	r.resourcename as agent,
	r.resourceid,
	avg(acd.talktime + acd.worktime) as AvgDuration,
	stdevp(acd.talktime + acd.worktime) as stdDev,
	min(acd.talktime + acd.worktime) as MinDuration,
	max(acd.talktime + acd.worktime) as MaxDuration
into #hoursummaryAgent
from
	[resource] r
	join agentconnectiondetail acd on r.resourceid = acd.resourceid
    join resourceskillmapping skm on r.resourceskillmapid = skm.resourceskillmapid
    join skill s on skm.skillid = s.skillid
    join skillgroup sg on s.skillid = sg.skillid
    join contactservicequeue csq on sg.skillgroupid = csq.skillgroupid
	join contactqueuedetail cqd on csq.recordid = cqd.targetid and cqd.targettype = 0
	join #HH on #HH.n = datepart(HH,acd.startdatetime)
where
	convert(date,acd.startdatetime,105) between @STARTDATE and @ENDDATE
	and #HH.n between @STARTHOUR and @ENDHOUR
	and (','+ @CSQS+',') LIKE '%,' + CAST(cqd.targetid as VARCHAR) + ',%' and cqd.targettype = 0
group by
	#HH.n,
	r.resourceid,
	r.resourcename
order by 1,2

select
	#HH.n as "Hour",
	hsa.agent,
	hsa.resourceid,
	hsa.AvgDuration,
	hsa.stdDev,
	hsa.MaxDuration,
	hsa.MinDuration,
	sum(case when (acd.talktime + acd.worktime) >= hsa.AvgDuration then 1 else 0 end) as GtAverage,
	sum(case when (acd.talktime + acd.worktime) < hsa.AvgDuration then 1 else 0 end) as LtAverage,
	sum(case when acd.talktime > 0 then 1 else 0 end) as TotalHandled
into #hourdataAgent
from
	[resource] r
	join agentconnectiondetail acd on r.resourceid = acd.resourceid
    join resourceskillmapping skm on r.resourceskillmapid = skm.resourceskillmapid
    join skill s on skm.skillid = s.skillid
    join skillgroup sg on s.skillid = sg.skillid
    join contactservicequeue csq on sg.skillgroupid = csq.skillgroupid
	join contactqueuedetail cqd on acd.sessionid = cqd.sessionid and csq.recordid = cqd.targetid and cqd.targettype = 0
	join contactcalldetail ccd on cqd.sessionid = ccd.sessionid
	join #HH on #HH.n = datepart(HH,acd.startdatetime)
	join #hoursummaryAgent hsa on r.resourceid = hsa.resourceid	and #HH.n = hsa."Hour"
where
	convert(date,acd.startdatetime,105) between @STARTDATE and @ENDDATE
	and #HH.n between @STARTHOUR and @ENDHOUR
	and (','+ @CSQS+',') LIKE '%,' + CAST(cqd.targetid as VARCHAR) + ',%' and cqd.targettype = 0
group by
	#HH.n,
	hsa.resourceid,
	hsa.agent,
	hsa.AvgDuration,
	hsa.stdDev,
	hsa.MaxDuration,
	hsa.MinDuration	
order by 1,2

-- Select all sub-queries

select 
	l."Hour",
	coalesce(q.Gt20Queue,0) as Gt20Queue,
	coalesce(q.MaxQueueSize,0) as MaxQueueSize,
	coalesce(q.MaxQueueTime,0) as MaxQueueTime,
	coalesce(l.LoggedIn,0) as LoggedIn,
	coalesce(l.Working,0) as Working,
	coalesce(hd.LtAverage,0) as LtAverage,
	coalesce(hd.MinDuration,0)as MinDuration,
	coalesce(hd.AvgDuration,0)as AvgDuration,
	coalesce(hd.MaxDuration,0)as MaxDuration,
	coalesce(hd.stdDev,0)as stdDev,
	coalesce(hd.GtAverage,0)as GtAverage,
	coalesce(q.TotalHandled,0)as TotalHandled,
	coalesce(q.TotalAbandoned,0)as TotalAbandoned,
	hda.agent as agent,
	coalesce(hda.resourceid,0),
	coalesce(hda.AvgDuration,0)as agent_AvgDuration,
	coalesce(hda.GtAverage,0)as agent_GtAverage,
	coalesce(hda.LtAverage,0)as agent_LtAverage,
	coalesce(hda.MaxDuration,0)as agent_MaxDuration,
	coalesce(hda.MinDuration,0)as agent_MinDuration,
	coalesce(hda.stdDev,0)as agent_stdDev,
	coalesce(hda.TotalHandled,0)as agent_TotalHandled
from
	#loggedin l
	join #queue q on l."Hour" = q."Hour"
	join #hourdata hd on l."Hour" = hd."Hour"
	join #hourdataAgent hda on l."Hour" = hda."Hour"
order by
	l."Hour",
	hda.agent asc
```

**Comment by lukaseder** [comment] 2018-12-19 10:08
Thank you very much for your report. We're still missing a variety of features to enable you to translate this statement batch to Informix

- The ability to declare variables: #7305
- The ability to assign values to variables: #7306
- The ability to use conditional statements: #8135
- The ability to parse statement batches that do not separate statements by semi colon (listed in #7518)
- SQL Server's aliasing syntax (`n = ROW_NUMBER() ...`). This is supported in jOOQ 3.12. The feature depends on being able to specify the input dialect as well (#7337), as the standard interpretation of this syntax is a boolean value expression (e.g. as implemented in PostgreSQL).
- Support for the SQL Server `DATEPART()` function (listed in #7518), as a synonym for `EXTRACT()`
- Support for SQL Server's `STDEVP()` function (listed in #7518)

As all the issues I've recognised have separate tickets here on GitHub, I will close this issue as a duplicate of the other ones.

Thanks again for reporting this!

**Closed by lukaseder** 2018-12-19 10:08 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect
