### ISSUE TITLE
R2DBC logging / Spring transactions

### ISSUE THREAD

**Issue by brahtala** [jOOQ/jOOQ#15116] opened 2023-05-24 14:00 UTC
### Expected behavior

jOOQ logging works fine with traditional data sources.
However, when using `R2DBC` (in my case `postgres-r2db`) I've noticed that no logs are produced.

I'm using Spring Boot, and there is no auto-configure for jOOQ + R2DBC.  
No problem, I created my own as:  
```java
        DSL.using(new DefaultConfiguration()
                .set(connectionFactory)
                .set(SQLDialect.POSTGRES)
//                .set(transactionProvider)
                .set(new LoggerListener());
```
and tried:
```java
DSL.using(connectionFactory);
```
I've dug a bit. The logging is typically done `LoggerListener`.  
That one, and the interfaces it implements, are not referenced from the `R2DBC` stack.  
Registering it does nothing.
And no matter what log level I put, I see no logs when executing calls.
Apart from the jOOQ logo, and the tip of the day.

Did I miss something, some configuration option somewhere, or are the logs completely missing?  
And a plugable way of doing logs myself.

Second question (probably should have been a separate issue, but I feel it has the same root cause).
Like i mentioned, Spring Boot jOOQ autoconfigure does not work with R2DBC.
I copied some of the configuration from:
https://github.com/spring-projects/spring-boot/blob/dcb97594c36e70cc35400ff0fac39b3aeb3bee11/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jooq/JooqAutoConfiguration.java#L56

Given the (possible) issue with execution listeners from above, this does not work:
```java
	@Bean
	@Order(0)
	public DefaultExecuteListenerProvider jooqExceptionTranslatorExecuteListenerProvider() {
		return new DefaultExecuteListenerProvider(new JooqExceptionTranslator());
	}
```
At least it seems it does not work.
Is there a chance that it is unnecessary?

this one does not work for sure, working on implementing it:
```java
	@Bean
	@ConditionalOnBean(PlatformTransactionManager.class)
	@ConditionalOnMissingBean(TransactionProvider.class)
	public SpringTransactionProvider transactionProvider(PlatformTransactionManager txManager) {
		return new SpringTransactionProvider(txManager);
	}
```

Also, thanks for this great framework!

### Steps to reproduce the problem

Do any query with jOOQ and a R2DBC driver.

Configuration:
```java
DSL.using(connectionFactory);
```
or
```java
        DSL.using(new DefaultConfiguration()
                .set(connectionFactory)
                .set(SQLDialect.POSTGRES)
//                .set(transactionProvider)
                .set(new LoggerListener());
```

### jOOQ Version

3.18.4

### Database product and version

Postgres 14

### Java Version

openJDK 17

### OS Version

Kubuntu 22.04.02 LTS

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:r2dbc-postgresql:jar:1.0.1.RELEASE

**Comment by lukaseder** [comment] 2023-05-24 14:14
Thanks for your report. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/12221

> And a plugable way of doing logs myself.

You can use the `LoggingConnection` as a workaround: https://www.jooq.org/doc/latest/manual/sql-execution/logging-connection/ (there's an R2DBC version as well)

> Second question (probably should have been a separate issue, but I feel it has the same root cause).

(Yeah, never a bad idea to keep issues separate in order to better track things)

> Like i mentioned, Spring Boot jOOQ autoconfigure does not work with R2DBC.

I've seen this on the web. I think there's a problem in Spring Boot 3.x, but I haven't investigated it yet. Perhaps, ask here? https://stackoverflow.com/questions/tagged/jooq

**Closed by lukaseder** 2023-05-24 14:14 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Duplicate, E: All Editions
