### ISSUE TITLE
ALTER COLUMN .. SET with identity type generates wrong query in MySQL and MariaDB

### ISSUE THREAD

**Issue by obirider** [jOOQ/jOOQ#6880] opened 2017-11-30 19:51 UTC
### Expected behavior and actual behavior:

```sql
alterTable("TT")
                .alterColumn("tt_id")
                .set(SQLDataType.BIGINT.identity(true))
                .execute()
```

generates

```sql
alter table `TT` change column `tt_id` `tt_id` bigint not null
```

instead of 

```sql
alter table `TT` change column `tt_id` `tt_id` bigint not null auto_increment
```

### Versions:

- jOOQ: 3.10.0
- Java: 8
- Database (include vendor): MariaDB 10.3.2
- JDBC Driver (include name if inofficial driver): org.mariadb.jdbc.Driver

**Comment by lukaseder** [comment] 2017-12-01 14:04
Thanks very much for your report. We'll look into this soon.

**Comment by lukaseder** [comment] 2017-12-07 10:40
The problem is related to the fact that jOOQ internally distinguishes between adding a column (in case of which the `auto_increment` flag would have been set) or modifying a column (in case of which it was omitted).

While we should certainly fix this, I'm curious: What's the use-case for adding that flag only later, when the column already exists?

**Comment by lukaseder** [comment] 2017-12-07 11:07
This is now fixed for jOOQ 3.11.0. We won't backport this fix, as there is a significant regression risk in this rather delicate part of the DDL logic. We'll be fixing quite a few DDL bugs during the next weeks for 3.11.0, so this fix will be part of it.

Thanks again for reporting!

**Closed by lukaseder** 2017-12-07 11:07 UTC
Labels: C: DB: MariaDB, C: DB: MySQL, C: Functionality, P: Medium, R: Fixed, T: Defect

**Comment by obirider** [comment] 2017-12-07 18:19
Thank's for solving!

Our "database updater" adds by design the table with all its column definitions and then the keys.
Since it is not allowed in MariaDB to set a column auto_increment before it is defined as a primary key ("Incorrect table definition; there can be only one auto column and it must be defined as a key"), my guess was to
1. add table and column definitions
2. adding keys
3. changing auto_increment flags
 
 
 
And I think another use-case could be: when changing an auto_increment-column (changing the datatype or not null constraint) with the command
```
.alterColumn("tt_id")
.set(SQLDataType.BIGINT.identity(true))
```
the column won't be auto_incremented anymore.

**Comment by lukaseder** [comment] 2017-12-11 10:43
I see, that makes sense. Thanks a lot for the explanation.
