### ISSUE TITLE
Wrong SQL syntax generated for empty inserts of fetched records without any touched values

### ISSUE THREAD

**Issue by Hellblazer** [jOOQ/jOOQ#17708] opened 2024-11-29 18:58 UTC
### Expected behavior

When inserting a record that uses the JOOQ record versioning, the generated SQL should not contain the key words "default values"

### Actual behavior

I am upgrading an ancient project from quite a while ago and running into trouble now that I'm updating JOOQ, etc.  The issue is that I selected a record from a table, and then reinsert that to bump the version.  This fails because the generated Postgres SQL contains "default values", while clearly adding the "version" column.

Here's what I'm doing:

```java
        ExistentialRecord existential = create.selectFrom(EXISTENTIAL)
                                              .where(EXISTENTIAL.ID.equal(wko.id()))
                                              .fetchOne();
        existential.insert();
```

Here's the stack trace:

```
org.jooq.exception.DataAccessException: SQL [insert into "ruleform"."existential" ("version") default values returning "ruleform"."existential"."id"]; ERROR: syntax error at or near "default"
  Position: 50
  
	at org.jooq_3.19.15.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3641)
	at org.jooq.impl.Tools.translate(Tools.java:3629)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:207)
	at org.jooq.impl.TableRecordImpl.lambda$storeInsert$0(TableRecordImpl.java:172)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:171)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:159)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:154)
	at com.chiralbehaviors.CoRE.kernel.Bootstrap.populate(Bootstrap.java:167)
	at com.chiralbehaviors.CoRE.kernel.Bootstrap.populateAgencies(Bootstrap.java:175)
	at com.chiralbehaviors.CoRE.kernel.Bootstrap.constructKernelWorkspace(Bootstrap.java:110)
	at com.chiralbehaviors.CoRE.kernel.Bootstrap.bootstrap(Bootstrap.java:101)
	at com.chiralbehaviors.CoRE.kernel.Bootstrap.boostrap(Bootstrap.java:57)
	at com.chiralbehaviors.CoRE.kernel.BootstrapTest.testBootstrap(BootstrapTest.java:36)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "default"
  Position: 50
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2733)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2420)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:372)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:517)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:434)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeQuery(DefaultPreparedStatement.java:104)
	at org.jooq.impl.AbstractDMLQuery.executeReturningQuery(AbstractDMLQuery.java:1382)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1213)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348)
	... 39 more
```

### Steps to reproduce the problem

Create a table that uses versioning.  Insert some records into it.  Select one of those records subsequently and reinsert using the record.insert()

### jOOQ Version

JOOQ open source version 3.19.15

### Database product and version

PostgreSQL 17

### Java Version

GraalVM 23

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.4

**Comment by lukaseder** [comment] 2024-12-02 08:06
Thanks for your report.

I'm assuming that by "versioning," you mean using the optimistic locking feature:
https://www.jooq.org/doc/latest/manual/sql-execution/crud-with-updatablerecords/optimistic-locking/

I can see how a versioned record should enforce updates to the versioning columns even if nothing else changed. As a workaround, just call `Record.touched()` on at least one column to trigger the expected behaviour.

**Comment by lukaseder** [comment] 2024-12-02 08:20
Hmm, I guess you don't want to touch any value, because you don't want to re-insert those values? But why choose this interaction pattern then, to create a new dummy record? Things would work correctly, if you just created a new record and inserted that.

I'll fix the bug, which is generating wrong SQL, of course, but I'm still curious about why choosing this interaction pattern.

**Comment by lukaseder** [comment] 2024-12-02 08:25
Fixed in versions:

- 3.20.0
- 3.19.16 (https://github.com/jOOQ/jOOQ/issues/17709)
- 3.18.23 (https://github.com/jOOQ/jOOQ/issues/17710)
- 3.17.32 (https://github.com/jOOQ/jOOQ/issues/17711)

**Closed by lukaseder** 2024-12-02 08:25 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by Hellblazer** [comment] 2024-12-02 15:05
The reason- at the time was to bump the version on the record. That version was used to indicate a larger notion of versioning of a graph.

**Comment by lukaseder** [comment] 2024-12-02 17:12
> The reason- at the time was to bump the version on the record. That version was used to indicate a larger notion of versioning of a graph.

Ah, so you've deleted the record in the database, given that you're calling `insert()` on it?

**Comment by Hellblazer** [comment] 2024-12-02 17:27
No, was something sillier. Just bump the version of the existing record with no changes. It was long ago and the reason for doing so no longer really exists and so have eliminated this call. Just filed this for the bug on the code generation which I thought have other unintended consequences. On Dec 2, 2024, at 09:13, Lukas Eder ***@***.***> wrote:﻿

The reason- at the time was to bump the version on the record. That version was used to indicate a larger notion of versioning of a graph.

Ah, so you've deleted the record in the database, given that you're calling insert() on it?

**Comment by lukaseder** [comment] 2024-12-03 08:05
> No, was something sillier. Just bump the version of the existing record with no changes. It was long ago and the reason for doing so no longer really exists and so have eliminated this call.

Ah, interesting, but `insert()` wouldn't do that, you'd have to call `update()`.

**Comment by Hellblazer** [comment] 2024-12-03 14:59
Ah. Of course. Thanks.On Dec 3, 2024, at 00:06, Lukas Eder ***@***.***> wrote:﻿

No, was something sillier. Just bump the version of the existing record with no changes. It was long ago and the reason for doing so no longer really exists and so have eliminated this call.

Ah, interesting, but insert() wouldn't do that, you'd have to call update().
