### ISSUE TITLE
`fetchAsync` for `InsertResultStep` and `DeleteResultStep`

### ISSUE THREAD

**Issue by danielgindi** [jOOQ/jOOQ#13297] opened 2022-03-17 07:41 UTC
### Use case:

We want to efficiently use coroutines, and we need the async fetch methods.
But turns out that insert/delete statements do not have `fetchAsync`, only `executeAsync`.

### Possible solution you'd like to see:

Add `fetchAsync` to all query types. 

### Possible workarounds:

Perhaps use `getSQL` and try to attach it to a `ResultQuery`, although I don't know if such methods exists.

### Versions:

- jOOQ: 3.14.7
- Java: 9
- Database (include vendor): Postgres
- OS: macOS

**Comment by lukaseder** [comment] 2022-03-17 07:46
Thanks for your suggestion. Please upgrade.

Duplicate of https://github.com/jOOQ/jOOQ/issues/3185

**Closed by lukaseder** 2022-03-17 07:46 UTC
Labels: T: Enhancement

**Comment by danielgindi** [comment] 2022-03-17 08:03
Another note: Making `SQLResultQuery` public, would make workarounds much easier to implement.

**Comment by danielgindi** [comment] 2022-03-17 08:11
@lukaseder Upgrading to latest did not magically add `async` method for these... What am I missing?

**Comment by lukaseder** [comment] 2022-03-17 08:12
> Another note: Making `SQLResultQuery` public, would make workarounds much easier to implement.

If you're willing to going down that route, you might as well put your workarounds in the `org.jooq.impl` package and hack your way through. Or use reflection. Or patch jOOQ. All of these are equivalent in terms of hacky-ness, but the fact that jOOQ's API clearly communicates that this type is internal by means of package private visibility at least communicates to the 99% of users that depending on such internals is a mistake.

So, no. The design of public vs private APIs is sound in jOOQ, that's not going to change. I'm open to discussing your *actual* problem, but visibility isn't negotiable. Anyway, the suggestion you made is already implemented in jOOQ 3.15.0 via #3185, so there's no need for further action.

**Comment by lukaseder** [comment] 2022-03-17 08:13
> @lukaseder Upgrading to latest did not magically add `async` method for these... What am I missing?

I don't know what you're missing, you didn't show your code. This compiles:

```java
ctx.insertInto(table("t")).values(1).returning().fetchAsync()
```

So, what's not working for you?

**Comment by lukaseder** [comment] 2022-03-17 08:14
By the way, if by "coroutines" you mean kotlin's coroutines, starting from jOOQ 3.15, perhaps you can use the new R2DBC binding, as a `ResultQuery<R>` extends `Publisher<R>`, so the usual kotlin extensions to bind reactive streams to coroutines could work for you.

**Comment by danielgindi** [comment] 2022-03-17 08:17
> ```java
> .fetchAsync()
> ```

Seems like Gradle cache insists on serving the old version. Looking into it. Thanks!

**Comment by danielgindi** [comment] 2022-03-17 12:02
@lukaseder it also looks like spring-boot [prohibits](https://github.com/spring-projects/spring-boot/blob/db293ba26da842dbc324e86a77b26a398d05ee73/spring-boot-project/spring-boot-dependencies/build.gradle#L954) using jooq>=3.15, no matter how we try to override the bom.
This is apparently due to jooq now requiring Java 11. So we have to wait for the new spring version to be release in order to be allowed to use the new jooq. Frustrating.

A public `SQLResultQuery` would have helped a lot here just in order to create a workaround.

**Comment by lukaseder** [comment] 2022-03-17 16:08
> @lukaseder it also looks like spring-boot [prohibits](https://github.com/spring-projects/spring-boot/blob/db293ba26da842dbc324e86a77b26a398d05ee73/spring-boot-project/spring-boot-dependencies/build.gradle#L954) using jooq>=3.15, no matter how we try to override the bom.

I don't think you're reading this right? I'm not too well acquainted with gradle to know how to override this, but it's no problem at all in Maven:
https://github.com/jOOQ/jOOQ/blob/main/jOOQ-examples/jOOQ-spring-boot-example/pom.xml

Also, the commercial jOOQ distributions still support Java 8, so surely, there's *some* way to do this. I can't think of a good reason why Spring Boot would prevent our commercial customers from using jOOQ 3.16.

I might be able to help you if you can provide details, alternatively, why not ask Spring Boot for support?

> So we have to wait for the new spring version to be release in order to be allowed to use the new jooq. Frustrating.

I understand. jOOQ is one of the first libraries to have moved forward from Java 8, at least in the open source edition. This was a good move. And the move forward to require Java 17 will also be a good move in the future.

My personal belief here is that Spring Boot is doing this wrong. They should have found, by now, a better solution to baseline their JDK versions, because they can't impose such a baseline on all the third parties they integrate with. The same is true for numerous libraries by now, among which Jetty, I think?

You can find discussions here: https://github.com/spring-projects/spring-boot/issues/26439. You can try your luck convincing them that their fixed Java baseline isn't correct. Or, you can wait, obviously. But I'm positive there's a solution.

> A public `SQLResultQuery` would have helped a lot here just in order to create a workaround.

I understand that you're now frustrated. Upgrading dependencies can be a hassle. And now you just want a "quick win," and move on.

But I can only tell you once more that asking a library to open up all of its internals is the wrong path (you're asking for one type, but there's no difference between opening this one and everyone else asking for opening up the other ones). There are very good reasons for internals to be package private. Just look at the mess created by `sun.misc.Unsafe` in the JDK. It has always been internal (but accessible), so people abused it, and complained when Oracle changed it.

I still don't know what workaround specific to this class you're talking about, you haven't really shared much from what you've tried, and why you think this particular change would have been a game changer, but please do understand, that maintaining a library as complex as jOOQ can only be successful if we don't get lured into such hackery. Encapsulation is a great feature and we make a lot of use of it. The very upgrade we're discussing here (https://github.com/jOOQ/jOOQ/issues/3185) would have never been possible to pull off in a somewhat backwards compatible way if we had opened up our internals. It is *because* of internals being all package private that a huge refactoring like this was possible, almost without breaking *any* client code.

**Comment by danielgindi** [comment] 2022-03-17 21:21
> I don't think you're reading this right? I'm not too well acquainted with gradle to know how to override this, but it's no problem at all in Maven:
Sadly, I am.
However, I did manage to force it to use my specified version- by manipulating the gradle cache files as it syncs. Then it decided on taking the latest version- but then we had some missing classes in Spring. There's a reason they prohibited it from 3.15 and above (than open bracket with the comma means an open range).


> I might be able to help you if you can provide details, alternatively, why not ask Spring Boot for support?
There is a version they're working on which seems to support this, it looks like it will be in 2.7.x or 3.x, if I'm reading their commit list correctly.  
About details, there's not much to provide, the situation is pretty simple with an Insert statement + returning.
We do not want blocking io of course.
I ended up working around it by taking the generated sql, and executing on the DSLContext itself.



> I understand. jOOQ is one of the first libraries to have moved forward from Java 8, at least in the open source edition. This was a good move. And the move forward to require Java 17 will also be a good move in the future.

I do not blame you :) Sticking to the old java versions is pointless and counterproductive.

> My personal belief here is that Spring Boot is doing this wrong. 
Not only that 😂


> But I can only tell you once more that asking a library to open up all of its internals is the wrong path (you're asking for one type, but there's no difference between opening this one and everyone else asking for opening up the other ones). There are very good reasons for internals to be package private. Just look at the mess created by `sun.misc.Unsafe` in the JDK. It has always been internal (but accessible), so people abused it, and complained when Oracle changed it.
You are correct about that. What I was referring to is not specifically opening up that class, but having some generic way for applying workarounds when needed. I did find a way eventually, stupid me did not think about going to the context we're already using...
In some other cases I've created async fetch versions by taking a stream and using it with FluxCollector, which allowed me to replicate the synchronous fetch counterparts.
 

Thanks for all your time!

**Comment by lukaseder** [comment] 2022-03-18 07:54
> However, I did manage to force it to use my specified version- by manipulating the gradle cache files as it syncs. Then it decided on taking the latest version- but then we had some missing classes in Spring.

You could document your approach on https://stackoverflow.com, so others can find it, and your own answer (it's OK to answer your own question: https://stackoverflow.blog/2011/07/01/its-ok-to-ask-and-answer-your-own-questions/). Also, perhaps, someone will be able to help you with an even better solution

> There's a reason they prohibited it from 3.15 and above (than open bracket with the comma means an open range).

The reason is they can't handle third party baselines larger than Java 8, which is a mistake IMO, but apparently can't be fixed easily.

> I ended up working around it by taking the generated sql, and executing on the DSLContext itself.

Yeah that always works :)

> I do not blame you :) Sticking to the old java versions is pointless and counterproductive.

That's not how I meant it. It makes sense to support older versions. We'll support Java 8 for our commercial customers for quite a while into the future.

Every upgrade is a risk, as you have seen here, now, because it ripples through the dependency tree and causes many side-effects, keeping you from doing actually productive work. (E.g. jOOQ 3.16 switched from `javax` to `jakarta` namespaces, which is also very painful for everyone who has been postponing this upgrade)

But a *platform* whose purpose is to manage third party libraries should have a better strategy of dealing with the third party libraries' JDK requirements and baselines.

We've lived in a period where everyone mystically agreed that Java 8 was a reasonable baseline, mostly because Java 9 took Oracle forever to make and didn't offer anything anyone wanted (modules were more of a hassle at first). But then, every release added new useful features to the language and the JDK, such that people will upgrade more eagerly, especially with Java 16 records.

There's no longer a "reasonable universal baseline". Any baseline is equally good. This means that Spring Boot (and all the others, e.g. Quarkus, Micronaut, etc.) need to have a better strategy of dealing with third party baselines. They can't just say "We don't support the last 3 releases of third party XYZ, because...".

Anyway, explaining this here won't fix it. :) I'll eventually try my luck with the Spring Boot folks again, though this year, they'll increase their own baseline to 17, so maybe, they can postpone their own problems in this area for now: https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6

> > My personal belief here is that Spring Boot is doing this wrong.
> 
> Not only that 😂

What do you have in mind?

> You are correct about that. What I was referring to is not specifically opening up that class, but having some generic way for applying workarounds when needed

The generic way is always plain SQL templating, which you have found yourself: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating
