### ISSUE TITLE
Error in where clause when using multiset

### ISSUE THREAD

**Issue by oclay1st** [jOOQ/jOOQ#12300] opened 2021-08-12 15:16 UTC
### Expected behavior
It sould retrive the film title with list of actors and film categories

### Actual behavior
It is rasing an SQLSyntaxException:
```
2021-08-12 11:00:58.462  INFO 11585 --- [nio-8080-exec-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2021-08-12 11:00:58.571 ERROR 11585 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [set @t = @@group_concat_max_len; set @@group_concat_max_len = 4294967295; select `sakila`.`film`.`title`, (select coalesce(json_merge_preserve('[]', concat('[', group_concat(json_array(`v0`, `v1`) separator ','), ']')), json_array()) from (select `sakila`.`actor`.`first_name` as `v0`, `sakila`.`actor`.`last_name` as `v1` from `sakila`.`actor` join `sakila`.`film_actor` using (`actor_id`) where `sakila`.`film_actor`.`film_id` = `sakila`.`film`.`film_id`) as `t`) as `actors`, (select coalesce(json_merge_preserve('[]', concat('[', group_concat(json_array(`v0`) separator ','), ']')), json_array()) from (select `sakila`.`category`.`name` as `v0` from `sakila`.`category` join `sakila`.`film_category` using (`category_id`) where `sakila`.`film_category`.`film_id` = `sakila`.`film`.`film_id`) as `t`) as `films` from `sakila`.`film` order by `sakila`.`film`.`title`; set @@group_concat_max_len = @t;]; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'sakila.film.film_id' in 'where clause'] with root cause

java.sql.SQLSyntaxErrorException: Unknown column 'sakila.film.film_id' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.23.jar:8.0.23]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.23.jar:8.0.23]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.23.jar:8.0.23]
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370) ~[mysql-connector-java-8.0.23.jar:8.0.23]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar:na]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[jooq-3.15.0.jar:na]
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4070) ~[jooq-3.15.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:230) ~[jooq-3.15.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:335) ~[jooq-3.15.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284) ~[jooq-3.15.0.jar:na]
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2842) ~[jooq-3.15.0.jar:na]

```

### Steps to reproduce the problem
- steup the Sakila Database
- execute this code:
```
  var result =
                dsl.select(
                        FILM.TITLE,
                        multiset(
                                select(ACTOR.FIRST_NAME, ACTOR.LAST_NAME)
                                        .from(ACTOR)
                                        .join(FILM_ACTOR).using(ACTOR.ACTOR_ID)
                                        .where(FILM_ACTOR.FILM_ID.eq(FILM.FILM_ID))
                        ).as("actors"),
                        multiset(
                                select(CATEGORY.NAME)
                                        .from(CATEGORY)
                                        .join(FILM_CATEGORY).using(CATEGORY.CATEGORY_ID)
                                        .where(FILM_CATEGORY.FILM_ID.eq(FILM.FILM_ID))
                        ).as("films")
                )
                        .from(FILM)
                        .orderBy(FILM.TITLE)
                        .fetch();
```

### Versions

- jOOQ: 3.15.1
- Java: 11
- Database (include vendor): MySQL
- OS: Linux
- JDBC Driver (include name if inofficial driver): com.mysql.jdbc.Driver

**Comment by oclay1st** [comment] 2021-08-14 21:33
I'm using MySQL 5.7, now that I know about the related  issue I will wait for it to get fixed. Thanks @lukaseder for everything regarding JOOQ

**Comment by lukaseder** [comment] 2021-08-16 06:02
Closing as duplicate of #12045.

**Closed by lukaseder** 2021-08-16 06:02 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Duplicate, E: All Editions
