### ISSUE TITLE
Problem in code generation for entities with @Type(type = "jsonb") from hibernate-types-52 library

### ISSUE THREAD

**Issue by tmdomingues** [jOOQ/jOOQ#10723] opened 2020-10-08 14:26 UTC
### Expected behavior
 Upon executing the plugin _jooq-codegen-maven_ with the correct project structure as indicated in the jOOQ documentation, the expected generated classes from the existing project entities should be the following (e.g. for the sake of demonstration let´s use an entity called User):

1. Under the folder _/tables_ we should have a **User.java** 
2. Under folder _/tables/records_ we should have a **UserRecord.java**

### Actual behavior
In my case i wanted to use the Postgres **jsonb** data type for a String field, so using the types provided by the very useful library
```
       <dependency>
            <groupId>com.vladmihalcea</groupId>
            <artifactId>hibernate-types-52</artifactId>
           <version>2.9.10</version>
        </dependency>
```
we get an example similar to the one below for the User entity. Configured like this, this entity **will not** have the expected classes (User and UserRecord) derived the execution of the _jooq-codegen-maven_ plugin.

```
@Entity
@Table(name = "user", schema = "schema1")
@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class) // By removing this jOOQ generated expected classes
public class User { 

 // (...)

@Type(type = "jsonb") // By removing this jOOQ generated expected classes
@Column(name = "elements", columnDefinition = "jsonb")
private String elements;

}
```

**Summary**: Let´s say i have 10 entities and 2 annotated like the example above, so these are excluded(or a silent error occurs) from code generation so i get 8 entities being processed correctly and respective classes generated.
When i removed the annotations i got a 10 out of 10.

### Steps to reproduce the problem

- An entity with a String field annotated with the annotations indicated above
- Execute jooq-codegen-maven with the desired configurations and structure (in my case the database was org.jooq.meta.extensions.jpa.JPADatabase)

### Versions

- jOOQ (3.13.5):
- Java (8):
- Database (Postgres 10):
- OS (macOS Catalina:
- JDBC Driver (spring-jdbc from spring Spring boot 2.3.3.RELEASE):

**Comment by lukaseder** [comment] 2020-10-08 14:57
Thanks a lot for your report. I'll try to reproduce this. Do you get any exceptions / stack traces in your logs?

**Comment by lukaseder** [comment] 2020-10-09 09:13
OK, I can reproduce it. There are no exceptions or other traces in the logs:

```
11:05:46,210 [INFO] --- jooq-codegen-maven:3.14.0-SNAPSHOT:generate (generate-jpadatabase) @ jooq-test-codegen ---
Okt. 09, 2020 11:05:47 VORM. org.hibernate.Version logVersion
INFO: HHH000412: Hibernate Core {5.4.10.Final}
Okt. 09, 2020 11:05:47 VORM. org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
Okt. 09, 2020 11:05:47 VORM. org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
Okt. 09, 2020 11:05:47 VORM. org.hibernate.resource.beans.spi.ManagedBeanRegistryInitiator resolveBeanContainer
INFO: HHH10005002: No explicit CDI BeanManager reference was passed to Hibernate, but CDI is available on the Hibernate ClassLoader.
Okt. 09, 2020 11:05:47 VORM. org.hibernate.tool.hbm2ddl.SchemaExport execute
INFO: HHH000227: Running hbm2ddl schema export
Okt. 09, 2020 11:05:48 VORM. org.hibernate.jpa.internal.util.LogHelper logPersistenceUnitInformation
INFO: HHH000204: Processing PersistenceUnitInfo [name: AttributeConverterExtractor]
Okt. 09, 2020 11:05:48 VORM. org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
Okt. 09, 2020 11:05:48 VORM. org.hibernate.resource.beans.spi.ManagedBeanRegistryInitiator resolveBeanContainer
INFO: HHH10005002: No explicit CDI BeanManager reference was passed to Hibernate, but CDI is available on the Hibernate ClassLoader.
Okt. 09, 2020 11:05:48 VORM. org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator initiateService
INFO: HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
```

I don't know Hibernate well enough to assess whether there should be any information with respect to why this table isn't being generated.

The problem seems to be that we're currently using an in-memory H2 database behind the scenes to run the Hibernate generated DDL on. H2 doesn't support a JSONB type, but the `JSON` type (from Vlad's `JsonStringType`) seems to be supported, see http://h2database.com/html/datatypes.html#json_type

In the future, we'll interpret the DDL generated by Hibernate for your actual target dialect (e.g. PostgreSQL), instead of passing by H2, but we're not there yet.

I think we'll have to live with the "known" limitation of the current implementation - I currently don't see an easy way to work around it.

**Comment by lukaseder** [comment] 2020-10-09 09:24
This will be fixed in a future version, when we can either interpret the DDL, or run it on an actual PostgreSQL database, e.g. using testcontainers: https://github.com/jOOQ/jOOQ/issues/6551. I'll revisit this issue to make sure this is fixed in one way or another.

**Comment by tmdomingues** [comment] 2020-10-09 10:53
Great...Thanks for the feedback.

**Comment by lukaseder** [comment] 2022-03-08 16:27
Revisiting this. The testcontainers (TC) based approach is probably the best here. Some manual plumbing might be needed to export the entities into the TC database prior to running jOOQ's code generator. Some ideas here: https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

**Closed by lukaseder** 2022-03-08 16:27 UTC
Labels: T: Defect, C: Code Generation, P: Medium, R: Wontfix, E: All Editions
