### ISSUE TITLE
SQL Translation Error (from PostgreSQL to SQL Server 2017)

### ISSUE THREAD

**Issue by egemenvardar** [jOOQ/jOOQ#8084] opened 2018-12-04 10:37 UTC
SQL translator gives an error while translating this query written in PostgreSQL to SQL Server 2017:

```sql
CREATE TABLE credit
(
  id              serial PRIMARY KEY,
  type_id         int                                              NOT NULL,
  amount          int                                              NOT NULL,
  person_id       int                                              NOT NULL,
  rental_id       int,
  subscription_id int,
  creator         text                                             NOT NULL,
  reason          text                                             NOT NULL,
  remark          text,
  created         timestamp DEFAULT timezone('UTC'::text, now()) NOT NULL,
  last_updated    timestamp DEFAULT timezone('UTC'::text, now()) NOT NULL
);
```

Here is the parser error:
```
Token ')' expected: [12:59] ...d         timestamp DEFAULT timezone('UTC' :: text[*], now()) NOT NULL,
last_updated    timestamp DEFAULT timezone('UTC' :: text, n...
```

Please note that the query was tested with PostgreSQL 9.6. 

p.s. Thanks for this amazing tool!

**Comment by lukaseder** [comment] 2018-12-04 10:59
Thanks a lot for your nice words. I'm glad to hear you find the tool useful to translate your SQL code.

Interesting use case - why are you not using PostgreSQL's `timestamp with time zone` data type instead? It is essentially a UTC timestamp, which guarantees the behaviour you're probably trying to emulate using the `timezone()` function.

In any case, we should support that function (#8085) as well as the `AT TIME ZONE` syntax (#7238)

**Comment by egemenvardar** [comment] 2018-12-04 11:57
Thanks for creating the follow-up issue.

I think it's just a convention in this project. The first person who wrote the defaults like that probably wanted to show it explicitly that all timestamps in the database are UTC. We later did stick to the same convention (though I agree that `timestamp with time zone DEFAULT now()` would be nicer).

**Comment by lukaseder** [comment] 2019-10-02 12:08
Closing this as a duplicate of issues #8085, #7238

**Closed by lukaseder** 2019-10-02 12:08 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Duplicate, T: Defect
