### ISSUE TITLE
Feedback about translation tool

### ISSUE THREAD

**Issue by onovikov16** [jOOQ/jOOQ#14483] opened 2023-01-11 10:28 UTC
Thank you so much for this tool. 
Would you please add translation from ORACLE a || b to PG concat(a, b) ?

Kind regards,
Novikov Oleg

**Comment by lukaseder** [comment] 2023-01-11 10:33
Thank you very much for your feature request.

Why would you prefer the `concat()` function over the `||` expression?

Note, while you cannot influence the output of the online translator (https://www.jooq.org/translate), this kind of syntax replacement should be easy if you're using the translator programmatically, using the pattern replacement feature:
https://www.jooq.org/doc/latest/manual/sql-building/model-api/model-api-replacement/

**Comment by onovikov16** [comment] 2023-01-11 12:11
Thank you for your answer!I prefer concat(), because of'X'||null in oracle results 'X'in PG it results nullSo I have to use concat()Is it possible to add  concat() in your web tool, if destination is PG ?Kind regards, Oleg Novikov14:34, 11 января 2023 г., Lukas Eder ***@***.***>:
Thank you very much for your feature request.
Why would you prefer the concat() function over the || expression?
Note, while you cannot influence the output of the online translator (https://www.jooq.org/translate), this kind of syntax replacement should be easy if you're using the translator programmatically, using the pattern replacement feature:
https://www.jooq.org/doc/latest/manual/sql-building/model-api/model-api-replacement/

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by lukaseder** [comment] 2023-01-11 12:20
Thanks for your explanation. I understand the use-case. We'll consider it in the future: https://github.com/jOOQ/jOOQ/issues/14485

I cannot promise when this will be implemented. The best immediate workaround is to use the mentioned programmatic approach.

I'm closing this issue as a duplicate of https://github.com/jOOQ/jOOQ/issues/14485, which will track the compatibility more generally than just for the online translator.

Thanks again for your feature request!

**Closed by lukaseder** 2023-01-11 12:20 UTC
Labels: T: Enhancement, P: Medium, R: Feedback Pending, E: All Editions, C: Translator
