### ISSUE TITLE
OnDuplicateKeyIgnore ignores every insertable

### ISSUE THREAD

**Issue by SzabKel** [jOOQ/jOOQ#7596] opened 2018-06-19 14:31 UTC
I am using a batch function to insert rows and would also like to ignore duplicates. Calling code:
```java
@Override
public BatchInsertResultDTO insertIgnore(List<R> dtos) {
	if (dtos.size() < 1)
		return BatchInsertResultDTO.empty();
	List<Field<?>> fields = dtos.get(0).insertFields();
	try {
		Loader<Record> execute = DSL.loadInto(table)
				.onDuplicateKeyIgnore()
				.loadArrays(dtos.stream().map(mn -> mn.asInsertArray())) // <-- Returns a 
												// Stream<Object[]> where the Object array
												// matches the fields
				.fields(fields) // <-- Got a List<Field<?>> in a matching order for the objects 
								// 		i am inserting. 
				.execute();
		return BatchInsertResultDTO.from(execute);
	} catch (IOException e) {
		throw new BatchInsertIgnoreException(e);
	}
}
```
Even though it should ignore rows only if there is a duplicate (based on a unique index or PK) it ignores everything (I can insert manually without problem). 

~~If I change the `onDuplicateKeyIgnore` to `onDuplicateKeyUpdate` the code works, but will update every time.~~ No I tested it again, and the Update will throw a duplicate key error.

Using this table:
```sql
create table web.pub_manufacturername
(
	id bigserial not null
		constraint pub_manufacturername_pkey
			primary key,
	"createdAt" timestamp(6) with time zone default CURRENT_TIMESTAMP not null,
	"updatedAt" timestamp(6) with time zone,
	name varchar(255) not null
		constraint pub_manufacturername_name_key
			unique
)
;
```

### Versions:
- Spring 2.0.2.RELEASE
- jOOQ: 3.10.7
- Java: Compiling 1.8 on version "10.0.1" 2018-04-17
- Database (include vendor):  PostgreSQL-10.4-1-win64-bigsql
- OS: Windows Server 2016 for db, Win10 1709 for dev
- JDBC Driver (include name if inofficial driver): org.postgresql 42.2.2

**Comment by SzabKel** [comment] 2018-06-19 14:33
I tried to figure out the problem myself, this seems possibly problematic:
![jooq-onduplicatekeyignore-1](https://user-images.githubusercontent.com/3736434/41604036-879922e4-73de-11e8-9d14-2cf0bf65f22c.jpg)

**Comment by lukaseder** [comment] 2018-06-26 11:48
Thanks for your report. The key problem in your displayed screenshot is the fact that there's not predicate looking for a specific primary key value. Why is that the case? How can it be reproduced? What's the content of your arrays / fields? Are you passing the primary key column as well?

**Comment by SzabKel** [comment] 2018-06-26 11:57
@lukaseder This is supposed to work as an insert ignore, so I do not pass in primary keys. The fields simply get the table's field objects:
```
   private static final PubManufacturername PMN = PubManufacturername.PUB_MANUFACTURERNAME;
   @Override
    public List<Field<?>> insertFields() {
        return Arrays.asList(
                PMN.NAME
        );
    }
```

The insert objects:

```
    @Override
    public Object[] asInsertArray() {
        return new Object[]{
                name().toUpperCase()
        };
    }
```

In this case.

**Comment by lukaseder** [comment] 2018-06-26 13:10
Oh, I see - so you're not actually passing the primary key, only the name (which has a unique key). Then, this is probably the same issue as this one that got fixed recently: https://github.com/jOOQ/jOOQ/issues/6462, except that your issue deals with the `Loader` API, not the ordinary `INSERT` API

**Comment by lukaseder** [comment] 2018-06-26 13:10
... will try to reproduce this soon. Thanks again for reporting!

**Comment by nkhatwani-unicommerce** [comment] 2020-01-06 14:11
I am able to reproduce this issue, refer steps below, not passing primary key but passing unique key column. Enabled jooq sql logging as per [https://stackoverflow.com/questions/11026214/how-can-one-see-the-sql-statements-that-jooq-executes](url). It is not executing an "INSERT IGNORE" 

Could you please suggest some workaround for this in the current release as we urgently need to use loader api with "insert ignore" mysql query.

**Schema**
`CREATE TABLE `author` (
    `id` int AUTO_INCREMENT PRIMARY KEY,
    `first_name` varchar(255)  NOT NULL,
     `last_name` varchar(255)  NOT NULL,
     UNIQUE KEY `code_first_name` (`first_name`)
   );`

**Code**
[https://gist.github.com/nkhatwani-unicommerce/95518b64869504eea83ee389e84ee949](url)

**Debug log output**
[main] DEBUG org.jooq.tools.LoggerListener  - Executing query          : select 1 as `one` from dual where exists (select `jooq_test`.`author`.`id`, `jooq_test`.`author`.`first_name`, `jooq_test`.`author`.`last_name` from `jooq_test`.`author` where `jooq_test`.`author`.`id` = ?)
[main] DEBUG org.jooq.tools.LoggerListener  - -> with bind values      : select 1 as `one` from dual where exists (select `jooq_test`.`author`.`id`, `jooq_test`.`author`.`first_name`, `jooq_test`.`author`.`last_name` from `jooq_test`.`author` where `jooq_test`.`author`.`id` = null)
[main] DEBUG org.jooq.tools.StopWatch  - Query executed           : Total: 22.496ms
[main] DEBUG org.jooq.tools.StopWatch  - Finishing                : Total: 42.663ms, +20.167ms
[main] DEBUG org.jooq.tools.LoggerListener  - Fetched result           : +----+
[main] DEBUG org.jooq.tools.LoggerListener  -                          : | one|
[main] DEBUG org.jooq.tools.LoggerListener  -                          : +----+
[main] DEBUG org.jooq.tools.LoggerListener  - Executing query          : **insert into** `jooq_test`.`author` (`id`, `first_name`, `last_name`) values (?, ?, ?)
[main] DEBUG org.jooq.tools.LoggerListener  - -> with bind values      **: insert into** `jooq_test`.`author` (`id`, `first_name`, `last_name`) values (null, 'Hellow', 'World')
[main] DEBUG org.jooq.tools.LoggerListener  - Affected row(s)          : 1
[main] DEBUG org.jooq.tools.StopWatch  - Query executed           : Total: 2.259ms

**Comment by nkhatwani-unicommerce** [comment] 2020-01-06 16:38
@SzabKel @lukaseder Could you please suggest any workarounds for using loading csv using "insert ignore" with MySQL until this issue is fixed?

**Comment by knutwannheden** [comment] 2020-01-09 08:35
It seems like it should be possible to change the loader to simply call `InsertQuery#onDuplicateKeyIgnore()` rather than doing its own thing with an additional query.

@lukaseder What is your take on this?

**Comment by lukaseder** [comment] 2020-01-10 12:33
Will have a look next week

**Comment by lukaseder** [comment] 2020-01-14 10:29
> It seems like it should be possible to change the loader to simply call `InsertQuery#onDuplicateKeyIgnore()` rather than doing its own thing with an additional query.

I'm not sure if it will be easy to have an opinion here. It seems that using `onDuplicateKeyIgnore()` should work, but then there are equally justified complaints about `INSERT IGNORE` not being *exactly* what jOOQ seems to promise: https://github.com/jOOQ/jOOQ/issues/5211

Changing the behaviour might break other assumptions that we haven't discussed yet.

> @SzabKel @lukaseder Could you please suggest any workarounds for using loading csv using "insert ignore" with MySQL until this issue is fixed?

The workaround is to implement your own "loader". The jOOQ `Loader` API is mere convenience on top of other jOOQ API. Using `InsertQuery::onDuplicateKeyIgnore` directly is straight forward.

I cannot think of a better workaround right now.

**Comment by lukaseder** [comment] 2020-07-03 14:21
This is probably a duplicate of https://github.com/jOOQ/jOOQ/issues/5200

**Closed by lukaseder** 2020-07-03 14:21 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect
