### ISSUE TITLE
<outputSchemaDefault></outputSchemaDefault> not compatible with jooq version 3.12

### ISSUE THREAD

**Issue by shreyabaid007** [jOOQ/jOOQ#9341] opened 2019-10-09 05:24 UTC
### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by knutwannheden** [comment] 2019-10-09 06:12
Thanks for your report. Would you be able to add a little bit more details? I am assuming you are having  problems with `<outputSchemaToDefault>true</outputSchemaToDefault>` and in #3018 you mention:

> ... jooq codegen is unable to convert enums

Would you be able to expand a little bit on that to help us reproduce the problem?

**Comment by lukaseder** [comment] 2020-06-09 13:20
Closing this as "works for me". The issue description does not explain what problem we're seeing here.

**Closed by lukaseder** 2020-06-09 13:20 UTC
Labels: C: Code Generation, E: All Editions, P: Medium, R: Worksforme, T: Defect
