### ISSUE TITLE
Regression in fetchCount execution when argument query uses plain SQL tables

### ISSUE THREAD

**Issue by codylerum** [jOOQ/jOOQ#16392] opened 2024-02-29 20:29 UTC
### Expected behavior

The following existing query was working in 3.19.3, but after upgrading to 3.19.5 it throws an exception

```
 Condition billDate_between = SubscriberCall.FIELD_BILL_DATE.between(Date.valueOf(period.getStart()), Date.valueOf(period.getEnd()));
        Condition billingCode_eq = SubscriberCall.FIELD_BILLING_ACCOUNT.eq(billingAccount.id());
        Condition type_eq = SubscriberCall.FIELD_TYPE.eq(type.uByteValue());
        Condition billableTrue = SubscriberCall.FIELD_BILLABLE.isTrue();
        try (Connection connection = callDataDB.getConnection()) {
            final DSLContext dslContext = DSL.using(connection, SQLDialect.MYSQL);
            final SelectQuery<Record> query = dslContext.selectQuery();
            query.addFrom(SubscriberCall.TABLE);
            query.addConditions(billDate_between, type_eq, billingCode_eq, billableTrue);
            return dslContext.fetchCount(query);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
```

### Actual behavior

Exception Raised

```
org.jooq.exception.DataAccessException: SQL [select count(*) as `c` from (select * from SubscriberCall where (billDate between ? and ? and type = ? and billingAccount = ? and billable = true)) as `t` ()]; You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
    at org.jooq_3.19.5.MYSQL.debug
    at org.jooq.impl.Tools.translate(Tools.java:3553)
    at org.jooq.impl.Tools.translate(Tools.java:3541)
    at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:362)
    at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301)
    at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322)
    at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
    at org.jooq.impl.DefaultDSLContext.fetchCount(DefaultDSLContext.java:5125)
```

### Steps to reproduce the problem

Was able to work around the issue by changing to a fetch one with a DSL.count

```
     Condition billDate_between = SubscriberCall.FIELD_BILL_DATE.between(Date.valueOf(period.getStart()), Date.valueOf(period.getEnd()));
        Condition billingCode_eq = SubscriberCall.FIELD_BILLING_ACCOUNT.eq(billingAccount.id());
        Condition type_eq = SubscriberCall.FIELD_TYPE.eq(type.uByteValue());
        Condition billableTrue = SubscriberCall.FIELD_BILLABLE.isTrue();
        try (Connection connection = callDataDB.getConnection()) {
            final DSLContext dslContext = DSL.using(connection, SQLDialect.MYSQL);
            final SelectQuery<Record> query = dslContext.selectQuery();
            Field<Integer> callCount = DSL.count(SubscriberCall.FIELD_ID);
            query.addFrom(SubscriberCall.TABLE);
            query.addConditions(billDate_between, type_eq, billingCode_eq, billableTrue);
            query.addSelect(callCount);
            Record result = query.fetchOne();
            return result.getValue(callCount);
        }
        catch (SQLException e) {
            throw new RuntimeException(e);
        }
```

### jOOQ Version

3.19.5

### Database product and version

8.0.36 (MySQL Community Server - GPL)

### Java Version

OpenJDK Runtime Environment Corretto-17.0.10.7.1 (build 17.0.10+7-LTS)

### OS Version

OSX

### JDBC driver name and version (include name if unofficial driver)

mysql connector j 8.3.0

**Comment by lukaseder** [comment] 2024-03-01 07:52
Thanks for your report. This is most likely a regression due to:

- https://github.com/jOOQ/jOOQ/issues/16326

Will look into this right away.

**Comment by lukaseder** [comment] 2024-03-01 08:40
The regression is caused by this underlying problem:

- https://github.com/jOOQ/jOOQ/issues/16393

**Comment by lukaseder** [comment] 2024-03-01 08:50
Ah, I see now, this is because your query probably uses a plain SQL table, which doesn't have known fields associated with it. This is why #16393 is triggered. We didn't have this use-case in our integration tests, thus the regression.

Will fix this right away.

**Comment by lukaseder** [comment] 2024-03-01 09:08
Fixed in versions:

- 3.20.0
- 3.19.6 (https://github.com/jOOQ/jOOQ/issues/16397)
- 3.18.13 (https://github.com/jOOQ/jOOQ/issues/16398)
- 3.17.22 (https://github.com/jOOQ/jOOQ/issues/16399)

**Closed by lukaseder** 2024-03-01 09:08 UTC
Labels: T: Defect, C: Functionality, P: Urgent, R: Fixed, E: All Editions
