### ISSUE TITLE
Building fails when postgressql enum data is generated by KotlinGenerator

### ISSUE THREAD

**Issue by OhriY** [jOOQ/jOOQ#10891] opened 2020-11-08 08:35 UTC
### Expected behavior
I want to generate kotlin code from database using jooq codegen

### Actual behavior

I can generate kotlin code but this code  failed build

### Steps to reproduce the problem
-The reasons for the error are as follows
TestEnum.kt: (22, 63): Expecting member declaration

-The codes that are shown as actual errors are as follows. Kotlin's syntax doesn't seem to allow it.
 override fun getCatalog(): Catalog? = getSchema() == null ? null : getSchema().getCatalog()

-You can solve this problem by changing the above generated code to the following
override fun getCatalog(): Catalog? =  schema?.catalog

I'm attaching a program that reproduces the url.
Running docer-compose in the Postgresql folder and then running "jooq-codegen-primary" will generate unbuildable kotlin code

https://github.com/OhriY/jooq_enum_gen

### Versions

- jOOQ:3.14.1
- Java: 1.8
- Database (include vendor): 
- OS:wiondows 10
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2020-11-09 08:21
Thanks a lot for your report.

Duplicate of https://github.com/jOOQ/jOOQ/issues/10761

**Closed by lukaseder** 2020-11-09 08:21 UTC
Labels: C: Integration: Kotlin, E: All Editions, P: Medium, R: Duplicate, T: Defect

**Comment by OhriY** [comment] 2020-11-12 00:37
I'm sorry. I didn't realize it was a duplicate issue. Thank you for the answer.
