### ISSUE TITLE
Updating from 3.10.X to 3.12.X breaks

### ISSUE THREAD

**Issue by SElab2019** [jOOQ/jOOQ#9730] opened 2020-01-14 17:40 UTC
During my updating jooq from 3.10.0 to 3.12.3, the following code breaks.
```
import org.jooq.*;
import org.jooq.impl.DSL;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;


import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

public class JooqTest {

    private static File outputDir;
    @BeforeAll
    static void setupPaths() {
        outputDir = new File(JooqTest.class.getResource("/jooq").getFile()).getAbsoluteFile();
    }

    @Test
    void simpleQuery() throws Exception {
    
        try (
        		
            Connection con = DriverManager.getConnection("jdbc:mock:csv;path=" + outputDir.toString());
            DSLContext context = DSL.using(con)
        ) {
            Result<Record> records = context.select().from("mytable").fetch();
            assertThat(records.size(), is(equalTo(2)));
            assertThat(records.fields(),
                is(
                    arrayContaining(
                        hasProperty("name", equalTo("a")),
                        hasProperty("name", equalTo("b"))
                    )
                )
            );
        }
    }
}
```

The test should pass, but it failed with:
```
java.lang.UnsupportedOperationException: getDatabaseMajorVersion
	at JooqTest.simpleQuery(JooqTest.java:32)
```
There are two csv files used in this test, but I think it doesn't matter to the error.

**Comment by lukaseder** [comment] 2020-01-15 12:36
Thank you very much for your report.

I think there's some information missing here to be able to reproduce this case.

1. Your posted code does not call `getDatabaseMajorVersion()`, yet your stack trace hints at this being the case. Either your posted code was simplified too much, or you left out relevant bits of the stack trace
2. You seem to be using a third party library, which jOOQ does not officially support.

Can you please update your bug report with the above missing information and/or provide an example that helps reproduce your issue? Ideally, you would be using our suggested template for the purpose: https://github.com/jOOQ/jOOQ-mcve

**Comment by lukaseder** [comment] 2020-02-06 13:18
I'll close this issue for now, due to missing information. If you can provide the missing information, I'll be very happy to reopen and investigate this problem.

**Closed by lukaseder** 2020-02-06 13:18 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Invalid, T: Defect
