### ISSUE TITLE
Oracle 11g %ROWTYPE binding not working if %ROWTYPE is a SUBTYPE

### ISSUE THREAD

**Issue by DiabolusExMachina** [jOOQ/jOOQ#6734] opened 2017-10-23 10:57 UTC
Maybe I'm doing something wrong but I still cannot use procedures that use %ROWTYPE

My procedure 

```sql 
CREATE OR REPLACE PROCEDURE TECH.READ_MAIL(
  P_MAIL_ID     IN     MAIL_ENTRIES.MAIL_ID%TYPE,
  P_REC_MAIL       OUT MAIL_ENTRIES%ROWTYPE,
  P_RUP         IN OUT NOCOPY RUP_TYPES.T_PROTOKOLL,
  P_RC             OUT NUMBER)
IS
...
```
my jooq config 

```xml
<plugin>
        <groupId>org.jooq.pro</groupId>
        <artifactId>jooq-codegen-maven</artifactId>
        <configuration>
          <generator>
            <database>
              <includes>
               READ_MAIL <!--is a Package -->
                |  MAIL_ENTRIES <!--is a Table -->
                | RUP_TYPES <!--is a Package -->
                | RUNTIMEPROTOKOLLE  <!--is a Table -->
              </includes>
              <schemata>
                <schema>
                  <inputSchema>tech</inputSchema>
                </schema>
              </schemata>
            </database>
          </generator>
        </configuration>
```

### Expected behavior and actual behavior:
Expected: Generated Procedure class should not have parameter of type "Object"

Actual: Parameter P_REC_MAIL and  P_RUP  a type "Object" and their getters are marked as deprecated. 
(@deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.)

### Steps to reproduce the problem:
generate code from a Stored Procedure that uses %ROWTYPE Parameters
### Versions:

- jOOQ:3.10.1
- Java: jdk8
- Database (include vendor): Oracle 11g
- JDBC Driver ojdbc7

**Comment by lukaseder** [comment] 2017-10-23 14:34
Thank you very much for your report. I think the problem here is that the `%ROWTYPE` type name generated by jOOQ will be `<procedure_name>_<parameter_name>` You'll have to include that as well. Also, the `T_PROTOKOLL` type should be included. Could you try this instead:

```xml
              <includes>
               READ_MAIL.*
                |  MAIL_ENTRIES
                | RUP_TYPES.*
                | RUNTIMEPROTOKOLLE
              </includes>
```

Clearly, this whole topic deserves more documentation, of course...

**Comment by DiabolusExMachina** [comment] 2017-10-24 11:19
Hi ok one step further.  

Now the type is not object anymore. But I get runtime error if I try to call the procedure. I think the Problem is the  P_RUP  Parameter. That is a type in different package that also a rowtype

```sql 
SUBTYPE t_protokoll IS runtimeprotokolle%ROWTYPE;
```

This is the exception

> java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at de.cosmosdirekt.betrieb.App.main(App.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.jooq.exception.DataAccessException: SQL [null]; Error while writing value at JDBC bind index: 3
	at org.jooq_3.10.1.ORACLE.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2202)
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:127)
	at org.jooq.impl.UDTConstant.bind0(UDTConstant.java:175)
	at org.jooq.impl.UDTConstant.accept(UDTConstant.java:68)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:254)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:420)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:181)
	at org.jooq.impl.AbstractRoutine.bind1(AbstractRoutine.java:627)
	at org.jooq.impl.AbstractRoutine.bind0(AbstractRoutine.java:589)
	at org.jooq.impl.AbstractRoutine.accept(AbstractRoutine.java:532)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:254)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:420)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:181)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:469)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:340)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:317)
	at de.cosmosdirekt.betrieb.App.run(App.java:30)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
	... 11 common frames omitted
Caused by: java.sql.SQLException: Error while writing value at JDBC bind index: 3
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:67)
	at org.jooq.impl.AbstractBindContext.bindValue(AbstractBindContext.java:124)
	... 29 common frames omitted
Caused by: java.sql.SQLException: Deskriptor konnte nicht erstellt werden: Unable to resolve type "TECH.READ_MAIL_P_RUP"
	at oracle.sql.TypeDescriptor.getTypeDescriptor(TypeDescriptor.java:1042)
	at oracle.sql.StructDescriptor.isValidObject(StructDescriptor.java:89)
	at oracle.sql.StructDescriptor.createDescriptor(StructDescriptor.java:114)
	at oracle.sql.StructDescriptor.createDescriptor(StructDescriptor.java:74)
	at oracle.sql.STRUCT.toSTRUCT(STRUCT.java:534)
	at oracle.jdbc.driver.OraclePreparedStatement.setObjectCritical(OraclePreparedStatement.java:10467)
	at oracle.jdbc.driver.OraclePreparedStatement.setObjectInternal(OraclePreparedStatement.java:9966)
	at oracle.jdbc.driver.OraclePreparedStatement.setObjectInternal(OraclePreparedStatement.java:10799)
	at oracle.jdbc.driver.OracleCallableStatement.setObject(OracleCallableStatement.java:6097)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setObject(OraclePreparedStatementWrapper.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy85.setObject(Unknown Source)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.setObject(DefaultPreparedStatement.java:204)
	at org.jooq.impl.DefaultBinding.set(DefaultBinding.java:1282)
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:62)
	... 30 common frames omitted

**Comment by lukaseder** [comment] 2017-10-24 11:22
Thanks for the additional info. Will investigate. We indeed haven't covered this kind of `SUBTYPE` usage yet, so quite likely there's a bug related to that particular type usage.

**Comment by lukaseder** [comment] 2017-10-28 12:00
I'm trying to reproduce this, but couldn't so far, with a simple setup. I don't think it is related to the `SUBTYPE`. Are your types / procedures / packages in different schemas? Does your table `runtimeprotokolle` contain any user defined types? Is there a minimal example to reproduce this on your side?

In the meantime, I've found another, similar issue which will be fixed immediately: #6742

**Comment by DiabolusExMachina** [comment] 2017-11-09 11:47
Yes the procedure and the types (the one subtype) are in different packages. 

The table runtimeprotokolle looks normal to me. Number, Varchar2 and Date columns.

I will try to create a simple sample project and add it to this issue

**Comment by lukaseder** [comment] 2017-11-09 15:25
Thank you very much

**Comment by DiabolusExMachina** [comment] 2017-11-20 13:21
Sorry It took me a while. I was quite busy the last weeks. 

Here is an example spring boot application. In die sql folder you will find a create table script and a simple plsql procedure.

[jooq-rowtype-example.zip](https://github.com/jOOQ/jOOQ/files/1487748/jooq-rowtype-example.zip)


1.  Create them in a schema of your choice
2. change the properties in the pom.xml
 -  jdbc.url, jdbc.user, jdbc.password, oracle.schema
3.  run mvn clean install
4.  run the application: mvn spring-boot:run

Then you should get the following error: 

 

> Caused by: org.springframework.jdbc.UncategorizedSQLException: jOOQ; uncategorized SQLException for SQL [{ call "DEVSBNIS"."JOOQ_TEST"."SIMPLE_READ_TEST"(?, ?) }]; SQL state [99999];
> error code [17003]; Ung├╝ltiger Spaltenindex; nested exception is java.sql.SQLException: Ung├╝ltiger Spaltenindex
>         at org.jooq_3.10.1.DEFAULT.debug(Unknown Source) ~[na:na]
>         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:90) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
>         at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.translate(JooqExceptionTranslator.java:92) ~[spring-boot-autoconfigure-1.5.8.RELEASE.jar:1.5.8.RELEASE]
>         at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.handle(JooqExceptionTranslator.java:81) ~[spring-boot-autoconfigure-1.5.8.RELEASE.jar:1.5.8.RELEASE]
>         at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.exception(JooqExceptionTranslator.java:54) ~[spring-boot-autoconfigure-1.5.8.RELEASE.jar:1.5.8.RELEASE]
>         at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:219) ~[jooq-3.10.1.jar:na]
>         at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:503) ~[jooq-3.10.1.jar:na]
>         at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:340) ~[jooq-3.10.1.jar:na]
>         at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:317) ~[jooq-3.10.1.jar:na]
>         at de.jooq.test.App.run(App.java:26) [classes/:na]
>         at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
>         ... 12 common frames omitted
> Caused by: java.sql.SQLException: Ung├╝ltiger Spaltenindex
>         at oracle.jdbc.driver.OracleCallableStatement.registerOutParameterInternal(OracleCallableStatement.java:125) ~[ojdbc7-12.1.0.2.jar:na]
>         at oracle.jdbc.driver.OracleCallableStatement.registerOutParameter(OracleCallableStatement.java:335) ~[ojdbc7-12.1.0.2.jar:na]
>         at oracle.jdbc.driver.OracleCallableStatement.registerOutParameter(OracleCallableStatement.java:583) ~[ojdbc7-12.1.0.2.jar:na]
>         at oracle.jdbc.driver.OracleCallableStatementWrapper.registerOutParameter(OracleCallableStatementWrapper.java:1603) ~[ojdbc7-12.1.0.2.jar:na]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
>         at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc-8.5.23.jar:na]
>         at com.sun.proxy.$Proxy85.registerOutParameter(Unknown Source) ~[na:na]
>         at org.jooq.tools.jdbc.DefaultCallableStatement.registerOutParameter(DefaultCallableStatement.java:92) ~[jooq-3.10.1.jar:na]
>         at org.jooq.impl.DefaultBinding.register(DefaultBinding.java:939) ~[jooq-3.10.1.jar:na]
>         at org.jooq.impl.AbstractRoutine.registerRecordOutParameter(AbstractRoutine.java:1021) ~[jooq-3.10.1.jar:na]
>         at org.jooq.impl.AbstractRoutine.registerOutParameter(AbstractRoutine.java:1182) ~[jooq-3.10.1.jar:na]
>         at org.jooq.impl.AbstractRoutine.registerOutParameters(AbstractRoutine.java:1175) ~[jooq-3.10.1.jar:na]
>         at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:470) ~[jooq-3.10.1.jar:na]
>         ... 16 common frames omitted
> 
> 2017-11-20 14:15:32.717  INFO 10996 --- [           main] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@123c157f: startup date [Mon Nov 20 14:15:20 CET 2017]; root of context hierarchy
> 2017-11-20 14:15:32.717  INFO 10996 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
> [WARNING]
> java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:527)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.IllegalStateException: Failed to execute CommandLineRunner
>         at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735)
>         at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
>         at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
>         at de.jooq.test.App.main(App.java:33)
>         ... 6 more
> Caused by: org.springframework.jdbc.UncategorizedSQLException: jOOQ; uncategorized SQLException for SQL [{ call "DEVSBNIS"."JOOQ_TEST"."SIMPLE_READ_TEST"(?, ?) }]; SQL state [99999];
> error code [17003]; Ung³ltiger Spaltenindex; nested exception is java.sql.SQLException: Ung³ltiger Spaltenindex
>         at org.jooq_3.10.1.DEFAULT.debug(Unknown Source)
>         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:90)
>         at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.translate(JooqExceptionTranslator.java:92)
>         at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.handle(JooqExceptionTranslator.java:81)
>         at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.exception(JooqExceptionTranslator.java:54)
>         at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:219)
>         at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:503)
>         at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:340)
>         at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:317)
>         at de.jooq.test.App.run(App.java:26)
>         at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
>         ... 12 more
> Caused by: java.sql.SQLException: Ung³ltiger Spaltenindex
>         at oracle.jdbc.driver.OracleCallableStatement.registerOutParameterInternal(OracleCallableStatement.java:125)
>         at oracle.jdbc.driver.OracleCallableStatement.registerOutParameter(OracleCallableStatement.java:335)
>         at oracle.jdbc.driver.OracleCallableStatement.registerOutParameter(OracleCallableStatement.java:583)
>         at oracle.jdbc.driver.OracleCallableStatementWrapper.registerOutParameter(OracleCallableStatementWrapper.java:1603)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
>         at com.sun.proxy.$Proxy85.registerOutParameter(Unknown Source)
>         at org.jooq.tools.jdbc.DefaultCallableStatement.registerOutParameter(DefaultCallableStatement.java:92)
>         at org.jooq.impl.DefaultBinding.register(DefaultBinding.java:939)
>         at org.jooq.impl.AbstractRoutine.registerRecordOutParameter(AbstractRoutine.java:1021)
>         at org.jooq.impl.AbstractRoutine.registerOutParameter(AbstractRoutine.java:1182)
>         at org.jooq.impl.AbstractRoutine.registerOutParameters(AbstractRoutine.java:1175)
>         at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:470)
>         ... 16 more
>

**Comment by lukaseder** [comment] 2017-11-28 15:07
I'm sorry for the delay and thank you very much for the detailed report. I can reproduce this now. Will look into it immediately, hoping for a fix to be ready by tomorrow, when 3.10.2 should ship.

**Comment by lukaseder** [comment] 2017-11-28 15:30
While I can reproduce this with your specific Spring Boot setup, I cannot reproduce it using our integration test setup. Will look further into this...

**Comment by lukaseder** [comment] 2017-11-28 15:53
Hmm, I see. The JDBC string that is being generated in your test case is:

```
{ call "U6734"."JOOQ_TEST"."SIMPLE_READ_TEST"(?, ?) }
```

This obviously cannot work, as there's no way jOOQ can bind the ROWTYPE through JDBC directly. When adding the following line to your code:

```java
LOG.info("{}", create.dialect());
```

I'm getting:

```
2017-11-28 16:46:36.047  INFO 32484 --- [           main] de.jooq.test.App                         : DEFAULT
```

So, clearly the `SQLDialect` is not set up correctly. Here's an indication on how you should set up Spring Boot to work with jOOQ dialects:
https://stackoverflow.com/a/43167379/521799

Essentially, just add this line to `application.properties`:

```
spring.jooq.sql-dialect=Oracle
```

When adding the following line:

```
logging.level.org.jooq=DEBUG
```

You'll see the correct generated SQL string (formatting mine):

```sql
declare 
  type rowtype2 is record(
    "ID" number, 
    "TEXT" varchar2(500), 
    "ERSTELLT_VON" varchar2(20), 
    "ERSTELLUNGSZEITPUNKT" date, 
    "GEAENDERT_VON" varchar2(20), 
    "AENDERUNGSZEITPUNKT" date
  ); 
  "r2" rowtype2; 
begin 
  "U6734"."JOOQ_TEST"."SIMPLE_READ_TEST"(
    "P_ID" => ?, 
    "P_REC_TEST" => "r2"
  ); 
  ? := "r2"."ID"; 
  ? := "r2"."TEXT"; 
  ? := "r2"."ERSTELLT_VON"; 
  ? := "r2"."ERSTELLUNGSZEITPUNKT"; 
  ? := "r2"."GEAENDERT_VON"; 
  ? := "r2"."AENDERUNGSZEITPUNKT"; 
end;
```

**Closed by lukaseder** 2017-11-28 15:53 UTC
Labels: C: Code Generation, C: DB: Oracle, P: Medium, T: Support request

**Comment by DiabolusExMachina** [comment] 2017-12-05 11:23
Oh wow it works. We had set this property to "oracle" in our basis framework but the correct value was "Oracle"

**Comment by lukaseder** [comment] 2017-12-05 21:27
> We had set this property to "oracle" in our basis framework but the correct value was "Oracle"

Oh no, this kind of case sensitivity matters in this case? I wonder if this could be reported to spring boot...?
