### ISSUE TITLE
Settings.returnDefaultOnUpdatableRecord and Settings.returnComputedOnUpdatableRecord don't work for replacing embeddables

### ISSUE THREAD

**Issue by NorbertKawinski** [jOOQ/jOOQ#16114] opened 2024-01-20 22:03 UTC
### Expected behavior

jOOQ should include "DEFAULT" and "GENERATED" columns inside "RETURNING" clause when using embeddables:
```
insert into "mcve"."test" default values returning "mcve"."test"."id", "mcve"."test"."embeddable_column"
```

### Actual behavior

jOOQ omit "DEFAULT" and "GENERATED" columns inside "RETURNING" clause when using embeddables:
```
insert into "mcve"."test" default values returning "mcve"."test"."id"
```

### Steps to reproduce the problem

Enable embeddables generation:
```
<embeddableDomains>.*</embeddableDomains>
```

Create following schema:
```
CREATE DOMAIN mcve.CD AS INT;

CREATE TABLE mcve.test (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  cdsimple1 INT NOT NULL DEFAULT 1,
  cdsimple2 INT NOT NULL GENERATED ALWAYS AS (cdsimple1 + cdsimple1) STORED,

  cddomain1 mcve.CD NOT NULL DEFAULT 1,
  cddomain2 mcve.CD NOT NULL GENERATED ALWAYS AS (cdsimple1 + cdsimple1) STORED,

  CONSTRAINT pk_test PRIMARY KEY (id) 
);
```

Run following test:
```
    @Test
    public void mcveTest() {
        ctx.settings().setReturnDefaultOnUpdatableRecord(true);
        ctx.settings().setReturnComputedOnUpdatableRecord(true);
        var r = ctx.newRecord(TEST);
        r.store();

        // These 2 passes because they are simple types
        assertEquals(1, r.getCdsimple1().intValue());
        assertEquals(2, r.getCdsimple2().intValue());

        //r.refresh();

        // These 2 fail because they are domains
        assertEquals(1, r.getCddomain1().getValue().intValue());
        assertEquals(2, r.getCddomain2().getValue().intValue());
    }
```

### jOOQ Version

org.jooq.pro:jooq:3.19.1

### Database product and version

postgres:16.1-alpine Docker image

### Java Version

Openjdk 21.0.1

### OS Version

Microsoft Windows 11 Pro [10.0.22621 Build 22621]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by NorbertKawinski** [comment] 2024-01-20 22:05
You can find MCVE here: https://github.com/NorbertKawinski/jOOQ-mcve/tree/mcve-for-issue-16114

**Comment by lukaseder** [comment] 2024-01-22 12:04
Thanks a lot for your report and MCVE. I'll have a look at this soon. I've added the issue also to this list:

- https://github.com/jOOQ/jOOQ/issues/15892

**Comment by lukaseder** [comment] 2024-01-26 10:54
I can reproduce this problem. It's due to a wrong implementation of these flags, which don't check for embeddables. The `Settings.returnAllOnUpdatableRecord` works correctly (as a workaround).

**Comment by lukaseder** [comment] 2024-01-26 11:07
The issue isn't specific to `<embeddableDomains/>`. All embeddables that replace their underlying columns are affected.

**Comment by lukaseder** [comment] 2024-01-26 11:30
Fixed in versions:

- 3.20.0
- 3.19.4 (https://github.com/jOOQ/jOOQ/issues/16185)
- 3.18.11 (https://github.com/jOOQ/jOOQ/issues/16186)

This is a jOOQ 3.18 feature, so no backport to 3.17 is needed:

- https://github.com/jOOQ/jOOQ/issues/14573

Thanks again for your report!

**Closed by lukaseder** 2024-01-26 11:30 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: Professional Edition, E: Enterprise Edition

**Comment by lukaseder** [comment] 2024-01-26 11:43
Checked your MCVE. Before the fix (`org.jooq.pro:*:3.19.1`):

```
[ERROR] Errors:
[ERROR]   JavaTest.mcveTest:91 NullPointer Cannot invoke "org.jooq.mcve.java.postgres.embeddables.records.CdRecord.getValue()" because the return value of "org.jooq.mcve.java.postgres.tables.records.TestRecord.getCddomain1()" is null
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

After the fix (`org.jooq.trial:*:3.20.0-SNAPSHOT`):

```
[ERROR] Errors:
[ERROR]   JavaTest.mcveTest:92 NullPointer Cannot invoke "org.jooq.mcve.java.postgres.embeddables.records.CdRecord.getValue()" because the return value of "org.jooq.mcve.java.postgres.tables.records.TestRecord.getCddomain2()" is null
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

Though, that's a different bug, it seems. From the logs:

```
12:40:17,145 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : insert into "mcve"."test" default values returning "mcve"."test"."id", "mcve"."test"."cdsimple1", "mcve"."test"."cddomain1", "mcve"."test"."cdsimple2"
12:40:17,187 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched result           : +----+---------+----+---------+
12:40:17,187 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |  id|cdsimple1|cd  |cdsimple2|
12:40:17,187 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +----+---------+----+---------+
12:40:17,188 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |   1|        1|(1) |        2|
12:40:17,188 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +----+---------+----+---------+
12:40:17,188 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched row(s)           : 1
```

This probably happens because both embeddables are named `CD`, after the domain. I've created a new issue to track this:

- https://github.com/jOOQ/jOOQ/issues/16187

**Comment by lukaseder** [comment] 2024-01-26 11:43
(It's probably a different issue, because I suspect https://github.com/jOOQ/jOOQ/issues/16187 affects all `INSERT .. RETURNING` statements, while this one only affects those statements generated from `UpdatableRecord`).

**Comment by NorbertKawinski** [comment] 2024-01-26 14:26
Thank you very much for solving it! ❤️ 

And yeah, #16187 seems to be a different issue that accidentally happened in my MCVE.
