### ISSUE TITLE
Adding converter on forcedType inside of a multiset cause ClassCastException

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#17428] opened 2024-10-10 16:31 UTC
### Expected behavior

jOOQ should be able to do this just fine.

### Actual behavior

See the MCVE for details: https://github.com/jOOQ/jOOQ-mcve/compare/main...alf:jOOQ-mcve:double-converting

When running the `multisetWithConvertedForcedType` test it fails with the following message:

```
JavaTest.multisetWithConvertedForcedType:128 » DataAccess SQL [select (select coalesce(json_arrayagg(json_array(t."v0", t."v1" null on null returning clob) format json returning clob), json_array(returning clob)) from (select "MCVE"."TEST"."SOURCE_VALUE" "v0", "MCVE"."TEST"."SOURCE_VALUE" "v1" from "MCVE"."TEST") t) from (values (?), (?)) "t" ("a")]; Error while reading field: multiset(
  select
    "MCVE"."TEST"."SOURCE_VALUE",
    "MCVE"."TEST"."SOURCE_VALUE"
  from "MCVE"."TEST"
), at JDBC index: 1
```

The exception provides some more details:

```
org.jooq.mcve.test.java.oracle.JavaTest.multisetWithConvertedForcedType -- Time elapsed: 0.097 s <<< ERROR!
org.jooq.exception.DataAccessException: 
SQL [select (select coalesce(json_arrayagg(json_array(t."v0", t."v1" null on null returning clob) format json returning clob), json_array(returning clob)) from (select "MCVE"."TEST"."SOURCE_VALUE" "v0", "MCVE"."TEST"."SOURCE_VALUE" "v1" from "MCVE"."TEST") t) from (values (?), (?)) "t" ("a")]; Error while reading field: multiset(
  select
    "MCVE"."TEST"."SOURCE_VALUE",
    "MCVE"."TEST"."SOURCE_VALUE"
  from "MCVE"."TEST"
), at JDBC index: 1
        at org.jooq_3.19.13.ORACLE.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:3640)
        at org.jooq.impl.Tools.translate(Tools.java:3628)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:827)
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1405)
        at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1366)
        at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:174)
        at org.jooq.impl.Tools.fetchOne(Tools.java:2914)
        at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
        at org.jooq.mcve.test.java.oracle.JavaTest.multisetWithConvertedForcedType(JavaTest.java:128)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.sql.SQLException: Error while reading field: multiset(
  select
    "MCVE"."TEST"."SOURCE_VALUE",
    "MCVE"."TEST"."SOURCE_VALUE"
  from "MCVE"."TEST"
), at JDBC index: 1
        at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1592)
        at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1512)
        at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1433)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
        at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1390)
        ... 35 more
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: class org.jooq.mcve.test.java.oracle.SourceEnum cannot be cast to class java.lang.String (org.jooq.mcve.test.java.oracle.SourceEnum is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
        at org.jooq.impl.JSONReader.read(JSONReader.java:126)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultisetJSON(DefaultBinding.java:4511)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.lambda$readMultiset$1(DefaultBinding.java:4472)
        at org.jooq.impl.Tools.apply(Tools.java:2340)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:4470)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.readMultiset(DefaultBinding.java:4442)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:4435)
        at org.jooq.impl.DefaultBinding$DefaultResultBinding.get0(DefaultBinding.java:4413)
        at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1179)
        at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1582)
        ... 39 more
Caused by: java.lang.ClassCastException: class org.jooq.mcve.test.java.oracle.SourceEnum cannot be cast to class java.lang.String (org.jooq.mcve.test.java.oracle.SourceEnum is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
        at org.jooq.mcve.test.java.oracle.SourceEnumConverter.from(SourceEnumConverter.java:5)
        at org.jooq.ContextConverter$1.from(ContextConverter.java:147)
        at org.jooq.Converters.from(Converters.java:208)
        at org.jooq.impl.ConvertedDataType.convert(ConvertedDataType.java:313)
        at org.jooq.impl.Tools.setValue(Tools.java:3726)
        at org.jooq.impl.DefaultRecordUnmapper$IterableUnmapper.unmap(DefaultRecordUnmapper.java:174)
        at org.jooq.impl.DefaultRecordUnmapper.unmap(DefaultRecordUnmapper.java:110)
        at org.jooq.impl.AbstractRecord.from0(AbstractRecord.java:924)
        at org.jooq.impl.AbstractRecord.from(AbstractRecord.java:972)
        at org.jooq.impl.JSONReader.lambda$read$1(JSONReader.java:222)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
        at org.jooq.impl.JSONReader.read(JSONReader.java:221)
        at org.jooq.impl.JSONReader.read(JSONReader.java:123)
        ... 48 more
```
```

### Steps to reproduce the problem

See the MCVE

### jOOQ Version

3.19.13

### Database product and version

Oracle

### Java Version

_No response_

### JDBC / R2DBC driver name and version (include name if unofficial driver)

_No response_

**Comment by alf** [comment] 2024-10-15 15:23
Do you have any suggestions for an easy work around here?

**Comment by lukaseder** [comment] 2024-10-16 08:20
This looks like an instance of:

- https://github.com/jOOQ/jOOQ/issues/16013

The problem is that two converters are chained within a `MULTISET` expression, which is the source of this bug. If that's the case, then the workaround would be to avoid the double conversion from within the `MULTISET` expression. E.g. this works, as a workaround:

```java
var rec = ctx
    .select(
            DSL.select(
                TEST.SOURCE_VALUE,

                // Workaround here:
                row(TEST.SOURCE_VALUE).mapping(TargetEnum::fromSourceEnum)
                ).from(TEST).asMultiset())
        .from(values(row(1),
                     row(2)).as("t", "a"))

        // This works around a wrong test design (?)
        .limit(1)
        .fetchOne();

var row = rec.value1().get(0);
assertEquals(SourceEnum.ONE, row.value1());
assertEquals(TargetEnum.ONE, row.value2());
```

**Comment by lukaseder** [comment] 2024-10-16 09:54
Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/16013, which will be fixed with the next set of patch releases.

Thanks again for your report!

**Closed by lukaseder** 2024-10-16 09:54 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
