### ISSUE TITLE
Keeping the individual key columns in addition to the embedded key-column

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#13036] opened 2022-02-10 09:23 UTC
### Use case:

We use a lot of [natural keys](https://en.m.wikipedia.org/wiki/Natural_key)  in our database design. This means that most of our keys are composite, and that key columns are used both as keys but also as data. Since enabling embedded keys replaces the original columns, we can't really enable this functionality.

We could of course get the data from the embedded key, however this changes the access path and is thus a breaking change for us. 

### Possible solution you'd like to see:

A way to toggle the `<replacesFields>true</replacesFields>` option.

### Possible workarounds:

I'm currently re-implementing a lot of the key-handling functionality on my side. I would prefer to use embedded keys. 

### Versions:

- jOOQ: 3.15.5
- Java: 11
- Database (include vendor): Oracle

**Comment by lukaseder** [comment] 2022-02-10 09:35
Thanks for your feature request. Can you please describe:

- What does it mean for a key to "contain data"?
- How is this a problem with the current design of the feature?

**Comment by alf** [comment] 2022-02-10 10:22
I updated the request text. Sorry for being terse. Let me know if you need more input.

**Comment by lukaseder** [comment] 2022-02-10 10:44
Oh, I see, so this is only about trying to enable the feature without having to refactor the application where key component column references are used?

**Comment by alf** [comment] 2022-02-10 10:48
Part of it is that, but another part is discoverability. I fear that the columns in question will become less discoverable if they are moved into an embedded ID-field.

**Comment by lukaseder** [comment] 2022-02-10 10:48
What do you mean by that?

**Comment by lukaseder** [comment] 2022-02-10 15:24
Thanks for the clarifications. That makes sense. I don't disagree that there are benefits to keeping the original columns accessible. But I fear there must have been an important caveat (which I will have to reproduce again) that prevented this in the case of embeddable keys.

I'll investigate this and provide more feedback next week.

**Comment by lukaseder** [comment] 2024-09-12 09:22
Good things come to those who wait. It has become increasingly obvious that embeddables are really just emulated UDTs:

- https://github.com/jOOQ/jOOQ/issues/10525

jOOQ 3.19 introduced path based access to UDT members, just like you'd do that in Informix, Oracle, PostgreSQL:

- https://github.com/jOOQ/jOOQ/issues/228

The same path based access to embeddable members would address the issues mentioned here:

- https://github.com/jOOQ/jOOQ/issues/17177

Since an embeddable key is an emulation of a UDT type used as a key directly in the database, accessing key components through path syntax will feel natural.

I'm closing this as a duplicate of #17177

**Closed by lukaseder** 2024-09-12 09:22 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, E: All Editions

**Comment by lukaseder** [comment] 2024-12-11 10:49
A simpler solution that will be implemented sooner than #17177 is to mark underlying columns of embedded keys, etc. as `hidden` columns with the new jOOQ 3.20 `<hidden/>` feature:

- https://github.com/jOOQ/jOOQ/issues/13411
- https://github.com/jOOQ/jOOQ/issues/17761

The columns will be accessible via `Table.fieldsIncludingHidden().field("name")`, for example.
