### ISSUE TITLE
implement UpdatableRecord.merge

### ISSUE THREAD

**Issue by fjf2002** [jOOQ/jOOQ#9687] opened 2019-12-18 18:19 UTC
### Use case:
The `DSL.mergeInto` function is valuable.

Unfortunately `UpdatableRecord` does not offer such function.

### Possible solution you'd like to see:
Could you add something like (here in Kotlin code, untested):
```kotlin
fun <R : UpdatableRecord<R>> UpdatableRecord<R>.merge() =
    DSL.using(configuration())
        .mergeInto(this.table, *this.fields())
        .key(this.table.primaryKey.fields)
        .values(*this.intoArray())
        .execute()
```

### Versions:

- jOOQ: 3.12.3

**Comment by lukaseder** [comment] 2019-12-19 10:23
Thanks a lot for your suggestion. This is a recurring feature request, which I agree we should address, in the future. There is a bit more subtlety in the question what would be desireable versions of this. Mostly `MERGE` / `UPSERT` / `INSERT OR UPDATE` are requested, but `INSERT OR IGNORE` is also something people would like to see.

Closing this as a duplicate of #2961

**Closed by lukaseder** 2019-12-19 10:23 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Enhancement

**Comment by lukaseder** [comment] 2020-04-06 14:14
jOOQ 3.14 will support `UpdatableRecord.merge()`: #2961
