### ISSUE TITLE
jOOQ gets confused about (unique) indexes with non-unique names

### ISSUE THREAD

**Issue by retoo** [jOOQ/jOOQ#7820] opened 2018-08-27 13:56 UTC
We're using a SQL Server schema that apparently has non-unique index names. A lot of tables seem to have index names like `'$0'` or `'$1'`. 

jOOQ seems to get confused by that and groups together indices of different tables. This results `Internal.createUniqueKey` calls with a crazy long list of columns listed, mixed from a wide variety of tables. 

Version 3.11.4

The code generated looks like this
```java
		Internal.createUniqueKey(TABLE_A,
						"$8",
						TABLE_A.CUSTOMER.TYPE_OF_RELATION,
						TABLE_A.CUSTOMER.NO_,
						TABLE_B.CUSTOMER_NO_,
						TABLE_B.CURRENCY_CODE,
						TABLE_B.SHIP_TO_CODE,
						TABLE_B.CONTRACT_TYPE,
						TABLE_B.CONTRACT_NO_,
						TABLE_C.START_DATE,
						TABLE_C.END_DATE,
						TABLE_C.BILL_TO_CUSTOMER_NO_,
						TABLE_C.REMAINING_AMOUNT,
						TABLE_C.CONTRACT_NO_)
		);
```

see also the following screenshot: 
https://i.imgur.com/61Pdhlt.jpg

**Comment by lukaseder** [comment] 2018-08-27 14:48
Right, thanks for the pointer. And now, do you have a question about this? :-)

I'm assuming that you would like to exclude some of those indexes, right? Indeed, `<include/>` and `<exclude/>` do not match indexes or constraints yet. I thought there was a feature request but there isn't. I've created one: #7821. As a workaround, you could create a subclass of `org.jooq.meta.sqlserver.SQLServerDatabase` and override `getIndexes0()` to filter out undesired indexes.

Is there anything else that I'm missing?

**Comment by retoo** [comment] 2018-08-27 15:17
Right now the generated code does not compile (because the third parameter of createUniqueKey points to different tables, i think). We were just looking for a way to get rid of the compile errors, so we don't really care about indices/keys/uniqueKeys in our project here. 


(Right now we remove  the `Internal.createUniqueKey`calls using a perl script :D ..)

**Comment by lukaseder** [comment] 2018-08-27 15:52
Thanks for the explanation. Hmm, do you know how this can be reproduced?

> (Right now we remove the Internal.createUniqueKeycalls using a perl script :D ..)

There's always a way. :-) If you're using Maven, I've been happy with the `com.google.code.maven-replacer-plugin`

**Comment by retoo** [comment] 2018-08-27 16:10
thanks for the pointer, we ware able to suppress the generation of unique keys the following way:
```
public class REDACTEDServerDatabase extends SQLServerDatabase {
	@Override
	protected void loadUniqueKeys(final DefaultRelations relations) throws SQLException {
		// do nothing
        }
}

```

**Comment by lukaseder** [comment] 2018-08-28 12:08
Thanks a lot for the feedback. So the only thing left is to try to reproduce this.

**Comment by retoo** [comment] 2018-08-28 12:29
Lets see how often some names are used : 
```sql
SELECT index_name, count(*)
FROM (SELECT distinct t.name, ind.object_id, ind.name index_name
      FROM sys.indexes ind
                  INNER JOIN sys.index_columns ic ON ind.object_id = ic.object_id and ind.index_id = ic.index_id
                  INNER JOIN sys.columns col ON ic.object_id = col.object_id and ic.column_id = col.column_id
                  INNER JOIN sys.tables t ON ind.object_id = t.object_id
      WHERE t.name LIKE 'REDACTED_CUSTOMER_PREFIX$%') x

GROUP BY index_name
ORDER BY 2 DESC
```
(please ignore the distinct, i was too lazy to rewrite one of the joins to an where exists clause :D)

=> returns:

{code}
$1	372
$2	223
$3	138
$4	96
$5	72
$6	54
{code}

=> maybe just create a database with two tables which both an index that has the same name?

Does that help something?

**Comment by lukaseder** [comment] 2018-08-28 12:35
> (please ignore the distinct, i was too lazy to rewrite one of the joins to an where exists clause :D)

You are excused. In fact, I think this is the same issue as https://github.com/jOOQ/jOOQ/issues/5538, which is now resolved thanks to https://github.com/jOOQ/jOOQ/issues/7826. The fix is backwards incompatible in jOOQ-meta, which is why it won't be merged to 3.11. Given the workarounds, I think this is OK for now.

I will close this as a duplicate of #5538

**Closed by lukaseder** 2018-08-28 12:35 UTC
Labels: C: Code Generation, C: DB: SQL Server, E: All Editions, P: High, T: Defect

**Comment by retoo** [comment] 2018-08-28 12:49
Thank you so much! And thanks for the quick responses, it's fun to work together with you/Jooq!

**Comment by lukaseder** [comment] 2018-08-28 12:58
I'm glad to hear that
