### ISSUE TITLE
Wrong SQL generated in PostgreSQL when aliasing unnested arrays

### ISSUE THREAD

**Issue by ciaccia** [jOOQ/jOOQ#7671] opened 2018-07-16 13:07 UTC
DSL.unnest currently has two issues that should probably be addressed:
- The returned table has a generic `?` template (instead of something more specific like `Table<Record1<Long>>`)
- The returned table has an undocumented `COLUMN_VALUE` column

Consider the following code:

```java
Table<?> tbl = DSL.unnest(Arrays.asList(1L, 2L, 3L, 4L)).as("t", "v");
Result<?> res = dslCtx.selectFrom(tbl).fetch();
```
When rendered in Postgres, it produces an invalid SQL eventually resulting in a PSQLException:
```sql
select "t"."COLUMN_VALUE" from unnest(?::bigint[]) as "t"("v")
```

Theoretically, the returned table should have a defined template:
```java
Table<Record1<Long>> tbl = DSL.unnest(Arrays.asList(1L, 2L, 3L, 4L)).as("t", "v");
```
Furthermore, the rendered query should not contain `"COLUMN_VALUE"`.

A workaround for this issue is to manually add the columns to the select statement as following:
```java
Table<?> tbl = DSL.unnest(Arrays.asList(1L, 2L, 3L, 4L)).as("t", "v");
Result<?> res = dslCtx.select(DSL.field(DSL.name("t", "v"), Long.class)).from(tbl).fetch();
```

**Comment by lukaseder** [comment] 2018-07-20 09:12
> DSL.unnest currently has two issues that should probably be addressed:

We're not running out of ticket IDs any time soon, so that's totally a good use-case to create two separate issues :-) Since issues are used to track progress of bugs to be fixed, it's always a good idea to keep them focused on only one problem. The SQL being wrong is more likely to get fixed soon than the API returning an "unfortunate" type.

So, let's keep this issue focused on the SQL being wrong. Feel free to create another one that discusses typing.

**Comment by rouzwawi** [comment] 2020-03-25 18:31
I'm running into an issue with the forced column aliases when unnesting a UDT array field.

I end up having to write this in order to reference the "name" field of my `Tag` UDT. the `.as("tag", "name")` only works as long as the field I'm interested in is in the first position in the UDT, which feel a bit fragile.

```java
public static Condition containsTagNamesCondition(final Set<String> tagNames) {
  // note: the alias "name" refers to the first field in the Tag UDT which is the tag name
  final Table<?> tag = unnest(EXPERIMENT_REVISIONS.TAGS).as("tag", "name");
  final Field<?> nameField = DSL.field(DSL.name("tag", "name"));
  return exists(select(nameField).from(tag).where(nameField.in(tagNames)));
}
```

**Comment by lukaseder** [comment] 2022-10-18 09:20
This works now in jOOQ 3.18.0. DEBUG log output is:

```
Executing query          : select "t"."v" from unnest(cast(? as bigint[])) as "t" ("v") -- SQL rendered with a free trial version of jOOQ 3.18.0-SNAPSHOT
    -> with bind values      : select "t"."v" from unnest(cast('{"1","2","3","4"}' as bigint[])) as "t" ("v")
    Fetched result           : +----+
                             : |   v|
                             : +----+
                             : |   1|
                             : |   2|
                             : |   3|
                             : |   4|
                             : +----+
    Fetched row(s)           : 4
```

It was probably fixed with these:

- https://github.com/jOOQ/jOOQ/issues/8933
- https://github.com/jOOQ/jOOQ/issues/14074

Closing as duplicate of #8933

**Closed by lukaseder** 2022-10-18 09:20 UTC
Labels: T: Defect, C: Functionality, C: DB: PostgreSQL, P: Medium, E: All Editions
