### ISSUE TITLE
org.jooq.impl.ParserException: Boolean field expected

### ISSUE THREAD

**Issue by lalithsuresh** [jOOQ/jOOQ#10155] opened 2020-05-04 05:24 UTC
### Expected behavior and actual behavior:

I'm using H2 Arrays as follows (simplified example):

```
create table t1(c1 array);
create table t2(c1 varchar);

select * from t1 join t2 on array_contains(t1.c1, t2.c1);
```

This works when I run tests within my IDE (that directly talk to H2 over jdbc), but when the jooq parser and codegen (via maven) encounters such a query, I get a parsing exception `org.jooq.impl.ParserException: Boolean field expected`.

Is the H2 `array_contains` function not supported? If not, what's the cleanest way to rewrite this? I want to check if a value from one column exists within an array value from another column. 

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

See above.

### Versions:

- jOOQ: 3.13.1
- Java: openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

- Database (include vendor): H2 v1.4.200
- OS: OSX Mojave
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2020-05-05 07:30
Thank you very much for your report.

There are indeed a few vendor specific functions around arrays that jOOQ does not support in the parser nor in the API, yet. If you were using the DSL API only, then [plain SQL templating](https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/) would be the solution but this doesn't work with the parser yet (see e.g. #9447)

What's your use-case of using jOOQ's parser in this case?

**Comment by lalithsuresh** [comment] 2020-05-05 19:37
Thanks for the quick response @lukaseder . Yes, I'm able to use this via plain SQL templating in the DSL API.

I'm using JOOQ's code-gen via a maven plugin. In the input schema to the maven plugin, I had views of the form, which is what triggered the exception:

```
create view v1 as
select * from t1 join t2 on array_contains(t1.c1, t2.c1);
```

For now, my workaround is to instead use the following which seems to work with the JOOQ codegen:

```
create view v1 as
select * from t1 join t2 on  t2.c1 in (unnest(t1.c1));
```

As a sidenote, I found it hard to know what array functions are supported via the documentation.

**Comment by lukaseder** [comment] 2020-05-07 08:54
Oh, I see. Views are tricky for the `DDLDatabase`, of course, as they require more vendor specific feature support from the parser and the jOOQ API.

As a workaround, you could preprocess your SQL script prior to feeding it to the `DDLDatabase`, search-replacing expressions like these by `1 = 1` (which doesn't change much for the code generator). You could also use the parser ignore comments feature, and write your view like this:

```sql
create view v1 as
select * 
from t1 
  join t2 
    on true
    /* [jooq ignore start] */ and array_contains(t1.c1, t2.c1) /* [jooq ignore stop] */
;
```

See: https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-parser/

**Comment by lukaseder** [comment] 2020-05-07 09:05
We'll support a few array functions in the near future, also in the parser: https://github.com/jOOQ/jOOQ/issues/10175

We've already supported them for PostgreSQL in the DSL via `PostgresDSL`, but it certainly makes sense to look into adding more support for H2 as well.

I'll close this as a duplicate of #10175

**Closed by lukaseder** 2020-05-07 09:05 UTC
Labels: C: DB: H2, C: Functionality, C: Parser, E: All Editions, P: Medium, R: Feedback Pending, T: Defect
