### ISSUE TITLE
JOOQ 3.18.3 MiniJAXB cannot access class jakarta.xml.bind.annotation.XmlSchema because module org.jooq does not read unnamed module

### ISSUE THREAD

**Issue by dgcooke** [jOOQ/jOOQ#15069] opened 2023-05-14 22:38 UTC
### Expected behavior

Should, compile and run as expected, however it does not

### Actual behavior

Exception in thread "main" java.lang.IllegalAccessError: class org.jooq.util.jaxb.tools.MiniJAXB (in module org.jooq) cannot access class jakarta.xml.bind.annotation.XmlSchema (in unnamed module @0x10e31a9a) because module org.jooq does not read unnamed module @0x10e31a9a
        at org.jooq@3.18.4/org.jooq.util.jaxb.tools.MiniJAXB.getNamespace(MiniJAXB.java:407)
        at org.jooq@3.18.4/org.jooq.util.jaxb.tools.MiniJAXB.addDefaultNamespace(MiniJAXB.java:189)
        at org.jooq@3.18.4/org.jooq.util.jaxb.tools.MiniJAXB.unmarshal0(MiniJAXB.java:176)
        at org.jooq@3.18.4/org.jooq.util.jaxb.tools.MiniJAXB.unmarshal(MiniJAXB.java:162)
        at org.jooq.codegen@3.18.4/org.jooq.codegen.GenerationTool.load(GenerationTool.java:1244)
        at org.jooq.codegen@3.18.4/org.jooq.codegen.GenerationTool.generate(GenerationTool.java:231)
        at com.smartphonedev.mqttlistener@1.0/com.smartphonedev.mqttlistener.MQTTClient.initialiseSystem(MQTTClient.java:97)
        at com.smartphonedev.mqttlistener@1.0/com.smartphonedev.mqttlistener.MQTTClient.main(MQTTClient.java:158)

            final var optionalConfigFile = JOOQConfigReader.instanceOf().getConfigurationAsString();
            if (optionalConfigFile.isPresent())
            {
                GenerationTool.generate(optionalConfigFile.get());  // <------ Line 97
            } else
            {
                System.out.println("Config file failed");
                throw new InvalidResourceFileException("Config file failed");
            }

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.13.0.xsd">

	<jdbc>
		<driver>org.postgresql.Driver</driver>
		<url>jdbc:postgresql://localhost:5432/mydatabase</url>
		<user>myuser</user>
		<password>I-bet-you-would-like-to-know</password>
	</jdbc>

	<generator>
		<name>org.jooq.codegen.JavaGenerator</name>

		<database>
			<name>org.jooq.meta.postgres.PostgresDatabase</name>
			<inputSchema>public</inputSchema>
			<includes>.*</includes>
			<excludes></excludes>
		</database>

		<target>
			<packageName>com.smartphonedev.mqttlistener.model</packageName>
			<directory>/Console/src/main/java</directory>
		</target>
	</generator>
</configuration>

### Steps to reproduce the problem

It is a module application here is my module file
module com.smartphonedev.mqttlistener {
    requires java.logging;
    //requires org.bouncycastle.provider;
    requires org.eclipse.paho.client.mqttv3;
    requires jcip.annotations;
    requires java.net.http;
    requires jakarta.json;
    requires jakarta.json.bind;
    requires lombok;
    requires org.jooq;
    requires org.jooq.codegen;
    requires jakarta.annotation;

    exports com.smartphonedev.mqttlistener;
    exports com.smartphonedev.mqttlistener.config;
    exports com.smartphonedev.mqttlistener.models.tables.records to org.jooq;
    exports com.smartphonedev.mqttlistener.internal;
}

### jOOQ Version

JOOQ Community 3.18.3

### Database product and version

psql (PostgreSQL) 13.11 (Ubuntu 13.11-1.pgdg22.04+1)

### Java Version

openjdk version "20" 2023-03-21

### OS Version

Linux development 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment] 2023-05-15 06:24
Thanks for your report.

jOOQ's `module-info.java` declares an optional JAXB dependency:

```java
requires static jakarta.xml.bind;
```

So, I doubt that the problem here is caused by jOOQ, or something that jOOQ could fix on your behalf. It appears that you have incorrectly set up your module path.

I might be able to help here, but I'd need to see a complete reproducer, e.g. starting from our MCVE template: https://github.com/jOOQ/jOOQ-mcve

**Comment by lukaseder** [comment] 2023-05-15 06:25
The main hint here should be:

> cannot access class jakarta.xml.bind.annotation.XmlSchema (in unnamed module @0x10e31a9a)

Somehow, you're building your application using the modulepath instead of classpath, but introduce the optional dependency in the unnamed module, instead of formally as its own module.

**Comment by lukaseder** [comment] 2023-06-26 07:12
A similar issue: https://github.com/jOOQ/jOOQ/issues/15275

**Comment by lukaseder** [comment] 2023-06-26 07:12
At the time, I couldn't reproduce your issue, so I'm closing this for now. I'll be happy to review any reproducer in case there's something jOOQ does wrong.

**Closed by lukaseder** 2023-06-26 07:12 UTC
Labels: C: Build, P: Medium, T: Support request, R: Feedback Pending, E: All Editions
