### ISSUE TITLE
array_agg alias seems to be mandatory but missing

### ISSUE THREAD

**Issue by MartinVerges** [jOOQ/jOOQ#7395] opened 2018-04-05 18:56 UTC
### Expected behavior and actual behavior:
arrayAgg() should generate an alias if none is given. 

Please add a alias if none is given. This behavior would match alias tables, where jooq generates an alias if none is given.

### Steps to reproduce the problem:
```kotlin
selectFrom(TABLE).leftJoin(
     select(arrayAgg(FIELD1), FIELD2).from(TABLE2).groupBy(FIELD2)
).using(FIELD2)
```

### Versions:
- jOOQ: 3.10.6
- Kotlin: 1.2.31
- Java: 1.8.0_162
- Database (include vendor): Postgres (9.6.8)
- OS: Linux Ubuntu 18.04
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver

### Generated Query:
```sql
SELECT
  --- ...stuff from "TABLE1"...
  "alias_49996494"."array_agg({0})",  
  "alias_49996494"."FIELD2"
FROM "public"."table1"
LEFT OUTER JOIN (
    SELECT 
       array_agg("public"."TABLE2"."FIELD1"), 
       "public"."TABLE2"."FIELD2"
    FROM "public"."TABLE2"
    GROUP BY "public"."TABLE2"."FIELD2"
) AS "alias_49996494"
USING("FIELD2")
```
_Error Message:_
org.postgresql.util.PSQLException: ERROR: column __alias_49996494.array_agg({0})__ does not exist
!   Position: 371

_Solution:_
arrayAgg(FIELD1).as("myalias")

**Comment by lukaseder** [comment] 2018-04-06 05:25
Thank you for reporting. There are two issues here:

1. Why is there `({0})` in the generated name of the `array_agg`? This is clearly a bug
2. The possibility of generating aliases for all columns in nested selects

The latter is not a good idea, because it is not easy to decide which column expression needs aliasing, and which one doesn't. For example, if all columns in derived tables need aliasing, then your `FIELD2` column would be aliased as well, and it would no longer be possible to dereference it explicitly. This is not a problem in your case, since you selected all columns, but what about 95% of all jOOQ code in production?

We could say that only functions would need aliasing, but even then, the outcome will not be desireable for many cases where client code already depends on the unaliased column names (they shouldn't, but they often do).

Column aliasing is not the same thing as table aliasing for derived tables. The latter is strictly required in some databases, so the query would simply not parse without an alias. That's not the case for columns.

**Comment by lukaseder** [comment] 2020-08-07 13:11
A more general case of this is being discussed here: #579, and here: #7977, as this problem isn't strictly related to `array_agg`. I'm closing this as a duplicate of the other two - we'll clearly need to address this eventually, more thoroughly, thinking about how to recognise "unnamed" column expressions and generate aliases for them, when this is required, syntactically.

**Closed by lukaseder** 2020-08-07 13:11 UTC
Labels: C: Functionality, P: Medium, T: Defect
