### ISSUE TITLE
3.12: Combination of implicit join, explicit join and subquery produces invalid SQL with PostgreSQL

### ISSUE THREAD

**Issue by tkalliom** [jOOQ/jOOQ#9745] opened 2020-01-17 17:25 UTC
### Expected behavior and actual behavior:
Expected: using implicit join, explicit join and subquery together produces valid SQL (worked on 3.11).
Actual: using implicit join, explicit join and subquery together produces invalid SQL with PostgreSQL on 3.12. An example of produced SQL (see the `FROM` part):
```
select "mcve"."order_lines"."id", "mcve"."reviewers"."id"
from ("mcve"."order_lines" left outer join "mcve"."orders" as "alias_114148427" on "mcve"."order_lines"."order_id" = "alias_114148427"."id")" left outer join "mcve"."orders" as "alias_114148427" on "mcve"."order_lines"."order_id" = "alias_114148427"."id") join "mcve"."reviewers" on "mcve"."reviewers"."department_name" = "alias_114148427"."department_name"
where not exists (select 1 as "one" from "mcve"."approvals" where ("mcve"."approvals"."order_line_id" = "mcve"."order_lines"."id" and "mcve"."approvals"."reviewer_id" = "mcve"."reviewers"."id"))
```

### Steps to reproduce the problem
A MCVE is at [https://github.com/tkalliom/jOOQ-mcve/tree/join-subquery-invalid-sql](https://github.com/tkalliom/jOOQ-mcve/tree/join-subquery-invalid-sql). The query in question:
```
Result<Record2<Integer, Integer>> result = ctx.select(ORDER_LINES.ID, REVIEWERS.ID)
        .from(ORDER_LINES)
        .join(REVIEWERS)
        .on(REVIEWERS.DEPARTMENT_NAME.eq(ORDER_LINES.orders().DEPARTMENT_NAME))
        .where(
                DSL.notExists(
                        DSL.selectOne()
                                .from(APPROVALS)
                                .where(APPROVALS.ORDER_LINE_ID.eq(ORDER_LINES.ID), APPROVALS.REVIEWER_ID.eq(REVIEWERS.ID))
                )
        )
        .fetch();
```

### Versions:

- jOOQ: 3.12.3
- Java: 8
- Database (include vendor): PostgreSQL 11.5
- OS: Linux
- JDBC Driver (include name if inofficial driver): PostgreSQL JDBC driver 42.2.9

**Comment by lukaseder** [comment] 2020-01-20 09:21
Thanks a lot for your report. This looks a lot like #9674, which has been fixed for the next releases already

**Comment by lukaseder** [comment] 2020-01-20 09:21
Can confirm, running the MCVE against 3.13.0-SNAPSHOT doesn't reproduce the issue. I'll try to backport #9674 to 3.12.4

**Comment by lukaseder** [comment] 2020-01-20 09:21
Duplicate of #9674

**Closed by lukaseder** 2020-01-20 09:21 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect

**Comment by lukaseder** [comment] 2020-01-20 09:34
Your MCVE now works when running with 3.12.4-SNAPSHOT as well:
https://github.com/jOOQ/jOOQ/tree/version-3.12.0-branch

Thanks again for your help!
