### ISSUE TITLE
Allow using generated field constants together with Table#where(Condition)

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9097] opened 2019-08-29 08:03 UTC
With #8010 (release 3.12) a new `Table#where(Condition)` API was added. Unfortunately a `SELECT` cannot use the generated field constants when selecting from such a table, as the generated SQL is incorrect for some dialects (e.g. Oracle).

```java
ctx
    .select(T_BOOK.AUTHOR_ID)
    .from(T_BOOK.where(T_BOOK.ID.in(1, 2)))
    .fetch()
```

will produce SQL like:

```sql
select "TEST"."T_BOOK"."AUTHOR_ID"
from (
  select 
    "TEST"."T_BOOK"."AUTHOR_ID",
    ...
  from "TEST"."T_BOOK"
  where "TEST"."T_BOOK"."ID" in (
    1, 2
  )
) "T_BOOK"
```

whereas the correct SQL would be:

```sql
select "T_BOOK"."AUTHOR_ID"
from (
  select 
    "TEST"."T_BOOK"."AUTHOR_ID",
    ...
  from "TEST"."T_BOOK"
  where "TEST"."T_BOOK"."ID" in (
    1, 2
  )
) "T_BOOK"
```

**Comment by lukaseder** [comment] 2023-01-18 13:03
This problem isn't specific to `Table::where` (backed by `InlineDerivedTable`). It can happen with other table based expressions. E.g. I've noticed this problem with the new `WITH ORDINALITY` support from jOOQ 3.18, which is emulated using derived tables in some RDBMS, producing unqualified table names: https://github.com/jOOQ/jOOQ/issues/14424

Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/14424. Note, perhaps this particular problem could be solved with https://github.com/jOOQ/jOOQ/issues/8012, when we generate `Table::where` overrides that return the generated table, similar to the overridden `Table::as` override.

**Closed by lukaseder** 2023-01-18 13:03 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, E: All Editions
