### ISSUE TITLE
select(val(1).as("x")) Doesn't work as expected

### ISSUE THREAD

**Issue by ofirnk** [jOOQ/jOOQ#6528] opened 2017-08-27 09:27 UTC
### Expected behavior and actual behavior:
Running 
```java
select(val(1).as("x"))
```
**Expected**
`select 1 as "x"`

**Actual**
`select ? as "depth"` - `3.9.1`
`select ? as `depth` from dual` -  3.9.5 (which adds `..FROM dual` for some strange reason)

### Steps to reproduce the problem:
**Run test**
```java
    @Test
    public void name() throws Exception {
        final DSLContext dslContext = new DefaultDSLContext(SQLDialect.POSTGRES);

        SelectQuery f1 = dslContext.selectQuery();
        f1.addSelect(val(1).as("depth"));
        System.out.println(f1.getSQL());
```

Or.. Follow documentation

https://www.jooq.org/doc/3.9/manual/sql-building/sql-statements/with-clause/#N3E58B
![image](https://user-images.githubusercontent.com/8449713/29748643-eea41566-8b22-11e7-95e1-01e0357e8af4.png)
```java
create.with("a").as(select(
                        val(1).as("x"),
                        val("a").as("y")
                   ))
      .select()
      .from(table(name("a")))
      .getSql();
```

### Versions:

- jOOQ: 3.9.1, 3.9.5 (which adds `..FROM dual` for some strange reason)
- Database (include vendor): Postgres 
- JDBC Driver (include name if inofficial driver): `org.postgresql.Driver`

**Comment by lukaseder** [comment] 2017-08-28 11:47
Thank you very much for your report. I'm afraid, I cannot reproduce this issue (and it would be a *very* surprising regression, as it would fail about half of our integration tests).

Is there anything else that might have influenced this outcome on your side? Would you mind posting a full Maven-built project that exposes the problem?

**Comment by ofirnk** [comment] 2017-08-28 12:42
> a _very_ surprising regression
agree :)

So after some  _going-down the debug-hole_ I've understood that it has to do something with `ParamType.INDEXED`.
It appears to default to `INDEXED` when using `spring-boot-starter-jooq` package.
And not when using vanilla Jooq.. 

I've tried digging the reason for difference but lost my way in spring-land after some time :laughing: 

Thanks for help :+1: 
I appreciate it (and your work) a lot!

**Comment by lukaseder** [comment] 2017-08-28 13:16
Thanks for the update. Hmm, how could the `ParamType` be related to whether or not the `FROM` clause is generated? I cannot reproduce this, still:

```java
import static org.jooq.impl.DSL.val;

import org.jooq.DSLContext;
import org.jooq.SQLDialect;
import org.jooq.SelectQuery;
import org.jooq.conf.ParamType;
import org.jooq.conf.Settings;
import org.jooq.impl.DefaultDSLContext;

public class Regr {
    public static void main(String[] args) {
        final DSLContext dslContext = new DefaultDSLContext(SQLDialect.POSTGRES, new Settings().withParamType(ParamType.INDEXED));

        SelectQuery f1 = dslContext.selectQuery();
        f1.addSelect(val(1).as("depth"));
        System.out.println(f1.getSQL());
    }
}
```

The easiest way forward would be to create a minimal Maven-built project that fails, even if using the `spring-boot-starter-jooq`. But again, maybe we're barking up the wrong tree. There are some dialects (e.g. MySQL) for which jOOQ generates the `FROM dual` clause, because in some cases, the parser will reject the SQL if there's no `FROM` clause (or in other databases, the parser doesn't support `FROM`-less `SELECT` statements at all, e.g. Oracle).

So, I'd rather investigate that way and check if you're *really* using the correct `Configuration`

**Comment by lukaseder** [comment] 2017-08-28 13:16
I'm closing this, as I don't think there's a problem in jOOQ here...

**Closed** 2017-08-28 13:16 UTC
Labels: C: Functionality, P: Medium, R: Answered, T: Support request
