### ISSUE TITLE
NullPointerException on Query.getBindValues

### ISSUE THREAD

**Issue by lpfeup** [jOOQ/jOOQ#7600] opened 2018-06-20 14:27 UTC
### Expected behavior and actual behavior:
Expected: Query.getBindValues() returns bind values
Actual: Query.getBindValues() throws NullPointerException

### Steps to reproduce the problem (include example code if possible):

Example
```java
DSLContext DSL_CONTEXT = DSL.using(SQLDialect.POSTGRES_9_5);

Query q = DSL_CONTEXT
    .select(DSL.field("field"))
    .from(DSL_CONTEXT
        .select(DSL.field("field"))
        .from(DSL.table("xtable"))
        .union(DSL_CONTEXT
            .select(DSL.field("field"))
            .from(DSL.table("xtable"))
            .where(DSL.field("field").equal(UUID.randomUUID()))).asTable().as("t"));
```

jOOQ 3.10.7:
```java
System.out.println(q.getSQL());
// select field from ((select field from xtable) union (select field from xtable where field = ?)) as "t"
System.out.println(q.getBindValues());
// [8b738cbc-5d10-4b3c-83f6-19cde78b8588]
```

jOOQ 3.11.0/3.11.1:
```java
System.out.println(q.getSQL());
// select field from ((select field from xtable) union (select field from xtable where field = cast(? as uuid))) as "t"
System.out.println(q.getBindValues());
// 
Exception in thread "main" java.lang.NullPointerException
	at org.jooq.impl.AbstractContext$ScopeStack.trim(AbstractContext.java:799)
	at org.jooq.impl.AbstractContext.scopeEnd(AbstractContext.java:581)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:795)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:254)
	at org.jooq.impl.ParamCollector.bindInternal(ParamCollector.java:99)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:446)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:207)
	at org.jooq.impl.AbstractDelegatingQuery.accept(AbstractDelegatingQuery.java:89)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:254)
	at org.jooq.impl.ParamCollector.bindInternal(ParamCollector.java:99)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:446)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:207)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:1430)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:1028)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:823)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:640)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:254)
	at org.jooq.impl.ParamCollector.bindInternal(ParamCollector.java:99)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:446)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:207)
	at org.jooq.impl.DerivedTable.accept(DerivedTable.java:92)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:254)
	at org.jooq.impl.ParamCollector.bindInternal(ParamCollector.java:99)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:417)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:207)
	at org.jooq.impl.Alias.toSQLWrapped(Alias.java:278)
	at org.jooq.impl.Alias.accept(Alias.java:205)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:254)
	at org.jooq.impl.ParamCollector.bindInternal(ParamCollector.java:99)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:446)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:207)
	at org.jooq.impl.TableAlias.accept(TableAlias.java:149)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:254)
	at org.jooq.impl.ParamCollector.bindInternal(ParamCollector.java:99)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:446)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:207)
	at org.jooq.impl.QueryPartList.accept(QueryPartList.java:119)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:254)
	at org.jooq.impl.ParamCollector.bindInternal(ParamCollector.java:99)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:446)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:207)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:1260)
	at org.jooq.impl.SelectQueryImpl.toSQLReference0(SelectQueryImpl.java:1028)
	at org.jooq.impl.SelectQueryImpl.toSQLReferenceLimitDefault(SelectQueryImpl.java:823)
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:640)
	at org.jooq.impl.AbstractBindContext.bindInternal(AbstractBindContext.java:254)
	at org.jooq.impl.ParamCollector.bindInternal(ParamCollector.java:99)
	at org.jooq.impl.AbstractBindContext.visit0(AbstractBindContext.java:88)
	at org.jooq.impl.AbstractContext.visit0(AbstractContext.java:446)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:207)
	at org.jooq.impl.DefaultDSLContext.extractBindValues(DefaultDSLContext.java:708)
	at org.jooq.impl.AbstractQuery.getBindValues(AbstractQuery.java:138)
	at org.jooq.impl.AbstractDelegatingQuery.getBindValues(AbstractDelegatingQuery.java:74)
```

### Versions:

- jOOQ: 3.11.0 / 3.11.1
- Java: 1.8.0_171
- Database (include vendor): PostgreSQL
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): -

**Comment by lukaseder** [comment] 2018-06-20 14:34
Thanks a lot for your detailed bug report. I'll investigate this ASAP

**Comment by lukaseder** [comment] 2018-06-21 10:55
I can reproduce this with your example code.

**Comment by lukaseder** [comment] 2018-06-21 10:59
The fix was very easy. I don't know what exactly triggered the regression from your particular example (e.g. the usage of plain SQL, the specific way you nest the queries, etc.), but the cause of the NPE is obvious. There is a direct access to a lazily initialised value.

This is fixed for jOOQ 3.12. A backport to 3.11.2 is scheduled and will be released probably next week: #7603. 3.10 is not affected

**Closed by lukaseder** 2018-06-21 10:59 UTC
Labels: C: Functionality, P: Urgent, T: Defect

**Comment by lpfeup** [comment] 2018-06-21 11:32
Thanks for handling it so quickly 👍

**Comment by lpfeup** [comment] 2018-06-21 13:44
`Context.scopeStart()` and `scopeEnd()` were added to `SelectQueryImpl.accept(Context<?>)` on jOOQ 3.11.0 with [this commit](https://github.com/jOOQ/jOOQ/commit/87c49895c2ba40e2f92c005c64852761e1ae6f19#diff-64d12045201b8a4578b32eefbe12e82a). 
This seems to have introduced the regression.

**Comment by lukaseder** [comment] 2018-06-21 13:48
Yes sure, I know what feature contributed the regression, but I don't know what makes your particular query "special", so that it triggers the regression, when our integration tests did not.
