### ISSUE TITLE
Add support for Sybase ASE UNSIGNED SMALLINT, UNSIGNED INTEGER, UNSIGNED BIGINT types

### ISSUE THREAD

**Issue by muskaan62** [jOOQ/jOOQ#17195] opened 2024-09-06 05:56 UTC
### Your question

When retrieving data for unsigned types(bigint,int,small int) in sybase ASE using Sybase Dialect getting Number overflow error.
It is working when we have smaller numbers in the column but failing after certain range
The behaviour is same with both jtds and Jconn driver
`            ResultQuery<Record> record =  context.resultQuery("select * from unsignedDataTypes");
`
```
at org.jooq_3.17.3.ASE.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3300)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:678)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1464)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1425)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:238)
	at org.jooq.impl.Tools.fetchOne(Tools.java:2592)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
Caused by: java.sql.SQLException: Error while reading field: "dbo"."unsignedDataTypes"."unsigned_smallint", at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1590)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1525)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1484)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1449)
	... 5 more
Caused by: java.sql.SQLException: JZ00B: Numeric overflow.
	at com.sybase.jdbc4.jdbc.ErrorMessage.raiseError(Unknown Source)
	at com.sybase.jdbc4.jdbc.Convert.checkShortOflo(Unknown Source)
	at com.sybase.jdbc4.tds.TdsInt.getShort(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybResultSet.getShort(Unknown Source)
	at org.jooq.tools.jdbc.DefaultResultSet.getShort(DefaultResultSet.java:139)
	at org.jooq.impl.CursorImpl$CursorResultSet.getShort(CursorImpl.java:707)
	at org.jooq.impl.DefaultBinding$DefaultShortBinding.get0(DefaultBinding.java:4188)
	at org.jooq.impl.DefaultBinding$DefaultShortBinding.get0(DefaultBinding.java:4155)
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1025)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1580)
	... 9 more
```

### jOOQ Version

3.17.3

### Database product and version

sybase ASE

### Java Version

11

### JDBC / R2DBC driver name and version (include name if unofficial driver)

jconn 16.0

**Comment by w2wewwww** [comment] 2024-09-06 05:57
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by lukaseder** [comment] 2024-09-06 06:05
Thanks for your message. This is a known issue, see:

- https://github.com/jOOQ/jOOQ/issues/17081

You can either apply a data type binding, or data type rewriting to `TINYINTUNSIGNED` in order to have jOOQ generate code that uses a `UByte` type rather than `Byte`

**Comment by muskaan62** [comment] 2024-09-06 07:29
@lukaseder Thanks for Informing..But it is failing at reading the result from db what is the work around for that?

**Comment by lukaseder** [comment] 2024-09-06 08:06
I see, you're using plain SQL. You can create a `ResultQuery` first and then coerce data types according to your expectations using `ResultQuery.coerce()`.

If you don't know the schema in advance, there's no workaround other than patching jOOQ. For this, change `ASEDataType.TINYINT`

**Comment by muskaan62** [comment] 2024-09-06 10:53
@lukaseder Thanks for your quick responses...did this fix will be in 3.17.x version or later one?

**Comment by lukaseder** [comment] 2024-09-06 12:07
We can implement it for 3.20

**Comment by muskaan62** [comment] 2024-09-06 12:30
@lukaseder Thanks for Your help here. Due to this issue our release is at risk, juts wanted to know Tentatively when can we expect this fix with release 3.20? I meant, Any ETA.

**Comment by lukaseder** [comment] 2024-09-06 12:45
We don't guarantee any release dates, but once this is fixed (probably next week), you can access our 3.20 snapshot builds here:
https://www.jooq.org/download/versions

Of course, as I mentioned before, you can always patch your own version with the fix as well.

**Comment by muskaan62** [comment] 2024-09-11 06:22
Thanks @lukaseder The issue is with short,Long,Int (for unsigned types) as well not only tiny..Hoping this gets addressed in the upcoming fix.
Thanks for your help!.

**Comment by lukaseder** [comment] 2024-09-11 07:32
Thanks for your comment, @muskaan62. I overlooked this part indeed, I'm sorry for the confusion. Your issue description did mention `SMALLINT`

The other issue https://github.com/jOOQ/jOOQ/issues/17081 was *only* about `TINYINT`, though I suspect there was a confusion regarding the Sybase products. The documentation linked from the issue is about SQL Anywhere, not ASE.

I will look into additional unsigned type support ASAP.

**Comment by lukaseder** [comment] 2024-09-11 13:32
@muskaan62 In order to validate your various support requests against our license database, can you please quickly provide us with your license information at contact@datageekery.com.

**Comment by muskaan62** [comment] 2024-09-12 06:30
@lukaseder Send the details

**Comment by lukaseder** [comment] 2024-09-13 07:26
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17240)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17241)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17242)

I'll run snapshot builds in a minute, which should be available this afternoon, CEST. Releases will be delivered by mid next week.

**Closed by lukaseder** 2024-09-13 07:26 UTC
Labels: T: Defect, C: Functionality, C: DB: Sybase ASE, P: Medium, E: All Editions

**Comment by lukaseder** [comment] 2024-09-13 07:32
My mistake. The backports won't be applied due to the backwards incompatible nature of this change (i.e. instead of returning `Long` for `UNSIGNED BIGINT`, jOOQ now returns `ULong`). This fix will be applied to 3.20.0 only.

**Comment by lukaseder** [comment] 2024-09-13 07:34
If you're interested in patching earlier versions yourself, the patch is entirely in `ASEDataType.java`:

```patch
diff --git a/jOOQ/src/main/java/org/jooq/util/ase/ASEDataType.java b/jOOQ/src/main/java/org/jooq/util/ase/ASEDataType.java
index 93fbd0c..b1d7c69 100644
--- a/jOOQ/src/main/java/org/jooq/util/ase/ASEDataType.java
+++ b/jOOQ/src/main/java/org/jooq/util/ase/ASEDataType.java
@@ -52,6 +52,9 @@
 import org.jooq.impl.BuiltInDataType;
 import org.jooq.impl.SQLDataType;
 import org.jooq.types.UByte;
+import org.jooq.types.UInteger;
+import org.jooq.types.ULong;
+import org.jooq.types.UShort;
 
 /**
  * Supported data types for the {@link SQLDialect#ASE} dialect
@@ -78,12 +81,12 @@
 
     public static final DataType<UByte>      TINYINT                    = new BuiltInDataType<>(FAMILY, SQLDataType.TINYINTUNSIGNED, "tinyint");
     public static final DataType<Short>      SMALLINT                   = new BuiltInDataType<>(FAMILY, SQLDataType.SMALLINT, "smallint");
-    public static final DataType<Short>      UNSIGNEDSMALLLINT          = new BuiltInDataType<>(FAMILY, SQLDataType.SMALLINT, "unsigned smallint");
+    public static final DataType<UShort>     UNSIGNEDSMALLLINT          = new BuiltInDataType<>(FAMILY, SQLDataType.SMALLINTUNSIGNED, "unsigned smallint");
     public static final DataType<Integer>    INT                        = new BuiltInDataType<>(FAMILY, SQLDataType.INTEGER, "int");
     public static final DataType<Integer>    INTEGER                    = new BuiltInDataType<>(FAMILY, SQLDataType.INTEGER, "integer");
-    public static final DataType<Integer>    UNSIGNEDINT                = new BuiltInDataType<>(FAMILY, SQLDataType.INTEGER, "unsigned int");
+    public static final DataType<UInteger>   UNSIGNEDINT                = new BuiltInDataType<>(FAMILY, SQLDataType.INTEGERUNSIGNED, "unsigned int");
     public static final DataType<Long>       BIGINT                     = new BuiltInDataType<>(FAMILY, SQLDataType.BIGINT, "bigint");
-    public static final DataType<Long>       UNSIGNEDBIGINT             = new BuiltInDataType<>(FAMILY, SQLDataType.BIGINT, "unsigned bigint");
+    public static final DataType<ULong>      UNSIGNEDBIGINT             = new BuiltInDataType<>(FAMILY, SQLDataType.BIGINTUNSIGNED, "unsigned bigint");
     public static final DataType<Double>     DOUBLE_PRECISION           = new BuiltInDataType<>(FAMILY, SQLDataType.DOUBLE, "double precision");
     public static final DataType<Double>     FLOAT                      = new BuiltInDataType<>(FAMILY, SQLDataType.FLOAT, "float");
     public static final DataType<Float>      REAL                       = new BuiltInDataType<>(FAMILY, SQLDataType.REAL, "real");
```

**Comment by muskaan62** [comment] 2024-09-13 08:26
Thanks @lukaseder for quickly fixing it.. when the tentatively the official release of 3.20 will be available?
