### ISSUE TITLE
Ill formatted Javadoc in DSLContext

### ISSUE THREAD

**Issue by sdyura** [jOOQ/jOOQ#13703] opened 2022-06-22 22:21 UTC
javadoc gets really screwed up half way down this page:

https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/DSLContext.html

just after the text:
```
  <R extends Record>
  @NotNull Result<R>	fetch(Table<R> table)	Execute and return all records for 
```
i am using Firefox and also tested it on safari

**Comment by lukaseder** [comment] 2022-06-23 09:46
Thanks a lot for your report. I can confirm this happens right where you said:

<img width="1733" alt="image" src="https://user-images.githubusercontent.com/734593/175270186-548795bc-61ee-4e58-9350-2b2815fd50c0.png">

**Comment by lukaseder** [comment] 2022-06-23 10:02
OK, this can be reproduced easily:

```
$ cat Test.java
public class Test {
        /**
         * Test 1
         */
        public void m1() {}

        /**
         * Test 2 <code><pre>Fail</pre></code>.
         */
        public void m2() {}

        /**
         * Test 3
         */
        public void m3() {}
}

$ javadoc Test.java
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Loading source file Test.java...
Constructing Javadoc information...
Building index for all the packages and classes...
Standard Doclet version 18.0.1+10
Building tree for all the packages and classes...
Generating .\Test.html...
Test.java:8: error: block element not allowed within inline element <code>: pre
         * Test 2 <code><pre>Fail</pre></code>.
                        ^
Test.java:1: warning: no comment
public class Test {
       ^
Test.java:1: warning: use of default constructor, which does not provide a comment
public class Test {
       ^
Generating .\package-summary.html...
Generating .\package-tree.html...
Generating .\overview-tree.html...
Building index for all classes...
Generating .\allclasses-index.html...
Generating .\allpackages-index.html...
Generating .\index-all.html...
Generating .\index.html...
Generating .\help-doc.html...
1 error
2 warnings
```

The error doesn't fail the javadoc build, but produces this output, instead:

<img width="544" alt="image" src="https://user-images.githubusercontent.com/734593/175272652-70624e02-f5c1-4b7c-bc8c-ec8f9789aad0.png">

I'm not sure if the javadoc tool is at fault here. It just reports the invalid HTML and generates it nonetheless, verbatim. The output HTML is:

```xml
<!--StartFragment-->

<!-- ============ METHOD DETAIL ========== -->
--
  | <li>
  | <section class="method-details" id="method-detail">
  | <h2>Method Details</h2>
  | <ul class="member-list">
  | <li>
  | <section class="detail" id="m1()">
  | <h3>m1</h3>
  | <div class="member-signature"><span class="modifiers">public</span>&nbsp;<span class="return-type">void</span>&nbsp;<span class="element-name">m1</span>()</div>
  | <div class="block">Test 1</div>
  | </section>
  | </li>
  | <li>
  | <section class="detail" id="m2()">
  | <h3>m2</h3>
  | <div class="member-signature"><span class="modifiers">public</span>&nbsp;<span class="return-type">void</span>&nbsp;<span class="element-name">m2</span>()</div>
  | <div class="block">Test 2 <code><pre>Fail</pre></code>.</div>
  | </section>
  | </li>
  | <li>
  | <section class="detail" id="m3()">
  | <h3>m3</h3>
  | <div class="member-signature"><span class="modifiers">public</span>&nbsp;<span class="return-type">void</span>&nbsp;<span class="element-name">m3</span>()</div>
  | <div class="block">Test 3</div>
  | </section>
  | </li>
  | </ul>
  | </section>
  | </li>
  | </ul>
  | </section>
  | <!-- ========= END OF CLASS DATA ========= -->

<!--EndFragment-->
```

So, it's the browser's behaviour. It seems our build is currently not failing when there are Javadoc errors, which is why this regression has gone unnoticed (for a while!)

**Comment by lukaseder** [comment] 2022-06-23 10:05
Yeah, we're using `-Xdoclint:none` because of some aggressive error reporting in the past. `-Xdoclint:html` might be a better choice

**Comment by lukaseder** [comment] 2022-06-23 12:58
Fixed in jOOQ 3.18.0, 3.17.1 (https://github.com/jOOQ/jOOQ/issues/13710), and 3.16.8 (https://github.com/jOOQ/jOOQ/issues/13711). Thanks again for the report.

**Closed by lukaseder** 2022-06-23 12:58 UTC
Labels: T: Defect, C: Documentation, P: Medium, E: All Editions

**Comment by lukaseder** [comment] 2022-06-24 06:47
Egh. I remember why I turned it off in the first place. It's really such a pain to fix all these HTML vs XHTML issues, e.g.

```
/var/lib/jenkins/workspace/jooq-deploy-all_main/workspace-jooq-pro-java-8/jOOQ/jOOQ/src/main/java/org/jooq/InsertQuery.java:202: error: self-closing element not allowed
     * {@link SQLDialect#HSQLDB}<br/>
```

Anyway... I guess that's what we'll do from now on.

**Comment by lukaseder** [comment] 2022-06-27 12:24
Hmm, the issue isn't fixed entirely yet. There does seem to be another problem in the javadoc tool, more likely a bug. For example, this method:

```java
    /**
     * Wrap a collection of statements in an anonymous procedural block that
     * does not wrap in <code>BEGIN .. END;</code>, unless explicitly needed.
     *
     * @see DSL#statements(Collection)
     */
    @NotNull @CheckReturnValue
    @Support({ AURORA_POSTGRES, BIGQUERY, DB2, EXASOL, FIREBIRD, H2, HANA, HSQLDB, INFORMIX, MARIADB, MYSQL, ORACLE, POSTGRES, SQLDATAWAREHOUSE, SQLSERVER, TERADATA, VERTICA, YUGABYTEDB })
    @Pro
    Block statements(Collection<? extends Statement> statements);
```

Produces this Javadoc:

```xml
<div class="block">Wrap a collection of statements in an anonymous procedural block that does not wrap in <code>BEGIN ..</div>
```

It appears the `<code>` element doesn't work in the Javadoc method title? Will investigate...

**Comment by lukaseder** [comment] 2022-06-27 14:14
OK, so that's because of the `.` in the first sentence, which

- doesn't mark the end of the sentence yet
- is in a `<code> .. </code>` tag
- has a whitespace before the end of teh `</code>` tag

Quite an interesting bug of the javadoc tool, I suspect? I've reported it to the OpenJDK: https://bugs.openjdk.org/browse/JDK-8289221

Will try to avoid it in jOOQ API, though it's hard to avoid because the javadoc tool doesn't report the flaw.

**Comment by lukaseder** [comment] 2022-06-27 14:19
Another one

![image](https://user-images.githubusercontent.com/734593/175963460-baac94d3-c54c-4282-9eef-49ce5de74bf6.png)

**Comment by lukaseder** [comment] 2022-06-27 14:21
I guess the quickest fix for this would be to replace all `..` contained in `<code> .. </code>` by `…`

**Comment by lukaseder** [comment] 2022-06-28 12:49
#13734 has now been fixed as well. It's already visible in the latest development version:
https://www.jooq.org/javadoc/dev/org.jooq/org/jooq/DSLContext.html

And will be integrated in 3.17.2 and 3.16.8. Thanks again for your report!
