### ISSUE TITLE
Make methods on SelectQuery/InsertQuery/UpdateQuery/DeleteQuery chainable, and potentially add methods with naming consistent with DSL methods

### ISSUE THREAD

**Issue by dbrokaw** [jOOQ/jOOQ#8358] opened 2019-02-27 09:41 UTC
### Use case:

We have a number of scenarios where it makes sense to use the "non-fluent" / underlying `SelectQuery/InsertQuery/UpdateQuery/DeleteQuery` mechanisms to construct core queries and then add further selections / joins / conditions, sometimes in helper methods that we pass the query to.  This cannot easily be done with the fluent DSL queries, and declaring variables of the various `SelectXxxStep` types is discouraged by the javadoc.  As you note in one of the blog posts, the ability to dynamically construct queries is one of the main values of Jooq, and we've made pretty extensive use of dynamic query construction in a home-grown query mechanism that we're thinking of replacing with Jooq.

### Possible solution you'd like to see:

1. Make the mutation methods (e.g. `addSelect()`, `addCondition()`, et al) on `Select/Insert/Update/DeleteQuery` chainable, by making them return `this` rather than `void`.

2. Ideally, add chainable versions of these methods with similar natural "fluent" naming as in SQL and the DSL API, e.g. `select( SelectFieldOrAsterisk... )`, `where( Condition )` rather than `addSelect()` and `addCondition()`, et al.  This could improve consistency, understandability, and portability between the two types of queries (e.g. to move more queries from dynamic to static/DSL or vice-versa), particularly if you have a mix of them in a given area of code.  Though I realize that would mean *adding* those as new methods (simple pass-thrus that call the existing ones), since the existing ones likely need to be kept for backward compatibility for a long time.

### Possible workarounds:

Use the methods as-is without chainability, or continue to use our own `Query` wrapper to support this type of chainable query construction with relaxed ordering.  Obviously neither of these is a complete showstopper, but curious how you think about them, and didn't see an existing ticket around these ideas.

### Versions:

- jOOQ: 3.11
- Java: 8 / 11
- Database (include vendor): MySQL
- OS: Ubuntu
- JDBC Driver (include name if inofficial driver): MySQL

**Comment by lukaseder** [comment] 2019-02-28 09:26
Thank you very much for your suggestions. There are a variety of other ideas going around to improve the current state of the DSL / Model APIs in a future jOOQ 4.0. Some ideas have already been collected here: #2198. I have added yours. The following two bullets will cover your ideas:

> - Model types shall be JavaBeans compliant (setters and getters)
> - Model types shall apply the fluent JavaBeans extension (with setters returning this, see also: #8358)

Some more comments on your suggestion:

> and then add further selections / joins / conditions, sometimes in helper methods that we pass the query to. This cannot easily be done with the fluent DSL queries

That will depend on how much you're willing to relax your imperative programming approach to building dynamic SQL. Here's an alternative approach:
https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq

I'm pretty sure you can get *very* far with the DSL API alone, without resorting to the model API.

> and declaring variables of the various `SelectXxxStep` types is discouraged by the javadoc

Indeed, that can get hairy and you'll risk a backwards incompatibility when upgrading jOOQ 4.0 (although that hasn't been set in stone yet. Maybe, we can upgrade the API in a backwards compatible way)

> a home-grown query mechanism that we're thinking of replacing with Jooq

That is obviously a very good idea :)

> 1\. Make the mutation methods (e.g. `addSelect()`, `addCondition()`, et al) on `Select/Insert/Update/DeleteQuery` chainable, by making them return `this` rather than `void`.

It makes sense to have such methods, but rather than changing them, I'd prefer following the ideas of #2198: Having JavaBeans compliant setters and getters (setters return void), and apply the common practice of "overloading" `setXYZ()` methods with an equivalent `withXYZ()` method that returns `this`.

> 2\. Ideally, add chainable versions of these methods with similar natural "fluent" naming as in SQL and the DSL API

I'm not convinced this would add more value than confusion. But the confusion originates with an unclear distinction between the purposes of the DSL API and the model API. The distinction is not for dynamic / static SQL use. The main distinctions (which is currently poorly implemented) should be:

- immutability (DSL) vs mutability (model)
- type safety (DSL) vs type flexibility (model)

> (e.g. to move more queries from dynamic to static/DSL or vice-versa)

This should not be a use case in general

> particularly if you have a mix of them in a given area of code

This shouldn't be either.

For the time being, I do suggest you review whether you really need the model API as much as you think you do, or if you could use the DSL API in a more functional approach. One key thing to understand here is that e.g. `SelectJoinStep.join(...)` methods are just convenience for calling `Table.join(...)` behind the scenes. The DSL API may feel like it's made for static SQL only, but it really isn't

**Comment by lukaseder** [comment] 2019-02-28 09:27
Closing this as a duplicate of #2198

**Closed by lukaseder** 2019-02-28 09:27 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Enhancement

**Comment by dbrokaw** [comment] 2019-03-06 21:36
Thanks for the detailed reply, and the pointer to 2198.

We'll definitely try using the DSL API as much as possible -- it may be sufficient in many cases.  I looked through https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq/, which from this perspective suggests "pre-computing" any additional joins/filters/selections, so the "core" query construction can still be constructed via DSL in canonical order, without needing intermediate `SelectXxxStep` variables.

Our main cases where this *didn't* feel as natural or sufficient were when helper methods need to "augment" a query with *both* additional selections and additional joins / filters to support them, based on various business logic.  That suggests you'd need your own simple "query struct" (or several local `Lists`) to build up the additional joins/selections/filters and pass them to the final DSL construction.  At that point it seems more natural to just construct the "base" query first, using the model API, and then pass it to the various helper methods to augment further.  This also lets the helpers know (assuming the query has getters) what's already been joined/selected, which can sometimes be useful for not adding redundant joins, etc.

> Moving queries from dynamic to static/DSL should not be a use case in general.

Yes, I misused "dynamic" a bit -- I meant having a mix of "model / flexibly-typed / flexibly-ordered" and "DSL / type-safe / SQL-ordered" constructions as above.  It seems like we'd have such a mix if we use DSL for most / simpler queries, but model construction for cases like above.

Either way, 2198 will be very helpful, particularly because we have an existing "query transform" mechanism that would likely become a set of VisitListeners, but some of the transforms feel a bit "hacky" without having getters on the query objects.  E.g. we have a case where we need to replace an `InsertQuery` with 2 queries that insert the fields to different tables, and the only apparent way to find the insert `Fields` and `Params` is by traversing the subtree with `QueryPartInternal.accept()`.  So having explicit getters for such things will really help.

Is there any current rough guess on the timeline for 2198 / Jooq 4.0?  1/2/3+ months / years away?

**Comment by lukaseder** [comment] 2019-03-07 09:13
> Our main cases where this didn't feel as natural or sufficient were when helper methods need to "augment" a query with both additional selections and additional joins / filters to support them, based on various business logic

Why not just join a derived table instead?

But you're right, at some point, the functional approach breaks down and the imperative one works better, hence the model API.

> particularly because we have an existing "query transform" mechanism that would likely become a set of VisitListeners

Interesting, what are those?

> Is there any current rough guess on the timeline for 2198 / Jooq 4.0? 1/2/3+ months / years away?

I'm afraid, no there isn't. jOOQ 4.0 will include very substantial changes, none of which add enough value to justify a major release yet.

**Comment by dbrokaw** [comment] 2019-06-05 22:00
Sorry it took a while to "reply".

Re derived tables (i.e. subqueries I assume), we've seen that potentially add a perf cost depending on how well the optimizer can "inline" them.

Re query transforms / listeners, we've used them to support several types of higher-level concepts based on additional model metadata and query / field properties, including:
- Generating joins to support path fields (which I saw you recently added to Jooq -- good deal :-)).
- Applying SQL:2011-style temporal versioning in DBs that don't support it, e.g. filtering based on an "asOf" property set on the query, end-dating and creating new date ranges on updates, etc.
- Currency conversion of any "money-typed" field in the query to a specified target currency, based on joining a rate table and replacing the field values with conversion expressions.
- Other virtual / calculated fields that are worth supporting centrally across multiple queries.

Bummer about 4.0 w.r.t 2198 (this ticket 8358 is mostly a "convenience" issue). It looks like our urgency to fully replace our existing persister with Jooq has abated a bit since it's reasonably mature / usable as well, but could still be nice when time allows. We'll keep an eye on 4.0 status, and if it turns out to be reasonable to just add getters to the model API for 3.xx without waiting for a "full release" (and understanding the new getters might immediately go into the "compat layer" when 4.0 comes), that would be great. In the meantime we'll likely use Jooq at least for newer / simpler projects and see where things go.
