### ISSUE TITLE
Kotlin extension infix operators for generating conditions

### ISSUE THREAD

**Issue by dump247** [jOOQ/jOOQ#12041] opened 2021-06-22 22:33 UTC
### Use case:

Kotlin has infix operators that could make the queries in the jooq DSL much more readable.

Turning this:

```kotlin
dslContext
    .selectFrom(TABLE)
    .where(FIELD1.eq(value1), FIELD2.lt(value2).or(FIELD3.between(10, 17))
    .execute()
```

Into this:

```kotlin
dslContext
    .selectFrom(TABLE)
    .where((FIELD1 eq value1) and ((FIELD2 lt value2) or (FIELD3 between 10..17))
    .execute()
```

### Possible solution you'd like to see:

Add infix extension operators that alias the various methods on Field and Condition to the jooq-kotlin library. The result will not impact any existing code.

I have written these sort of operators for various projects and would like to contribute the result to jooq.

### Versions:

?

**Comment by lukaseder** [comment] 2021-06-23 07:26
Thanks for your suggestion.

This was considered as part of https://github.com/jOOQ/jOOQ/issues/6256, and rejected. The problem is that there is no way to specify operator precedence for infix operators (see also https://discuss.kotlinlang.org/t/specify-operator-precedence-for-infix-functions/2685), and as such, it is a very dangerous approach for a relatively marginal gain of making things "more readable"

You carefully added parens where needed in your rather simple example. Imagine some poor soul forgetting when they have to add them and when they don't in a much more complex predicate. It's just not worth the risk.

Having said so, nothing prevents you from declaring your own infix operators on your end, or even from publishing a library with such extensions for others to use.

**Comment by lukaseder** [comment] 2021-06-23 07:26
Closing as duplicate of https://github.com/jOOQ/jOOQ/issues/6256

**Closed by lukaseder** 2021-06-23 07:26 UTC
Labels: C: Functionality, C: Integration: Kotlin, E: All Editions, P: Medium, T: Enhancement
