### ISSUE TITLE
Jooq generate my code, and when I run findbugs, an IC_INIT_CIRCULARITY bug reported.   

### ISSUE THREAD

**Issue by zkhzkhz** [jOOQ/jOOQ#12461] opened 2021-09-22 03:18 UTC
### Expected behavior

no  IC_INIT_CIRCULARITY  bug
### Steps to reproduce the problem

my tables contain Identities, unique constraints and foreign keys.
https://stackoverflow.com/questions/6416408/static-circular-dependency-in-java
http://findbugs.sourceforge.net/bugDescriptions.html

### Versions

- jOOQ: 3.13.2
- Java: 11
- Database (include vendor): PG 
- OS: Windows10
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2021-09-22 07:39
Thanks for your report.

1. Is there anything specific you can report on actual generated classes?
2. Can you provide a reproducer, please (ideally based on this template: https://github.com/jOOQ/jOOQ-mcve)
3. Do you have an indication that there is going to be an actual problem other than a static analysis report (e.g. something doesn't load correctly)

As it is right now, the issue is not really actionable, so I'm closing it for now as "works for me". I'll be happy to reopen if there's something specific we should act upon.

(I've long ago stopped using static analysis like FindBugs due to the excessive amount of false positives reported by those tools, producing only busywork)

**Closed by lukaseder** 2021-09-22 07:39 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by zkhzkhz** [comment] 2021-09-23 03:40
I have a schema that contains foreign keys, and the Keys.java which jooq generates  many codes like:
`Internal.createForeignKey(**Keys**.XX_PKEY,`
Maybe findbugs detect this as IC_INIT_CIRCULARITY  bug.
Finally I disabled foreign key generation  by `includeForeignKeys = false` in jooq.gradle, and no more `Keys.` like codes are generated.
