### ISSUE TITLE
Generated record field has Object type instead of Enum type

### ISSUE THREAD

**Issue by pzheltakova** [jOOQ/jOOQ#10573] opened 2020-09-01 19:16 UTC
### Expected behavior and actual behavior:
I've used  org.jooq.meta.postgres.PostgresDatabase to generate meta and table fields were generated like this:

```java
    public final TableField<MarginSettingsRecord, Mode> MODE = createField(DSL.name("mode"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false).asEnumDataType(net.iponweb.opd.dataservice.generated.enums.Mode.class), this, "");
``` 

But after switching to org.jooq.meta.extensions.ddl.DDLDatabase I'm getting "Object" instead of specified enum type:

```java
    public final TableField<MarginSettingsRecord, Object> MODE = createField(DSL.name("MODE"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"PUBLIC\".\"MARGIN_SETTINGS_MODE\"").nullable(false), this, "");
```
thought enum Mode.class is still generating correctly

### Versions:

- jOOQ: 3.13.4
- Java: 11
- Database (include vendor): PostgreSQL 10.12

**Comment by lukaseder** [comment] 2020-09-03 10:39
Thank you very much for your report. In our integration tests, we don't see any such issue. Can you provide some help to reproduce this problem? We have a template that could be useful for reproduction: https://github.com/jOOQ/jOOQ-mcve

**Comment by pzheltakova** [comment] 2020-09-03 11:47
hi! I've added https://github.com/pzheltakova/jOOQ-mcve
There you can also see that not only enums becomes Object but postrgresql real[] becomes Object[] in generated record.

**Comment by lukaseder** [comment] 2020-09-25 15:06
Thanks a lot for your MCVE, @pzheltakova. I see, the enum type problem should be fixed in jOOQ 3.14.0, which implemented quite a few changes in this area, including upgrading the H2 dependency in that module. There had been a few changes in that area as well.

In any case, as soon as you're using vendor specific features, the `DDLDatabase` might not work as well anymore. In the future, we'll stop translating things to H2 in the `DDLDatabase`, but we're not there yet. Another option rather than interpreting the DDL could be to use test containers to spin up an actual PostgreSQL database for code generation: https://github.com/jOOQ/jOOQ/issues/6551

You could probably do this yourself as well. https://github.com/jOOQ/jOOQ/issues/6551 is just about making this more convenient.

**Comment by lukaseder** [comment] 2023-01-17 13:54
I think this is a duplicate of some other issue. The root problem for this was that H2's enum types weren't capable of mimicking PostgreSQL's at the time this bug was reported, but this has changed, so H2, which is used behind the scenes by `DDLDatabase`, can now emulate the correct type.

Please let me know if the issue still persists on jOOQ 3.17.7

**Closed by lukaseder** 2023-01-17 13:54 UTC
Labels: T: Defect, C: Code Generation, C: DB: PostgreSQL, P: Medium, R: Duplicate, E: All Editions

**Comment by lukaseder** [comment] 2023-01-17 13:55
Related issues:

- https://github.com/jOOQ/jOOQ/issues/13936
- https://github.com/jOOQ/jOOQ/issues/14389
