### ISSUE TITLE
QuantifiedSelect wrapping array doesn't correctly convert array component types

### ISSUE THREAD

**Issue by Walti91** [jOOQ/jOOQ#16179] opened 2024-01-25 12:09 UTC
### Expected behavior

I have a table from which i want to query data using the DSL.any() functionality. On the column i use in the where class i have a converter. if i generate the condition with the static DSL class, everything looks fine. and i get the following condition. 

`where (
      "public"."labels"."id" = 42767
      or "public"."labels"."id" = 42768
  )`

### Actual behavior

Once i execute the sql using the dslContext, which is configured for Postgresql the transformation no longer works because instead of building the condition like before jooq uses the native any clause of postgres but then no longer considers the converter but as far as i can tell simply performs a toString() on the given data.

the where clause looks like this then:

```
where "public"."labels"."id" = any (cast(? as bigint[]))
```

ERROR: invalid input syntax for type bigint: "LabelId[id=42767]"

### Steps to reproduce the problem

i have the following table:

```
create table labels
(
    id bigserial primary key,
    name text
)
```

then i use the following class to wrap the id in:

```
public record LabelId(long id) {}
```

and the following converter:

```
public abstract class LabelIdConverter extends AbstractConverter<Long, LabelId> {

  public LabelIdConverter() {
    super(Long.class, LabelId.class);
  }

  @Override
  public Long to(LabelId id) {
    return id != null ? id.id() : null;
  }

  @Override
    public LabelId from(Long id) {
      return id != null ? new LabelId(id) : null;
    }
}
```

and have the following config for my forced type:

```
 <forcedType>
          <converter>LabelIdConverter</converter>
          <includeExpression>labels.id</includeExpression>
          <userType>LabelId</userType>
</forcedType>
```

now i query labels using the following statement:

```
var labels = dsl.selectFrom(LABELS).where(LABELS.ID.eq(DSL.any(ids))).fetch();
```

### jOOQ Version

jooq 3.18.7

### Database product and version

PostgreSQL 15.4

### Java Version

openjdk 21.0.2

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment] 2024-01-26 10:17
This appears to be a duplicate of https://github.com/jOOQ/jOOQ/issues/10695

**Comment by lukaseder** [comment] 2024-03-12 16:11
Closing as duplicate of https://github.com/jOOQ/jOOQ/issues/10695

**Comment by lukaseder** [comment] 2024-03-13 09:17
Another, related issue:

- https://github.com/jOOQ/jOOQ/issues/16439

**Comment by lukaseder** [comment] 2024-03-13 09:32
Fixed in versions:

- 3.20.0
- 3.19.7 (https://github.com/jOOQ/jOOQ/issues/16440)
- 3.18.14 (https://github.com/jOOQ/jOOQ/issues/16441)

A backport to 3.17 is too risky due to significant refactorings of quantified comparison predicates in jOOQ 3.18

Note that using the `IN` predicate should always work as a workaround, if you don't rely on any runtime characteristics of `eq(any(...))` (e.g. performance related):

```java
dsl.selectFrom(LABELS).where(LABELS.ID.in(ids)).fetch();
```

**Closed by lukaseder** 2024-03-13 09:32 UTC
Labels: T: Defect, C: Functionality, C: DB: PostgreSQL, P: Medium, E: All Editions
