### ISSUE TITLE
@kotlinx.serialization.Serializable

### ISSUE THREAD

**Issue by mleonhard-flexport** [jOOQ/jOOQ#15431] opened 2023-07-28 21:48 UTC
### Use case

We have some code that uses [debezium](https://debezium.io/) to publish Postgres row change events to Kafka.  We have Kotlin code that must consume these events.  The code must deserialize the "before" and "after" versions of the rows into JOOQ-generated row classes.  I wish to use the [`kotlinx.serialization`](https://kotlinlang.org/docs/serialization.html) library for this deserialization.  To do that, we must add the `@kotlinx.serialization.Serializable` annotation to the classes.

I see that our classes already inherit from `java.io.Serializable`.

### Possible solution

Change [GenerationTool.java](https://github.com/jOOQ/jOOQ/blob/2c69f45a7278ad4613c2016dc2bd98964dd4ce30/jOOQ-codegen/src/main/java/org/jooq/codegen/GenerationTool.java) to add the `@kotlinx.serialization.Serializable` annotation to classes.  Add a new `isPojosKotlinxSerializable` option to enable this.

Another option is to enable this when the user sets both `isPojosAsKotlinDataClasses = true` and `isSerializablePojos = true`.  This has the downside of breaking users who are using Java serialization with their Kotlin POJOs.

### Possible workarounds

Use a custom code generator and override `generateRecordClassJavadoc` to add `@kotlinx.serialization.Serializable` after the javadoc.  Docs: 
https://www.jooq.org/doc/latest/manual/code-generation/codegen-custom-code/

### jOOQ Version

3.18.2 Open Source

### Database product and version

PostgreSQL 14 RDS

**Comment by lukaseder** [comment] 2023-07-31 08:51
Thanks for your feature request.

This isn't specifically about the `@kotlinx.serialization.Serializable` annotations, but about annotations in general, a feature request that has been re-occuring frequently. See e.g. 

- https://github.com/jOOQ/jOOQ/issues/13846

The workaround in this case is simple, though admittedly, not very nice.

While I have usually rejected such feature requests due to the complexity of getting this right for arbitrary annotations, I think that one of the more frequent requests is also simpler to implement, namely to add annotations to generated classes (as opposed to methods, attributes, etc.)

I'll mark this as a duplicate of https://github.com/jOOQ/jOOQ/issues/13846, and give the latter some higher priority for 3.19, at least for some cases.

**Closed by lukaseder** 2023-07-31 08:51 UTC
Labels: T: Enhancement, C: Code Generation, P: Medium, R: Duplicate, E: All Editions
