### ISSUE TITLE
SQL Translation Error

### ISSUE THREAD

**Issue by berrujaime** [jOOQ/jOOQ#13451] opened 2022-04-13 18:13 UTC
### SQL translator incorrectly translates this query:

```sql
DELIMITER $$
CREATE TRIGGER triggerSaldo
AFTER INSERT ON Operacion
FOR EACH ROW
BEGIN 
    CASE
      WHEN NEW.tipo = 'i' THEN 
         UPDATE Cuenta
         SET saldo = saldo   NEW.cantidad WHERE IBAN = NEW.origen

**Comment by lukaseder** [comment] 2022-04-14 10:38
Thanks a lot for your report. While we support the `CASE` expression, we do not yet support the `CASE` statement, see: https://github.com/jOOQ/jOOQ/issues/8292

This, however, parses fine:

```sql
DELIMITER $$
CREATE TRIGGER triggerSaldo
AFTER INSERT ON Operacion
FOR EACH ROW
BEGIN 
    IF NEW.tipo = 'i' THEN 
         UPDATE Cuenta
         SET saldo =  NEW.cantidad WHERE IBAN = NEW.origen
    END IF;
END;
```

**Comment by lukaseder** [comment] 2022-04-14 10:38
Closing as duplicate of https://github.com/jOOQ/jOOQ/issues/8292

**Closed by lukaseder** 2022-04-14 10:38 UTC
Labels: T: Defect, P: Medium, E: All Editions, C: Translator
