### ISSUE TITLE
PascalCase and CamelCase clash

### ISSUE THREAD

**Issue by rit001** [jOOQ/jOOQ#15640] opened 2023-09-26 13:57 UTC
### Expected behavior

A database has the following tables  (as well as a few hundred others)

   review_detail
   review

Due to issues outlined in #6729 the naming strategy is left as the default, which is PascalCase according to the 3.18 docs

Once JOOQ generates the resulting files, I should end up with the following table classes 

   Review.java file             with a class defined as Review
   ReviewDetail.java file    with a class defined as ReviewDetail

### Actual behavior

Once JOOQ generates the resulting files, I end up with the following table classes 

   review.java file              with a class defined as Review
   ReviewDetail.java file    with a class defined as ReviewDetail

So the file name for a table that is not 'mult-word' ends up not having its name converted to PascalCase, but the class name is presented as PascalCase, the result is the following compile error
    
error: class Review is public, should be declared in a file named Review.java

### Steps to reproduce the problem

Used the following config to run the generator

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration>
  
  <jdbc>
    <driver>org.mariadb.jdbc.Driver</driver>
    <url>jdbc:mariadb://localhost:3306/vatogo_develop</url>
    <user>root</user>
    <password>password</password>
  </jdbc>

  <generator>
    
    <name>org.jooq.codegen.JavaGenerator</name>

    <database>
      
      <name>org.jooq.meta.mariadb.MariaDBDatabase</name>

      
      <inputSchema>vatogo_develop</inputSchema>

      
      <includes>.*</includes>

      
      <excludes></excludes>
	  
	  <unsignedTypes>true</unsignedTypes>
	  
    </database>

    

    <target>
      
      <packageName>com.example.demo.database</packageName>

      
      <directory>./src/main/java</directory>
    </target>
  </generator>
</configuration>

### jOOQ Version

Open Source 3.18.6

### Database product and version

MariaDB 10.11.5      mariadb-java-client-3.2.0.jar

### Java Version

21

### OS Version

Windows 11 desktop

### JDBC driver name and version (include name if unofficial driver)

org.mariadb.jdbc.Driver     3.2.0

**Comment by lukaseder** [comment] 2023-09-26 14:10
Thanks for your report.

There must be something else going on for your file to be named `review.java` despite the class being named `Review`, which you haven't shared in this issue yet. Can you please provide a complete reproducer? We have a template for MCVEs here: https://github.com/jOOQ/jOOQ-mcve, which was mentioned in the issue template. With that, it's usually quite simple to make such a reproducer that contains everything needed.

**Comment by rit001** [comment] 2023-09-26 16:50
I think this is going to have to be marked as 'unknown' as I can not now cause it to repeat locally with the only change having been a redeploy. The local test cycle has been as simple as this

     reboot
     drop the database from MariaDB
     run SQL script (which is 15416 lines long as it is a database dump)
     run scripted jOOQ
     Look at the resulting file structure
      
And now the results are different between runs.....

**Comment by lukaseder** [comment] 2023-09-27 08:58
One reason why I had this problem in the past was when developing on Windows, where `Review.java` and `review.java` are the same file name (case insensitive file system), and I configured jOOQ not to clear out all the output directory contents.

Now, when playing around with strategies in such a setup, it may well be that a file doesn't get replaced properly. Does that match what might have happened in your case?

**Comment by rit001** [comment] 2023-09-27 09:19
It is a Windows system, so that may have complicated the environment even more, but the config has the output directory being cleared down every time as I found when I set an incorrect output directory and had all my code removed :(. 

The real complication is just about everything being used is the latest tools for Java 21 and Swing Boot 3.2.0 (M3) so there are a few things that are a little 'dynamic'.

**Comment by lukaseder** [comment] 2023-09-28 13:32
I can't reproduce the case where a `Review` class would be generated in a `review.java` file (unless of course this is implemented in a user generator strategy), so I'm closing this as "worksforme".

If you have a reproducer, I'll be happy to reopen and look into it again.

**Closed by lukaseder** 2023-09-28 13:32 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Worksforme, E: All Editions
