### ISSUE TITLE
Latest h2 query with LIMIT in Oracle compatibility mode doesn't work any more

### ISSUE THREAD

**Issue by theodiefenthal** [jOOQ/jOOQ#13969] opened 2022-09-07 20:41 UTC
### Expected behavior

I just upgraded H2 in one of my microservices from 1.4.200 to 2.1.214. The H2 JDBC connection URL contains a `MODE=Oracle` clause. 

I have the following query:
```
        return ctx.selectFrom(MQUEUE)
            .where(MQUEUE.MCTX.eq(context))
            .orderBy(MQUEUE.CREATED_AT)
            .limit(DSL.inline(1))
            .fetchOne();
```
Without changing any code (or JDBC URL or whatever), the following query stopped working. I expect it to work :) 

### Actual behavior

I get a syntax error reported directly before the `limit`. If I remove the `limit` statement, the query will also work again. Here I read that H2 removed the LIMIT with 2.X in oracle compatibility mode: https://stackoverflow.com/questions/56853583/how-to-fix-h2-syntax-error-in-sql-statement

As far as I understand JOOQs awesome magics, it detects on a H2 connection in which Compatibility mode is is running and should hence be able to render the LIMIT to something H2 understands, the same as it does for Oracle. 

### Steps to reproduce the problem

Execute a Query with jooq `limit()` on a H2 2.1.214 database in MODE=Oracle compatibility mode. 

### jOOQ Version

JOOQ Professional 3.16.6

### Database product and version

H2 2.1.214

### Java Version

OpenJDK 11

### OS Version

Windows 10 x64

### JDBC driver name and version (include name if unofficial driver)

H2 2.1.214

**Comment by lukaseder** [comment] 2022-09-08 06:43
Thanks for your message. jOOQ does not support H2's compatibility modes. When you're using jOOQ, you shouldn't require them, because jOOQ already generates correct H2 native SQL. But we can't keep track of all the little incompatible changes of those H2 compatibility modes between H2 releases.

Here's a post that shows how to best use H2 with jOOQ as a test database:
https://blog.jooq.org/using-h2-as-a-test-database-product/

Starting with jOOQ 3.18, we'll stop generating `LIMIT` for `SQLDialect.H2`, and start generating `OFFSET .. FETCH`, always: https://github.com/jOOQ/jOOQ/issues/13891

But again, `LIMIT` used to be perfectly fine in H2 for ages (even though now it's no longer documented, and might be removed incompatibly, eventually!), and jOOQ's `SQLDialect.H2` corresponds to H2 SQL, not to some limited emulation of Oracle by H2.

I'm closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/13891

> it detects on a H2 connection in which Compatibility mode is is running and should hence be able to render the LIMIT to something H2 understands, the same as it does for Oracle.

No, why would jOOQ do that? We'd unnecessarily multiply our test and maintenance efforts across:

- H2 versions
- H2 compatibility modes

The test matrix would explode, when in fact the use-case is obsolete. H2 was a very fine test database 10-15 years ago. But even then, the best way to use jOOQ and H2 was to turn off the compatibility modes, which are useful *only* when using JDBC (or other native SQL APIs) directly. jOOQ's "compatibility mode" is *much better* than H2's. But it works only if you let H2 run in native mode.

You obviously needed another reason to argue in favour of testcontainers and against using H2 in your team? 😅

**Closed by lukaseder** 2022-09-08 06:43 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by theodiefenthal** [comment] 2022-09-08 07:12
> You obviously needed another reason to argue in favour of testcontainers and against using H2 in your team? 😅

:D Yeah, I am currently very happy with the task of upgrading old dependencies in our project, reducing some technical debt... But only upgrading, not replacing stuff like h2 with testcontainers :/  Nice thing is: If I want to remove the oracle compatibility mode in h2, I run into issues with our liquibase changelog and h2 version 2. We have lots of `<column name="DESCRIPTION" type="VARCHAR2(4000 CHAR)">` stuff in there as originally, we were running on Oracle only.. And H2 now renames that stuff to CHARACTERS... Guess I know what my next task is :( Its a good style anyways in liquibase to use properties for different dbs and types instead of writing them directly into the log.. 

But yeah, that's internal to our project. Thanks for linking the blog post which describes exactly the situation I faced yesterday :) "jOOQ doesn’t know about H2’s compatibility modes. This is an important thing to know" thats enough for me to remove the mode=Oracle everywhere in our projet.

**Comment by lukaseder** [comment] 2022-09-08 07:23
> But only upgrading, not replacing stuff like h2 with testcontainers :/

Of course, that's a much bigger change, although, H2 1.4 to 2.x was also quite the change with tons of incompatibilities on the H2 side. You're lucky you waited with this one, so jOOQ could address the most pressing differences.

> If I want to remove the oracle compatibility mode in h2, I run into issues with our liquibase changelog and h2 version 2.

I see, but do you need to remove it there? I don't think the H2 compatibility mode has anything to do with storage. It mostly affects the parser. So you can enable it in Liquibase and disable it in jOOQ? See: https://www.h2database.com/html/features.html#compatibility

You could of course try to use jOOQ's `ParsingConnection` as a proxy in between liquibase and H2 to translate the SQL generated by Liquibase: https://www.jooq.org/doc/latest/manual/sql-execution/parsing-connection/

Although, all of these options obviously aren't as clean as when you're in full control of the SQL / types, so yes, if you continue using H2 as a test database, perhaps you should treat it as a production database alternative, as if you were a product vendor that supports multiple RDBMS...

**Comment by katzyn** [comment] 2022-09-08 09:55
> I don't think the H2 compatibility mode has anything to do with storage.

In Oracle compatibility mode multi-column unique indexes don't allow duplicate rows with `NULL` values only in some indexed columns, for example, so situation with these modes is more complicated.
