### ISSUE TITLE
Incorrect conversion of LocalDateTime to LocalDate during daylight saving time

### ISSUE THREAD

**Issue by Legolek** [jOOQ/jOOQ#14866] opened 2023-03-28 09:49 UTC
### Expected behavior

Hi,
During winter we updated our jOOQ version to 3.17.7 and since last weekend (change standard to daylight saving time) one of our tests started to fail. After some investigation we found that problems occur when we are trying to build condition where value from LocalDate column is compared with provided LocalDateTime value.

In such scenario jOOQ tries to convert LocalDateTime to LocalDate which causes issue during daylight saving time.

Let's say we want to convert LocalDateTime object with value: 2015-12-23T00:00 to LocalDate. Expected result would be 2015-12-23.

### Actual behavior

Piece of code responsible for conversion:
```java
if (LocalDateTime.class == fromClass && Temporal.class.isAssignableFrom(this.toClass)) {
    return toDate(((LocalDateTime)from).toInstant(OffsetTime.now().getOffset()).toEpochMilli(), ((LocalDateTime)from).getNano(), this.toClass);
}
```

In daylight saving time abovementioned code is taking offset from current time which is UTC+2 (in Poland) so it decides that that offset is 7200000 milliseconds (2 hours) and calculates number of milliseconds for UTC date 2015-12-22T22:00.
Then this long millis value is being converted to java.sql.Date which looks at timezone and decides that timezone for date 2015-12-22T22:00 was actually in UTC+1 and sets value of Date to 2015-12-22T23:00+01:00 which then is converted toLocalDate and returns value 2015-12-22.

Problem seems to be that conversion from LocalDateTime to Instant always uses "now" timezone offset instead of actually converted date timezone offset.

### Steps to reproduce the problem

In general create where condition where you compare column mapped to LocalDate and provide LocalDateTime value.
LocalDateTime needs to be from standard time period and execution during daylight saving time period.

I can prepare mcve later if needed.

Don't know if thats useful but here is piece of code:
```java
public static void main(String[] args) {
  LocalDateTime from = LocalDateTime.of(2015, 12, 23, 0, 0, 0);
  LocalDate localDate = toDate(((LocalDateTime) from).toInstant(OffsetTime.now().getOffset()).toEpochMilli());
  System.out.println(localDate);
}
private static LocalDate toDate(long time) {
  return new java.sql.Date(time).toLocalDate();
}
```
that returns 2015-12-22 during daylight saving time period instead of 2015-12-23.
During standard time period it returns 2015-12-23.

### jOOQ Version

3.17.7

### Database product and version

MySQL 5.7

### Java Version

openjdk version "17"

**Comment by jgmur-prg** [comment] 2024-04-04 10:49
Is there a fix planned for this? It's an issue that started affecting us also.

**Comment by lukaseder** [comment] 2024-04-04 11:28
Yeah, we're using `OffsetTime.now().getOffset()` which is the current time zone. Instead, we should be using `ZoneId.systemDefault()`, and use `LocalDateTime.atZone(..)`, at least whenever `Timestamp`, `LocalDateTime`, `OffsetDateTime`, and `Instant` are involved.

Can any of you confirm that this patch will address the actual issues you're seeing?

```patch
diff --git a/jOOQ/src/main/java/org/jooq/impl/Convert.java b/jOOQ/src/main/java/org/jooq/impl/Convert.java
index 5f5ee9a..213274f 100644
--- a/jOOQ/src/main/java/org/jooq/impl/Convert.java
+++ b/jOOQ/src/main/java/org/jooq/impl/Convert.java
@@ -77,6 +77,7 @@
 import java.time.OffsetDateTime;
 import java.time.OffsetTime;
 import java.time.Year;
+import java.time.ZoneId;
 import java.time.format.DateTimeParseException;
 import java.time.temporal.Temporal;
 import java.util.ArrayList;
@@ -1053,7 +1054,7 @@
                     if (LocalDateTime.class == fromClass && Timestamp.class == toClass)
                         return (U) Timestamp.valueOf((LocalDateTime) from);
                     else if (LocalDateTime.class == fromClass && Temporal.class.isAssignableFrom(toClass))
-                        return toDate(((LocalDateTime) from).toInstant(OffsetTime.now().getOffset()).toEpochMilli(), ((LocalDateTime) from).getNano(), toClass);
+                        return toDate(((LocalDateTime) from).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli(), ((LocalDateTime) from).getNano(), toClass);
                     else if (LocalDate.class == fromClass && Date.class == toClass)
                         return (U) Date.valueOf((LocalDate) from);
                     else if (LocalTime.class == fromClass && Time.class == toClass)
@@ -1158,7 +1159,7 @@
 
                     // Try "local" ISO date formats first
                     try {
-                        return (U) java.sql.Timestamp.valueOf((String) from).toLocalDateTime().atOffset(OffsetDateTime.now().getOffset());
+                        return (U) java.sql.Timestamp.valueOf((String) from).toLocalDateTime().atZone(ZoneId.systemDefault()).toOffsetDateTime();
                     }
                     catch (IllegalArgumentException e1) {
                         try {
@@ -1174,7 +1175,7 @@
 
                     // Try "local" ISO date formats first
                     try {
-                        return (U) java.sql.Timestamp.valueOf((String) from).toLocalDateTime().atOffset(OffsetDateTime.now().getOffset()).toInstant();
+                        return (U) java.sql.Timestamp.valueOf((String) from).toLocalDateTime().atZone(ZoneId.systemDefault()).toInstant();
                     }
                     catch (IllegalArgumentException e1) {
                         try {
@@ -1663,7 +1664,7 @@
             else if (toClass == LocalDateTime.class)
                 return (X) toTimestamp(time, nanos).toLocalDateTime();
             else if (toClass == OffsetDateTime.class)
-                return (X) toTimestamp(time, nanos).toLocalDateTime().atOffset(OffsetDateTime.now().getOffset());
+                return (X) toTimestamp(time, nanos).toLocalDateTime().atZone(ZoneId.systemDefault()).toOffsetDateTime();
             else if (toClass == Instant.class)
                 if (nanos == 0L)
                     return (X) Instant.ofEpochMilli(time);
```

**Comment by lukaseder** [comment] 2024-04-04 11:29
Regarding the title:

> Incorrect conversion of LocalDateTime to LocalDate during daylight saving time

That's not an accurate description of the problem. More accurate:

- Winter `LocalDateTime` are converted wrongly during summer time
- Summer `LocalDateTime` are converted wrongly during winter time

**Comment by lukaseder** [comment] 2024-04-04 11:41
Fixed in versions:

- 3.20.0
- 3.19.7 (https://github.com/jOOQ/jOOQ/issues/16540)
- 3.18.14 (https://github.com/jOOQ/jOOQ/issues/16541)
- 3.17.23 (https://github.com/jOOQ/jOOQ/issues/16542)

**Closed by lukaseder** 2024-04-04 11:41 UTC
Labels: T: Defect, C: Functionality, P: High, E: All Editions

**Comment by lukaseder** [comment] 2024-04-04 11:44
This went undetected because the relevant unit tests used the same flawed logic, so the tests expected a wrong date, and jOOQ delivered the exact wrong date.

**Comment by karolina-prusaczyk** [comment] 2024-04-04 11:47
Thanks a lot @lukaseder ! When are you planning to release 3.19.7?

**Comment by lukaseder** [comment] 2024-04-04 11:48
@karolina-prusaczyk Maybe today, given the severity of this issue. But I'd love to have confirmation that this fixes the *actual* issue you've encountered, not just the reproducer in the issue description.

**Comment by karolina-prusaczyk** [comment] 2024-04-04 11:50
> @karolina-prusaczyk Maybe today, given the severity of this issue. But I'd love to have confirmation that this fixes the _actual_ issue you've encountered, not just the reproducer in the issue description.

Sure thing, I will check that. Thanks!

**Comment by lukaseder** [comment] 2024-04-04 12:09
You can also build from github if that's easier than patching your existing version.

**Comment by karolina-prusaczyk** [comment] 2024-04-04 12:22
Thanks, I did just that - it was easier. Your fix works, thanks a million! :slightly_smiling_face: :partying_face:

**Comment by karolina-prusaczyk** [comment] 2024-04-04 12:22
> You can also build from github if that's easier than patching your existing version.

Thanks, I did just that - it was easier. Your fix works, thanks a million! :slightly_smiling_face: :partying_face:

**Comment by lukaseder** [comment] 2024-04-04 12:34
OK, thanks for the feedback! I'll kick off the deployment then. Will take 3-4 hours if nothing goes wrong.

**Comment by karolina-prusaczyk** [comment] 2024-04-04 12:35
Awesome! :raised_hands:

**Comment by lukaseder** [comment] 2024-04-04 14:04
Duplicate of this issue:

- https://github.com/jOOQ/jOOQ/issues/14943
