### ISSUE TITLE
[org.jooq.impl.DefaultDSLContext]: Factory method 'dslContext' threw exception; nested exception is java.lang.StackOverflowError

### ISSUE THREAD

**Issue by xuzhao103389** [jOOQ/jOOQ#7994] opened 2018-10-30 16:45 UTC
### Steps to reproduce the problem (include example code if possible):
When I was depoying my zipkin-server onto Gaia,
it returens the error:

```
[org/springframework/boot/autoconfigure/jooq/JooqAutoConfiguration$DslContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jooq.impl.DefaultDSLContext]: Factory method 'dslContext' threw exception; nested exception is java.lang.StackOverflowError
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:590) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1256) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1105) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at com.jpmorgan.geeni.api.zipkinserver.ZipkinServerApplication.main(ZipkinServerApplication.java:16) [classes/:?]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
2018-10-30T16:07:03.751+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app/:?]
```

workaround:
the only workaround I found is that, enhance my tomcat memory to 10GB, and then the service can be started up

### Versions:

- jOOQ:
3.11.5
- Java:
1.8
- Database (include vendor):
mysql
- OS: cloudFoundry
- JDBC Driver (include name if inofficial driver):
com.mysql.jdbc.Driver

**Comment by lukaseder** [comment] 2018-10-30 16:52
Thank you for your report. Do you have the stack trace for that `StackOverflowError`? Also, how can this be reproduced?

**Comment by xuzhao103389** [comment] 2018-10-31 09:50
Hi, I hit this issue, when I was trying to deploy zipkin-server onto my cloud Foundry.
my zipkin-server is 2.11.7, and I put jooq as a dependency into my pom, that is because 
zipkin is using jooq to connect to mysql .

here is the full stack:
2018-10-31T09:49:43.259+00:00 [APP/PROC/WEB/0] [OUT] Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-10-31T09:49:43.268+00:00 [APP/PROC/WEB/0] [OUT] 2018-10-31 09:49:43.261 ERROR 7 --- [ main] o.s.b.SpringApplication : Application run failed
2018-10-31T09:49:43.268+00:00 [APP/PROC/WEB/0] [OUT] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dslContext' defined in class path resource [org/springframework/boot/autoconfigure/jooq/JooqAutoConfiguration$DslContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jooq.impl.DefaultDSLContext]: Factory method 'dslContext' threw exception; nested exception is java.lang.StackOverflowError
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:590) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1256) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1105) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at com.jpmorgan.geeni.api.zipkinserver.ZipkinServerApplication.main(ZipkinServerApplication.java:16) [classes/:?]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app/:?]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app/:?]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:?]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app/:?]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jooq.impl.DefaultDSLContext]: Factory method 'dslContext' threw exception; nested exception is java.lang.StackOverflowError
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:582) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] ... 26 more
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] Caused by: java.lang.StackOverflowError
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[app/:?]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_92]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.autoconfigure.jooq.JooqAutoConfiguration$DslContextConfiguration.dslContext(JooqAutoConfiguration.java:138) ~[spring-boot-autoconfigure-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-31T09:49:43.269+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.autoconfigure.jooq.JooqAutoConfiguration$DslContextConfiguration$$EnhancerBySpringCGLIB$$e2d39e4b.CGLIB$dslContext$0(<generated>) ~[spring-boot-autoconfigure-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-31T09:49:43.270+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.autoconfigure.jooq.JooqAutoConfiguration$DslContextConfiguration$$EnhancerBySpringCGLIB$$e2d39e4b$$FastClassBySpringCGLIB$$7737172a.invoke(<generated>) ~[spring-boot-autoconfigure-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-31T09:49:43.270+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.270+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.270+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.autoconfigure.jooq.JooqAutoConfiguration$DslContextConfiguration$$EnhancerBySpringCGLIB$$e2d39e4b.dslContext(<generated>) ~[spring-boot-autoconfigure-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
2018-10-31T09:49:43.270+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
2018-10-31T09:49:43.270+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
2018-10-31T09:49:43.270+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
2018-10-31T09:49:43.270+00:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
2018-10-31T09:49:43.270+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.270+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:582) ~[spring-beans-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
2018-10-31T09:49:43.270+00:00 [APP/PROC/WEB/0] [OUT] ... 26 more
2018-10-31T09:49:43.331+00:00 [APP/PROC/WEB/0] [OUT] Exit status 1
2018-10-31T09:49:43.333+00:00 [CELL/0] [OUT] Exit status 0
2018-10-31T09:49:43.343+00:00 [CELL/0] [OUT] Stopping instance ddfc9d6d-8e5f-4ff4-765a-6db0
2018-10-31T09:49:43.343+00:00 [CELL/0] [OUT] Destroying container
2018-10-31T09:49:43.362+00:00 [API/1] [OUT] Process has crashed with type: "web"
2018-10-31T09:49:43.385+00:00 [API/1] [OUT] App instance exited with guid 1664cb63-39df-4628-97e9-674a41605b21 payload: {"instance"=>"ddfc9d6d-8e5f-4ff4-765a-6db0", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>4, "crash_timestamp"=>1540979383335751646, "version"=>"9c22524e-1f3b-4136-9e09-225fe4a11eb3"}
2018-10-31T09:49:43.959+00:00 [CELL/0] [OUT] Successfully destroyed container

**Comment by lukaseder** [comment] 2018-10-31 10:32
Thanks for the update. I think I've seen a similar error in the past. The key line is this one, among others:

```
org.springframework.boot.autoconfigure.jooq.JooqAutoConfiguration$DslContextConfiguration$$EnhancerBySpringCGLIB$$e2d39e4b$$FastClassBySpringCGLIB$$7737172a.invoke(<generated>)
```

It seems that you're instrumenting tons of jOOQ API. With an MCVE (https://stackoverflow.com/help/mcve), I could try to reproduce it, but with your description that seems quite difficult. In any case, I don't think the problem is strictly jOOQ related, but depends on how you set up Spring.

**Comment by xuzhao103389** [comment] 2018-10-31 10:37
Hi 
in fact the only thing I did is to put jooq dependency into my pom, 
actually zipkin-server is using jooq to connect to mysql, I am not using it .
but it is will great if you can give any suggestions to avoid it

**Comment by lukaseder** [comment] 2018-10-31 11:46
Well, my suggestion is to contact zipkin then. I really don't see how this could be solved from the jOOQ side

**Comment by lukaseder** [comment] 2018-10-31 11:49
I'm closing this issue on the jOOQ side. I cannot really easily reproduce this, nor do I think it is strictly jOOQ related. If some other library / framework excessively instruments a library like jOOQ, that's what they're doing for whatever reason. It is not really related to jOOQ as far as I can tell from this discussion.

**Closed by lukaseder** 2018-10-31 11:49 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Worksforme, T: Defect

**Comment by xuzhao103389** [comment] 2019-01-04 09:38
By my testing, spring did not instrumenting tons of api calls for dslcontext, there is only 1 call.
I am pretty sure that there is memory leakage within this API:
public DefaultDSLContext(Configuration configuration) {
    super(configuration, configuration == null ? null : configuration.data());
  }

**Comment by lukaseder** [comment] 2019-01-04 09:54
> By my testing, spring did not instrumenting tons of api calls for dslcontext, there is only 1 call.

What does this mean? Can you help me reproduce this "1 call"? Ideally by providing an MCVE: https://github.com/jOOQ/jOOQ-mcve

> I am pretty sure that there is memory leakage within this API

Really? :) Based on what specific observation?

**Comment by xuzhao103389** [comment] 2019-01-04 09:58
I did printings , it only enters DefaultDSLContext once , if I allocate 1GB for my service, 
then stackoverflow, if I allocate 10GB, then it is passed

**Comment by lukaseder** [comment] 2019-01-04 10:12
> I did printings , it only enters DefaultDSLContext once , if I allocate 1GB for my service,
then stackoverflow, if I allocate 10GB, then it is passed

But that doesn't mean that whatever happens from within that `DefaultDSLContext()` constructor is not instrumented by some tool you're using. I definitely don't think that jOOQ itself is allocating this much memory on its own. This would be the first time I hear about this.

Perhaps you'll be able to track this down using Java Mission Control / Java Flight Recorder, or even VisualVM?

**Comment by lukaseder** [comment] 2019-01-04 11:01
I don't deny there is a problem worth addressing but as I said:

- I don't think this is really a jOOQ problem even if it seems to happen with jOOQ specifically. The jOOQ API is vast and may trigger a bug somewhere else that is not being triggered by other APIs
- I still don't know how to reproduce this, nor do the spring boot folks know how to reproduce this yet.

Please also observe this comment here: https://github.com/spring-projects/spring-boot/issues/8799#issuecomment-291632128

Quite obviously, there is a bug somewhere on your stack that may well be *triggered* by jOOQ, but again, I don't think it is a jOOQ problem.

**Comment by xuzhao103389** [comment] 2019-01-04 11:10
Hi


> I don't deny there is a problem worth addressing but as I said:
> 
> * I don't think this is really a jOOQ problem even if it seems to happen with jOOQ specifically. The jOOQ API is vast and may trigger a bug somewhere else that is not being triggered by other APIs
> * I still don't know how to reproduce this, nor do the spring boot folks know how to reproduce this yet.
> 
> Please also observe this comment here: [spring-projects/spring-boot#8799 (comment)](https://github.com/spring-projects/spring-boot/issues/8799#issuecomment-291632128)
>I read this comment as well , the way he did is similar to me:)(increase the memory for tomcat)

> Quite obviously, there is a bug somewhere on your stack that may well be _triggered_ by jOOQ, but again, I don't think it is a jOOQ problem.
