### ISSUE TITLE
Add fetchOneAsync

### ISSUE THREAD

**Issue by zatziky** [jOOQ/jOOQ#8354] opened 2019-02-26 09:26 UTC
### Use case:

We need to fetch one result asynchronously.

### Possible solution you'd like to see:

I'd like to see a method `fetchOneAsync()`. 

```
return dsl
   ...
   .fetchOneAsync()
```

### Possible workarounds:

```
return supplyAsync(() -> {
    return dsl
       ...
       .fetchOne()
)
```

### Additional info
There's already `fetchAsync()` but it maps to a collection.

**Comment by lukaseder** [comment] 2019-02-26 09:36
Thank you very much for your suggestion. I'll close this as a duplicate of #7951

**Closed by lukaseder** 2019-02-26 09:36 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Duplicate, T: Enhancement
