### ISSUE TITLE
Add extension points for DefaultRecordMapper

### ISSUE THREAD

**Issue by baev** [jOOQ/jOOQ#10062] opened 2020-04-13 19:04 UTC
### Use case:

Working on queries that use JSON aggregation functions (like `json_build_object` and `json_agg` in PostgreSQL) requires to write many boilerplate code in order to map JSON fields to objects:

```java
   //query
    var result = dsl
        .select(
            PERSON.DEPARTAMENT_ID, 
            function("json_build_object", JSON.class, val("count"), count())
        )
        .from(PERSON)
        .groupBy(PERSON.DEPARTAMENT_ID)
        .fetch()
        .map(record -> new StatDto(
                        record.component1(),
                        // basically objectMapper.readValue(obj, type)
                        convert(record.component2(), CountDto.class)
        ));

    //dtos
    @lombok.Value
    class StatDto {
       Long depId;
       CountDto stats;
    }

    @lombok.Value
    class CountDto {
       Long count;
    }
```

In order to use `.into(StatDto.class)` method, we need to change `StatDto.stats` field type to `JSON` , that requires additional processing later on. The other option would be to introduce `(Long, JSON)` constructor to `StatDto.class` but that means to copy paste mapping logic all across the project.

PS I'm aware of `.fetch(field, converter)` API provided by JOOQ, but for us such aggregation queries always using multi-select, so it would require aggregation later on.

### Possible solution you'd like to see:

Having a possibility to register custom type converter for `DefaultRecordMapper` on JOOQ's configuration level. 

Plus currently it's pretty much impossible to extend `DefaultRecordMapper` as it uses internal private API's. So splitting it to separate classes would help a lot either

### Versions:

- jOOQ: 3.13.1
- Java: openjdk version "11.0.2" 2019-01-15
- Database (include vendor): PostgreSQL

**Comment by lukaseder** [comment] 2020-04-14 10:11
Thanks for your suggestions. This request can be decomposed into different parts.

### We already support mapping into nested POJOs:

A lesser known feature is the possibility of using a column naming convention to auto-map flat results into nested POJOs. In your case, you could just write this, without resorting to using JSON:

```java
    var result = dsl
        .select(
            PERSON.DEPARTAMENT_ID.as("depId"), 
            count().as("stats.count")
        )
        .from(PERSON)
        .groupBy(PERSON.DEPARTAMENT_ID)
        .fetchInto(StatDto.class);
```

I think that's the best approach in this particular example. There may obviously be more complex examples where this doesn't work, but it does, in your case.

### Your suggestions

> Having a possibility to register custom type converter for `DefaultRecordMapper` on JOOQ's configuration level.

We already have that as well:
https://www.jooq.org/doc/latest/manual/sql-execution/fetching/pojos-with-recordmapper-provider/

Just override the `DefaultRecordMapper` in a new `RecordMapperProvider`.

> Plus currently it's pretty much impossible to extend `DefaultRecordMapper` as it uses internal private API's. So splitting it to separate classes would help a lot either

Making everything closed is a very strategic decision, and I still think it was a good choice. I've already pointed you towards two much better features than what you may have had in mind if you were able to "extend" the `DefaultRecordMapper`. Plus, we'll discuss future features as well.

In my opinion, between "extending" code that was not meant to be extended, and simply patching the code, there isn't a big difference. Both approaches are very brittle, and there should always be a better solution.

Implementations of jOOQ will not be opened up for extension. We might introduce new and better SPIs (like the `RecordMapperProvider`), though, see below.

### JSON (or XML) auto-mapping

I think it would make perfect sense to introduce new SPIs that allow for providing jOOQ with possible implementations for JSON / XML binding APIs, which would then be used by the `RecordMapper`. In case of XML, JAXB would be an obvious choice. With JSON, there are alternatives. We cannot introduce a dependency on any third party library for this (I already regret the JAXB dependency of the code generator since JDK 9). But with an SPI, this will be indeed very simple for users to implement. I've created a separate feature request for this: https://github.com/jOOQ/jOOQ/issues/10065

**Comment by lukaseder** [comment] 2020-04-14 10:12
I'm closing this as a duplicate of #10065. We'll definitely implement #10065 for jOOQ 3.14, though, as a part of our XML/JSON improvement efforts.

**Closed by lukaseder** 2020-04-14 10:12 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Duplicate, T: Enhancement

**Comment by baev** [comment] 2020-04-14 10:43
I'm aware of nested POJOs support in JOOQ. In my case we are always using `json_agg` together with `json_build_object`, the code provided is just a simplified example. I guess #10065 will work for us, thanks.

**Comment by lukaseder** [comment] 2020-04-14 10:46
> I'm aware of nested POJOs support in JOOQ. In my case we are always using `json_agg` together with `json_build_object`, the code provided is just a simplified example.

I was afraid of that :)

> I guess #10065 will work for us, thanks.

Yes, that should do it. We'll make sure our integration tests will cover such usage

**Comment by lukaseder** [comment] 2020-04-14 14:32
As discussed in #10065, an even more generic feature would be to revive the `ConverterProvider` discussion from #3896

**Comment by lukaseder** [comment] 2020-04-15 14:59
For the record, this will work in jOOQ 3.14: https://github.com/jOOQ/jOOQ/issues/3896#issuecomment-613994500

I'm now thinking about offering an out-of-the-box `ConverterProvider` that supports Gson, Jackson, or JAXB, if we find it on the classpath. If the default doesn't work well enough, of course, it can be overridden with this new `ConverterProvider`
