### ISSUE TITLE
ERROR: subquery in FROM must have an alias, when used in PostgreSQL MERGE

### ISSUE THREAD

**Issue by mundus08** [jOOQ/jOOQ#14582] opened 2023-02-06 16:45 UTC
### Expected behavior

Perform merge request (worked in older versions of jooq and postgres)

### Actual behavior

SQL error
org.jooq.exception.DataAccessException: SQL [merge into "data"."flatex_depotumsaetze" using (select 1 as "one") on "data"."flatex_depotumsaetze"."ta_nr" = ? when matched then update set "isin" = ?]; ERROR: subquery in FROM must have an alias
  Hinweis: For example, FROM (SELECT ...) [AS] foo.
  Position: 48

### Steps to reproduce the problem

         jooq.mergeInto(FLATEX_DEPOTUMSAETZE)
             .using(jooq.selectOne())
             .on(FLATEX_DEPOTUMSAETZE.TA_NR.eq((long)0))
             .whenMatchedThenUpdate()
             .set(FLATEX_DEPOTUMSAETZE.ISIN,"asd")
             .execute();

### jOOQ Version

3.17.7

### Database product and version

PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Java Version

jdk-17.0.4.1 

### OS Version

Windows 11

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.3

**Comment by lukaseder** [comment] 2023-02-08 10:09
Thanks a lot for your report. I'll look into this right away.

As a workaround, you could use jOOQ's synthetic `usingDual()` method, or explicitly pass the alias.

**Comment by lukaseder** [comment] 2023-02-08 10:25
Hmm, we do have an integration test query that runs correctly on PostgreSQL:

```java
create().mergeInto(TAuthor())
        .using(selectOne())
        .on(TAuthor_ID().equal(inline(1)))
        .whenMatchedThenUpdate()
        .set(TAuthor_FIRST_NAME(), "John")
        .whenNotMatchedThenInsert(TAuthor_ID(), TAuthor_LAST_NAME())
        .values(3, "Hitchcock")
        .execute();
```

It produces this query here:

```sql
merge into "public"."t_author"
using (
  select
    'Herman' as "f",
    'Hesse' as "l"
) as dummy_66582986("f", "l")
on "public"."t_author"."last_name" = "l"
when not matched then insert ("id", "first_name", "last_name", "date_of_birth")
values (
  4, 
  "f", 
  "l", 
  date '1970-01-01'
)
```

Note the correct application of a dummy alias. Are you sure you used the right `SQLDialect`?

**Comment by mundus08** [comment] 2023-02-08 15:49
I made a minimal repro but the error still occurs:
As soon as I use
   .using(ctx.selectOne())
or
   .usingDual()
a query containing
   using (select 1 as "one") on "data"."z_test"."unique" = ?
is executed.

Java code
```
import static org.mb.db.db_01.gen.data.Tables.Z_TEST;

         String url = "jdbc:postgresql://db-01:5432/Finanz_V02";
         Connection conn = DriverManager.getConnection(url, userName, password);
         DSLContext ctx = DSL.using(conn, SQLDialect.POSTGRES);

         logger_.debug ("Dialect {}", ctx.dialect());
         ctx.mergeInto(Z_TEST)
            .using(ctx.selectOne())
            // .usingDual()
            .on(Z_TEST.UNIQUE.equal(0))
            .whenMatchedThenUpdate()
            .set(Z_TEST.VALUE, "v5")
            .whenNotMatchedThenInsert(Z_TEST.UNIQUE, Z_TEST.VALUE)
            .values(0, "v6")
            .execute();
```

DDL
```
CREATE TABLE data.z_test (
  pk SERIAL,
  "unique" INTEGER NOT NULL,
  value VARCHAR(40),
  CONSTRAINT z_test_pkey PRIMARY KEY(pk),
  CONSTRAINT z_test_unique_key UNIQUE("unique")
) ;
```

Debug log
```
2023-02-08 16:45:54,845 DEBUG [main] [org.mb.apps.AppDb1] Dialect POSTGRES
2023-02-08 16:45:55,275 INFO  [main] [org.jooq.Constants] 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.17.7
                                      
2023-02-08 16:45:55,277 INFO  [main] [org.jooq.Constants] 

2023-02-08 16:45:55,322 DEBUG [main] [org.jooq.tools.LoggerListener] Executing query          : merge into "data"."z_test" using (select 1 as "one") on "data"."z_test"."unique" = ? when matched then update set "value" = ? when not matched then insert ("unique", "value") values (?, ?)
2023-02-08 16:45:55,324 DEBUG [main] [org.jooq.tools.LoggerListener] -> with bind values      : merge into "data"."z_test" using (select 1 as "one") on "data"."z_test"."unique" = 0 when matched then update set "value" = 'v5' when not matched then insert ("unique", "value") values (0, 'v6')
2023-02-08 16:45:55,354 DEBUG [main] [org.jooq.tools.LoggerListener] Exception                
org.jooq.exception.DataAccessException: SQL [merge into "data"."z_test" using (select 1 as "one") on "data"."z_test"."unique" = ? when matched then update set "value" = ? when not matched then insert ("unique", "value") values (?, ?)]; ERROR: subquery in FROM must have an alias

```

**Comment by lukaseder** [comment] 2023-02-08 16:18
Ah yes, I see. I tried jOOQ 3.18.0-SNAPSHOT on my end. jOOQ 3.17 doesn't yet support PostgreSQL 15: https://github.com/jOOQ/jOOQ/issues/13358

See also:
https://www.jooq.org/download/support-matrix

3.18 will be released soon, so this will work eventually, for you. Until then, may I recommend using the snapshot version if you need `MERGE`?

Closing this as duplicate of https://github.com/jOOQ/jOOQ/issues/13358

**Comment by lukaseder** [comment] 2023-02-08 16:18
Snapshots are available from here, if you're licensed: https://www.jooq.org/download/versions, or you can build directly from github.

**Closed by lukaseder** 2023-02-08 16:18 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Feedback Pending, E: All Editions

**Comment by mundus08** [comment] 2023-02-09 11:26
Thank you very much for your support!
>  jOOQ 3.17 doesn't yet support PostgreSQL 15
I used PostgreSQL 14 with jOOQ 3.17 before - unfortunately jOOQ 3.17 uses the merge statement which does not exist in PostgreSQL 14. If I remember correctly the merge statement was emulated in earlier versions of jOOQ for PostgreSQL. This no longer seems to be the case with the jOOQ 3.17 and  PostgreSQL 14 .
