### ISSUE TITLE
Restore streaming bind value method behaviour on ParsingStatement

### ISSUE THREAD

**Issue by richharms** [jOOQ/jOOQ#12666] opened 2021-11-25 16:50 UTC
### Use case:

I've been using DSLContext and obtaining a Connection from it to support database independence in an application:

        dslContext = DslContextFactory.getInstance().getDslContext();
        connection = dslContext.parsingConnection();

With jOOQ 3.15, it looks like setBinaryStream and setCharacterStream have been left unimplemented as part of a rewrite of some functionality in ParsingStatement. I'd ideally like to see this functionality restored and be able to continue to utilize jOOQ.

### Possible solution you'd like to see:

Restore implementations of these two functions.

    @Override
    public final void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public final void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

### Possible workarounds:

Downgraded to 3.14.

### Versions:

- jOOQ: 3.15.4
- Java: OpenJDK Runtime Environment Corretto-17.0.1.12.1 (build 17.0.1+12-LTS)
- Database (include vendor): mysql  Ver 8.0.27 for macos11 on x86_64 (MySQL Community Server - GPL)
- OS: macOS 12.0.1
- JDBC Driver (include name if inofficial driver): mysql-connector-java 8.0.27

**Comment by lukaseder** [comment] 2021-11-26 07:43
Thanks for your report. Indeed, the reason this logic was changed was https://github.com/jOOQ/jOOQ/issues/11512

The problem that #11512 solved is that a lot of parsing / translating decisions depend on the actual type of a bind value, which isn't always possible to infer from input SQL. For example:

```sql
select ? + ?
```

If both are numbers, the result is a number. If one value is a date and the other is a number, the result is a date, and this translates to some `DATE_ADD()` function. There are many of these cases, and the net benefit of refactoring this was much bigger than the risk of introducing regressions by omitting some bind value types that we currently don't know what to do about.

However, the case is different for streams and readers, which could simply be collected into memory as `String` or `byte[]` as a workaround. This may not be what users using these methods intended from a memory footprint perspective, but at least it would work.

I don't currently see how the input stream can be forwarded to the target JDBC driver via jOOQ's translation mechanism. jOOQ doesn't currently have a representation of a streaming bind value or result set data type.

**Comment by lukaseder** [comment] 2021-11-26 07:48
Changing the title, as this affects also other types of bind values, including:

- `PreparedStatement::setAsciiStream` -> `setString`
- `PreparedStatement::setUnicodeStream` -> `setString`
- `PreparedStatement::setBinaryStream` -> `setBytes`
- `PreparedStatement::setCharacterStream` -> `setString`
- `PreparedStatement::setBlob` -> `setBytes`
- `PreparedStatement::setClob` -> `setString`
- `PreparedStatement::setNClob` -> `setString`
- `PreparedStatement::setNCharacterStream` -> `setString`

**Comment by lukaseder** [comment] 2021-11-26 08:06
Will implement these using new auxiliary stream handling API: https://github.com/jOOQ/jOOQ/issues/12667

**Comment by lukaseder** [comment] 2021-11-26 10:21
Commits here: https://github.com/jOOQ/jOOQ/commit/0d77372b5e42b545ce45cb0409c7fddab5e5e194, https://github.com/jOOQ/jOOQ/commit/04257397292f8f1c83b6492df187eba82517502f

Fixed in jOOQ 3.16.0 and 3.15.5 (https://github.com/jOOQ/jOOQ/issues/12669). Thanks again for your report!

**Closed by lukaseder** 2021-11-26 10:21 UTC
Labels: T: Defect, P: Medium, E: All Editions, C: Parser

**Comment by richharms** [comment] 2021-12-04 15:38
Thank you for taking care of this so quick! I had a chance to test it today and everything is working great.

**Comment by lukaseder** [comment] 2021-12-04 16:10
Great to hear, thanks a lot for your feedback
