### ISSUE TITLE
Calling iterator() on a stream causes eager evaluation

### ISSUE THREAD

**Issue by chriskiehl** [jOOQ/jOOQ#14640] opened 2023-02-15 03:41 UTC
### Expected behavior

My rough expectation is that the `iterator()` to be non-eager (as described in the [docs here](https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html#StreamOps) ). However, it looks like calling it eagerly evaluates the stream. 

Here's a small example: 

**No call to iterator, directly consuming stream:**

```
long start = System.currentTimeMillis();
tx.dsl()
    .select(STUFF.ID).from(STUFF).limit(1000)
    .fetchSize(1)
    .stream()
    .forEach(__ -> {
        System.out.println("First result after: " + (System.currentTimeMillis() - start));
    });
```

This starts printing results as fast as the DB can vend them. A few milliseconds or so. 

### Actual behavior

The stream is eagerly consumed before allowing iteration. Here's an example: 

```
long start = System.currentTimeMillis();
tx.dsl()
    .select(STUFF.ID).from(STUFF).limit(1000)
    .fetchSize(1)
    .stream()
    .iterator()  // hangs out here while fetching the entire data set
    .next());
 System.out.println("First result after: " + (System.currentTimeMillis() - start));    
```

Is this expected behavior or a bug? `interator()` being an exception to the usual rule for terminal operators is pretty understated in the docs. So, I'm not sure if JOOQ is expected to honor it or not. 

### Steps to reproduce the problem

```
long start = System.currentTimeMillis();
tx.dsl()
    .select(STUFF.ID).from(STUFF).limit(1000)
    .fetchSize(1)
    .stream()
    .iterator()  // hangs out here while fetching the entire data set
    .next());
 System.out.println("First result after: " + (System.currentTimeMillis() - start));    
```

### jOOQ Version

JOOQ 3.14 

### Database product and version

Postgresql 12.xx 

### Java Version

OpenJDK 8 

### OS Version

MacOS

### JDBC driver name and version (include name if unofficial driver)

org.postgresql_postgresql-42.3.6

**Comment by lukaseder** [comment] 2023-02-15 08:12
Thanks for your report.

You're using jOOQ 3.14, which is 2.5 years old. jOOQ has improved quite a bit, including:

- #11892, which prevents fetching intermediate results, if unneeded
- #11895, which addresses fetching everything at once

Both have been implemented in jOOQ 3.15.

The current implementation of `ResultQuery::fetchStream` is:

```java
@Override
default Stream<R> fetchStream() {
    if (fetchIntermediateResult(Tools.configuration(this)))
        return fetch().stream();

    // [#11895] Don't use the Stream.of(1).flatMap(i -> fetchLazy().stream())
    //          trick, because flatMap() will consume the entire result set
    AtomicReference<Cursor<R>> r = new AtomicReference<>();

    // [#11895] Don't use the Stream.of(1).flatMap(i -> fetchLazy().stream())
    //          trick, because flatMap() will consume the entire result set
    return StreamSupport.stream(
        () -> {
            Cursor<R> c = fetchLazy();
            r.set(c);
            return c.spliterator();
        },
        Spliterator.IMMUTABLE | Spliterator.NONNULL | Spliterator.ORDERED,
        false
    ).onClose(() -> {
        safeClose(r.get());
    });
}
```

Which should be lazy in terms of fetching, but not in terms of execution. I'm not convinced the execution should be delayed lightheartedly as it may have transactional side effects, which the user may expect irrespective of the eager/lazy fetching of results, e.g.:

```java
// This should have immediate side effects right here
try (Cursor<?> c = ctx.select(STUFF.ID).from(STUFF).forUpdate(),fetchLazy()) {

    // But fetching of records can still be delayed
    c.fetchNext();
}
```

Noting that `fetchLazy()` and `fetchStream()` are equivalent in functionality, they differ only in terms of the type returned (procedural `Cursor` or functional `Stream`)

Closing this as a duplicate of #11892 and #11895.

**Closed by lukaseder** 2023-02-15 08:12 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
