### ISSUE TITLE
Provide additional DB meta information

### ISSUE THREAD

**Issue by rbuehlma** [jOOQ/jOOQ#8405] opened 2019-03-11 14:27 UTC
### Use case:

We are working on a migration tool which is able to do automated DDL migration to a predefined schema. To support multiple databases, we rely on jOOQ to generate the actual statements. jOOQ directly connects to the DB and is not used to generate any classes.

Currently it does not seem to be possible to retrieve the following objects & information:

- Constraints (like primary key, check)
- Sequences
- Custom types for columns (like enums)
- Whether a field is filled by an auto increment/sequence (e.g bigserial, serial in postgres)

### Possible solution you'd like to see:

Is it possible to add support for this meta information?

**Comment by lukaseder** [comment] 2019-03-12 17:01
Thank you very much for your request. I think some of these already exist as separate issues, but I cannot seem to find them right now.

You should definitely be able to access primary key constraints from the `org.jooq.Meta` model, but definitely not check constraints and maybe others, nor sequences or custom types.

Implementing this is a substantial bit of work, as we will no longer be able to rely on the JDBC `DatabaseMetaData` API, which we're doing now. We would need to move quite some logic from jOOQ-meta back into the jOOQ core library. Which might be a useful thing anyway.

**Comment by lukaseder** [comment] 2020-01-16 10:59
There are numerous issues that already cover this topic, including:

- #5181 Supporting a runtime model for indexes, and providing those from various parts of the jOOQ API
- #5179 Unique constraints exported from
- #4454 Identity columns

These things should already work:

- Primary keys

These things are rather difficult to get working via JDBC's `DatabaseMetaData`. There's a pending feature request that aims for moving logic from `jOOQ-meta` (currently only for the code generator) to the core library: https://github.com/jOOQ/jOOQ/issues/8655. That's a big project, and won't fit in the next release anymore. Such objects include:

- Check constraints
- Sequences
- Custom types (see also: #9509)

I'm closing this as a duplicate of various other issues as each one individually does take a bit of effort on its own.

**Closed by lukaseder** 2020-01-16 10:59 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Enhancement
