### ISSUE TITLE
Schema name not included in foreign key generation

### ISSUE THREAD

**Issue by yissachar** [jOOQ/jOOQ#8490] opened 2019-04-04 22:29 UTC
### Expected behavior and actual behavior:
A query to create a foreign key that references a specific Postgres schema should generate the correct SQL.

### Steps to reproduce the problem:

```java
Query query = alterTable(name("schemaname", "tablename")).add(
                        constraint("test_fk")
                                .foreignKey("col")
                                .references(name("schemaname", "tablename"))
        );
String querySql = query.getSQL(); // alter table "schemaname"."tablename" add constraint "test_fk" foreign key ("col") references "tablename"
```
JOOQ correctly uses the schema name in the alter table part of the query but when it comes to the FK reference only the tablename is used.

### Versions:

- jOOQ: 3.11.10
- Java: 8
- Database (include vendor): Postgres 9.6
- OS: OSX
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2019-04-05 13:49
Thank you very much for your report. As a side note, you may want to create your alter table statement from a `DSLContext` configured with PostgreSQL dialect...

Indeed, I can reproduce this for 3.11.10, but not 3.12. Will investigate what had changed between the versions

**Comment by lukaseder** [comment] 2019-04-05 13:54
This is a duplicate of #7633. Unfortunately, #7633 has never been backported to 3.11 despite having been fixed for a while. I have scheduled a backport for 3.11.11 (#8494)

Thanks again for reporting!

**Closed by lukaseder** 2019-04-05 13:54 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect

**Comment by yissachar** [comment] 2019-04-05 14:03
@lukaseder Thanks for the quick reply! The real query does configure it with Postgres dialect, but I forgot to include that with my MCVE - oops!

When is 3.11.11 scheduled for release? We've got an impending release that depends on this behaviour, if 3.11.11 is coming soon enough we can just use that, otherwise we'll have to use a workaround.

**Comment by lukaseder** [comment] 2019-04-05 14:11
> When is 3.11.11 scheduled for release? We've got an impending release that depends on this behaviour, if 3.11.11 is coming soon enough we can just use that, otherwise we'll have to use a workaround.

Probably next week.

**Comment by yissachar** [comment] 2019-04-10 14:13
Hi @lukaseder I noticed that 3.11.11 was released but I don't see a corresponding artifact on https://mvnrepository.com/artifact/org.jooq/jooq. Sorry for bothering, we've just got a bit of a timing issue.

**Comment by lukaseder** [comment] 2019-04-10 14:48
That's a third party cache probably aimed only at earning money off advertising :-)

The release is in Maven Central:
https://search.maven.org/artifact/org.jooq/jooq/3.11.11/jar

And also available from our website:
https://www.jooq.org/download

**Comment by yissachar** [comment] 2019-04-10 14:53
Hah, oops I guess I had should have been more careful. Thanks so much!

**Comment by lukaseder** [comment] 2019-04-10 15:34
No worries!
