### ISSUE TITLE
Querying array of values with user types fails in 3.16.5

### ISSUE THREAD

**Issue by sgrimm** [jOOQ/jOOQ#13337] opened 2022-03-24 18:43 UTC
### Expected behavior

```kotlin
dslContext.select(
    DSL.array(
        DSL.select(PROJECTS.ID)
            .from(PROJECTS)))
    .fetch()
```

should return a result with an array of values even if `PROJECTS.ID` uses a user type with a converter.

### Actual behavior

With 3.16.4, it works as expected.

With 3.16.5, it works as expected when querying a column with no user type (e.g., an ordinary `TEXT` or `INTEGER` value). But if a column has a user type, it throws an exception:

```
SQL [select array(select "public"."projects"."id" from "public"."projects")]; Error while reading field: array(
  select "public"."projects"."id"
  from "public"."projects"
), at JDBC index: 1
org.jooq.exception.DataAccessException: SQL [select array(select "public"."projects"."id" from "public"."projects")]; Error while reading field: array(
  select "public"."projects"."id"
  from "public"."projects"
), at JDBC index: 1
	at org.jooq_3.16.5.POSTGRES.debug(Unknown Source)
	at org.jooq_3.16.5.POSTGRES.debug(Unknown Source)
	at app//org.jooq.impl.Tools.translate(Tools.java:3102)
	at app//org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
	at app//org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1462)
	at app//org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1423)
	at app//org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:236)
	at app//org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177)
	at app//org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88)
	at app//org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:259)
	at app//org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
	at app//org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
	at app//org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2843)
[...]
Caused by: java.sql.SQLException: Error while reading field: array(
  select "public"."projects"."id"
  from "public"."projects"
), at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1584)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1523)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1482)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1447)
	... 92 more
Caused by: java.lang.ClassCastException: class [J cannot be cast to class [Ljava.lang.Object; ([J and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
	at org.jooq.tools.Convert.convertArray(Convert.java:362)
	at org.jooq.tools.Convert.convertArray(Convert.java:351)
	at org.jooq.tools.Convert.convertArray(Convert.java:321)
	at org.jooq.ArrayConverter.from(ArrayConverter.java:65)
	at org.jooq.ArrayConverter.from(ArrayConverter.java:51)
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1012)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1574)
	... 96 more
```

### Steps to reproduce the problem

```sql
CREATE TABLE projects (id BIGINT);
```

User type and converter:

```kotlin
package demo

class ProjectId(val value: Long) {
  constructor(value: String) : this(value.toLong())
  override fun equals(other: Any?): Boolean = other is ProjectId && other.value == value
  override fun hashCode(): Int = value.hashCode()
  override fun toString(): String = value.toString()
}

class ProjectIdConverter : AbstractConverter<Long, ProjectId>(Long::class.java, ProjectId::class.java) {
  override fun from(dbValue: Long?): ProjectId? = dbValue?.let { ProjectId(it) }
  override fun to(wrappedValue: ProjectId?): Long? = wrappedValue?.value
}
```

Forced type (fed to the Gradle code generation task):

```kotlin
ForcedType()
  .withUserType("demo.ProjectId")
  .withConverter("demo.ProjectIdConverter")
  .withIncludeTypes("BIGINT")
  .withIncludeExpression("projects\\.id")
```

Simple JUnit test case:

```kotlin
  @Test
  fun arrayBug() {
    dslContext.select(DSL.array(DSL.select(PROJECTS.ID).from(PROJECTS))).fetch()
  }
```

### Versions

- jOOQ: 3.16.5
- Java: Amazon Corretto 17.0.2 
- Database (include vendor): PostgreSQL 14.1
- OS: Ubuntu 20.04; also happens on OS X 12.3
- JDBC Driver (include name if inofficial driver): PostgreSQL 42.3.3

**Comment by lukaseder** [comment] 2022-10-13 09:46
Thanks a lot for your report. I'm sorry for the delay, the notification email seems to have gone missing. I will look into this right away, now.

**Comment by lukaseder** [comment] 2022-10-13 10:08
I can't reproduce this problem easily on jOOQ 3.18.

However, this seems to hint at it:

> Caused by: java.lang.ClassCastException: class [J cannot be cast to class [Ljava.lang.Object; ([J and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')

jOOQ doesn't support primitive type arrays, only reference type arrays. This is why you cannot cast a `long[]` to `Object[]`. This seems to stem from your kotlin usage here:

```kotlin
class ProjectIdConverter : AbstractConverter<Long, ProjectId>(Long::class.java, ProjectId::class.java) {
  override fun from(dbValue: Long?): ProjectId? = dbValue?.let { ProjectId(it) }
  override fun to(wrappedValue: ProjectId?): Long? = wrappedValue?.value
}
```

`Long::class.java` corresponds to Java's `long` type, not `Long`, which you should use here. One of the things that was backported to 3.16.5 (the regression introducing version) was https://github.com/jOOQ/jOOQ/issues/13097 and https://github.com/jOOQ/jOOQ/issues/13073. Probably something changed in this area which lead to different code paths being executed when mapping arrays.

Unless I'm still overlooking something, I'd say:

- The previous code relied on an unsupported feature (primitive array type support)
- The code worked by accident
- A simple reproducer that uses `java.lang.Long` instead of `long` doesn't reproduce the problem

As such, I'm closing this issue as "works for me". If I'm overlooking something, please let me know.

**Closed by lukaseder** 2022-10-13 10:08 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
