### ISSUE TITLE
Add support for converting oracle.sql.STRUCT to org.jooq.Record

### ISSUE THREAD

**Issue by ejchet** [jOOQ/jOOQ#11215] opened 2021-01-12 18:38 UTC
PL/SQL record of tables causes and exception: oracle.sql.STRUCT cannot be cast to org.jooq.Record RootException: java.lang.ClassCastException StackTrace: org.jooq_3.13.1.ORACLE.debug(Unknown Source)

```
Caused by: java.lang.ClassCastException: oracle.sql.STRUCT cannot be cast to org.jooq.Record
        at org.jooq_3.13.1.ORACLE.debug(Unknown Source)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3304)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3199)
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:837)
        at org.jooq.impl.UDTRecordImpl.readSQL(UDTRecordImpl.java:118)
        at oracle.sql.STRUCT.toClass(STRUCT.java:544)
        at oracle.sql.STRUCT.toJdbc(STRUCT.java:495)
        at oracle.jdbc.oracore.OracleTypeUPT.unpickle81UPT(OracleTypeUPT.java:292)
        at oracle.jdbc.oracore.OracleTypeUPT.unpickle81rec(OracleTypeUPT.java:248)
        at oracle.jdbc.oracore.OracleTypeCOLLECTION.unpickle81ImgBodyElements(OracleTypeCOLLECTION.java:586)
        at oracle.jdbc.oracore.OracleTypeCOLLECTION.unpickle81ImgBody(OracleTypeCOLLECTION.java:527)
        at oracle.jdbc.oracore.OracleTypeCOLLECTION.unpickle81(OracleTypeCOLLECTION.java:339)
        at oracle.jdbc.oracore.OracleTypeCOLLECTION.unlinearizeInternal(OracleTypeCOLLECTION.java:235)
        at oracle.jdbc.oracore.OracleTypeCOLLECTION.unlinearize(OracleTypeCOLLECTION.java:214)
        at oracle.sql.ArrayDescriptor.toJavaArray(ArrayDescriptor.java:790)
        at oracle.sql.ARRAY.getArray(ARRAY.java:320)
        at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.set(DefaultBinding.java:1309)
        at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.getArrayRecord(DefaultBinding.java:1339)
        at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.get0(DefaultBinding.java:1284)
        at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.get0(DefaultBinding.java:1218)
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:837)
        at org.jooq.impl.UDTRecordImpl.readSQL(UDTRecordImpl.java:118)
        at oracle.sql.STRUCT.toClass(STRUCT.java:544)
        at oracle.sql.STRUCT.toJdbc(STRUCT.java:495)
        at oracle.sql.OracleJdbc2SQLInput.readObject(OracleJdbc2SQLInput.java:516)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3304)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3199)
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:837)
        at org.jooq.impl.UDTRecordImpl.readSQL(UDTRecordImpl.java:118)
        at oracle.sql.STRUCT.toClass(STRUCT.java:544)
        at oracle.sql.STRUCT.toJdbc(STRUCT.java:495)
        at oracle.sql.OracleJdbc2SQLInput.readObject(OracleJdbc2SQLInput.java:516)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3304)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3199)
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:837)
        at org.jooq.impl.UDTRecordImpl.readSQL(UDTRecordImpl.java:118)
        at oracle.sql.STRUCT.toClass(STRUCT.java:544)
        at oracle.sql.STRUCT.toJdbc(STRUCT.java:495)
        at oracle.jdbc.driver.NamedTypeAccessor.getObject(NamedTypeAccessor.java:169)
        at oracle.jdbc.driver.OracleCallableStatement.getObject(OracleCallableStatement.java:1947)
        at oracle.jdbc.driver.OracleCallableStatementWrapper.getObject(OracleCallableStatementWrapper.java:645)
        at org.jooq.tools.jdbc.DefaultCallableStatement.getObject(DefaultCallableStatement.java:183)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3298)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3199)
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:832)
        at org.jooq.impl.AbstractRoutine.fetchOutParameter(AbstractRoutine.java:1220)
        at org.jooq.impl.AbstractRoutine.fetchOutParameters(AbstractRoutine.java:1190)
        at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:522)
        at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:409)
        at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:339)
```

- jOOQ: 3.13.1
- Java: 8
- Database (include vendor): Oracle 12.2
- OS: Linux 
- JDBC Driver (include name if inofficial driver): Oracle ojdbc8:12.2.0.1

**Comment by lukaseder** [comment] 2021-01-13 15:32
Thank you very much for your report, @ejchet. How can we reproduce this? E.g. what's the package/procedure/function and type specification and your jOOQ code that you used to call the procedure/function?

**Comment by ejchet** [comment] 2021-01-27 21:30
Hi Lukas

     I have reproduced the issue with code I can post so you can recreate the issue, thank you for your help on this issue.

Thanks,

Eric

CREATE OR REPLACE TYPE typ_state_flags FORCE AS OBJECT
(
  update_flag varchar2(1),
  allow_insert varchar2(1),
  allow_update varchar2(1),
  allow_delete varchar2(1),
  CONSTRUCTOR FUNCTION typ_state_flags RETURN SELF AS RESULT
)
NOT FINAL

CREATE OR REPLACE TYPE BODY typ_state_flags IS

  CONSTRUCTOR FUNCTION typ_state_flags RETURN SELF AS RESULT IS
  BEGIN
    update_flag := 'N' ;
    allow_insert := 'N' ;
    allow_update := 'N' ;
    allow_delete := 'N' ;
    RETURN ;
  END;

END;

CREATE OR REPLACE TYPE typ_properties_state_flags FORCE UNDER typ_state_flags
(
    object_property typ_web_object_property_tbl,
    CONSTRUCTOR FUNCTION typ_properties_state_flags RETURN SELF AS RESULT
)
NOT FINAL

CREATE OR REPLACE TYPE BODY typ_properties_state_flags IS

    CONSTRUCTOR FUNCTION typ_properties_state_flags RETURN SELF AS RESULT IS
        v_typ_state_flags typ_state_flags := typ_state_flags();
    BEGIN
        self.update_flag := v_typ_state_flags.update_flag;
        self.allow_insert := v_typ_state_flags.allow_insert;
        self.allow_update := v_typ_state_flags.allow_update;
        self.allow_delete := v_typ_state_flags.allow_delete;
        self.object_property := typ_web_object_property_tbl();
        RETURN;
    END;

END;

CREATE OR REPLACE TYPE typ_cycle_forms_row FORCE AS OBJECT
(
    org NUMBER(4),
    cycle_name VARCHAR2(20),
    cycle_form VARCHAR2(30),
    state_flag typ_state_flags,

    CONSTRUCTOR FUNCTION typ_cycle_forms_row RETURN SELF AS RESULT,
    CONSTRUCTOR FUNCTION typ_cycle_forms_row(p_org NUMBER,
                                             p_cycle_name VARCHAR2,
                                             p_cycle_form VARCHAR2) RETURN SELF AS RESULT

)
NOT FINAL;

CREATE OR REPLACE TYPE BODY typ_cycle_forms_row AS

    CONSTRUCTOR FUNCTION typ_cycle_forms_row RETURN SELF AS RESULT IS
    BEGIN
        SELF.state_flag := typ_properties_state_flags();
        RETURN;
    END;

    CONSTRUCTOR FUNCTION typ_cycle_forms_row(p_org NUMBER,
                                             p_cycle_name VARCHAR2,
                                             p_cycle_form VARCHAR2) RETURN SELF AS RESULT IS
    BEGIN

        SELF.org := p_org;
        SELF.cycle_name := p_cycle_name;
        SELF.cycle_form := p_cycle_form;
        SELF.state_flag := typ_properties_state_flags();
        RETURN;
    END;

END;

CREATE OR REPLACE TYPE typ_cycle_forms_all_row FORCE UNDER typ_cycle_forms_row
(

    first_form_yn VARCHAR2(1),
    second_form_yn VARCHAR2(1),
    selected_yn VARCHAR2(1),
    CONSTRUCTOR FUNCTION typ_cycle_forms_all_row RETURN SELF AS RESULT,

    CONSTRUCTOR FUNCTION typ_cycle_forms_all_row(p_row typ_cycle_forms_all_row) RETURN SELF AS RESULT,

    CONSTRUCTOR FUNCTION typ_cycle_forms_all_row(p_org NUMBER,
                                                 p_cycle_name VARCHAR2,
                                                 p_cycle_form VARCHAR2,
                                                 p_first_form_yn VARCHAR2,
                                                 p_second_form_yn VARCHAR2,
                                                 p_selected_yn VARCHAR2) RETURN SELF AS RESULT
)
NOT FINAL;

CREATE OR REPLACE TYPE BODY typ_cycle_forms_all_row AS

    CONSTRUCTOR FUNCTION typ_cycle_forms_all_row RETURN SELF AS RESULT IS
    BEGIN
        SELF.state_flag := typ_properties_state_flags();
        RETURN;
    END;

    CONSTRUCTOR FUNCTION typ_cycle_forms_all_row(p_row typ_cycle_forms_all_row) RETURN SELF AS RESULT IS
    BEGIN
        SELF.org := p_row.org;
        SELF.cycle_name := p_row.cycle_name;
        SELF.cycle_form := p_row.cycle_form;
        SELF.first_form_yn := p_row.first_form_yn;
        SELF.second_form_yn := p_row.second_form_yn;
        SELF.selected_yn := p_row.selected_yn;
        SELF.state_flag := typ_properties_state_flags();
        RETURN;
    END;

    CONSTRUCTOR FUNCTION typ_cycle_forms_all_row(p_org NUMBER,
                                                 p_cycle_name VARCHAR2,
                                                 p_cycle_form VARCHAR2,
                                                 p_first_form_yn VARCHAR2,
                                                 p_second_form_yn VARCHAR2,
                                                 p_selected_yn VARCHAR2) RETURN SELF AS RESULT IS
    BEGIN

        SELF.org := p_org;
        SELF.cycle_name := p_cycle_name;
        SELF.cycle_form := p_cycle_form;
        SELF.first_form_yn := p_first_form_yn;
        SELF.second_form_yn := p_second_form_yn;
        SELF.selected_yn := p_selected_yn;
        SELF.state_flag := typ_properties_state_flags();
        RETURN;
    END;

END;

CREATE OR REPLACE TYPE typ_cycle_forms_tbl FORCE AS TABLE OF typ_cycle_forms_all_row;

CREATE OR REPLACE TYPE typ_cycle_forms_wrp FORCE AS OBJECT
(

    data typ_cycle_forms_tbl,
    state_flag typ_state_flags,

    CONSTRUCTOR FUNCTION typ_cycle_forms_wrp RETURN SELF AS RESULT,

    CONSTRUCTOR FUNCTION typ_cycle_forms_wrp(p_table typ_cycle_forms_tbl) RETURN SELF AS RESULT
)
NOT FINAL;

CREATE OR REPLACE TYPE BODY typ_cycle_forms_wrp AS

    CONSTRUCTOR FUNCTION typ_cycle_forms_wrp RETURN SELF AS RESULT IS
    BEGIN
        SELF.data := typ_cycle_forms_tbl();
        SELF.state_flag := typ_state_flags();
        RETURN;
    END;

    CONSTRUCTOR FUNCTION typ_cycle_forms_wrp(p_table typ_cycle_forms_tbl) RETURN SELF AS RESULT IS
    BEGIN
        SELF.data := p_table;
        SELF.state_flag := typ_state_flags();
        RETURN;
    END;
END;

CREATE OR REPLACE PACKAGE pkg_jooq_test AS

   FUNCTION fn_get_wrp_tbl_rec_hierarchy RETURN typ_cycle_forms_wrp;

END pkg_jooq_test;

CREATE OR REPLACE PACKAGE BODY pkg_jooq_test AS

    FUNCTION fn_get_wrp_tbl_rec_hierarchy RETURN typ_cycle_forms_wrp IS
        v_wrp typ_cycle_forms_wrp := typ_cycle_forms_wrp();
        v_row typ_cycle_forms_all_row;
        v_err_msg VARCHAR2(1000);

    BEGIN
        v_err_msg := 'Failed to execute pkg_jooq_test.fn_get_typ_cycle_forms_wrp.';

        v_wrp.data := typ_cycle_forms_tbl();
        v_wrp.data.extend;
        v_row := typ_cycle_forms_all_row();
        v_row.org := 33;
        v_row.cycle_name := 'Test Cycle';
        v_row.cycle_form := 'Form ABC: Project Order';
        v_row.first_form_yn := 'N';
        v_row.second_form_yn := 'Y';
        v_row.selected_yn := 'N';
        v_wrp.data(1) := v_row;

        return v_wrp;

    EXCEPTION
        WHEN OTHERS THEN
            raise_application_error('Error exception:',
                                    v_err_msg || CHR(10) || SQLERRM || CHR(10) || dbms_utility.format_error_backtrace);
    END fn_get_wrp_tbl_rec_hierarchy;

END pkg_jooq_test;

@Repository
public class JooqTestDao extends JooqDao {

    public TypCycleFormsWrpTO fnGetCycleFormsTbl(TypCyclesRowTO row) {
        TypCycleFormsWrpTO result = null;

        try {

            result = new TypCycleFormsWrpTOImpl().getTypCycleFormsWrpTO(PkgJooqTest.fnGetWrpTblRecHierarchy(getDSLContext().configuration()));

        } catch (java.lang.Throwable t) {
            throwDataException(t);
        }

        return result;
    }

}

fnGetCycleFormsTbl() ExceptionMessage: oracle.sql.STRUCT cannot be cast to org.jooq.Record RootException: java.lang.ClassCastException StackTrace: org.jooq_3.13.1.ORACLE.debug(Unknown Source) com.dao.jooq.publish.jooq.packages.PkgJooqTest.fnGetWrpTblRecHierarchy(PkgJooqTest.java:37) com.dao.JooqTestDao.fnGetCycleFormsTbl(JooqTestDao.java:21) com.dao.JooqTestDao$$FastClassBySpringCGLIB$$3e4e3323.invoke(<generated>)

Caused by: java.lang.ClassCastException: oracle.sql.STRUCT cannot be cast to org.jooq.Record
        at org.jooq_3.13.1.ORACLE.debug(Unknown Source)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3304)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3199)
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:837)
        at org.jooq.impl.UDTRecordImpl.readSQL(UDTRecordImpl.java:118)
        at oracle.sql.STRUCT.toClass(STRUCT.java:544)
        at oracle.sql.STRUCT.toJdbc(STRUCT.java:495)
        at oracle.jdbc.oracore.OracleTypeUPT.unpickle81UPT(OracleTypeUPT.java:292)
        at oracle.jdbc.oracore.OracleTypeUPT.unpickle81rec(OracleTypeUPT.java:248)
        at oracle.jdbc.oracore.OracleTypeCOLLECTION.unpickle81ImgBodyElements(OracleTypeCOLLECTION.java:586)
        at oracle.jdbc.oracore.OracleTypeCOLLECTION.unpickle81ImgBody(OracleTypeCOLLECTION.java:527)
        at oracle.jdbc.oracore.OracleTypeCOLLECTION.unpickle81(OracleTypeCOLLECTION.java:339)
        at oracle.jdbc.oracore.OracleTypeCOLLECTION.unlinearizeInternal(OracleTypeCOLLECTION.java:235)
        at oracle.jdbc.oracore.OracleTypeCOLLECTION.unlinearize(OracleTypeCOLLECTION.java:214)
        at oracle.sql.ArrayDescriptor.toJavaArray(ArrayDescriptor.java:790)
        at oracle.sql.ARRAY.getArray(ARRAY.java:320)
        at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.set(DefaultBinding.java:1309)
        at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.getArrayRecord(DefaultBinding.java:1339)
        at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.get0(DefaultBinding.java:1284)
        at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.get0(DefaultBinding.java:1218)
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:837)
        at org.jooq.impl.UDTRecordImpl.readSQL(UDTRecordImpl.java:118)
        at oracle.sql.STRUCT.toClass(STRUCT.java:544)
        at oracle.sql.STRUCT.toJdbc(STRUCT.java:495)
        at oracle.jdbc.driver.NamedTypeAccessor.getObject(NamedTypeAccessor.java:169)
        at oracle.jdbc.driver.OracleCallableStatement.getObject(OracleCallableStatement.java:1947)
        at oracle.jdbc.driver.OracleCallableStatementWrapper.getObject(OracleCallableStatementWrapper.java:645)
        at org.jooq.tools.jdbc.DefaultCallableStatement.getObject(DefaultCallableStatement.java:183)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3298)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3199)
        at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:832)
        at org.jooq.impl.AbstractRoutine.fetchOutParameter(AbstractRoutine.java:1220)
        at org.jooq.impl.AbstractRoutine.fetchOutParameters(AbstractRoutine.java:1190)
        at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:522)
        at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:409)
        at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:339)
        at com.dao.jooq.publish.jooq.packages.PkgJooqTest.fnGetWrpTblRecHierarchy(PkgJooqTest.java:37)
        at com.dao.JooqTestDao.fnGetCycleFormsTbl(JooqTestDao.java:21)

**Comment by lukaseder** [comment] 2021-01-29 13:55
Thanks a lot for your additional info. I'll try to reproduce this early next week

**Comment by lukaseder** [comment] 2021-02-04 14:25
Thanks a lot for your patience. I'm looking into this now. Might be related to the fact that we don't yet formally support Oracle `OBJECT` type hierarchies using `UNDER`, see also: https://github.com/jOOQ/jOOQ/issues/644. Our integration tests do not yet include such a case.

https://github.com/jOOQ/jOOQ/issues/644 is mostly about recognising hierarchies also in the code generator, where most of the difficulties stem from. Perhaps, this here is merely a bug, and we can make it work for you without reflecting the hierarchy in generated code.

I'll revert to this issue with findings, soon.

**Comment by lukaseder** [comment] 2021-02-04 14:26
A workaround would be, of course, to avoid the type hierarchy - at least in the code that is being called by jOOQ. You could create auxiliary types that flatten the hierarchy into ordinary `OBJECT` types.

I'm aware that this may be a lot of work depending on your object hierarchy investment, and thus not viable.

**Comment by lukaseder** [comment] 2021-02-04 14:59
I'm trying to reduce your example to a more minimal one. Currently, I'm still missing the spec for `typ_web_object_property_tbl`. I'm going to assume it's a simple table of object:

```
CREATE TYPE typ_web_object_property AS OBJECT (a NUMBER(1));
CREATE TYPE typ_web_object_property_tbl AS TABLE OF typ_web_object_property;
```

**Comment by lukaseder** [comment] 2021-02-04 15:01
OK, with the added types, I can reproduce this:

```
java.lang.ClassCastException: class oracle.sql.STRUCT cannot be cast to class org.jooq.Record (oracle.sql.STRUCT and org.jooq.Record are in unnamed module of loader 'app')
	at org.jooq_3.15.0-SNAPSHOT.ORACLE18C.debug(Unknown Source)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3416)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:889)
	at org.jooq.impl.UDTRecordImpl.readSQL(UDTRecordImpl.java:119)
	at oracle.sql.STRUCT.toClass(STRUCT.java:612)
	at oracle.sql.STRUCT.toJdbc(STRUCT.java:563)
	at oracle.jdbc.oracore.OracleTypeUPT.unpickle81UPT(OracleTypeUPT.java:295)
	at oracle.jdbc.oracore.OracleTypeUPT.unpickle81rec(OracleTypeUPT.java:251)
	at oracle.jdbc.oracore.OracleTypeCOLLECTION.unpickle81ImgBodyElements(OracleTypeCOLLECTION.java:620)
	at oracle.jdbc.oracore.OracleTypeCOLLECTION.unpickle81ImgBody(OracleTypeCOLLECTION.java:542)
	at oracle.jdbc.oracore.OracleTypeCOLLECTION.unpickle81(OracleTypeCOLLECTION.java:362)
	at oracle.jdbc.oracore.OracleTypeCOLLECTION.unlinearizeInternal(OracleTypeCOLLECTION.java:236)
	at oracle.jdbc.oracore.OracleTypeCOLLECTION.unlinearize(OracleTypeCOLLECTION.java:215)
	at oracle.sql.ArrayDescriptor.toJavaArray(ArrayDescriptor.java:824)
	at oracle.jdbc.driver.OracleArray.getArray(OracleArray.java:282)
	at oracle.sql.ARRAY.getArray(ARRAY.java:389)
	at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.set(DefaultBinding.java:1358)
	at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.getArrayRecord(DefaultBinding.java:1388)
	at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.get0(DefaultBinding.java:1333)
	at org.jooq.impl.DefaultBinding$DefaultArrayRecordBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:889)
	at org.jooq.impl.UDTRecordImpl.readSQL(UDTRecordImpl.java:119)
	at oracle.sql.STRUCT.toClass(STRUCT.java:612)
	at oracle.sql.STRUCT.toJdbc(STRUCT.java:563)
	at oracle.jdbc.driver.NamedTypeAccessor.getObject(NamedTypeAccessor.java:172)
	at oracle.jdbc.driver.OracleCallableStatement.getObject(OracleCallableStatement.java:1956)
	at oracle.jdbc.driver.OracleCallableStatementWrapper.getObject(OracleCallableStatementWrapper.java:647)
	at org.jooq.tools.jdbc.DefaultCallableStatement.getObject(DefaultCallableStatement.java:183)
	at org.jooq.tools.jdbc.DefaultCallableStatement.getObject(DefaultCallableStatement.java:183)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3410)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:879)
	at org.jooq.impl.AbstractRoutine.fetchOutParameter(AbstractRoutine.java:1229)
	at org.jooq.impl.AbstractRoutine.fetchOutParameters(AbstractRoutine.java:1199)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:529)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:415)
	at org.jooq.impl.Tools.attach(Tools.java:1174)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:343)
	at org.jooq.test.oracle.generatedclasses.test.packages.PkgJooqTest.fnGetWrpTblRecHierarchy(PkgJooqTest.java:36)
	at org.jooq.test.OracleTest.testOracleTypeUnderHierarchies(OracleTest.java:4447)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

**Comment by lukaseder** [comment] 2021-02-04 15:34
The tables and nesting aren't strictly necessary. This reproduces it as well:

```sql
DROP PACKAGE p_11215;
/

DROP TYPE u_11215_a;
/

DROP TYPE u_11215_b;
/

CREATE TYPE u_11215_a AS OBJECT (
  a VARCHAR2(1),
  CONSTRUCTOR FUNCTION u_11215_a RETURN SELF AS RESULT
)
NOT FINAL
/

CREATE TYPE BODY u_11215_a AS
  CONSTRUCTOR FUNCTION u_11215_a RETURN SELF AS RESULT IS
  BEGIN
    a := 'a';
    RETURN;
  END;
END;
/

CREATE TYPE u_11215_b UNDER u_11215_a (
  b VARCHAR2(1),
  CONSTRUCTOR FUNCTION u_11215_b RETURN SELF AS RESULT
)
NOT FINAL
/

CREATE TYPE BODY u_11215_b AS
  CONSTRUCTOR FUNCTION u_11215_b RETURN SELF AS RESULT IS
  BEGIN
    b := 'b';
    RETURN;
  END;
END;
/

CREATE OR REPLACE PACKAGE p_11215 AS
  FUNCTION func RETURN u_11215_a;
END p_11215;
/

CREATE OR REPLACE PACKAGE BODY p_11215 AS
  FUNCTION func RETURN u_11215_a IS
    a u_11215_a;
  BEGIN
    a := u_11215_b();
    RETURN a;
  END func;
END p_11215;
/
```

In this case, with a slightly different stack trace because no table types are involved:

```
java.lang.ClassCastException: class oracle.sql.STRUCT cannot be cast to class org.jooq.Record (oracle.sql.STRUCT and org.jooq.Record are in unnamed module of loader 'app')
	at org.jooq_3.15.0-SNAPSHOT.ORACLE18C.debug(Unknown Source)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3410)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:879)
	at org.jooq.impl.AbstractRoutine.fetchOutParameter(AbstractRoutine.java:1229)
	at org.jooq.impl.AbstractRoutine.fetchOutParameters(AbstractRoutine.java:1199)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:529)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:415)
	at org.jooq.impl.Tools.attach(Tools.java:1174)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:343)
	at org.jooq.test.oracle.generatedclasses.test.packages.P_11215.func(P_11215.java:36)
	at org.jooq.test.OracleTest.testOracleTypeUnderHierarchies(OracleTest.java:4449)
```

The point is that the function declares returning the super type, but in fact, returns the subtype.

Our type map, which we're providing the JDBC driver with, only contains the super type:

![image](https://user-images.githubusercontent.com/734593/106915550-695b7c00-6706-11eb-80df-cc67f4c56f18.png)

I'm hoping we can simply add the sub types as well to these type maps. Historically, the type map is calculated on the fly based on the requested data types. But we could just generate the entire type map for the entire generated catalog instead to stay on the safe side. I'll investigate this.

**Comment by lukaseder** [comment] 2021-02-04 15:42
Too soon. Even with the subtypes in the type map, we can't return them because they're not assignment compatible with the declared type in generated code, as long as we don't also generate the type hierarchy, such that `U_11215BRecord <: U_11215ARecord`, or in your case, `TypPropertiesStateFlagsRecord <: TypStateFlagsRecord`.

This means that prior to supporting type hierarchies (https://github.com/jOOQ/jOOQ/issues/644) the only workarounds I can see is to avoid them:

- Either completely by defining auxiliary data structures
- By declaring the actual type, not a super type

I'll check out what is involved with implementing #644. I remember that there were some caveats with respect to generated interfaces, in case `<interfaces/>` is turned on in code generation (see https://github.com/jOOQ/jOOQ/issues/10509)

**Comment by lukaseder** [comment] 2021-02-04 16:32
A quick prototype shows that this can be made to work if:

- The `UDTRecord<R extends UDTRecord<R>>` type is changed to `UDTRecord<R extends UDTRecord<? super R>>` (and related types, too)
- The generated `U_11215BRecord` extends `U_11215ARecord` instead of `UDTRecordImpl<U_11215BRecord>`
- The type map includes all the types from the catalog (will be implemented as a separate issue: https://github.com/jOOQ/jOOQ/issues/11371)

This all seems like quite the change, especially the backwards incompatible change about the recursive generic type declaration of `<R>`, meaning we can't backport this change. But it looks like a good candidate for the next minor release 3.15.

I'm closing this as a duplicate of #644

**Closed by lukaseder** 2021-02-04 16:32 UTC
Labels: C: DB: Oracle, C: Functionality, E: Enterprise Edition, E: Professional Edition, P: Medium, T: Defect

**Comment by ejchet** [comment] 2021-02-04 22:44
Lukas I appreciate the analysis and target release 3.15 fix, has a release date been set?  A ballpark will help with our release planning.

Thanks,

Eric

**Comment by lukaseder** [comment] 2021-02-05 20:49
Thanks Eric. We're aiming for Q2 2021, but as always, no promises. The feature itself should be implemented in February 2021 still, and then available through our snapshot releases: https://www.jooq.org/download/versions

**Comment by ejchet** [comment] 2021-02-11 16:09
Thanks Lukas.

**Comment by lukaseder** [comment] 2024-08-27 12:58
Looking into https://github.com/jOOQ/jOOQ/issues/644 again for 3.20.

The solution I aimed for at the time was impractical and would have impacted end user code in non-desirable ways:

- https://github.com/jOOQ/jOOQ/issues/11215#issuecomment-773438891

A much better solution is this one:

- https://github.com/jOOQ/jOOQ/issues/644#issuecomment-2312464468
