### ISSUE TITLE
SAP HANA TINYINT is represented as Byte with wrong value

### ISSUE THREAD

**Issue by o-shevchenko** [jOOQ/jOOQ#16976] opened 2024-07-12 13:49 UTC
### Expected behavior

We should take into account the signed unsigned value and represent TINYINT 200 correctly.

### Actual behavior

TINYINT 200 is represented as Byte -56.
The problem is that: The TINYINT data type stores an 8-bit unsigned integer in SAP HANA.
In Java we have a minimum value of -128 and a maximum value of 127 (inclusive).
<img width="411" alt="image" src="https://github.com/user-attachments/assets/85fa1cf7-357f-45b7-9c4a-3e3165d03c13">
<img width="164" alt="image" src="https://github.com/user-attachments/assets/3b0acfb2-c3cd-4a61-a25d-3209ef18693f">
<img width="482" alt="image" src="https://github.com/user-attachments/assets/458c0dde-ac3a-45d4-b864-d13c3c0ee651">

https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/4ee2f261e9c44003807d08ccc2e249ac.html

### Steps to reproduce the problem

Read data from SAP HANA with TINYINT field:

context.resultQuery("SELECT * FROM table")

### jOOQ Version

3.19.10

### Database product and version

SAP HANA

### Java Version

17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.sap.cloud.db.jdbc:ngdbc:2.21.11

**Comment by lukaseder** [comment] 2024-07-12 14:26
Thanks for your report.

This is a duplicate of https://github.com/jOOQ/jOOQ/issues/10297

**Closed by lukaseder** 2024-07-12 14:26 UTC
Labels: T: Defect, C: Functionality, P: Medium, C: DB: Hana, E: Enterprise Edition

**Comment by o-shevchenko** [comment] 2024-07-12 14:29
Thanks @lukaseder !
Any advice on what is the best way of transforming types manually so far?

**Comment by lukaseder** [comment] 2024-07-12 14:31
If you're using the code generator, you can apply data type rewriting:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-rewrite/

Alternatively, for plain SQL queries, you can call `ResultQuery.coerce()` to provide explicit data types from `SQLDataType`.

**Comment by o-shevchenko** [comment] 2024-07-12 14:33
We don't use code generation. We write a data reader for SAP HANA to read any tables, so we don't know the exact types.
Is it possible to add any converting interactions?

**Comment by o-shevchenko** [comment] 2024-07-12 14:37
That's what we do:
```Kotlin
 return Flux.from(context.resultQuery("SELECT * FROM $tableName"))
            .map { it.toDataRecord() }
            ...
            fun Record.toDataRecord(): DataRecord {
    val fields = this.fields().map {
        DataField(
            key = it.name,
            value = this.get(it),
        )
    }
    return DataRecord(fields)
}
```
Is it possible to set rules to represent TINYINT as UByte?

**Comment by lukaseder** [comment] 2024-07-12 14:53
> We don't use code generation. We write a data reader for SAP HANA to read any tables, so we don't know the exact types.
> Is it possible to add any converting interactions?

See my previous comment:

*Alternatively, for plain SQL queries, you can call `ResultQuery.coerce()` to provide explicit data types from SQLDataType.*

**Comment by o-shevchenko** [comment] 2024-07-12 14:55
Thanks @lukaseder !
I will look into `coerce` workaround

**Comment by o-shevchenko** [comment] 2024-07-12 15:04
I just quickly checked https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/datatype-coercions/
We don't know the fields names before reading, and we don't know their types. So, I am just wondering if we can set rules to convert the underlined TINYINT type as UByte in Java without knowing the field names.

**Comment by KarlHakanNordgren** [comment] 2024-08-07 11:21
@lukaseder : The only way I can seem to make the above work is by first fetching a single row:

**Comment by KarlHakanNordgren** [comment] 2024-08-12 09:25
> > @lukaseder : The only way I can seem to make the above work is by first fetching the fields for a single row:
> 
> By "the above," you probably meant this suggestion? [#16976 (comment)](https://github.com/jOOQ/jOOQ/issues/16976#issuecomment-2225765322)
> 
> If you don't know the fields in advance, then I don't think you have any option, other than...:
> 
> > Is there a way to do the above without fetching a row first? (Also, patching jOOQ and proxying your JDBC driver are not options for us.)
> 
> Why aren't these options for you?

@lukaseder : Hi. Thanks for the response. I think it is unlikely that we will want to take on the maintenance burden for patching jOOQ or proxying the JDBC driver, but let's see. 

Could I ask for some pointers as to what "proxying your JDBC driver" means? I've had a look at `ResultSetMetaData` and `MetaDataFieldProvider` so I understand how they interact.

**Comment by lukaseder** [comment] 2024-08-12 10:28
> @lukaseder : Hi. Thanks for the response. I think it is unlikely that we will want to take on the maintenance burden for patching jOOQ or proxying the JDBC driver, but let's see.
> 
> Could I ask for some pointers as to what "proxying your JDBC driver" means? I've had a look at `ResultSetMetaData` and `MetaDataFieldProvider` so I understand how they interact.

I think you're overestimating the effort here.

Just wrap your existing `Connection` with a proxying implementation (e.g. extending that of jOOQ, the `DefaultConnection`), overriding the `createStatement()` and `prepareStatement()` methods to return a proxying implementation again (e.g. extending that of jOOQ, the `DefaultStatement` or `DefaultPreparedStatement`), repeat with `ResultSet`, and in that type, return your own proxy for the `ResultSetMetaData`. It's 10 minutes of work.

**Comment by lukaseder** [comment] 2024-08-13 13:06
For the record, I'll add support for `SMALLDECIMAL` to jOOQ 3.20 now:

- https://github.com/jOOQ/jOOQ/issues/16975

So, at least that will be fixed.

**Comment by KarlHakanNordgren** [comment] 2024-08-20 14:44
@lukaseder : Thanks! In that case we will do nothing and let dependabot bring us 3.20.0 and then verify that are problems are solved.
