### ISSUE TITLE
Scala enum -> case object generation does not namespace, causing collisions

### ISSUE THREAD

**Issue by tekacs** [jOOQ/jOOQ#5945] opened 2017-03-07 01:41 UTC
The ScalaGenerator [as it stands today][1] generates a single `case object` for each value in an enum.

Whilst it derives the `sealed trait` corresponding to its enum type, it isn't namespaced under that trait, leading to collisions in the `enums` namespace between enum values with the same name.

This currently makes the code generator output unworkable without overriding the generator to prevent this. For example:

```scala
// MaritalStatusType.scala
package model.jooq.enums

sealed trait MaritalStatusType extends EnumType { ... snip ... }
case object married extends MaritalStatusType { ... snip ... }
case object single extends MaritalStatusType { ... snip ... } // clash!

// EspressoShotType.scala
package model.jooq.enums

sealed trait EspressoShotType extends EnumType { ... snip ... }
case object single extends MaritalStatusType { ... snip ... } // clash!
case object doule extends MaritalStatusType { ... snip ... }
```

[1]: https://github.com/jOOQ/jOOQ/blob/863c1ee2c59169cd6c171bd0c965e8cf9da5b38f/jOOQ-codegen/src/main/java/org/jooq/util/JavaGenerator.java#L2122

**Comment by lukaseder** [comment] 2017-03-07 13:07
Thank you very much for reporting. Indeed, that's an unfortunate limitation. The best workaround here is to use a generator strategy to override packages (e.g. one package per enum)

**Comment by tekacs** [comment] 2017-03-07 23:37
That's definitely a workable workaround - were this to gain an 'official' fix in jOOQ, might I suggest nesting the case objects the companion of the enum trait (possibly behind a flag, if you need to do backwards compatibility)? That is:

```scala
package model.jooq.enums

sealed trait MaritalStatusType extends EnumType { ... snip ... }
object MaritalStatusType {
  case object married extends MaritalStatusType { ... snip ... }
  case object single extends MaritalStatusType { ... snip ... }
}
```

We'll go with the strategy override for now!

**Comment by lukaseder** [comment] 2017-03-08 07:42
Thanks for the suggestion. That looks reasonable

**Comment by lukaseder** [comment] 2020-11-20 09:39
The `ScalaGenerator`'s enum emulation has been a source of numerous headaches in the past. We're going to address this more thoroughly now via https://github.com/jOOQ/jOOQ/issues/10998.

It will be more pragmatic to:

- Default to generating a Java enum in Scala 2.x
- Add support for Scala's native enums starting with Scala 3.x (dotty)

Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/10998

**Closed by lukaseder** 2020-11-20 09:39 UTC
Labels: C: Code Generation, C: Integration: Scala, E: All Editions, P: Medium, T: Defect
