### ISSUE TITLE
DDLDatabase does not support CREATE DOMAIN

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#10221] opened 2020-05-23 19:18 UTC
Parsing fails on `CREATE DOMAIN user_id AS UUID;` with:

```
Caused by: org.jooq.impl.ParserException: GENERATOR, GLOBAL TEMPORARY TABLE, INDEX, OR ALTER VIEW, OR REPLACE VIEW, SCHEMA, SEQUENCE, TABLE, TEMPORARY TABLE, TYPE, UNIQUE INDEX, or VIEW expected: [1:8] CREATE [*]DOMAIN user_id AS UUID;
CREATE TABLE user
(
    id   user_id DEFAULT random_u...
        at org.jooq.impl.ParserContext.expected(ParserImpl.java:11102)
        at org.jooq.impl.ParserImpl.parseCreate(ParserImpl.java:2241)
        at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:859)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:556)
        at org.jooq.impl.ParserImpl.parse(ParserImpl.java:543)
        at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:170)
        at org.jooq.meta.extensions.ddl.DDLDatabase.access$000(DDLDatabase.java:86)
        at org.jooq.meta.extensions.ddl.DDLDatabase$2.load(DDLDatabase.java:155)
        at org.jooq.FilePattern.load0(FilePattern.java:297)
        at org.jooq.FilePattern.load(FilePattern.java:277)
        at org.jooq.FilePattern.load(FilePattern.java:223)
        at org.jooq.meta.extensions.ddl.DDLDatabase.export(DDLDatabase.java:152)
        at org.jooq.meta.extensions.AbstractInterpretingDatabase.connection(AbstractInterpreting
Database.java:100)
        ... 8 common frames omitted
```

### Versions:

- jOOQ: 3.13.2
- Java: 14
- Database (include vendor): H2 1.4.200

**Comment by lukaseder** [comment] 2020-05-25 07:19
Thanks for your report. We don't support `DOMAIN`s yet: #681. Closing this as a duplicate of #681

**Closed by lukaseder** 2020-05-25 07:19 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect
