### ISSUE TITLE
[3.7.3] NPE on DB field named 'class' when reflected through POJO

### ISSUE THREAD

**Issue by pchayka** [jOOQ/jOOQ#5185] opened 2016-04-03 08:20 UTC
I have a database which contains table PLAYERS_APPEARANCE where there's field named "Class".
I'm querying with jooq like so

```
PlayersAppearance pp = getCtx().select(PLAYERS_APPEARANCE.RACE,PLAYERS_APPEARANCE.CLASS,PLAYERS_APPEARANCE.GENDER).
    from(PLAYERS_APPEARANCE).where(PLAYERS_APPEARANCE.ID.equal(id)).fetchInto(PlayersAppearance.class).get(0);
```

PlayersAppearance.class is POJO generated by jooq. For Class field it generated **class_** field in java and I access it with **getClass_()** method. class_ is named to avoid conflict with native method getClass(), but it also breaks the database field value somehow

**Problem**

PlayersApperance pa = pa.getClass_() returns NPE

Debugger: [http://i.stack.imgur.com/Upt9f.png](url)

**However:**

` .fetchInto(PLAYERS_APPEARANCE)` instead of POJO class reads fine.

**Comment by lukaseder** [comment] 2016-04-03 13:20
Thank you very much for your thorough reporting of this issue. I'm closing this as a duplicate of #4867, as already commented in other channels.

For the record, this issue was also reported here:

- https://groups.google.com/forum/#!msg/jooq-user/23S69IRSaa0/BpcXApQKAwAJ
- http://stackoverflow.com/q/36374962/521799

**Closed by lukaseder** 2016-04-03 13:20 UTC
Labels: C: Functionality, P: Medium, R: Duplicate, T: Defect
