### ISSUE TITLE
Feature suggestion: enhanced type safety for primary and foreign keys

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#6553] opened 2017-09-01 11:36 UTC
### Expected behavior and actual behavior:

Currently if I have a table `abc` and a table `xyz` and both have a primary key say of type UUID, nothing prevents me from putting an id from `xyz` into a query for `abc`. The same applies to record creation involving foreign keys. Where is type-safety when we need it?!

What we have done to remedy this is the following:
- each table gets its own POJO key type (say `AbcId` and `XyzId` assuming the primary key columns are both called `id`)
- create a converter for each (say UUID<->AbcId and UUID<->XyzId)
- add a `forcedType` for both the primary key and the foreign keys referencing it

Voila! Beautiful type safety for primary keys!

This could be an optional flag in the generator for example. We have found this to be quite useful at catching refactoring errors early.

**Comment by lukaseder** [comment] 2017-09-01 11:48
Thanks for your suggestion. Yes, this is already on the roadmap through a variety of other features, including:

- https://github.com/jOOQ/jOOQ/issues/2530 (see discussion in this ticket)
- https://github.com/jOOQ/jOOQ/issues/6518

This appears all very simple when using single-column unique / foreign keys, but when we use composite keys, which may in fact participate in several keys simultaneously, then things get a bit more tricky. An example:

```sql
CREATE TABLE a (
  id IDENTITY,
  tenant BIGINT,
  business_id BIGINT,
  CONSTRAINT a_pk PRIMARY KEY (id), -- Surrogate key
  CONSTRAINT business_key UNIQUE (tenant, business_id), -- Business key
  CONSTRAINT business_id_fk FOREIGN KEY (business_id) REFERENCING tenant (id)
);
```

Probably not impossible but tricky.

Anyway, I'm closing this as a duplicate of #2530, which is certainly a high priority for jOOQ 3.11

**Closed by lukaseder** 2017-09-01 11:48 UTC
Labels: C: Code Generation, C: Functionality, P: Medium, R: Duplicate, T: Enhancement
