### ISSUE TITLE
IllegalAccessException when creating DSL.table(R...) from list of Kotlin generated TableRecords

### ISSUE THREAD

**Issue by assylias** [jOOQ/jOOQ#17202] opened 2024-09-06 10:25 UTC
### Expected behavior

Given a list of Records, I should be able to create a table:

    val c = CurrencyRecord(null, "EUR", "EUR", "EUR", LocalDate.now())
    val t = table(listOf(c))

see: https://stackoverflow.com/a/58502250/829571

### Actual behavior

The code:

    val c = CurrencyRecord(null, "EUR", "EUR", "EUR", LocalDate.now())
    val t = table(listOf(c))

throws an exception:

    java.lang.IllegalAccessException: class org.jooq.impl.Tools cannot access a member of class com.ramai.jooq.ram_dw.dim.tables.records.CurrencyRecord with modifiers "private"
	    at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
	    at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:714)
	    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:495)
	    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	    at org.jooq.impl.Tools.getRecordQualifier(Tools.java:3910)

This seems to be due to the private constructor in the CurrencyRecord class:

    open class CurrencyRecord private constructor() : UpdatableRecordImpl<CurrencyRecord>(Currency.CURRENCY) {
    
        open var currencyid: Int?
            set(value): Unit = set(0, value)
            get(): Int? = get(0) as Int?
    
        open var isocode: String
            set(value): Unit = set(1, value)
            get(): String = get(1) as String
    
        open var name: String
            set(value): Unit = set(2, value)
            get(): String = get(2) as String
    
        open var symbol: String
            set(value): Unit = set(3, value)
            get(): String = get(3) as String
    
        open var updatedate: LocalDate
            set(value): Unit = set(4, value)
            get(): LocalDate = get(4) as LocalDate
    
        // -------------------------------------------------------------------------
        // Primary key information
        // -------------------------------------------------------------------------
    
        override fun key(): Record1<Int?> = super.key() as Record1<Int?>
    
        /**
         * Create a detached, initialised CurrencyRecord
         */
        constructor(currencyid: Int? = null, isocode: String, name: String, symbol: String, updatedate: LocalDate): this() {
            this.currencyid = currencyid
            this.isocode = isocode
            this.name = name
            this.symbol = symbol
            this.updatedate = updatedate
            resetChangedOnNotNull()
        }
    }

### Steps to reproduce the problem

KotlinGenerator parameters:

        generate = Generate().apply {
          isFluentSetters = true
          isKotlinNotNullPojoAttributes = true
          isKotlinNotNullRecordAttributes = true
          isKotlinNotNullInterfaceAttributes = true
          isRoutines = false
        }

All records give the same error, so a standard test database should enable to reproduce the problem.

### jOOQ Version

jOOQ Pro 3.19.11

### Database product and version

SQL Server 17

### Java Version

21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.microsoft.sqlserver:mssql-jdbc:12.8.1.jre11

**Comment by assylias** [comment] 2024-09-06 10:26
As a separate note, which maybe requires a separate issue, the KotlinGenerator `isPojosAsKotlinDataClasses` seems to have no effect on the generated classes.

**Comment by lukaseder** [comment] 2024-09-06 11:50
Thanks for your report. I can reproduce this. We should make the constructor accessible using reflection.

> * the KotlinGenerator `isPojosAsKotlinDataClasses` seems to have no effect on the generated classes.

If you would like this to be addressed, can you please create a separate issue

**Comment by lukaseder** [comment] 2024-09-06 11:53
For the record, the `private constructor()` is present because of:

- https://github.com/jOOQ/jOOQ/issues/14002

**Comment by assylias** [comment] 2024-09-06 11:54
Thanks @lukaseder. My use case is below:

    val records = //some jooqRecords which I have created manually from an external source of data so can't use store on them (I think)
    val source = table(records)

    dsl().mergeInto(MY_TABLE)
      .using(source)
      .on(source.field("InstrumentId", Int::class.java)!!.eq(MY_TABLE.INSTRUMENTID))
      .whenMatchedThenUpdate()
      .set(MY_TABLE.fields().associateWith { source.field(it.name, it.type) })
      .whenNotMatchedThenInsert(*MY_TABLE.fields())
      .values(*source.fields())
      .execute()

I've been trying to find a workaround but without much success so far (the valuesRow workaround populates the table but can't be used in the mergeInto statement due to it being a Row instead of RowN).... Any ideas?

**Comment by lukaseder** [comment] 2024-09-06 11:56
You don't need type safe records (which are the cause of this problem here). Why not just use `DSL.selectFrom(DSL.values())` instead?

**Comment by lukaseder** [comment] 2024-09-06 11:58
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17204)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17205)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17206)

**Closed by lukaseder** 2024-09-06 11:58 UTC
Labels: T: Defect, C: Functionality, P: Medium, C: Integration: Kotlin, E: All Editions

**Comment by assylias** [comment] 2024-09-06 12:01
Not sure I understand, values also expects a RowN.

    val records = ...
    val rows = records.map { it.valuesRow() }.toTypedArray()
    val data = selectFrom(values(*rows)) //does not compile because it expects a RowN, not a Row

**Comment by lukaseder** [comment] 2024-09-06 12:07
E.g. `DSL.row(it.valuesRow().fields())`
