### ISSUE TITLE
DDLDatabase generator can not parse MySQL COLLATE

### ISSUE THREAD

**Issue by vojtapol** [jOOQ/jOOQ#7318] opened 2018-03-15 19:25 UTC
### Steps to reproduce the problem:
Try parsing this with the DDLDatabase generator:

```sql
DROP TABLE IF EXISTS `account`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `account` (
  `id` char(36) COLLATE utf8_unicode_ci NOT NULL COMMENT '(DC2Type:guid)',
  `active` tinyint(1) NOT NULL,
  `name` varchar(150) COLLATE utf8_unicode_ci NOT NULL,
  `created` datetime NOT NULL,
  `updated` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
```

throws:

```
org.jooq.impl.ParserException: C42000_NO_SUBCLASS: [26:17] utf8 */;
CREATE TABLE `account` (
  `id` char(36) [*]COLLATE utf8_unicode_ci NOT NULL COMMENT '(DC2Type:guid)',
  `active` tinyint(1)
	at org.jooq.impl.ParserImpl$ParserContext.unexpectedToken(ParserImpl.java:6727)
```

### Versions:

- jOOQ: 3.10.5

**Comment by lukaseder** [comment] 2018-03-16 07:51
Thanks for your report. jOOQ 3.11 will add support for collations (#2908), including the `COLLATE` clause on DDL data type specifications: #7118.

I'll keep this issue open to verify the rest of your DDL parses. For instance, the `DEFAULT CHARSET` argument doesn't parse yet in 3.11.

**Comment by lukaseder** [comment] 2018-03-22 11:18
Closing this as a duplicate of #7118. The `COLLATE` clause is parsed correctly in 3.11. The `DEFAULT CHARSET` clause is not documented (https://dev.mysql.com/doc/refman/8.0/en/create-table.html), but since it works we'll support it through #7171.

**Closed by lukaseder** 2018-03-22 11:18 UTC
Labels: C: Functionality, P: Medium, T: Defect

**Comment by lukaseder** [comment] 2018-03-22 11:24
Bug report for missing MySQL documentation: https://bugs.mysql.com/bug.php?id=90176
