### ISSUE TITLE
ERROR: syntax error at or near "merge"

### ISSUE THREAD

**Issue by mundus08** [jOOQ/jOOQ#14616] opened 2023-02-11 07:39 UTC
### Expected behavior

Command mergeInto should emulate merge for PostgreSQL 14

### Actual behavior

ERROR: syntax error at or near "merge"

### Steps to reproduce the problem

Code
```
String url = "jdbc:postgresql://db-01:5432/Finanz_V02";
Connection conn = DriverManager.getConnection(url, userName, password);
DSLContext ctx = DSL.using(conn, SQLDialect.POSTGRES);
logger_.debug ("Dialect:  {}", ctx.dialect());
logger_.debug ("Version: {}", ctx.resultQuery("select version()").fetchInto(String.class));
ctx.mergeInto(Z_TEST)
   .using(ctx.selectOne())
   .on(Z_TEST.UNIQUE.equal(0))
   .whenMatchedThenUpdate()
   .set(Z_TEST.VALUE, "v5")
   .whenNotMatchedThenInsert(Z_TEST.UNIQUE, Z_TEST.VALUE)
   .values(0, "v6")
   .execute();

```

Debug Log
```
2023-02-11 08:30:49,306 DEBUG [main] [org.mb.apps.AppDb1] Dialect:  POSTGRES
2023-02-11 08:30:49,348 INFO  [main] [org.jooq.Constants] 
                                      
...
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.17.7
                                      

2023-02-11 08:30:49,388 DEBUG [main] [org.jooq.tools.LoggerListener] Executing query          : select version()
2023-02-11 08:30:49,470 DEBUG [main] [org.jooq.tools.LoggerListener] Fetched result           : +--------------------------------------------------+
2023-02-11 08:30:49,470 DEBUG [main] [org.jooq.tools.LoggerListener]                          : |version                                           |
2023-02-11 08:30:49,470 DEBUG [main] [org.jooq.tools.LoggerListener]                          : +--------------------------------------------------+
2023-02-11 08:30:49,470 DEBUG [main] [org.jooq.tools.LoggerListener]                          : |PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) on x8...|
2023-02-11 08:30:49,470 DEBUG [main] [org.jooq.tools.LoggerListener]                          : +--------------------------------------------------+
2023-02-11 08:30:49,473 DEBUG [main] [org.jooq.tools.LoggerListener] Fetched row(s)           : 1
2023-02-11 08:30:49,474 DEBUG [main] [org.mb.apps.AppDb1] Version: [PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit]
2023-02-11 08:30:49,958 DEBUG [main] [org.jooq.tools.LoggerListener] Executing query          : merge into "data"."z_test" using (select 1 as "one") on "data"."z_test"."unique" = ? when matched then update set "value" = ? when not matched then insert ("unique", "value") values (?, ?)
2023-02-11 08:30:49,959 DEBUG [main] [org.jooq.tools.LoggerListener] -> with bind values      : merge into "data"."z_test" using (select 1 as "one") on "data"."z_test"."unique" = 0 when matched then update set "value" = 'v5' when not matched then insert ("unique", "value") values (0, 'v6')
2023-02-11 08:30:49,973 DEBUG [main] [org.jooq.tools.LoggerListener] Exception                
org.jooq.exception.DataAccessException: SQL [merge into "data"."z_test" using (select 1 as "one") on "data"."z_test"."unique" = ? when matched then update set "value" = ? when not matched then insert ("unique", "value") values (?, ?)]; ERROR: syntax error at or near "merge"

```

### jOOQ Version

3.17.7

### Database product and version

PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1)

### Java Version

V17

### OS Version

Windows 11

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.3

**Comment by lukaseder** [comment] 2023-02-13 11:04
Thanks for your report.

We'll publish jOOQ 3.18 soon, which includes PostgreSQL 15 support (which includes `MERGE` support), see https://github.com/jOOQ/jOOQ/issues/13758. jOOQ 3.17 won't support `MERGE` in PostgreSQL.

**Comment by lukaseder** [comment] 2023-02-13 11:04
Duplicate of https://github.com/jOOQ/jOOQ/issues/13758

**Closed by lukaseder** 2023-02-13 11:04 UTC
Labels: T: Defect, C: Functionality, C: DB: PostgreSQL, P: Medium, R: Duplicate, E: All Editions
