### ISSUE TITLE
Column Names as Final Static Constants

### ISSUE THREAD

**Issue by ErMejo74** [jOOQ/jOOQ#11920] opened 2021-05-27 15:21 UTC
### Use case:

We would like to use the table definition generated by jOOQ as the source of truth about the database for the rest of our application.

There are two pieces missing for this: a definition where table and column names are defined as [constant expressions.](https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.28)

As an example, we can obtain the column names by calling `getName()` on a `TableField`.

But since this is not a constant expression, we cannot use the `getName()` in an Annotation.

```
@MyAnnotation(colName=CUSTOMERDAT.DATAUT.getName())
public void myMethod(){...}
```
Does not compile, since `CUSTOMERDAT.DATAUT.getName()` is not a constant expression.
This means that we have to define a constant expression in our code, duplicating the information already available in the jOOQ table class.

### Possible solution you'd like to see:

The code generation currently generates this:
      
```
      public class Customerdat extends TableImpl<CustomerdatRecord> {
      ....
          public final TableField<CustomerdatRecord, String> DATAUT = createField(DSL.name("DATAUT"), org.jooq.impl.SQLDataType.CHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.CHAR)), this, "");

    public Customerdat() {
        this(DSL.name("CUSTOMERDAT"), null);
    }
      ....
```

Ideally the code generator should generate something like this, where the String constants are extracted as public static.

```
      public class Customerdat extends TableImpl<CustomerdatRecord> {
      ....

          public final static String COLUMN_DATAUT = "DATAUT";

          public final TableField<CustomerdatRecord, String> DATAUT = createField(DSL.name(COLUMN_DATAUT), org.jooq.impl.SQLDataType.CHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.CHAR)), this, "");

          public final static String TABLE_NAME="CUSTOMERDAT";
    public Customerdat() {
        this(DSL.name(TABLE_NAME), null);
    }
      ....
```

We could then use these constants in an annotation:

```
@MyAnnotation(colName=CUSTOMERDAT.COLUMN_DATAUT)
public void myMethod(){...}
```

**Comment by lukaseder** [comment] 2021-05-27 15:27
Thanks for your feature request. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/5210. It has been requested a few times, but it is not a high priority as cost/benefit isn't very favourable (there are many edge cases that need to be taken into consideration, leading to maintenance effort, for relatively moderate benefit).

Meanwhile, you can work around this very easily by generating your own custom code sections:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-custom-code/

**Comment by lukaseder** [comment] 2021-05-27 15:27
duplicate of #5210

**Closed by lukaseder** 2021-05-27 15:27 UTC
Labels: C: Code Generation, E: All Editions, P: Medium, R: Duplicate, T: Enhancement
