### ISSUE TITLE
jOOQ Meta executed a slow query (slower than 5 seconds) on PostgreSQL 10.3

### ISSUE THREAD

**Issue by SzabKel** [jOOQ/jOOQ#7509] opened 2018-05-25 07:18 UTC
```[INFO] ARRAYs fetched           : 0 (0 included, 0 excluded)
[INFO] Enums fetched            : 0 (0 included, 0 excluded)
[INFO] Packages fetched         : 0 (0 included, 0 excluded)
[INFO] Routines fetched         : 7 (7 included, 0 excluded)
[INFO] Tables fetched           : 31 (31 included, 0 excluded)
[INFO] No schema version is applied for catalog . Regenerating.
[INFO]                          
[INFO] Generating catalog       : DefaultCatalog.java
[INFO] ==========================================================
[INFO] Generating schemata      : Total: 2
[INFO] No schema version is applied for schema private. Regenerating.
[INFO] Generating schema        : Private.java
[INFO] ----------------------------------------------------------
[INFO] Sequences fetched        : 20 (20 included, 0 excluded)
[INFO] UDTs fetched             : 0 (0 included, 0 excluded)
[INFO] Generating sequences     
[INFO] Sequences generated      : Total: 1.485s
[INFO] Generating tables        
[WARNING] Slow SQL                 : Total: 5.041s
[WARNING] Slow SQL                 : jOOQ Meta executed a slow query (slower than 5 seconds)```

```
```sql
select 
  "information_schema"."columns"."column_name", 
  "information_schema"."columns"."ordinal_position", 
  "information_schema"."columns"."data_type", 
  "information_schema"."columns"."character_maximum_length", 
  "information_schema"."columns"."numeric_precision", 
  "information_schema"."columns"."numeric_scale", 
  "information_schema"."columns"."is_nullable", 
  "information_schema"."columns"."column_default", 
  "information_schema"."columns"."udt_schema", 
  "information_schema"."columns"."udt_name", 
  "pg_catalog"."pg_description"."description"
from "information_schema"."columns"
  join "pg_catalog"."pg_namespace"
  on "information_schema"."columns"."table_schema" = "pg_catalog"."pg_namespace"."nspname"
  join "pg_catalog"."pg_class"
  on (
    "pg_catalog"."pg_class"."relname" = "information_schema"."columns"."table_name"
    and "pg_catalog"."pg_class"."relnamespace" = "pg_catalog"."pg_namespace".oid
  )
  left outer join "pg_catalog"."pg_description"
  on (
    "pg_catalog"."pg_description"."objoid" = "pg_catalog"."pg_class".oid
    and "pg_catalog"."pg_description"."objsubid" = "information_schema"."columns"."ordinal_position"
  )
where (
  "information_schema"."columns"."table_schema" = 'private'
  and "information_schema"."columns"."table_name" = 'sys_useruisettingstype'
)
order by "information_schema"."columns"."ordinal_position"```

org.jooq.util.AbstractDatabase$1$SQLPerformanceWarning
	at org.jooq.util.AbstractDatabase$1.executeEnd(AbstractDatabase.java:294)
	at org.jooq.impl.ExecuteListeners.executeEnd(ExecuteListeners.java:170)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:263)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:317)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2597)
	at org.jooq.util.postgres.PostgresTableDefinition.getElements0(PostgresTableDefinition.java:98)
	at org.jooq.util.AbstractElementContainerDefinition.getElements(AbstractElementContainerDefinition.java:105)
	at org.jooq.util.AbstractElementContainerDefinition.getElement(AbstractElementContainerDefinition.java:149)
	at org.jooq.util.AbstractElementContainerDefinition.getElement(AbstractElementContainerDefinition.java:145)
	at org.jooq.util.AbstractTableDefinition.getColumn(AbstractTableDefinition.java:145)
	at org.jooq.util.postgres.PostgresDatabase.loadPrimaryKeys(PostgresDatabase.java:238)
	at org.jooq.util.AbstractDatabase.getRelations0(AbstractDatabase.java:1996)
	at org.jooq.util.AbstractDatabase.getRelations(AbstractDatabase.java:1724)
	at org.jooq.util.DefaultColumnDefinition.getPrimaryKey(DefaultColumnDefinition.java:91)
	at org.jooq.util.AbstractTableDefinition.getPrimaryKey(AbstractTableDefinition.java:76)
	at org.jooq.util.JavaGenerator.generateTable(JavaGenerator.java:3537)
	at org.jooq.util.JavaGenerator.generateTable(JavaGenerator.java:3531)
	at org.jooq.util.JavaGenerator.generateTables(JavaGenerator.java:3518)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:451)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:405)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:327)
	at org.jooq.util.GenerationTool.run(GenerationTool.java:647)
	at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)
	at org.jooq.util.maven.Plugin.execute(Plugin.java:192)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

### Versions:
- Spring 2.0.2.RELEASE
- jOOQ: 3.10.7
- Java: Compiling 1.8 on version "10.0.1" 2018-04-17
- Database (include vendor):  PostgreSQL-10.3-1 win64 bigsql
- OS: Windows Server 2016 for db, Win10 1703 for dev
- JDBC Driver (include name if inofficial driver): org.postgresql 42.2.2

**Comment by SzabKel** [comment] 2018-05-25 07:28
Only happens with multiple schemas.

**Comment by lukaseder** [comment] 2018-05-25 07:35
Thanks a lot for your report. That's a very curious query to take so long, it fetches the columns only for a single table, which should run quite fast. Is this reproducible every time for this table? How many rows does this query return?

**Comment by SzabKel** [comment] 2018-05-25 07:56
@lukaseder I ran the query manually through DataGrip, the query returns 0 rows and returns after <50ms every time.

I tried adding a second schema again to the generator and now it won't throw the error. It seems like it was slow only the first few times I tried.

**Comment by lukaseder** [comment] 2018-05-25 08:18
Interesting, how can it return 0 rows? There certainly must be columns in the `sys_useruisettingstype` table?

Anyway, if this is isn't really reproducible, then perhaps it was simply something else running on your system, slowing down your database in general.

If you don't mind, I'll close this as "works for me"

**Closed by lukaseder** 2018-05-25 08:18 UTC
Labels: C: Code Generation, P: Medium, T: Defect
