### ISSUE TITLE
`@SuppressWarnings("all")` does not suppress `this-escape` warning

### ISSUE THREAD

**Issue by magicrc** [jOOQ/jOOQ#15759] opened 2023-10-25 14:11 UTC
### Expected behavior

jOOQ generated code compiles without warnings with Java 21 compiler using `-Xlint:all -Werror`.

### Actual behavior

Although jOOQ generated code contains `@SuppressWarnings({ "all", "unchecked", "rawtypes" })`, it fails to compile with following warning:
```
warning: [this-escape] possible 'this' escape before subclass is fully initialized
    public final TableField<Entity, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");
```
`this-escape` lint check has been added in Java 21 (https://bugs.openjdk.org/browse/JDK-8015831) and as `all` (`@SuppressWarnings("all")` ) is not proper lint category (according to https://github.com/openjdk/jdk/blob/jdk-21%2B35/src/jdk.compiler/share/classes/com/sun/tools/javac/code/Lint.java#L164) it does not suppress this warning. Thus `@SuppressWarnings` should explicitly contain `this-escape`. Another solution (however I don't know if feasible) would be making generated class final. 

To temporarily workaround this issue, `-Xlint:-this-escape` compiler switch could be used.

Similar issue: https://github.com/jOOQ/jOOQ/issues/2298

### Steps to reproduce the problem

Code generation config using https://github.com/etiennestuder/gradle-jooq-plugin
```
jooq {
    configurations {
        main {
            generateSchemaSourceOnCompilation = false

            generationTool {
                logging = Logging.WARN
                jdbc {
                    driver = 'org.postgresql.Driver'
                    url = 'jdbc:postgresql://localhost:5432/postgres'
                    user = 'user'
                    password = 'password'
                }
                generator {
                    name = 'org.jooq.codegen.DefaultGenerator'
                    database {
                        name = 'org.jooq.meta.postgres.PostgresDatabase'
                        inputSchema = 'public'
                        properties {
                            property {
                                key   = "dialect"
                                value = "POSTGRES_17"
                            }
                        }
                    }
                    generate {
                        deprecated = false
                        records = true
                        immutablePojos = true
                        fluentSetters = true
                        generatedAnnotation = true
                        generatedAnnotationJooqVersion = false
                    }
                    target {
                        packageName = 'com.issue.api.jooq.generated'
                        directory = 'src/generated/java'
                    }
                    strategy.name = 'org.jooq.codegen.DefaultGeneratorStrategy'
                }
            }
        }
    }
}
```

### jOOQ Version

3.18.7

### Database product and version

PostgreSQL 17

### Java Version

openjdk version "21" 2023-09-19

**Comment by lukaseder** [comment] 2023-10-25 14:28
Duplicate of https://github.com/jOOQ/jOOQ/issues/15619 (it was backported to 3.18.7)

Note, for now, there's no way to configure this behaviour. It is enabled automatically if you run the code generator with JDK 21.

**Closed by lukaseder** 2023-10-25 14:28 UTC
Labels: T: Defect, C: Code Generation, P: Medium, E: All Editions

**Comment by magicrc** [comment] 2023-10-25 15:12
As I was using already using 3.18.7, in my case issue was with wrong version of `jooq-codegen` used in `gradle-jooq-plugin`, as it was defaulting it to 3.18.4.

Changing it to:
```
jooq {
    version = '3.18.7'
     ...
}
```
Solves the issue.
