### ISSUE TITLE
Add <configurationFile> element to Maven code generation plugin, for external configuration

### ISSUE THREAD

**Issue by driverpt** [jOOQ/jOOQ#5477] opened 2016-08-02 14:25 UTC
As title says.

e.g.:

```
<plugin>
    <groupId>org.jooq</groupId>
    <artifactId>jooq-codegen-maven</artifactId>
    <version>${jooq.version}</version>
    <dependencies>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>${postgresql.version}</version>
        </dependency>
    </dependencies>
    <configuration>
        <jdbc>
            <configFile>foo.properties</configFile>
            <!-- or xml -->
        </jdbc>
        <generator>
            <configFile>bar.xml</configFile>
        </generator>
    </configuration>
    <executions>
        <execution>
            <id>generate-postgresql</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

This will make it easier for CI/CD systems to dynamically generate Database Configurations, especially in Containerized environments (e.g.: Docker, rkt)

**Comment by lukaseder** [comment] 2016-08-02 14:35
Here you go :)
http://www.jooq.org/doc/latest/manual/code-generation/codegen-xml

**Comment by lukaseder** [comment] 2016-08-02 14:36
Btw, I'm just now working on supporting an XML import (https://github.com/jOOQ/jOOQ/issues/5437) / export (https://github.com/jOOQ/jOOQ/issues/5460) API in the jOOQ runtime library to support the jooq-meta.xsd format...

**Comment by lukaseder** [comment] 2016-08-02 14:37
Marking this as a duplicate of https://github.com/jOOQ/jOOQ/issues/3451

**Comment by driverpt** [comment] 2016-08-02 15:43
@lukaseder , how do i configure the `<jdbc>` part from a file?

**Comment by driverpt** [comment] 2016-08-04 14:32
Bump

**Comment by lukaseder** [comment] 2016-08-04 15:18
@driverpt It isn't needed when you have an `XMLDatabase`

**Comment by driverpt** [comment] 2016-08-04 15:31
@lukaseder , i'm trying to understand how to configure jOOQ maven plugin to use this configuration.

We use Jenkins to Bootstrap a Database for testing purposes making it necessary to dynamically generate database configuration.

Can you show me an example of a use-case for this with jOOQ-codegen maven plugin?

Thanks

**Comment by lukaseder** [comment] 2016-08-04 15:46
Hmm, but why do you need the XML format for that? And what's your current struggle?

**Comment by driverpt** [comment] 2016-08-05 10:33
Current struggle is that in our CI Process we have dynamic Docker container creation and we need to generate jdbc url on the fly and we wanted to generate a properties or xml file and have maven reference it to run jooq codegen

**Comment by ooxi** [comment] 2016-08-05 10:36
Could you use Maven properties inside the JDBC URL? Those could be injected by your CI server.

**Comment by driverpt** [comment] 2016-08-05 10:38
Problem is, they are generated with a Pre-Build Script. I could inject properties via -D but i'd prefer to generate a file.

**Comment by ooxi** [comment] 2016-08-05 10:41
As a workaround you could use the [Maven properties plugin](http://www.mojohaus.org/properties-maven-plugin/) for reading properties from a file and using those properties in the JDBC URL.

**Comment by lukaseder** [comment] 2016-08-05 10:44
Or, how about generating the entire pom.xml from a template?

**Comment by driverpt** [comment] 2016-08-05 10:47
@ooxi, i've tried that, but that doesn't work for Plugins.

**Comment by driverpt** [comment] 2016-08-05 10:49
@lukaseder , that's out of the question.

If you could please add this feature in the future, it would be nice. I like jOOQ a lot and it's an awesome work. The only downside for me is this small detail.

Look at how Liquibase is configured

`
            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>${liquibase.version}</version>
                <configuration>
                    <propertyFile>${liquibase.resource.properties}</propertyFile>
                    <promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>${postgresql.driver.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
`

**Comment by lukaseder** [comment] 2016-08-05 11:20
I'm sorry, I misunderstood you in the beginning. I thought you wanted an XML schema definition, not an external XML configuration.

I don't think an external property file will do the trick here. You'll need the entire XML structure, as the configuration is hierarchical. But that's already doable. You don't have to use the Maven plugin for code generation. You could use ant or a standalone call to the `GenerationTool`:

http://www.jooq.org/doc/latest/manual/code-generation/codegen-ant

Does that help?

**Comment by lukaseder** [comment] 2016-08-05 11:57
Sorry again for the misunderstanding, I was totally off at first. Nice idea, this is implemented for jOOQ 3.9

**Closed by lukaseder** 2016-08-05 11:57 UTC
Labels: C: Code Generation, P: Medium, R: Fixed, T: Enhancement

**Comment by driverpt** [comment] 2016-08-05 12:39
@lukaseder , no problem. Keep up with the excellent work! I'll give it a try with the Ant Plugin.

Meanwhile, is it possible to Backport to 3.8.x ? I can help if you want

**Comment by lukaseder** [comment] 2016-08-05 12:44
I'm sorry, we usually don't backport features across minor releases to minimise regression risk. In this case, given the possible workarounds, I'd prefer not to make an exception.

**Comment by driverpt** [comment] 2016-08-05 12:45
Fair enough 👍
