### ISSUE TITLE
If you had a need to implement TableField interface you cannot because of internal casting

### ISSUE THREAD

**Issue by apatrida** [jOOQ/jOOQ#14566] opened 2023-01-29 16:03 UTC
### Expected behavior

WARNING:  JAYSON TRYING TO DO THINGS THAT MESS WITH JOOQ INTERNALS AGAIN!!! WARNING!!!!

I want to have my own implementation of `TableField<R, T>` so that I can track original SQL type before conversion and also have derived tables that can reference existing field types while just adding them to my table field list.  This allows me to do things that require the original SQL type and not just the converted type.

But, you cannot implement `TableField` without a lot of other functionality.  Well, great, in Kotlin we can just delegate to another class any methods we don't implement.  But `TableFieldImpl` is package-local (even though `TableImpl` is not).  So we can only delegate to another `TableField` reference.  Ok, no problem.

Oh wait, but even if you did this there are casts in the system that cast `TableField` instances to `QueryPartInternal` which is not a base interface of `TableField` but rather only implemented by `TableFieldImpl`  ... and we aren't supposed to implement `QueryPartInternal` for any reason.

So a solution is to wrap the original field in a class, and delegate to it. But also delegate `QueryPartInternal` to the wrapped class and hope it is also a `TableFieldImpl` that implements this.  Eeeks!

```
class ConvertedTableField<R : Record, FORCETYPE, SQLTYPE>(
    delegate: TableField<R, FORCETYPE>,
    val sqlType: DataType<SQLTYPE>,
    val forceType: DataType<FORCETYPE>
) : TableField<R, FORCETYPE> by delegate, 
    QueryPartInternal by (delegate as QueryPartInternal)  // EEEEEEKS!!!!!
{
    fun coerceToSqlType(): Field<SQLTYPE> {
        return coerce(sqlType)
    }
}
```

Yes, I can have other place in the table hold "original values before conversion" for fields, but that makes access to it where I want to do coercions non-convenient.  

Regardless, just thought you should know that there is a cast of interface `A` to interface `Z` of which it has no declared relation other than internal knowledge knowing the class would normally succeed.

I know, "X,Y problem", "explain the original need", etc.  My point here is that there are public interfaces which appear to be implementable but are not due to internal "violations" of the interface heirarchy.

### Steps to reproduce the problem

implement `TableField` with a custom or delegating implementation in a table.

### jOOQ Version

3.17.6

### Database product and version

any

**Comment by lukaseder** [comment] 2023-01-30 08:25
Thanks for your report. The fact that you shouldn't do this is documented here:
https://www.jooq.org/doc/latest/manual/reference/dont-do-this/dont-do-this-jooq-implement-dsl/

Your attempts would have been prevented formally, in the future, once we'll be ready to seal the entire DSL type hierarchy (see https://github.com/jOOQ/jOOQ/issues/13640, *"Seal the type hierarchy with Java 17 sealed types."*). It isn't sealed yet, because both javac and ejc have still some hard to isolate limitations with sealed types, but we'll get there. `TableField` will be sealed, then, and the only allowed implementation will be `TableFieldImpl`

Your various attempts should have deterred you, including:

1. The API you have to implement is vast
2. The implementation is hidden
3. The implementation is cast to 2 internal types (which shows strong assumptions about the implicit rules above)

The Java language hasn't had sealed types until just now, so there was no way to formally declare that implementations of interfaces are discouraged, let alone forbidden. Bullet 1 has deterred pretty much any Java developer who attempted to do things this way, nonetheless.

There's nothing here that is surprising, or unknown. It would be nice if Java could have enforced things more formally, in the past, but it wasn't possible, and the DSL was still created with interfaces, because that's the best way to do it, see rationale here: https://blog.jooq.org/the-java-fluent-api-designer-crash-course. After all, an internal DSL isn't your every day Java enterprise application use-case, so the API design of the DSL doesn't *have to* follow most popular idioms in Java (this includes e.g. our stance on binary compatibility, which is extremely hard to achieve in a DSL: https://www.jooq.org/doc/latest/manual/getting-started/semantic-versioning/)

Already 15 years ago, I was aware of the "risk" of people thinking (*"hey this is an interface, so I can implement it"*), and to prevent people from doing that, those internal casts have been implemented all over the place as the best possible means of deterrence: `ClassCastException: QueryPartInternal` should produce: *"Oh, I might be doing something I shouldn't be doing, better get in touch and ask for a feature than continue on this seemingly discouraged path"*. I'm all ears for better ways to communicate these facts (pre Java 17), I always thought it was good enough. Engineers will be deterred and hackers are gonna hack anyway, no matter what, even with sealed types, there's probably a way. For example, tons of jOOQ users have put stuff in the `org.jooq.impl` package (prior to module paths), which allowed them to access internals. Tons of jOOQ users use reflection to open up jOOQ internals. What can I do? People will have their way.

Anyway. In the very near future, sealed types will formally prevent this particular thing, so I'm closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/13640 (sealed types).

(Still curious about your *actual* use-case, though, as you suggested via your XY problem reference 😀)

**Closed by lukaseder** 2023-01-30 08:25 UTC
Labels: T: Enhancement, C: Documentation, P: Medium, E: All Editions

**Comment by apatrida** [comment] 2023-01-30 13:31
Cleaner table creation, with Kotlin types indicating (and setting) nullability.  Also auto-enum from column type.  Also allowing coercion to SQL type for converted fields easily in cases where that is needed and don't want to hard code the type in the SQL DSL later.

<img width="1779" alt="Screenshot 2023-01-30 at 07 19 30" src="https://user-images.githubusercontent.com/182340/215488688-0f5207b1-f82e-4e5d-9b9f-064ccd1f8f43.png">

Insertable vs. Editable class along with Immutable/Mutable data classes w/no reflection for mapping and bypassing Record:

<img width="1506" alt="Screenshot 2023-01-30 at 07 30 02" src="https://user-images.githubusercontent.com/182340/215490851-0804d37c-fa31-4d98-b76b-e6405c4a0328.png">

Note that the Insert ,ethod parameters are mandatory fields, while the `override` section are those defaulted by the database but can be overridden using inline or SQL values (or a client provider for something such as `Clock`).  Mutation only allowed for non-readonly fields, and then the tracking is done by delegates.

things like that, is why I am exploring JOOQ to see what is possible (and safe) to do.

**Comment by apatrida** [comment] 2023-01-30 13:43
The Java view of JOOQ and the "one record to rule them all" or "one interface / POJO to rule them all" model causes conflicts with what the code generator does.  It creates one set which makes one group happy, or another set which makes another group of users happy.  The entity model above handles all cases with flexibility by generating the correct states of data representation that people actually use at any given mmoment.

* insertable - but let the database handle defaults, while allowing overrides of those defaults
* editable - things that should be mutable are mutable
* nullable - sometimes we just need to allow for anything to be null because, you know, joins and such
* typesafe - we just need a correct non-editable copy of the row that matches the table column nullability (because we know we aren't doing anything to violate this)

**Comment by apatrida** [comment] 2023-01-30 13:48
If you are interested, and don't just feel inclined to give a speech about internals I shouldn't touch (actually the running code touches none at the moment other than TableField as a trial), I can create a separate project and show you the code "as generated" (by hand as until the model is sound, no reason to write the code generation yet)

**Comment by lukaseder** [comment] 2023-01-30 18:39
Thanks a lot for sharing these things! I'll be looking into it in more detail later this week, with much interest! Just to be sure:

> If you are interested, and don't just feel inclined to give a speech about internals I shouldn't touch [...]

I know that this can come across "wrong." When I was first shown the xyproblem.info page, I felt attacked (I often fall for the temptation of discussing X rather than Y, myself, when I'm the user) 😅

Nevertheless, I think it's important to set expectations straight, both for you, but also for future readers of this issue on a public issue tracker. I'm *always* very interested in discussing Y, or at least, trying to find out what Y could be, and I'm positive that with your feedback, we'll find a lot of Ys, soon.

I'll be in touch. Thanks again for taking the time!

**Comment by lukaseder** [comment] 2023-02-02 13:51
Thanks again for all the feedback. This has been very insightful!

Apart from the usual mostly kotlin specific nullability takes, there are two major improvements that I've also seen in the past, namely:

- Being able to define tables (or "views" of tables) using a public API that makes more formal API guarantees than the internal `TableImpl`, which is designed to be consumed only by generated code. This is generally interesting, and not strictly dependent on (or a prerequisite to) the actual discussion here. It just enables a different style of creating derived data models from the database schema: Manually, rather than through code generation. See: https://github.com/jOOQ/jOOQ/issues/7444. I think this more addresses your various issues related to X that you've run into trying to achieve the Y, so while I don't oppose the idea of improving this area (eventually), I don't think it is crucial to your main ideas, being:
- The idea that columns are readable and/or writable, and that this has an impact on how you do CRUD: https://github.com/jOOQ/jOOQ/issues/12587 (to some extent)

In the latter case, you also distinguish between insertable ("writable once") and editable ("writable multiple times"), which is an interesting distinction that #12587 did not yet consider.

There are some things that aren't addressed in your model:

- There's a whole set of features that can be implemented only using triggers, and it would be very hard to model any of that in static generated code.
- There is the notion of deferred constraints in many SQL databases, which gets in the way of anything static (something is *"eventually not nullable"*, or *"eventually pointing to some parent"*, etc.)
- The whole SQL:2011 temporal database feature set isn't addressed, which gets in the way heavily of what is meant by "updatable". E.g. with a temporal database, an update is really just a new version of the data point, with the old version being still available. You're hinting at a related topic: Soft deletion: https://github.com/jOOQ/jOOQ/issues/2683
- The embeddable types, which is just a client side emulation of the ORDBMS feature called UDT (e.g. in Oracle, PostgreSQL). With embeddable types, composite data becomes an atomic unit, where multiple attributes become nullable/insertable/editable/readonly/whatever together.
- All of this is about working on individual records, never data sets. The whole idea of the SQL `MERGE` statement, for example, is omitted. Which may be fine for CRUD, just something to keep in mind.
 
These counter examples don't invalidate individual ideas, they just show that any CRUD abstraction will always be leaky and opinionated, and thus against someone's preferred way to operate. For example, soft deletion is a simple trick that can add value, but it is not sufficient for more complex models where temporal databases are the only viable solution.

With all of the above, the idea of modelling a `NOT NULL` constraint in the SQL type system becomes even harder to justify. Data may be `NULL` at some point, but no longer later on. It may be `NULL` in some view, but not in another. Like soft deletes, encoding nullability in jOOQ's SQL type system offers a quick win at a complexity price elsewhere. And what I think your examples show once more is that you don't strictly want this nullability to be encoded on `Field` references, but much rather on the CRUD types (e.g. generated `UpdatableRecord`), which allow you to interact with your data in the most probably correct way. It's another sign of the opinionatedness of CRUD, as opposed to the far less opinionatedness of SQL itself (left join is my favourite example, yes, but there are so many more). People have convinced me (and so did you), that much more can be done to improve things around nullability (and other type tricks) in the CRUD world, but I still think that the SQL world, via generated `Field` references, shouldn't pretend it can correctly implement nullability.

I'll reflect on this a bit more. I really like those insert/override/mutate views of an `UpdatableRecord`. This needn't be kotlin specific. Such record views can be generated for all 3 currently supported languages of the code generator.

**Comment by apatrida** [comment] 2023-02-02 14:42
Thanks for the feedback.  I am considering some of the type of things you mentioned as I go beyond crud.  But let me back up to the crud part for a moment, and multi-row crud.

The entity types are all immutable and the sealed interface contains:

* Insertable - the values I'm supposed to change for insert, with the option to override database defaults, and not just using fixed value but optionally SQL expressions.  (`birthdate = clientNow()` vs. `birthdate = sql(DSL.currentTimestamp)`)

* Typesafe - default projection: what you would expect from the full row matching the nullability of the table definition, and any annotated differences (i.e. you know about a trigger that makes a value not null in the end so you can force the type to not null, that would show up here)

* Nullable - nullable projection: anything could be null, because in SQL that can happen.  The join case, and other cases may cause you to want to reach for this type.

* Editable - a copy of the row, or partial row that I intend to modify and it tracks changes (it is kinda like a JOOQ Record but looks like a data class and tracks changes via delegates during the mutate stage ending up immutable again in the end).  Edits/mutations are literal client-side changes to the object.

* Updatable - this is not used directly but is an intermediate flavor of Editable that is having SQL expressions applied to it (`name = sql(DSL.concat(p.NAME, " (disabled)"))`) 

These types transition between them as you take action on on type.

```
Insertable -> [db insert returning] -> Editable
Insertable -> [db insert] -> Int rows inserted

Typesafe -> [mutate] -> Editable -> [db update returning] -> Editable
Typesafe -> [mutate] -> Editable -> [db update] -> Int rows updated

Typesafe -> [update w/sql expressions] -> Updatable -> [db update returning] -> Editable
Typesafe -> [update w/sql expressions] -> Updatable -> [db update] -> Int rows updated

...and so on 
```

If you start at the root of the entity:

```
PersonEntity.byId(PersonId(3)) -> Typesafe
PersonEnttiy.editableById(PersonId(3)) -> Editable

or for semi-sql group actions, update rows with SQL fragments: (generates normal SQL update)

```
PersonEntity.updateBy { p -> 
   name = sql(DSL.concat(p.NAME, ' (disabled)'))
   allowAccess = value(false)
}.where { p ->
   p.STATUS.eq(PersonStatus.disabled)
}.execute()
```

or edit rows with static values (generates normal SQL update):

```
PersonEntity.editBy {
   allowAccess = false
   name = "<deleted user>"
}.where { p ->
   p.STATUS.eq(PersonStatus.disabled)
}.execute()
```

then entities can also be used in inserts:

```
PersonsEntity.insertValues(
   insertableInstance1,
   insertableInstance2,
   ...
)

// or

PersonsEntity.insert(PERSONS_TABLE.NAME, PERSONS_TABLE.LOCATION)
.values(
   insertableInstance1,
   insertableInstance2,
   ...
)

// or alias to lambda variable the table

PersonsEntity.insert { p -> 
   columns(p.NAME, p.LOCATION)
}.values(
   insertableInstance1,
   insertableInstance2,
   ...
)
```

obviously this is just a helper around `DSLContext.insertInto(...)` which could also be extended to work. (syntax might be off, doing from memory)

```
val p = PersonsEntity._table

db.insertInto(p) // .columns(p.asterisk()) ? maybe
  .values(insertableInstance1, insertableInstance2)
  .execute()

// with subset of columns
db.insertInto(p).columns(p.NAME, p.LOCATION)
  .values(insertableInstance1, insertableInstance2)
  .execute()
``` 

You notice that the whol idea of records vs DAO goes away here.  All of the types above can have generated `fromRecor(R)` functions or `fromJdbcResultSet()` functions and just directly bind into the structure.  Nullable can bind a partial row into the structure. Records can still be used for queries that fall outside the scope of full or partial projections supported here.

About partial projections.  Any annotated data class can be a projection that I generate (Kotlin Symbol Processing) code to bind it:

```
@ProjectionOf(PersonEntity::class)
data class PersonName(val id: PersonId, val name: String)

// ... a few seconds later I write

val perp = PersonEntity.byId<PersonName>(...) // returns PersonName instance

val peeps = PersonEntity.by<PersonName> { p -> 
  p.STATUS.eq(PersonStatus.enabled).and(p.TYPE.in(1,2,3))
} // returns a list of PersonName instances 
 
```

and this can add whatever extension functions to the `PersonEntity` companion class, or to other classes and can even implement the traits such as editable, updatable, ... making it easy to create new projections with micro-code generation as you work without regenerating the visible code of the scema.

So now I've gone from CRUD to general single-table actions.  And now layer in implicit and explicit joins, to go out towards the ORM level.  Or use these entity types in other queries to hold full row or projected values in reporting queries, etc.  

Of course, not all of the SQL world is covered, but I'm aiming for something between the DOA level and the ORM level without going all the way into the bottomless pit of "ORM".

Jimmer kinda is in this direction: https://babyfish-ct.github.io/jimmer/docs/jimmer-sql/basic/usage

but I want to be able to move seamlessly between entity based CRUD, entity projections, entity based SQL, native JOOQ queries into entity types, native JOOQ with records so that where the entity model gets me part of the way there, raw JOOQ takes me the rest of the way.

I will create a separate repo, as this has continued to expand a lot since I originally posted and is improving by the minute.

It is a good experiment to see how this can go, because I have not seen the "entity state machine" implemented before and for me it removes the DOA need in a more sane way, while still making things useful for group actions (update entity where ...), and allowing them to be useful in JOOQ SQL.

**Comment by apatrida** [comment] 2023-02-02 14:54
note that the entity sealed interface looks like:

```

// individual row behavior

sealed interface KEntity<PK : Any> {
    interface Base<PK : Any> : KEntity<PK> // root level marker

    interface Insertable<PK : Any, E: Editable<PK, E>>
        : KEntity<PK>,
        InsertableTrait<E, PK>

    interface Editable<PK : Any, E: Editable<PK, E>> 
        : KEntity<PK>,
        PrimaryKeyTrait<PK>,
        StorableTrait<E, PK>,
        RefreshableTrait<E, PK>,
        TrackedEditTrait

    interface Updatable<PK : Any, E: Editable<PK, E>>
        : KEntity<PK>,
        PrimaryKeyTrait<PK>,
        StorableTrait<E, PK>

    interface Nullable<PK : Any, E: Nullable<PK, E>>
        : KEntity<PK>,
        PrimaryKeyNullableTrait<PK>

    interface Typesafe<PK : Any, E: Typesafe<PK, E>>
        : KEntity<PK>,
        PrimaryKeyTrait<PK>,
        RefreshableTrait<E, PK>
}

// companion objects for table-level behavior

sealed interface KEntityCompanion<PK : Any> {
    interface Base<PK : Any, E: KEntity.Editable<PK, E>>
        : KEntityCompanion<PK>,
        FetchByIdTrait<E, PK>. // root level companion, i.e. PersonEntity.Companion

    interface Insertable<PK : Any>
        : KEntityCompanion<PK>

    interface Editable<PK : Any, E: KEntity.Editable<PK, E>>
        : KEntityCompanion<PK>,
        FetchByIdTrait<E, PK>

    interface Updatable<PK : Any>
        : KEntityCompanion<PK>

    interface Nullable<PK : Any, E: KEntity.Nullable<PK, E>>
        : KEntityCompanion<PK>,
        FetchByIdTrait<E, PK>

    interface Typesafe<PK : Any, E: KEntity.Typesafe<PK, E>>
        : KEntityCompanion<PK>,
        FetchByIdTrait<E, PK>
}
```

The JOOQ specific versions of these are a parallel tree that subclasses these.

**Comment by apatrida** [comment] 2023-02-02 14:59
Ny the way, related to https://github.com/jOOQ/jOOQ/issues/7444 ... the code I show above for the table, is my variant of the Kotlin code generator for JOOQ and works on the current API as it is just using extension functions and an intermediary base class to make it prettier.  Also, makes it easier to hand write a table definition if desired.  Also the intent would be to be able to KSP (Kotlin symbol process) other entity models into JOOQ code more easily with simpler code. (i.e. take a JPA and render the JOOQ tables/records and entities on the fly)

**Comment by apatrida** [comment] 2023-02-02 16:24
Regardless, I'll post a feature suggestion issue linking to the repo once it has moved a bit further along so you can see what ideas from there you think are useful, vs. what will just staying in my codegen + wrapper addon.

**Comment by lukaseder** [comment] 2023-02-03 10:04
I have mixed feelings about how this is turning out. My feeling here is that something very complex and elaborate is being designed for something that most people like to keep simple.

As a side-note, all of the below assume that jOOQ is going to be changed into such a direction. A new third party library built on top of jOOQ is obviously free to do whatever it wants, including requesting low level API changes that enable things (such as tampering with the type hierarchy).

## State transitions (`Typesafe`, `Editable`, etc.)

Making the technical side of state transitions so explicit in client code *all the time* seems to be an impediment to adoption of such features, in my opinion:

- Users have to learn the concepts behind this
- Users have to learn the language implementing it (`Typesafe`, `Editable`, etc. whatever the names will be)
- Users will have to either abide by these rules, or if given the option to opt out (with a "classic" `UpdatableRecord`), they'll just opt out, out of laziness, because they can
- Finally, these type safe state transition concepts will not be simple to reconcile with "classic" bulk operations, such as an ordinary `UPDATE` or `MERGE`, or projections / aggregations, etc. where the type safety will inevitably fail. This is a risk already today, with `UpdatableRecord`, but today, that `UpdatableRecord` doesn't try to be more than a simple time saver. This is clearly more.

But this is just a criticism of the examples, not of the ideas. I still like the ideas of somehow being able to force users to provide all values that are necessary, but not more than possible, to successfully:

- `INSERT` a record (no missing values, no readonly values passed)
- `UPDATE` a record (no readonly or even insert-only values changed)

So, the main beef I have with the suggestions is that despite there being already sufficient information about what is to be done in the *operation name* (e.g. `insert()`, `update()`), users would have to again think about this operation and its possibilities via a type, such as `Typesafe`, `Editable`. I think this redundancy is unnecessary. Though, I might still be convinced, it's just a feeling I have at this point. It feels too laborious.

## An alternative language to SQL

What I don't like (for jOOQ) is to think in terms of a new language that replaces SQL. I'm not sure if the intention of methods like `PersonEntity.updateBy { .. }` or `PersonEntity.mutateBy { .. }` was to just show examples of what could be done, or if there's a real intent of replacing SQL `UPDATE` statement syntax. I think a solution that uses types directly on generated `TableField` references is better (https://github.com/jOOQ/jOOQ/issues/12587), as it should be implementable without too many implications on backwards compatibility and API design, nor would users have to learn new language. It's just an ordinary `UPDATE`, but suddenly, only actually `UPDATABLE` columns can be passed to it.

Your examples show a `}.where { ..` clause that is very kotlin specific and doesn't align with jOOQ's current DSL. From experience, people will eventually want all the other features of `UPDATE`, including `JOIN`, `ORDER BY`, `LIMIT`, etc. So, better try to look into how the existing DSL can be upgraded. As far as I can tell, this is only really about the `UPDATE .. SET` clause. I think #12587 could be sufficient.

## Kotlin specificity

Anything that will be implemented in jOOQ itself *must* work on all JVM languages, not just in kotlin. The maintenance effort of supporting a kotlin only solution is prohibitive. There's been a lot of discussion around that in this issue here:

- https://github.com/jOOQ/jOOQ/issues/6256

I've noticed that kotlin users have a fondness for kotlin-idiomatic DSLs, but this is a slippery slope we mustn't enter from a jOOQ maintenance perspective, and personally, I think this is where Exposed, Slick, et al fail. SQL is hard enough to learn. New DSLs don't fix SQL, they only complicate it. Simple kotlin-specific extensions can be OK, but fundamental features must work in Java as well, or their maintenance won't scale.

But again, that's just for things that go into jOOQ. Your own experiments outside of jOOQ will still be very valuable.

## Takeaway

Irrespective of how far you want to go on your end, or how far your experiments will influence jOOQ itself, I think https://github.com/jOOQ/jOOQ/issues/12587 (needs more polish) would be very interesting for everyone:

- The code generator knows a lot about the meta data both:
  - Provided by the actual schema
  - Provided by the code generation configuration, including synthetic objects or forced types, etc.
- It can encode this knowledge in `TableField` subtypes

**Comment by apatrida** [comment] 2023-02-03 14:36
I agree there is a lot more thought to go into this, and I am definitely building a Kotlin-specific wrapper for JOOQ that is meant for real-life cases in complicated backends, and not for the lazy.  There will be a lot less "magic" and a lot more "control"

What I am targeting is:

* Kotlin specific, I don't need to care about Java for my framework (you do, I understand, and it is a good thing that YOU do).
* can generate anything I need from my code generator, while delegating to the existing JOOQ generator for other object types.
* Be able to use JOOQ API/DSL as much as possible with some Kotlin cleanup but also worry about old methods that shouldn't be called in some cases (i.e. if using vertx database drivers, calling the wrong execute or fetch) -- not sure what to do about that last part yet. Kotlin we can scope things more carefully, JOOQ needs all methods available in many places and we can't undo that.
* Easily manually created TableImpl with a simpler syntax (easy, just extensions on a subclass of TableImpl for now) 
* Lower the need for JOOQ typed Records (PersonRecord, AnimalRecord) and reflection (instead codegen the bindings)
* Projections as propert citizens (we do this all the time in Kotlin with tons of little data classes, codegen bindings to avoid reflection)
* a replacement for DAO/JPA/ORM with an entity model that lands partway between DAO and JOOQ SQL that covers the 80% of all code related to database cases (I made up the 80% marker, but it is representative of some breaking point in commonality).  JOOQ DAO covers a smaller %, and ORMS cover 50-60% and then start to get into trouble beyond that, or have no type safety, or bad "magic", or whatever.
* allow easy and natural fallback to JOOQ DSL for the other 20% cases because you need JOOQ for this and it is crazy good at this.
* ...other things I can't remember right now until I have more coffee

So I will go places that JOOQ will not, but there are shareable ideas here between the two as you said.  And I'm trying radical ideas to see how each feels and works in realistic code before settling down to one that is more "public" consumable.  Likely some of the issues you pointed out above won't be there in the final and are rather internal states or transitional states that aren't really seen.

**Comment by apatrida** [comment] 2023-02-03 14:53
Side note about JOOQ API designs, if you ever revamp them in the future.

The world is changing around threading for example, with VirtualThreads, and which database access drivers will be important (JDBC, R2DBC, Vert.x, ...).  JDBC for example has problems with virtual threads (for now), and other drivers are just proving to be faster.  Jooq supports a mix (JDBC, R2DBC).  But, the API doesn't allow us to swap in any that we want easily, probably because of all the differences in semantics, datatypes allowed, binding, ...  

Related to this, in Kotlin we would likely separate executor from the DSL API, things like:

```
with (jdbcExecutor) {
   jooq.select(...).from(SCHEMA.MYTABLE).where(...).fetch() // extension on the executor context

   jooq.insert(...)
}
```

Where the `.fetch()` method would come from the context receiver and not from the `SelectLastStep` (or whatever the real JOOQ class providing that).  And if I only have an async driver, then `fetch()` won't ever show up, only `fetchAsync` would.  If we wanted that.  We can easily default the executor and even hide it up layers in the code so you rarely see it down in the methods (adding a more global extension), but then it is our choice of where to do that.

We can even bring tables into scope and schemas and really simplify the coding, which is why you see Kotlin people demanding things all the time.  We build code like:

```
with (Schema<MySchema>(jooq, MYSCHEMA)) {
    
    // now don't need schema nor JOOQ DSLContext nor DSL references below

    using (MYTABLE as "m", MYOTHER as "o") { m, o ->

       // now have short table references

       val mythings: List<MyTable> = select(m.ID, m.NAME)
           .from(m).join(o).on(o.MYID.eq(m.ID))
           .where(o.CREATEDAT.eq(someDate))
           .fetchTyped() // reified generics to decide data binding for target

    }
}
```

Which is why lambdas are important for Kotliners to be able to put things into narrow contexts.  With Kotlin 1.7/1.8 context receivers we can now go even more whacky:

```
with (Schema<MySchema>(jooq)) {
	with (LocalMyTableCache()) {
	     
        MyTableDao.fetchByIds(192, 333, 818) // uses and updates local scoped cache

	}

    MyTableDao.fetchByIds(192, 333, 818) // does not use a local cache
}

// because we have things like:

class MyTableDao { 
   // ...lot of stuff

   fun fetchByIds(...) {}

   context(MyTableCache)
   fun fetchByIds(...) {}
}
```

Of course that can be dangerous to do implicit changes like that, but there are explicit ways to also make that work by some option appearing and disappearing by the context available.

And we do other things like extend tables to make life easier:

```
fun MyTable.isPublic(): Condition = MYTABLE.PUBLIC.in(1,3,7) // or other complex predicate

... then later

select(...).from(m).where(m.isPublic())
```

In the end, we change the world to be readable for our Kotlin personality.  So a lot of requests will come your way from Kotlin people all having to do with this need for what we consider readable and expressive and simpler.  It may not be from another viewpoint, but it is a big part of the language.

We can't change who we are.

**Comment by lukaseder** [comment] 2023-08-09 12:38
Related discussion: 

- https://github.com/jOOQ/jOOQ/issues/15436#issuecomment-1671247639
