### ISSUE TITLE
Enum type with '-' character does not compile

### ISSUE THREAD

**Issue by rsmckinney** [jOOQ/jOOQ#8721] opened 2019-05-31 02:18 UTC
### Expected behavior and actual behavior:
Should encode SQL enum const name with a legal Java identifier character, preserving actual name elsewhere.

>By the way the same error exists with SET.  The spaces in the literals cause the same error:
>```sql
>special_features SET('Trailers','Commentaries','Deleted Scenes','Behind the Scenes') DEFAULT NULL,`
>```

### Steps to reproduce the problem
* Parse the jOOQ **sakila** sample schema (mysql)
* Boom:
Information:java:   G, PG, PG-13, R, NC-17;
Information:java:            ^
Information:java:             ^
Information:java:   public String getName() {
Information:java:          ^
Information:java:   }
Information:java:   ^
Information:java:   public String getLiteral() {
Information:java:     return name();  }
Information:java:                     ^
Information:java: 	at org.jooq.tools.reflect.Compile.compile(Compile.java:88)
Information:java: 	at org.jooq.tools.reflect.Reflect.compile(Reflect.java:77)
Information:java: 	at org.jooq.impl.ParserImpl.parseDataTypeEnum(ParserImpl.java:7394)
Information:java: 	at org.jooq.impl.ParserImpl.parseDataTypePrefix(ParserImpl.java:7104)
Information:java: 	at org.jooq.impl.ParserImpl.parseDataType(ParserImpl.java:7023)
Information:java: 	at org.jooq.impl.ParserImpl.parseCreateTable(ParserImpl.java:2296)
Information:java: 	at org.jooq.impl.ParserImpl.parseCreate(ParserImpl.java:1834)
Information:java: 	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:674)
Information:java: 	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:445)
Information:java: 	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:432)

### Versions:

- jOOQ: 3.11.11

**Comment by lukaseder** [comment] 2019-05-31 07:34
Thank you very much for your report.

This is a known issue, which we will address in the near future by re-implementing enum types in a more language agnostic way: https://github.com/jOOQ/jOOQ/issues/7025. See also conflicts caused by enum literals that are Java keywords: https://github.com/jOOQ/jOOQ/issues/8555

The code generator doesn't have this problem as it works around it by disambiguating such literals, but the runtime / parser does not implement the same logic yet. Because in jOOQ, historically, an enum must be implemented by a Java `enum` type, we had resorted to this in-memory compilation solution, which works well in most cases, but not when illegal Java identifier characters, or keywords are involved.

I will keep this issue open as a reminder to integration test a new solution #7025 against literals containing illegal characters, also.

**Comment by cghislai** [comment] 2019-08-15 08:42
Im not sure on which of the linked issue to report this, but the generated empty string '' enum value does not compile on java >=9 neither:
`Error:(27,5) java: as of release 9, '_' is a keyword, and may not be used as an identifier`

In the generated code, enum constants are prefixed by an underscore.

**Comment by lukaseder** [comment] 2019-08-15 08:46
Thanks, @cghislai. That is a separate issue: https://github.com/jOOQ/jOOQ/issues/4703

**Comment by lukaseder** [comment] 2019-09-30 11:04
This issue here is fixed with #8555 in 3.13.0. A backport will be available with 3.12.2, hopefully this week.

**Closed by lukaseder** 2019-09-30 11:04 UTC
Labels: C: Parser, E: All Editions, P: Medium, T: Defect
