### ISSUE TITLE
Field.contains(String[]) does not work for text[] fields

### ISSUE THREAD

**Issue by lightoze** [jOOQ/jOOQ#4754] opened 2015-11-23 19:58 UTC
Currently it converts String[] to varchar[] and it results into `ERROR: operator does not exist: text[] @> character varying[]`. As a result, you have to write something like `DSL.array(DSL.val(str).cast(PostgresDataType.TEXT))`.

P.S. while examining the issue I found that the problem lies not in `contains()` implementation itself, but somewhere deeper in type handling code.

**Comment by lukaseder** [comment] 2015-12-01 15:19
Thanks, I can reproduce this. We'll look into a fix ASAP

**Comment by lukaseder** [comment] 2015-12-01 15:20
Another workaround is to inline the bind variable:

```java
DSL.inline(new String[] { str })
```

**Comment by deinspanjer** [comment] 2017-01-23 18:33
Another work-around would be to add the necessary operators to the DB although that is obviously not something that I'd expect jOOQ to do:
```
/* These calls will throw an error without the below operator.
SELECT '{"a","b","c"}'::TEXT[] @> '{"d"}'::VARCHAR[];
SELECT '{"a","b","c"}'::VARCHAR[] @> '{"c"}'::TEXT[];
*/

CREATE OR REPLACE FUNCTION string_casting_array_contains(x TEXT[], y VARCHAR[])
  RETURNS BOOLEAN LANGUAGE sql IMMUTABLE AS $$
  -- Swap the args and reverse the operator to prevent recursively calling this function
  SELECT y::TEXT[] <@ x;
$$;

CREATE OPERATOR @> (
PROCEDURE = string_casting_array_contains
  , LEFTARG = TEXT[]
  , RIGHTARG = VARCHAR[]
);

-- Now they work!
SELECT '{"a","b","c"}'::TEXT[] @> '{"d"}'::VARCHAR[];
SELECT '{"a","b","c"}'::VARCHAR[] @> '{"c"}'::TEXT[];

```

**Comment by lukaseder** [comment] 2022-11-29 10:13
I've been looking into this now. One option I had was to simply change the default string type from `varchar` to `text` in PostgreSQL, but it looks as though this isn't what most people do:
https://twitter.com/lukaseder/status/1597144991863754752

Interesting feedback by Vik Fearing on why that particular limitation exists:
https://twitter.com/pg_xocolatl/status/1597275950005506050

It's because array data types aren't binary compatible. So, I suspect we'll just have to add an explicit widening cast in the `contains()` implementation in case the two `String[]` types don't match. Note: We represent the PG `TEXT` type as `CLOB`, so if you're using generated code, then we can fix this. Otherwise, the types have to be provided manually.

**Comment by lukaseder** [comment] 2022-12-01 15:29
I've added a test case:

```java
assertEquals(1,
create().selectCount()
        .from(T_ARRAYS)
        .where(T_ARRAYS.TEXT_ARRAY.contains(new String[] { "a", "b" }))
        .fetchOne(0));
```

But it works:

```sql
select count(*)
from "public"."t_arrays"
where "public"."t_arrays"."text_array" @> cast('{"a","b"}' as text[])
```

Maybe, this has been fixed in the meantime. There have been a few improvements in the recent past that aimed at making sure that implicitly wrapped bind values like this will re-use the other operands explicit `DataType`, in this case the one from the code generator.

If bind values are wrapped explicitly, then I'm not sure if we can really do much. The default type is `VARCHAR`, not `TEXT`, and given the twitter poll (and the implied risk of introducing regressions), I don't want to change that. Users will have to provide the `SQLDataType.CLOB` type explicitly.

In any case, I think the main way to use this feature now works.

**Comment by lukaseder** [comment] 2022-12-01 15:29
Closing as duplicate of some other recent fix.

**Closed by lukaseder** 2022-12-01 15:29 UTC
Labels: T: Defect, C: DB: PostgreSQL, P: Medium, E: All Editions

**Comment by ndawg** [comment] 2023-08-03 16:58
Hey @lukaseder, funnily enough, I just ran into this myself again, despite filing that other bug! Instead of checking if a `List<String>` had an overlap with a `text[]` column in the database, I wanted to check if the column contained a single value, so I attempted this:

```java
val(str).in(TABLE.COLUMN);
```

I think this is an intuitive enough use case to make sure it's supported on its own. Though, the more correct syntax might be this, and it works fine:

```java
val(str).eq(any(TABLE.COLUMN));
```

As an aside, is there a reason that `COLUMN.contains(String)` is not auto-generated? It seems `contains(String[])` is.
