### ISSUE TITLE
Meta:getTables(): DataTypeException when array column has default value

### ISSUE THREAD

**Issue by dwilches** [jOOQ/jOOQ#8520] opened 2019-04-12 18:04 UTC
### Expected behavior and actual behavior:

I invoked this method trying to get the list of tables in my schema (I'm using Postgres 10.7):
```
using(configuration).meta().getTables();
```

The `getTables()` method threw this exception:
```
org.jooq.exception.DataTypeException: Cannot convert from '{}'::text[] (class java.lang.String) to class [Ljava.lang.String;

	at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:1166)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:1055)
	at org.jooq.tools.Convert.convert0(Convert.java:321)
	at org.jooq.tools.Convert.convert(Convert.java:313)
	at org.jooq.tools.Convert.convert(Convert.java:385)
	at org.jooq.impl.DefaultDataType.convert(DefaultDataType.java:768)
	at org.jooq.impl.DSL.val(DSL.java:19893)
	at org.jooq.impl.DSL.inline(DSL.java:19490)
	at org.jooq.impl.MetaImpl$MetaTable.init(MetaImpl.java:796)
	at org.jooq.impl.MetaImpl$MetaTable.<init>(MetaImpl.java:495)
	at org.jooq.impl.MetaImpl$MetaSchema.getTables(MetaImpl.java:395)
	at org.jooq.impl.MetaImpl.getTables(MetaImpl.java:218)
	at org.jooq.mcve.test.MCVETest.mcveTest(MCVETest.java:70)
```

I found the column giving trouble was `k` in this table:
```
│                    Table "my_schema.x1"
│ Column |  Type   | Collation | Nullable |   Default
│--------+---------+-----------+----------+--------------
│ i      | integer |           |          |
│ j      | text[]  |           |          |
│ k      | text[]  |           |          | '{}'::text[]
```
If I drop that column then the method doesn't throw the exception anymore.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

I have a created a MCVE here: https://github.com/dwilches/jOOQ-mcve
That MCVE also creates the problematic table.
The test fails for me when I do `mvn clean install`.

### Versions:

- jOOQ: 3.11.9
- Java: 1.8.0_191
- Database (include vendor): Postgres 10.7 (Ubuntu 10.7-0ubuntu0.18.04.1)
- OS: Ubuntu 18.04
- JDBC Driver (include name if unofficial driver): How do I find this out? Can you check it in the MCVE?

**Comment by lukaseder** [comment] 2019-04-13 15:42
Thank you very much for your report. This looks like a duplicate of #8468. Will check soon

**Comment by lukaseder** [comment] 2019-04-16 15:28
duplicate of #8468

**Closed by lukaseder** 2019-04-16 15:28 UTC
Labels: C: DB: PostgreSQL, C: Functionality, E: All Editions, P: Medium, T: Defect
