### ISSUE TITLE
SQL Translation Error

### ISSUE THREAD

**Issue by wordhardqi** [jOOQ/jOOQ#17171] opened 2024-09-02 12:45 UTC
### SQL translator incorrectly translates this query:

```sql
WITH
  FUNCTION answer()
  RETURNS BIGINT
  RETURN 42
SELECT 'The answer is ' || CAST(answer() as varchar)

**Comment by lukaseder** [comment] 2024-09-02 13:13
Thanks for your report.

Duplicate of https://github.com/jOOQ/jOOQ/issues/11460

**Closed by lukaseder** 2024-09-02 13:13 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, E: All Editions, C: Parser

**Comment by lukaseder** [comment] 2024-09-02 13:16
What SQL dialect is your example from?
