### ISSUE TITLE
Ambiguous type name Warnings for `regexp_matches` and `regexp_split_to_table`

### ISSUE THREAD

**Issue by mrclrchtr** [jOOQ/jOOQ#16994] opened 2024-07-29 18:26 UTC
### Your question

I get the following warnings:

```
Ambiguous type name      : The database object public.regexp_matches generates a class de.mrclrchtr.holz.generated.persistence.entities.tables.RegexpMatchesTable (class org.jooq.meta.postgres.PostgresTableValuedFunction) which conflicts with the previously generated class de.mrclrchtr.holz.generated.persistence.entities.tables.RegexpMatchesTable (class org.jooq.meta.postgres.PostgresTableValuedFunction). Use a custom generator strategy to disambiguate the types. More information here:
 - https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/
 - https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy/
Ambiguous type name      : The database object public.regexp_split_to_table generates a class de.mrclrchtr.holz.generated.persistence.entities.tables.RegexpSplitToTableTable (class org.jooq.meta.postgres.PostgresTableValuedFunction) which conflicts with the previously generated class de.mrclrchtr.holz.generated.persistence.entities.tables.RegexpSplitToTableTable (class org.jooq.meta.postgres.PostgresTableValuedFunction). Use a custom generator strategy to disambiguate the types. More information here:
 - https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/
 - https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy/
```

I'm using `citext` in a Postgres DB with many constraints like:

```sql
create table contact_detail_address
(
    address_id  serial primary key,
    address      varchar(255)                not null
        constraint contact_detail_address_address_check check (street <> '')
);
```

I don't know why the message appears. But I think it has something to do with this, don't you?

Unfortunately, I don't know how to proceed to solve the problem.

### jOOQ Version

Open Source 3.19.10

### Database product and version

PostgreSQL 16.3 (Debian 16.3-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

### Java Version

openjdk version "21.0.2" 2024-01-16 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.3

**Comment by lukaseder** [comment] 2024-07-31 08:16
This looks like a duplicate of #4055

As you can see with this query:

```sql
select *
from information_schema.routines
where routine_name in ('regexp_matches', 'regexp_split_to_table');
```

The table valued functions are overloaded, and this is a known limitations in jOOQ's code generator. If you don't  need the functions, just exclude them from being generated. You probably don't need any functions from the `information_schema` and `pg_catalog` at all?

**Closed by lukaseder** 2024-07-31 08:16 UTC
Labels: T: Defect, C: Code Generation, P: Medium, E: All Editions

**Comment by mrclrchtr** [comment] 2024-07-31 08:22
Thank you very much! Yes, I think I don't need any of them.
