### ISSUE TITLE
Regression: Client code no longer compiles when calling DSLContext.fetchSingle(Table, Condition...)

### ISSUE THREAD

**Issue by baev** [jOOQ/jOOQ#13722] opened 2022-06-24 10:30 UTC
### Expected behavior

```java
JobRecord record = dsl.fetchSingle(
    JOB,
    JOB.SOME.eq(someValue), 
    JOB.OTHER.eq(otherValue)
);
```

doesn't compile while using 3.17.0.

### Actual behavior

 The wrong method is called 

` <T1, T2, T3> Record3<T1, T2, T3> fetchSingle(SelectField<T1> field1, SelectField<T2> field2, SelectField<T3> field3) `

```
 error: incompatible types: no instance(s) of type variable(s) T1,T2,T3 exist so that Record3<T1,T2,T3> conforms to JobRecord
        final JobRecord jobRecord = dsl.fetchSingle(
                                                   ^
  where T1,T2,T3 are type-variables:
    T1 extends Object declared in method <T1,T2,T3>fetchSingle(SelectField<T1>,SelectField<T2>,SelectField<T3>)
    T2 extends Object declared in method <T1,T2,T3>fetchSingle(SelectField<T1>,SelectField<T2>,SelectField<T3>)
    T3 extends Object declared in method <T1,T2,T3>fetchSingle(SelectField<T1>,SelectField<T2>,SelectField<T3>)
```

### Steps to reproduce the problem

- If the problem relates to code generation, please post your code generation configuration
- If the problem relates to upgrades, please check if your RDBMS version is still supported by jOOQ: https://www.jooq.org/download/support-matrix
- A complete set of DDL statements can help re-create the setup you're having
- An MCVE can be helpful to provide a complete reproduction case: https://github.com/jOOQ/jOOQ-mcve

### Versions

- jOOQ: 3.17.0 (pro, java11 distro)
- Java: 17
- Database (include vendor): PostgreSQL 14
- OS: Mac OS M!
- JDBC Driver (include name if inofficial driver): PostgreSQL latest

**Comment by baev** [comment] 2022-06-24 11:23
btw for us that causes a 100+ compilation errors, so I can't even fully test 3.17.0 at the moment

**Comment by lukaseder** [comment] 2022-06-24 11:33
Thanks a lot for your report.

The risk of having too many overloads. The varargs overload (`fetchSingle(Table<?>, Condition...)`) hadn't been covered by integration tests, only the overloads (e.g. `fetchSingle(Table<?>, Condition)` or `fetchSingle(Table<?>, Collection<? extends Condition>)`.

Regrettably, varargs have a low priority in the applicability resolution algorithm of the JLS, so despite the method `fetchSingle(Table<?>, Condition...)` seemingly being the one you want to call (obviously, because that's what you called pre jOOQ 3.17), the fact that `Condition <: SelectField<Boolean>` and `Table<R> <: SelectField<R>` since 3.17 means that the other methods are the ones that are being resolved.

That's a very regrettable side-effect of these useful new features. I'm not sure how this could be resolved. A hack would be to overload the method even more, as:

- `fetchSingle(Table<?>, Condition, Condition)`
- `fetchSingle(Table<?>, Condition, Condition, Condition)`
- `fetchSingle(Table<?>, Condition, Condition, Condition, Condition)`

That way we can avoid the above JLS quirk for people who upgrade. I'll think of other solutions.

A workaround for you is to either pass a single `Condition` (wrap them using `DSL.and()`), or pass a `Collection<Condition>`, e.g. by using `List.of()`:

```java
JobRecord record = dsl.fetchSingle(
    JOB,
    DSL.and(
        JOB.SOME.eq(someValue), 
        JOB.OTHER.eq(otherValue)
    )
);

JobRecord record = dsl.fetchSingle(
    JOB,
    List.of(
        JOB.SOME.eq(someValue), 
        JOB.OTHER.eq(otherValue)
    )
);
```

**Comment by lukaseder** [comment] 2022-06-24 11:34
> btw for us that causes a 100+ compilation errors, so I can't even fully test 3.17.0 at the moment

Yeah, understood. This is a high priority problem. I'm hoping to be able to fix this by early next week with 3.17.1

**Comment by lukaseder** [comment] 2022-06-24 14:50
Yes, those overloads would fix the regression. I mean, overloading is what we do, isn't it...

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/734593/175560768-d55223a4-ea21-4e07-89b4-d80e4316f15c.png">

**Comment by lukaseder** [comment] 2022-06-24 15:11
After fixing this, we'll rename the `fetchSingle(SelectField, SelectField, ...)` overloads, and deprecate the existing ones: https://github.com/jOOQ/jOOQ/issues/13725.

That means even more overloads for now, but in the future, we can get back to the number of methods we had in jOOQ 3.16, and these not strictly related methods will no longer be in conflict.

**Comment by baev** [comment] 2022-06-24 15:13
What about fetch , fetchOne and fetchOptional? Are they affected as well?

**Comment by lukaseder** [comment] 2022-06-24 15:14
No, they don't have the conflicting overload that #13725 will rename

**Comment by lukaseder** [comment] 2022-06-24 15:16
As far as I can tell, this is the only case where this particular change of API (type hierarchy of `Table` and `Condition`) caused overload resolution conflicts.

**Comment by lukaseder** [comment] 2022-06-24 15:17
Fixed in jOOQ 3.18.0 and 3.17.1 (https://github.com/jOOQ/jOOQ/issues/13726). Thanks again for your reports!

**Comment by lukaseder** [comment] 2022-06-24 15:17
I'll probably release 3.17.1 on Monday

**Closed by lukaseder** 2022-06-24 15:17 UTC
Labels: T: Defect, C: Functionality, P: Urgent, E: All Editions

**Comment by lukaseder** [comment] 2022-06-24 16:12
The next 3.17.1-SNAPSHOT containing this fix should be ready in ~1h
