### ISSUE TITLE
jooq-gen fails for 3.6.3 version

### ISSUE THREAD

**Issue by advancedschennady** [jOOQ/jOOQ#4577] opened 2015-09-24 21:27 UTC
I am getting below exception when I got jOOQ upgraded to 3.6.3 version jars and tried to generate Database entities with a command like $./jooq-gen config.xml. 
Is there any update for config.xml as well?
-------------------------------------
WARNING: SQL exception            : Exception while executing meta query: Invalid object name 'INFORMATION_SCHEMA.SEQUENCES'.

Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new

select count(*)
from [INFORMATION_SCHEMA].[SEQUENCES]
Sep 24, 2015 5:11:41 PM org.jooq.tools.JooqLogger info
INFO: Sequences fetched        : 0 (0 included, 0 excluded)
Sep 24, 2015 5:11:41 PM org.jooq.tools.JooqLogger info
INFO: Tables fetched           : 24 (24 included, 0 excluded)
Sep 24, 2015 5:11:41 PM org.jooq.tools.JooqLogger info
INFO: UDTs fetched             : 0 (0 included, 0 excluded)
org.jooq.util.GeneratorException: Error generating code for schema dbo
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:268)
	at org.jooq.util.GenerationTool.run(GenerationTool.java:426)
	at org.jooq.util.GenerationTool.generate(GenerationTool.java:176)
	at org.jooq.util.GenerationTool.main(GenerationTool.java:151)
Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 9
(?s:^.*?\Rpackage\s+(.*?);?\R.*?$)
         ^
	at java.util.regex.Pattern.error(Pattern.java:1924)
	at java.util.regex.Pattern.escape(Pattern.java:2416)
	at java.util.regex.Pattern.atom(Pattern.java:2164)
	at java.util.regex.Pattern.sequence(Pattern.java:2046)
	at java.util.regex.Pattern.expr(Pattern.java:1964)
	at java.util.regex.Pattern.group0(Pattern.java:2847)
	at java.util.regex.Pattern.sequence(Pattern.java:2018)
	at java.util.regex.Pattern.expr(Pattern.java:1964)
	at java.util.regex.Pattern.compile(Pattern.java:1665)
	at java.util.regex.Pattern.<init>(Pattern.java:1337)
	at java.util.regex.Pattern.compile(Pattern.java:1022)
	at org.jooq.util.JavaWriter.beforeClose(JavaWriter.java:121)
	at org.jooq.util.GeneratorWriter.close(GeneratorWriter.java:237)
	at org.jooq.util.JavaGenerator.generateSchema(JavaGenerator.java:3131)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:298)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:265)
	... 3 more
Sep 24, 2015 5:11:41 PM org.jooq.tools.JooqLogger error
SEVERE: Cannot read config.xml. Error : Error generating code for schema dbo
org.jooq.util.GeneratorException: Error generating code for schema dbo
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:268)
	at org.jooq.util.GenerationTool.run(GenerationTool.java:426)
	at org.jooq.util.GenerationTool.generate(GenerationTool.java:176)
	at org.jooq.util.GenerationTool.main(GenerationTool.java:151)
Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 9
(?s:^.*?\Rpackage\s+(.*?);?\R.*?$)
         ^
	at java.util.regex.Pattern.error(Pattern.java:1924)
	at java.util.regex.Pattern.escape(Pattern.java:2416)
	at java.util.regex.Pattern.atom(Pattern.java:2164)
	at java.util.regex.Pattern.sequence(Pattern.java:2046)
	at java.util.regex.Pattern.expr(Pattern.java:1964)
	at java.util.regex.Pattern.group0(Pattern.java:2847)
	at java.util.regex.Pattern.sequence(Pattern.java:2018)
	at java.util.regex.Pattern.expr(Pattern.java:1964)
	at java.util.regex.Pattern.compile(Pattern.java:1665)
	at java.util.regex.Pattern.<init>(Pattern.java:1337)
	at java.util.regex.Pattern.compile(Pattern.java:1022)
	at org.jooq.util.JavaWriter.beforeClose(JavaWriter.java:121)
	at org.jooq.util.GeneratorWriter.close(GeneratorWriter.java:237)
	at org.jooq.util.JavaGenerator.generateSchema(JavaGenerator.java:3131)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:298)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:265)
	... 3 more
Sep 24, 2015 5:11:41 PM org.jooq.tools.JooqLogger error
SEVERE: Usage : GenerationTool <configuration-file>

**Comment by dbichko** [comment] 2015-09-25 00:22
same issue as #4576

**Comment by lukaseder** [comment] 2015-09-27 09:32
Thanks for reporting. Indeed, this is a duplicate of #4576. Will continue discussion there

**Closed by lukaseder** 2015-09-27 09:32 UTC
Labels: C: Code Generation, P: Urgent, R: Duplicate, T: Defect

**Comment by lukaseder** [comment] 2015-09-29 12:25
This is now fixed and published also in 3.6.4
