### ISSUE TITLE
Adding explicit join in implicit correlated subquery makes correlation go away

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#17106] opened 2024-08-19 12:24 UTC
### Expected behavior

We should be able to control the join types used for the inner query.

### Actual behavior

By adding a left join to the inner query we lose correlation with the outer query.

### Steps to reproduce the problem

As demonstrated in [this mcve](https://github.com/alf/jOOQ-mcve/blob/8c8cc66295846000b831e56e9851dd4d2be246b4/jOOQ-mcve-java-postgres/src/test/java/org/jooq/mcve/test/java/postgres/JavaTest.java) we find that jOOQs support for implicit path correlation stops working if we use a left join in the subquery.

Given [this schema](https://github.com/alf/jOOQ-mcve/blob/8c8cc66295846000b831e56e9851dd4d2be246b4/jOOQ-mcve-java-postgres/src/main/resources/db/migration/init.sql), the following queries give different results. We expect them to give the same result:

Correct:

```java
var counts = ctx
                .select(PARENT.PARENT_ID,
                        DSL
                                .selectCount()
                                .from(PARENT.child())
                                .asField()
                )
                .from(PARENT)
                .fetchMap(Record2::value1, Record2::value2);

counts.forEach((parent_id, count) -> {
    assertEquals("Expected 10 rows for each child", 10, count);
});
```
By adding the leftJoin here, the subquery sees all rows from PARENT.child():

```java
var counts = ctx
                .select(PARENT.PARENT_ID,
                        DSL
                                .selectCount()
                                .from(PARENT.child())
                                .leftJoin(PARENT.child().nanny())
                                .asField()
                )
                .from(PARENT)
                .fetchMap(Record2::value1, Record2::value2);

counts.forEach((parent_id, count) -> {
    assertEquals("Expected 10 rows for each child", 10, count);
});
```

### jOOQ Version

jOOQ 3.19.10

### Database product and version

PostgreSQL 16.3

### Java Version

OpenJDK 17

**Comment by lukaseder** [comment] 2024-08-19 13:11
Thanks for your report and for your great (as always) reproducer!

The query being rendered is this:

```sql
select
  "mcve"."parent"."parent_id",
  (
    select count(*)
    from "mcve"."child" as "alias_115630269"
      left outer join "mcve"."nanny" as "alias_120874666"
        on (
          "alias_115630269"."parent_id" = "mcve"."parent"."parent_id"
          and "alias_120874666"."child_id" = "alias_115630269"."child_id"
        )
  )
from "mcve"."parent"
```

The correlation predicate is put into the `ON` clause of the `LEFT JOIN`, when it should be an ordinary predicate like this:

```sql
select
  "mcve"."parent"."parent_id",
  (
    select count(*)
    from "mcve"."child" as "alias_115630269"
      left outer join "mcve"."nanny" as "alias_120874666"
        on "alias_120874666"."child_id" = "alias_115630269"."child_id"
    where "alias_115630269"."parent_id" = "mcve"."parent"."parent_id"
  )
from "mcve"."parent"
```

The workaround is to avoid join path correlation, i.e.:

```java
.from(CHILD)
.leftJoin(CHILD.nanny())
.where(CHILD.PARENT_ID.eq(PARENT.PARENT_ID))
```

**Comment by lukaseder** [comment] 2024-08-19 13:16
Duplicate of https://github.com/jOOQ/jOOQ/issues/15936

**Closed by lukaseder** 2024-08-19 13:16 UTC
Labels: T: Defect, C: Functionality, P: High, E: All Editions
