### ISSUE TITLE
Cannot parse column character set specification in MySQL ALTER TABLE statements

### ISSUE THREAD

**Issue by frainmeng** [jOOQ/jOOQ#8618] opened 2019-05-13 09:30 UTC
### SQL translator incorrectly translates this query:

```sql
ALTER TABLE user_info MODIFY COLUMN test varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT 'teststr' AFTER `remark`,MODIFY COLUMN `test2` float NULL DEFAULT 20 AFTER `test`
```

### Parser output:

```sql
Unexpected token or missing query delimiter: [1:54] ...ER TABLE user_info MODIFY COLUMN test varchar(50) [*]CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT 'teststr' AFTER `rem...
```

**Comment by lukaseder** [comment] 2019-05-13 10:45
Thank you very much for your report. We'll look into this soon. Other occurrences of the MySQL `CHARACTER SET` clause are already recognised by the parser, and ignored.

**Comment by lukaseder** [comment] 2019-05-14 13:08
Duplicate of #8041

**Closed by lukaseder** 2019-05-14 13:08 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect
