### ISSUE TITLE
Add support for parsing arbitrary expressions in TOP / LIMIT / FETCH

### ISSUE THREAD

**Issue by IronPeak** [jOOQ/jOOQ#7267] opened 2018-03-08 16:33 UTC
### Expected behavior and actual behavior:
DB2: SELECT * FROM [Dbo].[MyTable] FETCH FIRST 1 ROWS ONLY;

### Steps to reproduce the problem:
SELECT TOP(1) * FROM [Dbo].[MyTable];

### Versions:
- jOOQ: Version that is on the website (2018.03.08)

Saw this on reddit, decided to try it out :)

**Comment by lukaseder** [comment] 2018-03-08 16:41
Thanks you very much for your report. Indeed, our parser doesn't seem to recognise the parentheses around `(1)`. Try removing them and it should work.

Of course, since SQL Server can parse the parentheses, so should we. Will fix immediately.

**Comment by lukaseder** [comment] 2018-03-08 16:41
And thanks for trying our new product! Let us know if you find anything else :)

**Comment by lukaseder** [comment] 2018-03-08 16:44
I was too optimistic. This depends in fact on #5695, the capability of using arbitrary expressions in `TOP` / `LIMIT`, etc. E.g. this is also possible in SQL Server:

```sql
SELECT TOP (SELECT 1) * FROM [Dbo].[MyTable];
```

**Comment by lukaseder** [comment] 2018-03-09 10:28
Closing this as a duplicate of #5695

**Closed by lukaseder** 2018-03-09 10:28 UTC
Labels: C: Functionality, P: Medium, T: Defect
