### ISSUE TITLE
CTE api does not allow adding insert, update & delete statements

### ISSUE THREAD

**Issue by BrentDouglas** [jOOQ/jOOQ#5689] opened 2016-12-01 00:11 UTC
PG 9.5.4, jOOQ 3.8.3

In PG you can have delete, update and insert statements in CTE's, the jOOQ api does not accept this.

A hacky workaround is to wrap your statement in a proxy but it's not a great solution:

```

    private static Select<?> asSelect(final QueryPart part) {
        return (Select<?>) Proxy.newProxyInstance(
                Thread.currentThread().getContextClassLoader(),
                new Class[]{Select.class, QueryPartInternal.class},
                (p, m, args) -> {
                    if ("getSelect".equals(m.getName())) {
                        return Collections.emptyList();
                    }
                    return m.invoke(part, args);
                }
        );
    }
```

**Comment by lukaseder** [comment] 2016-12-02 09:38
Thank you very much for your feature request and for documenting an interesting workaround (I'm a bit afraid about the fact that this is now "documented" in this way, though 😉)

Indeed, this feature is missing and will be implemented eventually:

- https://github.com/jOOQ/jOOQ/issues/4474: Allow to form CTE from plain SQL or from ResultQuery
- https://github.com/jOOQ/jOOQ/issues/3185: Let InsertResultStep<R>, UpdateResultStep<R>, DeleteResultStep<R> extend Select<R>

At this stage, it's not 100% clear yet, whether this API change can be done backwards-compatibly, though.

I'll leave this open for now (not closing as duplicate), because perhaps, there's another way to wrap a `Query` in a `Select` for use with jOOQ's CTE API, rather than extending the existing API.

**Comment by lukaseder** [comment] 2019-03-26 15:03
Closing this issue as a duplicate of the other two linked issues

**Closed by lukaseder** 2019-03-26 15:03 UTC
Labels: C: DB: PostgreSQL, C: Functionality, P: Medium, T: Enhancement

**Comment by BrentDouglas** [comment] 2019-03-26 15:10
@lukaseder Is this just so you dont have to keep retargetting tickets or this works now?

**Comment by lukaseder** [comment] 2019-03-26 15:13
> Is this just so you dont have to keep retargetting tickets 

Yes

> or this works now?

No
