### ISSUE TITLE
Providing the primary key and using INSERT ... RETURNING returns null for emulating databases

### ISSUE THREAD

**Issue by jklingsporn** [jOOQ/jOOQ#7945] opened 2018-10-16 09:50 UTC
When using the `INSERT ... RETURNING` syntax and providing the primary key, I've observed different behavior in case the feature is natively supported and if the feature is emulated.
E.g. doing 

```sql
INSERT INTO foo(some_id) VALUES(1) RETURNING some_id
```

returns `1` for Postgres, but `null` for SQLite which does internally

```sql
INSERT INTO foo(some_id) VALUES(1);
select last_insert_rowid(); //return 0
select foo.some_id from foo where foo.some_id = 0; //null
```

This affects jOOQ 3.10.6.

**Comment by lukaseder** [comment] 2018-10-25 16:20
Thank you very much for your report. This shouldn't be the case of course. Some questions to help reproduce this:

1) How do you define your `foo` table (the DDL)?
2) What SQLite version are you using?
3) What's the jOOQ statement you wrote?

**Comment by zero-88** [comment] 2018-10-28 10:10
Hi @lukaseder @jklingsporn 
> How do you define your foo table (the DDL)?

Not via `jooq`. Just execute plain SQL via jdbc when startup app. But why it is relevant?

> What SQLite version are you using?

- vertx 3.5.1
- jOOQ 3.10.6
- vertx-jooq-rx-jdbc 3.1.0
- vertx-jooq-generate 3.0.2
- sqlite-jdbc 3.23.1

> What's the jOOQ statement you wrote?
```
17:16:33.637 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - Executing query          : insert into tbl_x (key, a, b, c, d, e, f, g, h, k, l) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
17:16:33.639 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - -> with bind values      : insert into tbl_x (key, a, b, c, d, e, f, g, h, k, l) values ('key', 'a', 'b', 'c', null, 'e', 'f', g', null, '', null)
17:16:33.661 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - Affected row(s)          : 1
17:16:33.663 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - Executing query          : select last_insert_rowid()
17:16:33.666 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - Fetched result           : +-------------------+
17:16:33.666 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener -                          : |last_insert_rowid()|
17:16:33.666 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener -                          : +-------------------+
17:16:33.666 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener -                          : |                  0|
17:16:33.666 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener -                          : +-------------------+
17:16:33.667 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - Executing query          : select tbl_x.key from tbl_x where _rowid_ = ?
17:16:33.667 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - -> with bind values      : select tbl_x.key from tbl_x where _rowid_ = 0
17:16:33.668 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - Fetched result           : +----------+
17:16:33.668 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener -                          : |key|
17:16:33.668 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener -                          : +----------+
17:16:33.673 [vert.x-eventloop-thread-1] ERROR com.myapp - Failed to startup application
java.lang.NullPointerException: Failed inserting record or no key
	at java.util.Objects.requireNonNull(Objects.java:290)
	at io.github.jklingsporn.vertx.jooq.shared.internal.AbstractVertxDAO.lambda$insertReturningPrimary$3(AbstractVertxDAO.java:151)
	at io.github.jklingsporn.vertx.jooq.rx.jdbc.JDBCRXQueryExecutor.lambda$insertReturning$3(JDBCRXQueryExecutor.java:41)
```

> Also perhaps relevant to this particular case, how do you set up your JDBC connection in SQLite? 

I used `Hikari` for manage datasource and connection pool. 

> Might be that it's too late to call last_insert_rowid() in your case, because the transaction has already been committed

I don't think so. It is in same thread, so it should in one transaction. This is code from `vertx-jooq`
https://github.com/jklingsporn/vertx-jooq/blob/master/vertx-jooq-shared/src/main/java/io/github/jklingsporn/vertx/jooq/shared/internal/AbstractVertxDAO.java#L148-L167

**Comment by lukaseder** [comment] 2018-10-29 09:05
> Not via jooq. Just execute plain SQL via jdbc when startup app. But why it is relevant?

Well, as I said... *"Some questions to help reproduce this"*. Specifically, SQLite has some wonky specialities when it comes to "data types", which don't actually exist in SQLite.

Think of it this way. I can either try to guess many things on how to reproduce it (because our integration tests don't help here), which will lead to a lot of ping pong on this issue, or you can show me an MCVE (https://stackoverflow.com/help/mcve), which would definitely include the DDL of a table that produces this behaviour. Just trying to ask you to help me help you :)

> What's the jOOQ statement you wrote?

That's not what I meant by "jOOQ statement". I meant the Java code where you worte this statement using the jOOQ API.

Anyway, since vertx-jooq is involved here, I think I definitely do need an MCVE first before I might be able to reproduce this.

**Comment by lukaseder** [comment] 2018-10-29 10:40
> Yes, I see this point. But I mean whole DDL does not make sense (at least for me), it is just simple table. And IMHO, I think this issue is close to primary_key data type instead of table structure.How do you define your foo table (the DDL)?

**Comment by lukaseder** [comment] 2018-10-29 10:40
> Yes, I see this point. But I mean whole DDL does not make sense (at least for me), it is just simple table. 

Well, I did write *"How do you define your foo table (the DDL)?"*, didn't I? I'm just interested in this particular table :-)

Thank you very much!

**Comment by zero-88** [comment] 2019-07-18 03:03
Hi @lukaseder ,
Sorry for delay this one. 
I think it is my fault when setup `org.jooq.Configuration`. I declared `Configuration` without `SQLDialect` (but already had it in `Hikari`) so almost case it works correctly but failed in this case.
Please close this ticket if you don't have any concern

**Comment by lukaseder** [comment] 2019-07-18 08:20
Thanks for the feedback, @zero-88. There might still be an issue, in @jklingsporn's setup though, so I won't close the issue yet.

**Comment by lukaseder** [comment] 2020-08-10 12:17
Thus far, I could not reproduce this issue. Will be happy to reopen if reproduction information is available.

**Closed by lukaseder** 2020-08-10 12:17 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Worksforme, T: Defect
