### ISSUE TITLE
Explicit select projection with * may fail

### ISSUE THREAD

**Issue by sweco-sebhar** [jOOQ/jOOQ#5198] opened 2016-04-11 11:14 UTC
Current logic here:
https://github.com/jOOQ/jOOQ/blob/master/jOOQ/src/main/java/org/jooq/impl/SelectQueryImpl.java#L375

Assumes either * or a proper field list, but a select query could also be a combination of * and a field list and in that case the field meta for the Result will include * as a field.

**Comment by lukaseder** [comment] 2016-04-11 11:54
Thank you very much for bringing this to our attention. Indeed, that logic might not be complete, but could you perhaps show a client code example of how to produce this issue you're describing?

**Comment by sweco-sebhar** [comment] 2016-04-11 12:23
Sorry, I have no easily extractable code at the moment and will have to resort to parsing the ResultSet on my own. Perhaps this example will be useful still:

```java
// select with * and explicit field
Result<?> result = ctx.select(DSL.field("*"), field).from(table).fetch()
// result will now report as having two field, one named * and the other will be the explicit field name.
```

**Comment by lukaseder** [comment] 2016-04-11 12:35
I see, thanks. That's good enough. I was afraid you were doing that :)

The jOOQ query model doesn't really support using asterisks yet. There are two pending feature requests for this: #1677, #2769. Unfortunately, for the time being, you cannot work around this limitation yet.

While we could certainly tweak the implementation to search for actual asterisks and then just ignore the select field list, the problem is that your `fetch()` really returns `Result<Record2<Object, Something>>` which is a lie.

One workaround would be to write:

```java
ctx.select(table.fields())
   .select(field)
   .from(table)
   .fetch();
```

I'm closing this as a duplicate of the other two issues. Ideally, we should add a formal `DSL.asterisk()` method to allow for explicitly using this feature.

**Closed by lukaseder** 2016-04-11 12:35 UTC
Labels: C: Functionality, P: Medium, T: Defect
