### ISSUE TITLE
Add support for DB2 rand-function with numeric seed-value in parser

### ISSUE THREAD

**Issue by marco135** [jOOQ/jOOQ#14297] opened 2022-11-25 08:09 UTC
### Use case

In DB2 it is possible to use a numeric seed in `rand`-function. 
https://www.ibm.com/docs/en/db2-for-zos/11?topic=functions-rand

This is currently not supported by the jOOQ-Parser.

```
-- can be parsed with jOOQ
select TBCREATOR, rand() from sysibm.syscolumns limit 10;
-- can't be parsed with jOOQ
select TBCREATOR, rand(1) from sysibm.syscolumns limit 10;
```
If have implemented a workaround with ParseListener, but native support would be nice.

### jOOQ Version

3.17.5 pro

### Database product and version

IBM DB2 v10.5.0.7 But it also occurred in the customer environment in a db2 version > 11.0

### Java Version

1.8

### OS Version

Windows 10

### JDBC driver name and version (include name if unofficial driver)

4.29.24

**Comment by lukaseder** [comment] 2022-11-25 08:51
Thanks for your suggestion. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/2237.

The workaround is to use plain SQL templating: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

**Closed by lukaseder** 2022-11-25 08:51 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, E: All Editions
