### ISSUE TITLE
Breaking change in 3.18 related to a new jsonbOject() overload

### ISSUE THREAD

**Issue by obourgain** [jOOQ/jOOQ#15406] opened 2023-07-13 16:06 UTC
### Expected behavior

With Jooq 3.17, this code 
```
DSL.jsonbObject(ar3.TYPE, ar3.CODE);
```
would call the method 
```
public static JSONObjectNullStep<JSONB> jsonbObject(Field<?>... entries)
```
and produce this result:
```
json_object(
  key 'type' value "ar3"."type",
  key 'code' value "ar3"."code"
)
```

### Actual behavior

With Jooq 3.18, there is a new overload
```
public static JSONObjectNullStep<JSONB> jsonbObject(Field<String> key, Field<?> value)
```
so the same code 
```
DSL.jsonbObject(ar3.TYPE, ar3.CODE);
```
now calls this more specific overload and returns this result:
```
json_object(
  key "ar3"."type"
  value "ar3"."code"
)
```

### Steps to reproduce the problem

Just related to the DSL, not specific to a DDL.

### jOOQ Version

3.18

### Database product and version

PostgreSQL 12.8 (Debian 12.8-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Java Version

openjdk version "17.0.7" 2023-04-18 LTS OpenJDK Runtime Environment Zulu17.42+19-CA (build 17.0.7+7-LTS) OpenJDK 64-Bit Server VM Zulu17.42+19-CA (build 17.0.7+7-LTS, mixed mode, sharing)

### OS Version

OSX 13.4.1

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.3.8

**Comment by lukaseder** [comment] 2023-07-13 17:21
Thanks for your report. This appears to be a duplicate of https://github.com/jOOQ/jOOQ/issues/15196.

Let me know if I'm overlooking something and I can reopen.

**Closed by lukaseder** 2023-07-13 17:21 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Duplicate, E: All Editions

**Comment by obourgain** [comment] 2023-07-13 20:43
yes, it is a duplicate, I didn't find the other one, sorry.
