### ISSUE TITLE
Using `returning()` causes `ClassCastException`

### ISSUE THREAD

**Issue by JarvisCraft** [jOOQ/jOOQ#12398] opened 2021-09-05 16:35 UTC
### Expected behavior

Correct table row record (`ClansRecord`) gets returned.

### Actual behavior

`ClassCastException` gets thrown:

<details>
<summary>Exception message</summary>

```
java.lang.ClassCastException: class org.jooq.impl.RecordImpl2 cannot be cast to class {package}.jooq.tables.records.ClansRecord (org.jooq.impl.RecordImpl2 and {package}.jooq.tables.records.ClansRecord are in unnamed module of loader 'app')
```

<details>
<summary>Beautified</summary>

```
java.lang.ClassCastException:
  class
    org.jooq.impl.RecordImpl2
  cannot be cast to class
    {package}.jooq.tables.records.ClansRecord
  (
      org.jooq.impl.RecordImpl2
    and
      {package}.jooq.tables.records.ClansRecord
    are in
      unnamed module of loader 'app'
)
```

</details>

</details>

### Steps to reproduce the problem

1. Generate a table from the following migration:
```sql
-- All available clans
CREATE TABLE "clans"
(
    -- Unique internal identifier of a clan
    "id"  BIGSERIAL PRIMARY KEY,
    -- Unique human-friendly identifier of a clan
    "tag" CHARACTER VARYING(16) NOT NULL UNIQUE
);
```

<details>
<summary>jOOQ-generated classes</summary>

<details>
<summary>{package}.jooq.Tables</summary>

```java
/*
 * This file is generated by jOOQ.
 */
package {package}.jooq;

import {package}.jooq.tables.Clans;

/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>clans</code>.
     */
    public static final Clans CLANS = Clans.CLANS;
}

```

</details>

<details>
<summary>{package}.jooq.tables.Clans</summary>

```java
/*
 * This file is generated by jOOQ.
 */
package {package}.jooq.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import {package}.jooq.DefaultSchema;
import {package}.jooq.Keys;
import {package}.jooq.tables.records.ClansRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Clans extends TableImpl<ClansRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>clans</code>
     */
    public static final Clans CLANS = new Clans();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClansRecord> getRecordType() {
        return ClansRecord.class;
    }

    /**
     * The column <code>clans.id</code>.
     */
    public final TableField<ClansRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>clans.tag</code>.
     */
    public final TableField<ClansRecord, String> TAG = createField(DSL.name("tag"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    private Clans(Name alias, Table<ClansRecord> aliased) {
        this(alias, aliased, null);
    }

    private Clans(Name alias, Table<ClansRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>clans</code> table reference
     */
    public Clans(String alias) {
        this(DSL.name(alias), CLANS);
    }

    /**
     * Create an aliased <code>clans</code> table reference
     */
    public Clans(Name alias) {
        this(alias, CLANS);
    }

    /**
     * Create a <code>clans</code> table reference
     */
    public Clans() {
        this(DSL.name("clans"), null);
    }

    public <O extends Record> Clans(Table<O> child, ForeignKey<O, ClansRecord> key) {
        super(child, key, CLANS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ClansRecord, Long> getIdentity() {
        return (Identity<ClansRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ClansRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_5;
    }

    @Override
    public List<UniqueKey<ClansRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_5A);
    }

    @Override
    public Clans as(String alias) {
        return new Clans(DSL.name(alias), this);
    }

    @Override
    public Clans as(Name alias) {
        return new Clans(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Clans rename(String name) {
        return new Clans(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Clans rename(Name name) {
        return new Clans(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
```

<details>
<summary>{package}.jooq.tables.records.ClansRecord</summary>

```java
/*
 * This file is generated by jOOQ.
 */
package {package}.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import {package}.jooq.tables.Clans;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClansRecord extends UpdatableRecordImpl<ClansRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>clans.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>clans.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>clans.tag</code>.
     */
    public void setTag(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>clans.tag</code>.
     */
    public String getTag() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Clans.CLANS.ID;
    }

    @Override
    public Field<String> field2() {
        return Clans.CLANS.TAG;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTag();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTag();
    }

    @Override
    public ClansRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ClansRecord value2(String value) {
        setTag(value);
        return this;
    }

    @Override
    public ClansRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClansRecord
     */
    public ClansRecord() {
        super(Clans.CLANS);
    }

    /**
     * Create a detached, initialised ClansRecord
     */
    public ClansRecord(Long id, String tag) {
        super(Clans.CLANS);

        setId(id);
        setTag(tag);
    }
}
```

</details>

</details>

</details>

2. Use the table in `INSERT .. RETURNING` expression:
```java
Mono.from(context
                 .insertInto(CLANS, CLANS.TAG)
                 .values(tag)
                 .onConflictDoNothing()
                 .returning()
 )
 .flatMap(record -> createManagedClan(record.getId(), record.getTag())) // <- usage
```

### Notes

Generic-record form works as expected:
```java
Mono.from(context
                 .insertInto(CLANS, CLANS.TAG)
                 .values(tag)
                 .onConflictDoNothing()
                 .returningResult(CLANS.ID, CLANS.TAG)
 )
 .flatMap(record -> createManagedClan(record.value1(), record.value2()))
```

### Versions

- jOOQ: `3.15.2`
- Java:
```
openjdk version "17-ea" 2021-09-14
OpenJDK Runtime Environment (build 17-ea+29-2576)
OpenJDK 64-Bit Server VM (build 17-ea+29-2576, mixed mode, sharing)
```
- Database: `PostgreSQL 13.4` (via `testcontainers`)
- OS: `Ubuntu 21.04 x86_64`
- R2DBC Driver: `rddbc-postgresql:0.9.0.M2`

**Comment by lukaseder** [comment] 2021-09-06 06:25
Thanks for your report. Duplicate of https://github.com/jOOQ/jOOQ/issues/12373

**Closed by lukaseder** 2021-09-06 06:25 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Duplicate, E: All Editions

**Comment by JarvisCraft** [comment] 2021-09-06 07:04
> Thanks for your report. Duplicate of https://github.com/jOOQ/jOOQ/issues/12373

Thank you for quick response
