### ISSUE TITLE
StackOverflowError in Eclipse

### ISSUE THREAD

**Issue by yuecelm** [jOOQ/jOOQ#9702] opened 2019-12-27 21:13 UTC
### Expected behavior and actual behavior:
Got a StackOverflowError when building my project with maven in Eclipse, log attached:
[eclipse.log](https://github.com/jOOQ/jOOQ/files/4006250/eclipse.log)
When building with command line maven, this bug gets not triggered.

### Steps to reproduce the problem:
set a relative path in scripts, e.g.: src/main/resources/db/migration/*
Right-click in eclipse project root -> Maven -> Update Project...

### Workaround (for eclipse):
set an absolute path in scripts, e.g.: ${basedir}/src/main/resources/db/migration/*
 or
append the file suffix in scripts, e.g.: src/main/resources/db/migration/*.sql

### Versions:

- jOOQ: 3.12.3
- Java:1.8.0_232
- Database (include vendor): DDLDatabase
- OS: Linux
- JDBC Driver (include name if inofficial driver): H2 (internal)

**Comment by lukaseder** [comment] 2019-12-30 10:16
Thank you very much for your report. There's a related bug when using relative paths, where the `DDLDatabase` implementation traverses too many files and directories in the file system: https://github.com/jOOQ/jOOQ/issues/8335

I think your workaround works for you, because you're traversing less files and directories this way.

I suspect that you might have some symlinks somewhere, which, when resolved, produce very big and deep (possibly infinitely deep, if you have cycles) file hierarchies.

**Comment by lukaseder** [comment] 2019-12-30 10:18
Can you confirm that this is symlink related? If it is, then I don't think we'll have an easy fix for this particular issue, short of actually fixing #8335, of course.

**Comment by yuecelm** [comment] 2019-12-30 12:53
not symlink related, neither in my source directory nor in my eclipse/workspace setup

**Comment by lukaseder** [comment] 2019-12-30 15:12
OK, thanks. Would it be possible to provide an MCVE that allows for reproducing this (https://github.com/jOOQ/jOOQ-mcve)? We use Eclipse to develop jOOQ and have not yet encountered this issue. I'm curious what is actually causing this.

**Comment by lukaseder** [comment] 2019-12-30 15:16
What `INFO` log output are you getting on your Maven build? When the "infinite" recursion happens between these two lines:

- https://github.com/jOOQ/jOOQ/blob/version-3.12.3/jOOQ-meta/src/main/java/org/jooq/meta/tools/FilePattern.java#L178
- https://github.com/jOOQ/jOOQ/blob/version-3.12.3/jOOQ-meta/src/main/java/org/jooq/meta/tools/FilePattern.java#L184

... what paths are being jumped back and forth to?

**Comment by yuecelm** [comment] 2019-12-30 16:06
really strange, its scanning my home directory (only copied the first lines):
```
12/30/19, 4:57:27 PM GMT+1: [INFO] Reading from: /home/yuecelm
12/30/19, 4:57:27 PM GMT+1: [INFO] Reading from: /home/yuecelm/.AndroidStudio3.5
12/30/19, 4:57:27 PM GMT+1: [INFO] Reading from: /home/yuecelm/.AndroidStudio3.5/config
12/30/19, 4:57:27 PM GMT+1: [INFO] Reading from: /home/yuecelm/.AndroidStudio3.5/config/codestyles
12/30/19, 4:57:27 PM GMT+1: [INFO] Reading from: /home/yuecelm/.AndroidStudio3.5/config/fileTemplates
12/30/19, 4:57:27 PM GMT+1: [INFO] Reading from: /home/yuecelm/.AndroidStudio3.5/config/fileTemplates/code
12/30/19, 4:57:27 PM GMT+1: [INFO] Reading from: /home/yuecelm/.AndroidStudio3.5/config/fileTemplates/includes
12/30/19, 4:57:27 PM GMT+1: [INFO] Reading from: /home/yuecelm/.AndroidStudio3.5/config/fileTemplates/internal
12/30/19, 4:57:27 PM GMT+1: [INFO] Reading from: /home/yuecelm/.AndroidStudio3.5/config/fileTemplates/j2ee
12/30/19, 4:57:27 PM GMT+1: [INFO] Reading from: /home/yuecelm/.AndroidStudio3.5/config/migration
:
```
it also go recursively in every directory starting with a dot (hidden directories). Now the big question: why its not scanning in my source code directory?

**Comment by yuecelm** [comment] 2019-12-30 16:08
FYI: I installed 'm2e - slf4j over logback logging (Optional)' in my eclipse installation in order to see these message in the 'Maven Console'.

**Comment by yuecelm** [comment] 2019-12-30 16:29
I think I found a hint: its reading first from the directory where I started my eclipse. If I start my eclipse from my home directory, its scanning my home directory, if I start my eclipse from my workspace, its scanning my workspace

**Comment by yuecelm** [comment] 2019-12-30 16:33
something similiar I observe with the maven command line:
```
yuecelm@laptop:~/eclipse/eclipse_201912/workspace$ mvn -f ~/git/my-project/ clean verify site
:
[INFO] --- jooq-codegen-maven:3.12.3:generate (generate-jooq-sources) @ jg-eddystone-resolver ---
[INFO] No <inputCatalog/> was provided. Generating ALL available catalogs instead.
[INFO] Reading from: /home/yuecelm/eclipse/eclipse_201912/workspace
[INFO] Reading from: /home/yuecelm/eclipse/eclipse_201912/workspace/.metadata
[INFO] Reading from: /home/yuecelm/eclipse/eclipse_201912/workspace/.metadata/.mylyn
[INFO] Reading from: /home/yuecelm/eclipse/eclipse_201912/workspace/.metadata/.mylyn/contexts
:
```

**Comment by yuecelm** [comment] 2019-12-30 16:44
something similiar I observe with the maven command line:
```
yuecelm@laptop:~/eclipse/eclipse_201912/workspace$ mvn -f ~/git/my-project/ clean verify site
:
[INFO] --- jooq-codegen-maven:3.12.3:generate (generate-jooq-sources) @ my-project ---
[INFO] No <inputCatalog/> was provided. Generating ALL available catalogs instead.
[INFO] Reading from: /home/yuecelm/eclipse/eclipse_201912/workspace
[INFO] Reading from: /home/yuecelm/eclipse/eclipse_201912/workspace/.metadata
[INFO] Reading from: /home/yuecelm/eclipse/eclipse_201912/workspace/.metadata/.mylyn
[INFO] Reading from: /home/yuecelm/eclipse/eclipse_201912/workspace/.metadata/.mylyn/contexts
:
```

**Comment by yuecelm** [comment] 2019-12-30 20:14
> OK, thanks. Would it be possible to provide an MCVE that allows for reproducing this (https://github.com/jOOQ/jOOQ-mcve)? We use Eclipse to develop jOOQ and have not yet encountered this issue. I'm curious what is actually causing this.

this issue is reproducible with jOOQ-flyway-ddl-example, just remove the '${basedir}/' part under scripts in pom.xml, the test will fail except you use the following command:
```
yuecelm@laptop:~/git/jooq/jOOQ-examples/jOOQ-flyway-ddl-example$ mvn -f ../pom.xml clean verify
```
verified today with branches version-3.12.0-branch and master

**Comment by knutwannheden** [comment] 2020-01-08 09:06
@yuecelm Your observations are correct. The relative `scripts` path are resolved against the current working directory, which makes this issue a duplicate of #8335. We have already set the priority of that issue to "High" and will most likely also backport the fix to 3.12.

Thanks again for your analysis!

**Closed by knutwannheden** 2020-01-08 09:06 UTC
Labels: C: Code Generation, E: All Editions, P: Medium, R: Duplicate, T: Defect

**Comment by lukaseder** [comment] 2020-01-13 11:35
I'd like to keep this one open to be sure we'll fix this as well. It seems that a solution that works out of the box also in IDEs might be a bit more tricky than a solution that simply allows for overriding the working directory...

**Comment by lukaseder** [comment] 2020-01-13 11:36
(I agree that it's a duplicate, but I'd like to have a reminder to verify we will have fixed this for @yuecelm as well)

**Comment by lukaseder** [comment] 2020-01-14 15:38
With https://github.com/jOOQ/jOOQ/issues/8335, we're now resolving relative paths according to the `${basedir}` of Maven, when using the Maven plugin. That should work regardless if the code generation is triggered from Eclipse or the command line.

I'm positive that this will fix your problem, @yuecelm. Specifically, this behaviour is no longer reproducible:
https://github.com/jOOQ/jOOQ/issues/9702#issuecomment-569729962

There are a number of prerequisites to fix this issue, which makes backporting it risky. We're planning on releasing 3.14 by mid Q1 2020. Until then, the workaround is to refrain from using relative paths by using `${basedir}` in Maven.
