### ISSUE TITLE
Better support for mapping a subset of columns on a result set

### ISSUE THREAD

**Issue by archerz** [jOOQ/jOOQ#11782] opened 2021-04-19 01:51 UTC
### Use case:

Assume a simple Team / Player structure where `TEAM` and `PLAYER` are two separate relational tables, with a one-to-many relationship (many players on one team) using a foreign key.

Now, consider a simple view of this data represented by a Java record as follows:

```java
record Player(String firstName, String lastName, Team team) {
    static record Team(String name, int rank) {}
}
```

Today, you can simply do:

```java
DSLContext jooq = ...;
List<Player> result = jooq
    .select(
        PLAYER.FIRST_NAME.as("firstName"),
        PLAYER.LAST_NAME.as("lastName"),
        TEAM.NAME.as("team.name"),
        TEAM.RANK.as("team.rank")
    )
    // from, join, where, etc
    .fetchInto(Player.class);
```

So far, so good. However, say now we like to do some pagination. We're dealing with random offsets / page numbers and don't want to deal with keeping state on the application, so we're fine with the potential performance penalty of doing pagination via OFFSET / LIMIT. Technically, the only thing we really need from the database is the total number of rows matching our SQL statement.

The idea is to still easily get a `List<Player>` back, but also fetch the total count and then extract it separately from the result set:

```java
var query = jooq.select(
    PLAYER.FIRST_NAME.as("firstName"),
    PLAYER.LAST_NAME.as("lastName"),
    TEAM.NAME.as("team.name"),
    TEAM.RANK.as("team.rank")
    count().over().as("_count")
)
// from, join, where, offset, limit

query.execute();

var totalCount = query.fetch("_count").get(0);    // assuming there's always at least one matching row
var page = query.fetchInto(Player.class);         // FAILS

// maybe use totalCount and the provided offset / limit to calculate the total number of pages, or something else
```

The `.fetchInto(Player.class)` call fails because no matching constructor on `Player` is found that supports the added `_count` field too.

### Possible solution you'd like to see:

Technically, jOOQ should still be able to do this mapping. The standard constructor on the `Player` record has all the fields present on the result set. Unless this goes against some fundamental design decision for how mapping works, jOOQ could simply ignore the "extra" columns (`_count` in this case) on the result set.

### Possible workarounds:

I can think of at least three, IMO undesirable, workarounds:
* Fetch the total count separately
  * Bad for obvious reasons.
* Mapping the result set to records manually
  * The code one has to write explodes in size. 
* Implementing a `RecordMapper` that does workaround 2 automatically, by making the canonical constructor on the record the "source of truth" for mapping and failing if any record component is not found on the result set
  * But, but, what if jOOQ did support this OOTB? 😁 

And one that kinda works: First copying the subset of fields (all except count) into another result set:
```java
var fields = query.getSelect().stream()
        .filter(field -> !"_count".equals(field.getName()))
        .toArray(Field<?>[]::new);

var page = query.getResult().into(fields).into(Player.class);
```

I'm not sure about the cost of "copying the records" as stated by `.into(Field<?>...)`'s javadoc . Is it negligible?

### Versions:

- jOOQ: 3.14.4
- Java: 14
- Database (include vendor): Postgres 12.6
- OS: macOS Catalina
- JDBC Driver (include name if inofficial driver): Official Postgres driver

**Comment by lukaseder** [comment] 2021-04-19 07:40
Thanks a lot for your feature request. I agree that this "should work" by intuition. After all, the expectations don't seem unreasonable, at first. Let's summarise how things *do* work, first:

- You're using the immutable record mapping logic, not the mutable one, so let's ignore the latter
- You're not using named parameters (though that will be possible on records starting with jOOQ 3.15: https://github.com/jOOQ/jOOQ/issues/11778, when your approach should work out of the box, at least using jOOQ's new Java 17 distribution). You could do that by using `@ConstructorProperties`. But there's a bug: https://github.com/jOOQ/jOOQ/issues/11783
- Instead, you're using indexed parameters, which can only work when there's an exact match between source and target
- Your naming convention suggests that the two `team.X` columns are nested in a single compound `team` column, so that removes one of the parameter indexes. Originally, you had 3 values (`firstName`, `lastName`, `team`) for 3 parameters. Now you're adding a 4th value (`_count`), so mapping by parameter index cannot work.

Regarding your assumptions:

> jOOQ could simply ignore the "extra" columns (`_count` in this case) on the result set.

Yes, if you're using named parameter mapping (and it doesn't currently work because of bug #11783), but not if you're using indexed parameter mapping, in case of which jOOQ can't just ignore the extra field. I mean, we could change that, but I fear this will lead to numerous edge cases that are hard to predict, and even possibly breaking changes of behaviour in existing code. I'd rather not.

You seem to expect that even with indexed parameter mapping, we can "just" ignore the excess columns if we don't find a constructor of matching degree. Could you make a case for why this is the desired behaviour in general?

> Mapping the result set to records manually
> * The code one has to write explodes in size.

It doesn't have to. If you have a convention to always call your extra column `_count` (or any `_xyz` name), you could just implement a simple `RecordMapperProvider` for all your queries: https://www.jooq.org/doc/latest/manual/sql-execution/fetching/pojos-with-recordmapper-provider/

> I'm not sure about the cost of "copying the records" as stated by `.into(Field<?>...)`'s javadoc . Is it negligible?

It's not "negligible", but is it negligible for your application? Perhaps... It copies the `Result` into a separate `Result`, it doesn't create a view. You don't have to copy the `Result`, only the records, so this will certainly be faster:

```java
var page = query.getResult().map(r -> r.into(fields).into(Player.class));
```

**Comment by lukaseder** [comment] 2021-04-20 08:20
> You seem to expect that even with indexed parameter mapping, we can "just" ignore the excess columns if we don't find a constructor of matching degree. Could you make a case for why this is the desired behaviour in general?

I've left this issue open because there might be an open issue with the above question. Apart from the obvious bug in the algorithm for nested named parameter mapping, I think this issue was about nested indexed parameter mapping.

Is there still a case to be discussed in that area?

**Comment by archerz** [comment] 2021-04-20 14:02
> > You seem to expect that even with indexed parameter mapping, we can "just" ignore the excess columns if we don't find a constructor of matching degree. Could you make a case for why this is the desired behaviour in general?
> 
> I've left this issue open because there might be an open issue with the above question. Apart from the obvious bug in the algorithm for nested named parameter mapping, I think this issue was about nested indexed parameter mapping.
> 
> Is there still a case to be discussed in that area?

With indexed parameter mapping, I personally think the expectation of "ignoring excess columns" is unreasonable. I was originally under the impression that with properly aliased columns, one can simply use named parameter mapping (which [clearly works now](https://github.com/jOOQ/jOOQ/issues/11783#issuecomment-822455728)).

I would consider this feature request fulfilled (and so fast) :)

**Comment by lukaseder** [comment] 2021-04-20 14:41
> I was originally under the impression that with properly aliased columns, one can simply use named parameter mapping

I see, that's where the confusion comes from. I wish we could switch to doing named parameter mapping by default, but there are so many cases where it doesn't work, mostly because the JVM doesn't maintain parameter names unless the `-parameter` flag (which isn't recommended) is used.

Do you think there is some sort of quick win that could have hinted to you that

- named parameter mapping wasn't applied
- but you could have enabled it somehow

I'm looking for potential UX improvements, because that might be a common confusion.

**Comment by lukaseder** [comment] 2021-04-20 14:41
(Closed as duplicate of #11783)

**Closed by lukaseder** 2021-04-20 14:41 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Feedback Pending, T: Enhancement

**Comment by archerz** [comment] 2021-04-20 20:55
> Do you think there is some sort of quick win that could have hinted to you that
>
> * named parameter mapping wasn't applied
> * but you could have enabled it somehow
>
> I'm looking for potential UX improvements, because that might be a common confusion.

I had to debug `DefaultRecordMapper` to find out.

Thinking out loud about the possibilities for improving UX, I think the least intrusive option would to embed which mapping strategy was used in the exception thrown from `.into(Class<?> type)` methods in case mapping fails.

**Comment by lukaseder** [comment] 2021-04-22 12:40
> Thinking out loud about the possibilities for improving UX, maybe the least intrusive option is to embed some information about which mapping strategy was used in the exceptions thrown from `.into(Class<?> type)` methods in case mapping fails.

That sounds like a great idea, also to help discover features that might not be known to users, such as `@ConstructorProperties` support...

**Comment by lukaseder** [comment] 2021-04-22 12:42
Will be done in a new issue: https://github.com/jOOQ/jOOQ/issues/11794
