### ISSUE TITLE
setIf on update query

### ISSUE THREAD

**Issue by jottyfan** [jOOQ/jOOQ#7723] opened 2018-08-06 18:00 UTC
Currently, an update statement can be build using the jooq DSL method chain like this:

```java
  DSL.update(T_MYTABLE)
    .set(T_MYTABLE.MYVAR, 42)
    .set(T_MYTABLE.MYVAR2, T_MYTABLE.MYVAR)
    .where(T_MYTABLE.MYCOND.eq(true));
```
that procudes this sql statement (postgresql dialect):
```sql
  update "myschema"."t_mytable"
    set "myschema"."t_mytable"."myvar" = 42,
        "myschema"."t_mytable"."myvar2" = "myschema"."t_mytable"."myvar"
  where "myschema"."t_mytable"."mycond" = true;
```
This is great and again shows the flexibility of jooq. I like this.

We have the two set methods:
```java
  set(Field<T> field, Field<T> value)
  set(Field<T> field, T value)
```
that allow these sql statements. I'd like to have another one that allows to add either a `Field` or a `T`, due to the condition that I give. Assume this:

```java
  Integer value = 42;
  Boolean addMyvar1 = value != null;
  Boolean addMyvar2 = false;
   DSL.update(T_MYTABLE)
    .setIf(addMyvar1, T_MYTABLE.MYVAR, value)
    .setIf(addMyvar2, T_MYTABLE.MYVAR2, T_MYTABLE.MYVAR)
    .where(T_MYTABLE.MYCOND.eq(true));
```
that should produce this sql code:
```sql
  update "myschema"."t_mytable"
    set "myschema"."t_mytable"."myvar" = 42
  where "myschema"."t_mytable"."mycond" = true;
```
As you can see, `myvar2` does not be part of the sql statement any longer. This way, I could write update statements for such conditional cases without loosing the jooq flexibility.

I know this is a bit tricky to add that to the framework, but I wonder what it took to add such a simple `addIf` method. Where could I start development? Or shouldn't I, because this idea is too weird?

**Comment by lukaseder** [comment] 2018-08-07 06:12
Thank you very much for your suggestion. A similar issue had been on the roadmap a while ago. It has been rejected in the meantime. See: #1817

The reason for rejection is the fact that this kind of API enhancement does not scale. Right now, you need `setIf()`. But then, you will also need `valuesIf()` on the INSERT statement. And `whereIf()`, `havingIf()`, `andIf()`, `orIf()` on the SELECT statement and the `Condition` API. Of course, the heavily overloaded `and()` and `or()` APIs would need to be overloaded heavily once more for `andIf()` and `orIf()`.

All of this doesn't really add substantial value, because it is very easy to move your predicate out of the DSL into client code and write:

```java
Map<Field<?>, Object> map = new LinkedHashMap<>();
if (addMyvar1)
    map.put(T_MYTABLE.MYVAR, value);
if (addMyvar2)
    map.put(T_MYTABLE.MYVAR2, T_MYTABLE.MYVAR);
DSL.update(T_MYTABLE)
   .set(map)
   .where(T_MYTABLE.MYCOND.eq(true));
```

Hope this helps

**Comment by lukaseder** [comment] 2018-08-07 06:12
Duplicate of #1817

**Closed by lukaseder** 2018-08-07 06:12 UTC
Labels: C: Functionality, P: Medium, T: Enhancement

**Comment by lukaseder** [comment] 2022-05-23 09:09
Starting with jOOQ 3.17, a new `noField()` expression can be created for such purposes: https://github.com/jOOQ/jOOQ/issues/2333


Specifically:

```java
ctx.update(T)
   .set(T.COL1, "X")
   .set(T.COL2, condition ? val("Y") : noField(T.COL2))
   .execute();
```

**Comment by slobo** [comment] 2024-07-24 04:10
`noField` needs to be the first argument to `set`. The working incantation is:

```java 
ctx.update(T)
   .set(T.COL1, "X")
   .set(condition ? T.COL2 : noField(T.COL2), val("Y"))
   .execute();

**Comment by lukaseder** [comment] 2024-07-24 06:30
@slobo Hmm, this shouldn't matter. It should be possible to use `noField()` both as the first or second argument to `set()`. If you encounter this limitation in the latest version, please create a new issue and we'll look into fixing this.

**Comment by slobo** [comment] 2024-07-24 15:44
You are absolutely right, I was holding it wrong it seems. Sorry for the noise.
