### ISSUE TITLE
Jsr310 LocalDateTime fail on batch insert queries but works in standard queries

### ISSUE THREAD

**Issue by dmiorandi** [jOOQ/jOOQ#6081] opened 2017-04-15 13:47 UTC
Hi @lukaseder, 
        this code have a strange behavior. If I use batch I've got an error on insert on datetime fields. Probably this is due to wrong formatting of date time or something like this (I suspect due to some 
java.sql.Timestamp conversion that generate a string without 'T' in the middle), possible?)
By executing same code using non batch inserts (commented code) seems to works fine, this is the strange point. Strange cause queries are already prepared.
Any ideas?

In attachments jackson pojo used as input and jooq record 
[Objects.zip](https://github.com/jOOQ/jOOQ/files/923642/Objects.zip)

- jooq 3.9.1
- sqlserver 2016 with ms jdbc driver (last)
- jdk 8-121
- code generate with jsr310 enabled (the jooq 3.9.x one)

```java
   @Override
    public void fetchShowTripReportExtern(LocalDateTime rangeFromLdt, LocalDateTime rangeToLdt) throws JAXBException {
        logger.info("Checking tomtom showObjectGroupsObjects...");
        List<Insert> queries =
                webFleetApi.fetchShowTripReportExtern(rangeFromLdt,rangeToLdt)
                    .stream()
                    .map(x->createBiDisponenti()
                                    .insertInto(TOMTOM_WS_SHOWTRIPREPORTEXTERN)
                                    .set(createBiDisponenti().newRecord(TOMTOM_WS_SHOWTRIPREPORTEXTERN, x)))
                    .collect(toList());
//        seq(queries).zipWithIndex().stream().forEach(x->{
//            System.out.println(x.v2);
//            x.v1.execute();
//        });

        createBiDisponenti()
                .batch(queries)
                .execute();

        logger.info("Checking tomtom showObjectGroupsObjects done!");
    }
```

stacktrace:

```
org.jooq.exception.DataAccessException: SQL [null]; Conversione non riuscita durante la conversione di una stringa di caratteri in una data o ora.

	at org.jooq_3.9.1.SQLSERVER2012.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:1983)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:676)
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:125)
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:78)
	at com.smashit.fralog.services.transp.tomtom.BiTomTomWsBusinessImpl.fetchShowTripReportExtern(BiTomTomWsBusinessImpl.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy78.fetchShowTripReportExtern(Unknown Source)
	at com.smashit.tests.manual.TomtomWebFleetTest.webFleetShowObjectGroupsFetchTest(TomtomWebFleetTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Conversione non riuscita durante la conversione di una stringa di caratteri in una data o ora.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1635)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeBatch(SQLServerStatement.java:1834)
	at com.zaxxer.hikari.proxy.StatementProxy.executeBatch(StatementProxy.java:127)
	at com.zaxxer.hikari.proxy.HikariStatementProxy.executeBatch(HikariStatementProxy.java)
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:93)
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:93)
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:106)
	... 44 
```

**Comment by lukaseder** [comment] 2017-04-20 14:19
Thank you very much for reporting, @dmiorandi. This looks a lot like these two: https://github.com/jOOQ/jOOQ/issues/2738, https://github.com/jOOQ/jOOQ/issues/5910. I will confirm as soon as possible.

**Comment by lukaseder** [comment] 2017-05-29 12:51
Indeed, this looks like a duplicate of #2738

**Closed by lukaseder** 2017-05-29 12:51 UTC
Labels: C: DB: SQL Server, C: Functionality, P: Medium, T: Defect

**Comment by dmiorandi** [comment] 2018-08-31 09:43
Hi @lukaseder,
this is mark as closed but I still have issue on batch (on jooq 3.11.4).
It seems that batch doesn't execute a queries that works instead in single execution. 
This query fail cause missing 'T' inside datetime field, in fact the following query give an error also executing in sqlserver directly.
If I execute this query in single mode instead it works. Something magic happens in single mode,
I think because datetime is converted in a different way otherwise it wouldn't work.
Any ideas/work around?

```sql
insert into [BANBARCOD] (
  [bdd_barcode], 
  [bdd_codsoc], 
  [bdd_codart], 
  [bdd_dtvalidita]
)
values (
  '3284790032343', 
  '25', 
  'ABEB2096932', 
  cast('2018-08-31 11:27:24.703' as datetime)
)
```

code is 
```
                    BanbarcodRecord banbarcodeRecord=BANBARCOD.newRecord()
                        .setBddCodsoc(calcCodSoc())
                        .setBddCodart(product.getCode())
                        .setBddBarcode(product.getEan())
                        .setBddDtvalidita(LocalDateTime.now());
                    InsertSetMoreStep<BanbarcodRecord> query2=createHpSs
                        .insertInto(BANBARCOD)
                        .set(banbarcodeRecord);
//                    query2.execute();
.....
                  createHpSs.batch(executedQueries).execute();
```

columns is record is like this
```
    /**
     * The column <code>Stocksystem.dbo.BANBARCOD.bdd_dtvalidita</code>.
     */
    public final TableField<BanbarcodRecord, LocalDateTime> BDD_DTVALIDITA = createField("bdd_dtvalidita", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");
```

**Comment by lukaseder** [comment] 2018-09-03 10:41
Hi @dmiorandi. Thanks for your message. I'm not sure if this is related - would you mind creating a new issue? Also, which call is failing? The `Query.execute()` call or the `Batch.execute()` call? In the latter case, what is `executedQueries`?

**Comment by dmiorandi** [comment] 2018-09-03 12:00
ok, new issue here #7843, better explained I Hope
