### ISSUE TITLE
Error when trying to delay DataType inference for scalar SQL type converted to user array type

### ISSUE THREAD

**Issue by mihalyr** [jOOQ/jOOQ#16978] opened 2024-07-15 22:52 UTC
### Your question

Hi Lukas, I wrote a custom JsonbArrayConverter and just wanted to check if I'm using it correctly. 

This is my converter:

```java
/**
 * Used for converting between an array of java objects and a JSONB database column by serializing the array into a JSON
 * array string. It uses the ObjectMapper from the jOOQ configuration context with key "objectMapper".
 *
 * @param <U> The type of the elements in the array
 */
public class JsonbArrayConverter<U> extends AbstractContextConverter<JSONB, U[]> {
  private static final String EMPTY_JSON_ARRAY_VALUE = "[]";
  private static final JSONB EMPTY_JSONB_ARRAY = JSONB.valueOf(EMPTY_JSON_ARRAY_VALUE);

  @SuppressWarnings("unchecked")
  public JsonbArrayConverter(final Class<U> toElementType) {
    super(JSONB.class, (Class<U[]>) toElementType.arrayType());
  }

  @Nullable
  @Override
  public U[] from(@Nullable final JSONB databaseObject, final ConverterContext ctx) {
    if (databaseObject == null) {
      return null;
    }

    var data = databaseObject.data();
    if (EMPTY_JSON_ARRAY_VALUE.equals(data)) {
      return emptyArray();
    }

    var mapper = contextObjectMapper(ctx);
    try {
      return mapper.readValue(databaseObject.data(), toType());
    } catch (final Exception e) {
      throw new RuntimeException("Failed to convert JSONB to array", e);
    }
  }

  @SuppressWarnings("unchecked")
  private U[] emptyArray() {
    return (U[]) Array.newInstance(toType().componentType(), 0);
  }

  @Nullable
  @Override
  public JSONB to(@Nullable final U[] userObject, final ConverterContext ctx) {
    if (userObject == null) {
      return null;
    }

    if (userObject.length == 0) {
      return EMPTY_JSONB_ARRAY;
    }

    var mapper = contextObjectMapper(ctx);
    try {
      return JSONB.valueOf(mapper.writeValueAsString(userObject));
    } catch (final Exception e) {
      throw new RuntimeException("Failed to convert array to JSONB", e);
    }
  }

  private ObjectMapper contextObjectMapper(final ConverterContext ctx) {
    if (ctx.configuration().data(DatabaseModule.DATABASE_MAPPER_KEY) instanceof ObjectMapper objectMapper) {
      return objectMapper;
    }
    // jOOQ is not configured with an ObjectMapper
    throw new IllegalStateException("ObjectMapper not found in context");
  }
}
```

And here is the configuration:

```xml
                <!-- Convert SignatureTag arrays to JSONB -->
                <forcedType>
                    <userType>com.example.SignatureTag[]</userType>
                    <includeTypes>JSONB</includeTypes>
                    <includeExpression>.*\.SIGNATURE\.SIGNATURE_TAGS</includeExpression>
                    <converter>new com.example.jooq.JsonbArrayConverter(com.example.model.SignatureTag.class)</converter>
                </forcedType>

```

I already use this setup for another POJO in a simple insert with success and now I wanted to use this in bulk insert (PostgreSQL VALUES ...), which I used like this:

```java
    tx.insertInto(s)
        .columns(
            s.SIGNATURE_HASH,
            s.SIGNATURE_BODY,
            s.SIGNATURE_TAGS,
            s.SIGNATURE_MATCH
        )
        .valuesOfRows(signatures.stream()
            .map(sig -> DSL.row(
                sig.signature().hash(),
                sig.signature().body(),
                sig.tags().toArray(SignatureTag[]::new),
                sig.match()))
            .toList())
        .execute();
```

However, jOOQ throws an error from `DSL.row` that the `DEFAULT` dialect does not support the `SignatureTag` class. I realized, I can get around this error by using a new record like below: 

```java
    tx.insertInto(s)
        .set(signatures.stream()
            .map(sig -> tx.newRecord(s)
                .setSignatureHash(sig.signature().hash())
                .setSignatureBody(sig.signature().body())
                .setSignatureTags(sig.tags().toArray(SignatureTag[]::new))
                .setSignatureMatch(sig.match()))
            .toList())
        .execute();
```

This works, I was just wondering if `DSL.row` was also supposed to work this way or I have to use `DSLContext.newRecord` when using custom converters?

### jOOQ Version

jOOQ Community Edition 3.19.10

### Database product and version

PostgreSQL 16.3

### Java Version

openjdk version "21.0.2" 2024-01-16 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.3

**Comment by lukaseder** [comment] 2024-07-31 13:01
Thanks for your message, and for your patience.

jOOQ tries to infer data types from context whenever possible. However, when nesting expressions (e.g. with `DSL.row(T1, T2, ..., TN)`, it may be the case that the inference isn't possible. In such a case, you can always create a bind value explicitly using `DSL.val(U, DataType<U>)`, explicitly passing your converted data type, and call `DSL.row(Field<T1>, Field<T2>, ..., Field<TN>)` instead. This is what happens behind the scenes if you create the `TableRecord` in your second example.

However, looking at your example, I don't see why the conversion wouldn't have worked out of the box. I'll try to reproduce this, soon.

**Comment by lukaseder** [comment] 2024-07-31 13:22
Hmm, I cannot seem to reproduce it with a simple attempt. I might need a more complete reproducer, or maybe, just the stack trace leading to the error might suffice.

Can you please double-check that you're using 3.19.10? 3.19.7 included a fix for a very similar issue (though it doesn't look exactly like yours):

- https://github.com/jOOQ/jOOQ/issues/16425

**Comment by lukaseder** [comment] 2024-07-31 13:31
Related:

- https://github.com/jOOQ/jOOQ/issues/8517

**Comment by mihalyr** [comment] 2024-07-31 15:33
> Can you please double-check that you're using 3.19.10? 

I use 3.19.10, from the latest Spring Boot 3.3.x (3.3.2) release: https://github.com/spring-projects/spring-boot/blob/2d0861d5bae561a379a22475e7854f27b4db754c/spring-boot-project/spring-boot-dependencies/build.gradle#L890

```
git:(main) g -q dependencies --configuration runtimeClasspath | grep jooq
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
|    +--- org.springframework.boot:spring-boot-starter-jooq:3.3.2 (c)
|    +--- org.jooq:jooq:3.19.10 (c)
+--- org.springframework.boot:spring-boot-starter-jooq -> 3.3.2
|    \--- org.jooq:jooq:3.19.10
```

**Comment by lukaseder** [comment] 2024-07-31 16:12
Thanks, so a stack trace would be helpful for me, then.

**Comment by mihalyr** [comment] 2024-07-31 16:34
Hi @lukaseder, is this sufficient?


```
2024-07-31T16:18:42,665 [WARN ] (Test worker) : SQLDialectNotSupportedException - Not supported by dialect : Type class com.example.service.core.signature.model.SignatureTag is not supported in dialect DEFAULT

Type class com.example.service.core.signature.model.SignatureTag is not supported in dialect DEFAULT
org.jooq.exception.SQLDialectNotSupportedException: Type class com.example.service.core.signature.model.SignatureTag is not supported in dialect DEFAULT
	at org.jooq.impl.DefaultDataType.getDataType0(DefaultDataType.java:957)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:837)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:830)
	at org.jooq.impl.DefaultDataType.getDataType0(DefaultDataType.java:885)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:837)
	at org.jooq.impl.DSL.getDataType0(DSL.java:35633)
	at org.jooq.impl.DSL.val0(DSL.java:33288)
	at org.jooq.impl.Tools.lambda$field$51(Tools.java:2152)
	at org.jooq.impl.Tools.field0(Tools.java:2147)
	at org.jooq.impl.Tools.field(Tools.java:2152)
	at org.jooq.impl.DSL.row(DSL.java:34071)
```

**Comment by lukaseder** [comment] 2024-07-31 16:35
Yes, thanks. I'll look into this again tomorrow.

**Comment by mihalyr** [comment] 2024-07-31 16:51
Lukas, one more datapoint, if I switch all fields to params with `DSL.val` and specify the types and converters explicitly, than `valuesOfRows` works with this:

```java
        .valuesOfRows(signatures.stream()
            .sorted(comparing(sig -> sig.signature().hash()))
            .map(sig -> DSL.row(
                DSL.val(sig.signature().hash().toUUID(), SQLDataType.UUID),
                DSL.val(sig.signature().body(), SQLDataType.CLOB),
                DSL.val(sig.tags().toArray(SignatureTag[]::new),
                    SQLDataType.JSONB.asConvertedDataType(new JsonbArrayConverter<>(SignatureTag.class))),
                DSL.val(sig.match(),
                    SQLDataType.CHAR.asConvertedDataType(Converter.ofNullable(
                        String.class,
                        SignatureMatchStatus.class,
                        SignatureMatchStatus::fromIdString,
                        SignatureMatchStatus::getIdString)))
            ))
            .toList())
```

**Comment by mihalyr** [comment] 2024-07-31 16:54
Or this is a much simpler version of the above, which also works:

```java
        .valuesOfRows(signatures.stream()
            .sorted(comparing(sig -> sig.signature().hash()))
            .map(sig -> DSL.row(
                DSL.val(sig.signature().hash().toUUID(), s.SIGNATURE_HASH.getDataType()),
                DSL.val(sig.signature().body(), s.SIGNATURE_BODY.getDataType()),
                DSL.val(sig.tags().toArray(SignatureTag[]::new), s.SIGNATURE_TAGS.getDataType()),
                DSL.val(sig.match(), s.SIGNATURE_MATCH.getDataType())))
            .toList())
```

**Comment by lukaseder** [comment] 2024-07-31 17:46
Yes, that's what I meant. Note that you don't have to pass the built-in data types (from `SQLDataType`). Those are always inferred correctly.

**Comment by lukaseder** [comment] 2024-08-05 10:48
Looking into this now. There seems to be something specific to using arrays, as can be shown with this small example:

```java
record X (int i) {}

DSL.row(1, new X(1));             // This works (data type lookup is delayed)
DSL.row(1, new X[] { new X(1) }); // This fails
```

The failure is the same as with your stack trace:

```
Exception in thread "main" org.jooq.exception.SQLDialectNotSupportedException: Type class org.jooq.testscripts.JDBC$1X is not supported in dialect DEFAULT
	at org.jooq.impl.DefaultDataType.getDataType0(DefaultDataType.java:981)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:861)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:854)
	at org.jooq.impl.DefaultDataType.getDataType0(DefaultDataType.java:909)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:861)
	at org.jooq.impl.DSL.getDataType0(DSL.java:37644)
	at org.jooq.impl.DSL.val0(DSL.java:35299)
	at org.jooq.impl.Tools.lambda$56(Tools.java:2179)
	at org.jooq.impl.Tools.field0(Tools.java:2174)
	at org.jooq.impl.Tools.field(Tools.java:2179)
	at org.jooq.impl.DSL.row(DSL.java:36056)
	at org.jooq.testscripts.JDBC.main(JDBC.java:39)
```

**Comment by lukaseder** [comment] 2024-08-05 11:28
I see now.

We've had integration tests where some SQL type `X` was converted to e.g. `SignatureTag`, and then that type was already registered as a `LegacyConvertedDataType` internally, when another column used `X[]` and `SignatureTag[]`. In that case, we could look up that `LegacyConvertedDataType`, and delay the decision to log/throw in case the actual data type binding or converter wasn't supplied.

In your case, the scalar type `JSONB` is directly mapped to an array type `SignatureTag[]`, in case of which the `LegacyConvertedDataType` logic didn't apply, and thus the exception occurred.

I can see how this can be fixed.

**Comment by lukaseder** [comment] 2024-08-05 11:30
Fixed in versions:

- 3.20.0
- 3.19.11 (https://github.com/jOOQ/jOOQ/issues/17006)
- 3.18.18 (https://github.com/jOOQ/jOOQ/issues/17007)
- 3.17.27 (https://github.com/jOOQ/jOOQ/issues/17008)

**Closed by lukaseder** 2024-08-05 11:30 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by mihalyr** [comment] 2024-08-06 14:15
Awesome! Thank you, Lukas. I'll test it as soon the new versions are released to Maven Central.

**Comment by mihalyr** [comment] 2024-09-12 22:03
I just managed to test this on 3.19.11 and seems to be working well. Thank you!

**Comment by lukaseder** [comment] 2024-09-13 06:10
Great  to hear, thanks for the feedback!
