### ISSUE TITLE
DDLDatabase defaultNameCase=lower doesn't work with ENUM types

### ISSUE THREAD

**Issue by therealppa** [jOOQ/jOOQ#15048] opened 2023-05-08 12:33 UTC
### Expected behavior

Please note this is almost the same as https://github.com/jOOQ/jOOQ/issues/13309 but I am _not_ using an enum array.

In the schema below, DDLDatabase should apply defaultNameCase to enum types just as it does for table or column names.

```
create type fruit as enum ( 'APPLE', 'PEAR', 'ORANGE' );

create table test_table
(
    fruits fruit
);

```

### Actual behavior

While the enum type is created with the correct name (quoted & lowercased), its reference in the table definition is transformed to uppercase and thus not recognized:

```
[INFO] create type "fruit" as enum ('APPLE', 'PEAR', 'ORANGE')
[INFO] Update count: 0          
[INFO] create table "test_table" (
  "fruits" FRUIT
)
[ERROR] DDLDatabase Error        : Your SQL string could not be parsed or interpreted. This may have a variety of reasons, including:
- The jOOQ parser doesn't understand your SQL
- The jOOQ DDL simulation logic (translating to H2) cannot simulate your SQL
If you think this is a bug or a feature worth requesting, please report it here: https://jooq.org/bug

```

When I put the type name in quotes, it works:
```

create type "fruit" as enum ( 'APPLE', 'PEAR', 'ORANGE' );

create table test_table
(
    fruits "fruit"
);
```

### Steps to reproduce the problem

I'm using these settings for the generator:

```

            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>${jooq.version}</version>
                <executions>
                    <execution>
                        <id>generate-jooq-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <generator>
                                <database>
                                    <name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
                                    <properties>
                                        <property>
                                            <key>sort</key>
                                            <value>flyway</value>
                                        </property>
                                        <property>
                                            <key>scripts</key>
                                            <value>src/main/resources/db/migration/*.sql</value>
                                        </property>
                                        <property>
                                            <key>defaultNameCase</key>
                                            <value>lower</value>
                                        </property>
                                    </properties>
                                </database>
                            </generator>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-meta-extensions</artifactId>
                        <version>${jooq.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```

### jOOQ Version

3.17.12

### Database product and version

none for code generation (PostgreSQL 14.6 at runtime)

### Java Version

17+35-LTS-2724

### OS Version

macos 13.3.1 

### JDBC driver name and version (include name if unofficial driver)

none for code generation (org.postgresql:postgresql:42.5.4 at runtime)

**Comment by lukaseder** [comment] 2023-05-12 08:34
Thanks for your report. I can reproduce this. Will look into a fix right away.

**Comment by lukaseder** [comment] 2023-05-12 08:50
The reason is that `Tools::toSQLDDLTypeDeclaration0` just calls `Context.sql(typeName)` rather than `Context.visit(typeNamePart)`. The former doesn't trigger the `VisitListener` implemented in the `DDLDatabase`, to turn the `UnquotedName` into a `QuotedName`

**Comment by lukaseder** [comment] 2023-05-12 08:52
There's probably a more thorough fix in https://github.com/jOOQ/jOOQ/issues/10376 somewhere, but for now, we can add another special case treatment to `Tools::toSQLDDLTypeDeclaration0`

**Comment by lukaseder** [comment] 2023-05-12 09:49
Fixed in jOOQ 3.19.0, 3.18.5 (https://github.com/jOOQ/jOOQ/issues/15062), 3.17.14 (https://github.com/jOOQ/jOOQ/issues/15063), and 3.16.20 (https://github.com/jOOQ/jOOQ/issues/15064)

**Closed by lukaseder** 2023-05-12 09:49 UTC
Labels: T: Defect, C: Code Generation, P: Medium, E: All Editions

**Comment by lukaseder** [comment] 2023-05-12 10:11
The fix introduced a regression when creating computed columns in DDL:

```
SQL [create table "t" ("dummy" int not null, "d" int not null as (("t"."dummy" * 2)), "s" int not null as (("t"."dummy" * 3)), "v" int not null as (("t"."dummy" * 4)), primary key ("dummy"))]; Column "t.dummy" not found; SQL statement:
create table "t" ("dummy" int not null, "d" int not null as (("t"."dummy" * 2)), "s" int not null as (("t"."dummy" * 3)), "v" int not null as (("t"."dummy" * 4)), primary key ("dummy")) [42122-214]
```

**Comment by lukaseder** [comment] 2023-05-12 10:13
Or rather, there was an existing bug hiding in the generation of computed column expressions, which didn't manifest so far, because we unqualified *all* objects inside of `CREATE TABLE` statements.
