### ISSUE TITLE
Bulk insert of BigDecimals with different scale get truncated to first rows scale

### ISSUE THREAD

**Issue by jesset-twosigma** [jOOQ/jOOQ#8964] opened 2019-07-17 23:13 UTC
### Expected behavior and actual behavior:
I used the jooq loader api (described [here](https://www.jooq.org/doc/3.11/manual/sql-execution/importing/importing-csv/)) to insert a bunch of rows at once. The table has a decimal(28,15) column in it. When using prepared statements, the generated sql uses the scale on the actual bigdecimal rather than the 15 on the column. SQL Server 2016 appears to only honor the first inserted row's scale and rounds the rest of the rows to match.

I found a similar bug in another library: https://github.com/microsoft/mssql-jdbc/issues/1021

It appears a solution is to use the column's scale/precision instead of the passed in BigDecimal.

### Steps to reproduce the problem:
Here an example scenario that illustrates the problem. The generated code matches what I got out of a sql server-side trace when using the loader api with prepared statements:

```sql
CREATE DATABASE test_db;
USE test_db;
CREATE TABLE test_table (
	my_num decimal(28,15)
);

declare @p1 int
set @p1=0
exec sp_prepexec 
	@p1 output,
	N'@P0 decimal(38,1),@P1 decimal(38,5)',
	N'insert into [dbo].[test_table] ([my_num]) values (@P0),(@P1)',
	1.1,
	1.12345;
SELECT * FROM test_table;
```

The select will have both rows with 1.1. Its not clear to me this is a jOOQ bug, but it was a very serious issue we hit without realizing it for quite a while.

### Versions:
- jOOQ: 3.11.2 Pro
- Java: 10
- Database (include vendor): SQL Server 2016
- OS: Linux
- JDBC Driver (include name if inofficial driver): Not sure, can find if needed

**Comment by lukaseder** [comment] 2019-07-18 08:40
Thank you very much for your report. This does look serious indeed. Do you still have the jOOQ code you used to produce this `INSERT`?

**Comment by jesset-twosigma** [comment] 2019-07-18 15:38
We have some internal tools I can't include, but here's an example I put together:

```
import java.math.BigDecimal;
import java.util.List;

import org.jooq.DSLContext;
import org.jooq.Loader;
import org.jooq.SQLDialect;

/**
 * Set database up with: 
 * CREATE DATABASE test_db; USE test_db; CREATE TABLE test_table ( my_num decimal(28,15) );
 */

public class BugIllustrator
{
    public static void main(String args[]) {
        final DSLContext context = // built with internal tools can try to generalize if needed
        // drop all as prep
        context.deleteFrom(Tables.TEST_TABLE).execute();

        final TestTableRecord lowScaleRecord = new TestTableRecord(BigDecimal.valueOf(1));
        final TestTableRecord highScaleRecord = new TestTableRecord(BigDecimal.valueOf(1.12345));

        try {
            final Loader<?> loader = context.loadInto(Tables.TEST_TABLE)
                .bulkAfter(2)
                .batchAfter(2)
                .loadRecords(List.of(lowScaleRecord, highScaleRecord))
                .fields(Tables.TEST_TABLE.fields())
                .execute();

            if (!loader.errors().isEmpty()) {
                throw loader.errors().get(0).exception();
            }
        } catch (final Exception e) {
            throw new RuntimeException(e);
        }

        // this print shows two 1s, expect one 1, and one 1.12345
        System.out.println(context.selectFrom(Tables.TEST_TABLE).fetch());
    }
}
```
Let me know if I can help more.

**Comment by jesset-twosigma** [comment] 2019-07-18 15:46
To exactly match the SQL, I guess I should have made lowScaleRecord use 1.1 instead of 1

**Comment by jesset-twosigma** [comment] 2019-07-23 14:53
@lukaseder any suggestions on how we should work around this? Currently we use bulkAfter(1).

**Comment by lukaseder** [comment] 2019-07-23 17:24
@jesset-twosigma I'm sorry for the delay. And thanks for the test case to reproduce this issue. We'll look into this with high priority.

As a workaround, could you try setting the scale explicitly on `BigDecimal` using `setScale()` prior to passing the value to jOOQ and by consequence to the JDBC driver? https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/math/BigDecimal.html#setScale(int,java.math.RoundingMode). You could use the column's meta information to retrieve the expected precision / scale in your schema via `Field.getDataType()`

(Do note, despite the name, this is not a mutating operation, it returns a new `BigDecimal`)

Another option where you could intercept the `BigDecimal` value would be if you implemented your own data type binding. That would be a bit more intrusive, as it would affect all queries, not just this particular insertion: https://www.jooq.org/doc/3.11/manual/sql-building/queryparts/custom-bindings/

**Comment by knutwannheden** [comment] 2019-07-26 14:34
I did some more testing and this looks like a SQL Server bug / limitation to me, because the following `sp_prepexec` call (where I simply split the statement into two `INSERT`s) works correctly:

```sql
exec sp_prepexec 
	@p1 output,
	N'@P0 decimal(38,1),@P1 decimal(38,5)',
	N'insert into [dbo].[test_table] ([my_num]) values (@P0); insert into [dbo].[test_table] ([my_num]) values (@P1)',
	1.1,
	1.12345;
```

I want to investigate what exact SQL statement is produced by jOOQ and see if I can further narrow this down.

**Comment by jesset-twosigma** [comment] 2019-07-26 14:36
I agree it appears to be an SQL Server limitation/bug. I'm not really sure where to report that... jOOQ could work around this by setting the scale to make the column schema like lukas suggested I do as a workaround.

**Comment by lukaseder** [comment] 2019-07-26 14:43
> I'm not really sure where to report that

One option is the SQL Server JDBC driver, which is MIT licensed and issue tracked here on github: https://github.com/microsoft/mssql-jdbc. We could also do this for you, try to find a minimal example that reproduces the issue with JDBC alone and try our luck there, what do you think, @knutwannheden ?

Perhaps there's something the driver could do, or the driver folks could pass along the information to the server folks, or come up with some documented setting that governs this behaviour.

> jOOQ could work around this by setting the scale to make the column schema like lukas suggested

We could definitely do this, verifying potential regressions first. As a quick fix, I think it's safer to fix this only for your particular case on your side. Or, since @knutwannheden's finding yields that single statements in a batch solve the problem, you could try to specify `bulkAfter(1)` and `batchAfter(4)`, instead.

**Comment by jesset-twosigma** [comment] 2019-07-26 15:10
If microsoft/mssql-jdbc is the right place, then there's already an open bug about this. https://github.com/microsoft/mssql-jdbc/issues/1021.

Maybe the "set decimal precision/scale from schema" feature could be optional? I'll try implementing it on my side and paste back what was required.

**Comment by knutwannheden** [comment] 2019-07-29 14:33
@jesset-twosigma Is explicitly calling `BigDecimal#setScale()` an acceptable workaround on your side? Just to be clear, the proposed fix applied to your example would be to change the line:

```java
final TestTableRecord lowScaleRecord = new TestTableRecord(BigDecimal.valueOf(1));
```
to:
```java
final TestTableRecord lowScaleRecord = new TestTableRecord(BigDecimal.valueOf(1).setScale(5));
```

But I assume in your production code the fix could be a bit more involved.

I am still looking into how we can best do a workaround on our side. Since the problem is related to bulk `INSERT` I would however first try to add the fix to `AbstractStoreQuery.addValue(Field<T>, int, T)` and `AbstractStoreQuery.addValue(Field<T>, int, Field<T>)`.

**Comment by jesset-twosigma** [comment] 2019-07-29 14:35
I think that is do-able. One issue I will have is that I have a nullable decimal column in my table. It appears that something in jOOQ is setting the precision to 0 for that case. I've seen cases where the first row has a null column, and then all following rows get rounded to 0 decimals :(

**Comment by knutwannheden** [comment] 2019-07-29 15:17
> One issue I will have is that I have a nullable decimal column in my table. It appears that something in jOOQ is setting the precision to 0 for that case. I've seen cases where the first row has a null column, and then all following rows get rounded to 0 decimals :(

Isn't that just and edge case of the same issue? The `BigDecimal#setScale()` workaround has to be applied to the first non-null value for every DECIMAL with scale column in your data set.

Please note that we will provide a fix in jOOQ in any case. But until we can deliver the patch release I hope the workaround will work for you.

**Comment by knutwannheden** [comment] 2019-07-30 08:35
> Isn't that just and edge case of the same issue? The `BigDecimal#setScale()` workaround has to be applied to the first non-null value for every DECIMAL with scale column in your data set.

No, you are right. If the first value is a `null` value, this approach fails. I will see if an explicit `CAST` / `CONVERT` of the `null` helps.

**Comment by knutwannheden** [comment] 2019-07-30 08:42
> No, you are right. If the first value is a `null` value, this approach fails. I will see if an explicit `CAST` / `CONVERT` of the `null` helps.

Just to confirm, an explicit `CAST` of the `null` appears to solve the problem, in case you want to test that on your side.

**Comment by knutwannheden** [comment] 2019-07-30 09:07
I would thus propose that instead of working with `BigDecimal#setScale()` that we simply explicitly `CAST` the first value of every (decimal with scale typed) column. E.g. `CAST(? AS DECIMAL(38, 5))`. This also works correctly in the presence of `NULL` values.

We will build this workaround into jOOQ 3.12 and also deliver it as part of the next 3.11 patch release.

Can you verify on your end that the proposed fix works correctly?

**Comment by knutwannheden** [comment] 2019-07-30 11:09
Fixed in 3.12. Backport scheduled for 3.11.12 (#8998).

**Comment by lukaseder** [comment] 2019-08-15 10:44
Reopening this fix for review. The fix, as it is now, may work only:

- If the query is created using `DSLContext`, not `DSL`
- If users do not call `InsertQuery.addValue()` multiple times

There's probably a better possible fix in `org.jooq.impl.FieldMapsForInstert.toSQL92Values()`.

**Comment by knutwannheden** [comment] 2019-08-15 15:13
As suggested, fix is now implemented in `FieldMapsForInstert#toSQL92Values()`.

**Closed by knutwannheden** 2019-08-15 15:13 UTC
Labels: C: DB: SQL Server, C: Functionality, E: Enterprise Edition, E: Professional Edition, P: High, R: Fixed, T: Defect

**Comment by lukaseder** [comment] 2019-08-15 15:29
Thanks, @knutwannheden. I will look into releasing 3.11.12 including this fix tomorrow.

**Comment by lukaseder** [comment] 2019-08-16 13:55
jOOQ 3.11.12 has been released with a fix for this issue.

**Comment by mikef-twosigma** [comment] 2020-04-06 19:10
Hi all -

Here with a potentially related issue--I'm working on a team with Jesse, who originally created this issue.

I'm seeing a significant decrease in insert performance (~5x) when my table has one or more decimal fields.

**jOOQ code used to perform inserts**
```
final Loader<?> loader = context.loadInto(table)
    .bulkAfter(requestedNumberOfRecordsPerInsertStatement)
    .batchAfter(numberOfInsertStatementsPerBatch)
    // Leave transaction committing to the client.
    .commitNone()
    .loadRecords(records)
    .fields(table.fields())
    .execute();
```

When I use this code to insert into a particular table T that has a single decimal(28, 15) column C in it, I get ~5,500 inserts per second. When I remove C from T, I see ~25,000 inserts per second.

**Raw SQL inserts from logs***
```
16:09:59,108 DEBUG LoggerListener:241 - Executing batch query    : 
insert into [dbo].[T] ([bigint], [int], [bigint], [int], [date], [tinyint], [C], [datetime2(7)], [bigint], [int]) values 
(?, ?, ?, ?, ?, ?, cast(? as numeric(28, 15)), ?, ?, ?), 
(?, ?, ?, ?, ?, ?, cast(? as numeric(28, 15)), ?, ?, ?), 
(?, ?, ?, ?, ?, ?, cast(? as numeric(28, 15)), ?, ?, ?), 
(?, ?, ?, ?, ?, ?, cast(? as numeric(28, 15)), ?, ?, ?), 
(?, ?, ?, ?, ?, ?, cast(? as numeric(28, 15)), ?, ?, ?), 
(?, ?, ?, ?, ?, ?, cast(? as numeric(28, 15)), ?, ?, ?), 
(?, ?, ?, ?, ?, ?, cast(? as numeric(28, 15)), ?, ?, ?), 
(?, ?, ?, ?, ?, ?, cast(? as numeric(28, 15)), ?, ?, ?), 
(?, ?, ?, ?, ?, ?, cast(? as numeric(28, 15)), ?, ?, ?), 
(?, ?, ?, ?, ?, ?, cast(? as numeric(28, 15)), ?, ?, ?)
```

I'm wondering if the cast is the root cause of decreased insert performance.

I tried to remove casting by messing with the DSLContext settings, though no luck.

Any thoughts are greatly appreciated.

Thanks very much. We really like jOOQ, @lukaseder (:

**Comment by mikef-twosigma** [comment] 2020-04-07 12:40
**Additional data: jOOQ vs. JDBC, rows inserted per second**
Using (batch size, # rows per insert statement) = (50, 10), and the table defined above.
In jOOQ, using Loader as defined above.
In JDBC, implementing multi-value inserts and batching by use of prepared statements.

- jOOQ with decimal(28, 15): 5,500
- JDBC with decimal(28, 15): 5,800
- jOOQ without decimal(28, 15): 25,000
- JDBC without decimal(28, 15): 48,000

Note that my use of JDBC may be prone to the original issue posted here, though I didn't verify.

**Comment by mikef-twosigma** [comment] 2020-04-07 16:44
**Update**
When I explicitly set the scale of each BigDecimal object before insertion, I'm back to expected performance!

For some reason, my BigDecimal objects were coming in with a scale of 1. Explicitly setting scale to 15, to match my table's decimal(28, 15) column, fixed the issue.

It looks like this investigation is concluded, unless anyone has any additional ideas for further improving performance.

**Closing statistics**
```
JDBC with decimal(4, 0); [explicitly set scale of BigDecimal before insertion]: 21,000 rows inserted / second
JDBC with float: 19,000 rows inserted / second
JDBC with decimal(28, 0); [explicitly set scale of BigDecimal before insertion]: 21,000 rows inserted / second
JDBC with decimal(28, 8); [explicitly set scale of BigDecimal before insertion]: 20,000 rows inserted / second
JDBC with decimal(28, 15): 7,000 rows inserted / second
JDBC with decimal(28, 15); [explicitly set scale of BigDecimal before insertion]: 20,000 rows inserted / second
jOOQ with decimal(28, 15); [explicitly set scale of BigDecimal before insertion]: 21,500 rows inserted / second
```

**Comment by lukaseder** [comment] 2020-04-08 14:49
Thanks a lot for your thorough report, @mikef-twosigma.

It would be interesting to see where the performance problem is being caused. Perhaps in the JDBC driver? Did you run a profiling session on your benchmark, e.g. using [VisualVM](https://visualvm.github.io)?

**Comment by lukaseder** [comment] 2024-10-07 08:30
A more generic case of this error has surfaced, where no `INSERT` statement is involved:

- https://github.com/jOOQ/jOOQ/issues/17401

The fix implemented for this issue here at the time was a very "defensive fix," meaning it attempted to minimise the impact of the fix to exactly what has been reported here. But perhaps, it would be more thorough to simply cast all `NUMERIC` bind values to their exact type, if they have a non-zero scale.
