### ISSUE TITLE
DefaultRecordMapper cannot map into generic type variable in Kotlin

### ISSUE THREAD

**Issue by XhstormR** [jOOQ/jOOQ#8578] opened 2019-04-30 03:38 UTC
### Expected behavior and actual behavior:

I have a test code like this:
```kotlin
        create
                .select(
                        DSL.one().`as`("group"),
                        DSL.two().`as`("count")
                )
                .fetchInto(GroupCountResponse::class.java)
                .forEach { println(it) }
```

And there is a kotlin data class like this:
```kotlin
data class GroupCountResponse<T> (
        val group: T,
        val count: Long
)
```

Executing this code will cause an exception:
```
2019-04-30 11:24:33.301  INFO 20500 --- [           main] c.x.e.a.config.handler.SQLBaseListener   : select 
  1 as "group", 
  2 as "count"


java.lang.IllegalArgumentException: argument type mismatch

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.jooq.impl.DefaultRecordMapper.init(DefaultRecordMapper.java:407)
	at org.jooq.impl.DefaultRecordMapper.<init>(DefaultRecordMapper.java:314)
	at org.jooq.impl.DefaultRecordMapper.<init>(DefaultRecordMapper.java:305)
	at org.jooq.impl.DefaultRecordMapperProvider$1.call(DefaultRecordMapperProvider.java:87)
	at org.jooq.impl.DefaultRecordMapperProvider$1.call(DefaultRecordMapperProvider.java:84)
	at org.jooq.impl.Tools$Cache.run(Tools.java:2882)
	at org.jooq.impl.DefaultRecordMapperProvider.provide(DefaultRecordMapperProvider.java:84)
	at org.jooq.impl.ResultImpl.into(ResultImpl.java:1369)
	at org.jooq.impl.AbstractResultQuery.fetchInto(AbstractResultQuery.java:1440)
	at org.jooq.impl.SelectImpl.fetchInto(SelectImpl.java:3741)
	at com.xhstormr.erp.JooqTests.test1(JooqTests.kt:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:185)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:181)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:128)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
```

As workaround, I add the @ConstructorProperties annotation:
```kotlin
data class GroupCountResponse<T> @ConstructorProperties(value = ["group", "count"]) constructor(
        val group: T,
        val count: Long
)
```

 I passed the test:
```
2019-04-30 11:22:48.651  INFO 61728 --- [           main] c.x.e.a.config.handler.SQLBaseListener   : select 
  1 as "group", 
  2 as "count"

GroupCountResponse(group=1, count=2)
```

I looked at the source code, it seems that this line of code has a bug, It seems that this code will reflect the call to the getJavaClass method in kotlin:
https://github.com/jOOQ/jOOQ/blob/master/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java#L407
The kotlin version I am using is the latest 1.3.31. This version of the getJavaClass method does not require parameters, maybe the problem is here: 
https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/jvm/runtime/kotlin/jvm/JvmClassMapping.kt#L27

### Versions:

- jOOQ: org.jooq:jooq:3.11.10
- Java: "12.0.1"
- Database (include vendor): Postgresql 11
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.5

**Comment by lukaseder** [comment] 2019-04-30 06:53
Thank you very much for your report. We'll investigate soon.

**Comment by rusio** [comment] 2019-05-14 16:26
We can confirm a similar type of regression with Kotlin. This stopped working after upgrading to jOOQ-3.11.10:

```
// Custom record class:
import java.sql.Timestamp

class PresentationRecorderState(val recorderUuid: String,
                                val recorderHost: String,
                                val recorderState: String,
                                val recorderCreated: Timestamp,
                                val timeSinceLastActivity: Long) {
}

// Code that fetches a record into the custom type:
fun getPresentationRecorders(): Collection<PresentationRecorderState> {
  return withTransactionResult { configuration ->
    using(configuration).select(PRESENTATION_RECORDERS.UUID)
                        .select(PRESENTATION_RECORDERS.HOST)
                        .select(PRESENTATION_RECORDERS.STATE)
                        .select(PRESENTATION_RECORDERS.CREATED)
                        .select(DSL.timestampDiff(DSL.currentTimestamp(),
                                                  PRESENTATION_RECORDERS.MODIFIED)
                                   .`as`("timeSinceLastActivity"))
                        .from(PRESENTATION_RECORDERS)
                        .orderBy(PRESENTATION_RECORDERS.HOST)
                        .fetchInto(PresentationRecorderState::class.java)
  }
}

// Error at runtime:
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method eu.lindenbaum.presentation.recorder.PresentationRecorderState.<init>, parameter recorderUuid
```

It seems that the jOOQ mapper does not invoke the primary constructor of the custom class properly. 

If instead we supply field names that match the names of the Kotlin properties, it maps successfully:

```
fun getPresentationRecorders(): Collection<PresentationRecorderState> {
  return withTransactionResult { configuration ->
    using(configuration).select(PRESENTATION_RECORDERS.UUID.`as`("recorderUuid"))
                        .select(PRESENTATION_RECORDERS.HOST.`as`("recorderHost"))
                        .select(PRESENTATION_RECORDERS.STATE.`as`("recorderState"))
                        .select(PRESENTATION_RECORDERS.CREATED.`as`("recorderCreated"))
                        .select(DSL.timestampDiff(DSL.currentTimestamp(),
                                                  PRESENTATION_RECORDERS.MODIFIED)
                                   .`as`("timeSinceLastActivity"))
                        .from(PRESENTATION_RECORDERS)
                        .orderBy(PRESENTATION_RECORDERS.HOST)
                        .fetchInto(PresentationRecorderState::class.java)
  }
}
```

This regression is also observed with jOOQ-3.11.11. Kotlin version is 1.3.31 and kotlin-reflect is on the classpath.

**Comment by lukaseder** [comment] 2019-07-17 12:46
Looking into this now, as we're fixing a few other Kotlin issues just before releasing 3.12.

I think the issues reported here are different issues:

1. The original issue reported by @XhstormR relates to the usage of a generic type variable `<T>`, which jOOQ currently cannot map. I'll continue investingating this and update this issue here with findings.
2. The additional issue reported by @rusio relates to the mapping no longer happening by index, but by name, since this was improved in a previous jOOQ release. Of course, we should have a setting to turn off this functionality. I have created https://github.com/jOOQ/jOOQ/issues/8959 for this.

As a workaround, both of you can turn off the `Boolean` value `org.jooq.impl.Tools.isKotlinAvailable` using reflection, to turn off this feature.

**Comment by lukaseder** [comment] 2019-07-17 13:03
So, @rusio's issue should be fixed with this new `Settings.mapConstructorParameterNamesInKotlin` flag, which should have been introduced right away, when we modified the behaviour of the `DefaultRecordMapper`...

**Comment by lukaseder** [comment] 2019-07-17 13:33
I'm currently reverse engineering the existing reflection magic that supports calling Kotlin constructors by parameter name mapping. The existing logic expects the constructor reflection information to have a list of `KClass` as argument types, but in your case, @XhstormR, you have a `KTypeParameter` for your `T` constructor parameter. `KTypeParameter` does contain a classifier that is a `KClass`. It seems that this works:

```java
getJavaClass.invoke(jvmClassMappingKt.get(), Reflect.on(typeClassifier).call("getUpperBounds").call("get", 0).call("getClassifier").get())
```

**Comment by lukaseder** [comment] 2019-07-17 13:46
Can confirm, after fixing this, the following test passes:

```kotlin
    data class GenericDataClass<T, U : Long>(val group: T, val count: U)

    @Test
    fun testDataClassMapperWithGenerics() {
        val result =
        ctx().select(DSL.one().`as`("group"), DSL.two().`as`("count"))
                .fetchOneInto(GenericDataClass::class)

        assertEquals(1, result.group);
        assertEquals(2, result.count);
    }
```

**Closed** 2019-07-17 13:49 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Fixed, T: Defect
