### ISSUE TITLE
Redundant unique index on primary key makes foreign keys disappear in PostgreSQL

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#17059] opened 2024-08-13 17:14 UTC
### Expected behavior

jOOQ should pick up and generate code for the foreign key

### Actual behavior

jOOQ seems to ignore the foreign key

### Steps to reproduce the problem

This test demonstrates the problem: https://github.com/alf/jOOQ-mcve/blob/a6d270cac7fc53bef364b15ea4f8d611753f3f0e/jOOQ-mcve-java-postgres/src/test/java/org/jooq/mcve/test/java/postgres/JavaTest.java#L82

The test runs against [the following DDL](https://github.com/alf/jOOQ-mcve/blob/a6d270cac7fc53bef364b15ea4f8d611753f3f0e/jOOQ-mcve-java-postgres/src/main/resources/db/migration/init.sql):

```sql
CREATE TABLE mcve.parent (
  parent_id bigint not null generated always as identity
);

CREATE UNIQUE INDEX parent_ux ON mcve.parent (parent_id)
;

ALTER TABLE mcve.parent ADD CONSTRAINT parent_pk PRIMARY KEY (parent_id)
;

CREATE TABLE mcve.child (
  child_id bigint not null generated always as identity,
  parent_id bigint not null
);

ALTER TABLE mcve.child
  ADD CONSTRAINT child_parent_fk
    FOREIGN KEY (parent_id)
    REFERENCES mcve.parent (parent_id)
    ON UPDATE CASCADE DEFERRABLE
;
```

Dropping the redundant unique index `parent_ux` causes the problem to disappear.

### jOOQ Version

3.19.10

### Database product and version

PostgreSQL 16.3

**Comment by lukaseder** [comment] 2024-08-14 14:33
Thanks for your report. I can reproduce this on PostgreSQL, but not e.g. on H2. Might be PG specific. Will investigate right away.

**Comment by lukaseder** [comment] 2024-08-14 14:42
Oh my. We're using JDBC's `DatabaseMetaData.getExportedKeys()` to avoid querying the `INFORMATION_SCHEMA`, which can't handle ambiguous constraint names (see #3520)

But that returns:

```
+-----------+-------------+--------------+-------------+-----------+-------------+-------------+-------------+-------+-----------+-----------+----------------+-----------------+-------------+
|pktable_cat|pktable_schem|pktable_name  |pkcolumn_name|fktable_cat|fktable_schem|fktable_name |fkcolumn_name|key_seq|update_rule|delete_rule|fk_name         |pk_name          |deferrability|
+-----------+-------------+--------------+-------------+-----------+-------------+-------------+-------------+-------+-----------+-----------+----------------+-----------------+-------------+
|{null}     |public       |t_17059_parent|parent_id    |{null}     |public       |t_17059_child|parent_id    |      1|          0|          3|fk_t_17059_child|uk_t_17059_parent|            6|
+-----------+-------------+--------------+-------------+-----------+-------------+-------------+-------------+-------+-----------+-----------+----------------+-----------------+-------------+
```

So, the JDBC driver looks up the wrong referenced key! I'll investigate this a bit further and report it to pgjdbc. We'll have to run our own query then, I presume.

**Comment by lukaseder** [comment] 2024-08-14 15:06
Well, it seems that `pg_catalog` reports this to the JDBC driver:

```sql
select con.oid, con.conname, con.contype, con.conindid, c.relname
from pg_constraint con
join pg_class c on con.conindid = c.oid
where con.conname like '%17059%';
```

This produces:

```
|oid    |conname          |contype|conindid|relname          |
|-------|-----------------|-------|--------|-----------------|
|990,368|t_17059_parent_pk|p      |990,367 |t_17059_parent_pk|
|990,373|fk_t_17059_child |f      |990,366 |uk_t_17059_parent|
```

In fact I cannot drop the unique index:

```sql
drop index uk_t_17059_parent;
```

As this produces:

> SQL Error [2BP01]: ERROR: cannot drop index uk_t_17059_parent because other objects depend on it
  Detail: constraint fk_t_17059_child on table t_17059_child depends on index uk_t_17059_parent
  Hint: Use DROP ... CASCADE to drop the dependent objects too.

In other words, the unique index and the primary key become the same object, except that logically, they might not be.

This changes if either:

- You inverse the order of creation of the primary key / unique index
- You create the primary key like this: `ALTER TABLE t_17059_parent ADD CONSTRAINT t_17059_parent_pk PRIMARY KEY using index uk_t_17059_parent;` (though, *very* counter intuitively, that just seems to replace the index!)

I guess we can try to look up the primary key from the unique index definition. A related issue is this:

- https://github.com/jOOQ/jOOQ/issues/10206

As a workaround, I recommend re-ordering the DDL statements, or avoiding the unnecessary `UNIQUE` index.

**Comment by lukaseder** [comment] 2024-08-14 15:27
Looking at the data available, I can only imagine 3 things that can be done here:

- Allow for foreign keys referencing unique indexes in general (that's probably the soundest solution), because that's possible in many SQL dialects as well. However, I fear that's quite the task, and won't be backportable.
- Treat unique indexes as unique constraints in the code generator (though, that would be "lying," especially if you want to export DDL from jOOQ-generated code)
- Handle this particular case by looking up data in `pg_index`, see query below

This query:

```sql
select 
  i.*, 
  c.*, 
  array (
    select a.attname
    from pg_attribute a
    where a.attrelid = c.oid
    order by attnum
  )
from pg_index i
join pg_class c on i.indexrelid = c.oid
and c.relname like '%17059%';
```

Produces this result:

```
|indexrelid|indrelid|indnatts|indnkeyatts|indisunique|indnullsnotdistinct|indisprimary|indisexclusion|indimmediate|indisclustered|indisvalid|indcheckxmin|indisready|indislive|indisreplident|indkey|indcollation|indclass|indoption|indexprs|indpred|oid    |relname          |relnamespace|reltype|reloftype|relowner|relam|relfilenode|reltablespace|relpages|reltuples|relallvisible|reltoastrelid|relhasindex|relisshared|relpersistence|relkind|relnatts|relchecks|relhasrules|relhastriggers|relhassubclass|relrowsecurity|relforcerowsecurity|relispopulated|relreplident|relispartition|relrewrite|relfrozenxid|relminmxid|relacl|reloptions|relpartbound|array      |
|----------|--------|--------|-----------|-----------|-------------------|------------|--------------|------------|--------------|----------|------------|----------|---------|--------------|------|------------|--------|---------|--------|-------|-------|-----------------|------------|-------|---------|--------|-----|-----------|-------------|--------|---------|-------------|-------------|-----------|-----------|--------------|-------|--------|---------|-----------|--------------|--------------|--------------|-------------------|--------------|------------|--------------|----------|------------|----------|------|----------|------------|-----------|
|992,775   |992,772 |1       |1          |true       |false              |false       |false         |true        |false         |true      |false       |true      |true     |false         |1     |0           |3124    |0        |        |       |992,775|uk_t_17059_parent|2,200       |0      |0        |10      |403  |992,775    |0            |1       |0        |0            |0            |false      |false      |p             |i      |1       |0        |false      |false         |false         |false         |false              |true          |n           |false         |0         |0           |0         |      |          |            |{parent_id}|
|992,785   |992,772 |1       |1          |true       |false              |true        |false         |true        |false         |true      |false       |true      |true     |false         |1     |0           |3124    |0        |        |       |992,785|t_17059_parent_pk|2,200       |0      |0        |10      |403  |992,785    |0            |1       |0        |0            |0            |false      |false      |p             |i      |1       |0        |false      |false         |false         |false         |false              |true          |n           |false         |0         |0           |0         |      |          |            |{parent_id}|
```

As can be seen, we could compare unique indexes and other constraint's column lists, and assume they're the same thing, such that lookups will continue working.

**Comment by lukaseder** [comment] 2024-08-14 15:50
> * Handle this particular case by looking up data in `pg_index`, see query below, or looking up indexes while adding foreign keys to the meta data

I'll opt for this option. We can look up indexes before looking up constraints, and we look up primary / unique constraints before looking up foreign key constraints, so this should work out of the box with our own tools, without any additional queries. The only precondition for the fix to work is that indexes are included in the meta configuration (though, they don't have to be generated).

**Comment by lukaseder** [comment] 2024-08-14 15:51
In any case, I don't consider this a pgjdbc bug, just a limitation in jOOQ, how it handles this weird PG edge case.

**Comment by lukaseder** [comment] 2024-08-14 15:54
Yeah.

I'll check tomorrow if this also affects runtime behaviour via `org.jooq.Meta`. It probably does, as we're using the same JDBC `DatabaseMetaData` API there.

**Comment by lukaseder** [comment] 2024-08-14 15:56
This will be fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17076)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17077)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17078)

I'll keep this open for the runtime behaviour checks.

**Comment by lukaseder** [comment] 2024-08-15 11:40
So, `org.jooq.Meta` doesn't run into this, because it relies entirely on JDBC `DatabaseMetaData` for both unique and foreign keys, so the results are consistent already, it seems.

**Closed by lukaseder** 2024-08-15 11:40 UTC
Labels: T: Defect, C: Functionality, C: Code Generation, C: DB: PostgreSQL, P: Medium, E: All Editions
