### ISSUE TITLE
record.merge() does not update record key but record.insert() does

### ISSUE THREAD

**Issue by strindberg** [jOOQ/jOOQ#11607] opened 2021-03-10 13:43 UTC
### Expected behavior
I am unsure whether this is a bug or not: it could be that this is expected behavior, but in any case it has tripped us up. When merge() is called on an UpdatableRecordImpl representing a new record in a table with a db generated primary key, the primary key is not set in the record object, but it is set when calling insert() on the same record.

### Actual behavior
When I call merge() on a record, the record's primary key is not updated.

### Steps to reproduce the problem
Flyway code:

```
CREATE TABLE item (
    id   bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text   NOT NULL,
    PRIMARY KEY (id)
);
```

Kotlin code:

`data class Item(val id: Long? = null, var name: String)`

This version works as expected (the record's id is updated):
```
class ItemRepository(private val dsl: DSLContext) {
    fun save(item: Item): Item {
        val record = dsl.newRecord(ITEM, item)
        if (record.id == null) {
            record.insert()
       } else {
            record.update()
        }
        return item.copy(id = record.id)
    }
}
```

This does not work (the record's id is _not_ set):
```
class ItemRepository(private val dsl: DSLContext) {
    fun save(item: Item): Item {
        val record = dsl.newRecord(ITEM, item)
        record.merge()
        return item.copy(id = record.id)
    }
}
```

### Versions

- jOOQ: 3.14.8
- Java: Kotlin 1.4.30
- Database (include vendor): Postgresql 13.2
- OS: MacOS

**Comment by esfomeado** [comment] 2021-11-23 17:04
@lukaseder Can you give some input of where to look to implement this so I can submit a PR?

**Comment by lukaseder** [comment] 2021-11-24 12:44
Thanks for the offer, @esfomeado. PRs are generally not a good idea, see all the rationale here: https://github.com/jOOQ/jOOQ/blob/main/CONTRIBUTING.md

However, I can see how this can be inconvenient, and I think I've seen it reported elsewhere, too, e.g. this here is a duplicate of https://github.com/jOOQ/jOOQ/issues/10051.

I'll see what can be done for those dialects where this can be supported.

**Comment by lukaseder** [comment] 2021-11-24 12:44
Duplicate of https://github.com/jOOQ/jOOQ/issues/10051

**Closed by lukaseder** 2021-11-24 12:44 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by lukaseder** [comment] 2021-11-24 12:47
Note, @strindberg, your original example can be implemented using `UpdatableRecord.store()`, if you can reset the `ID`'s `record.changed()` value in your record.
