### ISSUE TITLE
ERROR: type "blob" does not exist when casting NULL as a domain converted as user defined type using class literal

### ISSUE THREAD

**Issue by mhogerheijde** [jOOQ/jOOQ#14841] opened 2023-03-23 15:19 UTC
### Your question

We have a custom type
```
CREATE DOMAIN encrypted_data AS bytea;
```
that gets generated into the following java (not sure if this is relevant)
```
    /**
     * The domain <code>public.encrypted_data</code>.
     */
    public static final Domain<byte[]> ENCRYPTED_DATA = Internal.createDomain(
          schema()
        , DSL.name("encrypted_data")
        , SQLDataType.BLOB
    );
```
and a table that uses it:

```
CREATE TABLE modem_message (
    "time" timestamp with time zone NOT NULL,
    sequence smallint NOT NULL,
    firmware_version smallint NOT NULL,
    id bigint NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    organization_id bigint NOT NULL,
    location point,
    modem_number integer NOT NULL,
    encrypted_customer_payload encrypted_data,
    via_gateway integer,
    contains_gateway_messages boolean DEFAULT false NOT NULL,
    via_gateway_message bigint,
    sources modem_message_source[],
    metadata jsonb,
    "real" boolean,
    message_key text,
    measured_at timestamp with time zone
);
```

When inserting data into the table that uses the custom type, the following SQL is generated

```
insert into "public"."modem_message" (
    "id", 
    "organization_id", 
    "modem_number", 
    "via_gateway", 
    "via_gateway_message", 
    "contains_gateway_messages", 
    "time", 
    "received_at", 
    "location", 
    "sequence", 
    "firmware_version", 
    "encrypted_customer_payload", 
    "sources", 
    "metadata", 
    "real", 
    "message_key"
) values (
    ?, 
    ?, 
    ?, 
    cast(null as int), 
    cast(null as bigint), 
    ?, 
    cast(? as timestamp with time zone), 
    cast(? as timestamp with time zone), 
    ?::point, 
    ?, 
    ?, 
    cast(null as blob), 
    cast(? as "public"."modem_message_source"[]), 
    cast(null as jsonb), 
    ?, 
    ?
) on conflict do nothing
```

which upon execution gives the error:
```
ERROR: type "blob" does not exist
```

If I'm not mistaken, the `null` should be converted to `bytea`, since PostgreSQL doesn't really have blob type?

What am I doing wrong? It used to work with 3.14, but we're in the process of upgrading to 3.17.

### jOOQ Version

3.17.10

### Database product and version

PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Java Version

openjdk version "17.0.2" 2022-01-18

### OS Version

Ubuntu 22.10 (5.19.0-31-generic)

### JDBC driver name and version (include name if unofficial driver)

postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment] 2023-03-28 09:36
Thanks a lot for your report. I'll try to reproduce this shortly. There should be a cast to `bytea`, not `blob`, of course.

**Comment by lukaseder** [comment] 2023-03-28 10:29
Yeah, I get the `bytea` cast as expected. How can the issue be reproduced? The first thing to check is: Do you really use the `SQLDialect.POSTGRES` or perhaps (even if just in this case), somehow `SQLDialect.DEFAULT` was applied?

We have a template to create minimal reproducers, if that helps isolate the problem: https://github.com/jOOQ/jOOQ-mcve

**Comment by mhogerheijde** [comment] 2023-03-28 14:21
I'll try to find a minimal example that I can share :+1: 

We do, indeed, set `SQLDialect.POSTGRES` for the `DSLContext`.

**Comment by mhogerheijde** [comment] 2023-03-29 10:47
Found a minimal example: https://github.com/HiberGlobal/jOOQ-mcve/tree/blob-error-postgresql

I think it might be due to how we manually cast a null value, so this might be user-error in that sense. This did work in 3.14, so it might be this was deprecated behaviour.

**Comment by lukaseder** [comment] 2023-03-29 15:10
> It seems to work.

Yeah, the SQL cast isn't really necessary in `INSERT .. VALUES`, at least not for `BYTEA` types. The kotlin cast is something else. That just satisfies type inference. It doesn't do anything in jOOQ's runtime.

> But the explicit existence of `DSL#castNull` seems to indicate to me that I should use that one.

That is internal API that leaked into the public API a very long time ago... It doesn't really do anything special if you look at the implementation.

Anyway, I'll see why it produced the wrong SQL cast syntax, soon.

**Comment by mhogerheijde** [comment] 2023-03-29 15:15
I'll check with my colleague why we have this here, I suspect this whole setup was solely done to satisfy the the type-checker. In the example it's easy to drop the conversion to `Field<T>` bit, but the original is a bit more convoluted unfortunately.

**Comment by mhogerheijde** [comment] 2023-03-29 15:31
First results by just removing the conversion to `Field<T>` and just having the parameters be the direct type `T` or `T?` compiles and the one test I was using to show the issues passes now. Running the entire suite.

**Comment by lukaseder** [comment] 2023-03-30 14:28
This simple example doesn't reproduce it:

```kotlin
var b1: ByteArray? = null
ctx.select(b1.orInsertNull()).fetch()

var b2: ByteArray = "abc".toByteArray()
ctx.select(b2.orInsertNull()).fetch()
```

**Comment by mhogerheijde** [comment] 2023-03-31 13:50
Right, but when I do this with the custom domain thing,iIt fails again:

```kotlin
val encryptedPayload2: EncryptedData? = null
ctx.select(encryptedPayload2.orInsertNull()).fetch()
```


I checked with my colleague, it seems we did this to satisfy the type-checker. We're using the Java generated code from Kotlin 1.3 & JDK1.8. We're at Kotlin 1.8 with JDK17 now, so the typechecker probably got way better. We might just want to drop these conversions, they don't seem to be needed for us anymore.

Or we should just start using the Kotlin generated code 🙂.

**Comment by lukaseder** [comment] 2023-03-31 14:15
Ah yes of course, I forgot, you also had a domain involved. I'll try again early next week.

**Comment by mhogerheijde** [comment] 2023-04-03 07:05
Let me know if I can try some things out or run tests for you.

For us, either removing the conversion to `Field<T>` or changing the `castNull(T::class.java)` to `value(null as T?)` seems to work, I only have a few failing testcases I need to investigate left, I suspect they are either using a cast I missed or are unrelated to this.

**Comment by lukaseder** [comment] 2023-04-06 09:34
Looking into the MCVE now, which does reproduce the problem. Will investigate.

**Comment by lukaseder** [comment] 2023-04-06 09:38
The inferred type for `T` is `global.hiber.example.EncryptedDataBinding`, which cannot really work as jOOQ doesn't know what to do with it per se.

However, our dreaded static type registry (which will be replaced in the future), has a reference to the converted data type:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/734593/230337700-be855d19-febe-4c2e-8c9a-db79983fda98.png">

And it knows that it's a `BLOB`, so the question is only why this particular configuration doesn't produce the vendor specific type instead of the standard type.

**Comment by lukaseder** [comment] 2023-04-06 10:59
Might be a regression caused by https://github.com/jOOQ/jOOQ/issues/11070, where the `LegacyConvertedDataType` is wrapped wrongly because the `nullability` flag is propagated from the field argument by the `CAST` expression...

**Comment by lukaseder** [comment] 2023-04-06 11:15
Fixed in jOOQ 3.19.0, 3.18.3 (https://github.com/jOOQ/jOOQ/issues/14917), 3.17.12 (https://github.com/jOOQ/jOOQ/issues/14918), and 3.16.18 (https://github.com/jOOQ/jOOQ/issues/14919)

**Comment by lukaseder** [comment] 2023-04-06 11:15
Thanks again for your report!

**Closed by lukaseder** 2023-04-06 11:15 UTC
Labels: C: Functionality, P: Medium, T: Support request, E: All Editions

**Comment by mhogerheijde** [comment] 2023-04-06 15:20
Thanks for the quick fix!
