### ISSUE TITLE
Generated jooq sources tables names are uppercase and in my docker container migration is lowercase

### ISSUE THREAD

**Issue by renzodg** [jOOQ/jOOQ#12698] opened 2021-12-04 05:19 UTC
### Expected behavior
Generate jooq sources tables use same name for tables as liquibase migration generates 

### Actual behavior
Generated jooq tables names in uppercase causing errors when performing queries or inserts,updates because of mismatch of table name. Message: "table doesn't exist"

### Steps to reproduce the problem

- If the problem relates to code generation, please post your code generation configuration
- If the problem relates to upgrades, please check if your RDBMS version is still supported by jOOQ: https://www.jooq.org/download/support-matrix
- A complete set of DDL statements can help re-create the setup you're having
- An MCVE can be helpful to provide a complete reproduction case: https://github.com/jOOQ/jOOQ-mcve

### Versions

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by huuff** [comment] 2021-12-04 12:39
Check out [the `RenderNameCase` setting](https://www.jooq.org/doc/3.15/manual/sql-building/dsl-context/custom-settings/settings-name-style/)

**Comment by renzodg** [comment] 2021-12-04 13:52
Is that a runtime setting or previous generating source code?

**Comment by huuff** [comment] 2021-12-04 14:19
It's a runtime setting, you can create a `Settings` object like

```java
var settings = new Settings().withRenderNameCase(RenderNameCase.LOWER);
```
(Might not be exactly like that, I can't test it now, but surely is close enough)

And then add it to your `DSLContext` like

```java
DSLContext dsl = DSL.using(connection, dialect, settings);
```

**Comment by renzodg** [comment] 2021-12-04 17:22
Thanks man, that works. Would be my temporal solution tho I'll still looking for some config source generator so I don have to modify settings in runtime

**Comment by lukaseder** [comment] 2021-12-06 15:04
Thanks for your report, @renzodg. There are numerous criticisms of the current behaviour of `DDLDatabase`, `JPADatabase`, `LiquibaseDatabase`, which all simulate your migration on an in-memory H2 database behind the scenes, inheriting H2's behaviour. This works sufficiently well for many cases, but we know we need to get better at this. We'll remove H2 from the equation and interpret the generated SQL instead in the future. There are many open issues in that area, including e.g. https://github.com/jOOQ/jOOQ/issues/9820

In the meantime, `LiquibaseDatabase` is what it is, and currently has this limitation. As suggested  by @huuff, you can change the runtime behaviour using various `Settings` flags. It may be even simpler to just turn off quoting of identifiers.

Another option is to avoid using this simulation approach, and use testcontainers to execute your Liquibase migration on an actual target database instance (PostgreSQL, I assume?). This approach is described here:
https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

That blog post uses Flyway, but it would work the same way using Liquibase. I hope this helps.

**Comment by lukaseder** [comment] 2021-12-06 15:04
Closing as a duplicate of various other existing issues.

**Closed by lukaseder** 2021-12-06 15:04 UTC
Labels: T: Defect

**Comment by Michael2109** [comment] 2024-01-08 13:49
Hi @lukaseder, I've had this same issue when using Liquibase. Is there a specific issue created to improve this? 
Currently I worked around it by changing the runtime behaviour (as you mentioned) but that wasn't particularly nice.
As you currently use H2 in the background another solution might be to allow configuring how H2 is executed by JOOQ? E.g. You could pass in params to H2 to specify that you don't want it to use uppercase table names, run in compatability modes etc.

**Comment by lukaseder** [comment] 2024-01-08 13:57
@Michael2109 You've probably read this comment? https://github.com/jOOQ/jOOQ/issues/12698#issuecomment-986859259

**Comment by Michael2109** [comment] 2024-01-08 14:02
@lukaseder Yes which makes sense. I'm just wondering if allowing configuration of the underlying H2 database could be sufficient for the uppercase tables issues? I'd rather not use test containers and it would be nice if I could avoid changing the runtime behaviour too.

**Comment by lukaseder** [comment] 2024-01-08 14:12
H2 is an implementation detail that won't be exposed to users. There are already sufficient workarounds for this problem, so it's not necessary to introduce new workarounds, which aren't better than the existing ones, just different.
