### ISSUE TITLE
I got an error that told me creat an issue here

### ISSUE THREAD

**Issue by dabraham02124** [jOOQ/jOOQ#8676] opened 2019-05-23 15:04 UTC
While I am by no means sure that I'm doing this right (I'm having trouble following the doc on how to create jooq code from schema sql), you can see what I'm doing at https://github.com/dabraham02124/jooqCreator.  

I did try using the "official jOOQ-codegen-maven plugin", but I couldn't figure out how to tell it to use my schema file.

I know I'm getting the warning about "The content of element 'jdbc' is not complete".  When it is complete, codegen tries to log into the db that my box can't reach.  I can't figure out how to get it to not even try.  But when I omit it entirely, or have it empty, codegen stops right there.

Anyway, I'm getting the following:
```
May 23, 2019 10:25:25 AM org.jooq.tools.JooqLogger info
INFO: Initialising properties  : src/main/resources/jooq-config.xml
May 23, 2019 10:25:25 AM org.jooq.tools.JooqLogger warn
WARNING: Unmarshal warning        : cvc-complex-type.2.4.b: The content of element 'jdbc' is not complete. One of '{"http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd":url, "http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd":schema, "http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd":user, "http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd":username, "http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd":password}' is expected.
May 23, 2019 10:25:25 AM org.jooq.tools.JooqLogger info
INFO: No <inputCatalog/> was provided. Generating ALL available catalogs instead.
May 23, 2019 10:25:25 AM org.jooq.tools.JooqLogger info
INFO: No <inputSchema/> was provided. Generating ALL available schemata instead.
May 23, 2019 10:25:25 AM org.jooq.tools.JooqLogger info
INFO: License parameters       
May 23, 2019 10:25:25 AM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
May 23, 2019 10:25:25 AM org.jooq.tools.JooqLogger info
INFO:   Thank you for using jOOQ and jOOQ's code generator
May 23, 2019 10:25:25 AM org.jooq.tools.JooqLogger info
INFO:                          
May 23, 2019 10:25:25 AM org.jooq.tools.JooqLogger info
INFO: Database parameters      
May 23, 2019 10:25:25 AM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
May 23, 2019 10:25:25 AM org.jooq.tools.JooqLogger info
INFO: Reading from: src/main/resources/schema.sql [*]
May 23, 2019 10:25:26 AM org.jooq.tools.JooqLogger error
SEVERE: An exception occurred while parsing script source : src/main/resources/schema.sql. Please report this error to https://github.com/jOOQ/jOOQ/issues/new
org.jooq.impl.ParserException: Unknown function: [13:30] ...orming_strings = on;
SELECT pg_catalog.set_config([*]'search_path', '', false);
SET check_function_bodies = false;
SET xmloption = co...
	at org.jooq.impl.ParserContext.exception(ParserImpl.java:8511)
	at org.jooq.impl.ParserImpl.parseUnaryOps(ParserImpl.java:4221)
	at org.jooq.impl.ParserImpl.parseExp(ParserImpl.java:4191)
	at org.jooq.impl.ParserImpl.parseFactor(ParserImpl.java:4174)
	at org.jooq.impl.ParserImpl.parseSum(ParserImpl.java:4159)
	at org.jooq.impl.ParserImpl.parseCollated(ParserImpl.java:4142)
	at org.jooq.impl.ParserImpl.parseConcat(ParserImpl.java:4132)
	at org.jooq.impl.ParserImpl.parsePredicate(ParserImpl.java:3357)
	at org.jooq.impl.ParserImpl.parseNot(ParserImpl.java:3338)
	at org.jooq.impl.ParserImpl.parseAnd(ParserImpl.java:3328)
	at org.jooq.impl.ParserImpl.parseOr(ParserImpl.java:3319)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:4049)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:3983)
	at org.jooq.impl.ParserImpl.parseSelectList(ParserImpl.java:3919)
	at org.jooq.impl.ParserImpl.parseQueryPrimary(ParserImpl.java:1086)
	at org.jooq.impl.ParserImpl.parseQueryTerm(ParserImpl.java:1009)
	at org.jooq.impl.ParserImpl.parseQueryExpressionBody(ParserImpl.java:980)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:848)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:840)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:733)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:445)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:432)
	at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:207)
	at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:181)
	at org.jooq.meta.extensions.ddl.DDLDatabase.create0(DDLDatabase.java:141)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:231)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:220)
	at org.jooq.meta.AbstractDatabase.getDialect(AbstractDatabase.java:202)
	at org.jooq.codegen.AbstractGenerator.logDatabaseParameters(AbstractGenerator.java:155)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:299)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:752)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:222)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)

May 23, 2019 10:25:26 AM org.jooq.tools.JooqLogger error
SEVERE: Cannot read src/main/resources/jooq-config.xml. Error : Unknown function: [13:30] ...orming_strings = on;
SELECT pg_catalog.set_config([*]'search_path', '', false);
SET check_function_bodies = false;
SET xmloption = co...
org.jooq.impl.ParserException: Unknown function: [13:30] ...orming_strings = on;
SELECT pg_catalog.set_config([*]'search_path', '', false);
SET check_function_bodies = false;
SET xmloption = co...
	at org.jooq.impl.ParserContext.exception(ParserImpl.java:8511)
	at org.jooq.impl.ParserImpl.parseUnaryOps(ParserImpl.java:4221)
	at org.jooq.impl.ParserImpl.parseExp(ParserImpl.java:4191)
	at org.jooq.impl.ParserImpl.parseFactor(ParserImpl.java:4174)
	at org.jooq.impl.ParserImpl.parseSum(ParserImpl.java:4159)
	at org.jooq.impl.ParserImpl.parseCollated(ParserImpl.java:4142)
	at org.jooq.impl.ParserImpl.parseConcat(ParserImpl.java:4132)
	at org.jooq.impl.ParserImpl.parsePredicate(ParserImpl.java:3357)
	at org.jooq.impl.ParserImpl.parseNot(ParserImpl.java:3338)
	at org.jooq.impl.ParserImpl.parseAnd(ParserImpl.java:3328)
	at org.jooq.impl.ParserImpl.parseOr(ParserImpl.java:3319)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:4049)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:3983)
	at org.jooq.impl.ParserImpl.parseSelectList(ParserImpl.java:3919)
	at org.jooq.impl.ParserImpl.parseQueryPrimary(ParserImpl.java:1086)
	at org.jooq.impl.ParserImpl.parseQueryTerm(ParserImpl.java:1009)
	at org.jooq.impl.ParserImpl.parseQueryExpressionBody(ParserImpl.java:980)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:848)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:840)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:733)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:445)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:432)
	at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:207)
	at org.jooq.meta.extensions.ddl.DDLDatabase.load(DDLDatabase.java:181)
	at org.jooq.meta.extensions.ddl.DDLDatabase.create0(DDLDatabase.java:141)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:231)
	at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:220)
	at org.jooq.meta.AbstractDatabase.getDialect(AbstractDatabase.java:202)
	at org.jooq.codegen.AbstractGenerator.logDatabaseParameters(AbstractGenerator.java:155)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:299)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:752)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:222)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
```

My environment is:
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T14:41:47-04:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G6030
```

Please let me know what I should be doing here.  Thank you very much.

**Comment by lukaseder** [comment] 2019-05-23 15:39
Thank you very much for your report.

There are two issues here:

- I know I'm getting the warning about "The content of element 'jdbc' is not complete". When it is complete, codegen tries to log into the db that my box can't reach. I can't figure out how to get it to not even try. But when I omit it entirely, or have it empty, codegen stops right there.

You need *either* the `<jdbc>` configuration *or* the `DDLDatabase`, not both. It's curious that the `<jdbc>` configuration isn't simply ignored, I have created an issue to fix this confusing error: https://github.com/jOOQ/jOOQ/issues/8677

Also, omission should be possible. Perhaps there's something going wrong when using external configurations like you did, as opposed to using the Maven plugin.

> Anyway, I'm getting the following ...

Unfortunately, there are a number of pg_dump specific script elements that our parser cannot parse or ignore (yet). These statements are:

```sql
SELECT pg_catalog.set_config('search_path', '', false);
```

To ignore this, we need to make this flag available to the `DDLDatabase`: https://github.com/jOOQ/jOOQ/issues/7344, or turn it on by default. I've created https://github.com/jOOQ/jOOQ/issues/8678 for this.

I'm not 100% sure if we can ignore it. Will need to be verified.

```sql
ALTER TABLE public.ams_dagger_links OWNER TO "ams-reporting-metrics";
```

This is a statement we should parse and ignore: https://github.com/jOOQ/jOOQ/issues/8452

```sql
ALTER TABLE ONLY public.ams_viewer_action_types
    ADD CONSTRAINT ams_viewer_action_types_pkey PRIMARY KEY (action_type_id);
```

This is a statement we should parse and ignore the `ONLY` keyword: https://github.com/jOOQ/jOOQ/issues/8452

```sql
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM company;
GRANT ALL ON SCHEMA public TO company;
GRANT USAGE ON SCHEMA public TO PUBLIC;
GRANT CREATE ON SCHEMA public TO "ams-reporting-metrics";

...
ALTER DEFAULT PRIVILEGES FOR ROLE "ams-reporting-metrics" IN SCHEMA public REVOKE ALL ON TABLES  FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE "ams-reporting-metrics" IN SCHEMA public REVOKE ALL ON TABLES  FROM "ams-reporting-metrics";
ALTER DEFAULT PRIVILEGES FOR ROLE "ams-reporting-metrics" IN SCHEMA public GRANT SELECT ON TABLES  TO "ams-reporting-metrics_readonly";
```

Same here, we don't support any of these privileges yet in our API, so we currently don't parse them. There are currently no plans on improving this soon, athough we could probably just parse and ignore them as well.

For now, if you want to use the `DDLDatabase` with jOOQ on a pg-dump output, I recommend separating all grants / revoke commands in a separate table and possible preprocess the file prior to passing it to jOOQ by removing the above failing commands, which aren't essential to jOOQ.

**Comment by lukaseder** [comment] 2019-05-23 15:40
I'm keeping this issue open to validate whether we can parse your particular SQL script in the near future, once these things have been fixed.

**Comment by dabraham02124** [comment] 2019-05-23 16:38
Huh, I had tried commenting out the jdbc section, I must have missed commenting part of it, and messed things up there.  Mea culpa.  I've now just deleted the section.  Then I went through and deleted all of the sql lines that shouldn't be there.

And it works!  Woot!  Thank you so very much.

**Comment by dabraham02124** [comment] 2019-05-23 16:47
Oh, and I also had to change the name of the schema from "public"  It _looks_ like you parse the SQL by dumping it into an H2 DB which already has a "public" schema, and then extracting from that.  I don't know whether that's a limitation that you want to worry about.

Either way again, thank you very much.

**Comment by lukaseder** [comment] 2019-05-23 17:53
> Oh, and I also had to change the name of the schema from "public" It looks like you parse the SQL by dumping it into an H2 DB which already has a "public" schema, and then extracting from that. I don't know whether that's a limitation that you want to worry about.

I'm not sure what the conflict could be here. What problem did you run into, specifically? The fact that the schema already existed?

**Comment by lukaseder** [comment] 2019-05-31 13:36
I'm closing this as a duplicate of various other issues, which I had updated to contain the failures reported in this issue.

Thanks again for reporting!

**Closed by lukaseder** 2019-05-31 13:36 UTC
Labels: C: Parser, E: All Editions, P: Medium, R: Duplicate, T: Defect
