### ISSUE TITLE
Add support for Redshift's DATE_DIFF(datepart, date, date) function

### ISSUE THREAD

**Issue by ghoshrahul** [jOOQ/jOOQ#11955] opened 2021-06-03 07:05 UTC
### Expected behavior
On using the datediff function on redshift, it should give a normal result.

### Actual behavior
It is throwing a parser exception

```
 Token ')' expected: [1:209] ...en datediff('day', cast("users"."created" as date)[*], cast("users"."created" as date)) is not null then datediff('day', cast("users"...
	at org.jooq.impl.ParserContext.expected(ParserImpl.java:12225)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:11603)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:11598)
	at org.jooq.impl.ParserImpl.parseFieldDateDiffIf(ParserImpl.java:8490)
	at org.jooq.impl.ParserImpl.parseTerm(ParserImpl.java:6750)
	at org.jooq.impl.ParserImpl.parseUnaryOps(ParserImpl.java:6544)
	at org.jooq.impl.ParserImpl.parseExp(ParserImpl.java:6521)
	at org.jooq.impl.ParserImpl.parseFactor(ParserImpl.java:6498)
	at org.jooq.impl.ParserImpl.parseSum(ParserImpl.java:6444)
	at org.jooq.impl.ParserImpl.parseNumericOp(ParserImpl.java:6429)
	at org.jooq.impl.ParserImpl.parseCollated(ParserImpl.java:6403)
	at org.jooq.impl.ParserImpl.parseConcat(ParserImpl.java:6393)
	at org.jooq.impl.ParserImpl.parsePredicate(ParserImpl.java:5323)
	at org.jooq.impl.ParserImpl.parseNot(ParserImpl.java:5253)
	at org.jooq.impl.ParserImpl.parseAnd(ParserImpl.java:5243)
	at org.jooq.impl.ParserImpl.parseOr(ParserImpl.java:5234)
	at org.jooq.impl.ParserImpl.parseCondition(ParserImpl.java:5230)
	at org.jooq.impl.ParserImpl.parseFieldCaseIf(ParserImpl.java:9393)
	at org.jooq.impl.ParserImpl.parseTerm(ParserImpl.java:6717)
	at org.jooq.impl.ParserImpl.parseUnaryOps(ParserImpl.java:6544)
	at org.jooq.impl.ParserImpl.parseExp(ParserImpl.java:6521)
	at org.jooq.impl.ParserImpl.parseFactor(ParserImpl.java:6498)
	at org.jooq.impl.ParserImpl.parseSum(ParserImpl.java:6444)
	at org.jooq.impl.ParserImpl.parseNumericOp(ParserImpl.java:6429)
	at org.jooq.impl.ParserImpl.parseCollated(ParserImpl.java:6403)
	at org.jooq.impl.ParserImpl.parseConcat(ParserImpl.java:6393)
	at org.jooq.impl.ParserImpl.parsePredicate(ParserImpl.java:5323)
	at org.jooq.impl.ParserImpl.parseNot(ParserImpl.java:5253)
	at org.jooq.impl.ParserImpl.parseAnd(ParserImpl.java:5243)
	at org.jooq.impl.ParserImpl.parseOr(ParserImpl.java:5234)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:6310)
	at org.jooq.impl.ParserImpl.parseField(ParserImpl.java:6235)
	at org.jooq.impl.ParserImpl.parseSelectList(ParserImpl.java:6158)
	at org.jooq.impl.ParserImpl.parseQueryPrimary(ParserImpl.java:1485)
	at org.jooq.impl.ParserImpl.parseQueryTerm(ParserImpl.java:1390)
	at org.jooq.impl.ParserImpl.parseQueryExpressionBody(ParserImpl.java:1357)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:1136)
	at org.jooq.impl.ParserImpl.parseSelect(ParserImpl.java:1131)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:988)
	at org.jooq.impl.ParserImpl.parseResultQuery(ParserImpl.java:722)
	at org.jooq.impl.ParserImpl.parseResultQuery(ParserImpl.java:716)`
```

### Configuration

```java
private Settings redshiftSettings = new Settings().withParseNameCase(ParseNameCase.AS_IS).withStatementType(StatementType.STATIC_STATEMENT) .withInterpreterDialect(SQLDialect.REDSHIFT).withParseDialect(SQLDialect.REDSHIFT);

DSL.using(datasource, SQLDialect.REDSHIFT, redshiftSettings);
```

### Steps to reproduce the problem

- ```sql
  String sqlQuery = select  "users"."id" "Id", "users"."created" "Created", case when datediff('day', cast("users"."created" as date), cast("users"."created" as date)) is not null then datediff('day', cast("users"."created" as date), cast("users"."created" as date)) else 0 end "Result" from "users" "users"
  ```
- ```java
  ResultQuery jooqQuery =
                DSL.using(dslContext.configuration()).parser().parseResultQuery(sqlQuery);
  ```

### Versions

- jOOQ: 3.14.11 pro trial edition
- Java: 11
- Database (include vendor): Amazon Redshift
- OS: Ubuntu 18.04
- JDBC Driver (include name if inofficial driver):

This is a blocker, as our company is planning to buy the pro edition of JOOQ, for support of Amazon Redshift dialect.

**Comment by lukaseder** [comment] 2021-06-03 12:15
Thanks a lot for your feature request. jOOQ 3.14 has not yet included support for this style of `DATEDIFF(datepart, date, date)` function, but jOOQ 3.15 will: https://github.com/jOOQ/jOOQ/issues/7900. I will make sure it works on Redshift as well.

If you're planning on using jOOQ's parser, verison 3.15 will include a new feature that will be very helpful if ever jOOQ does not (yet) support some vendor-specific functionality, the `ParseListener` SPI: https://www.jooq.org/doc/dev/manual/sql-building/sql-parser/sql-parser-listener/

If you would like to enrol for an extended trial (which gives you access to jOOQ 3.15.0-SNAPSHOT builds from here: https://www.jooq.org/download/versions), please get in touch at sales@datageekery.com.

**Comment by lukaseder** [comment] 2021-06-03 12:16
Closing as duplicate of https://github.com/jOOQ/jOOQ/issues/7900

**Closed by lukaseder** 2021-06-03 12:15 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Enhancement

**Comment by lukaseder** [comment] 2021-06-03 14:05
`DATEDIFF(datepart, date, date)` now also works in Redshift, as per https://github.com/jOOQ/jOOQ/issues/7900, starting from the next nightly build of jOOQ 3.15.0-SNAPSHOT.
