### ISSUE TITLE
PostGIS functions causes uncompilable classes in codegen

### ISSUE THREAD

**Issue by jusw85** [jOOQ/jOOQ#5060] opened 2016-02-05 09:09 UTC
I'm trying to use PostGIS's ST_* functions in a select query.

When I run codegen, the generated Routines have hundreds of the following errors in the Record classes:

```
Error:(49, 21) java: method setValue(java.lang.Double) is already defined in class jooq.generated.tables.records.StValuepercentRecord
Error:(56, 23) java: method getValue() is already defined in class jooq.generated.tables.records.StValuepercentRecord
Error:(63, 21) java: method setValue(java.lang.Double) is already defined in class jooq.generated.tables.records.StValuepercentRecord
Error:(70, 23) java: method getValue() is already defined in class jooq.generated.tables.records.StValuepercentRecord
Error:(77, 21) java: method setValue(java.lang.Double) is already defined in class jooq.generated.tables.records.StValuepercentRecord
Error:(55, 66) java: variable MIN is already defined in class jooq.generated.tables.StApproxhistogram
Error:(60, 66) java: variable MIN is already defined in class jooq.generated.tables.StApproxhistogram
Error:(65, 66) java: variable MIN is already defined in class jooq.generated.tables.StApproxhistogram
```

Note that these functions appear multiple times with different method signatures, but similar parameter names:
```
CREATE OR REPLACE FUNCTION public.st_valuepercent(
    IN rast raster,
    IN nband integer,
    IN searchvalues double precision[],
    IN roundto double precision DEFAULT 0,
    OUT value double precision,
    OUT percent double precision)
CREATE OR REPLACE FUNCTION public.st_valuepercent(
    IN rastertable text,
    IN rastercolumn text,
    IN nband integer,
    IN searchvalues double precision[],
    IN roundto double precision DEFAULT 0,
    OUT value double precision,
    OUT percent double precision)
```

**Comment by lukaseder** [comment] 2016-02-05 15:29
Thank you very much for reporting this. I think this is a duplicate of #4055. Indeed a rather annoying issue. Unfortunately, we don't have a solution yet...

**Closed by lukaseder** 2016-02-05 15:29 UTC
Labels: C: Code Generation, C: DB: PostgreSQL, P: Medium, T: Defect
