### ISSUE TITLE
Oracle to Postgres query translation: sysdate is not converted to current_timestamp

### ISSUE THREAD

**Issue by EvgenyMilenin** [jOOQ/jOOQ#16253] opened 2024-02-09 19:33 UTC
### Expected behavior

On this page https://www.jooq.org/translate/ select Input Dialect - Oracle, Output- Postgres. Try to convert this query:
`select trunc(sysdate) from dual`

It it should be 
`SELECT date_trunc('day', CURRENT_TIMESTAMP)`

### Actual behavior

Output is
`SELECT date_trunc('day', sysdate)`

### Steps to reproduce the problem

On this page https://www.jooq.org/translate/ select Input Dialect - Oracle, Output- Postgres.

### jOOQ Version

N/A

### Database product and version

N/A

### Java Version

N/A

### OS Version

N/A

### JDBC driver name and version (include name if unofficial driver)

N/A

**Comment by lukaseder** [comment] 2024-02-12 08:20
Thanks for your report. This is a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/9716

**Closed by lukaseder** 2024-02-12 08:20 UTC
Labels: T: Defect, P: Medium, R: Duplicate, E: All Editions, C: Parser, C: Translator
