### ISSUE TITLE
Exception thrown when creating table with SQLDataType.TIMESTAMPWITHTIMEZONE in H2

### ISSUE THREAD

**Issue by kovax** [jOOQ/jOOQ#5805] opened 2017-01-22 11:47 UTC
Running the java statement will throw the exception bellow.

```java
context.createTableIfNotExists(table(tableName))
            .column(field("UUID",      UUID.class),           SQLDataType.UUID.nullable(false))
            .column(field("ID",        Integer.class),        SQLDataType.INTEGER.nullable(false))
            .column(field("TIMESTAMP", OffsetDateTime.class), SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false))
            .constraints(constraint("PK_"+tableName).primaryKey(field("UUID"), field("ID")))
.execute();
```

```
org.jooq.exception.DataAccessException: SQL [create table if not exists EVENT(UUID uuid not null, ID int not null, TIMESTAMP timestamp with time zone not null, constraint "PK_EVENT" primary key (UUID, ID))]; Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS EVENT(UUID UUID NOT NULL, ID INT NOT NULL, TIMESTAMP TIMESTAMP WITH TIME[*] ZONE NOT NULL, CONSTRAINT ""PK_EVENT"" PRIMARY KEY (UUID, ID)) "; expected "TIMEZONE"; SQL statement:
create table if not exists EVENT(UUID uuid not null, ID int not null, TIMESTAMP timestamp with time zone not null, constraint "PK_EVENT" primary key (UUID, ID)) [42001-193]
	at org.jooq_3.9.0.H2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:1981)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:676)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:363)
	at org.cristalise.storage.jooqdb.JooqHistoryHandler.createTables(JooqHistoryHandler.java:208)

Caused by: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS EVENT(UUID UUID NOT NULL, ID INT NOT NULL, TIMESTAMP TIMESTAMP WITH TIME[*] ZONE NOT NULL, CONSTRAINT ""PK_EVENT"" PRIMARY KEY (UUID, ID)) "; expected "TIMEZONE"; SQL statement:
create table if not exists EVENT(UUID uuid not null, ID int not null, TIMESTAMP timestamp with time zone not null, constraint "PK_EVENT" primary key (UUID, ID)) [42001-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.getSyntaxError(DbException.java:205)
	at org.h2.command.Parser.getSyntaxError(Parser.java:537)
	at org.h2.command.Parser.read(Parser.java:3186)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4053)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3938)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5977)
	at org.h2.command.Parser.parseCreate(Parser.java:4238)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:317)
	at org.h2.command.Parser.parse(Parser.java:293)
	at org.h2.command.Parser.prepareCommand(Parser.java:254)
```

**Comment by lukaseder** [comment] 2017-01-22 13:40
Thanks for your report. Until recently, this data type was not yet available in the H2 database. There is now experimental support for `TIMESTAMP WITH TIMEZONE` in version 1.4.192. Coincidentally, the data type was renamed to the SQL standard `TIMESTAMP WITH TIME ZONE` (which is generated by jOOQ by default). The relevant issue for renaming the data type is here: https://github.com/h2database/h2database/issues/411

Since this is an experimental data type, and since the `TIMEZONE` keyword will be deprecated in favour of `TIME ZONE`, I think it will be best to not revert jOOQ's data type to `TIMEZONE`.

I'll close this issue as a duplicate of https://github.com/jOOQ/jOOQ/issues/5806 (which will add support for the data type in jOOQ)

**Closed by lukaseder** 2017-01-22 13:40 UTC
Labels: C: DB: H2, C: Functionality, P: Medium, T: Defect

**Comment by kovax** [comment] 2017-01-23 11:47
Thanks Lukas. Can you suggest me an alternative db that I can use in-memory mode for my unit tests, please? I tried to use HSQLDB, but it has problems with UUID. Unfortunately I could not find the documentation for SQLType feature matrix for supported databases.

**Comment by lukaseder** [comment] 2017-01-23 12:11
Sorry, I can't make such a recommendation right now, as this part simply isn't covered by integration tests (DDL on UUID types). The only way forward right now is to:

- Not use a test database different from your production one (PostgreSQL, I assume?)
- Patch jOOQ
