### ISSUE TITLE
Oracle: SQLException "Invalid Name Pattern" on Bind of procedure-parameter (IN parameter with type table of varchar)

### ISSUE THREAD

**Issue by phbreitbach** [jOOQ/jOOQ#11768] opened 2021-04-08 15:36 UTC
### Expected behavior

Hoping the problem does not sit before its laptop:

I expected the Call to the following procedure would succeed:

```
create or replace PACKAGE      VEK_Generator IS
...
PROCEDURE freigeben(
    ...
  , p_nachbearbeitenListe           IN  OUT NOCOPY  ver_ase_gen.t_plsNacharbeitungsListe
 , ...
);

END VEK_Generator;
```
The type in the package ver_ase_gen is defined as follows:

```
create or replace PACKAGE      ver_ase_gen IS
...
TYPE t_plsNacharbeitungsListe IS TABLE OF plausibilitaet_meldungen.plm_fehlertext%TYPE INDEX BY VARCHAR2(9);
...
END ver_ase_gen;
```
The column `plm_fehlertext` of table `plausibilitaet_meldungen` has type `VARCHAR2(240 BYTE)`.

The schema of those packages is ICIS.

The generated JOOQ classes look fine enough to me:

```
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Freigeben extends AbstractRoutine<java.lang.Void> {
...
public static final Parameter<TPlsnacharbeitungslisteRecord> P_NACHBEARBEITENLISTE = Internal.createParameter("P_NACHBEARBEITENLISTE", SQLDataType.VARCHAR(240).asArrayDataType(de.cosmosdirekt.jooq.icis.packages.ver_ase_gen.udt.records.TPlsnacharbeitungslisteRecord.class), false, false);
...
}

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPlsnacharbeitungslisteRecord extends ArrayRecordImpl<String> {
...
/**
     * Create a new <code>ICIS.VER_ASE_GEN.T_PLSNACHARBEITUNGSLISTE</code> record
     */
    public TPlsnacharbeitungslisteRecord() {
        super(Icis.ICIS, VerAseGen.VER_ASE_GEN, "T_PLSNACHARBEITUNGSLISTE", SQLDataType.VARCHAR(240));
    }
...
}
```

### Actual behavior
Calling the procedure via
```
Freigeben freigebenRoutine = new Freigeben();
...
freigebenRoutine.setPNachbearbeitenliste(new TPlsnacharbeitungslisteRecord());
...
freigebenRoutine.execute(dslContext.configuration());
```
isn't successful and yields the follwing exception 
[Exception_on_execute_call.txt](https://github.com/jOOQ/jOOQ/files/6279712/Exception_on_execute_call.txt)
(The part `Caused by: java.sql.SQLException: Ungültiges Namensmuster: ICIS.VER_ASE_GEN.T_PLSNACHARBEITUNGSLISTE` seems relevant to me)

### Steps to reproduce the problem

- If the problem relates to code generation, please post your code generation configuration
--> Not sure if the problem relates to code generation, nevertheless here's the (relevant) config:

```
<configuration>
  <generator>
    <database>
      <includeInvisibleColumns>false</includeInvisibleColumns>
      <includes>
        <!--Tabellen-->
        | ICIS.VERTRAGSVERSIONEN
        ...
        | ICIS.PLAUSIBILITAET_MELDUNGEN
        <!--Packages-->
        | ICIS.VEK_GENERATOR.*
        ...
        | ICIS.VER_ASE_GEN.*
      </includes>
      <schemata>
        <schema>
          <inputSchema>ICIS</inputSchema>
        </schema>
      </schemata>
    </database>
  </generator>
</configuration>
```
Hope this is sufficient for a first look into it, if you need more sophisticated documentation please let me know ...

Thx a lot for your help!

Best,
Philipp

### Versions

- jOOQ: 3.14.8 trial edition
- Java: 11 (AdoptOpenJDK 11 with Oracle HotSpot JVM - Version: 11.0.8-10)
- Database (include vendor): Oracle 18.12.0.0.0
- OS: Win 10 (on my developer laptop)
- JDBC Driver (include name if inofficial driver): ojdbc8-19.9.0.0.jar

**Comment by lukaseder** [comment] 2021-04-09 13:39
Thanks a lot for your report. Unfortunately, we do not yet support Oracle associative array types yet, see: https://github.com/jOOQ/jOOQ/issues/5620 (12cR2+ support via ojdbc) and https://github.com/jOOQ/jOOQ/issues/5849 (12cR1- support via an emulation)

**Comment by phbreitbach** [comment] 2021-04-09 13:57
Thanks for your quick answer!
I was aware of #5620 but was confused because ...

On another function I have an OUT parameter of a declared type in the same package, which is table of vertragsversionen%rowtype or similar. Although only a deprecated Record class is generated, I can handle this ArrayRecord<Object> and read the corresponding data (I wondered wether I can address a comfortable Record class by Custom Data Binding or Converter but didn't find a way yet).

That was the reason I assumend this should work with an IN parameter as well?

Do you have a guess when #5620 will make it into a release? Or would you pricipally be open for a contribution for #5620 (not knowing wether we can really do this)?

**Comment by lukaseder** [comment] 2021-04-09 15:30
> On another function I have an OUT parameter of a declared type in the same package, which is table of vertragsversionen%rowtype or similar. Although only a deprecated Record class is generated, I can handle this ArrayRecord and read the corresponding data (I wondered wether I can address a comfortable Record class by Custom Data Binding or Converter but didn't find a way yet).

I'd have to see an example to see what's going on here. Associative arrays aren't the same thing as ordinary tables.

> That was the reason I assumend this should work with an IN parameter as well?

Whenever we have to emulate these things, `OUT` parameters tend to be easier to emulate than `IN` parameters. If you look at the generated SQL (e.g. by turning on logging https://www.jooq.org/doc/latest/manual/sql-execution/logging/) you can see how complex it is to emulate fetching PL/SQL types without the help of ojdbc, which offers only limited functionality.

> Do you have a guess when #5620 will make it into a release? Or would you pricipally be open for a contribution for #5620 (not knowing wether we can really do this)?

We can try to re-proritise this for the next release 3.15, due for late Q2 2021. As far as contributions go, you don't have access to the integration tests, so it will be difficult to make sure everything works. Technically, it's certainly possible. If you're licensed, you get the source code and the right to modification. If you sign the transfer of rights agreement, we could find a way (though the contribution wouldn't be open sourced).

But much easier than that, if you have some good ideas on how to implement this (via ojdbc, or via some anonymous PL/SQL block), that would definitely help speed things up over the next few weeks. I have a few minor improvements in the area of PL/SQL planned, including e.g. also support for typed ref cursors: https://github.com/jOOQ/jOOQ/issues/11708

**Comment by phbreitbach** [comment] 2021-04-09 19:20
I guess I'll try to an mcve for the cases I have at first:
- Original case in this issue
- Case from my comment before this
- Another case related to dateAsTimestamp property (I get Jooq Records with Timestamp attributes on Oracle DATE columns - correct - when passing the same record back to Oracle procedure they were not casted back to DATE - bug?). If I can reproduce with the mcve I'll report another issue ...

Will think about anonymous PL/SQL Blocks / ojdbc stuff as well ...

Cheers,
Philipp

**Comment by phbreitbach** [comment] 2021-04-10 06:30
BTW: For the time being, do you think it's possible to repair the original case with custom data binding or Converter? I'm developing a showcase for a business use case and would like to be able to demo it as soon as possible ...

**Comment by lukaseder** [comment] 2021-04-13 14:59
> BTW: For the time being, do you think it's possible to repair the original case with custom data binding or Converter? I'm developing a showcase for a business use case and would like to be able to demo it as soon as possible ...

It might be possible to work around the limitation using a data type binding as you will need to access the JDBC API to bind the in / out parameter, using a `Converter` wouldn't work. Using a binding, you can access ojdbc API directly and from what I can tell from the docs, starting from at least 18c (possibly even 12cR2), you could bind simple associative arrays - I'm not sure about the one you've shown - you'd have to try.

**Comment by lukaseder** [comment] 2021-04-13 14:59
For the demo, why not avoid this particular type for now, and show usage of other supported types? In particular, SQL `TABLE` and `OBJECT` types are supported.

**Comment by phbreitbach** [comment] 2021-04-13 15:52
I will do both
I already noticed that I can get the JDBC connection (and also unwrap the ojdbc OracleConection) only in the binding and not in the converter. I already started experimenting there but haven't anything runnable yet.
Also I will try to find another function which doesn't need associative arrays.
However, that's only for the demo and not the way I want to leverage - in our PL/SQL system we have many procedures suitable to be an SPI for our Java REST interfaces and I want to leverage the existing SPI candidates instead of building callable shells around them.
Thx for your suggestions!

**Comment by lukaseder** [comment] 2021-04-14 13:25
Looking into this now. While it is possible to use ojdbc (note the deprecations in 18.1!):

- 12c: https://docs.oracle.com/en/database/oracle/oracle-database/12.2/jjdbc/Oracle-extensions.html#GUID-FB2396B0-92CC-4C16-806B-3F54184E087A
- 18c: https://docs.oracle.com/en/database/oracle/oracle-database/18/jajdb/oracle/jdbc/OracleCallableStatement.html

I feel like the API might not be covering all the cases of nested records, etc. I'll try to tackle this with the usual "jOOQ style" of generating anonymous PL/SQL blocks. The way forward for Oracle 18c is this:

```sql
create or replace package p as
  type r is record (a number(10), b varchar2(32767));
  type t is table of r index by pls_integer;

  function f return t;
end p;
/

create or replace package body p as
  function f return t is
    l_r r;
    l_t t;
  begin 
    l_r.a := 1;
    l_r.b := 'a';
    l_t(1) := l_r;
    l_r.a := 5;
    l_r.b := 'e';
    l_t(3) := l_r;
    return l_t;
  end f;
end p;
/
```

And then:

```sql
declare
  a p.t;
  i number;
  k dbms_sql.number_table;
  ck sys_refcursor;
  cv sys_refcursor;
begin
  k := dbms_sql.number_table();
  a := p.f;
  i := a.first;
  while i is not null loop
    k(i) := i;
    i := a.next(i);
  end loop;

  open ck for select * from table(k);
  open cv for select * from table(a);

  dbms_sql.return_result(ck);
  dbms_sql.return_result(cv);
end;
/
```

In prose: We have to

- Correctly reverse engineer an associative array's key and value types in the code generator
- fetch all the keys into an auxiliary `dbms_sql.number_table` or `dbms_sql.varchar2_table`
- return a `sys_refcursor` containing the keys
- return another `sys_refcursor` containing the values

**Comment by lukaseder** [comment] 2021-04-14 13:46
OK, I'm trying to reverse engineer also what's currently working (undocumented), and what isn't working yet. We can fetch PL/SQL associative array values (not the keys) for some cases. Your original example should work, in my opinion. Can you try a newer ojdbc driver version again? E.g. 21.1.0.0? https://search.maven.org/artifact/com.oracle.database.jdbc/ojdbc11/21.1.0.0/jar

**Comment by phbreitbach** [comment] 2021-04-14 14:27
Emulation sounds cool!
I noticed the ojdbc 18 deprecations and couldn't get a working ojdbc sample running up to now but I'm trying further.
Also I'll try your ojdbc 21 suggestion and post the feedback here, thx a lot!

**Comment by phbreitbach** [comment] 2021-04-15 01:38
That's great!
In the MCVE I'm building, ojdbc11 21.1.0.0 seems to work. Gonna check 2 other test cases and post results then ...
Can't confirm for my original case up to now as I'm still convincing our framework to use the newer ojdbc driver ;-) Will let you know once I'm through that ...

**Comment by phbreitbach** [comment] 2021-04-15 05:14
I've got a nice MCVE working with ojdbc11 21.1.0.0. (see attached files, as .txt, can't push to github unfortunately need to fix proxy rigths first). All tests are green.
Vexingly, the original case does not work, although now it's using ojdbc11 21.1.0.0 :-/
Digging ...
[JavaTest.txt](https://github.com/jOOQ/jOOQ/files/6315283/JavaTest.txt)
[V1__initialise_test_db.txt](https://github.com/jOOQ/jOOQ/files/6315284/V1__initialise_test_db.txt)
[pom.txt](https://github.com/jOOQ/jOOQ/files/6315285/pom.txt)

**Comment by phbreitbach** [comment] 2021-04-15 05:52
The only obvious difference between the MCVE and the real case is the DB user:

MCVE:
- User DEVSB to generate
- All DB objects are in the schema of DEVSB
- User DEVSB to run the tests against the database

Real case:
- User DEVSB to generate
- All DB objects are in the schema of **ICIS**
- User BATCH (also tried DEVSB) to run the tests against the database

Are there any specific rigths needed for BATCH or DEVSB during generation or runtime to access the DB Objects of ICIS for this case to work?

**Comment by phbreitbach** [comment] 2021-04-15 10:07
As it turns out it only works if the index of the associative array ist pls_integer.
When I switch to VARCHAR2 in the MCVE then all tests run in error:

```
TYPE t_associativearray IS TABLE OF mcvetest.fehlertext%TYPE INDEX BY VARCHAR2(9);
TYPE t_associativearray_row IS TABLE OF mcvetest%ROWTYPE INDEX BY VARCHAR2(9);
```

```
Results :
Tests in error: 
  arrayAsInOutParamTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 3
  arrayAsOutParamTest(org.jooq.mcve.test.java.JavaTest): SQL [{ call "DEVSB"."PROC_USE_ASSOCIATIVEARRAYS"."ARRAY_AS_OUT_PARAM" (?, ?, ?) }]; Ungültiges Namensmuster: DEVSB.TYPES.T_ASSOCIATIVEARRAY
  arrayAsInOutParamRowTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 3
  arrayAsInParamTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 2
  arrayAsOutParamRowTest(org.jooq.mcve.test.java.JavaTest): SQL [{ call "DEVSB"."PROC_USE_ASSOCIATIVEARRAYS"."ARRAY_AS_OUT_PARAM_ROW" (?, ?, ?) }]; Ungültiges Namensmuster: DEVSB.TYPES.T_ASSOCIATIVEARRAY_ROW
  arrayAsInRowParamTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 2
  arrayAsInOutNocopyParamTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 3
Tests run: 7, Failures: 0, Errors: 7, Skipped: 0
```

**Comment by phbreitbach** [comment] 2021-04-17 15:07
@lukaseder Here's the MCVE finally (took me some time to set everything up with proxy and ssh settings)
https://github.com/phbreitbach/jOOQ-mcve
I had to take URL, user and password out of POM and AbstractTest but you can add yours as System Properties in your run configurations:

-Ddb.url=jdbc:oracle:thin:@yourconninfo
-Ddb.username=youruser (best upper case)
-Ddb.password=yourpw

As indicated above, the tests were fine with index PLS_INTEGER but my scenrario has VARCHAR (I switched in between to try something out)
With VARCHAR all tests are failing unfortunately.

Please indicate wether I can be of further help or if there is some Layer 8 problem in my programming ;-)

**Comment by lukaseder** [comment] 2021-04-19 14:51
Thanks a lot for the MCVE and additional feedback. I'll be reviewing this tomorrow

**Comment by lukaseder** [comment] 2021-04-20 15:34
I've been caught up with a related issue, which is now supported in jOOQ 3.15.0 and will be available with the next nightly build 3.15.0-SNAPSHOT: https://github.com/jOOQ/jOOQ/issues/7863

We'll now support `TABLE OF T%ROWTYPE` types - I'll verify if associative arrays of such a type are also supported. Should be doable on Oracle 18c with jOOQ 3.15.0

**Comment by lukaseder** [comment] 2021-06-24 12:28
I'm afraid this doesn't fit jOOQ 3.15.0 anymore. A variety of larger features have been promised to customers by Q2 2021 (e.g. EXASOL support). Associative arrays are too complex to rush into 3.15.0.

I'll increase priorities for 3.16.0

**Comment by phbreitbach** [comment] 2021-07-19 17:54
Hi @lukaseder , sry for long time no comment! I had to trigger reordering of jOOQ support and since then due to changed personal priorities couldn't yet follow up here. I'm glad to here you're still on it and aim to give this priority for 3.16 - you got a rough schedule for 3.16? Meanwhile, I will try to find the time to retest the MCVE against the current jOOQ version ... Is there any further help on my/our side appreciated? Best regards, Philipp

**Comment by lukaseder** [comment] 2021-07-22 10:29
Thanks a lot for your message and for your ping - I apologise for the delay. Releasing 3.15.0 and 3.15.1 took more effort than I thought. I can reproduce the problem with your MCVE getting these errors:

```
Tests in error:
  arrayAsInOutParamTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 3
  arrayAsOutParamTest(org.jooq.mcve.test.java.JavaTest): SQL [{ call "MCVE"."PROC_USE_ASSOCIATIVEARRAYS"."ARRAY_AS_OUT_PARAM" (?, ?, ?) }]; Ungültiges Namensmuster: MCVE.TYPES.T_ASSOCIATIVEARRAY
  arrayAsInOutParamRowTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 3
  arrayAsInParamTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 2
  arrayAsOutParamRowTest(org.jooq.mcve.test.java.JavaTest): SQL [{ call "MCVE"."PROC_USE_ASSOCIATIVEARRAYS"."ARRAY_AS_OUT_PARAM_ROW" (?, ?, ?) }]; Ungültiges Namensmuster: MCVE.TYPES.T_ASSOCIATIVEARRAY_ROW
  arrayAsInRowParamTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 2
  arrayAsInOutNocopyParamTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 3

Tests run: 7, Failures: 0, Errors: 7, Skipped: 0
```

Will investigate right away

**Comment by lukaseder** [comment] 2021-07-22 11:11
So, the way I see this, we're not any further:

- Some things may have worked by accident (though I can't seem to see which ones)
- Others don't (e.g. passing an associative array as an `IN` parameter)

I don't know how to instantiate an associative array using ojdbc, because the driver doesn't seem to recognise the name. So, we can't easily create an `IN` parameter nor register an `OUT` parameter.

I think we can close this issue here. Associative arrays are not yet supported (see https://github.com/jOOQ/jOOQ/issues/5620). Though I do think it would be a very valuable addition to jOOQ, hopefully jOOQ 3.16 (I can't make promises, I'm afraid).

Closing as a duplicate of https://github.com/jOOQ/jOOQ/issues/5620

**Closed by lukaseder** 2021-07-22 11:11 UTC
Labels: C: DB: Oracle, C: Functionality, E: Enterprise Edition, E: Professional Edition, P: High, T: Defect

**Comment by lukaseder** [comment] 2021-07-22 14:11
For the record, I think it can be done with the emulation I've mentioned. I'll experiment with a draft implementation for 3.16.0-SNAPSHOT tomorrow. I've updated the documentaiton of https://github.com/jOOQ/jOOQ/issues/5620.

The improved code generator will capture the key/value pairs in a new type `org.jooq.AssociativeArrayRecord<K, V>`, which extends `java.util.Map<K, V>`. Even if something might have worked by accident so far, it was not possible to correctly retrieve the keys ("indexes") of an associative array, so whatever may have worked was incomplete anyway.

I'm really hoping this can be pulled off. It would be a very useful feature to add to jOOQ! Once done, I'll validate if the updated version will pass your tests from your MCVE. I'll ping you as soon as that is ready.

**Comment by phbreitbach** [comment] 2021-07-22 20:21
That sounds great! I'm watching #5620 now so I can pickup any news from there. Thx a lot for your help!
