### ISSUE TITLE
INSERT .. ON DUPLICATE KEY { IGNORE | UPDATE } emulation should consider all UNIQUE keys

### ISSUE THREAD

**Issue by Sonnbc** [jOOQ/jOOQ#6462] opened 2017-07-27 05:42 UTC
#1503 adds emulation for INSERT .. ON DUPLICATE KEY IGNORE. However, only the primary key is taken into account so the generated query can still fail on unique key constraints. The correct behavior is to ignore duplicate on both the primary key and unique keys. 

https://github.com/jOOQ/jOOQ/commit/715d0253b7dd95031f511802257c0c79f288a51e#diff-3b67ccdd8dd5dbddb9196ab5f8941901R346

**Comment by lukaseder** [comment] 2017-07-27 13:58
Thank you very much for reporting this. Just to be sure, you mean we should consider unique key constraints *in the absence* of a primary key constraint. Is this correct?

**Comment by Sonnbc** [comment] 2017-07-27 18:49
I think we should consider unique key constraints regardless of whether a primary key exists. This means that this line https://github.com/jOOQ/jOOQ/commit/715d0253b7dd95031f511802257c0c79f288a51e#diff-3b67ccdd8dd5dbddb9196ab5f8941901R346 should be something like this:
```java
.where(matchByPrimaryKeyOrAnyOfUniqueKeys())
```

**Comment by lukaseder** [comment] 2017-07-28 06:51
Hmm, interesting. I've checked MySQL's behaviour:

```sql
CREATE TABLE u (
  a int,-- primary key,
  b int,-- unique,
  c int,
  d int,
  e int,
  
  constraint pk primary key (a, b),
  constraint uk unique (d, e)
);

INSERT INTO u (a, b, c, d, e) VALUES (1, 1, 1, 1, 1) ON DUPLICATE KEY UPDATE c = c + 1;
INSERT INTO u (a, b, c, d, e) VALUES (1, 2, 1, 1, 1) ON DUPLICATE KEY UPDATE c = c + 1;
SELECT * FROM u;
```

And indeed, the result is the following single row:

```
a  b  c  d  e
-------------
1  1  2  1  1
```

So, even if the primary key `pk` wasn't duplicate, the unique key `uk` was, which triggered the update.

Since this clause is MySQL-specific, I suspect that changing it to the expected behaviour in a minor release is acceptable, even if this constitutes an incompatible change in some cases.

**Comment by lukaseder** [comment] 2017-07-28 07:16
Hmm, this will lead to interesting performance characteristics as the top-level predicate that is generated in such a `MERGE` or `INSERT .. SELECT .. WHERE NOT EXISTS` statement will be an `OR` predicate, comparing "apples and oranges". Some databases are known to poorly optimise such predicates, meaning that what can currently be done through an index unique scan might produce a full table scan.

Oracle, as an example, will use a still efficient bitmap conversion for the example shown here, but if there are many unique keys, it might also decide to prefer the FTS.

PostgreSQL has the `ON CONFLICT` clause, where key columns can be provided to disambiguate the key that should be considered for the conflict. I'd personally prefer that approach, but it is currently not emulated by jOOQ for other databases.

I prefer to wait with such a change and think about this more thoroughly. Would you mind describing a real-world use-case where the current behaviour bothers you?

**Comment by Sonnbc** [comment] 2017-07-28 20:54
Thanks for investigating this. 

In production, we use MySQL but for unit testing we use H2 as an in-memory DB since it's much faster. The difference in behavior for H2 causes the tests to fail even though the code is correct (when running with MySQL).

**Comment by lukaseder** [comment] 2017-07-31 13:40
Thanks for your explanation. I'm afraid, this won't be easy to fix right now. A workaround would be, of course, to switch on the dialect and generate vendor-specific SQL manually.

I really recommend integration testing against MySQL, though. The speed can be quite acceptable when using Docker and in-memory disks, for instance.

**Comment by blindbox** [comment] 2017-09-07 02:01
I'd like to mention that I'm experiencing this exact issue on Postgres 9.5 as well.

The `ON CONFLICT (<fields>) DO UPDATE` part of the SQL that was produced only has the primary key for fields i.e. it has `id`, but the unique key `user_id` is ignored, hence failing the query when duplicate `user_id` exists.

**Comment by lukaseder** [comment] 2017-09-07 05:58
@blindbox In PostgreSQL, you can use jOOQ's native `ON CONFLICT`  clause directly

**Comment by blindbox** [comment] 2017-09-19 06:26
How do you use the `ON CONFLICT` clause with Records? I know that there's `addValuesForUpdate`.

i.e. (in scala syntax to make it simpler)
```scala
val qb = DSL.using(SQLDialect.POSTGRES_9_5)
val userRecordInsert = new UsersRecord()
userRecordInsert.setEmail("exampleInsert@example.com")
val userRecordUpdate = userRecordInsert.copy()
userRecordUpdate.setEmail("exampleUpdate@example.com") 
val insertQuery = qb.insertQuery(Tables.USERS)
insertQuery.addRecord(userRecordInsert)
insertQuery.onConflict(Tables.USERS.EMAIL)
insertQuery.addRecordForUpdate(userRecordUpdate) // there's no method like this
```

**Comment by lukaseder** [comment] 2017-09-19 08:20
@blindbox Use `addValuesForUpdate(Map)`. The lack of an `addRecordForUpdate()` method is an API design oversight, which should be fixed, soon: https://github.com/jOOQ/jOOQ/issues/6587

If you're using the DSL API rather than the model API, you would have the desired method available:

```java
qb.insertInto(USERS)
  .set(userRecordInsert)
  .onConflict(USERS.EMAIL)
  .doUpdate()
  .set(userRecordUpdate)
  .execute();
```

**Comment by blindbox** [comment] 2017-09-19 09:47
Works perfectly, thanks!

**Comment by vojtapol** [comment] 2018-03-15 15:58
I am also using MySQL in production and H2 for testing so I need `.onDuplicateKeyIgnore()` to work the same way in both MySQL and H2.

Is there any workaround that would work identically for both of these databases? I tried `.onConflictDoNothing` but that seems to be supported only by Postgres.

**Comment by lukaseder** [comment] 2018-03-15 16:04
> I am also using MySQL in production and H2 for testing so I need .onDuplicateKeyIgnore() to work the same way in both MySQL and H2.

Yeah, use MySQL for testing as well (e.g. using Docker) :-)

Sorry, there's no workaround right now.

**Comment by vojtapol** [comment] 2018-03-15 16:07
If I changed the offending unique keys into composite primary keys, would it work with `.onDuplicateKeyIgnore()` on H2?

**Comment by lukaseder** [comment] 2018-03-15 16:56
I'm sorry, I currently cannot give such a guarantee.

**Comment by lukaseder** [comment] 2018-04-10 16:00
A similar issue was rather straightforward to implement, the emulation of PostgreSQL's `ON CONFLICT` clause through SQL standard merge: #7365 and #7409.

I'm positive that we can implement this emulation fix here as well. For backwards-compatibility reasons, we'll add a `Settings` to turn off this emulation change. I'm not sure about the default yet. The emulation will need to run an `OR` predicate on all the keys, which might in the best case lead to `BITMAP OR CONVERSION` operations in the execution plans (reading from all the relevant indexes), and in the worst case to a `FULL TABLE SCAN`

**Comment by lukaseder** [comment] 2018-04-13 08:42
This works quite well in integration tests. For H2, we recommend using `SET MODE MYSQL`

**Closed by lukaseder** 2018-04-13 08:42 UTC
Labels: C: Functionality, P: Medium, T: Defect, T: Incompatible change

**Comment by lukaseder** [comment] 2018-06-07 11:39
N.B: This has been fixed for all databases supporting `MERGE`. In PostgreSQL, which emulates `ON DUPLICATE KEY UPDATE` using `ON CONFLICT DO UPDATE`, it's not easy to get MySQL's behaviour. A separate issue has been created: #7552
