### ISSUE TITLE
BigQuery table creation with jOOQ does not include dataset

### ISSUE THREAD

**Issue by zineddine6** [jOOQ/jOOQ#17035] opened 2024-08-07 18:12 UTC
### Expected behavior

When I create a table on BigQuery I expect the generated SQL to be: `create table dataset.my_table ...`

### Actual behavior

Instead, I have this: `create table my_table ...`

### Steps to reproduce the problem

`DSLContext dslContext = DSL.using(SQLDialect.BIGQUERY);`
`dslContext.createTable(DSL.table(DSL.name("dataset", "my_table"))).getSQL();`

The returned SQL is: `create table my_table`

And this creates an error on BigQuery: `Table "my_table" must be qualified with a dataset (e.g. dataset.table).`

### jOOQ Version

Entreprise edition 3.20-SNAPSHOT

### Database product and version

Latest BigQuery

### Java Version

openJDK 17.0.8.1 2023-08-24

**Comment by lukaseder** [comment] 2024-08-08 07:21
Thanks for your report. This appears to be a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/16874

As a workaround, can you set the data set on your JDBC connection using `DefaultDataset=...`?

**Closed by lukaseder** 2024-08-08 07:21 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: Enterprise Edition, C: DB: BigQuery

**Comment by lukaseder** [comment] 2024-08-08 07:22
Another alternative would be to use a plain SQL template, instead of `DSL.name()`, e.g. `DSL.table("dataset.table")`
