### ISSUE TITLE
Incorrectly generated sqlite query?

### ISSUE THREAD

**Issue by asm0dey** [jOOQ/jOOQ#15543] opened 2023-09-02 16:56 UTC
### Expected behavior

Given the following function

```kotlin
private fun updateSequenceIds(txConfig: Configuration) {
    val tr = using(txConfig)
    val names = selectDistinct(BOOK.SEQUENCE)
        .from(BOOK)
        .where(BOOK.SEQUENCE.isNotNull)
        .orderBy(BOOK.SEQUENCE)
    val numbers = select(rowNumber().over(), names.field(0, String::class.java))
        .from(names)
    tr.update(BOOK)
        .set(BOOK.SEQID, numbers.field(0, Int::class.javaObjectType))
        .from(numbers)
        .where(BOOK.SEQUENCE.eq(numbers.field(1, String::class.java)))
        .execute()
}
```

I would expect it to compile to something like 

```sql
UPDATE book
SET seqid=numbers.seqrow
FROM (SELECT ROW_NUMBER() OVER () seqrow, seqname
      FROM (SELECT DISTINCT(sequence) seqname FROM book WHERE book.sequence IS NOT NULL ORDER BY sequence)) AS numbers
WHERE book.sequence = numbers.seqname;
```

The important part is `SET seqid=numbers.seqrow`

### Actual behavior

```
2023-09-02 18:30:41 [Scanner] io.github.asm0dey.ApplicationKt.scan$lambda$13(ApplicationKt:257)  ERROR: Error while updating sequence ids: org.jooq.exception.DataAccessException: SQL [update book set seqid = alias_86520149.
row_number from (select row_number() over (), alias_27893941.sequence from (select distinct book.sequence from book where book.sequence is not null order by book.sequence) as alias_27893941) as alias_86520149 where book.seq
uence = ?]; [SQLITE_ERROR] SQL error or missing database (no such column: alias_86520149.row_number)
        at org.jooq_3.18.4.SQLITE.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:3470)
        at org.jooq.impl.Tools.translate(Tools.java:3458)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:772)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:371)
        at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
        at io.github.asm0dey.ApplicationKt.updateSequenceIds(Application.kt:332)
        at io.github.asm0dey.ApplicationKt.scan$lambda$13(Application.kt:255)
        at org.jooq.impl.DefaultDSLContext.lambda$transaction$5(DefaultDSLContext.java:593)
        at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:531)
        at org.jooq.impl.Tools$3$1.block(Tools.java:6057)
        at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
        at org.jooq.impl.Tools$3.get(Tools.java:6054)
        at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:579)
        at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:503)
        at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:592)
        at io.github.asm0dey.ApplicationKt.scan(Application.kt:226)
        at io.github.asm0dey.plugins.RoutingKt$routes$1$1$1.invoke(Routing.kt:57)
        at io.github.asm0dey.plugins.RoutingKt$routes$1$1$1.invoke(Routing.kt:50)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: alias_86520149.row_number)
        at org.sqlite.core.DB.newSQLException(DB.java:1179)
        at org.sqlite.core.DB.newSQLException(DB.java:1190)
        at org.sqlite.core.DB.throwex(DB.java:1150)
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:126)
        at org.sqlite.core.DB.prepare(DB.java:264)
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:227)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:207)
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327)
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
        at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:109)
        at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:82)
        at org.jooq.impl.AbstractQuery.prepare(AbstractQuery.java:420)
        at org.jooq.impl.AbstractDMLQuery.prepare0(AbstractDMLQuery.java:924)
        at org.jooq.impl.AbstractDMLQuery.prepare(AbstractDMLQuery.java:915)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:324)
        ... 16 more
```

### Steps to reproduce the problem

DDL:
```
create table author
(
    id          INTEGER
        primary key autoincrement,
    fb2id       TEXT,
    first_name  TEXT,
    middle_name TEXT,
    last_name   TEXT,
    nickname    TEXT,
    added       TEXT not null
);

create index author_added
    on author (added);

create index author_names
    on author (middle_name, last_name, first_name, nickname);

CREATE TRIGGER tbl_ad
    AFTER DELETE
    ON main.author
BEGIN
    INSERT INTO authors_fts(authors_fts, rowid, nickname, middle_name, last_name, first_name)
    VALUES ('delete', old.id, old.nickname, old.middle_name, old.last_name, old.first_name);
END;

CREATE TRIGGER tbl_ai
    AFTER INSERT
    ON main.author
BEGIN
    INSERT INTO authors_fts(rowid, nickname, middle_name, last_name, first_name)
    VALUES (new.id, new.nickname, new.middle_name, new.last_name, new.first_name);
END;

CREATE TRIGGER tbl_au
    AFTER UPDATE
    ON main.author
BEGIN
    INSERT INTO authors_fts(authors_fts, rowid, nickname, middle_name, last_name, first_name)
    VALUES ('delete', old.id, old.nickname, old.middle_name, old.last_name, old.first_name);
    INSERT INTO authors_fts(rowid, nickname, middle_name, last_name, first_name)
    VALUES (new.id, new.nickname, new.middle_name, new.last_name, new.first_name);
END;

create table authors_fts_config
(
    k not null
        primary key,
    v
)
    without rowid;

create table authors_fts_data
(
    id    INTEGER
        primary key,
    block BLOB
);

create table authors_fts_docsize
(
    id INTEGER
        primary key,
    sz BLOB
);

create table authors_fts_idx
(
    segid not null,
    term  not null,
    pgno,
    primary key (segid, term)
)
    without rowid;

create table book
(
    id              INTEGER
        primary key autoincrement,
    path            TEXT                           not null,
    name            TEXT                           not null,
    date            TEXT,
    added           TEXT default CURRENT_TIMESTAMP not null,
    sequence        TEXT,
    sequence_number INTEGER,
    lang            TEXT,
    zip_file        TEXT,
    seqid           INT
);

create index book_added
    on book (added);

create unique index book_path_name
    on book (path, "COALESCE(zip_file, '')", name);

create index book_seq
    on book (sequence)
    where sequence IS NOT NULL AND TRIM(sequence) <> '';

create index book_sequence_index
    on book (sequence);

create unique index fully_unique_path
    on book (path, "COALESCE(zip_file, '')");

CREATE TRIGGER tbl_bd_2
    AFTER DELETE
    ON book
BEGIN
    INSERT INTO books_fts(books_fts, rowid, name, sequence) VALUES ('delete', old.id, old.name, old.sequence);
END;

CREATE TRIGGER tbl_bi_2
    AFTER INSERT
    ON book
BEGIN
    INSERT INTO books_fts(rowid, name, sequence) VALUES (new.id, new.name, new.sequence);
END;

CREATE TRIGGER tbl_bu_2
    AFTER UPDATE
    ON book
BEGIN
    INSERT INTO books_fts(books_fts, rowid, name, sequence) VALUES ('delete', old.id, old.name, old.sequence);
    INSERT INTO books_fts(rowid, name, sequence) VALUES (new.id, new.name, new.sequence);
END;

create table book_author
(
    book_id   INTEGER not null
        references book
            on update restrict on delete cascade,
    author_id INTEGER not null
        references author
            on update restrict on delete cascade,
    constraint pk_book_author
        primary key (book_id, author_id)
);

create index book_author_author_id
    on book_author (author_id);

create index book_author_book_id
    on book_author (book_id);

create table books_fts_config
(
    k not null
        primary key,
    v
)
    without rowid;

create table books_fts_data
(
    id    INTEGER
        primary key,
    block BLOB
);

create table books_fts_docsize
(
    id INTEGER
        primary key,
    sz BLOB
);

create table books_fts_idx
(
    segid not null,
    term  not null,
    pgno,
    primary key (segid, term)
)
    without rowid;

create table genre
(
    id   INTEGER
        primary key autoincrement,
    name TEXT not null
        unique
);

create table book_genre
(
    book_id  INTEGER not null
        references book
            on delete cascade,
    genre_id INTEGER not null
        references genre
            on delete cascade,
    constraint pk_book_genre
        primary key (book_id, genre_id)
);

create index book_genre_book_id
    on book_genre (book_id);

create index book_genre_genre_id
    on book_genre (genre_id);

create unique index genre_name
    on genre (name);

create virtual table authors_fts using fts5
(
    last_name,
    first_name,
    middle_name,
    nickname,
    content=
    author,
    content_rowid=
    id,
    tokenize="trigram"
);

create virtual table books_fts using fts5
(
    name,
    sequence,
    content=book,
    content_rowid=id,
    tokenize="trigram"
);
```

### jOOQ Version

3.18.6

### Database product and version

SQLIte

### Java Version

OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

### JDBC driver name and version (include name if unofficial driver)

org.xerial:sqlite-jdbc:3.42.0.1

**Comment by asm0dey** [comment] 2023-09-02 17:06
Giving aliases to everything is a workaround

```kotlin
private fun updateSequenceIds(txConfig: Configuration) {
    val tr = using(txConfig)
    val names = selectDistinct(BOOK.SEQUENCE.`as`("seqname"))
        .from(BOOK)
        .where(BOOK.SEQUENCE.isNotNull)
        .orderBy(BOOK.SEQUENCE)
        .asTable("names")
    val numbers = select(rowNumber().over().`as`("seqrow"), names.field("seqname")!!.`as`("seqname"))
        .from(names)
        .asTable("numbers")
    tr.update(BOOK)
        .set(BOOK.SEQID, numbers.field("seqrow", Int::class.javaObjectType))
        .from(numbers)
        .where(BOOK.SEQUENCE.eq(numbers.field("seqname", String::class.java)))
        .execute()
}
```

**Comment by lukaseder** [comment] 2023-09-04 06:57
Thanks for your report. This seems to be just another case of:

- https://github.com/jOOQ/jOOQ/issues/579

The question whether columns from subqueries (specifically derived tables) should be auto-aliased isn't a simple one to answer. Currently, queries will depend on vendor specific behaviour. E.g. some RDBMS may generate aliases like `C1`, `C2`, `C3` for such columns. Others may generate only so-called titles (the name of the projected column in the top level select), but not formal aliases for those columns. Others don't generate anything at all.

We can't change this easily without breaking user code, which is based on an assumption around RDBMS specific behaviour.

In any case, your "workaround" isn't just a workaround, it's the recommended way to do this kind of thing in SQL. Though I agree, your original query doesn't look wrong from the jOOQ side, and if #579 is ever possible, we might fix this for all subqueries.

Closing this as a duplicate of #579

**Closed by lukaseder** 2023-09-04 06:57 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
