### ISSUE TITLE
jOOQ-codegen-maven

### ISSUE THREAD

**Issue by sytolk** [jOOQ/jOOQ#5138] opened 2016-03-08 08:14 UTC
I use maven code generation plugin in Android project and I want to generate from DB tables structure java POJO`s only. I have this config but its have "routines" and "tables" classes generated too. Its need to delete it every time I have run maven build. Can we have preference like "pojosOnly" that generate only pojos?
```xml
<generate>
                                  <!-- Primary key / foreign key relations should be generated and used.
                                        This is a prerequisite for various advanced features.
                                        Defaults to false -->

                                    <relations>true</relations>
                                    <navigationMethods>false</navigationMethods>
                                    <deprecated>false</deprecated>
                                    <instanceFields>true</instanceFields>
                                    <generatedAnnotation>false</generatedAnnotation>
                                    <records>false</records>
                                    <pojos>true</pojos>
                                    <immutablePojos>false</immutablePojos>
                                    <interfaces>false</interfaces>
                                    <daos>false</daos>
                                    <jpaAnnotations>false</jpaAnnotations>
                                    <validationAnnotations>false</validationAnnotations>
                                </generate>
```

**Comment by lukaseder** [comment] 2016-03-08 16:02
Indeed, this would be very nice to have. I'm closing this as a duplicate of the existing #3482

**Closed by lukaseder** 2016-03-08 16:02 UTC
Labels: C: Code Generation, P: Medium, R: Duplicate, T: Enhancement
