### ISSUE TITLE
ClassCastException when calling PostgreSQL table valued functions returning enum types, when <instanceFields/> is false

### ISSUE THREAD

**Issue by ooz-rm** [jOOQ/jOOQ#6502] opened 2017-08-18 14:07 UTC
Hi Lukas,
I have the following situation that is causing a ClassCastException on an Enumeration when accessing the value of a record. This is happening on PostgreSQL 9.4 with jdbc driver 42.1.3 and JOOQ 3.9.4 on Java 8.

SQL:
```sql
CREATE TYPE nhc.answer_type_enum AS ENUM ('text', 'number', 'bool', 'options');

CREATE OR REPLACE FUNCTION nhc.get_poll_statistics_test()
RETURNS TABLE("answer_type" nhc.answer_type_enum) AS $$
	select 'options'::nhc.answer_type_enum;
$$ LANGUAGE SQL;
```
Java:
```java
final SelectWhereStep<GetPollStatisticsTestRecord> query = dslCtx.selectFrom(Routines.getPollStatisticsTest());
final Result<GetPollStatisticsTestRecord> result = query.fetch();
final Iterator<GetPollStatisticsTestRecord> iterator = result.iterator();
while (iterator.hasNext())
{
    final GetPollStatisticsTestRecord record = iterator.next();
    final AnswerTypeEnum answerType = record.getAnswerType();
}
```
Exception when retrieving the answerType from the record:
```
Caused by: java.lang.ClassCastException: org.postgresql.util.PGobject cannot be cast to net.oneoverzero.nhc.db.enums.AnswerTypeEnum
     [exec] 	at net.oneoverzero.nhc.db.tables.records.GetPollStatisticsTestRecord.getAnswerType(GetPollStatisticsTestRecord.java:44) [NHC.jar:]
```

I found out that with the jdbc driver postgresql-9.4-1201.jdbc41.jar this is working correctly, but from the driver postgresql-9.4.1202.jar and up it is not working.

What could be the problem?
Thank you in advance,
Best Regards
Roberto Morelli

**Comment by lukaseder** [comment] 2017-08-22 10:25
Interesting, thanks for your detailed report. Looks like a bug. Somewhere in the deserialisation chain, the enum is not correctly recognised / deserialised.

Will look into this ASAP

**Comment by lukaseder** [comment] 2017-08-29 09:21
Hmm, I have tried to reproduce this with this driver version:

```xml
<dependency>
    <groupId>org.postgresql</groupId>
    <artifactId>postgresql</artifactId>
    <version>9.4.1212</version>
</dependency>
```

This is the latest version in that stream, although, do note that there are even newer versions with the version scheme 42.1.4:
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.postgresql%22%20AND%20a%3A%22postgresql%22

Perhaps this was simply a regression in your driver version. Here are the full JDBC driver release notes:
https://jdbc.postgresql.org/documentation/changelog.html

I'm closing this as worksforme. Feel free to reopen if you find that newer versions of the driver also expose this problem with jOOQ.

**Comment by ciaccia** [comment] 2017-11-17 13:24
Hallo Lukas,
This issue is not a PostgresSQL driver regression, it is  still reproducible with latest driver 42.1.4. I created a mini demo to reproduce it (you can download it [here](https://www.dropbox.com/s/ern6idg3tqykj52/jooq-6502.zip?dl=0)). To start the demo you just have to replace the DB connection URL,username and password in file `org.jooq.JooqBug`.

Please let me know whether you can reproduce the issue or not.

**Comment by lukaseder** [comment] 2017-11-20 11:15
Thanks a lot for the nice test case. I can now reproduce this issue, if it's the same as the one originally reported. Will look into this ASAP

**Comment by lukaseder** [comment] 2017-11-20 11:24
Oh, I see now. The issue seems to be related to the (deprecated) `<instanceFields>false</instanceFields>` configuration. When I remove that from the code generator configuration, it works again. Can you both confirm this, @robertomorelli and @ciaccia ?

This can certainly be fixed, but what is the motivation of using this flag at your side?

**Comment by ciaccia** [comment] 2017-11-20 12:55
Hi Lukas,
This is due to a copy-paste FAIL, sorry... Months age we had one application where the flag was set to `false`, then I changed to `true` in order to fix some problems I was experiencing. I forgot to update it everywhere, so another XML configuration file kept the old (wrong) value.

Just another issue I noticed with the flag set to `false`. If you create a PG-function which accepts a list of enums a parameter, you cannot invoke it from jOOQ. For example:

    CREATE OR REPLACE FUNCTION sre.enum_array_fn(p_enums sre.jooq_type[])

I haven' tested it yet, but it probably gets fixed with the new `instanceFields` value.

Thanks a lot for your help

**Comment by lukaseder** [comment] 2017-11-20 13:03
Thanks for the reply. Indeed, I think that the type information is lost "both ways", i.e. both when passing arguments as well as when returning results.

If you don't really use this flag anymore, I'd like to prefer to wait with a fix here, until others also need this - given that the flag is deprecated anyway...

**Comment by ciaccia** [comment] 2017-11-20 14:14
Hi Lukas,
The issue with the returning enums is fixed, so I'm fine. Besides this, there is still an issue when the function takes an array of enums (as above). With the flag set to `true` works fine, as long the parameter is not `null`... When the parameter is `null`, an exception is thrown. Maybe this deserves a fix.

**Comment by lukaseder** [comment] 2017-11-20 14:25
Oh, I see, thanks for the update, @ciaccia. Would you mind reporting a separate issue for that? Since it doesn't depend on the flag, it doesn't seem strictly related.

**Comment by ciaccia** [comment] 2017-11-20 14:53
Hi Lukas, I have created Issue #6824

**Comment by lukaseder** [comment] 2020-07-17 14:17
`instanceFields` is deprecated functionality. In order to be able to decrease complexity in the future, we will eventually remove it, and recommend not using it when such edge cases are encountered.

**Closed by lukaseder** 2020-07-17 14:17 UTC
Labels: C: Code Generation, C: DB: PostgreSQL, E: All Editions, P: Medium, R: Wontfix, T: Defect
