### ISSUE TITLE
LocalDateTime param handled differently in hibernate query

### ISSUE THREAD

**Issue by cdalexndr** [jOOQ/jOOQ#11753] opened 2021-04-04 12:08 UTC
### Expected behavior
Same behavior as in hibernate.

### Actual behavior
In jooq `LocalDateTime` param is passed as-is to db.
In hibernate, the `LocalDateTime` is transformed from current time zone to utc, then passed to db:

LocalDateTime is transformed to Timestamp containing `TimeZone.getDefaultRef()` timezone
https://github.com/hibernate/hibernate-orm/blob/ad84aaf0bcb161b272731c82742018ad3445742b/hibernate-core/src/main/java/org/hibernate/type/descriptor/java/LocalDateTimeJavaDescriptor.java#L57-L65
,is used to transform to UTC before sending to db:
https://github.com/pgjdbc/pgjdbc/blob/187333e4a7c163b80efa8cca5a26dfea9a356f53/pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java#L1363

Jooq query is not compatible with hibernate native query. 
Trying to convert a jooq query into a jpa native query results in a different query (only works with UTC timezone).

### Steps to reproduce the problem

Not using UTC timezone.
Create jooq query with `LocalDateTime` param.
Create jpa native query from the jooq query, and set parameters directly from jooq query.
Executing the above two queries give two different results.
(Note that I use JOOQ to generate jpa native queries.)

### Versions

- jOOQ: 3.13.4
- Java: 11
- Database (include vendor): Postgres 12
- OS: Win 10
- JDBC Driver (include name if inofficial driver): `org.postgresql:postgresql:42.2.15`

**Comment by cdalexndr** [comment] 2021-04-04 12:09
Note that code generator generates `LocalDateTime` fileds for `timestamp without timezone` columns, that inherit this problem.

**Comment by cdalexndr** [comment] 2021-04-04 12:24
Related https://github.com/jOOQ/jOOQ/issues/5539

**Comment by lukaseder** [comment] 2021-04-05 08:47
Thanks a lot for your message

> Steps to reproduce the problem

It is difficult to be *sure* of what you observed to be a possible problem from reproduction steps in prose. Trying to reproduce this by re-creating a simple code example could go wrong in many ways, leading me on a wrong track. For example, the Hibernate source code link doesn't actually do what you described in prose. It just converts using `Timestamp.valueOf(LocalDateTime)`, which is the right thing to do, independently of time zones.

Why not just show some example code to help reproduce *exactly* what you did? We have a handy template for these cases:
https://github.com/jOOQ/jOOQ-mcve

But other means of producing "minimal, complete, verifiable examples" in code are very welcome as well.

**Comment by cdalexndr** [comment] 2021-04-05 08:53
`Timestamp.valueOf(LocalDateTime)` from [javadoc](https://docs.oracle.com/javase/8/docs/api/java/sql/Timestamp.html#valueOf-java.time.LocalDateTime-):
`The provided LocalDateTime is interpreted as the local date-time in the local time zone.`
Under the hood, the created timestamp object stores the timezone from `TimeZone.getDefaultRef()` that may not be UTC.

Will try to provide a sample.

**Comment by lukaseder** [comment] 2021-04-05 08:58
> Under the hood, the created timestamp object stores the timezone from `TimeZone.getDefaultRef()` that may not be UTC.

There is no requirement for a *local* timestamp to be in UTC. The point is, it is a *local* timestamp. For anything JDBC related, `Timestamp` and `LocalDateTime` are semantically the same type and they can be converted between each other.

**Comment by cdalexndr** [comment] 2021-04-05 19:27
Sample code:

```
private static <T> Object convertToDatabaseType( Param<T> param ) {
    return param.getBinding().converter().to( param.getValue() );
}

assert TimeZone.getDefault().getRawOffset() != 0;
LocalDateTime localTime = LocalDateTime.now();

Field<LocalDateTime> lastModCol = DSL.field( "last_update", LocalDateTime.class );
SelectConditionStep<Record1<Integer>> jooqQuery = dsl.selectCount()
        .from( table( name( "product" ) ) )
        .where( lastModCol.lessOrEqual( localTime ) );

int count = jooqQuery
        .fetch().map( Record1::component1 )
        .iterator().next();
//PgPreparedStatement: select count(*) from "product" where last_update <= cast('2021-04-05 18:41:51.284406+03' as timestamp)

int jpaCount = ((Number) entityManager.createNativeQuery( jooqQuery.getSQL() )
        .setParameter( 1, convertToDatabaseType( jooqQuery.getParams().values().iterator().next() ) )
        .getSingleResult()).intValue();
//PgPreparedStatement: select count(*) from "product" where last_update <= cast('2021-04-05 15:41:51.284406+00' as timestamp)
```

Note that `select  cast('2021-04-05 18:41:51.284406+03' as timestamp)` = `"2021-04-05 18:41:51.284406"`. 
Postgres's `timestamp` has no timezone.

It seems that the Timestamp is bind differently in jooq and hibernate.
- In jooq it uses [default calendar](https://github.com/jOOQ/jOOQ/blob/6fa0c352876b915145522948f1d0ecdeabe4c36e/jOOQ/src/main/java/org/jooq/impl/DefaultBinding.java#L4135) (using the java timezne) = differently from UTC in my case
- In hibernate, it uses [Session.getJdbcTimeZone()](https://github.com/hibernate/hibernate-orm/blob/ad84aaf0bcb161b272731c82742018ad3445742b/hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/TimestampTypeDescriptor.java#L53) = is UTC in my case
This, plus casting to timestamp that removes timezone, results in different query results.

**Comment by cdalexndr** [comment] 2021-04-05 19:29
Workarounds:

- jvm arg `-Duser.timezone=UTC` to use UTC as default timezone
- use param type `Instant` instead of `LocalDateTime`

**Comment by lukaseder** [comment] 2021-04-06 12:16
I'm afraid I fail to reproduce your example. I can't seem to get that timestamp literal with time zone on my setup. I created:

```sql
create table product (last_update timestamp);
insert into product values (timestamp '2000-01-01 00:00:00');
```

Then I set the log level to `TRACE` and executed the jOOQ part of your code:

```java
DSLContext dsl = DSL.using(connection);

assert TimeZone.getDefault().getRawOffset() != 0;
LocalDateTime localTime = LocalDateTime.now();

Field<LocalDateTime> lastModCol = DSL.field( "last_update", LocalDateTime.class );
SelectConditionStep<Record1<Integer>> jooqQuery = dsl.selectCount()
        .from( table( name( "product" ) ) )
        .where( lastModCol.lessOrEqual( localTime ) );

int count = jooqQuery
        .fetch().map( Record1::component1 )
        .iterator().next();
```

This produces the following log output:

```
14:08:17,683 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : select count(*) from "product" where last_update <= cast(? as timestamp) -- SQL rendered with a free trial version of jOOQ 3.15.0-SNAPSHOT
14:08:17,683 DEBUG [org.jooq.tools.LoggerListener                     ] - -> with bind values      : select count(*) from "product" where last_update <= timestamp '2021-04-06 14:08:17.33066'
14:08:17,701 TRACE [org.jooq.impl.DefaultBinding                      ] - Binding variable 1       : 2021-04-06T14:08:17.330660 (timestamp /* java.time.LocalDateTime */)
14:08:17,728 TRACE [org.jooq.tools.LoggerListener                     ] - Record fetched           : +-----+
14:08:17,728 TRACE [org.jooq.tools.LoggerListener                     ] -                          : |count|
14:08:17,728 TRACE [org.jooq.tools.LoggerListener                     ] -                          : +-----+
14:08:17,728 TRACE [org.jooq.tools.LoggerListener                     ] -                          : |    1|
14:08:17,728 TRACE [org.jooq.tools.LoggerListener                     ] -                          : +-----+
```

I've tried this with the latest snapshot versions of jOOQ 3.15, 3.14, 3.13. As you can see, there is no trace of a time zone in the literal, not in the bind value nor in the inlined version.

One thing that comes to mind is that you might have a converter on your classpath and due to some design flaw in early jOOQ days, converters have a way of registering themselves statically in an internal type registry. Does the problem still reproduce when you write:

```java
DSL.field( "last_update", SQLDataType.LOCALDATETIME)
```

... instead?

**Comment by cdalexndr** [comment] 2021-04-06 12:53
With `DSL.field( "last_update", SQLDataType.LOCALDATETIME)` the problem still reproduce.

**Comment by cdalexndr** [comment] 2021-04-06 13:00
Also, note that JOOQ shows statement without the timezone, but looking at the `PgPreparedStatement` shows with timezone suffix, also wrapped in `cast(... as timestamp).

- ctx.query: `select count(*) from "product" where last_update <= timestamp '2021-04-06 12:53:40.420982'`
- ctx.statement.deletage.delegate: `select count(*) from "product" where last_update <= cast('2021-04-06 12:53:40.420982+03' as timestamp)`

**Comment by lukaseder** [comment] 2021-04-06 14:53
> Did you used postgres jdbc driver?

I did this on PostgreSQL with the offical driver

> Also, note that JOOQ shows statement without the timezone, but looking at the `PgPreparedStatement` shows with timezone suffix, also wrapped in `cast(... as timestamp)`.

I'd like to rewind from what you observed is being done at various places to what is actually the problem here. We're deep down into https://xyproblem.info land, where we're comparing jOOQ and Hibernate behaviour despite your clear indication that you're using jOOQ with your local time zone on the JVM and Hibernate with UTC as their "JDBC time zone". If you just used the local time zone in Hibernate as well, you'd get the same behaviour I guess? I mean, we could introduce such an additional "JDBC time zone" as well to further complicate things in an already complicated topic, but I still haven't understood what you think the problem is. Is this just about a missing feature? (Note, as a workaround, you could create your own data type `Binding` that uses the `setTimestamp(int, Timestamp, Calendar)` method instead of the `setTimestamp(int, Timestamp)` one.

Let's ignore Hibernate for a second. Can you please show a clear example that leads to "wrong" behaviour? Ideally, I'd really like an MCVE (template here: https://github.com/jOOQ/jOOQ-mcve), because then we'll be looking at the *exact same code* rather than going back and forth with some snippets of "hints". E.g. I do not understand what you mean by your additional logs:

> * ctx.query: `select count(*) from "product" where last_update <= timestamp '2021-04-06 12:53:40.420982'`
> * ctx.statement.deletage.delegate: `select count(*) from "product" where last_update <= cast('2021-04-06 12:53:40.420982+03' as timestamp)`
> 
> This should be another bug :)

How did you create those logs? How can I reproduce them? Why do you think this is *another* bug? I'm more confused now than before. But again, rather than answering that, why not create an MCVE with a very simple and obvious test case that fails and can easily be reproduced on my side?

Because I'm not seeing a bug so far. Here's an illustration of something I've been doing over the past day:

```java
try (PreparedStatement s = connection.prepareStatement("select ?, ?, ? = ?")) {
    s.setTimestamp(1, Timestamp.valueOf("2000-01-01 15:30:45"));
    s.setObject(2, Timestamp.valueOf("2000-01-01 15:30:45").toLocalDateTime());
    s.setTimestamp(3, Timestamp.valueOf("2000-01-01 15:30:45"));
    s.setObject(4, Timestamp.valueOf("2000-01-01 15:30:45").toLocalDateTime());

    try (ResultSet rs = s.executeQuery()) {
        while (rs.next()) {
            System.out.println(rs.getTimestamp(1));
            System.out.println(rs.getTimestamp(2));
            System.out.println(rs.getObject(2, LocalDateTime.class));
            System.out.println(rs.getBoolean(3));
        }
    }
}
```

This works for me. It produces:

```
2000-01-01 15:30:45.0
2000-01-01 15:30:45.0
2000-01-01T15:30:45
true
```

So, `Timestamp` and `LocalDateTime` do seem to behave the same way in the pgjdbc driver. "But is that not what @cdalexndr meant? What *did* he mean?"

Yes, I can see that `PgPreparedStatement` makes use of `connection.getTimestampUtils().toString(cal, t)` and thus of the local time zone as I would have expected, but *why* is it a problem for you?

I'm going to close this as "works for me". Perhaps I'm overlooking something (that would be more obvious in an MCVE), but so far, I really don't understand what this issue seems to be about.

**Closed by lukaseder** 2021-04-06 14:53 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Feedback Pending, T: Defect

**Comment by cdalexndr** [comment] 2021-04-07 13:28
Heres a mcve with two failing tests: https://github.com/cdalexndr/jOOQ-11753

1. Storing an `Instant` into a `timestamp without timezone` db column fails
2. Binding `LocalDateTime` to query results in timestamp timezone removed (ex: `cast('2021-04-06 12:53:40.420982+03' as timestamp)`)

**Comment by lukaseder** [comment] 2021-04-07 14:18
Thanks for the MCVE. That's helpful to be sure I'm seeing what you're seeing. But I can only repeat this: You're trying to store a value that is timestamp specific (`Instant` or `OffsetDateTime`) in a column of a type that is not (`TIMESTAMP`).

### Regarding 1 `testInsertInstantTimestampWithoutTz`

Look at this JDBC snippet that runs on your schema:

```java
ctx.connection(c -> {
    try (PreparedStatement s1 = c.prepareStatement("insert into test (update) values (?) returning id");
         PreparedStatement s2 = c.prepareStatement("select update from test where id = ?")) {

        s1.setTimestamp(1, Timestamp.valueOf("2000-01-01 00:00:00"));

        try (ResultSet rs1 = s1.executeQuery()) {
            while (rs1.next()) {
                s2.setInt(1, rs1.getInt(1));

                try (ResultSet rs2 = s2.executeQuery()) {
                    while (rs2.next()) {
                        System.out.println(rs2.getTimestamp(1));
                    }
                }
            }
        }
    }
});
ctx.connection(c -> {
    try (PreparedStatement s1 = c.prepareStatement("insert into test (update) values (?) returning id");
         PreparedStatement s2 = c.prepareStatement("select update from test where id = ?")) {

        s1.setObject(1, LocalDateTime.parse("2000-01-01T00:00:00"));

        try (ResultSet rs1 = s1.executeQuery()) {
            while (rs1.next()) {
                s2.setInt(1, rs1.getInt(1));

                try (ResultSet rs2 = s2.executeQuery()) {
                    while (rs2.next()) {
                        System.out.println(rs2.getTimestamp(1));
                        System.out.println(rs2.getObject(1, LocalDateTime.class));
                    }
                }
            }
        }
    }
});
ctx.connection(c -> {
    try (PreparedStatement s1 = c.prepareStatement("insert into test (update) values (?) returning id");
         PreparedStatement s2 = c.prepareStatement("select update from test where id = ?")) {

        s1.setObject(1, OffsetDateTime.parse("2000-01-01T00:00:00Z"));

        try (ResultSet rs1 = s1.executeQuery()) {
            while (rs1.next()) {
                s2.setInt(1, rs1.getInt(1));

                try (ResultSet rs2 = s2.executeQuery()) {
                    while (rs2.next()) {
                        System.out.println(rs2.getTimestamp(1));
                        System.out.println(rs2.getObject(1, OffsetDateTime.class));
                    }
                }
            }
        }
    }
});
```

On my machine (currently in CEST), this prints:

```
2000-01-01 00:00:00.0
2000-01-01 00:00:00.0
2000-01-01T00:00
2000-01-01 01:00:00.0
2000-01-01T01:00Z
```

No jOOQ involved!

The first three (`Timestamp` / `LocalDateTime`) are equivalent and correct. The input gets echoed back as expected. But the third is simply wrong. I cannot store a value with timestamp information in a column that will lose the information, and expect to maintain the information when I fetch it again. I'm storing `2000-01-01T00:00:00Z`, which gets converted to `2000-01-01T01:00:00+01`. This is still the same timestamp value, but it's in a different time zone. But if you think you can fetch that value again in an `OffsetDateTime` (or `Instant`), you might get the wrong timestamp!

Again, as you can see, no jOOQ is involved here, only JDBC. You could try your luck and report this to pgjdbc, but then again, why use the wrong data types in the first place and expect the conversion to work?

### Regarding 2 `testBindTimestampWithTimezone`

On my machine, your test prints (again, because I'm in CEST):

```
PgPreparedStatement: select count(*) from "mcve"."test" where "mcve"."test"."update" < cast('2021-04-07 16:08:00.06385+02' as timestamp(6))
```

The pgjdbc driver sends the JDBC `Timestamp` value as a formatted string with the local time zone. I don't see why that's wrong. On my machine, that's the correct timestamp, and it seems to me that this is the correct behaviour here, as I've shown before.

### Conclusion

I really think you're just misunderstanding things here.

- Use `java.sql.Timestamp` or `java.time.LocalDateTime` for PostgreSQL `TIMESTAMP WITHOUT TIME ZONE`
- Use `java.time.OffsetDateTime` or `java.time.Instant` for PostgreSQL `TIMESTAMP WITH TIME ZONE`

This is how the JDBC spec defines things (apart from `Instant`, which is a jOOQ extension)

The code generator already generates things correctly. The generated `TEST.UPDATE` column is of type `Field<LocalDateTime>`. You can't just pretend you can store `INSTANT` there, and why would you? If you want to use `INSTANT` types, then please use a `TIMESTAMP WITH TIME ZONE` in PostgreSQL, because those are the matching types.

**Comment by cdalexndr** [comment] 2021-04-07 14:33
> The pgjdbc driver sends the JDBC Timestamp value as a formatted string with the local time zone. I don't see why that's wrong. On my machine, that's the correct timestamp, and it seems to me that this is the correct behaviour here, as I've shown before.

`select cast('2021-04-07 16:08:00.06385+02' as timestamp(6))` is evaluated to `2021-04-07 16:08:00.06385`, loosing timezone info because of the cast, resulting in different semantic (different date).
The cast is not added by pgjdbc driver, so the problem is with JOOQ doing an invalid cast.

For example, hibernate translates to UTC first (jdbc timezone), so that timezone info is not lost.

**Comment by lukaseder** [comment] 2021-04-07 15:03
This yields `true` on my machine where everything is set to CEST:

```sql
select cast('2021-04-07 16:08:00.06385+02' as timestamp(6)) = timestamp '2021-04-07 16:08:00.06385'
```

> The cast is not added by pgjdbc driver, so the problem is with JOOQ doing an invalid cast.

How can it possibly be invalid.

jOOQ renders `cast(? as timestamp(6))` and binds a JDBC `Timestamp` in the local time zone (no `Calendar`) as pretty much *every* JDBC driver supports, and as I've shown using the JDBC examples is correct. If you want, take my JDBC examples and change the `INSERT` statement to use this, instead:

```java
"insert into test (update) values (cast(? as timestamp)) returning id"
```

Same result.

The topic around casting is discussed in a few other issues. We could avoid the cast in some cases, but I don't want to open that can of worms in this issue here, which is unrelated.

> For example, hibernate translates to UTC first (jdbc timezone), so that timezone info is not lost.

I doubt Hibernate does that out of the box, because that would be *very wrong* default behaviour. You can see the default behaviour here, just below the line you've quoted:
https://github.com/hibernate/hibernate-orm/blob/ad84aaf0bcb161b272731c82742018ad3445742b/hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/TimestampTypeDescriptor.java#L56

That's a workaround *you* applied based on their "jdbc time zone" configuration option, because you chose not to run your JVM in UTC. You're using this feature here:
https://in.relation.to/2016/09/12/jdbc-time-zone-configuration-property/

And Hibernate devs probably had their own share of discussions with folks who chose to use different time zones on different servers (or even different time zones on the same server), such that they added an SPI as an escape hatch, which isn't a bad feature. Our escape hatch, as I already documented, is to write your own data type `Binding`, where you're free to pass whatever `Calendar` instance to the JDBC API:
https://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings

We *could* add an SPI for that as well (I've created a feature request for this: https://github.com/jOOQ/jOOQ/issues/11761), but I don't see this as anything urgent. If you want to reproduce the exact behaviour as Hibernate exposes, then please write your own data type binding and apply that to all of your `TIMESTAMP WITHOUT TIME ZONE` columns. It's just a few lines of code.

Does that make sense? In summary:

1. Please make sure all data types and how they can interact is properly understood. Otherwise, you'll continue running into issues
2. The workaround, if you can't run your JVM in UTC is to use a custom data type binding. That way, you can reproduce Hibernate's behaviour without having to wait on #11761.

**Comment by cdalexndr** [comment] 2021-04-07 15:06
Added real life example to: https://github.com/cdalexndr/jOOQ-11753 (method `testLocalDateTimeTimezone()`)

Consider that database contains `timestamp` dates, all considered at UTC timezone.
Using `LocalDateTime` to compare with the database UTC dates fails.

**Comment by cdalexndr** [comment] 2021-04-07 15:32
Indeed, the error was on my part, I had thought that all `timestamps without timezone` should be considered at UTC (but do they?).
I had `hibernate.jdbc.time_zone` to `UTC` resulting in this behavior. 
https://github.com/jOOQ/jOOQ/issues/11761 will allow the same behavior with jooq.

**Comment by lukaseder** [comment] 2021-04-07 15:34
> I had thought that all `timestamps without timezone` should be considered at UTC (but do they?).

No! That's the point I've been making all along! :) They should be considered as timestamps in your local time zone. You just chose to set that local time zone to UTC on the server, and in Hibernate, but not on the client (the JVM)

> I had `hibernate.jdbc.time_zone` to `UTC` resulting in this behavior.

Yes. Remove that, and Hibernate will behave the same as jOOQ.

> #11761 will allow the same behavior with jooq.

Yes. Or, you implement your own data type binding. Are you licensed? If so, we could prioritise this feature for you...

**Comment by lukaseder** [comment] 2021-04-07 15:35
But, if you can, I really recommend you start using `TIMESTAMP WITH TIME ZONE` in PostgreSQL. The naming is a bit weird, because they're not actually storing the time zone. They're just UTC timestamps.

**Comment by cdalexndr** [comment] 2021-04-07 15:39
> Are you licensed? If so, we could prioritise this feature for you...
No, but the workaround is pretty simple, just use UTC everywhere, just as a server in production.
