### ISSUE TITLE
Record.into() does not use configured converters

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#16192] opened 2024-01-30 21:18 UTC
### Expected behavior

`Record.into(Class<? extends E> type)` uses whatever converters were configured in the `forcedType` definitions

### Actual behavior

Conversion fails with

```
org.jooq.exception.MappingException: An error occurred when mapping record to class X
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:659)
	at org.jooq.impl.AbstractRecord.into(AbstractRecord.java:812)
	...
Caused by: org.jooq.exception.DataTypeException: Cannot convert from d3a51a4d-8739-46ae-8746-368725d7a650 (class Id) to class X
	at org.jooq.impl.Convert$ConvertAll.fail(Convert.java:1604)
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:1425)
	at org.jooq.impl.Convert.convert0(Convert.java:443)
	at org.jooq.impl.Convert.convert(Convert.java:518)
	at org.jooq.impl.DefaultConverterProvider.lambda$provide$1(DefaultConverterProvider.java:121)
	at org.jooq.Converter$1.from(Converter.java:181)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:355)
	at org.jooq.impl.DefaultRecordMapper$ValueTypeMapper.map(DefaultRecordMapper.java:714)
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:649)
	... 18 more
```

### DB

(PostgreSQL in this example)

```
CREATE TABLE a
(
    id UUID NOT NULL PRIMARY KEY
);
```

### ForcedType

```
forcedType {
    converter = "IdConverter"
    userType = "Id"
    includeExpression = "a\\.id"
}
```

### Converter

```kotlin
class IdConverter : DatabaseIdConverter<Id>(Id::class.java)

abstract class DatabaseIdConverter<U : DatabaseId>(private val toType: Class<U>) : Converter<UUID, U> {
    private val primaryConstructor = toType.kotlin.primaryConstructor!!

    override fun from(databaseObject: UUID?): U? = databaseObject?.let { primaryConstructor.call(databaseObject) }
    override fun to(userObject: U?): UUID? = userObject?.id
    override fun fromType(): Class<UUID> = UUID::class.java
    override fun toType(): Class<U> = toType
}
```

### Model

```kotlin
@JvmInline
value class Id(override val id: UUID) : DatabaseId {
    override fun toString(): String = id.toString()
}

interface DatabaseId {
    val id: UUID
}

data class X(val id: Id)
```

### Test code

```kotlin
val record = jooq.newRecord(A)
record.id = Id(UUID.randomUUID())
record.into(X::class.java)
```

### jOOQ Version

3.19.3

### Database product and version

PostgreSQL 15.3

### Java Version

openjdk version "21.0.1" 2023-10-17 LTS

### OS Version

Microsoft Windows [Version 10.0.22631.3007]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.1

**Comment by lukaseder** [comment] 2024-01-31 09:44
Thanks for your report.

I think there's a misunderstanding of what is a mapper and what is a converter. A `Converter` (which is part of a `Binding`) is applied when reading a `T` value from a JDBC `ResultSet` (or R2DBC `Result`), converting it into a `U` value that is already contained in the `Record`. You will read `Record.get(Field<U>): U`. This will not re-convert any value. The value has already been converted. A `RecordMapper`, on the other hand, allows for mapping a `Record` "into" a `Class<E>`. While it can do some auto-conversions (e.g. from known types like `Integer` to `String`, etc.), it doesn't apply user-defined converters anymore, because that step has already been made.

Now, since you're just using `@JvmInline`, I'm going to close this as a duplicate of existing issues:

- https://github.com/jOOQ/jOOQ/issues/14608
- https://github.com/jOOQ/jOOQ/issues/14533

**Closed by lukaseder** 2024-01-31 09:44 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
