### ISSUE TITLE
[Generator] SQLite Keywords exported as functions

### ISSUE THREAD

**Issue by m-i-k-e-e** [jOOQ/jOOQ#8635] opened 2019-05-16 07:55 UTC
Hey Guys,

Here is a small issues with the generator

### Expected behavior and actual behavior:

Using the following SQL code 

```
CREATE TABLE IF NOT EXISTS `dossier` (
    `id` VARCHAR(255),
    `name` VARCHAR(255),
    `etat` TINYINT,
    `owner` VARCHAR(25),
    `creation_date` DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT pk_dossier PRIMARY KEY(`id`)
);
```

for the field **creation_date**, it will produce the following java code : 
```
public final TableField<DossierRecord, LocalDate> CREATION_DATE = createField("creation_date", org.jooq.impl.SQLDataType.LOCALDATE.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_DATE()", org.jooq.impl.SQLDataType.LOCALDATE)), this, "");
```

The creation of the database looks like this : 

```
   it.createTableIfNotExists(DOSSIER)
                    .columns(Tables.DOSSIER.fields().asList())
                    .constraints(Tables.DOSSIER.references.map { fk ->
                        fk.constraint()
                    })
                    .constraints(Tables.DOSSIER.primaryKey.constraint())
                    .execute()
```

This code at runtime will produce the following error : 
>[SQLITE_ERROR] SQL error or missing database (near "(": syntax error)

The error is due to the CURRENT_DATE keyword being converted to **CURRENT_DATE()**

replacing the generated code with the following one fixes the problem : 

```
public final TableField<DossierRecord, LocalDate> CREATION_DATE = createField("creation_date", org.jooq.impl.SQLDataType.LOCALDATE.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_DATE", org.jooq.impl.SQLDataType.LOCALDATE)), this, "");
```

### Versions:

- jOOQ: 3.11.11
- Java: 8
- Database (include vendor): SQLite
- OS: Tested on Windows and Linux
- JDBC Driver (include name if inofficial driver): org.xerial:sqlite-jdbc:3.27.2.1
- Generator config file : [jooq-config.zip](https://github.com/jOOQ/jOOQ/files/3185907/jooq-config.zip)

Regards,
Michaël

**Comment by lukaseder** [comment] 2019-05-16 09:26
Thank you very much for your report.

The issue wouldn't occur if you had used the `SQLiteDatabase` instead of the `DDLDatabase`. It is related to the fact that behind the scenes, the `DDLDatabase runs the SQL in an embedded, in-memory H2 database, which then again reports `CURRENT_DATE` as `CURRENT_DATE()` to the code generator.

This is a "known" issue. We should not produce these expression strings in generated code, but try to parse the default expression strings and produce jOOQ code instead: #7849

I will keep your issue open as a validation when fixing #7849.

As a workaround, you could remove the default expressions from a copy of your SQL scripts prior to passing them to the `DDLDatabase`

**Comment by m-i-k-e-e** [comment] 2019-05-16 09:41
I'm using a DDLDatabase just to be able to generate from SQL files, it doesn't look possible with SQLite. 
Did I miss something in the documentation ?

**Comment by lukaseder** [comment] 2019-05-16 09:45
I understand that this is what you're doing, and I explained why there's currently a known bug/limitation in that approach :)

It is totally possible to use the DDLDatabase with SQLite, but you *currently* cannot use this type of default expression.

**Comment by katzyn** [comment] 2019-05-16 11:32
@lukaseder
Recent versions of H2 always return standard SQL for standard datetime value functions without arguments. If invalid `CURRENT_DATE()` was produced by H2, it was a some old version of H2 such as 1.4.197 or older.

**Comment by lukaseder** [comment] 2019-05-16 11:47
Oh, interesting, thanks for the pointer, @katzyn. So, this will perhaps resolve itself in jOOQ 3.12 then. 3.11 still references 1.4.197:
https://github.com/jOOQ/jOOQ/blob/version-3.11.11/pom.xml#L133

jOOQ 3.12 references 1.4.199:
https://github.com/jOOQ/jOOQ/blob/5156f503b46f13fca9f2877158b0f1ea6124377e/pom.xml#L30

@m-i-k-e-e Can you try updating the H2 dependency for `jOOQ-meta-extensions` on your side to make sure H2 `1.4.199` is included and try again?

**Comment by m-i-k-e-e** [comment] 2019-05-16 12:04
@lukaseder Yes it's fixed
Thanks @lukaseder @katzyn

**Comment by lukaseder** [comment] 2019-05-16 12:17
OK, thank you very much for the feedback. So, I'll close this issue here as a duplicate of us upgrading the H2 dependency and also #7849, which fixes these problems more thoroughly.

**Closed by lukaseder** 2019-05-16 12:17 UTC
Labels: C: DB: SQLite, C: Functionality, E: All Editions, P: Medium, R: Duplicate, T: Defect
