### ISSUE TITLE
Cannot generate from an XML schema with an xmlns that specifies an old version

### ISSUE THREAD

**Issue by deinspanjer** [jOOQ/jOOQ#7218] opened 2018-02-24 01:09 UTC
### Expected behavior and actual behavior:
I was trying to generate some Java files based off an older XMLDatabase captured from jooq 3.5.4.  The generator gave the following output:
```
[INFO] Using XML file           : /.../information_schema.xml
[WARNING] No schemata were loaded  : Please check your connection settings, and whether your database (and your database version!) is really supported by jOOQ. Also, check the case-sensitivity in your configured <inputSchema/> elements : null
[INFO] Excluding empty catalog  :
[INFO] Removing excess files
```
After trying a couple of different things, I eventually tried just replacing the xmlns line:
`<information_schema xmlns="http://www.jooq.org/xsd/jooq-meta-3.5.4.xsd">`
with one output by the current version:
`<information_schema xmlns="http://www.jooq.org/xsd/jooq-meta-3.10.0.xsd">`
and it worked with no further changes to the actual content of the file.

### Steps to reproduce the problem:
* Generate an XMLDatabase
* Change the information_schema xmlns to an older version such as 3.5.4
* try to generate from the XMLDatabase

### Versions:

- jOOQ: 3.10.0
- Java: 1.8.144
- Database (include vendor): MSSQL
- OS: Mac

**Comment by lukaseder** [comment] 2018-02-24 20:20
Thanks for your report. Indeed, that should be done for this XML content type as well. jOOQ is already doing it for https://www.jooq.org/xsd/jooq-codegen-3.10.0.xsd, but apparently not for http://www.jooq.org/xsd/jooq-meta-3.10.0.xsd

**Comment by lukaseder** [comment] 2018-02-26 09:07
This is in fact a duplicate of #6727.
I'll merge this to 3.10.6 (#7220) and 3.9.7 (#7221)

**Closed by lukaseder** 2018-02-26 09:07 UTC
Labels: C: Code Generation, P: High, T: Defect
