### ISSUE TITLE
dao.insert(pojo) not updating correctly pojo's new ID

### ISSUE THREAD

**Issue by tomas-silhavy** [jOOQ/jOOQ#6834] opened 2017-11-22 02:50 UTC
``` sql
CREATE TABLE user (
  id       INTEGER PRIMARY KEY AUTOINCREMENT,
  name     VARCHAR NOT NULL UNIQUE,
  password VARCHAR NULL
);
```
### Expected behavior and actual behavior:

```java
UserPojo user = new UserPojo();
user.setName("abc");
user.setPassword("xxx");
userDao.insert(user);
assert user.getId() != null;   //**FAIL!**
```

possible problem place in code
**AbstractDMLQuery.java**
```java
switch (ctx.family()) {

                // SQLite can select _rowid_ after the insert
                case SQLITE: {
                    listener.executeStart(ctx);
                    result = ctx.statement().executeUpdate();
                    ctx.rows(result);
                    listener.executeEnd(ctx);

                    DSLContext create = DSL.using(ctx.configuration());
                    returned =
                    create.select(returning)
                          .from(table)
                          .where(rowid().equal(rowid().getDataType().convert(create.lastID())))
                          .fetchInto(table);

                    return result;
                }
```

What's happening is that jOOQ when running `select last_insert_rowid()` to retrieve new ID asks again for new connection and pool (`ConnectionProvider`) just provides another connection and because of that `last_insert_rowid()` always return 0.

**Fix?:** make jOOQ use same connection in cases when doing round trip for new ID from auto-increment columns on DBs that don't support `INSERT...RETURNING`.

**Workaround (ugly):**
override `dao.insert()` method and annotate with `@Transactional`
```java
    @Override
    @Transactional
    public void insert(P pojo) {
        super.insert(pojo);
    }
```

### jooq log
```log
2017-11-22 15:22:39 DEBUG org.jooq.tools.LoggerListener - Executing query          : insert into user (name, password) values (?, ?)
2017-11-22 15:22:39 DEBUG org.jooq.tools.LoggerListener - -> with bind values      : insert into user (name, password) values ('abc', 'xxx')
2017-11-22 15:22:39 DEBUG org.jooq.tools.LoggerListener - Affected row(s)          : 1
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener - Executing query          : select last_insert_rowid()
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener - Fetched result           : +-------------------+
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener -                          : |last_insert_rowid()|
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener -                          : +-------------------+
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener -                          : |                  0|
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener -                          : +-------------------+
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener - Executing query          : select user.id from user where _rowid_ = ?
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener - -> with bind values      : select user.id from user where _rowid_ = 0
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener - Fetched result           : +----+
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener -                          : |  id|
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener -                          : +----+
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener - Executing query          : select user.id, user.name, user.password from user
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener - Fetched result           : +----+-----+----------+
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener -                          : |  id|name |password  |                      
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener -                          : +----+-----+----------+
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener -                          : |   1|abc  |xxx       |             
2017-11-22 15:22:40 DEBUG org.jooq.tools.LoggerListener -                          : +----+-----+----------+
```

### Versions:
- spring boot: 1.5.8.RELEASE, used autoconfig for everything (hikari,transactionManagement)
- jOOQ: 3.10.1
- Java: 8
- Database (include vendor): sqlite-jdbc 3.20.1
- Connection Pool: HikariCP 2.7.2
- JDBC Driver (include name if inofficial driver): sqlite-jdbc 3.20.1

**Comment by lukaseder** [comment] 2017-11-22 09:06
Thank you very much for your report. This looks like a duplicate of #2536.

**Closed by lukaseder** 2017-11-22 09:06 UTC
Labels: C: Functionality, P: Medium, R: Duplicate, T: Enhancement
