### ISSUE TITLE
Code generator fails to parse partial index when using DDLDatabase

### ISSUE THREAD

**Issue by petedmarsh** [jOOQ/jOOQ#7853] opened 2018-09-12 08:25 UTC
### Expected behavior and actual behavior:

I am running the jOOQ code generator on my SQL migrations. I'd like to add a partial unique index to a table, something like this:

```
CREATE UNIQUE INDEX some_index ON some_table(column_fk, column_boolean) WHERE column_boolean;
```

However, the code generator says that there's an error in the SQL statement (the exact same SQL runs as expected when run manually):

```
Error while exporting schema: SQL [create unique index some_index on some_table(column_fk, column_boolean) where column_boolean]; Syntax error in SQL statement "CREATE UNIQUE INDEX SOME_INDEX ON SOME_TABLE(COLUMN_FK, COLUMN_BOOLEAN) WHERE[*] COLUMN_BOOLEAN "; SQL statement:
[ERROR] create unique index some_index on some_table(column_fk, column_boolean) where column_boolean [42000-197]
```

This is the first time I've used flyway/jOOQ so it's quite possible I've misconfigured something (e.g. I've not set the SQL dialect properly or something like that), but I'm not sure :)

### Versions:

- jOOQ: 3.11.3
- flyway: 5.1.4
- Java: 1.8.0_161
- Database (include vendor): Postgres 10.3
- OS: OSX 10.13.6
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2018-09-12 08:30
Thank you very much for your report. Could you post your `pom.xml` file if you're using Maven, or some other means to help reproduce this issue?

**Comment by petedmarsh** [comment] 2018-09-12 09:14
Unfortunately I don't think I can post my entire `pom.xml` as there's a few proprietary things in there, however here is the jOOQ code generation config:

```
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>${jooq.version}</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <generator>
                        <database>
                            <name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
                            <includes>.*</includes>
                            <properties>
                                <property>
                                    <key>scripts</key>
                                    <value>${project.basedir}/src/main/resources/db/migration</value>
                                </property>
                                <property>
                                    <key>sort</key>
                                    <value>semantic</value>
                                </property>
                            </properties>
                        </database>
                        <target>
                            <packageName>com.someproject</packageName>
                        </target>
                    </generator>
                </configuration>
            </plugin>
```

**Comment by lukaseder** [comment] 2018-09-12 09:27
Sure, I'm mostly interested in the jOOQ plugin part, thanks! I'll try to reproduce and be in touch

**Comment by lukaseder** [comment] 2018-09-12 10:29
I can reproduce this with the `DDLDatabase`. It currently parses SQL, translates it to H2 dialect and runs it on an H2 database. We could work around each such feature that is not supported in H2 (see also #7771), but a much more thorough solution would be to avoid using H2 behind the scenes entirely, and actually "execute" the DDL in a simulated environment: #7034.

I think there had been enough requests about similar limitations of the `DDLDatabase` by now to prioritise #7034. Thus, I will close this issue as a duplicate of #7034

**Comment by lukaseder** [comment] 2018-09-12 10:42
On a second thought, a workaround can be implemented for jOOQ 3.11.5 as well, rather easily, prior to implementing the much more complex #7034

**Comment by lukaseder** [comment] 2018-09-12 10:51
Fixed for jOOQ 3.12. Backport scheduled for 3.11.5 (#7855)

**Closed** 2018-09-12 10:50 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Fixed, T: Defect

**Comment by petedmarsh** [comment] 2018-09-12 10:56
Fantastic, thank you for the quick turn around @lukaseder.

Just two quick questions:

1. Is there an approximate eta for the release of 3.11.5 and/or 3.12?
2. How do I actually set this flag for the work around, can I do so in my jooq xml config?

**Comment by lukaseder** [comment] 2018-09-12 11:48
> Is there an approximate eta for the release of 3.11.5 and/or 3.12?

This week / unknown

> How do I actually set this flag for the work around, can I do so in my jooq xml config?

You don't have to do anything
