### ISSUE TITLE
Convrt MYSQL Query in to Derby 

### ISSUE THREAD

**Issue by RohanaBandara** [jOOQ/jOOQ#11890] opened 2021-05-16 06:37 UTC
Hi I attempted to convert MYSQL Query in to Derby but it does not converted correctly.
MYSQL Query below shown

```sql
SELECT CASE WHEN sortId = 1 THEN CAST(orderId AS CHAR(10)) ELSE '' END AS orderId, CASE WHEN sortId = 1 THEN orderName ELSE '' END AS orderName, itemName, itemUnit, itemRate
FROM
(
    SELECT orderId, orderName, itemName, itemUnit, itemRate, ROW_NUMBER() OVER (PARTITION BY orderId ORDER BY itemId) AS sortId
    FROM
    (
        SELECT orderId, orderName, itemName, itemUnit, itemRate, itemId
        FROM tblitem 
        INNER JOIN  tblorder 
            on tblorder.orderId = tblitem.orderRef
    ) orderItems
) orderItemsSorted
ORDER BY orderItemsSorted.orderId, orderItemsSorted.sortId
```

**Comment by lukaseder** [comment] 2021-05-17 07:29
Thanks a lot for your feature request. We could indeed try to emulate some window functions in dialects that do not support them natively (https://github.com/jOOQ/jOOQ/issues/1715), but it's a lot of work, the results are probably very inefficient, as they rely on heavy self-joining, and the remaining SQL dialects that do not support window functions yet are not too numerous - so this isn't going to be a priority, I'm afraid.

I'm closing this as a duplicate of #1715

**Closed by lukaseder** 2021-05-17 07:29 UTC
Labels: C: Translator, E: All Editions, P: Medium, T: Enhancement
