### ISSUE TITLE
Use imports in generated code to enhance readability

### ISSUE THREAD

**Issue by rombert** [jOOQ/jOOQ#2884] opened 2013-12-09 22:05 UTC
Right now it's pretty hard to follow the code in generated classes due to all class names being fully-qualified, including the java.lang ones.

**Comment by lukaseder** [comment] 2015-11-25 10:35
Hmm, I think that we covered everything with #3336, so I'm closing this as a duplicate of #3336

**Closed by lukaseder** 2015-11-25 10:35 UTC
Labels: C: Code Generation, P: Low, T: Enhancement
