### ISSUE TITLE
JoinTable.join(...).onKey() does not work

### ISSUE THREAD

**Issue by RichardBradley** [jOOQ/jOOQ#6266] opened 2017-05-23 15:33 UTC
I love the [join "onKey()" functionality](https://www.jooq.org/doc/3.10/manual/sql-building/sql-statements/select-statement/join-clause/#N43BF2), I've always missed that in SQL.

I have found that the "onKey()" cannot infer which FK to use when there are more than one join in the query. Is that just an omission? I can't see any reason why that wouldn't work.

For example, if I do:

```
create.select()
      .from(AUTHOR)
      .join(BOOK).onKey()
      .join(LANGUAGE).onKey()
      .fetch();
```

... then I get:

```
org.jooq.exception.DataAccessException: Key ambiguous between tables "author"
  join "book"
  on "book"."author_id" = "author"."id" and "language"
```

I think all that would be required to fix this would be to handle "JoinTables" as a special case in the [AbstractTable.getReferencesTo](https://github.com/jOOQ/jOOQ/blob/3605697b8d0c74de6b2fbafc676dfc78cd74d11c/jOOQ/src/main/java/org/jooq/impl/AbstractTable.java#L482) method.

(It might also be nice to add more info to the "Key ambiguous" exception, which doesn't currently list the FKs which were found.)

**Comment by lukaseder** [comment] 2017-05-23 15:38
This should work as expected, but the question is, is your path from `AUTHOR` to `LANGUAGE` really non-ambiguous? What's the DDL to produce these tables? (note, our manual examples have `BOOK.AUTHOR_ID` and `BOOK.CO_AUTHOR_ID` columns, which make this type of join ambiguous)

**Comment by RichardBradley** [comment] 2017-05-23 15:42
Hmm, maybe I have slightly mis-stated or misunderstood the problem, sorry.

I have a schema which has a non-ambiguous path along my multi-table join which is failing with the above exception. If I put a breakpoint at the "throw" in JoinTable.onKey, then I see that both "leftToRight" and "rightToLeft" are empty (when an FK exists), which I think matches the above diagnosis.

I'll see if I can prepare a failing test case. What is the best example project to start from? Should I just fork something from https://github.com/jOOQ/jOOQ/tree/master/jOOQ-examples or maybe look for some unit tests near the "onKey" feature in the main repos?

**Comment by lukaseder** [comment] 2017-05-23 15:49
If I have the DDL for those exact tables, I'll probably be able to reproduce...

**Comment by RichardBradley** [comment] 2017-05-23 22:05
> I'll see if I can prepare a failing test case. 

There aren't any tests? I didn't see that coming. 

I'll see if I can repro from one of the examples.

**Comment by RichardBradley** [comment] 2017-05-23 22:23
It's an order issue.
If there is a joinable chain A -> B -> C, then issuing "join(x).onKey()" in that order works, but any other order fails with "Key ambiguous between tables". See https://github.com/RichardBradley/jOOQ/commit/0dbc4744671ff0fb12dc93640b299e24723d415f

While this seems like an easily avoidable issue in the A -> B -> C case, it is not avoidable if you have a forking join chain, e.g. A -> B -> C1, B -> C2

**Comment by lukaseder** [comment] 2017-05-25 09:20
> There aren't any tests? I didn't see that coming.

Indeed, there are a variety of Open Source projects out there that follow this model. E.g. there are proprietary licenses for a large amount of SQLite tests (https://www.sqlite.org/th3.html). It's one way for a vendor to leverage Open Source for secondary commercial offerings.

Thank you very much for your suggestions and PR. I'll review this shortly.

**Comment by lukaseder** [comment] 2020-07-02 12:47
Finally looking at this now. I can reproduce it with this schema:

```sql
-- [#6266] Code generation for onKey() usage
create table a (
  a_id int not null,
  text varchar(10),
  
  constraint a_pk primary key (a_id)
);

create table b (
  b_id int not null,
  a_id int,
  text varchar(10),
   
  constraint b_pk primary key (b_id),
  constraint b_fk foreign key (a_id) references a
);

create table c (
  c_id int not null,
  b_id int,
  text varchar(10),
   
  constraint c_pk primary key (c_id),
  constraint c_fk foreign key (b_id) references b
);

create table d (
  d_id int not null,
  b_id int,
  text varchar(10),
   
  constraint d_pk primary key (d_id),
  constraint d_fk foreign key (b_id) references b
);
```

And this test:

```java
@Test
public void testOnKey() throws Exception {
    ctx.insertInto(A).columns(A.A_ID, A.TEXT).values(1, "A").execute();
    ctx.insertInto(B).columns(B.B_ID, B.A_ID, B.TEXT).values(1, 1, "B").execute();
    ctx.insertInto(C).columns(C.C_ID, C.B_ID, C.TEXT).values(1, 1, "C").execute();
    ctx.insertInto(D).columns(D.D_ID, C.B_ID, D.TEXT).values(1, 1, "D").execute();

    ctx.select(
            A.TEXT,
            B.TEXT,
            C.TEXT,
            D.TEXT)
       .from(A)
        // Branching chains like Aa -> Bb -> Cc, Bb -> Dd cannot be handled by "onKey()"
       .join(B).onKey()
       .join(C).onKey()
       .join(D).onKey()
       .fetch();
}
```

**Comment by lukaseder** [comment] 2020-07-02 12:55
Curiously, the `JoinTable.getReferences()` method already recurses into its joined tables, which explains what you have found: that the order of joins matters: https://github.com/jOOQ/jOOQ/issues/6266#issuecomment-303549942

**Comment by lukaseder** [comment] 2020-07-02 13:07
Fixed in jOOQ 3.14.0. Backport scheduled for 3.13.3 (#10346).
 
Thanks again for reporting.

**Closed by lukaseder** 2020-07-02 13:07 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect

**Comment by lukaseder** [comment] 2020-07-02 13:21
This isn't the same bug as #5209, which still remains.

**Comment by RichardBradley** [comment] 2020-07-02 13:40
Thanks!

**Comment by pietrol83** [comment] 2023-03-28 13:06
hi I have the same problem. I've migrating mai code with jooq form version 3.6.4 to 3.18.1. The queries in my code are the same but with version 3.6.4 of jooq it work and with version 3.18.1 doesn't. one of the queries is:

SelectConditionStep<Record6< Long, Long, Long,Long,String,Short>>  qry=DSLUtil.getContext()
				.select(MP_OPERATION.AMOUNT_1,
						MP_OPERATION.AMOUNT_2,
						MP_OPERATION.AMOUNT_3,
						MP_CART.CR_ID,
						MP_CART.SOURCE_ACCESS,
						MP_PRODUCT_TYPE.PT_ID
						)
                .from(MP_OPERATION)
                .join(MP_CART).onKey()                
                .join(MP_PAYMENT).onKey()
                .join(MP_PRODUCT_TYPE).onKey()
                .where(buildPaymentInstrumentCondition(paymentInstruments)
                        .and(buildAccessSourceCondition(sources))
                        .and(MP_PRODUCT_TYPE.PT_CATEGORY.equal(paymentCategory.name()))
                        .and(MP_PAYMENT.PYS_CODE.equal(Configuration.PaymentStatus.CON.toString()))
                        .and(MP_PAYMENT.TS_EXE.between(interval[0], interval[1])));

and the exception is:

**Comment by lukaseder** [comment] 2023-03-28 13:26
Thanks for your report, @pietrol83. Since this issue is already a bit older, and you're upgrading between quite a few versions, perhaps this is not strictly related.

Can you please create a new issue and add some additional information to your request? Mainly the `CREATE TABLE` for your first 3 tables `MP_OPERATION`, `MP_CART`, and `MP_PAYMENT` will be needed.
