### ISSUE TITLE
Feedback about manual section jooq-in-7-steps-step3

### ISSUE THREAD

**Issue by jrojer** [jOOQ/jOOQ#12290] opened 2021-08-10 09:51 UTC
Generated `.java` files contain duplicate lines causing `is already defined` compile errors.
See the example of `.java` file and generation configuration here: [attach.zip](https://github.com/jOOQ/jOOQ/files/6960645/attach.zip).

**Comment by lukaseder** [comment] 2021-08-10 10:00
Thanks a lot for taking the time to report these things. It looks like our tutorial is in poor shape :( I'll look into this right away - duplicate generated members seems to be quite the bug

**Comment by lukaseder** [comment] 2021-08-10 10:28
Oh is `dblink_get_notify` an overloaded table valued function? In that case, this would be a known issue: https://github.com/jOOQ/jOOQ/issues/4055

The workaround is to exclude it from being generated in `<excludes>dblink_get_notify</excludes>`

**Comment by jrojer** [comment] 2021-08-10 10:50
Should a note about Table-valued functions be put into tutorial?

**Comment by jrojer** [comment] 2021-08-10 10:58
> The workaround is to exclude it from being generated in `<excludes>dblink_get_notify</excludes>`

The workaround worked.

**Comment by lukaseder** [comment] 2021-08-10 11:06
> Should a note about Table-valued functions be put into the tutorial?

Probably not, for the same reason as a note about the JDBC URL shouldn't necessarily be put into the tutorial, see https://github.com/jOOQ/jOOQ/issues/12289#issuecomment-895849000

The point here being that there would already be 2 noisy notes that don't affect the vast majority of users. I mean, imagine the many other caveats that a new users might run into. Each one an edge case, none of them warranting a note in the tutorial...

In this case, I'd rather this bug finally be fixed! While the actual fix of supporting overloaded table valued functions is hard, we can detect such overloads, and omit their code generation entirely, issuing a warning. I'll go ahead and implement that right now.

**Comment by lukaseder** [comment] 2021-08-10 11:07
Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/4055. Thanks again for your report!

**Closed by lukaseder** 2021-08-10 11:07 UTC
Labels: T: Defect, C: Code Generation, P: High, R: Duplicate, E: All Editions

**Comment by lukaseder** [comment] 2021-08-10 11:23
For the record, in the integration tests, there is a warning about ambiguous function names:

```
13:22:40,160 [WARNING] Ambiguous type name      : The object STORED_FUNCTIONS.F_OVERLOAD_TVF generates a type org.jooq.codegen.test.storedfunctions.db.tables.FOverloadTvf which conflicts with the existing type org.jooq.codegen.test.storedfunctions.db.tables.FOverloadTvf on some operating systems. Use a custom generator strategy to disambiguate the types.
```

It's curious that this doesn't seem to work in your case - perhaps something PostgreSQL specific

**Comment by lukaseder** [comment] 2021-08-10 11:25
Can you post the sources (or at least the signature) of the `dblink_get_notify` overloads?
