### ISSUE TITLE
MySQL "YEAR" column mapping to java.sql.Date causing truncation issues

### ISSUE THREAD

**Issue by er1c** [jOOQ/jOOQ#9738] opened 2020-01-15 16:44 UTC
Vanilla generated column:

```scala
  val YEAR : TableField[CatalogOrderNumberRecord, Date] = createField(DSL.name("year"), org.jooq.impl.SQLDataType.DATE.nullable(false), "")
```

The "insert" on Master works fine, but when it tries to replicate to a MySQL slave, it has a problem with the truncation.

```
    Read Replica Replication Error - SQLError: 1265, reason: Error &apos;Data truncated for column &apos;year&apos; at row 1&apos; on query. 
    Default database: &apos;catalog_preproduction&apos;. 
    Query: &apos;insert into `catalog_preproduction`.`catalog_order_number` (`catalog_id`, `year`, `next_order_number`) values (&apos;f�S{&amp;\�\�\�b�D\�&apos;, &apos;2020-01-01&apos;, 2)&apos
```

Should the `YEAR` data type really be `java.sql.Date` (vs `java.lang.Integer`)

The MySQL docs https://dev.mysql.com/doc/refman/5.7/en/year.html reference the 4-digits (e.g. `2020`) as the proper value to send/return back.

### Versions:

- jOOQ: 3.12.3
- Java: openjdk 11.0.3 2019-04-16
- Database (include vendor): MySQL 5.7.26 (AWS RDS)

**Comment by er1c** [comment] 2020-01-15 18:55
My "simple workaround" is to use a `SMALLINT` field + `CONSTRAINT` instead:

```
CREATE TABLE `catalog_order_number` (
  `catalog_id` BINARY(16) NOT NULL ,
  -- 2020-01-15 - MySQL column type YEAR causes problems w/JOOQ & java.sql.Date data type
  --              causing MySQL truncation errors on the serialized '2020-01-01' value
  `year` SMALLINT NOT NULL ,
  `next_order_number` INT NOT NULL DEFAULT '0',
  UNIQUE INDEX `uniqueCatalogAndYear` (`catalog_id` ASC, `year` ASC),
  -- MySQL 8.0 Column Type Docs for YEAR:
  --   As 4-digit strings in the range '1901' to '2155'.
  -- MySQL 8.0 Comparison Operator Docs for BETWEEN:
  --   If expr is greater than or equal to min and expr is less than or equal to max,
  CONSTRAINT year_chk CHECK (`year` BETWEEN 1901 AND 2155),
  CONSTRAINT `catalog_order_number_catalog_id`
    FOREIGN KEY (`catalog_id`)
    REFERENCES `catalog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;
```

**Comment by lukaseder** [comment] 2020-01-16 10:25
Thank you very much for your report.

We have some related issues:

- https://github.com/jOOQ/jOOQ/issues/2500
- https://github.com/jOOQ/jOOQ/issues/8647

It is quite possible that our out of the box mapping of `YEAR` to `DATE` is simply wrong. A workaround to achieve that you're getting the same behaviour as that of `INTEGER` or `SMALLINT` is to rewrite your data type in the code generator:
https://www.jooq.org/doc/latest/manual/code-generation/data-type-rewrites

Alternatively, you could use a data type binding if you want to bind the type to something like `java.time.Year`

**Comment by lukaseder** [comment] 2023-01-19 08:51
I'll implement this in jOOQ 3.18: https://github.com/jOOQ/jOOQ/issues/2500. Closing this here as a duplicate of https://github.com/jOOQ/jOOQ/issues/2500

**Closed by lukaseder** 2023-01-19 08:51 UTC
Labels: T: Defect, C: Code Generation, C: DB: MySQL, P: Medium, R: Duplicate, E: All Editions
