### ISSUE TITLE
Stop aligning generated POJO members and constructor arguments in columns

### ISSUE THREAD

**Issue by perlun** [jOOQ/jOOQ#13546] opened 2022-05-11 14:05 UTC
### Steps to reproduce the problem

(Unsure of whether to label this a "bug" or a "feature request". It's a bit in the eye of the beholder... :grin:)

When generating (immutable) POJOs, the fields in the output are nicely formatted using a padded form where the "max length of the type of any field" determines the padding. I think it's handled by this code in the `JavaGenerator` class (+ other code which handles the constructor parameters):

```java
            if (!generatePojosAsJavaRecordClasses())
                for (TypedElementDefinition<?> column : getTypedElements(tableUdtOrEmbeddable))
                    out.println("private %s%s %s;",
                        generateImmutablePojos() ? "final " : "",
                        StringUtils.rightPad(out.ref(getJavaType(column.getType(resolver(out, Mode.POJO)), out, Mode.POJO)), maxLength0),
                        getStrategy().getJavaMemberName(column, Mode.POJO));
```

While this may be useful to some people, I think it can also be an anti-feature if you consider these generated classes to be "static files" that you commit to your git history (yeah, we've started moving towards that approach with Testcontainers, as you suggested in email :bow: Much better that way with a real PG instance). It can cause very annoying diffs like the one below (my real-world example right now, which triggered me to submit this).

Some people may prefer this for readability, but I personally think it would be very useful to turn this feature off. A global kill-switch on e.g. `org.jooq.meta.jaxb.Generate` level which disables all `StringUtils.rightPad()` calls in the `JavaGenerator` would be good enough for us, I don't think there's any need to be able to control "individual padding" for different parts of the generation.

```diff
diff --git some/path/to/pojosTSDBUser.java
index 37cfd57d27..8567cad8b9 100644
--- some/path/to/pojos/TSDBUser.java
+++ some/path/to/pojos/TSDBUser.java
@@ -7,7 +7,6 @@ package some.path.to.pojos;
 import some.package.RevisionedEntity;
 
 import java.time.Instant;
-import java.time.OffsetDateTime;
 
 import javax.annotation.Nullable;
 
@@ -18,35 +17,35 @@ import javax.annotation.Nullable;
 @SuppressWarnings({ "all", "unchecked", "rawtypes" })
 public class TSDBUser implements RevisionedEntity {
 
-    private final Integer        id;
-    private final String         username;
-    private final OffsetDateTime lastPasswordChange;
-    private final String         firstName;
-    private final String         lastName;
-    private final String         company;
-    private final String         email;
-    private final Boolean        messageForwarding;
-    private final String         languageCode;
-    private final Integer        role;
-    private final String         logo;
-    private final String         timeZone;
-    private final Integer        dateTimeNotation;
-    private final Integer        vodDuration;
-    private final Integer        concurrentPlaybackSessionsAllowed;
-    private final String         contentRating;
-    private final Integer        priority;
-    private final Boolean        forcePasswordChange;
-    private final Boolean        isEnabled;
-    private final Boolean        isAdminEnabled;
-    private final Integer        imported;
-    private final Integer        _Revision;
-    private final Instant        _Time;
-    private final String         _TriggeringPrincipalType;
-    private final Integer        _TriggeringPrincipalEntityId;
-    private final String         _TriggeringPrincipalEntityReference;
-    private final String         _TriggeringPrincipalSource;
-    private final String         _Metadata;
-    private final Boolean        _IsTombstone;
+    private final Integer id;
+    private final String  username;
+    private final Instant lastPasswordChange;
+    private final String  firstName;
+    private final String  lastName;
+    private final String  company;
+    private final String  email;
+    private final Boolean messageForwarding;
+    private final String  languageCode;
+    private final Integer role;
+    private final String  logo;
+    private final String  timeZone;
+    private final Integer dateTimeNotation;
+    private final Integer vodDuration;
+    private final Integer concurrentPlaybackSessionsAllowed;
+    private final String  contentRating;
+    private final Integer priority;
+    private final Boolean forcePasswordChange;
+    private final Boolean isEnabled;
+    private final Boolean isAdminEnabled;
+    private final Integer imported;
+    private final Integer _Revision;
+    private final Instant _Time;
+    private final String  _TriggeringPrincipalType;
+    private final Integer _TriggeringPrincipalEntityId;
+    private final String  _TriggeringPrincipalEntityReference;
+    private final String  _TriggeringPrincipalSource;
+    private final String  _Metadata;
+    private final Boolean _IsTombstone;
 
     public TSDBUser(TSDBUser value) {
         this.id = value.id;
@@ -81,35 +80,35 @@ public class TSDBUser implements RevisionedEntity {
     }
 
     public TSDBUser(
-        Integer        id,
-        String         username,
-        OffsetDateTime lastPasswordChange,
-        String         firstName,
-        String         lastName,
-        String         company,
-        String         email,
-        Boolean        messageForwarding,
-        String         languageCode,
-        Integer        role,
-        @Nullable String         logo,
-        String         timeZone,
-        Integer        dateTimeNotation,
-        Integer        vodDuration,
-        Integer        concurrentPlaybackSessionsAllowed,
-        @Nullable String         contentRating,
-        Integer        priority,
-        Boolean        forcePasswordChange,
-        Boolean        isEnabled,
-        Boolean        isAdminEnabled,
-        Integer        imported,
-        Integer        _Revision,
-        Instant        _Time,
-        String         _TriggeringPrincipalType,
-        @Nullable Integer        _TriggeringPrincipalEntityId,
-        String         _TriggeringPrincipalEntityReference,
-        String         _TriggeringPrincipalSource,
-        String         _Metadata,
-        Boolean        _IsTombstone
+        Integer id,
+        String  username,
+        Instant lastPasswordChange,
+        String  firstName,
+        String  lastName,
+        String  company,
+        String  email,
+        Boolean messageForwarding,
+        String  languageCode,
+        Integer role,
+        @Nullable String  logo,
+        String  timeZone,
+        Integer dateTimeNotation,
+        Integer vodDuration,
+        Integer concurrentPlaybackSessionsAllowed,
+        @Nullable String  contentRating,
+        Integer priority,
+        Boolean forcePasswordChange,
+        Boolean isEnabled,
+        Boolean isAdminEnabled,
+        Integer imported,
+        Integer _Revision,
+        Instant _Time,
+        String  _TriggeringPrincipalType,
+        @Nullable Integer _TriggeringPrincipalEntityId,
+        String  _TriggeringPrincipalEntityReference,
+        String  _TriggeringPrincipalSource,
+        String  _Metadata,
+        Boolean _IsTombstone
     ) {
         this.id = id;
         this.username = username;
@@ -159,7 +158,7 @@ public class TSDBUser implements RevisionedEntity {
     /**
      * Getter for <code>public.user.last_password_change</code>.
      */
-    public OffsetDateTime getLastPasswordChange() {
+    public Instant getLastPasswordChange() {
         return this.lastPasswordChange;
     }
 
```

### Versions

- jOOQ: 3.16.5
- Java: 8

**Comment by perlun** [comment] 2022-05-12 12:39
> A workaround is to run an auto-formatter on jOOQ-generated output, prior to checking in the generated sources.

I looked into it but it was a bit of a can of worms (since it made other unrelated changes to the code that I wasn't overly happy about, and I also got peer review that wasn't "overly pleased" about reformatting the generated code). Tried with `google-java-format` and `palantir-java-format` for reference.

_However_, while working on this I found an actual bug in the current implementation: it doesn't properly take nullability annotations into consideration, for constructor parameters. Here's an example that illustrates this from our current code base:

```java
    public TSDBDevice(
        Integer id,
        String  platform,
        String  profile,
        String  profileOverrides,
        String  alias,
        Boolean dynamicIpAddress,
        @Nullable Integer tvModelId,
        String  displayMode,
        String  skinResolution,
        @Nullable Integer maxAgeRating,
        String  model,
        String  firmwareVersion,
        @Nullable String  ipAddress,
        @Nullable String  macAddress,
        @Nullable String  secondaryMacAddress,
        @Nullable String  serialNumber,
        Integer _Revision,
        Instant _Time,
        String  _TriggeringPrincipalType,
        @Nullable Integer _TriggeringPrincipalEntityId,
        String  _TriggeringPrincipalEntityReference,
        String  _TriggeringPrincipalSource,
        String  _Metadata,
        Boolean _IsTombstone
    ) {
```

(It would have to take the length of `@Nullable` into consideration here, to make all parameters be properly aligned.)

----

If I put it like this: how important is this padding functionality for you? Would you be willing to accept a PR that just removes the padding altogether? (no config flag, and no padding in `JavaGenerator` - shouldn't be much more than removing the three `StringUtils.rightPad()` calls there and move on with our lives. :slightly_smiling_face:)

**Comment by lukaseder** [comment] 2022-05-12 13:06
Well played with that additional bug... I can confirm this. It's more effort to fix the additional padding for annotations than to remove it entirely.

The configuration flag isn't a good idea, because if we start offering configuration options for the style of generated code, we'll never stop (just look at the options available in the IDEs). If users want custom formatted code, they should really just use a formatter.

No need for a PR, this is done in minutes. A PR would take longer, because you don't have access to the integration tests or the commercial distribution, etc.

Given that this is mostly a cosmetic fix, I won't backport it in order to avoid similar diffs when people check in generated sources after a patch release upgrade.

**Comment by lukaseder** [comment] 2022-05-12 13:49
Fixed in jOOQ 3.17.0

**Closed by lukaseder** 2022-05-12 13:49 UTC
Labels: T: Enhancement, C: Code Generation, P: Low, R: Fixed, E: All Editions

**Comment by perlun** [comment] 2022-05-13 06:42
Thanks for the fix. :pray: Will the next release of jOOQ be 13.6.7 or 3.17.0 btw, what do you reckon/anticipate?

**Comment by lukaseder** [comment] 2022-05-13 06:48
3.16.7 will be released soon, but it won't contain this fix, because:

> Given that this is mostly a cosmetic fix, I won't backport it in order to avoid similar diffs when people check in generated sources after a patch release upgrade.

3.17.0 is still a while away, probably Q3 2022? Some important new features still need a lot of polish around edge cases, including:

- https://github.com/jOOQ/jOOQ/issues/9879
- https://github.com/jOOQ/jOOQ/issues/13069

**Comment by perlun** [comment] 2022-05-13 06:54
> 3.16.7 will be released soon, but it won't contain this fix, because:
> 
> > Given that this is mostly a cosmetic fix, I won't backport it in order to avoid similar diffs when people check in generated sources after a patch release upgrade.

Yeah, I got that part. That's why I asked. :grin: 

But thanks for giving an approximation of when to expect it (the 3.17.0) release. :+1: It's of course not a rush in any way, so take whatever time you need as far as we're concerned.
