### ISSUE TITLE
Missing CAST in generated MERGE statement when using inline values in PostgreSQL 15's ON DUPLICATE KEY UPDATE emulation

### ISSUE THREAD

**Issue by ferraresso** [jOOQ/jOOQ#15412] opened 2023-07-18 18:11 UTC
### Expected behavior

Null values should be cast according to the column type.

### Actual behavior

Null values aren't cast. So in Postgres 15 they are interpreted as text.

### Steps to reproduce the problem

With a table like this:

```
CREATE TABLE test.services (
	id varchar NOT NULL,
	creation timestamptz NULL,
	author varchar NULL,
	last_update timestamptz NULL
	CONSTRAINT pk_services PRIMARY KEY (id)
);
```
Executing this operation:
```
        return tx.insertInto(SERVICES).set(record)
                .onDuplicateKeyUpdate()
                .set(record);
```
If record has null values for `creation` or `last_update`, the SQL generated by JOOQ raise this error:
```
SQL Error [42804]: ERROR: column "creation" is of type timestamp with time zone but expression is of type text
  Hint: You will need to rewrite or cast the expression.
  Position: 868 
```

This is the SQL that JOOQ is generating:

```
merge
into
	"test"."services"
		using (
	select
		'new-service-id1',
		null,
		'',
		null) as "t" ("id",
	"creation",
	"author",
	"last_update") on
	("test"."services"."id" = "t"."id")
	when matched then
		update
		set
			"id" = 'new-service-id1',
			"creation" = null,
			"author" = '',
			"last_update" = null
	when not matched then
insert
	("id",
	"creation",
	"author",
	"last_update")
values ("t"."id",
"t"."creation",
"t"."author",
"t"."last_update")
```

A workaround to avoid the error is to add explicit cast in operation:
```
tx.insertInto(SERVICES).set(record)
        .set(SERVICES.CREATION,
                cast(record.get(SERVICES.CREATION), OffsetDateTime.class))
        .set(SERVICES.LAST_UPDATE,
                cast(record.get(SERVICES.LAST_UPDATE), OffsetDateTime.class))
        .onDuplicateKeyUpdate()
        .set(record)
        .set(SERVICES.CREATION,
                cast(record.get(SERVICES.CREATION), OffsetDateTime.class))
        .set(SERVICES.LAST_UPDATE,
                cast(record.get(SERVICES.LAST_UPDATE), OffsetDateTime.class));
```

### jOOQ Version

3.18.4

### Database product and version

PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Java Version

openjdk version "17.0.7" 2023-04-18

### OS Version

macOS 13.4.1

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql 42.6.0

**Comment by lukaseder** [comment] 2023-08-07 12:40
Thanks a lot for your report. I can reproduce this. The problem is with the query from the `using` clause:

```sql
using (
  select
    'new-service-id1',
    null,
    '',
    null
) 
```

It only happens when you inline the values, not when you use  bind values. What's the reason why you're inlining values in your query?

**Comment by lukaseder** [comment] 2023-08-07 12:42
Note that the `MERGE` emulation only applies when there is more than 1 keys in the table. You probably have a `UNIQUE` constraint somewhere, which you omitted in your example.

**Comment by lukaseder** [comment] 2023-08-07 13:24
Fixed in versions:

- 3.19.0
- 3.18.6 (https://github.com/jOOQ/jOOQ/issues/15447)

Older versions aren't affected because we didn't implement `ON DUPLICATE KEY UPDATE` with `MERGE`, before #7552

**Closed by lukaseder** 2023-08-07 13:24 UTC
Labels: T: Defect, C: Functionality, C: DB: PostgreSQL, P: Medium, E: All Editions

**Comment by lukaseder** [comment] 2023-08-08 11:15
Related issue: https://github.com/jOOQ/jOOQ/issues/14199
