### ISSUE TITLE
Compilation error in ScalaGenerator generated code of UpdatableRecord subclasses when using scalac 3

### ISSUE THREAD

**Issue by 7Hazard** [jOOQ/jOOQ#16072] opened 2024-01-12 17:14 UTC
### Expected behavior

Generate Scala files with no errors for Scala 3.3

### Actual behavior

I get the following error
```shell
[error] -- [E164] Declaration Error: ...\server\target\scala-3.3.1\src_managed\main\org\jooq\server\tables\records\UserRecord.scala:18:6 
[error] 18 |class UserRecord extends UpdatableRecordImpl[UserRecord](User.USER) {
[error]    |      ^
[error]    |error overriding method with in trait QualifiedRecord of type [T]
[error]    |  (x$0: org.jooq.Field[T], x$1: T):
[error]    |    org.jooq.berit.server.tables.records.UserRecord;
[error]    |  method with┬▓ in class AbstractRecord of type [T](x$0: org.jooq.Field[T┬▓], x$1: T┬▓): org.jooq.Record 
has incompatible type;
[error]    |other members with override errors are:: method original
[error]    |
[error]    |where:    T     is a type variable with constraint <: Object
[error]    |          T┬▓    is a type variable with constraint <: Object
[error]    |          with  is a method in trait QualifiedRecord
[error]    |          with┬▓ is a method in class AbstractRecord
[error]    |
[error]    | longer explanation available when compiling with `-explain`
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 7 s, completed 12 jan. 2024 18:06:55
```

### Steps to reproduce the problem

I have the following PostgreSQL table
```SQL
CREATE TABLE "public"."user" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "name" text NOT NULL,
    "email" text NOT NULL,
    "company" uuid,
    CONSTRAINT "user_email" UNIQUE ("email"),
    CONSTRAINT "user_id" PRIMARY KEY ("id")
) WITH (oids = false);
```

And codegen generates this Scala
```scala
/*
 * This file is generated by jOOQ.
 */
package org.jooq.berit.server.tables.records


import java.lang.String
import java.util.UUID

import org.jooq.Record1
import org.jooq.berit.server.tables.User
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class UserRecord extends UpdatableRecordImpl[UserRecord](User.USER) {

  /**
   * Setter for <code>public.user.id</code>.
   */
  def setId(value: UUID): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.user.id</code>.
   */
  def getId: UUID = get(0).asInstanceOf[UUID]

  /**
   * Setter for <code>public.user.name</code>.
   */
  def setName(value: String): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.user.name</code>.
   */
  def getName: String = get(1).asInstanceOf[String]

  /**
   * Setter for <code>public.user.email</code>.
   */
  def setEmail(value: String): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.user.email</code>.
   */
  def getEmail: String = get(2).asInstanceOf[String]

  /**
   * Setter for <code>public.user.company</code>.
   */
  def setCompany(value: UUID): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>public.user.company</code>.
   */
  def getCompany: UUID = get(3).asInstanceOf[UUID]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record1[UUID] = super.key.asInstanceOf[ Record1[UUID] ]

  /**
   * Create a detached, initialised UserRecord
   */
  def this(id : UUID, name : String, email : String, company : UUID) = {
    this()

    this.setId(id)
    this.setName(name)
    this.setEmail(email)
    this.setCompany(company)
    resetChangedOnNotNull()
  }
}
```

This is the config I use for the generator
```xml
<configuration>
  <jdbc>
    <driver>org.postgresql.Driver</driver>
    <url>jdbc:postgresql://localhost:5432/postgres</url>
    <user>postgres</user>
    <password>pgpw</password>
  </jdbc>

  <generator>
    <name>org.jooq.codegen.ScalaGenerator</name>
    <database>
      <name>org.jooq.meta.postgres.PostgresDatabase</name>
      <includes>.*</includes>
      <excludes>
           UNUSED_TABLE                # This table (unqualified name) should not be generated
         | PREFIX_.*                   # Objects with a given prefix should not be generated
         | SECRET_SCHEMA\.SECRET_TABLE # This table (qualified name) should not be generated
         | SECRET_ROUTINE              # This routine (unqualified name) ...
      </excludes>
      <inputSchema>public</inputSchema>
    </database>

    <generate/>

    <target>
      <packageName>org.jooq.berit.server</packageName>
    </target>
  </generator>
</configuration>
```

### jOOQ Version

jOOQ Community 3.19.1

### Database product and version

PostgreSQL version: 16.1 (Debian 16.1-1.pgdg120+1)

### Java Version

openjdk version "21.0.1" 2023-10-17

### OS Version

Windows 10 Enterprise

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.1

**Comment by lukaseder** [comment] 2024-01-15 09:07
Thanks for your report. This appears to be a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/15760

In my opinion, this wasn't really a bug in jOOQ, but in scalac:

- https://github.com/lampepfl/dotty/issues/18764

The bug seems to have been fixed, but not yet released, as all the releases post 3.3.1 in Maven Central are just nightly builds:

- https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/

The error still reproduces with `3.4.0-RC1-bin-20231207-16f1680-NIGHTLY`

**Comment by lukaseder** [comment] 2024-01-15 09:49
I'm reopening this, given that the `scalac` compilation error still persists after all this time. I suspect we need to work around this problem.

**Comment by larochef** [comment] 2024-01-15 09:59
Just for information, the scalac fix wasn't included in the 3.3.x RCs when I watched, I tried with 3.4.0-RC1 and code generation worked

**Comment by lukaseder** [comment] 2024-01-15 10:25
> I tried with 3.4.0-RC1 and code generation worked

Thanks, I'll try again...

**Comment by lukaseder** [comment] 2024-01-15 10:31
Ah, I see. My mistake was that `repo1.maven.org` is no longer updated. There are more recent versions listed on https://central.sonatype.com/artifact/org.scala-lang/scala3-compiler_3

**Comment by lukaseder** [comment] 2024-01-15 10:57
Also "fun" stuff from compiling with 3.4.0:

```
[WARNING] C:/Users/lukas/jOOQ/3.20/workspace/jOOQ-pro/jOOQ-test-codegen/jOOQ-test-codegen-scala-3/src/test/scala/org/jooq/codegen/test/unqualifiedschemapublic/db/public/tables/T2.scala:144:45: `_` is deprecated for wildcard arguments of types: use `?` instead
[WARNING] C:/Users/lukas/jOOQ/3.20/workspace/jOOQ-pro/jOOQ-test-codegen/jOOQ-test-codegen-scala-3/src/test/scala/org/jooq/codegen/test/unqualifiedschemapublic/db/s/tables/T1.scala:134:123: The syntax `x: _*` is no longer supported for vararg splices; use `x*` instead
```

This language's stance on backwards compatibility keeps amazing me...

**Comment by lukaseder** [comment] 2024-01-15 11:06
So many regressions in this compiler. I also run into this now, after fixing others:

```
[ERROR] C:/Users/lukas/jOOQ/3.20/workspace/jOOQ-pro/jOOQ-test-codegen/jOOQ-test-codegen-scala-3/src/test/scala/org/jooq/codegen/test/storedprocedures/db/routines/POutOnly_2.scala:33:6: error overriding method configuration in trait Attachable of type (): org.jooq.Configuration;
  method configuration in class AbstractQueryPart of type (): org.jooq.Configuration has weaker access privileges; it should be public
```

**Comment by lukaseder** [comment] 2024-01-15 11:27
There's more:

```
[ERROR] C:/Users/lukas/jOOQ/3.20/workspace/jOOQ-pro/jOOQ-test-codegen/jOOQ-test-codegen-scala-3/src/test/scala/org/jooq/codegen/test/daos/db/AbstractSpringDAOImpl.scala:23:15: method deleteById overrides nothing
```

Probably a mismatch between scala varargs overriding Java varargs?

```
[ERROR] C:/Users/lukas/jOOQ/3.20/workspace/jOOQ-pro/jOOQ-test-codegen/jOOQ-test-codegen-scala-3/src/test/scala/org/jooq/codegen/test/daos/db/tables/daos/DaosPkDao.scala:44:15: error overriding method deleteById in class AbstractSpringDAOImpl of type (ids: Seq[Integer]): Unit;
  method deleteById of type (ids: Seq[Integer]): Unit needs `override` modifier
```

But the `override` modifier is right there in jOOQ's generated sources.

I might have another look later, possibly reporting some issues to the scalac team, but this really feels like beta testing a language that I personally don't think was necessary in the first place. I'm not convinced Scala 3 was a good thing at all. Hard to see how jOOQ can derive a meaningful cost / benefit ratio from these efforts, including a business case - perhaps making the `ScalaGenerator` closed source, once it produces Scala 3 code (https://github.com/jOOQ/jOOQ/issues/12180)?

**Comment by lukaseder** [comment] 2024-01-15 11:32
I'm listening the the Benny Hill theme while digesting these changes:

![image](https://github.com/jOOQ/jOOQ/assets/734593/70032a49-764b-42ad-9ddd-54074d2b8fed)

**Comment by 7Hazard** [comment] 2024-01-15 16:34
> I'm listening the the Benny Hill theme while digesting these changes:
> 
> ![image](https://private-user-images.githubusercontent.com/734593/296743123-70032a49-764b-42ad-9ddd-54074d2b8fed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMzY2NzIsIm5iZiI6MTcwNTMzNjM3MiwicGF0aCI6Ii83MzQ1OTMvMjk2NzQzMTIzLTcwMDMyYTQ5LTc2NGItNDJhZC05ZGRkLTU0MDc0ZDJiOGZlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQxNjMyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWVmODJlZGMwMjI2MGViYTg0MTE2ZWM5ZTIyMTZmMzljY2YxYTY0YzdjNWE2YWUyYzA2MjlhZGEyYzc3NTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x45CAc7uMAkILYJQ8fmXwHiEcjB8uxuCgXV76bEBe_Q)
> 
> From here: https://dotty.epfl.ch/docs/reference/changed-features/wildcards.html

Makes me really reconsider why we went with Scala over Kotlin or Java.

**Comment by larochef** [comment] 2024-01-16 08:57
For the available scala versions, the best, I think, is to look in the releases page of the github repo to get the versions:
https://github.com/lampepfl/dotty/releases 

at least for these versions we should have more confidence that the non regression suite will be ok than for the nightly versions

**Comment by lukaseder** [comment] 2024-08-29 11:32
I'm ironing out the last issues that I've seen in integration tests on our end with Scala 3.5.0. It looks like we can finally formally support Scala 3 in jOOQ 3.20 via:

- https://github.com/jOOQ/jOOQ/issues/12180

**Closed by lukaseder** 2024-08-29 11:32 UTC
Labels: T: Defect, C: Code Generation, C: Integration: Scala, P: Medium, R: Fixed, E: All Editions
