### ISSUE TITLE
Disambiguate generated object names of view and table valued function when they share the same name

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#13702] opened 2022-06-22 18:37 UTC
### Expected behavior

No warning message.

### Actual behavior

I recently ran `CREATE EXTENSION pg_stat_statements` against the `public` schema. My database has two schemas: `public` and `splinterlands`.

This led to JOOQ generating the following error message:

```
[WARNING] Ambiguous type name      : The object public.pg_stat_statements generates a type
io.bazari.database.schema.public_.tables.PgStatStatements which conflicts with the existing type
io.bazari.database.schema.public_.tables.PgStatStatements on some operating systems. Use a custom generator strategy to disambiguate the types.
```

Two things are odd about this:
1. The new and existing type are identical. There is no case-sensitivity difference between them.
2. Only one schema has this extension installed, so there should be no ambiguity or conflict.

### Steps to reproduce the problem

- If the problem relates to code generation, please post your code generation configuration

```
<plugin>
	<groupId>org.jooq</groupId>
	<artifactId>jooq-codegen-maven</artifactId>
	<version>3.16.6</version>
	<executions>
		<execution>
			<id>jooq-codegen</id>
			<phase>generate-sources</phase>
			<goals>
				<goal>generate</goal>
			</goals>
			<configuration>
				<logging>WARN</logging>
				<jdbc>
					<url>jdbc:postgresql://${database.host}/${database.name}</url>
					<user>${database.username}</user>
					<password>${database.password}</password>
				</jdbc>
				<generator>
					<database>
						<name>org.jooq.meta.postgres.PostgresDatabase</name>
						<includes>.*</includes>
						<excludes>(?i:(pg_catalog|information_schema)\..*)</excludes>
					</database>
					<target>
						<packageName>io.bazari.database.schema</packageName>
						<directory>${project.build.directory}/generated-sources/java</directory>
					</target>
					<generate>
						<records>false</records>
						<pojos>false</pojos>
						<interfaces>false</interfaces>
						<daos>false</daos>
						<sequences>false</sequences>
						<sequenceFlags>false</sequenceFlags>
						<queues>false</queues>
					</generate>
				</generator>
			</configuration>
		</execution>
	</executions>
</plugin>
```

### Versions

- jOOQ: 3.16.6
- Java: openjdk version
```
"17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```
- Database (include vendor): Postgresql 14.4.1
- OS: Microsoft Windows [Version 10.0.19044.1766]
- JDBC Driver (include name if inofficial driver): `org.postgresql:postgresql:42.3.4`

**Comment by lukaseder** [comment] 2022-06-23 07:41
Thanks for your report. I can reproduce this. Will look into it right away.

**Comment by lukaseder** [comment] 2022-06-23 07:51
The full query executed by `PostgresDatabase` to fetch all the tables is this one (using integration test input schemas):

```sql
select
  tables.table_schema,
  tables.table_name,
  tables.specific_name,
  tables.description,
  tables.table_type,
  tables.view_definition
from (
  select
    information_schema.tables.table_schema,
    information_schema.tables.table_name,
    information_schema.tables.table_name as specific_name,
    pg_catalog.pg_description.description,
    case
      when information_schema.tables.table_type = 'VIEW' then 'VIEW'
      else 'TABLE'
    end as table_type,
    information_schema.views.view_definition
  from information_schema.tables
    join pg_catalog.pg_namespace
      on information_schema.tables.table_schema = pg_catalog.pg_namespace.nspname
    join pg_catalog.pg_class
      on (
        pg_catalog.pg_class.relname = information_schema.tables.table_name
        and pg_catalog.pg_class.relnamespace = pg_catalog.pg_namespace.oid
      )
    left outer join pg_catalog.pg_description
      on (
        pg_catalog.pg_description.objoid = pg_catalog.pg_class.oid
        and pg_catalog.pg_description.objsubid = 0
      )
    left outer join information_schema.views
      on (
        information_schema.tables.table_schema = information_schema.views.table_schema
        and information_schema.tables.table_name = information_schema.views.table_name
      )
  where (
    information_schema.tables.table_schema in (
      'public', 'multi_schema', 'information_schema', 'pg_catalog', 's_5507', 's_7070_a', 
      's_7070_b', 's_7271_d', 's_7271_r', 's_7274', 's_7496', 's_7685', 's_7495', 
      's_10305_a'
    )
    and (information_schema.tables.table_schema, information_schema.tables.table_name) not in (
      select pg_catalog.pg_namespace.nspname, pg_catalog.pg_class.relname
      from pg_catalog.pg_class
        join pg_catalog.pg_namespace
          on pg_catalog.pg_class.relnamespace = pg_catalog.pg_namespace.oid
      where pg_catalog.pg_class.relkind = 'm'
    )
  )
  union all
  select
    pg_catalog.pg_namespace.nspname::varchar,
    pg_catalog.pg_class.relname::varchar,
    pg_catalog.pg_class.relname::varchar,
    pg_catalog.pg_description.description,
    'MATERIALIZED_VIEW' as table_type,
    ''
  from pg_catalog.pg_class
    join pg_catalog.pg_namespace
      on pg_catalog.pg_class.relnamespace = pg_catalog.pg_namespace.oid
    left outer join pg_catalog.pg_description
      on (
        pg_catalog.pg_description.objoid = pg_catalog.pg_class.oid
        and pg_catalog.pg_description.objsubid = 0
      )
  where (
    pg_catalog.pg_namespace.nspname in (
      'public', 'multi_schema', 'information_schema', 'pg_catalog', 's_5507', 's_7070_a', 
      's_7070_b', 's_7271_d', 's_7271_r', 's_7274', 's_7496', 's_7685', 's_7495', 
      's_10305_a'
    )
    and pg_catalog.pg_class.relkind = 'm'
  )
  union all
  select
    information_schema.routines.routine_schema,
    information_schema.routines.routine_name,
    information_schema.routines.specific_name,
    '',
    'FUNCTION' as table_type,
    ''
  from information_schema.routines
    join pg_catalog.pg_namespace
      on information_schema.routines.specific_schema = pg_catalog.pg_namespace.nspname
    join pg_catalog.pg_proc
      on (
        pg_catalog.pg_proc.pronamespace = pg_catalog.pg_namespace.oid
        and ((pg_catalog.pg_proc.proname || '_') || cast(pg_catalog.pg_proc.oid as varchar)) = information_schema.routines.specific_name
      )
  where (
    information_schema.routines.routine_schema in (
      'public', 'multi_schema', 'information_schema', 'pg_catalog', 's_5507', 's_7070_a', 
      's_7070_b', 's_7271_d', 's_7271_r', 's_7274', 's_7496', 's_7685', 's_7495', 
      's_10305_a'
    )
    and pg_catalog.pg_proc.proretset
  )
) as tables
order by 2 -- actual ordering is different
```

It produces these duplicate tables names:

```
|table_schema|table_name        |specific_name            |description|table_type|view_definition                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|------------|------------------|-------------------------|-----------|----------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|public      |pg_stat_statements|pg_stat_statements_756892|           |FUNCTION  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|public      |pg_stat_statements|pg_stat_statements       |           |VIEW      | SELECT pg_stat_statements.userid,¶    pg_stat_statements.dbid,¶    pg_stat_statements.toplevel,¶    pg_stat_statements.queryid,¶    pg_stat_statements.query,¶    pg_stat_statements.plans,¶    pg_stat_statements.total_plan_time,¶    pg_stat_statements.min_plan_time,¶    pg_stat_statements.max_plan_time,¶    pg_stat_statements.mean_plan_time,¶    pg_stat_statements.stddev_plan_time,¶    pg_stat_statements.calls,¶    pg_stat_statements.total_exec_time,¶    pg_stat_statements.min_exec_time,¶    pg_stat_statements.max_exec_time,¶    pg_stat_statements.mean_exec_time,¶    pg_stat_statements.stddev_exec_time,¶    pg_stat_statements.rows,¶    pg_stat_statements.shared_blks_hit,¶    pg_stat_statements.shared_blks_read,¶    pg_stat_statements.shared_blks_dirtied,¶    pg_stat_statements.shared_blks_written,¶    pg_stat_statements.local_blks_hit,¶    pg_stat_statements.local_blks_read,¶    pg_stat_statements.local_blks_dirtied,¶    pg_stat_statements.local_blks_written,¶    pg_stat_statements.temp_blks_read,¶    pg_stat_statements.temp_blks_written,¶    pg_stat_statements.blk_read_time,¶    pg_stat_statements.blk_write_time,¶    pg_stat_statements.wal_records,¶    pg_stat_statements.wal_fpi,¶    pg_stat_statements.wal_bytes¶   FROM pg_stat_statements(true) pg_stat_statements(userid, dbid, toplevel, queryid, query, plans, total_plan_time, min_plan_time, max_plan_time, mean_plan_time, stddev_plan_time, calls, total_exec_time, min_exec_time, max_exec_time, mean_exec_time, stddev_exec_time, rows, shared_blks_hit, shared_blks_read, shared_blks_dirtied, shared_blks_written, local_blks_hit, local_blks_read, local_blks_dirtied, local_blks_written, temp_blks_read, temp_blks_written, blk_read_time, blk_write_time, wal_records, wal_fpi, wal_bytes);|
```

So, this isn't really a false positive. It's a true positive, given that this extension installs both a `VIEW` and a (table valued) `FUNCTION` by the same name. The code generator can't handle both of these.

The workaround is the one suggested in the warning, i.e. to implement a generator strategy.

I'm changing this issue here into a feature request, namely to support this out of the box, though I'm not sure if this is possible in a backwards compatible way...

**Comment by cowwoc** [comment] 2022-06-23 18:48
@lukaseder It would be great to handle this automatically (in the next major version if nothing else). In the meantime, perhaps you could improve the error message. When the two names are identical you could mention the type, as such:

```
[WARNING] Ambiguous type name      : The object public.pg_stat_statements generates a type
io.bazari.database.schema.public_.tables.PgStatStatements (function) which conflicts with the existing type
io.bazari.database.schema.public_.tables.PgStatStatements (view) on some operating systems. Use a custom generator strategy to disambiguate the types.
```

**Comment by cowwoc** [comment] 2022-06-23 18:50
Also, out of curiosity, why are functions generated into the `tables` package instead of a separate `functions` package? That is another way to make error message clearer.

**Comment by lukaseder** [comment] 2022-06-24 07:00
> It would be great to handle this automatically (in the next major version if nothing else)

No promises about priorities here. This seems like such an edge case. It's rare for an RDBMS to allow two objects sharing the same name in the same namespace, let alone users taking advantage of this? It's the first time this showed up in many years of jOOQ's existence, so I'm thinking this really is an edge case, even within PostgreSQL.

> In the meantime, perhaps you could improve the error message.

That's a great idea. Will do separately: https://github.com/jOOQ/jOOQ/issues/13718

> Also, out of curiosity, why are functions generated into the `tables` package instead of a separate `functions` package? That is another way to make error message clearer, and avoid this conflict altogether.

Because they're table valued functions, not ordinary functions. Ordinary functions are in the `routines` package. Yes, it would prevent the conflict, and you can very easily achieve exactly this by implementing a custom generator strategy, as suggested. Just override the package name for `org.jooq.meta.postgres.PostgresTableValuedFunction` types. Yes, we could change this, but that would be an incompatible change, and cause tons of side effects, so I'm not convinced that enough is known about this edge case here to take action. The workaround is very simple.

> What actually happens now? Does neither class get generated? Does only one get generated?

The first as reported by the query wins. Which is random, currently.

**Comment by lukaseder** [comment] 2022-07-05 12:58
Closing as a duplicate of https://github.com/jOOQ/jOOQ/issues/7141

**Closed by lukaseder** 2022-07-05 12:58 UTC
Labels: T: Enhancement, C: Code Generation, C: DB: PostgreSQL, P: Medium, R: Duplicate, E: All Editions
