### ISSUE TITLE
DSL.coalesce lacking support for Condition

### ISSUE THREAD

**Issue by ciaccia** [jOOQ/jOOQ#7990] opened 2018-10-29 14:36 UTC
Consider the following SQL query:
```sql
SELECT * FROM tbl AS t WHERE coalesce(t.fieldA > t.fieldB, true)
```
Where we want to return all the columns where fieldA is greater than fieldB or one of them is null. Without `coalesce` we can write the same query but with more conditions, for example:

```sql
SELECT * FROM tbl AS t WHERE t.fieldA IS null OR t.fieldB IS NULL OR t.fieldA > t.fieldB
```

To my knowledge the first version of this query cannot be expressed in jOOQ, since [DSL.coalesce() ](http://www.jooq.org/javadoc/3.11.0/org/jooq/impl/DSL.html#coalesce-org.jooq.Field-org.jooq.Field...-) only supports `Field<T>` or values but not `Condition`.

Ideally we should be able to write something like this:
```java
DSL.select().from(TBL).where(DSL.coalesce(TBL.FIELDA.gt(TBL.FIELDB), Boolean.TRUE));
```

**Comment by lukaseder** [comment] 2018-10-29 15:27
Thank you very much for your report.

Indeed, a lot of API could profit from an improvement where `Condition <: Field<Boolean>`. There's a relevant feature request, which I've now reopened for re-consideration: #3867. I'm undecided whether this is going to be a good idea from an API design perspective - there are many open questions.

Overloading individual methods to accept both `Condition` and `Field<Boolean>` is practical in some cases, namely when the number of parameters is limited, or when the default type is `Condition` (in case of which we're already overloading the method with `Field<Boolean>`, see e.g. the `SelectWhereStep.where()` clause).

With functions like `DSL.coalesce()`, overloading might be overkill. There are many of these functions, including also aggregate functions, window functions, and many more.

In any case, there's always `DSL.field(Condition)` and `DSL.condition(Field<Boolean>)` to wrap one type into the other.

**Comment by ciaccia** [comment] 2018-11-05 08:42
Hi Lukas,
Thank you for your hint, I was not aware of `DSL.field(Condition)`. This should be enough for me.

Also the discussion about the feature request #3867 is interesting. From my limited knowledge in jOOQ internals it sounds reasonable, but as you said there are many open questions you can only answer...

**Comment by lukaseder** [comment] 2018-11-19 10:18
I've given this some additional thought. Adding a `Condition` accepting overload everywhere, where a `Field<T>` type is accepted is not practical. This feature requests asks for doing this for `DSL.coalesce()`. For consistency reasons, we would have to do it everywhere. So, if this idea is going to be supported in the future, then it can only happen through #3867.

Hence, I'm closing this as a duplicate of #3867

**Closed by lukaseder** 2018-11-19 10:18 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Enhancement
