### ISSUE TITLE
SQL Translation Error

### ISSUE THREAD

**Issue by bendi** [jOOQ/jOOQ#8765] opened 2019-06-10 12:38 UTC
This is MySQL/MariaDB dialect: https://dev.mysql.com/doc/refman/5.5/en/expressions.html#temporal-intervals 
### SQL translator incorrectly translates this query:

```sql
select now() - interval 1 day
```

### Parser output:

```sql
Unexpected token or missing query delimiter: [1:27] select now() - interval 1 [*]day
```

### Expected output:
```
+------------------------+
| now() - interval 1 day |
+------------------------+
| 2019-06-09 14:34:04    |
+------------------------+
```

**Comment by lukaseder** [comment] 2019-06-13 12:47
I have created two new feature requests: #8789 for the numeric interval literals, and #8790 for the string literals. The numeric ones, I'll implement right away.

I'm closing this as a duplicate of the other two new features.

**Closed by lukaseder** 2019-06-13 12:47 UTC
Labels: C: Parser, E: All Editions, P: Medium, T: Defect
