### ISSUE TITLE
Are JOOQ statements not reusable?

### ISSUE THREAD

**Issue by markuswernig** [jOOQ/jOOQ#9008] opened 2019-08-06 06:55 UTC
Hi all
I have a repository class within a Spring/Kotlin project that tries to reuse a statement like this:

```kotlin
@Repository
class MyRepository(
    private val dsl: DSLContext
) {
//...
val stmt = dsl.select(something).from(somewhere).join(somethingelse)

fun getSomethingById(id: Long) {
    val result = stmt.where(somewhere.id.eq(id)).fetch()
    //...
}

fun getSomethingByName(name: String) {
    val result = stmt.where(somewhere.name.eq(name)).fetch()
    //...
}
}
```

This does not seem to work, though, when the same method gets called multiple times in the same thread. When, eg. getSomethingById() is called sequentially for id1, id2, id3, I see the following getting generated by JOOQ:

1) "SELECT ... FROM SOMEWHERE ... WHERE SOMEWHERE.ID = id1"
2) "SELECT ... FROM SOMEWHERE ... WHERE SOMEWHERE.ID = id1 AND SOMEWHERE.ID = id2"
3) "SELECT ... FROM SOMEWHERE ... WHERE SOMEWHERE.ID = id1 AND SOMEWHERE.ID = id2 AND SOMEWHERE.ID = id3"
Obviously only the first call will work.

Is this the expected behaviour? 
Looking at https://www.jooq.org/doc/latest/manual/sql-building/dynamic-sql/ I thought this was supposed to work.
If so, is there another way to achieve reuse of that statement?

Thx, Markus

**Comment by markuswernig** [comment] 2019-08-06 09:27
Found this in the meantime: https://stackoverflow.com/questions/55197331/jooq-reusing-copying-queries

So it looks like this workaround works, but it doesn't really reuse anything, just prevents code duplication:

class MyRepository(
private val dsl: DSLContext
) {
//...
private fun stmt(): SelectConditionStep<Record> = dsl.select(something).from(somewhere).join(somethingelse)

fun getSomethingById(id: Long) {
val result = stmt().where(somewhere.id.eq(id)).fetch()
//...
}

fun getSomethingByName(name: String) {
val result = stmt().where(somewhere.name.eq(name)).fetch()
//...
}

So is there no way to really reuse the query?

**Comment by knutwannheden** [comment] 2019-08-07 07:58
Unfortunately, since the DSL API is not immutable, the "reuse" you are looking for is currently not possible with jOOQ.

In addition to the StackOverflow question I would here also like to mention this blog entry, which also shows how to do dynamic SQL with jOOQ in a functional way: https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq/.

Providing an immutable DSL API is definitely on our list for the next major release: #2198.

I will close this issue as a duplicate of #2198. Please reopen if I missed something.

**Closed by knutwannheden** 2019-08-07 07:58 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Duplicate, T: Enhancement
