### ISSUE TITLE
Forced type with conversion from boolean to string fails with row value expressions

### ISSUE THREAD

**Issue by erlendk** [jOOQ/jOOQ#5148] opened 2016-03-15 07:10 UTC
Using jOOQ 3.7, Java 6 pro version:

I have a table, let's call it "FOO", in an Oracle database which has a column varchar2(1) for storing "boolean" values, which we can call "BAR". I'm generating this table with the forced type `StringBoolean` which uses a `org.jooq.Converter<String, Boolean>` for converting between string and boolean values. The string literals are `"J"` (true) and `"N"` (false). When using FOO.BAR in a where-clause like this: ` ... .where(FOO.BAR.equal(false))` it renders like `... where "FOO"."BAR" = 'N'`, which is correct. But if i use it in a row value expression, like this: ` ... .where(row(FOO.BAR).equal(false))`, it renders like this: `... where ("FOO"."BAR") = ((0))`, which generates an "ORA-01722: invalid number".

The following anti-test kind of reveals the bug (it passes):

```
DSLContext dsl = DSLFactory.createRenderOnlyContext();
       
String sql = dsl
    .selectCount()
    .from(FOO)
    .where(row(FOO.BAR).equal(false))
    .getSQL(ParamType.INLINED);

assertThat(sql).endsWith("((0))");
```

**Comment by lukaseder** [comment] 2016-03-15 12:28
Thank you very much for reporting. This is a known, unfortunate limitation of the current implementation  of the jOOQ API, which does not coerce bindings and converters to bind variables that aren't "sufficiently close" to the column containing the binding or converter.

I'm closing this issue here as a duplicate of #4556

**Comment by lukaseder** [comment] 2016-03-15 12:29
The workaround here is the same as in #4556. To pass the column reference with an explicit bind variable creation:

```java
String sql = dsl
    .selectCount()
    .from(FOO)
    .where(row(FOO.BAR).equal(val(false, FOO.BAR)))
    .getSQL(ParamType.INLINED);
```

**Comment by lukaseder** [comment] 2016-03-15 12:36
Hmm, let me reopen this. I think that this might be a bit easier to fix for row value expression predicates *in particular*, rather than the general issue mentioned in #4556

**Comment by lukaseder** [comment] 2016-03-15 14:46
After further review, I don't think there's an easy way to fix this for row.

**Closed by lukaseder** 2016-03-15 14:46 UTC
Labels: C: DB: Oracle, C: Functionality, P: Medium, R: Duplicate, T: Defect
