### ISSUE TITLE
Provide contextual data to be passed to a converter

### ISSUE THREAD

**Issue by basanthjenuhb** [jOOQ/jOOQ#13933] opened 2022-08-30 05:03 UTC
### Use case

We use Jooq for generating queries.
One of things that jooq provides us is, contextual field generation
```
DSLContext context = DSL.using(POSTGRES);
context.data("key1", "val2");
context.data("key2", "val2");
```
This data is available in any generators that are associated
```
public class CustomGenerator<R extends Record, X extends Table<R>, T> implements Generator<R, X, T> {

    @Override
    public Field<T> apply(GeneratorContext<R, X, T> context) {
        var data = context.configuration().data();
        if (data.key1 == "val1") {
            // return field1;
        } else {
            // return field2;
        }
    }
}
```
This is a very powerful feature.
Because based on the context you can have custom logic to map the logical field to any physical field.

Now, the same logic can be extended to converters.
```
public class CurrencyConverter implements Converter<BigInteger, Currency> {

    @Override
    public Currency from(BigInteger value, Context context) {
        var data = context.configuration.data();
        var format = data.get("CURRENCY_FORMAT"); // return USD/INR etc
        return new Currency(value, format);
    }
    
}
```

### Use case
- So based on input user request of "Currency format"(USD/INR/GBP), we could convert the currency in jooq layer itself

_No response_

### jOOQ Version

Latest Pro edition

### Database product and version

Postgres Latest

### Java Version

8,11,17

### OS Version

M<acos Latest

### JDBC driver name and version (include name if unofficial driver)

Postgres JDBC Latest

**Comment by lukaseder** [comment] 2022-08-30 06:26
Thanks for your suggestion. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/13801

**Closed by lukaseder** 2022-08-30 06:26 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, E: All Editions
