### ISSUE TITLE
JOOQ meta getTables(name) and getTables(String) behavior

### ISSUE THREAD

**Issue by lalithsuresh** [jOOQ/jOOQ#7686] opened 2018-07-25 22:57 UTC
### Expected behavior and actual behavior:

I'm trying to get a table by name from JOOQ Meta.
```java
System.out.println(using.meta().getTables().get(0));
// prints "CURR"."HOSTS"

System.out.println(using.meta().getTables().get(0).getName());
// prints HOSTS
```

But then, if I use getTables(String) or getTables(Name):
```java
System.out.println(conn.meta().getTables(name("CURR", "HOSTS")));
// prints []

System.out.println(conn.meta().getTables(name("HOSTS")));
// prints []

System.out.println(conn.meta().getTables("HOSTS"));
// prints []

System.out.println(conn.meta().getTables("CURR.HOSTS"));
// prints []
```

How can I get a table or a field by name? Note, I need to get this from meta (and do not have access to the output of the code generator). 

Thanks in advance!

### Versions:

- jOOQ: 3.11.1
- Java: 1.8.101
- Database (include vendor): Derby
- OS: OSX
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2020-06-29 11:17
I cannot reproduce this with jOOQ 3.14. Perhaps this was a duplicate of #7835? Closing this as "works for me"

**Closed by lukaseder** 2020-06-29 11:17 UTC
Labels: C: DB: Derby, C: Functionality, E: All Editions, P: Medium, T: Defect
