### ISSUE TITLE
Field<byte[]>.compare(LIKE, Field<byte[]>) Generation Broken for Postgres

### ISSUE THREAD

**Issue by mbach979** [jOOQ/jOOQ#9587] opened 2019-11-22 15:56 UTC
### Expected behavior and actual behavior:

LIKE is supported on binary datatypes for a number of databases (H2 and Postgres for example).  The JOOQ DSL does not currently have overloads for like(Field<byte[]>), which is a separate issue/enhancement.  However, the workaround seems to be to use the Field.compare() method with the LIKE comparator.  

```java
field(name("col1"), byte[].class).compare(Comparator.LIKE, field(name("col2"), byte[].class))
```

This works for H2, but not for Postgres.  

For Postgres, this generates the following SQL:

```sql
cast("col1" as varchar) like "col2"
```

which Postgres then correctly complains about when used in a query:

```
ERROR: operator does not exist: character varying ~~ bytea
```

Because there is no LIKE operator between character and byte types.

The offending code seems to be org.jooq.CompareCondition:124 which is attempting to auto-cast the LHS of the comparison to a String without considering the RHS datatype.

### Versions:

- jOOQ: 3.12.1
- Java: 1.8
- Database (include vendor): Postgres (9.6.11-1)
- OS: Windows 7
- JDBC Driver (include name if inofficial driver): Postgres 42.2.6

**Comment by lukaseder** [comment] 2019-11-25 11:21
Thank you very much for your report.

The cast has been added a long time ago for convenience (jOOQ 2.0.5: https://github.com/jOOQ/jOOQ/issues/1159), when people want to match decimal parts of a number, e.g. `'123456' like '1234%'`.

I wonder what the rule should be here. There are at least two ways to fix this:

- Cast only non-binary types
- Cast only numeric types
- Cast only when the rhs operator (the pattern) is a `String` type

Each approach has tradeoffs, with a risk of introducing regressions...

**Comment by lukaseder** [comment] 2019-11-25 11:22
What would be your opinion here, @knutwannheden ?

**Comment by knutwannheden** [comment] 2020-01-10 21:32
I think the first alternative sounds best. Possibly even in combination with the third.

**Comment by lukaseder** [comment] 2024-01-17 16:56
See also:

- https://github.com/jOOQ/jOOQ/issues/16073
- https://github.com/jOOQ/jOOQ/issues/16101

I'll implement this as a new feature in jOOQ (#16101). Instead of retrofitting existing operators, I'd rather introduce new one with a different name, e.g. `binaryLike`. There are many other such functions and operators in PostgreSQL, so this isn't really about the `LIKE` operator alone.

Closing this as a duplicate of #16101

**Closed by lukaseder** 2024-01-17 16:56 UTC
Labels: T: Defect, C: Functionality, C: DB: PostgreSQL, P: Medium, E: All Editions
