### ISSUE TITLE
Unrecognized function

### ISSUE THREAD

**Issue by lrweck** [jOOQ/jOOQ#14250] opened 2022-11-17 19:46 UTC
Hey!

I was looking at https://www.jooq.org/translate/ and I think I found a bug. It appears that JOOQ does not recognize `clock_timestamp()` as a valid function (PostgreSQL specific, I think)

**Comment by lukaseder** [comment] 2022-11-18 11:03
Duplicate of https://github.com/jOOQ/jOOQ/issues/8078

**Closed by lukaseder** 2022-11-18 11:03 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, E: All Editions
