### ISSUE TITLE
Don't select row after update or insert while only exists identity key 

### ISSUE THREAD

**Issue by mumutu** [jOOQ/jOOQ#6001] opened 2017-03-22 15:04 UTC
Hi my issue is related with #1859  and is similar with #5940 

I am using Mysql  and my table has only one AI Primary key, with 3.7.x it works perfectly when turn to 3.9.x , I found every time I insert or update via a recorder an additional query would be executed..and I found it in 3.9.x  `org.jooq.impl.TableRecordImpl#setReturningIfNeeded` will always return the identity key so It seems no way to stop the additional query. 
In the #5940 A workaround was given , it can solve this problem well, but I using the RecordListener to achieve the auditable feature (e.g CREATE_TIME, CREATE_USER),  the workaround makes it useless..then I spend a whole day to learn how to achieve goal with VisitListener....Unfortunately it is difficult to me .. it seems non trivial to do it before dive deep in the code....So ..any suggestion Thanks..

**Comment by lukaseder** [comment] 2017-03-23 15:02
Thank you for your report. I wonder, is this really a different issue from #5940? If so, how is it different?

**Comment by mumutu** [comment] 2017-03-24 07:21
Maybe is the same in the internal~ but people's needs is varied ， `insert` `update` `store` make three interface for people so they maybe want different configs to control

**Comment by lukaseder** [comment] 2017-07-20 13:59
I'll close this as a duplicate of #5940, as I'm not sure how this is different from the current description.

**Comment by lukaseder** [comment] 2017-07-20 14:21
I may have closed this too quickly. The way I understand you, you'd like to control whether `insert()`, or `update()` calls produce any "returning" semantics at all. Yes, we can certainly add such settings for jOOQ 3.10

**Comment by lukaseder** [comment] 2017-07-20 14:24
I've created a new issue for this - which makes the requirement a bit clearer: https://github.com/jOOQ/jOOQ/issues/6438.

I'm closing this as a duplicate of #6438 now. Feel free to reopen if you still think there is a misunderstanding.

**Closed by lukaseder** 2017-07-20 14:24 UTC
Labels: C: DB: MySQL, C: Functionality, P: Medium, T: Defect

**Comment by lukaseder** [comment] 2017-07-28 13:46
This fix has now been released in jOOQ 3.9.5. Your further feedback would be very welcome

**Comment by mumutu66** [comment] 2017-07-30 06:08
Yes you are right~Thanks a lot~
