### ISSUE TITLE
DSLContext.batchStore() executes INSERT rather than UPDATE if previous delete transaction for a particular row gets rolled back

### ISSUE THREAD

**Issue by vsriram92** [jOOQ/jOOQ#9755] opened 2020-01-23 12:11 UTC
### Expected behavior:
DSLContext.batchStore() Should execute UPDATE statement.

### Actual Behaviour :
DSLContext.batchStore() executes INSERT

### Steps to reproduce the problem:
Consider a table Employee (EmployeeNo, EmployeeName) with EmployeeNo as primarykey with few data
1. Create a transaction
2. Try deleting a record using batchDelete
3. Rollback the transaction.
4. Try to update the same record using batchStore
5. batchStore() executes insert query rather than update query

### Effect:
Throws - Unique index or primary key violation exception

### Versions:

- jOOQ: 3.10.0
- Java: 8
- Database (include vendor): MSSQL
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): com.microsoft.sqlserver

**Comment by lukaseder** [comment] 2020-01-23 21:17
Thanks a lot for your suggestion. This is a duplicate of https://github.com/jOOQ/jOOQ/issues/5157.

It seems indeed, that under certain conditions, it would be desireable to have transaction aware `UpdatableRecord` instances, which revert their changes to a previous state upon rolling back a transaction.

**Closed by lukaseder** 2020-01-23 21:17 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Support request
