### ISSUE TITLE
Meta.ddl() generates broken DDL for Postgres triggers

### ISSUE THREAD

**Issue by mgramin** [jOOQ/jOOQ#16191] opened 2024-01-30 15:56 UTC
### Expected behavior

We expect that `Meta.ddl()` exports a valid DDL for triggers for Postgres

### Actual behavior

Meta.ddl() exports broken DDL for triggers for Postgres:

```sql
do $$
begin
  if (
    exists (
      select 1 as "one"
      from information_schema.routines
      where (
        (routine_schema = "public")
        and (routine_name = 'last_updated_function')
        and (data_type = 'trigger')
      )
    )
    and not exists (
      select 1 as "one"
      from information_schema.triggers
      where (
        (trigger_schema = "public")
        and (event_object_table = 'store')
        and (trigger_name = 'last_updated')
      )
    )
  ) then
    execute 'drop function "public"."last_updated_function"';
  end if;
  execute 'create function "public"."last_updated_function"()
returns trigger
language plpgsql
as
$trg$
begin
  EXECUTE FUNCTION last_updated();
  return new;
end;
$trg$';
  execute 'create trigger "public"."last_updated"
before update on "public"."store"
for each row
execute function "public"."last_updated_function"()';
end;
$$
```

### Steps to reproduce the problem

Create a table in with a simple trigger:

```sql
CREATE TABLE public.store (
	store_id serial4 NOT NULL,
	manager_staff_id int4 NOT NULL,
	address_id int4 NOT NULL,
	last_update timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT store_pkey PRIMARY KEY (store_id)
);

-- Table Triggers
create trigger last_updated before
update
    on
    public.store for each row execute function last_updated();
```

Run this code:

```java
        Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:6000/postgres", "postgres", "postgres");
        Configuration configuration = new DefaultConfiguration()
                .set(conn).set(SQLDialect.POSTGRES);
        Meta meta = using(configuration).meta();

        DDLExportConfiguration ddlExportConfiguration = new DDLExportConfiguration().flags(DDLFlag.TRIGGER);

        Arrays.stream(meta
                        .filterTables(v -> v.getTableType() != TableOptions.TableType.VIEW)
                        .filterSchemas(v -> v.getName().equalsIgnoreCase("public"))
                        .ddl(ddlExportConfiguration)
                        .queries())
                .map(Object::toString)
                .forEach(System.out::println);
```

Executing the resulting query against a different database or schema leads to the error:
```sql
SQL Error [42703]: ERROR: column "public" does not exist
```

### jOOQ Version

jOOQ Professional Edition 3.19.3

### Database product and version

PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

### Java Version

openjdk 17.0.2 2022-01-18

### OS Version

Microsoft Windows [Version 10.0.19044.2846]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment] 2024-02-02 13:11
Thanks a lot for your report. I'll have a look at this soon.

**Comment by lukaseder** [comment] 2024-02-13 15:14
This is the same issue as these ones:

- https://github.com/jOOQ/jOOQ/issues/16245
- https://github.com/jOOQ/jOOQ/issues/15392

The feature isn't supported yet. Though we shouldn't export invalid SQL, so the statements should be excluded for now, until #15392 is implemented.

Closing this as a duplicate of #16245

**Closed by lukaseder** 2024-02-13 15:14 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: Professional Edition, E: Enterprise Edition

**Comment by lukaseder** [comment] 2024-02-13 16:08
Same as with #16245:

> As a workaround (if you don't need the triggers), pass a `DDLExportConfiguration` to the `ddl()` method, excluding the triggers using the `DDLExportConfiguration.flags()` method.
