### ISSUE TITLE
jooq-codegen: Regression from 3.17.17 to 3.18.8 - TIMESTAMP NOT NULL DEFAULT NOW() generates @Nullable field

### ISSUE THREAD

**Issue by mvankampen-cais** [jOOQ/jOOQ#15981] opened 2023-12-21 20:36 UTC
### Expected behavior

A table with the following schema 

```
create table example (
    created_at                                       timestamp default now() not null
);
```
Should generate a java class with a getter for a field like this: 
```
/**
 * Getter for <code>example.created_at</code>.
 */
public LocalDateTime getCreatedAt() {
    return (LocalDateTime) get(1);
}
```

### Actual behavior

Starting from version 3.18.8 (possibly 3.18.x) it generates the getter with `@Nullable` like this

```
/**
 * Getter for <code>example.created_at</code>.
 */
@Nullable
public LocalDateTime getCreatedAt() {
    return (LocalDateTime) get(1);
}
```

### Steps to reproduce the problem

Use the following DDL

```
create table example (
    created_at                                       timestamp default now() not null
);
```

use jooq-codegen with versions 3.17.17 (generates correctly) and 3.18.8 (generates incorrectly)

### jOOQ Version

JOOQ Codegen 3.18.8

### Database product and version

Postgres 13

### Java Version

openjdk 17.0.8.1 2023-08-24

### OS Version

MacOs Ventura running on an Mac M1 Pro

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.1

**Comment by lukaseder** [comment] 2023-12-22 10:09
Thanks for your report.

This isn't a regression, see:

- https://github.com/jOOQ/jOOQ/issues/10212
- https://github.com/jOOQ/jOOQ/issues/15963

And various other issues. In short: The field is nullable prior to insertion. There's no perfect solution to this, but the current (since 3.18) implementation at least isn't wrong, even if some users may find it annoying.

Closing as duplicate of https://github.com/jOOQ/jOOQ/issues/15963

**Closed by lukaseder** 2023-12-22 10:09 UTC
Labels: T: Defect, C: Code Generation, P: Medium, E: All Editions
