### ISSUE TITLE
Allow overriding of `org.jooq.util.GenerationUtil.convertToIdentifier` without replacing generator

### ISSUE THREAD

**Issue by tekacs** [jOOQ/jOOQ#5964] opened 2017-03-11 12:24 UTC
For Scala use, it would be useful to be able to replace the current implementation of [org.jooq.util.GenerationUtil.convertToIdentifier][cti].

At the moment, the generator backticks keywords, unpicks setters and then escapes all remaining characters. Due to the high incidence of special characters in our enum type identifiers, we would prefer to simply backtick everything (as we have historically done). For clarification:

current behaviour: `<1m` -> `_3c1m`
preferred behaviour: `<1m` -> ``` `<1m` ```

Since Scala allows almost arbitrary strings (other than identifiers) inside backticks, the latter identifier naming is dramatically more useful for us. Unfortunately, [the current generator][tcg] uses a hardcoded reference to the aforementioned `convertToIdentifier` to perform this mangling, making it quite difficult to override.

Any chance this functionality could be moved to the GeneratorStrategy? Thanks!

[cti]: https://github.com/jOOQ/jOOQ/blob/66edc06dc32d55487b6b9a7128aca9ada359a455/jOOQ-codegen/src/main/java/org/jooq/util/GenerationUtil.java#L294
[tcg]: https://github.com/jOOQ/jOOQ/blob/66edc06dc32d55487b6b9a7128aca9ada359a455/jOOQ-codegen/src/main/java/org/jooq/util/JavaGenerator.java#L2056

**Comment by lukaseder** [comment] 2017-03-12 16:53
Thanks for the suggestion. We'll look into it.

**Comment by lukaseder** [comment] 2021-11-10 10:03
We already allow for overriding the identifier strategy using `GeneratorStrategy::getJavaIdentifier`. There's no need to introduce another mechanism. However, as you mentioned, that static utility method is currently called by the `JavaGenerator` directly, because enum literals aren't defined by the `GeneratorStrategy`, see https://github.com/jOOQ/jOOQ/issues/10881

I'll close this as a duplicate of https://github.com/jOOQ/jOOQ/issues/10881.

**Closed by lukaseder** 2021-11-10 10:03 UTC
Labels: T: Enhancement, C: Code Generation, C: Integration: Scala, P: Medium, E: All Editions
