### ISSUE TITLE
Configuration lost when multiselect field is converted

### ISSUE THREAD

**Issue by pawelgosztyla** [jOOQ/jOOQ#13438] opened 2022-04-08 17:29 UTC
When a multiselect field is converted inside record.into([fields]), for example to multiselect field with subset of fields, then the configuration is lost.

### Expected behavior
For example in the following context:

```
        RecordMapper<Record, List<Child>> mapper = record -> {
            
            return record.into(multiset(
                select(
                    ChildSchema.ID,
                    ChildSchema.NAME
                )
                    .from(ChildSchema.TABLE)
                    .where(ChildSchema.PARRENT_ID.eq(ParentSchema.ID))
            ).as("children").convertFrom(c -> {
                // here c has wrong configuration
                return c.into(Child.class);
            })).component1();
        };

        Result<Record2<UUID, Result<Record3<UUID, UUID, String>>>> records = dslContext().select(
            ParentSchema.ID,
            multiset(
                select(
                    ChildSchema.ID,
                    ChildSchema.ID2,
                    ChildSchema.NAME
                )
                    .from(ChildSchema.TABLE)
                    .where(ChildSchema.PARENT_ID.eq(ParentSchema.ID))
            ).as("children")
        ).from(ParentSchema.TABLE).where(ParentSchema.ID.eq(id)).fetch();

        return records.map(mapper).get(0);
```

Serialization to Child class should use the provided configuration. For example if org.jooq.conf.Settings.setMapConstructorParameterNames(true) is used then the DefaultRecordMapper should use constructor parameters.

### Actual behavior
Wrong configuration is used when converting record to Child class (without 'mapConstructorParameterNames' enabled)

However, if I manually attach configuration to record before conversion:
```
        RecordMapper<Record, List<Child>> mapper = record -> {
            
            return record.into(multiset(
                select(
                    ChildSchema.ID,
                    ChildSchema.NAME
                )
                    .from(ChildSchema.TABLE)
                    .where(ChildSchema.PARRENT_ID.eq(ParentSchema.ID))
            ).as("children").convertFrom(c -> {
                c.attach(dslContext().configuration());
                return c.into(Child.class);
            })).component1();
        };
```
then it works as expected

### Versions

- jOOQ: 3.16.6-SNAPSHOT
- Java: java SE 17
- Database (include vendor): PostgreSQL 14.0
- OS: macOS 12.3.1
- JDBC Driver (include name if inofficial driver):  org.postgresql:postgresql:42.3.3

**Comment by lukaseder** [comment] 2022-04-19 09:23
Thanks for your report.

I'm not sure what artifact we're chasing here, but when I translate your test case to something equivalent in our integration test database:

```java
            configuration.settings().setMapConstructorParameterNames(true);

            RecordMapper<Record, List<Child>> mapper = record -> {
                return record.into(multiset(
                    select(
                        T_BOOK.ID,
                        T_BOOK.TITLE
                    )
                        .from(T_BOOK)
                        .where(T_BOOK.AUTHOR_ID.eq(T_AUTHOR.ID))
                ).as("children").convertFrom(c -> {
                    // here c has wrong configuration
                    System.out.println(c.configuration().settings().isMapConstructorParameterNames());
                    return c.into(Child.class);
                })).component1();
            };

            Result<Record2<Integer, Result<Record2<Integer, String>>>> records = ctx.select(
                T_AUTHOR.ID,
                multiset(
                    select(
                        T_BOOK.ID,
                        T_BOOK.TITLE
                    )
                    .from(T_BOOK)
                    .where(T_BOOK.AUTHOR_ID.eq(T_AUTHOR.ID))
                ).as("children")
            ).from(T_AUTHOR).where(T_AUTHOR.ID.eq(1)).fetch();

            println(records.map(mapper).get(0));
```

Then on both 3.17.0-SNAPSHOT and 3.16.6-SNAPSHOT, I'm getting the expected result:

```
true
true
[Child[id=1, title=1984], Child[id=2, title=Animal Farm]]
```

I'm closing this as another duplicate of https://github.com/jOOQ/jOOQ/issues/12269

I'll be happy to review a fully reproducible test case (we have a template here: https://github.com/jOOQ/jOOQ-mcve, which helps make sure the example is minimal and *complete*, such that there are no doubts about any possible misconfigurations such as e.g. the wrong jOOQ version number being used, etc.)

There may still be a bug somewhere, but I can't reproduce it from your description.

**Closed by lukaseder** 2022-04-19 09:23 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
