### ISSUE TITLE
Add support for CockroachDB JOIN hints

### ISSUE THREAD

**Issue by trourance** [jOOQ/jOOQ#15437] opened 2023-08-02 10:25 UTC
### Use case

As other RDBMS do, cockroachdb also supports JOIN hints: https://www.cockroachlabs.com/docs/stable/sql-grammar#opt_join_hint
It might be particularly useful to workaround some bad query plans due to some wrong row estimate (e.g https://github.com/cockroachdb/cockroach/issues/84461). 

### jOOQ Version

jOOQ Professional Edition 3.18.2

### Database product and version

CockroachDB 22.9

### Java Version

openjdk version "11.0.16.1"

### OS Version

Linux

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment] 2023-08-03 06:39
Thanks for your suggestion. I'll investigate this soon. Some hints may be possible to add as emulations, others might be worth adding to the API given that they can be emulated elsewhere.

I can't promise anything, though. Hints are very hard to standardise across dialects.

**Comment by trourance** [comment] 2023-08-03 07:56
> I can't promise anything, though. Hints are very hard to standardise across dialects.
Of course, the syntax is so different between dialects. 

However, it would be great to have an alternative that allows to write custom join, because atm my only option is to write plain SQL in order to use `LEFT MERGE/HASH JOIN`, right ?

**Comment by lukaseder** [comment] 2023-08-06 09:01
Yes, plain SQL is probably the only option for you right now.

A related issue is to support SQL Server's syntax: https://github.com/jOOQ/jOOQ/issues/5694, regrettably, with the same concerns regarding API surface.

**Comment by lukaseder** [comment] 2023-11-08 10:02
I've been getting a few more requests for similar hints in the recent past, by email. I think it'll be worth implementing something for jOOQ 3.19.

There's probably a least common denominator that can be implemented here. Plus, in order to avoid further overload "explosion," I'll probably skip the usual 5 plain SQL template convenience overloads, as they're always convenience and thus redundant.

**Comment by lukaseder** [comment] 2023-11-08 13:05
I'll implement this in jOOQ 3.19 via a more vendor agnostic new API:

- https://github.com/jOOQ/jOOQ/issues/15807

Marking this as duplicate of the above.

**Closed by lukaseder** 2023-11-08 13:05 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, R: Duplicate, E: Professional Edition, E: Enterprise Edition
