### ISSUE TITLE
SQL Translation Error

### ISSUE THREAD

**Issue by obaidkhan3** [jOOQ/jOOQ#13519] opened 2022-05-04 15:07 UTC
### SQL translator incorrectly translates this query:

```sql
SELECT [QryS1-Summary Rolling 12 mos physician data].[Fiscal Period], 
[QryS1-Summary Rolling 12 mos physician data].Sub, [QryS1-Summary Rolling 12 mos physician data].Major, 
[QryS1-Summary Rolling 12 mos physician data].[AU Number], [QryS1-Summary Rolling 12 mos physician data].[EE Number], 
[QryS1-Summary Rolling 12 mos physician data].[Phys Name], [QryS1-Summary Rolling 12 mos physician data].[Rolling 12 wRVUs], 
IIf([QryS1-Summary Rolling 12 mos physician data]!Sub In ("GENETICS"),"",
IIf([Rolling 12 wRVUs]<[Level A],"10",
IIf([Rolling 12 wRVUs]<[Level B],(([Rolling 12 wRVUs]-[Level A])/([Diff AB]/[Tier Diff AB]) [A]),
IIf([Rolling 12 wRVUs]<[Level C],(([Rolling 12 wRVUs]-[Level B])/([Diff BC]/[Tier Diff BC]) [B]),
IIf([Rolling 12 wRVUs]<[Level D],(([Rolling 12 wRVUs]-[Level C])/([Diff CD]/[Tier Diff CD]) [C]),
IIf([Rolling 12 wRVUs]<[Level E],(([Rolling 12 wRVUs]-[Level D])/([Diff DE]/[Tier Diff DE]) [D]),
IIf([Rolling 12 wRVUs]<[Level F],(([Rolling 12 wRVUs]-[Level E])/([Diff EF]/[Tier Diff EF]) [E]),
IIf([Rolling 12 wRVUs]<[Level G],(([Rolling 12 wRVUs]-[Level F])/([Diff FG]/[Tier Diff FG]) [F]),"90")))))))) AS [wRVU MGMA %tile],
 Round([10th %tile],0) AS [wRVU 10th %tile],
  Round([25th %tile],0) AS [wRVU 25th %tile], 
 Round([38th %tile],0) AS [wRVU 38th %tile],
  Round([Median],0) AS [wRVU Median], 
  Round([63rd %tile],0) AS [wRVU 63rd %tile],
   Round([75th %tile],0) AS [wRVU 75th %tile], 
   Round([90th %tile],0) AS [wRVU 90th %tile], 
   [QryS1-Summary Rolling 12 mos physician data].[Department Name], 
   [Current - MGMA Work RVU].Connector, [QryS1-Summary Rolling 12 mos physician data].[Current FTE], 
   [QryW01-FTE Adjusted Averages by Sub].[Average RVUs], 
   IIf([QryS1-Summary Rolling 12 mos physician data]!Sub In ("GENETICS"),"",
   IIf([Average RVUs]<[Level A],"10",
   IIf([Average RVUs]<[Level B],(([Average RVUs]-[Level A])/([Diff AB]/[Tier Diff AB]) [A]),
   IIf([Average RVUs]<[Level C],(([Average RVUs]-[Level B])/([Diff BC]/[Tier Diff BC]) [B]),
   IIf([Average RVUs]<[Level D],(([Average RVUs]-[Level C])/([Diff CD]/[Tier Diff CD]) [C]),
   IIf([Average RVUs]<[Level E],(([Average RVUs]-[Level D])/([Diff DE]/[Tier Diff DE]) [D]),
   IIf([Average RVUs]<[Level F],(([Average RVUs]-[Level E])/([Diff EF]/[Tier Diff EF]) [E]),
   IIf([Average RVUs]<[Level G],(([Average RVUs]-[Level F])/([Diff FG]/[Tier Diff FG]) [F]),"90")))))))) AS [Average RVU MGMA %tile]

FROM ((([QryS1-Summary Rolling 12 mos physician data] 
LEFT JOIN [qryH0 - MGMA Work RVU Tiers

**Comment by lukaseder** [comment] 2022-05-05 07:48
Thanks a lot for your report. There are multiple issues here, it seems:

- https://github.com/jOOQ/jOOQ/issues/13523: Support for MS Access `!` operator to separate identifier parts, just like `.`
- https://github.com/jOOQ/jOOQ/issues/13524: Support for parsing `""` as an empty string, instead of `''`
- The fact that your query ends abruptly after `LEFT JOIN [qryH0 - MGMA Work RVU Tiers `. This is just a flaw in your input data.

I'm closing this issue here as a duplicate of the above. #13523 can be implemented easily, I think. #13524 will be much harder as the ambiguities of recognising `"` as a valid string literal delimiter vs an identifier delimiter (not in MS Access, but elsewhere) will be tricky.

**Closed by lukaseder** 2022-05-05 07:48 UTC
Labels: T: Enhancement, P: Medium, E: All Editions, C: Parser
