### ISSUE TITLE
NullPointerException when JDBC driver returns null on getGeneratedKeys call using ZDAL5 driver on MySQL

### ISSUE THREAD

**Issue by messense** [jOOQ/jOOQ#8993] opened 2019-07-29 03:19 UTC
### Expected behavior and actual behavior:

When underlying JDBC drive doesn't support `getGeneratedKeys` and returns `null` when calling `getGeneratedKeys()`, jOOQ raises `NullPointerException` in `AbstractDMLQuery. executeReturningGeneratedKeysFetchAdditionalRows `:

https://github.com/jOOQ/jOOQ/blob/4d6bbc902baf6e667c64eec69030a9a78b644b21/jOOQ/src/main/java/org/jooq/impl/AbstractDMLQuery.java#L1116-L1121

The `if rs != null` check does not work because the variable `rs` is a `DefaultResultSet` which is not `null` but its private member variable `delegate` could be `null`. So when calling `DefaultResultSet.next()` which in turn calls `this.delegate.next()` raises NPE.

I think it might be good to check JDBC's `DatabaseMetaData.supportsGetGeneratedKeys` before calling `getGeneratedKeys`.

### Versions:

- jOOQ: 3.11.11
- Java: java version "1.8.0_151"
- Database (include vendor): MySQL
- OS: macOS
- JDBC Driver (include name if inofficial driver): ZDAL5

**Comment by knutwannheden** [comment] 2019-07-29 08:38
Thank you very much for your report and provided PR!

According to the JDBC API the `Statement#getGeneratedKeys()` method should either return an empty `ResultSet` or throw an `SQLFeatureNotSupportedException` exception, if this feature isn't supported. So before making any changes in jOOQ, I would like to report this as a bug against the JDBC driver and see what feedback we get.

> I think it might be good to check JDBC's `DatabaseMetaData.supportsGetGeneratedKeys` before calling `getGeneratedKeys`.

We will investigate this in a separate issue: #8996. Many JDBC drivers are not very reliable when it comes to these `supportXyz()` methods. Have you already checked what your driver returns for `DatabaseMetaData.supportsGetGeneratedKeys()`?

> JDBC Driver (include name if inofficial driver): ZDAL5

What driver is this? Can you provide a link to the actual driver being used? We would like to be able to reproduce this issue on our side. The best would be if you could provide us with an MCVE: https://github.com/jOOQ/jOOQ-mcve.

**Comment by messense** [comment] 2019-07-29 08:52
> Have you already checked what your driver returns for `DatabaseMetaData.supportsGetGeneratedKeys()`

My JDBC driver returns `false`for `DatabaseMetaData.supportsGetGeneratedKeys()`.

> What driver is this? Can you provide a link to the actual driver being used?

ZDAL5 is a close source JDBC driver used in [Ant Financial](https://www.antfin.com/index.htm?locale=en_us)

**Comment by knutwannheden** [comment] 2019-07-29 09:02
> My JDBC driver returns `false` for `DatabaseMetaData.supportsGetGeneratedKeys()`.

OK. That is then at least correct.

> ZDAL5 is a close source JDBC driver used in Ant Financial

Ouch. Is this a commercial product for which you have a support contract? Would you be willing to raise a support ticket pertaining to the wrong behavior of `Statement#getGeneratedKeys()`?

Further, since your driver apparently doesn't support `Statement#getGeneratedKeys()`, I would be interested to see the code which reproduces this situation. It seems like you are executing a DML statement with a `RETURNING` clause. Could you instead change the query?

**Comment by messense** [comment] 2019-07-29 09:09
> Would you be willing to raise a support ticket pertaining to the wrong behavior of `Statement#getGeneratedKeys()`?

I'll try to do that.

> Could you instead change the query?

I'm currently workaround the issue by using DSL without `RETURNING` instead of  using generated `Dao`s to insert data.

**Comment by messense** [comment] 2019-07-29 09:11
> I would be interested to see the code which reproduces this situation

Using generated `Dao`s for example let's say `UserDao.insert(...)` reproduces this situation.

**Comment by messense** [comment] 2019-07-29 09:33
BTW, it feels a little odd for `public void DAOImpl.insert(...)` to generate a SQL with a `RETURNING` clause?

**Comment by knutwannheden** [comment] 2019-07-29 09:38
OK, knowing that this behavior is triggered by `DAO#insert()` helps. If possible I would still be interested in a full stack trace or a reproducable example, so that we can evaluate the different solutions / workarounds.

Does your patch for instance correctly update the record's primary key fields?

> BTW, it feels a little odd for public void DAOImpl.insert(...) to generate a SQL with a RETURNING clause?

This is used to update the record's primary key fields, in case these values are provided by the DB. If you don't require this behavior, then you can use `Settings#withReturnIdentityOnUpdatableRecord()` to disable this feature, which should then also solve your problem for now.

**Comment by messense** [comment] 2019-07-29 09:41
> Does your patch for instance correctly update the record's primary key fields?

Yes, I have the primary key value hard-coded.

> you can use `Settings#withReturnIdentityOnUpdatableRecord()` to disable this feature

Thanks for the tip, I'll try that.

**Comment by knutwannheden** [comment] 2019-07-29 09:55
> Thanks for the tip, I'll try that.

Let me know if this works out for you.

**Comment by knutwannheden** [comment] 2019-07-29 10:09
Also note that it seems to me like not supporting `getGeneratedKeys()` can be quite a serious limitation in your JDBC driver. Other MySQL drivers don't have this limitation, so I would also raise this question with the vendor of your JDBC driver.

**Comment by messense** [comment] 2019-07-29 11:32
Tried `java -Dorg.jooq.settings.returnIdentityOnUpdatableRecord=false` with no luck, still NPE.

**Comment by messense** [comment] 2019-07-29 11:42
Oh I see, `returnIdentityOnUpdatableRecord` feature isn't released yet.

**Comment by knutwannheden** [comment] 2019-07-29 11:53
Right. That was added later and will be part of the 3.12 release (which is expected to be released this August). Would you be able to test if this works for you using the current jOOQ 3.12 SNAPSHOT release? Alternatively you could test with the hack described here: https://github.com/jOOQ/jOOQ/issues/7962#issuecomment-432516313.

**Comment by lukaseder** [comment] 2019-08-13 09:15
> @messense I think it might be good to check JDBC's DatabaseMetaData.supportsGetGeneratedKeys before calling getGeneratedKeys.

I'm not convinced that a driver that manages to return a `null` ResultSet from `getGeneratedKeys()` produces a trustworthy value on `DatabaseMetaData.supportsGetGeneratedKeys` :)

> @messense ZDAL5 is a close source JDBC driver used in Ant Financial

Any solution we provide here will not be integration tested by us, so this is another indicator that we shouldn't implement too many hacks, or call JDBC `DatabaseMetaData` methods.

> @knutwannheden Also note that it seems to me like not supporting getGeneratedKeys() can be quite a serious limitation in your JDBC driver

Well, you're probably spoiled by having used ojdbc a lot in the past, which has the best generated keys support out there :) In summary, pretty much all other JDBC drivers suck at this in hundreds of different ways...

> @messense Tried java -Dorg.jooq.settings.returnIdentityOnUpdatableRecord=false with no luck, still NPE.

That looks like a very interesting way to pass those settings. Perhaps we should implement it :) (this currently doesn't work for any setting)

> Alternatively you could test with the hack described here

Or, proxy your JDBC driver (e.g. using jOOQ's `DefaultConnection` etc) and "fix" your JDBC driver's `Statement.getGeneratedKeys()` method

**Comment by lukaseder** [comment] 2019-08-13 09:33
After closer introspection and review, I do agree with your PR's intent. Our `DefaultStatement` and similar wrapper types should not be opinionated about any JDBC driver implementation. If they do choose to violate the JDBC spec by returning `null` where they're not supposed to, we should pass along this `null` value instead of wrapping it and causing unrelated side effects. This does not affect jOOQ's internals in any way, but it does seem to fix your issue.

**Comment by lukaseder** [comment] 2019-08-13 09:36
@messense Could you try applying this patch on your build? https://github.com/jOOQ/jOOQ/commit/e2a761e8d2007b2306057cb0c094be66c7ecedb4

We could backport it to 3.11.12, soon.

**Closed** 2019-08-13 09:35 UTC
Labels: C: DB: MySQL, C: Functionality, E: All Editions, P: Medium, R: Fixed, T: Defect
