### ISSUE TITLE
Regression in PostgreSQL query using 'x' = ANY (ARRAY [(SELECT ARRAY ['x'])]) style quantified comparison predicate on multi dimensional arrays

### ISSUE THREAD

**Issue by Bzil** [jOOQ/jOOQ#15980] opened 2023-12-21 16:03 UTC
### Expected behavior

We have our application running in jooq 3.17.4 and we want to bump jooq to 3.18.4 (and after in 3.19.x) but we encounter some issues. 

When we use jooq to generate query like : 
```sql
SELECT "mcve"."test"."code", "mcve"."test"."parent_code"
FROM "mcve"."test"
WHERE "mcve"."test"."code" <> 'value' AND
       ('value' = ANY ("mcve"."test"."parent_code") OR "mcve"."test"."code" = ANY (ARRAY [(SELECT "mcve"."test"."parent_code" FROM "mcve"."test" WHERE "mcve"."test"."code" = 'value')]))
;
```

Our current code looks like
```java 
        Condition condition = includeRoot ? trueCondition() : TEST.CODE.ne("");
        if (StringUtils.isNotEmpty(code)) {
            condition = condition.and(
                    or(
                            // get children
                            value(code).equal(any(TEST.PARENT_CODE)),
                            // get parents
                            TEST.CODE.equal(any(array(select(TEST.PARENT_CODE)
                                    .from(TEST)
                                    .where(TEST.CODE.equal(code))
                                    .asField())))
                    )
            );
        }

        return ctx.select(TEST.CODE, TEST.PARENT_CODE)
                .from(TEST)
                .where(condition)
                .fetch(TEST.CODE):
```

See mcve for full example

### Actual behavior

in jooq 3.18.7, application raise exception like

```
        org.jooq.exception.DataAccessException: SQL [select "mcve"."test"."code", "mcve"."test"."parent_code" from "mcve"."test" where ("mcve"."test"."code" <> ? and (? = any ("mcve"."test"."parent_code") or "mcve"."test"."code" = (select "mcve"."test"."parent_code" from "mcve"."test" where "mcve"."test"."code" = ?)))]; ERROR: operator does not exist: character varying = character varying[]
  Indice : No operator matches the given name and argument types. You might need to add explicit type casts.
  Position : 179
```

we can see the current request is not well generated

### Steps to reproduce the problem

https://github.com/Bzil/jOOQ-mcve/tree/main/jOOQ-mcve-java-postgres

### jOOQ Version

3.18.7

### Database product and version

 PostgreSQL 12.12 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

### Java Version

openjdk 21.0.1 2023-10-17 LTS OpenJDK Runtime Environment Zulu21.30+15-CA (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Zulu21.30+15-CA (build 21.0.1+12-LTS, mixed mode, sharing)

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment] 2023-12-22 10:16
Thanks a lot for your report. I can reproduce the issue with your MCVE. Will look into it right away.

**Comment by lukaseder** [comment] 2023-12-22 10:29
A simpler reproducer shows the problem:

```java
public static void main(String[] args) {
    System.out.println(TEST.CODE.equal(any(array(select(TEST.PARENT_CODE)
            .from(TEST)
            .asField()))));
}
```

It renders this SQL:

```sql
"mcve"."test"."code" = (
  select "mcve"."test"."parent_code"
  from "mcve"."test"
)
```

Both `any()` and `array()` operators are completely ignored, it seems.

**Comment by lukaseder** [comment] 2023-12-22 10:37
The query itself is a bit weird though, and I'm very surprised (again) that PostgreSQL even allows it in its original form. Essentially, your comparing a scalar value with an array, extracted from a multi dimensional array, similar to this:

```sql
select 'a' = any (array[array['a', 'b'], array['b', 'c']])
```

Somehow, PostgreSQL flattens these nested arrays.

This could possibly be a regression due to jOOQ 3.18's new support for multi dimensional arrays:

- https://github.com/jOOQ/jOOQ/issues/252

And I'm kinda surprised this worked before.

**Comment by lukaseder** [comment] 2023-12-22 10:43
I mean, the fact that you used the type-unsafe `.asField()` method instead of the type safe `DSL.field(Select)` method hints at this being weird :)

**Comment by lukaseder** [comment] 2023-12-22 10:47
The regression is more likely caused by this refactoring:

- https://github.com/jOOQ/jOOQ/issues/14560

**Comment by lukaseder** [comment] 2023-12-22 11:43
The fix will also include a fix for this somewhat related issue, where the type of an empty array is erroneously cast to `int[]`:

- https://github.com/jOOQ/jOOQ/issues/15982

**Comment by lukaseder** [comment] 2023-12-22 12:54
Fixed in versions:

- 3.20.0
- 3.19.2 (https://github.com/jOOQ/jOOQ/issues/15985)
- 3.18.9 (https://github.com/jOOQ/jOOQ/issues/15986)

Thanks again for your report!

**Comment by lukaseder** [comment] 2023-12-22 13:04
Hmm, no the fix wasn't complete it seems.

**Closed** 2023-12-22 13:12 UTC
Labels: T: Defect, C: Functionality, C: DB: PostgreSQL, P: High, E: All Editions

**Comment by Bzil** [comment] 2023-12-26 09:50
Thx @lukaseder for the fix :)
