### ISSUE TITLE
Generated code uses Object[] for any array type

### ISSUE THREAD

**Issue by bannmann** [jOOQ/jOOQ#13308] opened 2022-03-20 11:23 UTC
### Expected behavior

When a PostgreSQL column uses an array type (e.g. `varchar(32)[]`), the jOOQ code generator (using DDLDatabase) should map it to an array of the corresponding Java type (e.g. `String[]`).

### Actual behavior

jOOQ maps the column to `Object[]`.

### Steps to reproduce the problem

Use the following SQL schema:

```
create table if not exists test_table
(
    id serial primary key,

    numbers integer[],
    strings varchar(32)[],
    date_times timestamp without time zone[]
);
```

Use the following code generator settings:
```
<plugin>
    <groupId>org.jooq</groupId>
    <artifactId>jooq-codegen-maven</artifactId>
    <version>${org.jooq.version}</version>
    <dependencies>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-meta-extensions</artifactId>
            <version>${org.jooq.version}</version>
        </dependency>
    </dependencies>
    <executions>
        <execution>
            <id>jooq-codegen</id>
            <goals>
                <goal>generate</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
                <generator>
                    <database>
                        <name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
                        <properties>
                            <property>
                                <key>scripts</key>
                                <value>${project.basedir}/src/main/db/schema.sql</value>
                            </property>
                            <property>
                                <key>defaultNameCase</key>
                                <value>lower</value>
                            </property>
                        </properties>
                    </database>
                </generator>
            </configuration>
        </execution>
    </executions>
</plugin>
```

I also prepared an MCVE.

### Versions

- jOOQ: 3.14.9
- Java: 11.0.13_8
- Database: none for code generation (PostgreSQL 12 at runtime)
- OS: Windows
- JDBC Driver: none for code generation (org.postgresql:postgresql:42.2.16 at runtime)

**Comment by bannmann** [comment] 2022-03-20 11:25
Here's the MCVE: https://github.com/bannmann/jOOQ-mcve/commit/3d206ebd1c064aa8af22c845ff2057223c6f6450

**Comment by bannmann** [comment] 2022-03-20 11:29
Wow, with 3.16.3 this no longer occurs. No I only need to figure out which version between 3.14.9 and 3.16.3 (inadvertently?) fixed the bug *and* does not cause too much work for my upstream dependencies when upgrading jOOQ to that version.

**Comment by lukaseder** [comment] 2022-03-21 09:14
Thanks a lot for your report. Prior to jOOQ 3.16.0, jOOQ depended on H2 1.4 internally, e.g. for the simulation of a `DDLDatabase`. H2 1.4 did not yet support standard SQL array types, like PostgreSQL. All of H2 1.4's arrays were effectively `Object[]`. As such, there was no way to mimick PostgreSQL's array behaviour in jOOQ 3.14 and 3.15 with the `DDLDatabase`.

This has changed with jOOQ 3.16.0 and https://github.com/jOOQ/jOOQ/issues/9609. I hope this helps.

Closing this as a duplicate of #9609

**Closed by lukaseder** 2022-03-21 09:14 UTC
Labels: T: Defect, C: Code Generation, P: Medium, E: All Editions
