### ISSUE TITLE
PG database when value is null , the generated sql just like ' cast (? as varchar)' so that generate Exception 

### ISSUE THREAD

**Issue by zhoutaoq** [jOOQ/jOOQ#15257] opened 2023-06-20 09:51 UTC
### Expected behavior

jooq version : 3.14.15
when execute update statement and field p_sort is null , will generate this exception: 

```
org.jooq.exception.DataAccessException: SQL [update org_organization set p_credit_code = cast(? as varchar), version = ?, p_level = ?, p_sort = cast(? as varchar), creator = ?, modifier = ?, date_created = cast(? as timestamp), parent_id = ?, p_valid = ?, p_phone = cast(? as varchar), p_code = ?, p_address = ?, p_name = ?, date_modified = cast(? as timestamp), attributes = ?, p_full_name = ?, p_person_id = ? where (id = ? and trash = ?)]; ERROR: column "p_sort" is of type integer but expression is of type varchar
  Hint: You will need to rewrite or cast the expression.
 Caused by: com.kingbase8.util.KSQLException: ERROR: column "p_sort" is of type integer but expression is of type varchar
  Hint: You will need to rewrite or cast the expression.
  Position: 103 At Line: 1, Line Position: 103
```

I look at the source and see is org jooq. Impl. DefaultBinding. AbstractBinding# sqlCast (org. Jooq. BindingSQLContext < U >, T) transformed 707 lines

### Steps to reproduce the problem

Update the integer type field of a table to null

### jOOQ Version

3.14.15

### Database product and version

pgsql

### Java Version

jdk11.0.18

### OS Version

Linux Mint 20.3

### JDBC driver name and version (include name if unofficial driver)

kingbase8-8.6.0.jar

**Comment by lukaseder** [comment] 2023-06-20 10:15
Thank you very much for your support request. Can you please provide a complete reproducer, including your jOOQ code that produces this error, as well as anything else that might be needed to reproduce this issue.

**Comment by zhoutaoq** [comment] 2023-06-21 01:22
`		this.dslContext.transaction(configuration -> {
			val update = DSL.using(configuration).update(table(tableName())).set(fieldValueMap)
					.where(field(EntitySystemColumn.ID.getName()).eq(entity.getId()).and(notTrashCondition()));
			debugSQL(update);
			update.execute();
		});`

**Comment by zhoutaoq** [comment] 2023-06-21 01:28
dslContext is a bean which type is org.jooq.DSLContext，The fieldMap contains an null value p_sort attribute

**Comment by gadfly3173** [comment] 2023-06-21 02:45
Duplicated with #11511 , this is fixed in 3.15.0, you should upgrade JOOQ version.

**Comment by zhoutaoq** [comment] 2023-06-21 02:50
I resolved the issue by upgrading the jooq version to 3.15.x

**Closed** 2023-06-21 02:52 UTC
Labels: C: Functionality, P: Medium, T: Support request, R: Feedback Pending, E: All Editions

**Comment by lukaseder** [comment] 2023-06-21 06:20
Great to hear, thanks for the feedback.

I was certain that this was caused by the lack of using generated code. Unless you have *very good* reasons  not to use code generation (the most popular one being that your schema is dynamic), I would really recommend you re-consider using code generation:
https://blog.jooq.org/why-you-should-use-jooq-with-code-generation/

You will not run into such limitations that way. If not, please always provide data type information with your `field(name, type)` expressions for the best experience with jOOQ.

**Comment by lukaseder** [comment] 2023-06-21 06:41
I have updated the Javadoc on the relevant `DSL::field` methods to recommend either using code generation instead, or at least pass an explicit `DataType` reference: 

- https://github.com/jOOQ/jOOQ/issues/15261

**Comment by zhoutaoq** [comment] 2023-06-21 06:49
Thank you for your reply, I will look into both usages

**Comment by gadfly3173** [comment] 2023-06-21 06:52
> I was certain that this was caused by the lack of using generated code. Unless you have _very good_ reasons not to use code generation (the most popular one being that your schema is dynamic), I would really recommend you re-consider using code generation: https://blog.jooq.org/why-you-should-use-jooq-with-code-generation/
> 

Type of `fieldValueMap` is `Map<org.jooq.Field, Object>`, the key is generated from `org.jooq.impl.DSL#field(java.lang.String, java.lang.Class<T>)` statement.

**Comment by lukaseder** [comment] 2023-06-21 07:36
> Type of `fieldValueMap` is `Map<org.jooq.Field, Object>`, the key is generated from `org.jooq.impl.DSL#field(java.lang.String, java.lang.Class<T>)` statement.

Interesting, but you're not passing the right `Class` reference? You said this was a duplicate of https://github.com/jOOQ/jOOQ/issues/11511, so are you just passing `Object.class`?

**Comment by gadfly3173** [comment] 2023-06-21 07:53
> so are you just passing Object.class?

I think that's the problem. In the field conversion method we used, the `fieldValueMap` was operated twice, and the `DataType` was not passed in for the second operation.Thank you for your patience and help.
