### ISSUE TITLE
Syntax error in generated SQL of ALTER INDEX or ALTER SCHEMA statement, when identifiers aren't quoted

### ISSUE THREAD

**Issue by padeledicq** [jOOQ/jOOQ#16080] opened 2024-01-15 12:19 UTC
Hi,

After upgrading from 3.18.7 to 3.19.2, the generator is failing on this statement:

```sql
ALTER INDEX produits_composes_produits_composes_ibfk1_idx RENAME TO kit_id_sous_produit_idx;
```

I get the following error, it just seems a space is missing before 'rename':
>[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.19.2:generate (generate-jooq-sources) on project scanandstock-api: Error running jOOQ code generation tool: Error while exporting schema: SQL [alter index PRODUITS_COMPOSES_PRODUITS_COMPOSES_IBFK1_IDXrename to KIT_ID_SOUS_PRODUIT_IDX]; Erreur de syntaxe dans l'instruction SQL "alter index PRODUITS_COMPOSES_PRODUITS_COMPOSES_IBFK1_IDXrename [*]to KIT_ID_SOUS_PRODUIT_IDX"; attendu "., RENAME"
>[ERROR] Syntax error in SQL statement "alter index PRODUITS_COMPOSES_PRODUITS_COMPOSES_IBFK1_IDXrename [*]to KIT_ID_SOUS_PRODUIT_IDX"; expected "., RENAME"; SQL statement:
>[ERROR] alter index PRODUITS_COMPOSES_PRODUITS_COMPOSES_IBFK1_IDXrename to KIT_ID_SOUS_PRODUIT_IDX [42001-224]

Here is my generator configuration.
```xml
          <execution>
            <id>generate-jooq-sources</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <logging>WARN</logging>
              <generator>
                <generate>
                  <pojos>true</pojos>
                  <fluentSetters>true</fluentSetters>
                  <pojosEqualsAndHashCode>true</pojosEqualsAndHashCode>
                  <generatedAnnotation>true</generatedAnnotation>
                  <generatedAnnotationType>DETECT_FROM_JDK</generatedAnnotationType>
                  <generatedAnnotationDate>true</generatedAnnotationDate>
                  <validationAnnotations>true</validationAnnotations>
                  <constructorPropertiesAnnotation>true</constructorPropertiesAnnotation>
                  <constructorPropertiesAnnotationOnPojos>true</constructorPropertiesAnnotationOnPojos>
                  <constructorPropertiesAnnotationOnRecords>true</constructorPropertiesAnnotationOnRecords>
                  <javaTimeTypes>true</javaTimeTypes>
                  <deprecated>false</deprecated>
                </generate>
                <database>
                  <name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
                  <includes>.*</includes>
                  <excludes>flyway_schema_history|event_publication</excludes>
                  <properties>
                    <property>
                      <key>sort</key>
                      <value>flyway</value>
                    </property>
                    <property>
                      <key>scripts</key>
                      <value>src/main/resources/db/migration/*.sql</value>
                    </property>
                  </properties>
                </database>
                <target>
                  <clean>true</clean>
                  <packageName>com.wallsweb.sns.data</packageName>
                  <encoding>UTF-8</encoding>
                </target>
              </generator>
            </configuration>
          </execution>
```

If you need a mcve, just ask me.

Thank you.

### jOOQ Version

3.19.2 Open Source

### Database product and version

H2

### Java Version

Oracle jdk 21

### OS Version

Windows 11

**Comment by lukaseder** [comment] 2024-01-15 12:33
Thanks a lot for your report. I can reproduce this, so no MCVE is necessary.

The reason why the integration tests didn't catch this is because we always quote identifiers by default (which would be a workaround for you here).

I'll add a generic test that checks if such whitespace is missing from all tested SQL. This isn't the first time something like this happened.

**Comment by lukaseder** [comment] 2024-01-15 12:46
The regression was introduced with this change:

- https://github.com/jOOQ/jOOQ/issues/15591

**Comment by lukaseder** [comment] 2024-01-15 12:57
Fixed in versions

- 3.20.0
- 3.19.3 (https://github.com/jOOQ/jOOQ/issues/16082)

**Closed as completed by lukaseder** 2024-01-15 12:57 UTC
Labels: T: Defect, C: Functionality, P: High, R: Fixed, E: All Editions

**Comment by padeledicq** [comment] 2024-01-15 13:12
Thank you for the quick reply and the workaround. I really have to take the habit of using quotes in SQL statements.

And thank you again for this awesome library!

**Comment by lukaseder** [comment] 2024-01-15 13:13
`ALTER SCHEMA` is also affected

**Comment by lukaseder** [comment] 2024-01-15 13:14
> I really have to take the habit of using quotes in SQL statements.

beware that makes your identifiers case sensitive in most RDBMS, including H2

**Comment by lukaseder** [comment] 2024-01-15 14:02
I haven't found any other cases than `ALTER INDEX` or `ALTER SCHEMA` with the new test.
