### ISSUE TITLE
jOOQ-codegen-gradle should lazily evaluate its configuration

### ISSUE THREAD

**Issue by jobayle** [jOOQ/jOOQ#16188] opened 2024-01-26 18:08 UTC
### Expected behavior

The jOOQ PluginExtension should evaluate its configuration as necessary, to save build time and allow lazy loading of resources.

Note: doing so is considered to be best practices by the gradle community.

### Actual behavior

Configuration is always immediately evaluated, even though no jOOQ task is to be run.

For example, this is my use case: I start a containerised PostgreSQL instance using a [SharedBuildService](https://docs.gradle.org/current/userguide/build_services.html)
I would like to use a random available port instead of a static port in case it's already in use.
Therefore to configure the jOOQ extension I have to get the JDBC URL from the SharedBuildService:

```kt
jooq {
    executions {
        create("main") {
            configuration {
                jdbc { // This action being executed immediately ...
                    username = DB_USERNAME
                    password = DB_PASSWORD
                    url = containerProvider.get().database.getJdbcUrl() // ... prevents lazy loading of the containers !
                }
```

Hence even though I'm just running `./gradlew tasks`, the containers are started!

### Steps to reproduce the problem

The following minimal `build.gradle.kts` can be used to reproduce:

```
plugins {
    java
    id("org.jooq.jooq-codegen-gradle") version "3.19.3"
}

dependencies {
    jooqCodegen("org.jooq:jooq-meta-extensions:3.18.6")
}

jooq {
    executions {
        create("kwp") {
            configuration {
                jdbc {
                    println("You should not read this message unless invoking a jOOQ task")
                }
            }
        }
    }
}
```

Then run: `gw tasks`

Output is:

```
> Configure project :
You should not read this message unless invoking a jOOQ task
org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 12; cvc-complex-type.2.4.b: The content of element 'jdbc' is not complete. One of '{"http://www.jooq.org/xsd/jooq-codegen-3.19.2.xsd":driver, "http://www.jooq.org/xsd/jooq-codegen-3.19.2.xsd":url, "http://www.jooq.org/xsd/jooq-codegen-3.19.2.xsd":schema, "http://www.jooq.org/xsd/jooq-codegen-3.19.2.xsd":user, "http://www.jooq.org/xsd/jooq-codegen-3.19.2.xsd":username, "http://www.jooq.org/xsd/jooq-codegen-3.19.2.xsd":password, "http://www.jooq.org/xsd/jooq-codegen-3.19.2.xsd":autoCommit, "http://www.jooq.org/xsd/jooq-codegen-3.19.2.xsd":properties, "http://www.jooq.org/xsd/jooq-codegen-3.19.2.xsd":initScript, "http://www.jooq.org/xsd/jooq-codegen-3.19.2.xsd":initSeparator}' is expected.

> Task :tasks
...
```

### jOOQ Version

probably all jOOQ versions

### Database product and version

unrelated

**Comment by lukaseder** [comment] 2024-01-29 13:27
Thanks for your suggestion.

What would need to be changed, specifically, to make configuration evaluation lazy?

**Comment by jobayle** [comment] 2024-01-30 17:22
Hi Lukas,

Sure, for instance at this location: https://github.com/jOOQ/jOOQ/blob/59fe044378911cb48ff5df7375865dfef4fd3e49/jOOQ-codegen-gradle/src/main/java/org/jooq/codegen/gradle/MetaExtensions.java#L80

The action (a closure) is immediately applied and the outcome is stored.

To make configuration lazy, the action should be stored and applied upon request.

**Comment by lukaseder** [comment] 2024-02-01 08:03
I think I see what you mean, @jobayle. I don't think we'll have to do this for the entire hierarchy of `MetaExtensions`. It's unlikely someone would want only the `jdbc { }` block to be evaluated lazily, but not the `configuration { }` block - nor is that delay really significant. jOOQ's `GenerationTool` always consumes the entire object in one go.

It will probably be sufficient if only `NamedConfiguration.configuration(Action)` is lazy:
https://github.com/jOOQ/jOOQ/blob/59fe044378911cb48ff5df7375865dfef4fd3e49/jOOQ-codegen-gradle/src/main/java/org/jooq/codegen/gradle/NamedConfiguration.java#L116

**Comment by jobayle** [comment] 2024-02-01 09:19
You're right, making `NamedConfiguration.configuration(Action)` lazy would be sufficient to cover all cases.

**Comment by lukaseder** [comment] 2024-03-01 12:44
So, the integration test here will be:

```kotlin
var schema = "X"

jooq {
    configuration {
        logging = Logging.DEBUG
        generator {
            database {
                name = "org.jooq.meta.extensions.ddl.DDLDatabase"
                properties {
                    property {
                        key = "sql"
                        value = """
                        create schema ${schema};
                        create table ${schema}.t (i int primary key, j int, k int)
                        """
                    }
                }
                inputSchema = schema
            }
            target {
                directory = "${projectDir}/src/generated/jooq"
                packageName = "org.jooq.codegen.gradle.test.only.configuration.db"
            }
        }
    }
}

schema = "Y"
```

With eager configuration, this produces output in `schema = "X"`. With lazy configuration, the output is for `schema = "Y"`

**Comment by lukaseder** [comment] 2024-03-01 13:03
For the record, another similar use-case for lazy configuration is using docker / testcontainers in a build. The configuration should be able to read JBDC URLs that are created at build time, but currently the URLs are accessed prematurely when the testcontainers container isn't up yet:
https://groups.google.com/g/jooq-user/c/WYKlwguBHwE

**Comment by lukaseder** [comment] 2024-03-01 13:16
So, an additional test:

```kotlin
jooq {
    configuration {
        logging = Logging.DEBUG
        generator {
            database {
                name = "org.jooq.meta.extensions.ddl.DDLDatabase"
                properties {
                    property {
                        key = "sql"
                        value = """
                        create schema s;
                        create table s.t (i int primary key, j int, k int)
                        """
                    }
                }
                inputSchema = "S"
            }
            target {
                directory = "${projectDir}/src/generated/jooq"
            }
        }
    }

    executions {
        // ...

        create("fail") {
            configuration {
                throw RuntimeException("Fail")
            }
        }
    }
}
```

With the above, obviously this should fail:

```
./gradlew jooqCodegenFail
```

But these shouldn't

```
./gradlew tasks
./gradlew jooqCodegen -x jooqCodegenFail
```

**Comment by lukaseder** [comment] 2024-03-01 13:21
Fixed in versions:

- 3.20.0
- 3.19.6 (https://github.com/jOOQ/jOOQ/issues/16400)

**Closed by lukaseder** 2024-03-01 13:21 UTC
Labels: T: Defect, C: Code Generation, P: High, E: All Editions

**Comment by lukaseder** [comment] 2024-06-12 14:35
Thanks, folks (@FrontierPsychiatrist, @jobayle). I'm currently investigating this in the context of #16318. Indeed, this change triggered the regression in IntelliJ. Reverting the change fixes the problem - though I won't revert the change, obviously. Lazy configuration is a desirable feature, and the problem doesn't appear on the command line when building with `gradle`.

The workaround is to explicitly re-declare the source sets, e.g. like this:

```kotlin
sourceSets {
    main {
        java {
            srcDir("build/generated-sources/jooq")
        }
    }
}
```

I don't think the approach using the `idea {}` plugin is the best one here, given that it doesn't really add value outside of IntelliJ, whereas the `sourceSets` re-declaration is something you could have done anyway, for any type of sources.

**Comment by lukaseder** [comment] 2024-06-12 15:44
I've looked into options for hours now, and I really don't know how to allow for both:

- Lazy configuration
- Eager discovery of source sets in IntelliJ

The source sets are generated only when the code generation task is executed due to this change, and IntelliJ obviously doesn't want to execute the task automatically, and gradle doesn't have a way of simulating the execution (I think?), so the only remaining option that I'm seeing is to offer two ways to invoke the plugin:

- Normal (non-lazy), where source sets are available automatically
- Lazy, where source sets are available only if declared explicitly by the user

**Comment by lukaseder** [comment] 2024-06-12 16:03
It'll work like this:

```kotlin
jooq {

    // Eager configuration
    configuration {
        // ...
    }

    executions {
        create("eager") {

            // Also eager configuration, source sets added eagerly, recognised by IntelliJ
            configuration {
                // ...
            }
        }

        create("lazy") {

            // Lazy configuration, source sets added lazily, not recognised by IntelliJ
            lazyConfiguration {
                // ...
            }
        }
    }
}

sourceSets {
    main {
        java {
            srcDir("... the lazy code generation target directory ...")
        }
    }
}
```

**Comment by lukaseder** [comment] 2024-06-13 08:31
I've tried looking into making all of the configuration element hierarchy lazy-enabled, e.g. to allow for things like `lazyDatabase { .. }`, `lazyJdbc { .. }`, etc. in order to offer more fine-grained control, but this really complicates dealing with configurations in the plugin. I prefer not to go down that route for now (though it might be an option in the future).

I'm still contemplating if `lazyConfiguration` is the solution though. I feel like there must be a better solution to the IntelliJ source sets problem, rather than partially reverting this cahnge here, where configurations are always lazy.

**Comment by lukaseder** [comment] 2024-06-13 08:52
On the other hand, I do think this change here was not correct according to Gradle philosophies. It is a good thing to lazy configure tasks, but that doesn't mean delaying the configuration of the task until it is actually executed. I don't see any hint in here that indicates this is a good practice:
https://docs.gradle.org/current/userguide/lazy_configuration.html

Your approach originally expects another task to *execute* first before you *configure* the code generation task, because you're using `containerProvider.get().database.getJdbcUrl()`. But perhaps that's the wrong approach in the first place. The JDBC URL can be set to a `System` property:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-system-properties/

That would also have the effect of delaying the resolution of the JDBC URL.

So, I think I'll be in favour of:

- Reverting the default to eagerly configure the task when task configuration is requested
- Allowing for explicitly delaying the task configuration in the rare case where this is desired, using a different name, e.g. `lazyConfiguration` or `delayedConfiguration`

**Comment by lukaseder** [comment] 2024-06-13 09:44
Yes, the original assumption here was wrong. Consider this build script:

```kotlin
tasks.register("x") {
    println("X")
}

tasks.create("y") {
    println("Y")
}
```

Running:

```
./gradlew projects
```

Yields:

```
> Configure project :jOOQ-test-codegen-gradle-kotlin
Y

> Task :projects
...
```

As expected, `Y` is eager configured (and thus prints its message), `X` is lazy configured (and thus doesn't print its message, because it doesn't need to be configured for the `projects` task).

However, when running:

```
./gradlew tasks
```

Then we get:

```
> Configure project :jOOQ-test-codegen-gradle-kotlin
Y

> Task :tasks
X
```

The `x` task has to be configured in order for the `tasks` task to be able to document it. So, the original example:

```
jooq {
    executions {
        create("kwp") {
            configuration {
                jdbc {
                    println("You should not read this message unless invoking a jOOQ task")
                }
            }
        }
    }
}
```

Which assumed that this won't print the message:

> Then run: `gw tasks`

Was simply wrong. The task is being *configured* (thus `configuration`), not *executed*!

This will be enough to justify reverting the work here, and introducing a `delayedConfiguration` (as an experimental thing, because I'm still not convinced that this is the correct way)

**Comment by lukaseder** [comment] 2024-06-13 09:50
New task reverting this change:

- https://github.com/jOOQ/jOOQ/issues/16821

**Comment by asm0dey** [comment] 2024-06-13 09:50
Probably the right way is to understand how to configure test containers without launching them. WHich is definitely out of scope for jOOQ, but still nice to know.

**Comment by lukaseder** [comment] 2024-06-13 11:06
@asm0dey That's certainly one way to see it, though it wouldn't be surprising if testcontainer JDBC URLs contain an unpredictable random element.

In any case, the approach using the system property is certainly viable:
https://github.com/jOOQ/jOOQ/issues/16188#issuecomment-2165038105

**Comment by asm0dey** [comment] 2024-06-13 11:14
They have an unpredictable random element: at least source

**Comment by FrontierPsychiatrist** [comment] 2024-06-13 11:19
Thank you for all the work on this @lukaseder , appreciated

**Comment by moreginger** [comment] 2024-07-31 20:55
@lukaseder - just discovered this change, I ran into it while adopting the plugin, and we ended up using the system property approach.

However, we have a multi-service build and have recently tried to add jooq codegen to a second service. Of course, the naive approach of starting two containers doesn't work, because the system property can only be set to one value. For the time being, the experimental property you've added let's us get things working.

I'm not sure what the right answer is... should we be reusing the same postgres container with different schemas, or perhaps it would be better to be able to configure the url late in a doFirst (as works with the liquibase plugin)?
Anyway, I just wanted to give you a heads up about this use case, as it wasn't one that I'd thought about, and could be difficult to support.

**Comment by lukaseder** [comment] 2024-08-01 08:39
@moreginger You can set the system property to a new value before the second execution, or, you can configure multiple executions:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-gradle/codegen-gradle-executions/

**Comment by lukaseder** [comment] 2024-08-12 07:13
The more I learn about gradle, the more it became clear that the assumptions made in this issue here were quite wrong. For example, the configuration cache that became non-experimental in recent versions hints at a configuration not being allowed to capture any state from the project model:

- https://github.com/jOOQ/jOOQ/issues/16997

So, the message here:

```
println("You should not read this message unless invoking a jOOQ task")
```

This isn't correct. The message will be printed whenever the task is *configured* (for whatever reason), not only when the task is executed.

At the same time, this:

```
url = containerProvider.get().database.getJdbcUrl() // ... prevents lazy loading of the containers !
```

Is unlikely to be the correct way to access such objects as it seems to prevent configuration cache usage, and the JDBC URL isn't available until task execution anyway, so accessing it is premature.

I already came to this conclusion before, but now with knowledge about the configuration cache, it becomes even more clear.

The much better approach here (using jOOQ tools only) is to use these system properties:

- https://github.com/jOOQ/jOOQ/issues/16188#issuecomment-2165038105

Though, there are probably other approaches too.

**Comment by asm0dey** [comment] 2024-08-13 10:37
So, do I get it right that setting up a test container is a configuration step, not execution, and therefore it should be executed during the configuration phase?

**Comment by lukaseder** [comment] 2024-08-13 11:05
> So, do I get it right that setting up a test container is a configuration step, not execution, and therefore it should be executed during the configuration phase?

No

> Or what's the correct pattern of usage of TestContainers with jOOQ?

The correct pattern is to configure jOOQ's gradle plugin to look up the connection URL at task execution time, e.g. using a System property, or whatever gradle offers. I don't know what gradle has to offer here.

Alternatively, if testcontainers can be configured to produce static connection URLs, even better.
