### ISSUE TITLE
Codegen throw NoClassDefFoundError on org/reactivestreams/Publisher

### ISSUE THREAD

**Issue by ByRicardoSimoes** [jOOQ/jOOQ#9328] opened 2019-10-03 15:35 UTC
### Expected behavior and actual behavior:

Expected behaviour would be the same as in the tutorial for jooq, as seen here:
https://www.jooq.org/doc/3.12/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step3/

ONLY difference is that I am using `mysql-connector-java-8.0.17.jar` instead of the bin. I have no idea where to get that bin from, so I am using the latest jar.

The output in cmd:

```bash
Okt 03, 2019 5:26:19 PM org.jooq.tools.JooqLogger info
INFORMATION: Initialising properties  : library.xml
Okt 03, 2019 5:26:22 PM org.jooq.tools.JooqLogger info
INFORMATION: No <inputCatalog/> was provided. Generating ALL available catalogs instead.
Exception in thread "main" java.lang.NoClassDefFoundError: org/reactivestreams/Publisher
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.jooq.impl.DSL.using(DSL.java:601)
        at org.jooq.meta.mysql.MySQLDatabase.create0(MySQLDatabase.java:527)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:260)
        at org.jooq.meta.AbstractDatabase.create(AbstractDatabase.java:249)
        at org.jooq.meta.AbstractDatabase.setConnection(AbstractDatabase.java:239)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:501)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:221)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:216)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:188)
Caused by: java.lang.ClassNotFoundException: org.reactivestreams.Publisher
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
```

### Steps to reproduce the problem (if possible, create an MCVE: 

Setup a project with a folder like in the tutorial, use `mysql-connector-java-8.0.17.jar`, call the command:
java -classpath jooq-3.12.1.jar;^
jooq-meta-3.12.1.jar;^
jooq-codegen-3.12.1.jar;^
mysql-connector-java-8.0.17.jar;. ^
org.jooq.codegen.GenerationTool library.xml

### Versions:

- jOOQ: 3.12.1
- Java: 1.8.0_202
- Database (include vendor): MySQL
- OS: Windows 10
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2019-10-03 15:47
I'm sorry for the inconvenience this is causing. We've added a new dependency in jOOQ 3.12, which we're currently not shipping with the ZIP file that you've downloaded from our website. We'll fix that ASAP: #9329

In the meantime, you can either use Maven to resolve this dependency automatically for you, or download it manually from Maven Central: https://search.maven.org/remotecontent?filepath=org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar

I hope this helps.

I'm closing this as a duplicate of #9329

**Closed by lukaseder** 2019-10-03 15:47 UTC
Labels: C: Build, E: All Editions, P: Medium, T: Support request
