### ISSUE TITLE
KeepNamesGeneratorStrategy generates ambiguous path names if implicitJoinPathTableSubtypes is activated

### ISSUE THREAD

**Issue by eitan-rosenberg** [jOOQ/jOOQ#15942] opened 2023-12-15 23:32 UTC
### Expected behavior

Valid source code like always... :-) 

### Actual behavior

Invalid source code generated :-(

For example, I have AUTHOR class that have a nested class with the same name...

[AUTHOR.java.txt](https://github.com/jOOQ/jOOQ/files/13690315/AUTHOR.java.txt)

![2023-12-16_01-08-16](https://github.com/jOOQ/jOOQ/assets/48506054/2949dc14-a364-4efe-9271-a89a5465b637)
![2023-12-16_01-03-43](https://github.com/jOOQ/jOOQ/assets/48506054/0d2b6d5b-ffe9-40eb-b5eb-2048fc9da6f2)

Any response will be appreciated

### Steps to reproduce the problem

This is my generator since 2019.
[MyGenerator.java.txt](https://github.com/jOOQ/jOOQ/files/13690332/MyGenerator.java.txt)

### jOOQ Version

3.19.0

### Database product and version

Apache Derby - 10.17.1.0

### Java Version

openjdk version "21" 2023-09-19

### OS Version

Windows 10 Home 22H2

### JDBC driver name and version (include name if unofficial driver)

org.apache.derby.jdbc.ClientDriver

**Comment by lukaseder** [comment] 2023-12-18 08:40
Thanks for your report. This seems to be a problem with the `KeepNamesGeneratorStrategy`. 

As a workaround, you can turn off the generation of those nested `Path` classes by specifying `generate.withImplicitJoinPathTableSubtypes(false)`, or you can extend the `KeepNamesGeneratorStrategy` to implement a more suitable naming strategy for those path types.

**Comment by lukaseder** [comment] 2023-12-18 09:21
Related issue: https://github.com/jOOQ/jOOQ/issues/15946

**Comment by eitan-rosenberg** [comment] 2023-12-18 09:28
Good morning.

Many thanks for the swift response.

Since my code handle KeepNamesGeneratorStrategy naming I opt for generate.withImplicitJoinPathTableSubtypes(false).
All is well now.

Season's Greetings to you all.

**Comment by lukaseder** [comment] 2023-12-18 09:41
Good for you, but the issue isn't fixed yet, so this won't be closed yet.

**Comment by lukaseder** [comment] 2023-12-18 09:50
Fixed in versions

- 3.20.0
- 3.19.1 (https://github.com/jOOQ/jOOQ/issues/15947)

Thanks again for your report!

**Closed by lukaseder** 2023-12-18 09:50 UTC
Labels: T: Defect, C: Code Generation, P: High, E: All Editions

**Comment by eitan-rosenberg** [comment] 2023-12-21 06:05
Good morning.
3.19.1 works just fine, thanks.

![image](https://github.com/jOOQ/jOOQ/assets/48506054/73000ed2-2f81-44c5-b938-80529734f2f9)
