### ISSUE TITLE
Column "rank" is confused with same aggregation function

### ISSUE THREAD

**Issue by GordeevArt** [jOOQ/jOOQ#6703] opened 2017-10-13 14:34 UTC
I have a problem using "rank" field, but I have no aggregation:

> org.springframework.jdbc.BadSqlGrammarException: dbTask; bad SQL grammar 
> 
> [select "public"."roles"."id", "public"."roles"."name", "public"."roles"."sysname", "public"."roles"."aspect" as "aspect.id", "public"."roles"."isactive" as "isActive", "public"."roles"."rank" from "public"."roles" where "public"."roles"."sysname" = ?]; 
> 
> nested exception is org.postgresql.util.PSQLException: ERROR: WITHIN GROUP is required for ordered-set aggregate rank

- jOOQ: 3.9.5
- Java: 1.8
- Database (include vendor): PostgreSQL 9.6.2
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.1.3.jre7

**Comment by lukaseder** [comment] 2017-10-13 18:37
Thank you for your report. That looks like a PostgreSQL parser bug. I don't see what could possibly be wrong with this query. Does the problem persist with version 9.6.5?

**Comment by lukaseder** [comment] 2017-10-20 10:34
I'm closing this as "worksforme" as I cannot reproduce this with the latest PostgreSQL versions.

**Closed by lukaseder** 2017-10-20 10:34 UTC
Labels: C: DB: PostgreSQL, C: Functionality, P: Medium, R: Worksforme, T: Defect

**Comment by GordeevArt** [comment] 2017-10-23 13:25
Sorry for too late answer. It was another bug with strange message. Now it works fine.
