### ISSUE TITLE
Support disabling foreign key constraints in DDLDatabase

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9156] opened 2019-09-04 09:24 UTC
Some dialects like MySQL allow to temporarily disable foreign key constraints using a command like e.g. `SET FOREIGN_KEY_CHECKS = 0`. That way `CREATE TABLE` statements presumably don't have to appear in the correct order in a DDL script.

See also #9120.

**Comment by JanecekPetr** [comment] 2019-09-04 10:09
Looks like a duplicate of #8105.

**Comment by lukaseder** [comment] 2019-09-04 10:12
And I did not even have a déjà vu! Thanks a lot for the feedback, @JanecekPetr

**Closed by lukaseder** 2019-09-04 10:12 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Enhancement
