### ISSUE TITLE
Add DSLContext.batchInsert(records).onDuplicateKeyUpdate() and Ignore()

### ISSUE THREAD

**Issue by adriancole** [jOOQ/jOOQ#3172] opened 2014-04-08 21:58 UTC
I'd love to be able to have something like this:

``` java
queries = records.stream().map(
            record -> DSL.using(context.configuration())
                .insertInto(MY_TABLE)
                .set(record)
                .onDuplicateKeyUpdate()
                .set(record))
    .toArray(Query[]::new);
context.batch(queries).execute()
```

compressed to this `context.batchInsert(records).onDuplicateKeyUpdate()`

**Comment by lukaseder** [comment] 2015-04-13 10:33
We should take inspiration from various vendor's `UPSERT` statement implementations, e.g. HANA #3887

**Comment by vicmosin** [comment] 2018-08-23 07:45
Is this gonna be implemented after all?

**Comment by lukaseder** [comment] 2018-08-23 09:02
@vicmosin Maybe, but so far, no really compelling API has been found. This change isn't just about the `batchInsert()` functionality. For such a change to be reasonable, we'd have to have similar functionality in a variety of other API as well, which needs more research (and more community traction)

**Comment by lukaseder** [comment] 2020-06-19 15:25
This has been implemented as `DSLContext.batchMerge()`: https://github.com/jOOQ/jOOQ/issues/10046, which was added for consistency reasons, along with other `MERGE` operations, such as `UpdatableRecord.merge()`: https://github.com/jOOQ/jOOQ/issues/2961

While the name was chosen to reflect `MERGE` semantics, it can execute `INSERT .. ON DUPLICATE KEY UPDATE` in MySQL style dialects, or `INSERT .. ON CONFLICT` in PostgreSQL style dialects, as suggested in the original feature request.

Closing this as a duplicate of the other issues.

**Closed by lukaseder** 2020-06-19 15:25 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Enhancement

**Comment by chihaiaalex** [comment] 2022-03-11 13:32
Hi, given a list of records, what is the equivalent of the following statement:
`INSERT INTO TEST values (1), (2), (3) ON CONFLICT DO NOTHING;`
?

**Comment by lukaseder** [comment] 2022-03-11 13:36
I'm not sure what you mean by "equivalent". Why not just run exactly that statement?

**Comment by chihaiaalex** [comment] 2022-03-11 13:48
Basically, I'm looking for the equivalent in the JOOQ API:
Would something like this:
```
var inserts = records.stream()
            .map(record -> db.insertInto(TEST)
                .set(record)
                .onConflictDoNothing())
            .toArray(Query[]::new);
db.batch(inserts).execute();
```
translate into:
 INSERT INTO TEST values (1), (2), (3) ON CONFLICT DO NOTHING;
?

**Comment by lukaseder** [comment] 2022-03-11 13:53
Why not just call `valuesOfRecords()` instead of `set()`

**Comment by chihaiaalex** [comment] 2022-03-11 14:15
I don't think it's available in the version that I'm running (3.14.15). I see it got added with 3.15. Is there any alternative to that?

**Comment by lukaseder** [comment] 2022-03-11 14:45
Yeah, upgrading 😅. You can implement it yourself. Just call `values()` several times...

**Comment by dangnhdev** [comment] 2023-02-07 14:51
> I don't think it's available in the version that I'm running (3.14.15). I see it got added with 3.15. Is there any alternative to that?

Version 3.17.6 doesn't have this too. I'm using ```DSLContext.batchMerge(records)``` while waiting.

**Comment by lukaseder** [comment] 2023-02-07 16:29
@dangnhdev  You can call `set(record)`

**Comment by dangnhdev** [comment] 2023-02-08 04:03
Currently I can't set(record) multiple times like values(). I think it's related to #13330

**Comment by lukaseder** [comment] 2023-02-08 09:29
> Currently I can't set(record) multiple times like values(). 

Sure, you can call `newRecord()` between records, or you can also use `valuesOfRecords()`. 

> I think it's related to #13330

That issue is about the `UPDATE` statement

**Comment by curioustechizen** [comment] 2025-04-11 12:58
Do I understand correctly that doing a `batchMerge()` will always imply `onDuplicateKeyUpdate()` semantics?
And if I want to achieve `batchInsert()` with `onDuplicateKeyIgnore()` semantics then I need to use the approach described in https://github.com/jOOQ/jOOQ/issues/3172#issuecomment-1065130316; while replacing `set(record)` with `valuesOfRecords()`?

**Comment by lukaseder** [comment] 2025-04-12 08:40
> Do I understand correctly that doing a `batchMerge()` will always imply `onDuplicateKeyUpdate()` semantics?

A `batchMerge` is just a batch of `UpdatableRecord::merge` (consecutive identical statements are grouped in a batch). `UpdatableRecord::merge` is specified in its Javadoc:
https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/UpdatableRecord.html#merge()

> And if I want to achieve `batchInsert()` with `onDuplicateKeyIgnore()` semantics

`batchInsert()` does not offer any upsert semantics, but perhaps, you're mixing up terms here and weren't really asking about the actual `DSLContext::batchInsert` method.

> I looked into the API a bit more and I think `valuesOfRecords` is not applicable for my case

I don't really know what "your case" is.

**Comment by curioustechizen** [comment] 2025-04-13 04:36
Sorry I think I did mix up the terms. Perhaps it helps if I start with describing my requirements.

- I have a `List<SomeTableRecord>`
- I want to insert them into `SOME_TABLE` in a batch operation 
- `SOME_TABLE` has a uniqueness constraint (on columns beyond the primary key). The batch insert operation should ignore a row if the attempt to insert it would result in a unique constraint violation.
- I want the generated SQL to have a single `ON CONFLICT` clause (as opposed to having one for each row).

This is very similar to what's described in this comment: https://github.com/jOOQ/jOOQ/issues/3172#issuecomment-1065130316

The response to that discussion led me to discover `valuesOfRecords()`. However I haven't been able to figure out how to use `valuesOfRecords()` in combination with `insertInto(SOME_TABLE).set(record)`. It seems it only works with `insertInto(SOME_TABLE, fields)` which is not applicable for me.

Does that make sense?
