### ISSUE TITLE
org.jooq.meta.extensions.jpa.JPADatabase doesn't pick up abstract entities

### ISSUE THREAD

**Issue by vitko** [jOOQ/jOOQ#17194] opened 2024-09-05 15:51 UTC
### Expected behavior

when you generate jooq classes from the jpa entities all the classes annotated with @Entity added to the MetadataSources to generate the schema, including abstract classes

### Actual behavior

JPADatabase uses ClassPathScanningCandidateComponentProvider to scan for the entity classes which only consider top level concrete classes. And if you have abstract entity class it is not added to the MetadataSources, causing hibernate to fail with unknown entity mapping errors.

### Steps to reproduce the problem

add abstract entity class, i.e.

```java
@Entity
@Table(name = "base_entity")
public class MyBaseEntity
{
}
```

and it will not be picked up by the codegen to generate table in the schema

### jOOQ Version

JOOQ community 3.14.16

### Database product and version

h2

### Java Version

openjdk 11

**Comment by lukaseder** [comment] 2024-09-10 11:00
Thanks for your report. I've tried adding base classes or interfaces to entities, and couldn't reproduce the problem. Can you please provide a complete reproducer? We have a template for reproducers here:
https://github.com/jOOQ/jOOQ-mcve

It may not be necessary to use the template, but I'll still need:

- Code generator configuration
- Example entities and super types with exact annotations, etc. to reproduce the issue

**Comment by lukaseder** [comment] 2024-09-24 13:47
I'm closing this for now as I couldn't reproduce it. Will be happy to reopen with a reproducer.

**Closed by lukaseder** 2024-09-24 13:47 UTC
Labels: T: Defect, C: Code Generation, P: Medium, R: Worksforme, C: Integration: Jakarta EE, E: All Editions
