### ISSUE TITLE
Firebird batch statements can produce java.sql.DataTruncation

### ISSUE THREAD

**Issue by perceptron8** [jOOQ/jOOQ#9992] opened 2020-03-26 14:36 UTC
Because of how batching is implemented, it's practically impossible to use `Loader` to load `String` data in batches, at least in case of Firefox which apparently needs (?) casting. I believe this is because of `query` being rendered entirely on the basis of first record in every batch.

Just after `ctx.sql(dsl.render(query));` inside `BatchSingle.executePrepared()`, `ctx.sql()` is going to be similar to `insert into "TARGET" ("DATA") values (cast(? as varchar(N)))` where `N` comes from actual length of data in the first record. This makes all records having `DATA` length being greater than `N` ignored.

I'll provide a link to MCVE in the next comment.

BTW I'd like to ask why there is no `fieldsFromTarget()` or similar method in `LoaderRowsStep` (analogous to `fieldsFromSource()`)? I'm also really curious why parameter casting is based on source data rather than target metadata (`DataType`s of `Field`s of table passed to `DSLContext.loadInto(Table<?>)`).

**Comment by perceptron8** [comment] 2020-03-26 14:40
git clone https://github.com/perceptron8/jooq-9992
cd jooq-9992
mvn test

**Comment by perceptron8** [comment] 2020-03-26 14:48
Please note that if you change selection = insertion order from `asc()` to `desc()` the test will pass.

You can also easily modify the test to verify that it's indeed about first row in every batch. Just replace `batchAll()` with `batchAfter(2)` and modify test data like so:

```
context.execute("insert into SOURCE (DATA) values ('a')");
context.execute("insert into SOURCE (DATA) values ('b')");
context.execute("insert into SOURCE (DATA) values ('cc')");
context.execute("insert into SOURCE (DATA) values ('dd')");
```

The test modified in that way will also pass.

**Comment by lukaseder** [comment] 2020-03-26 14:56
Thank you very much for your report. Indeed, this is a very unfortunate limitation in jOOQ. I believe this is a duplicate of #1749, #3398. Will verify later.

jOOQ needs to cast some bind variables at certain locations where a JDBC driver and/or database server cannot infer the data type from the SQL syntax or the first sent bind value alone. But the `INSERT` statement shouldn't be such a case.

I'll also increase the priority of #2823, which should review our general bind variable casting strategy.

**Comment by perceptron8** [comment] 2020-03-30 12:16
@lukaseder Thank you! #1749 and #3398 are more general than this, but I agree they make this issue a duplicate. At the same time my question about `fieldsFromTarget()` and source of metadata (input vs output fields) remains relevant.

**Comment by lukaseder** [comment] 2020-03-30 13:10
> At the same time my question about `fieldsFromTarget()` and source of metadata (input vs output fields) remains relevant.

Aha! That's what you get for piggy-backing unrelated things into an issue ;-) (I overlooked it, sorry. But better create two issues, next time. I'll have to create them anyway, if there's a feature request like in your case).

> BTW I'd like to ask why there is no fieldsFromTarget() or similar method in LoaderRowsStep (analogous to fieldsFromSource())? 

Yes, that makes sense. I've created #10010.

> I'm also really curious why parameter casting is based on source data rather than target metadata (DataTypes of Fields of table passed to DSLContext.loadInto(Table<?>)).

Can you please create a new issue with some more details about what's happening and why this is a problem?

**Comment by perceptron8** [comment] 2020-03-30 14:42
Thank's for creating #10010 :-) I'll create a new issue to explain my source vs target metadata related doubts.

**Comment by lukaseder** [comment] 2020-04-03 13:26
As mentioned in #10012, this issue has nothing to do with the `Loader` API, but with the `Batch` API that you're using in your test case. `BatchSingle` uses the first bind variable set's data types in isolation, instead of considering the actual statement's target types. The statement is not known to the `BatchSingle` API. It could be any string, so I'll investigate where a fix would have to go.

**Comment by lukaseder** [comment] 2020-04-03 13:38
The problem quite generic. We do pass around the target table's column type information just short before creating a `org.jooq.BindingSQLContext`, which unfortunately does not keep a reference to that data type. So `org.jooq.impl.DefaultBinding.AbstractBinding.sqlCast()`, which produces the cast, can only derive the data type from the Java type (`String.class`), which has no length:

https://github.com/jOOQ/jOOQ/blob/41847ec6484d8bfe32f54532d846dff6689e46ac/jOOQ/src/main/java/org/jooq/impl/DefaultBinding.java#L654-L655

Because of https://github.com/jOOQ/jOOQ/issues/1727, we then cast the value to its actual length:

https://github.com/jOOQ/jOOQ/blob/41847ec6484d8bfe32f54532d846dff6689e46ac/jOOQ/src/main/java/org/jooq/impl/DefaultBinding.java#L710-L713

Now, I'll need to investigate if 1) #1727 is still needed and 2) if it can be relaxed.

**Comment by lukaseder** [comment] 2020-04-03 13:41
Skipping the code from #1727 obviously fixes this issue, because now the cast is always to `CAST(? AS VARCHAR(4000))`. But this would probably introduce new regressions...

**Comment by lukaseder** [comment] 2020-04-03 13:46
The obvious regression is that longer `VARCHAR` values will now be truncated. The arbitrary max length of `4000` can be traced back to the introduction of firebird support #430, without much documentation about why the choice was made.

I think the solution here should really be to pass along the well known `DataType` from the target table (which is referenced from the `org.jooq.impl.Val` object containing the bind variable) to the `BindingSQLContext`, such that this `cast()` method can make a more informed decision.

**Comment by lukaseder** [comment] 2020-04-03 14:22
The fix leads to new regressions. The `DataType` might have a wrong length for other reasons, so that new wrong length would now be applied.

In order to fix this particular issue, maybe, it would be much sounder to work on #2823. I don't think any RDBMS needs bind values to be cast in an `INSERT .. VALUES` clause like in this example

**Comment by lukaseder** [comment] 2020-04-03 14:36
Haha, the fool I am, thinking that PostgreSQL doesn't need casts in `INSERT .. VALUES` (e.g. for JSON) types...

**Comment by lukaseder** [comment] 2020-04-03 14:53
I've created a new issue for this: https://github.com/jOOQ/jOOQ/issues/10033

Integration tests show that we can indeed skip bind variable casting for most dialects, except PostgreSQL. The regression risk shown by PostgreSQL, however, makes me feel that I shouldn't backport this issue to a patch release.

**Comment by lukaseder** [comment] 2020-04-03 15:18
This has been fixed via #10033. A fix will be available in jOOQ 3.14.0

**Comment by lukaseder** [comment] 2020-04-03 15:19
For the time being, as a workaround, you could:

- Avoid batching
- Apply the fix in a fork on your side
- Work with 3.14.0-SNAPSHOT

**Closed by lukaseder** 2020-04-03 15:18 UTC
Labels: C: DB: Firebird, C: Functionality, E: All Editions, P: High, T: Defect

**Comment by lukaseder** [comment] 2020-04-03 15:22
Another workaround is to set `Settings.paramCastMode = NEVER` for the execution of such queries

**Comment by perceptron8** [comment] 2020-04-03 15:34
Batching is inevitable as I load whole database into another. I'll go with the SNAPSHOT or `Settings.paramCastMode` workaround. Thank you very much!

**Comment by perceptron8** [comment] 2020-04-03 15:44
I'm happy to say that `Settings.paramCastMode = NEVER` works great.

**Comment by lukaseder** [comment] 2020-04-06 17:56
@perceptron8 That's great to hear!

**Comment by lukaseder** [comment] 2020-07-06 09:44
Looks like this problem appears elsewhere as well, e.g. in #7253. A better fix will be needed: https://github.com/jOOQ/jOOQ/issues/10362, which will also fix this for `INSERT .. SELECT`, not just for `INSERT .. VALUES`
