### ISSUE TITLE
Incorrect convertFrom being called

### ISSUE THREAD

**Issue by TomBeckett** [jOOQ/jOOQ#14693] opened 2023-02-23 15:35 UTC
### Your question

I've got two different SQL select queries (both with a multisetAgg column) that are combined into a union:

```java
        final var rollupItems = dslContext.select(
                        SQUAD_TIMELINE.EVENT_TYPE,
                        DSL.multisetAgg(
                                        idField,
                                        SQUAD_TIMELINE.ID,
                                        SQUAD_TIMELINE.SQUAD_ID,
                                        SQUAD_TIMELINE.CREATED_DATE,
                                        SQUAD_TIMELINE.SESSION_TEMPLATE_ID,
                                        SQUAD_TIMELINE.SESSION_COMPLETE_ID,
                                        SESSION_TEMPLATE.TEMPLATE_NAME,
                                        completerTable.FIREBASE_ID,
                                        completerTable.DISPLAY_NAME,
                                        squadUserTable.DISPLAY_NAME
                                ).orderBy(idField.desc())
                                .convertFrom(s -> s.into(TimelineRollupProjection.class)) <--- here
.....snip
```

```java
final var noRollupItems = DSL.select(
                        SQUAD_TIMELINE.EVENT_TYPE,
                        DSL.multisetAgg(
                                        idField,
                                        SQUAD_TIMELINE.ID,
                                        SQUAD_TIMELINE.SQUAD_ID,
                                        SQUAD_TIMELINE.CREATED_DATE,
                                        SQUAD_TIMELINE.SESSION_TEMPLATE_ID,
                                        SQUAD_TIMELINE.SESSION_COMPLETE_ID,
                                        SQUAD_TIMELINE.MILESTONE_COUNT,
                                        SESSION_TEMPLATE.TEMPLATE_NAME,
                                        SESSION_TEMPLATE.CREATED_DATE,
                                        SESSION_TEMPLATE.UPDATED_DATE,
                                        SESSION_TEMPLATE.ARCHIVED,
                                        isFavorite,
                                        completedCount,
                                        completedByCount,
                                        templateAuthorTable.FIREBASE_ID,
                                        templateAuthorTable.DISPLAY_NAME,
                                        DSL.multiset(
                                                DSL.select(EXERCISE.ID)
                                                        .from(EXERCISE)
                                                        .join(SESSION_PARAMETER).on(EXERCISE.ID.eq(SESSION_PARAMETER.EXERCISE_ID))
                                                        .join(EXERCISE_BLOCK).on(EXERCISE_BLOCK.ID.eq(SESSION_PARAMETER.EXERCISE_BLOCK_ID))
                                                        .where(EXERCISE_BLOCK.SESSION_TEMPLATE_ID.eq(SESSION_TEMPLATE.ID))
                                                        .union(DSL.select(EXERCISE.ID)
                                                                .from(EXERCISE)
                                                                .join(SESSION_COMPLEX_EXERCISE).on(EXERCISE.ID.eq(SESSION_COMPLEX_EXERCISE.EXERCISE_ID))
                                                                .join(EXERCISE_BLOCK).on(EXERCISE_BLOCK.ID.eq(SESSION_COMPLEX_EXERCISE.EXERCISE_BLOCK_ID))
                                                                .where(EXERCISE_BLOCK.SESSION_TEMPLATE_ID.eq(SESSION_TEMPLATE.ID)))
                                        ).convertFrom(t -> t.collect(Records.intoList(r -> r.get(EXERCISE.ID)))),
                                        DSL.inline(null, String.class) // squadUserTable.DISPLAY_NAME
                                )
                                .orderBy(idField.desc())
                                .convertFrom(s -> s.into(TimelineRollupProjection.class)) <--- here
                ).from(SQUAD_TIMELINE)
.....snip
```

```java
        final var items = rollupItems
                .union(noRollupItems)
                .limit(pageable.getPageSize())
                .offset(pageable.getOffset())
                .fetch()
                .map(s -> mapRecord(publicCode, s));
```

I find that the first convertFrom (`rollupItems`) always gets called but never the second? This results in the second query never being converted correctly with many properties being left null.

Is there a way to force convertFrom type to use a different constructor? Many examples use `::new` rather than a static factory for example.

```java
// Used by non roll up items
public record TimelineRollupProjection(
        String id,
        Long timelineId,
        Long squadId,
        LocalDateTime createdDate,
        Long sessionTemplateId,
        Long sessionCompleteId,
        Short milestoneCount,
        String sessionTemplateName,
        LocalDateTime sessionTemplateCreatedDate,
        LocalDateTime sessionTemplateUpdatedDate,
        Boolean sessionTemplateArchived,
        LocalDateTime favoriteDate,
        Integer completedCount,
        Integer completedByCount,
        String firebaseId,
        String displayName,
        List<Long> exerciseIds,
        String squadUserDisplayName
) {
    // Used by roll up items in getTimelineItems
    @SuppressWarnings("unused")
    public TimelineRollupProjection(
            String id,
            Long timelineId,
            Long squadId,
            LocalDateTime createdDate,
            Long sessionTemplateId,
            Long sessionCompleteId,
            String sessionTemplateName,
            String firebaseId,
            String displayName,
            String squadUserDisplayName
    ) {
        this(
                id,
                timelineId,
                squadId,
                createdDate,
                sessionTemplateId,
                sessionCompleteId,
                (short) 0,
                sessionTemplateName,
                null,
                null,
                null,
                null,
                null,
                null,
                firebaseId,
                displayName,
                null,
                squadUserDisplayName
        );
    }
}
```

In an ideal world. would have two different records, one for rollup items and one for non-rollup items. Even though its a SQL union, they are different things.

### jOOQ Version

3.17.8 Open Source

### Database product and version

MySQL 8.0.32

### Java Version

openjdk 19.0.2 2023-01-17

**Comment by TomBeckett** [comment] 2023-02-24 11:20
I've also tried using inline ad-hoc converters:

```java
final var rollupItems = dslContext.select(
              SQUAD_TIMELINE.EVENT_TYPE,
              DSL.multisetAgg(
                              idField,
                              SQUAD_TIMELINE.ID,
                              SQUAD_TIMELINE.CREATED_DATE,
                              SQUAD_TIMELINE.SESSION_TEMPLATE_ID,
                              SQUAD_TIMELINE.SESSION_COMPLETE_ID,
                              SESSION_TEMPLATE.TEMPLATE_NAME,
                              completerTable.FIREBASE_ID,
                              completerTable.DISPLAY_NAME,
                              squadUserTable.DISPLAY_NAME
                      ).orderBy(idField.desc())
                      .convertFrom(r -> r.map(
                              s -> new TimelineRollupProjection(
                                      s.get(idField),
                                      s.get(SQUAD_TIMELINE.ID),
                                      s.get(SQUAD_TIMELINE.CREATED_DATE),
                                      s.get(SQUAD_TIMELINE.SESSION_TEMPLATE_ID),
                                      s.get(SQUAD_TIMELINE.SESSION_COMPLETE_ID),
                                      null,
                                      s.get(SESSION_TEMPLATE.TEMPLATE_NAME),
                                      null,
                                      null,
                                      null,
                                      null,
                                      null,
                                      null,
                                      s.get(completerTable.FIREBASE_ID),
                                      s.get(completerTable.DISPLAY_NAME),
                                      null,
                                      null
                              )))
```

But I find that only one `convertFrom` gets called. I can only assume some kind of squashing happens in JOOQ and it thinks these two ad-hoc converters are the same (so only call one of them)?

**Comment by lukaseder** [comment] 2023-02-28 18:59
Thanks a lot for your detailed report. I will look into this soon.

**Comment by lukaseder** [comment] 2023-03-01 09:57
First off, I guess you assumed this, you probably set:

```java
ctx.settings().setMapRecordComponentParameterNames(true);
```

Correct?

Next, there's an interesting combination of `UNION` (you probably don't need that? `UNION ALL` should suffice?) and `MULTISET_AGG` and a reflective `DefaultRecordMapper`. In your case, it is possible to have a `UNION` over otherwise incompatible union subquery row types (different number of columns projected within `MULTISET_AGG`). Thinking about this, I don't see a good reason why this shouldn't be possible in principle. After all, both subqueries use `Record2<EventTypeType, TimelineRollupProjection>`. The default implementation projects two compatible `JSON` or `JSONB` types, so there's nothing wrong from a SQL perspective. Without using `convertFrom()`, your query wouldn't compile, however.

I'm somewhat torn about whether this is legitimate jOOQ API usage. It seems equally correct as it seems wrong :) Though, I can see how jOOQ should make this work, so I'll add additional integration tests. It's just that this is probably the root cause of your problem.

So, after trying to reproduce this (see also https://github.com/jOOQ/jOOQ/issues/14724 for an additional description), I can confirm, there are 2 problems:

- Something's going wrong when nesting `MULTISET` in `MULTISET_AGG()`. I didn't think this was possible, but apparently, PostgreSQL is more powerful, so let's get that to work. I'll create a separate issue for this.
- When using `UNION`, only the first `UNION` subquery's ad-hoc converters are actually used, not the second one's. That's logical if you think about it. When a record is retrieved from the database, jOOQ has no way of knowing which subquery produced it. This raises a lot of questions, which I can't answer yet, simply. But it hints at the above discussion showing a code smell: Projecting two different things in different `UNION` subqueries.

I think that if the first problem is addressed in your case, then the second problem will be irrelevant *for this particular query*. It won't be irrelevant in general, though!

I did reproduce an issue: https://github.com/jOOQ/jOOQ/issues/14724. I'm not sure if this is the same as yours? You said "incorrect `convertFrom` being called". But in #14724, it looks like it isn't being called at all.

**Comment by lukaseder** [comment] 2023-03-01 10:07
> I didn't think this was possible, but apparently, PostgreSQL is more powerful, so let's get that to work.

Nah, I just forgot. We already have an integration test for that usage, just not one that also tests combining this with `DefaultRecordMapper`

**Comment by lukaseder** [comment] 2023-03-01 10:26
In fact, the problem where the nested mapping doesn't work, could be related to `ctx.settings().setMapRecordComponentParameterNames(true);` With the flag being turned off, I can't reproduce the problem (though in your case, because of the `UNION`, other problems appear, then)

**Comment by lukaseder** [comment] 2023-03-01 10:31
But if that flag is set, there's currently no way to rename the nested `MULTISET` to the expected target attribute without having any negative effect on the generated SQL, see:

- https://github.com/jOOQ/jOOQ/issues/13870
- https://github.com/jOOQ/jOOQ/issues/13937

**Comment by lukaseder** [comment] 2023-03-01 10:47
So, the issues is far more complex than I expected. To work around it, can you confirm your query works if you:

- Make sure the projections are really compatible between `UNION ALL` subqueries (don't omit any columns)
- You use only complete constructor based mappings, not the `DefaultRecordMapper`
- You make sure the first `UNION ALL` subquery contains all the mapping logic necessary for the second one as well.

I'll make sure the `UNION` subquery converter behaviour is documented at various places: https://github.com/jOOQ/jOOQ/issues/14726

It doesn't apply only to ad-hoc converters. Converters attached to generated code are also affected.

**Comment by lukaseder** [comment] 2023-03-01 10:53
Another workaround, instead of doing rollup manually, perhaps use MySQL's `WITH ROLLUP`? We support it via standard SQL `DSL.rollup()`

**Comment by TomBeckett** [comment] 2023-03-01 11:29
Hey @lukaseder thanks for taking the time to look at this.

I've managed to workaround the problem by making sure all columns for both match. 

This may sound _obvious_ in that its a union but I was hoping my multisetAgg would not need to match but it does need to. Heres the record I needed to convert into to achieve this:

```java
public record TimelineRollupProjection(
        String id,
        int commentsCount,
        Long timelineId,
        LocalDateTime createdDate,
        Long sessionTemplateId,
        Long sessionCompleteId,
        Short milestoneCount,
        String sessionTemplateName,
        LocalDateTime sessionTemplateCreatedDate,
        LocalDateTime sessionTemplateUpdatedDate,
        Boolean sessionTemplateArchived,
        LocalDateTime favoriteDate,
        Integer completedCount,
        Integer completedByCount,
        String firebaseId,
        String displayName,
        List<Long> exerciseIds,
        String squadUserDisplayName
) {
}
```

In an ideal world I would have maybe a several smaller projection records. After reading https://github.com/jOOQ/jOOQ/issues/14726 I am coming to terms with the ideal that maybe I'm just using JOOQ incorrectly.

I'll investigate the MySQL `WITH ROLLUP` thats totally news to me, so thank you for that!

Finally, if your planning an further documentation on mutliset/mutlisetagg, please make it and I will read it! It is absolutely the killer feature of JOOQ.

**Comment by lukaseder** [comment] 2023-03-01 11:50
> This may sound _obvious_ in that its a union but I was hoping my multisetAgg would not need to match but it does need to.

Well, again, `multisetAgg()` does need to match between union subqueries (the type is `Result<Record[N]<...>>`, so the `Record[N]` types have to match. If `MULTISET` is implemented natively, or once we implement the `ARRAY` emulation (https://github.com/jOOQ/jOOQ/issues/13746), this becomes more clear also in SQL.

It just so happens that:

- The JSON (or also XML) emulations don't really care in SQL, because JSON is weakly structured
- Once you use ad-hoc converters, jOOQ / javac also stops caring whether the actual projection matches

I'll have to think about these things a bit more. The error is very subtle, and people may thus have bugs that they're not aware of. It's not ideal.

> In an ideal world I would have maybe a several smaller projection records

If you understand the tradeoffs, you can. You just have to make sure that the first `UNION` subquery contains all the logic for all the possible projection records.

> Finally, if your planning an further documentation on mutliset/mutlisetagg, please make it and I will read it! It is absolutely the killer feature of JOOQ.

Well, there are a few blog posts already. They should all be tagged:
https://blog.jooq.org/tag/multiset/

There are so many benefits to this approach, here's one of my favourites:
https://blog.jooq.org/how-to-typesafely-map-a-nested-sql-collection-into-a-nested-java-map-with-jooq/

**Comment by lukaseder** [comment] 2023-03-03 09:31
Another user has run into this problem: https://github.com/jOOQ/jOOQ/issues/14657#issuecomment-1452301772

**Comment by lukaseder** [comment] 2023-03-03 09:40
> I'll have to think about these things a bit more. The error is very subtle, and people may thus have bugs that they're not aware of. It's not ideal.

After giving this a bit of additional thought, I'm concluding:

- It would be hard to formally verify that two union subquery converters are equivalent. There's no easy way of structurally comparing lambdas, let alone other types of ad-hoc converters.
- Even if using the `DefaultRecordMapper`, it is hard to assess whether two union subquery converters would effectively be equivalent.
- We can't even warn against passing a converter to the second union subquery, because for the compiler to accept the union, *some* converter is needed, and if we can't be sure they're compatible, we can't warn anything without creating noise.
- The approach you've chosen initially could have worked if you had followed the rules established in this issue (even if they're not necessarily intuitive), so we can't forbid the approach per se, (even if it were technically possible), as users probably already rely on this. The fact that the reflective `DefaultRecordMapper` is used hints at users being fine with forgoing some type safety, so jOOQ shouldn't be judgy.

So, I'm closing this issue as "works for me".

**Closed by lukaseder** 2023-03-03 09:40 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by lukaseder** [comment] 2024-11-12 08:19
A similar case where the expectation was for a converter to apply from within a JSON tree producing expression:

- https://github.com/jOOQ/jOOQ/issues/17597
