### ISSUE TITLE
MemSQL does not support "nested scalar subselects in project list"

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8609] opened 2019-05-08 10:16 UTC
Currently the test `testUpdateSelect()` fails for MemSQL with the error message "nested scalar subselects in project list". The Java code looks like this:

```java
        Table<A> a1 = TAuthor();
        Table<A> a2 = TAuthor().as("a2");
        Field<String> f1 = a1.field(TAuthor_FIRST_NAME());
        Field<String> f2 = a2.field(TAuthor_FIRST_NAME());
        Field<String> f3 = a2.field(TAuthor_LAST_NAME());

        UpdateQuery<A> u = create().updateQuery(a1);
        u.addValue(f1, create().select(max(f3)).from(a2).where(f1.equal(f2)).<String> asField());
        u.execute();
```

The SQL produced looks like this:

```sql
update `test`.`t_author`
set `test`.`t_author`.`FIRST_NAME` = (
      select *
      from (
        select max(`a2`.`LAST_NAME`)
        from `test`.`t_author` as `a2`
        where `test`.`t_author`.`FIRST_NAME` = `a2`.`FIRST_NAME`
      ) as `t`
    )
```
The following simplified statement would however work:

```sql
update `test`.`t_author`
set `test`.`t_author`.`FIRST_NAME` = (
        select max(`a2`.`LAST_NAME`)
        from `test`.`t_author` as `a2`
        where `test`.`t_author`.`FIRST_NAME` = `a2`.`FIRST_NAME`
    )
```
It should be investigated how and under what circumstances a scalar subquery can be generated without a surrounding `SELECT *`.

**Comment by lukaseder** [comment] 2019-05-08 10:20
Interseting. That generated derived table is because of #6583, which is required in MySQL and MariaDB. If that's not a requirement for MemSQL, all the better. You can try deactivating this emulation.

**Comment by knutwannheden** [comment] 2019-05-08 10:21
Oh, I hadn't noticed this. Let me look into it.

**Comment by knutwannheden** [comment] 2019-05-08 10:25
At least the mentioned test runs through fine. I will have to rerun all other tests.

**Comment by lukaseder** [comment] 2019-05-08 10:26
Perhaps we might also need additional tests for these self-references, just to be sure this isn't a special case that happens to work on MemSQL, but not on MySQL.

**Comment by knutwannheden** [comment] 2019-05-08 10:43
MemSQL's UPDATE and DELETE statements support LIMIT, but not ORDER BY... But jOOQ's "emulation" on MemSQL only works with the generated derived table. So this works:

```sql
update `test`.`t_book`
set `test`.`t_book`.`TITLE` = 'X'
where `test`.`t_book`.`ID` in (
  select *
  from (
    select `test`.`t_book`.`ID`
    from `test`.`t_book`
    where `test`.`t_book`.`ID` > 1
    order by `test`.`t_book`.`ID`
    limit 2
  ) as `t`
)
```

and this doesn't:

```sql
update `test`.`t_book`
set `test`.`t_book`.`TITLE` = 'X'
where `test`.`t_book`.`ID` in (
  select `test`.`t_book`.`ID`
  from `test`.`t_book`
  where `test`.`t_book`.`ID` > 1
  order by `test`.`t_book`.`ID`
  limit 2
)
```
So some DML *requires* the derived table while other DML doesn't work with the derived table. WTF?

**Comment by lukaseder** [comment] 2019-05-08 14:25
The wonderful world of supporting every possible "RDBMS" :-)

We can keep this open and not support `UPDATE .. [ ORDER BY .. ] LIMIT`, or you could think about adding new flags to the `ctx.data()` to decide further down in the SQL generation whether the derived table is required or not. I'm undecided right now, without looking at the code in more detail.

**Comment by jjqq2013** [comment] 2023-02-27 15:52
I had same issue. This is an actually breaking change since JOOQ 3.12.4 (maybe more earlier but > 3.11.2), it worked in 3.11.2.

The change is https://github.com/jOOQ/jOOQ/blob/8039850d7ca55946ca681405708b578749c70d55/jOOQ/src/main/java/org/jooq/impl/SelectQueryImpl.java#L1431-L1431

This change does not make sense
- JOOQ need not hide the syntax error by surrounding subquery with "select *". JOOQ should let users decide how to do.
- It breaks previous working code.

**Comment by lukaseder** [comment] 2023-02-28 07:35
Thanks a lot for your comment, @jjqq2013. I'm not sure if this is strictly related? The error from this issue is about:

- MemSQL / SingleStore
- Using the correlated subquery in `UPDATE .. SET`, not `UPDATE .. WHERE`.

At some point, the `UPDATE .. WHERE` clause still required this particular workaround also in MemSQL? See #6583 for details. But I can have another look at this issue, to validate we're still doing the optimal thing for MemSQL.

> * JOOQ need not hide the syntax error by surrounding subquery with "select *". JOOQ should let users decide how to do.

There are different points of view to this. The main benefit of using jOOQ, apart from being able to get dynamic SQL, is to no longer worry about *any* of these syntactic quirks. jOOQ makes your SQL "just work." Obviously, this is only true for as long as jOOQ doesn't make any mistakes on its own, but I trust that you're already profiting from jOOQ's stance a ton, without being aware of it.

Sure, we can debate whether an additional "mode" to turn off all of these fixes in jOOQ is reasonable, but:

1. That mode would have to be integration tested as well, and that would be very time consuming on our end
2. Most people would just turn it back on, because these things get so cumbersome, precisely why people tend to like jOOQ

To give you a few examples, just look at these things:

- https://blog.jooq.org/standard-sql-json-the-sobering-parts/
- https://blog.jooq.org/the-many-ways-to-return-data-from-sql-dml/

So, let's focus only on the specific issues, without escalating this to an attempt to shift jOOQ's fundamental strategies.

> * It breaks previous working code, like following sql works previously but now not

Yes, it's annoying when this kind of thing happens, and I'm glad you reported it, so let's work on fixing this for you ASAP. Since your issue doesn't seem to be the exact same issue as the original one, may I ask you to open up a new one, including all the usual information (jOOQ versions, MemSQL versions, etc.)

**Comment by lukaseder** [comment] 2023-02-28 08:03
The `IN (SELECT .. LIMIT)` transformation should be applied also to MemSQL:

- https://github.com/jOOQ/jOOQ/issues/8521
- https://github.com/jOOQ/jOOQ/issues/14717

**Comment by lukaseder** [comment] 2023-02-28 08:14
Well, I can confirm that removing this MySQL specific workaround for MemSQL doesn't produce any regressions (after applying #14717) on SingleStore `version()` = 5.5.58, `@@memsql_version` = 7.3.8. I guess it's time to add dialect versioning to this dialect...

**Comment by lukaseder** [comment] 2023-02-28 08:23
Dialect versioning task: https://github.com/jOOQ/jOOQ/issues/14718

**Comment by lukaseder** [comment] 2023-02-28 08:51
Fixed for jOOQ 3.18.0. A backport won't be possible without having versioned dialects (#14718). But jOOQ 3.18.0 will be released soon, hopefully in March 2023.

Note, as a workaround, you might be able to trick jOOQ into no longer finding the equivalence of the target table and the source table by using plain SQL, e.g. ``table("`test`.`table1` as `table1`")`` or something like this. This is a bit of a laborious trick, but maybe, that helps work around this problem in the meantime.

**Closed by lukaseder** 2023-02-28 08:51 UTC
Labels: T: Defect, C: Functionality, P: Medium, C: DB: SingleStore, E: Professional Edition, E: Enterprise Edition

**Comment by jjqq2013** [comment] 2023-03-02 03:38
@lukaseder thank you for detail explanation.

> Yes, it's annoying when this kind of thing happens, and I'm glad you reported it, so let's work on fixing this for you ASAP. Since your issue doesn't seem to be the exact same issue as the original one, may I ask you to open up a new one, including all the usual information (jOOQ versions, MemSQL versions, etc.)

The issue I reported should be essentially same as this ticket. I used the `notExists`, while this ticket used `IN`, but the essential process are in same place(https://github.com/jOOQ/jOOQ/blob/8039850d7ca55946ca681405708b578749c70d55/jOOQ/src/main/java/org/jooq/impl/SelectQueryImpl.java#L1431-L1431), it is the only place that added an extra "select *" wrapper.

No worry about the fix, I fixed with replace the subquery's reference of update target table with inner join.

> There are different points of view to this. The main benefit of using jOOQ, apart from being able to get dynamic SQL, is to no longer worry about any of these syntactic quirks. jOOQ makes your SQL "just work." Obviously, this is only true for as long as jOOQ doesn't make any mistakes on its own, but I trust that you're already profiting from jOOQ's stance a ton, without being aware of it.

I don't mind that you fix JOOQ so users no longer worry about any of these syntactic quirks and let jOOQ makes our SQL "just work."

What I mind is that the fix in the https://github.com/jOOQ/jOOQ/blob/8039850d7ca55946ca681405708b578749c70d55/jOOQ/src/main/java/org/jooq/impl/SelectQueryImpl.java#L1431-L1431 produced an expected SQL *hierarchy*, I would not say it is a good work around for its original purpose https://github.com/jOOQ/jOOQ/issues/6583, there should be other better ways such as automatically adding a uniq table alias for the update/insert/delete target table  and tables in subquery. I might comment in the original ticket later.

**Comment by lukaseder** [comment] 2023-03-02 07:24
> produced an expected SQL _hierarchy_, I would not say it is a good work around for its original purpose #6583, there should be other better ways

I'm aware of the risk of creating derived tables in RDBMS that have poor support for correlating them. But for 80% of all cases, the workaround still works, and that's better than if it doesn't work *at all* (granted, here, for MemSQL, the fix may not have been necessary, at least not in versions 7+, but that's just a bug).

I'm all ears for better ways of emulating things, always. This is what is constantly being done in jOOQ as well. We get things to work, and then, we improve how we get things to work, and we iterate, etc.

> such as automatically adding a uniq table alias for the update/insert/delete target table and tables in subquery

Have you tried this? E.g. in MySQL:

```sql
update t as x
set i = (select max(i) from t as u);
```

That doesn't outsmart the parser:

> SQL Error [1093] [HY000]: You can't specify target table 'x' for update in FROM clause

> I might comment in the original ticket later.

Please, can you create a new ticket, instead? Closed issues are no longer being tracked.

**Comment by lukaseder** [comment] 2023-03-02 09:39
Removing the restriction also for MariaDB, which seems to have also fixed this: https://github.com/jOOQ/jOOQ/issues/14742

**Comment by jjqq2013** [comment] 2023-03-02 10:28
@lukaseder  thanks for you detail explanation. 

> But for 80% of all cases, the workaround still works, and that's better than if it doesn't work at all
Much appreciate your work, this make sense.

> Please, can you create a new ticket, instead? Closed issues are no longer being tracked.
Sure, I will create a new ticket to discuss the issue when I find time.
