### ISSUE TITLE
MySQL 5.7: Invalid SQL for set operations in subqueries

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9751] opened 2020-01-20 13:24 UTC
The following jOOQ examples all work as expected with MySQL 8.0 and MariaDB 10.4+ but don't parse in MySQL 5.7 and MariaDB 10.3 and earlier:
```java
ctx.select(select(one()).union(select(one())).asField()).fetch();
ctx.select(one()).where(one().in(select(one()).union(select(one())))).fetch();
```

The following examples on the other hand also work in MySQL 5.7 and MariaDB 10.3 and earlier:
```java
ctx.select(one()).where(exists(select(one()).union(select(one())))).fetch();
```
The problem with the former two queries is that in the subquery the two queries combined by the `UNION` set operator have a parenthesis around them, which the dialect doesn't like. So for the first query for example jOOQ renders the following:
```sql
select (
  (
    select 1
    from dual
  )
  union (
    select 1
    from dual
  )
)
```
whereas MySQL 5.7 would require:
```sql
select (
  select 1
  from dual
  union (
    select 1
    from dual
  )
)
```
or:
```sql
select (
  select 1
  from dual
  union
  select 1
  from dual
)
```

**Comment by knutwannheden** [comment] 2020-01-20 13:29
As a workaround SQL templating can be used. Instead of:
```java
ctx.select(select(A.ID).from(A).union(select(B.ID).from(B)).asField());
```
the following works:
```java
ctx.select(select(A.ID).from("{0} union {1}", A, select(B.ID).from(B)).asField());
```

**Comment by lukaseder** [comment] 2020-01-20 20:54
Might be a duplicate of https://github.com/jOOQ/jOOQ/issues/4856

**Comment by lukaseder** [comment] 2020-01-20 22:09
Obviously, avoiding the seemingly unnecessary parentheses seems like the best option here. As you suggested:

```sql
select (
  select 1
  from dual
  union
  select 1
  from dual
)
```

A related issue is this one: https://github.com/jOOQ/jOOQ/issues/3676, which could partially fix this problem.

**Comment by lukaseder** [comment] 2020-01-20 22:14
I think #3676 should be a relatively easy fix with little risk, which could fix most problems that might appear in MySQL 5.7.

**Comment by lukaseder** [comment] 2020-01-20 22:15
A backport to 3.12.4 could be guarded by a `Settings` which is turned off by default.

**Comment by lukaseder** [comment] 2020-01-20 22:48
This patch implementing #3676 seems quite promising.

```patch
diff --git a/jOOQ/src/main/java/org/jooq/impl/SelectQueryImpl.java b/jOOQ/src/main/java/org/jooq/impl/SelectQueryImpl.java
index db92648..01d1d95 100644
--- a/jOOQ/src/main/java/org/jooq/impl/SelectQueryImpl.java
+++ b/jOOQ/src/main/java/org/jooq/impl/SelectQueryImpl.java
@@ -1140,6 +1140,7 @@
         boolean qualify = context.qualify();
 
         int unionOpSize = unionOp.size();
+        boolean unionParensRequired = false;
         boolean unionOpNesting = false;
 
         // The SQL standard specifies:
@@ -1232,7 +1233,10 @@
                     case UNION_ALL:     context.start(SELECT_UNION_ALL);     break;
                 }
 
-                unionParenthesis(context, '(', getSelect().toArray(EMPTY_FIELD));
+                // [#3676] There might be cases where nested set operations do not
+                //         imply required parentheses in some dialects, but better
+                //         play safe than sorry
+                unionParenthesis(context, '(', getSelect().toArray(EMPTY_FIELD), unionParensRequired = unionOpNesting || unionParensRequired());
             }
         }
 
@@ -1521,7 +1525,7 @@
         // SET operations like UNION, EXCEPT, INTERSECT
         // --------------------------------------------
         if (unionOpSize > 0) {
-            unionParenthesis(context, ')', null);
+            unionParenthesis(context, ')', null, unionParensRequired);
 
             for (int i = 0; i < unionOpSize; i++) {
                 CombineOperator op = unionOp.get(i);
@@ -1531,14 +1535,14 @@
                            .visit(op.toKeyword(family))
                            .sql(' ');
 
-                    unionParenthesis(context, '(', other.getSelect().toArray(EMPTY_FIELD));
+                    unionParenthesis(context, '(', other.getSelect().toArray(EMPTY_FIELD), unionParensRequired);
                     context.visit(other);
-                    unionParenthesis(context, ')', null);
+                    unionParenthesis(context, ')', null, unionParensRequired);
                 }
 
                 // [#1658] Close parentheses opened previously
                 if (i < unionOpSize - 1)
-                    unionParenthesis(context, ')', null);
+                    unionParenthesis(context, ')', null, unionParensRequired);
 
                 switch (unionOp.get(i)) {
                     case EXCEPT:        context.end(SELECT_EXCEPT);        break;
@@ -1773,7 +1777,24 @@
         return false;
     }
 
-    private final void unionParenthesis(Context<?> ctx, char parenthesis, Field<?>[] fields) {
+    private final boolean unionParensRequired() {
+        if (unionOp.size() <= 1)
+            return false;
+
+        CombineOperator op = unionOp.get(0);
+
+        // [#3676] These are not associative
+        if (op == EXCEPT || op == EXCEPT_ALL)
+            return true;
+
+        for (int i = 1; i < unionOp.size(); i++)
+            if (op != unionOp.get(i))
+                return true;
+
+        return false;
+    }
+
+    private final void unionParenthesis(Context<?> ctx, char parenthesis, Field<?>[] fields, boolean parensRequired) {
         boolean derivedTable =
 
             // [#3579] [#6431] [#7222] Some databases don't support nested set operations at all
@@ -1792,14 +1813,16 @@
             || (ctx.subquery() && UNION_PARENTHESIS_IN_DERIVED_TABLES.contains(ctx.family()))
             ;
 
-        if (')' == parenthesis) {
+        parensRequired |= derivedTable;
+
+        if (parensRequired && ')' == parenthesis) {
             ctx.formatIndentEnd()
                .formatNewLine();
         }
 
         // [#3579] Nested set operators aren't supported in some databases. Emulate them via derived tables...
         // [#7222] Do this only in the presence of actual nested set operators
-        else if ('(' == parenthesis) {
+        else if (parensRequired && '(' == parenthesis) {
             if (derivedTable) {
                 ctx.formatNewLine()
                    .visit(K_SELECT).sql(' ');
@@ -1828,16 +1851,18 @@
                 break;
 
             default:
-                ctx.sql(parenthesis);
+                if (parensRequired)
+                    ctx.sql(parenthesis);
+
                 break;
         }
 
-        if ('(' == parenthesis) {
+        if (parensRequired && '(' == parenthesis) {
             ctx.formatIndentStart()
                .formatNewLine();
         }
 
-        else if (')'== parenthesis) {
+        else if (parensRequired && ')'== parenthesis) {
             if (derivedTable)
                 ctx.sql(" x");
         }
```

Limitations include:

- Formatting is not right yet
- `testUnionWithOrderByInSubselect` regression (which hints at 1-2 edge cases when parentheses are required after all, because jOOQ set operation subqueries are permitted `ORDER BY`, `OFFSET`, `FETCH` clauses, whereas in standard SQL, they're not)

Would be curious to hear your opinion about this patch, @knutwannheden. Preliminary integration test results (on my machine) seem so successful, I'm almost tempted to say this `Settings` guard could be turned on by default

**Comment by lukaseder** [comment] 2020-01-21 07:31
For the record, I'm suggesting a backport to 3.12.4 *only* for older versions of MySQL, MariaDB, which expose this problem. For all other dialects, I would implement this only in 3.13, to minimise the regression risk. Specifically, in Oracle, I've encountered many syntactic edge cases in the past, related to set operations.

**Comment by lukaseder** [comment] 2020-01-21 18:24
Another workaround for the `IN` predicate case.

Instead of:

```sql
select *
from t
where t.x in (
  select x from u1
  union
  select x from u2
)
```

Write

```sql
select *
from t
where t.x in (select x from u1)
or t.x in (select x from u2)
```

**Comment by knutwannheden** [comment] 2020-01-22 08:59
> For the record, I'm suggesting a backport to 3.12.4 _only_ for older versions of MySQL, MariaDB, which expose this problem. For all other dialects, I would implement this only in 3.13, to minimise the regression risk. Specifically, in Oracle, I've encountered many syntactic edge cases in the past, related to set operations.

I see. That is indeed a good idea, because I would be a bit worried if this change could cause regressions for other dialects.

I was in fact assuming that for some dialects the extra parenthesis were required, but I think I now understand that these were primarily introduced to circumvent issues with set operator precedence, which of course is a non-issue in many cases.

**Comment by knutwannheden** [comment] 2020-01-22 10:27
For 3.12.4 I would think that we probably don't even need a new setting, since only MySQL 5.7 and MariaDB 10.3 and older will be affected.

For 3.13 I suppose it is safest if we add a new setting despite our integration test suite.

**Comment by knutwannheden** [comment] 2020-01-22 11:26
Hmm, on the 3.12 branch we don't yet distinguish the various MariaDB releases as separate dialects. So maybe we should only fix the issue for MySQL 5.7 on the 3.12 branch.

**Comment by knutwannheden** [comment] 2020-01-22 11:37
A backport has been scheduled for the 3.12.4 release: #9752.

**Closed** 2020-01-22 11:42 UTC
Labels: C: DB: MariaDB, C: DB: MySQL, E: Enterprise Edition, E: Professional Edition, P: Medium, R: Fixed, T: Defect

**Comment by lukaseder** [comment] 2020-01-28 09:59
I agree with the fix and backport. Will release 3.12.4 today, with this fix
