### ISSUE TITLE
Consider adding Field.in(Iterable<?> values)

### ISSUE THREAD

**Issue by anuraaga** [jOOQ/jOOQ#6886] opened 2017-12-06 05:53 UTC
### Expected behavior and actual behavior:

Expected: Be able to pass an `Iterable` to `Field.in`
Actual: `Field.in` only accepts `Collection`

As all the `in` methods make a copy of the parameter by iterating, it would make them more useful if there was an `in` method that takes `Iterable` - then an intermediate copy can sometimes be avoided (e.g. using `Stream::iterator`). It would be as simple as replacing the current method to take `Iterable` and have the `Collection` method delegate to it.

### Steps to reproduce the problem:

API suggestion

### Versions:

- jOOQ: 3.10.2
- Java: 1.8

**Comment by lukaseder** [comment] 2017-12-06 07:01
Thank you very much for your suggestion. Indeed, this change could add quite some value to the API, although it certainly must not be limited to the `in()` method alone. Pretty much every method that currently accepts an `X[]` and `Collection<? extends X>` type would be affected, so this is a large change.

A pre-existing, related feature request is #5133, which would do the same for `Stream`. Given the significance of such a change, I prefer not to rush this for the occasional convenience...

Closing this as a duplicate of #5133

**Closed by lukaseder** 2017-12-06 07:01 UTC
Labels: C: Functionality, P: Medium, T: Enhancement
