### ISSUE TITLE
错误: 从发行版 9 开始, '_' 为关键字, 不能用作标识符

### ISSUE THREAD

**Issue by oylshe1314** [jOOQ/jOOQ#9705] opened 2020-01-02 07:57 UTC
#9330 # Expected behavior and actual behavior:

```java
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum COLUMNS_COLUMN_KEY implements EnumType {

    _(""), //

    PRI("PRI"),

    UNI("UNI"),

    MUL("MUL");
```

### Versions:

- jOOQ: 3.12.3
- Java:  13.0.1
- Database (include vendor):  MySQL 8.0.18 
- OS: win10
- JDBC Driver (include name if inofficial driver):com.mysql.cj.jdbc.Driver

**Comment by lukaseder** [comment] 2020-01-02 10:41
Thank you very much for your report.

This looks like a duplicate of https://github.com/jOOQ/jOOQ/issues/4703. We'll increase the priority of fixing #4703. In the meantime, you may consider using a generator strategy as a workaround:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/

**Closed by lukaseder** 2020-01-02 10:41 UTC
Labels: C: Functionality, E: All Editions, P: Medium, T: Defect
