### ISSUE TITLE
Add support for H2 index hints

### ISSUE THREAD

**Issue by thomasrudin** [jOOQ/jOOQ#6216] opened 2017-05-14 17:33 UTC
H2 Supports index hints since version 1.4.194 (2017-03-10).
`SELECT * FROM TEST USE INDEX (idx1, idx2)`

It would be nice to use them through jooq.

References:
* [Table Expression Syntax](http://h2database.com/html/grammar.html#table_expression)
* [Changelog](http://h2database.com/html/changelog.html)

**Comment by lukaseder** [comment] 2017-05-14 17:37
Thanks for your suggestion. Luckily, H2 uses MySQL's syntax which is not documented yet in jOOQ (https://github.com/jOOQ/jOOQ/issues/5679), but already supported since jOOQ 3.5: https://github.com/jOOQ/jOOQ/issues/3431

**Comment by lukaseder** [comment] 2017-05-14 17:37
Closing this as duplicate of #3431

**Closed by lukaseder** 2017-05-14 17:37 UTC
Labels: C: DB: H2, C: Functionality, P: Medium, T: Enhancement

**Comment by thomasrudin** [comment] 2017-05-14 17:41
Ha! that was fast...
Thank you and keep up the good work
