### ISSUE TITLE
Out of sync in return types

### ISSUE THREAD

**Issue by AnvarYasinov1997** [jOOQ/jOOQ#14522] opened 2023-01-19 20:13 UTC
### Expected behavior

class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')

My db dependencies 

    implementation("org.springframework.boot:spring-boot-starter-jdbc")
    implementation("org.postgresql:r2dbc-postgresql:1.0.0.RELEASE")
    implementation("io.r2dbc:r2dbc-spi:1.0.0.RELEASE")
    implementation("io.r2dbc:r2dbc-pool:1.0.0.RELEASE")
    implementation("org.flywaydb:flyway-core")
    implementation("org.postgresql:postgresql")
    implementation("org.jooq:jooq:3.17.7")

    val intVariable = dslContext.deleteFrom(OFFER_REQUISITES_MAPPING)
                .where(OFFER_REQUISITES_MAPPING.OFFER_ID.eq(offerId))
                .toMono().awaitFirst()

My mono source returns an int, I guess the r2dbc-1.0.0.RELEASE driver gives me a long

I remember you already told me that integration with r2dbc-1.0.0 will be available in jooq 3.18, I just want to highlight this problem

### Steps to reproduce the problem

Every call of update method and use a publisher for consume the data

### jOOQ Version

3.17.7

### Database product and version

14.5-alpine

### Java Version

17

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:r2dbc-postgresql:1.0.0.RELEASE

**Comment by lukaseder** [comment] 2023-01-20 12:45
Thanks for your report. I've stumbled upon this problem from "the other side" recently, i.e. after upgrading the r2dbc-spi dependency to 1.0.0.RELEASE, the one driver that isn't ready yet (third party mysql contribution) has the same problem the other way round:
https://github.com/jOOQ/jOOQ/issues/13565#issuecomment-1378770897

jOOQ 3.18 will work around this by using rawtypes, in case of which the binary method signature being linked uses `Object` instead of the generic synthetic bridge method's `Integer` (r2dbc 0.9) or `Long` (r2dbc 1.0). I'm reluctant to backporting this, as jOOQ 3.17 doesn't get integration tested with r2dbc 1.0 drivers.

So, the solution is to wait for jOOQ 3.18 with the r2dbc upgrade, or use the 3.18 snapshot versions. Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/13565

**Comment by lukaseder** [comment] 2023-01-20 12:46
(Still useful bug report, someone might find this via your error message and thus will find the conclusion).

**Closed by lukaseder** 2023-01-20 12:45 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by AnvarYasinov1997** [comment] 2023-01-23 07:39
What suitable set of libraries with drivers and API can I use for the most stable operation of the service in conjunction with jooq 3.17.7. I mean the following
implementation("org.postgresql:r2dbc-postgresql")
implementation("io.r2dbc:r2dbc-spi")
implementation("io.r2dbc:r2dbc-pool")

**Comment by lukaseder** [comment] 2023-01-23 08:08
The `pom.xml` holds the answer:
https://search.maven.org/artifact/org.jooq/jooq-parent/3.17.7/pom

Look for `r2dbc`
