### ISSUE TITLE
Table.field(alias, Year.class) assumes int backing as of 3.18

### ISSUE THREAD

**Issue by josephlbarnett** [jOOQ/jOOQ#14812] opened 2023-03-18 16:30 UTC
### Expected behavior

this issue is a similar use case as #9423 , where we are for various reasons trying to look up a field by name & type from a CTE.  We currently (jooq < 3.18) are able to use https://github.com/trib3/leakycauldron/blob/main/db/src/main/kotlin/com/trib3/db/converters/YearConverter.kt to configure our fields, and subsequent lookups against `Table.field(alias, Year.class)` work with a varchar backing.

### Actual behavior

With native Year support being added in 3.18.0, our existing varchar backed years break against postgres doing a condition based on this looked up field (see mcve below).  A code path that uses the YearConverter directly works ok, but a different path that uses `Table.field(alias, Year.class)` appears to assume an int backing.

By default that's probably the right thing to do, but is there a way to override the DefaultDataType to assume a varchar based Year instead of an int backed one?

### Steps to reproduce the problem

mcve here: https://github.com/josephlbarnett/jOOQ-mcve/tree/year-int-backing

unit test that just looks to make sure the year is a quoted string vs/ an int literal passes on 3.17.8 but fails on 3.18.0 -- running a query with this condition against h2 appears to work fine, but running against postgres results in 
```
ERROR: operator does not exist: character varying < integer
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
```

### jOOQ Version

3.18.0

### Database product and version

postgres 14

### Java Version

17

### OS Version

ubuntu 22.10

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgres:42.5.4

**Comment by lukaseder** [comment] 2023-03-21 10:07
Thanks for your report and MCVE. I'll look into this shortly.

**Comment by lukaseder** [comment] 2023-03-21 10:26
I see what you mean. The lookup `table.field(x, Class<T>)` coerces the `table.x` field to whatever data type can be looked up from `Class<T>`. When there's a built-in data type, then that should be looked up. For historic reasons, user defined data types also landed in the built-in static type registry, in no well defined order. For example, you could have 3 `Converter<?, Year>` converters on your classpath, and this particular lookup would then produce a "random" one (the one that was first loaded by the static initialisation of generated code).

So, arguably, your code already wasn't safe before 3.18, but now that we natively support the `Year` type, you got new behaviour.

If you don't rely on this `Class<T>` -> `DataType<T>` lookup, but instead use the `DataType<T>` reference directly, then you won't have this problem. So, in the MCVE, write this instead:

```java
    @Test
    public void mcveTest() {
        // Field field = Tables.TEST.field("YEAR", Year.class);
        Field field = Tables.TEST.field("YEAR", Tables.TEST.YEAR.getDataType());
        Assert.assertTrue(field.lt("2022").toString().contains("'2022'"));
    }
```

I don't think this is a bug. Every time we add support for a new `SQLDataType`, some user based assumptions break. Usually, they break at code generation time (e.g. when someone has a converter on a MySQL `YEAR` type, which used to be a `Converter<Short, U>` and now needs to be a `Converter<Year, U>`). This is more subtle, but again, it worked by accident.

I think it may be worth going through the jOOQ API and:

- Better document all `Class<T>` receiving methods, making it clear that only built-in types have defined behaviour
- Possibly discourage using `Class<T>` receiving methods? I'm undecided about this one. I've contemplated deprecating them a few times. It's usually better to use a `DataType<T>` reference, but I understand that `Class<T>` seems more convenient.
- Finally remove that static type registry for user-defined types. That's already being worked on, see #9492, #10312. You should have seen a deprecation warning in your logs, in the past (can you confirm this?): "User-defined, converted data type <type> was registered statically, which will be unsupported in the future, see https://github.com/jOOQ/jOOQ/issues/9492. Please use explicit data types in generated code, or e.g. with DSL.val(Object, DataType), or DSL.inline(Object, DataType)."

It's probably time to double down on the deprecation making it more visible. Possibly throwing a (configurable) exception?

**Comment by lukaseder** [comment] 2023-03-22 08:09
> It'll take a little more work to figure out the best way to deal with those.

Perhaps, just unsafe cast them? `field as Field<Any?>`

> as far as the "User-defined, converted data type was registered statically" warning goes, we haven't noticed it in our logs, not sure what that means

OK, I'll check again if it is really emitted in your case. The point of the warning is to start helping people move away from this API usage, which will be deprecated and removed eventually (because it works by accident rather than by design, leading to issues like this). Obviously, such a removal can't happen for years, still.

**Comment by josephlbarnett** [comment] 2023-03-22 22:13
>> It'll take a little more work to figure out the best way to deal with those.

> Perhaps, just unsafe cast them? `field as Field<Any?>`

turns out we had a datatype available after all: `field(alias, someOtherField.dataType).eq(someOtherField)`, just needed to look at it again with the right lens

thanks for your help and guidance on this, feel free to close as not-a-bug or to use to discourage/deprecate `Class<T>` api methods more in future releases

**Closed** 2023-03-23 10:13 UTC
Labels: C: Functionality, P: Medium, T: Support request, R: Answered, E: All Editions
