### ISSUE TITLE
Remove @Nullable annotation from methods affected by RecordMapper behaviour

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#10777] opened 2020-10-21 15:27 UTC
### Expected behavior

Kotlin code:

```kotlin
val r = jooq.newRecord(MY_TABLE)
r.store()
val p: MyPojo = r.into(MyPojo::class.java)
```

Compiles correctly.

### Actual behavior

Fails to compile due to nullability.

### Versions

- jOOQ: 3.14.0 
- Java: 14
- Kotlin 1.4.10

**Comment by lukaseder** [comment] 2020-10-21 16:04
Duplicate of https://github.com/jOOQ/jOOQ/issues/10774

**Closed** 2020-10-21 20:12 UTC
Labels: C: Functionality, E: All Editions, P: Medium, R: Duplicate, T: Defect
