### ISSUE TITLE
Oracle: jOOQ Insert causes high memory consumption in shared pool

### ISSUE THREAD

**Issue by mnisius** [jOOQ/jOOQ#10310] opened 2020-06-23 11:59 UTC
Hi, one of our dba told us that some insert statements are causing high memory consumption in the shared pool. 

The statement looks like this:

```java
create.insertInto(BEAF)
        .set(BEAF.BEAF_BER_ID, beratungsId)
        .set(BEAF.BEAF_FRA_ID, beantworteteFrage.getFrageId())
        .set(BEAF.BEAF_ANT_ID, beantworteteFrage.getAntwortId())
        .set(BEAF.BEAF_BDA_ID, beantworteteFrage.getBedarfId())
        .set(BEAF.BEAF_ERSTELLT_VON, name)
        .set(BEAF.BEAF_ERSTELLUNGSZEITPUNKT, LocalDateTime.now())
        .set(BEAF.BEAF_WERT, beantworteteFrage.getWert())
```
this is the sql
```sql
"BERATUNG"."BEANTWORTETE_FRAGEN" "beaf" ("BEAF_BER_ID", "BEAF_FRA_ID", "BEAF_ANT_ID", "BEAF_BDA_ID", "BEAF_ERSTELLT_VON", "BEAF_ERSTELLUNGSZEITPUNKT", "BEAF_WERT") 
values (:"SYS_B_0", :"SYS_B_1", :"SYS_B_2", :"SYS_B_3", :"SYS_B_4", cast(timestamp :"SYS_B_5" as date), null);
```

It allocates over 10gig in the shared pool. According to our dba this is because of the cast(timestamp :"SYS_B_5" as date). Oracle seems to create a lot of child cursors for this statement.  

There is also an oracle bug report "Bug 13407937 - High Version Count For Insert with CURSOR_SHARING=FORCE and Timestamp Column" but it is resolved as expected behavior. Can you access this report? I could post a screenshot but I'm not sure if I'm allowed to publish it here on github because you need an oracle account to access it. 

Our DBA suggested to replace the cast(timestamp :"SYS_B_5" as date), with a to_date(:SYS_B_5,'DD.MM.YYYY HH24:MI:SS') but that would mean we had to change every insert statment. Is it possible to change the generated sql in jooq itself? 

### Versions:

- jOOQ:  3.12.1
- Java: 11
- Database (include vendor): Oracle 18
- JDBC Driver (include name if inofficial driver): ojdbc8

**Comment by lukaseder** [comment] 2020-06-24 09:04
Thanks for your report. That's curious - the opinion I generally hear about `CURSOR_SHARING=FORCE` is that it's buggy and generally not recommended to use, see e.g.: https://blog.dbi-services.com/when-changing-cursor_sharing-takes-effect. What's the reason why you're using it? I'm sure this is not the only problem you're having because of this flag...

> I could post a screenshot but I'm not sure if I'm allowed to publish it here on github because you need an oracle account to access it.

You can send us any information in private to the commercial support email address that you have received with your license. If you don't have access to that, there's always `contact@datageekery.com`.

> Our DBA suggested to replace the cast(timestamp :"SYS_B_5" as date), with a to_date(:SYS_B_5,'DD.MM.YYYY HH24:MI:SS') but that would mean we had to change every insert statment.

I think we can fix this on our side as well. The cast is not really required in an `INSERT` statement. The reason why we cast `java.sql.Timestamp` types to Oracle `DATE` is because of improved performance when querying for `DATE` columns, see: https://blog.jooq.org/2014/12/22/are-you-binding-your-oracle-dates-correctly-i-bet-you-arent/

We've already removed a few of these casts from other dialects, when they are happening in a context where it isn't necessary. This is possibly already fixed with https://github.com/jOOQ/jOOQ/issues/2823 - I'll check this soon.

> Is it possible to change the generated sql in jooq itself?

You can attach a custom data type `Binding` to all of your `DATE` types in generated code, but that will affect all statements, including `SELECT`. I suspect this isn't a problem in your case, because the `TO_DATE()` conversion is equivalent to the `CAST()` expression. Here's how to do that:
https://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings/

Let me know if you have any questions about this approach.

**Comment by mnisius** [comment] 2020-06-25 07:57
> That's curious - the opinion I generally hear about CURSOR_SHARING=FORCE is that it's buggy and generally not recommended to use, see e.g.: https://blog.dbi-services.com/when-changing-cursor_sharing-takes-effect. What's the reason why you're using it? I'm sure this is not the only problem you're having because of this flag...

It seems we're using CURSOR_SHARING=FORCE for histroic reasons. We are investigating if we can change this behavoir. 

>You can send us any information in private to the commercial support email address that you have received with your license. If you don't have access to that, there's always contact@datageekery.com.

I've send an e-mail to contact@datageekery.com. 

>I think we can fix this on our side as well. The cast is not really required in an INSERT statement. The reason why we cast java.sql.Timestamp types to Oracle DATE is because of improved performance when querying for DATE columns, see: https://blog.jooq.org/2014/12/22/are-you-binding-your-oracle-dates-correctly-i-bet-you-arent/

If I understand the problem the root cause is not the cast but the usage of timestamp. So I'm not sure if this would have any effect. 

>You can attach a custom data type Binding to all of your DATE types in generated code, but that will affect all statements, including SELECT. I suspect this isn't a problem in your case, because the TO_DATE() conversion is equivalent to the CAST() expression. Here's how to do that:
https://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings/

I will try this as well. 

For now I tried to use the to_date function in actual query but it was rather complicated because we have dateAsTimestamp set to true. So every DSL.toDate call was translated to to_timestamp. 
So I came up with this ugly workaround 

```java
var dateField = DSL.function("to_date", LocalDateTime.class,
      DSL.field("'" + LocalDateTime.now().truncatedTo(SECONDS).toString() + "'", String.class),
      DSL.field("'YYYY-MM-DD\"T\"HH24:MI:SS'", String.class));
```

**Comment by lukaseder** [comment] 2020-06-26 14:09
> If I understand the problem the root cause is not the cast but the usage of timestamp. So I'm not sure if this would have any effect.

Oh interesting, well you can of course implement your own data type binding and bind an `oracle.sql.DATE` value from the ojdbc driver. That would make the cast or conversion unnecessary.

**Comment by mnisius** [comment] 2020-06-30 11:30
I think I understand now what the problem was. 

1. cursor_sharing=force as our default setting
2. the usage of a jdbc batch statment with literals instead of bind values  -> create.batch(statmentList).execute();

because of the forced cursor sharing this cursor was extracted 
```sql
"BERATUNG"."BEANTWORTETE_FRAGEN" "beaf" ("BEAF_BER_ID", "BEAF_FRA_ID", "BEAF_ANT_ID", "BEAF_BDA_ID", "BEAF_ERSTELLT_VON", "BEAF_ERSTELLUNGSZEITPUNKT", "BEAF_WERT") 
values (:"SYS_B_0", :"SYS_B_1", :"SYS_B_2", :"SYS_B_3", :"SYS_B_4", cast(timestamp :"SYS_B_5" as date), null)
```
however if jooq generates a statement with bind variables it looks lke this
```sql
"BERATUNG"."BEANTWORTETE_FRAGEN" "beaf" ("BEAF_BER_ID", "BEAF_FRA_ID", "BEAF_ANT_ID", "BEAF_BDA_ID", "BEAF_ERSTELLT_VON", "BEAF_ERSTELLUNGSZEITPUNKT", "BEAF_WERT") 
values (:1, :2, :3, :4, :5", cast(:6 as date), null)
```sql

As you can see the timestamp is not part of the cursor and so there is no problem with to many child cursors. 
Because we still want to send multiple statments to the database I'm simply going to change 

```java
create.batch(statmentList).execute();
```
to 

```java
create.statment(statmentList).execute();
```
This begin/end block uses bind variables and the problem should be gone. We're also setting cursor_sharing=exact for this application and consider using this setting in all our new java applications. Thanks for the hint

**Comment by lukaseder** [comment] 2020-06-30 12:54
Oh, I see, that's very interesting, thanks for clarifying this here.

Does `statementList` contain "heterogeneous" statements, i.e. statements of different types and inserting into different tables? Otherwise, you probably meant to use the "single query" batch API in jOOQ:
https://www.jooq.org/doc/latest/manual/sql-execution/batch-execution/

Or, alternatively, even the import API:
https://www.jooq.org/doc/latest/manual/sql-execution/importing/importing-records

**Comment by mnisius** [comment] 2020-06-30 14:04
Yes in this case the statementList does indeed contain heterogeneous statements.
Still good to know that it is possible use bind variables with jdbc batch statments as well. 

Are there any benefits in using jdbc batch statments over an anonymous begin/end block?

**Comment by lukaseder** [comment] 2020-06-30 14:09
Well, since we're talking about cursor cache optimisations, I would say that if all the statements are the same, then a JDBC batch will produce less cursor cache contention...

**Comment by lukaseder** [comment] 2020-07-02 15:31
I'm closing this. I don't think we can do much here without risking regressions for other users. `cursor_sharing=force` is known to cause a variety of issues in Oracle, and the `TIMESTAMP` type originates from a rewrite of the query by Oracle. The workarounds are provided.

Please let me know if I can be of any further assistance here.

**Closed by lukaseder** 2020-07-02 15:31 UTC
Labels: C: DB: Oracle, C: Functionality, E: Enterprise Edition, E: Professional Edition, P: Medium, T: Support request

**Comment by mnisius** [comment] 2020-07-02 15:33
Yes this is solved. Thanks again for the help
