### ISSUE TITLE
context.batchInsert().onDuplicateKeyIgnore()

### ISSUE THREAD

**Issue by asm0dey** [jOOQ/jOOQ#6092] opened 2017-04-17 19:35 UTC
I would like to perform batchInsert and have option to add ignore inserts with errors. Postgres JDBC driver optimises batch insert very fine.

**Comment by lukaseder** [comment] 2017-04-18 18:18
Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/3172 (update / ignore actions are treated as the same, here)

Note, there's an option to do this with the `Loader` API:
https://www.jooq.org/doc/latest/manual/sql-execution/importing

**Closed by lukaseder** 2017-04-18 18:18 UTC
Labels: C: Functionality, P: Medium, T: Enhancement
