### ISSUE TITLE
DATE column in Oracle is null when fetched through multiset

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#16043] opened 2024-01-09 18:48 UTC
### Expected behavior

Getting a DATE column in a multiset should get the value from the database.

### Actual behavior

Getting a DATE column in a multiset results in NULL.

### Steps to reproduce the problem

https://github.com/alf/jOOQ-mcve/commit/b9b0378cbb3e95c7e29df3d4816470a32c849556

### jOOQ Version

3.19.1

### Database product and version

Oracle 18 XE

**Comment by lukaseder** [comment] 2024-01-10 06:39
Thanks for your report. Interesting, a very similar integration test doesn't fail, so let's see what's different about yours. I'll look into this right away.

**Comment by lukaseder** [comment] 2024-01-10 06:43
I can reproduce the issue with this log entry:

```
07:42:17,187 DEBUG [org.jooq.tools.LoggerListener                     ] - Affected row(s)          : 0
07:42:17,261 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : insert into "MCVE"."TEST" ("DATE_CREATED") values (cast(? as date))
07:42:17,261 DEBUG [org.jooq.tools.LoggerListener                     ] - -> with bind values      : insert into "MCVE"."TEST" ("DATE_CREATED") values (date '2024-01-10')
07:42:33,307 DEBUG [org.jooq.tools.LoggerListener                     ] - Affected row(s)          : 1
07:42:33,625 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : select (select coalesce(json_arrayagg(json_array("t"."v0" null on null returning clob) format json returning clob), json_array(returning clob)) from (select "MCVE"."TEST"."DATE_CREATED" "v0" from "MCVE"."TEST") "t") from "MCVE"."TEST"
07:42:33,728 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched result           : +----------+
07:42:33,728 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |multiset  |
07:42:33,728 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +----------+
07:42:33,728 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |[({null})]|
07:42:33,729 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +----------+
07:42:33,729 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched row(s)           : 1
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 19.722 s <<< FAILURE! - in org.jooq.mcve.test.java.oracle.JavaTest
[ERROR] org.jooq.mcve.test.java.oracle.JavaTest.mcveTest  Time elapsed: 16.735 s  <<< FAILURE!
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertNotNull(Assert.java:713)
        at org.junit.Assert.assertNotNull(Assert.java:723)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at org.jooq.mcve.test.java.oracle.JavaTest.mcveTest(JavaTest.java:115)
```

**Comment by lukaseder** [comment] 2024-01-10 08:54
Interesting, this seems to be `DATE` and `JSON` specific, it works for `DATE` and `XML` emulations, as well as for `TIMESTAMP` in both emulation types.

The issue was known in the integration tests, but there hasn't been an issue registered for tracking, which is why this hasn't been noticed.

**Comment by lukaseder** [comment] 2024-01-10 08:55
This illustrates the problem:

```sql
select (
  select coalesce(
    json_arrayagg(json_array("t"."v0" null on null returning clob) format json returning clob),
    json_array(returning clob)
  )
  from (
    select null "v0"
    union all
    select date '2000-03-15' "a"
  ) "t"
  group by null
)
```

It produces:

```
[[null],["2000-03-15T00:00:00"]]
```

There's unexpected timestamp information being generated by Oracle in the `DATE` to `JSON` conversion. I suspect we just have to be more lenient when parsing date information and accept timestamps as well, truncating the time information.

**Comment by lukaseder** [comment] 2024-01-10 09:01
Ah, yes obviously... Oracle's `DATE` type is really a `TIMESTAMP(0)`, thus, we must expect time information

**Comment by alf** [comment] 2024-01-10 09:17
So happy I can leave getting these things right to you. :1st_place_medal:

**Comment by lukaseder** [comment] 2024-01-10 09:39
Well, you're welcome :) Thanks for these high quality bug reports!

**Comment by lukaseder** [comment] 2024-01-10 09:43
There's an additional issue regarding the `TIME` data type:

- https://github.com/jOOQ/jOOQ/issues/16048

I'll fix that one later. `TIME` is a much less frequent data type (especially in Oracle), than `DATE`.

**Comment by lukaseder** [comment] 2024-01-10 09:51
I'll release 3.19.2 soon with a fix. Until then, you can probably format your date using `TO_CHAR()` and a `YYYY-MM-DD` mask, and then coerce the expression back to `DATE`? This seems to work for me:

```java
System.out.println(
    ctx
    .select(multiset(select(
        DSL.toChar(
            val(Date.valueOf("2000-01-01")),
            "YYYY-MM-DD"
        ).coerce(SQLDataType.DATE)
    )))
    .fetchOne()
);

Printing:

```
+--------------+
|multiset      |
+--------------+
|[(2000-01-01)]|
+--------------+
```
```

**Comment by lukaseder** [comment] 2024-01-10 10:03
Fixed in versions

- 3.20.0
- 3.19.2 (https://github.com/jOOQ/jOOQ/issues/16049)
- 3.18.9 (https://github.com/jOOQ/jOOQ/issues/16050)
- 3.17.18 (https://github.com/jOOQ/jOOQ/issues/16051)

**Closed by lukaseder** 2024-01-10 10:03 UTC
Labels: T: Defect, C: Functionality, C: DB: Oracle, P: High, E: Professional Edition, E: Enterprise Edition

**Comment by alf** [comment] 2024-01-10 10:11
Thank you. We can wait until 3.19.2 before we enable multiset for the few cases where this hits us. :)
