### ISSUE TITLE
Cannot use Table as SelectField from derived table where nesting records is supported natively

### ISSUE THREAD

**Issue by diastremskii** [jOOQ/jOOQ#13843] opened 2022-08-09 09:56 UTC
### Expected behavior

When using `.as` method together with row value expressions, column alias should be added to the query.

### Actual behavior

In case of using `row().as()`, the alias is not added to the query.
In case of using the table directly, the alias is added, but it's wrapped inside `cast`, so it's not possible to reference it.
Examples are below.

### Steps to reproduce the problem

Let's say we have a simple table like that:
```sql
CREATE TABLE example_table (
    id              uuid             PRIMARY KEY
);
```

And we want to select all fields with row value expression and add an alias to the row.
**Option 1:**
```kotlin
val subquery = context.select(EXAMPLE_TABLE).from(EXAMPLE_TABLE)
context.selectFrom(subquery).execute()
```
<details>
<summary>Generated query</summary>

```sql
SELECT
    alias_118559696.example_table
FROM
    (
        SELECT
            cast (ROW (example_table.*) AS example_table)
        FROM
            example_table
    ) AS alias_118559696
```
</details>

In this case, because the row is wrapped in `cast`, the alias isn't visible to the outer query and the query fails.

**Option 2:**
```kotlin
val subquery = context.select(EXAMPLE_TABLE.`as`("alias")).from(EXAMPLE_TABLE)
context.selectFrom(subquery).execute()
```
<details>
<summary>Generated query</summary>

```sql
SELECT
    alias_111737497.alias
FROM
    (
        SELECT
            cast (ROW (alias.*) AS example_table)
        FROM
            example_table
    ) AS alias_111737497
```
</details>

In this case, we are trying to select `alias.*`, which doesn't exist and the query fails.

**Option 3:**
```kotlin
val subquery = context.select(field(EXAMPLE_TABLE).`as`("alias")).from(EXAMPLE_TABLE)
context.selectFrom(subquery).execute()
```
<details>
<summary>Generated query</summary>

```sql
SELECT
    alias_118559696.alias
FROM
    (
        SELECT
            cast (ROW (example_table.*) AS example_table)
        FROM
            example_table
    ) AS alias_118559696
```
</details>

In this case, the alias is represented in the outer query, but the inner query doesn't have it (and also has a `cast`) and the query fails.

**Option 4:**
```kotlin
val subquery = context.select(EXAMPLE_TABLE.fieldsRow().`as`("alias")).from(EXAMPLE_TABLE)
context.selectFrom(subquery).execute()
```
<details>
<summary>Generated query</summary>

```sql
SELECT
    alias_72309234.alias
FROM
    (
        SELECT
            ROW (example_table.id)
        FROM
            example_table
    ) AS alias_72309234
```
</details>

In this case, alias isn't added to the generated subquery, but it is present in the outer query and the query fails.

#### Possible workaround:
It's possible to do something like that, to select `ROW (table.*) AS alias` without using DSL. Perhaps it's possible to construct the same query using DSL, but I'm not sure how.
```kotlin
val subquery = context
    .select(field("ROW (example_table.*)", ExampleTableRecord::class.java).`as`("alias"))
    .from(EXAMPLE_TABLE)
context.selectFrom(subquery).execute()
```
<details>
<summary>Generated query</summary>

```sql
SELECT
    alias_91537551.alias
FROM
    (
        SELECT
            ROW (example_table.*) AS alias
        FROM
            example_table
    ) AS alias_91537551
```
</details>

### Versions

- jOOQ: 3.17.2
- Java: 17.0.3
- Database (include vendor): PostgreSQL
- OS: MacOS
- JDBC Driver (include name if unofficial driver): 42.4.0

**Comment by lukaseder** [comment] 2022-08-31 09:01
Thanks a lot for your report. I think there are multiple problems here, which are kinda related, but perhaps not all easy to solve. I'll look into individual "options" and then possibly create separate issues to resolve problems individually.

**Comment by lukaseder** [comment] 2022-08-31 10:24
Looking into the details of this, it's probably not really multiple unrelated issues. The existing aliasing isn't implemented correctly, and it has to work together with the new "auto aliasing" that has to be implemented. I'll fix all of these concerns in this single issue.

Thanks again for showing these multiple attempts. Many of them have been already part of expected integration test failures, listed on some internal TODO list. Great reminder to address them now.

**Comment by lukaseder** [comment] 2022-08-31 13:08
New issue for non-PostgreSQL compatible dialects: https://github.com/jOOQ/jOOQ/issues/13940

**Comment by lukaseder** [comment] 2022-08-31 13:34
Your option 2 is indeed a different case: https://github.com/jOOQ/jOOQ/issues/13941

```java
val subquery = context.select(EXAMPLE_TABLE.`as`("alias")).from(EXAMPLE_TABLE)
context.selectFrom(subquery).execute()
```

The problem is that `SelectField.as()` conflicts with `Table.as()`, which has different semantics when used in `SELECT` or `FROM`. An explanation is in #13941. Perhaps we can disambiguate the semantics, but since that problem has nothing to do with projecting tables from derived tables, I'll prefer moving the discussion to #13941

**Comment by lukaseder** [comment] 2022-08-31 13:39
Options 3 and 4 are the same problem as option 1, and will be fixed by the same fix.

**Comment by lukaseder** [comment] 2022-08-31 13:53
Fixed in jOOQ 3.18.0 and 3.17.4 (https://github.com/jOOQ/jOOQ/issues/13943). Thanks again for your report.

If you have time to test this and provide early feedback based on your real world queries, that would be very useful.

**Comment by lukaseder** [comment] 2022-08-31 13:53
3.17 patch here: https://github.com/jOOQ/jOOQ/commit/89bcd7543116a4d6ef71ad46be6edb49f1f87502.patch

**Closed by lukaseder** 2022-08-31 13:53 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions

**Comment by diastremskii** [comment] 2022-09-12 09:16
Thank you for investigating and for the fix! Yes, it does work on real world queries as well :)
There are some duplicated aliases or different levels of nesting, like `SELECT cast (ROW (example_table.*) AS example_table) AS example_table`, but it does work.
The only issue was with subquery used as expression, i.e. the code like this
```
val subquery = context
    .select(
        field(select(EXAMPLE_TABLE))
    )
    .from(EXAMPLE_TABLE)
context.selectFrom(subquery).execute()
```
generates a query like this:
```
SELECT
    alias_73405056."select"
FROM
    (
        SELECT
            (
                SELECT
                    cast (ROW (example_table.*) AS example_table) AS example_table
            )
        FROM
            example_table
    ) AS alias_73405056
```
that fails because there is no alias `select`.
Of course, it can be fixed by manually adding an alias:
```
val subquery = context
    .select(
        field(select(EXAMPLE_TABLE)).`as`("example_table")
    )
    .from(EXAMPLE_TABLE)
context.selectFrom(subquery).execute()
```
which generates
```
SELECT
    alias_66394886.example_table
FROM
    (
        SELECT
            (
                SELECT
                    cast (ROW (example_table.*) AS example_table) AS example_table
            ) AS example_table
        FROM
            example_table
    ) AS alias_66394886
```
, but this way there are three aliases with the same name. Not that it's a big issue, just an observation.

**Comment by lukaseder** [comment] 2022-09-14 12:55
> There are some duplicated aliases or different levels of nesting, like `SELECT cast (ROW (example_table.*) AS example_table) AS example_table`, but it does work.

Those aren't the same kind of `AS` tokens, syntactically. One is part of the cast, the other is an alias.

> The only issue was with subquery used as expression, i.e. the code like this

Thanks. I've created a new issue: https://github.com/jOOQ/jOOQ/issues/13988. I prefer tracking separate problems as separate issues, even if they're loosely related.
