### ISSUE TITLE
MySQL error "BLOB, TEXT, GEOMETRY or JSON column can't have a default value" when running DDL from generated code

### ISSUE THREAD

**Issue by trydofor** [jOOQ/jOOQ#16853] opened 2024-06-25 03:12 UTC
### Expected behavior

in https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html#data-type-defaults-explicit

> The [BLOB](https://dev.mysql.com/doc/refman/8.0/en/blob.html), [TEXT](https://dev.mysql.com/doc/refman/8.0/en/blob.html), GEOMETRY, and [JSON](https://dev.mysql.com/doc/refman/8.0/en/json.html) data types can be assigned a default value only if the value is written as an expression, even if the expression value is a literal:

```sql
`current`  TEXT NOT NULL DEFAULT ('') COMMENT 'current value',
```

```java
//WinConfRuntimeTable.java
// should some one with `()`
defaultValue(DSL.inline("(\\'\\')"
defaultValue(DSL.inline("('')"
```

### Actual behavior

```java
//WinConfRuntimeTable.java
    /**
     * The column <code>win_conf_runtime.current</code>.
     */
    public final TableField<WinConfRuntimeRecord, String> Current = createField(
DSL.name("current"), 
SQLDataType.CLOB.nullable(false)
.defaultValue(DSL.inline("_utf8mb4\\'\\'", SQLDataType.CLOB)), this, "");
```

### Steps to reproduce the problem

(1) create a table with column `TEXT NOT NULL DEFAULT ('')`

```sql
`current`  TEXT NOT NULL DEFAULT ('') COMMENT 'current value',
```

(2) jooq generate the Table object
(3) check the java field

### jOOQ Version

3.18.9

### Database product and version

mysql 8.0.35

### Java Version

java 21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

mysql-connector-j-8.3.0.jar

**Comment by lukaseder** [comment] 2024-06-25 06:16
Thanks for your report.

Just to confirm, the missing parentheses are the problem in your opinion?

I can confirm these work in MySQL:

```sql
create table t (i varchar(10) default '');
create table t (i varchar(10) default (''));
create table t (i text default (''));
```

But this doesn't:

```sql
create table t (i varchar(10) text '');
```

The error being:

> SQL Error [1101] [42000]: BLOB, TEXT, GEOMETRY or JSON column 'i' can't have a default value

**Comment by lukaseder** [comment] 2024-06-25 06:18
The limitation doens't appear in MariaDB, this is a MySQL only problem. Obviously a bug, because the error message claims there's no way to define a default, yet there is.

**Comment by lukaseder** [comment] 2024-06-25 06:25
A similar issue has been fixed just recently for SQLite:

- https://github.com/jOOQ/jOOQ/issues/15943

**Comment by lukaseder** [comment] 2024-06-25 06:28
MemSQL also doesn't have this limitation. It's hard to see why this should be a limitation in the first place... Anyway, we'll work around it, as always.

**Comment by lukaseder** [comment] 2024-06-25 06:41
It's not a code generation problem. The default  expression doesn't really need parentheses generated. Much rather, we should render the parentheses at runtime. E.g. this new integration test would still fail if we fixed this only in the code generator:

```java
public void testCreateTableWithConstantDefaultsMySQLTextLimitation() throws Exception {
    assumeSupportsBinaryTypes();

    try {
        byte[] a = new byte[] { 'a' };

        Field<String> s = field("s", CLOB.default_("a"));
        Field<byte[]> b = field("b", BLOB.default_(a));

        create().createTable(t)
                .column(dummy)
                .column(s)
                .column(b)
                .primaryKey(dummy)
                .execute();

        assertEquals(1,
        create().insertInto(t)
                .columns(dummy)
                .values(1)
                .execute());

        Record2<String, byte[]> r = create().select(s, b).from(t).fetchOne();
        assertEquals("a", r.get(s));
        assertArrayEquals(a, r.get(b));
    }
    finally {
        ignoreThrows(drop(t));
    }
}
```

**Comment by lukaseder** [comment] 2024-06-25 06:51
Fixed in versions:

- 3.20.0
- 3.19.11 (https://github.com/jOOQ/jOOQ/issues/16855)
- 3.18.18 (https://github.com/jOOQ/jOOQ/issues/16857)
- 3.17.27 (https://github.com/jOOQ/jOOQ/issues/16856)

**Closed by lukaseder** 2024-06-25 06:51 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: All Editions
