### ISSUE TITLE
Warning exception slow query.

### ISSUE THREAD

**Issue by mickmcl** [jOOQ/jOOQ#7949] opened 2018-10-17 11:29 UTC
### Expected behavior and actual behavior:
Expected build log to not contain stacktrace exceptions while generating jooq objects.
### Versions:
3.15.1
- jOOQ:
- Java: 1.8
- Oracle 12c
- OS: Windows
- JDBC Driver (include name if inofficial driver): Hikari

[INFO] Generating catalogs      : Total: 1
[WARNING] Slow SQL                 : Total: 16.169s
[WARNING] Slow SQL                 : jOOQ Meta executed a slow query (slower than 5 seconds, configured by configuration/generator/database/logSlowQueriesAfterSeconds)

Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new

```sql
select 
  "s3"."OWNER", 
  "s3"."SYNONYM_NAME", 
  connect_by_root "s3"."TABLE_OWNER" "TABLE_OWNER", 
  connect_by_root "s3"."TABLE_NAME" "TABLE_NAME", 
  substr(
    ((((sys_connect_by_path((("s3"."TABLE_OWNER" || '.') || "s3"."TABLE_NAME"), ' <- ') || ' <- ') || "s3"."OWNER") || '.') || "s3"."SYNONYM_NAME"), 
    5
  )
from (
  select 
    "s2"."OWNER", 
    "s2"."SYNONYM_NAME", 
    "s2"."TABLE_OWNER", 
    "s2"."TABLE_NAME"
  from (
    (
      select 
        "SYS"."ALL_SYNONYMS"."OWNER", 
        "SYS"."ALL_SYNONYMS"."SYNONYM_NAME", 
        "SYS"."ALL_SYNONYMS"."TABLE_OWNER", 
        "SYS"."ALL_SYNONYMS"."TABLE_NAME"
      from "SYS"."ALL_SYNONYMS"
    )
    union (
      select 
        "SYS"."ALL_SYNONYMS"."OWNER", 
        "SYS"."ALL_SYNONYMS"."SYNONYM_NAME", 
        'PUBLIC', 
        "SYS"."ALL_SYNONYMS"."TABLE_NAME"
      from "SYS"."ALL_SYNONYMS"
    )
  ) "s2"
  where ("s2"."OWNER", "s2"."SYNONYM_NAME") <> (("s2"."TABLE_OWNER", "s2"."TABLE_NAME"))
) "s3"
start with exists (
  select 1 "one"
  from "SYS"."ALL_OBJECTS"
  where (
    "s3"."TABLE_OWNER" = "SYS"."ALL_OBJECTS"."OWNER"
    and "s3"."TABLE_NAME" = "SYS"."ALL_OBJECTS"."OBJECT_NAME"
    and "SYS"."ALL_OBJECTS"."OBJECT_TYPE" <> 'SYNONYM'
    and "SYS"."ALL_OBJECTS"."OWNER" in (
      'TDAPP', 'TDRUN', 'THIE'
    )
  )
)
connect by (
  "s3"."TABLE_OWNER" = prior "s3"."OWNER"
  and "s3"."TABLE_NAME" = prior "s3"."SYNONYM_NAME"
)```

org.jooq.meta.AbstractDatabase$1$SQLPerformanceWarning
	at org.jooq.meta.AbstractDatabase$1.executeEnd(AbstractDatabase.java:292)
	at org.jooq.impl.ExecuteListeners.executeEnd(ExecuteListeners.java:181)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:269)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:323)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2700)
	at org.jooq.meta.oracle.OracleDatabase.getSynonym(OracleDatabase.java:1134)
	at org.jooq.meta.oracle.OracleDatabase.getTypeInfo(OracleDatabase.java:1168)
	at org.jooq.meta.oracle.OracleDatabase.getArrays0(OracleDatabase.java:656)
	at org.jooq.meta.AbstractDatabase.getArrays(AbstractDatabase.java:1480)
	at org.jooq.codegen.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:415)
	at org.jooq.codegen.JavaGenerator.generateCatalogIfEmpty(JavaGenerator.java:405)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:379)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:750)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:220)
	at org.jooq.codegen.maven.Plugin.execute(Plugin.java:197)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

**Comment by lukaseder** [comment] 2019-01-15 18:37
I'm very sorry for the delay. This issue didn't get triaged as it should have.

Does the issue still persist? How many synonyms do you have in your system?

**Comment by lukaseder** [comment] 2020-01-15 15:48
Closing this, as I could not reproduce this issue when it was reported.

Feel free to reopen if the issue persists.

**Closed by lukaseder** 2020-01-15 15:48 UTC
Labels: C: Code Generation, E: Enterprise Edition, E: Professional Edition, P: Medium, R: Feedback Pending, T: Defect
