### ISSUE TITLE
Advanced Queue, when dequeueing with correlation: SQLException: Invalid column index

### ISSUE THREAD

**Issue by retoo** [jOOQ/jOOQ#4781] opened 2015-12-04 14:33 UTC
```java
            MESSAGE_PROPERTIES_T msgProperties = new MESSAGE_PROPERTIES_T();
            DEQUEUE_OPTIONS_T dequeueOptions = new DEQUEUE_OPTIONS_T();
            EventMsgTypeRecord result = DBMS_AQ.dequeue(create.configuration(),
                        Queues.EVENT_QUEUE, 
                        dequeueOptions,
                        msgProperties);
```

Exception:
```
Exception in thread "main" org.jooq.exception.DataAccessException: Error while dequeuing message
	at org.jooq.util.oracle.OracleDSL$DBMS_AQ.dequeue(OracleDSL.java:790)
	at Aq.main(Aq.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.sql.SQLException: Invalid column index
	at oracle.jdbc.driver.OracleCallableStatement.getObject(OracleCallableStatement.java:2289)
	at oracle.jdbc.driver.OracleCallableStatementWrapper.getObject(OracleCallableStatementWrapper.java:826)
	at org.jooq.util.oracle.OracleDSL$DBMS_AQ.dequeue(OracleDSL.java:787)
	... 6 more

Process finished with exit code 1
```

```plsql
CREATE OR REPLACE TYPE event_msg_type AS OBJECT (
  name            VARCHAR2(10),
  current_status  NUMBER(5),
  next_status     NUMBER(5)
);

SET serveroutput on;
BEGIN
 DBMS_AQADM.create_queue_table (
   queue_table            =>  'event_queue_tab',
   queue_payload_type     =>  'event_msg_type');
end;
/

BEGIN
  DBMS_AQADM.create_queue (
   queue_name            =>  'event_queue',
   queue_table           =>  'event_queue_tab');
end;
/
BEGIN

  DBMS_AQADM.start_queue (
   queue_name         => 'event_queue',
   enqueue            => TRUE);
end;
/
```

and enqueue:

```plsql
DECLARE

  r_enqueue_options    DBMS_AQ.ENQUEUE_OPTIONS_T;
  r_message_properties DBMS_AQ.MESSAGE_PROPERTIES_T;
  v_message_handle     RAW(16);
  o_payload            event_msg_type;

BEGIN

  o_payload := event_msg_type('test', 1,4);
   r_message_properties.correlation := 'foo';

  DBMS_AQ.ENQUEUE(
      queue_name         => 'event_queue',
      enqueue_options    => r_enqueue_options,
      message_properties => r_message_properties,
      payload            => o_payload,
      msgid              => v_message_handle
  );

  COMMIT;

END;
/
```

**Comment by lukaseder** [comment] 2015-12-05 12:31
See also: #4782

**Comment by lukaseder** [comment] 2015-12-05 12:32
Thanks for this submission. It seems as though this API really isn't properly integration tested...

**Comment by lukaseder** [comment] 2015-12-08 15:30
Closing this as a duplicate of #4782

**Closed by lukaseder** 2015-12-08 15:30 UTC
Labels: C: Functionality, P: High, R: Duplicate, T: Defect
