### ISSUE TITLE
Problem with DSL.inline wrapped in DSL.selectQuery

### ISSUE THREAD

**Issue by cajar1988** [jOOQ/jOOQ#4573] opened 2015-09-22 11:01 UTC
### Description
I have to mix real columns with literals in single SELECT query.
For some reasons this query must be wrapped one more time by DSL.selectQuery. Result query has bad syntax: it tries to refer my literal column like as if it were a real DB column.

Version of jOOQ: 3.6.2.

### Example:
Code:
```
SelectJoinStep<Record3<Object, Object, String>> sampleQuery = getDSL()
				.select(field("code"), field("subject"), inline("some value"))
				.from("invoice");

System.out.println(sampleQuery.getSQL());
System.out.println(getDSL().selectQuery(sampleQuery).getSQL());
```

Result:
`select code, subject, 'some value' from invoice` - this query works fine

`select "alias_64689313"."code", "alias_64689313"."subject", "alias_64689313"."some value" from (select code, subject, 'some value' from invoice) as "alias_64689313"` - this query is broken - there's no column 'some value' in aliased table

**Comment by lukaseder** [comment] 2015-09-27 11:15
Thanks for reporting. This is indeed an issue that we've known as #579. The workaround is to give all non-top-level select statement expressions an explicit name by aliasing them as you would in regular SQL. I.e.

```sql
SELECT code, subject, some_value
FROM (
  SELECT code, subject, 'some value' AS some_value
  FROM invoice
) t
```

I'm closing this as Duplicate of #579, which we certainly should fix eventually, as we should generate these aliases in case they're absent.

**Closed by lukaseder** 2015-09-27 11:15 UTC
Labels: C: Functionality, P: Medium, T: Defect
