### ISSUE TITLE
reactive stream support

### ISSUE THREAD

**Issue by hepin1989** [jOOQ/jOOQ#4485] opened 2015-08-20 09:03 UTC
how about provide reactive stream support?
we are currently using jooq,in a akka cluster as a db node.
we want to streaming the operation to the db directly with akka stream ,thanks.
this would be a nice addition.

the query side maybe simpler,so we could do this first.:)

**Comment by lukaseder** [comment] 2015-08-20 09:24
Thank you very much for your suggestion. Thus far, we haven't seen jOOQ as the right place to implement explicit support for "asynchronous" transaction semantics (or at least emulation thereof) - given our strategy that the transaction semantics is the responsibility of the client architecture, not jOOQ.

However, we're always open to low-hanging fruit, e.g. to allow for a very easy configuration of such a semantics. I'd love to learn more about your current implementation, and where you'd like to go with it. Do you have any examples of how you're currently using jOOQ in your akka cluster, and what kind of API you'd like to have in jOOQ?

**Comment by hepin1989** [comment] 2015-08-20 10:04
@lukaseder AFAIK,the slick project just implement the query side too,which return a publisher of the result.which means return the ```Seq[R]``` to ```Publisher[R] ```,and the write side have not implemented yet.and the reactive-kafka project which implement both  write and query side.and the write side implemented as ```Subscriber[R] ``` which we need stream data to it,and the query side as ```Publisher[R]``` which we need to attach a sink/flow to consume the data from a specified topic too.

so back to the JOOQ.We are defined some Command in Protobuf and sending the Command to the db node in an actor level message,then at the db node,one table one actor,and and the actor have specified actor for CRUD,do the actually work.what I want is:

-  return a ```Publisher[R]``` for a query and then I could start a new actor the streaming the data to the consumer 
- return a ```Subscriber[T]``` for a batch insert,then I could streaming the data from the node to it.

both of this is very useful when I have a big datasheet ,we are using JOOQ for our game server,where we need streaming data from the db to some service ,so I think that if JOOQ have RS implement would be very great,to handle potential load and provide a better way to compose with other RS implement.

thanks for JOOQ.




`

**Comment by hepin1989** [comment] 2015-08-20 10:14
I think could make ```ResultQuery<R>``` extends ```Publiser<R>```?

**Comment by lukaseder** [comment] 2015-08-20 12:24
Oh, interesting. What game server is this and what database are you using, if I may ask?

In any case thank you very much for your feedback. Your explanations cover well what I've seen in various presentations. In any case, we can not extend `Publisher` right now as we don't want to add any such external dependency to jOOQ. However, we could implement bridge logic, especially in the Scala project, where `implicit` allows us to extend our API without modifying it.

One thing that I have never seen answered in any presentation is the question regarding a `Publisher[R]` modelling a given `ResultSet` and the implications of keeping open cursors with potential read locks in the database. I would imagine that this is a rather dangerous situation in an MVCC database from an UNDO/REDO log perspective, especially when the `Subscriber` isn't very fast. How big will your results be?

Similar things are true for exposing a `Subscriber[R]` for batch insert, where long-running transactions aren't really desireable. It's better to divide the batch into chunks of certain bulk / batch / commit sizes. That is also something that I haven't seen in any presentation yet. Perhaps, the added value of jOOQ would be to provide means for configuring the individual fetch / insert batch sizes on various levels to keep transactions short-running.

Finally, I think we agree that an exposed `Publisher[R]` is only useful for `SELECT`, whereas an exposed `Subscriber[R]` is only useful for `INSERT`, e.g. in a CQRS environment, or do you have a different take, here?

**Comment by hepin1989** [comment] 2015-08-21 02:31
@lukaseder 
For your question:
- our gameserver is totally based on typesafe stack + JOOQ,and it's online in the appstore now,new game is developing too.
- database is mysql,try to switch to postgresql,but time limited.

And for the RS implement ,you are right I could implement once simply with the current API,and provide it as a thin wrapper,but the implicit is will not help the java side:).and for the read side,we have a master and some slaver db node,so that maybe not a problem.and the result is like 10K+ records,depends on players.

And for the batch insert ,yes the problem is there and I could implement the application level backpressure and then do the batch insert to the JOOQ too,I am doing something like these in part of the system.

So the final words is If JOOQ provide one,it would be nice,if not,the current API is so convenient for implementation too.

Thanks lukaseder.

**Comment by lukaseder** [comment] 2015-08-24 09:58
Thanks for the additional info.

We'll certainly keep an eye out on possibilities that may arise with an integration of "reactive" APIs in jOOQ. Glad to hear that you can find a short-term solution on your side, though, as this may still take some time.

I will be putting this on the long-term roadmap for now.

**Comment by lukaseder** [comment] 2015-09-11 09:53
I suspect that the efforts to be made for "Reactive jOOQ", i.e. "Reactive `Cursor`" in jOOQ will match what is described in this issue here: #4371.

There are signs that JDK 9 will include a "reactive" API via a new `java.util.concurrent.Flow` type and its nested types. See: http://cs.oswego.edu/pipermail/concurrency-interest/2015-January/013641.html.

So, I'll close this discussion as a duplicate of #4371

**Closed by lukaseder** 2015-09-11 09:53 UTC
Labels: C: Functionality, P: Medium, T: Enhancement

**Comment by hepin1989** [comment] 2015-09-11 11:29
@lukaseder I knew that ,thanks for update .
