### ISSUE TITLE
Query gets affected by previous query and unexpectedly fails (seems that caching in DefaultDataType causes the problem)

### ISSUE THREAD

**Issue by Tsar** [jOOQ/jOOQ#14165] opened 2022-11-02 10:25 UTC
### Expected behavior

I expect that two SELECT-queries run independently and finish successfully. See the code in "steps to reproduce".

Expected console output:
```
0
1
```

### Actual behavior

Second SELECT-query crashes with the following error:
```
SQL [select row (array_agg(row (test_table.id, test_table.id))) as nested from test_table group by test_table.id]; Error while reading field: row (array_agg(row ("test_table"."id", "test_table"."id"))), at JDBC index: 1
org.jooq.exception.DataAccessException: SQL [select row (array_agg(row (test_table.id, test_table.id))) as nested from test_table group by test_table.id]; Error while reading field: row (array_agg(row ("test_table"."id", "test_table"."id"))), at JDBC index: 1
	at org.jooq_3.17.4.POSTGRES.debug(Unknown Source)
	at org.jooq_3.17.4.POSTGRES.debug(Unknown Source)
	at app//org.jooq.impl.Tools.translate(Tools.java:3307)
	at app//org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:678)
	at app//org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1464)
        <.......>
Caused by: java.sql.SQLException: Error while reading field: row (array_agg(row ("test_table"."id", "test_table"."id"))), at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1590)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1525)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1484)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1449)
	... 94 more
Caused by: org.jooq.exception.DataTypeException: Error while creating array
	at app//org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgNewArray(DefaultBinding.java:4013)
	at app//org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgFromString(DefaultBinding.java:3911)
	at app//org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgSetValue(DefaultBinding.java:3984)
	at app//org.jooq.impl.DefaultBinding$DefaultRecordBinding.lambda$pgNewRecord$13(DefaultBinding.java:3976)
	at app//org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at app//org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgNewRecord(DefaultBinding.java:3972)
	at app//org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3767)
	at app//org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3687)
	at app//org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1025)
	at app//org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1580)
	... 98 more
Caused by: java.lang.NumberFormatException: Character array is missing "e" notation exponential mark.
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:641)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:467)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:896)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgFromString(DefaultBinding.java:3857)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgSetValue(DefaultBinding.java:3984)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.lambda$pgNewRecord$13(DefaultBinding.java:3976)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgNewRecord(DefaultBinding.java:3972)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgFromString(DefaultBinding.java:3927)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.lambda$pgNewArray$14(DefaultBinding.java:4003)
	at org.jooq.impl.Tools.map(Tools.java:2226)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgNewArray(DefaultBinding.java:4001)
	... 107 more
```

**But** if I remove the first SELECT-query, then the second is completed successfully.

Some digging showed, that jOOQ caches the type for the internal `row` of two elements in `DefaultDataType.TYPES_BY_TYPE`. And the key in this cache is `class org.jooq.impl.RecordImpl2`. But in the second SELECT-query the elements of the `row` have other data types, so it's incorrect to use the cache for it.

### Steps to reproduce the problem

The table:
```sql
create table test_table
(
    id uuid primary key,
    decimal_value decimal not null
);
```

The code:
```kotlin
    val res1 = context.select(
        row(arrayAgg(field(row(TEST_TABLE.DECIMAL_VALUE, TEST_TABLE.DECIMAL_VALUE)))),
    )
        .from(TEST_TABLE)
        .groupBy(TEST_TABLE.ID)
        .fetch()

    println(res1.size)

    context.batchInsert(
        TestTableRecord(
            id = UUID.fromString("da5736fb-59eb-4b2a-a784-75fe13673177"),
            decimalValue = BigDecimal.ZERO,
        ),
    ).execute()

    // The following statement throws DataAccessException
    val res2 = context.select(
        row(arrayAgg(field(row(TEST_TABLE.ID, TEST_TABLE.ID)))),
    )
        .from(TEST_TABLE)
        .groupBy(TEST_TABLE.ID)
        .fetch()

    println(res2.size)
```

The same bug can also be reproduced if the first query uses `first_value(field(row(<2 elements>)))`.

### jOOQ Version

3.17.4

### Database product and version

PostgreSQL 13.8 (Debian 13.8-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Java Version

17.0.4.1

### OS Version

macOS Ventura 13.0 (22A380)

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.0

**Comment by lukaseder** [comment] 2022-11-02 10:37
Thanks for your report. Could that be a duplicate of https://github.com/jOOQ/jOOQ/issues/14105 ? It is fixed in jOOQ 3.18.0 and 3.17.5 (https://github.com/jOOQ/jOOQ/issues/14117), which haven't been released yet. Can you confirm your issue is fixed or persists on 3.17.5-SNAPSHOT?

If you're licensed, snapshot builds are available from here: 
https://www.jooq.org/download/versions

Otherwise, you can build directly from github.

**Comment by Tsar** [comment] 2022-11-02 11:30
Thank you for so fast response!
We checked with the latest `version-3.17.0-branch`. The issue is fixed, bug does not reproduce!

**Comment by lukaseder** [comment] 2022-11-02 11:36
Thanks for the feedback. That's great to hear. I'm hoping to release 3.17.5 this week.

**Closed by lukaseder** 2022-11-02 11:36 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Duplicate, E: All Editions

**Comment by Tsar** [comment] 2022-11-04 10:38
I created a temporary workaround for using until jOOQ 3.17.5 is released.
Sharing it here in case someone needs it.

```kotlin
import org.jooq.impl.DefaultDataType

// TODO: remove after updating jOOQ to 3.17.5+
// Information about the bug: https://github.com/jOOQ/jOOQ/issues/14165
fun <T> inJooqDefaultDataTypeBugWorkaround(action: () -> T): T {
    val typesCacheField = DefaultDataType::class.java.getDeclaredField("TYPES_BY_TYPE")
    typesCacheField.trySetAccessible()
    val typesCache = typesCacheField.get(null) as Array<MutableMap<Class<*>, DefaultDataType<*>>>
    val keysBefore = typesCache[0].keys.toSet()

    val result = action()

    val newKeys = typesCache[0].keys - keysBefore
    newKeys.forEach { typesCache[0].remove(it) }

    return result
}
```

Usage:

```kotlin
fun functionWithComplicatedSql() = inJooqDefaultDataTypeBugWorkaround {
    // complicated SQL here: context.select...
}
```
