### ISSUE TITLE
Regression when using expressions in ORDER BY clauses of MULTISET subqueries in PostgreSQL

### ISSUE THREAD

**Issue by jdussouillez** [jOOQ/jOOQ#17676] opened 2024-11-27 13:19 UTC
I'm upgrading from 3.19.10 to 3.19.15 and I face some issues with the use of `order by` inside multisets. The regression appeared in 3.19.11 and is still there in latest 3.19.15.

### Expected behavior

Order by working in multiset sub query.

Generated query in v3.19.10 (working):

```sql
SELECT
    "mcve"."products"."id",
    (
        SELECT coalesce(jsonb_agg(jsonb_build_array("v0", "v1", "v2")), jsonb_build_array())
        FROM (
            SELECT
                "mcve"."photos"."id" AS "v0",
                "mcve"."photos"."broadcast_type" AS "v1",
                "mcve"."photos"."broadcast_order" AS "v2"
            FROM "mcve"."photos"
            WHERE "mcve"."photos"."product_id" = "mcve"."products"."id"
            ORDER BY
                CASE
                    WHEN "mcve"."photos"."broadcast_type" = 'PUBLIC' THEN 0
                    WHEN "mcve"."photos"."broadcast_type" = 'INTERNAL' THEN 1
                    ELSE 2
                END ASC,
                "mcve"."photos"."broadcast_order" ASC
        ) AS t
    ) AS "photos"
FROM "mcve"."products"
WHERE "mcve"."products"."id" = 'P001'
```

### Actual behavior

The query fails

> ERROR: column "v1" does not exist

Generated query (failing):

```sql
SELECT
    "mcve"."products"."id",
    (
        SELECT coalesce(jsonb_agg(jsonb_build_array("v0", "v1", "v2")), jsonb_build_array())
        FROM (
            SELECT
                "mcve"."photos"."id" AS "v0",
                "mcve"."photos"."broadcast_type" AS "v1",
                "mcve"."photos"."broadcast_order" AS "v2"
            FROM "mcve"."photos"
            WHERE "mcve"."photos"."product_id" = "mcve"."products"."id"
            ORDER BY
                CASE
                    WHEN "v1" = 'PUBLIC' THEN 0
                    WHEN "v1" = 'INTERNAL' THEN 1
                    ELSE 2
                END ASC,
                "v2" ASC
        ) AS t
    ) AS "photos"
FROM "mcve"."products"
WHERE "mcve"."products"."id" = 'P001'
```

Diff from working version:

```diff
14,15c14,15
<                     WHEN "mcve"."photos"."broadcast_type" = 'PUBLIC' THEN 0
<                     WHEN "mcve"."photos"."broadcast_type" = 'INTERNAL' THEN 1
---
>                     WHEN "v1" = 'PUBLIC' THEN 0
>                     WHEN "v1" = 'INTERNAL' THEN 1
18c18
<                 "mcve"."photos"."broadcast_order" ASC
---
>                 "v2" ASC
```

### Steps to reproduce the problem

I created a reproducer based on jOOQ-mcve here: https://github.com/jdussouillez/jOOQ-mcve/tree/multiset-order-by/jOOQ-mcve-java-postgres (:warning:  use branch `multiset-order-by`).

- `mvn verify` -> error :red_circle: 
- Change the version of jOOQ to `3.19.10` and run `mvn verify` again -> OK :heavy_check_mark: 

[See the test](https://github.com/jdussouillez/jOOQ-mcve/blob/multiset-order-by/jOOQ-mcve-java-postgres/src/test/java/org/jooq/mcve/test/java/postgres/JavaTest.java#L111)

### jOOQ Version

3.19.11..3.19.15

### Database product and version

PostgreSQL 16

### Java Version

openjdk version "21.0.4" 2024-07-16 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.2

**Comment by lukaseder** [comment] 2024-11-28 16:32
Thanks for your report and detailed reproducer. I'll have a look at this, soon.

**Comment by lukaseder** [comment] 2024-12-04 08:08
Looking into this now. jOOQ 3.19.11 indeed had multiple fixes in the area of getting `UNION`, `ORDER BY`, and `MULTISET` to behave:
https://www.jooq.org/notes/#3.19.11

**Comment by lukaseder** [comment] 2024-12-04 08:20
I see, there's a wrong assumption about the fact that if `ORDER BY <select-alias>` is possible in an RDBMS, then logically, `ORDER BY expr(<select-alias>)` is also possible. You didn't specify any such alias in your user query, jOOQ did that internally, so this is different from an existing issue that attempts to emulate this for all dialects:

- https://github.com/jOOQ/jOOQ/issues/3695

The aliasing is necessary outside of the auxiliary derived table `t` when building the JSON data structure, but not necessarily within the derived table:

```sql
select
  "mcve"."products"."id",
  (
    select coalesce(
      jsonb_agg(jsonb_build_array("v0", "v1", "v2")), -- Aliasing necessary here
      jsonb_build_array()
    )
    from (
      select
        "mcve"."photos"."id" as "v0",
        "mcve"."photos"."broadcast_type" as "v1",
        "mcve"."photos"."broadcast_order" as "v2"
      from "mcve"."photos"
      where "mcve"."photos"."product_id" = "mcve"."products"."id"
      order by
        case
          when "v1" = 'PUBLIC' then 0
          when "v1" = 'INTERNAL' then 1
          else 2
        end asc,
        "v2" asc -- But not here
    ) as t
  ) as "photos"
from "mcve"."products"
where "mcve"."products"."id" = 'P001';
```

For the record, the reason why we alias at all is because in most RDBMS, derived tables aren't allowed to project duplicate column names (e.g. `photos.id` and `products.id` or similar), so we have to enumerate all column names.

**Comment by lukaseder** [comment] 2024-12-04 10:44
A workaround is to replace teh `PHOTOS.BROADCAST_TYPE` field from the `CASE` expression by the following plain SQL template: `DSL.field("broadcast_type ")`. The whitespace ensures that `Field::equals` won't be true when comparing the `Field` with the aliased column. Another is to avoid re-using the same column between `select()` and `orderBy()`, e.g. by adding a dummy expression to the `select()` clause like this:

```java
coalesce(PHOTOS.BROADCAST_TYPE, PHOTOS.BROADCAST_TYPE)
```

**Comment by lukaseder** [comment] 2024-12-04 10:49
The original issue that produced these substitutions was:

- https://github.com/jOOQ/jOOQ/issues/2080

It was specific to only a few RDBMS, and to `OFFSET .. FETCH` emulation. Most of these dialects (E.g. Oracle, SQL Server, Db2) now support standard SQL `OFFSET .. FETCH`, so the original problem seems to have disappeared.

**Comment by lukaseder** [comment] 2024-12-04 11:45
Fixed in versions:

- 3.20.0
- 3.19.16 (https://github.com/jOOQ/jOOQ/issues/17728)
- 3.18.23 (https://github.com/jOOQ/jOOQ/issues/17729)
- 3.17.32 (https://github.com/jOOQ/jOOQ/issues/17730)

**Closed as completed by lukaseder** 2024-12-04 11:45 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Fixed, E: All Editions

**Comment by jdussouillez** [comment] 2024-12-04 16:02
Thanks for the quick fix and the information about the workaround and the cause!

**Comment by jdussouillez** [comment] 2024-12-12 10:51
FYI: Fix is working great on the reproducer when using v3.19.16.

Thanks again!
