### ISSUE TITLE
Feedback about jOOQ-codegen-gradle

### ISSUE THREAD

**Issue by lfgcampos** [jOOQ/jOOQ#16749] opened 2024-05-31 19:26 UTC
### The documentation URL

https://www.jooq.org/doc/latest/manual/code-generation/codegen-gradle/

### Feedback

Hi @lukaseder, first of all, thank you very much for your effort and project!

I've been working at replacing `nu.studer.jooq` by `org.jooq.jooq-codegen-gradle` and took some notes of the process and struggles.
Some of those, mind you, might be me failing to understand something or not knowing enough - but nevertheless, took notes and decided to share anyway.

- `.apply` is not possible anymore
	- maybe just a sugar syntax but it looked "nicer" in my opinion before
- missing logs info
	- compared to the `nu.studer.jooq`, the current plugin offers a lot less logs and info
	- all the `Database parameters`, `JavaGenerator parameters`, `JavaGenerator parameters`, etc are missing
- log level not properly used
	- making it `logging = Logging.TRACE` doesn't add any log to help debugging problems
- after changing it, I started to get a `java.lang.OutOfMemoryError: Metaspace`
	- first time seeing it, really a shot in the dark
	- I managed to kinda track down it to [this](https://youtrack.jetbrains.com/issue/KT-56093)
	- it is seen on Kotlin `1.8.0` and fixed on `1.8.10`
	- coincidence or not, jooq is on `1.8.0`
- I've started getting some `Ambiguous key name` errors, which were not present before
	- probably something on my side to investigate, but pointing out anyway
- I am missing a clean task
	- similar to [this](https://github.com/etiennestuder/gradle-jooq-plugin?tab=readme-ov-file#deleting-the-generated-jooq-sources)
	- as you can see, I've created an [issue](https://github.com/etiennestuder/gradle-jooq-plugin/issues/695) to understand how that is created as I can't tell myself
- incremental building and building caches are missing
	- in the other plugin, it was achieved by [allInputsDeclared](https://github.com/etiennestuder/gradle-jooq-plugin?tab=readme-ov-file#configuring-the-jooq-generation-task-to-participate-in-incremental-builds-and-build-caching) flag
	- probably related to https://github.com/jOOQ/jOOQ/issues/16275
	- possibly tracked by https://github.com/jOOQ/jOOQ/issues/16318
- source sets are not being set properly
        - it used to work before and the code can be found [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/main/src/main/groovy/nu/studer/gradle/jooq/JooqPlugin.java#L51-L60)
        - you have a similar approach but that isn't working. Again, code can be found [here](https://github.com/jOOQ/jOOQ/blob/main/jOOQ-codegen-gradle/src/main/java/org/jooq/codegen/gradle/CodegenPlugin.java#L116-L120)
        - to fix it, I've added this to my config
        ```
        sourceSets.getByName("main").java.srcDirs(
            "build/generated-sources" // this is the jooq output dir
        )
        ```

I've also failed to find some good examples of how to do it, even a simple `build.gradle.kts` with "complete" examples.

To make it complete, here are the versions I am using:
- JDK17
- jooq 3.19.9
- liquibase 
- postgres

If you need any additional info or help, I am happy to help.

**Comment by lukaseder** [comment] 2024-06-04 07:16
Thanks a lot for your collected feedback.

> `.apply` is not possible anymore
> * maybe just a sugar syntax but it looked "nicer" in my opinion before

That `.apply` usage is just a kotlin-specific, opinionated hack to make things DSL-ish. It isn't the most idiomatic way to do things in gradle. It is much better for a gradle DSL to look (almost) exactly the same in groovy/kotlin. In fact, jOOQ 3.19 published a new `jOOQ-meta-kotlin`  extensions module, which helps third parties like Etienne Studer's plugin to get the 2 DSLs to align, and Etienne liked it:

- https://github.com/etiennestuder/gradle-jooq-plugin/issues/62#issuecomment-1840475801

Gradle being gradle, you can obviously do anything you want, including using the underlying programmatic code generation API and then do whatever you want with it. `apply()` is just a function from the stdlib: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/apply.html. You can also use `let()`, etc. I suspect that should still be possible?

So, we're definitely not going to focus on documenting (let alone endorsing) such kotlin specifics, or we'll never stop arguing bikesheds. We should document the default, and the current default is better than any previous hack using `apply()`

> missing logs info
> * compared to the `nu.studer.jooq`, the current plugin offers a lot less logs and info
> * all the `Database parameters`, `JavaGenerator parameters`, `JavaGenerator parameters`, etc are missing

That's interesting, can you show some console output? I get this (note the gradle `-i` flag, which is unrelated to jOOQ):

```
lukas@DESKTOP-F2SE3C1 MINGW64 ~/jOOQ/3.20/workspace/jOOQ-pro/jOOQ-test-codegen/jOOQ-test-codegen-gradle/jOOQ-test-codegen-gradle-kotlin-only-configuration
$ ./gradlew jooqCodegen -i
[...]
> Task :jOOQ-test-codegen-gradle-kotlin-only-configuration:jooqCodegen
Caching disabled for task ':jOOQ-test-codegen-gradle-kotlin-only-configuration:jooqCodegen' because:
  Build cache is disabled
Task ':jOOQ-test-codegen-gradle-kotlin-only-configuration:jooqCodegen' is not up-to-date because:
  Task.upToDateWhen is false.
The input changes require a full rebuild for incremental task ':jOOQ-test-codegen-gradle-kotlin-only-configuration:jooqCodegen'.
No <inputCatalog/> was provided. Generating ALL available catalogs instead.
create schema S
Update count: 0
create table S.T (
  I int,
  J int,
  K int,
  primary key (I)
)
Update count: 0
License parameters
----------------------------------------------------------
  Thank you for using jOOQ and jOOQ's code generator

Database parameters
----------------------------------------------------------
  dialect                : H2_2_2_220
  URL                    :
  target dir             : C:\Users\lukas\jOOQ\3.20\workspace\jOOQ-pro\jOOQ-test-codegen\jOOQ-test-codegen-gradle\jOOQ-test-codegen-gradle-kotlin-only-configuration\build\generated-sources\jooq
  target package         : org.jooq.codegen.gradle.test.only.configuration.db
  includes               : []
  excludes               : []
  includeExcludeColumns  : false
----------------------------------------------------------

JavaGenerator parameters
----------------------------------------------------------
annotations
  generated              : false
  JPA                    : false
  JPA version            :
  validation             : false
  spring                 : false
comments
  comments               : true
  on attributes          : true
  on catalogs            : true
  on columns             : true
  on embeddables         : true
  on keys                : true
  on links               : true
  on packages            : true
  on parameters          : true
  on queues              : true
  on routines            : true
  on schemas             : true
  on sequences           : true
  on tables              : true
  on udts                : true
sources
  sources                : true
  sources on views       : true
global references
  global references      : true
  catalogs               : true
  domains                : true
  indexes                : true
  keys                   : true
  links                  : true
  queues                 : true
  routines               : true
  schemas                : true
  sequences              : true
  tables                 : true
  udts                   : true
object types
  daos                   : false
  indexes                : true
  instance fields        : true
  interfaces             : false
  interfaces (immutable) : false
  javadoc                : true
  keys                   : true
  links                  : true
  pojos                  : false
  pojos (immutable)      : false
  queues                 : true
  records                : true
  routines               : true
  sequences              : true
  sequenceFlags          : true
  table-valued functions : true
  tables                 : true
  triggers               : true
  udts                   : true
  relations              : true
other
  deprecated code        : true
----------------------------------------------------------

Generation remarks
----------------------------------------------------------

----------------------------------------------------------
Generating catalogs      : Total: 1
ARRAYs fetched           : 0 (0 included, 0 excluded)
Domains fetched          : 0 (0 included, 0 excluded)
Triggers fetched         : 0 (0 included, 0 excluded)
Tables fetched           : 1 (1 included, 0 excluded)
Embeddables fetched      : 0 (0 included, 0 excluded)
Enums fetched            : 0 (0 included, 0 excluded)
Packages fetched         : 0 (0 included, 0 excluded)
Routines fetched         : 0 (0 included, 0 excluded)
Sequences fetched        : 0 (0 included, 0 excluded)
No schema version is applied for catalog . Regenerating.

Generating catalog       : DefaultCatalog.java
==========================================================
Comments fetched         : 0 (0 included, 0 excluded)
Generating schemata      : Total: 1
No schema version is applied for schema S. Regenerating.
Generating schema        : S.java
----------------------------------------------------------
UDTs fetched             : 0 (0 included, 0 excluded)
Generating tables
Generating table         : T.java [input=T, pk=CONSTRAINT_5]
Indexes fetched          : 0 (0 included, 0 excluded)
Tables generated         : Total: 209.973ms
Generating table records
Generating record        : TRecord.java
Table records generated  : Total: 212.269ms, +2.295ms
Generating table references
Table refs generated     : Total: 217.76ms, +5.491ms
Generating Keys
Keys generated           : Total: 218.782ms, +1.021ms
Generating Indexes
Skipping empty indexes
Generation finished: S   : Total: 218.9ms, +0.118ms

Affected files: 6
Modified files: 6
Removing excess files

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
Watched directory hierarchies: [C:\Users\lukas\jOOQ\3.20\workspace\jOOQ-pro\jOOQ-test-codegen\jOOQ-test-codegen-gradle]
```

Seems to work alright?

> log level not properly used
> * making it `logging = Logging.TRACE` doesn't add any log to help debugging problems

I don't recall logging much below the debug level in the `GenerationTool`. What additional trace logs are you expecting here?

> after changing it, I started to get a `java.lang.OutOfMemoryError: Metaspace`
> * first time seeing it, really a shot in the dark
> * I managed to kinda track down it to [this](https://youtrack.jetbrains.com/issue/KT-56093)
> * it is seen on Kotlin `1.8.0` and fixed on `1.8.10`
> * coincidence or not, jooq is on `1.8.0`

Interesting, I'll look into this. We can probably upgrade to 1.8.10 (though I'd rather jump to 2.0 directly). But I don't have any confidence that this is really the cause of the problem.

From what I understand, Gradle doesn't work with classloaders (!), which means that any static cache, etc. will live forever, and "memory leaks" in the code generator, which usually don't appear (because there's no eternally living classloader in standalone execution or in maven), have now manifested with gradle.

I'm still planning on looking at those things, trying to make sure all jOOQ caches are cleaned once the `GenerationTool` completes... But to be honest, without usage of classloaders in the build tool, I don't have a lot of confidence to ever 100% address all of these OOM problems.

> I've started getting some `Ambiguous key name` errors, which were not present before
> * probably something on my side to investigate, but pointing out anyway

I'll be happy to look at a specific bug report.

> I am missing a clean task
> * similar to [this](https://github.com/etiennestuder/gradle-jooq-plugin?tab=readme-ov-file#deleting-the-generated-jooq-sources)
> * as you can see, I've created an [issue](https://github.com/etiennestuder/gradle-jooq-plugin/issues/695) to understand how that is created as I can't tell myself

I don't fully understand why this is needed, coming from maven. It should be the build system's responsibility to clean derived output like generated code, in my opinion. Why would a gradle plugin have to worry about this?

Can you point to other code generating plugins (e.g. XJC, etc.) which do this? If you think this should be a thing in jOOQ, you can try creating a feature request with detailed requirements explaining why this is needed.

> incremental building and building caches are missing
> * in the other plugin, it was achieved by [allInputsDeclared](https://github.com/etiennestuder/gradle-jooq-plugin?tab=readme-ov-file#configuring-the-jooq-generation-task-to-participate-in-incremental-builds-and-build-caching) flag
> * probably related to [Remove unnecessary up-to-date prevention in jOOQ-codegen-gradle plugin #16275](https://github.com/jOOQ/jOOQ/issues/16275)
> * possibly tracked by [Implement correct up-to-date output logic in jOOQ-codegen-gradle #16318](https://github.com/jOOQ/jOOQ/issues/16318)

Yes, that's already covered there

> * source sets are not being set properly
>   - it used to work before and the code can be found [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/main/src/main/groovy/nu/studer/gradle/jooq/JooqPlugin.java#L51-L60)
>   - you have a similar approach but that isn't working. Again, code can be found [here](https://github.com/jOOQ/jOOQ/blob/main/jOOQ-codegen-gradle/src/main/java/org/jooq/codegen/gradle/CodegenPlugin.java#L116-L120)
>   - to fix it, I've added this to my config
>   `sourceSets.getByName("main").java.srcDirs( "build/generated-sources" // this is the jooq output dir )`

Are you sure? Our integration tests indicate that things work correctly. You'll have to connect the tasks, of course. "It doesn't work" isn't enough for me to take action. I don't know "what" doesn't work in your case. Our issue templates request an MCVE (Minimal, Complete, Verifiable Example) for bug reports. We'll soon have gradle templates as well:

- https://github.com/jOOQ/jOOQ-mcve/issues/41

I'll be happy to look at complete bug reports with reproducers. It's much easier to say whether there's a usage error, a UX problem, or an actual bug.

Now, there's these issues:

- https://github.com/jOOQ/jOOQ/issues/16088
- https://github.com/jOOQ/jOOQ/issues/16087

I'm reluctant of spending too much time documenting a volatile status quo when there are so many different opinions on how to "best" do things in gradle. Things will change (drastically, I suspect) again when "declarative gradle" will be a thing, finally (coming from maven again, I truly hope that will fix all of this everyone-their-own-gradle mess).

Things will also change, once some of the above issues are addressed, because the status quo is based on many wrong assumptions that have to be fixed first, before being able to e.g. support incremental building.

This is why I've marked the plugin as experimental in the manual. Expect more significant (breaking) changes in the near future.

Now, as there's nothing actionable left in this issue, I'm closing it. Looking forward to more specific issues on a per-problem basis (which can be tracked properly), if you have time and are interested to follow up on individual topcis.

**Closed by lukaseder** 2024-06-04 07:16 UTC
Labels: C: Code Generation, C: Documentation, P: Medium, T: Support request, E: All Editions

**Comment by lfgcampos** [comment] 2024-06-04 08:53
hi @lukaseder, thanks for the response!
And I hope you don't mind the reply here as well, even though it is closed =)
(in retrospect, I should have numbered the feedback to make it easier to track - I am gonna edit my initial post to make it easier for us haha)

---

1. Thanks for pointing that out! I've now migrated to the DSL way, as you suggested and because I couldn't make the `.apply` work. Nevertheless, since it was a "difference", I decided to list it. I am happy for your choice of not documenting/endorsing it.

2. `-i` definitely give me a lot more! It is just looking at the logs before and after, the difference is huge! Not even the `jooq` banner is displayed which was always there before 😅 
Again, this doesn't make a big difference for my use case, but pointing out as it was one of the differences I could perceive.

3. Well, there is a reason one can supply a `logging` parameter in the jooq Configuration class. I'd expect to see more than the normal output when changing/playing with it. In the plugin code, I see no usage of logging at all which can probably be improved.

4. As I said before on this one, this is a shot in the dark. I took notes of all I could find and maybe bumping Kotlin minor will fix it (maybe not 🤷). As always, up to you. Also, jumping to 2.0 is nice but it will take some time for projects to catch up and bump to 2.0 as well. I'd rather have a version on latest Kotlin 1.x and another one on 2.x =)

5. I don't think this is a bug but probably something on my side. Generation is working, even though I have all those messages. It is on my list to investigate - if it turns out to be something wrong with the plugin, you can expect a bug in the future.

6. Again, it is not needed but I took notes as a "difference". And sorry to compare with the third party plugin but that is inevitable at this point. Etienne answered on my linked issue how/why that exists. Maybe that indicates you are missing an `@OutputDirectories`?

7. Yes, nothing to add here.

8. There are no tests in the plugin itself where I could look at. It could be just IntelliJ not liking it but without the piece I've added - `"build/generated-sources"` - it is not a source set and all my classes goes red on any generated jOOQ import.

---

Again, thanks for your answers and for spending time on it.  I can try to create some small reproducibles for some of the reported issues and get back to you at some point in the future but hopefully this issue at least help you, the project and others somehow. <3

**Comment by lukaseder** [comment] 2024-06-04 09:14
> (in retrospect, I should have numbered the feedback to make it easier to track - I am gonna edit my initial post to make it easier for us haha)

Well, one topic one issue is really the best approach.

> 3\. Well, there is a reason one can supply a `logging` parameter in the jooq Configuration class. I'd expect to see more than the normal output when changing/playing with it.

jOOQ's `GenerationTool` exists outside of the world of build systems. It will try to use a logger which it finds on the classpath. Logger configurations can still override whatever the jOOQ `GenerationTool` does, and mute its output. People will want to use `-i` but mute jOOQ's output separately, for example.

> Maybe that indicates you are missing an `@OutputDirectories`?

It's right there:
https://github.com/jOOQ/jOOQ/blob/b55b0bcc40837eb1f53228c263b68c8a802e438d/jOOQ-codegen-gradle/src/main/java/org/jooq/codegen/gradle/CodegenTask.java#L123

> There are no tests in the plugin itself where I could look at.

Indeed, our tests aren't open source. An example test will be in the MCVE template soon, but it won't cover all possible cases.

> It could be just IntelliJ not liking it but without the piece I've added - `"build/generated-sources"` - it is not a source set and all my classes goes red on any generated jOOQ import.

Yes, it's an IntelliJ problem in my opinion. If the build works but the IDE shows errors, then the IDE is not up to date with the build logic (I don't envy them for this work, though!)
