### ISSUE TITLE
Support postgres ALTER statements

### ISSUE THREAD

**Issue by codemonstur** [jOOQ/jOOQ#12006] opened 2021-06-14 10:31 UTC
I generated some migration scripts for postgres using the [apgdiff ](https://www.apgdiff.com/)tool. The output looks like this:

    ALTER TABLE table
	      ALTER COLUMN created_date TYPE bigint USING created_date::bigint /* TYPE change - table: table original: integer new: bigint */,
	      ALTER COLUMN last_updated TYPE bigint USING last_updated::bigint /* TYPE change - table: table original: integer new: bigint */,
	      ALTER COLUMN deleted_date TYPE bigint USING deleted_date::bigint /* TYPE change - table: table original: integer new: bigint */,
	      ALTER COLUMN name TYPE character varying(64) USING name::character varying(64) /* TYPE change - table: table original: character varying(64)[] new: character varying(64) */;

These statements work without error if you execute them on the DB using psql. But JOOQ doesn't parse them.
First error I got was about the USING clause, and the second error was about having multiple ALTERs separated by comma's:

```
[ERROR] An exception occurred while parsing script source : src/main/resources/db/generation/*.sql. Please report this error to https://github.com/jOOQ/jOOQ/issues/new
org.jooq.impl.ParserException: Unsupported query type: [5:40] ...ABLE table
        ALTER COLUMN created_date TYPE bigint [*]USING created_date::bigint /* TYPE change - table: table original: integer new: ...

[ERROR] An exception occurred while parsing script source : src/main/resources/db/generation/*.sql. Please report this error to https://github.com/jOOQ/jOOQ/issues/new
org.jooq.impl.ParserException: Unsupported query type: [5:102] ...ge - table: table original: integer new: bigint */[*],
        ALTER COLUMN last_updated TYPE bigint USING last_updated::bigint /* TYPE chan...
```
### Possible solution you'd like to see:

I'd like the original format to be supported.

### Possible workarounds:

I rewrote the statement manually to

    ALTER TABLE table ALTER COLUMN created_date TYPE bigint;
    ALTER TABLE table ALTER COLUMN last_updated TYPE bigint;
    ALTER TABLE table ALTER COLUMN deleted_date TYPE bigint;
    ALTER TABLE table ALTER COLUMN name TYPE character varying(64);

### Versions:

- jOOQ: 3.14.11
- Java: 16 targeting 11
- Database (include vendor): postgres 13
- OS: windows

PS. Sorry for the rather generic title, I know ALTER statements have a lot of support already. Just didn't really know what to name the issue.

**Comment by lukaseder** [comment] 2021-06-14 10:48
Thanks a lot for your feature request. Duplicate of https://github.com/jOOQ/jOOQ/issues/8834 (API support) and https://github.com/jOOQ/jOOQ/issues/8846 (parser support)

**Closed by lukaseder** 2021-06-14 10:48 UTC
Labels: C: Functionality, C: Parser, E: All Editions, P: Medium, T: Enhancement

**Comment by codemonstur** [comment] 2021-06-14 11:13
Hey lukas! When I read the two issues you referenced I only see mention of the multiple alter statements error, but nothing about the USING clause. Are you sure this issue is fully covered by the two linked issues?

**Comment by lukaseder** [comment] 2021-06-14 11:34
OK, so another duplicate :) https://github.com/jOOQ/jOOQ/issues/9264.

What's the value of that `using` clause in this case?

**Comment by codemonstur** [comment] 2021-06-14 19:26
Wow I realy suck at searching :(. I don't think there is a value to it. The tool I use adds it but the migration script will work if its not there as well. So no need to prioritise this one. Right now I'm using a workaround of managing two sets of migration scripts; one for jooq, one for flyway. A bit more work but mostly fine.

**Comment by lukaseder** [comment] 2021-06-15 09:29
Hey, no worries. Always good to get a bunch of additional hints at what features people need!

Notice that if you're using testcontainers for jOOQ's code generation (see some examples in this thread: https://github.com/jOOQ/jOOQ/issues/6551), then you might not have to work around this problem...
