### ISSUE TITLE
Add missing tabs to the "Run jOOQ code generation" heading in the manual section "codegen-configuration"

### ISSUE THREAD

**Issue by RadixSeven** [jOOQ/jOOQ#13455] opened 2022-04-15 20:28 UTC
I can switch to the "Programmatic" tab for the [example configuration](http://www.jooq.org/doc/3.17/manual/code-generation/codegen-configuration/#configure-jooq-s-code-generator), but there is no similar switch for the [Run jOOQ code generation](http://www.jooq.org/doc/3.17/manual/code-generation/codegen-configuration/#run-jooq-code-generation) section. The code in that section assumes you're using an XML file. I'm sure people using the Gradle would also appreciate a version for their application.

----
See: https://www.jooq.org/doc/3.17/manual/code-generation/codegen-configuration/

**Comment by lukaseder** [comment] 2022-04-18 15:20
Thanks for your suggestion. I can see your point, although rather than just tweaking the example, I think this whole section could be re-written to make different use-cases more clear.

**Comment by RadixSeven** [comment] 2022-04-18 15:58
I agree, a rewrite would work too.

**Comment by lukaseder** [comment] 2024-09-25 08:46
Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/11090

**Closed by lukaseder** 2024-09-25 08:46 UTC
Labels: T: Enhancement, C: Documentation, P: Low, R: Duplicate, E: All Editions
