### ISSUE TITLE
Null left joined record selected into reference has placeholder/empty row

### ISSUE THREAD

**Issue by reubenfirmin** [jOOQ/jOOQ#16052] opened 2024-01-10 11:34 UTC
### Expected behavior

Please see screenshot:

![2024-01-10_05-28](https://github.com/jOOQ/jOOQ/assets/14217993/e4b4813e-d6ad-443b-bce0-75219cc829e9)

I left joined a child table, for which there are no values, and then fetched the records into the reference object (see #16035  for why I'm doing this.)

Expectation: this should be an empty ResultImpl, with no records.

### Actual behavior

Instead, as you can see in the screenshot, it creates an empty Record object with no values. This means that I can't detect no results with `isEmpty()`; instead I have to look for: `isEmpty() || size() == 1 && first.values().all { it == null }}` (or similar), which is obviously ugly.

### Steps to reproduce the problem

Left join a child table with no records, set up code as in screenshot.

### jOOQ Version

3.18.6

### Database product and version

Postgres 15

### Java Version

OpenJDK version 17

### OS Version

Ubuntu 23.10

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.1

**Comment by lukaseder** [comment] 2024-01-10 11:40
Duplicate of:

- https://github.com/jOOQ/jOOQ/issues/11888
- https://github.com/jOOQ/jOOQ/issues/13776
- https://github.com/jOOQ/jOOQ/issues/15086

With an in-depth explanation of why this isn't a good idea (though it does appear to be one, at first), here:

- https://github.com/jOOQ/jOOQ/issues/13776#issuecomment-1176380681

**Closed by lukaseder** 2024-01-10 11:40 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, E: All Editions
