### ISSUE TITLE
Exception while executing meta query: ERROR: column c.consrc does not exist

### ISSUE THREAD

**Issue by Akshaymisal5** [jOOQ/jOOQ#9829] opened 2020-02-12 13:42 UTC
Postgres: 12
jooq-codegen-maven: 3.10.3
jooq-meta:  3.10.3
postgresql: 42.1.4

[ERROR] **Error while fetching domains**
org.jooq.exception.DataAccessException: SQL [with recursive "domains"("domain_id", "base_id", "typbasetype", "src") as ((select "d".oid, "d".oid, "d"."typbasetype", array["c"."consrc"] from "pg_catalog"."pg_type" as "d" join "pg_catalog"."pg_namespace" as "n" on "n".oid = "d"."typnamespace" left outer join "pg_catalog"."pg_constraint" as "c" on "d".oid = "c"."contypid" where ("d"."typtype" = ? and "n"."nspname" in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?))) union all (select "domains"."domain_id", "d".oid, "d"."typbasetype", case when "c"."consrc" is null then "domains"."src" else array_append("domains"."src", "c"."consrc") end from "domains" join "pg_catalog"."pg_type" as "d" on "domains"."typbasetype" = "d".oid left outer join "pg_catalog"."pg_constraint" as "c" on "d".oid = "c"."contypid")) select "n"."nspname", "d"."typname", "d"."typnotnull", "d"."typdefault", "b"."typname", "b"."typlen", "domains"."src" from "pg_catalog"."pg_type" as "d" join "domains" on ("domains"."typbasetype" = ? and "domains"."domain_id" = "d".oid) join "pg_catalog"."pg_type" as "b" on "domains"."base_id" = "b".oid join "pg_catalog"."pg_namespace" as "n" on "n".oid = "d"."typnamespace" where ("d"."typtype" = ? and "n"."nspname" in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?))]; ERROR: column c.consrc does not exist
  **Hint: Perhaps you meant to reference the column "c.conkey" or the column "c.conbin".**
  Position: 127
	at org.jooq_3.10.3.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2197)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:704)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:317)
	at org.jooq.impl.AbstractResultQuery.iterator(AbstractResultQuery.java:328)
	at org.jooq.impl.SelectImpl.iterator(SelectImpl.java:2607)
	at org.jooq.util.postgres.PostgresDatabase.getDomains0(PostgresDatabase.java:614)
	at org.jooq.util.AbstractDatabase.getDomains(AbstractDatabase.java:1563)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:514)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:405)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:327)
	at org.jooq.util.GenerationTool.run(GenerationTool.java:642)
	at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)
	at org.jooq.util.maven.Plugin.execute(Plugin.java:192)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.postgresql.util.PSQLException: ERROR: column c.consrc does not exist
  Hint: Perhaps you meant to reference the column "c.conkey" or the column "c.conbin".
  Position: 127
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:158)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3209)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:262)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
	... 33 more

**Comment by lukaseder** [comment] 2020-02-12 14:31
Duplicate of https://github.com/jOOQ/jOOQ/issues/9331

**Closed by lukaseder** 2020-02-12 14:31 UTC
Labels: C: Code Generation, E: All Editions, P: Medium, R: Duplicate, T: Defect
