### ISSUE TITLE
how to generate database as only has jpa entities?

### ISSUE THREAD

**Issue by zzsoszz** [jOOQ/jOOQ#6134] opened 2017-04-23 15:12 UTC
how to generate database as only has jpa entities?

**Comment by lukaseder** [comment] 2017-04-24 09:24
I'm sorry, I'm not quite sure what you mean by this. Am I right that this question is a duplicate of your other question? https://github.com/jOOQ/jOOQ/issues/6135

Thanks,
Lukas

**Closed by lukaseder** 2017-04-24 09:24 UTC
Labels: C: Code Generation, P: Medium, T: Support request
