### ISSUE TITLE
Smaller units in DatePart

### ISSUE THREAD

**Issue by coudy** [jOOQ/jOOQ#6017] opened 2017-03-25 01:48 UTC
I'm sure there's some horrible reason this hasn't been implemented yet but it'd be good to have milliseconds in `DatePart` to support date arithmetic, extraction and truncation.

**Comment by lukaseder** [comment] 2017-03-25 19:01
Thank you for your suggestion. Indeed that would be useful - especially in some databases that have native support for non SQL standard date parts. In fact, this is already on the roadmap: https://github.com/jOOQ/jOOQ/issues/2132 (so I'll close this as a duplicate of the latter).

The "horrible reason" is that in order to support additional date parts on 21 RDBMS with all the "horrible" date time arithmetic emulation that goes with it, we simply preferred to do other more pressing (and less time consuming) issues, first :)

**Closed by lukaseder** 2017-03-25 19:01 UTC
Labels: C: Functionality, P: Medium, T: Enhancement
