### ISSUE TITLE
Code Generation  jooq-codegen version:3.8.0

### ISSUE THREAD

**Issue by lucky8987** [jOOQ/jOOQ#6288] opened 2017-05-27 09:14 UTC
With two tables in the mysql database, they are not a foreign key relationship, why in the generated table classes exist in the fields outside the keys?The code is as follows:
```java
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobPosition extends TableImpl<JobPositionRecord> {
    // the city column type is int, why become the reference record type here
    public static final TableField<JobPositionRecord, JobPositionCityRecord> CITY = createField("city", com.xxxx.xx.db.jobdb.tables.JobPositionCity.JOB_POSITION_CITY.getDataType(), JOB_POSITION, "");
}
```
What reason is this excuse me?What is the configuration parameters can get rid of this operation, because it caused a bitter pill for me

**Comment by lukaseder** [comment] 2017-05-27 09:43
That looks like https://github.com/jOOQ/jOOQ/issues/5334, which was backported to version 3.8.3. Could you please try upgrading to the latest version, either 3.9.3 or 3.8.7.

I'm closing this as a duplicate of #5334. Please reopen, if upgrading didn't help

**Closed by lukaseder** 2017-05-27 09:43 UTC
Labels: C: Code Generation, P: Medium, T: Defect
