### ISSUE TITLE
Issues with Postgres RETURNING with field expressions

### ISSUE THREAD

**Issue by mjustin** [jOOQ/jOOQ#6690] opened 2017-10-12 04:21 UTC
In the RETURNING clause, Postgres supports "any expression using the table's columns is allowed".  jOOQ appears to partially support this, but the behavior varies in surprising ways based on how the library is used.  I'd expect this to either be supported and always work or be unsupported and never work, rather than the current behavior where it sometimes works.

I've noticed two issues related to this, so I'm documenting them both here — one involving the generated SQL, and one involving the fields on the resulting Records.

#### Generated SQL Issue
Given the following code:

```java
DSLContext dsl = DSL.using(getConnection(), SQLDialect.POSTGRES);

Table<Record> table = new TableImpl<>(DSL.name("test"));
Field<String> field = DSL.field("field", String.class);
Field<Integer> aliasedFieldAsInt = field.cast(Integer.class).as("int_field");

System.out.println(dsl.insertInto(table).columns(field).values("1").returning(aliasedFieldAsInt).getSQL());
```

I would expect the output to be:
```sql
insert into "test" (field) values (?) returning cast(field as int) as "int_field"
```

However, it is instead:
```sql
insert into "test" (field) values (?) returning "int_field"
```

Note that if I declare the field without an alias, it works as expected:
```java
Field<Integer> fieldAsInt = field.cast(Integer.class);
System.out.println(dsl.insertInto(table).columns(field).values("1").returning(fieldAsInt).getSQL());
```

The above returns the expected value:
```sql
insert into "public"."test" (field) values (?) returning id, cast(field as int)
```

#### asMap() Issue
A second issue I discovered with RETURNING is that calling `fields()` and `intoMap()` on the result works as expected when the table is manually created as above.  However, if the table is generated using the schema generation (or the table is manually generated in a manner consistent with the schema generation, namely using the static `createField` method on `AbstractTable`), the `fields()` method returns the list of fields on that table, not the list of fields that were declared in the `returning` method.

For example, given a table named "test" in schema "public" with columns "id" and "field" and a generated `Test` table class, and the following code:

```java
Table<Record> table = Test.TEST;
Field<String> field = DSL.field("field", String.class);

InsertResultStep<Record> returningAsInt = dsl.insertInto(table).columns(field).values("1").returning(field, fieldAsInt);

System.out.println(Arrays.toString(returningAsInt.fetchOne().fields()));
System.out.println(returningAsInt.fetchOne().intoMap());
```

I would expect the output to be analogous to the that of an equivalent select statement:
```
[field, cast(field as integer)]
{field=1, cast=1}
```

But it is instead:
```
["public"."test"."id", "public"."test"."field"]
{id=null, field=1}
```

**Comment by lukaseder** [comment] 2017-10-12 08:23
Thank you very much for your detailed report.

> I'd expect this to either be supported and always work or be unsupported and never work, rather than the current behavior where it sometimes works.

Well, and then, there are bugs, missing features, omissions, oversights, postponements... Sorry :)

This is a duplicate of #5688, #5622

Currently, only actual columns of the table inserted to can be returned, not arbitrary expressions.

**Closed by lukaseder** 2017-10-12 08:23 UTC
Labels: C: Functionality, P: Medium, T: Defect

**Comment by mjustin** [comment] 2017-10-12 14:23
Thanks, and sorry that I missed the duplicate issues.

**Comment by lukaseder** [comment] 2017-10-12 14:30
> Thanks, and sorry that I missed the duplicate issues.

No worries at all :) It's good to get these duplicates. This helps get a feel of what users need most.

> It makes sense that the fields()/intoMap() issue is due to it returning the same generic type, not an arbitrary record. That hadn't occurred to me while tracking this down.

Yeah, although, it doesn't make sense at all to return the generic type in the first place. That's really a bad API blunder...
