### ISSUE TITLE
Exception thrown when creating table with SQLDataType.UUID in MySQL

### ISSUE THREAD

**Issue by kovax** [jOOQ/jOOQ#5807] opened 2017-01-22 16:25 UTC
Running the java statement will throw the exception bellow.

```java
context.createTableIfNotExists(table(tableName))
            .column(field("UUID",      UUID.class),           SQLDataType.UUID.nullable(false))
            .column(field("ID",        Integer.class),        SQLDataType.INTEGER.nullable(false))
            .column(field("TIMESTAMP", OffsetDateTime.class), SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false))
            .constraints(constraint("PK_"+tableName).primaryKey(field("UUID"), field("ID")))
.execute();
```

```
org.jooq.exception.DataAccessException: SQL [create table if not exists EVENT(UUID varchar not null, ID int not null, TIMESTAMP timestamp with time zone not null, constraint "PK_EVENT" primary key (UUID, ID))]; length must be specified in type definition: VARCHAR in statement [create table if not exists EVENT(UUID varchar not null, ID int not null, TIMESTAMP timestamp with time zone not null, constraint "PK_EVENT" primary key (UUID, ID))]
	at org.jooq_3.9.0.HSQLDB.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:1981)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:676)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:363)
	at org.cristalise.storage.jooqdb.JooqHistoryHandler.createTables(JooqHistoryHandler.java:208)

Caused by: java.sql.SQLSyntaxErrorException: length must be specified in type definition: VARCHAR in statement [create table if not exists EVENT(UUID varchar not null, ID int not null, TIMESTAMP timestamp with time zone not null, constraint "PK_EVENT" primary key (UUID, ID))]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:112)
	at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:76)
	at org.jooq.impl.AbstractQuery.prepare(AbstractQuery.java:415)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:321)
	... 25 more
Caused by: org.hsqldb.HsqlException: length must be specified in type definition: VARCHAR
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.ParserDQL.readTypeDefinition(Unknown Source)
	at org.hsqldb.ParserTable.readColumnDefinitionOrNull(Unknown Source)
	at org.hsqldb.ParserTable.readTableContentsSource(Unknown Source)
	at org.hsqldb.ParserTable.compileCreateTableBody(Unknown Source)
	at org.hsqldb.ParserTable.compileCreateTable(Unknown Source)
	at org.hsqldb.ParserDDL.compileCreate(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatement(Unknown Source)
	at org.hsqldb.Session.compileStatement(Unknown Source)
	at org.hsqldb.StatementManager.compile(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 31 more
```

----
See also:
http://stackoverflow.com/q/43438099/521799

**Comment by lukaseder** [comment] 2017-01-22 16:38
Thank you very much for reporting. About time we add the `UUID` type to our DDL integration tests...

**Comment by lukaseder** [comment] 2017-02-01 09:01
The issue you've reported is probably affecting other databases as well. In the case of HSQLDB, there's also the possibility to support the native `UUID` type that HSQLDB offers: https://github.com/jOOQ/jOOQ/issues/5823

**Comment by lukaseder** [comment] 2017-02-01 10:00
With #5823 implemented, this now works for HSQLDB in jOOQ 3.10. This issue will fix the problem for jOOQ 3.9.2 and for other databases than HSQLDB

**Comment by Faithcaio** [comment] 2017-06-04 20:43
I've got a related problem with converted DataTypes:

I'm creating a custom DataType which is a String representation of a uniquely identified player:
`DataType<Player> PLAYER_TYPE = SQLDataType.VARCHAR(36).asConvertedDataType(new PlayerConverter())` 
[PlayerConverter](https://github.com/CubeEngine/core/blob/c7570c28105b908fbee8073483230a10c120f489/libcube/src/main/java/org/cubeengine/libcube/service/database/PlayerConverter.java)

Using MySQL DDL fails because the VARCHAR type is missing the length.

This is because `Tools#toSQLDDLTypeDeclaration` checks for `DataType#hasLength` which is implemented in `DefaultDataType` as `return (type == byte[].class || type == String.class) && !isLob();`
Obviously my Player is none of those so the length is not added.

I think this could be fixed by checking if `binding.converter().fromType()` has a length instead of `type`

**Comment by lukaseder** [comment] 2017-06-05 16:18
Thank you very much for your additional comment, @Faithcaio. Would you mind creating a new issue for this along with some steps to reproduce the problem? We'll see afterwards if this is really related.

**Comment by lukaseder** [comment] 2017-07-24 13:16
Closing this as a duplicate of #5823 (which is implemented in jOOQ 3.10)

**Comment by kovax** [comment] 2017-07-28 10:05
Lukas, I think your comment indicates that UUID support was corrected in 3.9.2 for all databases except HSQLDB. I am trying to use MySQL (connector: 5.1.43) with 3.9.4, and I am getting the following exception:

```
Exception in thread "main" org.jooq.exception.DataAccessException: SQL [create table if not exists `ITEM`(`UUID` varchar not null, `IOR` varchar(4096) null, `IS_AGENT` boolean not null, `PASSWORD` varchar(4096) null, constraint `PK_"ITEM"` primary key (`UUID`))]; You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'not null, `IOR` varchar(4096) null, `IS_AGENT` boolean not null, `PASSWORD` varc' at line 1
	at org.jooq_3.9.4.MYSQL.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:1994)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:676)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:363)
	at org.cristalise.storage.jooqdb.lookup.JooqItemHandler.createTables(JooqItemHandler.java:67)
	at org.cristalise.storage.jooqdb.auth.JooqAuthenticator.authenticate(JooqAuthenticator.java:55)
	at org.cristalise.kernel.process.Gateway.connect(Gateway.java:240)
	at org.cristalise.kernel.process.StandardServer.standardInitialisation(StandardServer.java:44)
	at org.cristalise.kernel.process.StandardServer.main(StandardServer.java:57)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'not null, `IOR` varchar(4096) null, `IS_AGENT` boolean not null, `PASSWORD` varc' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2494)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:195)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:431)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
	... 5 more
```

**Comment by lukaseder** [comment] 2017-07-28 10:13
Thanks for your report. Hmm, yes that's the same problem. In HSQLDB, there exists a native UUID type, which is why #5823 fixes this more thoroughly, but if UUID types are emulated through varchars (e.g. in MySQL), we should still generate appropriate data type definitions. I'm reopening this for reconsideration.

**Comment by kovax** [comment] 2017-07-28 11:19
Thanks, for the confirmation. I would appreciate if you could tell me when this bug will be fixed, otherwise I might need to do the ExecuteListener workaround you suggested here:

https://stackoverflow.com/questions/43438099/how-to-generate-proper-sql-for-mysql-with-jooq-with-uuid-fields

**Comment by lukaseder** [comment] 2017-07-28 13:39
I cannot make any promises about fix dates yet, but you'll get a notification from this ticket, I suspect.

**Comment by kovax** [comment] 2017-09-07 15:29
Lukas, do you have any update on this issue? I need to plan the workaround, if needed. Thanks.

**Comment by lukaseder** [comment] 2017-09-07 16:18
No, I don't have an update, sorry.

**Comment by kovax** [comment] 2017-09-07 17:20
Perhaps I could contribute the fix for mysql only. Is it possible that the only change is in this class?
org.jooq.util.mysql.MySQLDataType

**Comment by lukaseder** [comment] 2017-09-20 08:34
Thanks for your suggestion. This cannot be fixed in `MySQLDataType`, unfortunately. But the fix was rather easy in the relevant DDL utilities.

MySQL (and historically also MariaDB) are a bit special, unfortunately. jOOQ stores a "cast" type in `DataType.getCastTypeName()`, which is usually used to emulate data types also in DDL. The "cast" type contains a hard-wired length (or precision / scale) that is required for such an emulation. In this case, it would be `VARCHAR(36)`. But because [MySQL doesn't allow for casting to "ordinary" type specifications](https://dev.mysql.com/doc/refman/5.7/en/cast-functions.html#function_cast), this gets a bit more hairy.

But again, because the type is only needed in DDL right now, there's a simple patch. It'll be implemented in jOOQ 3.10, 3.9.6, 3.8.9

**Comment by lukaseder** [comment] 2017-09-20 08:35
To speed things up, this issue will deal only with MySQL, as the originally reported HSQLDB flaw already works through another fix, and other databases might be considered later.

**Closed** 2017-09-20 08:36 UTC
Labels: C: DB: MySQL, C: Functionality, P: High, R: Fixed, T: Defect

**Comment by kovax** [comment] 2017-09-20 12:04
I hope 3.9.6 will be out in the next months.

**Comment by lukaseder** [comment] 2017-09-20 12:06
All of these versions will be released next week.
