### ISSUE TITLE
Error while generating classes from Record Types and Oracle Types in Oracle 11g

### ISSUE THREAD

**Issue by rponte** [jOOQ/jOOQ#6643] opened 2017-10-06 18:13 UTC
### Expected behavior and actual behavior:
I expected to see all my Record Types and Oracle Types generated as happened in previous JOOQ version (3.9.5). But it seems like the generator is creating all table classes but not any custom type, like Record Types and Oracle Types.

When I try to generate my classes through my Ant script I've got this error:
```shell
[java] ADVERTÊNCIA: SQL exception            : Exception while executing meta query: ORA-00904: "a"."ORIGIN_CON_ID": identificador inválido
     [java] Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new
     [java] with "args_with_siblings" as (
     [java]   select 
     [java]     "a"."OWNER", 
     [java]     "a"."OBJECT_NAME", 
     [java]     "a"."PACKAGE_NAME", 
     [java]     "a"."OBJECT_ID", 
     [java]     "a"."OVERLOAD", 
     [java]     "a"."SUBPROGRAM_ID", 
     [java]     "a"."ARGUMENT_NAME", 
     [java]     "a"."POSITION", 
     [java]     "a"."SEQUENCE", 
     [java]     "a"."DATA_LEVEL", 
     [java]     "a"."DATA_TYPE", 
     [java]     "a"."DEFAULTED", 
     [java]     "a"."DEFAULT_VALUE", 
     [java]     "a"."DEFAULT_LENGTH", 
     [java]     "a"."IN_OUT", 
     [java]     "a"."DATA_LENGTH", 
     [java]     "a"."DATA_PRECISION", 
     [java]     "a"."DATA_SCALE", 
     [java]     "a"."RADIX", 
     [java]     "a"."CHARACTER_SET_NAME", 
     [java]     "a"."TYPE_OWNER", 
     [java]     "a"."TYPE_NAME", 
     [java]     "a"."TYPE_SUBNAME", 
     [java]     "a"."TYPE_LINK", 
     [java]     "a"."PLS_TYPE", 
     [java]     "a"."CHAR_LENGTH", 
     [java]     "a"."CHAR_USED", 
     [java]     "a"."ORIGIN_CON_ID", 
     [java]     lead(
     [java]       "a"."SEQUENCE", 
     [java]       1, 
     [java]       99999999
     [java]     ) over (partition by 
     [java]       "a"."OWNER", 
     [java]       "a"."PACKAGE_NAME", 
     [java]       "a"."SUBPROGRAM_ID", 
     [java]       "a"."DATA_LEVEL"
     [java]      order by "a"."SEQUENCE") "next_sibling"
     [java]   from "SYS"."ALL_ARGUMENTS" "a"
     [java]   where (
     [java]     "a"."OWNER" in ('MDB_IMDB_TEST')
     [java]     and "a"."PACKAGE_NAME" is not null
     [java]   )
     [java] )
     [java] (
     [java]   select 
     [java]     "SYS"."ALL_TYPES"."OWNER", 
     [java]     '' "pkg", 
     [java]     "SYS"."ALL_TYPES"."TYPE_NAME", 
     [java]     0 "synthetic"
     [java]   from "SYS"."ALL_TYPES"
     [java]   where (
     [java]     "SYS"."ALL_TYPES"."OWNER" in ('MDB_IMDB_TEST')
     [java]     and "SYS"."ALL_TYPES"."TYPECODE" in (
     [java]       'OBJECT', 'XMLTYPE'
     [java]     )
     [java]   )
     [java] )
     [java] union (
     [java]   select 
     [java]     "a"."TYPE_OWNER" "OWNER", 
     [java]     "a"."TYPE_NAME" "pkg", 
     [java]     "a"."TYPE_SUBNAME" "TYPE_NAME", 
     [java]     0 "synthetic"
     [java]   from "SYS"."ALL_ARGUMENTS" "a"
     [java]   where (
     [java]     "a"."TYPE_OWNER" in ('MDB_IMDB_TEST')
     [java]     and "a"."DATA_TYPE" = 'PL/SQL RECORD'
     [java]   )
     [java] )
     [java] union (
     [java]   select distinct 
     [java]     "a"."OWNER" "OWNER", 
     [java]     "a"."PACKAGE_NAME" "pkg", 
     [java]     (case
     [java]       when "a"."DATA_LEVEL" = 0 then "a"."OBJECT_NAME"
     [java]       else (
     [java]         select "q"."TYPE_SUBNAME"
     [java]         from "args_with_siblings" "q"
     [java]         where (
     [java]           "a"."DATA_LEVEL" = ("q"."DATA_LEVEL" + 1)
     [java]           and "a"."OWNER" = "q"."OWNER"
     [java]           and "a"."PACKAGE_NAME" = "q"."PACKAGE_NAME"
     [java]           and "a"."SUBPROGRAM_ID" = "q"."SUBPROGRAM_ID"
     [java]           and "a"."SEQUENCE" between "q"."SEQUENCE" and "q"."next_sibling"
     [java]         )
     [java]       )
     [java]     end || nvl2("a"."ARGUMENT_NAME", ('_' || "a"."ARGUMENT_NAME"), '')) "TYPE_NAME", 
     [java]     1 "synthetic"
     [java]   from "SYS"."ALL_ARGUMENTS" "a"
     [java]   where (
     [java]     "a"."OWNER" in ('MDB_IMDB_TEST')
     [java]     and "a"."TYPE_OWNER" is null
     [java]     and "a"."TYPE_NAME" is null
     [java]     and "a"."TYPE_SUBNAME" is null
     [java]     and "a"."DATA_TYPE" = 'PL/SQL RECORD'
     [java]   )
     [java] )
     [java] order by 
     [java]   1, 
     [java]   2, 
     [java]   3
     [java] out 06, 2017 3:05:19 PM org.jooq.tools.JooqLogger error
     [java] GRAVE: Error while fetching udts
     [java] org.jooq.exception.DataAccessException: SQL [with "args_with_siblings" as (select "a"."OWNER", "a"."OBJECT_NAME", "a"."PACKAGE_NAME", "a"."OBJECT_ID", "a"."OVERLOAD", "a"."SUBPROGRAM_ID", "a"."ARGUMENT_NAME", "a"."POSITION", "a"."SEQUENCE", "a"."DATA_LEVEL", "a"."DATA_TYPE", "a"."DEFAULTED", "a"."DEFAULT_VALUE", "a"."DEFAULT_LENGTH", "a"."IN_OUT", "a"."DATA_LENGTH", "a"."DATA_PRECISION", "a"."DATA_SCALE", "a"."RADIX", "a"."CHARACTER_SET_NAME", "a"."TYPE_OWNER", "a"."TYPE_NAME", "a"."TYPE_SUBNAME", "a"."TYPE_LINK", "a"."PLS_TYPE", "a"."CHAR_LENGTH", "a"."CHAR_USED", "a"."ORIGIN_CON_ID", lead("a"."SEQUENCE", 1, 99999999) over (partition by "a"."OWNER", "a"."PACKAGE_NAME", "a"."SUBPROGRAM_ID", "a"."DATA_LEVEL" order by "a"."SEQUENCE") "next_sibling" from "SYS"."ALL_ARGUMENTS" "a" where ("a"."OWNER" in (?) and "a"."PACKAGE_NAME" is not null)) (select "SYS"."ALL_TYPES"."OWNER", '' "pkg", "SYS"."ALL_TYPES"."TYPE_NAME", 0 "synthetic" from "SYS"."ALL_TYPES" where ("SYS"."ALL_TYPES"."OWNER" in (?) and "SYS"."ALL_TYPES"."TYPECODE" in ('OBJECT', 'XMLTYPE'))) union (select "a"."TYPE_OWNER" "OWNER", "a"."TYPE_NAME" "pkg", "a"."TYPE_SUBNAME" "TYPE_NAME", 0 "synthetic" from "SYS"."ALL_ARGUMENTS" "a" where ("a"."TYPE_OWNER" in (?) and "a"."DATA_TYPE" = 'PL/SQL RECORD')) union (select distinct "a"."OWNER" "OWNER", "a"."PACKAGE_NAME" "pkg", (case when "a"."DATA_LEVEL" = 0 then "a"."OBJECT_NAME" else (select "q"."TYPE_SUBNAME" from "args_with_siblings" "q" where ("a"."DATA_LEVEL" = ("q"."DATA_LEVEL" + 1) and "a"."OWNER" = "q"."OWNER" and "a"."PACKAGE_NAME" = "q"."PACKAGE_NAME" and "a"."SUBPROGRAM_ID" = "q"."SUBPROGRAM_ID" and "a"."SEQUENCE" between "q"."SEQUENCE" and "q"."next_sibling")) end || nvl2("a"."ARGUMENT_NAME", ('_' || "a"."ARGUMENT_NAME"), '')) "TYPE_NAME", 1 "synthetic" from "SYS"."ALL_ARGUMENTS" "a" where ("a"."OWNER" in (?) and "a"."TYPE_OWNER" is null and "a"."TYPE_NAME" is null and "a"."TYPE_SUBNAME" is null and "a"."DATA_TYPE" = 'PL/SQL RECORD')) order by 1, 2, 3 -- SQL rendered with a free trial version of jOOQ 3.10.0]; ORA-00904: "a"."ORIGIN_CON_ID": identificador inválido
     [java] 	at org.jooq_3.10.0.ORACLE.debug(Unknown Source)
     [java] 	at org.jooq.impl.Tools.translate(Tools.java:2202)
     [java] 	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:680)
     [java] 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361)
     [java] 	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:317)
     [java] 	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2597)
     [java] 	at org.jooq.util.oracle.OracleDatabase.getUDTs0(OracleDatabase.java:541)
     [java] 	at org.jooq.util.AbstractDatabase.getAllUDTs(AbstractDatabase.java:1636)
     [java] 	at org.jooq.util.AbstractDatabase.getUDTs(AbstractDatabase.java:1667)
     [java] 	at org.jooq.util.JavaGenerator.generateSchema(JavaGenerator.java:4280)
     [java] 	at org.jooq.util.JavaGenerator.generateSchema(JavaGenerator.java:4199)
     [java] 	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:445)
     [java] 	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:406)
     [java] 	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:328)
     [java] 	at org.jooq.util.GenerationTool.run(GenerationTool.java:642)
     [java] 	at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)
     [java] 	at org.jooq.util.GenerationTool.main(GenerationTool.java:175)
     [java] Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: "a"."ORIGIN_CON_ID": identificador inválido
     [java] 	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
     [java] 	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
     [java] 	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
     [java] 	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
     [java] 	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
     [java] 	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
     [java] 	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
     [java] 	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
     [java] 	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:776)
     [java] 	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:897)
     [java] 	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1034)
     [java] 	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
     [java] 	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3923)
     [java] 	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1385)
     [java] 	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
     [java] 	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3161)
     [java] 	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:262)
     [java] 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
     [java] 	... 13 more
     [java] out 06, 2017 3:05:20 PM org.jooq.tools.JooqLogger info
     [java] INFORMAÇÕES: Generating sequences     
     [java] out 06, 2017 3:05:20 PM org.jooq.tools.JooqLogger info
     [java] INFORMAÇÕES: Enums fetched            : 0 (0 included, 0 excluded)
     [java] out 06, 2017 3:05:20 PM org.jooq.tools.JooqLogger info
```

### Steps to reproduce the problem:
Just create any Oracle type in your schema like this:
```sql
create or replace TYPE "REMESSA" AS OBJECT (
  id          VARCHAR2(60),
  nome        VARCHAR2(255),
  criado_em   TIMESTAMP,
  status      NUMBER(1)
);
```
And now try to generate your classes through this [Ant script](https://gist.github.com/rponte/c96f8561bbbc22de0a6febeda6012669#file-build-xml) using this [jooq configuration](https://gist.github.com/rponte/c96f8561bbbc22de0a6febeda6012669#file-jooq-config-xml). To do this, just run the command `ant` inside your project in the console.

### Versions:

- jOOQ: 3.10
- Java: 1.8.0_91
- Database (include vendor): Oracle 11g XE
- JDBC Driver (include name if inofficial driver): ojdbc7.jar, orai18n.jar, xdb6.xml

**Comment by rponte** [comment] 2017-10-06 19:15
It's working like a charm with JOOQ version 3.9.6!

**Comment by lukaseder** [comment] 2017-10-09 09:11
Thank you very much for your report. I can reproduce this with Oracle 11g XE. I'm not sure why our integration tests hadn't failed here - it is definitely reproducible. The reason for this problem is that we're using `ALL_ARGUMENTS.fields()`, which includes all columns from the `ALL_ARGUMENTS` table as it is defined in 12c.

**Comment by lukaseder** [comment] 2017-10-09 09:14
The corrected queries are now:

```sql
with "args_with_siblings" as (
  select 
    "a"."OWNER", 
    "a"."OBJECT_NAME", 
    "a"."PACKAGE_NAME", 
    "a"."SUBPROGRAM_ID", 
    "a"."ARGUMENT_NAME", 
    "a"."POSITION", 
    "a"."SEQUENCE", 
    "a"."DATA_LEVEL", 
    "a"."DATA_TYPE", 
    "a"."DATA_LENGTH", 
    "a"."DATA_PRECISION", 
    "a"."DATA_SCALE", 
    "a"."TYPE_OWNER", 
    "a"."TYPE_NAME", 
    "a"."TYPE_SUBNAME", 
    lead(
      "a"."SEQUENCE", 
      1, 
      99999999
    ) over (partition by 
      "a"."OWNER", 
      "a"."PACKAGE_NAME", 
      "a"."SUBPROGRAM_ID", 
      "a"."DATA_LEVEL"
     order by "a"."SEQUENCE") "next_sibling"
  from "SYS"."ALL_ARGUMENTS" "a"
  where (
    "a"."OWNER" in (
      'TEST'
    )
    and "a"."PACKAGE_NAME" is not null
  )
)
(
  select 
    "SYS"."ALL_TYPES"."OWNER", 
    '' "pkg", 
    "SYS"."ALL_TYPES"."TYPE_NAME", 
    0 "synthetic"
  from "SYS"."ALL_TYPES"
  where (
    "SYS"."ALL_TYPES"."OWNER" in (
      'TEST'
    )
    and "SYS"."ALL_TYPES"."TYPECODE" in (
      'OBJECT', 'XMLTYPE'
    )
  )
)
union (
  select 
    "a"."TYPE_OWNER" "OWNER", 
    "a"."TYPE_NAME" "pkg", 
    "a"."TYPE_SUBNAME" "TYPE_NAME", 
    0 "synthetic"
  from "SYS"."ALL_ARGUMENTS" "a"
  where (
    "a"."TYPE_OWNER" in (
      'TEST'
    )
    and "a"."DATA_TYPE" = 'PL/SQL RECORD'
  )
)
union (
  select distinct 
    "a"."OWNER" "OWNER", 
    "a"."PACKAGE_NAME" "pkg", 
    (case
      when "a"."DATA_LEVEL" = 0 then "a"."OBJECT_NAME"
      else (
        select "q"."TYPE_SUBNAME"
        from "args_with_siblings" "q"
        where (
          "a"."DATA_LEVEL" = ("q"."DATA_LEVEL" + 1)
          and "a"."OWNER" = "q"."OWNER"
          and "a"."PACKAGE_NAME" = "q"."PACKAGE_NAME"
          and "a"."SUBPROGRAM_ID" = "q"."SUBPROGRAM_ID"
          and "a"."SEQUENCE" between "q"."SEQUENCE" and "q"."next_sibling"
        )
      )
    end || nvl2("a"."ARGUMENT_NAME", ('_' || "a"."ARGUMENT_NAME"), '')) "TYPE_NAME", 
    1 "synthetic"
  from "SYS"."ALL_ARGUMENTS" "a"
  where (
    "a"."OWNER" in (
      'TEST'
    )
    and "a"."TYPE_OWNER" is null
    and "a"."TYPE_NAME" is null
    and "a"."TYPE_SUBNAME" is null
    and "a"."DATA_TYPE" = 'PL/SQL RECORD'
  )
)
order by 
  1, 
  2, 
  3
```

And later on:

```sql
with 
  "args_with_siblings" as (
    select 
      "a"."OWNER", 
      "a"."OBJECT_NAME", 
      "a"."PACKAGE_NAME", 
      "a"."SUBPROGRAM_ID", 
      "a"."ARGUMENT_NAME", 
      "a"."POSITION", 
      "a"."SEQUENCE", 
      "a"."DATA_LEVEL", 
      "a"."DATA_TYPE", 
      "a"."DATA_LENGTH", 
      "a"."DATA_PRECISION", 
      "a"."DATA_SCALE", 
      "a"."TYPE_OWNER", 
      "a"."TYPE_NAME", 
      "a"."TYPE_SUBNAME", 
      lead(
        "a"."SEQUENCE", 
        1, 
        99999999
      ) over (partition by 
        "a"."OWNER", 
        "a"."PACKAGE_NAME", 
        "a"."SUBPROGRAM_ID", 
        "a"."DATA_LEVEL"
       order by "a"."SEQUENCE") "next_sibling"
    from "SYS"."ALL_ARGUMENTS" "a"
    where (
      "a"."OWNER" in (
        'TEST'
      )
      and "a"."PACKAGE_NAME" is not null
    )
  ), 
  "record_types" as (
    select 
      case
        when (
          "p"."TYPE_OWNER" is null
          and "p"."TYPE_NAME" is null
          and "p"."TYPE_SUBNAME" is null
        ) then case
          when "p"."DATA_LEVEL" = 0 then 'TOP_LEVEL_ROWTYPE'
          else 'NESTED_ROWTYPE'
        end
        else 'NON_ROWTYPE'
      end "type", 
      case
        when (
          "p"."TYPE_OWNER" is null
          and "p"."TYPE_NAME" is null
          and "p"."TYPE_SUBNAME" is null
        ) then case
          when "p"."DATA_LEVEL" = 0 then ((((("a"."OWNER" || '.') || "a"."PACKAGE_NAME") || '.') || "a"."OBJECT_NAME") || nvl2("p"."ARGUMENT_NAME", ('_' || "p"."ARGUMENT_NAME"), ''))
          else ((
            select (((("q"."TYPE_OWNER" || '.') || "q"."TYPE_NAME") || '.') || "q"."TYPE_SUBNAME")
            from "args_with_siblings" "q"
            where (
              "a"."DATA_LEVEL" = ("q"."DATA_LEVEL" + 2)
              and "a"."OWNER" = "q"."OWNER"
              and "a"."PACKAGE_NAME" = "q"."PACKAGE_NAME"
              and "a"."SUBPROGRAM_ID" = "q"."SUBPROGRAM_ID"
              and "a"."SEQUENCE" between "q"."SEQUENCE" and "q"."next_sibling"
            )
          ) || nvl2("p"."ARGUMENT_NAME", ('_' || "p"."ARGUMENT_NAME"), ''))
        end
        else (((("p"."TYPE_OWNER" || '.') || "p"."TYPE_NAME") || '.') || "p"."TYPE_SUBNAME")
      end "qualifier", 
      "a"."OWNER", 
      "a"."OBJECT_NAME", 
      "a"."PACKAGE_NAME", 
      "a"."SUBPROGRAM_ID", 
      "a"."ARGUMENT_NAME", 
      "a"."POSITION", 
      "a"."SEQUENCE", 
      "a"."DATA_LEVEL", 
      "a"."DATA_TYPE", 
      "a"."DATA_LENGTH", 
      "a"."DATA_PRECISION", 
      "a"."DATA_SCALE", 
      "a"."TYPE_OWNER", 
      "a"."TYPE_NAME", 
      "a"."TYPE_SUBNAME", 
      "a"."next_sibling"
    from "args_with_siblings" "a"
      join "args_with_siblings" "p"
      on (
        "p"."DATA_TYPE" = 'PL/SQL RECORD'
        and "a"."DATA_LEVEL" = ("p"."DATA_LEVEL" + 1)
        and "a"."OWNER" = "p"."OWNER"
        and "a"."PACKAGE_NAME" = "p"."PACKAGE_NAME"
        and "a"."SUBPROGRAM_ID" = "p"."SUBPROGRAM_ID"
        and "a"."SEQUENCE" between "p"."SEQUENCE" and "p"."next_sibling"
      )
  )
select distinct 
  "qualifier", 
  "a"."ARGUMENT_NAME" "ATTR_NAME", 
  "a"."POSITION" "ATTR_NO", 
  case
    when (
      "a"."DATA_TYPE" = 'PL/SQL RECORD'
      and "a"."TYPE_OWNER" is null
    ) then "a"."OWNER"
    else "a"."TYPE_OWNER"
  end "ATTR_TYPE_OWNER", 
  case
    when (
      "a"."DATA_TYPE" = 'PL/SQL RECORD'
      and "a"."TYPE_OWNER" is null
    ) then "a"."PACKAGE_NAME"
    else nvl2("a"."TYPE_SUBNAME", "a"."TYPE_NAME", null)
  end "package_name", 
  case
    when (
      "a"."DATA_TYPE" = 'PL/SQL RECORD'
      and "a"."TYPE_OWNER" is null
    ) then ((substr(
      "qualifier", 
      instr("qualifier", '.', 1, 2) + 1
    ) || '_') || "a"."ARGUMENT_NAME")
    else coalesce(
      "a"."TYPE_SUBNAME", 
      "a"."TYPE_NAME", 
      "a"."DATA_TYPE"
    )
  end "ATTR_TYPE_NAME", 
  "a"."DATA_LENGTH" "LENGTH", 
  "a"."DATA_PRECISION" "PRECISION", 
  "a"."DATA_SCALE" "SCALE"
from "record_types" "a"
order by 
  "qualifier", 
  "a"."POSITION"
```

**Comment by lukaseder** [comment] 2017-10-09 09:17
Fixed for jOOQ 3.11. This will be merged to 3.10.1 (#6649). Release due this week.

**Closed by lukaseder** 2017-10-09 09:17 UTC
Labels: C: Code Generation, C: DB: Oracle, P: Urgent, R: Fixed, T: Defect

**Comment by lukaseder** [comment] 2017-10-11 15:12
The fix for this issue has now been released in 3.10.1

**Comment by rponte** [comment] 2017-10-11 15:24
Nice! Is it possible to download it so that I can test it?

**Comment by lukaseder** [comment] 2017-10-11 18:01
Here you go: https://www.jooq.org/download/
