### ISSUE TITLE
R2DBC nested subscription loops forever when nesting or sequencing INSERT .. RETURNING run on r2dbc-pool

### ISSUE THREAD

**Issue by vinith-dev** [jOOQ/jOOQ#12104] opened 2021-07-02 16:10 UTC
### Steps to reproduce the problem
Please verify the code and execute the test cases to reproduce the issue.

[https://github.com/vinith-dev/jooq-sequential-write.git](url)

### Versions

- jOOQ: 3.15.0-SNAPSHOT
- Java: 16
- Database (include vendor): postgresql
- OS: Ubuntu20
- JDBC Driver (include name if inofficial driver): R2DBC with connection pooling

**Comment by lukaseder** [comment] 2021-07-02 18:57
Thanks a lot for your detailed reproducer. I'll check it out early next week!

**Comment by lukaseder** [comment] 2021-07-05 07:47
I can reproduce the issue as described in the MCVE, thanks again. Will investigate now

**Comment by lukaseder** [comment] 2021-07-05 08:51
Can't reproduce this with an H2 integration test:

```java
final Table<?>       t = table(name("t"));
final Field<Integer> i = field(name("t", "i"), INTEGER.identity(true));

ConnectionPool pool;
DSLContext     ctx;

@Before
public void setup() throws Exception {
    ConnectionFactory connectionFactory = ConnectionFactories.get(
        ConnectionFactoryOptions
            .parse("r2dbc:h2:file://localhost/~/r2dbc-pool-test")
            .mutate()
            .option(ConnectionFactoryOptions.USER, "sa")
            .option(ConnectionFactoryOptions.PASSWORD, "")
            .build()
    );

    ConnectionPoolConfiguration configuration = ConnectionPoolConfiguration.builder(connectionFactory)
       .maxIdleTime(Duration.ofMillis(1000))
       .maxSize(1)
       .build();

    pool = new ConnectionPool(configuration);
    ctx = DSL.using(pool, H2);
}

@After
public void teardown() {
    pool.close().block();
    pool.dispose();
}

@Test
public void testNestedInsertions() {
    testT(() -> {
        Mono<Boolean> mono = Mono.create(sink -> {
            sink.onRequest(cons -> {
                Mono.from(ctx.insertInto(t).defaultValues().returningResult(i)).subscribe(
                    r1 -> {
                        assertEquals(1, (int) r1.value1());

                        Mono.from(ctx.insertInto(t).defaultValues().returningResult(i)).subscribe(
                            r2 -> {
                                assertEquals(2, (int) r2.value1());
                                sink.success(true);
                            },
                            error -> {
                                sink.error(new AssertionError());
                            }
                        );
                    },
                    error -> {
                        sink.error(new AssertionError());
                    }
                );
            });
        });

        assertEquals(true, mono.block());
    });
}

private void testT(Runnable runnable) {
    try {
        Mono.from(ctx.createTable(t).column(i)).block();
        runnable.run();
    }
    finally {
        Mono.from(ctx.dropTable(t)).block();
    }
}
```

**Comment by lukaseder** [comment] 2021-07-05 09:00
Test passes when I upgrade the dependencies to:

```xml
    <dependency>
        <groupId>io.r2dbc</groupId>
        <artifactId>r2dbc-pool</artifactId>
        <version>0.9.0.M1</version>
    </dependency>
    <dependency>
        <groupId>io.r2dbc</groupId>
        <artifactId>r2dbc-spi</artifactId>
        <version>0.9.0.M1</version>
    </dependency>
    <dependency>
        <groupId>org.postgresql</groupId>
        <artifactId>r2dbc-postgresql</artifactId>
        <version>0.9.0.M1</version>
    </dependency>
```

**Comment by lukaseder** [comment] 2021-07-05 09:06
In fact, the r2dbc-postgresql driver can be left on version `0.8.8.RELEASE`. The upgrade of the `r2dbc-pool` seems to be sufficient here. Can you confirm this?

**Comment by lukaseder** [comment] 2021-07-05 09:09
The test passes on my side, though there are exceptions in the logs, which may not be related. Will investigate:

```
11:07:20,627 ERROR [reactor.core.publisher.Operators                  ] - Operator called default onErrorDropped
io.r2dbc.postgresql.client.ReactorNettyClient$PostgresConnectionClosedException: Connection closed
	at io.r2dbc.postgresql.client.ReactorNettyClient.lambda$static$1(ReactorNettyClient.java:100) ~[r2dbc-postgresql-0.9.0.M1.jar:0.9.0.M1]
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.close(ReactorNettyClient.java:1000) ~[r2dbc-postgresql-0.9.0.M1.jar:0.9.0.M1]
	at io.r2dbc.postgresql.client.ReactorNettyClient.drainError(ReactorNettyClient.java:514) ~[r2dbc-postgresql-0.9.0.M1.jar:0.9.0.M1]
	at io.r2dbc.postgresql.client.ReactorNettyClient.lambda$close$8(ReactorNettyClient.java:193) ~[r2dbc-postgresql-0.9.0.M1.jar:0.9.0.M1]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4099) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:173) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4099) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4214) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4070) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4006) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.pool.SimpleDequePool.maybeRecycleAndDrain(SimpleDequePool.java:430) ~[reactor-pool-0.2.2.jar:0.2.2]
	at reactor.pool.SimpleDequePool$QueuePoolRecyclerInner.onComplete(SimpleDequePool.java:622) ~[reactor-pool-0.2.2.jar:0.2.2]
	at reactor.core.publisher.Operators.complete(Operators.java:136) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4099) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.pool.SimpleDequePool$QueuePoolRecyclerMono.subscribe(SimpleDequePool.java:735) ~[reactor-pool-0.2.2.jar:0.2.2]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:154) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:154) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4099) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4214) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4070) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4006) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.pool.SimpleDequePool.maybeRecycleAndDrain(SimpleDequePool.java:430) ~[reactor-pool-0.2.2.jar:0.2.2]
	at reactor.pool.SimpleDequePool$QueuePoolRecyclerInner.onComplete(SimpleDequePool.java:622) ~[reactor-pool-0.2.2.jar:0.2.2]
	at reactor.core.publisher.Operators.complete(Operators.java:136) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4099) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.pool.SimpleDequePool$QueuePoolRecyclerMono.subscribe(SimpleDequePool.java:735) ~[reactor-pool-0.2.2.jar:0.2.2]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:154) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:154) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4099) ~[reactor-core-3.4.4.jar:3.4.4]
	at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.lambda$0(R2DBC.java:558) ~[classes/:?]
	at java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210) ~[?:?]
	at org.jooq.impl.R2DBC$AbstractNonBlockingSubscription.cancel0(R2DBC.java:553) ~[classes/:?]
	at org.jooq.impl.R2DBC$AbstractSubscription.complete(R2DBC.java:197) ~[classes/:?]
	at org.jooq.impl.R2DBC$AbstractSubscription.cancel(R2DBC.java:183) ~[classes/:?]
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:81) ~[reactor-core-3.4.4.jar:3.4.4]
	at org.jooq.impl.Internal$1.onNext(Internal.java:433) ~[classes/:?]
	at org.jooq.impl.R2DBC$Forwarding.onNext(R2DBC.java:229) ~[classes/:?]
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:657) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:735) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:777) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:255) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) ~[reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154) [reactor-core-3.4.4.jar:3.4.4]
	at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:717) [r2dbc-postgresql-0.9.0.M1.jar:0.9.0.M1]
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:968) [r2dbc-postgresql-0.9.0.M1.jar:0.9.0.M1]
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:842) [r2dbc-postgresql-0.9.0.M1.jar:0.9.0.M1]
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:749) [r2dbc-postgresql-0.9.0.M1.jar:0.9.0.M1]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118) [reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) [reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220) [reactor-core-3.4.4.jar:3.4.4]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220) [reactor-core-3.4.4.jar:3.4.4]
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:267) [reactor-netty-core-1.0.4.jar:1.0.4]
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:377) [reactor-netty-core-1.0.4.jar:1.0.4]
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:381) [reactor-netty-core-1.0.4.jar:1.0.4]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94) [reactor-netty-core-1.0.4.jar:1.0.4]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.59.Final.jar:4.1.59.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.59.Final.jar:4.1.59.Final]
	at java.lang.Thread.run(Thread.java:831) [?:?]

```

**Comment by lukaseder** [comment] 2021-07-05 09:48
The connection closed exception will be tracked separately: https://github.com/jOOQ/jOOQ/issues/12108

**Comment by lukaseder** [comment] 2021-07-07 08:12
OK, I've updated the MCVE to remove the r2dbc-pool, and I can still reproduce it. I was chasing the wrong issue. Probably, the pool just introduced a delay somewhere, which caused what probably is a timing issue to stop manifesting

**Comment by lukaseder** [comment] 2021-07-07 08:31
Never mind. The pool was still being used, because of the `.option(DRIVER, "pool")`. Changing that to `.option(DRIVER, "postgresql")` also fixes the issue.

**Comment by lukaseder** [comment] 2021-07-07 08:39
Another way to fix this in the MCVE seems to be to let the pool warm up before running your queries. I.e. in `AbstractTest`, after initialising the `DSLContext`, add a 

```java
Mono.from(ctx.selectOne()).block();
```

And the problem disappears. So, it seems that we loop endlessly when the pool can't provide a connection fast enough. In the blocking world, clients just wait for the pool to be ready, but here, I wonder whose fault this is...

**Comment by lukaseder** [comment] 2021-07-07 09:14
This patch seems to fix it:

```patch
diff --git a/jOOQ/src/main/java/org/jooq/impl/R2DBC.java b/jOOQ/src/main/java/org/jooq/impl/R2DBC.java
index 7b08c2b..b00e1c1 100644
--- a/jOOQ/src/main/java/org/jooq/impl/R2DBC.java
+++ b/jOOQ/src/main/java/org/jooq/impl/R2DBC.java
@@ -220,14 +220,14 @@
         @Override
         public final void onSubscribe(Subscription s) {
             subscription.set(s);
-            resultSubscriber.downstream.request1(s);
+            resultSubscriber.downstream.request2(s);
         }
 
         @Override
         public final void onNext(T value) {
             if (!resultSubscriber.downstream.completed.get()) {
                 resultSubscriber.downstream.subscriber.onNext(value);
-                resultSubscriber.downstream.request1(subscription.get());
+                resultSubscriber.downstream.request2(subscription.get());
             }
         }
 
@@ -530,20 +530,35 @@
         final void request0() {
 
             // Lazy execution of the query
-            if (!subscribed.getAndSet(true))
-                connection.subscribe(delegate());
+            if (!subscribed.getAndSet(true)) {
+                ConnectionSubscriber<T> delegate = delegate();
 
+                connection.subscribe(subscriber(
+                    delegate::onSubscribe,
+                    c -> {
+                        delegate.onNext(c);
+                        request1();
+                    },
+                    delegate::onError,
+                    delegate::onComplete
+                ));
+            }
+            else
+                request1();
+        }
+
+        private void request1() {
             // Forwarders all forward to the same downstream and are not
             // expected to be contained in the map at the same time.
             for (Forwarding<T> f : forwarders.values()) {
                 Subscription s = f.subscription.get();
 
                 if (s != null)
-                    request1(s);
+                    request2(s);
             }
         }
 
-        final void request1(Subscription s) {
+        final void request2(Subscription s) {
             if (moreRequested())
                 s.request(1);
         }
```

**Comment by lukaseder** [comment] 2021-07-07 09:28
Patch has been committed and backported to 3.15.1 (https://github.com/jOOQ/jOOQ/issues/12115).

Waiting for confirmation that this fixes the original issue outside of the MCVE as well.

**Comment by lukaseder** [comment] 2021-07-07 19:49
Fix has been confirmed to work.

**Closed by lukaseder** 2021-07-07 19:49 UTC
Labels: C: Functionality, E: All Editions, P: High, R: Fixed, T: Defect
