### ISSUE TITLE
Query in citext fields return empty result

### ISSUE THREAD

**Issue by Mithrandir21** [jOOQ/jOOQ#7093] opened 2018-01-23 18:06 UTC
### Expected behavior and actual behavior:
When querying a PostgreSQL table (and any views), where the db column type is "citext", the query returns an empty list. The query seems to disregard the citext column.

```java
dsl.selectFrom(USERDATA)
   .where(USERDATA.USER_FIRSTNAME.eq(name))
   .fetchInto(Userdata.class);
```

**Note** that the citext column has been forcedType'd with the following code:

```xml
<forcedType>
   <name>TEXT</name> <!-- From CITEXT -->
   <expression>userdata.User_Firstname</expression>
</forcedType>
```

If I run the SQL code, shown in the debug log, directly on the PostgreSQL, results are returned as expected.
```sql
select * from "content"."userdata" where "content"."userdata"."user_firstname" = 'name'
```

### Steps to reproduce the problem:

```sql
CREATE TABLE content.user_info(user_firstname public.citext NOT NULL);

CREATE OR REPLACE VIEW content.userdata AS 
 SELECT usertable.user_firstname,
 FROM content.user_info AS usertable;
```

### Versions:

- jOOQ: 3.10.2
- Java: 1.8
- Database (include vendor): PostgreSQL v.9.6.6-1
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment] 2018-01-23 21:22
Thanks a lot for reporting. I'll look into this soon.

**Comment by lukaseder** [comment] 2018-01-25 15:59
Related: #5934

**Comment by lukaseder** [comment] 2018-01-25 16:04
@Mithrandir21 Just to be sure, since the query specifies an all lower case `user_firstname` column, yet you referenced a mixed case, partially qualified column:

```xml
   <expression>userdata.User_Firstname</expression>
```

Are you sure your forced type was applied appropriately? Have you tried this expression instead (case insensitive, fully qualified):

```xml
   <expression>(?i:.*?\.userdata\.user_firstname)</expression>
```

**Comment by lukaseder** [comment] 2018-01-25 16:15
Never mind, I can reproduce this issue. I don't think jOOQ can do anything here right now, short of actually supporting the `CITEXT` data type (see #5934).

I've found the following discussion hinting at a possible workaround:
https://www.postgresql.org/message-id/CAJFs0QC_nn5WxhrgMuXsK%3DWCc5JHvMmGk%2BzHoiwLz-EG7W2a4A%40mail.gmail.com

You could add this JDBC connection parameter to your JDBC connection URL: `stringtype=unspecified`, e.g.:

```
jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified
```

I'm closing this as a duplicate of #5934

**Comment by lukaseder** [comment] 2018-01-25 16:16
Another option is, of course, to implement your own custom data type binding as documented here:
https://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings

That would probably work better than simply rewriting the type to `TEXT`

**Closed by lukaseder** 2018-01-25 16:15 UTC
Labels: C: DB: PostgreSQL, C: Functionality, P: Medium, T: Defect

**Comment by Mithrandir21** [comment] 2018-01-25 22:23
Thank you for the suggestion. I will surely look into it.

One of my assumptions might have been tripping me up here. I will explain.
In addition to using JOOQ to make the queries, I am also generating POJOs.
For the class in question, the fields in question are generated and ForceTyped to String fields.
This led me to believe that the Query created with JOOQ would also treat the fields in the SQL query as Strings.

But that is where I think I might have gotten it wrong.
Could it be that JOOQ is simply disregarding those fields from the executed query because they are of a type not supported (citext)?

However, the log does show a valid SQL query, which works completely fine when run directly on the DB server.

**Comment by lukaseder** [comment] 2018-01-26 09:21
> Could it be that JOOQ is simply disregarding those fields from the executed query because they are of a type not supported (citext)?

No, jOOQ is completely unaware of the fields being of type `citext`. It pretends that they're of type `text`.

> However, the log does show a valid SQL query, which works completely fine when run directly on the DB server.

The explanation is here:
https://www.postgresql.org/message-id/CAJFs0QC_nn5WxhrgMuXsK%3DWCc5JHvMmGk%2BzHoiwLz-EG7W2a4A%40mail.gmail.com

**Comment by Mithrandir21** [comment] 2018-01-26 21:51
@lukaseder Thank you very much for the explanation and link. They helped resolve the issue.

It was, as you pointed to, an issue with the jdbc driver and the `stringtype` property.

I resolved the issue on my end by changing my jdbc connection URL to include `?stringtype=unspecified` at the end like so `jdbc:postgresql://[host]:[port]/[db]?stringtype=unspecified`. [Info](https://stackoverflow.com/questions/40473588/spring-boot-spring-datasource-connectionproperties-not-working-in-1-4-1)

This issue is resolved for me and can be closed if that is appropriate for you.

**Comment by lukaseder** [comment] 2018-01-29 09:22
> I resolved the issue on my end by changing my jdbc connection URL to include...

Well, just be sure that doesn't have any unwanted side-effects :)

> Please keep up the amazing work

Thanks for your nice words!

**Comment by lukaseder** [comment] 2022-03-03 08:36
jOOQ 3.17.0 has native `CITEXT` data type support in the `jooq-postgres-extensions` module: https://github.com/jOOQ/jOOQ/issues/5934
