### ISSUE TITLE
Insert Method of DAOImp should not be void.

### ISSUE THREAD

**Issue by Gemini-Akash** [jOOQ/jOOQ#14012] opened 2022-09-22 13:12 UTC
### Use case

When i am using the Daos with the service and controller layer and My POST method uses the insert() method in this cases i am not able to get the record which is added by the user, I want that record to show in the ResponseEntity body.
   

### jOOQ Version

jooq:3.14.16

### Database product and version

Mysql

### Java Version

11

### OS Version

windows

### JDBC driver name and version (include name if unofficial driver)

Mysql

**Comment by lukaseder** [comment] 2022-09-22 13:37
Thanks for your report. Probably a duplicate of these ones?

- https://github.com/jOOQ/jOOQ/issues/2536
- https://github.com/jOOQ/jOOQ/issues/3021

**Comment by Gemini-Akash** [comment] 2022-09-22 15:11
Hello Lukas,

Yeah, the issue already there.

**Comment by lukaseder** [comment] 2022-09-23 07:27
Why the reopen? We won't change the signature of the methods, and the underlying request is already going to be addressed elsewhere...

**Comment by Gemini-Akash** [comment] 2022-09-23 07:27
Hey Lukas,

I want to ask how we are going to get the record once inserted we are going to use two query **first insert and then fetch** if this is the case then we have a cost to hit a database and if we insert a one record then it will hits the database two times if we add one record.

for ex- I have to insert the 100 records in batch then for every records it hits the database twice. so total hits will be 200. which is not feasible.

Also want to know the ETA of this 3.18

**Closed by lukaseder** 2022-09-23 07:27 UTC
Labels: T: Enhancement, C: Functionality, P: Medium, R: Duplicate, E: All Editions

**Comment by lukaseder** [comment] 2022-09-23 07:30
> I want to ask how we are going to get the record once inserted we are going to use two query **first insert and then fetch** if this is the case then we have a cost to hit a database and if we insert a one record then it will hits the database two times if we add one record.

You don't *have to* use the `DAO` API. Use jOOQ's `UpdatableRecord` API instead. Or just write a plain `INSERT .. RETURNING` query.

> for ex- I have to insert the 100 records in batch then for every records it hits the database twice. so total hits will be 200. which is not feasible.

We currently don't fetch generated IDs in batch queries, see: https://github.com/jOOQ/jOOQ/issues/3327

> Also want to know the ETA of this 3.18

Probably Q1 2023, though, we never make promises.

**Comment by Gemini-Akash** [comment] 2022-09-24 20:31
I Use the all the above Methods nothing work in my use case all the methods are returning the ID NULL.
