### ISSUE TITLE
SQLite's MetaImpl can't distinguish between multiple unnamed UNIQUE constraints

### ISSUE THREAD

**Issue by Jeremy-Doneghue** [jOOQ/jOOQ#16854] opened 2024-06-25 04:35 UTC
### Expected behavior

Generated `BadTableDefaultDao` class should have methods:

`fun fetchOneByCd(value: String): org.jooq.mcve.kotlin.sqlite.tables.pojos.BadTablePojo`
`fun fetchOneByE(value: Int): org.jooq.mcve.kotlin.sqlite.tables.pojos.BadTablePojo`

### Actual behavior

Generated BadTableDefaultDao is missing method: `fetchOneByCd`, and `fetchOneByE`

The presence of the second unique column `e INTEGER UNIQUE` on `bad_table` appears to cause the problem.
Its sister table `good_table` correctly has a `fetchOneByCd` method.

I could not find any older version of jooq that behaved correctly either, I tried a handful of major versions down to 3.15.

### Steps to reproduce the problem

MCVE: https://github.com/Jeremy-Doneghue/jOOQ-mcve/tree/sqlite-missing-dao-generateed-fetchone Test case is in jOOQ-mcve-kotlin-sqlite

Related to: https://github.com/jOOQ/jOOQ/issues/16667

### jOOQ Version

3.19.10

### Database product and version

SQLite 3.44.1.0

### Java Version

openjdk 17.0.11 2024-04-16

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.xerial:sqlite-jdbc:3.44.1.0

**Comment by lukaseder** [comment] 2024-06-25 07:21
Thanks a lot for your report and reproducer. This looks similar to the problem reported here:

- https://github.com/jOOQ/jOOQ/issues/16667#issuecomment-2109081263

I think the problem is related to the unique constraints being unnamed. The problem reproduces with this table:

```sql
CREATE TABLE t_16667 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cd TEXT NOT NULL UNIQUE,
  e  INTEGER UNIQUE
);
```

But not with this one:

```sql
CREATE TABLE t_16667 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cd TEXT NOT NULL,
  e  INTEGER,
  CONSTRAINT u1 UNIQUE (cd),
  CONSTRAINT u2 UNIQUE (e)
);
```

Will look into this right away.

**Comment by lukaseder** [comment] 2024-06-25 07:44
Yes, that was it. It's not really a code generation problem, though it does manifest there as well, as the code generation uses the runtime `Meta` API to reverse engineer unique constraints, as SQLite's `SQLITE_MASTER` table and pragmas don't provide sufficient information about constraints.

**Comment by lukaseder** [comment] 2024-06-25 07:45
Fixed in versions:

- 3.20.0
- 3.19.11 (https://github.com/jOOQ/jOOQ/issues/16858)
- 3.18.18 (https://github.com/jOOQ/jOOQ/issues/16859)
- 3.17.27 (https://github.com/jOOQ/jOOQ/issues/16860)

**Closed by lukaseder** 2024-06-25 07:45 UTC
Labels: T: Defect, C: Functionality, C: DB: SQLite, P: Medium, E: All Editions
