### ISSUE TITLE
Generator tool can't read schema and so throw NPE

### ISSUE THREAD

**Issue by hepin1989** [jOOQ/jOOQ#6847] opened 2017-11-23 09:52 UTC
### Expected behavior and actual behavior:
could not load `/xsd/jooq-codegen-3.10.0.xsd.xml`,need to change the xsd to `/xsd/jooq-codegen-3.10.0.xsd.xml` or 

```
GenerationTool.class.getClassLoader().getResource("xsd/jooq-codegen-3.10.0.xsd.xml")
```
### Versions:

- jOOQ: 3.10.1
- Java: 1.8
- Database (include vendor): MySQL
- JDBC Driver (include name if inofficial driver):

![image](https://user-images.githubusercontent.com/501740/33166916-d8c3bbae-d076-11e7-8c4a-2f110de93269.png)

![image](https://user-images.githubusercontent.com/501740/33166989-13613cdc-d077-11e7-8961-36c2020f2b75.png)

Btw,I have to create it with datasource in code;)

**Comment by lukaseder** [comment] 2017-11-23 10:37
The file is called `jooq-codegen-3.10.0.xsd`, not `jooq-codegen-3.10.0.xsd.xml`. Does that resolve your issue?

**Comment by hepin1989** [comment] 2017-11-23 12:00
@lukaseder yes,But I have to construct my DataSource from code,so When I down load the file,this called `xsd.xml`,and I can't find the `jooq-codegen-3.10.0.xsd`.

https://github.com/jOOQ/jOOQ/issues/6851

**Comment by lukaseder** [comment] 2017-11-23 12:04
Not sure what you mean, the file is here: https://www.jooq.org/xsd/jooq-codegen-3.10.0.xsd

Anyway, that seems to be discussing your workaround instead of the actual problem. Can you please show how your problem can be reproduced? Is there a stack trace? What's your code / configuration that leads to the problem? Etc.

Here are some guidelines to follow: https://stackoverflow.com/help/mcve

**Comment by hepin1989** [comment] 2017-11-23 12:10
@lukaseder When I run code from main,https://github.com/jOOQ/jOOQ/issues/6851, It can't find the xsd, So I download it and put it here:

![image](https://user-images.githubusercontent.com/501740/33172244-42567c24-d08a-11e7-8572-ab936a06f820.png)

before that ,I found when the file is end with xml,it could not load,and then I changed it to xsd

I change to 3.8 cause that another issue in Spring boot starter.

**Comment by hepin1989** [comment] 2017-11-23 12:24
Another reason it that I did not depending on the `jooq-meta` dependency . Should mention to dependent on  in doc one we wan't to generate the tables by code.

https://www.jooq.org/doc/3.10/manual/code-generation/codegen-advanced/codegen-config-generator/#N49976

should mention the dependencies

**Comment by lukaseder** [comment] 2017-11-23 13:14
I'm not sure about the dependencies part. I mean, the tutorial mentions the dependencies, the jooq-codegen's `pom.xml` also documents the dependency, and the page you pointed to isn't really the right place to document such a dependency...

I'll close this as works for me. Thanks for documenting this problem here.

**Closed by lukaseder** 2017-11-23 13:14 UTC
Labels: C: Code Generation, P: Medium, T: Defect
