### ISSUE TITLE
Support case conversion in generator field transform 

### ISSUE THREAD

**Issue by vojtapol** [jOOQ/jOOQ#11098] opened 2020-12-05 05:47 UTC
### Use case:

My column is called `address_line_1` and I would like the generated getter be called `getAddressLine1()`.

I am trying:
```xml
<fields>                                              
    <field>                                           
        <expression>^(.*?)_(.\d*)$</expression>       
        <fieldGetter>                                 
            <transform>CAMEL</transform>              
            <expression>get\u$1$2</expression>        
          </fieldGetter>                                          
    </field>                                          
</fields>       
```

But the generated getter is `getuaddressLine1()`.                                      

See https://www.regular-expressions.info/refreplacecase.html

Can jOOQ add case conversions to regex replacements?

**Comment by lukaseder** [comment] 2020-12-07 08:26
Thanks for your suggestion. There's no such escape sequence as `\u` in Java patterns, see:
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html

Quite possibly, some random other regex syntax supports this, but this is Java...

I'm aware of the limitations in this area - I don't think I have a solution here right now, short of implementing a programmatic generator stategy of course. See also this discussion: https://github.com/jOOQ/jOOQ/issues/10574

Closing as duplicate of https://github.com/jOOQ/jOOQ/issues/10574

**Closed** 2020-12-07 18:58 UTC
Labels: C: Code Generation, E: All Editions, P: Medium, R: Duplicate, T: Enhancement
