### ISSUE TITLE
FieldAlias - need ability to get wrapped original field

### ISSUE THREAD

**Issue by slavap** [jOOQ/jOOQ#5208] opened 2016-04-18 22:09 UTC
FieldAlias.alias is private, and Alias.wrapped() is package accessible. BOTH should be public to simplify runtime conditions construction.

**Comment by lukaseder** [comment] 2016-04-19 09:40
Thank you very much for your suggestion.

However, I very strongly disagree with making anything public prematurely, without fully undestanding your requirements. I'm pretty sure there will be a better way for you to solve the issues you're having. Why do you want to access these things?

**Comment by slavap** [comment] 2016-04-19 10:05
It's just VERY simplified example, in real application I'm populating lists of query parts and constructing query in absolutely different place and then applying user filters in another different place. So I have to store non-aliased and aliased fields separately, because I don't want to find fields by string names like query.field("duration")

```java
        PackageType t = PackageType.PACKAGE_TYPE.as("t");
        SelectQuery<Record> query = renderer.selectQuery();
        query.addSelect(t.PACKAGE_TYPE_ID);
        query.addSelect(t.PACKAGE_TYPE_);
        Field<BigDecimal> duration = DSL.round(MyCommon.getpkgtypeduration(t.PACKAGE_TYPE_)
                .mul(24).mul(60)).as("duration");
        query.addSelect(duration);
...
        // much later in the code I'm adding search condition by duration:
        query.addConditions(duration.equal(new BigDecimal(60))); // FAILS!
        // so I have to store non-aliased version of duration to be able to add filters later.
```

**Comment by lukaseder** [comment] 2016-04-22 07:07
Thank you for these details. I can see two immediate solutions to this problem:

1. You shouldn't store the aliased field in the local variable. Do this instead:

    ```java
        Field<BigDecimal> duration = DSL.round(MyCommon.getpkgtypeduration(t.PACKAGE_TYPE_)
                .mul(24).mul(60));
        query.addSelect(duration.as("duration"));
    ```

2. Use a derived table for the `duration` expression. This would also help prevent the double SQL - PL/SQL context switch, in case you're not using the scalar subquery caching flag.

We're going to improve things in the future, especially in jOOQ 4.0, with respect to AST manipulation, where we'll expose more of jOOQ's internals. This will need to be designed carefully though. Just opening up internals for a quick use case is something we'd regret.

Do note there is also a pending feature request that is related to this one: https://github.com/jOOQ/jOOQ/issues/2579

**Comment by slavap** [comment] 2016-04-22 07:20
1. Thanks for advice, I know how to make it working :-) You just missed my point. List of fields is constructed in one place (and there is no query in that place, so fields are just placed in plain List object). And it's natural to put them with needed aliases, otherwise Map<Field, String> should be used to specify needed alias. And query will be constructed later in a different place.

2. What is derived table? Any link to example or documentation?

**Comment by lukaseder** [comment] 2016-04-22 08:12
>  You just missed my point

Or, you missed mine. :) Why do you think it is natural to put aliases with those fields? Once you alias the field, it becomes a new field that is valid for the scope of `SELECT` and `ORDER BY` only. In SQL it is not at all natural to reuse such a field in the `WHERE` clause. I know this is a bit weird, but that's how SQL works. Column aliases are declared in `SELECT`, and thus it is not natural to reference the alias from a "previous" clause (even if that clause is lexicographically "following")

I do appreciate that this confusion leads to the problems you're experiencing, and we'll solve that eventually, but we need to be careful not to be too clever about this solution.

A derived table is a `SELECT` in the `FROM` clause:

```sql
SELECT *
FROM (
  /* derived table start */
  SELECT * FROM x
  /* derived table end */
) t

**Comment by slavap** [comment] 2016-04-22 08:28
You are right, but it's absolutely natural to have an ability to figure out what is "hidden" under alias. And we are talking about class hierarchy, which models SQL, not about text. So it's ok to have more information to simplify objects instantiation and processing.

**Comment by lukaseder** [comment] 2016-04-22 09:52
We'll be looking into it in future releases :)

**Comment by slavap** [comment] 2016-04-22 09:55
Thanks! I'm actually quite impressed by jooq after Hibernate usage.

**Comment by lukaseder** [comment] 2016-04-22 09:57
Thank you for your nice words. :)
I'm curious, what were your biggest pain points that are now solved with jOOQ?

**Comment by slavap** [comment] 2016-04-22 10:03
In case of Hibernate it's almost impossible to predict/control which resulting SQL you will get, especially in case of complex joins and exists. Also in case of jooq compiler controls a lot, in case of Hibernate you getting runtime errors unpredictable.

**Comment by lukaseder** [comment] 2016-04-22 10:06
I see, yes indeed, those problems do arise a lot. Specifically, there's also the question of being able to predictably tune any statement that is more complex than `SELECT * FROM ... WHERE ...`.

Anyway, thanks for your feedback and suggestions! Looking forward to more suggestions, if you find anything.

**Comment by lukaseder** [comment] 2020-01-15 15:37
In the near future, we will be working on a prototype of a new publicly available query object model that allows for accessing the internal data structure of jOOQ queries, including e.g. `FieldAlias`:

- https://github.com/jOOQ/jOOQ/issues/9163
- https://github.com/jOOQ/jOOQ/projects/2

This issue will be addressed and is not a special case, so I'm closing this as a duplicate of the above larger projects.

**Closed by lukaseder** 2020-01-15 15:37 UTC
Labels: C: Functionality, P: Medium, T: Enhancement
