### ISSUE TITLE
retain source locations of parsed artifacts

### ISSUE THREAD

**Issue by wisnesky** [jOOQ/jOOQ#10530] opened 2020-08-26 01:47 UTC
### Use case:

I'm using JOOQ to parse the select-from-where fragment of many vendors and perform semantic analysis.  I would like to report errors in terms of the source locations, but can't map the parsed artifacts (Queries, Tables, etc) back to the source locations that create them.

### Possible solution you'd like to see:

```java
Queries q = parse("select * from X; select * from Y;");
int srcPosOfQuery1 = q.get(0).srcPos(); //offset 0
int srcPosOfQuery2 = q.get(1).srcPos(); //offset 20-ish
```

### Possible workarounds:

Do one's own parsing.

### Versions:

- jOOQ: 3.12

**Comment by lukaseder** [comment] 2020-08-26 07:33
Thanks a lot for your suggestion. Indeed, this would be very helpful when using the parser as a standalone tool outside of other jOOQ usage, see also: #8722.

Right now, as a workaround, you could patch the `ParserImpl.parse(String, Object...)` method and emit some positional information, at least for queries, through some means. This approach won't work for individual query parts contained in resulting queries, though, such as tables, columns, keywords, etc.

Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/8722

**Closed by lukaseder** 2020-08-26 07:33 UTC
Labels: C: Parser, E: All Editions, P: Medium, T: Enhancement

**Comment by wisnesky** [comment] 2020-08-26 19:27
Sorry for the duplicate tickets!  Thanks for your help!
