### ISSUE TITLE
IllegalArgumentException when calling UpdatableRecord methods on tables with embedded domains that replace their underlying fields

### ISSUE THREAD

**Issue by NorbertKawinski** [jOOQ/jOOQ#15873] opened 2023-11-25 20:53 UTC
### Expected behavior

New record is created in the database

### Actual behavior

```
Exception in thread "main" java.lang.IllegalArgumentException: Field ("author"."id") is not contained in Row (
  "author"."id",
  "author"."name"
)
```

### Steps to reproduce the problem

For such database:
```
CREATE DOMAIN author_id AS uuid NOT NULL;
CREATE TABLE author
(
    id   author_id    NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name varchar(255) NOT NULL
);
```

Generated with
`embeddableDomains = ".*"`

This code
```
AuthorRecord author = sql.newRecord(AUTHOR);
author.setName("Sample Author");
author.store();
```

throws an exception.
Without the `embeddableDomains` flag, everything works fine.

### jOOQ Version

org.jooq.trial:jooq:3.18.7

### Database product and version

postgres:16.1-alpine Docker image

### Java Version

Openjdk 21.0.1

### OS Version

Microsoft Windows 11 Pro [10.0.22621 Build 22621]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by NorbertKawinski** [comment] 2023-11-25 20:53
MCVE available here: https://github.com/NorbertKawinski/jOOQ-mcve-domain-embeddable-illegalargumentexception

**Comment by lukaseder** [comment] 2023-11-28 07:35
Thanks a lot for your report. I'll look into this right away.

**Comment by lukaseder** [comment] 2023-11-28 07:51
Yeah, I can reproduce it, with or without defaults.

**Comment by lukaseder** [comment] 2023-11-28 07:52
Stack trace of the new integration test:

```
java.lang.IllegalArgumentException: Field ("EMBEDDABLE_DOMAINS_IN_KEYS"."ID") is not contained in Row (
  "EMBEDDABLE_DOMAINS_IN_KEYS"."ID",
  "EMBEDDABLE_DOMAINS_IN_KEYS"."V"
)
	at org.jooq.impl.Tools.indexFail(Tools.java:2157)
	at org.jooq.impl.Tools.indexOrFail(Tools.java:2164)
	at org.jooq.impl.AbstractRecord.changed(AbstractRecord.java:574)
	at org.jooq.impl.UpdatableRecordImpl.store0(UpdatableRecordImpl.java:205)
	at org.jooq.impl.UpdatableRecordImpl.lambda$0(UpdatableRecordImpl.java:150)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:149)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:141)
	at org.jooq.codegen.test.embeddabledomains.EmbeddableDomainsTest.testEmbeddableDomainsInKeys(EmbeddableDomainsTest.java:130)
```

**Comment by lukaseder** [comment] 2023-11-28 08:03
The problem is that the generated `Table.getPrimaryKey()` is referencing the underlying columns, not the embeddables. I'll investigate separately, if this needs to be changed. Such a change couldn't be backported for compatibility reasons:

- https://github.com/jOOQ/jOOQ/issues/15875

However, it's probably possible to fix this even without the above change, and backport the fix.

**Comment by lukaseder** [comment] 2023-11-28 08:13
Within jOOQ, there is an internal `UpdatableRecord::getPrimaryKey()` method to fetch generated keys:

<img width="423" alt="image" src="https://github.com/jOOQ/jOOQ/assets/734593/084859e6-96e6-4f0f-b4bb-d42719acb680">

Given that it's internal (package private), we could just fix that particular method for this case here.

**Comment by lukaseder** [comment] 2023-11-28 09:11
Another related issue that will be fixed with this one:

- https://github.com/jOOQ/jOOQ/issues/15876

**Comment by lukaseder** [comment] 2023-11-28 09:31
This only happens when the embeddable *replaces* the underlying column(s)

**Comment by lukaseder** [comment] 2023-11-28 09:38
Duplicate of https://github.com/jOOQ/jOOQ/issues/12689

**Comment by lukaseder** [comment] 2023-11-28 10:04
Fixed in versions:

- 3.19.0
- 3.18.8 (https://github.com/jOOQ/jOOQ/issues/15880)
- 3.17.17 (https://github.com/jOOQ/jOOQ/issues/15881)
- 3.16.23 (https://github.com/jOOQ/jOOQ/issues/15882)

Thanks again for your report! I will continue investigating related edge cases (e.g. embeddable keys, keys combining domains and non-embeddables) to see if other, related problems still exist. Will link to further issues from here.

**Closed by lukaseder** 2023-11-28 10:04 UTC
Labels: T: Defect, C: Functionality, P: Medium, E: Professional Edition, E: Enterprise Edition

**Comment by lukaseder** [comment] 2023-11-28 12:15
I realise there was a comment here:

> EDIT: Probably related, the embedded keys generation have the same issue.

What did you mean by this? Enabling both embedded keys *and* domains? This is currently not working due to the inability to nest embeddables:

- https://github.com/jOOQ/jOOQ/issues/13059
- https://github.com/jOOQ/jOOQ/issues/11975

Or did you have something else in mind?

**Comment by lukaseder** [comment] 2023-11-28 12:19
Another issue when a composite key referneces a domain type:

- https://github.com/jOOQ/jOOQ/issues/15883

**Comment by NorbertKawinski** [comment] 2023-11-28 17:02
Ah, no, not that complex with nesting, sorry for not being clear :)
I just meant that the same issue "Field (xxx) is not contained in Row" happened when I used "embeddablePrimaryKeys" <<instead of>> domains.

Actually this is how I first bumped into this issue because I started generating the embedded keys.
When it didn't work I tried using domains with the same issue.

If you'd like to see what I mean, then I updated my MCVE with "embeddablePrimaryKeys"
https://github.com/NorbertKawinski/jOOQ-mcve/commit/e04cc825276a1d6b4336ee070fc71e713921964f

**Comment by lukaseder** [comment] 2023-11-29 07:14
> Ah, no, not that complex with nesting, sorry for not being clear :)
> I just meant that the same issue "Field (xxx) is not contained in Row" happened when I used "embeddablePrimaryKeys" --instead of-- domains.

I see, I'll check that as well, thanks. When combining the two flags (which isn't unlikely), then, nesting would have to occur, though. The domain generates an embeddable first, and then the key generates another one after, based on the first. This doesn't work yet.

**Comment by lukaseder** [comment] 2023-11-29 07:37
I can confirm, this fixes also the case of using `embeddablePrimaryKeys` (or `embeddableUniqueKeys`)
