### ISSUE TITLE
GroupConcat renders string_agg separator argument within wrong parentheses

### ISSUE THREAD

**Issue by matjazs** [jOOQ/jOOQ#12801] opened 2022-01-07 15:31 UTC
### Expected behavior

The following use-case for PostgreSQL:
```Java
SelectJoinStep<Record1<String>> query = create
            .select(DSL.groupConcatDistinct(DSL.coalesce(TABLE1.FIELD1, TABLE1.FIELD2)))
            .from(TABLE1);
```

Should render SQL similar to:
```SQL
select string_agg(distinct coalesce("schema1"."table1"."field1", "schema1"."table1"."field2"), ',')
from "schema1"."table1"
```

### Actual behavior
Instead, I get this (note the separator argument being part of the wrong parentheses):

```SQL
select string_agg(distinct (coalesce("schema1"."table1"."field1", "schema1"."table1"."field2"), ','))
from "schema1"."table1"
```

### Steps to reproduce the problem

See expected behaviour.

I suspect this was introduced in #12742 and the culprit is `org.jooq.impl.ListAgg#acceptStringAgg`.

### Versions

- jOOQ: 3.16.1
- Java: OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)
- Database (include vendor): PostgreSQL 14
- OS: MacOS Monterey
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.3.1

**Comment by lukaseder** [comment] 2022-01-11 08:50
Thanks a lot for your report and investigation. That's a likely cause for this regression. Will look into fixing this right away.

**Comment by lukaseder** [comment] 2022-01-11 09:30
Fixed in jOOQ 3.17.0 and 3.16.2 (https://github.com/jOOQ/jOOQ/issues/12817). Thanks again for your report!

**Closed by lukaseder** 2022-01-11 09:30 UTC
Labels: T: Defect, C: Functionality, P: High, E: All Editions

**Comment by lukaseder** [comment] 2022-01-11 09:41
Similar problem: https://github.com/jOOQ/jOOQ/issues/12818. The problem was in both cases that we had less test coverage for `GROUP_CONCAT` than for `LISTAGG` directly.

**Comment by lukaseder** [comment] 2022-04-04 13:01
This issue seems to persist in EXASOL: https://github.com/jOOQ/jOOQ/issues/13415
