### ISSUE TITLE
SQL Translation Error - translated query is not executable

### ISSUE THREAD

**Issue by dgandhe** [jOOQ/jOOQ#12631] opened 2021-11-16 10:36 UTC
### SQL translator incorrectly translates this query:

```sql
SELECT DISTINCT 'F' AS RECORDIDENTIFIER, SUBSTR( FOOTNOTEIDANDTEXT, LEVEL) AS FOOTNOTEIDANDTEXT 
FROM ( 
SELECT DISTINCT 'F' AS RECORDIDENTIFIER, SUBSTR( FOOTNOTEIDANDTEXT,2) AS FOOTNOTEIDANDTEXT 
FROM INDEXOFCUSTOMERS IOC 
WHERE IOC.POSTING_ID=1
) 
CONNECT BY SUBSTR( FOOTNOTEIDANDTEXT, LEVEL) 
```

### Parser output:

```sql
WITH RECURSIVE CTE_CONNECT_BY AS (
SELECT 1 AS LEVEL, S.* FROM ( S
UNION ALL
SELECT LEVEL + 1 AS LEVEL, S.* FROM CTE_CONNECT_BY R INNER JOIN ( S ON s.SUBSTR( s.FOOTNOTEIDANDTEXT, s.LEVEL)
)
SELECT DISTINCT 'F' AS RECORDIDENTIFIER, SUBSTR( FOOTNOTEIDANDTEXT, LEVEL) AS FOOTNOTEIDANDTEXT 
FROM cte_connect_by 
SELECT DISTINCT 'F' AS RECORDIDENTIFIER, SUBSTR( FOOTNOTEIDANDTEXT,2) AS FOOTNOTEIDANDTEXT 
FROM INDEXOFCUSTOMERS IOC 
WHERE IOC.POSTING_ID=1 
) 
  
```

**Comment by lukaseder** [comment] 2021-11-16 11:28
Thanks for your feedback.

What SQL dialect runs your input statement? In Oracle, `SUBSTR(FOOTNOTEIDANDTEXT, LEVEL)` cannot be used like that in `CONNECT BY`. The output is:

> SQL Error [920] [42000]: ORA-00920: invalid relational operator

**Comment by dgandhe** [comment] 2021-11-16 12:44
Please ignore the earlier query, see below the Oracle & Postgres queries.

**------Oracle SQL query-----------**
SELECT DISTINCT 'F' AS RECORDIDENTIFIER, NULL AS FACILITYNAME, NULL AS FACFERCCIDCODE, NULL AS FACIOCREPORTDATE, NULL AS FACIOCORIGREVISEDIND, 
        NULL AS FACIOCQUARTERDATE, NULL AS FACIOCTRANSCAPACITYUOM, NULL AS FACIOCSTORGCAPACITYUOM, NULL AS FACIOCCONTACT, 
        NULL AS DETIOCSHIPPERNAME, NULL AS DETIOCSHIPPERDUNS,  NULL AS DETIOCSHIPPERAFFILIND, NULL AS DETIOCRATESCHEDULE, 
        NULL AS DETIOCCONTRACTNAME, NULL AS DETIOCCONTRACTBEGDATE, NULL AS DETIOCCONTRACTPRIMARYENDDATE, NULL AS DETIOCCONTRACTNEXTEXPIRATION, 
        NULL AS DETIOCKTNEGOTIATEDRATESIND, NULL AS DETIOCTRANSPORTKTMDQ, NULL AS DETIOCSTORAGEKTMDQ, 
        NULL AS AGENTNAME, NULL AS AGENTAFFILIATEINDICATOR,         NULL AS POINTIDCODE, NULL AS POINTLEGALNAME, NULL AS POINTNAME, NULL AS POINTDESCRIPTION, NULL AS POINTCODEQUALIFIER, NULL AS POINTZONENAME, 
        NULL AS POINTTRANSPORTMDQ, NULL AS POINTSTORAGEMDQ, NULL AS POINTLOCATIONUSAGE, 
        POSTING_ID, INCLUDEFLAG, SUBSTR( FOOTNOTEIDANDTEXT, LEVEL)  AS FOOTNOTEIDANDTEXT 
        FROM ( 
          SELECT DISTINCT 'F' AS RECORDIDENTIFIER, NULL AS FACILITYNAME, NULL AS FACFERCCIDCODE, NULL AS FACIOCREPORTDATE, NULL AS FACIOCORIGREVISEDIND, 
          NULL AS FACIOCQUARTERDATE, NULL AS FACIOCTRANSCAPACITYUOM, NULL AS FACIOCSTORGCAPACITYUOM, NULL AS FACIOCCONTACT, 
          NULL AS DETIOCSHIPPERNAME, NULL AS DETIOCSHIPPERDUNS,  NULL AS DETIOCSHIPPERAFFILIND, NULL AS DETIOCRATESCHEDULE, 
          NULL AS DETIOCCONTRACTNAME, NULL AS DETIOCCONTRACTBEGDATE, NULL AS DETIOCCONTRACTPRIMARYENDDATE, NULL AS DETIOCCONTRACTNEXTEXPIRATION, 
          NULL AS DETIOCKTNEGOTIATEDRATESIND, NULL AS DETIOCTRANSPORTKTMDQ, NULL AS DETIOCSTORAGEKTMDQ, 
          NULL AS AGENTNAME, NULL AS AGENTAFFILIATEINDICATOR,           NULL AS POINTIDCODE, NULL AS POINTLEGALNAME, NULL AS POINTNAME, NULL AS POINTDESCRIPTION, NULL AS POINTCODEQUALIFIER, NULL AS POINTZONENAME, 
          NULL AS POINTTRANSPORTMDQ, NULL AS POINTSTORAGEMDQ, NULL AS POINTLOCATIONUSAGE, 
          IOC.POSTING_ID, IOC.INCLUDEFLAG, 1 as FOOTNOTEIDANDTEXT 
          FROM INDEXOFCUSTOMERS IOC           WHERE IOC.POSTING_ID=1
      ) 
      CONNECT BY SUBSTR( FOOTNOTEIDANDTEXT, LEVEL)  IS NOT NULL 
      
**-----Gets convert to Postgres------**

 WITH RECURSIVE CTE_CONNECT_BY AS (
SELECT 1 AS LEVEL, S.* FROM ( S
UNION ALL
SELECT LEVEL + 1 AS LEVEL, S.* FROM CTE_CONNECT_BY R INNER JOIN ( S ON s.SUBSTR( s.FOOTNOTEIDANDTEXT, s.LEVEL)  s.IS s.NOT s.NULL
)
        SELECT DISTINCT 'F' AS RECORDIDENTIFIER, NULL AS FACILITYNAME, NULL AS FACFERCCIDCODE, NULL AS FACIOCREPORTDATE, NULL AS FACIOCORIGREVISEDIND, 
        NULL AS FACIOCQUARTERDATE, NULL AS FACIOCTRANSCAPACITYUOM, NULL AS FACIOCSTORGCAPACITYUOM, NULL AS FACIOCCONTACT, 
        NULL AS DETIOCSHIPPERNAME, NULL AS DETIOCSHIPPERDUNS,  NULL AS DETIOCSHIPPERAFFILIND, NULL AS DETIOCRATESCHEDULE, 
        NULL AS DETIOCCONTRACTNAME, NULL AS DETIOCCONTRACTBEGDATE, NULL AS DETIOCCONTRACTPRIMARYENDDATE, NULL AS DETIOCCONTRACTNEXTEXPIRATION, 
        NULL AS DETIOCKTNEGOTIATEDRATESIND, NULL AS DETIOCTRANSPORTKTMDQ, NULL AS DETIOCSTORAGEKTMDQ, 
        NULL AS AGENTNAME, NULL AS AGENTAFFILIATEINDICATOR,         NULL AS POINTIDCODE, NULL AS POINTLEGALNAME, NULL AS POINTNAME, NULL AS POINTDESCRIPTION, NULL AS POINTCODEQUALIFIER, NULL AS POINTZONENAME, 
        NULL AS POINTTRANSPORTMDQ, NULL AS POINTSTORAGEMDQ, NULL AS POINTLOCATIONUSAGE, 
        POSTING_ID, INCLUDEFLAG, SUBSTR( FOOTNOTEIDANDTEXT, LEVEL)  AS FOOTNOTEIDANDTEXT 
        FROM cte_connect_by 
          SELECT DISTINCT 'F' AS RECORDIDENTIFIER, NULL AS FACILITYNAME, NULL AS FACFERCCIDCODE, NULL AS FACIOCREPORTDATE, NULL AS FACIOCORIGREVISEDIND, 
          NULL AS FACIOCQUARTERDATE, NULL AS FACIOCTRANSCAPACITYUOM, NULL AS FACIOCSTORGCAPACITYUOM, NULL AS FACIOCCONTACT, 
          NULL AS DETIOCSHIPPERNAME, NULL AS DETIOCSHIPPERDUNS,  NULL AS DETIOCSHIPPERAFFILIND, NULL AS DETIOCRATESCHEDULE, 
          NULL AS DETIOCCONTRACTNAME, NULL AS DETIOCCONTRACTBEGDATE, NULL AS DETIOCCONTRACTPRIMARYENDDATE, NULL AS DETIOCCONTRACTNEXTEXPIRATION, 
          NULL AS DETIOCKTNEGOTIATEDRATESIND, NULL AS DETIOCTRANSPORTKTMDQ, NULL AS DETIOCSTORAGEKTMDQ, 
          NULL AS AGENTNAME, NULL AS AGENTAFFILIATEINDICATOR,           NULL AS POINTIDCODE, NULL AS POINTLEGALNAME, NULL AS POINTNAME, NULL AS POINTDESCRIPTION, NULL AS POINTCODEQUALIFIER, NULL AS POINTZONENAME, 
          NULL AS POINTTRANSPORTMDQ, NULL AS POINTSTORAGEMDQ, NULL AS POINTLOCATIONUSAGE, 
          IOC.POSTING_ID, IOC.INCLUDEFLAG, 1 as FOOTNOTEIDANDTEXT 
          FROM INDEXOFCUSTOMERS IOC           WHERE IOC.POSTING_ID=1
      )

**Comment by lukaseder** [comment] 2021-11-16 12:49
Thanks a lot for the additional details. We currently support a few special cases of `CONNECT BY` (https://github.com/jOOQ/jOOQ/issues/11660), not the general case (https://github.com/jOOQ/jOOQ/issues/668).

I'm closing this as a duplicate of #668

**Closed by lukaseder** 2021-11-16 12:49 UTC
Labels: T: Defect, P: Medium, R: Feedback Pending, E: All Editions, C: Translator
