### ISSUE TITLE
forcedType's includeTypes doesn't work for various types on H2

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#10231] opened 2020-05-28 15:24 UTC
There are currently a number of `includeTypes` that jOOQ fails to match for H2:

- `int` -> must use `integer` for things to work
- `smalldatetime` -> must use `timestamp` for things to work

### Versions:

- jOOQ: 3.13.2
- Java: 14
- Database (include vendor): H2 1.4.200

**Comment by katzyn** [comment] 2020-05-28 15:53
`SMALLDATETIME` is not a native type of H2, this data type should never be used by normal applications. It is for compatibility with MS SQL only and is not guaranteed to work in future versions of H2 without a compatibility mode.

**Comment by axelfontaine** [comment] 2020-05-28 16:04
@katzyn If that's the case, you may want to mention it in https://h2database.com/html/datatypes.html#timestamp_type , because currently there is nothing in the H2 docs that supports your statement ...

**Comment by katzyn** [comment] 2020-05-28 16:10
I'm talking about the current status, all compatibility-only grammar elements were explicitly marked in documentation for the next not yet released version.

**Comment by lukaseder** [comment] 2020-05-29 08:11
We currently operate on the data type that is presented to us in the relevant `INFORMATION_SCHEMA` (or whatever the vendor specific dictionary views are called) queries.

Those queries are not documented or specified, and neither are the data types, so this has definitely been a source of confusion in the past. We could probably define a few common aliases for the built-in data types that we support, but this isn't trivial. For example, if `SMALLDATETIME` and `TIMESTAMP` are different things in a given RDBMS (e.g. in SQL Server, they're quite unrelated), we don't want to just match them because they happen to be similar in another RDBMS.

There's room for improvement, but I don't think it's as simple as you're suggesting.

**Comment by axelfontaine** [comment] 2020-05-29 08:36
Just in case this helps, this is what I naively had in mind (in pseudocode):

```
config = readGeneratorConfig()
postProcessedConfig = postProcessConfig(config, dbType)
// do all the usual stuff
```
```
Config postProcessConfig(Config  original, DBType dbType) {
  postProcessedConfig = copyOf(original)
  switch (dbType) {
    case H2:
        // substitute synonyms for internally known types...
  }
  return postProcessedConfig 
}
```

This thin translation layer would:
- eliminate end user confusion as I experienced while debugging this
- NOT affect jOOQ internals
- be completely isolated in the config processing part of the code

**Comment by lukaseder** [comment] 2020-05-29 11:57
This is all assuming we already have a maintainable public API in the code generator that would give us the confidence that documenting / publishing / maintaining such an extension point would be a good idea. Alas, we don't :)

> This thin translation layer

"Thin"... a word that is very similar to "just"... ;-) This will be improved eventually: https://github.com/jOOQ/jOOQ/issues/3883. But that's a big and complex project...

**Comment by axelfontaine** [comment] 2020-05-29 12:14
I wasn't arguing for a public SPI, but rather a JOOQ-internal decorator.

Either way, maybe an additional table detailing these in the manual is maybe also a sufficient "fix" for now.

**Comment by lukaseder** [comment] 2020-05-29 12:32
> I wasn't arguing for a public SPI, but rather a JOOQ-internal decorator.

I see

> Either way, maybe an additional table detailing these in the manual is also a sufficient "fix" for now.

There are different ways to fix this, documentation is one of them, but I tend to prefer fixing things thoroughly rather than documenting complex status quos, and by the way of documentation, setting them in stone.

I'm currently reviewing a lot of jOOQ's type system via the new `DOMAIN` support #681. And I'm positive, there will be a much better fix than documentation.

**Comment by axelfontaine** [comment] 2020-08-27 11:19
Thinking about this a bit more, it would probably make sense to throw an error if a forcedType had zero "matches" as that is almost certainly not what the author intended. It would allow a fail fast feedback loop for the kind of mistakes that led to this issue.

**Comment by lukaseder** [comment] 2020-08-27 11:48
There should already be a warning in the log output

**Comment by lukaseder** [comment] 2020-09-15 13:44
Some related trouble, on the mailing list. User used Oracle's `NUMBER` syntax to create tables in H2, which are reported as `NUMBER` in H2's tooling, but are internally really `DECIMAL`:
https://groups.google.com/g/jooq-user/c/sTzBMtblY00

I think that independently of the solution that will be applied here, it would be useful to have some tooling that allows for navigating the `jOOQ-meta` provided schema as jOOQ sees it. Currently, people have to either:

- Reverse engineer `jOOQ-meta`
- Debug through it
- Make wild guesses
- Read the manual or the various issues on this topic

It would be better if we had a way to log the entire schema that is included: https://github.com/jOOQ/jOOQ/issues/10632

Also, the warning message that is displayed if a `<forcedType/>` configuration is unused should refer to the possibility of using this debug output.

**Comment by katzyn** [comment] 2020-09-15 14:03
H2 1.4.200 was the last version of H2 where original data type of a column can be retrieved, H2 2.0 always stores normalized names, because original names may be not recognized on the next restart, for example, due to changes in database settings, some data types are mode-specific. Some numeric data types, however, will have different real and declared data types. `DECIMAL` / `DEC` will have `NUMERIC` real and `DECIMAL` declared data types, and `FLOAT` will have `REAL` or `DOUBLE PRECISION` as a real data type depending on declared precision and `FLOAT` as declared data type name.

**Comment by lukaseder** [comment] 2020-09-15 14:20
> H2 1.4.200 was the last version of H2 where original data type of a column can be retrieved, H2 2.0 always stores normalized names

That's great news, thank you!

**Comment by katzyn** [comment] 2020-09-15 14:36
H2 2.0 wasn't yet released, but we'll try to make a release in the near future. Unfortunately, there is a known unresolved regression that needs to be addressed before the release.

**Comment by lukaseder** [comment] 2020-09-15 14:41
> H2 2.0 wasn't yet released, but we'll try to make a release in the near future. Unfortunately, there is a known unresolved regression that needs to be addressed before the release.

No worries

**Comment by lukaseder** [comment] 2020-09-18 08:26
As mentioned elsewhere, this problem can be addressed in 2 ways:

- By implementing functionality (difficult to design)
- By helping troubleshoot the problem (easy, low hanging fruit)

#10632 has been implemented for jOOQ 3.14. On `DEBUG` level, we now log all the column types that we're trying to match per column, for the entire database.

If a `<forcedType/>` isn't used, there's a warning at the end of the code generation run. That warning includes a hint about the above `DEBUG` level output.

With the above in place, I'll postpone any decision about this issue for now, as I'm not sure how to best implement this.

**Comment by axelfontaine** [comment] 2020-09-23 14:25
> There should already be a warning in the log output

This is currently logged as `INFO`. May I suggest at least upgrading this to `WARN`.

I however still stand by my assessment that this really should be an error that breaks the build as I am pretty sure this is _never_ the intention of the developer to have unused forced types. If there are any counterexamples to may claim, this could be implemented as a switch which defaults to an exception but could be deactivated to produce a warning instead.

**Comment by lukaseder** [comment] 2020-09-23 14:53
> This is currently logged as `INFO`. May I suggest at least upgrading this to `WARN`.

Right. It was changed to `WARN` in jOOQ 3.14 in https://github.com/jOOQ/jOOQ/issues/8353, https://github.com/jOOQ/jOOQ/commit/14c2fac8f0d4b66907fb2c31a44eb8e82d561e33

> I am pretty sure this is _never_ the intention of the developer to have unused forced types

Yeah, we can argue this way. We have an `OnError` configuration (`SILENT`, `LOG`, `FAIL`), the default being `FAIL`. I can see a few cases where we combine configurations from different sources for different code generation runs, where it is acceptable for some parts to apply in one run, but not in another. We have that in our integration tests. But I think it's fine to then just specify `LOG` instead of `FAIL`. I've created a separate issue, because it isn't strictly related to this here: https://github.com/jOOQ/jOOQ/issues/10677

**Comment by lukaseder** [comment] 2022-10-24 09:05
Looking at this issue, it has been the source of various improvements in the code generator, mostly to logging. The original suggestion won't be implemented, but the improvements were very useful.

I'm closing this now. Any further improvements on more recent versions can be requested in a new issue.

**Closed by lukaseder** 2022-10-24 09:05 UTC
Labels: T: Enhancement, C: Code Generation, P: Medium, R: Wontfix, E: All Editions
