### ISSUE TITLE
Rename org.jooq.scala package name to avoid conflicts with wildcard imports of org.jooq._ in scala

### ISSUE THREAD

**Issue by er1c** [jOOQ/jOOQ#5440] opened 2016-07-21 16:19 UTC
Almost all of the jooq documentation pages recommend doing something like:
```
import org.jooq._
import org.jooq.impl._
```

The problem with doing a wildcard import on the org.jooq._ is the naming conflict with the normal "scala" package library.

So for instance:
```
import org.jooq._
import org.jooq.impl._
import scala.compat.java8.FutureConverters._
```
will throw a compiler error because "compat" is not found in `org.jooq.scala`

The work around involves aliasing the package:

```
import org.jooq.{scala => jooqscala, _}
import org.jooq.impl._
import scala.compat.java8.FutureConverters._
```

But that's a little over-annoying, especially because the only time you use the scala package is for importing the Conversions, which has to be done in an extra import statement anyhow `import org.jooq.scala.Conversion._`

The pattern in scala for importing java converters is an object 'JavaConverters': `import collection.JavaConverters._`

https://github.com/jOOQ/jOOQ/blob/master/jOOQ-scala/src/main/scala/org/jooq/scala/Conversions.scala could potentially be renamed to "ScalaConverters.scala" in the top-level org.jooq package to be a bit more-scala like and avoid the import namespace problem.

**Comment by lukaseder** [comment] 2016-07-25 08:54
This is a duplicate of https://github.com/jOOQ/jOOQ/issues/2684

**Closed by lukaseder** 2016-07-25 08:54 UTC
Labels: C: Integration: Scala, P: Medium, R: Duplicate, T: Enhancement
