### ISSUE TITLE
Field.contains() is rendered incorrectly with JOIN

### ISSUE THREAD

**Issue by relgames** [jOOQ/jOOQ#6091] opened 2017-04-17 18:57 UTC
Tables:
```sql
create table dish (
	id uuid not null  constraint dish_pkey primary key,
	place_id text,
	name text not null,
	photo text not null,
	price jsonb
);

create table tag (
	entity_id uuid not null constraint tag_pkey	primary key,
	type text not null,
	tags text[] default '{}'::text[] not null
);
```

Code:
```java
String[] tagsArray = {"tag1", "tag2"};
Condition condition = TAG.TAGS.contains(tagsArray);
log.info("condition = {}", condition);  // (1)

SelectSeekStep1<Record, String> q = create
        .select(DISH.fields()).select(TAG.TAGS)
        .from(DISH)
        .leftJoin(TAG).on(TAG.ENTITY_ID.eq(DISH.ID))
        .where(condition)
        .orderBy(DISH.NAME);

log.info("q = {}", q); // (2)
```

Outputs
```sql
(1) condition = "public"."tag"."tags" @> ARRAY['tag1', 'tag2']   <---- correct
(2) q = select 
  "public"."dish"."id", 
  "public"."dish"."place_id", 
  "public"."dish"."name", 
  "public"."dish"."photo", 
  "public"."dish"."price", 
  "public"."tag"."tags"
from "public"."dish"
  left outer join "public"."tag"
  on "public"."tag"."entity_id" = "public"."dish"."id"
where "public"."tag"."tags" @> cast('{"tag1","tag2"}' as varchar[])   <------ incorrect
order by "public"."dish"."name" asc
```
So the Condition alone is rendered correctly as `"tags" @> ARRAY['tag1', 'tag2']`, see (1).
But when used inside SELECT ... JOIN, it is rendered as `"tags" @> cast('{"tag1","tag2"}' as varchar[])` which fails.

Is should be rendered as `@> ARRAY...` in both cases.

**Comment by relgames** [comment] 2017-04-17 18:59
If I replace `create` with `PostgresDSL`, then it is rendered correctly:
```
            SelectSeekStep1<Record, String> q = PostgresDSL
                .select(DISH.fields()).select(TAG.TAGS)
                .from(DISH)
                .leftJoin(TAG).on(TAG.ENTITY_ID.eq(DISH.ID))
                .where(condition)
                .orderBy(DISH.NAME);
```
```
q = select 
  "public"."dish"."id", 
  "public"."dish"."place_id", 
  "public"."dish"."name", 
  "public"."dish"."photo", 
  "public"."dish"."price", 
  "public"."tag"."tags"
from "public"."dish"
  left outer join "public"."tag"
  on "public"."tag"."entity_id" = "public"."dish"."id"
where "public"."tag"."tags" @> ARRAY['tag1', 'tag2']
order by "public"."dish"."name" asc
```

**Comment by lukaseder** [comment] 2017-04-19 14:19
Thank you very much for reporting. This is indeed a very unfortunate issue, which we don't have a solution for yet. The workaround is to resort to using plain SQL to cast the array back to `text[]`

I'm closing it as a duplicate of https://github.com/jOOQ/jOOQ/issues/4754

**Closed by lukaseder** 2017-04-19 14:19 UTC
Labels: C: DB: PostgreSQL, C: Functionality, P: Medium, T: Defect
