### ISSUE TITLE
Invalid code generated when pojosEqualsAndHashCode option is enabled and column name is 'result'

### ISSUE THREAD

**Issue by nnmatveev** [jOOQ/jOOQ#6209] opened 2017-05-11 09:51 UTC
In my project I have a column with name 'result' and 'pojosEqualsAndHashCode' option enabled in jOOQ configuration. As a result, I have invalid code generated because of name clashes.

```java
@Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((billId == null) ? 0 : billId.hashCode());
        result = prime * result + ((amount == null) ? 0 : amount.hashCode());
        result = prime * result + ((created == null) ? 0 : created.hashCode());
        result = prime * result + ((result == null) ? 0 : result.hashCode());
        return result;
    }
```
Instance field 'result' name clashed with the local variable 'result'. My suggestion is always prepend instance fields names with 'this.'. So the code generated by jOOQ should be the following

```java
@Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.billId == null) ? 0 : this.billId.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        result = prime * result + ((this.result == null) ? 0 : this.result.hashCode());
        return result;
    }
```

If you agree with the suggestion I will create a PR.

The same could be applied to toString() method where 'sb' local variable could clash with a column name (yeah, 'sb' is a strange name for a column). I could add it to the PR as well.

**Comment by lukaseder** [comment] 2017-05-11 11:16
Too late, but thanks for the offer :)

Closing as duplicate of: https://github.com/jOOQ/jOOQ/issues/6191

**Closed by lukaseder** 2017-05-11 11:16 UTC
