### ISSUE TITLE
Kotlin Code generator generated nullable property for "not null" database column with default value

### ISSUE THREAD

**Issue by tomirio619** [jOOQ/jOOQ#14978] opened 2023-04-24 08:56 UTC
### Expected behavior

I have the following database definition:
```sql
CREATE TABLE my_table
(
    "my_field"       real NOT NULL default 0,
    "my_other_field" real NOT NULL
);
```
I configured jOOQ code generator to use the Kotlin generator together with the options `kotlinNotNullPojoAttributes` and `kotlinNotNullRecordAttributes`.
After pointing it to a PostgreSQL DB with the aforementioned definition, jOOQ generated the following POJO:

```kotlin
@Suppress("UNCHECKED_CAST")
data class MyTable(
    var myField: Float? = null,
    var myOtherField: Float
): Serializable { //.... }
```

### Actual behavior

I expected jOOQ to generate the following POJO:

```kotlin
@Suppress("UNCHECKED_CAST")
data class MyTable(
    var myField: Float,
    var myOtherField: Float
): Serializable { //.... }
```

### Steps to reproduce the problem

See attached file.

Run `./mvnw clean verify`.
Observe the generated file in `target/generated-sources/jooq/org.jooq.example.db/tables/pojos/MyTable`.

[jooq-non-nullable-reproduction-master.zip](https://github.com/jOOQ/jOOQ/files/11308511/jooq-non-nullable-reproduction-master.zip)

### jOOQ Version

jOOQ Open Source 3.18.3

### Database product and version

PostgreSQL 13.9

### Java Version

openjdk version "17.0.2" 2022-01-18

### OS Version

macOS 13.3.1

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment] 2023-04-24 14:51
Thanks for your report. This appears to be a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/14948
- https://github.com/jOOQ/jOOQ/issues/14786
- https://github.com/jOOQ/jOOQ/issues/14787

**Closed by lukaseder** 2023-04-24 14:51 UTC
Labels: T: Defect, C: Code Generation, P: Medium, R: Duplicate, C: Integration: Kotlin, E: All Editions
