### ISSUE TITLE
The UDT Array insertion is succeeded but query is failed on R2DBC

### ISSUE THREAD

**Issue by enif-lee** [jOOQ/jOOQ#15197] opened 2023-06-09 06:06 UTC
#### Environment

```SQL
CREATE TYPE task AS
(
  id     VARCHAR(255),
  name   VARCHAR(255),
  isDone BOOLEAN
);


CREATE TABLE projects
(
  id    SERIAL,
  tasks task[]
)
```

```kotlin
context.insertInto(PROJECTS)
    .set(ProjectsRecord(
        id = 1,
        tasks = arrayOf(
            TaskRecord(
                "id",
                "name",
                true
            )
        )
    ))
    .awaitFirst()

context.selectFrom(PROJECTS).asFlow().toList()
```

### Dependencies
- 3.18.0 jOOQ
- R2DBC 1.0.0.RELEASE

### Actual behavior

Insertion is succeeded.
I expected the records will be shown as query result but thrown an exception.

```
org.jooq.exception.DataAccessException: SQL [select "test_zAsA5WL1HT"."projects"."id", "test_zAsA5WL1HT"."projects"."tasks" from "test_zAsA5WL1HT"."projects"]; Error while reading field: "platform"."projects"."tasks", at JDBC index: 2
```

### Steps to reproduce the problem

It's seems to be R2DBC issue and jOOQ R2DBC support #13590 

### jOOQ Version

3.18.0

### Database product and version

PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Java Version

OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)

**Comment by lukaseder** [comment] 2023-06-09 11:24
Thanks a lot for your report. As you noticed in issue https://github.com/jOOQ/jOOQ/issues/13590, UDTs and arrays are not yet officially supported. They may or may not work by accident.

From experience with JDBC / pgjdbc support, this stuff is a ton of work both in jOOQ and in the drivers (pgjdbc doesn't formally support UDTs via JDBC's `SQLData` API, let alone arrays of UDTs, so I don't have high hopes that the reactive driver supports these cases). At the same time, R2DBC is an experiment that may well fade away again once Loom ships and addresses most concerns people have when opting for the complex world of reactive programming (in my experience also mostly for reasons that weren't validated).

Having said so, while this would definitely complete jOOQ's R2DBC experience, I can't make any promises about how many of those bullets from https://github.com/jOOQ/jOOQ/issues/13590 will be implemented in the near future, given the complexity of the work. If you already *know* that there are some low hanging fruit, I can definitely speed things up.

Closing this as a duplicate of #13590

**Closed by lukaseder** 2023-06-09 11:24 UTC
Labels: T: Defect, C: Functionality, P: Medium, R: Duplicate, E: All Editions
