### ISSUE TITLE
3.14.12+ regression when de-serializing abstract types 

### ISSUE THREAD

**Issue by sheinbergon** [jOOQ/jOOQ#12424] opened 2021-09-12 10:03 UTC
### Expected behavior

When trying to delegate to Jackson for type conversion, we may sometimes wish to deserialize to an abstract type (or interface), and have jackson resolve the type itself, using custom `@JsonDesreializer` or `@JsonType` annotations (a very common practice)

### Actual behavior

Starting with 3.14.12 and onwards, this behavior fails due to a `ProxyMapper` type convertor being resolved instead of the desired `ConverterProvider` implementation. The exact problem can be found in line [374](https://github.com/jOOQ/jOOQ/blob/08b44259cbf44da6ce9f3b55bd84b6eab3bdd550/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java#L374) of the class `org.jooq.impl.DefaultRecordMapper`:

```java
        // [#1470] Return a proxy if the supplied type is an interface
        // [#10071] [#11148] Primitive types are abstract! They're mapped by a ConverterProvider only later
        if (Modifier.isAbstract(type.getModifiers()) && !type.isPrimitive()) {
            delegate = new ProxyMapper();
            return;
        }
```

### Steps to reproduce the problem

Here's a minimal example written in Kotlin 1.5.30. It works with Jooq 3.14.11 but fails with 3.14.12 and onwards:

```kotlin
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "type")
@JsonSubTypes(
  JsonSubTypes.Type(value = Interface.Sample::class, name = "SAMPLE"),
)
sealed interface Interface {
  data class Sample(
    @JsonProperty("number") val number: Int,
    @JsonProperty("text") val text: String,
    @JsonProperty("flag") val flag: Boolean,
  ) : Interface
}

object SampleConverterProvider : ConverterProvider {
  private val fallback by lazy { DefaultConverterProvider() }

  @Suppress("UNCHECKED_CAST")
  override fun <F, T> provide(from: Class<F>, to: Class<T>): Converter<F, T>? = when {
    from == JSONB::class.java && to == Interface.Sample::class.java -> SampleConverter as Converter<F, T>
    else -> fallback.provide(from, to)
  }
}

object SampleConverter : JacksonConverter<Interface.Sample>(Interface.Sample::class.java)

sealed class JacksonConverter<T : Any>(private val type: Class<T>) : Converter<JSONB, T> {
  companion object {
    private val JACKSON = ObjectMapper()
      .deactivateDefaultTyping()
      .registerModule(KotlinModule())
  }

  override fun from(databaseObject: JSONB): T = JACKSON.readValue(databaseObject.data(), type)

  override fun to(userObject: T): JSONB = JSONB.jsonb(JACKSON.writeValueAsString(userObject))

  override fun fromType(): Class<JSONB> = JSONB::class.java

  override fun toType(): Class<T> = type
}

fun main() {
  val source = PGSimpleDataSource().apply {
    password = "postgis"
    user = "postgis"
    setURL("jdbc:postgresql://127.0.0.1:5432/postgres")
  }
  val provider = DataSourceConnectionProvider(source)
  val dsl = DefaultConfiguration()
    .set(provider)
    .set(SQLDialect.POSTGRES)
    .set(Settings().withRenderFormatted(true))
    .set(SampleConverterProvider)
    .let(DSL::using)
  dsl.fetchSingle("SELECT '{\"type\":\"SAMPLE\",\"number\":2,\"text\":\"some text\",\"flag\":false}'::jsonb AS value")
    .into(Interface::class.java)
    .let { Assert.isInstanceOf(Interface.Sample::class.java, it) }
}
```

### Versions

- jOOQ: 3.14.12, 3.14.13, 3.14.14,
- Java: 11
- Database : PostgreSQL 12
- OS: Debian, Ubuntu

**Comment by lukaseder** [comment] 2021-09-16 13:40
Thanks a lot for your report.

I can reproduce this particular issue, but I'm not sure if it's really a regression or rather something that happened to work "by accident" in older releases of jOOQ.

The `DefaultRecordMapper` has this frequently re-occurring flaw of breaking subtly in cases where the order of checking for preconditions is changed subtly or not so subtly by a new feature or a fix.

The only truly reasonable fix here is to offer its various implementations for configuration: https://github.com/jOOQ/jOOQ/issues/11974

I don't think you *ever* want to use this `ProxyMapper`, and if you do, you'd probably want to opt in for a few specific queries. So, rather than moving this feature around again, better offer you a flag.

You can always override the default behaviour already today by providing your own implementation using a `RecordMapperProvider`: https://www.jooq.org/doc/latest/manual/sql-execution/fetching/pojos-with-recordmapper-provider/

I'm closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/11974

**Closed by lukaseder** 2021-09-16 13:40 UTC
Labels: T: Defect, C: Functionality, P: Medium, C: Integration: Kotlin, E: All Editions
