### ISSUE TITLE
Support multiple values expressions in H2 merge statements

### ISSUE THREAD

**Issue by epkugelmass** [jOOQ/jOOQ#9340] opened 2019-10-08 22:13 UTC
### Use case:

The H2 merge command supports multiple value expression in a single `MERGE INTO` statement. See http://www.h2database.com/html/commands.html#merge This statement succeeds: `merge into test_table (test_col) values (1), (2), (3);`

But the various `MergeValuesStep*` types have signatures `Merge<R> values(*)` meaning that calls to `values` cannot be chained. See for comparison `InsertValuesStep*` which returns on the same type from `values`.

### Possible solution you'd like to see:

Chaining of `values` should be supported.

I haven't thought carefully about support for other databases other than H2, especially for those databases where jOOQ emulates `merge` via `insert ... on duplicate key update`. At least MySQL supports VALUES($FIELD) assignments. And given the current implementation of the emulation in MergeImpl, I am optimistic this might simply work.

### Possible workarounds:

Batch a bunch of `merge` statements together.

### Versions:

- jOOQ: 3.12.1
- Java: 11.0.4
- Database (include vendor): H2 1.4.199
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by knutwannheden** [comment] 2019-10-09 06:15
Thank you for your report. We will look into this.

**Comment by lukaseder** [comment] 2019-10-09 21:33
This definitely offers value through a variety of emulations. I can see how this works well through PostgreSQL `ON CONFLICT` or SQL standard `MERGE`.

Notice, you can already use `MERGE .. SELECT` through jOOQ API, which is just a minor indirection to emulate the more canonical `MERGE .. VALUES` for multiple rows.

**Comment by epkugelmass** [comment] 2019-10-10 16:05
Thanks for taking a look at this. The consequence of using `MERGE .. SELECT` (in the jooq API) is that you lose supports for derby, maria, mysql, and postgres.

**Comment by richard-berg** [comment] 2020-04-15 02:36
Can you demonstrate `MERGE .. SELECT` in jOOQ?  Best I can tell, the only available interfaces are:

- The variadic family of `MergeNotMatchedValuesStepN<>`  interfaces, which permit a single (not chainable) `values` method.  Although there exists an overload of `values` that takes a `Collection<?>`, its elements are unpacked into `Field<T>`, so you'll get a runtime exception if you try to pass a collection of `RowN` or `Record` or similar (as you can with the table constructor of the same name).

- The `MergeNotMatchedSetStep` interface, which permits chaining of MySQL-style `set` methods -- that is, one per _field_, not one per row.

SQL is a set-based language.  These single-row statements are pretty useless for the scenarios MERGE was intended.

**Comment by lukaseder** [comment] 2020-04-15 08:20
@richard-berg Thanks for your message. This issue here is about the H2 `MERGE` statement (which I'm actually thinking of unsupporting, now that H2 supports standard `MERGE`: #10045).

I think your question is about the standard `MERGE` statement, though? In that case, I don't think you need multiple `VALUES` clauses (which `MERGE` does not support). You should provide multiple rows in the `MERGE .. USING` source table, and then, for each row, decide whether you want to match it (`UPDATE` or `DELETE`) or not (`INSERT`).

An example:

```sql
-- T and S are RIGHT JOINed
MERGE INTO t
USING (
  SELECT 1 a, 2 b
  UNION ALL
  SELECT 3 a, 4 b
) s
ON (t.x = s.a)

-- Each of these match each row from the above RIGHT JOIN individually
WHEN MATCHED THEN UPDATE SET y = b
WHEN NOT MATCHED THEN INSERT (x, y) VALUES (a, b)
```

> SQL is a set-based language. These single-row statements are pretty useless for the scenarios MERGE was intended.

Thanks for the hint, which was surely well intended. `MERGE` already is set based, but only if you use it correctly :) Here's a good blog post which I suggest reading:
https://blog.jooq.org/2020/04/10/the-many-flavours-of-the-arcane-sql-merge-statement/

**Comment by lukaseder** [comment] 2020-04-15 08:21
I'm closing this issue as we will unsupport the H2-specific `MERGE` statement: https://github.com/jOOQ/jOOQ/issues/10045

**Closed by lukaseder** 2020-04-15 08:21 UTC
Labels: C: DB: H2, C: Functionality, E: All Editions, P: Low, T: Enhancement
