### ISSUE TITLE
final and private in JavaGenerator

### ISSUE THREAD

**Issue by bluestix** [jOOQ/jOOQ#4384] opened 2015-06-14 12:26 UTC
Trying to extend JavaGenerator to add additional outputs. Pretty much impossible without patching it as far as I can tell.

The public method generate(Database db) is marked final.

The method generate(SchemaDefinition schema) is marked private. 

That doesn't make sense. Why would you do that in a class that is supposed to be extended? Habit? 

Default should be protected and not final.

**Comment by ooxi** [comment] 2015-06-14 14:43
While it could be benefitial being extendable in this case I strongly disagree on being protected and not finalby default. Everything not private becomes part of your API and you have to take care of backward compatibility.

**Comment by bluestix** [comment] 2015-06-14 14:49
Adding an extra method that is called by generate, specifically made to be overridden, would work just as well.

Like generateUserDefinedTypes(SchemaDefinition schema) or something similar.

I have already wasted like an hour patching JavaGenerator and modifying my build to use the patched version. Now I am stuck because passing the name of my custom generator doesn't seem to affect the generation.

I know my custom class is being loaded because if I typo the name or remove the dependency I get a class not found exception for the class. But the custom class doesn't seem to actually be used in the generation.

Am I missing something?

**Comment by lukaseder** [comment] 2015-06-15 06:41
Thanks for your suggestion. We will cover a strategic redo of the code generation API in jOOQ 4.0 (#3883). Before that, I don't think it makes much sense discussing individual occurrences of `final` and `private` - which may be inconvenient, but as part of a generally not very overridable API aren't the biggest problem.

For the time being, writing custom generators is probably more effective.

> Now I am stuck because passing the name of my custom generator doesn't seem to affect the generation.

We'll need more information here.

- How do you generate classes? With maven, commandline, standalone API?
- Can you show your implementation?
- Can you show your configuration?

**Comment by lukaseder** [comment] 2015-06-15 06:41
(closing this as a duplicate of #3883)

**Closed by lukaseder** 2015-06-15 06:42 UTC
Labels: C: Code Generation, P: Medium, R: Duplicate, R: Wontfix, T: Enhancement
